### ISSUE TITLE
Feedback for: docker-for-windows/index.md

### ISSUE THREAD

**Issue by shazChaudhry** [docker/docker.github.io#100]
URL: docker-for-windows/index.md

I am using Docker v1.12.1 on a Windows 10 laptop. Enabling Hyper-V feature turns my wi-fi off. How do I ensure that my wi-fi stays on while using Hyper-V features?

**Comment by londoncalling** [comment]
@friis @rneugeba can you take a look at this problem ? (enabling Hyper-V turns off wifi) I have not encountered this myself.

**Comment by rneugeba** [comment]
@shazChaudhry thanks for the report. I have not encountered this issue myself. Could you open an issue in the [Docker for Windows github project](https://github.com/docker/for-win/issues)? This is where we track the issues with Docker for Windows. Could you also include a diagnostics ID as well?
thanks

**Comment by londoncalling** [comment]
@rneugeba @shazChaudhry I have created an issue for you on the Docker for Windows github project here: [Enabling Hyper-V feature turns my wi-fi off #139](https://github.com/docker/for-win/issues/139)

**Comment by londoncalling** [comment]
Closing this issue, as it's now being tracked on https://github.com/docker/for-win/issues/139
