### ISSUE TITLE
Confusing Sentence Under "Step 2. Install UCP" That May Lead to Errors

### ISSUE THREAD

**Issue by javajason** [docker/docker.github.io#10002]
File: [ee/dtr/admin/install/index.md](https://docs.docker.com/ee/dtr/admin/install/)

Under "Step 2. Install UCP" is the following: "Since DTR requires Docker Universal Control Plane (UCP) to run, you need to install UCP on all the nodes where you plan to install DTR."
This makes it appear that the user should install DTR on the same nodes that are running UCP. This is not recommended as it could cause resource and port conflicts. We generally recommend customers install DTR on worker nodes (not UCP nodes). This sentence seems to indicate otherwise.

**Comment by KoryKessel-Docker** [comment]
PR submitted for approval.

**Comment by KoryKessel-Docker** [comment]
#10120 merged and closed.
