### ISSUE TITLE
Docker Engine .zip URL missing from Windows Server page

### ISSUE THREAD

**Issue by kobykahane** [docker/docker.github.io#10020]
File: [ee/docker-ee/windows/docker-ee.md](https://docs.docker.com/ee/docker-ee/windows/docker-ee/)

Previously, the section "Use a script to install Docker Engine - Enterprise" in this page had the URL of the latest .zip of Docker Engine. In the latest version of the page it appears that the URL has been truncated, the command now reads:

```
# On an online machine, download the zip file.
Invoke-WebRequest -UseBasicParsing -OutFile .zip https://download.docker.com/components/engine/windows-server/19.03/.zip
```

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
