### ISSUE TITLE
404 at: /engine/reference/commandline/stack_tasks/

### ISSUE THREAD

**Issue by versus** [docker/docker.github.io#1002]
URL: /engine/reference/commandline/stack_tasks/

**Comment by mstanleyjones** [comment]
I believe this command no longer exists. @johndmulhausen @thaJeztah can you confirm?

**Comment by thaJeztah** [comment]
Correct, that command no longer exists, and was replaced with `docker stack ps` https://docs.docker.com/engine/reference/commandline/stack_ps/

@mstanleyjones it does seem to be missing in the navigation though (`docker stack ps`)

**Comment by mstanleyjones** [comment]
You're right! I'm on it in #1305.
