### ISSUE TITLE
Missing Distro Release for Ubuntu 19.10

### ISSUE THREAD

**Issue by rallen71366** [docker/docker.github.io#10037]
File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

E: The repository 'https://download.docker.com/linux/ubuntu eoan Release' does not have a Release file.

This is for a dev environment. The convenience script is not convenient.

**Comment by zilexa** [comment]
The solution described here works for some (not on a clean Ubuntu Budgie 19.10 install):
https://github.com/docker/docker.github.io/issues/8891
