### ISSUE TITLE
Indent error in first sample file

### ISSUE THREAD

**Issue by kmulmer** [docker/docker.github.io#10035]
File: [get-started/index.md](https://docs.docker.com/get-started/)

Under "Enable Kubernetes" for OSX Step 3 the following text is provided for pod.yaml:

apiVersion: v1
 kind: Pod
 metadata:
   name: demo
 spec:
   containers:
   - name: testpod
     image: alpine:3.5
     command: ["ping", "8.8.8.8"]

However, this results in the following error upon executing Step 4:

error: error parsing pod.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context

If the indents are removed to produce the following text, the file parses properly:

apiVersion: v1
kind: Pod
metadata:
   name: demo
spec:
   containers:
   - name: testpod
     image: alpine:3.5
     command: ["ping", "8.8.8.8"]

**Comment by usha-mandya** [comment]
@kmulmer Thanks for your feedback. This has been fixed in the Getting started guide - https://docs.docker.com/get-started/orchestration/. Closing this issue here as it the issue has been fixed. Feel free to comment on the ticket after I close. Thanks.
