### ISSUE TITLE
Mising character in example

### ISSUE THREAD

**Issue by deive** [docker/docker.github.io#10052]
File: [engine/examples/running_ssh_service.md](https://docs.docker.com/engine/examples/running_ssh_service/)

The default sshd config has all parameters commented out so the following line did not take effect:
`RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config`
I had to change it to the following to get it to work:
`RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config`

**Comment by deive** [comment]
Opened a PR for this at https://github.com/docker/docker.github.io/pull/10053

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the topic no longer exists except as a redirect.
