### ISSUE TITLE
Change in regex in the doc to Dockerize an SSH service

### ISSUE THREAD

**Issue by moulip** [docker/docker.github.io#10060]
File: [engine/examples/running_ssh_service.md](https://docs.docker.com/engine/examples/running_ssh_service/)

The `RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config`
should be
`RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config`
The # prevents the PermitRootLogin value to be effective upon change.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the topic no longer exists except as a redirect.
