### ISSUE TITLE
Discount code for Manning Publications

### ISSUE THREAD

**Issue by cobbjb** [docker/docker.github.io#10077]
File: [get-started/resources.md](https://docs.docker.com/get-started/resources/)

The discount code "webdoc40" has expired as of 11/18/19.

**Comment by usha-mandya** [comment]
@cobbjb Apologies for the discount code error. I'll check with the author and see if we can get an updated code.

**Comment by usha-mandya** [comment]
@cobbjb Unfortunately, there isn't a discount code available at the moment. We'll update the page when we receive an updated code. I'm closing this issue here for that reason.
