### ISSUE TITLE
needed detail for enabling Docker App

### ISSUE THREAD

**Issue by mpstaton** [docker/docker.github.io#10082]
File: [app/working-with-app.md](https://docs.docker.com/app/working-with-app/)

"To enable experimental features, edit the config.json file and set experimental to enabled. The example below enables experimental features in a config.json file that already enables a debug feature."

Can you explain where I can find the config.json file?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As the issue is old, the context may have changed.
You can find information about the config.json file at https://docs.docker.com/engine/reference/commandline/cli/#docker-cli-configuration-file-configjson-properties
