### ISSUE TITLE
Using bind mounts with nonexistent directory leads to error

### ISSUE THREAD

**Issue by ethancn** [docker/docker.github.io#10088]
File: [storage/bind-mounts.md](https://docs.docker.com/storage/bind-mounts/)

As the doc above said, when using bind mounts, "The file or directory does not need to exist on the Docker host already. It is created on demand if it does not yet exist", but this is not the same as what I tested.

I ran the following command with a nonexistent directory `/home/workspace/app`,

```shell
docker run -it \
  --name mycontainer \
  --mount type=bind,src="$(pwd)"/app,dst=/usr/src/app \
  alpine:latest
```

and got this error: `invalid mount config for type "bind": bind source path does not exist: /home/workspace/app.`

<img width="922" alt="屏幕快照 2019-12-26 下午6 18 35" src="https://user-images.githubusercontent.com/28993381/71471965-2729f080-280c-11ea-980f-977db9265cb7.png">

I think the doc is incorrect about this. The host is CentOS 7 with Docker 19.03.5 installed.

**Comment by thaJeztah** [comment]
This is the expected behavior, and described here; https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior

> Differences between `-v` and `--mount` behavior
> 
> If you use `--mount` to bind-mount a file or directory that does not yet exist on the Docker host, Docker does not automatically create it for you, but generates an error.

**Comment by ethancn** [comment]
> This is the expected behavior, and described here; https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior
> 
> > Differences between `-v` and `--mount` behavior
> > If you use `--mount` to bind-mount a file or directory that does not yet exist on the Docker host, Docker does not automatically create it for you, but generates an error.

Thanks for reminding me, didn't notice the difference before. This issue can be closed.
