### ISSUE TITLE
self-hosted registry deletion not supported for azure blob storage

### ISSUE THREAD

**Issue by leim** [docker/docker.github.io#10097]
### Problem description

i am using azure blob storage as storage backend. i uploaded a lot of docker images. i want to delete some, but when i am using the registry api to do this, something error occurs.

i am sure my configuration file is correct.

![aabbbb](https://user-images.githubusercontent.com/1665397/71667871-d2edb600-2da1-11ea-9747-89e1e2d004bb.PNG)

### Problem location

![aaaaa](https://user-images.githubusercontent.com/1665397/71667787-8ace9380-2da1-11ea-955e-aed18797191e.PNG)

### Project version(s) affected

i am using docker ce 19.03.5 and docker registry v2.7.0, not tested on other version.

when i am using filesystem as my storage backend, the deletion works well, but when i am using azure blob as my storage backend, the problem occurs.

### Suggestions for a fix

i dont know when it is a feature or a bug. so if it is a bug, would you please fix it.
if it is a feature, would you please explain the reason.

thanks a lot.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This sounds like a issue with the app or configuration. If the issue still exists, please help create an issue in the project's repo at https://github.com/distribution/distribution or reach out in the #distribution channel in the CNCF Slack.
