### ISSUE TITLE
More explanation needed about the step to remove the image

### ISSUE THREAD

**Issue by irontribe** [docker/docker.github.io#1009]
File: [engine/getstarted/step_six.md](https://docs.docker.com/engine/getstarted/step_six/)

Under "Step 2: Pull your new image", it says ",you need to remove the maryatdocker/docker-whale and docker-whale images from your local system."

It then goes on to use the command 

$ docker rmi -f 7d9495d03763

I feel that 1) it's still not quite clear that this command only removes it from the local machine as opposed to the local machine and/or the repo.  2) From what I can tell, the -f flag is not explained. I did a $ docker rmi --help and found that -f forces removal. So I tried a plain  $  docker rmi 7d9495d03763 assuming it would ask me if I really wanted to delete the image. Instead the image was deleted silently. So what purpose does the -f flag for rmi serve?

**Comment by unbreakableIce** [comment]
#dibs for hackathon

**Comment by johndmulhausen** [comment]
This topic no longer exists.
