### ISSUE TITLE
Sugestions for the front page

### ISSUE THREAD

**Issue by irontribe** [docker/docker.github.io#1010]
File: [index.md](https://docs.docker.com/)

First off, the tutorial is very well written and illustrated. I love the emphasis on exact steps to follow through a single, tangible, interesting task. Thank you.

I believe some material is missing in a couple of places.

1. A semitechnical explanation of what docker is! From what I can tell, it's a virtual machine manager-like thing I'm downloading from your website. But I'm not sure. In sections like [Build your own image](https://docs.docker.com/engine/getstarted/step_four/), there should be a one-sentence explanation in  [Step 2](Step 2: Build an image from your Dockerfile) along the lines of "You have just created a custom version of Ubunu that runs as a virtual machine inside MacOS." Or something along those lines, because I'm pretty sure Docker images are not exactly the same as VMs. I think.
2. I think a tutorial should always tell you how to clean up after yourself and shut down properly. 
3. Finally, it would be a service to readers in places with poor internet connections or expensive data charges that these exercises involve moving hundreds of megabytes over the wire.

**Comment by johndmulhausen** [comment]
I think this is a little on the old side. We have a totally revamped tutorial. Let us know if there are ideas based on what you're seeing there now. :)
