### ISSUE TITLE
stackoverflow.com page with docker link failed

### ISSUE THREAD

**Issue by pico99** [docker/docker.github.io#10102]
### Problem description

Sorry, we can't find that page
There might be a mistake in the URL or you might’ve clicked a link to content that no longer exists.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/registry/nginx/

source with a link to docs.docker.com URL: https://stackoverflow.com/questions/34490451/securing-a-docker-container-with-http-basic-auth

### Project version(s) affected

N/A

### Suggestions for a fix

Does this page exist somewhere else? I could attempt to add an update to the stackoverflow page with the new link.

**Comment by thaJeztah** [comment]
I edited the answer on StackOverflow to link to the GitHub repository (as the registry project has been donated to the CNCF, and the GitHub repository is the "source of truth" for these docs (docs.docker.com only presents a copy)
