### ISSUE TITLE
Ubuntu version inconsistent between text and image

### ISSUE THREAD

**Issue by tonychenc** [docker/docker.github.io#10117]
File: [storage/storagedriver/index.md](https://docs.docker.com/storage/storagedriver/)

Ubuntu version inconsistent between text and image

![image](https://user-images.githubusercontent.com/3282291/71960300-9bfb2280-322f-11ea-8d7d-beb4b411f61f.png)

![image](https://user-images.githubusercontent.com/3282291/71960467-175cd400-3230-11ea-93fd-700daf415d31.png)

**Comment by Vageesha17** [comment]
will work on this issue and fix it
