### ISSUE TITLE
Feedback for: docker-cloud/getting-started/deploy-app/2_set_up.md

### ISSUE THREAD

**Issue by Downes** [docker/docker.github.io#1011]
File: [docker-cloud/getting-started/deploy-app/2_set_up.md](https://docs.docker.com/docker-cloud/getting-started/deploy-app/2_set_up/)

This page is really unclear.

After years of installing and running apps, I always read the phrase "you can simply" as a red flag saying something difficult is coming up. Please don't say it's simple. Make the instructions clear instead.

> "If you have Docker Engine installed locally, you can simply run the following command regardless of which operating system you are using."

- run the command *where*
   - in Kitematic? (Kitematic has not been mentioned at all in the documentation to this point)
   - in Windows terminal?

- when I open Kitematic it sort of works.
   - docker-cloud -v  is not recognized as a valid command
   - login works and successfully authenticates me to Docker
   - export cowardly refuses to save to a terminal

- when I run in windows nothing works, though I see the same startup message as in Docker.

- if installing in Windows - the usage of 'pip' presupposes a python install has previously occurred (which version? link?) (I'm on a new machine) - I'll try Anaconda - if I hit additional issues I'll get back to you.

**Comment by sanscontext** [comment]
Hi @Downes, Kitematic is a wrapper for some Docker utilities, but it does not include the `docker-cloud` commands. If you have `docker` running on your machine, it should work when you run `docker run dockercloud/cli -h` in Terminal or your equivalent shell. I wouldn't use Kitematic for this step.

Can you show me the output of running the above command ^ in your shell?

And, I'm not a Windows user, but do you have a preferred package manager for Windows? (Ideally something that comes pre-installed and works from the command line, but I'm open to suggestions.) I don't believe the version of the python install matters since pip is going to download the latest version of the cli anyway.

**Comment by Downes** [comment]
On 2017-01-03 2:03 PM, LRubin wrote:
>
> Hi @Downes <https://github.com/Downes>, Kitematic is a wrapper for 
> some Docker utilities, but it does not include the |docker-cloud| 
> commands. If you have |docker| running on your machine, it should work 
> when you run |docker run dockercloud/cli -h| in Terminal or your 
> equivalent shell. I wouldn't use Kitematic for this step.
>
> Can you show me the output of running the above command ^ in your shell?
>

I get this:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\downess>docker run dockercloud/cli -h
usage: docker-cloud [-h] [-v]
{action,container,event,exec,login,node,nodecluster,repository,run,service,stack,tag,trigger,up}
                     ...

Docker Cloud CLI

optional arguments:
   -h, --help            show this help message and exit
   -v, --version         show program's version number and exit

Docker Cloud CLI commands:
{action,container,event,exec,login,node,nodecluster,repository,run,service,stack,tag,trigger,up}
     action              Action-related operations
     container           Container-related operations
     event               Get real time Docker Cloud events
     exec                Run a command in a running container
     login               Please use "docker login" to log into Docker Cloud
     node                Node-related operations
     nodecluster         NodeCluster-related operations
     repository          Repository-related operations
     run                 Create and run a new service
     service             Service-related operations
     stack               Stack-related operations
     tag                 Tag-related operations
     trigger             Trigger-related operations
     up                  Create and deploy a stack

C:\Users\downess>


And then this...


C:\Users\downess>docker-cloud -v
Traceback (most recent call last):
   File "c:\program 
files\anaconda3\lib\site-packages\dockercloud\api\auth.py", line 56, in 
load_from_file
     out = p.communicate(input=HUB_INDEX)[0]
   File "c:\program files\anaconda3\lib\subprocess.py", line 1072, in 
communicate
     stdout, stderr = self._communicate(input, endtime, timeout)
   File "c:\program files\anaconda3\lib\subprocess.py", line 1306, in 
_communicate
     self._stdin_write(input)
   File "c:\program files\anaconda3\lib\subprocess.py", line 1012, in 
_stdin_write
     self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "c:\program files\anaconda3\lib\runpy.py", line 184, in 
_run_module_as_main
     "__main__", mod_spec)
   File "c:\program files\anaconda3\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "C:\Program 
Files\Anaconda3\Scripts\docker-cloud.exe\__main__.py", line 5, in <module>
   File "c:\program 
files\anaconda3\lib\site-packages\dockercloudcli\cli.py", line 7, in 
<module>
     import dockercloud
   File "c:\program 
files\anaconda3\lib\site-packages\dockercloud\__init__.py", line 31, in 
<module>
     basic_auth = auth.load_from_file("~/.docker/config.json")
   File "c:\program 
files\anaconda3\lib\site-packages\dockercloud\api\auth.py", line 58, in 
load_from_file
     raise dockercloud.AuthError('error getting credentials - err: exec: 
"%s": executable file not found in $PATH, out: ``' % cmd)
dockercloud.api.exceptions.AuthError: error getting credentials - err: 
exec: "docker-credential-wincred": executable file not found in $PATH, 
out: ``


> And, I'm not a Windows user, but do you have a preferred package 
> manager for Windows? (Ideally something that comes pre-installed and 
> works from the command line, but I'm open to suggestions.) I don't 
> believe the version of the python install matters since pip is going 
> to download the latest version of the cli anyway.
>

I just use pip. Nothing more specific than that.

I get this result consistently on two separate machines.

I know this item keep getting closed but it feels like a real bug.

Note that I did eventually get docker-cloud to run in the Linux bash 
window on the same machine. (Bash on Ubuntu on Windows). This was using 
python 2.7 while Anaconda (on windows) was running 3.5.

-- Stephen

**Comment by sanscontext** [comment]
Hey @Downes `docker run dockercloud/cli` is a `docker` command used to run a docker container that installs the separate `docker-cloud` CLI. The `-h` output you're showing is confusing to me - it might be pulling the help text from the container somehow?

So first you'd run `docker run dockercloud/cli` (no `-h`) and that *installs* the docker-cloud CLI, then you can run `docker-cloud -v` to check which version.

**Comment by sanscontext** [comment]
Hey @Downes this repo is for docs bugs specifically, and it sounds like there might be an actual bug here. Please email support@docker.com and they can help you troubleshoot and file the bug if needed.
