### ISSUE TITLE
Docker container not starting.showing error: attaching to network failed

### ISSUE THREAD

**Issue by alokkv** [docker/docker.github.io#10110]
hi friends,
I have 16 servers in a docker swarm. I have created an attachable overlay driver in the swarm. I have created all 16 as manager. I have 14 containers running in each server or node. But now I tried to add a new server to the swarm. it joined the swarm fine as manager but if I try to bring up containers with the existing driver I am getting the following error.

Cannot start service ‘containername’: attaching to network failed, make sure your network options are correct and check manager logs: context deadline exceeded

can anyone please help on this matter. want to know why this error happens. I have checked the network TCP dump from these servers. didn’t find any drops in the logs. please suggest the reasons for this error so I can debug this problem.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For support, please try:
 - https://dockercommunity.slack.com/
 - https://forums.docker.com/
