### ISSUE TITLE
Where are the Linux instructions?

### ISSUE THREAD

**Issue by jonnyli** [docker/docker.github.io#10128]
File: [get-started/index.md](https://docs.docker.com/get-started/)

I'm following the quick-start document and everything on this page focuses on Mac and Windows. Is there another page for Linux?

**Comment by usha-mandya** [comment]
@jonnyli Thanks for your feedback. The easiest way to get started with Docker is through Docker Desktop. However, if you are looking to install Docker on Linux, go to https://docs.docker.com/engine/install/ and select a distro from the _Installation per distro_ section

After you've installed Docker on a Linux machine, you can follow the instructions in the Quick start guide and use CLI to build, run, and share your images - https://docs.docker.com/get-started/part2/. Let me know how you get on.

**Comment by usha-mandya** [comment]
@jonnyli Hope you were able to follow through the instructions and get started with Docker on a Linux machine. I'm closing the issue here as this is not a documentation issue. Feel free to continue the conversation after I close.
