### ISSUE TITLE
Uninstall instructions for Docker Desktop for macOS

### ISSUE THREAD

**Issue by StephenTaylor-Kx** [docker/docker.github.io#10132]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/)

Uninstall instructions refer to _Uninstall_ button on Troubleshooting dialog, but there is none. 

Docker Desktop 2.1.0.5 (40693)
macOS Mojave 10.14.6

**Comment by aevesdocker** [comment]
Closing ticket as system requirements are detailed on the individual platform installation pages
