### ISSUE TITLE
Creating a new host-only adapter produced an error: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create failed:

### ISSUE THREAD

**Issue by mtlc1217** [docker/docker.github.io#10152]
Docker Version:           19.03.1
VirtualBox Graphical User Interface
Version 5.2.20 r125813 (Qt5.6.2)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If there's an issue in the docs, please let us know. For support, please try:
 - https://dockercommunity.slack.com/
 - https://forums.docker.com/
