### ISSUE TITLE
Docker ToolBox is very important to people who don't want to use Hyper-V

### ISSUE THREAD

**Issue by dtpoirot** [docker/docker.github.io#10163]
File: [toolbox/index.md](https://docs.docker.com/toolbox/)

Microsoft Hyper-V is very toxic and hostile to VMware and VirtualBox. People who want or need to use VB or VMW can not use Hyper-V at the same time. Hyper-V doesn't release the Vt-x resources and this blockes both VB and VMW.

Please make the note in the cover page and in the docs that Docker ToolBox is still a valid option for people who can't tolerate Hyper-V in their systems.

**Comment by sundhaug92** [comment]
VB (and a number of other virtualization-solutions) supports using Hyper-V as a backend through WHP, and has for a while. VMW has announced support for WHP coming in the future.

ref #10679

**Comment by dtpoirot** [comment]
...how well does that work with Windows 10 Home Edition or with a corporate machine with a group policy which prohibits Hyper-V?
