### ISSUE TITLE
Provide the safe way to shut down  containers this guide has started

### ISSUE THREAD

**Issue by jmzaleski** [docker/docker.github.io#1017]
File: [compose/django.md](https://docs.docker.com/compose/django/)

It would help if the page ended with the safe way to shutdown the containers that have started up..
(I'm about to google up how to do that)

**Comment by fuzzy76** [comment]
AFAIK a single ctrl-c (as the output tells you) is a safe way to shutdown (double tapping it probably isn't).

**Comment by jmzaleski** [comment]
Thanks! my point was that as a newbie,  upon following the recipe, i was left wondering how to shut it down cleanly. Also there is the information that if you shutdown cleanly the container commits to the image (I think?) but if you do it wrong it does not..

Anyway, in retrospect I thought the recipe left the newbie hanging a bit more than was necessary.

**Comment by bdwill** [comment]
taking this one for hackathon

**Comment by mstanleyjones** [comment]
Thanks @bdwill and @jmaitrehenry I think you should both get the points for this!

**Comment by mstanleyjones** [comment]
Closed via #2857, #2971 
Points to @bdwill
