### ISSUE TITLE
Search bar does no show up in Firefox with Enhanced Tracking Protection

### ISSUE THREAD

**Issue by ingshtrom** [docker/docker.github.io#10188]
### Problem description
When going to docs.docker.com I do not see a search bar. I realized I had [Enhanced Tracking Protection](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop) set to "strict" and turning it off causes the search bar to show back up. I'm not sure what is being tracked with the search box, but it should still work without needing to turn off my browser's built in tracking protection

Browser troubleshooting information:
Name: 	Firefox Developer Edition
Version :	73.0b8
Build ID: 	20200122012721

### Problem location
- I saw a problem on the following URL: docs.docker.com

### Project version(s) affected
n/a

### Suggestions for a fix
n/a

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It appears to be resolved. I just tried with version 101.0 and Enhanced Track Protection enabled to Strict. If the issue is still occurring with the latest version, please let us know.
