### ISSUE TITLE
Add release note to avoid using DTR's TLS syslog flags with reconfigure

### ISSUE THREAD

**Issue by vikstrous** [docker/docker.github.io#1019]
File: [datacenter/dtr/2.1/guides/release-notes.md](https://docs.docker.com/datacenter/dtr/2.1/guides/release-notes/)

Add a release note mentioning to avoid using dtr's tls syslog flags with reconfigure. Internally tracked at: https://github.com/docker/dhe-deploy/issues/3264 The problem is that certs are not delivered to all DTR machines if tls syslog is configured via reconfigure instead of during install time. We plan to remove this feature in 2.2 to avoid customers breaking things and re-introduce it when we make TLS certs easier to configure in docker: https://github.com/docker/docker/issues/29784 (possibly docker 1.14 / dtr 2.3)

**Comment by johndmulhausen** [comment]
Version has shipped; closing per triage discussion.
