### ISSUE TITLE
Docker machine doesn't come with Docker products by Default

### ISSUE THREAD

**Issue by ivorcummings** [docker/docker.github.io#10194]
You should probably change the docs and inform people that docker-machine no longer gets installed by default. Thanks. 
File: [machine/install-machine.md](https://docs.docker.com/machine/install-machine/)

**Comment by v-braun** [comment]
My deployments and provisioning of the infrasturecture is done via terraform.
I use docker-machine only to simply switch between my docker hosts. 
Like a bookmark manager for docker hosts.
Is there a light alternative to docker-machine that can handle only the same thing for me?

**Comment by ivorcummings** [comment]
Closing this they updated the docs now
https://docs.docker.com/v17.09/machine/install-machine/#install-machine-directly

**Comment by ivorcummings** [comment]
"On macOS and Windows, Machine is installed along with other Docker products when you install the Docker for Mac, Docker for Windows, or Docker Toolbox." -- this first sentence should be changed

**Comment by ivorcummings** [comment]
@v-braun Do you need an alternative? You can still use docker-machine. It's just not included with Docker Desktop products. You simply need to install it manually.

**Comment by ivorcummings** [comment]
Made a PR to fix the docs: https://github.com/docker/docker.github.io/pull/10232
