### ISSUE TITLE
Doc bug: storage/volumes.md

### ISSUE THREAD

**Issue by TNT911** [docker/docker.github.io#10224]
The NFSV4 example has the following bugs:
- `,volume-opt=device=:/,` should be `,volume-opt=device=:/var/docker-nfs,`
- `volume-opt=o=10.0.0.10` should be `volume-opt=o=addr=10.0.0.10`

File: [storage/volumes.md](https://docs.docker.com/storage/volumes/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It was fixed in the following commits:
https://github.com/docker/docker.github.io/commit/9a416422b5dd597e69ab47217d1f6c69f6f64057
https://github.com/docker/docker.github.io/commit/cdee2dd67c2be064c9ff2a7fc31364cea601e4ef
