### ISSUE TITLE
Enterprise Engine relnotes reference CE

### ISSUE THREAD

**Issue by bryceryan-docker** [docker/docker.github.io#10229]
File: [engine/release-notes.md](https://docs.docker.com/engine/release-notes/)
The enterprise engine release notes for february (or latest, really), direct the customer to install the CE version. This is in error. Please update the paragraph with ```For example, on Ubuntu: sudo apt install docker-ce docker-ce-cli containerd.io. See the install instructions for the corresponding linux distro for details.``` to refer to EE installation guidance.

**Comment by usha-mandya** [comment]
@bryceryan-docker closing this issue as Enterprise docs have now moved to Mirantis and `engine/release-notes.md` doesn't reference any Enterprise releases.
