### ISSUE TITLE
Restart policy docs are wrong or misleading

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/docker.github.io#10243]
The [restart policy](https://docs.docker.com/engine/reference/run/#restart-policies---restart) documentation is wrong or misleading or both, depending on how you read them. See [this article](https://www.getconvey.com/blog/docker-restart-policies/) for more info.

File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference
