### ISSUE TITLE
Give hint for --isolation argument on installation page

### ISSUE THREAD

**Issue by danny-p93** [docker/docker.github.io#10249]
File: [ee/docker-ee/windows/docker-ee.md](https://docs.docker.com/ee/docker-ee/windows/docker-ee/)

I had difficutlies in running container on my Microsoft Server 2019 and there was no clue, why it doesn't work. At the end i ended with installing the Hyper-V Feature on the Server and run the container with --Isolation=hyperv Argument. But everywhere i searched for a solution didn't mention, that it could work with that.
I think it has something todo with the way the Windows Server is virtualized by esx. But all in all the only Thing i had to Change in the end was --Isolation (before that, every docker run ended without doing anything, it just stopped without error or sth.)

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
