### ISSUE TITLE
Backup a container

### ISSUE THREAD

**Issue by bhishekarora** [docker/docker.github.io#10251]
File: [storage/volumes.md](https://docs.docker.com/storage/volumes/)

I don't think there is a need to spin another temporary container to backup a container. 

I could do $docker cp sourcecontainer:/data . 
and i got the complete mount on my host as a directory

also i could do 
$docker cp data targetcontainer:/ 
and it moved the complete data directory to the target container..

Not sure why are you spinning another temporary container, is it only to make tar, what if 
size is small and we don't want to tar the directory.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. These are examples based on Volumes and are not the only way to perform the task. If there is an error in one of the examples, please let us know.
