### ISSUE TITLE
Troubleshooting DNS issues on D4M

### ISSUE THREAD

**Issue by ebuildy** [docker/docker.github.io#1025]
File: [docker-for-mac/networking.md](https://docs.docker.com/docker-for-mac/networking/)

Lot of people (included me) complain about DNS issues, D4M is not using same DNS setting than OSX (for instance, DNS from VPN).

It's a pitty because that means you cannot use D4M in entreprise environment properly.

I suggest adding some indication in the doc to include that, and some workaround.

Thanks you,

**Comment by johndmulhausen** [comment]
FWD this product feedback to D4M repo @londoncalling

**Comment by londoncalling** [comment]
Issue moved to [docker/for-mac #2000](https://github.com/docker/for-mac/issues/2000) via [**ZenHub**](https://www.zenhub.com/)
