### ISSUE TITLE
Missing instructions for installing CS Engine offline

### ISSUE THREAD

**Issue by anweiss** [docker/docker.github.io#1026]
### Problem description

There are currently no instructions for downloading the CS Engine packages (and their dependencies) and installing them offline. These should be included.

### Problem location

The installation page at https://docs.docker.com/cs-engine/install/ should include download locations for the .rpm, .deb, and SUSE packages, along with their required package dependencies.

### Project version(s) affected

All versions of CS Engine

### Suggestions for a fix

Either edit the existing install page (https://github.com/docker/docker.github.io/blob/master/cs-engine/install.md) or create a new one under `cs-engine` with Offline install instructions (similar to https://github.com/docker/docker.github.io/blob/master/datacenter/ucp/2.0/guides/installation/install-offline.md).

**Comment by joaofnfernandes** [comment]
@mavenugo, @cpuguy83 can you help with this?

**Comment by banjot** [comment]
@joaofnfernandes I think it would be similar to this page: https://docs.docker.com/engine/installation/binaries/

**Comment by mstanleyjones** [comment]
I don't think that's necessarily the right approach, because this needs to be documented for each supported distribution, both for Engine and CS. I made #1029 for that.
