### ISSUE TITLE
sshd

### ISSUE THREAD

**Issue by kaushikabhishek02** [docker/docker.github.io#10260]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
Hello @kaushikabhishek02 There's isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
