### ISSUE TITLE
WSL 2 Guide should warn existing containers won't be transfered. 

### ISSUE THREAD

**Issue by kf6nux** [docker/docker.github.io#10274]
File: [docker-for-windows/wsl-tech-preview.md](https://docs.docker.com/docker-for-windows/wsl-tech-preview/)

It should be noted that switching to WSL backend will stop your existing containers and the existing containers will neither be transferred to the new backend nor be deleted from the prior backend (allowing you to switch back to recover them).

**Comment by thaJeztah** [comment]
ping @simonferquel @nebuk89 ptal

**Comment by simonferquel** [comment]
We are working on the upgrade experience with machines capable of running WSL 2. The Upgrade to WSL 2 Popup will have this information in it.
