### ISSUE TITLE
Broken links in the right pane (engine/reference/builder/)

### ISSUE THREAD

**Issue by janhn** [docker/docker.github.io#10275]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

Clicking e.g. `HEALTHCHECK` on the right pane of the page links to:
- https://docs.docker.com/engine/reference/#healthcheck

which is a broken link. The correct one seems to be:
- https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by usha-mandya** [comment]
Hello @janhn Thank you for the feedback. The link to `Healthcheck` on the right pane works fine for me and correctly redirects to https://docs.docker.com/engine/reference/builder/#healthcheck. 

I'm closing this issue as it wasn't reproducible. Please feel free to reopen this if you still experience this issue. Thanks.
