### ISSUE TITLE
Docker machine release is hardcoded to an old release (0.13.0)

### ISSUE THREAD

**Issue by tamers** [docker/docker.github.io#10282]
File: [machine/install-machine.md](https://docs.docker.com/machine/install-machine/)

This somehow needs to either get latest release dynamically or clearly instruct users to get latest release from GitHub release page

**Comment by usha-mandya** [comment]
@tamers Thank you for the feedback. The examples on the Docker Machine installation page now point to v0.16.0. Also, the introductory section points users to Docker Machine releases page on GitHub for the latest binaries.
