### ISSUE TITLE
Connection Reset on docker pulls from our datacenter in Sydney

### ISSUE THREAD

**Issue by naftulee** [docker/docker.github.io#10309]
### Problem description

We use docker hub for some images in our k8s.  Recently we started getting disconnects from our Sydney Datacenter.  Is there any way to prevent this from happening to us. These are production clusters.

Thanks

connection reset by peer

docker pull jimmidyson/configmap-reload:v0.2.2

v0.2.2: Pulling from jimmidyson/configmap-reload
4d472840d001: Pulling fs layer
3739ec7a17e1: Pulling fs layer
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/7a/7a344aad0fdbe8fd3ebd3ace7268d59946408503db1fe7c171bdb016a51729b7/data?verify=1582016116-fTgW0EEZxbyJFyf186uxPu7gtSk%3D: read tcp 10.160.184.10:59436->104.18.125.25:443: read: connection reset by peer

### Problem location

This happens to kubernetes nodes running in our Sydney datacenter

### Suggestions for a fix

stop blocking our IP address :)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For support, please try:
 - https://hub.docker.com/support/contact/ 
 - https://forums.docker.com/
 - https://dockercommunity.slack.com/
