### ISSUE TITLE
Ubuntu eoan strable has no containerd.io package

### ISSUE THREAD

**Issue by tanyanghan** [docker/docker.github.io#10308]
File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

I had to add the nightly repository in order to install containerd.io.

**Comment by DeeDeeG** [comment]
The `containerd.io` package has now been added for Eoan. So I think this issue can be closed.

**Comment by thaJeztah** [comment]
Thanks; yes, a regression was found in the containerd.io 1.2.12 version, and we had to temporarily roll back those packages; unfortunately no prior releases of the package were done for Ubuntu Eoan, so there were no packages for it during that time.

containerd.io 1.2.13 is now up, so closing this
