### ISSUE TITLE
Need to writelist the Rails DB

### ISSUE THREAD

**Issue by fiveNinePlusR** [docker/docker.github.io#1030]
File: [compose/rails.md](https://docs.docker.com/compose/rails/)

To be able to connect to the database you need to add a whitelist inside ApplicationController.rb

``` ruby
module Myapp
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
    config.web_console.whitelisted_ips = '172.18.0.0/16'
  end
end
```

**Comment by alfonso-cabrera** [comment]
Claimed.

**Comment by alfonso-cabrera** [comment]
This does not hinder the compose and rails quickstart tutorial. I was able to follow the tutorial and load the welcome page without any issues. Since the tutorial works without this config setting it seems best to not introduce an additional step to the quickstart.

**Comment by mstanleyjones** [comment]
Thanks @alfonso-cabrera
