### ISSUE TITLE
Windows commands

### ISSUE THREAD

**Issue by shashidharps** [docker/docker.github.io#10312]
File: [engine/reference/commandline/import.md](https://docs.docker.com/engine/reference/commandline/import/)

The import command doesnt work on windows, please provide commands in documentation to import tar images on windows too.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. You can try [docker load](https://docs.docker.com/engine/reference/commandline/load/) depending on how the tarball was created. For support, please try the Docker Community Slack or Forums.
- https://forums.docker.com/
- https://dockercommunity.slack.com/
