### ISSUE TITLE
Remove invalid symbols

### ISSUE THREAD

**Issue by akopchinskiy** [docker/docker.github.io#10327]
File: [engine/reference/commandline/cp.md](https://docs.docker.com/engine/reference/commandline/cp/)

Replace this:
```
docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH
```

With this:
```
docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH
docker cp [OPTIONS] SRC_PATH CONTAINER:DEST_PATH
```

**Comment by thaJeztah** [comment]
The `SRC_PATH|-` and `DEST_PATH|-` to indicate that either a `SRC_PATH` or `DEST_PATH` can be used (e.g. `/some/directory`) _or_ ( the `|` means "or") `-`, which will use `stdin` or `stdout`.


For example, the following example copies the `/etc/hosts` file from the container to a "tar" stream on `stdout`:


```bash
docker run -dit --name mycontainer busybox

docker cp mycontainer:/etc/hosts -

hosts0100644000000000000000000000025613623770630012152 0ustar00rootroot00000000000000127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.4	b8600dca38ef
```

Which could be useful to pipe it to another command for further processing
