### ISSUE TITLE
"Edit this page" links don't work on reference docs not on docker.github.io

### ISSUE THREAD

**Issue by londoncalling** [docker/docker.github.io#1033]
### Problem description

On reference docs pulled from repos other than https://github.com/docker/docker.github.io/, the `Edit this page` links don't work

### Problem location, examples

e.g, see: 
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/
https://docs.docker.com/engine/reference/api/docker_remote_api/

### Suggestions for a fix

API docs are in the `docker/docker` repo here: https://github.com/docker/docker/tree/master/docs/api

We need to find a way of making the `Edit this page` links on those pages link to the correct pages on the `docker/docker` repo. The code for this is in the file: https://github.com/docker/docker.github.io/blob/master/_layouts/docs.html

### Related issues, links

@ahmetalpbalkan caught the problem and mentioned it on a tweet here: https://twitter.com/AhmetAlpBalkan/status/816769099841667072

### Interested folks

@thaJeztah @ahmetalpbalkan @johndmulhausen @mstanleyjones

**Comment by londoncalling** [comment]
@thaJeztah , that's tricky ! ...

**Comment by thaJeztah** [comment]
Yes, I think an option to open an issue would be good, from there on, we can point them to the right location to open a pull request.

**Comment by johndmulhausen** [comment]
@johndmulhausen Look for this logic; add stuff to YAML file: 

`{% assign edit_url = "https://github.com/docker/docker.github.io/edit/master/" | append: page.path %} {% for entry in site.data.not_edited_here.overrides %} {% if page.url contains entry.path %} {% if entry.source %}{% assign edit_url = entry.source %}`
