### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by gmisagm** [docker/docker.github.io#10359]
### Problem description

Searching for docker info about size of images on Google led me to the broken link below

### Problem location

https://docs.docker.com/v17.09/engine/userguide/storagedriver/imagesandcontainers/

**Comment by usha-mandya** [comment]
Hello @gmisagm, thank you for reporting the broken link issue. This issue has been fixed.

You can find more information about Docker images in the following topics:

- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
- https://docs.docker.com/develop/develop-images/baseimages/
- https://docs.docker.com/develop/develop-images/image_management/
- https://docs.docker.com/docker-hub/official_images/

We recommend that you refer to our latest documentation - https://docs.docker.com/ to learn about Docker.

Hope this helps!
