### ISSUE TITLE
help documents not useful

### ISSUE THREAD

**Issue by tirelibirefe** [docker/docker.github.io#10357]
File: [engine/reference/commandline/cp.md](https://docs.docker.com/engine/reference/commandline/cp/)

Help documentation is prepared but can not be understood. The same command is explained here more understandable by a plain way.
https://www.shellhacks.com/docker-cp-command-copy-file-to-from-container/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The topic has been updated to include simple examples.
