### ISSUE TITLE
Step 5 for "Uninstall Docker Engine -Enterprise" does not work

### ISSUE THREAD

**Issue by UweHey** [docker/docker.github.io#10362]
File: [ee/docker-ee/windows/docker-ee.md](https://docs.docker.com/ee/docker-ee/windows/docker-ee/)

Platform: Windows Server 2016
Docker version: 19.05

Step 5 says:
 Get-HNSNetwork | Remove-HNSNetwork
 Remove-Item -Path "C:\ProgramData\Docker" -Recurse -Force

None of the two commands works for me.

- Get-HNSNetwork cmdlet is not found by powershell

- Deleting "C:\ProgramData\Docker" with file tools (File Explorer, cmd line, powershel) is impossible due to access denied

In https://github.com/moby/moby/issues/26873 I have found reference to https://github.com/moby/docker-ci-zap and folder is now empty.

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this here for that reason. Feel free to continue the conversation after I close.
