### ISSUE TITLE
Docker machine link is broken: https://docs.docker.com/v17.09/machine/install-machine/

### ISSUE THREAD

**Issue by knoriy** [docker/docker.github.io#10378]
### Problem location

- I saw a problem on the following URL: <https://docs.docker.com/v17.09/machine/install-machine/>

- I couldn't find the information I wanted. I expected to find it near the following URL: <https://docs.docker.com/v17.09/machine/install-machine/>

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
Thank you for your feedback @knoriy. This issue has been fixed.
