### ISSUE TITLE
[Low priority] Duplicate anchor appended to URL when using anchor link

### ISSUE THREAD

**Issue by strarsis** [docker/docker.github.io#10379]
### Problem description
When having arrived at a Docker documentation page via an URL that already contains an anchor and then clicking the anchor link next to a heading in the Docker documentation, the existing anchor in URL is kept and the anchor of the selected anchor is appended.

E.g. visit the logging section: https://docs.docker.com/compose/compose-file/compose-file-v2/#logging
Now select the anchor link next to the "logging" heading (hover it to make the anchor link appear left to it).
Notice that the `#logging` part is appended to the browser URL although it is already there. The URL becomes https://docs.docker.com/compose/compose-file/compose-file-v2/#logging#logging.
Subsequent selection of the link will not further append to the URL.

### Problem location
Probably the whole documentation, where headings are used as they offer an anchor link.

### Suggestions for a fix
Make the function that appends the anchor "idempotent"? Maybe this isn't even worth the hassle...

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This appears to have been resolved. If the issue still persists, please let us know.
