### ISSUE TITLE
dockerd CLI YAML file needs to be properly mirrored, replace Markdown

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#1038]
https://github.com/docker/docker.github.io/tree/vnext-engine/_data/dockerd-cli

This YAML file replaces the Markdown that previously covered the dockerd CLI, creating this page in the process:

http://docker-docs-vnext-engine.netlify.com/engine/reference/commandline/dockerd/

By some magic, this file should probably live on docker/docker (so that the core team can update it when there are daemon changes) and get pushed or pulled to the docs.

**Comment by mstanleyjones** [comment]
@thaJeztah do you have any preference for where the `dockerd.yaml` lives if it goes in the `docker/docker` repo?

**Comment by thaJeztah** [comment]
@mstanleyjones sorry for the delay (didn't read your ping yet); @johndmulhausen, @tiborvass and I had a chat today to see how we can improve the current status, and worked out some short-term solutions, and "long-term" goals.
