### ISSUE TITLE
Docker export link is broken

### ISSUE THREAD

**Issue by rpedrodasilva10** [docker/docker.github.io#10381]
### Problem description

Broken link to the reference manual on docker export
### Problem location
On the [Docker export reference](https://docs.docker.com/engine/reference/commandline/export/), 
when trying to access the link that should explain how to use [backup](https://docs.docker.com/v17.03/engine/tutorials/dockervolumes/#backup-restore-or-migrate-data-volumes)

- I saw a problem on the following URL: <https://docs.docker.com/v17.03/engine/tutorials/dockervolumes/#backup-restore-or-migrate-data-volumes>

### Suggestions for a fix

I found the link adjusting the version to **v17.06** on the link, as follows: 
https://docs.docker.com/v17.06/engine/tutorials/dockervolumes/#backup-restore-or-migrate-data-volumes

So the version in the URI tree should be reviewed.

**Comment by usha-mandya** [comment]
@rpedrodasilva10 Thank you for reporting the broken link. This issue has now been fixed. 

We apologize for any inconvenience this may have caused you.
