### ISSUE TITLE
Documentation for X-Registry-Auth might be incomplete

### ISSUE THREAD

**Issue by cfauchere** [docker/docker.github.io#10395]
### Problem description

The documentations tells that X-Registry-Auth is base64 encoded json:
{
  "username": "string",
  "password": "string",
  "email": "string",
  "serveraddress": "string"
}

I am facing an issue that seems related to the presence of / in the base64 encoded header. Using the same credentials and powershell the header is the same except that / seems to be replaced by _. Is there any kind of escaping required?

### Problem location

https://docs.docker.com/engine/api/v1.40/#section/Authentication

### Project version(s) affected

Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      19.03.5
 API version:  1.40
 Go version:   go1.12.12
 Git commit:   633a0ea
 Built:        Wed Nov 13 07:29:19 2019
 OS/Arch:      linux/amd64

**Comment by epogenesis** [comment]
I'm unsure about it being good leaving this as a comment, but the description also fails to explain the exact meaning of serveraddress. I just assumed it was the registry address, but I don't think it is made clear at all here

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The API documentation is maintained in an upstream repo at https://github.com/moby/moby/blob/master/api/swagger.yaml
If the issue is still applicable, please help create an issue in the source repo.
