### ISSUE TITLE
docker service ps

### ISSUE THREAD

**Issue by kakawi** [docker/docker.github.io#10405]
File: [engine/reference/commandline/service_ps.md](https://docs.docker.com/engine/reference/commandline/service_ps/)

Please change the line
`docker service ps` to `docker service ls`

**Comment by usha-mandya** [comment]
@kakawi Please note that `docker service ps` is still supported and it would be technically incorrect to remove `docker service ps` or replace it with `docker service ls` in the documentation. I'm closing this issue for this reason. Feel free to comment if you disagree.
