### ISSUE TITLE
Unsetting env variables in a Dockerfile

### ISSUE THREAD

**Issue by bikashlama541** [docker/docker.github.io#10419]
Docker CE version:19.03.05
OS: Mac 

Hello , 

In my  Dockerfile, I have some credentials hard coded. I want these credential get removed from environment during container run time. For this I had overriden the environment variables with blank string on entrypoint.sh script but the process does not work as expected. I can still see password inside my container env . I tried linux unset too but it did not work as well .  Can anyone please help me with this issue . Below is my Dockerfile and entrypoint.sh file . Thank you

## Dockerfile

```
FROM alpine:latest
ENV DB_USERNAME="mongo"
ENV DB_PASSWORD="mongo"
WORKDIR /
ADD entrypoint.sh /entrypoint.sh
#ENTRYPOINT ["/bin/ash"]
CMD ["/bin/sh","/entrypoint.sh"]
```
## entrypoint.sh file

```
#!/bin/sh
echo $DB_USERNAME
echo $DB_PASSWORD
#unset -v DB_USERNAME
#unset -v DB_PASSWORD
touch /tmp/hello
DB_USERNAME="" DB_PASSWORD="" /bin/sh

**Comment by imba-tjd** [comment]
Secrets shouldn't be stored in ENV, `docker history` can see every building steps even if you successfully unset it in your script, let alone `ENTRYPOINT` can be overwritten. There are some ways to use secrets, but you should (search and) ask questions on https://stackoverflow.com/
