### ISSUE TITLE
Broken link in Support for Let's Encrypt section

### ISSUE THREAD

**Issue by divlv** [docker/docker.github.io#10428]
### Problem description

Broken link in section:

**Support for Let's Encrypt**
For more information on Let's Encrypt, see https://letsencrypt.org/how-it-works/ and the relevant section of the **registry configuration**

### Problem location

Words **registry configuration** linked incorrectly.

**Comment by usha-mandya** [comment]
@divlv Thank you for the feedback. I couldn't spot any broken links in https://docs.docker.com/registry/deploying/#support-for-lets-encrypt. Both the external link to Let's Encrypt docs and the internal link to registry configuration work as expected. 

Could you elaborate on the issue you are experiencing so I can try and reproduce this issue internally? Thanks.

**Comment by divlv** [comment]
Check the https://github.com/docker/docker.github.io/blob/master/registry/deploying.md file
and search for "relevant section of the registry configuration" string.
