### ISSUE TITLE
Feedback for: datacenter/dtr/2.1/guides/monitor-troubleshoot/index.md

### ISSUE THREAD

**Issue by vikstrous** [docker/docker.github.io#1042]
File: [datacenter/dtr/2.1/guides/monitor-troubleshoot/index.md](https://docs.docker.com/datacenter/dtr/2.1/guides/monitor-troubleshoot/)

Warn that we are planning to remove `/load_balancer_status` in DTR 2.3.

**Comment by joaofnfernandes** [comment]
What endpoint should be used? `/health`?

**Comment by vikstrous** [comment]
Yep.

**Comment by joaofnfernandes** [comment]
This is going to be addressed on DTR 2.2
