### ISSUE TITLE
the port error when I follow your command

### ISSUE THREAD

**Issue by 416381012** [docker/docker.github.io#10427]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)
command: docker container run --publish 8000:8080 --detach --name bb bulletinboard:1.0
should change to : docker container run --publish 8080:8080 --detach --name bb bulletinboard:1.0

I use macbook-air, and i meet this issue,i changed  8000 to 8080 is ok.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The get-started tutorial has changed. If the issue still persists, please let us know.
