### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by emails01** [docker/docker.github.io#10438]
not sure
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
Hello @emails01, there isn't enough information on this ticket for us to work on. Therefore, I'm closing this ticket. Feel free to reopen with more information about the issue you are experiencing.
