### ISSUE TITLE
Invalid link from docker for windows release notes to networking known issues

### ISSUE THREAD

**Issue by eddykavanagh** [docker/docker.github.io#10444]
### Problem description

When viewing the release notes for docker for windows, following the networking known issues link in the main document took me to a 404.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/docker-for-windows/release-notes/

- Other: <DETAILS>

### Project version(s) affected

N/A

### Suggestions for a fix

Update the link from https://docs.docker.com/docker-for-win/networking/#use-cases-and-workarounds to https://docs.docker.com/docker-for-windows/networking/#use-cases-and-workarounds.

**Comment by craig-osterhout** [comment]
The link now redirects.
