### ISSUE TITLE
Correct support win-build version for WIN HOME WSL2 in Docker Desktop Community 2.2.2.0

### ISSUE THREAD

**Issue by mkontani** [docker/docker.github.io#10454]
### Problem description

Windows 10 Home users can now use Docker Desktop through the experimental WSL 2 support since Docker Desktop Community 2.2.2.0.

In [official release note](https://github.com/docker/docker.github.io/blob/master/docker-for-windows/edge-release-notes.md) says that its future requires Windows Insider Preview Build **19018** or later, 
but in [docker blog](https://www.docker.com/blog/docker-desktop-for-windows-home-is-here/), 
it says that  its future requires Windows Insider Preview build **19040** or higher.

Which version is correct? maybe later 19040?

Thank you.

**Comment by usha-mandya** [comment]
Hello @mkontani Thank you for the feedback. 

Docker Desktop recently announced support for Windows Home. If you would like to install Docker Desktop with WSL 2 integration on Windows Home, you'd need Windows Insider Preview build 19040 or higher. 
However, if you'd like to use WSL 2 with Docker Desktop, you need Windows Insider Preview Build 19018 or higher.

Hope that clarifies.
