### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by deugister** [docker/docker.github.io#10463]
### Problem description

on the page:
https://docs.docker.com/docker-for-windows/dashboard/
there is a link to the asp.net version of the frontend in the text:
>>The example voting application contains:
>>A front-end web app in Python or ASP.NET Core which lets you vote between two options
which leads to 404....

### Problem location

- I saw a problem on the following URL: <URL>

https://docs.docker.com/docker-for-windows/dashboard/

### Suggestions for a fix

check the docu and fix the links.

**Comment by usha-mandya** [comment]
@deugister Thank you for the feedback. I've created PR to fix the broken links issue.
