### ISSUE TITLE
Use PowerShell DSC: The referenced github repository is no longer available

### ISSUE THREAD

**Issue by chrischu** [docker/docker.github.io#10478]
In the documentation for how to use PowerShell DSC the referenced GitHub repository https://github.com/anweiss/DockerClientDSC is no longer available.

File: [config/thirdparty/dsc.md](https://docs.docker.com/config/thirdparty/dsc/)

**Comment by thaJeztah** [comment]
Thanks for reporting! Yes, we were recently reviewing those pages, and plan to remove them as they are either outdated/no longer exist, or at least unmaintained.

I'll open a pull request to remove them
