### ISSUE TITLE
doesn't tell you to start the service

### ISSUE THREAD

**Issue by NickFranceschina** [docker/docker.github.io#10482]
File: [ee/docker-ee/windows/docker-ee.md](https://docs.docker.com/ee/docker-ee/windows/docker-ee/)

after checking the restart, if there is no restart needed, then you have to run docker before you can run the hello-world

`Start-Service docker`

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
