### ISSUE TITLE
Please fix the ipv6 page

### ISSUE THREAD

**Issue by sixcorners** [docker/docker.github.io#10490]
File: [config/daemon/ipv6.md](https://docs.docker.com/config/daemon/ipv6/)
Can we go back to the old ipv6 page? The instructions here don't seem to work.
related to: moby/moby#36954

**Comment by sixcorners** [comment]
Here is an older version of this page.
https://github.com/docker/docker.github.io/blob/c0eb65aabe4de94d56bbc20249179f626df5e8c3/engine/userguide/networking/default_network/ipv6.md

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It appears fixed in https://github.com/docker/docker.github.io/commit/1b319c30a57334d82096bc4e1cabfab3a8b6dda1

**Comment by sixcorners** [comment]
@craig-osterhout Could this page be fixed too?
https://gdevillele.github.io/engine/userguide/networking/default_network/ipv6/
I click "edit this page" at the bottom but it's broken.

It says that setting this to true should be enough to give the containers link local ipv6 addresses but it just errors out dockerd.
