### ISSUE TITLE
Switching channel is not correctly described

### ISSUE THREAD

**Issue by PerMildner** [docker/docker.github.io#10491]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/)

"Uninstall the current version of Docker Desktop and install a different version (Stable or Edge), or reset your VM disk."

The suggestion "reset your VM disk" as a way to switch channel (e.g. from Edge to Stable) does not give any useful information. In particular, if I reset the VM image in the Docker (edge) settings then nothing obvious happens that would let me switch back to Stable channel.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This is no longer part of the topic.
