### ISSUE TITLE
Beautify or prettify json with format command option

### ISSUE THREAD

**Issue by AvtsVivek** [docker/docker.github.io#10515]
### Problem description

Using format option in commands like events, ls etc formats the output into Json. 

docker container ls -a --format='{{json .}}'
docker events --format '{{json .}}'

But its not prettified. I feel it would be much easy to read if its prettfied.

Raised on [so](https://stackoverflow.com/q/60848049/1977871) but the suggestions did not work.

**Comment by thaJeztah** [comment]
This has been discussed in the past, but was considered out of scope (JSON is generally for machine processing, and not for "human" consumption).

I would recommend installing `jq`, which allows you to both pretty-print JSON, and even adds color, as well as allowing you to further manipulate json output.

For example;

```bash
docker container ls -a --format='{{json .}}' | jq .
```
Which produces:

```json
{
  "Command": "\"nginx -g 'daemon of…\"",
  "CreatedAt": "2020-03-25 17:19:12 +0100 CET",
  "ID": "64b8eb835270",
  "Image": "nginx:alpine",
  "Labels": "maintainer=NGINX Docker Maintainers <docker-maint@nginx.com>",
  "LocalVolumes": "0",
  "Mounts": "",
  "Names": "xenodochial_hopper",
  "Networks": "bridge",
  "Ports": "80/tcp",
  "RunningFor": "4 seconds ago",
  "Size": "0B",
  "Status": "Up 3 seconds"
}
{
  "Command": "\"nginx -g 'daemon of…\"",
  "CreatedAt": "2020-03-25 14:17:22 +0100 CET",
  "ID": "41a7cde38df1",
  "Image": "nginx:alpine",
  "Labels": "maintainer=NGINX Docker Maintainers <docker-maint@nginx.com>",
  "LocalVolumes": "0",
  "Mounts": "",
  "Names": "hardcore_mclaren",
  "Networks": "bridge",
  "Ports": "80/tcp",
  "RunningFor": "3 hours ago",
  "Size": "0B",
  "Status": "Up 3 hours"
}
```

**Comment by thaJeztah** [comment]
I'll close this ticket because of the above (also; given that this is a feature request for the docker engine, not for the documentation, https://github.com/moby/moby would've been a better place for this)

Feel free to continue the conversation after I closed though 👍

**Comment by AvtsVivek** [comment]
I run windows 10 pro, and I tried both on powershell as well visual studio cmd; jq simply does not work. Not sure what I am missing. Raised on [SO ](https://stackoverflow.com/a/60848171/1977871)as well.

**Comment by thaJeztah** [comment]
In PowerShell, something like this looks to work;

```powershell
docker ls -a --format="{{ json . }}" | ConvertFrom-Json | ConvertTo-Json
```

**Comment by thaJeztah** [comment]
oh, I see someone replied that on SO as well

**Comment by AvtsVivek** [comment]
Ok, So finally I found out. With powershell it did not work. But with cmd prompt it worked.

See my update the [SO question](https://stackoverflow.com/q/60848049/1977871) it self.

**Comment by thaJeztah** [comment]
Perfect!
