### ISSUE TITLE
Broken link in Links section

### ISSUE THREAD

**Issue by cilphex** [docker/docker.github.io#10517]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

The Links section contains this text: "we recommend that you use [user-defined networks ](https://docs.docker.com/engine/userguide/networking//#user-defined-networks)".

Where `user-defined networks` is a hotlink pointing to https://docs.docker.com/engine/userguide/networking//#user-defined-networks. This page shows "Sorry, we can't find that page" with status code `403`. (Not `404`.)

**Comment by qckzr** [comment]
The referenced link has an additional '/'

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/docker.github.io/pull/10518
