### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by itprohelper** [docker/docker.github.io#10516]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/v18.03/docker-cloud/index.md

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: This link was given by Slack Foqal app when I asked a question in a Docker channel 'Docker Mastery'
<img width="794" alt="Screen Shot 2020-03-25 at 2 19 51 PM" src="https://user-images.githubusercontent.com/43117994/77571413-bb573280-6ea3-11ea-946e-e04c9512a071.png">

**Comment by thaJeztah** [comment]
The Docker Cloud service was shut-down two years ago, so I think those pages were removed at some point
