### ISSUE TITLE
Docker Desktop Windows - Note to switch to Linux Containers

### ISSUE THREAD

**Issue by derekgroh** [docker/docker.github.io#10519]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

While working through the docs, you will be unable to continue after the `docker run --interactive --tty ubuntu bash` command unless you switch Docker to Linux Containers

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As the issue is old, the context may have changed. If the issue still persists, please let us know.
