### ISSUE TITLE
Broken link in /install/linux/docker-ce/debian

### ISSUE THREAD

**Issue by hansklotz** [docker/docker.github.io#10528]
### Problem description

The page https://docs.docker.com/install/linux/docker-ce/debian/ contains a broken link in the right sidebar called "Uninstall old versions".

### Problem location

Probably the tag "uninstall-old-version" is missing.

**Comment by thaJeztah** [comment]
Looks like this is fixed now, and it links to https://docs.docker.com/engine/install/debian/#uninstall-old-versions
