### ISSUE TITLE
add information about another configuration file to check for conflicting configuration

### ISSUE THREAD

**Issue by sahlawat** [docker/docker.github.io#10526]
File: [machine/drivers/generic.md](https://docs.docker.com/machine/drivers/generic/)

Replace:
For systems that use systemd, if you have an existing configuration defined in ‘/etc/systemd/system/docker.service.d/’ this may conflict with the settings created by docker-machine. Make sure you don’t have any other configuration files in this location that override the [ExecStart] setting.

With:
For systems that use systemd, if you have an existing configuration defined in ‘/etc/systemd/system/docker.service.d/’ this may conflict with the settings created by docker-machine. Make sure you don’t have any other configuration files in this location or any other settings in '/etc/docker/daemon.json' that override the [ExecStart] settings.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as Docker Machine has been deprecated.
