### ISSUE TITLE
Network on laptop does not work (Windows 10 1909)

### ISSUE THREAD

**Issue by danzaharescu** [docker/docker.github.io#10523]
### Problem description

Transparent network can be created, but the container does not get the IP I want to assign.
Also, with the default settings, the container does not get a generated IP and cannot be accessed.
On other stations both cases work well.

### Problem location

I have uploaded the diagnostics with ID: 
872172A6-2C37-4AF5-805E-2F13638A9F17/20200327063916

### Project version(s) affected

Happened on 1903 and also 1909.

### Suggestions for a fix

I do not see any possible fix. 
I am not able to see any error in any console, the network just does not work.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If you need support, you can try the Docker Community Forums. If you believe this is a bug, please create an issue in the application repo. If there is an error in the documentation, please let us know.
