### ISSUE TITLE
Broken links in /config/daemon/systemd/

### ISSUE THREAD

**Issue by Kaiser925** [docker/docker.github.io#10537]
### Problem description

The page https://docs.docker.com/config/daemon/systemd/ contains two broken links called " Configure Docker to start on boot" and "Daemon configuration file".

### Problem location

- I saw a problem on the following URLs: 
   - https://docs.docker.com/config/daemon/systemd/#start-automatically-at-system-boot

### Suggestions for a fix

Probably the page about docker systemd config is missing.

**Comment by usha-mandya** [comment]
Hello @Kaiser925, thank you for reporting the broken links issue. The links you have specified above work fine for me. Could you try again and let us know if you are still seeing the issue? Thanks.

**Comment by Kaiser925** [comment]
The links works fine now. @usha-mandya

**Comment by usha-mandya** [comment]
Thanks for confirming @Kaiser925. Closing this issue.
