### ISSUE TITLE
docker import tar ball

### ISSUE THREAD

**Issue by rushins** [docker/docker.github.io#10530]
Hello Support,

i have issue with import to my private registry .

i have build a system on docker container and exported as local tar file and from there i was trying to upload the image to my private registry and its running forever for past 24 hours ? not sure if this is going to end or its doing anything ? 

here are my comamnds.

image creation
--------------
docker container stop nw
docker export nw > /data/export/nw.tar
cat /data/export/nw .tar | docker import - docker.priv:5000/nwnew:latest

it returned SHA256 output which confirms that tar is created as image 
-----------------
sha256:17c46abbc447e93ac2567b88ccc76f760454329a40fc0cacae7bf572e0182d3f

 here is the command i used to upload to private registry 
--------------------------------------------
docker import - docker login docker.priv:5000/nwnew:latest

can you check if i am doing anywhere wrong? do i have to specify the image or tar ? 

BR,
Rushi.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue.
If you believe it is a bug, please report in the registry repo. For details, see https://docs.docker.com/registry/help/

For general support, you can try the Docker Community Slack and forums
- https://forums.docker.com/
- https://dockercommunity.slack.com/
