### ISSUE TITLE
Stable/Edge references are missing information

### ISSUE THREAD

**Issue by csdfgraham** [docker/docker.github.io#10538]
File: [storage/storagedriver/device-mapper-driver.md](https://docs.docker.com/storage/storagedriver/device-mapper-driver/)

There are references to Stable and Edge that are links, but the links don't take to a page that explains these terms

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As the issue is old, some context may have changed. The terms no longer appear on the page.
