### ISSUE TITLE
overlay2 driver: randomly ineffective write operations

### ISSUE THREAD

**Issue by heidricha** [docker/docker.github.io#10544]
### Problem description

- I start several (like 15) similar (almost identical) containers in a raw, from python script (docker module)
- run's command arg invokes python scripts inside the containers as well, before starting monit as process supervisor
- these scripts make modification on some config files by merging json files, overwriting one of them
- the "overwritten" files are left intact in some (random!) of the almost identical containers (best case: one, worst case: 8) -  although script finished with no error. 
- running the same command by hand does the json merge fine

it only happens using overlay2 driver. btrfs does the job well. tried with xfs, ext4, and btrfs under overlay2, all faulty. also tried several OSs, like
- centos8: xfs - problem arose here since no btrfs driver anymore - and ext4 - errors
- centos7: btrfs, no problem
- alpine: ext4 - errors, btrfs/onerlay2 (just moved the docker dir to btrfs) - errors, btrfs/btrfs (reinstalled docker)- fine

I have tried to play with timing and insert sync calls after writes, with no visible effect

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If the issue is with the driver and not the docs, please create an issue at https://github.com/moby/moby
If you need support, you can try the Docker Community Slack at https://dockercommunity.slack.com/
