### ISSUE TITLE
Can you kill a container by name or ID or either?

### ISSUE THREAD

**Issue by fardok** [docker/docker.github.io#1054]
File: [engine/reference/commandline/kill.md](https://docs.docker.com/engine/reference/commandline/kill/)

what is it CONTAINER?   - is it  code or his name?

**Comment by ralphtheninja** [comment]
`CONTAINER` stands for either a container id or container name.

**Comment by scjane** [comment]
#dibs

**Comment by ashishkamat2791** [comment]
Hi @mstanleyjones 
I checked by running commands. It does not kill as it supposed to but just stop the running container and shows as exited 
I think we need to pass the signal using `-s` flag for `docker kill` to completely remove container which can be achieved using `docker rm -f CONTAINER-ID/CONTAINER-NAME` for a single container and `docker rm -f $(docker ps )` for all  running containers and `docker rm -f $(docker ps -aq) for all running as well as dead containers

**Comment by scjane** [comment]
@ashishkamat2791 Hi, here's my undrstanding:

- `docker kill` forcibly stops running containers. By default, it sends the `-s KILL` signal even if you only run `docker kill <container_id or container_name>`; that is, `docker kill <container_id or container_name>` and `docker kill -s KILL <container_id or container_name>` works the same way. After running this command for a container, the container exited but still exists, that is, it still can be seen using `docker ps -a` and can be started again using `docker start`. 
- `docker stop` gracefully stop running containers. After running this command for a container, the container exited but still exists, that is, it still can be seen using `docker ps -a` and can be started again using `docker start`.
- `docker rm` removes containers. After running this command for a container, the container does not exist anymore. It cannot be seen using `docker ps -a` and thus cannot be started again using `docker start`.

**Comment by mstanleyjones** [comment]
@scjane sounds like you have the info to fix this then!

**Comment by scjane** [comment]
@mstanleyjones I think we can add information in the "Extended Desciption" section referring that a  container can be killed by its ID or name using this command, as the "docker attach" page does, as shown in the following figure.
![155](https://cloud.githubusercontent.com/assets/25146885/25212798/3b6e79dc-25bf-11e7-89a1-bae9643dc258.jpg

Is this the file to be editted?https://github.com/moby/moby/edit/17.03.x/docs/reference/commandline/kill.md

**Comment by mstanleyjones** [comment]
@scjane that's the one! But do it in the `master` branch and make a note that it should be cherry-picked.

**Comment by mstanleyjones** [comment]
Under review upstream. Thanks @scjane!
