### ISSUE TITLE
Corrections to running_ssh_service.md

### ISSUE THREAD

**Issue by mjhenke** [docker/docker.github.io#1055]
File: [engine/examples/running_ssh_service.md](https://docs.docker.com/engine/examples/running_ssh_service/)

The following RUN line should be changes:
    from
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    to
RUN sed -i 's/PermitRootLogin [a-zA-Z-]*/PermitRootLogin yes/' /etc/ssh/sshd_config

thus making it agnostic of image setting...

**Comment by jadametz** [comment]
I'll take this one.

**Comment by mstanleyjones** [comment]
No action for two days, so this is up for grabs!

**Comment by mstanleyjones** [comment]
We decided not to merge the PR, but you get the points. thanks @jadametz !
