### ISSUE TITLE
Task. 3, Step 9 will fail.

### ISSUE THREAD

**Issue by ismudnx** [docker/docker.github.io#10555]
File: [swarm/swarm_at_scale/deploy-infra.md](https://docs.docker.com/swarm/swarm_at_scale/deploy-infra/)

Task.3 Step 9 will fail since config.toml is expected inside the current docker host, but the steps direct to create that in localhost confg/config.toml. Succeeded after doing an ssh into the loadbalancer machine and creating the config.toml to be binded.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the issue is old, some context changed. If the issue persists, please let us know.
