### ISSUE TITLE
Broken doc link

### ISSUE THREAD

**Issue by xenophiler** [docker/docker.github.io#10568]
### Problem description
Starting page
https://docs.docker.com/install/linux/docker-ce/fedora/

Bottom of page

Next Steps 

"Continue to Post-installation steps for Linux"..... Link broken.

https://docs.docker.com/install/linux/linux-postinstall.md

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/install/linux/docker-ce/fedora/

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

It's just a broken page to a github style MD README file.

**Comment by thaJeztah** [comment]
Thanks for reporting; this link was fixed, and now correctly leads to https://docs.docker.com/engine/install/linux-postinstall/
