### ISSUE TITLE
No "Preferences" option present on Docker Desktop for Windows

### ISSUE THREAD

**Issue by KoditkarVedant** [docker/docker.github.io#10572]
File: [config/containers/live-restore.md](https://docs.docker.com/config/containers/live-restore/)
Section: https://docs.docker.com/config/containers/live-restore/#enable-live-restore

Under enable live restore section - the steps mentioned to add the configuration to the daemon configuration file by click on docker icon in task bar is not the same for Docker Desktop for Windows version: 2.2.0.5 (43884).
![image](https://user-images.githubusercontent.com/18693839/78473335-6c3fb600-775d-11ea-809d-519807eecb39.png)

**Expected Path:**
`Preferences -> Daemon -> Advanced.`

**Actual actual is Path**
`Settings -> Docker Engine`

![image](https://user-images.githubusercontent.com/18693839/78473363-aad57080-775d-11ea-8ab8-d07d3e86e4e2.png)

![image](https://user-images.githubusercontent.com/18693839/78473372-ba54b980-775d-11ea-8699-26c3117720e1.png)

**Comment by dvdksn** [comment]
Thanks for pointing this out @KoditkarVedant ! I've corrected the settings path now.
