### ISSUE TITLE
Request for adding chkconfig equivalent using update-rc.d

### ISSUE THREAD

**Issue by NI1993** [docker/docker.github.io#10571]
File: [install/linux/linux-postinstall.md](https://docs.docker.com/install/linux/linux-postinstall/)

Hello all!
I'm trying to [Configure Docker to start on boot](https://docs.docker.com/install/linux/linux-postinstall/#chkconfig) and as I followed the instructions there the last instruction was executing the following command: `sudo chkconfig docker on`

I'm using an Ubuntu 16.04 OS, and apparently `chkconfig` is [not supported](https://stackoverflow.com/questions/20680050/how-do-i-install-chkconfig-on-ubuntu) on such OS.

Perhaps I'm missing something or doing it wrong, but can u please add an equivalent command using `update-rc.d` ?

I'll be glad to receive any feedback or supply more info on the matter.

Thanks a lot!

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This section has been updated. If the issue still persists, please let us know.
