### ISSUE TITLE
Error with documentation

### ISSUE THREAD

**Issue by Jen-Pearson** [docker/docker.github.io#10576]
File: [compose/aspnet-mssql-compose.md](https://docs.docker.com/compose/aspnet-mssql-compose/)

The build fails 
![image](https://user-images.githubusercontent.com/8033039/78532458-a1660a00-782a-11ea-9bf9-48d2af6ceef5.png)

And using the compose up command fails - but I'm not even sure why it's trying to access a sqlite database if I followed the instructions for sql server. 

![image](https://user-images.githubusercontent.com/8033039/78532535-c3f82300-782a-11ea-8caa-e80be705bab7.png)

**Comment by craig-osterhout** [comment]
Closing in favor of https://github.com/docker/docker.github.io/issues/11345
