### ISSUE TITLE
Containers, clock and NTP client

### ISSUE THREAD

**Issue by marcobellaccini** [docker/docker.github.io#10591]
File: [develop/dev-best-practices.md](https://docs.docker.com/develop/dev-best-practices/)

At the bottom of the page, I read:

> Always run an NTP client on the Docker host and within each container process and sync them all to the same NTP server. If you use swarm services, also ensure that each Docker node syncs its clocks to the same time source as the containers.

AFAIK adjusting the clock is not allowed in containers (they get the time from the host).

Can you confirm?

That statement seems to be source of confusion for some users - see also [this](https://github.com/docker/docker.github.io/issues/7790) stale issue.

**Comment by kluisi** [comment]
As the author of the original linked issue, I agree. The documentation is confusing and seems wrong.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Merging the duplicate issues. Closing in favor of  #14834
