### ISSUE TITLE
404 at: /v1.8/introduction/understanding-docker/

### ISSUE THREAD

**Issue by jsrikrishna** [docker/docker.github.io#1059]
URL: /v1.8/introduction/understanding-docker/

Not able to find the doc for "Understanding Architecture". 

If it already exists at some other place, this can be closed.

**Comment by johndmulhausen** [comment]
@jsrikrishna You probably should be looking at the current docs rather than 1.8 :) 

https://docs.docker.com/engine/understanding-docker/
