### ISSUE TITLE
check-config.sh script: is it still valid with 5.6 linux kernels?

### ISSUE THREAD

**Issue by funder7** [docker/docker.github.io#10592]
File: [check-config.sh](https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh)

My pc is running ubuntu eoan, previously with a custom 5.3 kernel, with all unnecessary options disabled. Then in order to install & run docker, I had to recompile the kernel. 

So I've fetched the latest stable version, which is 5.6. 
I couldn't find some options returned by the check-config script,
listed here:
```
Generally Necessary:
...
- CONFIG_NF_NAT_IPV4: missing
...
- CONFIG_NF_NAT_NEEDED: missing
Optional Features:
...
- CONFIG_IOSCHED_CFQ: missing
- CONFIG_CFQ_GROUP_IOSCHED: missing
...
- Network Drivers:
  - CONFIG_BRIDGE_VLAN_FILTERING: missing 
  - CONFIG_INET_XFRM_MODE_TRANSPORT: missing
...
- Storage Drivers:
    - CONFIG_AUFS_FS: missing
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing
```

Now docker is running fine on the host, at least, after recompiling the kernel I installed it with no errors, and I was able to run the hello-world image. 

I hope that it will be fine with other images too.. Anyway I wanted to report this as the kernel config is quite long, especially because you don't see all the options in the config file, some options are shown only after enabling others... :-)

Anyone else have encountered this problem?

**Comment by whoo** [comment]
Script didn't work for me with > 5.2-kernel.
(Options were merged)

**Comment by aendeavor** [comment]
Experiencing the same issue with `>=5.4`

**Comment by funder7** [comment]
Closing the issue as this is more for stackoverflow, 
cheers
