### ISSUE TITLE
Feedback for: engine/reference/commandline/service_create.md

### ISSUE THREAD

**Issue by sg1970** [docker/docker.github.io#1060]
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/)

Questions:

1. How do we create a service that uses a **private** repo hosted on Docker Hub ( https://hub.docker.com/r/...) ? **PLEEAAASE** be very explicit and detailed in the explanation and commands. My intent is to have a container running on a swarm with more than one replicas.
2. If that is not possible what are the alternatives/workarounds ?

Many thanks.
SG

**Comment by ralphtheninja** [comment]
`docker login -u myorg -p mypassword`
`docker service create --name myservice --replicas 5 --with-registry-auth myorg/myservice:tag`

**Comment by sg1970** [comment]
Thanks much! It got me further but not all the way. the service is created but it wont start. I suspect its something to do with my image being a Windows native image (as opposed to a linux image). The ostype for my manager and workers is Linux ( How do I change this ??) 

Error Msg when I try to pull the image from my docker private repo (on the Swarm manager ) :

docker@manager1:~$ docker pull  sg1970/myimage
failed to register layer: Error processing tar file(exit status 1): link /Files/Windows/Boot/Resources/en-US/bootres.dll.mui /Files/Windows/WinSxS/amd64_microsoft-windows-bootres.resources_31bf3856ad364e35_10.0.14393.479_en-us_1b80fad7f4a09a1e/bootres.dll.mui: no such file or directory

----- Versions ------

I'am running docker Version 1.13.0-rc5-beta35 (9606) on a Windows 10 Pro (Anniversary Edition) using hyper-v and in Windows Containers Mode (not Linux !). 

Do you know if swarm is supported for that platform ? Thanks for your help !!
---
Boot2Docker version 1.13.0-rc5, build HEAD : 4eec8f1 - Thu Jan  5 22:47:39 UTC 2017
Docker version 1.13.0-rc5, build 43cc971
docker@manager1:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-rc5
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: gjgoh8fef84tj86bk3bl2xofc
 Is Manager: true
 ClusterID: z14pnjfr41ktnsnz4zcmn780o
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.127
 Manager Addresses:
  192.168.1.127:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.39-boot2docker
Operating System: Boot2Docker 1.13.0-rc5 (TCL 7.2); HEAD : 4eec8f1 - Thu Jan  5 22:47:39 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 987.1 MiB
Name: manager1
ID: F3ZI:WMHZ:522G:DK77:347C:WQ2J:PYAU:4VYE:4CUU:YRIY:KL5N:PAPO
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 144
 System Time: 2017-01-10T12:35:04.940377571Z
 EventsListeners: 0
Username: sg1970
Registry: https://index.docker.io/v1/
Labels:
 provider=hyperv
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
docker@manager1:~$

**Comment by sg1970** [comment]
Any luck with this ?

**Comment by mstanleyjones** [comment]
This is the type of question you should probably be asking on forums.docker.com. Sorry for the delay.
