### ISSUE TITLE
Issue while running docker run hello-world

### ISSUE THREAD

**Issue by prasadmahadik** [docker/docker.github.io#10620]
File: [get-started/index.md](https://docs.docker.com/get-started/)
For running the command "docker run hello-world", you have to switch to linux container.
It took 3 hours to run this command due to network issue and google the issues.

**Comment by usha-mandya** [comment]
@prasadmahadik You don't have to switch to Linux containers to run hello-world. I tried running the command after switching to Windows containers in Docker Desktop and it works fine. 

Could you install the latest version of Docker Desktop and give this a try? Let me know how you get on.

To download the latest version of Docker Desktop on Windows, see https://docs.docker.com/docker-for-windows/release-notes/.

**Comment by prasadmahadik** [comment]
Hi Usha, Thanks for the answer. I will check it once again and post the results here.

**Comment by usha-mandya** [comment]
Sure. Closing this ticket now. Feel free to comment on this or open a new ticket if you still experience the issue.

**Comment by thaJeztah** [comment]
This could be related to https://github.com/docker/for-win/issues/2695 and https://github.com/docker-library/hello-world/issues/56. Some time ago, Microsoft deprecated and _removed_ images from Docker Hub for older Windows releases, which means that the `hello-world:latest` image may no longer be available, depending on what version of Windows you're running on 😞
