### ISSUE TITLE
"docker run -dit" vs "docker run -d"

### ISSUE THREAD

**Issue by kzhui125** [docker/docker.github.io#10632]
from https://github.com/docker/docker.github.io/blob/master/config/containers/start-containers-automatically.md

`$ docker run -dit --restart unless-stopped redis`

What's the difference between "docker run -dit" and "docker run -d"?

Thanks,

**Comment by thaJeztah** [comment]
`-dit` is a short-hand notation for `-d -i -t`.

Usually `-i -t` (or `-it`) is used to run a container interactively, but it can also be used to run a container "detached" (`-d`) (in the background) for situations where the container's process expects a TTY (`-t`) to be attached to keep running.

In this example, a `redis` container is started, which doesn't require `-i` or `-t` to be set to keep running, so I think we can remove it to prevent confusion.

I'll open a PR to remove it

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/10698 to remove it
