### ISSUE TITLE
[ee] Broken link in "Where to go next"

### ISSUE THREAD

**Issue by ppetriuk** [docker/docker.github.io#10634]
File: [ee/cluster/aws.md](https://docs.docker.com/ee/cluster/aws/)

The link in "Where to go next" to vSphere is broken:
"View the quick start guide for Azure or [vSphere](https://docs.docker.com/ee/cluster/vsphere/)"
Returns HTTP404 "Sorry, we can't find that page".

**Comment by thaJeztah** [comment]
ping @Dawn-Wood ptal

**Comment by Dawn-Wood** [comment]
Hi @thaJeztah and @ppetriuk we are not fixing bugs in this repo any longer. We have moved our content to a new private repo. I can tell you that this link has been fixed and you will be able to see the fix in our new docs in May. Apologies for the confusion.

**Comment by thaJeztah** [comment]
this link was removed
