### ISSUE TITLE
docker run not working with multiple local disks

### ISSUE THREAD

**Issue by solo7773** [docker/docker.github.io#10637]
### Problem description

docker is installed successfully with hello-word test passed. 

#### OS

Ubuntu 18.04

#### OS file system structure

/dev/vda1, docker is installed in this disk

**If I bind dir in this disk to docker container, everything is ok**

However, dir in another disk will give errors

/dev/vdb2, dir in this disk I want to bind-mount

When I use -v to bind path, the error is

`error while creating mount source path xxx : mkdir xxx`

When I use --mount to bind path, the error is

`bind source does not exist`

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://github.com/docker/for-win/issues/5516

### Project version(s) affected

docker 18.09.9 build 1752eb3

### Suggestions for a fix

No

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If there is an issue the documentation, please let us know. If you need support, you can try the Docker Community Forums.
