### ISSUE TITLE
What does "range" do?

### ISSUE THREAD

**Issue by kmathewmk** [docker/docker.github.io#10639]
File: [config/formatting.md](https://docs.docker.com/config/formatting/)

Could you please document the "range" keyword in https://docs.docker.com/config/formatting/#println ?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. More details are documented in the link at the top of the topic, https://golang.org/pkg/text/template/
If you'd like more Docker-specific examples, you can refer to the CLI reference. For example, https://docs.docker.com/engine/reference/commandline/inspect/
