### ISSUE TITLE
Subcommands and option documentation should be versioned

### ISSUE THREAD

**Issue by Xophmeister** [docker/docker.github.io#1064]
### Problem description

The documentation describes the subcommands and their options based on the current release version of Docker. It's common that hosts run older versions of Docker where certain commands aren't yet available. For example, I was reading up about `--build-arg`, but I only found out that this wasn't supported on my host's older Docker 1.8.3 when it complained at build time.

### Problem location

This affects all CLI and API documentation.

### Suggestions for a fix

There are two options, in my view:

1. Document the release subcommands and options, but put a note regarding minimum version (e.g., "available since Docker 1.9") somewhere nearby.
2. Keep versioned documentation for each release of Docker, allowing users to match the documentation to their environment.

The former would be far easier and, in my view, satisfactory. Others may feel that the full-blown versioning option would be better, from a completeness perspective.

**Comment by mstanleyjones** [comment]
Hi there, we do have versioned documentation under the
[archive](https://docs.docker.com/docsarchive/). Version 1.12 is not yet archived, and we appreciate your patience. These are basically snapshots of our full documentation at the time that a given version of **Docker Engine** is released.

**Comment by johndmulhausen** [comment]
@Xophmeister See v1.12 docs at https://docs.docker.com/v1.12
