### ISSUE TITLE
Some Docker Desktop for Windows Troubleshooting links are self-referential

### ISSUE THREAD

**Issue by C0missar** [docker/docker.github.io#10647]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

Not applicable
  - Diagnostics ID: None

### Expected behavior

That troubleshooting links on the https://docs.docker.com/docker-for-windows/troubleshoot/ actually link to information.

### Actual behavior
Bad links:

1 - The links above in this template all lead to a 404, apparently because the description has been run together with the link
2 - A number of links on the https://docs.docker.com/docker-for-windows/troubleshoot/ page just refer back to the same page (the reference tag is invalid), such as https://docs.docker.com/docker-for-windows/troubleshoot/#how-do-i-add-custom-ca-certificates and https://docs.docker.com/docker-for-windows/troubleshoot/#switch-between-windows-and-linux-containers
3 - Although that page suggests submitting a GitHub issue for documentation, this form is clearly not designed with documentation issues in mind.

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...https://github.com/docker/docker.github.io/issues for the documentation
  2. ...https://docs.docker.com/docker-for-windows/troubleshoot/#how-do-i-add-custom-ca-certificates
  3. ...https://docs.docker.com/docker-for-windows/troubleshoot/#switch-between-windows-and-linux-containers

**Comment by thaJeztah** [comment]
Looks like it's the JavaScript "link fix-up" problem; the links on that page are correct if you disable JavaScript 😞 same as https://github.com/docker/docker.github.io/pull/10615#issuecomment-613990378

And will ultimately be fixed once https://github.com/docker/docker.github.io/pull/10549 is merged, but that has some blockers

**Comment by giv777** [comment]
https://ptjtjshwwqdrugakey.10to8.com
