### ISSUE TITLE
name of the service is mentioned twice 

### ISSUE THREAD

**Issue by AnilPothula** [docker/docker.github.io#10673]
File: [engine/reference/commandline/service_update.md](https://docs.docker.com/engine/reference/commandline/service_update/)

docker service create \
    --name=myservice \
    --mount \
      type=volume,source=test-data,target=/somewhere \
    nginx:alpine \
    myservice

**Comment by thaJeztah** [comment]
nice catch! opened a pull request to fix the example; https://github.com/docker/cli/pull/2466
