### ISSUE TITLE
Link Dead - `Docker for Linux`

### ISSUE THREAD

**Issue by nclarx** [docker/docker.github.io#10689]
### Problem description

From the guides page: https://docs.docker.com/get-docker/ the link to the guide for Linux is dead: https://docs.docker.com/get-docker/engine/install/

### Problem locations
https://docs.docker.com/get-docker/
https://docs.docker.com/get-docker/engine/install/

- I saw a problem on the following URL: https://docs.docker.com/get-docker/engine/install/

### Project version(s) affected

Docker website as at 24/04/2020.

### Suggestions for a fix

- Correct/update the link to the Linux guide at https://docs.docker.com/get-docker/
![2020-04-24-192628_1183x725_scrot](https://user-images.githubusercontent.com/30969962/80197133-90f2c380-8661-11ea-8671-782ba039d103.png)

**Comment by thaJeztah** [comment]
Thanks for reporting; this should be fixed by https://github.com/docker/docker.github.io/pull/10691 (which will be published on docs.docker.com soon)

Meanwhile, the correct URL is https://docs.docker.com/engine/install/
