### ISSUE TITLE
Invalid link for the multi-stage section

### ISSUE THREAD

**Issue by bilalchraibi** [docker/docker.github.io#10681]
File: [develop/develop-images/dockerfile_best-practices.md](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

This link is not valid anymore:
github.com/golang/dep/cmd/dep

**Comment by thaJeztah** [comment]
Can you describe what's not working? Note that this line;

```dockerfile
RUN go get github.com/golang/dep/cmd/dep
```

Is the name of the _package_ / _module_ that's used, it's not the URL to open in your browser if you want to view the source; to view the source of that package on GitHub, use https://github.com/golang/dep/tree/master/cmd/dep

Trying to build the example (only the first few lines) worked fine for me, so I don't think there's something to fix


```dockerfile
FROM golang:1.11-alpine AS build

# Install tools required for project
# Run `docker build --no-cache .` to update dependencies
RUN apk add --no-cache git
RUN go get github.com/golang/dep/cmd/dep
```

**Comment by thaJeztah** [comment]
Let me close this ticket, because I don't think there's an issue with the documentation, but feel free to continue the conversation in case I overlooked something 😅

**Comment by bilalchraibi** [comment]
@thaJeztah Thank you for you the explanation 👍
