### ISSUE TITLE
How about put the base url somewhere it can be found easily?

### ISSUE THREAD

**Issue by soydantaylor** [docker/docker.github.io#10682]
I've been searching for the base url for the api for about 10 min and am having a hard time finding it.  Maybe I'm missing something really obvious though.  
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/)

**Comment by thaJeztah** [comment]
That page describes the specification of the "distribution spec" API, which is implemented by (e.g.) the open source registry (https://docs.docker.com/registry/), but also Docker Hub itself. The base-url thus depends on which registry you're connecting to, which could be your own registry (if you run the open source registry somewhere), or Docker Hub (https://registry-1.docker.io)

**Comment by soydantaylor** [comment]
Yep that makes sense.  It would be good to use dockerhub’s base uri as the example though, so we can test against it with the repos that are already there and compare to whatever registry might be deployed.  Just my $0.02

**Comment by thaJeztah** [comment]
I don't think many (if any) of the parts in that specification could be used without manually modifying them to fill in the fields (e.g. name or the repository, authentication information). These pages are taken from the upstream repository for the open source registry (https://github.com/docker/distribution/blob/master/docs/spec/api.md), and I don't it would work to have that reference Docker Hub (for example, some endpoints are "optional" and are not implemented in large scale registries). The markdown is generated using a template (https://github.com/docker/distribution/blob/master/docs/spec/api.md.tmpl), so perhaps for your own use you could update the template, and generate it to include a base URL in the template?

I'm closing this ticket for now; while I understand what you're looking for, I don't think it's possible to address this at this moment for reasons mentioned above. Feel free to continue the conversation though
