### ISSUE TITLE
When a node joins a swarm cluster, it will cause the docker service of the server where the node is located to hang

### ISSUE THREAD

**Issue by ZhangDianPeng** [docker/docker.github.io#10695]
When a node joins a swarm cluster, it will cause the docker service of the server where the node is located to hang。There is no problem when the two machines independently establishing a swarm network。

Docker version: 17
Centos version:  7.4 
Kernel version: 3.10

Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: time="2020-04-23T18:23:27.661786170+08:00" level=info msg="Attempting next endpoint for pull after error: Get https://localhost/v2/: http: server gave HTTP response to HTTPS client"
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: panic: no ':' separator in digest ""
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: goroutine 55666736 [running]:
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/vendor/github.com/opencontainers/go-digest.Digest.sepIndex(0x0, 0x0, 0x1d45426)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/vendor/github.com/opencontainers/go-digest/digest.go:136 +0x13f
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/vendor/github.com/opencontainers/go-digest.Digest.Algorithm(0x0, 0x0, 0x1be46c0, 0xc42142b440)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/vendor/github.com/opencontainers/go-digest/digest.go:110 +0x35
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/image.(*fs).contentFile(0xc4202c0e70, 0x0, 0x0, 0xc42142e300, 0xc4233210c0)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/image/fs.go:60 +0x42
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/image.(*fs).get(0xc4202c0e70, 0x0, 0x0, 0x47, 0xc4242bb3b8, 0x138751b, 0xc42133c460, 0x70)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/image/fs.go:98 +0x5a
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/image.(*fs).Get(0xc4202c0e70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/image/fs.go:94 +0xac
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/image.(*store).Get(0xc4202407e0, 0x0, 0x0, 0x1d45426, 0x6, 0x2bb9460)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/image/store.go:205 +0x4c
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/distribution.(*imageConfigStore).Get(0xc42222af30, 0x0, 0x0, 0xc42249ccf0, 0xc42018b4f0, 0x47, 0x0, 0x0)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/distribution/config.go:136 +0x4b
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/distribution.(*v2Puller).pullSchema2(0xc421aa4540, 0x7fac2c18da68, 0xc421796300, 0x2ba6ae0, 0xc424306600, 0xc42249ccf0, 0x1d4347c, 0x5, 0x0, 0x0, ...)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/distribution/pull_v2.go:545 +0x1ad
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/distribution.(*v2Puller).pullV2Tag(0xc421aa4540, 0x7fac2c18da68, 0xc421796300, 0x2ba6ae0, 0xc424306600, 0x1d4347c, 0x5, 0xc422dfde40, 0x2bb4c60, 0xc42469dd50)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/distribution/pull_v2.go:398 +0xc7e
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/distribution.(*v2Puller).pullV2Repository(0xc421aa4540, 0x7fac2c18da68, 0xc421796300, 0x2ba6ae0, 0xc424306600, 0x1d4347c, 0x5, 0xc423d08f00, 0xc420a03ad0)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/distribution/pull_v2.go:91 +0x440
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/distribution.(*v2Puller).Pull(0xc421aa4540, 0x7fac2c18da68, 0xc421796300, 0x2ba6ae0, 0xc424306600, 0x1d4347c, 0x5, 0x2b950e0, 0xc421aa4540)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/distribution/pull_v2.go:73 +0x276
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/distribution.Pull(0x7fac2c18da68, 0xc421796300, 0x2ba6ae0, 0xc424306600, 0xc421a0b4a0, 0xc421bbea20, 0xc42183d8c0)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/distribution/pull.go:123 +0x548
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/daemon.(*Daemon).pullImageWithReference(0xc4201cc000, 0x7fac2c18da68, 0xc421796300, 0x2ba6ae0, 0xc424306600, 0x1d4347c, 0x5, 0xc420a03ad0, 0xc42469dd50, 0x2b98d60, ...)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/daemon/image_pull.go:84 +0x436
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/daemon.(*Daemon).PullImage(0xc4201cc000, 0x7fac2c18da68, 0xc421796180, 0xc424554ba0, 0x1e, 0x0, 0x0, 0x1d4347c, 0x5, 0xc420a03ad0, ...)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/daemon/image_pull.go:46 +0x14c
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: github.com/docker/docker/daemon/cluster/executor/container.(*containerAdapter).pullImage.func1(0xc421932c30, 0x7fac2c18da68, 0xc421796180, 0xc420a03ad0, 0xc42469dd50, 0xc4214fe9d0)
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/daemon/cluster/executor/container/adapter.go:95 +0xdd
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: created by github.com/docker/docker/daemon/cluster/executor/container.(*containerAdapter).pullImage
Apr 23 18:23:27 youdata01.deppon.com.cn dockerd[4810]: /go/src/github.com/docker/docker/daemon/cluster/executor/container/adapter.go:91 +0x2a2
Apr 23 18:23:27 youdata01.deppon.com.cn systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 23 18:23:27 youdata01.deppon.com.cn systemd[1]: Unit docker.service entered failed state.
Apr 23 18:23:27 youdata01.deppon.com.cn systemd[1]: docker.service failed.
Apr 23 18:24:41 youdata01.deppon.com.cn systemd[1]: Started Docker Daemon.
Apr 23 18:24:41 youdata01.deppon.com.cn systemd[1]: Starting Docker Daemon...

**Comment by thaJeztah** [comment]
```
Docker version: 17
Centos version: 7.4
```

Please note that Docker 17.xx versions have reached EOL a few years back, and CentOS uses a rolling release model, which means that 7.4 reached EOL when CentOS 7.5 was released. Docker 17.xx versions are no longer maintained, and have known vulnerabilities, so I would highly recommend updating to a current version of docker (19.03.x at time of writing).


As to the problem;

```
23T18:23:27.661786170+08:00" level=info msg="Attempting next endpoint for pull after error: Get https://localhost/v2/: http: server gave HTTP response to HTTPS client"
```

It looks like you're using a custom registry, which doesn't have TLS enabled, and doesn't return a proper response, which leads to a panic in the daemon; `panic: no ':' separator in digest ""`.

That looks to be a problem in your setup  / configuration of your registry (or perhaps a proxy that's configured).

Also note that this issue tracker is intended for reporting issues with the documentation, not the software itself.

I'm closing this issue because of the above, but feel free to continue the conversation
