### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by jiejiiie** [docker/docker.github.io#10692]
[]() https://docs.docker.com/get-docker/install/linux/ubuntu/

**Comment by thaJeztah** [comment]
Thanks for reporting; this should be fixed by https://github.com/docker/docker.github.io/pull/10691 (which will be published on docs.docker.com soon)

Meanwhile, the correct URL is https://docs.docker.com/engine/install/ or https://docs.docker.com/engine/install/ubuntu/ (for ubuntu)
