### ISSUE TITLE
"Sorry, we can't find that page" on the website, get docker section

### ISSUE THREAD

**Issue by denisix** [docker/docker.github.io#10690]
### Problem description

- The following link is broken, shows "Sorry, we can't find that page":
https://docs.docker.com/get-docker/engine/install/

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/get-docker/engine/install/

### Suggestions for a fix

- I'm not sure, but looks like it should point to the following URL:
https://docs.docker.com/engine/install/#server

**Comment by thaJeztah** [comment]
Thanks for reporting; we removed some code recently that tried to "fix" broken links, and these seem to be ones that were broken (and no longer "fixed" when viewing the page);

opening a PR
