### ISSUE TITLE
Problems installing Docker

### ISSUE THREAD

**Issue by awsBuildServices** [docker/docker.github.io#10694]
### Problem description

Cannot install docker on Linux i get the error: 
E: The repository 'https://download.docker.com/linux/ubuntu focal Release' does not have a Release file.

Also this page gets a can't find the page message:
https://docs.docker.com/get-docker/engine/install/

**Comment by thaJeztah** [comment]
Thanks for reporting; this should be fixed by https://github.com/docker/docker.github.io/pull/10691 (which will be published on docs.docker.com soon)

Meanwhile, the correct URL is https://docs.docker.com/engine/install/ or https://docs.docker.com/engine/install/ubuntu/ (for ubuntu)

**Comment by awsBuildServices** [comment]
root@ip-172-16-0-76:/var/discourse# sudo apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Unable to locate package docker-ce-cli
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'

**Comment by thaJeztah** [comment]
What distribution and version are you installing on?

**Comment by thaJeztah** [comment]
Oh, you're trying to install on Focal; there's no packages yet for Focal, those will arrive with the upcoming 20.xx release of Docker; in the meantime you may be able to install the packages for Ubuntu 18.04 (bionic)

**Comment by awsBuildServices** [comment]
Yeah thanks managed to update my repo to point at the right version. Not sure what happened there.

Thanks for the super support!
