### ISSUE TITLE
need ubuntu20.04 focal

### ISSUE THREAD

**Issue by GlenLiu-2432** [docker/docker.github.io#10706]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

there is no repository for ubuntu20.04 focal

**Comment by rogierlommers** [comment]
Double: https://github.com/docker/docker.github.io/issues/10703

**Comment by thaJeztah** [comment]
Packages for ubuntu 20.04 should be available now

**Comment by rogierlommers** [comment]
yeah, but the official documentation is not yet updated. (https://docs.docker.com/engine/install/ubuntu/)

**Comment by thaJeztah** [comment]
Ah, good point; I think there was a branch somewhere to update it, but it may have dropped of my list 🤔. Let me have a quick look if I still have that branch, or otherwise create a new one and push a PR.

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/10944
