### ISSUE TITLE
Ubuntu 20.04 not supported

### ISSUE THREAD

**Issue by kxxoling** [docker/docker.github.io#10703]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

Since 20.04 LTS is released, when would docker-ce updated to support it?

**Comment by matifali** [comment]
Have you tried installing on 20.04?

**Comment by kxxoling** [comment]
> Have you tried installing on 20.04?

Of course, and `404 NOT Found` returned every time. And there should exists a folder named `focal` in at [this page](https://download.docker.com/linux/ubuntu/dists/) if docker-ce for 20.04 is ready.

**Comment by codecat** [comment]
Waiting for this myself as well. Really unsure where to discuss this, but at least I saw this github issue I suppose?

**Comment by rogierlommers** [comment]
Here is the same question, including the workaround to use bionic repo.
https://askubuntu.com/a/1230190/869999

Would love to have an official focal repo though.

**Comment by matifali** [comment]
For a workaround, you can install docker using a single command

`sudo apt install docker-compose`

**Comment by kxxoling** [comment]
> For a workaround, you can install docker using a single command
> 
> `sudo apt install docker-compose`

Actually, that's not what I need. I've installed docker-compose from pip3, which has no docker engine included. I know I can use docker.io instead for now, but I prefer an docker offical release.

**Comment by codecat** [comment]
> Here is the same question, including the workaround to use bionic repo.

This seems like a dangerous workaround to me, I'm not sure if there are any implications of using something designed for a completely different version of Ubuntu.

Also as a sidenote, the `docker.io` package does work, and is in fact up-to-date, so I'm using it for now combined with `docker-compose` installed using `sudo -H pip3 install docker-compose`.

**Comment by matifali** [comment]
> > Here is the same question, including the workaround to use bionic repo.
> 
> This seems like a dangerous workaround to me, I'm not sure if there are any implications of using something designed for a completely different version of Ubuntu.
> 
> Also as a sidenote, the `docker.io` package does work, and is in fact up-to-date, so I'm using it for now combined with `docker-compose` installed using `sudo -H pip3 install docker-compose`.

You can also try this with apt. https://github.com/docker/docker.github.io/issues/10703#issuecomment-619514815

**Comment by codecat** [comment]
> You can also try this with apt. [#10703 (comment)](https://github.com/docker/docker.github.io/issues/10703#issuecomment-619514815)

I saw your comment, but I've had problems with this on 18.04 (strange random errors), so I don't like using the Ubuntu-provided `docker-compose` package.

**Comment by rogierlommers** [comment]
Hey @thaJeztah , I saw you as a PRO here. Can you say something about how we can fix this? Ubuntu 20.04 LTS is released now and I think it would be good to have Docker docs be up to date. Agree?

**Comment by matifali** [comment]
> > You can also try this with apt. [#10703 (comment)](https://github.com/docker/docker.github.io/issues/10703#issuecomment-619514815)
> 
> I saw your comment, but I've had problems with this on 18.04 (strange random errors), so I don't like using the Ubuntu-provided `docker-compose` package.

Can you point out what strange issues you are facing?  It is working fine for me.

**Comment by codecat** [comment]
> Can you point out what strange issues you are facing? It is working fine for me.

When running `docker build` while Ubuntu's `docker-compose` was installed, I would encounter this bug: https://bugs.launchpad.net/ubuntu/+source/golang-github-docker-docker-credential-helpers/+bug/1813003

Simply running `apt remove docker-compose` would fix the problem entirely. Then if I installed it from `pip3`, everything worked fine as expected.

**Comment by rogierlommers** [comment]
So no official Docker statement on this issue?

**Comment by codecat** [comment]
> So no official Docker statement on this issue?

There is - see my comment earlier in this thread. Ubuntu 20.04 support is coming with Docker version 20.xx.

**Comment by akharitonov** [comment]
> > So no official Docker statement on this issue?
> 
> There is - see my comment earlier in this thread. Ubuntu 20.04 support is coming with Docker version 20.xx.

What makes you think they're not going to support Ubuntu focal for almost a year?

We're on Docker 19.03 and their stable releases are made quarterly (.03, .06, .09, .12). 
So hopefully we'll get focal supported with 19.06, meaning June.

**Comment by codecat** [comment]
> What makes you think they're not going to support Ubuntu focal for almost a year?
> 
> We're on Docker 19.03 and their stable releases are made quarterly (.03, .06, .09, .12).
> So hopefully we'll get focal supported with 19.06, meaning June.

I've been trying to find the exact comment I read on this, but can't find it anymore now. Perhaps I misread it at the time or it's just hidden away in some other thread. :/

**Comment by joho** [comment]
@codecat are you thinking of https://github.com/docker/docker-ce-packaging/pull/443#issuecomment-618340415

**Comment by codecat** [comment]
Yes! That's the one. I'm not sure if I interpreted it correctly.

**Comment by akharitonov** [comment]
Focal package is now available: https://download.docker.com/linux/ubuntu/dists/focal/

**Comment by thaJeztah** [comment]
Only containerd at this moment; engine packages should go live on Monday

**Comment by andradei** [comment]
Are we there? I have the eoan package installed, but don't know how to tell whether focal is finally available.

Thanks.

**Comment by rogierlommers** [comment]
I'm waiting until [this page](https://docs.docker.com/engine/install/ubuntu/) has been updated for 20.04.

**Comment by andradei** [comment]
Good idea! Provided all caches get refreshed soon.

**Comment by ciklista** [comment]
appears to be live now.

**Comment by StefanScherer** [comment]
Docker 19.03.9 is released, with packages for Ubuntu Focal Fossa.
Thanks for you patience. Enjoy!

**Comment by bogdanvlviv** [comment]
Thank you! :bow:

**Comment by TBERB** [comment]
I'm trying right now, and I am getting the error. Running Xubuntu Focal Fossa, all updated.
