### ISSUE TITLE
Link Broken in docker docs

### ISSUE THREAD

**Issue by abhishekPhukan** [docker/docker.github.io#10707]
The link "Flags related to service restarts" in page https://docs.docker.com/config/containers/start-containers-automatically/ is broken.  Takes me to page https://docs.docker.com/config/engine/reference/commandline/service_create/ which does not exist.

**Comment by thaJeztah** [comment]
thanks for reporting; I opened https://github.com/docker/docker.github.io/pull/10726 to fix the link

**Comment by abhishekPhukan** [comment]
Seems to be fixed. Thanks
