### ISSUE TITLE
Option types link doesn't work

### ISSUE THREAD

**Issue by PatilSac** [docker/docker.github.io#10710]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/run/

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/engine/reference/run/commandline/cli.md#option-types

- Other: Link for Option types for docker run command. Line in article "To learn how to interpret the types of [OPTIONS]"

### Project version(s) affected
Docker v19.03 documentation

**Comment by thaJeztah** [comment]
Thanks for reporting; I opened https://github.com/docker/cli/pull/2480 and https://github.com/docker/cli/pull/2481 to fix the links

**Comment by thaJeztah** [comment]
https://github.com/docker/cli/pull/2481 was merged, and will be published on docs.docker.com soon (probably tomorrow); I'll go ahead and close this ticket
