### ISSUE TITLE
missing needed parameter

### ISSUE THREAD

**Issue by Alekisan** [docker/docker.github.io#10721]
File: [config/daemon/ipv6.md](https://docs.docker.com/config/daemon/ipv6/)

as it stands, if you only do what it says here it will crash your demon on reboot.

it is missing the 
"fixed-cidr-v6": "2001:db8:1::/64"
or something there abouts.. This but if info is all over the internet but you guys don't have it here.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It appears fixed in https://github.com/docker/docker.github.io/commit/1b319c30a57334d82096bc4e1cabfab3a8b6dda1
