### ISSUE TITLE
Feedback for: engine/swarm/admin_guide.md

### ISSUE THREAD

**Issue by pascalandy** [docker/docker.github.io#1072]
File: [engine/swarm/admin_guide.md](https://docs.docker.com/engine/swarm/admin_guide/)

On this section: https://docs.docker.com/engine/swarm/admin_guide/#back-up-the-swarm-state

It looks like we can backup a docker swarm cluster easily:
`cp -r /var/lib/docker/swarm/raft /tmp/backup && tar ... && scp ....`

#### Here are my questions and my assumptions:

1) Does the backup process care about online vs offline backups? I assume we can do a hot backup
2) Can I simply cp -r or rsync that folder without worrying about the integrity of the backup? I assume yes.
3) Do I need to disable the swarm cluster to ensure an accurate backup? I assume it's no.
4) Can I ensure that the swarm state is consistent at backup time? No idea
5) Does the backup is reliable no matter which manager it's made from ? Or should we do it from the leader node ?

Thanks!

**Comment by daviddyball** [comment]
Another thing to add would be documentation on the process required for restore in case of cluster failure. The documentation is very light on this portion of the recovery, with the exception of saying "it's as easy as `cp -r .....`"

**Comment by pascalandy** [comment]
This is what I see. I find it a bit weird.

```
root@N01-PAR1:/var/lib/docker/swarm/raft# tree
.
├── snap
└── wal
    └── 0000000000000000-0000000000000000.wal

2 directories, 1 file
root@N01-PAR1:/var/lib/docker/swarm/raft# ls -la

drwx------ 4 root root 4096 Jan 12 15:11 .
drwx------ 5 root root 4096 Jan 12 15:11 ..
drwx------ 2 root root 4096 Jan 12 15:11 snap
drwx------ 2 root root 4096 Jan 12 15:11 wal

root@N01-PAR1:/var/lib/docker/swarm/raft# ls -la
drwx------ 4 root root 4096 Jan 12 15:11 .
drwx------ 5 root root 4096 Jan 12 15:11 ..
drwx------ 2 root root 4096 Jan 12 15:11 snap
drwx------ 2 root root 4096 Jan 12 15:11 wal

root@N01-PAR1:/var/lib/docker/swarm/raft# cd wal/
root@N01-PAR1:/var/lib/docker/swarm/raft/wal# ls
0000000000000000-0000000000000000.wal

root@N01-PAR1:/var/lib/docker/swarm/raft/wal# ls -la
drwx------ 2 root root    4096 Jan 12 15:11 .
drwx------ 4 root root    4096 Jan 12 15:11 ..
-rw------- 1 root root 1641838 Jan 13 15:16 0000000000000000-0000000000000000.wal
```

**Comment by mstanleyjones** [comment]
@stevvooe @aaronlehmann do you have any info about this topic?

**Comment by aaronlehmann** [comment]
> Does the backup process care about online vs offline backups? I assume we can do a hot backup
> Can I simply cp -r or rsync that folder without worrying about the integrity of the backup? I assume yes.
> Do I need to disable the swarm cluster to ensure an accurate backup? I assume it's no.
> Can I ensure that the swarm state is consistent at backup time? No idea

Hmm, I think in most cases it should work fine, but if the file is changing underneath a tool like `cp` or `rsync`, that may cause problems. I think it's best to do it offline, if possible.

> Does the backup is reliable no matter which manager it's made from ? Or should we do it from the leader node ?

This should not matter. Theoretically the other nodes can be slightly behind, but it shouldn't be an issue.

**Comment by pascalandy** [comment]
Glad to see traction over this. I [googled](https://www.google.ca/search?q=restaure+your+docker+swarm+cluster&oq=restaure+your+docker+swarm+cluster&aqs=chrome..69i57.7408j0j7&sourceid=chrome&ie=UTF-8#safe=off&q=restore+your+docker+swarm+cluster) it many times and now post/blogs it doing the hard work of crashing a cluster to restore it. 

So important for serious orchestration setup. Thanks for caring :)

**Comment by dogtail9** [comment]
It would be great if Docker provided the commands to backup and restore of a swarm. Like the UCP and DTR do.

Example:
docker swarm backup --passphrase "secret"> /tmp/backup.tar
docker swarm restore --passphrase "secret" </tmp/backup.tar

Or package the tools in their own swarm admin image:
docker run --rm -i --name swarmtools -v /var/run/docker.sock:/var/run/docker.sock docker/swarmtools backup --passphrase "secret"> /tmp/backup.tar
docker run --rm -i --name swarmtools -v /var/run/docker.sock:/var/run/docker.sock docker/swarmtools restore --passphrase "secret" </tmp/backup.tar

It does not really matter. Make it easy to maintain a Docker swarm.

**Comment by mstanleyjones** [comment]
@pascalandy @dogtail9 I just merged #1566 which addresses this. Thanks!

**Comment by pascalandy** [comment]
Thanks great!! Many thanks!

**Comment by xophere** [comment]
This is a basic operational requirement.  You need a way to rebuild a swarm from backup.  Someone needs to specify this.  This https://docs.docker.com/engine/swarm/admin_guide/#back-up-the-swarm is just an after thought.  Yes it will work but it isn't a modern or reasonable expectation.

**Comment by mistyhacks** [comment]
Hi there, you're in the docs repository now. If you would like Moby to support more features relating to backing up swarms, please file an issue there: https://github.com/moby/moby

I worked closely with the swarm engineering team to write the backup content that exists now. It is the truth of what the technology currently supports and how it works.

**Comment by xophere** [comment]
Oh darn.  Sorry.   My error.  That make sense.  And the documentation is clear.  Just the functionality it wanting.

**Comment by mistyhacks** [comment]
I hope you do open the PR upstream and get the functionality that you feel is missing! Thanks for helping us improve.
