### ISSUE TITLE
Docker Release notes don't list engine API version

### ISSUE THREAD

**Issue by dadrian** [docker/docker.github.io#10733]
File: [engine/release-notes/index.md](https://docs.docker.com/engine/release-notes/)

It'd be nice if the Daemon API version was listed for each release, so you could map API version number to release, e.g. answer the question "What is the minimum release I need to install to have engine API 1.39?"

**Comment by thaJeztah** [comment]
You can also see an overview in the [API version matrix](https://docs.docker.com/engine/api/#api-version-matrix)
