### ISSUE TITLE
`docker image ls` and `docker image prune` don't accept the same filters

### ISSUE THREAD

**Issue by gchappell99** [docker/docker.github.io#10730]
File: [engine/reference/commandline/image_prune.md](https://docs.docker.com/engine/reference/commandline/image_prune/)

> Predicting what will be removed
> 
> If you are using positive filtering (testing for the existence of a label or that a label has a specific value), you can use docker image ls with the same filtering syntax to see which images match your filter.

This statement appears to be very untrue/misleading...`docker image ls` does not accept the `until` filter to predict by timestamp, and `docker image prune` does not accept the `reference` filter to act on a predicted list by repository...

```
[root@docker ~]# docker image ls --filter "reference=myrepo:5000/*" | wc -l
641
[root@docker ~]# docker image prune --filter "reference=myrepo:5000/*"
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N] y
Error response from daemon: Invalid filter 'reference'
```

```
[root@docker ~]# docker image ls --filter "until=1h"
Error response from daemon: Invalid filter 'until'
```

```
[root@docker ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by thaJeztah** [comment]
The note looks to describe filtering on `label` specifically. I can see where it can be confusing (but also would like to prevent the note to become overly long); do you have suggestions for wording that would make this more apparent for you?

(also related discussion about differences in filtering; https://github.com/docker/cli/issues/625)

**Comment by gchappell99** [comment]
I don't right now - but I can explain what I'm trying to achieve which I think would be a pretty common goal to see if that helps stir up some ideas.

This server runs Docker for two purposes - primarily CI testing with first-party images from our own repo, but it also holds some "permanent" services (for example a third-party database image with data required for those tests). The third-party images may not be in active use at the time so may be considered dangling.

My goal is to be able to clean up both by repository AND by date (first-party AND older than 1w). `docker image prune` seems to be able to handle the timestamp issue, but it would also delete third-party images. `docker image ls` can provide me with a list of only first-party image IDs, but can't filter them by age.

If what you say about filtering on label specifically is correct, then maybe you could document the equivalent format for being able to use this with `docker image ls` and treat filtering by repository as (probably) one of the common use cases for doing this? I tried `docker image ls --filter "label=reference=myrepo:5000/*"` and got no results, so the filter is accepted but I'm clearly matching on the wrong label. There are no custom labels assigned to these first-party images, but I'm assuming there's some kind of filter that can be applied to match the repository as a "system" label?

**Comment by thaJeztah** [comment]
Yes, the label is filtering on the _labels_ that are present on the image, not the tag/image reference (and it doesn't support wildcards).

If your image builds are automated, you could consider setting labels on those images during build;

```bash
docker build -t myrepo:5000/foo:latest --label=ci.job=foo .
docker build -t myrepo:5000/bar:latest --label=ci.job=bar .
docker build -t myrepo:5000/baz:latest --label=ci.job=baz .
```

To prune all images with label `ci.job=foo`:

```bash
docker image prune -a -f --filter=label=ci.job=foo

# Deleted Images:
# deleted: sha256:7c4e763aa5bc5807e846ed6d39e1cbf08919577dd2c6d76c70c65ae1ff712068
# untagged: myrepo:5000/foo:latest
# deleted: sha256:29d8506132f9418f8fac33c7a0fa4f39472bf5c63f22d5a2422611e388e09bf7
# 
# Total reclaimed space: 0B
```

To prune all images with label `ci.job` (irregardless the value of that label);

```bash
docker image prune -a -f --filter=label=ci.job
# Deleted Images:
# untagged: myrepo:5000/baz:latest
# deleted:  sha256:9fe43859c153d708314a669ed39562cf158f0260ef8e80085648aa956cbb5d50
# untagged: myrepo:5000/bar:latest
# deleted: sha256:3c5ff6a0f70d9e54da3dcfc8d74194a3c989dca37a66970eb419573f1926f5f7
```
