### ISSUE TITLE
Stable release notes page leads to 404

### ISSUE THREAD

**Issue by dickinse** [docker/docker.github.io#10734]
File: [404.md](https://docs.docker.com/404.html)

https://docs.docker.com/docker-for-mac/edge-release-notes/ 
Click on stable release in the first paragraph

**Comment by thaJeztah** [comment]
Thanks for reporting, I'll open a pull-request to fix those links. In the meantime, you should be able to find the right link in the left-hand navigation 👍

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/10735
