### ISSUE TITLE
Link don't work: Docker Engine - Enterprise for Windows Server

### ISSUE THREAD

**Issue by user18x** [docker/docker.github.io#10731]
### Problem description

Link in https://docs.docker.com/ee/supported-platforms/#where-to-go-next 

> Install Docker Engine - Enterprise for Windows Server

don't work

### Problem location
https://docs.docker.com/ee/docker-ee/windows/docker-ee.md

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
