### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Tarvinder91** [docker/docker.github.io#10737]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/builder/#buildkit

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: Please search for the text "see using the -P flag." on the document link provided above. The link embedded in this text is broken.

**Comment by thaJeztah** [comment]
Thanks for reporting; I opened https://github.com/docker/cli/pull/2484 to fix
