### ISSUE TITLE
WSL integration doesn't include buildx

### ISSUE THREAD

**Issue by Maddog2050** [docker/docker.github.io#10743]
### Problem description

Docker Desktop for Windows doesn't contain the buildx command for WSL2 when using the WSL integration.

### Problem location

WSL Integration

### Project version(s) affected

Docker Desktop for Windows v2.3.0.1 (edge)

### Suggestions for a fix

Please include the buildx command for use when using the "WSL integration"

**Comment by StefanScherer** [comment]
Thanks @Maddog2050 for reporting this.

Indeed, inside a WSL distro the WSL integration does not set the Docker CLI experimental configuration at the moment. The corresponding Docker Desktop setting only works in a Windows terminal like PowerShell and for the (old) Hyper-V backend.

You can use the experimental CLI features by setting a variable running the Docker CLI. The following command gives you the buildx help:

    DOCKER_CLI_EXPERIMENTAL=enabled docker buildx help

But you can enable the experimental setting permanently in your WSL distro just the same way a Linux user would do it.

As mentioned in https://docs.docker.com/buildx/working-with-buildx/:
> To enable experimental features in the Docker CLI, edit the `config.json` file and set `experimental` to `enabled`.

In https://docs.docker.com/engine/reference/commandline/cli/#experimental-features you can also see an example of a `config.json`.

In a fresh WSL distro you could use the following to commands to enable the experimental CLI features permanently.

1.  Create a folder `.docker` in your WSL home directory.
    ```
    mkdir -p $HOME/.docker
    ```

2.  Create the `~/.docker/config.json` config file if it does not exist.
    ```
    test -f $HOME/.docker/config.json || echo '{ "experimental": "enabled" }' > $HOME/.docker/config.json
    ```

/cc @usha-mandya we probably need something like this in our WSL docs / FAQ.

**Comment by StefanScherer** [comment]
Closing this. We are working on a synchronization of the experimental flag from the settings UI.
