### ISSUE TITLE
Please include Fedora 32-compatible instructions(if such system is supported) to docker engine installation documentation

### ISSUE THREAD

**Issue by ilchub** [docker/docker.github.io#10744]
File: [engine/install/fedora.md](https://docs.docker.com/engine/install/fedora/)
Please update docs to match repositories and packages that will work on Fedora 32. DNF(YUM) docker repository refuses to work after changing fedora release number from 31 to 32 due to inexistence of packages for Fedora 32.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As this issue is old, it no longer applies to the currently supported versions.
