### ISSUE TITLE
 Application Templates and App Designer Link on www.docker.com

### ISSUE THREAD

**Issue by FireMMDC** [docker/docker.github.io#10755]
### Problem description

Attempted to access a link on the docker.com page, the link to "Application Templates and App Designer"'s learn more attempted to send me to https://docs.docker.com/app-template/working-with-template/ which is missing.

### Problem location

- I saw a problem on the following URL: https://www.docker.com/products/docker-desktop

### Suggestions for a fix

Re-add the resource or update the content on https://www.docker.com/products/docker-desktop

**Comment by thaJeztah** [comment]
@nebuk89 @usha-mandya ptal

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as it appears that the issue was resolved. If the issue still persists, please let us know.
