### ISSUE TITLE
Ubuntu install broken link

### ISSUE THREAD

**Issue by NukeManDan** [docker/docker.github.io#10750]
### Problem description

Broken link to Ubuntu install instructions: https://docs.docker.com/engine/install/ubuntu.md

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ee/docker-ee/ubuntu/
Link is in the `! Important` header note

**Comment by thaJeztah** [comment]
Docker Enterprise docs have been moved to Mirantis. If there's still an issue, could you report this over there? https://docs.mirantis.com
