### ISSUE TITLE
Container is able to perform all file system operations, except removing directories

### ISSUE THREAD

**Issue by Maryannah** [docker/docker.github.io#10782]
### Problem description

I am using a container to build a cordova application, which runs on Ubuntu 18.04. 

I run the container in interactive mode and run .sh scripts that I wrote, and I use a volume to add my files to the container. 

if I run the following commands

```bash
mkdir www
cd www
touch test.js
mkdir assets
cd assets
touch img.png
```

It all works well, everything is created on the host. 

Then I run 

```bash
rm -rf www/*
rm -rf www
```

And from there, the files are deleted, but the directories are not. 

Worse, when I try to remove them from the host, they can't be deleted, Windows require privileges (and giving them doesn't work) and Ubuntu WSL says "directory not empty" (although it is and I run the command with -rf). I have to restart my computer so that I can safely delete this folder (from the host, the container still doesn't want to)

I have chmoded 777 all of my project files to be sure, but the error still persists. 

# Other

I am running on a brand new operating system (factory reset two weeks ago) and Docker was the first thing I installed. 

I am running on Windows 1903 (OS Build 18362.778), I have installed the WSL Ubuntu "focal" 20.04 and used `apt install docker.io` (19.03.8) to install docker. I have added the docker user group and myself in it, 

I also did everything necessary to be able to run docker from the WSL (TLS and such) and it works great, it's just that `rm` that is messed up. 

I don't really know what other information to provide, so feel free to ask for it !

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If you're looking for support, you can try the Docker Community Forums. If you believe this is a bug, please create an issue the the application repo. If there is an issue in the documentation, please let us know.
