### ISSUE TITLE
About --opt=encrypted /// Feedback for: engine/userguide/networking/overlay-security-model.md

### ISSUE THREAD

**Issue by pascalandy** [docker/docker.github.io#1078]
File: [engine/userguide/networking/overlay-security-model.md](https://docs.docker.com/engine/userguide/networking/overlay-security-model/)

### I'm creating three networks:

```
NETWORK_GRP=(NET_FRONT NET_BACK NET_MONIT)

export MIN=0
export MAX=2
for ACTION in $(seq $MIN $MAX); do
	docker network create --driver=overlay --opt=encrypted --subnet 10.0.1$ACTION.0/24 ${NETWORK_GRP[$ACTION]} && echo
	echo -e "$PIK_GREEN Freshly created - overlay ${NETWORK_GRP[$ACTION]}" && echo
	fct_count1
done
```

#### Let's inspect NETW_front:

```
[
    {
        "Name": "NETW_front",
        "Id": "6iqeqa6hx4do6xwgxxw3dk9q9",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.10.0/24",
                    "Gateway": "10.0.10.1"
                }
            ]
        },
        "Internal": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "257",
            "encrypted": ""
        },
        "Labels": null
    }
]
```

#### You see: `"encrypted": ""`
This guys is empty. I don't thing it's normal... What should we see here?

Cheers!
https://twitter.com/_pascalandy

---

Pikwi >  ### Output of docker version:

Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

My Swarm have 3 nodes.

**Comment by mstanleyjones** [comment]
See https://docs.docker.com/engine/userguide/networking/overlay-security-model/. It's empty because your syntax is not quite right. It's a Boolean option, and it should be `--opt encrypted` or `--opt encrypted=true`. Notice the space. Each option is a key-value pair of its own.

**Comment by pascalandy** [comment]
Yes make sense! Thank you
