### ISSUE TITLE
Request docs change - What are the options for the --filter in container ls

### ISSUE THREAD

**Issue by RoelTiny** [docker/docker.github.io#10788]
File: [engine/reference/commandline/container_ls.md](https://docs.docker.com/engine/reference/commandline/container_ls/)

To filter containers by image apparently I have to use 'ancestor' which works perfectly but i could not find in the docs and had to google for.

I know of the following options: 
name=string             - works with partial similarity so if name is 'alice' searching name=al will return that container
ancestor=string       - only works with complete match so image is alice, ancestor=al won't return this container, have to search ancestor=alice
id=string           - also works with partial similarity

Are there others?

Thx in advance.

**Comment by thaJeztah** [comment]
Thanks for reporting; the details can be found in the `docker ps` reference page (`docker ps` is a short-hand for `docker container ls`); we're working on unifying / redirecting those pages, but that work isn't done yet (see https://github.com/docker/docker.github.io/pull/10471)


You can find the docs here; https://docs.docker.com/engine/reference/commandline/ps/#filtering

**Comment by RoelTiny** [comment]
That response was surprisingly fast. 

Thank you for your response and pointing me in the right direction.
