### ISSUE TITLE
Additional info in the IPv6 page

### ISSUE THREAD

**Issue by duncs** [docker/docker.github.io#10790]
File: [config/daemon/ipv6.md](https://docs.docker.com/config/daemon/ipv6/)

Need to specify 

{
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80"
}

to allow the docker daemon to restart (if you only need IPv6 work and not communicate with anything, such as in package builds of IPv6 usable software)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It appears fixed in https://github.com/docker/docker.github.io/commit/1b319c30a57334d82096bc4e1cabfab3a8b6dda1
