### ISSUE TITLE
Need setup docker from win10 home

### ISSUE THREAD

**Issue by newcido** [docker/docker.github.io#10792]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by BboyAkers** [comment]
You have to have Win10 Pro/Enterprise
It says it here: https://docs.docker.com/docker-for-windows/install/
Windows 10 64-bit: Pro, Enterprise, or Education (Build 15063 or later).

It's because of the Hyper-V requirement.

**Comment by usha-mandya** [comment]
@newcido You can find instructions on installing Docker Desktop on Windows 10 Home here - https://docs.docker.com/docker-for-windows/install-windows-home/.
