### ISSUE TITLE
https://docs.docker.com/docker-for-windows/wsl/ for details

### ISSUE THREAD

**Issue by himanshumunjal** [docker/docker.github.io#10802]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by thaJeztah** [comment]
Thanks for reporting; the correct URL is now https://docs.docker.com/desktop/windows/wsl/

I found where the "faulty" URL is coming from; more details in https://github.com/docker/docker.github.io/pull/13382.
