### ISSUE TITLE
docker error CTC1015 width vs2019

### ISSUE THREAD

**Issue by ruby0602** [docker/docker.github.io#10825]
using vs2019 to launch linux docker，give the error message
 docker: Error response from daemon: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled"}
I has already added Fileshareing directory，how can I solve the error？thanks

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
If the information at https://docs.docker.com/desktop/windows/#resources does not help solve the issue, please try to get support for your specific environment in the Docker Community Slack or forums.
- https://dockercommunity.slack.com/
- https://forums.docker.com/
