### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by robbiejackson** [docker/docker.github.io#10822]
### Problem description

Broken link on this page:
https://docs.docker.com/docker-for-windows/install-windows-home/
 
to https://docs.docker.com/wsl-tech-preview.md

### Problem location
At end of first section, where it says
For detailed information about WSL 2, see Docker Desktop WSL 2 backend

**Comment by mr3** [comment]
It has been fixed. see: d1c269e#diff-25d8ac8a0c25a3a16a89b3a0fcc20eff

The fixed link is : https://docs.docker.com/docker-for-windows/wsl/

**Comment by thaJeztah** [comment]
Thanks; yes this should be fixed
