### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by beaconcross** [docker/docker.github.io#10836]
### Problem description
In the page mentioned below on the following text "For detailed information about WSL 2, see Docker Desktop WSL 2 backend" the link is dead

### Problem location
- I saw a problem on the following URL: https://docs.docker.com/docker-for-windows/install-windows-home/

**Comment by mr3** [comment]
It has been fixed. see: https://github.com/docker/docker.github.io/commit/d1c269e58d74bf34823e2fc1cafcda6d7720b867#diff-25d8ac8a0c25a3a16a89b3a0fcc20eff

**Comment by thaJeztah** [comment]
Thanks! Yes, looks to be fixed
