### ISSUE TITLE
Stable doesn't work on windows 10

### ISSUE THREAD

**Issue by cgthayer** [docker/docker.github.io#10832]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)

I installed on a fresh system with hyper-v enabled, but it hangs.  I had to install the "edge" release which brings up the engine, but docker desktop doesn't launch.

It looks like the accepted way now is to use WSL (windows subsystem for linux) but that doesn't appear to be documented here.

Thanks for any clarifications.

**Comment by usha-mandya** [comment]
@cgthayer Thank you for the feedback. If you have a system that supports WSL 2, the Docker Desktop installer prompts you to enable WSL during installation. You can find more information about WSL 2 installation at https://docs.docker.com/docker-for-windows/wsl/#prerequisites.

If you are looking to install a Stable version of Docker Desktop, could you try installing using the following link and let me know how you get on? 

https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe

**Comment by craig-osterhout** [comment]
Closing this issue as stale. If the issue still persists, please provide the feedback requested in the previous comment.
