### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by binascohub** [docker/docker.github.io#10834]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by thaJeztah** [comment]
Your description doesn't mention which link (and on which page); did you open this accidentally, or could you provide more details?

**Comment by usha-mandya** [comment]
Hello @binascohub There's isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
