### ISSUE TITLE
Invalid link in dockerd documentation

### ISSUE THREAD

**Issue by izabelabee** [docker/docker.github.io#10846]
### Problem description

I was reading Docker Daemon CLI documentation, the section Example, subsection Daemon Socket Option. In the fist paragraph of that subsection I have found invalid link to Docker Engine API.

Here is the documentation site where i found the fault:
https://docs.docker.com/engine/reference/commandline/dockerd/

### Problem location

- I saw a problem on the following URL: 
On this page:
https://docs.docker.com/engine/reference/commandline/dockerd/
I have found a link to this invalid location:
https://docs.docker.com/engine/reference/commandline/api/

- I couldn't find the information I wanted. I expected to find it near the following URL: 
Possibly this is the location where Docker Engine API should be forwarding https://docs.docker.com/engine/api/

- Other: <DETAILS>
NA

### Project version(s) affected
NA

### Suggestions for a fix
NA

**Comment by thaJeztah** [comment]
Thanks for reporting! I'll have a look 👍

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/2547 with a fix
