### ISSUE TITLE
Link in UCP install page leads to 404 page

### ISSUE THREAD

**Issue by asankov** [docker/docker.github.io#10857]
### Problem description
There is a link on this page https://docs.docker.com/ee/ucp/admin/install/ which leads to a 404 page.
The link is part of this excerpt:
>This runs the install command in interactive mode, so that you’re prompted for any necessary configuration values. To find what other options are available in the install command, including how to install UCP on a system with SELinux enabled, check the reference documentation.

The link point to https://docs.docker.com/reference/ucp/3.2/cli/install.md which shows the 404 page.

Deleting `install.md` shows a valid page - https://docs.docker.com/reference/ucp/3.2/cli/
but is not exactly what I need.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ee/ucp/admin/install/

### Suggestions for a fix

- Update the link to point to a valid page like https://docs.docker.com/reference/ucp/3.2/cli/ or another `install` specific one if there is such.

- Add the `install.md` file wherever is needed, so that https://docs.docker.com/reference/ucp/3.2/cli/install.md becomes a valid page.

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this here for that reason. Feel free to continue the conversation after I close.
