### ISSUE TITLE
"Edit this page" is 404

### ISSUE THREAD

**Issue by hwaterfall** [docker/docker.github.io#10864]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

Clicking the [Edit this page](https://github.com/docker/docker.github.io/edit/master/engine/reference/run.md) link that appears on the sidebar of the [Docker v19.03 run reference documentation](https://docs.docker.com/engine/reference/run/) leads to the error: **404: This not the web page you are looking for.**

**Comment by craig-osterhout** [comment]
The "Edit this page" link now redirects to the GitHub repo.
