### ISSUE TITLE
Missing Network Plugins API documentation

### ISSUE THREAD

**Issue by vmorris** [docker/docker.github.io#10863]
### Problem description

Missing page at https://docs.docker.com/engine/extend/plugins_network/plugin_api.md

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/extend/plugins_network/#write-a-network-plugin

### Suggestions for a fix

Resurrect the documentation for the API and correct the link from the `plugins_network` page.

**Comment by craig-osterhout** [comment]
Closing. The link on https://docs.docker.com/engine/extend/plugins_network/#write-a-network-plugin is now https://docs.docker.com/engine/extend/plugin_api/ . If there is still an issue, please let us know.
