### ISSUE TITLE
--rm=false documented incorrectly

### ISSUE THREAD

**Issue by hwaterfall** [docker/docker.github.io#10862]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

The Docker [v19.03 run reference documentation](https://docs.docker.com/engine/reference/run/#clean-up---rm) indicates:
> --rm=false: Automatically remove the container when it exits

I believe that it should indicate:

> --rm=true: Automatically remove the container when it exits

**Justification:**
Version: Docker version 19.03.8, build afacb8b
OS: macOS Catalina v10.15.4

1. Run a docker container w/ the option: **--rm=false**
2. Exit the container w/ **`<ctrl>d`**
3. Repeat the original run command

Result: Error message indicating that the container is already in use - i.e. it was not removed.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference
