### ISSUE TITLE
"Sorry, we can't find that page" for URL https://docs.docker.com/wsl-tech-preview.md

### ISSUE THREAD

**Issue by richard-grin** [docker/docker.github.io#10882]
### Problem description

In the page https://docs.docker.com/docker-for-windows/install-windows-home/, if I click on the link "see Docker Desktop WSL 2 backend", URL https://docs.docker.com/wsl-tech-preview.md, I receive the error "Sorry, we can't find that page".

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/docker-for-windows/install-windows-home/

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/wsl-tech-preview.md

- Other:

**Comment by StefanScherer** [comment]
Thanks @richard-grin for reporting this. Indeed, there is a typo that then links you to a non existing page. You should see this page instead: https://docs.docker.com/docker-for-windows/wsl/

We're working on a fix.
