### ISSUE TITLE
Datacenter Directories with no index

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#1089]
https://docs.docker.com/datacenter/dtr/2.1/reference
https://docs.docker.com/datacenter/dtr/2.1
https://docs.docker.com/datacenter/dtr
https://docs.docker.com/datacenter/install
https://docs.docker.com/datacenter/ucp/2.0/reference
https://docs.docker.com/datacenter/ucp/2.0
https://docs.docker.com/datacenter/ucp
https://docs.docker.com/datacenter

https://docs.docker.com/docker-trusted-registry/configure
https://docs.docker.com/docker-trusted-registry/high-availability
https://docs.docker.com/docker-trusted-registry/monitor-troubleshoot
https://docs.docker.com/docker-trusted-registry/repos-and-images
https://docs.docker.com/docker-trusted-registry/upgrade

https://docs.docker.com/ucp/access-ucp
https://docs.docker.com/ucp/applications
https://docs.docker.com/ucp/configuration
https://docs.docker.com/ucp/high-availability
https://docs.docker.com/ucp/installation
https://docs.docker.com/ucp/monitor
https://docs.docker.com/ucp/reference
https://docs.docker.com/ucp/user-management

**Comment by johndmulhausen** [comment]
Note: May be false positives in here; the use of `redirect_from` can create some of these directories. Thanks for having a look!

**Comment by JimGalasyn** [comment]
This may be fixed by the new `/enterprise` node IA.

**Comment by johndmulhausen** [comment]
Closing as irrelevant; the new IA we're forming should handle this as a byproduct.
