### ISSUE TITLE
Feedback for: machine/drivers/rackspace.md

### ISSUE THREAD

**Issue by patakijv** [docker/docker.github.io#109]
URL: machine/drivers/rackspace.md

I've tried using this example providing username, api-key, and region and it fails 

```
docker-machine create --driver rackspace --rackspace-username=XXXXXXXX --rackspace-api-key=XXXXXXXX --rackspace-region=DFW test-docker2

Running pre-create checks...
Creating machine...
(test-docker2) Creating machine...
Error creating machine: Error in driver during machine creation: Expected HTTP response code [201 202] when accessing [POST https://dfw.servers.api.rackspacecloud.com/v2/XXXXXXX/servers], but got 403 instead
403 Forbidden

Access was denied to this resource.

 Exactly 1 isolated network(s) must be attached  
```

The username I am using has full product access.

**Comment by londoncalling** [comment]
@nathanleclaire any ideas on this, or what I should do with it in terms of docs?

**Comment by nathanleclaire** [comment]
@londoncalling Not sure -- @patakijv this seems more an issue for the Machine repo. Can we move discussion there please?

**Comment by londoncalling** [comment]
Closing this issue, as I've created a new one on the `docker/machine/` repository per @nathanleclaire
