### ISSUE TITLE
Cloud directories with no index

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#1090]
https://docs.docker.com/docker-cloud/faq
https://docs.docker.com/docker-cloud/feature-reference
https://docs.docker.com/docker-cloud/getting-started/beginner
https://docs.docker.com/docker-cloud/getting-started/intermediate
https://docs.docker.com/docker-cloud/tutorials

**Comment by johndmulhausen** [comment]
Note: May be false positives in here; the use of `redirect_from` can create some of these directories. Thanks for having a look!

**Comment by sanscontext** [comment]
`faq` is the only valid one. I'm on it!

**Comment by sanscontext** [comment]
Wait, no, not even `faq` is valid - the build is just putting things in that folder.

**Comment by sanscontext** [comment]
This is a no-op on my part, so I'm going to close it.

**Comment by johndmulhausen** [comment]
Thanks for having a look, @sanscontext :)
