### ISSUE TITLE
Install instructions no longer work by default

### ISSUE THREAD

**Issue by dlitty** [docker/docker.github.io#10900]
File: [ee/docker-ee/windows/docker-ee.md](https://docs.docker.com/ee/docker-ee/windows/docker-ee/)

Hello,

If you follow these instructions on Windows Server 2019 explicitly, you will receive an error on the very first step:

WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package provider requires 'PackageManagement' and
'Provider' tags. Please check if the specified package has the tags.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21
+ ...     $null = PackageManagement\Install-PackageProvider -Name $script:N ...

-- The reason is because Microsoft is now forcing TLS 1.2 on the server end, but Powershell still tries to negotate 1.1.   To have it work properly, before the first step, you need to run:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;

Then proceed with the rest of the instructions.

**Comment by thaJeztah** [comment]
The Docker Enterprise docs have been moved to Mirantis, could you report this problem with them? https://docs.mirantis.com/welcome/

Thanks!
