### ISSUE TITLE
Docker Desktop for Windows Proxies Page Missing

### ISSUE THREAD

**Issue by ngodber** [docker/docker.github.io#10908]
### Problem description

Navigating through https://docs.docker.com/docker-for-windows/networking/ and selecting the 'Proxies' hyperlink https://docs.docker.com/docker-for-windows/networking/index#proxies leads to a 'Sorry, we can't find that page'.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/docker-for-windows/networking/index#proxies

### Suggestions for a fix

Unsure what the correct documentation seems to be. There are help articles for Docker for Windows but unsure if they apply.

**Comment by usha-mandya** [comment]
@ngodber Thank you for reporting the broken links issue. The PR has been merged to master. Updates will be live in the next publish cycle.
