### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by nerdjerry** [docker/docker.github.io#10917]
File: [engine/extend/plugins_network.md](https://docs.docker.com/engine/extend/plugins_network/)

Network plugins implement the Docker plugin API and the network plugin protocol

Link in Docker plugin API is broken, need to fix

**Comment by thaJeztah** [comment]
What page is the broken link on?

**Comment by nerdjerry** [comment]
Check this page https://docs.docker.com/engine/extend/plugins_network/

**Comment by thaJeztah** [comment]
Thanks! found it.

I know what's causing it (related to a Jekyll plugin we use to generate the site); in the meantime; this is the correct link; https://docs.docker.com/engine/extend/plugin_api/

**Comment by thaJeztah** [comment]
Will be fixed by https://github.com/docker/cli/pull/2556 / https://github.com/docker/cli/pull/2557

**Comment by nerdjerry** [comment]
Ok, thank you for consideration

**Comment by craig-osterhout** [comment]
Closing. This issue seems to have been resolved.
