### ISSUE TITLE
outdated info in the docs

### ISSUE THREAD

**Issue by shasan101** [docker/docker.github.io#10933]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact)

Docker version 19.03.9
OS: 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

The grid summarizing the usage of CMD and ENTRYPOINT in various combinations has one entry that is outdated.
![image](https://user-images.githubusercontent.com/36844715/83338375-36dac300-a2dd-11ea-97ef-5813b33cab82.png)

As you can see from my Dockerfile that there is no CMD or ENTRYPOINT being used in my test image and yet the container starts and then exits without any error.
 Dockerfile:
![image](https://user-images.githubusercontent.com/36844715/83338412-9042f200-a2dd-11ea-8fa9-a0a7e2630b3f.png)

And this shows that there is not error:
![image](https://user-images.githubusercontent.com/36844715/83338427-ae105700-a2dd-11ea-934c-0b88c8ae6c25.png)

**Comment by thaJeztah** [comment]
Your Dockerfile extends an existing image (`FROM alpine`), and because of that inherits the `CMD` and `ENTRYPOINT`
