### ISSUE TITLE
link not found

### ISSUE THREAD

**Issue by vijaykankane** [docker/docker.github.io#10946]
### Problem description
Link not available 

### Problem location
https://docs.docker.com/engine/userguide/networking/overlay-standalone-swarm/#create-a-swarm-cluster

- I saw a problem on the following URL: <URL>
https://docs.docker.com/engine/userguide/networking/overlay-standalone-swarm/#create-a-swarm-cluster
- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>
https://docs.docker.com/engine/userguide/networking/overlay-standalone-swarm/#create-a-swarm-cluster
- Other: <DETAILS>

**Comment by thaJeztah** [comment]
That page is describing networking for legacy swarm, for which the docs are no longer hosted on docs.docker.com; if you're looking for setting up an overlay network using the embedded k/v store, you're probably interested in this page; https://docs.docker.com/network/overlay/

Where did you find the link to that page?

**Comment by craig-osterhout** [comment]
Closing this issue as stale. If the issue still persists, please provide the details requested in the previous comment..
