### ISSUE TITLE
Bad Docker Compose link on Docker for Windows Home Install page

### ISSUE THREAD

**Issue by hardikszaveri** [docker/docker.github.io#10962]
Hi,

Docker compose link is old/bad here on this page https://docs.docker.com/docker-for-windows/install-windows-home/

![image](https://user-images.githubusercontent.com/26033308/83958467-659def80-a82f-11ea-849d-7437ebff6aa1.png)

**Comment by thaJeztah** [comment]
Thanks for reporting! I opened a pull request to fix; https://github.com/docker/docker.github.io/pull/10975
