### ISSUE TITLE
'Enable Kubernetes' section not correct

### ISSUE THREAD

**Issue by FrankAtHexagon** [docker/docker.github.io#10961]
File: [get-started/orchestration.md](https://docs.docker.com/get-started/orchestration/)

The _Windows_ tab of the _Enable Kubernetes_ section of the documentation says:
> After installing Docker Desktop, you should see a Docker icon in your system tray. Right-click on it, and navigate __Settings__ > __Kubernetes__.

The current version of Docker Desktop for Windows does not include a 'Kubernetes' section in Settings.

**Comment by usha-mandya** [comment]
@FrankAtHexagon Thanks for the feedback. Could you check whether you are running Windows containers? You can check this by clicking on the Docker menu from your task bar. If you see the option, "Switch to Linux containers", you are running on Windows containers. Please note that Kubernetes is only available on the Linux container mode.

**Comment by usha-mandya** [comment]
@FrankAtHexagon Closing this issue here as this is not a documentation issue. Feel free to continue the conversation after I close.

**Comment by FrankAtHexagon** [comment]
Thanks for your reply. There's nothing in the documentation, or at least what I was reading, that says that Kubernetes only works with Linux containers. Without a correction, I imagine others will have the same confusion.
