### ISSUE TITLE
Remove docs on non-existent GCS volume driver

### ISSUE THREAD

**Issue by knaperek** [docker/docker.github.io#10971]
File: [registry/storage-drivers/gcs.md](https://docs.docker.com/registry/storage-drivers/gcs/)

GCS volume driver is apparently not supported and probably never has been.
`$ docker volume create --driver gcs`
returns an error
`error looking up volume plugin gcs: plugin "gcs" not found`

If there's no intention to support gcs, this page should be removed from docs to avoid confusion.

**Comment by thaJeztah** [comment]
The page you linked to is documenting storage drivers for the open source image registry, not for volumes

**Comment by knaperek** [comment]
Right, my bad, thanks.
Perhaps it would help to have the context displayed on that page directly, because one can easily miss this pertains to the Docker **Registry** only (maybe change the title, or add breadcrumbs?)

**Comment by thaJeztah** [comment]
Thanks for the suggestion! Yes, it's currently listed under the "registry storage driver" section in the navigation on docs.docker.com;

<img width="272" alt="Screenshot 2020-06-09 at 10 08 55" src="https://user-images.githubusercontent.com/1804568/84122848-58545100-aa39-11ea-9fe6-ee42580b0027.png">


But we are discussing some re-design/restructuring of the docs (and have been discussing breadcrumbs) 👍
