### ISSUE TITLE
where does one find the logs in case of local docker log driver?

### ISSUE THREAD

**Issue by tomin11** [docker/docker.github.io#10974]
File: [config/containers/logging/local.md](https://docs.docker.com/config/containers/logging/local/)

**Comment by thaJeztah** [comment]
The actual store is somewhere in the `/var/lib/docker` directory on the host where the daemon runs, however, those files are not for consumption by external tools, as is called out by this note on that page;

> The local logging driver uses file-based storage. The file-format and storage mechanism are designed to be exclusively accessed by the Docker daemon, and should not be used by external tools as the implementation may change in future releases.

To access the logs, use the `docker container logs <your container>` (or the  `docker logs <your container>` shorthand) subcommands, or the equivalent API endpoint (https://docs.docker.com/engine/api/)
