### ISSUE TITLE
Need some explanation of the output of `docker image ls`

### ISSUE THREAD

**Issue by mansoor2016** [docker/docker.github.io#10970]
File: [engine/reference/commandline/image_ls.md](https://docs.docker.com/engine/reference/commandline/image_ls/)

**Comment by thaJeztah** [comment]
`docker image ls` is the "long hand" form for `docker images`. The plan is to make the reference documentation redirect to the same page for both, but that's not yet implemented, but you can find details on this page; https://docs.docker.com/engine/reference/commandline/images/
