### ISSUE TITLE
Link to "Authorization plugins" broken

### ISSUE THREAD

**Issue by ptxmac** [docker/docker.github.io#10984]
### Problem description

From https://docs.docker.com/engine/security/https/ there's a small paragraph about authorization plugins:

> Authorization plugins offer more fine-grained control to supplement authentication from mutual TLS. In addition to other information described in the above document, authorization plugins running on a Docker daemon receive the certificate information for connecting Docker clients.

That start of this is a link to https://docs.docker.com/engine/security/extend/plugins_authorization which doesn't exists

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/security/https/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It appears that it was fixed. If the issue still persists, please let us know.
