### ISSUE TITLE
Change WARNING note style `{.warning}`

### ISSUE THREAD

**Issue by chbrandt** [docker/docker.github.io#10985]
File: [config/containers/logging/configure.md](https://docs.docker.com/config/containers/logging/configure/)

The WARNING box (see below) _looks like an error/danger_ box would in most documents out there: it is **red** with a **X** symbol.

I suggest a WARNING note to look like one: **orange** with a **!** (or alike) symbol.

![image](https://user-images.githubusercontent.com/482051/84283033-cdf41600-ab3a-11ea-9bb8-60f578989058.png)

**Comment by craig-osterhout** [comment]
Thanks for sharing the suggestion. The icon has been updated to `!` and the style has slightly changed.
