### ISSUE TITLE
Use multi-stage builds examples are not working any more

### ISSUE THREAD

**Issue by lei-rwe** [docker/docker.github.io#10986]
File: [develop/develop-images/multistage-build.md](https://docs.docker.com/develop/develop-images/multistage-build/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.  Can you provide more details and the error output you received?
The topic is not intended to be a follow along tutorial and does not contain all the prerequisite steps.

**Comment by craig-osterhout** [comment]
Closing this as stale.
