### ISSUE TITLE
App Development Best Practices 

### ISSUE THREAD

**Issue by szchenjing** [docker/docker.github.io#10994]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If you're looking for the developing with Docker best practices, you can find them here, https://docs.docker.com/develop/dev-best-practices/
As the issue has no details, I'll close it. If there is an issue with the documentation, please provide more details.
