### ISSUE TITLE
More detail on docker run -v with files 

### ISSUE THREAD

**Issue by jchristn** [docker/docker.github.io#11004]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

Hello, I ran into an issue trying to get ```-v``` to work by bringing a file from my local filesystem into an image that I was trying to run.

It may be helpful to include the syntax for this use case.  Please see the stackoverflow.com question I asked on this: https://stackoverflow.com/questions/62416376/overwriting-files-with-v-in-docker-run-not-working

The part that caught me was the order of the parameters to ```-v```.  I mistakenly thought the first parameter was for the path to the file in the image and the second parameter for the path to the file on the local filesystem.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference
