### ISSUE TITLE
save command example

### ISSUE THREAD

**Issue by KY-7** [docker/docker.github.io#11019]
File: [engine/reference/commandline/save.md](https://docs.docker.com/engine/reference/commandline/save/)

the save command example provided (docker save my_image_id > my_image_file.tar) does not work properly on windows: it generates a dumb tar file that cannot be used.

However, the following command works:
docker save my_image_id -o my_image_file.tar

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
