### ISSUE TITLE
Provide checksums for D4M download links

### ISSUE THREAD

**Issue by browze** [docker/docker.github.io#1101]
File: [docker-for-mac/index.md](https://docs.docker.com/docker-for-mac/)
Perhaps a checksum on the download page could be provided?  I know its not a silver bullet so far as security concerns go, but still its something.

**Comment by sanscontext** [comment]
@NathanMcCauley do we have the ability to do that?

**Comment by mstanleyjones** [comment]
I'm not sure how we feel about this since these links change quite often right?

**Comment by londoncalling** [comment]
@browze @mstanleyjones Checksums are provided for Docker for Mac and Docker for Windows download links in the Docs per this PR: https://github.com/docker/docker.github.io/pull/2508

So far, we've not been adding them on Docker Store. Closing this issue for now. Let me and @nandhini know if you want these added to Docker Store.

cc: @FrenchBen @friism
