### ISSUE TITLE
Digest string example does not match spec

### ISSUE THREAD

**Issue by MMeent** [docker/docker.github.io#11018]
https://docs.docker.com/registry/spec/api/#content-digests

The spec specifies `algorithm   := /[A-Fa-f0-9_+.-]+/`, but the algorithm commonly used (`sha256`) does not match this regex .

File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/)

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/distribution/distribution/tree/main/docs/spec
