### ISSUE TITLE
Can we get an easy to remember command to remove stopped containers?

### ISSUE THREAD

**Issue by kurtwheeler** [docker/docker.github.io#11033]
File: [engine/reference/commandline/rm.md](https://docs.docker.com/engine/reference/commandline/rm/)

These docs suggest:

```
docker rm $(docker ps -a -q)
```

as the way to remove stopped containers. I have to look this up EVERY. SINGLE. TIME. Why not just `docker rm --stopped`?

**Comment by craig-osterhout** [comment]
Thanks for sharing the suggestion. If this is still applicable, please help create an issue for a feature request in the CLI repo at https://github.com/docker/cli
