### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by oliphantlt** [docker/docker.github.io#11038]
### Problem description

on this site (https://docs.docker.com/machine/overview/) I tried to follow the link that says (Provision a Docker Swarm cluster with Docker Machine (Legacy Swarm)) to the URL (https://docs.docker.com/machine/swarm/provision-with-machine.md) and got a 404 error.

### Problem location

I saw a problem on the following URL: https://docs.docker.com/machine/overview/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The issue is no longer applicable.
