### ISSUE TITLE
Add image to show how directory would look for this example(s)

### ISSUE THREAD

**Issue by imelendez** [docker/docker.github.io#11044]
File: [compose/django.md](https://docs.docker.com/compose/django/)

These instructions or steps refer to the "root of your project directory."

It would be beneficial to someone new to be able to see how the file system would look for these instructions.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. Did you encounter any errors when following the quick start guide?
In regards to more information about which Docker files are necessary to containerize an application, please refer to the updated general [getting started guide](https://docs.docker.com/get-started/). It's more targeted at new users and provides more details. The intent of the quick start guides is to quickly get started with less details.

**Comment by craig-osterhout** [comment]
Closing as stale. I think the assumption is the user would already know about the files that they just created. If I misunderstood the issue, please provide more details.
