### ISSUE TITLE
Feedback for: docker-id/index.md

### ISSUE THREAD

**Issue by cherylq26** [docker/docker.github.io#1104]
File: [docker-id/index.md](https://docs.docker.com/docker-id/)

There should be a section to include the Docker ID naming convention to notify users about what a valid Docker ID should be:

- a minimum of 4 characters 
- lowercase alphanumeric characters only (no spaces and dashes/hyphens `-`)

**Comment by sanscontext** [comment]
Hi @cherylq26, thanks for your feedback. We generally try to include this in our on-screen error messaging at account creation, but I could see it being useful as reference information as well. I'll see if I can get this updated in the next few days.
