### ISSUE TITLE
Find more information on Delegation Keys here.

### ISSUE THREAD

**Issue by ghandalf** [docker/docker.github.io#11063]
### Problem description
Unable to access the URL provided

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/security/trust/content_trust/
- To make it easier to find look for the text: "Find more information on Delegation Keys here."

- The URL <https://docs.docker.com/engine/security/trust/content_trust/trust_delegation/#creating-delegation-keys> provided doesn't exist.
- Maybe you should use this URL: <https://docs.docker.com/engine/security/trust/trust_delegation/#creating-delegation-keys>

Have a great day, 
Francis

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. It looks like that link no longer exists in the topic.
