### ISSUE TITLE
htpasswd  has disappeared 

### ISSUE THREAD

**Issue by scottstensland** [docker/docker.github.io#11060]
File: [registry/deploying.md](https://docs.docker.com/registry/deploying/)

binary htpasswd  used to work OK as per your docs however now it has disappeared when using your

    docker run --entrypoint htpasswd registry:2 -Bbn ${local_username}  ${local_reg_pwd}  > ${GKE_DOCKER_REG_INFO}/auth/htpasswd

if you pin to version 2.7.0 it does work

    docker run --entrypoint htpasswd registry:2.7.0 -Bbn ${local_username}  ${local_reg_pwd}  > ${GKE_DOCKER_REG_INFO}/auth/htpasswd 

for details see

 https://github.com/GoogleContainerTools/jib/pull/2538/commits/f816c837e34eb389c2cdee1bc9a2918c5d2e33e3 

https://github.com/GoogleContainerTools/jib/pull/2539 

https://github.com/docker/distribution-library-image/issues/106 

please update your docs to tell us what is now the new proper usage to create password file as your doc gives bad advice

**Comment by raylua2566** [comment]
Not work for `2.7.1` again.

**Comment by sekhemrekhutawysobekhotep** [comment]
true ... avoid using 2.7.1 as its broken instead use 2.7.0 for same reason as above OP has

**Comment by scottstensland** [comment]
here is corresponding stackoverflow ticket where folks have problems due to this unresolved issue

https://stackoverflow.com/questions/62531462/docker-local-registry-exec-htpasswd-executable-file-not-found-in-path/62531540#62531540

**Comment by craig-osterhout** [comment]
This looks like it was fixed in https://github.com/docker/docker.github.io/commit/d39b0d8e6e047ffcf5d0e6eecf45b3495437ceb8

If the issue still persists, please let us know.
