### ISSUE TITLE
Add a note to create a context in different subscription

### ISSUE THREAD

**Issue by sujaypillai** [docker/docker.github.io#11064]
File: [engine/context/aci-integration.md](https://docs.docker.com/engine/context/aci-integration/)

If you have already created a ACI context in a subscription then to create a new context in different subscription you need to login again to Azure to the respective account. To do this you need to execute the command `docker login azure` each time for change in subscription for a new context change.

Opening up this issue to add a **NOTE** section highlighting the same.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It looks like you resolved it in https://github.com/docker/docker.github.io/pull/11065
If the issue is still applicable, please let us know.
