### ISSUE TITLE
this WSL 1 distro

### ISSUE THREAD

**Issue by jy257** [docker/docker.github.io#11087]
Fildocker run -it nginx bash root@a6c26812d23b:/#

The command 'docker' could not be found in this WSL 1 distro.
We recommend to convert this distro to WSL 2 and activate
the WSL integration in Docker Desktop settings.e: [404.md](https://docs.docker.com/404.html)

**Comment by danthe1st** [comment]
Docker does not work with WSL 1, only with WSL 2.

**Comment by jy257** [comment]
Thanks! You are the first who answered me!

**Comment by usha-mandya** [comment]
Thank you @danthe1st. 

@jy257 Docker Desktop only works with WSL 2 when you've enabled the WSL integration in the settings. Closing this issue here as there's also a conversation active in https://github.com/docker/docker.github.io/issues/11099#issuecomment-656566296
