### ISSUE TITLE
-nostartfiles in example looks unneeded

### ISSUE THREAD

**Issue by alexey-milovidov** [docker/docker.github.io#11090]
File: [develop/develop-images/baseimages.md](https://docs.docker.com/develop/develop-images/baseimages/)

Without startfiles the simple program like `int main(int, char **) { return 0; }` cannot run, it needs at least `_start` function.

Also it is strange that the example has misleading comments:
https://github.com/docker-library/hello-world/blob/master/hello.c#L44

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The example has been modified in https://github.com/docker/docker.github.io/commit/1ef73b3a8a04b89191e8a7dd640372785959a338
In regards to the misleading comments in the hello.c file, please create an issue in the source repo at https://github.com/docker-library/hello-world/blob/master/ if it's still applicable.
