### ISSUE TITLE
Link not found , provided on Godoc page.

### ISSUE THREAD

**Issue by vibhordubey333** [docker/docker.github.io#11106]
Page where I found link https://godoc.org/github.com/CenturyLinkLabs/docker-reg-client/registry#ImageService , link which is not available ,  https://docs.docker.com/reference/api/registry_api/#put-image-layer_1

**Comment by usha-mandya** [comment]
@vibhordubey333 The Regsitry API docs are now at https://docs.docker.com/registry/spec/api/. The godoc needs to be updated to point to this URL instead. Please get in touch with them. I'm closing this issue here, but feel free to add a comment.
