### ISSUE TITLE
Docker Desktop dashboard not showing file share option(Windows container)

### ISSUE THREAD

**Issue by savar566** [docker/docker.github.io#11104]
### Problem description

Docker Desktop dashboard not showing file share option(Windows container)

### Problem location

Docker dashboard

![docker_Dashboard](https://user-images.githubusercontent.com/67837406/86873510-6a62f700-c0ac-11ea-8942-bad0fbb1f0af.PNG)

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64

**Comment by usha-mandya** [comment]
@savar566 The File sharing tab is only available in the Hyper-V mode. See https://docs.docker.com/docker-for-windows/#file-sharing.

Closing this issue. Feel free to continue the conversation after I close.
