### ISSUE TITLE
Link is not found 

### ISSUE THREAD

**Issue by vibhordubey333** [docker/docker.github.io#11105]
Link is mentioned on godoc but not able to access it : https://docs.docker.com/reference/api/registry_api/

**Comment by thaJeztah** [comment]
I think the correct URL for that is https://docs.docker.com/registry/spec/api/

Do you have a link to the godoc page that mentions that URL? Looks like that may have to be updated

**Comment by vibhordubey333** [comment]
Page that is mentioning the URL is [https://godoc.org/github.com/CenturyLinkLabs/docker-reg-client/registry#ImageService]

**Comment by thaJeztah** [comment]
Hm, yes, that looks like quite an old project. Not sure if it's still maintained (https://github.com/CenturyLinkLabs/docker-reg-client). Might be worth trying to open a pull request there to see if they accept

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/distribution/pull/3196 and https://github.com/docker/distribution/pull/3197 to add redirects

**Comment by thaJeztah** [comment]
Those PR's were merged, and the URL now redirects to the right location. Thanks again for reporting!
