### ISSUE TITLE
Link not found.

### ISSUE THREAD

**Issue by vibhordubey333** [docker/docker.github.io#11119]
Link not found. Page where I found link which is not accessible : https://godoc.org/docker.io/go-docker#Client.ImageLoad  

Link I tried to access : https://docs.docker.com/develop/api

**Comment by usha-mandya** [comment]
@vibhordubey333 The Godoc needs to be updated to point to https://docs.docker.com/engine/api/. Please work with them to get this and any other links to Docker docs updated. Closing this here as it's not a Docker documentation issue.
