### ISSUE TITLE
Documentation broken link in Main Page: Template API

### ISSUE THREAD

**Issue by hagargi** [docker/docker.github.io#11128]
### Problem description

Documentation broken link in Main Page: Template API
<img width="978" alt="Screen Shot 2020-07-11 at 10 24 43 PM" src="https://user-images.githubusercontent.com/2812046/87229413-5af1ef80-c3c5-11ea-8ba9-81df0700a021.png">

### Problem location

- I saw a problem on the following URL: 
https://docs.docker.com/reference/
https://docs.docker.com/reference/app-template/api-reference

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The content no longer exists and the link has been removed.
