### ISSUE TITLE
No HTTP example for "Pull an image with authentication"

### ISSUE THREAD

**Issue by copiltembel** [docker/docker.github.io#11121]
File: [engine/api/sdk/examples.md](https://docs.docker.com/engine/api/sdk/examples/)

Go to https://docs.docker.com/engine/api/sdk/examples/#pull-an-image-with-authentication

Click on HTTP. Either Python or Go code will be displayed instead of HTTP.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It looks like it was fixed in https://github.com/docker/docker.github.io/commit/e9750cda7800167870ac303f98b2313ae413abbd
