### ISSUE TITLE
Invalid docker logs example

### ISSUE THREAD

**Issue by DanielChabrowski** [docker/docker.github.io#11122]
File: [engine/reference/commandline/logs.md](https://docs.docker.com/engine/reference/commandline/logs/)

For both online reference and `man docker-container-logs` the example executes `docker logs -f --until=2s` which is invalid as it is missing container parameter. Should be changed to `docker logs -f --until=2s test`.

I wanted to make a PR but it not clear to me whether it should go here or docker/cli or both. README and https://docs.docker.com/opensource/ do not even mention docker/cli so it's a little bit confusing imho.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline https://github.com/docker/cli/tree/master/man/src
