### ISSUE TITLE
Update screenshot to reflect changed website layout

### ISSUE THREAD

**Issue by vishalramesh** [docker/docker.github.io#11130]
File: [opensource/index.md](https://docs.docker.com/opensource/)

Website no longer shows Get Support on the right-side menu.

![Screenshot (72)_LI](https://user-images.githubusercontent.com/18702900/87276078-2ccdf600-c512-11ea-8bbd-6893ca4a311e.jpg)

**Comment by usha-mandya** [comment]
Thank you @vishalramesh. The screenshot has been updated. The changes will go live in the next publish cycle.
