### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by som632000** [docker/docker.github.io#11133]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
@som632000  There's isn't any information on the ticket for us to take action on. Could you add more details?

**Comment by usha-mandya** [comment]
I'm closing the issue here due to the lack of information. Feel free to add more information on the ticket to continue the conversation.
