### ISSUE TITLE
incorrect order in Dockerfile

### ISSUE THREAD

**Issue by VarunVemala** [docker/docker.github.io#11149]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

in the Dockerfile content, we have CMD [ "npm", "start" ] before COPY . .
This will fail, and newbies will not understand!

**Comment by usha-mandya** [comment]
@VarunVemala Thanks for you feedback. This works fine for me. Could you provide more details on the error that you see and at which step you experience this issue?

**Comment by usha-mandya** [comment]
Closing this issue here as the the Dockerfile works fine with the existing order. Feel free to continue the conversation after I close.
