### ISSUE TITLE
Missing info regarding enabling IPv6 

### ISSUE THREAD

**Issue by wdec** [docker/docker.github.io#11143]
File: [config/daemon/ipv6.md](https://docs.docker.com/config/daemon/ipv6/)

As per the following discussion: https://github.com/moby/moby/issues/29443 a fixed-cidr-v6 parameter, corresponding to a network routed to the host, is needed to enable IPv6 support.
```
{
"ipv6": true,
"fixed-cidr-v6": "2001:db8::/64",
}
```

**Comment by thaJeztah** [comment]
ping @arkodg PTAL
