### ISSUE TITLE
Clarify explanation of having multiple CMD instructions

### ISSUE THREAD

**Issue by mwaggonerzam** [docker/docker.github.io#11157]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

For the CMD command documentation, it says:

> There can only be one CMD instruction in a Dockerfile. If you list more than one CMD then only the last CMD will take effect.

The first sentence is confusing in light of the second sentence. There evidently _can_ be more than one CMD instruction, but only the most recent one will take effect. (Even in `docker history`, an image that was built from a Dockerfile with more than one CMD instruction will list all of them, even though only the last one actually has any effect.)

The sentences could be rewritten as follows:

> A Dockerfile may contain multiple CMD instructions, but only the last CMD instruction will take effect. If a Dockerfile has a CMD instruction, it will override any CMD instructions that were in the base image.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference
