### ISSUE TITLE
Update api registry docs to indicate how to retrieve full manifest from manifest list

### ISSUE THREAD

**Issue by anorth2** [docker/docker.github.io#11155]
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/)

https://stackoverflow.com/questions/62941505/how-to-extract-full-docker-image-manifest-from-manifest-list

When you retrieve with `distribution.manifest.v2` from a multiplatform image it appears to only return the first manifest. If you retrieve with `distribution.manifest.list.v2` it returns a list of the manifest digests, but not the manifest contents. How do you retrieve the full manifest contents for every manifest in the list?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/distribution/distribution/tree/main/docs/spec
