### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by HimanshuGup** [docker/docker.github.io#11162]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
@HimanshuGup There's isn't any information on the ticket for us to take action on. Could you add more details?

**Comment by usha-mandya** [comment]
Closing the issue here as there's isn't any information on the ticket. Feel free to add more information on the ticket to continue the conversation.
