### ISSUE TITLE
Dockerfile COPY --from documentation is misleading

### ISSUE THREAD

**Issue by vide** [docker/docker.github.io#11169]
### Problem description

There is a behaviour of `COPY --from=$REGISTRY_IMAGE` syntax explained only in the [multi-stage guide](https://docs.docker.com/develop/develop-images/multistage-build/#use-an-external-image-as-a-stage) and that it is not reflected in the Dockerfile `COPY` documentation, which should be the source of truth for COPY syntax

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/builder/#copy

### Suggestions for a fix

Mention that you can use an external registry image as the `--from` image in a `COPY` operation, alongside named or indexed stages, would make things easier to discover or check.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference
