### ISSUE TITLE
Incorrect explanation of ENTRYPOINT instruction

### ISSUE THREAD

**Issue by l0n3star** [docker/docker.github.io#11160]
### Problem description

This statement is incorrect:

`You can see that when the container starts up, the command portion is interpreted to be sh -c 'docker-entrypoint.sh postgres'`.

In the dockerfile the ENTRYPOINT instruction uses the exec form, so it won't invoke a shell.  

### Problem location

I saw a problem on the following URL: https://success.docker.com/article/use-a-script-to-initialize-stateful-container-data

### Suggestions for a fix

That line should state:

`You can see that when the container starts up, the command portion is interpreted to be 'docker-entrypoint.sh postgres'`

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the article no longer exists.
