### ISSUE TITLE
Example code for this feature

### ISSUE THREAD

**Issue by hajimurtaza** [docker/docker.github.io#11172]
File: [docker-for-windows/networking.md](https://docs.docker.com/docker-for-windows/networking/)

Can you add an example for the following scenario:

`I WANT TO CONNECT FROM A CONTAINER TO A SERVICE ON THE HOST`

**Comment by usha-mandya** [comment]
Hey @hajimurtaza, we are looking to an add example on how to connect from a container to a service on the host. I'll update the ticket when this is available. Thanks for letting us know.

**Comment by usha-mandya** [comment]
This PR has been merged to master. The changes will go live at the next publisher run.
