### ISSUE TITLE
Inconsistent usage of the word "repository"

### ISSUE THREAD

**Issue by monktastic** [docker/docker.github.io#11186]
File: [engine/reference/commandline/tag.md](https://docs.docker.com/engine/reference/commandline/tag/)

> To tag a local image with ID “0e5574283393” into the “fedora” repository with “version1.0”:
> $ docker tag 0e5574283393 fedora/httpd:version1.0

I haven't done a survey of the Docker docs to confirm, but it seems widely understood that the repository here is "fedora/httpd" and not just "fedora."[0] I think the above should read "into the 'fedora:httpd' repository" for consistency, or else these examples are needlessly confusing (at least, for someone literal-minded like me).

[0] https://stackoverflow.com/questions/31115098/what-is-the-difference-between-an-image-and-a-repository

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help open an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
