### ISSUE TITLE
Link-rot (bad URL)

### ISSUE THREAD

**Issue by wickahead** [docker/docker.github.io#11196]
### Problem description

As a newbie developer learning about docker desktop,
I wanted to learn more 
So that I could become enlightened.

### Problem location

- I saw a problem on the following URL: https://www.docker.com/products/docker-desktop

When I clicked on the "---> Learn more" link in upper right (with address of: https://docs.docker.com/app-template/working-with-template/) ; it 404'd on me.

- Other: <DETAILS>

### Project version(s) affected

Accessed July 29, 2020

**Comment by craig-osterhout** [comment]
The link now redirects to the documentation.
