### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by belchior** [docker/docker.github.io#11201]
### Problem description
There is a broken link at https://docs.docker.com/compose/production/#running-compose-on-a-swarm-cluster

The "Docker Swarm" link redirects to a 404 page.

I think the correct link is: https://docs.docker.com/engine/swarm

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The issue appears to be no longer applicable. If you still encounter the issue, please let us know.
