### ISSUE TITLE
Docker default seccomp container profile allows setns syscall, but documentations says otherwise

### ISSUE THREAD

**Issue by TheDiveO** [docker/docker.github.io#11200]
File: [engine/security/seccomp.md](https://docs.docker.com/engine/security/seccomp/)

https://raw.githubusercontent.com/moby/moby/master/profiles/seccomp/default.json shows that the `setns` syscall actually is allowed in the default profile, while the documentation claims the contrary. Please remove the table row on `setns` from the table in the section entitled "Significant syscalls blocked by the default profile".

**Comment by thaJeztah** [comment]
I may be mistaken, but think it's allowed by default; it's gated by having `SCMP_ACT_ALLOW` permissions; if you run the container with `--cap-add SYS_ADMIN` it will be allowed, but not without; https://github.com/moby/moby/blob/v19.03.12/profiles/seccomp/default.json#L594-L605

See https://github.com/moby/moby/pull/22554

**Comment by TheDiveO** [comment]
So I have been fooled by the section being entitled "blocked syscalls", yet the table containing exceptions in the form of "...gated...". Oh well.

**Comment by TheDiveO** [comment]
So I have been fooled by the section being entitled "blocked syscalls", yet the table containing exceptions in the form of "...gated...". Oh well.

**Comment by thaJeztah** [comment]
Ah, yes, it's mentioned there indeed.

Looks like this can be closed? Let me go ahead and do so, but feel free to continue the conversation 👍 

Thanks for reporting; it never hurts to report such issues as it could've been that it was forgotten to update ❤️
