### ISSUE TITLE
Too Few Parameters in Go API Docs

### ISSUE THREAD

**Issue by jkelly80** [docker/docker.github.io#11210]
File: [engine/api/sdk/index.md](https://docs.docker.com/engine/api/sdk/)

I may have mixed up my versions, but I believe the following call to ContainerCreate does not compile because ContainerCreate requires 6 arguments, but only 5 are provided here. For the purposes of this quickstart, I believe adding a third `nil` would fix the issue. 

``` go
    resp, err := cli.ContainerCreate(ctx, &container.Config{
        Image: "alpine",
        Cmd:   []string{"echo", "hello world"},
    }, nil, nil, "")
```

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It looks like it was fixed in https://github.com/docker/docker.github.io/commit/ce3c977b7019154d7d3694a29752f6297f1381b5
If the issue still persists, please let us know.
