### ISSUE TITLE
What drives the alternatives described in the paragraph under heading "The example voting app contains"

### ISSUE THREAD

**Issue by lleeoo** [docker/docker.github.io#11229]
For example: 
> A front-end web app in Python or ASP.NET Core which lets you vote between two options

I'm guessing that it will be ASP.NET on Windows and Python elsewhere? Is any combination of the five bullet points possible? If this isn't the correct place to discuss that, then it would be helpful to point to an explanation elsewhere.

File: [desktop/dashboard.md](https://docs.docker.com/desktop/dashboard/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Information about the app can be found in the GitHub repo already linked in the topic. https://github.com/dockersamples/example-voting-app
