### ISSUE TITLE
Nimble has moved

### ISSUE THREAD

**Issue by datamattsson** [docker/docker.github.io#11239]
File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/)

Can we please link the Nimble DVP to https://scod.hpedev.io/docker_volume_plugins/hpe_nimble_storage/index.html

**Comment by craig-osterhout** [comment]
Created a new issue in the upstream repo that contains this file. Closing this issue in favor of the new one.
https://github.com/docker/cli/issues/3589
