### ISSUE TITLE
Run Docker in IOS/Android

### ISSUE THREAD

**Issue by Linoy339** [docker/docker.github.io#11231]
HI all,
Can we run a docker image in IOS?
Actually, I am working on an offline project using node js and this will be run in mobile using nodejs-mobile(which is a library to run node in mobile). But there is some complication in running it in mobile as one of the dependency of offline db is not working properly in nodejs-mobile.  If I set up a docker image, can I pull it for IOS as well as android and work it as an app.

Thank you

**Comment by thaJeztah** [comment]
No there's no support currently for iOS or Android
