### ISSUE TITLE
different-types-of-volumes page not found

### ISSUE THREAD

**Issue by mjhea0** [docker/docker.github.io#11244]
I'm getting a 400 error when I try to go to https://success.docker.com/article/different-types-of-volumes.

<img width="1167" alt="search results" src="https://user-images.githubusercontent.com/2018167/90139575-2d8abf80-dd3e-11ea-9ec6-a6085a36ad62.png">
<img width="1085" alt="error" src="https://user-images.githubusercontent.com/2018167/90139611-3bd8db80-dd3e-11ea-816c-efc19774c231.png">

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As this issue is old, some context may have changed. The page no longer appears in the search results. If you were searching for any particular information and you were not able to find it, please let us know.
