### ISSUE TITLE
Server: ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by rickrichi** [docker/docker.github.io#11246]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by rickrichi** [comment]
apt 2.0.2ubuntu0.1 (amd64)
Usage: apt-get [options] command
       apt-get [options] install|remove pkg1 [pkg2 ...]
       apt-get [options] source pkg1 [pkg2 ...]

apt-get is a command line interface for retrieval of packages
and information about them from authenticated sources and
for installation, upgrade and removal of packages together
with their dependencies.

Most used commands:
  update - Retrieve new lists of packages
  upgrade - Perform an upgrade
  install - Install new packages (pkg is libc6 not libc6.deb)
  reinstall - Reinstall packages (pkg is libc6 not libc6.deb)
  remove - Remove packages
  purge - Remove packages and config files
  autoremove - Remove automatically all unused packages
  dist-upgrade - Distribution upgrade, see apt-get(8)
  dselect-upgrade - Follow dselect selections
  build-dep - Configure build-dependencies for source packages
  satisfy - Satisfy dependency strings
  clean - Erase downloaded archive files
  autoclean - Erase old downloaded archive files
  check - Verify that there are no broken dependencies
  source - Download source archives
  download - Download the binary package into the current directory
  changelog - Download and display the changelog for the given package

See apt-get(8) for more information about the available commands.
Configuration options and syntax is detailed in apt.conf(5).
Information about how to configure sources can be found in sources.list(5).
Package and version choices can be expressed via apt_preferences(5).
Security details are available in apt-secure(8).
                                        This APT has Super Cow Powers.
root@LAPTOP-RAF4LSFJ:~# apt-check
apt-check: command not found
root@LAPTOP-RAF4LSFJ:~# apt-get check
Reading package lists... Done
Building dependency tree
Reading state information... Done
root@LAPTOP-RAF4LSFJ:~# ls
 aws            docker-relay                             openethereum
 awscliv2.zip   google-chrome-stable_current_amd64.deb  't all the installed Packages'
root@LAPTOP-RAF4LSFJ:~# apt-get build-dep
E: Must specify at least one package to check builddeps for
root@LAPTOP-RAF4LSFJ:~# apt-get build-dep openethereum
Reading package lists... Done
E: You must put some 'deb-src' URIs in your sources.list
root@LAPTOP-RAF4LSFJ:~# apt-get build-dep https://github.com/openethereum/openethereum
Reading package lists... Done
E: You must put some 'deb-src' URIs in your sources.list
root@LAPTOP-RAF4LSFJ:~# echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/chrome.list
root@LAPTOP-RAF4LSFJ:~# cd ~/.chainlink-ropsten
root@LAPTOP-RAF4LSFJ:~/.chainlink-ropsten# dir
root@LAPTOP-RAF4LSFJ:~/.chainlink-ropsten# sudo daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
sudo: daemonize: command not found
root@LAPTOP-RAF4LSFJ:~/.chainlink-ropsten# dockerd
INFO[2020-08-13T12:07:29.569771200-07:00] Starting up
INFO[2020-08-13T12:07:29.581663900-07:00] libcontainerd: started new containerd process  pid=767
INFO[2020-08-13T12:07:29.581975800-07:00] parsed scheme: "unix"                         module=grpc
INFO[2020-08-13T12:07:29.582167300-07:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-08-13T12:07:29.582416000-07:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-08-13T12:07:29.582651500-07:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-08-13T12:07:29.619360800-07:00] starting containerd                           revision= version=1.3.3-0ubuntu2
INFO[2020-08-13T12:07:29.640395200-07:00] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2020-08-13T12:07:29.641405400-07:00] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
INFO[2020-08-13T12:07:29.644710600-07:00] skip loading plugin "io.containerd.snapshotter.v1.btrfs"...  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs (lxfs) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2020-08-13T12:07:29.645826100-07:00] loading plugin "io.containerd.snapshotter.v1.devmapper"...  type=io.containerd.snapshotter.v1
WARN[2020-08-13T12:07:29.646998000-07:00] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
INFO[2020-08-13T12:07:29.648330900-07:00] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[2020-08-13T12:07:29.660670800-07:00] skip loading plugin "io.containerd.snapshotter.v1.aufs"...  error="modprobe aufs failed: \"modprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-18362-Microsoft\\n\": exit status 1: skip plugin" type=io.containerd.snapshotter.v1
INFO[2020-08-13T12:07:29.662124900-07:00] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2020-08-13T12:07:29.664608100-07:00] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2020-08-13T12:07:29.666519100-07:00] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2020-08-13T12:07:29.668307900-07:00] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2020-08-13T12:07:29.669331000-07:00] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2020-08-13T12:07:29.670475200-07:00] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
INFO[2020-08-13T12:07:29.672912500-07:00] metadata content store policy set             policy=shared
INFO[2020-08-13T12:07:29.682354800-07:00] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2020-08-13T12:07:29.683507300-07:00] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2020-08-13T12:07:29.685621200-07:00] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2020-08-13T12:07:29.686976500-07:00] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2020-08-13T12:07:29.688416200-07:00] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2020-08-13T12:07:29.690388600-07:00] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2020-08-13T12:07:29.693012200-07:00] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2020-08-13T12:07:29.695313100-07:00] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2020-08-13T12:07:29.696837000-07:00] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2020-08-13T12:07:29.698115700-07:00] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2020-08-13T12:07:29.699827300-07:00] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2020-08-13T12:07:29.701311900-07:00] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2020-08-13T12:07:29.703371500-07:00] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2020-08-13T12:07:29.705375300-07:00] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2020-08-13T12:07:29.706435800-07:00] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.707860000-07:00] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.708593200-07:00] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.709203100-07:00] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.709790500-07:00] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.711052900-07:00] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.713255700-07:00] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.714532700-07:00] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.715729600-07:00] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2020-08-13T12:07:29.716849300-07:00] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.717794200-07:00] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.718531000-07:00] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.719199800-07:00] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2020-08-13T12:07:29.723013300-07:00] serving...                                    address=/var/run/docker/containerd/containerd-debug.sock
INFO[2020-08-13T12:07:29.727467700-07:00] serving...                                    address=/var/run/docker/containerd/containerd.sock.ttrpc
INFO[2020-08-13T12:07:29.730108300-07:00] serving...                                    address=/var/run/docker/containerd/containerd.sock
INFO[2020-08-13T12:07:29.731204200-07:00] containerd successfully booted in 0.113053s
INFO[2020-08-13T12:07:29.748642900-07:00] parsed scheme: "unix"                         module=grpc
INFO[2020-08-13T12:07:29.748973200-07:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-08-13T12:07:29.750678300-07:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-08-13T12:07:29.753443600-07:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-08-13T12:07:29.760257400-07:00] parsed scheme: "unix"                         module=grpc
INFO[2020-08-13T12:07:29.760629900-07:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-08-13T12:07:29.761526300-07:00] ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-08-13T12:07:29.764190600-07:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-08-13T12:07:29.782970400-07:00] [graphdriver] using prior storage driver: overlay2
WARN[2020-08-13T12:07:29.796945400-07:00] Your kernel does not support cgroup memory limit
WARN[2020-08-13T12:07:29.797465100-07:00] Unable to find cpu cgroup in mounts
WARN[2020-08-13T12:07:29.798110500-07:00] Unable to find blkio cgroup in mounts
WARN[2020-08-13T12:07:29.800182300-07:00] Unable to find cpuset cgroup in mounts
WARN[2020-08-13T12:07:29.800920200-07:00] mountpoint for pids not found
INFO[2020-08-13T12:07:29.802693000-07:00] Loading containers: start.
WARN[2020-08-13T12:07:29.811656200-07:00] Running iptables --wait -t nat -L -n failed with message: `iptables v1.8.4 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.`, error: exit status 3
INFO[2020-08-13T12:07:29.936200300-07:00] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2020-08-13T12:07:29.937369500-07:00] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2020-08-13T12:07:29.937384200-07:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.4 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)

**Comment by Rowanto** [comment]
check https://github.com/docker/roadmap/issues/91

**Comment by thaJeztah** [comment]
closing in favor of https://github.com/docker/roadmap/issues/91
