### ISSUE TITLE
Please update this documentation!

### ISSUE THREAD

**Issue by dkennedy87** [docker/docker.github.io#11256]
File: [compose/aspnet-mssql-compose.md](https://docs.docker.com/compose/aspnet-mssql-compose/)

There are a lot of steps missing, out of order, and much of it is out of date.  Please update this to .net core 3, and add in the steps to include the proper references, and put the reference additions before the code they are needed for!

**Comment by pietersweter** [comment]
The documentation for listing `/tags` seems out of date.
I encountered problems using `GET /v2/<name>/tags/list` as stated in https://docs.docker.com/registry/spec/api/#listing-image-tags

**Example:**
**GET** https://hub.docker.com/v2/repositories/perconalab/percona-server-mongodb-operator/tags/list
returns 
```
{
txnid: "REPOSREQ-cafbce86-5b8d-4051-91a3-e3dddc028fe9",
message: "tag 'list' not found",
errinfo: {
api_call_docker_id: "",
api_call_name: "GetRepositoryTag",
api_call_start: "2020-08-17T21:30:50.540228295Z",
api_call_txnid: "REPOSREQ-cafbce86-5b8d-4051-91a3-e3dddc028fe9",
namespace: "perconalab",
repository: "percona-server-mongodb-operator",
tag: "list"
}
}
```
and **GET** https://hub.docker.com/v2/repositories/perconalab/percona-server-mongodb-operator/tags returns
```
count: 615,
next: "https://hub.docker.com/v2/repositories/perconalab/percona-server-mongodb-operator/tags?page=2",
previous: null,
results: [
{
...
```

Seems like `/tags` is the way to go and `/tags/list` is legacy, but the docs do not reflect that.
Please clarify this information and update the docs accordingly

**Comment by umi0410** [comment]
@pietersweter I suffered from legacy documentation to get list of `tags`. I also hope the registry API docs to be updated.

**Comment by craig-osterhout** [comment]
@dkennedy87, thanks for sharing the issue. Closing in favor of https://github.com/docker/docker.github.io/issues/14560
@ptak7 please open a new issue as this seems unrelated to the parent issue. In addition, that particular content is maintained in an upstream repo. Please help open the issue in the source repo at https://github.com/distribution/distribution/tree/main/docs/spec
