### ISSUE TITLE
Question about the new terms of service

### ISSUE THREAD

**Issue by jshen28** [docker/docker.github.io#11253]
### Problem description

I notice that on August 13th, the terms of service is updated as it is now stated

_20.8 You understand that the Service is subject to United States export controls administered by the U.S. Department of Commerce and the United States Department of Treasury Office of Foreign Assets Control. You acknowledge and agrees that the Service and any User Content or Third Party Content accessed by you shall not be used, transferred or otherwise exported or re-exported to countries as to which the United States, maintains an embargo (collectively, "Embargoed Countries"), or to or by a national or resident thereof, or any person or entity on the U.S. Department of Treasury's List of Specially Designated Nationals or the U.S. Department of Commerce's Entity List, Denied Persons List, or Unverified List, or the U.S. Department of State’s Nonproliferation Sanctions list (collectively, "Designated Nationals"). The lists of Embargoed Countries and Designated Nationals are subject to change without notice. By using the Service, including without limitation by uploading or accessing any User Content or Third Party Content, you represent and warrant that you are not located in, under the control of, or a national or resident of an Embargoed Country or Designated National. You agree to comply strictly with all U.S. export laws and assume sole responsibility for obtaining United States government export licenses to export or re-export as may be required. You will defend, indemnify, and hold harmless Docker and its suppliers and licensors from and against any violation of such laws or regulations by you or any of your agents, officers, directors or employees._

As a Chinese developer I am concerned that docker is not allowed to use in China any more. Am I
understanding it correctly? If so, does anyone know what could be a potential alternative for docker?
Thanks.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If you are unable to access the Docker installer or any services, please seek support in the Docker Community Slack or forums. 
- https://forums.docker.com/
- https://dockercommunity.slack.com/

It is your responsibility to ensure that your use and/or transfer does not violate applicable laws.
For more information, please see https://www.bis.doc.gov
See also https://www.apache.org/dev/crypto.html and/or seek legal counsel.
