### ISSUE TITLE
Unable to change kernel.core_pattern with --privileged

### ISSUE THREAD

**Issue by abrararshad** [docker/docker.github.io#11255]
Hi,  trying to setup core dump files. --privileged with "docker exec" or "docker-compose exec" both run into read-only issue for me. Searched a lot on this, everyone gives example with docker run. I assume --privileged with RUN and EXEC should work the same.

```
$ docker exec --privileged -it CONTAINER sysctl -w kernel.core_pattern=/tmp
sysctl: error setting key 'kernel.core_pattern': Read-only file system
```
I am running docker desktop on mac 
version: 2.3.0.4

Any idea please

**Comment by craig-osterhout** [comment]
For support, please try the Docker Community Slack or forums:
- https://dockercommunity.slack.com/
- https://forums.docker.com/

If there's an issue in the documentation, please let us know.
