### ISSUE TITLE
ubuntu version mismatch

### ISSUE THREAD

**Issue by alirezaazad625** [docker/docker.github.io#11254]
File: [storage/storagedriver/index.md](https://docs.docker.com/storage/storagedriver/)

in this page you always said you use ubuntu version 18.04 but pictures show the ubuntu version 15.04.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Quick fix in https://github.com/docker/docker.github.io/commit/5bf5f94c32b58bbc70c1de6b12ffdca36ba9cc9a
It still has both 18.04 and 15.04, but the diagram intros now match diagrams.
