### ISSUE TITLE
Unable to start docker service

### ISSUE THREAD

**Issue by rchouhan** [docker/docker.github.io#11263]
I have installed the latest docker version on my centOS (CentOS Linux release 7.8.2003 (Core)) but I am unable to start the docker service the error I am seeing is mentioned below
[root@COMP-2462-1 ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.13-beta2
 API version:       1.40
 Go version:        go1.13.14
 Git commit:        ff3fbc9d55
 Built:             Mon Aug  3 15:04:07 2020
 OS/Arch:           linux/amd64
 Experimental:      false
**Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?**
[root@COMP-2462-1 ~]# dockerd
INFO[2020-08-19T00:41:37.535805830-04:00] Starting up
INFO[2020-08-19T00:41:37.537222865-04:00] parsed scheme: "unix"                         module=grpc
INFO[2020-08-19T00:41:37.537248243-04:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-08-19T00:41:37.537287930-04:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-08-19T00:41:37.537305457-04:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-08-19T00:41:37.538496416-04:00] parsed scheme: "unix"                         module=grpc
INFO[2020-08-19T00:41:37.538514830-04:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-08-19T00:41:37.538533887-04:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-08-19T00:41:37.538546254-04:00] ClientConn switching balancer to "pick_first"  module=grpc
WARN[2020-08-19T00:41:37.546236380-04:00] Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man dockerd` to refer to dm.thinpooldev section.  storage-driver=devicemapper
INFO[2020-08-19T00:41:37.782029534-04:00] Creating filesystem xfs on device docker-253:1-5409198-base, mkfs args: [-m crc=0,finobt=0 /dev/mapper/docker-253:1-5409198-base]  storage-driver=devicemapper
INFO[2020-08-19T00:41:37.782988805-04:00] Error while creating filesystem xfs on device docker-253:1-5409198-base: exit status 1  storage-driver=devicemapper
ERRO[2020-08-19T00:41:37.783010634-04:00] [graphdriver] prior storage driver devicemapper failed: exit status 1
failed to start daemon: error initializing graphdriver: exit status 1

I have tried with overlay2 storage as well but that doesn't solved this issue.

Any pointers to solve this issue?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If you need support, you may try the Docker Community Forums. If you believe it is a bug in the application, please share the issue the application repository. Closing the issue as it is not a documentation issue.
