### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by OleksandrNikitin** [docker/docker.github.io#11265]
File: [404.md](https://docs.docker.com/404.html)

**Comment by usha-mandya** [comment]
@NikitinOleksandr There's isn't any information on the ticket for us to take action on. Could you provide more information?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. We are unable to reproduce the issue and are closing it due to insufficient information. If you still encounter the issue, please respond with the requested details.
