### ISSUE TITLE
https://docs.docker.com/installation/binaries/

### ISSUE THREAD

**Issue by tvajjala** [docker/docker.github.io#11272]
### Problem description

https://docs.docker.com/installation/binaries/ 404

### Problem location

- I saw a problem on the following URL:  https://docs.docker.com/installation/binaries/

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
@tvajjala Thank you for the feedback. For information on how to download and install Docker, see https://docs.docker.com/get-docker/.

https://docs.docker.com/installation/binaries/ doesn't exist anymore. I'll update the redirects.

**Comment by usha-mandya** [comment]
See also https://docs.docker.com/engine/install/binaries/
