### ISSUE TITLE
instructions for pas

### ISSUE THREAD

**Issue by andrewufrank** [docker/docker.github.io#11276]
File: [engine/reference/commandline/login.md](https://docs.docker.com/engine/reference/commandline/login/)

the instructions are at least incomplete for using pass. After installation of pass (apt install pass) `docker login` returns (after correct user name and password): 
  
    Error saving credentials: error storing credentials - err: exec: "docker-credential-pass": executable file not found in $PATH, out: ``

obviously the instructions on the necessary steps to install the `docker-credential-pass' are missing. From the long discussion on the net on this point -- using various old versions -- i am left baffled what I should do. 

please fix docs! - it is a show stopper when running a headless system where D-bus cannot be used, for lack of a X11 $DISPLAY.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
