### ISSUE TITLE
Add docs for --env-file option.

### ISSUE THREAD

**Issue by DavidTheProgrammer** [docker/docker.github.io#11286]
File: [compose/environment-variables.md](https://docs.docker.com/compose/environment-variables/)

Add documentation for `--env-file` flag merged in https://github.com/docker/compose/pull/6535

**Comment by usha-mandya** [comment]
Closing this issue as it has been fixed - https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files.
