### ISSUE TITLE
Pure scrolling annoyingly expands menu items

### ISSUE THREAD

**Issue by Enselic** [docker/docker.github.io#1128]
When scrolling through the docs on my iPhone, menu items are expanded. The shall not be expanded by touchdown/up when scrolling, only when clicking. It is extremely annoying and makes the docs almost unreadable in terms of user experience.

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by johndmulhausen** [comment]
Thinking aloud: I'm pretty sure the necessary JS here would:

- Trigger an "I got touched" event onMouseDown for the node that sets a global variable ("hasScrolled") to false
- If the user scrolls the window after touching a node, assume it's inadvertent and set "hasScrolled" to true
- onMouseUp, only open the node if "hasScrolled" is false

**Comment by Enselic** [comment]
Why not simply use 'click' instead of 'mouseup'/'touchend'? I have created a pull-request with this fix. If you want to test how it works, my fork with that fix applied runs here: https://enselic.github.io/

I have only done some quick sanity testing and the fix at least fixes the super-annoying bug reported in this issue. I have not found any other problems, but then again: I have not performed extensive testing.
