### ISSUE TITLE
docker.github.io/machine/reference/scp.md is very sparse

### ISSUE THREAD

**Issue by zfrenchee** [docker/docker.github.io#1129]
### Problem description

This page could use a few more examples. My specific issue is here: 

http://stackoverflow.com/questions/41651212/how-to-move-a-local-volume-onto-a-remote-docker-machine

And the docs don't answer my question, which I feel like they should, since it's a narrow question about `docker-machine scp` and a common use case I suspect. 

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/machine/reference/scp/

### Suggestions for a fix

I think a couple more examples could go a long way to improving this page. I'm particularly interested in my use case but I imagine there are other common ones as well.

**Comment by londoncalling** [comment]
@fresnizky thanks for your feedback on this.

I just added some detail to `docker-machine scp` reference around your example. I know it's an issue specific to your use case, but I think the understanding the idea of copying to remote systems for deployment is useful in a more general sense. I contextualized your use case as a sort of second example, beyond the use of `scp` and more about file paths on remote systems. We are somewhat de-emphasizing `docker-machine` going forward but if you have ideas for more pointers that can help those docs, please do send, and we'll have a look at them.

**Comment by zfrenchee** [comment]
@londoncalling no worries I solved these issues long long ago. =) Thanks for patching up the docs though.
