### ISSUE TITLE
how to setup docker

### ISSUE THREAD

**Issue by khinmyomyat558** [docker/docker.github.io#11303]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
@khinmyomyat558 Suggest you take a look at the following topics to learn how to set up Docker:

- https://docs.docker.com/get-docker/
- https://docs.docker.com/get-started/
