### ISSUE TITLE
notes for "Shell form ENTRYPOINT example" need to be cleaned up

### ISSUE THREAD

**Issue by jf** [docker/docker.github.io#11319]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

These points relate to https://docs.docker.com/engine/reference/builder/#shell-form-entrypoint-example.  Several points:

1. The following Dockerfile does not build:
```
FROM ubuntu
ENTRYPOINT top -b
CMD --ignored-param1
```

```
# docker build -t top .
Sending build context to Docker daemon  70.14kB
Error response from daemon: Dockerfile parse error line 6: Unknown flag: ignored-param1
#
```

2. command output conflicts with argument(s?) to `docker run` in the example given:
```
$ docker run -it --name test top --ignored-param2

Mem: 1704184K used, 352484K free, 0K shrd, 0K buff, 140621524238337K cached
CPU:   9% usr   2% sys   0% nic  88% idle   0% io   0% irq   0% sirq
Load average: 0.01 0.02 0.05 2/101 7
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
    1     0 root     S     3168   0%   0% /bin/sh -c top -b cmd cmd2
    7     1 root     R     3164   0%   0% top -b
```
Command gives `--ignored-param2`, while output uses `cmd cmd2`. _This is besides the fact that the container's output from top does not reveal the command line arguments for both `sh` and `top`; you need to use `docker top test` for that._

3. The table at https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact needs to be updated. Specifically the `ENTRYPOINT exec_entry p1_entry`, with `CMD exec_cmd p1_cmd` entry. I get `/bin/sh -c exec_entry p1_entry sh -c exec_cmd p1_cmd`

**Comment by StefanScherer** [comment]
Thanks @jf, I'll make a PR in [github.com/docker/cli](github.com/docker/cli ) repo for 1. and 2. See https://github.com/docker/cli/pull/2704 and https://github.com/docker/cli/pull/2705 for a backport to 19.03.

For 3. the table looks good to me.

**Comment by jf** [comment]
My testing for the table shows otherwise. Have you tested it?

**Comment by StefanScherer** [comment]
Yes I have tested it. How did you test it?
I replaced `exec_entry` with `echo` and looked what gets echoed.

**Comment by jf** [comment]
If you only look at the output, how do you verify that `echo` got run with `sh -c echo`?

**Comment by jf** [comment]
It's either that the table has to be changed.. or the statement that `The shell form prevents any CMD or run command line arguments from being used, ...` has to be changed.

```
FROM ubuntu
ENTRYPOINT top -b
CMD exec_cmd p1_cmd
```

`docker build ...`
`docker run --name test ...`
`docker top test`

**Comment by jf** [comment]
```
# docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by jf** [comment]
> It's either that the table has to be changed.. or the statement that `The shell form prevents any CMD or run command line arguments from being used, ...` has to be changed.
> 

@StefanScherer can you confirm which is correct?

**Comment by StefanScherer** [comment]
@jf OK, your investigation looks correct. I've verified it on a Mac like this:

1. Create file `sh.go`

```golang
package main

import (
    "fmt"
    "os"
)

func main() {
    fmt.Println(os.Args)
}
```

2. Build it for Linux statically

```shell
$ GOOS=linux go build sh.go
```

3. Create a `Dockerfile`

```dockerfile 
FROM scratch
COPY sh /bin/sh
ENTRYPOINT exec_entry p1_entry
CMD exec_cmd p1_cmd
```

4. Build the test image

```shell
$ docker build -t test .
```

5. Run the container

```shell
$ docker run test
[/bin/sh -c exec_entry p1_entry /bin/sh -c exec_cmd p1_cmd]
```

**Comment by jf** [comment]
yeah, I know because I did see the result of `docker top`... but also because I investigated the process data (not necessary, but just helps to confirm things) in the container. Now the question remains: is this a bug? is it still intended that, according to the doc `The shell form prevents any CMD or run command line arguments from being used`? Which is it?

**Comment by jf** [comment]
(Your `echo` test, btw, failed because it would have been (breaking up the parameters) run as `/bin/sh`, `-c`, `echo`, `/bin/sh`,`-c`, `exec_cmd p1_cmd`. All of those arguments after `echo` got passed as arguments to `/bin/sh`, and not to `echo`)

**Comment by jf** [comment]
But coming back to what I would like to verify (or else I could have just done the PR to `docker/cli` myself): is this a bug and the intention of `The shell form prevents any CMD or run command line arguments from being used` still remains the same... or has that changed? Can you help me with that?

**Comment by StefanScherer** [comment]
I've adjusted my sample code a bit

sh.go:

```golang
package main

import (
	"encoding/json"
	"fmt"
	"os"
)

func main() {
	argsJson, _ := json.Marshal(os.Args)
	fmt.Printf("%s\n", argsJson)
}
```

Dockerfile:
```dockerfile
FROM golang:alpine as build
COPY sh.go sh.go
RUN go build sh.go

FROM scratch
COPY --from=build /go/sh /bin/sh
COPY --from=build /go/sh exec_entry
COPY --from=build /go/sh exec_cmd

ENTRYPOINT ./exec_entry p1_entry
# ENTRYPOINT [ "./exec_entry", "p1_entry" ]
CMD ./exec_cmd p1_cmd
# CMD [ "./exec_cmd", "p1_cmd" ]
```

Now no external dependencies are needed to play with all combinations of `ENTRYPOINT` and `CMD`.

```shell
$ docker build -t test .

$ docker run test
["/bin/sh","-c","./exec_entry p1_entry","/bin/sh","-c","./exec_cmd p1_cmd"]

$ docker run test cmd1 p1
["/bin/sh","-c","./exec_entry p1_entry","cmd1","p1"]
```

At least the shell form prevents the CMD to be used. A second /bin/sh normally doesn't make sense in the command line, but of course depends on what the entrypoint does with it.

I you like you could draft a PR to update the table in docker/cli repo.

**Comment by jf** [comment]
> Now no external dependencies are needed to play with all combinations of `ENTRYPOINT` and `CMD`.

this is great! thanks.

> At least the shell form prevents the CMD to be used. A second /bin/sh normally doesn't make sense in the command line, but of course depends on what the entrypoint does with it.

Surely the shell form still does something with the CMD provided in the Dockerfile? That was my point and why I say the documentation isnt really correct.

> I you like you could draft a PR to update the table in docker/cli repo.

Thanks. I can. Just not too sure about (as I've said) whether this is a bug in the doc, or if the behaviour has changed.
