### ISSUE TITLE
Mutagen not available on edge

### ISSUE THREAD

**Issue by leonboot** [docker/docker.github.io#11327]
File: [docker-for-mac/mutagen.md](https://docs.docker.com/docker-for-mac/mutagen/)

The documentation mentions a toggle for enabling Mutagen based file synchronisation in the Preferences > Resources > File sharing window which is not present in the current edge version (2.3.6.0, build 47622).

**Comment by usha-mandya** [comment]
@leonboot Thanks for your feedback. Mutagen has been removed from Docker Desktop 2.3.5.0. Please see https://docs.docker.com/docker-for-mac/edge-release-notes/#docker-desktop-community-2350.
