### ISSUE TITLE
Docker run reference page lacks details, options, and structure

### ISSUE THREAD

**Issue by PerMildner** [docker/docker.github.io#11321]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

The reference page is not suitable as a **reference**.

- It lacks several options (`--env`, ...), i.e. it does not describe all options that `docker run --help` outputs.
- it lacks a reference-style list of options, it's just an "essay"
- it lacks details about the option values, e.g. `docker run --help` says that several options takes a `list` argument, but `list` is not described anywhere, and `list` is not mentioned at the reference page and not present in the examples I looked at.

It would be helpful if each command was described in a more formalized way, with a list of all options (like `docker run --help` does, but with details). The current tutorial-style text is nice as a tutorial but unsuitable as reference.

```
% docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference
