### ISSUE TITLE
Wrong Linking to download

### ISSUE THREAD

**Issue by Tutuviz** [docker/docker.github.io#11343]
File: [docker-for-windows/install-windows-home.md](https://docs.docker.com/docker-for-windows/install-windows-home/#install-docker-desktop-on-windows-10-home/)

In the topic "Install Docker Desktop on Windows 10 Home" 1.1 the link to the installer for Windows 10 Home is the same for the installer on other Windows's versions (Pro, Enterprise or Education), even when the installer must be different because of de Hiper-V situation

**Comment by usha-mandya** [comment]
@Tutuviz Thanks for the feedback. Docker Desktop started supporting on Windows Home since Docker Desktop version 2.3.0.2. If you are using Docker Desktop version 2.3.0.2 or later, you should be able to install Docker Desktop using the same URL. Hope that helps.
