### ISSUE TITLE
Feedback for: engine/installation/linux/centos.md

### ISSUE THREAD

**Issue by bish0polis** [docker/docker.github.io#1134]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

CentOS7 ships with v3.10 of the kernel by default.  There's no actual way someone can install centos7 without having kernel 3.10 .   The version pinning is one of the main deliverables of enterprise linux.  

So, no need to say "you should have this version of the kernel" if one is installing it on centos7.  It's confusing to say so and should be removed.

**Comment by mstanleyjones** [comment]
This content was completely rewritten for Engine 1.13, including addressing your feedback here. Please take a look!
