### ISSUE TITLE
The formatting of the sidebar is unreadable on smaller screens

### ISSUE THREAD

**Issue by ingshtrom** [docker/docker.github.io#11366]
### Problem description
On desktop when I have my screen split and I open the sidebar from the hamburger menu, it just overlays the current text without additional formatting, so I cannot read it. I have attached a quick video of it happening to better describe it.

https://drive.google.com/file/d/1hajRmJ5zpw46wf_tszl6lFmyjgZIdsvX/view?usp=sharing

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/registry/deploying/

- Other: I'm guessing since there is a sidebar almost everywhere, then this issue would apply everywhere

### Project version(s) affected
n/a

### Suggestions for a fix
I'm taking a look to see if it is an easy fix

**Comment by usha-mandya** [comment]
Thank you @ingshtrom for the feedback. I was able to easily reproduce this issue. Please let me know how you get on with fixing it :)
