### ISSUE TITLE
unable to access https://docs.docker.com/engine/admin/ambassador_pattern_linking.md

### ISSUE THREAD

**Issue by Niteshbhat** [docker/docker.github.io#11365]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
@Niteshbhat Thank you for the feedback. I was not able to find this URL within our docs. Could you let me know where you found this URL? Also, please let me know the information you are looking for?

**Comment by thaJeztah** [comment]
closing as this looks to have gone stale
