### ISSUE TITLE
Recommend isolated partition for /var/lib/docker?

### ISSUE THREAD

**Issue by dHannasch** [docker/docker.github.io#11364]
File: [config/daemon/index.md](https://docs.docker.com/config/daemon/)

I am running Docker automatically on a server.
A problem I run into is that /var/lib/docker grows to fill the entire disk.
In theory, the solution is trivial: a cron job to docker system prune. In practice, usage is bursty, and the disk tends to fill up between runs of docker system prune. And when the disk is full, nothing works, including docker system prune.
As far as I know, there is no way to configure Docker itself to restrict disk usage. (And I certainly wouldn't know how to make a pull request to do that.) The best solution I know of is to create a separate partition and mount /var/lib/docker there. Then, if a request tries to exceed the storage available, it will simply fail rather than hose the system.

I am thinking of editing the documentation to recommend this as a best practice when running Docker on a server. https://docs.docker.com/config/daemon/ seems like perhaps the natural place to mention it, though it's not exactly tied to Docker's configuration per se (Docker itself doesn't really know about the mount).

Comments? Would there be a better place to address disk usage limitation?

**Comment by usha-mandya** [comment]
@dHannasch Thanks a lot for the feedback. I believe it would be good to discuss this in the upstream https://github.com/moby/moby/issues repository. I'm closing this issue here for that reason. Please feel free to continue the conversation here after I close. Thanks again.
