### ISSUE TITLE
broken link to https://github.com/docker/scan-cli-plugin/issues/new in https://docs.docker.com/engine/scan/

### ISSUE THREAD

**Issue by thomas-riccardi** [docker/docker.github.io#11380]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/scan/

- Link for feedback is broken: https://github.com/docker/scan-cli-plugin/issues/new returns 404

**Comment by thaJeztah** [comment]
Thanks for reporting; I see that the repository for the scan-cli is not (yet) open source. Was there a fix you wanted to suggest for that page?

**Comment by thomas-riccardi** [comment]
Hello @thaJeztah 
no fix to suggest, I just wanted to find early access to linux scan cli, like buildx was accessible before being shipped with docker-cli, and found that link :), inaccessible :(
I'll wait some more then.
