### ISSUE TITLE
docker config.json - 'alias' for repo fqdn

### ISSUE THREAD

**Issue by sooslaca** [docker/docker.github.io#11388]
Hello Team,

### Problem description
It's a feature request/idea.
We're deploying in AWS and pulling from long FQDNs causing inconsistency against accounts for compose files.
Host format is: **<aws_account_id>.dkr.ecr.<region>.amazonaws.com.**
Where **aws_account_id** is changing between aws accounts.

For docker pull can't there be a **hostalias** config.json variable introduced where we can define a short name for this?
like define "<aws_account_id>.dkr.ecr.<region>.amazonaws.com." --> alias: "myregistry"

then instead of
`docker pull <aws_account_id>.dkr.ecr.<region>.amazonaws.com/image`
we should be able to do
`docker pull myregistry/image`

### Problem location
docker pull, docker compose file image definition

### Project version(s) affected
As much as I know this feature does not exists in any docker version

### Suggestions for a fix
Feature request explanation written above.

Thank you

**Comment by craig-osterhout** [comment]
Thanks for sharing this. For feature requests to the CLI, please create an issue in the repo at https://github.com/docker/cli
