### ISSUE TITLE
404 at: /v1.9/reference/api/docker_remote_api/

### ISSUE THREAD

**Issue by artheus** [docker/docker.github.io#1140]
URL: /v1.9/reference/api/docker_remote_api/

Link is erroneous in the first paragraph of the following documentation page
https://docs.docker.com/v1.9/swarm/api/swarm-api/

**Comment by artheus** [comment]
Should be pointing to /v1.9/engine/reference/api/docker_remote_api/

**Comment by johndmulhausen** [comment]
Fixed by 22410f4de5f547f6063e9d90a2c75dea1492c3d3
