### ISSUE TITLE
Add screenshot under Install #1 on where to enable WSL

### ISSUE THREAD

**Issue by bevin0708** [docker/docker.github.io#11407]
File: [docker-for-windows/wsl.md](https://docs.docker.com/docker-for-windows/wsl/)

Please provide a screenshot on where during the installation WSL needs to be enabled.
I just reinstalled Docker 2.3.05 and did not receive any prompt.

Or can it be enabled on an existing docker installation?

**Comment by usha-mandya** [comment]
@bevin0708 Thanks for the feedback.

Do you have a system that supports WSL 2? If you meet the system requirements, Docker Desktop prompts you to enable WSL 2 during installation. You can find information about the system requirements at https://docs.docker.com/docker-for-windows/wsl/#prerequisites.

**Comment by craig-osterhout** [comment]
Closing this issue as stale. If the issue still persists, please provide the details requested in the previous comment. 

To verify if WSL 2 is already installed and running, view the Microsoft documentation link in the topic. If you run the following command, you can view which version of WSL is installed and its status
wsl -l -v
