### ISSUE TITLE
Should specify this is using the "docker run" command

### ISSUE THREAD

**Issue by AquaDocs** [docker/docker.github.io#11420]
File: [config/containers/container-networking.md](https://docs.docker.com/config/containers/container-networking/)

For people really familiar with docker, this might be obvious, but for those just learning how docker works, the "-p" options should be specified as "docker run -p" to prevent possible confusion for those of us who are new to the whole docker thing.

Thanks!

**Comment by AquaDocs** [comment]
Thanks!

**Comment by thaJeztah** [comment]
Thanks for reporting!
