### ISSUE TITLE
security-opt Credential Spec

### ISSUE THREAD

**Issue by jimbo8098** [docker/docker.github.io#11421]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

Is is worthwhile adding the "credentialspec" security-opt to the run reference as per Microsoft's documentation?

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/gmsa-run-container

This is quite a large part of running containers with gMSA which I would say is one of the larger advantages to running an MS backend, especially when paired with MSSQL.

**Comment by craig-osterhout** [comment]
Thanks for sharing this. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference
