### ISSUE TITLE
Feedback for: docker-hub/official_repos.md

### ISSUE THREAD

**Issue by deannm** [docker/docker.github.io#1142]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by sanscontext** [comment]
Hi @deannm, can you describe your issue? Otherwise I'll assume this was filed accidentally and close it out.

**Comment by sanscontext** [comment]
No actual problem in the issue, I'm going to close this out.
