### ISSUE TITLE
Error in Content Digests: algorithm grammar

### ISSUE THREAD

**Issue by palbr** [docker/docker.github.io#11437]
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/)

In section "Content Digests" one can read

> We define a digest string to match the following grammar:
>digest      := algorithm ":" hex
>algorithm   := /[A-Fa-f0-9_+.-]+/
> ...

I think, the line `algorithm   := /[A-Fa-f0-9_+.-]+/` should be changed to `algorithm   := /[A-Za-z0-9_+.-]+/`, since "sha256" would need the letter "s" and "h".

Apart from that, excelent documentation! Thank you!

**Comment by thaJeztah** [comment]
Thanks for reporting; we fetch that page of the documentation from the upstream docker/distribution repository; https://github.com/docker/distribution/tree/master/docs/spec

I recall there have been some fixes for these, but perhaps there's one that's not been merged yet (or no pull request made for that yet); could you check if the upstream file has the problem still?

We may be pulling our docs from the latest release branch (https://github.com/docker/distribution/tree/release/2.7/docs/spec), so it's possible a fix is present on that master branch, but not back ported yet

**Comment by palbr** [comment]
Seems to be upstream fix: https://github.com/docker/distribution/pull/3255

Pull-Request not yet merged. So I guess we can close this issue.
