### ISSUE TITLE
Finding out about my own pull rate

### ISSUE THREAD

**Issue by benny-burkhart** [docker/docker.github.io#11432]
File: [docker-hub/download-rate-limit.md](https://docs.docker.com/docker-hub/download-rate-limit/)

Docker Hub is planning to introduce pull rate limiting: https://docs.docker.com/docker-hub/download-rate-limit/

Looking through my account, I cannot find a place where the number of pulls is listed.

Would it be good to document where to find out about the number of pulls that I've made?

**Comment by jaythamke** [comment]
Hello,
I have the same question. From the [docker slack channel](https://dockercommunity.slack.com/archives/C7GKACWDV/p1603478847221000?thread_ts=1603356076.179600&cid=C7GKACWDV) thread I came to know that the rate could be measured by using response header. But still not clear. May be docker colleagues could answer in detail for authenticated (but non paid) user and anonymous pull.
Anonymous pull rates is calculated by IP address. 

Some blogs - https://www.docker.com/blog/understanding-inner-loop-development-and-pull-rates/
https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/ 

regards,
Jayesh

**Comment by jaythamke** [comment]
Hi @usha-mandya could you please comment on this issue/request? Thanks

**Comment by usha-mandya** [comment]
Hello @benny-burkhart The links to blog posts shared above by @jaythamke might help answer the questions you have about pull requests.

Hey @jaythamke Thanks for your feedback. We are in the process of updating our docs to include information on how to check rate limits using headers. Watch this space.

**Comment by benny-burkhart** [comment]
Thank y'all -- the question remains where a subscriber can find out their own current pull rate. 

[Docker's recent blog post](https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/) says:
> Excessive usage/abuse of Pro and Team limits will be initially managed through a process where a customer will be informed about the usage overage through email as well as the ability to get usage information in response headers from Docker Hub.

My interpretation is that a way to request one's own pull rate may be implemented later. Is this correct?

**Comment by usha-mandya** [comment]
Hey @benny-burkhart and @jaythamke Here's the link to the updated docs that now describe how to check your current rates - https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by jaythamke** [comment]
Hi @usha-mandya , thank you for comment and updating docs. By the way I have tried _grep_ ing header for manifest of our repository, it did not show the RateLimit header yet. Is the new policy applied only for `ratelimitpreview/test` image?

```
curl -v -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/stewardci/stewardci-tenant-controller/manifests/TEST_201022_34a4187 2>&1 | grep RateLimit
```
