### ISSUE TITLE
What is ment by "Have your code in your default Linux distribution?"

### ISSUE THREAD

**Issue by hanjoosten** [docker/docker.github.io#11469]
File: [docker-for-windows/wsl.md](https://docs.docker.com/docker-for-windows/wsl/)

I am trying to set up a development environment for a Haskell project. I have a windows 10 machine with two drives locally. (`C:\` and `D:\`). I have installed wsl2 and docker. I use vscode with the devcontainer stuff. 

When I open my project (which is on the D:\ - drive, for my C:\ drive has limited space), I get a warning that I should have my code somewhere else. A reference to this page is nicely provided. It reads:

```
We recommend that you have your code in your default Linux distribution for the best development experience using Docker and WSL 2
```
I do not understand what this means. I have ubuntu as my default Linux distribution. How can I have my code in ubuntu? 
Please elaborate what this scentence means.

**Comment by thaJeztah** [comment]
@stephen-turner ptal

**Comment by stephen-turner** [comment]
@hanjoosten WSL 2 has its own file system. If you open a WSL 2 terminal, and type `ls`, that's where you want your files to be, for performance reasons. This link from Microsoft might help: https://docs.microsoft.com/en-us/windows/wsl/compare-versions
