### ISSUE TITLE
There is an ERROR in scripts. 

### ISSUE THREAD

**Issue by gglee4ai** [docker/docker.github.io#11473]
File: [get-started/nodejs/develop.md](https://docs.docker.com/get-started/nodejs/develop/)

I copied and pasted all scripts in my local computer, however I got errors

```
$ docker-compose -f docker-compose.dev.yml up --build
ERROR: The Compose file './docker-compose.dev.yml' is invalid because:
Unsupported config option for services.volumes: 'mongodb'
```

Please check this. 
My system is docker-desktop for MAC.

**Comment by anthony-malkoun** [comment]
Having just come across this, the indentation is invalid. Make sure that the `volumes` stanza isn't indented under the `services` stanza.

**Comment by thaJeztah** [comment]
looks like this was fixed in https://github.com/docker/docker.github.io/pull/11724. Let me close this ticket, but feel free to continue the conversation if there's still an issue
