### ISSUE TITLE
Enter doesn't submit search request

### ISSUE THREAD

**Issue by vikstrous** [docker/docker.github.io#1147]
To repro:

1. type `healthcheck` into the search bar
2. hit enter
3. nothing happens

In the javascript console I see:
```
https://api.segment.io/v1/p net::ERR_BLOCKED_BY_CLIENTo @ analytics.min.js:5i @ analytics.min.js:5w.send @ analytics.min.js:5w.onpage @ analytics.min.js:5(anonymous function) @ analytics.min.js:5o.emit @ analytics.min.js:6(anonymous function) @ analytics.min.js:6o._invoke @ analytics.min.js:1(anonymous function) @ analytics.min.js:6o.page @ analytics.min.js:1(anonymous function) @ analytics.min.js:6(anonymous function) @ analytics.min.js:1o.2../analytics @ analytics.min.js:1i @ analytics.min.js:1e @ analytics.min.js:1(anonymous function) @ analytics.min.js:1(anonymous function) @ analytics.min.js:8
```

Chrome version: 54.0.2840.100 (Official Build) (64-bit)
Revision	ed651c97177b2ac846b27f62bb8efed6dac0f90b-refs/branch-heads/2840@{#833}

OS: nixos (unstable branch)

relevant addons: adblock, ublock origin, https everywhre
I disabled all of them while testing this though.

**Comment by mstanleyjones** [comment]
I think @johndmulhausen fixed this. Can you please try it again?

**Comment by vikstrous** [comment]
works now
