### ISSUE TITLE
Feedback for: docker-cloud/builds/advanced.md

### ISSUE THREAD

**Issue by imissyouso** [docker/docker.github.io#115]
URL: docker-cloud/builds/advanced.md

Hi! It would be very useful to present some examples of hook files. 

I've found this https://github.com/tutumcloud/builder/blob/staging/build.sh
but I am not sure that it's the same with your execution script.
I used this file for logic understanding but have no results.
I saw the line like:
`docker build --rm --force-rm -t this .`
what is `this` in this context?

**Comment by sanscontext** [comment]
Hey there, I checked with the team, and we're no longer using the `tutumcloud/builder` image in Cloud. (We're now using a better build system that's also available in UCP.) I'm afraid I can't really tell you what `this` means in the context above.  

But you're right, it'd be nice to have some examples! I'll try to get something in the doc in the next week or so. In the mean time, you might try checking with folks on the [Docker Cloud Forums](https://forums.docker.com/c/docker-cloud) to see what they're doing?
