### ISSUE TITLE
Broken links from https://www.docker.com/products/developer-tools

### ISSUE THREAD

**Issue by bradym** [docker/docker.github.io#11503]
### Problem description

There are two broken links in the "Integrated Developer Tools" section on https://www.docker.com/products/developer-tools that are pointing to urls on docs.docker.com:

- https://docs.docker.com/assemble/install/
- https://docs.docker.com/app-template/working-with-template/

### Problem location

- I saw a problem on the following URL: https://www.docker.com/products/developer-tools

The two broken links are highlighted below

![image](https://user-images.githubusercontent.com/289182/95401944-5ef9b480-08c3-11eb-817e-dfc9667bf867.png)

**Comment by thaJeztah** [comment]
Thanks for reporting; I asked the marketing team, who maintains the main website to have a look 👍
