### ISSUE TITLE
Missing data for example

### ISSUE THREAD

**Issue by austin752** [docker/docker.github.io#11518]
File: [get-started/nodejs/develop.md](https://docs.docker.com/get-started/nodejs/develop/)

This page talks abut opening the notes-service project that was previously created - a notes-service project was not created.
The project that was built was a bulletin board. Also, there is no link to see or download the notes-service project, if that is what is to be used for the example.

       "The notes-service project uses MongoDB as its data store. If you remember from Part I of this series, we had to start the 
        Mongo container manually and connect it to the same network that our notes-service is running on. We also had to create 
        a couple of volumes so we could persist our data across restarts of our application and MongoDB"

The examples I used in the Getting Started section did not go through connecting to MongoDB.

**Comment by StefanScherer** [comment]
Thanks for raising this issue. Indeed, we lost a chapter from https://www.docker.com/blog/getting-started-with-docker-using-node-part-ii/ when we transferred the blog post into our docs. In the meantime, please have a looks at the blog post where we introduced the database.
