### ISSUE TITLE
docker stack privileged issue

### ISSUE THREAD

**Issue by shencangsheng** [docker/docker.github.io#11525]
I configure the privileged : true configuration in stack.yml and docker stack deploy -c stack.yml warns "Ignoring unsupported options: privileged ", I'd like to know how to get true root permissions for the container in stack.yml.

**Comment by thaJeztah** [comment]
The container can run as `root` (and many containers do so by default); the `privileged` option controls other security options (effectively, using `privileged: true` or `--privileged` disables all security options on a container, therefore making it a security risk to run it in a swarm setup. 

More discussion on this can be found in https://github.com/moby/moby/issues/24862 and https://github.com/docker/swarmkit/issues/1030

Given that this  issue is not related to the documentation, I'll close, but feel free to continue the conversation
