### ISSUE TITLE
Make it clear in documentation that the installer for Windows Home is the same as the installer for Windows Pro

### ISSUE THREAD

**Issue by urig** [docker/docker.github.io#11546]
File: [docker-for-windows/install-windows-home.md](https://docs.docker.com/docker-for-windows/install-windows-home/)

The button that says "Download from Docker Hub" appears right after the paragraph that explains the difference between Docker Desktop on Windows 10 Home and Docker Desktop on Windows 10 Pro, Enterprise or Education.

I find it a bit confusing that the button leads to the Docker Desktop for Windows download page where requirements state Requires Microsoft Windows 10 Professional or Enterprise 64-bit.

It might be better to explain in the document that the installer is the same for both options. Also, to update the requirements in the download page.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The docs have been updated with all requirements listed on the same page.

**Comment by urig** [comment]
Thank you craig 🌷
