### ISSUE TITLE
Link is broken 

### ISSUE THREAD

**Issue by xjmo1688** [docker/docker.github.io#11545]
The link on the page https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch08-aws.adoc at "Requirements 1.Permissions" to
https://docs.docker.com/docker-for-aws/iam-permissions/
was broken. 
Can't follow the workshop. Please check.

**Comment by thaJeztah** [comment]
Thanks for reporting; Docker for AWS is a legacy product that no longer exists, so we should probably update that tutorial.

You may be interested in the integration with ECS that's currently in Beta; https://docs.docker.com/engine/context/ecs-integration/


/cc @justincormack @nebuk89
