### ISSUE TITLE
404 at /develop/develop-images/dockerfile_best-practices/%E2%80%A2

### ISSUE THREAD

**Issue by rifana14** [docker/docker.github.io#11569]
I found a broken link : https://docs.docker.com/develop/develop-images/dockerfile_best-practices/%E2%80%A2

**Comment by thaJeztah** [comment]
Thanks for reporting; do you remember where you found that broken link? I checked the source code in this repository, and couldn't find it, but perhaps it was fixed already

**Comment by thaJeztah** [comment]
closing, as this looks to have gone stale
