### ISSUE TITLE
404 at /compose/networking/swarm.md

### ISSUE THREAD

**Issue by andrii482** [docker/docker.github.io#11575]
I found a broken link : https://docs.docker.com/compose/networking/swarm.md
I arrived on this page through: https://docs.docker.com/compose/networking/

**Comment by thaJeztah** [comment]
Thanks for reporting; that page deals with overlay networks in the legacy (and deprecated) "classic" swarm. If you're looking for information about overlay networking for docker swarm services, please have a look at this page instead; https://docs.docker.com/network/network-tutorial-overlay/

I'll open a pull request to remove the links to the now deprecated pages
