### ISSUE TITLE
404 at /develop/develop-images/dockerfile_bestpractices

### ISSUE THREAD

**Issue by praveenthcruz** [docker/docker.github.io#11580]
I found a broken link : https://docs.docker.com/develop/develop-images/dockerfile_bestpractices

**Comment by thaJeztah** [comment]
Thanks for reporting; I did a quick search in our repository, but couldn't find that link; where did you find the link to that page?

The correct link should be https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ (a `-` between `dockerfile_best` and `practices`)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This issue will be closed as stale. If the issue still persists, please provide the details requested in the previous comment.
