### ISSUE TITLE
The links to BusyBox,  CentOS / Scientific Linux CERN (SLC) on Debian/Ubuntu or on CentOS/RHEL/SLC/etc., And Debian / Ubuntu are broken

### ISSUE THREAD

**Issue by TheOtherRealm** [docker/docker.github.io#11590]
File: [develop/develop-images/baseimages.md](https://docs.docker.com/develop/develop-images/baseimages/)
These links point to a repository that no longer exists
....
There are more example scripts for creating parent images in the Docker GitHub Repo:
[BusyBox](https://github.com/moby/moby/blob/master/contrib/mkimage/busybox-static)
CentOS / Scientific Linux CERN (SLC) on [Debian/Ubuntu](https://github.com/moby/moby/blob/master/contrib/mkimage/rinse) or on [CentOS/RHEL/SLC/etc.](https://github.com/moby/moby/blob/master/contrib/mkimage-yum.sh)
[Debian / Ubuntu](https://github.com/moby/moby/blob/master/contrib/mkimage/debootstrap)
....

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It looks like it was fixed in https://github.com/docker/docker.github.io/commit/340fe84d1ba4729dd3500214d69816b657d44473
If the issue still persists, please let us know.
