### ISSUE TITLE
Title is misleading

### ISSUE THREAD

**Issue by eelcowen** [docker/docker.github.io#11592]
File: [compose/startup-order.md](https://docs.docker.com/compose/startup-order/)

Please add info about shutdown order or remove this from the title.

**Comment by thaJeztah** [comment]
Could you elaborate what kind of information you're looking for? I see this as the first paragraph;

> You can control the order of service startup and shutdown with the depends_on option. Compose always starts and stops containers in dependency order, where dependencies are determined by depends_on, links, volumes_from, and network_mode: "service:...".

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as stale. If issue is still applicable, please provide the details requested in the previous comment.
