### ISSUE TITLE
Docker Volume Plugin contract

### ISSUE THREAD

**Issue by chrisbecke** [docker/docker.github.io#11607]
File: [engine/extend/plugins_volume.md](https://docs.docker.com/engine/extend/plugins_volume/)

As someone interested in implementing a docker volume plugin this page is distressingly sparse on detail.

Unanswered questions include:

* What is the expected behaviour of Get and Path when called on volumes that have not been mounted?
* What is the expected implementation for Remove for Scope=global plugins?
* What are the expectations of a plugin that answers Scope=global to Capabilities?
* What is the expected behaviour on Unmount if the ID passed mismatches the ID passed to mount?
* What are expected values for "Status" in the call to Get?
* Why do https://github.com/docker/go-plugins-helpers/blob/master/volume/api.go mention "CreatedAt" as a response field to Get, but this page does not?

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular topic is maintained in an upstream repo. If the issues are still applicable, please help create an issue or a PR in the source repo at https://github.com/docker/cli/tree/master/docs/extend 
Closing this issue as unable to fix in this repo.
