### ISSUE TITLE
Err: failed to register layer: ApplyLayer exit status 1 stdout: stderr: no such file or directory

### ISSUE THREAD

**Issue by kami1983** [docker/docker.github.io#11602]
I got an err, when I set up " --data-root=mydir " on MacOs 10.15.7
```

   $ docker pull centos 
   failed to register layer: ApplyLayer exit status 1 stdout:  stderr: no such file or directory  

```
What's the problem? Thanks.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
For support, please try the Docker Community Slack or Forums:
- https://dockercommunity.slack.com/
- https://forums.docker.com/
