### ISSUE TITLE
404 at /compose/production/swarm.md

### ISSUE THREAD

**Issue by ktowen** [docker/docker.github.io#11606]
I found a broken link : https://docs.docker.com/compose/production/swarm.md
I arrived on this page through: https://docs.docker.com/compose/production/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. I was unable to find any link to https://docs.docker.com/compose/production/swarm.md via the current https://docs.docker.com/compose/production/ . If you're still experiencing an issue, please let us know which link on https://docs.docker.com/compose/production/  brought you to https://docs.docker.com/compose/production/swarm.md.
