### ISSUE TITLE
404 in README to .NOT_EDITED_HERE.yaml

### ISSUE THREAD

**Issue by charlottemach** [docker/docker.github.io#11616]
### Problem description

Link in README leads to 404
https://github.com/docker/docker.github.io/blob/master/.NOT_EDITED_HERE.yaml

> ### Files not edited here
> 
> Files and directories listed in the `path:` keys in
> [`.NOT_EDITED_HERE.yaml`](.NOT_EDITED_HERE.yaml) are maintained in other
> repositories and should not be edited in this one. Pull requests against these
> files will be rejected. Make your edits to the files in the repository and path
> in the `source:` key in the YAML file.
> 

### Problem location

README.md 

### Suggestions for a fix

File was removed here (https://github.com/docker/docker.github.io/commit/4dc252c910e6b82a1348aad37eb8428139390a85).

**Comment by craig-osterhout** [comment]
Thank you for sharing the issue. This appears no longer applicable. If you are still experiencing the issue, please provide more details.
