### ISSUE TITLE
Linux container reaching Windows Host documentation is wrong or there's a bug

### ISSUE THREAD

**Issue by alexlian** [docker/docker.github.io#11622]
File: [docker-for-windows/networking.md](https://docs.docker.com/docker-for-windows/networking/)

Following instructions for "I WANT TO CONNECT FROM A CONTAINER TO A SERVICE ON THE HOST" fails for me on my Windows Docker Desktop.

Diagnostics: 0599A95D-DF64-45D2-9D63-0F025ABE50D1/20201024213021

**Comment by aevesdocker** [comment]
Closing ticket as this should be reported to https://github.com/docker/for-win/issues
