### ISSUE TITLE
Configuring Webcam with Docker

### ISSUE THREAD

**Issue by Sherry112** [docker/docker.github.io#11629]
### Problem description
Hello, I am using OpenCV in a Python Flask App which uses Facial encoding for Employee registration. I have used a production server using Gunicorn. 
`gunicorn --config gunicorn_config.py app:app`
The gunicorn_config file is as follows:
`bind = "0.0.0.0:5000"
threads = 4
certfile="localhost.crt"
keyfile="private.key"
accesslog="-"
loglevel = 'info'
errorlog="-"
`

I am deploying my App on Docker containers. I have first created a docker image and then used Docker compose to deploy it. I am running the docker app as follows: 

`docker run -t --env="DISPLAY" --volume="/tmp/.X11-unix://tmp/.X11-unix:rw" --device="/dev/video0:/dev/video0" -p 5000:5000 -d docker-flask .`

I have followed this tutorial for this: https://medium.com/@zwinny/docker-using-webcam-9fafb26cf1e6

The problem I am facing now is that when any person hits the URL at port 5000(which I am mapping) it always opens the camera connected to the NUC where the docker container is running, while I want the camera connected to the local computer to run.

I am using OpenCV for facial registration and so am accessing the camera using the following code.
`camera = cv2.VideoCapture(0)`

I have tried modifying the number in Video capture but none of it seems to be working. Please help me on this issue.

**Comment by craig-osterhout** [comment]
Thanks for sharing this. As it is an issue of support and not an issue related to the documentation, I will close it. You may try the Docker Community Forum for help.
