### ISSUE TITLE
Guide broken, fails during run step

### ISSUE THREAD

**Issue by jarethill** [docker/docker.github.io#11628]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

Following the guide exactly as written, entering the run command ```docker run --publish 8000:8080 --detach --name bb bulletinboard:1.0``` fails with this error:

```
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:

npm ERR! /root/.npm/_logs/2020-10-26T04_26_23_908Z-debug.log

```

The package.json does not include a scripts section by default after cloning. I added a start script to the package.json that runs ```node server.js``` and rebuilt, however it doesn't seem to help and still gives the same error.

I'm not sure what I could be doing wrong, I tried the whole process over 3 times from clone to run but it fails at the exact same step every time.

--- 

System Info

- Host OS: Windows 10 with WSL2 (Ubuntu)
- Docker version 19.03.13, build 4484c46d9d
- Set to use Linux Containers

---

**EDIT:**

 Adding the scripts object *does* fix the issue, contrary to my original testing. Bulletinboard repo just needs the package.json updated. Submitted pull request

**Comment by abva222** [comment]
Hi! I actually just ran into this issue myself. The problem is that the dockerfile is trying to run "npm start", which expects a "start" property in the "scripts" object of the package.json.

To fix this you can change your package.json file to this:

**Comment by jarethill** [comment]
> 
> 
> Hi! I actually just ran into this issue myself. The problem is that the dockerfile is trying to run "npm start", which expects a "start" property in the "scripts" object of the package.json.
> 
> To fix this you can change your package.json file to this:

Thank you for responding! I did originally try adding the scripts object in package.json but perhaps I made a typo. I'll give it another shot!

**Comment by abva222** [comment]
No problem! I should add that when I got it running I didn't run headless (I removed the ```--detached``` flag). Also sorry if this is obvious but gotta cover all the bases - but make sure when you alter the package.json file you shut down the container you were running (```docker rm --force bb```), reubild the image (```docker build --tag bulletinboard:1.0 .```) and then start it up again.

**Comment by jarethill** [comment]
> 
> 
> No problem! I should add that when I got it running I didn't run headless (I removed the `--detached` flag). Also sorry if this is obvious but gotta cover all the bases - but make sure when you alter the package.json file you shut down the container you were running (`docker rm --force bb`), rebuild the image (`docker build --tag bulletinboard:1.0 .`) and then start it up again.

Yep it must of been a typo, or maybe I forgot to rebuild after adding the scripts object like you mentioned; regardless the app does indeed work after altering the package.json. Leaving the issue open though so the repo can get updated. Thanks for your help!

**Comment by abva222** [comment]
Good deal, you're welcome!

**Comment by jarethill** [comment]
Issue resolved
