### ISSUE TITLE
Add instructions for how to gracefully connect to the HyperKit vm for advanced users.

### ISSUE THREAD

**Issue by zealoushacker** [docker/docker.github.io#11633]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/)

The [latest release docs](https://docs.docker.com/docker-for-mac/release-notes/#bug-fixes-and-minor-changes) indicate how to use `nc` to connect to and get a shell on the HyperKit VM. This was useful to learn, but unfortunately the default shell prompt is fairly useless, because of a lack of tab completion, lack of support for special chars, etc. It seems like it would be helpful to add the following content to an advanced use section, for those who want to have more introspection into the HyperKit VM:

- Getting a sane prompt
  - this is easily achieved by using `$ stty -echo -icanon && nc -U ~/Library/Containers/com.docker.docker/Data/debug-shell.sock && stty sane`
- Grokking and navigating the file structure of the VM (without modifying it)
  - for example, @nigelpoulton has some great content on this in his PluralSight [Docker Deep Dive](https://app.pluralsight.com/library/courses/docker-deep-dive-update/table-of-contents) course's [Images in Detail](https://app.pluralsight.com/course-player?clipId=04a8b96e-84c5-4fdb-9801-e9c2a1cf2a7d) section. Unfortunately, though a mac user cannot follow that topic in as much detail, without understanding how to connect to the VM, which is a bummer.
- Commands that may be executed on the vm, such as `ctr version`, `ctr -n services.linuxkit tasks ls`, etc.

If there's some support for this request, I'd be happy to work on a PR. @nigelpoulton want to collaborate on it?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As this issue is old, some context may have changed as stuff got superseded or moved around. Closing this as stale, but if applicable, feel free to comment and update the context to reopen.
