### ISSUE TITLE
page references non-existent project

### ISSUE THREAD

**Issue by lfarrgouch** [docker/docker.github.io#11634]
File: [get-started/nodejs/develop.md](https://docs.docker.com/get-started/nodejs/develop/)

This page references a project called notes-service which is not referenced in any of the other prerequisites in this tutorial, so I have no idea what it is.  You probably should include that project somewhere since you're building off it, because this part of the tutorial isn't really helpful without that.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This was resolved by https://github.com/docker/docker.github.io/issues/11623
If the issue still persists, please let us know.
