### ISSUE TITLE
404 at /reference/commandline/inspect/

### ISSUE THREAD

**Issue by newcuit** [docker/docker.github.io#11638]
I found a broken link : https://docs.docker.com/reference/commandline/inspect/
I arrived on this page through: https://www.ctl.io/

**Comment by maximillianfx** [comment]
Hi @newcuit , the correct page is https://docs.docker.com/engine/reference/commandline/inspect/. Where at ctl.io do you found the broken link?

**Comment by craig-osterhout** [comment]
Thanks for reporting the broken link. Please report this issue on the source page where the link is located.
