### ISSUE TITLE
Missing Reference NodeJS file

### ISSUE THREAD

**Issue by muratcanberber** [docker/docker.github.io#11655]
Under Get Started -> NodeJS -> Develop section, it has been referenced to a NodeJS file which i assumed it was created previously but at the very and  of documentation, it says "Add the following code to the server.js file on line 19 and save the file." . Neither i have that long server.js nor there is include nodemon library which is refered after this.  

Adding this to server.js does not make NodeJS server reload becouse there is not nodemon installed from the previous lecture.

` server.use( '/foo', (req, res) => {
   return res.json({ "foo": "bar" })
 })`

Am i missing something ?  I get the general idea but this was confusing for me.

File: [get-started/nodejs/develop.md](https://docs.docker.com/get-started/nodejs/develop/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This was resolved by https://github.com/docker/docker.github.io/issues/11623
If the issue still persists, please let us know.
