### ISSUE TITLE
Apparent mismatch in service name in anonymous authentication for hub rate limit preview

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [docker/docker.github.io#11660]
Folllowing the docs for how to preview your rate limit anonymously, cf.

File: [docker-hub/download-rate-limit.md](https://docs.docker.com/docker-hub/download-rate-limit/)

getting a tocken with

```bash
TOKEN=$(curl -Lvs \
  "https://auth.docker.io/token?service=registry-1.docker.io&scope=repository:ratelimitpreview/test:pull" | \
   jq -r .token)
```
running the second request

```bash
curl -Lvs -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
```

I get a the following respose in curl

```
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json
< Docker-Distribution-Api-Version: registry/2.0
< Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:ratelimitpreview/test:pull",error="invalid_token"
< Date: Thu, 29 Oct 2020 11:25:38 GMT
< Content-Length: 164
< Strict-Transport-Security: max-age=31536000
```
upon detailed inspection, even though I requested the host `registry-1.docker.io`, the server requires authentication for the service `registry.docker.io`.

After changing the first request to respect the requested service in the authentication challenge (thank god i've spent some hours fighting with these kind of challenges before), it worked:

```
```bash
TOKEN=$(curl -Lvs \
  "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | \
   jq -r .token)
curl -Lvs -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
```

So I suggest the docs be changed, more precisely the curl for the token should be adjusted by changing the `service`.

Interestingly, adjusting the host in the second request to `registry.docker.io` yielded

> `<html><body><h1>503 Service Unavailable</h1>`
> `No server is available to handle this request.`

**Comment by valentin-krasontovitsch** [comment]
I should add that I did not test the username and password based process.

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/docker.github.io/pull/11656 (thanks for reporting!)
