### ISSUE TITLE
Incorrect TLS cert configuration instructions for Intermediate CA on UCP

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#1168]
### Problem description

If a customer has an intermediate CA, it should be provided in the CA certificate field not the Certificate field. Otherwise the customer will receive an error updating certs that states `unable to load x509 key pair, the private key does not match the public key`

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/datacenter/ucp/2.0/guides/configuration/#/customize-the-ucp-tls-certificates

### Project version(s) affected

UCP 2.0 and UCP 2.1 

### Suggestions for a fix

`CA certificate` - root CA followed by the intermediate CA
`Certificate` - server public certificate followed by any other intermediates (typically there aren't multiple)
`Key` - private key (make sure it is not encrypted with a password)
for encrypted keys, it should say `ENCRYPTED` in the first line

**Comment by clocklear** [comment]
Claimed!

**Comment by joaofnfernandes** [comment]
@clocklear let me know if you need help testing this out.

**Comment by joaofnfernandes** [comment]
@clocklear is following up on this on #1168, but I think I know what happened here. The user put in the `Server certificate` field the intermediate + the public cert for their domain. The first cert should always be the one for the domain.

If you reverse this and put the intermediates or even CA at the start, UCP will try to validate if your private key belongs to that cert, and will tell you that it doesn't.
