### ISSUE TITLE
404 at /docker-for-windows/instal/

### ISSUE THREAD

**Issue by obilingga** [docker/docker.github.io#11683]
I found a broken link : https://docs.docker.com/docker-for-windows/instal/

**Comment by thaJeztah** [comment]
The links should be with double `l` at the end; https://docs.docker.com/docker-for-windows/install/

Where did you find that broken link? I did a quick search in the source-code of the documentation, and didn't this link; did you find it somewhere else, or did you manually type it in your browser?

**Comment by thaJeztah** [comment]
Looks like this one went stale, so let me close
