### ISSUE TITLE
chkconfig not available on linux, page needs to be modified

### ISSUE THREAD

**Issue by cskalyan** [docker/docker.github.io#11693]
File: [engine/install/linux-postinstall.md](https://docs.docker.com/engine/install/linux-postinstall/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Fixed in https://github.com/docker/docker.github.io/commit/6b1bae466f6f27aa91c9cca735cdbc7d720d116c
If the issue still persists, please let us know.
