### ISSUE TITLE
Docker not starting. I followed all Troubleshooting steps

### ISSUE THREAD

**Issue by xeviff** [docker/docker.github.io#11694]
### Problem description

After install Docker on Windows Pro, it never starts up.

### Problem location

It begins with the state "Docker is starting" and never changes.

### Suggestions for a fix

I attach the log file so you can investigate the problem. (I have got no more 
recommendation from the Troubleshooting wizard)
[20201103163140.zip](https://github.com/docker/docker.github.io/files/5482766/20201103163140.zip)
[20201103161606.zip](https://github.com/docker/docker.github.io/files/5482767/20201103161606.zip)

**Comment by craig-osterhout** [comment]
Thanks for sharing this. As it is an issue of support and not an issue related to the documentation, I will close it. You may try the Docker Community Forum for help.
