### ISSUE TITLE
Remove dollar sign from code sections

### ISSUE THREAD

**Issue by julien-lecomte** [docker/docker.github.io#11695]
File: [engine/install/debian.md](https://docs.docker.com/engine/install/debian/)

Remove the dollar sign used as a prefix in code sections. It prevents triple-click to select line then copy & paste in console. With the dollar sign present, we have to double-click a word, than select each word, where horizontal scrolling can also happen just to copy-paste in a console.

Bad:
~~~
$ sudo apt-get remove docker docker-engine docker.io containerd runc
~~~

Good:
~~~
sudo apt-get remove docker docker-engine docker.io containerd runc
~~~

**Comment by KritikaRanjan** [comment]
Do we have to remove all the $ sign or just from this code " $ sudo apt-get remove docker docker-engine docker.io containerd runc" 
actually this is the first time i am contributing so don't know much. Help me
