### ISSUE TITLE
GitHub Actions 'actions/checkout@v2' Step missing on CI Pipeline Documentation  

### ISSUE THREAD

**Issue by euclides-c** [docker/docker.github.io#11718]
File: [ci-cd/github-actions.md](https://docs.docker.com/ci-cd/github-actions/)

Hi, I am just learning to set up CI pipelines using GitHub actions and Docker Hub, and for that I am used Docker Documentation. After failing 7 times, I looked around on the internet, and found out that if I just added one more step:

- uses: actions/checkout@v2

before the rest of the steps, my CI would work. I understand that this step is to check-out the GitHub code to the ubuntu image on which the build will run.

without this step, I would get the following error:

buildx call failed with: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount144986414/Dockerfile: no such file or directory

**Comment by thaJeztah** [comment]
looks like this was fixed through https://github.com/docker/docker.github.io/pull/11719
