### ISSUE TITLE
Feedback for: engine/reference/commandline/stats.md

### ISSUE THREAD

**Issue by akailash** [docker/docker.github.io#1171]
File: [engine/reference/commandline/stats.md](https://docs.docker.com/engine/reference/commandline/stats/)
Kindly mention details regarding the docker stats output. For example, that MEM USAGE includes Page Cache as well as RES. Or just mention exactly which cgroups metric is reflected here. This missing information has resulted in atleast 4/5 stackoverflow.com questions already.

**Comment by mstanleyjones** [comment]
This content has been expanded. If you need more info, please raise an issue in the `docker/docker` project, as that is where this content is maintained.
