### ISSUE TITLE
404 at /docker-forwindows/wsl/%E3%80%82

### ISSUE THREAD

**Issue by coco0613** [docker/docker.github.io#11737]
I found a broken link : https://docs.docker.com/docker-forwindows/wsl/%E3%80%82

**Comment by usha-mandya** [comment]
@coco0613 The correct URL is https://docs.docker.com/docker-for-windows/wsl/. Could you let us know how you arrived at the broken URL referenced above?

**Comment by thaJeztah** [comment]
Looks like this one went stale, so let me close
