### ISSUE TITLE
Docker examples don't say anything about specifying a key 

### ISSUE THREAD

**Issue by lfmunoz** [docker/docker.github.io#11747]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

```
$ docker -H ssh://me@example.com:22 ps
$ docker -H ssh://me@example.com ps
$ docker -H ssh://example.com ps

# please add example of how to add key
$ docker -i /path/to/my/key???  -H ssh://example.com ps      
```

Is it possible to specify the ssh key? ssh -i ?  Documentation doesn't say anything about this. 

```
To use SSH connection, you need to set up ssh so that it can reach the remote host with public key authentication.  (**yes I did this, but how do I tell it what key to use?**) Password authentication is not supported. If your key is protected with passphrase, you need to set up ssh-agent.
```

if it is not possible  maybe add a a line that says, you must add key  using
```
ssh-add -k ${SSH_KEY_LOCATION}
```

Note: willing to do pull request for this.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://docs.docker.com/engine/reference/commandline/dockerd/
