### ISSUE TITLE
404 at /reference/commandline/cli/

### ISSUE THREAD

**Issue by 925818189** [docker/docker.github.io#11779]
I found a broken link : https://docs.docker.com/reference/commandline/cli/
I arrived on this page through: https://www.widuu.com/

**Comment by thaJeztah** [comment]
The correct URL for that page is https://docs.docker.com/engine/reference/commandline/cli/
(although it's possible that it was at that URL a long time ago); if it was at that location, it's probably too long ago to add a redirect for this, so let me close this for now (but we may add a redirect if we see more sites pointing to the old location)
