### ISSUE TITLE
Documentation guidance and 

### ISSUE THREAD

**Issue by harshnagarkar** [docker/docker.github.io#11785]
I am currently doing a project related to docker and would like to know the inner workings of the docker daemon.
Where can I find such a information as most of the information that I saw online was pretty superficial.
Are there any research papers or summarized daemon working online, especially related to resource allocation.

**Comment by craig-osterhout** [comment]
Thanks for sharing this. As it is not an issue related to the documentation and is not in scope, I will close it. You may try to reach out to the community in the Docker Community Forums to get more info.
