### ISSUE TITLE
Suggest changing install instructions to automatically use latest version

### ISSUE THREAD

**Issue by spikyjt** [docker/docker.github.io#11805]
File: [compose/install.md](https://docs.docker.com/compose/install/)

Whilst it would be handy if GitHub provided a download link to the latest release, it does at least provide a redirect to the page on which it is displayed. We can examine the headers of the response from https://github.com/docker/compose/releases/latest to get the actual release url and therefore acquire the latest version in order to generate the download link.

So instead of using: (version is the latest at time of writing)
```sh
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```
we can use:
```sh
sudo curl -L "$(curl -L -w %{url_effective} -s -o /dev/null 'https://github.com/docker/compose/releases/latest' | sed 's_/tag/_/download/_')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

I find this particularly useful for scripts that install docker-compose on remote or automated instances.

I'm sure somebody can do a better job with parsing the output than my clumsy use of `sed`!

Obviously this is just for Linux. I'm sure something similar could be done for Windows Server, but I don't have (a box|the knowledge|the need).

**Comment by craig-osterhout** [comment]
Thanks for sharing this. There is currently a note informing the user that they can replace the current version for a different version, which would no longer be applicable if we changed this. Also, from another ticket, using "$(uname -s)" may produce different capitalization on some systems that breaks the link.
