### ISSUE TITLE
max_replicas_per_node doesn't work after use restart

### ISSUE THREAD

**Issue by khaledAlokby** [docker/docker.github.io#11809]
### Problem description

Setup: 3 swarm nodes, the service that the issue occur on is maxscale, our deployment for this service is: 
replicated mode, with 2 replicas and max_replicas_per_node: 1.
after performing restart command on one of the containers, we witnessed a wired undesirable functioning 

![restart](https://user-images.githubusercontent.com/23505663/100542404-4fa73f80-3252-11eb-8f48-7fa36afa77c1.jpeg)

as you can see bellow, the sward rise a new container beside restarting the old one make it 2 containers on the same node and violating the constrains of rising only one replica per node (you can see the max 1 per node bellow also)
![issue1](https://user-images.githubusercontent.com/23505663/100542622-c42eae00-3253-11eb-9074-fd00dd725084.jpeg)
![issu2](https://user-images.githubusercontent.com/23505663/100542625-c7299e80-3253-11eb-9331-bb35d7757314.jpeg)
![issue3](https://user-images.githubusercontent.com/23505663/100542627-c98bf880-3253-11eb-9a5a-d658bb7ca459.jpeg)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
If you believe this is a bug, please create an issue in the engine repo at https://github.com/moby/moby
If you need support, please try the Docker Community Slack or Forums:
- https://dockercommunity.slack.com/
- https://forums.docker.com/
