### ISSUE TITLE
404 at /composer/yml

### ISSUE THREAD

**Issue by yxx-java** [docker/docker.github.io#11800]
I found a broken link : https://docs.docker.com/composer/yml

**Comment by thaJeztah** [comment]
I checked the source code of the docs, and couldn't find a link pointing to that URL. Did you find a link to that page somewhere or could this have been a typo?

I _think_ the page you're looking for is; https://docs.docker.com/compose/compose-file/

Let me close this ticket, as I couldn't find a link pointing to that page, but feel free to continue the conversation if you have more info
