### ISSUE TITLE
Feedback for: docker-cloud/getting-started/deploy-app/12_data_management_with_volumes.md

### ISSUE THREAD

**Issue by sardjv** [docker/docker.github.io#1180]
File: [docker-cloud/getting-started/deploy-app/12_data_management_with_volumes.md](https://docs.docker.com/docker-cloud/getting-started/deploy-app/12_data_management_with_volumes/)

    $ docker-cloud service redeploy redis

This command does not reset the counter to zero. Is this because redeploying now reuses the existing container volumes by default? If I do the same thing at [https://cloud.docker.com](https://cloud.docker.com) there's a toggle switch "Reuse existing container volumes?". If I turn this off then the counter is set to zero. I'm not sure how this would be done through the CLI so I couldn't submit a change request.

**Comment by sardjv** [comment]
Found it!

    docker-cloud service redeploy redis --not-reuse-volumes

Works. Will submit a change request.

**Comment by sardjv** [comment]
This tutorial doesn't seem to work because redeploying the service doesn't reset the counter. It appears the volume is set up from the beginning?

**Comment by sanscontext** [comment]
Hey @sardjv I don't think the `--not-reuse-volumes` flag is correct. (I believe it's `--reuse-volumes=false`_

**Comment by sanscontext** [comment]
Hm, it looks like I need to update the API docs - hold tight I'm asking around.

**Comment by sanscontext** [comment]
Relates to #1181

**Comment by sanscontext** [comment]
Thanks again @sardjv !

**Comment by gdvalderrama** [comment]
@sanscontext what's the correct flag then: `--not-reuse-volumes` or `--reuse-volumes=false`?
