### ISSUE TITLE
404 at /registry/spec/manifest-v2-2/

### ISSUE THREAD

**Issue by HENRY-jc** [docker/docker.github.io#11829]
I found a broken link : https://docs.docker.com/registry/spec/manifest-v2-2/
I arrived on this page through: https://docs.docker.com/reference/

browser : either chrome or Edge = same thing

**Comment by thaJeztah** [comment]
Thanks for reporting! Looks like this was a temporary glitch; we published the docs again on docs.docker.com, and the URL now works
