### ISSUE TITLE
Feedback for: engine/userguide/storagedriver/device-mapper-driver.md

### ISSUE THREAD

**Issue by zechocobo** [docker/docker.github.io#1183]
File: [engine/userguide/storagedriver/device-mapper-driver.md](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/)

The daemon.json was wrong for me (Debian Jessie), the good is :
{
"storage-driver": "devicemapper",
"storage-opts": [
"dm.thinpooldev=/dev/mapper/docker-thinpool-tpool",
"dm.use_deferred_removal=true",
"dm.use_deferred_deletion=true"
]
}

**Comment by mbentley** [comment]
Did you change the name of the thin pool you created?  If you follow the docs exactly, the current documented config should be correct still:
```
{
  "storage-driver": "devicemapper",
   "storage-opts": [
     "dm.thinpooldev=/dev/mapper/docker-thinpool",
     "dm.use_deferred_removal=true",
     "dm.use_deferred_deletion=true"
   ]
}
```

**Comment by mstanleyjones** [comment]
Please reopen if this is still a problem and you didn't rename the thin pool.
