### ISSUE TITLE
404 at /registry/deploying/spec/auth/token.md

### ISSUE THREAD

**Issue by viesti** [docker/docker.github.io#11835]
I found a broken link : https://docs.docker.com/registry/deploying/spec/auth/token.md
I arrived on this page through: https://docs.docker.com/registry/deploying/

**Comment by thaJeztah** [comment]
Thanks for reporting; the correct URL for that page is https://docs.docker.com/registry/spec/auth/token/

Looks like this was a temporary glitch; we published the docs again on docs.docker.com, and the correct link is now present again on https://docs.docker.com/registry/deploying/
