### ISSUE TITLE
Daemon configuration file - default-address-pools example fix

### ISSUE THREAD

**Issue by kbendl** [docker/docker.github.io#11868]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

Please change the example configuration section for `default-address-pools` to use valid CIDR addresses:
Is:

    "default-address-pools": [
      {
        "base": "172.80.0.0/16",
        "size": 24
      },
      {
       "base": "172.90.0.0/16",
        "size": 24
      }
    ],

Should use valid 172.16.0.0/12 CIDR address, so as not to collide with valid routing. 

An example with valid CIDRs: 

    "default-address-pools": [
      {
        "base": "172.30.0.0/16",
        "size": 24
      },
      {
       "base": "172.31.0.0/16",
        "size": 24
      }
    ],

Thanks!

refs:

- https://tools.ietf.org/html/rfc1918

**Comment by pepawel** [comment]
I've created pull request for this issue:
https://github.com/docker/cli/pull/3295
