### ISSUE TITLE
GH Actions errors (removing Netlify preview) when publishing docs

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#11867]
As commented in https://github.com/docker/docker.github.io/pull/11864#issuecomment-741488978 by @tiborvass (but I've seen similar errors before); GitHub Actions is showing errors when publishing docs.

I'm not sure if we need to perform the `delete` step (perhaps needed to prevent the previous deploy from being left around, as these previews are always generated from the same branch?)

Thought I'd open a ticket for tracking, and copy the comments here

/cc @StefanScherer @usha-mandya  

-----------

Error:
```
+ netlify sites:delete --force 
deleting site
 ›   Error: Missing 1 required arg:
 ›   siteId  Site ID to delete.
 ›   See more help with --help
```

----------

Investigating the CI failure, it seems that an empty site_id variable is passed on the command line to netlify https://github.com/docker/docker.github.io/blob/master/.github/actions/netlify-clean/entrypoint.sh#L33 which means get_site_id does not behave correctly in https://github.com/docker/docker.github.io/blob/master/.github/actions/netlify-clean/entrypoint.sh#L15

I don't quite know what happened, but these actions were not changed published and master branches, therefore I'm assuming that I hit a corner case when i initially closed and reopened the PR.

**Comment by craig-osterhout** [comment]
This looks like it was fixed in https://github.com/docker/docker.github.io/commit/0d2c7a2f53249da78e53bc510dd0967302434843
Please reopen if not fixed.
