### ISSUE TITLE
404 at /en/latest/use/builder/

### ISSUE THREAD

**Issue by FlavioCorreia** [docker/docker.github.io#11875]
I found a broken link : https://docs.docker.com/en/latest/use/builder/#expose

**Comment by thaJeztah** [comment]
That's a REALLY old link; where did you find that link?

The current location for that page is https://docs.docker.com/engine/reference/builder/#expose

**Comment by thaJeztah** [comment]
Let me close this ticket, as we're not planning to add redirects for those links, but feel free to continue the conversation
