### ISSUE TITLE
Guide references to non existing project notes-services

### ISSUE THREAD

**Issue by Golpe82** [docker/docker.github.io#11873]
### Problem description

Guide references to non existing project 'notes-services'

### Problem location

https://docs.docker.com/get-started/nodejs/develop/#use-compose-to-develop-locally

### Suggestions for a fix

Project 'notes-services' should be previously implemented in this guide, so that the user knows what project are you talking about (there is no part 1 in this guide with a project called 'notes-services')

**Comment by royas** [comment]
It's a duplicate of #11518.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This appears fixed in https://github.com/docker/docker.github.io/pull/11770
If the issue still persists, please let us know.
