### ISSUE TITLE
2.5.0.1 link no longer works

### ISSUE THREAD

**Issue by feltz916** [docker/docker.github.io#11880]
File: [docker-for-mac/release-notes.md](https://docs.docker.com/docker-for-mac/release-notes/)

**Comment by michaelsanford** [comment]
Same for docker-for-windows.

PR incoming.

**Comment by sudo-bmitch** [comment]
Mac release notes have been fixed in #11881.

Looks like Windows release notes still need to be updated:

https://github.com/docker/docker.github.io/blame/78421ba741a93678268b09baad169a90340cc7a7/docker-for-windows/release-notes.md#L56

**Comment by thaJeztah** [comment]
This should be fixed by https://github.com/docker/docker.github.io/pull/12036, which will be published soon
