### ISSUE TITLE
Delegated and Cached flags for volumes documentation missing

### ISSUE THREAD

**Issue by benfreke** [docker/docker.github.io#11884]
The information on these flags used to be available. There is a myriad of information on their usage still on the Internet, but nothing on the official documentation. 

Have they been deprecated? Removed? Are they still safe to use? 

I'd be happy with a release note or deprecation so that I know that I'm expected to have bad performance on a Mac, but on the 3.0.0 release it still provides a massive performance improvement, of up to 1/3 faster. i.e. 30 second would go to 20 seconds.

**Comment by akauppi** [comment]
They are still documented in the Docker for Mac > [Performance tuning for volume mounts (shared filesystems)](https://docker-docs.netlify.app/docker-for-mac/osxfs-caching/) page, which look<strike>s</strike>ed official to me... It says "current" at the top right corner.

But you are right. It's 18.x when Docker Desktop for Mac engine is now 20.x.

Yet, these things work on Docker Compose so it *really* needs to be better communicated.
