### ISSUE TITLE
Incorrect Download link

### ISSUE THREAD

**Issue by BrizzleRocker** [docker/docker.github.io#11887]
File: [docker-for-mac/release-notes.md](https://docs.docker.com/docker-for-mac/release-notes/)

The Download link for 2.5.0.1 links directly to the latest version (3.0.0) and not to the binary for the version specified.

Could someone with the necessary access and knowledge correct this please as the latest version is incompatible with Docksal?

**Comment by sudo-bmitch** [comment]
Fixed in #11881
