### ISSUE TITLE
get-started/nodejs/develop relies on a project not included in part 1 or 2

### ISSUE THREAD

**Issue by michaelpetty** [docker/docker.github.io#11898]
File: [get-started/nodejs/develop.md](https://docs.docker.com/get-started/nodejs/develop/)

this page refers to a project `notes-service` from Part-1 that the current node-js track and get-started pages don't have. there is no mongodb set-up example. 

the current https://docs.docker.com/get-started/nodejs/run-containers/ and https://docs.docker.com/get-started/nodejs/build-images/ build node-docker which runs a mock server, db.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This was resolved by https://github.com/docker/docker.github.io/pull/11770
If the issue still persists, please let us know.
