### ISSUE TITLE
Add system requirements in Release Notes

### ISSUE THREAD

**Issue by esdc-esac-esa-int** [docker/docker.github.io#11911]
File: [docker-for-mac/release-notes.md](https://docs.docker.com/docker-for-mac/release-notes/)

It would help if you can see the system requirements for older versions of the application.
For instance, if you have an specific OS version, you do not know which Docker version you have to install.
(I am looking at release notes web page)

**Comment by aevesdocker** [comment]
Closing ticket as system requirements are detailed on the individual platform installation pages
