### ISSUE TITLE
please send me docker for windows 7 -64 bit 

### ISSUE THREAD

**Issue by kamix531** [docker/docker.github.io#11918]
File: [docker-for-windows/docker-toolbox.md](https://docs.docker.com/docker-for-windows/docker-toolbox/)
docker for windows 7 ( 64 bit )

**Comment by thaJeztah** [comment]
Docker Toolbox has been deprecated now that Windows 7 reached EOL; you can still download older releases from the GitHub repository https://github.com/docker/toolbox/releases/tag/v19.03.1, but I'd highly recommend updating to a more current version of Windows to run Docker Desktop for Windows
