### ISSUE TITLE
docker-compose v3 and index of the compose file reference

### ISSUE THREAD

**Issue by ldez** [docker/docker.github.io#11935]
### Problem description

PR #11744 creates a regression: 

the item "Version 3" point to the https://docs.docker.com/compose/compose-file/ instead of https://docs.docker.com/compose/compose-file/compose-file-v3/

![Screenshot_2020-12-18 Compose file](https://user-images.githubusercontent.com/5674651/102641527-7f17e080-415c-11eb-84f2-207d48809ef8.png)

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/compose/compose-file/

**Comment by atomicwrites** [comment]
I'm having the same issue, was very confused until I got it from the wayback machine.

**Comment by Zenexer** [comment]
Temporary workaround for anyone looking for the v3 reference: [visit the link directly](https://docs.docker.com/compose/compose-file/compose-file-v3/).

At the moment, the v3 reference doesn't seem to be accessible from the menu and at least some search engines.

**Comment by thaJeztah** [comment]
This is fixed by https://github.com/docker/docker.github.io/pull/11959, which will be published to docs.docker.com soon
