### ISSUE TITLE
Spelling error in ToC of Guides

### ISSUE THREAD

**Issue by yaleman** [docker/docker.github.io#11937]
### Problem description

The table of contents for the page [Persisting Data](https://docs.docker.com/get-started/05_persisting_data/) page has a spelling error.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/get-started/05_persisting_data/

### Suggestions for a fix

[PR 11936 raised here](https://github.com/docker/docker.github.io/pull/11936)

**Comment by thaJeztah** [comment]
Thanks for reporting; https://github.com/docker/docker.github.io/pull/11936 was merged, and will be published soon
