### ISSUE TITLE
Docker-compose version 3 Reference seam to be missing completly

### ISSUE THREAD

**Issue by GorkamWorka** [docker/docker.github.io#11966]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

Looking at  https://docs.docker.com/compose/compose-file/compose-file-v3/ the file does exist but doesn't get displayed when asked via the menu to display the version 3 reference

**Comment by leonardoraele** [comment]
- [This commit](https://github.com/docker/docker.github.io/commit/d0f70fdbb98791037123fc2fabccf64f19add75a#diff-48814d2fb4d1022bf337dc503d9476b595ff2fe08f5473cff000f998a37e2b39) moved it to it's own separate file; and
- [This commit](https://github.com/docker/docker.github.io/commit/00119346fe8883200c7f51af592ade898782fbd5#diff-48814d2fb4d1022bf337dc503d9476b595ff2fe08f5473cff000f998a37e2b39) liked it in the [About versiond and upgrading page](https://docs.docker.com/compose/compose-file/compose-versioning/)

So you can find the compose-file-v3 reference by going to the versioning page and clicking on "Version 3".

But that's not where people will search for it. People will go to the [compose file reference](https://docs.docker.com/compose/compose-file/). There should be a link there to the actual compose file reference document.

**Comment by leonardoraele** [comment]
Also, dup of https://github.com/docker/docker.github.io/issues/11961

**Comment by sudo-bmitch** [comment]
Thanks for the report. I believe this is fixed in #11959

**Comment by thaJeztah** [comment]
https://github.com/docker/docker.github.io/pull/11959 was merged and will be published soon, thanks!
