### ISSUE TITLE
There is no link to the compose file documentation in the Compose file reference

### ISSUE THREAD

**Issue by fieldse** [docker/docker.github.io#11976]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

## Summary:

There is no link In the entire docker compose documentation to the actual docker compose file reference, which is primarily what is actually necessary to start building with docker Compose.

## Desired solution
Add a link to the compose file reference (here: https://docs.docker.com/compose/compose-file/compose-file-v3/)

## Reasoning
Note the 700 downvotes on this page. 
![image](https://user-images.githubusercontent.com/394065/103079645-2db19a80-460f-11eb-8a8e-4a772fe74887.png)

The menu to the left provides the following options, which indicate they should lead us to an actual file reference:

![image](https://user-images.githubusercontent.com/394065/103079602-1a9eca80-460f-11eb-9753-99ed51b25e2a.png)

Instead, we have an unhelpful "Version compatibility Matrix", followed by several links which lead to anything except an actual file reference:

![image](https://user-images.githubusercontent.com/394065/103079834-9e58b700-460f-11eb-905a-6f0307fb9f47.png)

I end up having to google every time to find the actual page. :-1:

**Comment by qqaatw** [comment]
Same issue. I remembered that it used to be there, don't know why it is missing now.

**Comment by sudo-bmitch** [comment]
Thanks for the report. I believe this is fixed in #11959
