### ISSUE TITLE
Getting Starded: !!! info MD error

### ISSUE THREAD

**Issue by shaderecker** [docker/docker.github.io#11978]
File: [get-started/index.md](https://docs.docker.com/get-started/)

Not sure how this is supposed to be rendered (some infobox?), but it is displayed like this on the final page:

!!! info “Creating Containers from Scratch”
and
!!! info If you’re familiar with chroot

The MD syntax seems to be broken.

**Comment by thaJeztah** [comment]
Thanks for reporting; I opened https://github.com/docker/docker.github.io/pull/12047 to fix the markdown

**Comment by shaderecker** [comment]
Thank you @thaJeztah this looks really nice now 👍🏻

**Comment by StefanScherer** [comment]
Nice catch. Thanks!
