### ISSUE TITLE
Typo in navigation Get started - Part 5: Persiting our DB

### ISSUE THREAD

**Issue by puenka** [docker/docker.github.io#11985]
### Problem description
There is a typo (missing letter s) in the navigation bar on the left of the documentation page where it says Part 5: Persiting our DB instead of the correct headline.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/get-started/05_persisting_data/

**Comment by sudo-bmitch** [comment]
Fixed by #11936

**Comment by thaJeztah** [comment]
https://github.com/docker/docker.github.io/pull/11936 was merged, and will be published soon
