### ISSUE TITLE
Code snippets not showing correctly 

### ISSUE THREAD

**Issue by xberna16** [docker/docker.github.io#12006]
File: [get-started/08_using_compose.md](https://docs.docker.com/get-started/08_using_compose/)
on https://docs.docker.com/get-started/08_using_compose/#defining-the-app-service there are snippets referencing the code,
they are not shown as intended. I see tags and header shown (```yaml hl_lines=”7 8” version: “3.7”). I am using chrome

**Comment by sudo-bmitch** [comment]
Thanks for the report. This will be fixed in #11958.

**Comment by thaJeztah** [comment]
This is fixed through https://github.com/docker/docker.github.io/pull/11947, which was merged, so let me close this one; thanks for contributing!!
