### ISSUE TITLE
Code block formatting not working

### ISSUE THREAD

**Issue by huiosx** [docker/docker.github.io#12005]
File: [get-started/08_using_compose.md](https://docs.docker.com/get-started/08_using_compose/)
![Screenshot 2020-12-28 at 17 21 38](https://user-images.githubusercontent.com/72471384/103232104-7af47b80-4931-11eb-8ee4-1bb2aeca4729.png)

The code block formatting on this page doesn't seem to work. The above screenshot is from a Brave private window (i.e. with no extensions) and was looking exactly the same way in a normal tab too. Notably, some code blocks are showing as intended. For example, the first 4 on the page are fine. Then as shown, steps 1-5 of Defining the App Service are broken, then the first 2 of Defining the MySQL Service work fine, but then steps 1-3 are broken. Everything else works fine. I thought it might be to do with the numbering of steps, but Running Our Application Stack has 3 steps and the code blocks there work fine.

**Comment by sudo-bmitch** [comment]
This will be fixed by #11947

**Comment by thaJeztah** [comment]
https://github.com/docker/docker.github.io/pull/11947 was merged (and will be published on docs.docker.com soon); I'll go ahead and close this, thanks for reporting!
