### ISSUE TITLE
Where did the actual compose file reference go ?  Please put it back.

### ISSUE THREAD

**Issue by wrmay** [docker/docker.github.io#12020]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

I do see the link to the specification on GitHub but I don't see any way to get to the previous versions of the compose file specification.  There is a table on this page that lists versions of the compose file specification (e.g 3.8, 3.7 ) but there is no apparent way to access those.  I expected 3.8, 3.7, etc to be links.

**Comment by sudo-bmitch** [comment]
This will be fixed in #11959

**Comment by thaJeztah** [comment]
This is fixed by https://github.com/docker/docker.github.io/pull/11959, which will be published to docs.docker.com soon
