### ISSUE TITLE
404 at /docker-for-mac/%29

### ISSUE THREAD

**Issue by potturi528** [docker/docker.github.io#12028]
I found a broken link : https://docs.docker.com/docker-for-mac/%29
I arrived on this page through: https://www.youtube.com/

**Comment by thaJeztah** [comment]
That URL looks to be invalid, and needs to be fixed on YouTube. Unfortunately, not something we can fix (the correct url is https://docs.docker.com/docker-for-mac/)

Do you know which video on YouTube mentioned that link?

I'll close this issue here, but feel free to continue the conversation
