### ISSUE TITLE
description for entrypoint is as clear as mud.

### ISSUE THREAD

**Issue by nmishr** [docker/docker.github.io#12035]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

It would be good to answer  why and when to use it in addition to the what.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/blob/master/docs/reference/builder.md
