### ISSUE TITLE
Request docs changes: rootless installation

### ISSUE THREAD

**Issue by libbin** [docker/docker.github.io#12053]
File: [engine/security/rootless.md](https://docs.docker.com/engine/security/rootless/)

https://github.com/docker/docker.github.io/blob/1976c2178c6317400fdbdc0933570c5ef9248ab6/engine/security/rootless.md

1) To install Rootless Docker as the "ROOT" user, see the Manual installation steps.

But the purpose of this page is installation without root privilege...

2) Manual installation (https://docs.docker.com/engine/security/rootless/#manual-installation)

Seems a placeholder, people don't know how to manually install without dig https://get.docker.com/rootless

3) It's better to provide the Uninstallation as the complement. This will make user more confident about the installation.

**Comment by AkihiroSuda** [comment]
https://github.com/docker/docker.github.io/pull/12234 contains guide for uninstallation
