### ISSUE TITLE
Running our App with MySQL

### ISSUE THREAD

**Issue by mihai-preda** [docker/docker.github.io#12052]
File: [get-started/07_multi_container.md](https://docs.docker.com/get-started/07_multi_container/)
The command to run the app with mysql doesn't work on Ubuntu 20.04.
Error I get is:
docker: invalid reference format.
See 'docker run --help'.

**Comment by thaJeztah** [comment]
What is the command you're running? Is this the problem with this step; ?

```bash
docker exec -it <mysql-container-id> mysql -p todos
```

If so, you probably need to replace `<mysql-container-id>` with the actual ID of the container


We should probably update the instructions to use a name for the container to make it easier to use

**Comment by mihai-preda** [comment]
Hi @thaJeztah 
**The command i was running was this:** docker run -dp 3000:3000 \ -w /app -v "$(pwd):/app" \ --network todo-app \ -e MYSQL_HOST=mysql \ -e MYSQL_USER=root \ -e MYSQL_PASSWORD=secret \ -e MYSQL_DB=todos \ node:12-alpine \ sh -c "yarn install && yarn run dev"
I have noticed that the command was edited by somebody to look like this:
docker run -dp 3000:3000 \
   -w /app -v "$(pwd):/app" \
   --network todo-app \
   -e MYSQL_HOST=mysql \
   -e MYSQL_USER=root \
   -e MYSQL_PASSWORD=secret \
   -e MYSQL_DB=todos \
   node:12-alpine \
   sh -c "yarn install && yarn run dev"
I believe that that's the app container.
I do not get the same error anymore, however, the container fails to run without any error message.
The mysql container runs fine. I even tried restarting the docker service on my machine.

**Comment by mihai-preda** [comment]
This issue is fixed when automating the deployment with docker compose. 
I guess this ticket can be closed.
