### ISSUE TITLE
Add more debugging information to error messages

### ISSUE THREAD

**Issue by jeffsilverm** [docker/docker.github.io#12065]
File: [engine/reference/commandline/image_build.md](https://docs.docker.com/engine/reference/commandline/image_build/)
Add information about the path and url parameters.
I have discovered (empirically) that if my requirements.txt file is in my current directory, then the command
`sudo docker image build .` will build the image.  I have not yet figured out what the url parameter does.

This might not be the best place to note this, and if not, then please: let me know where it should go.  The error message `failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/snap/microk8s/current/docker.sock: connect: no such file or directory` has several possible errors including that the daemon is not running.  However, docker might need to run as root with `sudo` or there might a protection issue with the socket that the docker client is connecting to.  These kinds of problems could (should) be checked programmatically, e.g. `sudo ss -a -p | fgrep docker` can verify that the docker server is running.  I have looked over the internet and I find lots of different ways of troubleshooting.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
It looks like the error message is generated from the Engine. If the issue is still applicable, please help create an issue at https://github.com/moby/moby/issues
