### ISSUE TITLE
flicker page when dark mode

### ISSUE THREAD

**Issue by sinsinpurin** [docker/docker.github.io#12067]
File: [compose/compose-file/compose-file-v3.md](https://docs.docker.com/compose/compose-file/compose-file-v3/)

only this page flicker when dark mode.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
This seems similar to https://github.com/docker/docker.github.io/issues/11468
Does the issue still occur and does it only happen when navigating to a new page?

**Comment by craig-osterhout** [comment]
Closing this as stale. I was only able to reproduce a flicker when changing pages. If the issue still persists and is different than 11468, please provide more details on how to reproduce.
