### ISSUE TITLE
apt-key is deprecated

### ISSUE THREAD

**Issue by joedemcher** [docker/docker.github.io#12071]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

Under _SET UP THE REPOSITORY_ in the second step the user is directed to run the following command:

`$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -`

Doing so returns the following warning:

_Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))._

**Comment by ankostis** [comment]
Why did you close it, it is still a deprecated step, no?
