### ISSUE TITLE
Cant apt update on debian install 

### ISSUE THREAD

**Issue by aftxavier** [docker/docker.github.io#12070]
File: [engine/install/debian.md](https://docs.docker.com/engine/install/debian/)
Doing
```
$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
```

will result in 

```
E: The repository 'https://download.docker.com/linux/ubuntu buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Also maybe the documentation's "request doc changes" (upper right corner) could open github on a new page? 

thanks

**Comment by denis-roy** [comment]
`E: The repository 'https://download.docker.com/linux/ubuntu buster Release' does not have a Release file.`

buster is a Debian Release, Ubuntu and Debian releases don't mix :)

It would seems to me you are trying to follow [Debian's installation procedure](https://docs.docker.com/engine/install/debian/) on Ubuntu. Following [Ubuntu's procedure](https://docs.docker.com/engine/install/ubuntu/) will surely help you reach a more satisfying outcome :)

**Comment by craig-osterhout** [comment]
@denis-roy, thanks for providing a solution.
@aftxavier, thanks for sharing the issue. If you still experience issues after following denis-roy's solution, please try the Docker Community Slack or forums for support:
- https://dockercommunity.slack.com/
- https://forums.docker.com/
