### ISSUE TITLE
Redirect loop on the docker-for-windows networking docs page

### ISSUE THREAD

**Issue by bobgodfrey** [docker/docker.github.io#12075]
File: [docker-for-windows/networking](https://docs.docker.com/docker-for-windows/networking/)

click the link below to duplicate.
https://docs.docker.com/docker-for-windows/networking/

**Comment by sudo-bmitch** [comment]
Can you verify the issue still exists for you? I'm not able to reproduce it.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as stale. If the issue still persists, please let us know.
