### ISSUE TITLE
Install docker desktop with power shell

### ISSUE THREAD

**Issue by lhh1522** [docker/docker.github.io#12078]
I use power shell to install docker desktop with command 'Start-Process $dockerInstallerPath -ArgumentList "install --quiet" -Wait -passthru', but this way use the default configuration, how can i install without wsl2 like this 
![image](https://user-images.githubusercontent.com/41094418/104258924-61b80700-54bb-11eb-9ec4-37492d8fcd5c.png)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
If you have a paid Docker subscription, please raise a ticket through [Docker Desktop support](https://hub.docker.com/support/desktop/).
If you do not have a paid subscription,  you can get support through our Github repo [for-win](https://github.com/docker/for-win), where we respond on a best-effort basis.
