### ISSUE TITLE
Compose file says Docker engine 19.03 supports the Compose specification - but it doesn't?

### ISSUE THREAD

**Issue by thernstig** [docker/docker.github.io#12082]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

The information for this is unclear:
Compose file format | Docker Engine release
-- | --
Compose specification | 19.03.0+

https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element says:

> Top-level `version` property is defined by the specification for backward compatibility but is only informative.

I am using `19.03.13` (see below). But when I try to remove `version: "3.8"` from my `compose.yaml` file and then try to launch it with docker stack, it does not work:

```sh
> docker stack deploy -c compose.yaml cnom
unsupported Compose file version: 1.0
```

Are the docs wrong here? What is missing?

> 

```sh
docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by thernstig** [comment]
Or is it that `version` is still required, but just informative? I cannot find any info anywhere about how we are supposed to write a compose file with regards to `version` as I find the current documentation ambiguous.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. When using `docker stack deploy`, only compose file version 3.x is supported, https://docs.docker.com/engine/reference/commandline/stack_deploy/#compose-file
For more details, see https://github.com/moby/moby/issues/41875
