### ISSUE TITLE
Incorrect example for Container Resources

### ISSUE THREAD

**Issue by huiosx** [docker/docker.github.io#12081]
File: [cloud/ecs-compose-features.md](https://docs.docker.com/cloud/ecs-compose-features/)

Within the last section, 'Container Resources', `cpu: 0.5` should be `cpus: '0.5'`. The parameter must be `cpus` and the argument must be a string.

Refer to https://github.com/compose-spec/compose-spec/blob/master/deploy.md#resources

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
Added the issue to the upstream repo containing the file https://github.com/docker/compose-cli/issues/2152
Closing this.
