### ISSUE TITLE
404 at /userguide/level1

### ISSUE THREAD

**Issue by udaykrg** [docker/docker.github.io#12113]
I found a broken link : https://docs.docker.com/userguide/level1
I arrived on this page through: https://rominirani.com/docker-tutorial-series-writing-a-dockerfile-ce5746617cd

**Comment by sudo-bmitch** [comment]
It looks like that blog post was written over 5 years ago. A lot has changed since then, including the Docker website. It would probably be best to contact the blog post author to update their page.

**Comment by craig-osterhout** [comment]
Thanks for reporting the broken link. Please report this issue on the source page where the link is located.
