### ISSUE TITLE
404 at /go/compose-native-build

### ISSUE THREAD

**Issue by Paraphraser** [docker/docker.github.io#12148]
I found a broken link : https://docs.docker.com/go/compose-native-build

```
$ sudo pip3 install -U docker-compose
```

Logout. Login.

```
$ which docker-compose
/usr/local/bin/docker-compose

$ docker-compose version
docker-compose version 1.28.0, build unknown
docker-py version: 4.4.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

$ docker-compose up -d
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
•••
```

Learn about native build in Compose here: [https://docs.docker.com/go/compose-native-build/](https://docs.docker.com/go/compose-native-build/)

I'd really like to be able to:

1. Read the information about "native build"; then
2. **SILENCE** the "Building with native build..." line.

I was hoping (1) would help me with (2).

**Comment by Paraphraser** [comment]
Ahah! Can turn the whole thing off:

```
$ export COMPOSE_DOCKER_CLI_BUILD=0
```

**Comment by outloudvi** [comment]
#12150 dups here.

This is related to docker/compose#7978 and #11858. Seems that the redirect has been in the docs repo but not yet deployed to docs.docker.com. As more users upgrading to new versions and seeing the message, this would bring about more confusion.

@thaJeztah @nebuk89 would you like to have a look of this?

**Comment by thaJeztah** [comment]
Hmm... that PR was published.

Arf; I see the mistake; looks like I changed from `ttps://docs.docker.com/go/compose-native-builds/` (plural) to `https://docs.docker.com/go/compose-native-build/` in the CLI output 😬

Let me fix the redirect
