### ISSUE TITLE
pasted multi line command in Windows cmd or Powershell returns errors

### ISSUE THREAD

**Issue by torvista** [docker/docker.github.io#12145]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

Page says to use this command
` docker run -dp 3000:3000 \
     -w /app -v "$(pwd):/app" \
     node:12-alpine \
     sh -c "yarn install && yarn run dev"`

but each line returns errors
![Clipboard01](https://user-images.githubusercontent.com/4391026/105249573-9d686600-5b78-11eb-9220-062574ee2320.gif)

Removing the backslashes seems to get further but still fails:
![Clipboard02](https://user-images.githubusercontent.com/4391026/105249441-65f9b980-5b78-11eb-9b1f-962a6cb1c5dd.gif)

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The topic now provides code examples for Windows PowerShell. Windows Command Shell will not work with some of the commands, so you will need to use PowerShell to follow along with the examples.
