### ISSUE TITLE
asp.net core guides request

### ISSUE THREAD

**Issue by CrossPlatformProgrammer** [docker/docker.github.io#12141]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As it lacks details, I assume it's to update the tutorial.
Closing this in favor of https://github.com/docker/docker.github.io/issues/14560
If this was a request for something different, please provide more details.
