### ISSUE TITLE
404 at /reference/run/

### ISSUE THREAD

**Issue by altassian-fullstack-devs** [docker/docker.github.io#12149]
I found a broken link : https://docs.docker.com/reference/run/
I arrived on this page through: https://forums.docker.com/

**Comment by thaJeztah** [comment]
Thanks for reporting, looks like that is an old URL; the new URL is https://docs.docker.com/engine/reference/run/

I opened a PR to add a redirect https://github.com/docker/cli/pull/2942

**Comment by altassian-fullstack-devs** [comment]
Thanks, @thaJeztah.
Willing to keep in touch with you.
Again thanks.
