### ISSUE TITLE
404 at /reference/run/

### ISSUE THREAD

**Issue by Colin-XKL** [docker/docker.github.io#12151]
I found a broken link : https://docs.docker.com/reference/run/#mode-host
I arrived on this page through: https://github.com/RattyDAVE/alpine-vpn-pptp

**Comment by thaJeztah** [comment]
Thanks for reporting, looks like that is an old URL; the new URL is https://docs.docker.com/engine/reference/run/#network-host

I opened a pull request to add a redirect; https://github.com/docker/cli/pull/2942, and a pull request to fix the readme where you found the broken link; https://github.com/RattyDAVE/alpine-vpn-pptp/pull/2

**Comment by Colin-XKL** [comment]
Thank you very much!


在 2021年1月21日，22:45，Sebastiaan van Stijn <notifications@github.com> 写道：

﻿

Thanks for reporting, looks like that is an old URL; the new URL is https://docs.docker.com/engine/reference/run/#network-host

I opened a pull request to add a redirect; docker/cli#2942<https://github.com/docker/cli/pull/2942>, and a pull request to fix the readme where you found the broken link; RattyDAVE/alpine-vpn-pptp#2<https://github.com/RattyDAVE/alpine-vpn-pptp/pull/2>
