### ISSUE TITLE
404 at: /engine/reference/builder/

### ISSUE THREAD

**Issue by ajaygm** [docker/docker.github.io#1216]
URL: /engine/reference/builder/

Two ways to reach this...
1. Search for dockerfile reference (https://docs.docker.com/search/?q=dockerfile) => https://docs.docker.com/engine/reference/builder/
2. Link on the left hand side (Docker Engine -> Dockerfile reference) at https://docs.docker.com.

**Comment by mstanleyjones** [comment]
Fixed in #1286
