### ISSUE TITLE
No arrows visible while using the dark theme while reading docs

### ISSUE THREAD

**Issue by AlexGeniusMan** [docker/docker.github.io#12178]
File: [get-started/overview.md](https://docs.docker.com/get-started/overview/)
Hi! No arrows visible while using the dark theme. Ex:
![image](https://user-images.githubusercontent.com/47246896/105713982-d152db00-5f2c-11eb-9b4b-69b5114b24e5.png)

**Comment by craig-osterhout** [comment]
Merging with similar issue https://github.com/docker/docker.github.io/issues/14955
