### ISSUE TITLE
Confusing statement

### ISSUE THREAD

**Issue by radsatjob** [docker/docker.github.io#12172]
File: [cloud/aci-container-features.md](https://docs.docker.com/cloud/aci-container-features/)

> A single container is executed in its own ACI container group, that will container only one container.

This line needs to be modified to

> A single container is executed in its own ACI container group, which will contain a single container.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. I've opened an issue in the upstream repo containing the source file at https://github.com/docker/compose-cli/issues/2154
Closing this issue in favor of that one.
