### ISSUE TITLE
404 at /reference/commandline/cli/

### ISSUE THREAD

**Issue by whalefall541** [docker/docker.github.io#12177]
I found a broken link : https://docs.docker.com/reference/commandline/cli/#run

**Comment by jerae-duffin** [comment]
Hi @whalefall541 can you provide more details on how you arrived to this link?

**Comment by jerae-duffin** [comment]
Hi @whalefall541, referencing link: https://docs.docker.com/reference/commandline/cli/#run.

**Comment by whalefall541** [comment]
I can not arrive this sites either. It hints that There might be a mistake in the URL or you might’ve clicked a link to content that no longer exists. 

发自我的iPhone

**Comment by thaJeztah** [comment]
I think this was a very old URL for which we didn't have a redirect in place yet.

The new location for this page is https://docs.docker.com/engine/reference/commandline/cli/

And I opened a pull request to add a redirect; https://github.com/docker/cli/pull/3266

**Comment by whalefall541** [comment]
Yeah， So the problem is solved. 

发自我的iPhone

**Comment by thaJeztah** [comment]
Great!

Let me keep this ticket open until the redirect has been published
