### ISSUE TITLE
Python script returns error on Ubuntu 18.04

### ISSUE THREAD

**Issue by ap13istream** [docker/docker.github.io#12175]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

$ sudo add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>    $(lsb_release -cs) \
>    stable"
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 12, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 28, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The topic has been updated. If the issue still persists, please let us know.
