### ISSUE TITLE
Feedback for: engine/installation/linux/debian.md

### ISSUE THREAD

**Issue by partha-arjunan** [docker/docker.github.io#1218]
File: [engine/installation/linux/debian.md](https://docs.docker.com/engine/installation/linux/debian/)

The command for adding **Docker’s official GPG key** should be $ **curl -s http://yum.dockerproject.org/gpg | sudo apt-key add -**

**Comment by mstanleyjones** [comment]
This has been fixed in `master`. Thanks!
