### ISSUE TITLE
Docker compose file does not work

### ISSUE THREAD

**Issue by hbwork** [docker/docker.github.io#12239]
File: [language/nodejs/develop.md](https://docs.docker.com/language/nodejs/develop/)

I got the below error when I run 
curl --request GET --url http://localhost:8080/m/notes
curl: (56) Recv failure: Connection reset by peer

And it works if I change to 
ports:
  - 8000:8000

and remove "SERVER_PORT:8080" from the environment variables with below curl cmd:
curl --request GET --url http://localhost:8000/notes
{"code":"success","meta":{"total":0,"count":0},"payload":[]}

**Comment by t3hami** [comment]
The ronin server used in example runs by default on port 8000. You need to update the code/configuration for the server if you want to use a different port.

**Comment by tymik** [comment]
it was fixed in #12218
