### ISSUE TITLE
docker machine is no longer bundled with docker desktop

### ISSUE THREAD

**Issue by filmaj** [docker/docker.github.io#12243]
File: [machine/index.md](https://docs.docker.com/machine/)

> The installers for Docker Desktop for Mac and Docker Desktop for Windows include Docker Machine, along with Docker Compose.

I believe the above statement is false. It seems the installation page itself was updated about a year ago (#10194), but the 'Overview' page is still outdated. That was frustrating to figure out 😕

**Comment by usha-mandya** [comment]
@filmaj Thanks for reporting this. The statement that Machine has been bundled with Docker Desktop has been removed.

**Comment by filmaj** [comment]
Thanks for updating it!
