### ISSUE TITLE
Docker exit code 0 - Dot Net core

### ISSUE THREAD

**Issue by crazyoutlook** [docker/docker.github.io#12247]
My dot net core solution works fine both in debug and release mode. When I package it in Docker, it fails to work. Container starts and stops with exit code 0.

How do I verify what can be issue ? How to check any generated error logs.

Dockerfile:

FROM mcr.microsoft.com/dotnet/aspnet:3.1

COPY publish/ App/
WORKDIR /App
ENTRYPOINT ["dotnet", "FrameGrabber.dll"]

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For troubleshooting and support, please try the Docker Community Slack or Forums:
- https://dockercommunity.slack.com/
- https://forums.docker.com/
