### ISSUE TITLE
replace  `/nodejs/develop/ `  server.js 

### ISSUE THREAD

**Issue by zhuijing** [docker/docker.github.io#12257]
### Problem description

can not connect mongodb.

### Problem location

https://docs.docker.com/language/nodejs/develop/ 

We should pass the port parameter。

replace  server.js 
`
const ronin     = require( 'ronin-server' )
const mocks     = require( 'ronin-mocks' )
const database  = require( 'ronin-database' )
const server = ronin.server({
  port:  process.env.SERVER_PORT
})

database.connect( process.env.CONNECTIONSTRING )
server.use( '/', mocks.server( server.Router(), false, false ) )
server.start()

`

**Comment by newBird01** [comment]
If the port is not passed, the request cannot be initiated。Because the service defaults to 8000。

**Comment by t3hami** [comment]
@newBird01 have you created network and used it in both of the containers as described in documentation?

**Comment by tymik** [comment]
seems like it was fixed in #12218
