### ISSUE TITLE
docs: Wrong path to manage.py and inconsistent docker running process listing command shown

### ISSUE THREAD

**Issue by sandipb** [docker/docker.github.io#12268]
File: [compose/django.md](https://docs.docker.com/compose/django/)

In the `docker-compose.yml` file, the path to `manage.py` should be `composeexample/manage.py` and not `manage.py`.

Also (it is such a trivial problem I was debating if i should be opening a separate ticket for this).

At the end of the section, it asks that you should use `docker container ls` to list running containers. But the example shows `docker ps`. I understand that it is equivalent, but just wanted to point out that from the point of view of documentation, this is inconsistent.

I can create a pull request if someone confirms that these fixes are needed.

**Comment by StefanScherer** [comment]
Thanks @sandipb 
I walked through the tutorial, but the `manage.py` file is created in the current directory and not inside the `compose example` folder. So this page is correct.
But I'll update the `docker container ls` command. :-)
