### ISSUE TITLE
Missing docker command

### ISSUE THREAD

**Issue by jcalfee** [docker/docker.github.io#12275]
File: [engine/security/rootless.md](https://docs.docker.com/engine/security/rootless/)

Everything went well on Debian 10.  It is just missing one little thing: Where is the `docker` command?

Of course I figured out I needed to install `docker` separately.  Perhaps a quick note would help.  Any thoughts on how a docker install might be a little different under rootless mode?

For starters, in the Debian (etc) install it is probably good to skip:
```bash
sudo usermod -aG docker <your-user>
```

**Comment by t3hami** [comment]
@jcalfee the docker installation for rootless mode is mentioned in https://docs.docker.com/engine/security/rootless/#install. It'll install docker in ~/bin directory of user and you will need to add this path to your path variable (Mentioned in specified docs).
