### ISSUE TITLE
Play-with-docker link needs to be updated

### ISSUE THREAD

**Issue by d-rita** [docker/docker.github.io#12271]
File: [get-started/04_sharing_app.md](https://docs.docker.com/get-started/04_sharing_app/)

The link to the `play-with-docker` site needs to be updated to point to `https://labs.play-with-docker.com/`. The current one does not seem to lead to a functional site.

**Comment by usha-mandya** [comment]
@d-rita Thanks for reporting this. The link has been updated to point to the 'Play with Docker' homepage.
