### ISSUE TITLE
Missing Resources -> Advanced in new docker version for Windows

### ISSUE THREAD

**Issue by LucianoRogerio** [docker/docker.github.io#12284]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

Hi
I need to move the "Disk Image Location" for another Hard drive.
I also need to know how to change the "RAM memory" and the "CPUs number", I will this machine for several statistical analysis.

Thanks for your attention
Best Regards

**Comment by craig-osterhout** [comment]
Please find info on resource constraints at https://docs.docker.com/config/containers/resource_constraints/ and storage at https://docs.docker.com/storage/

If you need more support, please try the forums or Slack.
- https://forums.docker.com/
- https://dockercommunity.slack.com/

**Comment by thaJeztah** [comment]
If this is for Docker Desktop, then I think this content was moved to https://docs.docker.com/desktop/settings/windows/  in this PR: https://github.com/docker/docker.github.io/pull/15122
