### ISSUE TITLE
numa_available() return 0

### ISSUE THREAD

**Issue by dimarusyy** [docker/docker.github.io#12281]
1. Have wsl2 installed
2. Have docker desktop installed on windows
3. Have docker installed in Ubunut-20.04 on wsl using Docker server on windows host
4. Run `numactl --show` in wsl :

> $ numactl --show
> physcpubind: 0 1 2 3 4 5 6 7
> No NUMA support available on this system.`
> 

5. Create docker container via wsl with installed numa libraries
6. Create simple test-case and compile in wsl :

> #include <numa.h>
> #include <iostream>
> int main()
> {
>     auto n = numa_available();
>     std::cout  << "numa_available=" << n << "\n";
>     return 0;
> }
> 

7. Run `./test_numa` in wsl :

>$ ./test_numa
>numa_available=-1

8. Run `./test_numa` in docker image :

>$ docker run -it -v `pwd`/:/app --entrypoint /app/test_numa 53fda3c718da
>numa_available=0

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For troubleshooting and support, please try the Docker Community Slack or Forums:
- https://dockercommunity.slack.com/
- https://forums.docker.com/
