### ISSUE TITLE
Feedback for: compose/env-file.md

### ISSUE THREAD

**Issue by Stasmo** [docker/docker.github.io#123]
URL: [https://docs.docker.com/compose/env-file.md](https://docs.docker.com/compose/env-file/)

There are a few different formats for .env files floating around out there. I think a little clarification around how quotation marks are handled would be pretty useful here.

I had accidentally included single-quotes in my .env file when I copied some values from my Django project .env file, which uses [Python dotenv](https://github.com/theskumar/python-dotenv) and handles the quotes implicitly. It took us embarrassingly long to figure out what was happening.

Cheers

**Comment by londoncalling** [comment]
@shin- can you help clarify .env format details per @Stasmo 's comment?

**Comment by londoncalling** [comment]
ping @dnephin @shin- can you help with this issue?

**Comment by shin-** [comment]
The document already contains the information, I think:

> Compose expects each line in an env file to be in `VAR=VAL` format. Lines beginning with `#` (i.e. comments) are ignored, as are blank lines.

There is no special handling of quotation marks, which IMO is implied by the fact that we make no mention of special handling of quotation marks.

**Comment by Stasmo** [comment]
Explicitly stating that no special handling is done for quotation marks is
better than having people make assumptions based on a lack of information.

Take a quick look around and you'll find that I'm not the only one who's
been bit by this.

Cheers

**Comment by sstaszkiewicz-copperleaf** [comment]
Something like this would be extremely helpful: https://www.npmjs.com/package/dotenv#rules

There's a huge number of people that will assume that key value pairs will be read in the same way that bash reads key value pairs, and they include quotations marks in their env files.

**Comment by londoncalling** [comment]
@Stasmo the docs updates are published now [here](https://docs.docker.com/compose/env-file/) so I'll close this issue. Please ping me again on this or a new issue if you have more comments or feedback. Thanks!
