### ISSUE TITLE
404 at /engine/security/https/

### ISSUE THREAD

**Issue by Andriy2** [docker/docker.github.io#12308]
I found a broken link : https://docs.docker.com/engine/security/https/
I arrived on this page through: https://www.google.com/
Search request: docker setup tls

**Comment by manelbdcosta** [comment]
This issue seems to have been fixed here:
https://github.com/docker/docker.github.io/pull/12237/files

**Comment by thaJeztah** [comment]
oh; actually not; looks like the redirect that was created is incorrect; https://github.com/docker/docker.github.io/pull/12237/files#diff-1b37445b8d60f8f91d1847a51015fbbd4a2f6966403a132ebd31680e0d1274ffR7

**Comment by manelbdcosta** [comment]
Oh I see. Mind if take this one @thaJeztah ?

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker.github.io/pull/12322 to fix

in the meantime; the correct URL is https://docs.docker.com/engine/security/protect-access/

**Comment by thaJeztah** [comment]
> Oh I see. Mind if take this one @thaJeztah ?

Oh!! So sorry, I think I was just walking to my computer, and missed your comment 😔
Apologies!!

**Comment by manelbdcosta** [comment]
> > Oh I see. Mind if take this one @thaJeztah ?
> 
> Oh!! So sorry, I think I was just walking to my computer, and missed your comment 😔
> Apologies!!

No worries!! 😄 And good catch!
