### ISSUE TITLE
[Node.js docs feedback] develop page steps are incorrect

### ISSUE THREAD

**Issue by nkronlage** [docker/docker.github.io#12329]
### Problem description

Following steps on https://docs.docker.com/language/nodejs/develop/ does not work at the docker-compose step.

Issues:
  * curl after the docker-compose up step returns 'curl: (52) Empty reply from server'. 
     - The curl command uses http://localhost:8080/services/m/notes, but there's no explanation where the 'services/m/notes' part of it came from 
     - The SERVER_PORT env variable appears unused. I was able to make some progress by removing that and switching to use 8000.
  * Changes to the server.js file do not cause the server to restart.
     - Switching the volume line from "./:/code" to "./:/app" gets it working. 
  * The section that adds '/foo' to server.js says to add it at line 19, but the file is only 8 lines long.
     - It appears it should go before the use('/', ...) line. Printing the entire file would be helpful here.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/language/nodejs/develop/

### Suggestions for a fix

See Issues above for some potential fixes.

**Comment by david-szabo97** [comment]
>The section that adds '/foo' to server.js says to add it at line 19, but the file is only 8 lines long. It appears it should go before the use('/', ...) line. Printing the entire file would be helpful here.

Fixed by https://github.com/docker/docker.github.io/pull/12218

> curl after the docker-compose up step returns 'curl: (52) Empty reply from server'.
> The curl command uses http://localhost:8080/services/m/notes, but there's no explanation where the 'services/m/notes' part of it came from
> The SERVER_PORT env variable appears unused. I was able to make some progress by removing that and switching to use 8000.

Fixed by https://github.com/docker/docker.github.io/pull/12218

> Changes to the server.js file do not cause the server to restart.
> Switching the volume line from "./:/code" to "./:/app" gets it working.

Opened a PR https://github.com/docker/docker.github.io/pull/12354

**Comment by tymik** [comment]
Changes to the server.js file do not cause the server to restart.
    Switching the volume line from "./:/code" to "./:/app" gets it working.

Fixed by #12354
