### ISSUE TITLE
404 at: /engine/reference/builder/

### ISSUE THREAD

**Issue by casperc** [docker/docker.github.io#1234]
URL: /engine/reference/builder/

Currently when searching for onbuild in the on-site search engine (https://docs.docker.com/search/?q=onbuild) an invalid or broken link is returned as the first argument: https://www.google.com/url?q=https://docs.docker.com/engine/reference/builder/&sa=U&ved=0ahUKEwjC3r2ot9DRAhVJ3iwKHTLJDZ0QFggEMAA&client=internal-uds-cse&usg=AFQjCNHWrFeuzOjTpux3y4YlhSoEHAl2rg

**Comment by mstanleyjones** [comment]
Fixed in #1286
