### ISSUE TITLE
Had to create a bunch of extra commands due to proxy and others.

### ISSUE THREAD

**Issue by TimothyMalahy** [docker/docker.github.io#12393]
This is probably not really an issue so to speak.

How do I go about handling this more properly? I had my docker proxy settings set correctly before any of this.

So I was following the tutorial and was having a great deal of issues due to my proxy settings and other corporate non-sense.

I ended up making this my DockerFile commands

```
FROM node:12-alpine
WORKDIR /app
COPY . .
RUN yarn version
RUN yarn config set httpProxy proxy.company.com:80
RUN yarn config set httpsProxy proxy.company.com:80
RUN npm config set proxy http://proxy.company.com:80
RUN npm config set https-proxy http://proxy.company.com:80
RUN npm install --global --force yarn
RUN yarn install --production
CMD ["node", "/app/src/index.js"]
```
I added in
```
yarn config proxys
npm config proxy
npm install --global --force yarn
```

This is obviously not optimal, especially if needing to rerun this. Because it ends up taking a couple extra minutes extra.

I also ran the line like this from my terminal
```
docker build --build-arg HTTP_PROXY='proxy.company.com:80' --build-arg HTTPS_PROXY='proxy.company.com:80' -t getting-started .
```

File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For support, please try the Docker Community Slack or Forums:
- https://forums.docker.com/
- https://dockercommunity.slack.com/
