### ISSUE TITLE
Docker desktop can't switch containers on Windows with Bitlocker

### ISSUE THREAD

**Issue by sirdawidd** [docker/docker.github.io#12399]
### Expected behavior
Docker switch default containers to Windows.
### Actual behavior
[
![32516147-53cc5c56-c3d0-11e7-8dbd-a90bf0b34a26](https://user-images.githubusercontent.com/8491227/109316062-84279900-784b-11eb-9ef4-3b620de209cc.png)
](url)

### Information
![Captffffffffffffure](https://user-images.githubusercontent.com/8491227/109316147-9e617700-784b-11eb-96a9-5521e4c6f574.PNG)

### Windows Version:
Windows 10 Enterprise  
Domain-joined Work computer with Bitlocker encryption. Not possible to disable bitlocker as it's internal security rule in company.

### Steps to reproduce the behavior
Install Docker  
Launch Docker 
Press in launch bar option -> Switch to Windows containers

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. To report an issue with the Docker Desktop app, please use https://github.com/docker/for-win
