### ISSUE TITLE
Estimated reading time

### ISSUE THREAD

**Issue by zopefiend** [docker/docker.github.io#12404]
File: [develop/develop-images/baseimages.md](https://docs.docker.com/develop/develop-images/baseimages/) OK, but the only thing that really counts is the estimated comprehension time, which can be hours, even days, as a newbie wades across the web looking for definitions of lingo that you don't bother to explain, and Google can't find because of lack of context. Too many assumptions of common knowledge for a tutorial. Define terms, don't link to other pages with equally undefined terms. Actually, this applies to every page I've seen on this site. Just happened to lose patience on this page.

**Comment by craig-osterhout** [comment]
Thank you for your feedback. What are the specific terms that were not defined or linked to other pages?

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue is still applicable, please help provide more info.
