### ISSUE TITLE
Video URL is unreachable

### ISSUE THREAD

**Issue by zopefiend** [docker/docker.github.io#12405]
File: [get-started/index.md](https://docs.docker.com/get-started/) Can't play the video, Ms was so helpful dering recent update to break my audio, tried everything, can' hear though Windows thinks all is well. Tried to copy the URL to my chromebook, so I can hear the speaker. No dice. URL unreachable. Do you realize you are using bogus links?

**Comment by sudo-bmitch** [comment]
I just pulled up both videos on the page, and each had audio. Have you perhaps muted the page?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. There appears to be no issues on our side with the videos or shortened URLs. Closing the issue as this appears to be specific to your environment. 
The full URLs are:
https://www.youtube.com/watch?v=8fi7uSYlOdc
https://www.youtube.com/watch?v=iqqDU2crIEQ

You may also browse and find the videos at https://www.youtube.com/c/DockerIo/videos

You may also try opening an incognito window on your Chromebook to verify that no extensions are blocking the videos.
