### ISSUE TITLE
Documentation inconsistent with code (db/initdb route)

### ISSUE THREAD

**Issue by fletch29** [docker/docker.github.io#12407]
File: [language/python/develop.md](https://docs.docker.com/language/python/develop/)

In the "Use containers for development" section, the "app.py" file vends two routes:
```
/widgets
/db
```
However, below, the test command uses an undefined route, that 404s:
```
curl http://localhost:5000/initdb
```

**Comment by Chavithra** [comment]
Hello there,

looks like they have fixed the issue here :  #12397

I think this issue can be closed.

**Comment by StefanScherer** [comment]
Thanks @fletch29, we're working on a fix in #12559
