### ISSUE TITLE
Get started procedure results in error on Windows: '"$(pwd)" includes invalid characters for a local volume name'

### ISSUE THREAD

**Issue by adudsic** [docker/docker.github.io#12411]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

Trying to learn Docker using the **Get started** tutorial.

### Environment
I'm running Docker Desktop version 3.1.0(51484) on Windows 10 Pro version 1909.

### Issue
Under **Start a dev-mode container**, the first code block in step 2 (and the subsequent bullet list item explaining the commands) includes

`-v "$(pwd):/app"`

In Windows, when I run the command from the command line (i.e., I'm not using PowerShell), I receive the following error message:

`docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.`

### Resolution
Based on the error message, I tried using an absolute path. That didn't work.

Based on the issue [Windows sample docker command does not work](https://github.com/sitespeedio/sitespeed.io/issues/1464), I tried changing:
FROM `-v "$(pwd):/app"`
TO `-v "%cd%:/app"`

Using %cd% instead of $(pwd) worked on Windows.

### Suggested Fix
I understand that on Linux and Mac platforms, the $(pwd) should work as expected; the issue I ran in to is Windows-specific.

My suggestion is to add a **Note** immediately following the first code block. The content of the **Note** should explain that the command as shown is for Linux and Mac, and that on Windows, the user should use %cd% in place of $(pwd).

### Additional Env Info
Not sure whether this helps you to know:

I have WSL 2 enabled, but I don't have a WSL 2 distro installed. Results of running "docker version" in my command window shows the following for my [Windows] Client:
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

**Comment by mgilkes** [comment]
I tried what you said above, and I still get an error. It is a different error from before. I tried it in the Windows CMD and in PowerShell:

`C:\Users\xxxxx\Docker\app>docker run -dp 3000:3000 -w /app -v "%cd%:/app" node:12-alpine sh -c "yarn install && yarn run dev"`
`23190f0a093160ce576b47578dc224bf664617e8590a2b899d2e37e8489f7820`
`docker: Error response from daemon: error while creating mount source path '/run/desktop/mnt/host/c/Users/xxxxx/Docker/app': mkdir /run/desktop/mnt/host/c: file exists.`

What does this new error mean, and how do I fix it?
