### ISSUE TITLE
container is closed after few seconds

### ISSUE THREAD

**Issue by ZezoPrime** [docker/docker.github.io#12421]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

docker run -dp 3000:3000 `
     -w /app -v "$(pwd):/app" `
     node:12-alpine `
     sh -c "yarn install && yarn run dev"

this command runs the container but it closes after 3 seconds

**Comment by t3hami** [comment]
@ZezoPrime have you followed along or just jumped to this step? An application was set up in previous steps and you should be in that application's directory. See https://docs.docker.com/get-started/02_our_app/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this issue as stale. If the issue still persists, please provide more details.
If you need support, please try the Docker Community Slack at https://dockercommunity.slack.com/
