### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Rizkywijayasuteja** [docker/docker.github.io#12432]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by craig-osterhout** [comment]
Closing this issue as it appears empty. If there is an issue in the documentation, please let us know.

**Comment by craig-osterhout** [comment]
Closing this issue as it appears empty. If there is an issue in the documentation, please let us know.
