### ISSUE TITLE
docs: improve documents for beginners

### ISSUE THREAD

**Issue by longqua69** [docker/docker.github.io#12455]
Hello Docker team,

I'm a beginner who is exploring Docker. I've read the documents and followed the guidelines.

In [get-started/07_multi_container.md](https://docs.docker.com/get-started/07_multi_container/), there's a point that I think we should improve for other beginners who are like me at this time.

There's no description shows how to exit CLI after using **SHOW DATABASES;** command:

![mysql](https://user-images.githubusercontent.com/37626565/110236960-cb103f80-7f6b-11eb-9f9d-a2fa95fe5a29.PNG)

I did this way. I think that there are some beginners who haven't had MySQL knowledge like me at this time.

![bash](https://user-images.githubusercontent.com/37626565/110237014-175b7f80-7f6c-11eb-879d-f55be9adcfdb.PNG)

Now, I can handle it. Just need to use the command **EXIT** before starting a new container. But this interrupted my self-training. Because the target of documents is for everyone. I think we should add 1 more guide.

Could you consider this? BTW, this is awesome. Thanks for your contributions.

Best regards,

Anh Tran

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The exit command is included in the topic now.
