### ISSUE TITLE
[Run a database in a container: Connection Refused]

### ISSUE THREAD

**Issue by replork** [docker/docker.github.io#12450]
### Need to update tutorial to work with WSL2

This section of checking the connection  does not appear to be compatible with Window 10 when editing on WSL2: Ubuntu

$ curl http://localhost:5000/initdb
curl: (7) Failed to connect to localhost port 5000: Connection refused

$ curl --request POST \
  --url http://localhost:5000/widgets \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'name=widget01' \
  --data 'description=this is a test widget'
curl: (7) Failed to connect to localhost port 5000: Connection refused

I have not been able to determine a fix for this, so it would be greatly appreciated if anyone could document how to perform this step with WSL2. I have double checked the ports for the mysqldb container and the rest-server container, and all seem correct.

CONTAINER ID   IMAGE           COMMAND                  CREATED          STATUS          PORTS                               NAMES
30eb8b4dfd37   python-docker   "python3 -m flask ru…"   50 minutes ago   Up 50 minutes   0.0.0.0:5000->5000/tcp              rest-server
6d8d2c92297f   mysql           "docker-entrypoint.s…"   2 hours ago      Up 2 hours      0.0.0.0:3306->3306/tcp, 33060/tcp   mysqldb

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/language/python/develop/

- Other: Development on Windows 10 with VS Code editing on WSL2: Ubuntu

**Comment by tymik** [comment]
The documentation is not targeting the use of the WSL/WSL2 and I suppose it will not target them in near future - WSL2 is a specific layer of abstraction developed by Microsoft and should be used only by advanced users that are aware of the need of special amendments targeting WSL2.
This is beyond the Docker documentation.
