### ISSUE TITLE
Typo in "Uninstall Docker Desktop" section

### ISSUE THREAD

**Issue by ghesrob** [docker/docker.github.io#12460]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/)

The first line of the **Uninstall Docker Desktop** section contains a typo:
"_To **unistall** Docker Desktop from your Mac_": "n" is missing in "uninstall"

**Comment by usha-mandya** [comment]
@ghesrob Thanks for reporting this issue. This has been fixed :)
