### ISSUE TITLE
Feedback For: engine/installation/linux/debian.md 

### ISSUE THREAD

**Issue by jsangilve** [docker/docker.github.io#1249]
Similar to issue #1218, installation instructions suggest to execute the following command to add stable repo to apt.

```
$ sudo add-apt-repository \
       "deb https://apt.dockerproject.org/repo/pool/ \
       $(lsb_release -cs) \
       main"
```
That results on `deb https://apt.dockerproject.org/repo/pool/ jessie main` for Debian Jessie. It causes  `HttpError403` on `apt-get update`.

The URI should be: `deb https://apt.dockerproject.org/repo/ debian-jessie main`.
Debian's docs could be changed to:

```
$ sudo add-apt-repository \
       "deb https://apt.dockerproject.org/repo \
       debian-$(lsb_release -cs) \
       main"
```
Ubuntu users probably have this problem as well.

### Problem location
Installation instructions for Docker Engine in Debian/Ubuntu
https://docs.docker.com/engine/installation/linux/debian/

**Comment by mstanleyjones** [comment]
This has been fixed in `master`. Thanks!
