### ISSUE TITLE
docs: Could not find a version that satisfies the requirement cloud-init==20.4

### ISSUE THREAD

**Issue by longqua69** [docker/docker.github.io#12492]
Hi Docker team,

In this training [language/python/build-images.md](https://docs.docker.com/language/python/build-images/), I have an issue with: 

`pip3 install -r requirements.txt`

![Capture](https://user-images.githubusercontent.com/37626565/111036586-7af51980-8452-11eb-9d20-01d0829143f0.PNG)

I've tried to investigate the root cause but I can't resolve this error now. I guess the ERROR caused by the parent image of this course: **python:3.8-slim-buster**

I'm trying to figure out what the root cause is. Maybe this ERROR is not caused by Docker but I think we should add some notes for watchers.

Thanks & Best regards,

Anh Tran

**Comment by Stig124** [comment]
I believe that you ran that on the `system` python install (and that MS has added some specific python packages in wsl)

Python uses virtual environnements (`virtualenv`) to isolate packages install, and permit to create independant packages

I suggest you to run a virtualenv using [Pipenv](https://pipenv.pypa.io/en/latest/install/#make-sure-you-ve-got-python-pip) and then continue the tutorial

**Comment by longqua69** [comment]
Hello @Stig124,

Thanks for your contact. I tried the way in your shared link [Pipenv](https://pipenv.pypa.io/en/latest/install/#make-sure-you-ve-got-python-pip). But this way doesn't work.

![Capture](https://user-images.githubusercontent.com/37626565/111177311-b02d7300-85dc-11eb-9227-e061a877f937.PNG)

The fact that, I don't really know your suggestion due to I don't have enough knowledge currently (I've not understood about virtual environment, dependencies manager... and how they work).

If I didn't understand and follow correctly your intention. Please let me know ^^!

Thanks,

Anh Tran

**Comment by Stig124** [comment]
I'll give you a requirements.txt when I'll be home

**Comment by longqua69** [comment]
Hi @Stig124,

Thanks for your dedicated support

**Comment by Stig124** [comment]
@longqua69 

Paste that into the requirements.txt file

```python
click==7.1.2
Flask==1.1.2
itsdangerous==1.1.0
Jinja2==2.11.3
MarkupSafe==1.1.1
Werkzeug==1.0.1
```

**Comment by Stig124** [comment]
No, replacing the contents, not appending

**Comment by longqua69** [comment]
Hi,

I got it. It works.

Thank you so much for your support.

Could you please share me what is the root cause? Do we need to add more notes in the document for helping other people?

Best regards,

Anh Tran

**Comment by Stig124** [comment]
When you're doing `pip freeze > requirements.txt` you are reporting every packages installed, not the one that you just installed

The usage of a virtual environnement is to shield packages from a project to interfere with one another (some projects require specific versions of packages).

Take it like a Docker container, you have : 
- the `system` pip *(the host)* where almost every piece of software (you still require root privileges to install packages on system pip) can look into to see what's installed,

- the `user` pip *(rootless install of docker)* which require a specific user to run it and is shielded from the system pip (packages are installed on home directory in opposition with the system-wide pip)

And then a 
- `virtualenv` pip *(a container)*, which is project-based, only that projects knows what is installed. The advantage of `pipenv` over other pieces of `venv-wrapper` (the venv is a built-in python component and critical for any developper that does python) are it's ease of use, you run `pipenv install <package>` and then the venv is created, with only one command. And it's got a requirements.txt-like file that even auto-updates

**Comment by longqua69** [comment]
Hello @Stig124 ,

Thanks for your dedicated support. Now I can keep moving forward.

About your explanation, I haven't had enough knowledge to understand clearly what you've shared now. There are many terms that I've just known. But I can imagine the way it works because of your professional explanation.

For a clean, easy to self-study version of this document, could you please make a PR for closing this issue 😃? I think your explanation will be better than mine.

I'm waiting for your answer so I don't close this issue.

Best regards,

Anh Tran

**Comment by maoz123** [comment]
@longqua69  Hello, after filling the new dependencies, does the Python starts in your environment ?
In my case, I couldn't launch the python app.

**Comment by longqua69** [comment]
Hi @maoz123 

In my case, Python still starts in my environment. I think there's some conflicts between Virtual env and the root environment.
I close this issue. If you need to find a way to handle your issue, I think you should open a new issue.

Best regards,

Anh Tran

**Comment by Fatih90FM91** [comment]
hello guysi have same issue 
click==7.1.2
Flask==1.1.2
itsdangerous==1.1.0
Jinja2==2.11.3
MarkupSafe==1.1.1
Werkzeug==1.0.1

i tried those but it did not work please help anyone

**Comment by bhasmeht** [comment]
I have tried this on the ubuntu machine(AWS) and that is working. You please try once on that.

**Comment by bhaskarmehta** [comment]
Earlier I was getting the same issues but now I have tried this on the ubuntu machine(AWS) and this time it is working.
So please try this and I think it will work

**Comment by anushka192001** [comment]
i want to install  cloud-init==22.2 in my virtual env python 3.8.13 in windows 10.
but i am getting an error 
![image](https://user-images.githubusercontent.com/63954873/197339895-e93cace6-d5bb-4535-86e3-a8d14acebb1d.png)
