### ISSUE TITLE
Indicate if a configuration option is a build option or runtime option

### ISSUE THREAD

**Issue by sbrattla** [docker/docker.github.io#1250]
Please refer to https://docs.docker.com/compose/compose-file/ for this issue.

I find it hard to see from the documentation if a configuration option is a build option or runtime option. By this, I mean that it's hard to see if an option is respected by docker-compose when building the container or when running the container.

For instance, the `dockerfile` option is a build option. There is no way to distinguish this option from the `expose` option which is a runtime option. There might be options which are taken into consideration both during build and run; but then that should be indicated as well. Right now, there is a **build** heading / section on that page but the **build** heading  is on the same level as all other headings (`h3`). I would at least expect the build sub headings to be `h4` and to see a corresponding runtime (`h3`) heading where sub headings would be `h4` as well.

A better way, in my opinion, would be to add a build or runtime label (or both) just next to the configuration option name. 

The reason I came across this is that we use the same `docker-compse.yml` for both local development (`docker-compose build`) and swarm deployments. The "runtime" configuration options in `docker-compose.yml` must be provided to `service create` as arguments - and it would be nice to use the configuration as a definitive guide to which options we would have to provide during `service create`.

![image](https://cloud.githubusercontent.com/assets/1845372/22149056/f1e7e1fc-df11-11e6-803c-5083ffe7df6b.png)

**Comment by dnephin** [comment]
The fields that apply to build are under the `build` section (https://docs.docker.com/compose/compose-file/#build). They are H4 headings.

The rest are runtime config. This was fixed in c2 of the Compose file.

**Comment by londoncalling** [comment]
@sbrattla Please see Daniel's response ^^. I hope this clarifies build v. runtime for you. Please ping us if you have more questions or feedback.

**Comment by sbrattla** [comment]
@londoncalling I have to admit that I still think there is something odd with how things are presented. Considering that **build** (the h3 header) represents build parameters, why is then **expose** also a h3 header? **build** is an "abstract" term representing build parameters, while **expose** is a part of the Dockerfile syntax. 

My (naive and simplistic?) approach would be that there are two "top" groups : (1) build and (2) runtime. I would then add "subsections" to these groups such as "Volumes", "Networking" etc. Then I would add the actual Dockerfile syntax terms to these subgroups again. This would make it much easier understand the context of a specific syntax term.

If a term for some reason would be both a runtime and build parameter, then maybe something as simple as a @see notation could be introduced.

**Comment by dnephin** [comment]
The heading structure matches the Compose file structure. `expose` and `build` are both keys on a `service` object. 

`expose` in the Compose file refers to the runtime `expose` flag, not the Dockerfile directive.

**Comment by londoncalling** [comment]
@sbrattla just following up on @dnephin  comment, that we want the docs page to match the Compose file structure. It both reinforces the structure in terms of learning it, and also in terms of navigating both the configuration file and the document that describes it. 

That said, one thing I do think would help is to add one or two example Compose files to this page and /or link out to example files. We have them scattered around in labs and in examples in the docs. So I'll open a PR to do that and link it to this issue.

**Comment by londoncalling** [comment]
@sbrattla fyi, I'm still modifying this document, even though I merged the previous PR. I'm working on an example to include (rather than linking out to multiple samples), and I'm also revising the explanation of the structure. This should help with clarifying the Compose file structure. More soon.

**Comment by londoncalling** [comment]
@sbrattla I'm going to go ahead and close this issue now, as I feel it's better addressed with the most recent changes per the referenced PR's ^^. Feel free to re-open if you have ideas for more improvement. Thanks for the feedback.
