### ISSUE TITLE
Trying to expand documentation items, but browser fails

### ISSUE THREAD

**Issue by jeggy** [docker/docker.github.io#12510]
### Problem description

I can't expand information on the documentation page. Opening the chrome inspector I'm getting these errors:
`core.es5.js:1020 ERROR Error: Can't load component schema at /paths/~1services~1create/post/parameters/0/schema/properties/Labels`

and `core.es5.js:1020 ERROR TypeError: Cannot read property '_widgetType' of null` is showing up 4 times after each click on the expand icon.

![image](https://user-images.githubusercontent.com/51459/111299547-f66bec00-8647-11eb-98c8-690a8fbdde10.png)

### Problem location

I want to see information on this: https://docs.docker.com/engine/api/v1.40/#operation/ServiceCreate
But it seems like it's happening on every collapsed item on the page.

**Comment by pengln** [comment]
Me too, Chrome and Firfox both error

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. Closing this as a duplicate in favor of https://github.com/moby/moby/issues/32917
