### ISSUE TITLE
Make description more clearly

### ISSUE THREAD

**Issue by longqua69** [docker/docker.github.io#12537]
Hi Docker support team,

I've been learning this chapter: [language/python/run-containers.md](https://docs.docker.com/language/python/run-containers/)

I was quite confused, didn't know that I need to open a new terminal before using the `curl` command.

Because we need to use the `curl` command when the container is running. If we press `Ctrl+C` then use the `curl` command, it's not the expectation, right?

Thanks & Best regards,

Anh Tran

**Comment by StefanScherer** [comment]
Thanks @longqua69 for the feedback. Yes, a second terminal is the best way to do it. I'll take a look how we can improve that part.

**Comment by longqua69** [comment]
@StefanScherer

Thanks for your contact. I created a PR for this

**Comment by StefanScherer** [comment]
Awesome, thank you that you already created a PR for this! I'll review later.
Yes, if you see something in the other tutorial, please contribute. ❤️
