### ISSUE TITLE
Installation/getting started instructions for windows don't reflect the actuality

### ISSUE THREAD

**Issue by timrobinson33** [docker/docker.github.io#12530]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)

Actually installing and running the docker desktop is straightforward but after you've run it, the instructions tell you to expect a button with "start" which will launch the onboarding tutorial. it also says that you can go to the docker desktop menu and select "learn" to return to the tutorial at any time.

I was unable to find the start button, the docker desktop menu or the learn button. instead were some instructions to run the command `docker run -d -p 80:80 docker/getting-started`. 

the command seemed to work but didn't launch a tutorial. As a guess I opened up a browser and typed localhost in the address bar and the tutorial appeared, but I'm not sure how a novice would be expected to know that.

**Comment by aevesdocker** [comment]
Closing as this has now been fixed
