### ISSUE TITLE
A similar permission error occurred when the Docker container was started

### ISSUE THREAD

**Issue by moluzhui** [docker/docker.github.io#12533]
### Problem location
The following error occurred when I tried to run EMQX
```
root@test:~/# docker run --rm emqx/emqx:v4.1.1
node.max_ports=1048576
/usr/bin/docker-entrypoint.sh: line 133: can't create /opt/emqx/etc/emqx.conf: Permission denied
```
On **other machines**, however, the command works fine.

But it works again when I add the **-u parameter**, but isn't docker root itself

```
docker run --rm -u root emqx/emqx:v4.1.1
```

In addition, it also affects the operation of **Harbor**. I cannot open the front end of Harbor and cannot query the log information of Harbor. The error is as follows
```
docker logs -f harbor-db
Error response from daemon: configured logging driver does not support reading
```
This also appears to be a permission issue due to **Docker user error**.  I tried to restart Docker through the systemctl command and even restart the server, but it obviously didn't work. So I don't know what went wrong. 

It's worth mentioning that I once moved Docker's file directory to another location due to server storage issues
```
root@test:~/# docker info | grep Dir
WARNING: No swap limit support
 Docker Root Dir: /mnt/data/docker

cat /etc/docker/daemon.json
{
  "live-restore": true,
  "data-root": "/mnt/data/docker"
}
```

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Project version(s) affected
```
docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If there is an issue in the docs, please let us know. For support, please try the forums or Slack.
  - https://forums.docker.com/
  - https://dockercommunity.slack.com/
