### ISSUE TITLE
port number of registry.hub.docker.com is not documented

### ISSUE THREAD

**Issue by peschue** [docker/docker.github.io#12543]
I could not find the port number that should be used with registry.hub.docker.com documented anywhere.

I have a tool that requires docker registry to be specified as <host> <port> <directory> <tag> and everything must be specified.

What is the port number?

File: [registry/introduction.md](https://docs.docker.com/registry/introduction/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
The default port is 443, https://docs.docker.com/registry/deploying/#run-an-externally-accessible-registry
If you need support, please try the Docker Community Slack or Forums:
- https://forums.docker.com/
- https://dockercommunity.slack.com/
