### ISSUE TITLE
docker app init --single-file not worked in Docker 20.10.5 

### ISSUE THREAD

**Issue by chenghaopeng** [docker/docker.github.io#12568]
File: [app/working-with-app.md](https://docs.docker.com/app/working-with-app/)
unknown flag: --single-file
See 'docker app init --help'.

**Comment by jonasfa** [comment]
Looks like [this feature was removed](https://github.com/docker/app/pull/608) 2 years ago and the documentation is still outdated.

**Steps to reproduce:**
Execute:
```bash
$ docker app init --single-file hello-world
```

**Expected result:** the documentation matches the command behavior. As of writing, the documentation states that `docker app init --single-file hello-world` should create one file named `hello-world.dockerapp` containing 3 YAML sections.

**Actual result:** the documentation doesn't match the command behavior, as the command fails:
```bash
$ docker app init --single-file hello-world
unknown flag: --single-file
See 'docker app init --help'.
```
