### ISSUE TITLE
Issue with Dockerfile Code

### ISSUE THREAD

**Issue by nichecloudexpert** [docker/docker.github.io#12576]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

The container is creating, but exited immediately. the app is not working in the browser, because container is not running.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this issue as it appears to be not related to an issue in the documentation. If there is an issue in the documentation, please let us know. If you seek support, you may find help in the Docker Community Forums.
