### ISSUE TITLE
Text in docs do not match the code examples

### ISSUE THREAD

**Issue by ahorn42** [docker/docker.github.io#12590]
File: [engine/reference/commandline/login.md](https://docs.docker.com/engine/reference/commandline/login/)

The text says "For example, to use 'docker-credential-osxkeychain'" but the example code block does not contain this text. 

The same issues exists with multiple examples and code blocks at that page - or it is not clear enough what you want to tell us ;)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The preceding sentence describes why the prefix is missing in the code block.
`The value of the config property should be the suffix of the program to use (i.e. everything after docker-credential-). `
