### ISSUE TITLE
Node.js getting started: app.router is deprecated

### ISSUE THREAD

**Issue by visschersm** [docker/docker.github.io#12595]
### Problem description

In the node.js tutorial I ran into a deprecated piece of node.js code.

### Problem location

Following the node.js tutorial I ran into a deprecation error. The tutorial uses ronin-mocks with the method 'ronin-server'.router() which is deprecated. I am new to node so I did not know how to solve this. 

https://github.com/docker/docker.github.io/blob/master/get-started/nodejs/build-images.md

I've found this link to the migration github page: https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x

**Comment by foxpjustin** [comment]
https://github.com/docker/docker.github.io/issues/11778
I found the solution for me was here. The third answer about capitalization on the word "Router" from kgkars

**Comment by craig-osterhout** [comment]
@foxpjustin, thanks for linking the issues.
@visschersm, thanks for sharing the issue. As mentioned in the other issue, please verify the letter case. If you still experience an issue after that, please let us know.
