### ISSUE TITLE
Documentation on aufs driver is lacking

### ISSUE THREAD

**Issue by ph-hs** [docker/docker.github.io#126]
https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/

1. Documentation doesn't say what the default host storage limit is. I think it is 50G presently.

2. Documentation doesn't say how to change the storage limit. Specifically `--storage-opt size=150G` doesn't work with `aufs`.

**Comment by mstanleyjones** [comment]
Thanks for your feedback. I'll research this and improve the docs.

**Comment by mstanleyjones** [comment]
Hi, @ph-hs. Sorry for the delay.

1. There is no hard limit on the default host storage with AUFS, but there is a limit of 128 layers.
2. There are no configurable options for the `aufs` driver. Specifically, if you try to pass `--storage-opt`, you will get an error: https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L212-L214

If you need more configuration options, consider using a different storage driver: https://docs.docker.com/engine/userguide/storagedriver/selectadriver/

If you have more questions, please feel free to ask on https://forums.docker.com/. Thanks!
