### ISSUE TITLE
Document docker-compose vs docker compose

### ISSUE THREAD

**Issue by sumanthratna** [docker/docker.github.io#12608]
### Problem description

In the docs, it's unclear whether:
- `docker compose` and `docker-compose` are exactly the same
- users should prefer one command over the other

### Problem location

I saw a problem on the following URL:
  - https://docs.docker.com/engine/reference/commandline/compose/
  - https://docs.docker.com/compose/reference/overview/

### Project version(s) affected

n/a

### Suggestions for a fix

not really sure, since I don't know the answers to the above two questions

**Comment by AGenchev** [comment]
I wonder who decides how to name docker commands. Why on earth 'docker run' creates a new container ?!

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. A brief explanation is at documented at https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command

Some info that's outside the scope of the docs can be found below from the community.
https://www.reddit.com/r/docker/comments/mmfr5p/docker_compose_vs_dockercompose/
