### ISSUE TITLE
Ruby example .sh code block rendering command as comment

### ISSUE THREAD

**Issue by njwest** [docker/docker.github.io#12607]
File: [compose/rails.md](https://docs.docker.com/compose/rails/)

Running docker run/docker build fails with `standard_init_linux.go:187: exec user process caused "exec format error"`

**Comment by njwest** [comment]
Correction, the example works, but a bug with the way Docker docs renders code blocks makes it impossible to copy comments, and in this case causes an issue with `entrypoint.sh` because `#!/bin/bash` is mistaken for a comment.

![Screen Shot 2021-04-02 at 11 44 40 AM](https://user-images.githubusercontent.com/3742496/113378225-1241f280-93a9-11eb-98a8-04549fad2f35.png)

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. It appears this issue was fixed, although it's difficult to pinpoint the commit. If the issue still persists, please let us know.
