### ISSUE TITLE
Missing command line argument

### ISSUE THREAD

**Issue by matsuand** [docker/docker.github.io#12602]
File: [docsarchive.md](https://docs.docker.com/docsarchive/)

Im afraid there is no command line argument for the first example in this file.  The variable ``{{ archive.image }}`` specified in the document source is undefined (or blank?) because this source file was changed not to include _data/docsarchive/archive.yaml.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This appears to be fixed. If the issue still persists, please let us know.
