### ISSUE TITLE
apt-key add missing in documentation

### ISSUE THREAD

**Issue by gounselor** [docker/docker.github.io#12637]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

I think the installation instruction are missing this command:

apt-key add /usr/share/keyrings/docker-archive-keyring.gpg

Please check.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The steps appear to be correct. If you received an error when following the steps, please let us know the command and the error output.
