### ISSUE TITLE
Docker Push : Private Registry

### ISSUE THREAD

**Issue by linuxadmin25** [docker/docker.github.io#12653]
### Problem description

Hi Team,

When I am trying to push docker image to my private repository which i have set it up it throws me an error :
 
The push refers to repository [docker.io/t/ubuntu]
346be19f13b0: Preparing                                                                                                                                                     935f303ebf75: Preparing                                                                                                                                                     0e64bafdc7ee: Preparing                                                                                                                                                     denied: requested access to the resource is denied
root@DESKTOP-S3H1OVS:~/certs#

Could you please help in rectifying this? And please let me know what i am doing wrong. I am a newbie and trying to get my hands dirty on this.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For support, please try the Docker Community Slack or Forums:
- https://forums.docker.com/
- https://dockercommunity.slack.com/
