### ISSUE TITLE
mac docker desktop 启动无响应，且弹框无响应

### ISSUE THREAD

**Issue by lujiamingzZ** [docker/docker.github.io#12655]
网上看到的类似问题：https://www.coder.work/article/7378876
我遇到的问题：
![image](https://user-images.githubusercontent.com/38057088/114373898-a6843480-9bb5-11eb-8936-5976147b1842.png)
这个弹框是无法关闭的，一直在等待，mac 的活动监视器中一直是 未响应 状态。我没有办法来运行我本地的docker程序。

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As this issue is not documentation related, I will close it. You can report Docker Desktop for Mac issues at https://github.com/docker/for-mac
