### ISSUE TITLE
Docker Publish port

### ISSUE THREAD

**Issue by gautamkct** [docker/docker.github.io#12672]
Hi All,

I am bit curious about following docker run command with -p option 

`docker container run -p [host_port]:[container_port] [docker_image]`

I understand to access container port we need to map this to host port but why docker has not considered following option

`docker container run -p [container_port] [docker_image] `interpret to ------> `docker container run -p [container_port as host_port]:[container_port] [docker_image] by default`

Means If we don't specify host_port by default it should consider container_port as host_port rather than ephemeral high numbered port.

Any rational  behind why docker will assume or implemented in this way ? means why not specified container port as host port if not mentioned already in publish command instead of random ephemeral high numbered port.

**Comment by craig-osterhout** [comment]
Thanks for sharing this. For feature requests regarding the CLI, please use https://github.com/docker/cli
