### ISSUE TITLE
install instructions do not work 

### ISSUE THREAD

**Issue by TiTime** [docker/docker.github.io#12691]
File: [engine/install/debian.md](https://docs.docker.com/engine/install/debian/)

apt-get update -y \
    && apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    gnupg \
    # Add Docker’s GPG key:
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    # Download docker
    && echo  "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    # cleanup
    && apt-get autoremove -y \
    && apt-get autoclean \
    && apt-get clean \ 
    && rm -rf /var/lib/apt/lists/* \

![image](https://user-images.githubusercontent.com/16934155/115001272-cceeec00-9ea3-11eb-8df9-c1e73e82add1.png)
`

**Comment by thaJeztah** [comment]
Looks like you tried to add the package repository for Ubuntu on a Debian machine (or vice-versa)
