### ISSUE TITLE
image 'getting-started:1.0' is not referenced in "part 2"

### ISSUE THREAD

**Issue by cloojure** [docker/docker.github.io#12711]
File: [get-started/swarm-deploy.md](https://docs.docker.com/get-started/swarm-deploy/)

This page refers to the "bulletinboard:1.0" image, but in the intro Part 2 we created the "getting-started" image.  The k8s page has the same defect.  It looks like these 2 pages are referring to an outdated version of "Part 2"...?

**Comment by craig-osterhout** [comment]
Duplicate, closing in favor of https://github.com/docker/docker.github.io/issues/14066 and https://github.com/docker/docker.github.io/issues/12305
