### ISSUE TITLE
[Python docs feedback]

### ISSUE THREAD

**Issue by hrbjoern** [docker/docker.github.io#12714]
### Problem description

When I tried to do the Python tutorial:
The "pip3 freeze > requirements.txt" step created ~240 requirements (because I'm using an Anaconda installation of Python), many of which couldn't be met in the "pip install" phase of the docker image construction. Hence, the docker build returned with an error

### Suggestions for a fix

it could be helpful to link an example "requirements.txt" file, to let the reader see which modules are actually needed for the tutorial project.

**Comment by usha-mandya** [comment]
Thanks for reporting this issue. It's now fixed as part of #13507.
