### ISSUE TITLE
404 at /engine/install/ubuntu/linux-postinstall.md

### ISSUE THREAD

**Issue by civviGH** [docker/docker.github.io#12758]
I found a broken link : https://docs.docker.com/engine/install/ubuntu/linux-postinstall.md#manage-docker-as-a-non-root-user
I arrived on this page through: https://docs.docker.com/engine/install/ubuntu/

the broken link is in this section:
https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script
specifically the line:
If you would like to use Docker as a non-root user please see the post-installation steps for Linux.

kind regards

**Comment by usha-mandya** [comment]
@civviGH  Thanks for reporting the broken link issue. This issue has been fixed.
