### ISSUE TITLE
Could not find a version that satisfies the requirement cloud-init==20.2 . how do i solve this in django heroku

### ISSUE THREAD

**Issue by EdwardDanu** [docker/docker.github.io#12785]
ERROR: Could not find a version that satisfies the requirement cloud-init==20.2 (from -r /tmp/build_4329fc7b/requirements.txt (line 8)) (from versions: none)
remote:        ERROR: No matching distribution found for cloud-init==20.2 (from -r /tmp/build_4329fc7b/requirements.txt (line 8))
remote:  !     Push rejected, failed to compile Python app.

My requirement.txt
asgiref==3.3.4
attrs==19.3.0
Automat==0.8.0
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==20.2
colorama==0.4.3
command-not-found==0.3
conda==4.3.16
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
dbus-python==1.2.16
distro==1.4.0
distro-info===0.23ubuntu1
dj-database-url==0.5.0
Django==3.2
django-heroku==0.3.1
entrypoints==0.3
gunicorn==20.1.0
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
jellyfish==0.8.2
Jinja2==2.10.1
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lib50==2.0.8
MarkupSafe==1.1.0
more-itertools==4.2.0
netifaces==0.10.4
oauthlib==3.1.0
pbr==5.6.0
pexpect==4.8.0
psycopg2==2.8.6
ptyprocess==0.6.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.20.0
pycosat==0.6.3
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyrsistent==0.15.5
pyserial==3.4
python-aalib==0.4
python-apt==2.0.0+ubuntu0.20.4.1
python-debian===0.1.36ubuntu1
python-decouple==3.4
pytz==2021.1
PyYAML==5.3.1
requests==2.22.0
requests-unixsocket==0.2.0
ruamel.yaml==0.17.4
ruamel.yaml.clib==0.2.2
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
sqlparse==0.4.1
ssh-import-id==5.10
submit50==3.0.2
systemd-python==234
termcolor==1.1.0
testresources==2.0.1
touch==2020.12.3
Twisted==18.9.0
ubuntu-advantage-tools==20.3
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
values==2020.12.3
wadllib==1.3.3
whitenoise==5.2.0
zipp==1.0.0
zope.interface==4.7.1

**Comment by tymik** [comment]
Apologies for your issues. They are solely related to the Python app you have and the packages you use.
[This StackOverflow issue](https://stackoverflow.com/questions/32302379/could-not-find-a-version-that-satisfies-the-requirement-package) may have a solution that you are looking for.
