### ISSUE TITLE
404 at: /engine/reference/builder/

### ISSUE THREAD

**Issue by gabrielsallum** [docker/docker.github.io#1278]
URL: /engine/reference/builder/

Heads up: Dockerfile on the main site is inaccessible.
When I Click on the Dockerfile reference, I get a Big 404.

I guess I'll look into the TheWayBackMachine for now:
https://web.archive.org/web/20170107004921/https://docs.docker.com/engine/reference/builder/

**Comment by mstanleyjones** [comment]
Fixed in #1286
