### ISSUE TITLE
Syntax Error in: opensource/workflow/find-an-issue.md

### ISSUE THREAD

**Issue by jaredrcarlson** [docker/docker.github.io#128]
URL: https://docker.github.io/opensource/workflow/find-an-issue/

There is an extra HTML table heading opening tag on line 113.
The extra \<thead\> tag causes the table to not be displayed as intended.

**Comment by jaredrcarlson** [comment]
#dibs

**Comment by jaredrcarlson** [comment]
URL: https://docker.github.io/opensource/workflow/find-an-issue/

I have removed the extra \<thead\> tag from line 113.
I have created a pull request for this edit.

**Comment by johndmulhausen** [comment]
Thanks for the PR! Merged. :)
