### ISSUE TITLE
Proposal: Dockerfile TOC or cheat sheet

### ISSUE THREAD

**Issue by SetTrend** [docker/docker.github.io#12809]
I'm not working with Docker everyday. Actually, I'm a beginner to Docker. Often I need a quick recall of the commands available in a Dockerfile.

I like the already existing `docker` CLI [child commands](https://docs.docker.com/engine/reference/commandline/docker/) TOC, giving a brief overview of the available commands. I'm using that page as a cheat sheet.

So, I created a similar page for the Dockerfile:

![Dockerfile cheat sheet](https://user-images.githubusercontent.com/9283914/117374397-5efb7a80-aecd-11eb-9eaa-03262f0d3a51.gif)
<br/>

If you like it, I can create a PR to add it to the documentation as an introductory page for the [Dockerfile Reference](https://docs.docker.com/engine/reference/builder/) page.

To do so, I would need to know where to add the new file in the document tree, what the file name should be and how to add the new file to the navigation on the left of the page.

**Comment by craig-osterhout** [comment]
Thanks for sharing this. The [Dockerfile Reference](https://docs.docker.com/engine/reference/builder/) and most of the CLI documentation is maintained in an upstream repo by the CLI maintainers at https://github.com/docker/cli/tree/master/docs

If you'd like to try to get it added, the first step is creating a PR to add the doc in that repo. After that, it'll be pulled in and we can add it to the TOC in this repo. In regards to file naming, please look at the other file names and use your best judgement. For more info, you can check https://github.com/docker/docker.github.io/blob/master/CONTRIBUTING.md
