### ISSUE TITLE
samples/rails.md - bug in Dockerfile contents

### ISSUE THREAD

**Issue by Smacznego** [docker/docker.github.io#12819]
File: [samples/rails.md](https://docs.docker.com/samples/rails/)

Line 8 of example Dockerfile should be `COPY . /myapp` instead of current `COPY ../compose /myapp`
Seems this file was accidentally changed when doc was moved to samples dir from compose dir: https://github.com/docker/docker.github.io/commit/f4ed09424bbd237245be4a911ae888ced0b7e891#diff-3f382a1e0352f4ff5397f3e2006ee40e3c579ec833000f5975b807400f091e76R26

**Comment by thaJeztah** [comment]
looks like this was addressed in https://github.com/docker/docker.github.io/pull/13007, but these samples are quite outdated, and definitely need a cleanup overall
