### ISSUE TITLE
doesnt work on silcon Apple

### ISSUE THREAD

**Issue by justinblayney** [docker/docker.github.io#12818]
File: [get-started/04_sharing_app.md](https://docs.docker.com/get-started/04_sharing_app/)

Hello,

I have been following along your tutorial and whe nI get to the part where I need to view it in Docker playground I get the following error

WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
1c8562b20d21532f86e44b98597fe68ffbcf2ed3612d588dd29e9a4c9d2a3404

I have been trying to learn Docker the last few days with many tutorials, I get this error all over the place

![Screen-Shot-2021-05-08-at-2 03 24-PM-2](https://user-images.githubusercontent.com/5121698/117549048-4773dd00-b006-11eb-8e0e-1ea2e382ea30.jpg)

**Comment by craig-osterhout** [comment]
Closing duplicate in favor of #14546
