### ISSUE TITLE
404 at /docker-for-windows/wsl/%20for%20details%20I%20arrived%20on%20this%20page%20through:%20https://github.com/docker/docker.github.io/issues/new

### ISSUE THREAD

**Issue by omarhelmyhassan** [docker/docker.github.io#12820]
I found a broken link : https://docs.docker.com/docker-for-windows/wsl/%20for%20details%20I%20arrived%20on%20this%20page%20through:%20https://github.com/docker/docker.github.io/issues/new?title=404+at+%2Fdocker-for-windows%2Fwsl%2F%2520for%2520details.&body=I+found+a+broken+link+%3A+https%3A%2F%2Fdocs.docker.com%2Fdocker-for-windows%2Fwsl%2F%2520for%2520details.

**Comment by jerae-duffin** [comment]
Hi @omarhelmyhassan, can you provide more details how you arrived to this link?

**Comment by thaJeztah** [comment]
Thanks for reporting; the correct URL is now https://docs.docker.com/desktop/windows/wsl/

I found where the "faulty" URL is coming from; more details in https://github.com/docker/docker.github.io/pull/13382, which is not in the docs itself, but will be fixed in Docker Desktop.
