### ISSUE TITLE
Platform mismatch when using Play with Docker

### ISSUE THREAD

**Issue by brunoricardi** [docker/docker.github.io#12848]
File: [get-started/04_sharing_app.md](https://docs.docker.com/get-started/04_sharing_app/)

On the last step of this exercise, when running the freshly pushed image in a different environment (Play with Docker), I keep getting
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested.

I tried to change the underlying OS using the tools/config buttons on the left, but nothing really changes when you use them.
Adding `-- partform linux/arm64` to `docker run` seems to get rid of that error, but I can't still see anything in port 3000. Also, `docker ps` remains empty.

**Comment by craig-osterhout** [comment]
Closing duplicate in favor of #14546
