### ISSUE TITLE
404 at /docker-for-mac/)

### ISSUE THREAD

**Issue by kanika-06** [docker/docker.github.io#12852]
I found a broken link : https://docs.docker.com/docker-for-mac/)
I arrived on this page through: https://youtube.com/

**Comment by jerae-duffin** [comment]
Hi @kanika-06 
Thanks for reporting the broken link. Please report this issue on the source page where the link is located.

**Comment by thaJeztah** [comment]
That URL works for me (and redirects to https://docs.docker.com/desktop/mac/), but perhaps the redirects don't work when opened from YouTube.

let me close this one for now, as I don't think there's much we can fix there
