### ISSUE TITLE
Docker desktop - Got error when clicking Open in visual studio code 

### ISSUE THREAD

**Issue by emonno13** [docker/docker.github.io#12863]
## I got an error when opening my source code with VS code. Please help me !!

![image](https://user-images.githubusercontent.com/53046415/118675318-b5997a80-b824-11eb-9bc2-5723298ed28d.png)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Please report bugs in the for-mac or for-win repos. You can also search for existing issues there.
https://github.com/docker/for-mac/ 
https://github.com/docker/for-mac/

For support, please try the Docker Community Slack or Forums.
https://www.docker.com/support/
