### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by Accesohola** [docker/docker.github.io#12899]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

Message-ID

**Comment by Accesohola** [comment]
NoCtHuzS29@Gmail.com

**Comment by Accesohola** [comment]
12899

**Comment by tymik** [comment]
would you mind providing any details?

**Comment by thaJeztah** [comment]
let me close this one as we need more information
