### ISSUE TITLE
404 at /desktop/backup-and-restore/(../engine/reference/commandline/load.md)

### ISSUE THREAD

**Issue by Oxize** [docker/docker.github.io#12908]
I found a broken link : https://docs.docker.com/desktop/backup-and-restore/(../engine/reference/commandline/load.md)
I arrived on this page through: https://docs.docker.com/desktop/backup-and-restore/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It appears the broken link is no longer present in the current https://docs.docker.com/desktop/backup-and-restore/ .  The link should be https://docs.docker.com/engine/reference/commandline/load/ .
If you still encounter the issue, please let us know which link on https://docs.docker.com/desktop/backup-and-restore/ leads you to the 404.
