### ISSUE TITLE
Remove twin pages for commands existing twice

### ISSUE THREAD

**Issue by SetTrend** [docker/docker.github.io#12910]
Quite a number of `docker` commands exist in two (or more?) different versions.

Learning `docker` from the `docker` documentation, it's cumbersome and frustrating to print or read content, only to recognize the time and paper was wasted on double content.

Both, the surplus printing and time effort, should be addressed by having the Docker docs web server serve a redirection for twin commands, redirecting to a single canonical page, and have the single remaining page listing all sibling notation variants.

[SSOT](https://en.wikipedia.org/wiki/Single_source_of_truth) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) should be applied to docs as well as it is applied to code.

### Expected Result

| Web Address | Server response |
|-|-|
|/engine/reference/commandline/builder_build/|302 Found<br/><br/>_/engine/reference/commandline/build/_|
|/engine/reference/commandline/build/|200 OK<br/><br/>Usage:<br/>$ docker build<br/>$ docker builder build|

File: [engine/reference/commandline/builder_build.md](https://docs.docker.com/engine/reference/commandline/builder_build/)

**Comment by craig-osterhout** [comment]
Thanks for sharing this. The CLI documentation is built from an upstream repo and not maintained in this repo. To report issues or create PRs for this content, please use the source repo at https://github.com/docker/cli/tree/master/docs
