### ISSUE TITLE
Error in code for Dockerfile in Compose and Rails Quickstart example

### ISSUE THREAD

**Issue by RMaxCt** [docker/docker.github.io#12916]
File: [samples/rails.md](https://docs.docker.com/samples/rails/)

Your example Dockerfile includes

`COPY ../compose /myapp`

According to my research Docker does not allow accessing files outside the context so "../compose" causes an error.  Changing your code to the following works with your example:

`COPY . .`

**Comment by seyong** [comment]
#12819 #12721 pointed same issues.

**Comment by lucifer** [comment]
Aw thanks, man I;be just spent about an hour on this. I thought they'd deprecated `build: .` in place of the new line `context: .`

**Comment by h3ct0rjs** [comment]
Hi, I was checking the documentation, after doing a few test I noticed the same problem.

I was wondering why this issue take so long ? or do we need to do something ?

Regards, 
H

**Comment by thaJeztah** [comment]
looks like this was addressed in https://github.com/docker/docker.github.io/pull/13007, but these samples are quite outdated, and definitely need a cleanup overall
