### ISSUE TITLE
Syntax mistake?

### ISSUE THREAD

**Issue by Thomson42** [docker/docker.github.io#12915]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

In the process of following this tutorial, I came across an issue in which my get-stated container would stop immediatelyupon bootup. Thankfully I was able to find an error log in my IDE in the system. It gave me this error:
````
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/app/src/indux.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
````
Now I suspect that this error is happening because of a typo with the word indux meant to actually be spelling index. If I could I would change the typo myself but at the moment I'm lost on how to do so.

**Comment by Thomson42** [comment]
Why has no one responded? isn't this supposed to be effective documentation?

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. 
Check for the typo in your Dockerfile.
Closing as this is not related to documentation. If there is an issue in the documentation, please let us know.
