### ISSUE TITLE
Container name doesn't support in js file

### ISSUE THREAD

**Issue by Benzeman97** [docker/docker.github.io#12943]
`var db = connect("mongodb://admin:14292@mongo-db/admin");
`

when I use container name rather than `host `and `port `in the `js` file then the following error has thrown

```
connecting to: mongodb://127.0.0.1:27017/billing_db?compressors=disabled&gssapiServiceName=mongodb
Error: Authentication failed. :
```

**init_scripts/mongo_init.js**

```
var db = connect("mongodb://admin:14292@mongo-db/admin");

db = db.getSiblingDB('patient_db'); /* 'use' statement doesn't support here to switch db */

db.createUser(
    {
        user: "patient_db",
        pwd: "14292",
        roles: [ { role: "readWrite", db: "patient_db" } ]
    }
);
```

 If I use the connection with host and port instead of the container name then it works

` var db = connect("mongodb://admin:14292@127.0.0.1:27017/admin");`

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists in the docs, please provide more details.
