### ISSUE TITLE
Remove list of Buildkit benefits from reference page

### ISSUE THREAD

**Issue by telpirion** [docker/docker.github.io#12970]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

For someone who is completely new to using Docker and Dockerfiles, I found the following section unnecessary:

```
Starting with version 18.09, Docker supports a new backend for executing your builds that is provided by the
moby/buildkit project. The BuildKit backend provides many benefits compared to the old implementation.
For example, BuildKit can:

* Detect and skip executing unused build stages
* Parallelize building independent build stages
* Incrementally transfer only the changed files in your build context between builds
* Detect and skip transferring unused files in your build context
* Use external Dockerfile implementations with many new features
* Avoid side-effects with rest of the API (intermediate images and containers)
* Prioritize your build cache for automatic pruning
```

This list of benefits from the BuildKit interrupts the flow of this guide. It also sounds a lot like marketing copy. You might consider removing this list in order to keep this guide more succinct, example:

```
Starting with version 18.09, Docker supports the moby/buildkit project for executing your builds. To use the
BuildKit backend, you need to set an environment variable `DOCKER_BUILDKIT=1` on the CLI before
invoking `docker build`.

For more information about the benefits of the BuildKit backend, see [link to some other page]().
```

**Comment by craig-osterhout** [comment]
Thanks for sharing this. This content is pulled from an upstream repo and not maintained in this repo. If the issue is still applicable, please create an issue or PR in the source repo at https://github.com/docker/cli/blob/master/docs/reference/builder.md
