### ISSUE TITLE
How to change docker default registry to my private registry

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [docker/docker.github.io#12979]
Hello,

I know it's not been done till now, but I want to know whether there's a way to do this:

Suppose I have created an image called `test`. So When I run `docker run my_private.com/test`, it pulls the image. But I want is whenever I run `docker run test`, in fact it pulls from `my_private.com` registry.

Is there anyway?

**Comment by craig-osterhout** [comment]
Thanks for sharing this. Please check https://github.com/moby/moby/issues/1988
If you need interactive support, please try the Docker Community Slack or Forums, https://www.docker.com/support/
