### ISSUE TITLE
Incorrect markup seen on several pages

### ISSUE THREAD

**Issue by ry4nz** [docker/docker.github.io#13]
https://docker.github.io/docker-for-mac/
https://docker.github.io/docker-for-windows/
etc

![screen shot 2016-09-23 at 2 14 31 pm](https://cloud.githubusercontent.com/assets/8811746/18801649/e5178152-8198-11e6-8f7d-7c08d6f4c63b.png)

**Comment by frozenice** [comment]
Seems like the triple backtick isn't fully supported yet. https://docker.github.io/engine/swarm/services/ is also borked, because the nginx response code isn't escaped and includes `</html>` etc.

**Comment by johndmulhausen** [comment]
Should be fixed now, thanks!
