### ISSUE TITLE
[BUG] New apple T2 Security Chip does not work for Docker hub 

### ISSUE THREAD

**Issue by dvncan** [docker/docker.github.io#13006]
### Problem description

I just got a macbook pro 16" T2 Apple Chip, fresh install. I went to download docker hub from the online location. I got this broken Icon when dragging it to the Applications folder, image below. 

I tried the other version (the intel chip one), which didnt give me the broken image but it wouldn't let me start the application. I got the error: 
```You can’t open the application “Docker” because this application is not supported on this Mac.```

### Problem location

On install

<img width="623" alt="Screen Shot 2021-06-12 at 5 08 27 PM" src="https://user-images.githubusercontent.com/44993570/121791749-2755b180-cba2-11eb-8317-4237d06a495c.png">

### Project version(s) affected

Latest Mac Chip application

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. To report bugs in Docker Desktop, please use https://github.com/docker/for-mac
