### ISSUE TITLE
Authentication to GHCR is now possible via GITHUB_TOKEN

### ISSUE THREAD

**Issue by MakisH** [docker/docker.github.io#13037]
File: [ci-cd/github-actions.md](https://docs.docker.com/ci-cd/github-actions/)

In this documentation page, the user is instructed to create a Personal Access Token `password: ${{ secrets.GHCR_TOKEN }}`. I was confused on how to do this in the context of an organization, only to find out that there is actually an easier way now: just using `GITHUB_TOKEN`: https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry#authenticating-to-the-container-registry

> The Container registry now supports `GITHUB_TOKEN` for easy and secure authentication in your workflows. If your workflow is using a personal access token (PAT) to authenticate to ghcr.io, then we highly recommend you update your workflow to use `GITHUB_TOKEN`.

The fix here would be rather straight-forward (replace `GHCR_TOKEN` with `GITHUB_TOKEN`, but I am not sure if this would have any side-effects in other pages.

I hope I am not just more confused through this process.

**Comment by crazy-max** [comment]
@MakisH Yes this part is "outdated", we should use the ephemeral `GITHUB_TOKEN` as explained [on the `login-action` repo](https://github.com/docker/login-action#github-container-registry). (see docker/login-action#59).

@thaJeztah Do I open a PR to update documentation?

**Comment by thaJeztah** [comment]
@crazy-max if you know what needs updating, yes, feel free to open a PR to update https://docs.docker.com/ci-cd/github-actions/
