### ISSUE TITLE
macos equivalent please?

### ISSUE THREAD

**Issue by srtripathy** [docker/docker.github.io#13030]
File: [engine/release-notes/18.09.md](https://docs.docker.com/engine/release-notes/18.09/)
what is the macos equivalent of running this?
sudo systemctl show --property=MountFlags docker.service

**Comment by thaJeztah** [comment]
On macOS, the Docker Daemon ("Docker Engine") is managed by the VM that's part of Docker Desktop.  MountFlags cannot be / should not be customised in that setup, but there should be no need to check that configuration on macOS (as it should be set up correctly inside the VM)
