### ISSUE TITLE
Feedback for: docker-cloud/getting-started/your_first_service.md

### ISSUE THREAD

**Issue by lythix** [docker/docker.github.io#1304]
File: [docker-cloud/getting-started/your_first_service.md](https://docs.docker.com/docker-cloud/getting-started/your_first_service/)

Please add clean up steps. i.e. how to remove the node after testing it, and clean up the container (i.e. remove it) from the Services tab when you no longer need it.)

**Comment by sanscontext** [comment]
Hey @lythix thanks for your feedback. I've put in a PR, but I wanted to check if those instructions meet your needs?

**Comment by lythix** [comment]
Yes, thank you. I think that would help. I'm not sure what the no-local-docker instructions is but as long as it explains how to clean up and remove the service once done. It wasn't clear to me so others may also benefit the extra cleanup step. thanks!

**Comment by sanscontext** [comment]
Thanks @lythix !  (The no-local-docker thing is unrelated to your issue :) )

**Comment by lythix** [comment]
Looks good. The note about the terminated nodes etc remaining in the UI for five minutes is useful. 
I would suggest, from a UI/UX perspective that a message indicating that would make that screen more usable. It's not clear they will automatically remove. Either a message indicating they will automatically clean up or give the user a button to remove terminated nodes.

**Comment by sanscontext** [comment]
Thanks @lythix, I'll pass that on to the team.
