### ISSUE TITLE
Port explaination

### ISSUE THREAD

**Issue by Mikelsoft99** [docker/docker.github.io#13063]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

Can you please fill in different ports for host and docker, so the explaination would be much more easier to understand. Its really hard to understand if the left side is on the docker host or the right.

Thanks Mike

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This commit, https://github.com/docker/docker.github.io/commit/bcc2a90f52b125bf5de0f2974203466d99058175, should make it more clear without explicitly stating which is which.
