### ISSUE TITLE
Add docs for Prometheus metrics

### ISSUE THREAD

**Issue by justincormack** [docker/docker.github.io#1307]
We don't seem to have any documentation about the Prometheus metrics endpoint for Docker (new in 1.13) yet.

There is a daemon option `--metrics-addr` to configure (currently experimental I think), but it is really only experimental in that the exact metrics may change, this feature is not going away and will become increasingly important.

(not sure if best place - I couldnt find anything anywhere)
File: [engine/admin/runmetrics.md](https://docs.docker.com/engine/admin/runmetrics/)

The only thing on the blog is https://blog.docker.com/2016/12/docker-prometheus-joint-holiday-meetup-recap/

The 1.13 blog briefly mentions it and links to the PR https://github.com/docker/docker/pull/25820

cc @stevvooe @thaJeztah

**Comment by alexellis** [comment]
I would like to see this too 👍, it may also be worth outlining that Swarm metrics don't appear to be available yet and maybe link out here or in the docs to any PR / discussion around where they fit in the roadmap.

**Comment by thaJeztah** [comment]
It's documented in the dockerd reference, https://github.com/docker/docker/blob/master/docs/reference/commandline/dockerd.md

But that didn't make into the docs

**Comment by arun-gupta** [comment]
+1, would love to see simpler docs. @thaJeztah dockerd reference docs are a bit dense.

**Comment by stevvooe** [comment]
This is an experimental feature and we reserve the right to change the everything about it, including metrics names. I don't know how we document this in way to avoid pissing people off when we make changes.

**Comment by justincormack** [comment]
Yes, we need to make that clear, but in order to help people get started,
and feed back on the current state and requirements we need some more
docs...

**Comment by arun-gupta** [comment]
https://github.com/docker/docker/issues/27843#issuecomment-274367906 worked for me.

**Comment by alexellis** [comment]
@benhall was looking to extend the metrics, if it's likely the names of metrics could change completely that will be a real pain. stevvooe has a point about communicating that.

I've also seen Grafana plugins etc emerging for the Docker metrics available.
