### ISSUE TITLE
404 at /docker-for-windows/engine/security/trust.md

### ISSUE THREAD

**Issue by ssjin2** [docker/docker.github.io#13070]
I found a broken link : https://docs.docker.com/docker-for-windows/engine/security/trust.md

**Comment by jerae-duffin** [comment]
Hey @ssjin2 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
I think this link has been removed (or updated), so let me close this ticket, but feel free to continue the conversation if there's still a link to fix 😅
