### ISSUE TITLE
404 at /en/latest/installation/ubuntulinux/

### ISSUE THREAD

**Issue by TuLingZb** [docker/docker.github.io#13097]
I found a broken link : https://docs.docker.com/en/latest/installation/ubuntulinux/#ufw

**Comment by jerae-duffin** [comment]
Hey @TuLingZb,
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
That appears to be a very old URL, and those docs have been moved to https://docs.docker.com/engine/install/ubuntu/

Given that those (`/en/...`) URLs are at least 5 years old, I don't think we need to add redirects for these (unless a significant number of users run into those), so let me close this ticket for now
