### ISSUE TITLE
404 at /desktop/storage/volumes/index.md

### ISSUE THREAD

**Issue by mohammad-sk** [docker/docker.github.io#13096]
I found a broken link : https://docs.docker.com/desktop/storage/volumes/index.md
I arrived on this page through: https://docs.docker.com/desktop/dashboard/?utm_source=docker&utm_medium=inproductad&utm_campaign=totw-18-volume-mgmt

**Comment by craig-osterhout** [comment]
Thank you for reporting the issue. The issue appears to be fixed. https://docs.docker.com/desktop/storage/volumes/index.md does not appear in https://docs.docker.com/desktop/dashboard/?utm_source=docker&utm_medium=inproductad&utm_campaign=totw-18-volume-mgmt
If the link is still broken, please provide more details about how you accessed it, such as if you were redirected from another link.
