### ISSUE TITLE
Content on Mac and Windows Card is going out of box on get Docker Page

### ISSUE THREAD

**Issue by Jassi10000** [docker/docker.github.io#13120]
### Problem description

In the Get Docker page , the written content on cards of Mac nd Windows is going out of box

Screenshot 👍🏻 
![image](https://user-images.githubusercontent.com/64856348/124427332-e3149600-dd88-11eb-893c-3d8cbb0163ce.png)

### Problem location

- I saw a problem on the following URL: <https://docs.docker.com/get-docker/>  

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

If the styling is done with something like CSS or another styling framework , then its simple to correctly align it

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. It appears to have been resolved. If the issue still persists, please let us know.
