### ISSUE TITLE
404 at /docker-for-mac%20for%20more%20info

### ISSUE THREAD

**Issue by lifengsbotlp** [docker/docker.github.io#13128]
I found a broken link : https://docs.docker.com/docker-for-mac%20for%20more%20info

**Comment by jerae-duffin** [comment]
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
I suspect you copied some text that was not part of the URL. Let me close this ticket
