### ISSUE TITLE
curl not possible because container is still running

### ISSUE THREAD

**Issue by Sammeeey** [docker/docker.github.io#13143]
### Problem description

When the container is still running, you can't run the curl commands.

### Problem location

- I saw a problem on the following URL:
https://docs.docker.com/compose/reference/up/

### Suggestions for a fix
With the `docker-compose up` command containers can be run in detached mode.
So changing the given command from:
`$ docker-compose -f docker-compose.dev.yml up --build`
to
`$ docker-compose -f docker-compose.dev.yml up --build -d`
would run the container in the background.
So that the given curl commands (just afterwards) can be run in the same terminal windows.

Another fix would be to tell the reader to call the curl commands in a new terminal - as you did before and as suggested here:
#13142

**Comment by thaJeztah** [comment]
looks like this was fixed in https://github.com/docker/docker.github.io/pull/13142
