### ISSUE TITLE
[Python docs feedback] when building the image in docker tutorial, it can't install package from requirements.txt (Flask)

### ISSUE THREAD

**Issue by jangjungkeon** [docker/docker.github.io#13166]
When i follow this tutorial(https://docs.docker.com/language/python/build-images/) in docker guide, i have some error. this tutorial is how to build image in python code. When i write "docker build --tag python-docker .", Error occurs. 

bash can't install flask package in requirements.txt. Especially, it can't install this format like "<package name> @ file :/// ~~~ "

my error log is here
$ docker build --tag python-docker .
[+] Building 9.4s (12/13)                                                                                          
 => [internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 37B    
...
...
 => ERROR [4/5] RUN pip3 install -r requirements.txt                                                          3.0s
 > [4/5] RUN pip3 install -r requirements.txt:
#12 2.247 Processing /opt/concourse/worker/volumes/live/893742d6-dd9e-4693-6ad8-7402592041f5/volume/aiohttp_1607109646206/work
#12 2.250 ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/concourse/worker/volumes/live/893742d6-dd9e-4693-6ad8-7402592041f5/volume/aiohttp_1607109646206/work'
#12 2.250 

my requirements.txt is here
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/43978802/125236604-40778c80-e31f-11eb-97d8-5ae0e4397797.png">

my docker file is here
<img width="807" alt="image" src="https://user-images.githubusercontent.com/43978802/125236278-a6174900-e31e-11eb-9491-e4f17a4b0ccd.png">

Actually, i can't solve this problem. many package in requirement.txt are "@ file:/// ~~" format. So i can't edit to <package name>==<version> in manually.

what should i do? i need your help!

version
docker : 20.10.7
flask installed : 1.1.2
python : 3.8.2(anaconda, virtual name is python_pro2net)

**Comment by usha-mandya** [comment]
Thanks for reporting this issue. It's now fixed as part of https://github.com/docker/docker.github.io/pull/13507.
