### ISSUE TITLE
My docker start cannot start the image

### ISSUE THREAD

**Issue by trh812** [docker/docker.github.io#13163]
I am also having this issue.

I appear to have started also also not having docker be able to delete some containers after they finished running.

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 4
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.4.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.795GiB
 Name: Rain
 ID: 256T:4W3A:PUPX:TG3L:R4YB:Z67S:D23R:YSJN:J3IQ:KX3I:4ZUN:OLD6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:

 Live Restore Enabled: false

● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since 日 2021-07-11 23:59:03 CST; 10min ago
     Docs: 
 Main PID: 14666 (dockerd)
    Tasks: 10
   Memory: 115.8M
   CGroup: /system.slice/docker.service
           └─14666 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

7月 11 23:59:03 Rain systemd[1]: Started Docker Application Container Engine.
7月 11 23:59:03 Rain dockerd[14666]: time="2021-07-11T23:59:03.514512552+08:00" level=info msg="API listen on /var/run/docker.sock"
7月 11 23:59:16 Rain dockerd[14666]: time="2021-07-11T23:59:16.779758085+08:00" level=error msg="stream copy error: reading from a closed fifo"
7月 11 23:59:16 Rain dockerd[14666]: time="2021-07-11T23:59:16.789624452+08:00" level=error msg="stream copy error: reading from a closed fifo"
7月 11 23:59:16 Rain dockerd[14666]: time="2021-07-11T23:59:16.875893134+08:00" level=error msg="d0097eef061e8664df61d3e33356259b9d145aacea7fd6b8f5c182b4f585d12e cleanup: failed to delete container from containerd: no such container"
7月 11 23:59:16 Rain dockerd[14666]: time="2021-07-11T23:59:16.875951736+08:00" level=error msg="Handler for POST /v1.41/containers/d0097eef061e/start returned error: dial unix \x00/run/containerd/s/f93cfe2f6a6d610cbca7b7b5ef0134e8df32a4d5664f2ceb89c77325c5652ff8: connect: connection refused: unknown"
7月 12 00:08:33 Rain dockerd[14666]: time="2021-07-12T00:08:33.169566559+08:00" level=error msg="stream copy error: reading from a closed fifo"
7月 12 00:08:33 Rain dockerd[14666]: time="2021-07-12T00:08:33.169797977+08:00" level=error msg="stream copy error: reading from a closed fifo"
7月 12 00:08:33 Rain dockerd[14666]: time="2021-07-12T00:08:33.252149869+08:00" level=error msg="d0097eef061e8664df61d3e33356259b9d145aacea7fd6b8f5c182b4f585d12e cleanup: failed to delete container from containerd: no such container"
7月 12 00:08:33 Rain dockerd[14666]: time="2021-07-12T00:08:33.252202601+08:00" level=error msg="Handler for POST /v1.41/containers/d0097eef061e/start returned error: dial unix \x00/run/containerd/s/f93cfe2f6a6d610cbca7b7b5ef0134e8df32a4d5664f2ceb89c77325c5652ff8: connect: connection refused: unknown"

When I run docker start, I am prompted to report an error
[root@Rain ~]# docker start d0097eef061e
Error response from daemon: dial unix /run/containerd/s/f93cfe2f6a6d610cbca7b7b5ef0134e8df32a4d5664f2ceb89c77325c5652ff8: connect: connection refused: unknown
Error: failed to start containers: d0097eef061e

**Comment by thaJeztah** [comment]
This doesn't appear to be related to the documentation (this issue tracker is to report issues / feature requests for the documentation).

Please keep in mind that our GitHub issue trackers are not intended as a general support forum. Consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because of the above, but feel free to continue the conversation
