### ISSUE TITLE
asp.net core link on github

### ISSUE THREAD

**Issue by DanRegalia** [docker/docker.github.io#13167]
File: [samples/aspnet-mssql-compose.md](https://docs.docker.com/samples/aspnet-mssql-compose/)

Can you change the link to https://hub.docker.com/_/microsoft-dotnet

Current link goes to page not found

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The links appear to resolve correctly now. If the issue still persists, please let us know more details.
