### ISSUE TITLE
docker service logs stops showing logs after service restart due to any error 

### ISSUE THREAD

**Issue by nishant-vunet** [docker/docker.github.io#13165]
### Description
Running docker service logs foo on a swarm  where foo is a service, whenever foo service restart docker service logs -f foo shows previous logs not the current service logs.

###  Steps to reproduce the issue:

- Create a service foo using docker stack deploy -c foo.yml foo
- Run docker service logs --follow foo_foo
- Initially observe logs of the service
- Then container restart due to some dependency or memory issue
- Run docker service logs --follow foo
- Observe old logs of the service not the current one of the service running.

### Describe the results you received:
Logs of the service of first time when it start ,after restart new logs not shown.

### Describe the results you expected:
Logs of latest service after restart should be shown.

### Output of docker version:

> Client: Docker Engine - Community
>  Version:           20.10.6
>  API version:       1.41
>  Go version:        go1.13.15
>  Git commit:        370c289
>  Built:             Fri Apr  9 22:46:01 2021
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
>  Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.6
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       8728dd2
>   Built:            Fri Apr  9 22:44:13 2021
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.4.4
>   GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
>  runc:
>   Version:          1.0.0-rc93
>   GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

### Output of docker info:

> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   app: Docker App (Docker Inc., v0.9.1-beta3)
>   buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
> 
> Server:
>  Containers: 11
>   Running: 10
>   Paused: 0
>   Stopped: 1
>  Images: 15
>  Server Version: 20.10.6
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: false
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Cgroup Version: 1
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: active
>   NodeID: 21sivb65s84h6sum0nm5n8hn6
>   Is Manager: true
>   ClusterID: p3nlo92kiugft9uewndk2rf66
>   Managers: 3
>   Nodes: 3
>   Default Address Pool: 10.0.0.0/8  
>   SubnetSize: 24
>   Data Path Port: 4789
>   Orchestration:
>    Task History Retention Limit: 5
>   Raft:
>    Snapshot Interval: 10000
>    Number of Old Snapshots to Retain: 0
>    Heartbeat Tick: 1
>    Election Tick: 10
>   Dispatcher:
>    Heartbeat Period: 5 seconds
>   CA Configuration:
>    Expiry Duration: 3 months
>    Force Rotate: 0
>   Autolock Managers: false
>   Root Rotation In Progress: false
>   Node Address: 10.0.14.12
>   Manager Addresses:
>    10.0.14.12:2377
>    10.0.14.13:2377
>    10.0.14.14:2377
>  Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
>  runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
>  init version: de40ad0
>  Security Options:
>   apparmor
>   seccomp
>    Profile: default
>  Kernel Version: 5.4.0-1051-azure
>  Operating System: Ubuntu 18.04.5 LTS
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 8
>  Total Memory: 15.64GiB
>  Name: vunet-shipper1
>  ID: UMVO:WQQ2:7K4A:7H6H:BNKF:KS2H:3F7Z:USDX:2SPG:JMW6:M55D:PGWF
>  Docker Root Dir: /data/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false

### Additional environment details (AWS, VirtualBox, physical, etc.):
Running on azure 
Linux 5.4.0-1051-azure #53~18.04.1-Ubuntu SMP Fri Jun 18 22:32:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If any issue in the docs, please let us know. For support, please try the Docker Forums or Slack.
- https://forums.docker.com/
- https://dockercommunity.slack.com/
