### ISSUE TITLE
Language-specific guides request

### ISSUE THREAD

**Issue by wyattbiker** [docker/docker.github.io#13173]
### Problem description
Please create a guide for PHP.  Why is there no language guide for PHP? It happens to be one of the top web development tools in the world.

Thanks!

**Comment by rubersonramon7** [comment]
Please create a guide for PHP.

**Comment by navidanwar** [comment]
Please create a guide for both languages PHP and .NET as well.

**Comment by outspokenjoules** [comment]
Yes, PHP please! Bonus points if it includes the pdo_mysql extension.

**Comment by aadil96** [comment]
+1

**Comment by thaJeztah** [comment]
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12719 and https://github.com/docker/docker.github.io/issues/12249
