### ISSUE TITLE
No updated!

### ISSUE THREAD

**Issue by xiaojxiao2021** [docker/docker.github.io#13175]
File: [engine/install/centos.md](https://docs.docker.com/engine/install/centos/)

1. Repo link broken
2. Lots of dependency packages missing

**Comment by thaJeztah** [comment]
Can you provide more details on what's missing? We have many users installing (and running) docker engine on CentOS, but perhaps it's something specific to your environment / install / setup?

**Comment by thaJeztah** [comment]
closing as this went stale
