### ISSUE TITLE
Step 6/9 : COPY *.go . When using COPY with more than one source file, the destination must be a directory and end with a /

### ISSUE THREAD

**Issue by stolpovski** [docker/docker.github.io#13207]
File: [language/golang/build-images.md](https://docs.docker.com/language/golang/build-images/)

**Comment by thaJeztah** [comment]
Thanks for reporting. I suspect you are trying to build with the classic builder, which is a bit more strict on these.

Are you seeing the same problem when enabling buildkit? You can do so by setting the `DOCKER_BUILDKIT=1` environment variable; assuming you're using a Linux or macOS shell;

```bash
DOCKER_BUILDKIT=1 docker build <etc>.......
```

Or

```bash
export DOCKER_BUILDKIT=1
docker build <etc>.......
```

Other options are outlined in https://docs.docker.com/go/buildkit/



That said, I think it's good to be explicit, and to update the examples to have a trailing slash if a directory is intended to be the target.

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker.github.io/pull/13208
