### ISSUE TITLE
Absolutely no discussion about OS permissions in the OS X instructions

### ISSUE THREAD

**Issue by jdmarshall** [docker/docker.github.io#13239]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/)

When run for the first time it declares that it needs admin privileges to run, but then no more prompts appear, so I don't know what privileges it needs to run. This is not discussed anywhere in the docs.

**Comment by aevesdocker** [comment]
Closing ticket as this has now been resolved https://docs.docker.com/desktop/mac/permission-requirements/
