### ISSUE TITLE
404 at /docker-for-windows/troubleshho/virtualization

### ISSUE THREAD

**Issue by Eshebright** [docker/docker.github.io#13240]
I found a broken link : https://docs.docker.com/docker-for-windows/troubleshho/#virtualization

**Comment by thaJeztah** [comment]
Thanks for reporting the correct link should be https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization


However, I can't find a link to that location in our docs;

```bash
git grep -o "troubleshho" | wc -l
       0
```

Where did you find this link, or did you type/copy it yourself from somewhere?

**Comment by thaJeztah** [comment]
closing because of the above, but feel free to continue the conversation
