### ISSUE TITLE
404 at /toolbox/tollbox_install_windows/

### ISSUE THREAD

**Issue by Ernesto18021995** [docker/docker.github.io#13244]
I found a broken link : https://docs.docker.com/toolbox/tollbox_install_windows/

**Comment by thaJeztah** [comment]
I suspect you made a typo; the url should've been https://docs.docker.com/toolbox/toolbox_install_windows/

did you find this link somewhere, or did you type it manually?

**Comment by thaJeztah** [comment]
closing because of the above, but feel free to continue the conversation
