### ISSUE TITLE
404 at /engine/reference/commandline/compose_restart/

### ISSUE THREAD

**Issue by GeorgHs** [docker/docker.github.io#13251]
I found a broken link : https://docs.docker.com/engine/reference/commandline/compose_restart/
I arrived on this page through: https://docs.docker.com/engine/reference/commandline/compose/

**Comment by thaJeztah** [comment]
Thanks for reporting; this should be fixed by https://github.com/docker/docker.github.io/pull/13256 (which will be published on docs.docker.com soon)
