### ISSUE TITLE
Feedback for: compose/compose-file.md

### ISSUE THREAD

**Issue by brettdh** [docker/docker.github.io#1326]
File: [compose/compose-file.md](https://docs.docker.com/compose/compose-file/)

The visual difference between a configuration option (e.g. [deploy](https://docs.docker.com/compose/compose-file/#deploy)) and its sub-options is so slight that they become difficult to distinguish, especially when scrolling through a long list. For instance, scrolling down from the deploy option, I eventually see "devices", which initially seems like another sub-option but is in fact the next service configuration option below "deploy".

Please consider making these easier to distinguish - perhaps through text style or indentation.

**Comment by mstanleyjones** [comment]
I believe we improved this a lot in the site re-design. There is quite a lot of difference now in the right-hand in-page TOC.
