### ISSUE TITLE
404 at /in

### ISSUE THREAD

**Issue by neonn323** [docker/docker.github.io#13270]
I found a broken link : https://docs.docker.com/in
I arrived on this page through: https://ssh.cloud.google.com/

Trying to install outline vpn server but stumble upon the following error:

 Verifying that Docker is installed .......... NOT INSTALLED
> Would you like to install Docker? This will run 'curl                                      yttps://get.docker.com
> Installing Docker ........................... Docker installation failed, please visit https://docs.docker.com/in
stall for instructions.
Last error: # Executing docker install script, commit: 28bc4d09b3938ea30c69407d198ee8ece52c3e12
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmor -o /usr/share/keyrings/docker-arc
hive-keyring.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com
/linux/debian buster stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
W: GPG error: https://download.docker.com/linux/debian buster InRelease: The following signatures couldn't be verif
ied because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/debian buster InRelease' is not signed.
Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline M
anager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_logrwa

**Comment by jerae-duffin** [comment]
Hey @neonn323, 
Thanks for reporting the broken link. Please report this issue on the source page where the link is located.
