### ISSUE TITLE
Request update to setup Dev environment container pages

### ISSUE THREAD

**Issue by Ch3ck** [docker/docker.github.io#133]
**Description**
This issue is related to [this](https://github.com/docker/docker/issues/27244).
I just built the Docker development container on Fedora 22 using the latest clone from the docker master. When I try to run a docker daemon('docker daemon -D&') and 'dockerd -D&' in the background following the documentation; I get the following error: 
Command "daemon" is deprecated, and will be removed in Docker 1.16. 
Please run dockerd directly.
exec: "dockerd": executable file not found in $PATH

Secondly I try running dockerd -D&. I get this error:
1.) bash: dockerd: command not found

Steps to reproduce the issue:
1. make shell
2. cp bundles/1.13.0-dev/binary-client/docker* /usr/bin 
3. docker daemon -D&
4. dockerd -D&

I think the page should be updated to reflect the current build. I'm ready to fix this and PR. I just need more assistance.

**Comment by mstanleyjones** [comment]
Can you please run `ls /usr/bin/docker*` and `which dockerd` and paste the output of both of those commands here?

**Comment by Ch3ck** [comment]
@mstanleyjones Let me do that now

**Comment by Ch3ck** [comment]
Here are the details @mstanleyjones. However, I made discussed this further [here](https://github.com/docker/docker/issues/27244)
```
root@c08b4191b12d:/go/src/github.com/docker/docker# ls /usr/bin/docker*
/usr/bin/docker				/usr/bin/docker-init.md5
/usr/bin/docker-1.13.0-dev		/usr/bin/docker-init.sha256
/usr/bin/docker-1.13.0-dev.md5		/usr/bin/docker-proxy
/usr/bin/docker-1.13.0-dev.sha256	/usr/bin/docker-proxy-1.13.0-dev
/usr/bin/docker-containerd		/usr/bin/docker-proxy-1.13.0-dev.md5
/usr/bin/docker-containerd-ctr		/usr/bin/docker-proxy-1.13.0-dev.sha256
/usr/bin/docker-containerd-ctr.md5	/usr/bin/docker-runc
/usr/bin/docker-containerd-ctr.sha256	/usr/bin/docker-runc.md5
/usr/bin/docker-containerd-shim		/usr/bin/docker-runc.sha256
/usr/bin/docker-containerd-shim.md5	/usr/bin/dockerd
/usr/bin/docker-containerd-shim.sha256	/usr/bin/dockerd-1.13.0-dev
/usr/bin/docker-containerd.md5		/usr/bin/dockerd-1.13.0-dev.md5
/usr/bin/docker-containerd.sha256	/usr/bin/dockerd-1.13.0-dev.sha256
/usr/bin/docker-init
root@c08b4191b12d:/go/src/github.com/docker/docker# which dockerd
/usr/bin/dockerd
root@c08b4191b12d:/go/src/github.com/docker/docker# 
```

**Comment by Ch3ck** [comment]
@mstanleyjones Any updates on this yet?

**Comment by mstanleyjones** [comment]
On https://github.com/docker/docker/issues/27244, you were given the solution for this and also the docs in the `vnext-engine` branch have been updated to address this issue (as per https://github.com/docker/docker/issues/27244#issuecomment-252577815). This change does not apply to 1.12, which is what the `master` docs document right now. Thanks for the report, but I don't think there is anything else that needs to be done here.

By the way, Fedora 22 is EOL, so you should consider upgrading to a supported operating system for the best experience.
