### ISSUE TITLE
CentOS 7 - cannot install docker as documentation

### ISSUE THREAD

**Issue by nhantr** [docker/docker.github.io#13301]
### Problem description

I installed as the document in [https://docs.docker.com/engine/install/centos/](https://docs.docker.com/engine/install/centos/).

When I run `$ sudo yum install docker-ce docker-ce-cli containerd.io`
I got errors:
```
Error: moby-runc conflicts with containerd.io-1.4.9-3.1.el7.x86_64
Error: moby-containerd conflicts with containerd.io-1.4.9-3.1.el7.x86_64
You could try using --skip-broken to work around the problem`
```

I found the ticket for this issue in [https://github.com/docker/docker.github.io/issues/11198](https://github.com/docker/docker.github.io/issues/11198) and applied the fix as:

> 
> 
> Update --- my repo's needed to be updated --- the following resolved me: 
> ```
> curl https://packages.microsoft.com/config/rhel/7/prod.repo > ./microsoft-prod.repo
> sudo cp ./microsoft-prod.repo /etc/yum.repos.d/
> yum update -y
> ```
> [https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software](url)
> 
> _Originally posted by @cutty201 in https://github.com/docker/docker.github.io/issues/11198#issuecomment-667726765_
> 

However, it didn't help as well. I got errors:
```
Not using downloaded packages-microsoft-com-prod/repomd.xml because it is older than what we have:
  Current   : Thu Aug  5 22:06:58 2021
  Downloaded: Wed Aug  4 17:12:19 2021
No packages marked for update
```

How can I install docker??
My system is:
```
OS: CentOS Linux 7 (Core) x86_64
Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-2.9)
Kernel: 3.10.0-1160.15.2.el7.x86_64
```

**Comment by thaJeztah** [comment]
Looks like you may already have installed Microsoft's build of `docker` and `containerd` (which are called `moby-engine` and `moby-containerd`); they both provide the same, but with a different name, so you'd probably have to uninstall one.

/cc @cpuguy83

**Comment by bd0n4lds** [comment]
This worked for me, it looks like it updates the different packages, and now I can start the docker service.

[](https://linuxconfig.org/how-to-install-and-configure-docker-ce-moby-engine-on-fedora-32)

sudo dnf install docker-ce docker-ce-cli containerd.io

**Comment by craig-osterhout** [comment]
Closing this issue as stale. If you need further support, please try the Docker Community Slack or Forums:
- https://dockercommunity.slack.com/
- https://forums.docker.com/
