### ISSUE TITLE
[Python docs feedback]

### ISSUE THREAD

**Issue by jhancock1229** [docker/docker.github.io#13320]
### Problem description

The instructions for setting up the docker container pull in both Python requirements and OS requirements and it throws an error when you try to build the docker container. 

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/language/python/build-images/

### Suggestions for a fix

https://stackoverflow.com/questions/66100767/from-dockers-doc-could-not-find-a-version-that-satisfies-the-requirement-aptur

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Looks like this was fixed by https://github.com/docker/docker.github.io/commit/a9a8311643622a802932b752e49f285efa878c80
If the issue still persists, please let us know.
