### ISSUE TITLE
404 at /subscription/download-rate-limit.md

### ISSUE THREAD

**Issue by mcncyo** [docker/docker.github.io#13354]
I found a broken link : https://docs.docker.com/subscription/download-rate-limit.md#how-do-i-authenticate-pull-requests
I arrived on this page through: https://docs.docker.com/subscription/faq/

**Comment by thaJeztah** [comment]
Thanks for reporting; I opened https://github.com/docker/docker.github.io/pull/13402 to fix the link


In the meantime, the correct URL for the link is: https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests
