### ISSUE TITLE
Drop first sentence of get-started-macvlan.md

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#1335]
File: [engine/userguide/networking/get-started-macvlan.md](https://docs.docker.com/engine/userguide/networking/get-started-macvlan/)

Opening sentence no longer makes sense after migration from [docker/experimental/vlan-networks.md](https://github.com/docker/docker/blob/master/experimental/vlan-networks.md).

> The Macvlan driver is in order to make Docker users use cases and vet the implementation to ensure a hardened, production ready driver.

Would suggest dropping this sentence, and removing `now` from the second.  Will prepare a PR to the same effect.

**Comment by mstanleyjones** [comment]
Weird, this was fixed but somehow Github didn't notice.
