### ISSUE TITLE
404 at /dockerfor-windows/troubleshoot/

### ISSUE THREAD

**Issue by kushagra00** [docker/docker.github.io#13359]
![image](https://user-images.githubusercontent.com/72225297/129587465-6dab94f8-d510-4d51-9941-37db78199c08.png)
how to fix this

**Comment by thaJeztah** [comment]
I think you missed a `-` when typing that URL; the correct URL is https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization (with a dash (`-`) between `docker` and `for`)

(but it now moved to https://docs.docker.com/desktop/windows/troubleshoot/#virtualization
