### ISSUE TITLE
Linked Accounts option no longer in menu

### ISSUE THREAD

**Issue by AlicePod1** [docker/docker.github.io#13371]
File: [docker-hub/builds/link-source.md](https://docs.docker.com/docker-hub/builds/link-source/)

Please update how to link accounts, the linked accounts option shown in the menu no longer exists.

**Comment by craig-osterhout** [comment]
Banner has been added to indicate that the feature requires a subscription. https://github.com/docker/docker.github.io/commit/c605df87c64fcc15c0aaf005a77c4384703f487a
