### ISSUE TITLE
PROVA INVIO DOCUMENTALE - TORINO ORE 15:30 - DATA 21 agosto 2021 

### ISSUE THREAD

**Issue by offarj** [docker/docker.github.io#13389]
File: [search.md](https://docs.docker.com/search/), descrittivo:

Devo creare uno spazio dati che contenga in algoritmo di compressione e criptografia uno spazio dati riservati di 200 g byte in formato compresso - COME POSSO FARE?

offarj@libero.it mail end algoritmo di compressione dr. ing. gest. Calosso p.i. Aldo

**Comment by thaJeztah** [comment]
looks off-topic for this issue tracker
