### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntu.md

### ISSUE THREAD

**Issue by dmark** [docker/docker.github.io#1339]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/)

The docs as written use `lsb_release` to grab the distribution code name. If these commands are followed verbatim on a Linux Mint system, the resulting codename will be Mint-specific, but Ubuntu-specific. E.g., 'serena' rather than 'xenial'.

I'd like to suggest either adding a note for Mint users to this effect, or removing the call to `lsb_release` to make the instructions more generic.

**Comment by mstanleyjones** [comment]
We did add this note.
