### ISSUE TITLE
Feedback for: machine/get-started.md

### ISSUE THREAD

**Issue by engcheng** [docker/docker.github.io#134]
URL: [https://docs.docker.com/machine/get-started.md](https://docs.docker.com/machine/get-started/)

Under the section, "If you are using Docker for Windows"

The first line mentions: 
> Docker for Windows uses Microsoft Hyper-V for virtualization, and Hyper-V and Oracle VirtualBox are incompatible

Is there a typo error? Because Hyper-V for virtualization and Hyper-V seems to be pointing to the same thing.

.

**Comment by johndmulhausen** [comment]
@engcheng I can't repro there being more than one link. Which browser are you using?

**Comment by engcheng** [comment]
@johndmulhausen thanks for feedback. I'm using Firefox 45.4.0 on Linux 64 bits.

The [url](https://docs.docker.com/machine/get-started/) with typo which I'm referring to can be traced in the following sequence:

1. Get started with Docker Machine and a local VM
2. Prerequisite Information
3. If you are using Docker for Windows
4. Line 1

I've also attached a screenshot for further clarity in [PicPaste](http://picpaste.com/docker_machine_typo-Ylj0iPnq.png)

Hope its clearer now.

**Comment by johndmulhausen** [comment]
Thanks, @engcheng that does help, especially the screenshot. :)

So by "point to the same thing" you don't mean that there are two Hyper-V links pointing to the same thing, you mean that "Hyper-V" is being used twice in this sentence and it is not clear why, correct?

**Comment by engcheng** [comment]
yes @johndmulhausen 

If we break the statement into 2 parts, 
First, it mentions: "Docker for Windows uses Microsoft Hyper-V for virtualization"
Then, followed by "and Hyper-V and Oracle VirtualBox are incompatible"

Substituting the product name by symbols, "Docker for Windows uses A for virtualization, and A and B are incompatible". Thus it creates an impression A is both compatible and incompatible.

Think I get it. The first statement is stating what works. The second statement is saying what don't work, right?

If that's the case, perhaps may I suggest:

- it may be clearer to state that Hyper-V needs to be the only hypervisor.
- reword using however. "Docker for Windows uses A for virtualization. **However**, A and B are incompatible. Therefore, you cannot run the two solutions simultaneously.".

Do you think its clearer? Thanks for taking time to enlighten :smile:

**Comment by mstanleyjones** [comment]
I think I might understand this. You can't use Hyper-V with VirtualBox because they are incompatible. There are not enough specific nouns used in the sentence. Let me take a stab at this.

**Comment by mstanleyjones** [comment]
@engcheng PTAL at #256
