### ISSUE TITLE
Impossible to copy command snippet from docs

### ISSUE THREAD

**Issue by ash2k** [docker/docker.github.io#13403]
File: [desktop/mac/troubleshoot.md](https://docs.docker.com/desktop/mac/troubleshoot/)

In the [Check logs](https://docs.docker.com/desktop/mac/troubleshoot/#check-the-logs) section it is impossible to select (and then copy) the fist code snippet.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. It appears the issue was fixed although it's hard to track down the specific commit. If the issue still persists, please let us know.
