### ISSUE TITLE
Can't remove inactive images from docker hub

### ISSUE THREAD

**Issue by ghost** [docker/docker.github.io#13406]
### Problem description
When checking one or more inactive images / tags in Docker Hub I got this error message when clicking on the red trash-can / delete button 

"Something went wrong. Please refresh and try again."

I tried multiple private repositories with the same result.

**Comment by craig-osterhout** [comment]
Closing this as the user no longer exists, it's not a doc issue, and looks like it's been forwarded to the right team.
