### ISSUE TITLE
Pagenation broken on "Advanced Image Management" / delete inactive images

### ISSUE THREAD

**Issue by ghost** [docker/docker.github.io#13407]
### Problem description

If I have multiple pages with images and I go to page 3 as one example while filter "All" is applied and then check "Active" filter. In my case I have 10 active images. The page returns "You have no active images in this repository!"

I got all 10 images if I go to page 1 before I check "Active" filter. 

It seems pagination does not work correctly while changing filter.

**Comment by craig-osterhout** [comment]
Closing this as the user no longer exists, it's not a doc issue, and looks like it's been forwarded to the right team.
