### ISSUE TITLE
Docker daemon access denied while running from github actions

### ISSUE THREAD

**Issue by manju0906** [docker/docker.github.io#13416]
I am currently trying to setup the Github - actions and use windows VM as build server (self hosted runner). i have installed docker on windows. i am able to connect to our harbor registry from windows VM example screenshot from powershell : 

![image](https://user-images.githubusercontent.com/5094716/130992739-3254b277-d538-44f9-8e5a-d1091283d5d5.png)

but, when i try to execute the same command from github actions, i am getting access denied error

please refer the following screenshot from github-actions : 
![image](https://user-images.githubusercontent.com/5094716/130992759-5e2c7a65-fb4f-42bc-92e6-08b90612e57e.png)

can someone help me here?

**Comment by craig-osterhout** [comment]
For interactive support, please try the Docker Community Slack or Forums, https://www.docker.com/support/
