### ISSUE TITLE
Tutorial ERROR run pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by bgwells** [docker/docker.github.io#13411]
### Problem description
Tutorial Link: https://docs.docker.com/language/python/build-images/

I was following the Docker Python tutorial and came across a docker build error: 

>ERROR [4/5] RUN pip3 install -r requirements.txt 

>ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/build/80754af9/babel_1607110387436/work'

and 

>ERROR: Could not find a version that satisfies the requirement

### Problem location

Occurred after running the cmd: 
>docker build --tag python-docker .

### Suggestions for a fix

In the initial step "Sample application" I had to run the command in order to clean up the trailing @ file://path/myfile/: 
>pip3 list --format=freeze > requirements.txt

as opposed to the tutorial which populated my file in this format i.e. [Babel @ file:///tmp/build/80754af9/babel_1607110387436/work]:
>pip3 freeze > requirements.txt 

After trial and error docker builds I only required the following dependencies in my 'requirements.txt' 
>Flask
>json5
>mysql-connector-python

I would recommend including a snippet of what 'requirements.txt' should have at a minimum in case their pip3 freeze generated file causes issues.

Eventually I successfully completed the tutorial and was able to run
>docker-compose -f docker-compose.dev.yml up --build

**Comment by tetorea** [comment]
Same problem.
I modified requirements.txt to contain only Flask and I could finally build the image

**Comment by usha-mandya** [comment]
This is now fixed as part of https://github.com/docker/docker.github.io/pull/13507
