### ISSUE TITLE
Move registry/architecture.md back to docker/distribution

### ISSUE THREAD

**Issue by stevvooe** [docker/docker.github.io#1342]
This is mostly just a few architectural notes that aren't even published. Let's move this back.

https://github.com/docker/docker.github.io/blob/master/registry/architecture.md for reference.

**Comment by mstanleyjones** [comment]
Now that https://github.com/docker/distribution/issues/2282 and https://github.com/docker/distribution/issues/2284 are merged, I can do the docs part of this.
