### ISSUE TITLE
Not able to copy given code

### ISSUE THREAD

**Issue by shyamal-jadav** [docker/docker.github.io#13430]
File: [language/nodejs/develop.md](https://docs.docker.com/language/nodejs/develop/)

![Capture](https://user-images.githubusercontent.com/26648851/131259200-b220fe9c-a220-4b80-b745-be46c7edd4ad.PNG)

**Comment by thaJeztah** [comment]
Thanks for reporting! I'll have a look at this.

For context; we tried to make the code-blocks easier to copy without accidentally copying the command _output_ that's shown in some examples, but it looks like in this case, the code-highlighter detects the "payload" to be "output", and therefore doesn't allow copying.

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker.github.io/pull/13456 to fix it
