### ISSUE TITLE
Language-specific guides request c#

### ISSUE THREAD

**Issue by jimmytricks** [docker/docker.github.io#13440]
There are a few other issues that have been raised relating to there not being a c# language specific guide. 

Wanting to add some more weight behind this, as I'm quite surprised a language as large as c# and used in a great deal of enterprise level application doesn't have a language-specific guide.

If there is something I can do to help make this happen please let me know.

Contrastingly, Microsoft do have some good initial information that could be used to help build this article:

https://docs.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows

**Comment by JakubTracz** [comment]
+1

**Comment by thaJeztah** [comment]
Thanks for requesting; let me close this as duplicate of https://github.com/docker/docker.github.io/issues/12249 and https://github.com/docker/docker.github.io/issues/12697
