### ISSUE TITLE
Feedback for: engine/getstarted/step_three.md

### ISSUE THREAD

**Issue by seantcanavan** [docker/docker.github.io#1345]
File: [engine/getstarted/step_three.md](https://docs.docker.com/engine/getstarted/step_three/)

On Opera 42.0.2393.137 on Mac OS X 10.11.6 64-bit the following HTML text is rendered as raw text:

Open your browser and <a href=”https://hub.docker.com/?utm_source=getting_started_guide&utm_medium=embedded_MacOSX&utm_campaign=find_whalesay” target=_blank> browse to the Docker Hub</a>.

<img width="1213" alt="screen shot 2017-01-23 at 11 06 46 pm" src="https://cloud.githubusercontent.com/assets/6250751/22234809/a46a8bda-e1c0-11e6-8b55-be96804e556d.png">

**Comment by johndmulhausen** [comment]
Fixed in https://github.com/docker/docker.github.io/pull/1347
