### ISSUE TITLE
404 at /engine/userguide/networking//

### ISSUE THREAD

**Issue by roukmoute** [docker/docker.github.io#13462]
I found a broken link : https://docs.docker.com/engine/userguide/networking//#user-defined-networks

Comes from: https://stackoverflow.com/a/31168354/714996

**Comment by thaJeztah** [comment]
Thanks for reporting; looks like the person writing that answer in stackoverflow made a typo (double slash). I edited the answer there; https://stackoverflow.com/a/31168354/1811501

The correct URL is now https://docs.docker.com/network/network-tutorial-standalone/

Let me close this ticket
