### ISSUE TITLE
404 at /toolbox/toolbox_install_windows/%5D%E3%81%AB%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9

### ISSUE THREAD

**Issue by katsukiakima** [docker/docker.github.io#13475]
I found a broken link : https://docs.docker.com/toolbox/toolbox_install_windows/%5D%E3%81%AB%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9
I arrived on this page through: https://qiita.com/

**Comment by thaJeztah** [comment]
Those `%...` in the URL are the URL-encoded representation of `]にアクセス`. I suspect the link at https://qiita.com/ is incorrect, or that you accidentally copied some characters that were not part of the URL.

The correct URL is https://docs.docker.com/toolbox/toolbox_install_windows/, but Docker Toolbox has been deprecated, and is replaced with Docker Desktop for Windows (https://docs.docker.com/desktop/windows/).
