### ISSUE TITLE
[Node.js docs feedback]

### ISSUE THREAD

**Issue by asdf23** [docker/docker.github.io#13500]
### Problem description

Documentation does not match code example

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/language/nodejs/build-images/

- Other:  The code example and text explaining the example don't seem to match ...?

Original text:
The COPY command **takes two parameters.** The first parameter tells Docker what file(s) you would like to copy into the image. The second parameter tells Docker where you want that file(s) to be copied to. We’ll copy the package.json and package-lock.json file **into our working directory /app.**

COPY ["package.json", "package-lock.json*", "./"]

^- That looks like 1 parameter which is an array with a specific format. I suppose /app was set in the set working directory command. 
So COPY takes the first n-1 strings which are expected to be files..  then copies them to the directory which is specified in the last string?

### Suggestions for a fix

Read the documentation update the code examples to match

**Comment by tymik** [comment]
Fixed by #13711
