### ISSUE TITLE
404 at /desktop/windows/wsl/%20for%20details

### ISSUE THREAD

**Issue by sujoy00005** [docker/docker.github.io#13511]
I found a broken link : https://docs.docker.com/desktop/windows/wsl/%20for%20details

**Comment by jerae-duffin** [comment]
Hey @sujoy00005 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
Closing this ticket as this went stale

**Comment by sujoy00005** [comment]
Please go ahead, I don't remember what happened there 😢.
