### ISSUE TITLE
Docker Bug & Crash Report

### ISSUE THREAD

**Issue by classicvalues** [docker/docker.github.io#13523]
File: [desktop/dashboard.md](https://docs.docker.com/desktop/dashboard/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If you're looking for where to share bug and crash reports, please check https://docs.docker.com/desktop/faqs/general/#where-can-i-find-information-about-diagnosing-and-troubleshooting-docker-desktop-issues
