### ISSUE TITLE
Can't copy from PS code excerpt | General Copy Code button feature request

### ISSUE THREAD

**Issue by ollyhowell** [docker/docker.github.io#13536]
File: [get-started/07_multi_container.md](https://docs.docker.com/get-started/07_multi_container/)

Copying code from https://github.com/docker/getting-started/edit/master/docs/tutorial/using-bind-mounts/index.md works but not from https://github.com/docker/getting-started/blob/master/docs/tutorial/multi-container-apps/index.md. Kinda annoying since it's several lines and works elsewhere.

I had a look at source but couldn't work out why.

If you copy from github directly (which also has the Copy Code button) then you don't get this issue.

**Comment by craig-osterhout** [comment]
It appears to have been fixed in https://github.com/docker/docker.github.io/commit/5bf13c7380b25c7a42bcbc4782f79af7114c96cd
If the issue still persists, please let us know.
