### ISSUE TITLE
missing description regarding restart (not restart_policy)

### ISSUE THREAD

**Issue by Vad1mo** [docker/docker.github.io#1353]
### Problem description

I was looking for
restart options but could not find any entries especially the option that existed none, on-failure and always can't be found anymore. also they are not marked as deprecated.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/compose/compose-file/

### Project version(s) affected
compose 1.10

### Suggestions for a fix

I remember this info was in older docs, but I can't find them anymore.

**Comment by surajnarwade** [comment]
i will work on this
