### ISSUE TITLE
Docker Daemon

### ISSUE THREAD

**Issue by rozzamozza** [docker/docker.github.io#13542]
File: [desktop/mac/install.md](https://docs.docker.com/desktop/mac/install/)

At no point do you mention that this is just docker client and that docker daemon wont be installed. 

Lots of time wasted trying to realise mac install is not a full install:
https://stackoverflow.com/questions/44084846/cannot-connect-to-the-docker-daemon-on-macos

**Comment by thaJeztah** [comment]
Can you provide more details? The Docker Desktop installation installs both the `docker` cli and a minimal Linux VM that runs the Docker Engine (Docker Daemon). The "failed to connect to the docker daemon" error can occur if the VM failed to start (you can see the status through the "whale" icon in your menu bar, which should show "Docker Desktop is Running").

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as stale unless more details are provided.
