### ISSUE TITLE
The filesystem path doesn't show up in the UI, it's below the fold...!

### ISSUE THREAD

**Issue by epugh** [docker/docker.github.io#13558]
File: [desktop/mac/space.md](https://docs.docker.com/desktop/mac/space/)

I didn't realize I could edit the location until reading the docs TWICE, and it's because it's not clear you need to scroll..   The filesystem path setting shouldn't be below the fold of the screen, there isn't that much going on in this UI to need scrolling ;-)

**Comment by aevesdocker** [comment]
Closing as this is now resolved
