### ISSUE TITLE
Provide download links for older versions

### ISSUE THREAD

**Issue by matthughes** [docker/docker.github.io#1356]
File: [docker-for-mac/release-notes.md](https://docs.docker.com/docker-for-mac/release-notes/)

The changelog should provide links to download older releases.

**Comment by mstanleyjones** [comment]
Not sure the policy on this.

**Comment by friism** [comment]
@matthughes thanks for opening this issue. Quoting from [here](https://github.com/docker/for-mac/issues/1120#issuecomment-277774579):

> We're continuously fixing bugs (including security-related problems), and those fixes are released in new versions of Docker for Mac. We don't support or patch older versions - we only support the latest version on the stable and beta channels respectively.
> Because we want users to be running software that's patched and secure, we don't publicly document how to download and install old versions.
> If you find bugs in Docker for Mac and Windows (either stable or beta), please run the in-app diagnostics and open an issue so that we can address the problem.

**Comment by londoncalling** [comment]
@friism thanks for the clarification, closing this issue for now

**Comment by panuhorsmalahti** [comment]
That explanation by @matthughes is problematic, since it forces users to accept new software licenses / end user license agreements. Users should have the possibility to download older versions with different EULAs, even if they have security issues.

**Comment by sistematico** [comment]
And docker newer than 1.10 don't run with CentOS 7 OpenVZ...
