### ISSUE TITLE
404 at /reference/commandline/inspect/

### ISSUE THREAD

**Issue by Hadagan** [docker/docker.github.io#13565]
I found a broken link : https://docs.docker.com/reference/commandline/inspect/

**Comment by jerae-duffin** [comment]
Hey @Hadagan 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
I think this may have been a _really_ old URL (I recall that used to be the URL for those reference docs); the current URL for that page is https://docs.docker.com/engine/reference/commandline/inspect/

Perhaps we should add redirects for those, but I haven't seen many reports, so I think that can wait for now.

Let me close this ticket for now, but feel free to continue the conversation 👍
