### ISSUE TITLE
404 at /desktop/windows/install/%20

### ISSUE THREAD

**Issue by Pranay4852** [docker/docker.github.io#13583]
I found a broken link : https://docs.docker.com/desktop/windows/install/%20
I arrived on this page through: https://www.google.com/

**Comment by thaJeztah** [comment]
I suspect you accidentally copied a trailing space (or someone posted an incorrect URL somewhere)

The correct URL for that page is https://docs.docker.com/desktop/windows/install/


I checked our source code, and I couldn't find the link mentioned, so let me close this ticket, but feel free to continue the conversation
