### ISSUE TITLE
Validate and install commands seem to be deprecated - this guide appears to be outdated

### ISSUE THREAD

**Issue by petrunov** [docker/docker.github.io#13599]
File: [engine/reference/commandline/app.md](https://docs.docker.com/engine/reference/commandline/app/)

**Comment by danBamikiya** [comment]
Hi the entire guide is deprecated so it shouldn't be used.

![docker_docs_website_issue_close_2](https://user-images.githubusercontent.com/58262528/136817335-1db81ece-ef47-4a2c-82b8-512c8d2a1b7a.png)
