### ISSUE TITLE
/desktop/windows/wsl.md has a broken link

### ISSUE THREAD

**Issue by nazrhyn** [docker/docker.github.io#13605]
### Problem description
https://github.com/docker/docker.github.io/blob/master/desktop/windows/wsl.md
```md
- If you have concerns about the size of the docker-desktop-data VHDX, or need to change it, take a look at the [WSL tooling built into Windows](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#understanding-wsl-2-uses-a-vhd-and-what-to-do-if-you-reach-its-max-size).
```

The link in this line is broken.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/desktop/windows/wsl/

### Suggestions for a fix

I'm not 100% sure what the right link is, but maybe this one: https://docs.microsoft.com/en-us/windows/wsl/vhd-size

If you can confirm the correct URL, I'd be happy to make a PR to change it.

**Comment by craig-osterhout** [comment]
Resolved in https://github.com/docker/docker.github.io/commit/5ef5b7228f65b52efe939e45267c9f8af78c3917
If the issue still persists, please let us known.
