### ISSUE TITLE
Add ability to hide right side nav

### ISSUE THREAD

**Issue by willfranklyn** [docker/docker.github.io#13617]
File: [cloud/ecs-compose-features.md](https://docs.docker.com/cloud/ecs-compose-features/)

Right nav often covers up documentation while I'm trying to view the page. It would be great if you could toggle it open or closed.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as stale. If the comment above didn't resolve the issue, please let us know more details.
