### ISSUE TITLE
Issue while pushing images to registry after upgrade of docker desktop to 4.1.0 version

### ISSUE THREAD

**Issue by goyash17** [docker/docker.github.io#13652]
### Problem description
Unable to push images to local docker registry after upgarding docker desktop from 4.0.1 to 4.1.0

### Problem location

Problem observed by me on my terminal while pushing to the local docker registry-
The push refers to repository [localhost:5000/mysql]
Get "http://localhost:5000/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
make: *** [download-images] Error 1

### Project version(s) affected
docker desktop - 4.1.0

### Suggestions for a fix
For fixing the problem at my end, i had to downgrade docker desktop from 4.1.0 to 4.0.1

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. To report bugs with Docker Desktop, please use:
- https://github.com/docker/for-mac
- https://github.com/docker/for-win
