### ISSUE TITLE
404 at /desktop/subscription/index.md

### ISSUE THREAD

**Issue by akmalick** [docker/docker.github.io#13690]
I found a broken link : https://docs.docker.com/desktop/subscription/index.md#docker-desktop-license-agreement
I arrived on this page through: https://docs.docker.com/desktop/windows/release-notes/

**Comment by thaJeztah** [comment]
Thanks for reporting; I think a fix for this is included in https://github.com/docker/docker.github.io/pull/13514 (likely to be merged soon)
