### ISSUE TITLE
Run `spring-javaformat:apply` to fix

### ISSUE THREAD

**Issue by clnmahone** [docker/docker.github.io#13693]
### Problem description
`Failed to execute goal io.spring.javaformat:spring-javaformat-maven-plugin:0.0.25:validate (default) on project spring-petclinic: Formatting violations found in the following files:`

### Problem location
https://docs.docker.com/language/java/develop/#use-compose-to-develop-locally

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by tymik** [comment]
@clnmahone thank you for the report. Unfortunately, this seems like an issue with the spring example and should be reported there.
