### ISSUE TITLE
Feedback for: ucp/installation/license.md

### ISSUE THREAD

**Issue by patrocinio** [docker/docker.github.io#137]
URL: [https://docs.docker.com/ucp/installation/license.md](https://docs.docker.com/ucp/installation/license/)

Is there a way to load the license file through API or CLI?

Thanks!

**Comment by joaofnfernandes** [comment]
You can bind-mount the license file when running the install command, as specified in the [UCP install reference docs](https://docs.docker.com/ucp/reference/install/).

Next time, please post your questions like these in https://forums.docker.com/.
