### ISSUE TITLE
Docker compose installation on linux fails due to wrong download link

### ISSUE THREAD

**Issue by srikarad07** [docker/docker.github.io#13716]
### Problem description

I was following the download instructions for Linux and used the below command to download:

`sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

However, the curl output returns - Not found for the aforementioned link. 

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/compose/install/  For the download instructions for linux at 1  where you can see the curl link to download docker-compose. 

### Suggestions for a fix

This issue happens because the download link is not correct and hence cannot be found. For my purposes I just used this and it worked: 

`sudo curl -L https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose`

So essentially there should be a "v" before the version and it will work.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The example command has been updated.
