### ISSUE TITLE
404 at /destok/windows/troubleshoot/

### ISSUE THREAD

**Issue by joaovkruger** [docker/docker.github.io#13721]
I found a broken link : https://docs.docker.com/destok/windows/troubleshoot/#virtualization

**Comment by thaJeztah** [comment]
I suspect you made a typo when typing that URL (`destok` instead of `desktop`); the correct URL is https://docs.docker.com/desktop/windows/troubleshoot/#virtualization, but let us know if you found the broken link somewhere in our docs
