### ISSUE TITLE
docker-for-azure/deploy.md no longer referenced on docs.docker.com

### ISSUE THREAD

**Issue by larryms** [docker/docker.github.io#1374]
### Problem description
This is really a documentation feedback report:  when docker-for-azure moved out of beta, it appears that the docs.azure.com site lost the link to docker-for-azure/deploy.md.
This is an important piece of documenation on how to use the docker-for-azure tool, and it should be available on the docs.docker.com without having to dig around for the file on github.

**Comment by mstanleyjones** [comment]
@FrenchBen PTAL

**Comment by FrenchBen** [comment]
@larryms What am I missing?
https://docs.docker.com/docker-for-azure/deploy/

**Comment by larryms** [comment]
@FrenchBen looks like this issue was fixed at some point after I opened it.  Thanks anyway!
