### ISSUE TITLE
404 at /desktop/windows/trobleshoot/

### ISSUE THREAD

**Issue by ProBablo** [docker/docker.github.io#13743]
I found a broken link : https://docs.docker.com/desktop/windows/trobleshoot/#virtualization

**Comment by thaJeztah** [comment]
Thanks for reporting; where did you find that link? I did a search in our source repositories, and couldn't find that one.

The correct URL for that page is https://docs.docker.com/desktop/windows/troubleshoot/#virtualization

**Comment by thaJeztah** [comment]
let me close this ticket as we need more details
