### ISSUE TITLE
Error invoking remote method 'desktop-backend': Error: "invalid daemon settings: \"host\":\n Invalid option"

### ISSUE THREAD

**Issue by finagin** [docker/docker.github.io#13755]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)
MacOS: 11.6
Docker Engine: v20.10.8

**Comment by craig-osterhout** [comment]
@finagin, thanks for sharing the issue. For support, please try the Docker forums or Slack.
- https://forums.docker.com/
- https://dockercommunity.slack.com/
