### ISSUE TITLE
404 at /reference/api/docker-io_api/

### ISSUE THREAD

**Issue by javastl** [docker/docker.github.io#13752]
I found a broken link : https://docs.docker.com/reference/api/docker-io_api/#delete-a-user-repository

I need to delete an empty repository in my account

**Comment by thaJeztah** [comment]
Could you tell where you found that link?

**Comment by javastl** [comment]
It was one of the answers found in this thread
https://stackoverflow.com/questions/44209644/how-do-i-delete-a-docker-image-from-docker-hub-via-command-line

**Comment by thaJeztah** [comment]
> Use the Docker Hub API as documented in: https://docs.docker.com/v1.7/reference/api/docker-io_api/#delete-a-user-repository

Hm.. yes, that looks to be an archived link from around [docker 1.7  (2015)](https://github.com/moby/moby/releases/v1.7.0). The source for that can still be found here; https://github.com/moby/moby/blob/v1.7.0/docs/reference/api/docker-io_api.md#delete-a-user-repository

But that describes the deprecated V1 registry, which is no longer supported. Container Registries now use the v2 OCI Distribution Spec API (see https://github.com/opencontainers/distribution-spec/blob/v1.0.0/spec.md#content-management, and https://docs.docker.com/registry/spec/api/)
