### ISSUE TITLE
teach to copy application (files) from getting-started

### ISSUE THREAD

**Issue by ak211** [docker/docker.github.io#13750]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

At this point of tutorial users don't have any application (/app). Maybe this is the reason why so many ,,not OK'' ratings are added on this page.

It would be a great opportunity to teach copy files from container.

In my case I found app.js.. and copied it with ,,docker cp __myContainerId__:/app /home/ak/tmp/''

Aftert this step my changes worked fine on app.js

Best regards,
Ak (a docker newbie)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As the issue is old, some context may have changed. The current getting started topics are meant to be done sequentially and are currently numbered. 
The application is acquired before doing part 6, in part 2, https://docs.docker.com/get-started/02_our_app/
