### ISSUE TITLE
Feedback for: compose/compose-file.md

### ISSUE THREAD

**Issue by caervs** [docker/docker.github.io#1376]
File: [compose/compose-file.md](https://docs.docker.com/compose/compose-file/)

The `update_config` subsection under [deploy](https://docs.docker.com/compose/compose-file/#/deploy) still has two fields with description "TODO"

**Comment by londoncalling** [comment]
@caervs thanks for the feedback! I've added these descriptions to the file and republished it, so you can check it out here: https://docs.docker.com/compose/compose-file/#/deploy

Much appreciate it, closing the issue. Please ping us again if you find more problems.

**Comment by caervs** [comment]
Looks good. Thanks for the quick response, @londoncalling!
