### ISSUE TITLE
docker-compose install command 

### ISSUE THREAD

**Issue by jacky9813** [docker/docker.github.io#13780]
File: [compose/install.md](https://docs.docker.com/compose/install/)

About the installation process of Linux, `uname -s` returns "Linux" with capital "L". 
Unfortunately, the path name of GitHub Release is case sensitive,
With the release file using `linux` instead of `Linux`, the command will write "Not Found" to `/usr/local/bin/docker-compose`.

Changing to the following may help, which uses `tr` to lower the case of `uname -s` output.
``` bash
$ COMPOSE_VERSION=v2.1.0
$ sudo curl -L "https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)" -o /usr/local/bin/docker-compose
```

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The docs were revamped recently, so some context may have been lost. The install docs no longer use variables. If you still see the issue in another topic, please let us know.
