### ISSUE TITLE
Installation docs do not say if docker supports MacOS Monterey

### ISSUE THREAD

**Issue by clemf** [docker/docker.github.io#13788]
### Problem description

From the docs:
> Docker supports Docker Desktop on the most recent versions of macOS. That is, the current release of macOS and the previous two releases. As new major versions of macOS are made generally available, Docker stops supporting the oldest version and supports the newest version of macOS (in addition to the previous two releases). Docker Desktop currently supports macOS Mojave, macOS Catalina, and macOS Big Sur.

Monterey has been the newest version for over a week now making this statement contradictory.

### Problem location

https://docs.docker.com/desktop/mac/install/

### Suggestions for a fix

Update installation docs with information on Monterey.

**Comment by thaJeztah** [comment]
Thanks for reporting; this should be fixed by https://github.com/docker/docker.github.io/pull/13816
