### ISSUE TITLE
Track Compose 3.1 docs updates incl. secrets to be released w/Engine 1.13.1

### ISSUE THREAD

**Issue by londoncalling** [docker/docker.github.io#1379]
This is a tracking issue to make sure docs are updated for Compose 3.1

- secrets

- other ...?

If developers update docs for Compose v3.1, please submit PR's to `vnext-compose` at  https://github.com/docker/docker.github.io/tree/vnext-compose

### Reviewers

@dnephin @shin- @mstanleyjones @joaofnfernandes

**Comment by londoncalling** [comment]
@dnephin we are going to create vnext-1.13.1 branch for docs re: all products so Compose docs updates can go in there

**Comment by mstanleyjones** [comment]
I'm gonna make the branch now...

**Comment by mstanleyjones** [comment]
And, done.

**Comment by mstanleyjones** [comment]
@joaofnfernandes see https://github.com/docker/docker/milestone/64 to answer your question about what's included.

**Comment by mstanleyjones** [comment]
ping @londoncalling

**Comment by londoncalling** [comment]
@mstanleyjones ok there is stuff in there ...

**Comment by mstanleyjones** [comment]
See #1662
