### ISSUE TITLE
SEO redirects for "daemon" broken

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#138]
It looks like the SEO redirects (aliases) don't work on the new site. I haven't checked others, but for example;

- https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file
- https://docs.docker.com/engine/reference/commandline/daemon/

Do not redirect to 

https://docs.docker.com/engine/reference/commandline/dockerd/

(although the source looks to contain an alias: https://github.com/docker/docker.github.io/blame/master/engine/reference/commandline/dockerd.md#L3

**Comment by johndmulhausen** [comment]
Fixed in 778f02e5992d8eefdb9b8813c371e5d580b427db
