### ISSUE TITLE
Linux install command, URL formatting beware

### ISSUE THREAD

**Issue by cj0nes** [docker/docker.github.io#13802]
File: [compose/install.md](https://docs.docker.com/compose/install/)

The instructions state that if a different version than what is indicated is required, just replace the the version number. This is slightly misleading because it seems as of v2.0.0-rc.3, the URL formatting has changed to include a "v".

When excluding the "v", curl completes successfully, but `docker-compose` cannot be ran. It results in `/usr/local/bin/docker-compose: line 1: Not: command not found`.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The "v" is now included in the example curl command and the "v" is indicated as part of the version string.
