### ISSUE TITLE
404 at /docker-for-linux/troubleshoot

### ISSUE THREAD

**Issue by curiouslove** [docker/docker.github.io#13817]
I found a broken link : https://docs.docker.com/docker-for-linux/troubleshoot

**Comment by thaJeztah** [comment]
Thanks for reporting; I'm curious; where did you find a link to that page? Was it from somewhere on docs.docker.com, or did you arrive there from an external website?

**Comment by thaJeztah** [comment]
let me close this ticket as we need more details
