### ISSUE TITLE
remove duplicate "r" character in "Azure Container Instances: running single containerrs" title

### ISSUE THREAD

**Issue by M-M-M-M** [docker/docker.github.io#13824]
File: [cloud/aci-container-features.md](https://docs.docker.com/cloud/aci-container-features/)

rename:
Azure Container Instances: running single containerrs

to:
Azure Container Instances: running single containers

**Comment by thaJeztah** [comment]
Thanks for reporting; looks like this was fixed in https://github.com/docker/compose-cli/pull/2102
