### ISSUE TITLE
Update Docker Registry docs to v2.6

### ISSUE THREAD

**Issue by fresnizky** [docker/docker.github.io#1383]
### Problem description
Docker Registry 2.6 was released on 2017-01-18, but the docs are still not available, can you please update them?

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://github.com/docker/docker.github.io/tree/master/registry

### Project version(s) affected
Docker Registry 2.6

**Comment by mstanleyjones** [comment]
I don't think Registry 2.6 has shipped in a Docker Engine version yet. @stevvooe can you confirm?

**Comment by stevvooe** [comment]
> I don't think Registry 2.6 has shipped in a Docker Engine version yet.

The registry ships independently, as far as I know. Looks like the release was tagged in https://github.com/docker/distribution/releases. We've shipped binaries here: https://hub.docker.com/_/registry/.

@dmp42 @andrewhsu What is the process for this going forward?

**Comment by mstanleyjones** [comment]
If the Registry files used by the `master` branch in the docs need to be pulled from a different branch, someone in that team should either raise a PR against our Dockerfile or raise a GH issue for us to do it. This time, this issue will suffice if someone can confirm that version 26 is correct.
