### ISSUE TITLE
404 at /go/guides/github.com/dockersamples/example-voting-app

### ISSUE THREAD

**Issue by Kastellos** [docker/docker.github.io#13838]
I found a broken link : https://docs.docker.com/go/guides/github.com/dockersamples/example-voting-app

**Comment by jerae-duffin** [comment]
Hey! @Kastellos 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
let me close this ticket as we need more details
