### ISSUE TITLE
Dockerfile example shows "python" instead of "python3" (even though there's python3 in the page source)

### ISSUE THREAD

**Issue by RichardBenes** [docker/docker.github.io#13830]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

Hello,

as the caption says - the code example of Dockerfile states:
```dockerfile
RUN apk add --no-cache python g++ make
```
And that does not work. There has to be `python3`.
Weirdly enough, there **is** `python3` in the page source. 
So maybe some flaw in syntax highlighter?
I experienced this problem with Firefox & Chromium on Linux Mint.

Best regards,
Richard Beneš

**Comment by thaJeztah** [comment]
The source was updated recently (https://github.com/docker/docker.github.io/pull/13826) but that was merged after the last deploy of the docs; it should be published soon (later today)

**Comment by usha-mandya** [comment]
@RichardBenes The updates are now live - https://docs.docker.com/get-started/02_our_app/

**Comment by usha-mandya** [comment]
Closing this issue as the updates are live. Feel free to continue the conversation after I close.
