### ISSUE TITLE
Feedback for: compose/compose-file.md

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#1385]
File: [compose/compose-file.md](https://docs.docker.com/compose/compose-file/)

Under `update_config`, the last three items (`update_config`, `parallelism`, and `delay`) should be bullets but aren't:

<img width="729" alt="screenshot 2017-01-26 at 5 34 58 am" src="https://cloud.githubusercontent.com/assets/414445/22329934/34378758-e389-11e6-89aa-d5cbb782219a.png">

**Comment by JimGalasyn** [comment]
Thank you for the feedback! In fact, they should be in a code block, and this has been fixed: https://docs.docker.com/compose/compose-file/#updateconfig .
