### ISSUE TITLE
Which version does this documentation relate to?

### ISSUE THREAD

**Issue by AndreSteenveld** [docker/docker.github.io#13859]
File: [engine/reference/commandline/compose_ps.md](https://docs.docker.com/engine/reference/commandline/compose_ps/)

As stated in the title, which version of the CLI is documented here? I think I'm on the most recent version I can get for windows (`docker --version` outputs `Docker version 20.10.9, build c2ea9bc`) but when running `docker compose ps --help` I'm not seeing the option to specify a service. I've tried looking further up in the tree (the general CLI documentation) to see if I could find a version number it should relate to but I can't seem to find any.

```
$ docker compose ps --help

Usage:  docker compose ps

List containers

Options:
  -a, --all             Show all stopped containers (including those
                        created by the run command)
      --format string   Format the output. Values: [pretty | json].
                        (default "pretty")
  -q, --quiet           Only display IDs
      --services        Display services
```

**Comment by thaJeztah** [comment]
Are you running Docker Desktop for Windows? What version does `docker compose version` show?

I tried this on the current version of Docker Desktop (for Mac in my case, but this should be the same), and see the `[SERVICE..]` in the output;

```bash
docker compose ps --help

Usage:  docker compose ps [SERVICE...]

List containers

Options:
  -a, --all                  Show all stopped containers (including those created by the run command)
      --format string        Format the output. Values: [pretty | json] (default "pretty")
  -q, --quiet                Only display IDs
      --services             Display services
      --status stringArray   Filter services by status. Values: [paused | restarting | removing | running | dead | created | exited]
```

**Comment by craig-osterhout** [comment]
Closing this as stale. If the issue is still applicable, please help provide the info requested in the previous comment.
