### ISSUE TITLE
Installation Instruction Outdated for Version 2.1.x

### ISSUE THREAD

**Issue by barmanroys** [docker/docker.github.io#13867]
File: [compose/install.md](https://docs.docker.com/compose/install/)

The installation instruction, does not work for versions 2.1.x (the latest recommended release). Replace the instruction to make them consistent with [https://github.com/docker/compose/releases](url)

**Comment by iamk3** [comment]
I also raised this the other day without doing more research. It could definitely be more clear in the docs about compose v1 vs v2, but the installation method for v2 is completely different and is covered in the documentation.
