### ISSUE TITLE
problem in docker-compose

### ISSUE THREAD

**Issue by boistordu** [docker/docker.github.io#1389]
### Problem description

ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
### Problem location

everything is int the error message I guess
### Project version(s) affected

docker engine 1.13 for the moment

**Comment by mstanleyjones** [comment]
We need more info. It sounds like you were having trouble with a specific compose file. Were you using one from an example in the docs?

**Comment by boistordu** [comment]
Sorry I m traveling for now so I don't get always the time to test correctly. I will provide you with the launch line if you want but a compose file ?
There is only 3 files right? And so which file are you talking about? And what would be the point to combine several files from different container? I'm using the pull command anyway so it s highly doubtful

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by mstanleyjones** [comment]
I think the composefile references have been updated to clarify the different possible values for `version`. Please have a look and let us know if you are still having trouble.
