### ISSUE TITLE
Feedback for: engine/installation/linux/debian.md

### ISSUE THREAD

**Issue by alexlist** [docker/docker.github.io#1390]
File: [engine/installation/linux/debian.md](https://docs.docker.com/engine/installation/linux/debian/)

linux-image-extra-* does not exist anymore on Debian (tried on Jessie)

It looks like jessie comes with aufs in the standard kernel, and stretch adds it via DKMS:

http://stackoverflow.com/questions/37110291/how-to-enable-aufs-on-debian

**Comment by Teszko** [comment]
you are correct.
#1391 

I havn't checked on Debian Testing yet, but the Packages mentioned don't exist on any Debian branch. 
It was most likely copied from engine/installation/linux/ubuntu.md without checking.

**Comment by alexlist** [comment]
Thanks, that was fast. As mentioned - I haven't tested stretch (testing) yet either, but according to above link one needs a DKMS package on stretch. I may test it over the next cpl days, stretch is most likely going to be released in Feb or Mar 2017.

**Comment by alexlist** [comment]
Tested on stretch. It dtrt by pulling in the required aufs packages as a dependency, so nothing to be done here.

**Comment by mstanleyjones** [comment]
This has been fixed.
