### ISSUE TITLE
Bad RHEL repository

### ISSUE THREAD

**Issue by electropolis** [docker/docker.github.io#13902]
File: [engine/install/rhel.md](https://docs.docker.com/engine/install/rhel/)

I think `docker-ce.repo` for `rhel` isn't correct. 
This url
`https://download.docker.com/linux/rhel/$releasever/$basearch/stable` isn't available on the repository URL. For Centos yes, but for rhel the structure is different.

**Comment by thaJeztah** [comment]
What hardware were you trying to install on? We currently only provide RHEL packages for s390x and ppc64le, not for other architectures;

From the prerequisites sections on that page; https://docs.docker.com/engine/install/rhel/#prerequisites

> We currently only provide packages for RHEL on s390x (IBM Z). Other architectures are not yet supported for RHEL, but you may be able to install the CentOS packages on RHEL. Refer to the Install Docker Engine on CentOS page for details.

**Comment by thaJeztah** [comment]
closing as this went stale
