### ISSUE TITLE
Running composer returns an error related to superuser password

### ISSUE THREAD

**Issue by draentropia** [docker/docker.github.io#13944]
File: [samples/django.md](https://docs.docker.com/samples/django/)
This is the message I got:
db_1   | Error: Database is uninitialized and superuser password is not specified.
db_1   |        You must specify POSTGRES_PASSWORD to a non-empty value for the
db_1   |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
db_1   | 
db_1   |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
db_1   |        connections without a password. This is *not* recommended.

**Comment by roldel** [comment]
Issue sorted PR #14065

May be closed
