### ISSUE TITLE
ssh ip172-18-0-17-c6n64h5mrepg00cend10@direct.labs.play-with-docker.com

### ISSUE THREAD

**Issue by VVictoriaM** [docker/docker.github.io#13941]
### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by thaJeztah** [comment]
Looks like this was opened accidentally
