### ISSUE TITLE
Wrong curl release link

### ISSUE THREAD

**Issue by lipflip010** [docker/docker.github.io#13953]
File: [compose/install.md](https://docs.docker.com/compose/install/)

` sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
`

Please add a hint that for version 2.2.2 you need to write /download/v.2.2.2...

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The example command has been updated to the latest version.
