### ISSUE TITLE
docker-compose "Getting Started" references Docker Machine

### ISSUE THREAD

**Issue by scottopell** [docker/docker.github.io#13957]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

There's a section in this guide:
> If you’re using Docker Machine on a Mac or Windows, use `docker-machine ip MACHINE_VM` to get the IP address of your Docker host. Then, open `http://MACHINE_VM_IP:5000` in a browser.

https://docs.docker.com/machine/ gives a message that Docker Machine is deprecated.

What should this section say instead?

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This appears fixed in https://github.com/docker/docker.github.io/commit/bcc2a90f52b125bf5de0f2974203466d99058175
