### ISSUE TITLE
The example is not working 

### ISSUE THREAD

**Issue by Yangbai** [docker/docker.github.io#13961]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

yarn install v1.22.15

[1/4] Resolving packages...

success Already up-to-date.

Done in 0.13s.

yarn run v1.22.15

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

error Couldn't find a package.json file in "/app"

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
Ensure that your package.json file exists in the /app directory. You can find the file here, https://docs.docker.com/get-started/02_our_app/#get-the-app
Closing this issue as it does not appear to be a documentation issue. If this is an issue in the documentation, please let us know.
