### ISSUE TITLE
The docker run example in the GELF logging page has a typo

### ISSUE THREAD

**Issue by ItsCollinT** [docker/docker.github.io#13998]
File: [config/containers/logging/gelf.md](https://docs.docker.com/config/containers/logging/gelf/)

The sample is:

 docker run \
      --log-driver gelf –-log-opt gelf-address=udp://1.2.3.4:12201 \
      alpine echo hello world

but the first dash before log-opt is an incorrect character.

**Comment by thaJeztah** [comment]
Nice catch! Looks like the first hyphen is an n-dash, instead of a regular hyphen; I opened https://github.com/docker/docker.github.io/pull/14013 to fix
