### ISSUE TITLE
404 at /go%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20/guides/

### ISSUE THREAD

**Issue by AdmNaidu** [docker/docker.github.io#14008]
I found a broken link : https://docs.docker.com/go%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20/guides/

**Comment by thaJeztah** [comment]
Where did you find that link? Looks like you tried to open a URL with a lot of spaces in it (each `%20` represents a space)

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as I don't think the broken link is in the docs itself, but let us know if you have more details about how you arrived at that URL
