### ISSUE TITLE
404 at /articles/host_integration/

### ISSUE THREAD

**Issue by Jimmmmmmycode** [docker/docker.github.io#14014]
I found a broken link : https://docs.docker.com/articles/host_integration/
I arrived on this page through: https://blog.container-solutions.com/running-docker-containers-with-systemd

**Comment by thaJeztah** [comment]
Thanks for reporting; that looks to be a very old blog post from 2015. The source Markdown for that page can still be found here; https://github.com/moby/moby/blob/v1.7.0/docs/articles/host_integration.md

Perhaps we can add a redirect to https://docs.docker.com/config/daemon/systemd/, which looks to be the closest replacement for what was described on that page.

I should add that the article you came from describes how to control individual containers using systemd units which, although "possible" (to some extend), is not a scenario for which the docker cli was designed, and which may be "tricky" in some scenarios (doing so means that systemd will control the cli, which controls the docker daemon (which uses containerd and runc), which are all by themselves also systemd units / services, so there will be a complex "stack", with many possible scenarios where this may fail.

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/docker.github.io/pull/14015 to add additional redirects
