### ISSUE TITLE
404 at /machines/drviers/

### ISSUE THREAD

**Issue by hpatelcj2** [docker/docker.github.io#14027]
I found a broken link : https://docs.docker.com/machines/drviers/

**Comment by thaJeztah** [comment]
I suspect you (or the website where you found that link) made some typos; "machines" should be singular ("machine") and "drviers" should be "drivers";

https://docs.docker.com/machine/drivers/

But note that Docker Machine has been deprecated.


closing this ticket per the above, but feel free to continue the conversation
