### ISSUE TITLE
An unexpected error on startup 

### ISSUE THREAD

**Issue by mapastudiopl** [docker/docker.github.io#14048]
### Problem description
I'm trying to use latest version of Docker on Intel Q6600. Virtualization and data execution protection are enabled in BIOS. OS: Windows 10 Pro 21H2. 
![docker-error](https://user-images.githubusercontent.com/80180684/147390958-a1822531-c348-4f43-bce2-e6f621a42ae6.png)

Virtual Machine Platform - installed,
WSL - installed, 
Virtualization - enabled in BIOS

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. To report bugs in Docker Desktop, please use https://github.com/docker/for-win
