### ISSUE TITLE
$ git --version

### ISSUE THREAD

**Issue by chieh71** [docker/docker.github.io#14043]
File: [desktop/dev-environments.md](https://docs.docker.com/desktop/dev-environments/)

**Comment by thaJeztah** [comment]
Did you open this accidentally? If not, could you describe what changes you're requesting?

**Comment by chieh71** [comment]
Sir,
I am not open it accidentally，I am going to set the node, but it is too
hard for me , I'm just to study, let me studing, I am Taiwanese, could I
use Chinese to contact with you?


Sebastiaan van Stijn ***@***.***> 於 2021年12月24日 週五 下午9:01 寫道：

**Comment by thaJeztah** [comment]
I don't speak Taiwanese/Chinese myself, but perhaps colleagues do (and otherwise I can try @google translate") 👍

**Comment by chieh71** [comment]
Cool, thanks!

Sebastiaan van Stijn ***@***.***> 於 2021年12月25日 週六 上午12:51 寫道：

**Comment by chieh71** [comment]
@thaJeztah
Merry Christmas

吳哲 ***@***.***> 於 2021年12月25日 週六 上午12:58 寫道：

**Comment by chieh71** [comment]
@Sebastiaan
Merry Christmas and Happy new year.

Sebastiaan van Stijn ***@***.***> 於 2021年12月24日 週五 下午9:01 寫道：

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this issue as stale. If the issue still persists, please let us know more details.
