### ISSUE TITLE
.NOT_EDITED_HERE.yaml referenced in README.md doesn't exist in the repo

### ISSUE THREAD

**Issue by amerixan** [docker/docker.github.io#14059]
### Problem description

In the `README.md`, there is a reference to a `.NOT_EDITED_HERE.yaml` file, but that file does not exist in the repo anywhere.

I did a `grep -rni NOT_EDITED_HERE` and only found a reference to it in the `README.md`.

Output:
```bash
grep -rni NOT_EDITED_HERE                                                                                                              
README.md:59:[`.NOT_EDITED_HERE.yaml`](.NOT_EDITED_HERE.yaml) are maintained in other
```

**Comment by thaJeztah** [comment]
Thanks for reporting; yes, I think we removed use of that file at some point, but didn't update the instructions; if I'm not mistaken, this will be fixed as part of https://github.com/docker/docker.github.io/pull/13909
