### ISSUE TITLE
Prefer `docker <object> <verb>` over `docker <verb>`

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#1405]
### Problem description

To keep things consistent, prefer the format `docker <object> <verb>` where possible in examples. The old way still works.

cc/ @joaofnfernandes

**Comment by joaofnfernandes** [comment]
This will probably be a lot of work. Maybe we should address this in three stages:
1. Fix get started tutorials, and top X doc pages with most page views
2. There are some reference pages like the one for `docker run` that have content maintained by hand. Start migrating that content to the new version.
3. Fix the rest of the docs

**Comment by mstanleyjones** [comment]
I've got a local branch where I've been taking a different approach, doing semi-automated search-and-replace within the `engine/` subdirectory. I am concentrating on `docker container` and `docker image` as those are the two where the short form has been the most common. When I start the PR, it might make the most sense for each of us to push into the PR for our areas of responsibility. This may not get done for 13.1.

**Comment by joaofnfernandes** [comment]
Yup, compose 3.1 is higher priority than this for the 1.13.1 release. This is maintenance work and if it doesn't fit on the 1.13.1 release timeline, that's ok.
