### ISSUE TITLE
Deprecated/Undocumented option -g for docker deamon 

### ISSUE THREAD

**Issue by elfranne** [docker/docker.github.io#14056]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

The `-g` for `dockerd` is used in examples but not documented correctly, it is mentioned under [miscellaneous-options](https://docs.docker.com/engine/reference/commandline/dockerd/#miscellaneous-options)

Edit: apparently the -g is [deprecated](https://github.com/moby/moby/blob/b64b9811c3adb69641e2356fd12e2077d1f34ae1/cmd/dockerd/daemon.go#L444), in favor of `--data-root`

**Comment by amerixan** [comment]
This is indeed an issue, but that file is not in the repository.  I was going to update it but can't figure out which repo it is in. Opened #14059 to hopefully help resolve this.

**Comment by thaJeztah** [comment]
Thanks for reporting; I opened https://github.com/docker/cli/pull/3405 to address this
