### ISSUE TITLE
Url Change required for launching the app 

### ISSUE THREAD

**Issue by Sam-Dragon** [docker/docker.github.io#14078]
Hi,

Please find the required changes in the docs

Instead of hitting url with http://localhost:3000/
we need to hit the url with http://localhost:3000/index.html

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Can you share a link to the topic that contains the issue?

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists, please provide more details on the location of the issue.
