### ISSUE TITLE
Finding Quick Start

### ISSUE THREAD

**Issue by afbarksd** [docker/docker.github.io#14109]
File: [desktop/windows/install.md](https://docs.docker.com/desktop/windows/install/)

I am very new to Docker.  I installed Docker using the information on https://docs.docker.com/desktop/windows/install/ and started going through the Quick Start Guide.  When I clicked the link to the next step after creating and running the app from app.zip, the link failed with a JSON error.  I tried to start over using the instructions from the web page, "To run the Quick Start Guide on demand, right-click the Docker icon in the Notifications area (or System tray) to open the Docker Desktop menu and then select Quick Start Guide."  The Quick Start Guide link did not appear when I followed those instructions.

Also, you should not assume that someone going through the motions of the Quick Start has any understanding of what is happening.  Links to explanations would be helpful.  When someone who knows a lot about a subject writes a quick start guide, they usually omit information that is absolutely necessary for the newbie.  I suggest having a newbie try to use the Quick Start while recording his or her saying what he or she is thinking and then using this information to find what newbies are missing.

**Comment by craig-osterhout** [comment]
Hi @afbarksd, thanks for sharing the issue. If the quickstart did not appear in product, it sounds like a bug. Please help report the issue as a bug with more details based on your OS:
- https://github.com/docker/for-win
- https://github.com/docker/for-mac

You may also want to check the `Containers` tab in Docker Desktop to make sure that the quickstart is not already running. If it is already running, click the `Open in browser` button. For details about the `Containers` tab, see https://docs.docker.com/desktop/use-desktop/container/

You mentioned `app.zip`, so it sounds like you made it to part 2.
While the quickstart has you run the instructions locally in a container, you can also access them online at https://docs.docker.com/get-started/02_our_app/

If you need more support, please try the Community Slack at https://join.slack.com/t/dockercommunity/shared_invite/zt-1fukl8thi-Iq2rTGyJGMAkCeQKuyfWIA
