### ISSUE TITLE
Incorrect download link (docker-compose)

### ISSUE THREAD

**Issue by ThomasKraaibeek** [docker/docker.github.io#14117]
### Problem description
Commit f413d25dbafda880a7d1e2854d24ff0b9faae0d5 changed the download link adding a 'v'. For me this is not working. Removing the 'v' worked.

### Problem location
https://docs.docker.com/compose/install/#alternative-install-options
Commit f413d25dbafda880a7d1e2854d24ff0b9faae0d5

### Affected version
Current docker-compose installation documentation

### Suggestions for a fix

Remove the 'v' from the download link.

**Comment by keunes** [comment]
Sorry to tag you @usha-mandya, but it seems a recent change you approved (#14079) introduced an error.

Side note, also about the download link:
On my Raspberry Pi 4 with Raspberry Pi OS `uname -s` and `uname -m` output values that make for an unavailable download link: The former gives `Linux` (with a capital L being the problem), the latter `armv7l` (with the extra `l` being the problem). No biggy - 'hard-typing' the URL worked fine, but I had to search a bit what I had to do. From [this SO answer](https://stackoverflow.com/a/29167402) I understood I could safely adjust the architecture(?) name. It'd be great if that somehow could be solved (or mentioned as an infobox?).

**Comment by usha-mandya** [comment]
@keunes Thanks for flagging this.

@StefanScherer wondering if we can solve this in the code?

**Comment by StefanScherer** [comment]
@usha-mandya Oh yes, we probably have to revert #14079 😬. 
The `v` is needed for compose v2, but currently we show how to download version 1.29.2. 
We have a special page for v2 on Linux.
So, for now it's without the `v` in the URL.

**Comment by usha-mandya** [comment]
Closing this as the updates are live on the Docs site.
