### ISSUE TITLE
Composer download path is not valid anymore

### ISSUE THREAD

**Issue by nlescure** [docker/docker.github.io#14112]
File: [compose/install.md](https://docs.docker.com/compose/install/)

the path to download docker-compose is outdated (v1 instead of v2):
`sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

And changing the version is not enough, because you have to add a "v" before the number. Here is a valid link for docker compose 2 :
`sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The command has been updated.
