### ISSUE TITLE
Download URL

### ISSUE THREAD

**Issue by arulselvan** [docker/docker.github.io#14127]
File: [compose/install.md](https://docs.docker.com/compose/install/)

I think Linux download URL need to be without v prefix in the version.

From:
sudo curl -L "https://github.com/docker/compose/releases/download/v1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

To:
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

**Comment by IreshMM** [comment]
v2.2.3 which is the latest worked for me

**Comment by salimkanoun** [comment]
confirmed there is a bug in the documentation URL 'v1.29.2' should be replaced by '1.29.2'

**Comment by ichisuke55** [comment]
I had the same problem and found this issue!

**Comment by wadabee** [comment]
Version 2 requires within "v" prefix in the URL version , but below version 2 don't need "v" prefix.

**Comment by roldel** [comment]
Sorted https://github.com/docker/docker.github.io/pull/14151
