### ISSUE TITLE
Extra Dot

### ISSUE THREAD

**Issue by afbarksd** [docker/docker.github.io#14146]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

I think that "docker build -t getting-started .." should be "docker build -t getting-started .".

**Comment by thaJeztah** [comment]
Thanks for reporting; yes, that example is formatted a bit awkward as it's part of a sentence; I opened https://github.com/docker/docker.github.io/pull/14485 to fix the formatting
