### ISSUE TITLE
Install doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by nicholasRenninger** [docker/docker.github.io#14142]
File: [compose/install.md](https://docs.docker.com/compose/install/)

when installing on ubuntu 16.04/20.04, incorrect building of curl URL:
```
> uname -s
Linux
```
the release page url uses lowercase `linux`. Making this changes fixes the installation procedure.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.  $(uname -s) is no longer used in the curl command in the docs. If the issue still persists, please let us know.
