### ISSUE TITLE
Fix a typo in the download link

### ISSUE THREAD

**Issue by FrankyHollywood** [docker/docker.github.io#14152]
File: [compose/install.md](https://docs.docker.com/compose/install/)

Hi, I couldn't get it working on Linux, due to a typo:

the page says;

> sudo curl -L "https://github.com/docker/compose/releases/download/v1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

which should be:
> sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

best,
Frank

**Comment by aevesdocker** [comment]
Hi, 

Thank you for reporting this issue. Closing issue as it has now been fixed.
