### ISSUE TITLE
Networking in Compose - Default driver in swarm mode

### ISSUE THREAD

**Issue by rvernica** [docker/docker.github.io#1417]
### Problem description

The _Networking in Compose_ page mentions that:

> The cluster will use the overlay driver by default, but you can specify it explicitly if you prefer - see below for how to do this.

I have a Docker `1.13.0` installation in swarm mode and it seems that `bridge` is the default network driver. I could not find any reference on the default driver in Docker.

```
> docker-compose up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "foo_default" with the default driver
Creating scidbdocker_bar_1
> docker network ls
NETWORK ID          NAME                  DRIVER              SCOPE
b9653fe43369        bridge                bridge              local
f111200c51a0        docker_gwbridge       bridge              local
a0bdd5df7a75        host                  host                local
6u4dleo7zzmn        ingress               overlay             swarm
e9de752139c3        none                  null                local
66505aa0823a        foo_default           bridge              local
```

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/compose/networking/#/multi-host-networking

### Project version(s) affected

Docker `1.13.0`
Docker Compose `1.10.0`

**Comment by londoncalling** [comment]
@rvernica There is info starting here on the default bridge network: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

But I'm going to need help on answering this from @dnephin , @shin- , @thaJeztah , @ManoMarks . Can you guys respond?

**Comment by dnephin** [comment]
That document is referring to https://github.com/docker/swarm, not swarm mode. `docker-compose` doesn't work directly with Swarm mode (as it says in the warning), you have to go through `docker stack deploy`.

**Comment by johnharris85** [comment]
I'll take a look / claim this :)
