### ISSUE TITLE
docs: tells that Docker should

### ISSUE THREAD

**Issue by shaunwxi** [docker/docker.github.io#14176]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

> The . at the end of the docker build command **tells that Docker should** look for the Dockerfile in the current directory.

perhaps this should be

> The . at the end of the docker build command, tells Docker that it should look for Dockerfile in the current directory.

**Comment by danBamikiya** [comment]
@shaunwxi What about:

> The . at the end of the docker build command, tells Docker to look for the Dockerfile in the current directory.

?

**Comment by craig-osterhout** [comment]
Fixed in https://github.com/docker/docker.github.io/commit/a08aca98fbcff8612c55e6f5b5831656582e6df5
