### ISSUE TITLE
Instructions for setting up PAT in Go CI/CD are unclear

### ISSUE THREAD

**Issue by robroe** [docker/docker.github.io#14182]
File: [language/golang/configure-ci-cd.md](https://docs.docker.com/language/golang/configure-ci-cd/)

Go CI/CD talks about setting up PAT in previous section, but this section is not in the GO instructions. Should link to https://docs.docker.com/ci-cd/github-actions/ or have a copy of the instructions for there?

**Comment by robroe** [comment]
Having completed the tutorial, the instructions for setting up access are further down. https://docs.docker.com/language/golang/configure-ci-cd/#enable-access-to-docker-hub

I would suggest removing/amending the text in https://docs.docker.com/language/golang/configure-ci-cd/#set-up-the-ci-workflow

> In the previous section, we created a PAT and added it to GitHub to ensure we can access Docker Hub from any GitHub Actions workflow. But before setting out to build the images for releasing our software, let’s build a CI pipeline to run the tests first.

**Comment by danBamikiya** [comment]
Thanks for this! Sent a PR to fix the issue :)
