### ISSUE TITLE
Documentation is running in Quirks Mode

### ISSUE THREAD

**Issue by ForbiddenEra** [docker/docker.github.io#14195]
### Problem description

The documentation appears to be running in Quirks Mode, at least in Firefox. This is due to there being a comment with the page generation date preceeding the `<!DOCTYPE html>` which is disallowed for HTML5 standard.

Just happened to have devtools open while browsing and noticed this.

![image](https://user-images.githubusercontent.com/7980490/151769327-e516c0cf-8d68-4046-8932-e79cec0566dc.png)

**Comment by danBamikiya** [comment]
same for Microsoft Edge:

![image](https://user-images.githubusercontent.com/58262528/152686587-7286f142-430c-481d-98df-c05c1372d6da.png)

Is that really a problem tho? I read about [Quirks Mode](https://en.wikipedia.org/wiki/Quirks_mode) and it doesn't seem to have any disadvantages for the documentation.

**Comment by thaJeztah** [comment]
Thanks for reporting; I knew "old browsers" were picky about this, but didn't know current browsers still did. I opened a PR to move the comment after the doctype, which should (hopefully) fix this; https://github.com/docker/docker.github.io/pull/14484

Preview of that PR is available at https://deploy-preview-14484--docsdocker.netlify.app
