### ISSUE TITLE
404 at /terms/image/

### ISSUE THREAD

**Issue by Wyclif3** [docker/docker.github.io#14209]
I found a broken link : https://docs.docker.com/terms/image/
I arrived on this page through: https://bitbucket.org/

**Comment by thaJeztah** [comment]
Thanks for reporting; that looks to be a _very_ old location that we used years ago (https://web.archive.org/web/20150321045040/http://docs.docker.com/terms/image), and we didn't preserve links for that long ago

I think the equivalent for the current documentation would be the "images" description in the glossary; https://docs.docker.com/glossary/#image, and the getting started; https://docs.docker.com/get-started/#what-is-a-container-image

Given that these URLs are very old, we don't plan to add redirects for these, so I'll close this ticket, but feel free to continue the conversation
