### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by VroyCLe-Niranjan** [docker/docker.github.io#14216]
### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by thaJeztah** [comment]
I guess this was accidentally (again? https://github.com/docker/docker.github.io/issues/13192#issuecomment-997941323)
