### ISSUE TITLE
Unable to install RediSearch or Redis on Windows Server 2016

### ISSUE THREAD

**Issue by Kailash-Ramco** [docker/docker.github.io#14217]
Hi Team,

I am trying to install RediSearch using docker on Windows Server 2016 

Operating System Details:

![image](https://user-images.githubusercontent.com/97166966/152317678-e3efce36-effc-4f69-89d0-c39160c8bdde.png)

I have installed docker using the below official documentation from microsoft

https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server

On trying to pull the docker redis/redisearch image i get the below error response

![image](https://user-images.githubusercontent.com/97166966/152317889-4473a9e5-fe01-4a2d-b716-2d5614099ab3.png)

Is there any option to switch to linux container using powershell command for the above images to be installed ?

**Comment by craig-osterhout** [comment]
@Kailash-Ramco, thanks for sharing the issue. You can find our current supported platforms at https://docs.docker.com/engine/install/
For unsupported platforms, you can try to get support in the Docker forums or slack.
- https://forums.docker.com/
- https://dockercommunity.slack.com/

You can also take a look at https://github.com/docker/labs/blob/master/windows/windows-containers/README.md, although the documentation may not be maintained.
