### ISSUE TITLE
denied: requested access to the resource is denied And doesn't push

### ISSUE THREAD

**Issue by hcymysql** [docker/docker.github.io#14222]
[root@centos8-m1 ~]# docker logout
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Removed login credentials for registry.fedoraproject.org
[root@centos8-m1 ~]# 
[root@centos8-m1 ~]# docker login
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Username: hcymysql
Password: 
Login Succeeded!
[root@centos8-m1 ~]# docker images
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
REPOSITORY                        TAG                 IMAGE ID      CREATED            SIZE
localhost/hcymysql/mysql_monitor  2022-02-04_GA       2827881acec7  5 minutes ago      2.18 GB
localhost/mysql_monitor           2022-02-04_GA       2827881acec7  5 minutes ago      2.18 GB
localhost/hcymysql/mysql_monitor  2022-02-03_GA       772817e1a238  About an hour ago  2.18 GB
localhost/hcymysql/mysql_monitor  latest              772817e1a238  About an hour ago  2.18 GB
localhost/hcymysql/mysql_monitor  2022-02-03          772817e1a238  About an hour ago  2.18 GB
localhost/hcymysql/mysql_monitor  1.0                 772817e1a238  About an hour ago  2.18 GB
localhost/hcymysql/mysql_monitor  2022-02-03_nightly  bc7de2266766  3 hours ago        1.96 GB
[root@centos8-m1 ~]# 
[root@centos8-m1 ~]# docker push  hcymysql/mysql_monitor:2022-02-04_GA
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Getting image source signatures
Copying blob da04ba31ef88 [--------------------------------------] 8.0b / 215.9MiB
Copying blob 8b8d7063aa7c [--------------------------------------] 8.0b / 183.5MiB
Copying blob 4a6cf4a70c42 [--------------------------------------] 8.0b / 261.6MiB
Copying blob 2653d992f4ef [--------------------------------------] 8.0b / 206.5MiB
Copying blob b1d44b1dee85 [--------------------------------------] 8.0b / 1.2GiB
**Error: writing blob: initiating layer upload to /v2/hcymysql/mysql_monitor/blobs/uploads/ in registry-1.docker.io: errors:
denied: requested access to the resource is denied
unauthorized: authentication required**

[root@centos8-m1 ~]# cat /etc/redhat-release 
CentOS Linux release 8.5.2111

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For interactive troubleshooting and support, please try the Docker Community Slack or Forums, https://www.docker.com/support/
