### ISSUE TITLE
Docker installation on Ubuntu 21.10 Impish Indri

### ISSUE THREAD

**Issue by mrsaeeddev** [docker/docker.github.io#14245]
Does anyone know how to fix this error `Cannot connect to the Docker daemon at unix:///home/user/.docker/desktop/docker.sock`? 

I'm able to run it with sudo but without sudo it doesn't work. Have tried adding usergroup and everything as specified in the docs but nothing worked.

I'm on Ubuntu 21.10 Impish Indri.

When I check docker's logs, it says: `failed to start daemon: error while opening volume store metadata database: time out`

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For interactive troubleshooting and support, please try the Docker Community Slack or Forums, https://www.docker.com/support/
