### ISSUE TITLE
Discount code for Elton Stoneman: Docker for .NET Apps - on Linux and Windows has expired

### ISSUE THREAD

**Issue by iSatishYadav** [docker/docker.github.io#14252]
File: [get-started/resources.md](https://docs.docker.com/get-started/resources/)

The docs mention :
`
[Elton Stoneman](https://docker4.net/udemy): Docker for .NET Apps - on Linux and Windows. Includes the discount code 644ABCBC33F474541885.
`
![image](https://user-images.githubusercontent.com/4049421/153341070-0345405e-bbba-4bb7-a7c9-df95e90aff75.png)

The coupon code has expired.

![image](https://user-images.githubusercontent.com/4049421/153340985-6bfe24f6-6a38-4c6c-89f6-75ff59a2e156.png)

Either remove this code from the docs or add a new coupon code.

**Comment by iSatishYadav** [comment]
@usha-mandya Issue still persists:

_The coupon code entered is inactive or expired._

![image](https://user-images.githubusercontent.com/4049421/154901344-625b21f6-19f0-405f-b93e-ac230be9a6a5.png)

**Comment by usha-mandya** [comment]
@sixeyed Could you please check?

**Comment by sixeyed** [comment]
Fixed now. Apologies - you can't have a permanent voucher in Udemy and I haven't found a way to automate creating a new one, so it needs a manual process.

**Comment by thaJeztah** [comment]
Thanks @sixeyed ! A bit similar to the invite-links we have for our slack; they also keep expiring 😫

Let me close this one again

**Comment by iSatishYadav** [comment]
Hi @sixeyed, I’m so sorry you have to do this manually. Could you please generate one last time.

**Comment by sixeyed** [comment]
Hi @iSatishYadav  - it should have still been live yesterday, but I've generated a new one today with a bigger saving :)
