### ISSUE TITLE
404 at /desktop/windows/%20troubleshoot/

### ISSUE THREAD

**Issue by parsa1387** [docker/docker.github.io#14274]
I found a broken link : https://docs.docker.com/desktop/windows/%20troubleshoot/#virtualization

**Comment by thaJeztah** [comment]
It looks like there's an accidental space in your URL (which shows as `%20` in the URL); the correct link is

https://docs.docker.com/desktop/windows/troubleshoot/#virtualization

I'll close this ticket as I think this may have been a typo when entering the URL or a copy/paste mistake, but if you have details where you found the broken link, and if it's on one of our websites, we can fix.
