### ISSUE TITLE
Verify whether swarm tutorial works on native Windows containers and if any steps are different

### ISSUE THREAD

**Issue by sg1970** [docker/docker.github.io#1428]
File: [engine/swarm/swarm-tutorial/index.md](https://docs.docker.com/engine/swarm/swarm-tutorial/)

Does that Tutorial in the above link work for Native Windows Hyper-V Containers  (Not Linux Containers running on Windows  !!) . If so are the steps **EXACTLY** the same ?  I would like to use native Windows Images from Microsoft and create a swarm. I have the latest docker version 1.13.0-beta39 (9861) running on Win10-Pro-Anniversary Edition.

Please clarify.
Thanks.

**Comment by orthros** [comment]
I'm running WIn10 Pro Anniversary. I'll take a look at this

**Comment by sg1970** [comment]
@orthros  @mstanleyjones  @JimGalasyn  @johndmulhausen 
Thanks Everyone for considering this. I made some minor edits to the OP ( typos and added Hyper-V in the first line ).

**Comment by mstanleyjones** [comment]
Swarm on Windows is supported as of Docker 17.05. For the most part, the CLI commands are the same as for Linux, but you need to use a Windows parent image. One example is here: https://docs.docker.com/engine/swarm/configs/#simple-example-use-configs-in-a-windows-service
