### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by faranguizl** [docker/docker.github.io#14294]
File: [get-started/07_multi_container.md](https://docs.docker.com/get-started/07_multi_container/)

Hi, please include an example using an image available for ARM64 architecture. MySQL has not yet an image on this architecture.

5.7: Pulling from library/mysql
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It looks like it was resolved in https://github.com/docker/docker.github.io/commit/a4de787aed5344b54eb067bb8ad7b36d6e78b242
