### ISSUE TITLE
404 at /home/inside/docker.github.io-master/404.html

### ISSUE THREAD

**Issue by inside90** [docker/docker.github.io#14301]
I found a broken link : https://docs.docker.com/home/inside/docker.github.io-master/404.html

**Comment by jerae-duffin** [comment]
Hey @inside90 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
closing as we didn't receive more information to address the issue, but feel free to leave a comment if you have more details for us to fix.
