### ISSUE TITLE
Link to download installer is broken

### ISSUE THREAD

**Issue by Wizarth** [docker/docker.github.io#14317]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)

The line:

> If you haven’t already downloaded the installer (Docker for Windows Installer.exe), you can get it from [download.docker.com](https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe).

links to a file that doesn't exist. Browsing to the root of https://download.docker.com/ doesn't show the referenced file. It appears there are no installers present, just zips of builds.

**Comment by aevesdocker** [comment]
Hi @Wizarth , 
Thanks for reporting the issue. 
Looks like the file you referenced redirects to https://docs.docker.com/desktop/windows/install/ where you will be able to download the Docker for Windows Installer.exe.

**Comment by Wizarth** [comment]
Sorry, perhaps I should have attached a screenshot or such, I get:

url: `https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe`

``` xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>KHZWBZ4Q0AW2R0Q0</RequestId>
<HostId>
nDbjyGG344NmtqDj8VqP21YH0hxcqq2hV77dkhf0g9iWNg40U9r2tYhQwKOp/v+v9mH/rho80MI=
</HostId>
</Error>
```

and there is no redirection.
