### ISSUE TITLE
404 at /cloud/ecs-compose-examples/

### ISSUE THREAD

**Issue by dhiraj-bochare** [docker/docker.github.io#14329]
I found a broken link : https://deploy-preview-12080--docsdocker.netlify.app/cloud/ecs-compose-examples/
I arrived on this page through: https://deploy-preview-12080--docsdocker.netlify.app//cloud/ecs-integration/

**Comment by thaJeztah** [comment]
The "deploy-preview" URLs are for previewing changes in pull requests, and those previews do not contain a full version of the documentation (some external docs are not included). The correct URL for that page on our published documentation can be found here; https://docs.docker.com/cloud/ecs-integration/


I'm closing this ticket, but feel free to continue the conversation
