### ISSUE TITLE
404 at /influxdb

### ISSUE THREAD

**Issue by khwolf1955** [docker/docker.github.io#14360]
I found a broken link : https://docs.docker.com/influxdb

**Comment by yamikarajput546** [comment]
hey @khwolf1955 i can fix it?
can you provide me the current link

**Comment by thaJeztah** [comment]
I recall we had some of the documentation of the official images mirrored in our documentation, but don't think we had it as a top-level URL (they used to live at https://docs.docker.com/samples/influxdb/); you can find those docs on Docker Hub; https://hub.docker.com/_/influxdb/

@khwolf1955 how did you arrive at that URL? Was that through one of our websites? (if it's a link on an external website, we can't fix that 😅)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as stale unless more details are provided.
