### ISSUE TITLE
Wrong instruction to install Docker Compose on Linux

### ISSUE THREAD

**Issue by sebastienserre** [docker/docker.github.io#14367]
File: [compose/install.md](https://docs.docker.com/compose/install/)

Hello
The doc says:
` sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

I think a `v` has been added to the tags as now the right link is
`sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The command has been updated in the docs.
