### ISSUE TITLE
Update doc : for docker installation on ubuntu

### ISSUE THREAD

**Issue by Sachin1O1** [docker/docker.github.io#14386]
### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by thaJeztah** [comment]
can you provide more details what information is missing? (this is the page for installation on Ubuntu: http://docs.docker.com/engine/install/ubuntu/)

**Comment by craig-osterhout** [comment]
@Sachin1O1, thanks for sharing the issue. Closing this as stale unless more details are provided.
