### ISSUE TITLE
Suggestions for the style guide

### ISSUE THREAD

**Issue by Rick-Anderson** [docker/docker.github.io#1440]
### Problem description

Consider having important style information up front for the few folks who take the time to read your style guide. The first link I clicked 

Generally, Docker’s
documentation uses the standards described in the
[Associated Press's (AP) style guide](http://en.wikipedia.org/wiki/AP_Stylebook).
If a question about syntactical, grammatical, or lexical practice comes up,
**refer to the AP guide first**.

The Wikipedia link has no style guide info. I would consider removing 

>Over time, different publishing communities have written standards for the style
and grammar they prefer in their publications. These standards are called
[style guides](http://en.wikipedia.org/wiki/Style_guide). 

That doesn't help anyone who wants to quickly check your style guide.  I would remove the suggestion to use the AP style guide first given that few have access to it.  I suggest you remove all ref to the AP style guide or perhaps move it to the very bottom as a footnote.

**Comment by johndmulhausen** [comment]
Subsumed by #2625 -- we'll address this there as part of that general update. Thanks, @Rick-Anderson !
