### ISSUE TITLE
404 at /install/)%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85

### ISSUE THREAD

**Issue by loks666** [docker/docker.github.io#14414]
I found a broken link : https://docs.docker.com/install/)%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85

**Comment by jerae-duffin** [comment]
Hey @loks666 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?
