### ISSUE TITLE
404 at /desktop/windows/troubleshoot/

### ISSUE THREAD

**Issue by kojitorauto** [docker/docker.github.io#14428]
I found a broken link : https://docs.docker.com/desk.top/windows/troubleshoot/#virtualozation

**Comment by thaJeztah** [comment]
the correct URL for the above is: https://docs.docker.com/desktop/windows/troubleshoot/#virtualization

(there's a `.` in your URL (`desk.top`) that shouldn't be there, and `#virtualozation` needs to be `#virtualization`).


I assume this was possibly a typo when typing the URL in your browser, so let me close this ticket, but feel free to continue the conversation after I closed
