### ISSUE TITLE
404 at /engine/reference/commandline/cli/

### ISSUE THREAD

**Issue by UUxUU** [docker/docker.github.io#14421]
I found a broken link : https://deploy-preview-14418--docsdocker.netlify.app/engine/reference/commandline/cli/
I arrived on this page through: https://github.com/docker/docker.github.io/issues/14420

**Comment by thaJeztah** [comment]
The `deploy-preview` URLs are temporary URLs used to preview changes that were made in a pull request.

The URL on the website for this is https://docs.docker.com/engine/reference/commandline/cli/

**Comment by mickie999** [comment]
Is this the reason I could not reproduce it in local env?

**Comment by thaJeztah** [comment]
if you built the docs locally (through docker compose), then you get a full set of the docs yes. The Netlify preview does not include pages that are fetched from some of the source repositories
