### ISSUE TITLE
Invisible link to the amazing blog post in the Tip Section: "Setting Connection Settings via Env Vars"

### ISSUE THREAD

**Issue by vlatushko** [docker/docker.github.io#14453]
File: [get-started/07_multi_container.md](https://docs.docker.com/get-started/07_multi_container/)

**Comment by vlatushko** [comment]
The issue persists only in the night mode of the page.

**Comment by thaJeztah** [comment]
Ah, yes, I noticed that as well. In "light" mode, the link is visible;

<img width="958" alt="Screenshot 2022-03-27 at 14 18 21" src="https://user-images.githubusercontent.com/1804568/160281194-91d0a515-e798-4398-964f-17528a721db8.png">

But in dark mode, the link color is the same as the body text;

<img width="967" alt="Screenshot 2022-03-27 at 14 18 27" src="https://user-images.githubusercontent.com/1804568/160281214-452a96e1-6aa1-450d-81f7-4b0863b63b29.png">


This was introduced in https://github.com/docker/docker.github.io/pull/13158, which changed the color scheme for these blocks. Before that PR, they looked like this (which had a higher contrast, and different color for links);

<img width="980" alt="Screenshot 2022-03-27 at 14 23 16" src="https://user-images.githubusercontent.com/1804568/160281238-b3329995-cc3a-4145-8172-537db98d4255.png">

**Comment by thaJeztah** [comment]
@mark-dr @usha-mandya PTAL

**Comment by mark-dr** [comment]
Looks like our design system evolved since these alerts were implemented. Should be some quick changes to the CSS vars, will put it on my to-do list. Thanks for reporting, @vlatushko!

**Comment by vlatushko** [comment]
Hi Mark H,
I am happy I could help ;) Thanks!
