### ISSUE TITLE
doc improvement suggestion

### ISSUE THREAD

**Issue by nankingrider** [docker/docker.github.io#14464]
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)

HI, the content below this title "Communicate between a container and a swarm service[🔗](https://docs.docker.com/network/network-tutorial-overlay/#communicate-between-a-container-and-a-swarm-service)"

has nothing to do with it ... maybe a mislocation, please check
thanks . !

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/docker.github.io/issues/8387
