### ISSUE TITLE
404 at /engine/install/linux-postinstall/:

### ISSUE THREAD

**Issue by sairam2621** [docker/docker.github.io#14462]
I found a broken link : https://docs.docker.com/engine/install/linux-postinstall/:

**Comment by jerae-duffin** [comment]
Hey @sairam2621 Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
The `https://docs.docker.com/engine/install/linux-postinstall/` works for me. Or was the `:` at the end part of the URL that you tried?

From the above, I don't think there's anything actionable here, so I'll go ahead and close, but feel free to continue the conversation if you think I closed mistakenly.
