### ISSUE TITLE
Feedback for: engine/installation/linux/centos.md

### ISSUE THREAD

**Issue by acdha** [docker/docker.github.io#1447]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

The instructions tell you how to remove the older `docker` package on CentOS but the attempt to install `docker-engine` will still fail due to conflicts with the `container-selinux` and `docker-common` common packages. The suggested command should be:

```
sudo yum -y remove docker docker-common container-selinux
```

**Comment by thaJeztah** [comment]
fixed by #1560, thanks!
