### ISSUE TITLE
404 at /go/ws12/

### ISSUE THREAD

**Issue by Beto8914** [docker/docker.github.io#14497]
I found a broken link : https://docs.docker.com/go/ws12/

**Comment by thaJeztah** [comment]
Did you find this link somewhere, or did you type it manually in your browser? Looks like there's a typo in the URL; the `1` should be an `l`; https://docs.docker.com/go/wsl2/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as stale. If the issue is still applicable, please help provide the requested details from the previous comment.
