### ISSUE TITLE
describe difference between docker node rm and docker swarm leave

### ISSUE THREAD

**Issue by nicolaka** [docker/docker.github.io#1451]
### Problem description

please describe the difference between `swarm leave` and `node rm`. Also include a details process to remove a node from the swarm. 

### Problem location

/engine/swarm/join-nodes/

**Comment by mstanleyjones** [comment]
@aaronlehmann @stevvooe can you provide some guidance on this?

**Comment by aaronlehmann** [comment]
I think this is already covered in a pretty detailed way in the CLI reference guide:

https://github.com/docker/docker/blob/master/docs/reference/commandline/swarm_leave.md
https://github.com/docker/docker/blob/master/docs/reference/commandline/node_rm.md

Do you have any questions that aren't covered by those documents?

I'm not sure why this isn't showing up on `docs.docker.com`. Pages like https://docs.docker.com/engine/reference/commandline/swarm_leave/ contain very little useful information.

Also, I noticed just now that `swarm_leave.md` has a gramatical error: "You can use the `--force` option to on a manager to remove it from the swarm.". I'll open a PR to fix that.

**Comment by nicolaka** [comment]
@aaronlehmann one aspect that isn't described is the order of operation when removing a node from the cluster. I still don't understand if both `swarm leave` and `node rm` are required?

**Comment by aaronlehmann** [comment]
If you use `swarm leave`, the node still appears in the node list (it will be marked "down"). `node rm` can remove entries like this from the nodes list. It's never necessary but may be useful to clear clutter in the list.

**Comment by mstanleyjones** [comment]
@aaronlehmann we are working with @frenchben on getting the extended reference material back in sync, in #1506.

**Comment by mistyhacks** [comment]
Or https://docs.docker.com/engine/reference/commandline/node_rm/ and https://docs.docker.com/engine/reference/commandline/swarm_leave/

It was fine to unassign me as I don't work at Docker anymore. 👼
