### ISSUE TITLE
404 at /desktop/extensions/

### ISSUE THREAD

**Issue by oleksis** [docker/docker.github.io#14515]
I found a broken link : https://docs.docker.com/desktop/extensions/

**Comment by jerae-duffin** [comment]
Hey! @oleksis Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by oleksis** [comment]
> Could you let us know how you arrived at the broken link?

I was testing the Docker Extensions [Docker Desktop 4.7.0 (77074)] link for build my own extension.

**Comment by oleksis** [comment]
Fixed in Docker Desktop 4.8.0 or a later.
