### ISSUE TITLE
404 at /reference/commandline/run/

### ISSUE THREAD

**Issue by nobe4** [docker/docker.github.io#14538]
I found a broken link : https://docs.docker.com/reference/commandline/run/
I arrived on this page through: https://www.google.com/

<img width="687" alt="image" src="https://user-images.githubusercontent.com/2452791/162899107-b7cfe621-de8f-4a26-aea1-2653ffe17ea0.png">

**Comment by aevesdocker** [comment]
Hi @nobe4 , 

Thank you for reporting the broken link. 
Unfortunately this is a problem on Google's side, so I'm closing the issue.
