### ISSUE TITLE
broken link - about docker ee containers and windows server

### ISSUE THREAD

**Issue by bfmcneill** [docker/docker.github.io#14549]
File: [install/windows/docker-ee.md](https://docs.docker.com/install/windows/docker-ee/)

link is broken for 

`[Setup - Windows Server 2016 (Lab)](https://github.com/docker/labs/blob/master/windows/windows-containers/Setup-Server2016.md) describes environment setup in detail.`

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Did you see that link in the current Docker documentation?

It looks like that topic no longer exists in the documentation and that link was removed in https://github.com/docker/docker.github.io/commit/4ec035596edcadfe90b0d6968236589853d71e5e

You can still find the archived file below at
https://github.com/docker/labs/blob/4a1b82c24034c05c89700ad3172051e3d91d5d48/windows/windows-containers/Setup-Server2016.md

**Comment by craig-osterhout** [comment]
Closing as stale unless more details are provided.
