### ISSUE TITLE
404 at /docker-for-mac/)

### ISSUE THREAD

**Issue by msaliev** [docker/docker.github.io#14558]
I found a broken link : https://docs.docker.com/docker-for-mac/)

**Comment by thaJeztah** [comment]
Perhaps it was the URL _including_ the trailing `)` (so `https://docs.docker.com/docker-for-mac/)`)

@msaliev did you copy that link from somewhere and accidentally included the trailing `)`, or where did you find that link?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as stale unless more details are provided.
