### ISSUE TITLE
Explain why "docker attach" may appear to hang

### ISSUE THREAD

**Issue by alexryan** [docker/docker.github.io#1456]
File: [engine/reference/commandline/attach.md](https://docs.docker.com/engine/reference/commandline/attach/)

would be helpful if it was explained why this command seems to hang.
this is unexpected behavior for many of us.

**Comment by mstanleyjones** [comment]
This file is in the `docker/docker` repo and any changes need to happen there.

**Comment by gschaetz** [comment]
I got this one

**Comment by mstanleyjones** [comment]
Closing here because the work is happening upstream. Thanks @gschaetz
