### ISSUE TITLE
404 at /get-involved/docs/communityleaders/eventhandbooks/java/

### ISSUE THREAD

**Issue by rshn-dev** [docker/docker.github.io#14591]
I found a broken link : https://docs.docker.com/get-involved/docs/communityleaders/eventhandbooks/java/
I arrived on this page through: https://docker.github.io/

**Comment by craig-osterhout** [comment]
Arrived via https://docker-community-leaders.github.io/dockercommunity/docs/communityleaders/eventhandbooks/

**Comment by craig-osterhout** [comment]
@rshn-dev, thanks for sharing the issue. 
The correct link is probably https://docker-community-leaders.github.io/dockercommunity/docs/communityleaders/eventhandbooks/java/ 
If the link was found on an https://docker-community-leaders.github.io page, please report the issue on that site/repo.

Was the broken link found on an https://docker-community-leaders.github.io page or on an https://docs.docker.com page?

**Comment by craig-osterhout** [comment]
Closing this issue as stale. If the issue still persists, please provide more details.
