### ISSUE TITLE
Update compose field mappings: service.deploy.restart_policy and service.restart

### ISSUE THREAD

**Issue by MrChrisRodriguez** [docker/docker.github.io#14590]
File: [cloud/ecs-compose-features.md](https://docs.docker.com/cloud/ecs-compose-features/)

**Current:**
- `service.restart` says "Replaced by service.deployment.restart_policy"
- `service.deploy.restart_policy` has a checkmark indicating it is supported

**Instead, the table should show:**
- `service.restart` should have an x indicating it is not supported.
- `service.deploy.restart_policy` should have an x indicating it is not supported.

Neither of these fields is supported by this ECS integration.

**Comment by slavdok** [comment]
I am so confused by this, is this supported or not?

**Comment by MrChrisRodriguez** [comment]
@slavdok the documentation is incorrect. Neither of these capabilities is supported for ECS Compose.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
I've added the issue to the upstream repo containing the source file at https://github.com/docker/compose-cli/issues/2153
Closing this issue in favor of that one.
