### ISSUE TITLE
404 at /dekstop/windows/wsl/

### ISSUE THREAD

**Issue by fauzanhardy** [docker/docker.github.io#14607]
I found a broken link : https://docs.docker.com/dekstop/windows/wsl/

**Comment by thaJeztah** [comment]
the URL you're looking for is https://docs.docker.com/desktop/windows/wsl/

I suspect you made a typo (dekstop instead of desktop), or did you find that link somewhere? If so, could you tell us where you find the link?

**Comment by PMohanJ** [comment]
The URL you mentioned https://docs.docker.com/desktop/windows/wsl/ is broken 
in this page: https://docs.docker.com/desktop/windows/install/ 

It is a redirecting link under the heading of "Hyper-V backend and Windows containers" with text saying 'System requirements for WSL 2 backend'.

**Comment by PMohanJ** [comment]
@thaJeztah I looked into the markdown file of the URL https://docs.docker.com/desktop/windows/install/ 
and found that the redirection link is typed as `[System requirements for WSL 2 backend](#wsl-2-backend)`

After analyzing the page, I'm guessing the text should redirect to one of the following URL  / .md 
https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-2---check-requirements-for-running-wsl-2
https://docs.docker.com/desktop/windows/wsl/ (of which the markdown file is wsl.md)

Please let me know the information, if I can, I would like to fix it.
Thank you.

**Comment by thaJeztah** [comment]
RIght, so that looks to be somewhat unrelated to the broken URL

Looks like that link was meant to be toggling to the other ("WSL 2 backend") tab, but while it linked to the right heading, it didn't toggle the tab, so the heading it linked to wasn't made visible.

I just opened https://github.com/docker/docker.github.io/pull/14698 to "somewhat" fix it, but there's still an issue (see that PR's description)

**Comment by craig-osterhout** [comment]
Hi @fauzanhardy,
Thanks for sharing the issue. Closing this as stale. If the issue is still applicable, please help provide the requested details from the earlier comment.

 
> I suspect you made a typo (dekstop instead of desktop), or did you find that link somewhere? If so, could you tell us where you find the link?
