### ISSUE TITLE
404 at /go/dae

### ISSUE THREAD

**Issue by 1045334875** [docker/docker.github.io#14639]
I found a broken link : https://docs.docker.com/go/dae

**Comment by thaJeztah** [comment]
I think you're looking for https://docs.docker.com/go/daemon-access/

I know that URL may be printed on the command-line in when running docker, and possibly your terminal wasn't wide enough and truncated the output.

Did you arrive at that URL from the command-line, or did you find the link somewhere on one of our websites? (if so, could you let us know where you found the link?)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as stale. If the issue is still applicable, please help provide the requested details from the previous comment.
