### ISSUE TITLE
404 at /desktop/windows/release-motes/

### ISSUE THREAD

**Issue by jieke131419** [docker/docker.github.io#14640]
I found a broken link : https://docs.docker.com/desktop/windows/release-motes/

**Comment by thaJeztah** [comment]
I think you made a typo when typing that URL; `motes`  should be `notes`, so the correct URL is;

https://docs.docker.com/desktop/windows/release-notes/


Or did you find a link to that page somewhere on one of our websites? (If so, can you let us know where you found the broken link?)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as stale unless more details are provided.
