### ISSUE TITLE
Specify that all nodes need to be the same exact Docker version for production UCP clusters

### ISSUE THREAD

**Issue by mark-church** [docker/docker.github.io#1465]
File: [datacenter/ucp/2.0/guides/installation/plan-production-install.md](https://docs.docker.com/datacenter/ucp/2.0/guides/installation/plan-production-install/)

Can we specify on this page that for production UCP clusters, unless a temporary upgrade is occurring, all engines need to be the same x.y.z version number? We have seen several situations where this has caused issues and it should be documented.

**Comment by programmerq** [comment]
UCP could issue a warning in the gui/cli too. "engine version discrepancy detected. Please upgrade all engines to the same version."

**Comment by constanzekratel** [comment]
It looks like this one has already been fixed. Made a minor change to the page and added "exact" to same version to emphasize importance. See PR https://github.com/docker/docker.github.io/pull/2885

**Comment by constanzekratel** [comment]
Submitted a new PR for the same fix for UCP version 2.1: https://github.com/docker/docker.github.io/pull/2924
