### ISSUE TITLE
并没有告诉我如何安装Docker-compose

### ISSUE THREAD

**Issue by Doinng** [docker/docker.github.io#14674]
File: [compose/install.md](https://docs.docker.com/compose/install/)

**Comment by craig-osterhout** [comment]
Hi @Doinng, thanks for sharing the issue. 

For Windows and Mac, you'll need to Docker Desktop which includes compose. 
- Mac: https://docs.docker.com/desktop/mac/install/
- Windows: https://docs.docker.com/desktop/windows/install/

For Linux, you can drill down and use a script based on your distribution at https://docs.docker.com/engine/install/#server

If you're still unable to find the information, please let us know which operating system you're trying to install compose on.

**Comment by craig-osterhout** [comment]
I just noticed someone else mentioned a similar issue with more details. If this is the same issue, I'll keep this ticket closed in favor of #14665
