### ISSUE TITLE
cvcvcvcvcvvvvvcvcv

### ISSUE THREAD

**Issue by Chandrasai510** [docker/docker.github.io#14675]
### _cvvcvcvvcvvvccvvvcvFile:_ [get-started/index.md](https://docs.docker.com/get-started/)

**Comment by craig-osterhout** [comment]
Hi @Chandrasai510, thanks for contributing. If there's an issue with that topic, can you provide more details about the issue you encountered?

**Comment by craig-osterhout** [comment]
Closing this issue as stale. If the issue still persists in the documentation, please let us know more details.
