### ISSUE TITLE
$(pwd) doesnt work on windows

### ISSUE THREAD

**Issue by allenross356** [docker/docker.github.io#14686]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

Running the command in step 2 on Windows
$ docker run -dp 3000:3000 \
     -w /app -v "$(pwd):/app" \
     node:12-alpine \
     sh -c "yarn install && yarn run dev"

gives following error:
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by craig-osterhout** [comment]
Hi @allenross356, thanks for sharing the issue. 
If you are using Windows, please run the command in PowerShell.
The first command should specify that it's intended for another shell and not CMD.
