### ISSUE TITLE
opensource get-help page layout incorrectly rendering

### ISSUE THREAD

**Issue by programmerq** [docker/docker.github.io#147]
The layout on https://docs.docker.com/opensource/get-help/ is incorrectly rendering:

![image](https://cloud.githubusercontent.com/assets/37278/19249284/f1cf8b68-8ef1-11e6-9ca1-3a75db27f258.png)

**Comment by johndmulhausen** [comment]
Fixed in 6760a6a88b616f5a569a3a01021b27c2f0e1aa2b
