### ISSUE TITLE
Docker Compose Getting Started could not find Flask version as stated.

### ISSUE THREAD

**Issue by davethekay** [docker/docker.github.io#14703]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

Ran into an error when executing the first docker-compose command as follows:
 => ERROR [5/6] RUN pip install -r requirements.txt                                                                9.6s
------
 > [5/6] RUN pip install -r requirements.txt:
#13 6.954 Collecting flask
#13 7.059   Downloading Flask-2.1.2-py3-none-any.whl (95 kB)
#13 7.564      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 KB 176.3 kB/s eta 0:00:00
#13 7.732 ERROR: Could not find a version that satisfies the requirement reddis (from versions: none)
#13 7.734 ERROR: No matching distribution found for reddis
------
executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 1
ERROR: Service 'web' failed to build : Build failed

Please update or maybe give advise to prevent this from happening.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
Based on the error message, `redis` may be spelled wrong. 

Please verify the contents of requirements.txt for `redis` with one d.

For support in the future, please try the Docker Community Slack. https://dockercommunity.slack.com/

**Comment by davethekay** [comment]
OHHHHH, you were right! Subtle issue on my end. Thanks.
