### ISSUE TITLE
Release notes for Windows Docker Desktop 4.8.0 duplicated and not properly escaped

### ISSUE THREAD

**Issue by maffe** [docker/docker.github.io#14717]
### Problem description

- Section "Docker Desktop 4.8.0" appears twice.
- Changes subsection mentions `Fixed a bug where dangling images were not selected in the cleanup process if their name was not marked as “ " but their tag is.` The `<none>` in the quotation marks is not escaped and therefore not displayed in the browser.

### Problem location

- https://docs.docker.com/desktop/windows/release-notes/#docker-desktop-480
- https://docs.docker.com/desktop/windows/release-notes/#docker-desktop-480-1

**Comment by aevesdocker** [comment]
Hi maffe, 

Thank you for raising the issue. This has now been fixed so I'm closing the PR.

**Comment by aevesdocker** [comment]
Thanks, done https://github.com/docker/docker.github.io/pull/14820
