### ISSUE TITLE
unable to connect to docker labs instance (play with docker website) via SSH 

### ISSUE THREAD

**Issue by salim-dawod** [docker/docker.github.io#14715]
I'm trying to connect to docker instance on `https://labs.play-with-docker.com` via ssh as usual but i got an error:

EX:  `ssh ip172-18-0-173-c9tp6fk33d5g0xxxxxx@direct.labs.play-with-docker.com`

Error is: Unable to negotiate with 40.76.55.146 port 22: no matching host key type found. Their offer: ssh-rsa

and When i set `-oHostKeyAlgorithms=+ssh-rsa` I've got:
ip172-18-0-173-c9tp6fk33d5g0xxxxxx@direct.labs.play-with-docker.com: Permission denied (publickey).

OS : Kali linux

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
Based on https://github.com/play-with-docker/play-with-docker/issues/499, try using 
`ssh -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa [connection string as given on instance page]`

If you're still unable to connect, you can try opening an issue on the play-with-docker repo (https://github.com/play-with-docker/play-with-docker/issues), or try to get support on the Docker Community Slack (https://dockercommunity.slack.com/)

**Comment by vyapaari** [comment]
This can be simplified as

select the text below and copy to clipboard buffer 
by mouse, we will need to paste later.   

<pre>
Host playdocker
 HostName direct.labs.play-with-docker.com
 Port 22
 HostkeyAlgorithms +ssh-rsa
 PubkeyAcceptedKeyTypes +ssh-rsa 
 User ip172-18-0-xxx-xxxxxxxxxxxxxxxxxxx 
 IdentitiesOnly yes
 AddKeysToAgent yes
</pre>

replace ip172-18-0-xxx-xxxxxxxxxxxxxxxxxxx with your 
connection string as given on instance page 

now type and enter 

` cd ~/.ssh && ls -a ` 

This will list all the files in the directory ~/.ssh 
which is also currenct directory now;  
check if config file there; 
if false then make one by.

` touch config `  

If config file already there; 
then edit by 

` nano config `  

Remember we have already text copied in the clipboard buffer;  
while the cursor is blinking in nano. 

Hit Keys `Shift` + `Insert` on the key board to paste ; 
now hit `Ctrl` + `X` + `Y` `Enter` to exit and save  . 

Once again verify the User you paste in config file;
match with the user obtained on the instance page. 

type this on terminal and `Enter` 

`ssh playdocker`  

voila your are inside play with docker
