### ISSUE TITLE
Feedback for: engine/installation/binaries.md

### ISSUE THREAD

**Issue by justincormack** [docker/docker.github.io#1471]
File: [engine/installation/binaries.md](https://docs.docker.com/engine/installation/binaries/)

can we remove "This is strongly discouraged in production environments." - we use these for editions, and we are fixing issues that come up with the static binaries.

**Comment by mstanleyjones** [comment]
My impression was that we strongly prefer for users to use the binaries compiled for their platform if possible. @friism do you have thoughts on this?

**Comment by friism** [comment]
(responding out of channel)
