### ISSUE TITLE
Typo in 'container on port 8000'

### ISSUE THREAD

**Issue by iuriizhesson** [docker/docker.github.io#14730]
File: [language/golang/run-containers.md](https://docs.docker.com/language/golang/run-containers/)

![image](https://user-images.githubusercontent.com/36559044/168093013-2f347a68-8f0b-4fca-8350-a5ad06df4701.png)

I believe it should be 'container on port 8080'

**Comment by thaJeztah** [comment]
Thanks for reporting; this has been fixed by https://github.com/docker/docker.github.io/pull/14737
