### ISSUE TITLE
404 at /get-involved/docs/communityleaders/resources/guidelines/

### ISSUE THREAD

**Issue by selvaraj-kuppusamy** [docker/docker.github.io#14757]
I found a broken link : https://docs.docker.com/get-involved/docs/communityleaders/resources/guidelines/
I arrived on this page through: https://docker.github.io/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The page you're probably looking for is at https://docker-community-leaders.github.io/dockercommunity/docs/communityleaders/resources/guidelines/

If the broken link was located on a page under https://docs.docker.com, can you tell us which page and the location on the page?
