### ISSUE TITLE
Confusing page title for "stack yaml reference"

### ISSUE THREAD

**Issue by stevvooe** [docker/docker.github.io#1476]
This doc shows up when searching for "docker stack file". It is a bit confusing in conjunction with the new `docker stack deploy` support. It might be good to have a link at the top of the page to take the user to the compose v3 documentation or at least bring that to light.

File: [docker-cloud/apps/stack-yaml-reference.md](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/)

**Comment by bdwill** [comment]
dibs for hackathon

**Comment by mstanleyjones** [comment]
Fixed via #2971 and #2857 

Points to @bdwill and @jmaitrehenry

**Comment by joaofnfernandes** [comment]
Closing, as it was fixed by the PRs mentioned above.
