### ISSUE TITLE
Broken anchor link

### ISSUE THREAD

**Issue by mcctomsk** [docker/docker.github.io#1477]
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/)

I suppose you have mistake with formatting this paragraph:
### Set metadata on a service (-l, –label)
and it doesn't look like title one of examples and doesn't have cross link:
https://docs.docker.com/engine/reference/commandline/service_create/#set-metadata-on-a-service-l-label  
which use another pages.

**Comment by mstanleyjones** [comment]
https://docs.docker.com/engine/reference/commandline/service_create/#set-metadata-on-a-service--l---label is the correct link (see the extra `-`).

**Comment by scjane** [comment]
#dibs

**Comment by scjane** [comment]
The "Set metadata on a service (-l, –label)" section is disaplyed correctly under "Examples", and its anchor is valid now. 

![5](https://cloud.githubusercontent.com/assets/25146885/25162756/be221cda-24f7-11e7-91d9-08e9c7c68773.jpg)

This issue can be closed.

**Comment by johndmulhausen** [comment]
Thanks, @scjane -- you still get 25 points for validating that it was fixed. :)
