### ISSUE TITLE
Type in Container Resources Section

### ISSUE THREAD

**Issue by rmcsqrd** [docker/docker.github.io#14773]
File: [cloud/ecs-compose-features.md](https://docs.docker.com/cloud/ecs-compose-features/)

Hello, I believe there is a typo in the "Container Resources" section of the above documentation. Per https://github.com/docker/compose-cli/blob/main/ecs/compatibility.go#L63 I believe that the documentation referenced above should say "cpus" not "cpu". I was getting an error when using `cpu` that was corrected by changing it to `cpus` in my docker compose file.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
Added the issue to the upstream repo containing the file https://github.com/docker/compose-cli/issues/2152
Closing this.
