### ISSUE TITLE
step 3 of "Install using the repository" doesn't copy and paste correctly

### ISSUE THREAD

**Issue by osheroff** [docker/docker.github.io#14788]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

try to copy and paste the "echo ..." step 3 of "how to install on ubuntu".  doesn't c/p right.

**Comment by osheroff** [comment]
(on google chrome mac)

**Comment by thaJeztah** [comment]
Hmm.. yes, it looks like the highlighter (which was possibly updated to a more current version) now doesn't like commands that are wrapped and continue on the next line; it highlights them as process output (which we disable in the text-selection);

Before https://github.com/docker/docker.github.io/pull/14685

<img width="347" alt="Screenshot 2022-05-20 at 19 33 53" src="https://user-images.githubusercontent.com/1804568/169582038-0cb10e36-b766-442f-aab9-347d0e63bfa0.png">
<img width="965" alt="Screenshot 2022-05-20 at 19 33 58" src="https://user-images.githubusercontent.com/1804568/169582045-ce445350-c057-434a-8957-f08529b88596.png">


After https://github.com/docker/docker.github.io/pull/14685

<img width="967" alt="Screenshot 2022-05-20 at 19 31 23" src="https://user-images.githubusercontent.com/1804568/169581860-267ec2d9-9711-4ccb-b9ec-09a15da8c19e.png">
<img width="406" alt="Screenshot 2022-05-20 at 19 31 29" src="https://user-images.githubusercontent.com/1804568/169581867-952ac6f8-3ffa-4182-a2fe-a2a2c53aef16.png">

**Comment by thaJeztah** [comment]
^^ working on a fix

**Comment by thaJeztah** [comment]
Alright! Fix was merged https://github.com/docker/docker.github.io/pull/14791 and published;

<img width="610" alt="Screenshot 2022-05-20 at 20 24 41" src="https://user-images.githubusercontent.com/1804568/169590016-b9922500-28c6-4f61-ad43-0df9a4bff9cc.png">

Thank you @osheroff for reporting, and thanks @outloudvi for pointing to the related PR, that was really useful to create a fix!!


So it looks to be a regression in "rouge", which is the highlighter used by Jekyll for our docs; so looks like we need to have a look at their source to see what introduced the regression, and see if we can contribute a fix.

As a workaround, we temporarily downgraded to the previous version we used
