### ISSUE TITLE
Old docs inaccessible

### ISSUE THREAD

**Issue by rthrfrd** [docker/docker.github.io#1478]
### Problem description

- Cannot access https://docs.docker.com/v1.12/
- I also cannot see - in the current docs for a feature - the history of a feature (i.e. when it was introduced/changed). This would seem a basic requirement for an API as fluid and inconsistent as Docker's.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/v1.12/

### Project version(s) affected

- `<` current

### Suggestions for a fix

- Maintenance.

**Comment by mstanleyjones** [comment]
This was fixed by #1496
