### ISSUE TITLE
Documentation Needs to be Updated

### ISSUE THREAD

**Issue by wmullaney** [docker/docker.github.io#14794]
File: [compose/install.md](https://docs.docker.com/compose/install/)

The documentation states "The instructions below outline installation of the current stable release (v2.5.0) of Compose." When you look below in large bold text "Uninstallation" it gives instructions for how to uninstall compose. This should be updated. It's confusing. There is a link that goes to the install instructions but seeing as the page is specifically for install and not uninstall, the uninstall instructions should be on it's own page.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The uninstall instructions were moved in https://github.com/docker/docker.github.io/commit/d49af6a4495f653ffa40292fd24972b2df5ac0bc
