### ISSUE TITLE
apt install instruction

### ISSUE THREAD

**Issue by andrewfowlie** [docker/docker.github.io#14805]
File: [desktop/linux/install/ubuntu.md](https://docs.docker.com/desktop/linux/install/ubuntu/)

Should the instruction

    sudo apt-get install ./docker-desktop-<version>-<arch>.deb

be

    sudo dpkg -i ./docker-desktop-<version>-<arch>.deb

**Comment by craig-osterhout** [comment]
HI @andrewfowlie,
Thanks for sharing this issue. Does the `sudo apt-get install ./docker-desktop-<version>-<arch>.deb` command not work, or is there any reason to use the other command instead?

**Comment by andrewfowlie** [comment]
I thought it didn’t work. Afraid I did not record the exact problem as I thought it was just an error in the instructions, and switched to dpkg which is how I’d usually install deb files.

However, I now see though that apt supported installing local deb files for some time. Let’s close this then.
