### ISSUE TITLE
404 at /engine/installation/cloud/

### ISSUE THREAD

**Issue by arafat35** [docker/docker.github.io#14807]
I found a broken link : https://docs.docker.com/engine/installation/cloud/
I arrived on this page through: https://shinyproxy.io/

**Comment by thaJeztah** [comment]
That looks to have been a _very_ old link. Looks like we had some content on that URL a long time ago, but it's no longer there (this is the page that was at that location); https://github.com/docker/docker.github.io/blob/v1.12/engine/installation/cloud/index.md


Given that that page was removed a long time ago, I don't think we'll be adding a redirect for that, but if you were looking for specific content, let me know and perhaps I can point you to an alternative page 👍
