### ISSUE TITLE
404 at /desktop/windows/inst

### ISSUE THREAD

**Issue by imtisals** [docker/docker.github.io#14811]
I found a broken link : https://docs.docker.com/desktop/windows/inst
I arrived on this page through: https://teams.microsoft.com/

**Comment by thaJeztah** [comment]
I suspect someone posted an incomplete link in your teams change; you're likely looking for https://docs.docker.com/desktop/windows/install/


As this doesn't look like a broken link on one of our websites, I'll go ahead and close this ticket, but feel free to continue the conversation.
