### ISSUE TITLE
https://docs.docker.com/docker-for-mac/install/, consulté le 4 août 2019 [26] https://docs.docker.com/docker-for-windows/install/, consulté le 4 août 2019

### ISSUE THREAD

**Issue by selmi-13** [docker/docker.github.io#14817]
I found a broken link : https://docs.docker.com/docker-for-mac/install/,%20consult%C3%A9%20le%204%20ao%C3%BBt%202019%20[26]%20https://docs.docker.com/docker-for-windows/install/,%20consult%C3%A9%20le%204%20ao%C3%BBt%202019

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Can you let us know how you arrived at the broken link?

The links you were probably trying to access are here:
- https://docs.docker.com/docker-for-mac/install/
- https://docs.docker.com/docker-for-windows/install/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as stale. If the issue is still applicable, please help provide the requested details from the previous comment.
