### ISSUE TITLE
JeremyRockthunder 

### ISSUE THREAD

**Issue by rockthunderj** [docker/docker.github.io#14827]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If there is an issue with that topic, please share more details about the problem and any suggested fixes. 
Also, that topic is from an upstream repo. If there is an issue, please help create the issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference
Closing this issue in the docker.github.io repo.
