### ISSUE TITLE
MAC OS Rejects localhost certificate

### ISSUE THREAD

**Issue by gshafer** [docker/docker.github.io#14839]
File: [engine/swarm/configs.md](https://docs.docker.com/engine/swarm/configs/)

The config example uses localhost for the certificate. The Mac OSX does not recognize the localhost certificate and gives an error.

![Screen Shot 2022-05-26 at 3 06 51 PM](https://user-images.githubusercontent.com/203958/170559241-7562f5c4-22a0-4298-8520-f05629e56bfc.png)
.

**Comment by thaJeztah** [comment]
From the output, it looks like it's using TLS, but your browser won't accept a self-signed certificate by default; can you check what it says if you click the "not-secure"? If that shows information about the certificate you created, it means that the example itself worked (so the config is passed to the service)

**Comment by gshafer** [comment]
Does this give you the info you need?

![Screen Shot 2022-05-29 at 9 25 57 AM](https://user-images.githubusercontent.com/203958/170871264-f9b7735b-2351-49c5-9b13-f5e0296780ed.png)
