### ISSUE TITLE
Block IO: "read to and written from" should be-> "read from and written to"

### ISSUE THREAD

**Issue by spikerobinsonDLG** [docker/docker.github.io#14843]
File: [engine/reference/commandline/stats.md](https://docs.docker.com/engine/reference/commandline/stats/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Fixed in https://github.com/docker/cli/commit/c6636d4d658065f2ce72902271de58728debad99
It's not merged with the active branch yet.
