### ISSUE TITLE
503 for https://docs.docker.com/engine/reference/commandline/image_build/

### ISSUE THREAD

**Issue by dave-tucker** [docker/docker.github.io#1484]
### Problem description

Searched for `--build-args` and selected the 3rd result.
Clicked the link and was given a 503 error page.

### Problem location

- I saw a problem on the following URL:
https://docs.docker.com/engine/reference/commandline/image_build/

**Comment by johndmulhausen** [comment]
No repro -- we'll keep an eye out tho
