### ISSUE TITLE
Update command-line completion docs

### ISSUE THREAD

**Issue by mcnesium** [docker/docker.github.io#14854]
File: [compose/completion.md](https://docs.docker.com/compose/completion/)

Linked files currently result in 404s.

Also it seems that despite [GA announcement](https://www.docker.com/blog/announcing-compose-v2-general-availability/) there [is no cli completion for `docker compose` yet](https://github.com/docker/compose/issues/8436).

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Please see the discussion in https://github.com/docker/docker.github.io/issues/14692
