### ISSUE TITLE
Add a composefile example to the Docker for AWS and Azure deploy topic

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker.github.io#1486]
File: [docker-for-aws/deploy.md](https://docs.docker.com/docker-for-aws/deploy/)

https://docs.docker.com/docker-for-aws/deploy/ needs to be updated to show how a Compose application can be deployed to Docker for AWS. It shows only individual services at this time.

This was originally created at https://github.com/docker/docker/issues/30689.

**Comment by domg123** [comment]
#dibs

**Comment by jpooler** [comment]
@arun-gupta would something like https://github.com/julianespinel/stockreader/wiki/Deploy-to-AWS-using-docker-machine-and-docker-compose suffice? I would prefer to give credit to the author but not sure the process on that.

**Comment by arun-gupta** [comment]
That would be a good app.

I don't see a need for Docker Machine though. https://github.com/julianespinel/stockreader/blob/master/docker-compose.yml should be sufficient IMHO.

**Comment by mstanleyjones** [comment]
Fixed via #4620
