### ISSUE TITLE
docker-cli is no more

### ISSUE THREAD

**Issue by FredericLeroy** [docker/docker.github.io#14860]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

replace docker-cli by docker-ce-cli

**Comment by thaJeztah** [comment]
Can you point where on the page `docker-cli` is still mentioned? I did a quick search on the page, but didn't see it;

<img width="422" alt="Screenshot 2022-05-31 at 18 21 25" src="https://user-images.githubusercontent.com/1804568/171223965-18385810-e610-4a5b-8253-5cc19eedad58.png">

**Comment by FredericLeroy** [comment]
Sorry ! I must made a mistake, the page is good.
My hand must be hardcoded with docker-cli instead docker-ce-cli.
This was in the "Install Docker Engine"

My bad !

**Comment by thaJeztah** [comment]
Ha! No worries! Thanks for confirming 👍
