### ISSUE TITLE
Missing _docker-compose files in official documentation

### ISSUE THREAD

**Issue by Mellgood** [docker/docker.github.io#14865]
File: [compose/completion.md](https://docs.docker.com/compose/completion/)

Hi there,
I'm following the procedure to configure completion on my zsh shell, without oh-my-zsh.

The first step in documentation ask to curl a resource which is not abailable as I got a 404 not found error.

This is the link to the documentation:
https://docs.docker.com/compose/completion/#zsh

This is the missing file:
https://raw.githubusercontent.com/docker/compose/v2.5.0/contrib/completion/zsh/_docker-compose

Is it possible to get back that file?

P.S. i noted that also other links on that page are broken.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Please see the discussion in https://github.com/docker/docker.github.io/issues/14692
