### ISSUE TITLE
Can't build container when following tutorial

### ISSUE THREAD

**Issue by vtnate** [docker/docker.github.io#14878]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

### My versions
MacOS 10.15.7, Docker 4.9.0 (80466)

Step 2 of [this section](https://docs.docker.com/get-started/02_our_app/#build-the-apps-container-image) leads to sadness instead of understanding. Fwiw the contents of `/app/Dockerfile` in the tutorial is slightly different in the website and the getting-started repo. I've tried both and got the same error each time.

Below is the command I ran and the output from it:

>  ❯ docker build -t getting-started .
[+] Building 2.0s (6/9)
 => [internal] load build definition from Dockerfile                             0.0s
 => => transferring dockerfile: 269B                                             0.0s
 => [internal] load .dockerignore                                                0.0s
 => => transferring context: 2B                                                  0.0s
 => [internal] load metadata for docker.io/library/node:12-alpine                1.5s
 => CACHED [1/5] FROM docker.io/library/node:12-alpine@sha256:d4b15b3d48f42059a  0.0s
 => [internal] load build context                                                0.0s
 => => transferring context: 2.72kB                                              0.0s
 => ERROR [2/5] RUN apk add --no-cache python2 g++ make                          0.4s
------
 > [2/5] RUN apk add --no-cache python2 g++ make:
#5 0.230 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
#5 0.317 139740710574920:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
#5 0.319 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
#5 0.319 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: Permission denied
#5 0.412 139740710574920:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
#5 0.415 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: Permission denied
#5 0.415 ERROR: unable to select packages:
#5 0.417   g++ (no such package):
#5 0.417     required by: world[g++]
#5 0.417   make (no such package):
#5 0.417     required by: world[make]
#5 0.417   python2 (no such package):
#5 0.417     required by: world[python2]
------
> executor failed running [/bin/sh -c apk add --no-cache python2 g++ make]: exit code: 3

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Please check https://stackoverflow.com/questions/70508308/docker-build-getting-started-tutorial-certificate-error
If you're still having issues, please join the Docker Community Slack and try to get support. https://dockercommunity.slack.com
