### ISSUE TITLE
404 at /search/%EF%BC%89

### ISSUE THREAD

**Issue by qq0916979393** [docker/docker.github.io#14872]
File： [search.md]（https://docs.docker.com/search/）

**Comment by jerae-duffin** [comment]
Hey @qq0916979393 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by craig-osterhout** [comment]
Hi @qq0916979393, closing this as stale. To re-open, please share more details about how you arrived at the broken link.
