### ISSUE TITLE
404 at /registry/spec/deprecated-schema-v1/:

### ISSUE THREAD

**Issue by kobboi** [docker/docker.github.io#14887]
I found a broken link : https://docs.docker.com/registry/spec/deprecated-schema-v1/:

Getting this when pushing an image in, admittedly, a ecosystem that is old. I have no idea whether this is a client or server message, but the broken link is not very user-friendly.

**Comment by thaJeztah** [comment]
That URL works for me (not getting a 404); can you verify if you're still getting a 404 on that URL? https://docs.docker.com/registry/spec/deprecated-schema-v1/

**Comment by kobboi** [comment]
Turns out my terminal emulator thinks the colon is part of the URL. I didn't catch it, but seeing that you didn't either, I feel less bad ;)

**Comment by thaJeztah** [comment]
Ah! Hm, perhaps we need to print it on a new line, or add a space in between if we print it there 🤔
