### ISSUE TITLE
docker-compose documentation broken

### ISSUE THREAD

**Issue by mcrapts** [docker/docker.github.io#14885]
- I saw a problem at the following URL: https://docs.docker.com/compose/install/compose-plugin/#installing-compose-on-linux-systems

Issues I found with this page:

- A lot of subheaders/tabs missing for easy navigation
- Numbering is all over the place
- Code block contains instructions (bug?)
- Random capitalization ("Install the Plugin")

Also on the [landing page](https://docs.docker.com/compose/install/) there is a spelling error as well: "plugin,s" should be "plugins"

I'm not sure what happened, yesterday morning the page was fine and all of a sudden it's a huge mess that is extremely unclear. I think even if these issues are fixed, the new installations instructions are a step backwards, a lot of clicks and navigation required before finding the installation instruction. Previously you immediately saw the `curl` command you needed to copy/paste.

Edit: I think this commit is the culprit: https://github.com/docker/docker.github.io/commit/d49af6a4495f653ffa40292fd24972b2df5ac0bc

**Comment by dockertopia** [comment]
Hi @mcrapts, you also created a PR (for these same remarks) where we have addressed your concerns. I saw that you left extra comments on the merged PR :). If I don't reach out for a sync mid July, please ping me.
