### ISSUE TITLE
Provide optional tabs for code blocks - Linux and Windows Server

### ISSUE THREAD

**Issue by BrandonRoyal** [docker/docker.github.io#1488]
### Problem description
Most of the documentation examples only work on Linux.  In an effort to provide Windows Containers users access to these guides, we should allow users to toggle between a Linux and Windows Server code samples.

### Problem location
Anywhere there's a code sample.  One example would be https://docs.docker.com/engine/getstarted/step_three/#/step-2-run-the-whalesay-image

### Project version(s) affected
All

### Suggestions for a fix

**For example, where first tab is "Linux" and second tab is "Windows Server":**
![image](https://cloud.githubusercontent.com/assets/2762697/22573921/6707841c-e960-11e6-903b-185366689f0e.png)

In this example, the user can select the language of their choice.  In our case they would select the O/S of their choice.

Recognizing that these examples will be applied over time, it would be ideal for this tab to be optional in the documentation markup.

**Comment by johndmulhausen** [comment]
The old getting started is no longer with us, and now there is a Microsoft path through the Getting Started that replaced it! I'm closing this so that we have an opportunity to get more focused feedback.
