### ISSUE TITLE
Non root user not able to access log file

### ISSUE THREAD

**Issue by Renukasonwane** [docker/docker.github.io#14901]
Added non root user in the application , user is being added. But while running docker container , it is giving permission denied error while opening Log file to the non root user and also docker container is getting re-started automatically.

Please suggest how can I grant access to non root user and why container is getting restarted.

**Comment by craig-osterhout** [comment]
Hi @Renukasonwane,
Were you following a tutorial or topic in the documentation when you encountered issues?
If so, can you share the topic URL, the commands you entered, and the output.

If you're on Linux and trying to manage Docker as a non-root user, please see https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

If you need support for issues other than the documentation issues, you can try the Docker Community Slack or Forums:
 - https://forums.docker.com/
 - https://dockercommunity.slack.com/

**Comment by Renukasonwane** [comment]
To add non - root users followed this tutorial - https://www.thegeekdiary.com/run-docker-as-a-non-root-user/ .
And after adding non - root user getting error - rror: EACCES: permission denied, open 'logs/containename.slog' file

**Comment by craig-osterhout** [comment]
Thanks for sharing the additional info. It's not enough information to be able to reproduce the error after only following the steps in the Docker documentation. This does not seem to be an issue with the documentation. For support, you can try the Docker Community Slack or Forums:

- https://forums.docker.com/
- https://dockercommunity.slack.com/
