### ISSUE TITLE
Docker Desktop Kubernetes does not mention .kube/config file

### ISSUE THREAD

**Issue by gebrouwe** [docker/docker.github.io#14916]
File: [desktop/kubernetes.md](https://docs.docker.com/desktop/kubernetes/)
The page describes the command: kubectl config get-contexts.
However, it does not describe what should be done when kubectl config get-contexts returns an empty result.
In my situation (in Cygwin), I could fix this by setting the KUBECONFIG to 'C:\Users\<username>\.kube\config'
This can be solved in the page by mentioning the location of the .kube/config file, and the KUBECONFIG environment variable.

**Comment by aevesdocker** [comment]
Thank you for the feedback @gebrouwe. The page has been updated to reflect your comments and should be live in docs.docker.com soon.
