### ISSUE TITLE
404 at /desktop/previous-versions/3.x-windows/undefined

### ISSUE THREAD

**Issue by k2tt5141** [docker/docker.github.io#14926]
<font class="papago-parent"><font class="papago-source" style="display:none;">I found a broken link : https://docs.docker.com/desktop/previous-versions/3.x-windows/undefined
</font>끊어진 링크를 찾았습니다.https://docs.docker.com/desktop/previous-versions/3.x-windows/undefined</font><font class="papago-parent"><font class="papago-source" style="display:none;">I arrived on this page through: https://docs.docker.com/desktop/previous-versions/3.x-windows/</font>이 페이지는 https://docs.docker.com/desktop/previous-versions/3.x-windows/ 에서 입수했습니다.</font>

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this ticket in favor of https://github.com/docker/docker.github.io/issues/13553, but if you're able to provide more details that could help us find the problem, feel free to comment on that ticket.
