### ISSUE TITLE
404 at /compose/compo...%C3%A2%C2%80%C2%8B

### ISSUE THREAD

**Issue by mjsanthosh** [docker/docker.github.io#14929]
I found a broken link : https://docs.docker.com/compose/compo...%C3%A2%C2%80%C2%8B
I arrived on this page through: https://www.youtube.com/

**Comment by craig-osterhout** [comment]
Thanks for sharing the broken link issue. 
You can probably browse and find the topic you were looking for at https://docs.docker.com/compose/
In regards to the broken link, if the issue is still applicable, please report the broken link on the platform/page that you arrived through.
