### ISSUE TITLE
404 at /desktop/extensions-sdk/dev/api/reference/interfaces/BackendV0/null

### ISSUE THREAD

**Issue by tukobadnyanoba** [docker/docker.github.io#14922]
I found a broken link : https://docs.docker.com/desktop/extensions-sdk/dev/api/reference/interfaces/BackendV0/null
I arrived on this page through: https://docs.docker.com/desktop/extensions-sdk/dev/api/reference/interfaces/BackendV0/

**Comment by craig-osterhout** [comment]
![image](https://user-images.githubusercontent.com/103533812/173403648-907781fa-5a3b-4556-8f4a-d7ba7a06b4f8.png)
