### ISSUE TITLE
Documentation section on the escape character needs an update

### ISSUE THREAD

**Issue by ferrlen** [docker/docker.github.io#14939]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

Hi!

I believe the section https://docs.docker.com/engine/reference/builder/#escape is outdated and should be rewritten. First, `microsoft/nanoserver` is not maintained anymore, so running `FROM microsoft/nanoserver` [implicit tag: latest] will output an error. But most importantly, I couldn't reproduce the `COPY testfile.txt c:\\` bug mentioned there, this has probably been fixed already. I only get a weird bug if I run `RUN dir c:\\`, which is absent if `RUN dir c:\somedir\\` is run instead.

I'd like to ask one of the mods/people in charge to please update this section, so other users don't waste time trying to figure out how to escape the "escape character". I think it can always be escaped by using it twice (for example: `\\`), except in RUN or CMD instructions

Thanks

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/blob/master/docs/reference/builder.md
