### ISSUE TITLE
Documentation for how to use 'tag' confusing

### ISSUE THREAD

**Issue by davewichers** [docker/docker.github.io#14935]
File: [engine/reference/commandline/tag.md](https://docs.docker.com/engine/reference/commandline/tag/)

This documentation is confusing because it says:

docker tag
  Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE

Usage
 docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]

Notice that the docker tag explanation and the Usage of the TARGET/SOURCE images backwards from each other.

And when you run: docker it outputs the line:  tag     Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
but when you run docker tag, it says:   Usage:   docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]

So. if you simply run docker tag TARGET_IMAGE[:TAG] SOURCE_IMAGE[:TAG], which is how the 1st example plains how to use it, it breaks.

I suggest you rewrite this page to instead say something like:

docker tag
  Reference SOURCE_IMAGE to create the tag TARGET_IMAGE

Usage
 docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]

And also update this same documentation when running just: docker

That way the SOURCE/TARGET are in the same order, reducing confusion. And this doesn't break the command at all as its simply a documentation change. I do admit that this new language is a bit awkward, but having the params in the right order is important.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo along with the CLI. Please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline

**Comment by davewichers** [comment]
Done. See: https://github.com/docker/cli/issues/3674
