### ISSUE TITLE
I can't run this exemple

### ISSUE THREAD

**Issue by rafaelfrancisco-contato** [docker/docker.github.io#14946]
File: [get-started/08_using_compose.md](https://docs.docker.com/get-started/08_using_compose/)

When running the exemple the 'app' container isn't start. The MySQL is ok.
Can you help me?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. For support and troubleshooting, please try the Docker Community Slack or forums:
- https://dockercommunity.slack.com/
- https://forums.docker.com/
