### ISSUE TITLE
404 at /build/bake/

### ISSUE THREAD

**Issue by fredericdalleau** [docker/docker.github.io#14953]
I found a broken link : https://docs.docker.com/build/bake/
I arrived on this page through: https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As this content is maintained in an upstream repo, please help create an issue in the source repo to fix https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md
