### ISSUE TITLE
404 at /build/bake/file-definition/

### ISSUE THREAD

**Issue by fredericdalleau** [docker/docker.github.io#14954]
I found a broken link : https://docs.docker.com/build/bake/file-definition/
I arrived on this page through: https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md

**Comment by crazy-max** [comment]
Yes indeed we have not yet published the new buildx docs on the website. Will be fixed with https://github.com/docker/docker.github.io/pull/14905. See preview https://deploy-preview-14905--docsdocker.netlify.app/build/bake/file-definition/
