### ISSUE TITLE
URL Paths in Repo file don't match the Site Repos

### ISSUE THREAD

**Issue by Byte-alyzer** [docker/docker.github.io#15010]
File: [engine/install/rhel.md](https://docs.docker.com/engine/install/rhel/)

Snippet from the docker-ce.repo file downloaded per instructions in above doc:

[docker-ce-stable]
name=Docker CE Stable - $basearch
baseurl=https://download.docker.com/linux/rhel/$releasever/$basearch/stable

Result:

yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin
Updating Subscription Management repositories.
Docker CE Stable - x86_64                                            3.9 kB/s | 381  B     00:00    
Errors during downloading metadata for repository 'docker-ce-stable':
  - Status code: 404 for https://download.docker.com/linux/rhel/8/x86_64/stable/repodata/repomd.xml (IP: 99.86.224.27)
Error: Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Apparent URL path:"

https://download.docker.com/linux/rhel/8/source/stable/

**Comment by thaJeztah** [comment]
This is because you're trying to install the package on x86, but no packages are provided currently for RHEL on x86. From the same page; https://docs.docker.com/engine/install/rhel/#prerequisites

> Prerequisites[🔗](https://docs.docker.com/engine/install/rhel/#prerequisites)
> Note
> 
> We currently only provide packages for RHEL on s390x (IBM Z). Other architectures are not yet supported for RHEL, but you may be able to install the CentOS packages on RHEL. Refer to the [Install Docker Engine on CentOS](https://docs.docker.com/engine/install/centos/) page for details.


Closing this ticket because of the above, but feel free to continue the conversation
