### ISSUE TITLE
Unable to find image 'hello-world:latest' locally docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": unable to connect to 44.194.155.131:443. Do you need an HTTP proxy?.

### ISSUE THREAD

**Issue by tanaybasak** [docker/docker.github.io#15029]
### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by craig-osterhout** [comment]
Related to https://github.com/docker/for-win/issues/12750

**Comment by sanketwagh147** [comment]
Facing the same issue with Docker Desktop.

**Comment by aevesdocker** [comment]
Closing this as it is not a documentation issue.
