### ISSUE TITLE
404 at: /v1.8/introduction/understanding-docker/

### ISSUE THREAD

**Issue by pravarsh** [docker/docker.github.io#1502]
URL: /v1.8/introduction/understanding-docker/

**Comment by mstanleyjones** [comment]
404 in archive version.

**Comment by mstanleyjones** [comment]
The correct URL is https://docs.docker.com/v1.8/engine/introduction/understanding-docker/, FYI.

**Comment by mstanleyjones** [comment]
Closed via #2787
