### ISSUE TITLE
wrong path, Docker folder does not exist

### ISSUE THREAD

**Issue by sercasti** [docker/docker.github.io#15020]
File: [compose/install/compose-plugin.md](https://docs.docker.com/compose/install/compose-plugin/)

Step says " -OutFile $Env:ProgramFiles\Docker\docker-compose.exe" but the \Docker folder does not exist, so command fails

**Comment by dockertopia** [comment]
@sercasti thanks for reaching out, can you please provide more context about which method of installation were you following, your starting point of installation and the steps you took? Thanks in advanced.

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists, please provide the requested information.
