### ISSUE TITLE
Link for Bash Completion script returns 404 Error

### ISSUE THREAD

**Issue by alexmerm** [docker/docker.github.io#15034]
File: [compose/completion.md](https://docs.docker.com/compose/completion/)
Link in the docs for the bash completion script (included in the scripts) leads to a 404 error. I can't seem to locate the correct file either.

**Comment by glours** [comment]
@alexmerm where did you get this link?
The code completion for Compose v2 is currently a work in progress, so [we removed temporarily](https://github.com/docker/docker.github.io/pull/14732/files) the page in the documentation and we don't have any completion scripts available at the moment

**Comment by dockertopia** [comment]
@alexmerm Both the page and the scripts the page mentions are unavailable until we implement code completion for Compose v2 like @glours mentioned. In the meantime you should be redirected to compose/index while trying to navigate to this page.
