### ISSUE TITLE
Installation file for Apple silicon does not have a .dmg extension

### ISSUE THREAD

**Issue by pfranjic** [docker/docker.github.io#15047]
File: [desktop/mac/apple-silicon.md](https://docs.docker.com/desktop/mac/apple-silicon/)

The installation file for Apple silicon does not have a .dmg extension

**Comment by sarkartanmay393** [comment]
I don't see the problem, you are mentioning though.

**Comment by pfranjic** [comment]
If it helps, this is what the file looks like in my download history, with other `.dmg`s for comparison
<img width="502" alt="Screenshot 2022-07-04 at 13 23 35" src="https://user-images.githubusercontent.com/19371132/177145171-3c621df1-9921-4c54-a066-b00fb69d1f99.png">

**Comment by sarkartanmay393** [comment]
Yes, but It's not an issue, I think. In macbook m1, it's working fine and that link also downloads .dmg for me. Let's see if other people mention this issue.

**Comment by aroramrinaal** [comment]
> Yes, but It's not an issue, I think. In macbook m1, it's working fine and that link also downloads .dmg for me. Let's see if other people mention this issue.

It's working fine for me 
<img width="1440" alt="Screenshot 2022-07-04 at 5 59 05 PM" src="https://user-images.githubusercontent.com/90490253/177155146-464ab7b0-c55d-42c3-8429-beb5ea25bce4.png">

**Comment by pfranjic** [comment]
It's working fine for me in Safari as well, maybe it's browser-related

**Comment by Aebrathia** [comment]
I had the issue on FF. I then tried on Chrome and it has the expected .dmg extension.

**Comment by sarkartanmay393** [comment]
Hey @pfranjic, as it is not an issue, you can close the PR.
