### ISSUE TITLE
404 at /en/latest/installation/vagrant/

### ISSUE THREAD

**Issue by nzapodege** [docker/docker.github.io#15065]
I found a broken link : https://docs.docker.com/en/latest/installation/vagrant/

**Comment by aevesdocker** [comment]
Hi @nzapodege thanks for reporting the broken link. Could you please tell me how you arrived on this broken link? Which page did you come from?

**Comment by nzapodege** [comment]
Ci sono arrivato da qui

   https://github.com/pdulvp/jellyfin-qnap

   Da "Allie Sadler" ***@***.***
   Un "docker/docker.github.io" ***@***.***
   Cc "nzapodege" ***@***.***,"Menzione" ***@***.***
   Data lun, 11 lug 2022 04:35:26 -0700
   Oggetto Re: [docker/docker.github.io] 404 in /en/latest/installation/vagrant/ (Numero 15065)

   ***@***.*** per aver segnalato il collegamento interrotto. Potresti per favore dirmi come sei arrivato su questo link interrotto? Da quale pagina vieni?

   —
   Rispondi direttamente a questa email, visualizzala su GitHub o annulla l'iscrizione .
   Stai ricevendo questo perché sei stato menzionato. Message ID: ***@***.***>

**Comment by aevesdocker** [comment]
Thanks. Please report this issue on the source page where the link is located as it may be they have entered the link incorrectly and the real link should be https://docs.docker.com/engine/install/
