### ISSUE TITLE
Can the maximum size of the disk image be set in a configuration file?

### ISSUE THREAD

**Issue by jhammons** [docker/docker.github.io#15083]
File: [desktop/linux/space.md](https://docs.docker.com/desktop/linux/space/)

I am hoping I can add something to $HOME/.docker/daemon.json or similar to limit the maximum size. I am trying to initialize an installation on a system with limited resources, but cannot get to the settings to change this limit without it first attempting to create a 64GB file and then crashing.

**Comment by aevesdocker** [comment]
Hi @jhammons please report this issues to the Docker Desktop for Linux GitHub repo where they'll be better placed to answer your question 
https://github.com/docker/desktop-linux/issues

**Comment by jhammons** [comment]
Thank you.
