### ISSUE TITLE
Github Actions have not UI.

### ISSUE THREAD

**Issue by jjoselon** [docker/docker.github.io#15093]
File: [language/python/configure-ci-cd.md](https://docs.docker.com/language/python/configure-ci-cd/)

https://docs.github.com/es/actions/quickstart#creating-your-first-workflow

**Comment by craig-osterhout** [comment]
Hi @jjoselon, thanks for sharing the issue. Can you provide more details about what you mean by GitHub Actions has no UI?

By following the steps in [Set up the GitHub Actions Workflow](https://docs.docker.com/language/python/configure-ci-cd/#set-up-the-github-actions-workflow), I was able to access the UI. Granted that the UI is basically a web-based text editor.

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists, please let us know more details.
