### ISSUE TITLE
docker desktop install error (fedora 36 rpm)

### ISSUE THREAD

**Issue by orestephen** [docker/docker.github.io#15092]
File: [desktop/linux/install/fedora.md](https://docs.docker.com/desktop/linux/install/fedora/)

```cli
sudo dnf install ./docker-desktop-4.10.1-x86_64.rpm
Fedora 36 - x86_64 - Updates                     40 kB/s |  17 kB     00:00    
Fedora 36 - x86_64 - Updates                    302 kB/s | 465 kB     00:01    
Fedora Modular 36 - x86_64 - Updates             44 kB/s |  16 kB     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides docker-ce-cli needed by docker-desktop-4.10.1-82475.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

Seems like there is more prerequisites than what is listed?

any ideas where to start in reporting this issue with more details?

**Comment by aevesdocker** [comment]
Hi @orestephen, thanks for raising the PR. The best place to report this issue in more detail is https://github.com/docker/desktop-linux/issues
