### ISSUE TITLE
Feedback for: engine/installation/linux/centos.md

### ISSUE THREAD

**Issue by b-t-o** [docker/docker.github.io#1509]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

Only removing old version of docker did not work for me, because of the depencies.

I had to execute

sudo yum -y remove docker-selinux  
sudo yum -y remove docker-common

additionally

**Comment by mstanleyjones** [comment]
This feedback was addressed by earlier work. Thanks!
