### ISSUE TITLE
Docker file missing DMG extension for x86 variant.

### ISSUE THREAD

**Issue by petertorelli** [docker/docker.github.io#15136]
File: [desktop/install/mac-install.md](https://docs.docker.com/desktop/install/mac-install/)

FYI the downloaded file is "Docker" and needs to be renamed to "Docker.dmg"

**Comment by StefanScherer** [comment]
Thanks for the report. We checked everything on our side and it turns out it is a bug in Firefox 102 and it should be fixed in the next Firefox release.
