### ISSUE TITLE
mac-install.md shows a Linux screenshot...

### ISSUE THREAD

**Issue by olalonde** [docker/docker.github.io#15135]
<img width="884" alt="Screen Shot 2022-07-16 at 3 00 05 PM" src="https://user-images.githubusercontent.com/416585/179354029-8eef481b-0fe3-4837-a39a-897e53b4c703.png">

**Comment by aevesdocker** [comment]
Thanks for reporting. This has now been fixed https://github.com/docker/docker.github.io/pull/15171
