### ISSUE TITLE
Downloaded docker file does not have .dmg extension

### ISSUE THREAD

**Issue by JohnGiorgi** [docker/docker.github.io#15139]
After following the "Mac with intel chip" download link, a file `Docker` (without the `.dmg` extension) is downloaded. You have to manually add the `.dmg` extension in order to be able to follow the rest of the instructions (double-clicking and dragging the `Docker.app` into Applications). Happens in Firefox on a 16" MBP with an Intel chip, running macOS Monterey 12.4.

<img width="1194" alt="Screen Shot 2022-07-17 at 10 46 51 AM" src="https://user-images.githubusercontent.com/8917831/179418276-4ef72c7f-40af-4737-a454-6239ddbd4a95.png">

File: [desktop/install/mac-install.md](https://docs.docker.com/desktop/install/mac-install/)

**Comment by StefanScherer** [comment]
Thanks for the report. We checked everything on our side and it turns out it is a bug in Firefox 102 and it should be fixed in the next Firefox release.
