### ISSUE TITLE
remove duplicate word

### ISSUE THREAD

**Issue by Cristian-Vt** [docker/docker.github.io#15131]
File: [engine/api/index.md](https://docs.docker.com/engine/api/)

To force the Docker CLI or the Docker Engine SDKs to use an old version version of the API than the version reported by docker version, set the environment variable DOCKER_API_VERSION to the correct version. This works on Linux, Windows, or macOS clients.

you've got a duplication. version version

**Comment by jerae-duffin** [comment]
Hey @Cristian-Vt Thank you for reporting this issue. We're working to get it updated.

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/docker.github.io/pull/15319
