### ISSUE TITLE
Feedback for: engine/installation/linux/fedora.md

### ISSUE THREAD

**Issue by rajeshpv** [docker/docker.github.io#1513]
File: [engine/installation/linux/fedora.md](https://docs.docker.com/engine/installation/linux/fedora/)
around line "4. Start Docker."
The Docker Start should be other way (if I am right!)
Current line is "$ sudo systemctl docker start"
CORRECT line "$ sudo systemctl start docker"

Thanks
Rajesh

**Comment by mstanleyjones** [comment]
This was fixed in #1523. Thanks!
