### ISSUE TITLE
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority.

### ISSUE THREAD

**Issue by vikascse29** [docker/docker.github.io#15142]
File: [search.md](https://docs.docker.com/search/)
Getting this error while running hello world
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority.

**Comment by craig-osterhout** [comment]
Hi @vikascse29, thanks for sharing the issue. One thing to check is if you're using a proxy or VPN.
For further support, please try the following:
- [Docker Community Forums](https://forums.docker.com/)
- [Docker Community Slack](https://dockercommunity.slack.com/)
- If you have a paid Docker subscription, you can use [Docker support](https://hub.docker.com/support/contact/).
