### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntu.md

### ISSUE THREAD

**Issue by sravan-s** [docker/docker.github.io#1516]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/)

I'm using Linux Mint Rafaela. Since mint is a distribution based on Ubuntu, I believe people would usually use this page

Now this part
```
sudo add-apt-repository \
       "deb https://apt.dockerproject.org/repo/ \
       ubuntu-$(lsb_release -cs) \
       main"  
```

Creates an additional-repositories.list file saying:
`deb https://apt.dockerproject.org/repo/        ubuntu-rafaela        main`
Which in turn throws 403 forbidden error while running **apt-get update**
And I wasn't able to finish my installation

But when I used 

```
sudo add-apt-repository \
       "deb https://apt.dockerproject.org/repo/ \
        ubuntu-precise \
       main"  
```
Everything worked fine.
I guess it would be good if we add a pointer saying **ubuntu-$(lsb_release -cs)** means give the stable version of your parent distribution

What are your opinions?

**Comment by sravan-s** [comment]
@mstanleyjones ,

Is it fine, if I try to contribute to this?

**Comment by sravan-s** [comment]
@mstanleyjones,
Is it fine to close this issue now?

**Comment by mstanleyjones** [comment]
Yep! In the future, if you add a line like "Fixes #<issue_number>", Github will do this automatically when your PR is closed.
