### ISSUE TITLE
Not able to download the app

### ISSUE THREAD

**Issue by Nitinsharma271** [docker/docker.github.io#15167]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)
Hello,

I'm trying to download app but not able to download the zip from here 
https://github.com/docker/getting-started/tree/master/app
<img width="1235" alt="Screenshot 2022-07-19 at 22 14 32" src="https://user-images.githubusercontent.com/29594141/179849692-9aad80e9-2451-4380-aee2-edbda25a472a.png">

Thank you

**Comment by craig-osterhout** [comment]
Hi @Nitinsharma271, thanks for sharing this.
You can go to https://github.com/docker/getting-started/tree/master, click `Code`, and then select `Download ZIP`. Extract the `app` directory out of that zip file.
