### ISSUE TITLE
Feedback for: engine/api/v1.24.md

### ISSUE THREAD

**Issue by abha10** [docker/docker.github.io#1517]
File: [engine/api/v1.24.md](https://docs.docker.com/engine/api/v1.24/)

While using `Create a service` API , I'm not able to authenticate `X-Registry-Auth` i.e. if in case I have entered incorrect base64-encoded login value , it does not through any error instead it creates a service successfully with no image created.

**Comment by mstanleyjones** [comment]
@aaronlehmann did you intend to make a PR for this?

To the OP, please file an issue in the `docker/docker` repo about this.

**Comment by aaronlehmann** [comment]
See https://github.com/docker/docker.github.io/issues/1530#issuecomment-291701118
