### ISSUE TITLE
Where is the registry source?

### ISSUE THREAD

**Issue by bigtfromaz** [docker/docker.github.io#15193]
File: [registry/index.md](https://docs.docker.com/registry/)

In the Registry overview, you state that the project is open source. Consider adding a link to the git repo near that assertion.  I want to report a bug and am having great difficulty finding the git repo so I can open an issue.

**Comment by usha-mandya** [comment]
@bigtfromaz Here's the link to the Registry open source project - https://github.com/distribution/distribution. Thanks for the feedback. We'll add this link from the Registry Docs page.
