### ISSUE TITLE
Unable to connect oracle database after migrating to another server

### ISSUE THREAD

**Issue by mitul198** [docker/docker.github.io#15226]
I am getting below error post migrating oracle db container from one machine to another -

Status : Failure -Test failed: IO Error: The Network Adapter could not establish the connection (CONNECTION_ID=naeUgqEAQ46y+asY1KlQ6A==)

I am able to connect to db inside container but outside container connection not happening.

**Comment by craig-osterhout** [comment]
Hi @mitul198, thanks for sharing the issue. For support, you can try the following:
- [Docker Community Slack](https://dockercommunity.slack.com/)
- [Docker Community Forums](https://forums.docker.com/)

If there are any issues in the documentation, please let us know more details about which topic and the errors in the topic.
