### ISSUE TITLE
404 at /desktop/mac/

### ISSUE THREAD

**Issue by azul-jf** [docker/docker.github.io#15232]
I found a broken link : https://docs.docker.com/desktop/mac/
I arrived on this page through: https://www.google.com/
My search terms were "linux container macos"

**Comment by thaJeztah** [comment]
Thanks for reporting! Looks like https://github.com/docker/docker.github.io/pull/15219 removed the pages, but didn't add redirects; I opened a pull request to fix this; https://github.com/docker/docker.github.io/pull/15231
