### ISSUE TITLE
Feedback for: engine/installation/linux/centos.md

### ISSUE THREAD

**Issue by huangsen365** [docker/docker.github.io#1524]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

 Update centos.md

change "systemctl docker start" to "systemctl start docker"

https://github.com/docker/docker.github.io/commit/ffa7fc49dffed4fb7265974de7388dc3c26e5d2f#diff-8d6ad4aec4d08d0acfdbb07eef6ef28d

**Comment by mstanleyjones** [comment]
Fixed in #1523
