### ISSUE TITLE
404 at /desktop/troubleshoot/overview/https://docs.docker.com/desktop/troubleshoot/overview/

### ISSUE THREAD

**Issue by sofiah99** [docker/docker.github.io#15266]
I found a broken link : https://docs.docker.com/desktop/troubleshoot/overview/https://docs.docker.com/desktop/troubleshoot/overview/

**Comment by craig-osterhout** [comment]
Hi @sofiah99, thanks for sharing the broken link. 
You probably already found it, but just in case, the correct link is https://docs.docker.com/desktop/troubleshoot/overview/

Is the broken link's source somewhere in docs.docker.com or does another website contain the broken link?
