### ISSUE TITLE
Add note that Compose version 3 doesn't support additional IPAM configs

### ISSUE THREAD

**Issue by qmcree** [docker/docker.github.io#1528]
### Problem description

Need to mention that Docker Compose version 3 does not support any additional IPAM configurations except for subnet. See docker/compose#4366.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/compose/compose-file/#ipam

### Suggestions for a fix

Add note that the configurations are only acceptable for version 2 at the moment.

**Comment by Rubab-Syed** [comment]
I'll take this one.

**Comment by johndmulhausen** [comment]
Points to @Rubab-Syed -- thanks!
