### ISSUE TITLE
Document TaskTemplate > ContainerSpec > Hostname for /services/create and /services/update

### ISSUE THREAD

**Issue by sbrattla** [docker/docker.github.io#1531]
The following is (part of a) valid JSON when creating or updating a service :

```
{
  "Name": "testservice",
  "TaskTemplate": {
    "ContainerSpec": {
      "Hostname": "stage01{{.Service.Name}}-{{.Node.ID}}"
```

There is no mention of `Hostname` in the [API v1.25 Reference](https://docs.docker.com/engine/api/v1.25/#operation/ServiceCreate).

**Comment by mstanleyjones** [comment]
Duplicate of #1530
