### ISSUE TITLE
404 at /install/linux/docker-centos

### ISSUE THREAD

**Issue by Ban05RF** [docker/docker.github.io#15318]
I found a broken link : https://docs.docker.com/install/linux/docker-centos

**Comment by jerae-duffin** [comment]
Hey @Ban05RF Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by jerae-duffin** [comment]
Thank you for reporting this issue.  Please open a new ticket with the location of the broken link.
