### ISSUE TITLE
[Python docs feedback]

### ISSUE THREAD

**Issue by ganeshrevanth123** [docker/docker.github.io#15315]
### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by ganeshrevanth123** [comment]
Hi team, 

I need small help from you. I am learning Docker from your documentation. Now I am learning build image from PYTHON application. I build the image using Dockerfile. In the next module(run containers), I am unable to run the image using container. I have attached the screenshot of the error here. 
![DockerError](https://user-images.githubusercontent.com/74895811/182847702-1746e565-4506-49ec-a8a7-6a179c290b67.PNG)

Team, kindly help in this. 

Thanks and Regards,
Ganesh Revanth

**Comment by craig-osterhout** [comment]
Hi @ganeshrevanth123, thanks for sharing the issue. For support and troubleshooting, please try the forums or Slack. If you find any issues in the docs, please create an issue in this repo.
- https://dockercommunity.slack.com/
- https://forums.docker.com/

Please try the above resources for support. A few quick things to check/include, are:
 - In [test the application](https://docs.docker.com/language/python/build-images/#test-the-application), does the app run outside of the container?
 - Copy and paste the commands to ensure there is no typo. For example, check the capitalization of Flask and flask. It also helps if you include the contents of your Dockerfile, requirements, and py source file for others to troubleshoot.
