### ISSUE TITLE
[Java docs feedback]

### ISSUE THREAD

**Issue by JTBJ** [docker/docker.github.io#15376]
location: Dockerfile
reference: docker documentation (Java section)
documentation url: [https://docs.docker.com/language/java/build-images/](url)
problem: `RUN ./mvnw dependency:resolve`
error: 
```
ERROR [5/6] RUN ["./mvnw dependency:resolve"]                                                                                                                                     0.9s
 > [5/6] RUN ["./mvnw dependency:resolve"]:
#15 0.836 runc run failed: unable to start container process: exec: "./mvnw dependency:resolve": stat ./mvnw dependency:resolve: no such file or directory
executor failed running [./mvnw dependency:resolve]: exit code: 1
```

The problem is with a command provided in the Java section of the Docker documentation. When I attempt to run ` docker build --tag java-docker .` from the command line, I get the above error. The error corresponds to the RUN entry in the Dockerfile.

**Comment by craig-osterhout** [comment]
Hi @JTBJ, it looks like no details were added to the feedback. If there is an issue in the docs, please provide more details.
