### ISSUE TITLE
Add example of "docker stack deploy"

### ISSUE THREAD

**Issue by marikaris** [docker/docker.github.io#1538]
File: [engine/getstarted-voting-app/index.md](https://docs.docker.com/engine/getstarted-voting-app/)

I really need an example of docker stack deploy, using the command, I keep getting messages that I am doing it wrong but I do not know how to use this command properly. 
It is not a logical next step after the getting started tutorial, it gives way too much information and not enough examples.

**Comment by bdwill** [comment]
dibs for hackathon

**Comment by bdwill** [comment]
I feel that the actual deploy command doesn't need to be included here as it is an overview document and the full ``` deploy ``` command is illustrated in [/engine/getstarted-voting-app/deploy-app](https://docs.docker.com/engine/getstarted-voting-app/deploy-app). 

@marikaris take a look there and you should be good to go!

**Comment by johndmulhausen** [comment]
Sorry, but this topic no longer exists.
