### ISSUE TITLE
Wrong content under Communicate between a container and a swarm service

### ISSUE THREAD

**Issue by amaranand** [docker/docker.github.io#15384]
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)

Under section, Communicate between a container and a swarm service

The details show only communication among containers in a bridge network and does not show communication of container to Service (overlay network), please check. thanks !

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/docker.github.io/issues/8387
