### ISSUE TITLE
Missing '"experimental": true' in daemon.json listing in docerd.md

### ISSUE THREAD

**Issue by afolarin** [docker/docker.github.io#1539]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

"experimental" option missing on /etc/docker/daemon.json

**Comment by mstanleyjones** [comment]
The file in question is in the `docker/docker/` repo under `docs/reference/commandline/dockerd.md` so the pull request needs to be made there, not in this repo.

**Comment by jadametz** [comment]
@johndmulhausen Happy to take this on if it's still an issue, but as far as I can tell, this has been previously resolved.

**Comment by mstanleyjones** [comment]
Thanks @jadametz
