### ISSUE TITLE
Docker for Windows, add Windows container example to docs

### ISSUE THREAD

**Issue by londoncalling** [docker/docker.github.io#154]
See Slack comment in #microsoft-discuss: https://docker.slack.com/archives/microsoft-discuss/p1476140921001755

Create an example of using Windows containters in https://docs.docker.com/docker-for-windows/

Work on with @friism and/or @rneugeba

**Comment by friism** [comment]
@londoncalling I think the best prototype content we have for this is this blog post: https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

**Comment by londoncalling** [comment]
@friism @ManoMarks will start this in next day or two, and leverage the blog referenced above and figure out how to incorporate, support, or link to what you guys have started in: https://github.com/docker/labs/tree/master/windows/windows-containers

**Comment by londoncalling** [comment]
This issue was addressed by linking to the blog post 
[BUILD AND RUN YOUR FIRST DOCKER WINDOWS SERVER CONTAINER](https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/), along with other resources under a subtopic [**here**](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers) on Getting started with Windows containers. 

(See also referenced PR's ^^ in this issue)
