### ISSUE TITLE
[Java docs feedback]

### ISSUE THREAD

**Issue by gaoagong** [docker/docker.github.io#15419]
### Problem description
Page has the text "To remove a container, simple run the..".

### Problem location
- I saw a problem at the following URL: https://docs.docker.com/language/java/run-containers/

### Project version(s) affected
Just documentation. Not sure if it effects different versions.

### Suggestions for a fix
I believe the desired sentence should be "To remove a container, simply run the...".
Use "simply" instead of "simple".

**Comment by craig-osterhout** [comment]
Fixed by https://github.com/docker/docker.github.io/pull/15420
