### ISSUE TITLE
curl downloaded script file is 404 

### ISSUE THREAD

**Issue by ChapmanCheng** [docker/docker.github.io#15411]
File: [compose/completion.md](https://docs.docker.com/compose/completion/)

the completion script file downloaded by curl on this page is not found, plz fix

**Comment by dockertopia** [comment]
Hi @ChapmanCheng, thanks for raising this. Both this feature and page is not available at the moment. It might be recovered in the near future, at which point we will revisit any scripts available for download. For more details, see https://github.com/docker/docker.github.io/pull/15444.
