### ISSUE TITLE
Feedback for: engine/reference/commandline/stats.md

### ISSUE THREAD

**Issue by r3m0t** [docker/docker.github.io#1541]
File: [engine/reference/commandline/stats.md](https://docs.docker.com/engine/reference/commandline/stats/)

I don't understand the correspondence between the headers NET I/O BLOCK I/O and the stats listed here: https://docs.docker.com/engine/admin/runmetrics/

**Comment by mstanleyjones** [comment]
The `NET I/O` and `BLOCK I/O` refer to the amount of data moved in and out of the container on block devices and the network.
