### ISSUE TITLE
problem: container in container

### ISSUE THREAD

**Issue by bangzhuzhu** [docker/docker.github.io#15427]
### Problem description
1. I use k3d to build 2 agent nodes (which means 2 containers (work0, work1) in docker)
![image](https://user-images.githubusercontent.com/111118214/185569634-65c75ea7-1c4a-4a79-b651-f3ac252ec970.png)

2. deploy nginx, I find that the nginx run in the container work0 with some new containers.
![image](https://user-images.githubusercontent.com/111118214/185569709-f9eaa6e5-b2d6-42dd-993a-fbd5f4f63045.png)

Does such way (containers in container) have any side effect and why?
Thank you

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Is there a particular place in the documentation where you would expect to find the information?

For information about container in container, you can check the information in the docker in docker image https://hub.docker.com/_/docker.
Particularly, the link to https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/.

**Comment by craig-osterhout** [comment]
Closing this as stale. If you'd like to contribute to the docs, please let us know more details about your expectations. If you're looking for more info, please try the Community Slack at https://join.slack.com/t/dockercommunity/shared_invite/zt-1fukl8thi-Iq2rTGyJGMAkCeQKuyfWIA
