### ISSUE TITLE
unable to run "mvnw spring-boot:run" during docker build. Error:  /bin/sh: 1: ./mvnw: not found

### ISSUE THREAD

**Issue by sreedhark1243** [docker/docker.github.io#15430]
File: [storage/storagedriver/index.md](https://docs.docker.com/storage/storagedriver/)

From https://docs.docker.com/language/java/build-images/ page, while I was trying to build the image on my windows 11 machine, its was throwing me Error:  /bin/sh: 1: ./mvnw: not found. This is specifically while "RUN mvnw spring-boot:run". It required to be changed to below for the fix. We need to add "RUN apt-get update && apt-get install dos2unix" and "RUN dos2unix mvnw".

# syntax=docker/dockerfile:1

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./

COPY src ./src

RUN apt-get update && apt-get install dos2unix

RUN dos2unix mvnw

RUN ./mvnw dependency:resolve

CMD ["./mvnw", "spring-boot:run"]

**Comment by dvdksn** [comment]
Hi @sreedhark1243, thanks for reaching out. If you are using Windows, we recommend that you change line endings to Unix-style in your script file before adding them to your container.

See [troubleshooting topics for Windows](https://docs.docker.com/desktop/troubleshoot/topics/#avoid-unexpected-syntax-errors-use-unix-style-line-endings-for-files-in-containers) for more information.
