### ISSUE TITLE
404 at /get-involved/

### ISSUE THREAD

**Issue by jdanderson2** [docker/docker.github.io#15441]
I found a broken link : https://docs.docker.com/get-involved/
I arrived on this page through: https://docker.github.io/

**Comment by dvdksn** [comment]
Hi @jdanderson2, I can't seem to find the broken link on the page that you've included here in this ticket. Could you share where exactly you found it?

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still exists, please provide more details.
To get involved with the community, please join the [Community Slack](https://join.slack.com/t/dockercommunity/shared_invite/zt-1fukl8thi-Iq2rTGyJGMAkCeQKuyfWIA) and take a look at https://www.docker.com/community/.
