### ISSUE TITLE
Feedback for: engine/api/v1.19.md

### ISSUE THREAD

**Issue by hc000** [docker/docker.github.io#1546]
File: [engine/api/v1.19.md](https://docs.docker.com/engine/api/v1.19/)
would be nice if the breaking changes are listed somewhere for each new versions

**Comment by mstanleyjones** [comment]
I believe the APIs always maintain backward compatibility. We are very careful about that. @thaJeztah is there anything more to add here?

**Comment by thaJeztah** [comment]
The API is versioned, so if you stick to a specific version (e.g., v1.19 or v1.20), no changes should be present; changes between versions are documented in the API version history; https://docs.docker.com/engine/api/version-history/

If you _do_ find a breaking change / change in behavior in a versioned API endpoint, please open an issue in the docker/docker issue tracker (https://github.com/docker/docker/issues
