### ISSUE TITLE
docker repo link for rhel 8 does not work

### ISSUE THREAD

**Issue by ameenab** [docker/docker.github.io#15463]
File: [engine/install/rhel.md](https://docs.docker.com/engine/install/rhel/)

The docker repo configured for rhel 8 using "yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo" does not work . link do not exist

**Comment by thaJeztah** [comment]
The file does exist; does it not download for you?

What architecture are you running on? We currently only provide RHEL packages for s390x and ppc64le; for other architectures you can install the CentOS packages, which should be compatible with RHEL; see the note at the top of the installation page; https://docs.docker.com/engine/install/rhel/#prerequisites

<img width="1005" alt="Screenshot 2022-08-28 at 19 45 04" src="https://user-images.githubusercontent.com/1804568/187087680-9ad8f851-40b9-405e-bed0-79fec22ec4ef.png">

**Comment by usha-mandya** [comment]
Closing as stale. Please reopen the issue with more information if the issue still persists.
