### ISSUE TITLE
404 at /compose/compose-file/compse-file

### ISSUE THREAD

**Issue by wutongsh** [docker/docker.github.io#15471]
I found a broken link : https://docs.docker.com/compose/compose-file/compse-file-v3

**Comment by craig-osterhout** [comment]
@wutongsh, thanks for reporting the issue. Where did you find this link?

The link you're looking for is probably https://docs.docker.com/compose/compose-file/compose-file-v3/

**Comment by craig-osterhout** [comment]
Closing as stale. If the broken link still exists, please share more details about the source.
