### ISSUE TITLE
Typo: "redploy"

### ISSUE THREAD

**Issue by phs** [docker/docker.github.io#1548]
File: [engine/getstarted-voting-app/test-drive.md](https://docs.docker.com/engine/getstarted-voting-app/test-drive/)

> In the next steps, we’ll customize the app and _redploy_ it.

**Comment by scjane** [comment]
#dibs

**Comment by scjane** [comment]
The typo does not exist now, so this issue can be closed.
![redeploy](https://cloud.githubusercontent.com/assets/25146885/25084713/9a810dc6-2390-11e7-8524-19d7aaa48438.jpg)
