### ISSUE TITLE
Feedback for: engine/reference/commandline/attach.md

### ISSUE THREAD

**Issue by bseib** [docker/docker.github.io#1550]
What does `docker attach` actually do? I don't know how to interpret the word "attach" in the given description:

![image](https://cloud.githubusercontent.com/assets/1313561/22716836/bcb73112-ed3b-11e6-8c07-8983057973f5.png)

So does `attach` give me a shell? Or does it tap into the stdout of the container? I don't know by this page's description.

File: [engine/reference/commandline/attach.md](https://docs.docker.com/engine/reference/commandline/attach/)

**Comment by mstanleyjones** [comment]
It connects your terminal's standard input, standard output, and standard error to the container, so that you can interact with the container using your keyboard and terminal display.

**Comment by bseib** [comment]
That one sentence would be *worth gold* right beneath Description. Currently it just says "Attach to a running container". Well, I could have guessed *that* much! :-)

![image](https://cloud.githubusercontent.com/assets/1313561/24566491/6a02cd22-15f5-11e7-999c-532a4a3a9909.png)

Putting your one sentence in that spot would work way better!  :-) It would help out a new docker person (like me) reading what all the docker commands can do. It also frames the context of the entire page -- re-reading that page with your one sentence description as context makes all of it make much more sense.

**Comment by mstanleyjones** [comment]
See https://github.com/docker/docker/pull/32282 :)

**Comment by bseib** [comment]
I'm so glad you guys have this user feedback process baked into your documentation. It will make you win.

Also. the bat is awesome.

**Comment by mstanleyjones** [comment]
The `docker/docker` project has a tradition about those animals, and someone made https://twitter.com/DockerCuties based on that. :)
