### ISSUE TITLE
Small typo in Wordpress docs.

### ISSUE THREAD

**Issue by TurboWindX** [docker/docker.github.io#15523]
File: [samples/wordpress.md](https://docs.docker.com/samples/wordpress/)

**https://docs.docker.com/samples/wordpress/#define-the-project**
The .yml docker-file config stipulates port 80 as such:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80

**https://docs.docker.com/samples/wordpress/#bring-up-wordpress-in-a-web-browser**
But later on, it tells us that is on port 8000:

At this point, WordPress should be running **on port 8000** of your Docker Host, and you can complete the “famous five-minute installation” as a WordPress administrator.
Note: The WordPress site is not immediately available **on port 8000** because the containers are still being initialized and may take a couple of minutes before the first load.
If you are using Docker Desktop for Mac or Docker Desktop for Windows, you can use http://localhost as the IP address, **and open http://localhost:8000** in a web browser.

Not a big deal at all but it might just be a bit confusing for a beginner trying to put all the pieces together !

**Comment by NitishKumar06** [comment]
Thank you @TurboWindX for this issue. I've raised the PR for it. The default port for Wordpress is 80.
