### ISSUE TITLE
Questions about the way we run sshd and apache in the "Using Supervisord" example

### ISSUE THREAD

**Issue by helgein** [docker/docker.github.io#1554]
File: [engine/admin/using_supervisord.md](https://docs.docker.com/engine/admin/using_supervisord/)

- Why are sshd and apache running in foreground ?
- How is that setup different from running multiple processes from a bash script, each line terminated with an "&" ?
- How is that setup different from running sshd as a daemon and apache in the foreground ?
- Above simple solutions allow to run multiple processes without supervisor.

So, what is the point of supervisor here ?

The important thing of a process manager - respawning (after honoring an interval) after a process crashed - is not mentioned.
`docker run --restart` does that also - but for the container, not for individual processes in the container.
Redirection of stdout and stderr to files seem to be advantages too.

A link to http://supervisord.org/introduction.html#features
would be helpful as well.

**Comment by mstanleyjones** [comment]
This whole topic has been rewritten and this issue  is no longer applicable.
