### ISSUE TITLE
404 at /install/linux/docker/ubuntu/set-up-the-ropository

### ISSUE THREAD

**Issue by kishortalari** [docker/docker.github.io#15559]
I found a broken link : https://docs.docker.com/install/linux/docker/ubuntu/set-up-the-ropository

**Comment by kishortalari** [comment]
please get me this

**Comment by usha-mandya** [comment]
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

Here's the right link - https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository

**Comment by craig-osterhout** [comment]
Closing as stale.
