### ISSUE TITLE
404 at /products/docker-desktop

### ISSUE THREAD

**Issue by ysykk** [docker/docker.github.io#15550]
I found a broken link : https://docs.docker.com/products/docker-desktop

**Comment by craig-osterhout** [comment]
@ysykk, thanks for sharing the issue. Where did you find this broken link?

It looks very similar to https://www.docker.com/products/docker-desktop/
You can find the Docker Desktop docs at https://docs.docker.com/desktop/

**Comment by craig-osterhout** [comment]
Closing as stale.
