### ISSUE TITLE
Feedback for: engine/reference/commandline/tag.md

### ISSUE THREAD

**Issue by samprog1** [docker/docker.github.io#1556]
File: [engine/reference/commandline/tag.md](https://docs.docker.com/engine/reference/commandline/tag/)

Please add the registry-parameter to the doc, best as additional option. Also a reference for docker best practices with the repository added before the imagename

USAGE:
docker tag SOURCE_IMAGE[:TAG] REPO/TARGET_IMAGE[:TAG]

To push an image to another registry than DockerHub, you'd have to add
[REGISTRY:PORT/]REPO/TARGET_IMAGE[:TAG]

**Comment by mstanleyjones** [comment]
The usage instructions in this document are programmatically pulled straight from the Cobra specification in the Docker code, and match the output of `docker tag --help`. Please raise this issue [there](https://github.com/docker/docker) if you feel that the usage instructions for `docker tag` need to be enhanced.
