### ISSUE TITLE
Explain why the db and visualizer need to be constrained onto the manager node

### ISSUE THREAD

**Issue by markhowells** [docker/docker.github.io#1558]
File: [engine/getstarted-voting-app/test-drive.md](https://docs.docker.com/engine/getstarted-voting-app/test-drive/)
There's an explanation of the constraint placed on the db and vizualizer services - in so far as the mechanism is explained. However, there's no explanation as to _why_ the db and vizualizer need to be contrained onto the managter node. It would be helpful if the text gave a brief explanation of that.

**Comment by johndmulhausen** [comment]
This topic no longer exists.
