### ISSUE TITLE
Broken Links to access the documentation guide

### ISSUE THREAD

**Issue by NitishKumar06** [docker/docker.github.io#15586]
### Problem:

The following link (https://github.com/docker/docker.github.io/blob/master/contribute/overview.md) contains various links such as [Contribution guideline](https://github.com/docker/docker.github.io/blob/master/contribute/overview.md#contribution-guidelines-), [Grammar guide](https://github.com/docker/docker.github.io/blob/master/contribute/overview.md#grammar-guide) and 4 more such useful links which are broken.

### Solution: 

Fix those broken links

**Comment by vedant-kakde** [comment]
Hey @NitishKumar06 , I'd like to work on this issue.

**Comment by usha-mandya** [comment]
@NitishKumar06 The Docs contribution guidelines are meant to be used as HTML pages on the Docs site - https://docs.docker.com/contribute/overview/. Please take a look and let us know if you still spot any broken links there.

**Comment by NitishKumar06** [comment]
@usha-mandya If that's the case, I'd like to bring one suggestion :

In the following link (https://github.com/docker/docker.github.io#contribute-to-docker-docs) especially the **Contribute to Docker docs** , there's a link which mentions [Contribute Section](https://github.com/docker/docker.github.io/blob/master/contribute/overview.md) which redirects the user to [here](https://github.com/docker/docker.github.io/blob/master/contribute/overview.md). Would it be a good idea to link _Contribute Section_ to directly [here](https://docs.docker.com/contribute/overview/)? WDYT?

**Comment by usha-mandya** [comment]
@NitishKumar06 Agree

**Comment by NitishKumar06** [comment]
@usha-mandya I'd like to work on this issue. Can you assign it to me?

**Comment by usha-mandya** [comment]
@NitishKumar06 Feel free to create a PR and reference this issue in the PR.

**Comment by NitishKumar06** [comment]
@usha-mandya Alright! I'm working on this issue.

**Comment by NitishKumar06** [comment]
@usha-mandya Kindly review this PR: https://github.com/docker/docker.github.io/pull/15605
