### ISSUE TITLE
Cannot create a new Dev Environment from existing GitHub repo. Key fingerprint causes hanging.

### ISSUE THREAD

**Issue by J0hn3ch** [docker/docker.github.io#15598]
Hello Docker Community!
### Problem description
I tried to create a new Dev Environment from Docker Desktop in Windows 11 using WSL2. When I select _compose based dev environment_ from Docker Desktop and select my existing git repo, the log shell ask for a confirmation of the unknown host github.com and wait for the answer, but it is not possible to interact with it, so it causes hanging in creating the Dev Environment.

![Immagine 2022-09-07 231034](https://user-images.githubusercontent.com/37618867/188994071-5c928181-d10a-44d1-9099-4d9f6a75797c.png)

### Problem location

- I follow the example in this page: https://docs.docker.com/desktop/dev-environments/

- Other: Instead of https://github.com/dockersamples/single-dev-env.git, I use my own empty repository.

### Project version(s) affected
Docker Desktop v4.11.1

**Comment by craig-osterhout** [comment]
HI @J0hn3ch, thanks for sharing the issue.
Please help create an issue at https://github.com/docker/dev-environments/issues

There are few related issues, you can check if any of the solutions work for you.
https://github.com/docker/dev-environments/issues?q=is%3Aissue+fingerprint+is%3Aclosed
