### ISSUE TITLE
`docker-ce` is not available, and I can't install as recommended

### ISSUE THREAD

**Issue by carpben** [docker/docker.github.io#15593]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

I ran the command ` sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin` as instructed and got the following message: 
```console
➜  duda sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Unable to locate package docker-ce-cli
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
E: Unable to locate package docker-compose-plugin
```

**Comment by thaJeztah** [comment]
What version of ubuntu are you running? 

Did you install the package-repository, as outlined in these first steps? https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

**Comment by carpben** [comment]
You are right @thaJeztah. I misread the instructions. Thanks.
