### ISSUE TITLE
404 at /go/guides/PS

### ISSUE THREAD

**Issue by 6010513061** [docker/docker.github.io#15599]
I found a broken link : https://docs.docker.com/go/guides/PS

**Comment by thaJeztah** [comment]
Can you tell us where you found this link?

Did you perhaps copy this link from the commmandline? I suspect you may have copied your shell's prompt (`PS>`)

The URL you're looking for is https://docs.docker.com/go/guides/

**Comment by craig-osterhout** [comment]
Closing as stale.
