### ISSUE TITLE
Syntax highlighting issues in code blocks

### ISSUE THREAD

**Issue by lgpawel** [docker/docker.github.io#1559]
File: [engine/getstarted-voting-app/node-setup.md](https://docs.docker.com/engine/getstarted-voting-app/node-setup/)

In code snippets, lines like
```
docker-machine create --driver virtualbox <HOSTNAME>
```
or
```
manager   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.13.0-rc6
```
appear as partially commented out in the syntax highlighting due to `--` and `//`. This is clearly not intended and may be confusing.

**Comment by johndmulhausen** [comment]
The solution is to change the triple backticks around the coding blocks so that they have the `none` label directly afterwards, e.g.

```none
```none
code {
  code code...
}
```

**Comment by scjane** [comment]
#dibs

**Comment by scjane** [comment]
The page related to this issue has been reorganized, and the code that displays incorrectly as described does not exist now. Perhaps someone has fixed this in his or her PR. This issue can be closed.
