### ISSUE TITLE
404 at /examples/running_redis_service/

### ISSUE THREAD

**Issue by samarth-ty** [docker/docker.github.io#15611]
I found a broken link : https://docs.docker.com/examples/running_redis_service/
I arrived on this page through: https://stackoverflow.com/

**Comment by akankshakumari393** [comment]
Could you please share the correct link, like where did you get the broken link from?

**Comment by aevesdocker** [comment]
Thanks for reporting the broken link. Please report this issue on the source page where the link is located.
