### ISSUE TITLE
Remove cautious language about 'overlay' storage driver: engine/userguide/storagedriver/overlayfs-driver/ & engine/userguide/storagedriver/selectadriver/

### ISSUE THREAD

**Issue by stefanlasiewski** [docker/docker.github.io#1564]
From what I see in Docker 1.13.x, the Overlay storage driver is now the default storage driver for EL7 systems. I'm right the middle of re-evaluating some of our storage, and so I was confused between the idea that OverlayFS is now the default and the cautious language used to describe OverlayFS in the Docker Docs. I suggest a couple of changes.

If OverlayFS actually is stable, then the following language should probably be changed in a couple Docker documents. They imply that OverlayFS is unstable and shouldn't be used in Production.

File: [engine/userguide/storagedriver/overlayfs-driver/](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/)

> As promising as OverlayFS is, it is still relatively young. Therefore caution should be taken before using it in production Docker environments.

File: [engine/userguide/storagedriver/selectadriver/](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/)

> Many people consider OverlayFS as the future of the Docker storage driver. However, it is less mature, and potentially less stable than some of the more mature drivers such as aufs and devicemapper. For this reason, you should use the OverlayFS driver with caution and expect to encounter more bugs and nuances than if you were using a more mature driver.

**Comment by mstanleyjones** [comment]
@aaronlehmann @nishanttotla can you confirm this is an OK change?

**Comment by aaronlehmann** [comment]
punting to @dmcgowan @cpuguy83

**Comment by cpuguy83** [comment]
I think this language is suitable.
Note that the default devicemapper setup is not suitable for production either.

**Comment by mstanleyjones** [comment]
Thanks for weighing in, @cpuguy83
