### ISSUE TITLE
404 at /engine/reference/commandline/attach/)

### ISSUE THREAD

**Issue by deniskorotaevsky** [docker/docker.github.io#15655]
I found a broken link : https://docs.docker.com/engine/reference/commandline/attach/)
I arrived on this page through: https://hh.ru/

**Comment by craig-osterhout** [comment]
Hi @deniskorotaevsky, thanks for sharing the issue.
It looks like there's a round bracket `)` on the end. The correct link is https://docs.docker.com/engine/reference/commandline/attach/
As this link is from an external site, please inform the maintainers of hh.ru of the issue.
