### ISSUE TITLE
Missing wordpress_data volume 

### ISSUE THREAD

**Issue by MannyAdumbire** [docker/docker.github.io#15677]
File: [samples/wordpress.md](https://docs.docker.com/samples/wordpress/)

The guide mentions a wordpress_data volume, but no such volume is defined in the example docker-compose.yml section.

<img width="1402" alt="docker-sample-wp-missing-volume" src="https://user-images.githubusercontent.com/4621391/190836601-0829bbb1-9934-4ed4-8c6b-8d68e4fb072c.png">

**Comment by craig-osterhout** [comment]
Fixed by #15680
