### ISSUE TITLE
Windows Download link for "Docker Desktop Community 2.5.0.1" not working

### ISSUE THREAD

**Issue by StrnadJan** [docker/docker.github.io#15674]
### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by StrnadJan** [comment]
https://docs.docker.com/desktop/previous-versions/2.x-windows/

**Comment by usha-mandya** [comment]
@StrnadJan Thanks for reporting the broken links issue. We have PR to fix this issue.
