### ISSUE TITLE
Trying to execute the container build, but there are errors running the dockerfile

### ISSUE THREAD

**Issue by olivertech** [docker/docker.github.io#15673]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

I am trying to execute the tutorial, bur in charpter 2, I got an error running this dockerfile:

# syntax=docker/dockerfile:1
FROM node:12-alpine
RUN apk add --no-cache python2 g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 3000

**Result:**

[+] Building 11.5s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s 
 => => transferring dockerfile: 227B                                                                                                                                                                   0.0s 
 => [internal] load .dockerignore                                                                                                                                                                      0.0s 
 => => transferring context: 2B                                                                                                                                                                        0.0s 
 => resolve image config for docker.io/docker/dockerfile:1                                                                                                                                             1.8s 
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc                                                                        0.0s 
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s 
 => [internal] load .dockerignore                                                                                                                                                                      0.0s 
 => [internal] load metadata for docker.io/library/node:12-alpine                                                                                                                                      0.0s 
 => CACHED [1/5] FROM docker.io/library/node:12-alpine                                                                                                                                                 0.0s 
 => [internal] load build context                                                                                                                                                                      0.0s 
 => => transferring context: 2.69kB                                                                                                                                                                    0.0s 
 => [2/5] RUN apk add --no-cache python2 g++ make                                                                                                                                                      8.2s 
 => [3/5] WORKDIR /app                                                                                                                                                                                 0.0s 
 => [4/5] COPY . .                                                                                                                                                                                     0.0s 
 => ERROR [5/5] RUN yarn install --production                                                                                                                                                          1.2s 
------
 > [5/5] RUN yarn install --production:
#13 0.606 yarn install v1.22.18
#13 0.681 [1/4] Resolving packages...
#13 0.762 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
#13 0.767 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
#13 0.961 [2/4] Fetching packages...
#13 1.151 error An unexpected error occurred: "https://registry.yarnpkg.com/content-disposition/-/content-disposition-0.5.3.tgz: self signed certificate in certificate chain".
#13 1.151 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
#13 1.151 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install --production]: exit code: 1

After searching stackoverflow, I got some tips, and the dockerfile becomes this:

# syntax=docker/dockerfile:1
FROM node:12-alpine
RUN apk add --no-cache python2 g++ make
WORKDIR /app
COPY . .
**RUN yarn config set "strict-ssl" false -g**
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 3000

**Result**

[+] Building 13.6s (14/14) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s 
 => => transferring dockerfile: 270B                                                                                                                                                                   0.0s 
 => [internal] load .dockerignore                                                                                                                                                                      0.0s 
 => => transferring context: 2B                                                                                                                                                                        0.0s 
 => resolve image config for docker.io/docker/dockerfile:1                                                                                                                                             0.8s 
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc                                                                        0.0s 
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s 
 => [internal] load .dockerignore                                                                                                                                                                      0.0s 
 => [internal] load metadata for docker.io/library/node:12-alpine                                                                                                                                      0.0s 
 => [1/6] FROM docker.io/library/node:12-alpine                                                                                                                                                        0.0s 
 => [internal] load build context                                                                                                                                                                      0.0s 
 => => transferring context: 2.73kB                                                                                                                                                                    0.0s 
 => CACHED [2/6] RUN apk add --no-cache python2 g++ make                                                                                                                                               0.0s 
 => CACHED [3/6] WORKDIR /app                                                                                                                                                                          0.0s 
 => [4/6] COPY . .                                                                                                                                                                                     0.0s 
 => [5/6] RUN yarn config set "strict-ssl" false -g                                                                                                                                                    0.5s 
 => ERROR [6/6] RUN yarn install --production                                                                                                                                                         12.1s 
------
 > [6/6] RUN yarn install --production:
#14 0.442 yarn install v1.22.18
#14 0.532 [1/4] Resolving packages...
#14 0.603 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
#14 0.612 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
#14 0.804 [2/4] Fetching packages...
#14 9.554 [3/4] Linking dependencies...
#14 10.45 [4/4] Building fresh packages...
#14 12.04 error /app/node_modules/sqlite3: Command failed.
#14 12.04 Exit code: 1
#14 12.04 Command: node-pre-gyp install --fallback-to-build
#14 12.04 Arguments:
#14 12.04 Directory: /app/node_modules/sqlite3
#14 12.04 Output:
#14 12.04 node-pre-gyp info it worked if it ends with ok
#14 12.04 node-pre-gyp info using node-pre-gyp@0.11.0
#14 12.04 node-pre-gyp info using node@12.22.12 | linux | x64
#14 12.04 node-pre-gyp WARN Using request for node-pre-gyp https download
#14 12.04 node-pre-gyp info check checked for "/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" (not found)
#14 12.04 node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-x64.tar.gz
#14 12.04 node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.2 and node@12.22.12 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
#14 12.04 node-pre-gyp WARN Hit error self signed certificate in certificate chain
#14 12.04 gyp info it worked if it ends with ok
#14 12.04 gyp info using node-gyp@3.8.0
#14 12.04 gyp info using node@12.22.12 | linux | x64
#14 12.04 gyp info ok
#14 12.04 gyp info it worked if it ends with ok
#14 12.04 gyp info using node-gyp@3.8.0
#14 12.04 gyp info using node@12.22.12 | linux | x64
#14 12.04 gyp http GET https://unofficial-builds.nodejs.org/download/release/v12.22.12/node-v12.22.12-headers.tar.gz
#14 12.04 gyp WARN install got an error, rolling back install
#14 12.04 gyp ERR! configure error
#14 12.04 gyp ERR! stack Error: self signed certificate in certificate chain
#14 12.04 gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
#14 12.04 gyp ERR! stack     at TLSSocket.emit (events.js:314:20)
#14 12.04 gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:937:8)
#14 12.04 gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)
#14 12.04 gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
#14 12.04 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"#14 12.04 gyp ERR! cwd /app/node_modules/sqlite3
#14 12.04 gyp ERR! node -v v12.22.12
#14 12.04 gyp ERR! node-gyp -v v3.8.0
#14 12.04 gyp ERR! not ok
#14 12.04 node-pre-gyp ERR! build error
#14 12.04 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#14 12.04 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
#14 12.04 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
#14 12.04 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
#14 12.04 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
#14 12.04 node-pre-gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
#14 12.04 node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#14 12.04 node-pre-gyp ERR! cwd /app/node_modules/sqlite3
#14 12.04 node-pre-gyp ERR! node -v v12.22.12
#14 12.04 node-pre-gyp ERR! node-pre-gyp -v v0.11.0
#14 12.04 node-pre-gyp ERR! not ok
#14 12.04 Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#14 12.04 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install --production]: exit code: 1

And, finally, with more one change in dockerfile, becomes this:

# syntax=docker/dockerfile:1
FROM node:12-alpine
RUN apk add --no-cache python2 g++ make
WORKDIR /app
COPY . .
**RUN yarn config set "strict-ssl" false -g
RUN sh -c "yarn install --production"** 
CMD ["node", "src/index.js"]
EXPOSE 3000

**Result**

[+] Building 14.1s (14/14) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s 
 => => transferring dockerfile: 32B                                                                                                                                                                    0.0s 
 => [internal] load .dockerignore                                                                                                                                                                      0.0s 
 => => transferring context: 2B                                                                                                                                                                        0.0s 
 => resolve image config for docker.io/docker/dockerfile:1                                                                                                                                             0.9s 
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc                                                                        0.0s 
 => [internal] load .dockerignore                                                                                                                                                                      0.0s 
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s 
 => [internal] load metadata for docker.io/library/node:12-alpine                                                                                                                                      0.0s 
 => [1/6] FROM docker.io/library/node:12-alpine                                                                                                                                                        0.0s 
 => [internal] load build context                                                                                                                                                                      0.0s 
 => => transferring context: 2.49kB                                                                                                                                                                    0.0s 
 => CACHED [2/6] RUN apk add --no-cache python2 g++ make                                                                                                                                               0.0s 
 => CACHED [3/6] WORKDIR /app                                                                                                                                                                          0.0s 
 => CACHED [4/6] COPY . .                                                                                                                                                                              0.0s 
 => CACHED [5/6] RUN yarn config set "strict-ssl" false -g                                                                                                                                             0.0s 
 => ERROR [6/6] RUN sh -c "yarn install --production"                                                                                                                                                 13.0s 
------
 > [6/6] RUN sh -c "yarn install --production":
#14 0.345 yarn install v1.22.18
#14 0.417 [1/4] Resolving packages...
#14 0.517 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
#14 0.522 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
#14 0.697 [2/4] Fetching packages...
#14 10.67 [3/4] Linking dependencies...
#14 11.39 [4/4] Building fresh packages...
#14 12.92 error /app/node_modules/sqlite3: Command failed.
#14 12.92 Exit code: 1
#14 12.92 Command: node-pre-gyp install --fallback-to-build
#14 12.92 Arguments:
#14 12.92 Directory: /app/node_modules/sqlite3
#14 12.92 Output:
#14 12.92 node-pre-gyp info it worked if it ends with ok
#14 12.92 node-pre-gyp info using node-pre-gyp@0.11.0
#14 12.92 node-pre-gyp info using node@12.22.12 | linux | x64
#14 12.92 node-pre-gyp WARN Using request for node-pre-gyp https download
#14 12.92 node-pre-gyp info check checked for "/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" (not found)
#14 12.92 node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-x64.tar.gz
#14 12.92 node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.2 and node@12.22.12 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
#14 12.92 node-pre-gyp WARN Hit error self signed certificate in certificate chain
#14 12.92 gyp info it worked if it ends with ok
#14 12.92 gyp info using node-gyp@3.8.0
#14 12.92 gyp info using node@12.22.12 | linux | x64
#14 12.92 gyp info ok
#14 12.92 gyp info it worked if it ends with ok
#14 12.92 gyp info using node-gyp@3.8.0
#14 12.92 gyp info using node@12.22.12 | linux | x64
#14 12.92 gyp http GET https://unofficial-builds.nodejs.org/download/release/v12.22.12/node-v12.22.12-headers.tar.gz
#14 12.92 gyp WARN install got an error, rolling back install
#14 12.92 gyp ERR! configure error
#14 12.92 gyp ERR! stack Error: self signed certificate in certificate chain
#14 12.92 gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
#14 12.92 gyp ERR! stack     at TLSSocket.emit (events.js:314:20)
#14 12.92 gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:937:8)
#14 12.92 gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)
#14 12.92 gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
#14 12.92 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"#14 12.92 gyp ERR! cwd /app/node_modules/sqlite3
#14 12.92 gyp ERR! node -v v12.22.12
#14 12.92 gyp ERR! node-gyp -v v3.8.0
#14 12.92 gyp ERR! not ok
#14 12.92 node-pre-gyp ERR! build error 
#14 12.92 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#14 12.92 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
#14 12.92 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
#14 12.92 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
#14 12.92 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
#14 12.92 node-pre-gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
#14 12.92 node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#14 12.92 node-pre-gyp ERR! cwd /app/node_modules/sqlite3
#14 12.92 node-pre-gyp ERR! node -v v12.22.12
#14 12.92 node-pre-gyp ERR! node-pre-gyp -v v0.11.0
#14 12.92 node-pre-gyp ERR! not ok
#14 12.92 Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#14 12.93 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c sh -c "yarn install --production"]: exit code: 1

I am using this tutorial to learn Docker step by step, and I got an error already in the second lesson. That in my view, is an absurd.

How many years this tutorial in online ? How many professionals is there to update and check those kind of things ?

Well, I am trying to run this tutorial, in a Windows 10 machine, using Docker for Windows.

I will appreciate, have a solution to those errors... 

Thanks.
Marcelo.

**Comment by craig-osterhout** [comment]
@olivertech, thanks for sharing the issue. Are you behind a proxy or some other device modifying the certificate?

**Comment by craig-osterhout** [comment]
Closing as stale. If you need more support, please try the Community Slack, https://join.slack.com/t/dockercommunity/shared_invite/zt-1fukl8thi-Iq2rTGyJGMAkCeQKuyfWIA.
