### ISSUE TITLE
I wish there was a page about PHP

### ISSUE THREAD

**Issue by YannZeRookie** [docker/docker.github.io#15688]
File: [language/index.md](https://docs.docker.com/language/)

The https://hub.docker.com/_/php page is not enough for a beginner (like me). I wish there was something as detailed as the pages about Python. Thanks!

**Comment by craig-osterhout** [comment]
Hi @YannZeRookie, thanks for feedback. Closing as duplicate of #12719
If you have any specific questions about using the php image, please feel free to join the Docker Community Slack, https://join.slack.com/t/dockercommunity/shared_invite/zt-1fukl8thi-Iq2rTGyJGMAkCeQKuyfWIA
