### ISSUE TITLE
404 at /engine/installation/)

### ISSUE THREAD

**Issue by 9491241722** [docker/docker.github.io#15694]
I found a broken link : https://docs.docker.com/engine/installation/)

**Comment by craig-osterhout** [comment]
Hi @9491241722, thanks for sharing the issue. Where did you find this link?

It looks like there's an extra `)` at the end of the link.
The correct link is https://docs.docker.com/engine/installation/, which redirects to https://docs.docker.com/engine/install/

**Comment by craig-osterhout** [comment]
Closing as stale. If the source link is inside docs.docker.com, please let us know.
