### ISSUE TITLE
Clarify virtualbox on Windows

### ISSUE THREAD

**Issue by SachsenCoder** [docker/docker.github.io#1569]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

I highly recommend to mention in "Step 5: Update the application", that there is an issue with Virtualbox and shared folders on Windows.
That is, if you update the static content of "app.py", the redis-Server recognises the change and does restart, but you see still the old static content in the browser, after you refresh the page. (The counter, on the other hand, works and updates well!)
This issue is described in more detail here: https://www.virtualbox.org/ticket/14920

**Comment by mstanleyjones** [comment]
@londoncalling I think you might have addressed this already.

**Comment by londoncalling** [comment]
@SachsenCoder @mstanleyjones please check out the update per PR #2652 , I think this should cover it.

**Comment by londoncalling** [comment]
LGTM

**Comment by londoncalling** [comment]
LGTM

**Comment by londoncalling** [comment]
Thanks for the feedback @SachsenCoder. 

This is now addressed per the above PR ^^, which I just merged.
