### ISSUE TITLE
404 at /en/latest/examples/linking_into_redis/

### ISSUE THREAD

**Issue by cgourlay** [docker/docker.github.io#15704]
I found a broken link : https://docs.docker.com/en/latest/examples/linking_into_redis/

The reference to the URI above is made on the Docker Blog @ https://www.docker.com/blog/docker-0-6-5-links-container-naming-advanced-port-redirects-host-integration/ under the 'Examples' section

**Comment by craig-osterhout** [comment]
@cgourlay, thanks for sharing the issue and additional details.
It looks like the flag has been deprecated and the example has been removed. 
You can find more details about the flag and alternatives at https://docs.docker.com/network/links/

Closing this issue as the flag is deprecated and the blog is a very old snapshot in time.
