### ISSUE TITLE
Question about upgrading CSE from 1.12 to 1.13

### ISSUE THREAD

**Issue by bnewson-dunn** [docker/docker.github.io#1571]
File: [cs-engine/1.12/upgrade.md](https://docs.docker.com/cs-engine/1.12/upgrade/)

Change version from 1.12 to 1.13

Use these instructions to update APT-based systems.

Add the docker engine repository.
$ echo "deb https://packages.docker.com/1.13/apt/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list

**Comment by johndmulhausen** [comment]
Closing per triage discussion, @joaofnfernandes is going to file replacement bug.
