### ISSUE TITLE
Explain docker build parameters (as you do for docker run)

### ISSUE THREAD

**Issue by mthurston2020** [docker/docker.github.io#15738]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

Hi there, could you describe the command parameters in the step 6 (below) of the above page as you with bullet points before `docker run`
`docker build -t getting-started .`

**Comment by craig-osterhout** [comment]
Hi @mthurston2020, thanks for sharing the issue. Although it's possible to skip around to different parts of the tutorial, it's intended to be sequential. The build command is explained in a previous part of the tutorial. Please refer to https://docs.docker.com/get-started/02_our_app/#build-the-apps-container-image for more details about the build command.
