### ISSUE TITLE
404 at /desktop/previous-versions/archive-mac/undefined

### ISSUE THREAD

**Issue by haiweri** [docker/docker.github.io#15745]
I found a broken link : https://docs.docker.com/desktop/previous-versions/archive-mac/undefined
I arrived on this page through: https://docs.docker.com/desktop/previous-versions/archive-mac/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this ticket in favor of https://github.com/docker/docker.github.io/issues/13553, but if you're able to provide more details that could help us find the problem, feel free to comment on that ticket.

**Comment by haiweri** [comment]
yandex переводчик видать блокировал возможность скачать док выдовал ошибку шас на прямую все качается. ==============================Yandex translator apparently blocked the ability to download the dock gave an error shas directly everything swings.Сообщение, полученное 26 сент. 2022 г. в 23:02 от Craig Osterhout ***@***.***>:Thanks for sharing the issue. Closing this ticket in favor of #13553, but if you're able to provide more details that could help us find the problem, feel free to comment on that ticket.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
