### ISSUE TITLE
Document how to upgrade UCP from the UI

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1577]
Our current docs teach you how to upgrade from the CLI but don't tell you the easier way: the UI. Update the docs to give more relevant to the UI upgrade but also mention the CLI so that users can still script upgrades.

--- 
[You can find the current docs here](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/upgrade/)

**Comment by tombee** [comment]
#dibs
