### ISSUE TITLE
Docker push failed with unexpected HTTP status: 501 Not Implemented

### ISSUE THREAD

**Issue by harshana5** [docker/docker.github.io#158]
Hi,

I have been trying to figure this out for the last week and I am running out of options. So raising this as a last resort. Any insights appreciated

The issue
I have a private insecure registry on `registry:2` and I have exposed this to `0.0.0.0:80->5000/tcp` .  Then when I try to push a Image I'm getting the following exception

```
The push refers to a repository [XXXXX.XXX.XXX.co.nz:80/wyn-monitoring-elasticsearch]
2288ad7cdad5: Pushing [==================================================>] 2.406 MB
e9e4f296a748: Pushing [==================================================>] 940.1 kB
480e97baa728: Pushing [==================================================>] 238.4 kB
47bfd9e697e9: Retrying in 1 second
6d87f537561f: Retrying in 1 second
3db27154534e: Waiting
dd30060048da: Waiting
08f7fd848eff: Waiting
45f31a2ab382: Waiting
995c4aba0d9f: Waiting
a8f27d9ee463: Waiting
2d5a026b4fe9: Waiting
8934c1ccbcac: Waiting
bd28175e8656: Waiting
9d32d8190824: Waiting
7b190e778aad: Waiting
d0411e98f1d9: Waiting
3242004f198a: Waiting
b2ac5371e0f2: Waiting
142a601d9793: Waiting
received unexpected HTTP status: 501 Not Implemented
```
looking at the registry logs there is a post action

```
[11/Oct/2016:03:03:33 +0000] "POST /v2/wyn-monitoring-elasticsearch/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.12.1 go/go1.6.3 git-commit/23cf638 kernel/3.10.0-229.14.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"
```` 

Docker info

```

Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 64
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:2-28311872-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 32.21 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.14 GB
 Data Space Total: 107.4 GB
 Data Space Available: 106.2 GB
 Metadata Space Used: 4.018 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.52 GiB
Name: wynchcs257.wyn.cnw.co.nz
ID: MRSE:WF4H:3NJF:SHNB:YGY3:HBQK:C6EK:VICY:G4VI:ZK45:3RBU:XYOQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.xxxx.co.nz:8080/
Https Proxy: https://proxy.xxx.co.nz:8080/
No Proxy: localhost,127.0.0.0/8,docker-registry.somecorporation.com
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 xxxxxx.co.nz:80
 127.0.0.0/8

```

**Comment by mstanleyjones** [comment]
Hi, I am sorry you are running into trouble getting this going. Please don't give up. :) Please post your question on forums.docker.com, and include a bit more logging information, including the actual commands you typed to get this far. One thing I noticed is that you say your registry is on port 5000, but your `docker info` and `docker push` both show that the registry is on port 80.

Sorry to send you elsewhere, but this repository is for documentation issues, and not a general place to ask for help with Docker. Good luck!

**Comment by zoltan-fedor** [comment]
Hi @harshana5, have you ever figured this out?
I have the same issue now and the https://forums.docker.com has nothing about this and over there it seems nobody replies when issues are raised.
Thanks

**Comment by zoltan-fedor** [comment]
I have managed to solve this.

In case if anybody else stumbles upon this, this was an issue with proxies. Our nodes are behind an internet proxy, but the docker registry is not on the internet and it needed to be added to the noproxy list. Why docker was giving unhelpful 501 Not Implemented error and "invalid remote IP address "unknown"" errors on the server side was a bit misleading.

In the end looking at the golang code throwing the "invalid remote IP address "unknown"" error helped to identify that it is missing certain http headers which lead me to believe that something is interfering with the docker push, which is how I came to the proxy.

If you are on CentOS like us, you can set the proxy & noproxy at `/etc/systemd/system/docker.service.d/http-proxy.conf` with:
```
[Service]
Environment="HTTP_PROXY=http://[your proxy]:[port]/" "HTTPS_PROXY=http://[your proxy]:[port]/" "NO_PROXY=localhost,127.0.0.1,[your private docker registry]"
```
