### ISSUE TITLE
Explain how to use constraints in UCP

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1580]
DDC has docs that explain how to [apply labels to nodes ](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/configure/add-labels-to-cluster-nodes/). Now we need a user guide explaining how to leverage this and deploy a simple service that is scheduled on a node that meets certain criteria.

**Comment by jmaitrehenry** [comment]
I will start working on it
