### ISSUE TITLE
404 at /descktop/windons/instal/

### ISSUE THREAD

**Issue by EvilAlves** [docker/docker.github.io#15811]
I found a broken link : https://docs.docker.com/descktop/windons/instal/

**Comment by usha-mandya** [comment]
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by PMohanJ** [comment]
Hi, I've checked that link. There are some typos in his mentioned URL : https://docs.docker.com/descktop/windons/instal/.
He might've probably typed link incorrectly.
This is the actual URL : https://docs.docker.com/desktop/install/windows-install/

So you can close this issues I guess.
