### ISSUE TITLE
Feedback for: Documentation in general

### ISSUE THREAD

**Issue by Harrison-Uhl** [docker/docker.github.io#1583]
Please auto gen & provide PDF versions of the API docs.

The present HTML pages confuse my browser/printer (FireFox latest/ Brother on Win 8) and over write the side menu's on top of the first page(s).

I print manuals because I heavily annotate the hard copy over time as I learn on the fly.  (I also do this with preprinted reference books.)

Thanks
Harrison

**Comment by johndmulhausen** [comment]
Sorry, this isn't something we can do. :(

**Comment by Harrison-Uhl** [comment]
Hi:

Thanks.

Can you direct me to whom I should ask instead?

Harrison
