### ISSUE TITLE
Remove the UCP tarball link.

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#1593]
File: [datacenter/dtr/2.2/guides/admin/install/install-offline.md](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/install/install-offline/)

Remove the UCP tarball link.  That belongs in the UCP docs.

**Comment by joaofnfernandes** [comment]
Also see #1628

**Comment by johndmulhausen** [comment]
Per triage discussion, closing as this is an old docset. It is fixed in the newer docsets.
