### ISSUE TITLE
Multiple 404s from documentation pages

### ISSUE THREAD

**Issue by hlandau** [docker/docker.github.io#1597]
### Problem description
1. Visit https://docs.docker.com/engine/swarm/
2. Visit any of the links at the end of the main body of the page. For example, under "Explore swarm mode CLI commands", click "swarm init".
3. 404 error.

**Comment by johndmulhausen** [comment]
No repro.

**Comment by hlandau** [comment]
```
$ curl https://docs.docker.com/engine/swarm/ | grep 'swarm init'
  <li><a href="../reference/commandline/swarm_init.md">swarm init</a></li>
$ curl https://docs.docker.com/engine/reference/commandline/swarm_init.md
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.11.9</center>
</body>
</html>
```

**Comment by johndmulhausen** [comment]
@hlandau When I visit https://docs.docker.com/engine/reference/commandline/swarm_init.md I am directed to https://docs.docker.com/engine/reference/commandline/swarm_init/ which is correct, and with JS enabled you shouldn't be able to actually follow the link to swarm_init.md
