### ISSUE TITLE
ucp install --host-address flag incorrect

### ISSUE THREAD

**Issue by ezeeetm** [docker/docker.github.io#16]
per docs here:  https://docs.docker.com/ucp/reference/install/

`--host-address	Specify the visible IP/hostname for this node.`

however, passing an actual hostname results in the error below.  Hostnames cannot be used, only ipv4 names

`FATA[0046] Unsupported host address (ucp.mydomain.com). Please specify an IPv4 address using the '--host-address' flag, and pass the hostname using the '--san' flag.`

**Comment by ezeeetm** [comment]
sorry, just merge one of those.

**Comment by johndmulhausen** [comment]
Fixed in c4f548e8e1cec288201a29ca31ba14e9f45e5f0d
