### ISSUE TITLE
Feedback for: engine/reference/commandline/images.md

### ISSUE THREAD

**Issue by stolati** [docker/docker.github.io#1604]
File: [engine/reference/commandline/images.md](https://docs.docker.com/engine/reference/commandline/images/)

This page don't have the image format we can use.

**Comment by JimGalasyn** [comment]
Thank you for your feedback. Can you provide details about your OS environment to help us diagnose your issue?

**Comment by stolati** [comment]
Looking back at the page, it has been updated with the info that I was searching back then.
You can close this request, thanks.
