### ISSUE TITLE
Feedback for: compose/compose-file/index.md

### ISSUE THREAD

**Issue by shin-** [docker/docker.github.io#1607]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

We should remove `extends` from this list and call out the change on the [compose versioning](https://docs.docker.com/compose/compose-file/compose-versioning/) page.

See: docker/compose#4470, docker/compose#4315

**Comment by Electron-libre** [comment]
I am working on this since I've lost lots of working hours because of this.
