### ISSUE TITLE
Remove extra dotfiles left over from the migration

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#161]
They can probably be killed, but should be checked on first, right?

**Comment by sanscontext** [comment]
Is `.foo` actually a file type? o_O

**Comment by mstanleyjones** [comment]
I am not sure I understand this. I can't find any files with extension `.foo`:

```bash
$ find . -type f -name *.foo

```

Do you mean dotfiles? If so, I can take care of them.

**Comment by johndmulhausen** [comment]
I did mean dotfiles, sorry for the confusion. Thanks, @mstanleyjones !
