### ISSUE TITLE
Make Google detect the publish date

### ISSUE THREAD

**Issue by chrisguidry** [docker/docker.github.io#1612]
File: [engine/swarm/secrets.md](https://docs.docker.com/engine/swarm/secrets/)

Hi, folks.  I was searching for a guide on Docker secrets, and I was surprised by the rank of this page in Google results:

![image](https://cloud.githubusercontent.com/assets/8194/22853533/d1fe47e8-f026-11e6-9c01-e4f19af41657.png)

I noticed the date was listed as "Dec 17, 2013", which I thought was odd until I noticed this about midway down the guide:

![image](https://cloud.githubusercontent.com/assets/8194/22853536/e6a03daa-f026-11e6-87a4-13cdf8f7de4e.png)

I think Google (and probably other web crawlers) are picking up that "17 Dec 13" in the example output as the publish date of the article (it's the first "date-ish" looking thing), and might be demoting the page in results as being old information.  I'd recommend adding the real publish date higher up in the article near the heading.

(Also, your docs are generally amazing, thank you!)

**Comment by thaJeztah** [comment]
Wow, that's surprising. Guess we should look into adding a header with a date to prevent this. Nice find! (fwiw, SEO can definitely be improved overall, I know it's on the todo list)

/cc @johndmulhausen @mstanleyjones
