### ISSUE TITLE
Add overall Swarm architecture diagrams

### ISSUE THREAD

**Issue by devenfan** [docker/docker.github.io#1614]
File: [engine/swarm/swarm-tutorial/index.md](https://docs.docker.com/engine/swarm/swarm-tutorial/)

Better have some architecture pictures to describe the whole picture of swarm.

**Comment by mstanleyjones** [comment]
@sarahpark do y'all have any swarm architectural diagrams pre-baked?

**Comment by johndmulhausen** [comment]
@nishanttotla Ping on this for ideas.

**Comment by nishanttotla** [comment]
@johndmulhausen we used to have architecture diagrams that have been used in presentations before. Particularly one demonstrating cluster topology with 3 managers and 5 workers, and indicating that the managers replicate data using Raft while workers share information p2p using Gossip protocol. Is this the kind of thing you're looking for?

**Comment by sarahpark** [comment]
@mstanleyjones 🤔 not that I know of

**Comment by mistyhacks** [comment]
Closing. Out of date and we don't have anyone to make the diagram.
