### ISSUE TITLE
Explain the benefits of tagging an image

### ISSUE THREAD

**Issue by shubheksha** [docker/docker.github.io#1621]
### Problem description
File: [engine/getstarted/step_four.md](https://docs.docker.com/engine/getstarted/step_four/
)

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/getstarted/step_four/#/step-2-build-an-image-from-your-dockerfile

### Suggestions for a fix
It isn't clear how a tag helps in running the image easily later on. Can a line be added elaborating on that point?

**Comment by jaredestroud** [comment]
Got this one!

**Comment by johndmulhausen** [comment]
Note: This topic no longer exists but we'll credit the participant with hackathon points for their PR anyway.
