### ISSUE TITLE
ESP protocol details in https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-protocols-and-ports-between-the-hosts

### ISSUE THREAD

**Issue by sandys** [docker/docker.github.io#1627]
### Problem description

A lot of people are mistaking "protocol 50" ESP as port 50. Even the developers did not correct me in a separate bug.

### Problem location

https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-protocols-and-ports-between-the-hosts

### Suggestions for a fix
Give examples of examples for particular cloud.

For example in google cloud - gcloud compute firewall-rules create allow-esp  --allow esp --source-range ENTER_IP_OR_RANGE

**Comment by joaofnfernandes** [comment]
Until #1526 the instructions were telling `port` instead of `protocol`, so maybe some users were being mislead by this.

**Comment by briandeheus** [comment]
Thanks @sandys. This actually solved an issue we were having earlier.

**Comment by briandeheus** [comment]
Thanks @sandys. This solved an issue we were having earlier.

**Comment by joaofnfernandes** [comment]
I'm closing this since #1526 fixed it. Feel free to open a new issue if you find out that people are still confused and we need to improve docs even further.
