### ISSUE TITLE
Feedback for: engine/reference/commandline/stack_ps.md

### ISSUE THREAD

**Issue by vide** [docker/docker.github.io#1631]
File: [engine/reference/commandline/stack_ps.md](https://docs.docker.com/engine/reference/commandline/stack_ps/)

Can you please add what kind of filter expressions are supported? Filters you can find in `man 1 docker-ps` (on CentOS at least) do not apply to `stack ps`

**Comment by mstanleyjones** [comment]
https://docs.docker.com/engine/reference/commandline/stack_ps/#filtering This is done!
