### ISSUE TITLE
default docker swarm installation ip addresses conflict with google cloud

### ISSUE THREAD

**Issue by sandys** [docker/docker.github.io#1632]
when we installed a swarm cluster on a google cloud east-1a machine, we saw that the default ip addresses were 10.0.0.*. 
This is conflicting with the ip addresses that Google Cloud assigns to its machines. On a distributed swarm cluster, we were having miscommunications. 

What worked was the 100.64.* ip address range. 100.64 is considered as "carrier grade nat" range (https://en.wikipedia.org/wiki/Carrier-grade_NAT) and is not generally used by the dominant cloud providers.
FYI - some of the other orchestration platforms have also started using 100.64 as their defaults.

In docker swarm case, I recommend adding this to the quickstart docs as a warning. Most people will deploy to AWS or Google Cloud and this will be a big help for them.

**Comment by mstanleyjones** [comment]
@aaronlehmann I don't think this is a docs issue. What do you think?

**Comment by aaronlehmann** [comment]
I'm not sure what the next steps are on this one, so let me ping @docker/core-libnetwork-maintainers.

**Comment by mstanleyjones** [comment]
@nishanttotla PTAL

**Comment by johndmulhausen** [comment]
Issue moved to [docker/editions #1442](https://github.com/docker/editions/issues/1442) via [**ZenHub**](https://www.zenhub.com/)
