### ISSUE TITLE
[Docs] Support docs don't mention the CLI support dump

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1648]
@alexmavr commented on [Wed Jan 25 2017](https://github.com/docker/orca/issues/4862)

The "Get Support" page https://docs.docker.com/datacenter/ucp/2.0/guides/support/ explains how to get a cluster-wide support dump, which is what we should be encouraging users to be doing.

However, if the UI is not even accessible, we usually attempt to retrieve a CLI support dump from one of the managers using the bootstrapper tool. That command is documented at https://docs.docker.com/datacenter/ucp/2.0/reference/cli/support/, but it's not mentioned in the "Get Support" page.

Additionally, the `support` command seems to suggest that there are optional `[command options]` that could be passed in, but at this point there are no such options.

**Comment by tombee** [comment]
#dibs
