### ISSUE TITLE
[Docs] explain cluster management + recovery operations

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1649]
@nicolaka commented on Tue Jan 31 2017

### What's the problem/feature request?

just got off the phone with a customer who were very confused on node management with UCP. IMO both swarm and ucp docs lack the end-to-end story around cluster management. Neither docs goes through (in details) the difference between `node rm` `node demote` `swarm leave` and UCP's UI's node remove operations along with the recommended process to remove nodes from a cluster. For UCP especially, how does node operations affect the  HA and what to do when node removal/demotion goes wrong. 

I think fixing these issues are crucial for next release:

https://github.com/docker/docker.github.io/issues/1451
https://github.com/docker/docker.github.io/issues/815

### What versions/components are affected?
2.1

---

@alexmavr commented on Tue Jan 31 2017

+1 I agree that our documentation is strongly lacking on that subject and I had a similar discussion earlier regarding several customer issues that arise from this confusion. Our recommended path for removing a node from the cluster / uninstalling UCP from one node should be:

1. Perform `docker node demote` for the target node from another manager node. This step can be skipped if the target node is not a manager
2. (Optional) wait for 5-10 seconds so that node reconciliation kicks in and starts cleaning up the UCP leftovers. This guarantees that adding new nodes later on is not going to result in problems.
3. Perform a `docker swarm leave` on the target node 
4. Perform a `docker node rm` for the target node from another manager node.

---

@joaofnfernandes commented on Tue Jan 31

Relates to #2699

**Comment by alexmavr** [comment]
Fixed in https://github.com/docker/docker.github.io/pull/1792

@joaofnfernandes please close if you agree
