### ISSUE TITLE
Feedback for: engine/installation/linux/debian.md

### ISSUE THREAD

**Issue by Zaphox** [docker/docker.github.io#1654]
File: [engine/installation/linux/debian.md](https://docs.docker.com/engine/installation/linux/debian/)

Following the debian wheezy instructions, I can only ever get
```
W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-wheezy/Release  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)
```
when doing `apt-get update`.

```
deb https://apt.dockerproject.org/repo/ debian-wheezy main
deb-src https://apt.dockerproject.org/repo/ debian-wheezy main
```

**Comment by ksigjayt** [comment]
I'm seeing the same thing - I can't install docker-engine because the repo appears to have bad information
# sudo apt-get update
...
W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-wheezy/Release  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

# uname -m
armv7l

# lsb_release -a -cs
Debian
Debian GNU/Linux 7.7 (wheezy)
7.7
wheezy

# grep docker /etc/apt/sources.list 
deb https://apt.dockerproject.org/repo/ debian-wheezy main
deb-src https://apt.dockerproject.org/repo/ debian-wheezy main

**Comment by andrewhsu** [comment]
I can confirm that the [current instructions](https://docs.docker.com/engine/installation/linux/debian/#install-using-the-repository) for debian wheezy use the `add-apt-repository` tool and this is what is adding an extra `deb-src` line even though that repository endpoint does not exist. Reproducible with the `debian:wheezy` docker image.
```
bash# add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
bash# tail /etc/apt/sources.list
deb http://deb.debian.org/debian wheezy main
deb http://deb.debian.org/debian wheezy-updates main
deb [arch=amd64] https://download.docker.com/linux/debian wheezy stable
deb-src [arch=amd64] https://download.docker.com/linux/debian wheezy stable
deb http://security.debian.org wheezy/updates main
```

For now, workaround by adding a source file manually like so:
```
bash$ echo 'deb [arch=amd64] https://download.docker.com/linux/debian wheezy stable' \
  | sudo tee /etc/apt/sources.list.d/docker-ce.list
```

/cc @mstanleyjones

**Comment by thaJeztah** [comment]
Confirmed; the version of `add-apt-repository` on wheezy is different than on later versions of debian. Later versions by default comment-out the `deb-src` line;

```bash
$ cat /etc/apt/sources.list

[....]
# jessie-updates, previously known as 'volatile'
deb http://mirrors.digitalocean.com/debian jessie-updates main
deb [arch=amd64] https://download.docker.com/linux/debian jessie stable
# deb-src [arch=amd64] https://download.docker.com/linux/debian jessie stable
deb-src http://mirrors.digitalocean.com/debian jessie-updates main
````

And have an extra option to _enable_ it during install (on Debian Jessie);

```bash
add-apt-repository --help
Usage: add-apt-repository <sourceline>

[...]

Options:
  -h, --help            show this help message and exit

[...]

  -s, --enable-source   Allow downloading of the source packages from the
                        repository
  -y, --yes             Assume yes to all queries
```

We should probably add instructions to comment that line when installing on wheezy
