### ISSUE TITLE
Request for instructions on connecting to AWS hosts through VPN

### ISSUE THREAD

**Issue by cap10morgan** [docker/docker.github.io#1661]
File: [docker-for-aws/deploy.md](https://docs.docker.com/docker-for-aws/deploy/)

How do you do this without an SSH tunnel? I already have a VPN setup to access my AWS hosts, and want to just set `DOCKER_HOST` (and whatever other env vars are necessary) to connect my `docker` CLI tools to this cluster. I cannot for the life of me find the right combination of settings to make that work.

**Comment by johndmulhausen** [comment]
cc @FrenchBen 
cc @friism 

Ben, can you take a look and advise? We're happy to doc this but we're not sure of the solution.

**Comment by FrenchBen** [comment]
@cap10morgan Wouldn't it simply be to connect to your VPN, then setup the SSH per usual?
We don't expose any ports for `DOCKER_HOST`, which is what the SSH tunnel is emulating.

**Comment by cap10morgan** [comment]
I've long since moved on to kubernetes, but what I was looking for here is a way to access the cluster without needing a separate step that adds no value in the case of already using a VPN.

If this is a "won't fix" I'm happy to close it as I have no more personal issue here.

**Comment by FrenchBen** [comment]
@cap10morgan Out of curiosity what made you move to Kubernetes - Is it also on AWS?
You should've been able to just 'SSH' into the nodes if you wanted to. I may be missing the "extra step" that you were trying to find.

**Comment by mstanleyjones** [comment]
Insufficient info
