### ISSUE TITLE
Capture Engine CLI experimental annotations on commands and flags

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#1663]
### Problem description

It would be good to capture, in the CLI YAML, when a command or a flag is experimental. Here are some examples in the code:

- [experimental command](https://github.com/docker/docker/blob/master/cli/command/checkpoint/cmd.go#L16)
- [experimental flag](https://github.com/docker/docker/blob/master/cli/command/image/build.go#L115)

If this info was surfaced in the YAML, we could template it to automatically mark commands and flags as experimental.

cc/ @johndmulhausen @thaJeztah @dnephin @vieux

**Comment by thaJeztah** [comment]
There's also an [API version annotation](https://github.com/docker/docker/blob/master/cli/command/image/build.go#L116), which could be used to document "new in version x.y.z" (if we translate API version to docker version

**Comment by FrenchBen** [comment]
Experimental command example:
https://github.com/docker/docker/blob/master/cli/command/checkpoint/cmd.go

Experimental flag example:
https://github.com/docker/docker/blob/master/cli/command/container/start.go

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #494](https://github.com/docker/cli/issues/494) via [**ZenHub**](https://www.zenhub.com/)
