### ISSUE TITLE
Check release version for system_prune reference topic

### ISSUE THREAD

**Issue by mkobit** [docker/docker.github.io#1665]
File: [engine/reference/commandline/system_prune.md](https://docs.docker.com/engine/reference/commandline/system_prune/)

It looks like this may contain the latest builds (like possibly from https://github.com/docker/docker/pull/29226) but not the current stable release (`1.13.1`). I would expect it to be the latest release version

```
➜  docker system prune --help

Usage:  docker system prune [OPTIONS]

Remove unused data

Options:
  -a, --all     Remove all unused images not just dangling ones
  -f, --force   Do not prompt for confirmation
      --help    Print usage
➜  docker system prune --filter until='3 hours ago'
unknown flag: --filter
See 'docker system prune --help'.

➜  docker image prune --help

Usage:  docker image prune [OPTIONS]

Remove unused images

Options:
  -a, --all     Remove all unused images, not just dangling ones
  -f, --force   Do not prompt for confirmation
      --help    Print usage
```

**Comment by alfonso-cabrera** [comment]
Working on this

**Comment by alfonso-cabrera** [comment]
The reference topic appears to be correct in not listing the --filter flag for docker system prune - it was not released with v17.03. This can be closed.

**Comment by mkobit** [comment]
Looks like it may have been fixed between when this was filed and now. Thanks for checking it out. Feel free to close!

**Comment by mstanleyjones** [comment]
Thanks @alfonso-cabrera
