### ISSUE TITLE
Fix for wordpress password issue

### ISSUE THREAD

**Issue by matthewf-ucsd** [docker/docker.github.io#1667]
File: [compose/wordpress.md](https://docs.docker.com/compose/wordpress/)

Quickstart fails if I set MYSQL_ROOT_PASSWORD to be different from MYSQL_PASSWORD (as one ought to for security purposes)

This is resolved by defining WORDPRESS_DB_USER in the wordpress environment to match MYSQL_USER in the db environment.

**Comment by johnharris85** [comment]
Claimed :)

**Comment by mstanleyjones** [comment]
Closed via #2824 and #2825
