### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntulinux.md

### ISSUE THREAD

**Issue by grantwinney** [docker/docker.github.io#167]
It's unclear to me what step 11 means by _"Verify that APT is pulling from the right repository"_.

After I run the command `apt-cache policy docker-engine` I get a bunch of output, but I'm unsure which part of that output might indicate that things went okay or horribly wrong.

For reference, here's a sample of the output I get:

```
Installed: (none)
Candidate: 1.12.1-0~trusty
Version table:
   1.12.1-0~trusty 0
      500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
   1.12.0-0~trusty 0
      500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
   1.11.2-0~trusty 0
      500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
```

If possible, it may help if that step was made more clear.

> Verify that APT is pulling from the right repository by viewing the output and looking for &lt;something that indicates the happy path>.

URL: [https://docs.docker.com/engine/installation/linux/ubuntulinux.md](https://docs.docker.com/engine/installation/linux/ubuntulinux/)

**Comment by mstanleyjones** [comment]
Thanks for the feedback. Let me see what I can do.

**Comment by grantwinney** [comment]
@mstanleyjones Thanks for taking care of it.

**Comment by thaJeztah** [comment]
Thanks for reporting @grantwinney, it's appreciated!
