### ISSUE TITLE
404 link to env-file page

### ISSUE THREAD

**Issue by seanf** [docker/docker.github.io#1670]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

The link `.env` in "You can set default values for environment variables using a .env file" is broken (404).

This is included from `_includes/content/compose-var-sub.md`, and it should probably refer to the file `compose/env-file.md`.

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by seanf** [comment]
Thanks!
