### ISSUE TITLE
https://docs.docker.com/machine/get-started-cloud/ send a 503 error

### ISSUE THREAD

**Issue by n-raymond** [docker/docker.github.io#1674]
Hi !

Page [machine/get-started-cloud](https://docs.docker.com/machine/get-started-cloud/) of the documentation doesn't load, sending a 503 error : 
```Failed to load resource: the server responded with a status of 503 ()          https://docs.docker.com/machine/get-started-cloud/```

This page is then printed instead of the documentation :
![capture du 2017-02-15 12-14-08](https://cloud.githubusercontent.com/assets/4958865/22972063/56255648-f378-11e6-92f1-ec7949f342b8.png)

**Comment by JimGalasyn** [comment]
Thank you for your feedback. This issues appears to have been fixed. Please let me know if you have more problems with this topic.

**Comment by JimGalasyn** [comment]
If you're satisfied with this resolution, I'll go ahead and close this issue.
