### ISSUE TITLE
Command execution ambiguity in compose/install.md

### ISSUE THREAD

**Issue by aruseni** [docker/docker.github.io#1678]
In [compose/install.md](https://docs.docker.com/compose/install/#/install-as-a-container) it is unobvious whether you should run the command as root or as a user. The $ in the beginning of the lines suggests that one runs it as user, though actually you should be running this as root (and also prepending sudo to the first of these lines would not work as with many others).

**Comment by londoncalling** [comment]
### Hackathon Hings

See also issue #2435 and maybe work together with whomever works on that issue, or try both!

**Comment by surajnarwade** [comment]
I will take this up
