### ISSUE TITLE
Embedded link to "HEALTHCHECK Dockerfile instruction" appears to go to wrong section

### ISSUE THREAD

**Issue by comjf** [docker/docker.github.io#1680]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

Link following link embedded in text is broken: https://docs.docker.com/engine/reference/builder/#healthcheck
```
Configure a check that’s run to determine whether or not containers for this service are “healthy”. See the docs for the HEALTHCHECK Dockerfile instruction for details on how healthchecks work.
```

**Comment by scjane** [comment]
#dibs

**Comment by scjane** [comment]
This embedded link is valid now. Perhaps it is fixed in someone's PR before. This issue can be closed.
