### ISSUE TITLE
[Docs] DDC on AWS documentation steps are unclear

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1682]
@alexmavr commented

### What's the problem/feature request?

On https://docs.docker.com/datacenter/install/aws/ under section Installation and step 1, there is an instruction to "Click on Launch Stack below. This link will take you to AWS cloudformation portal.".

However that link will take the user to an AWS login page if there is no active AWS session. After the user logs in, they are redirected to their AWS console, rather than the CF template. At this point they are probably confused and have to return back to the same page and decide to click the launch stack button again, without any such guidance

**Comment by johndmulhausen** [comment]
Closing as obsolete per triage discussion.
