### ISSUE TITLE
Error in UCP docs about port 7946

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1683]
@adrahon commented

In the System Requirements part of the docs for both UCP 2.0 and 2.1 beta, we list ports that need to be open, we have the following entries:
managers, workers	in	TCP 2377 (configurable)	Port for communication between swarm nodes
managers, workers	in, out	TCP, UDP 4789	Port for overlay networking
managers, workers	in, out	TCP, UDP 7946	Port for overlay networking

According to the Docker Engine Swarm docs it's:
TCP port 2377 for cluster management communications
TCP and UDP port 7946 for communication among nodes
TCP and UDP port 4789 for overlay network traffic

My understanding is that:
 - TCP 2377 is for swarm node RPC communication
 - TCP / UDP 7946 is for gossip-based clustering
 - TCP / UDP 4789 for overlay networking

**Comment by clocklear** [comment]
Claimed.
