### ISSUE TITLE
Restore docs should state you must use the same version that was backed up

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1685]
@bgrissin commented

Add to the documentation for DDC (UCP and DTR backup and restore) that performing restore require restoration to the same release that the backups were acquired from

All DDC releases for UCP and DTR

**Comment by vikstrous** [comment]
done for dtr

**Comment by mstanleyjones** [comment]
No action for two days, so this is up for grabs!

**Comment by prashant171992** [comment]
I'm taking this up.
