### ISSUE TITLE
DCT docs are shaky at best

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1686]
@programmerq commented

Here's a list of questions/concerns straight from ticket 00014560:

-----

Tried the following links the install and configuration pages are very ambigious at best: 
1) https://docs.docker.com/datacenter/ucp/2.0/guides/content-trust/ 
this has a link "install the Notary CLI Client" ok that link provides a download for a binary. how do we know that will match/work with the docker/dtr-notary-server:2.1.1? 
2) how do they work together? 
3) where is the best location for ".docker/trust" if several people will usr it ? 
4) is setting up a team the best approach? We Use LDAP to access the UCP/DTR consoles. 
5) where should the Notary config file be located? is it a json file? a text file? 
6) can the Notary client be ran as a container ? 

I guess it would be nice to have a better step-by step approach with detailed instructions. our Docker Datacenters don't access outside our environment. 

When setting up the notary the instructions on the above link are not too bad except the install instructions. should the binary be in /var/lib/docker ? or /usr/local/bin ? not clear where things need to be to interact correctly with the latest Docker Datercenter.

-----

if I try to run teh notary binary downloaded from the install link I get this message: 

* fatal: client is offline 

So where are the actual install and startup instructions ?

-----

I've also included my response to all of these:

> 1) https://docs.docker.com/datacenter/ucp/2.0/guides/content-trust/ 
this has a link "install the Notary CLI Client" ok that link provides a download for a binary. how do we know that will match/work with the docker/dtr-notary-server:2.1.1? 

I agree, this is unclear. It took some doing for me, and I have access to the source code. DTR 2.1.1 uses notary 0.4.2, which is the current latest version of notary. 

> 2) how do they work together? 

Similar to docker's daemon and client, notary has a server and client. The server serves up an API, and the client can interact with it. The docker client also talks to notary server as a notary client when docker content trust is enabled. For more advanced operations than simply doing push/pull, you can drop out to the notary client. This is necessary in the context of DDC since you have to set up delegations (more on that in a bit) 

> 3) where is the best location for ".docker/trust" if several people will usr it ? 

For content publishers, that is where private keys will go, so it should not be shared. Generally speaking, each person that can sign content will have their own ~/.docker/trust directory in their own home directory on their own worksation, and shouldn't make those private keys available to others. 

If you (or an automated system) are *only* doing deploys, it doesn't really matter. In that case, that location really just caches data that is stored in notary. Technically, you could delete that whole directory after each operation, and docker content trust would still run the same, just a little bit slower since it isn't caching data. 

> 4) is setting up a team the best approach? We Use LDAP to access the UCP/DTR consoles. 

When you want to use docker content trust to restrict which images can be run, setting up a team is a good approach. You can set a policy that says "any image sigend by the key of someone in this team can be run on UCP" 

> 5) where should the Notary config file be located? is it a json file? a text file? 

Changing the notary config file isn't strictly necessary for use with DDC. It is most definitely possible. Details on the ~/.notary/config.json file can be found here: https://docs.docker.com/notary/reference/client-config/ 

Since you are in an offline environment, it might make sense to have a file that looks like this: 

{"remote_server": {"url": "https://dtr.example.com/"}} 

> 6) can the Notary client be ran as a container ? 

Yes indeed it can. I don't believe there's a premade container that has it installed, but you could do something like this: 

alias notary='docker run -v $HOME:/homedir -e $HOME=/homedir -u `id` -w /homedir <imagewithnotaryinstalled notary' 

I would actually recommend installing the notary client on your workstation directly rather than going about it this way. 

> I guess it would be nice to have a better step-by step approach with detailed instructions. our Docker Datacenters don't access outside our environment. 

Agreed. One thing to keep in mind is that there's "regular old content trust" and then there's the UCP features that build on top of that. I'd recommend looking at content trust in general, outside of the context of UCP, just to get a feel for what it is and how it works. Then, learning the UCP features on top will be a bit easier than trying for it all at once. 

> When setting up the notary the instructions on the above link are not too bad except the install instructions. should the binary be in /var/lib/docker ? or /usr/local/bin ? not clear where things need to be to interact correctly with the latest Docker Datercenter. 

The notary client should go somewhere in your $PATH on your local workstation.

> if I try to run teh notary binary downloaded from the install link I get this message: 
> 
> * fatal: client is offline 

This looks like you might have ran notary without pointing it to your DTR. What was the exact command you ran?

-----

hopefully these answers help paint the picture of what sort of stuff customers are asking about.

**Comment by johndmulhausen** [comment]
Closing as obsolete per triage discussion.
