### ISSUE TITLE
Feedback for: ucp/installation/install-production.md

### ISSUE THREAD

**Issue by ahb-sjsu** [docker/docker.github.io#169]
URL: [https://docs.docker.com/ucp/installation/install-production.md](https://docs.docker.com/ucp/installation/install-production/)

If I try to specify UCP with alternative address when in a proxy enabled environment, I get error even if firewall and proxy environment is configured correctly.

Also, I notice the install flow is different. Without the "-i" option, it skips this part (and defaults to admin/orca):

	Please choose your initial UCP admin password:
	Confirm your initial password:

##########################################
INFO
##########################################
lab-c1 (physical host) is 172.23.122.56
lab-ucp is 172.23.122.54

[root@lab-c1 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@lab-c1 ~]# docker -v
Docker version 1.12.1-cs1, build e7f4338
[root@lab-c1 ~]# env | grep -i proxy
NO_PROXY=localhost,127.0.0.0/8,172.23.120.0/21,::1,/var/run/docker.sock
http_proxy=http://proxy.esl.cisco.com:80/
ftp_proxy=http://proxy.esl.cisco.com:80/
https_proxy=http://proxy.esl.cisco.com:80/
no_proxy=localhost,127.0.0.0/8,172.23.120.0/21,::1,/var/run/docker.sock
[root@lab-c1 ~]# firewall-cmd --list-ports
12385/tcp 2376/tcp 12384/tcp 12381/tcp 443/tcp 12380/tcp 12386/tcp 12383/tcp 12379/tcp 12382/tcp 12376/tcp

########################################################
FATAL error with -i option to use 172.23.122.56 for UCP:
########################################################
[root@lab-c1 system]# docker run --rm -it --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp install -i --host-address 172.23.122.54 --fresh-install
INFO[0000] Verifying your system is compatible with UCP
INFO[0000] Your engine version 1.12.1-cs1, build e7f4338 (3.10.0-327.el7.x86_64) is compatible
WARN[0000] Your system uses devicemapper.  We can not accurately detect available storage space.  Please make sure you have at least 3.00 GB available in /var/lib/docker
Please choose your initial UCP admin password:
Confirm your initial password:
INFO[0007] All required images are present
We detected the following hostnames/IP addresses for this system [lab-c1.cisco.com 127.0.0.1 172.17.0.1 172.23.122.54]

You may enter additional aliases (SANs) now or press enter to proceed with the above list.
Additional aliases: lab-ucp
INFO[0011] Installing UCP with host address 172.23.122.54 - If this is incorrect, please specify an alternative address with the '--host-address' flag
INFO[0000] Checking that required ports are available and accessible
FATA[0034] The following required ports are blocked on your host: 12384, 12383, 12376, 443, 12386, 2376, 12379, 12385, 12381, 12382, 12380.  Check your firewall settings.

########################################################
Install success without -i option (uses 172.23.122.56 for UCP):
########################################################
[root@lab-c1 system]# docker run --rm -it --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp install
INFO[0000] Verifying your system is compatible with UCP
INFO[0000] Your engine version 1.12.1-cs1, build e7f4338 (3.10.0-327.el7.x86_64) is compatible
WARN[0000] Your system uses devicemapper.  We can not accurately detect available storage space.  Please make sure you have at least 3.00 GB available in /var/lib/docker
INFO[0002] All required images are present
INFO[0002] Installing UCP with host address 172.23.122.56 - If this is incorrect, please specify an alternative address with the '--host-address' flag
INFO[0000] Checking that required ports are available and accessible
INFO[0006] Generating UCP Cluster Root CA
INFO[0030] Generating UCP Client Root CA
INFO[0032] Deploying UCP Containers
INFO[0075] New configuration established.  Signalling the daemon to load it...
INFO[0076] Successfully delivered signal to daemon
INFO[0076] UCP instance ID: HJ3Y:PTZP:GFFU:4S3E:FHJR:H7QB:I6S6:WLY6:6EUP:T753:LHTH:NPMV
INFO[0076] UCP Server SSL: SHA-256 Fingerprint=5B:40:92:E8:F3:0B:68:BD:B5:3A:83:11:26:C6:0C:B6:87:A6:E8:82:03:3E:1B:F4:CA:52:89:9D:2A:AA:95:A9
INFO[0076] Login as "admin"/"orca" to UCP at https://172.23.122.56:443

**Comment by joaofnfernandes** [comment]
Thanks for reporting this, I've created an internal issue so that we can continue tracking this.
Since this repo is for docs only, and there is nothing that needs to be done at the docs level, I'm closing the issue.

Next time you can use [Docker support channels](https://docs.docker.com/ucp/support/) to report issues with the commercial products. 🐋
