### ISSUE TITLE
How to configure UCP for separating app and management traffic

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1690]

**Comment by mstanleyjones** [comment]
https://docs.docker.com/engine/swarm/networking/#use-a-separate-interface-for-control-and-data-traffic

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #450](https://github.com/docker/docs-private/issues/450) via [**ZenHub**](https://www.zenhub.com/)
