### ISSUE TITLE
Best practices for load balancer timeouts

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1691]
When using UCP or DTR with a load balancer, what is a sane timeout value?

**Comment by whoshuu** [comment]
I think anything on the order of tens of seconds to a minute sounds reasonable. For a cluster-wide check, you might be justified in pushing this value higher.

A healthy replica should return a real-time status on the order of network traffic + tens of ms.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #453](https://github.com/docker/docs-private/issues/453) via [**ZenHub**](https://www.zenhub.com/)
