### ISSUE TITLE
How to set an HTTP/HTTPS proxy for DTR

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1699]
Installations behind a firewall might have to use proxies, but there is no docs guiding you on how to do this.

**Comment by jpooler** [comment]
@joaofnfernandes Any preference on the proxy to use? I'd think an example with https://github.com/containous/traefik or nginx would suffice? Or were you thinking more along the lines of how to set it up for a physical device?

**Comment by joaofnfernandes** [comment]
Oh... This is for the case where I deploy Docker Trusted Registry, but all communications between clients and DTR go through a proxy. So I need to configure DTR for this.
This is not about deploying your own proxy.

**Comment by vikstrous** [comment]
Actually this issue is about --http-proxy and --https-proxy. They allow you to use a proxy for DTR's connection to external services listed in https://docs.docker.com/datacenter/dtr/2.2/guides/admin/install/install-offline/#preventing-outgoing-connections
