### ISSUE TITLE
DTR nodes clock should be synched

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1700]
UCP will warn when it detects clock skews but we can improve the DTR docs to mention this and explain how to fix it

**Comment by vikstrous** [comment]
This is no longer an issue in DTR 2.2. Rethinkdb doesn't require synchronized clocks. The jepsen test used intentionally out of sync clocks: https://jepsen.io/analyses/rethinkdb-2-1-5
