### ISSUE TITLE
404 at /compose/docker-compose

### ISSUE THREAD

**Issue by vcastano1986** [docker/docker.github.io#17032]
I found a broken link : https://docs.docker.com/compose/docker-compose
I arrived on this page through: https://github.com/warpcomdev/optest_public

**Comment by SashankMeka1** [comment]
I can work on this issue, but I am not sure where it is supposed to redirect?

**Comment by thaJeztah** [comment]
I don't think we ever had a page at that URL, so this seems like an issue with the repository that has a link to it; might be best to report it there; https://github.com/warpcomdev/optest_public

**Comment by usha-mandya** [comment]
Thanks all. Closing this issue as the page is located outside of the docs GitHub repo.
