### ISSUE TITLE
404 at: /reference/commandline/login/

### ISSUE THREAD

**Issue by afdalwahyu** [docker/docker.github.io#173]
URL: /reference/commandline/login/

I'm looking for logn documentation, but shows 404 page
all links at section **Docker commands and Docker Hub** from https://docs.docker.com/docker-hub/ return 404

**Comment by joaofnfernandes** [comment]
@afdalwahyu can you check if this has been fixed?
Both:
* https://docs.docker.com/engine/reference/commandline/login/
* https://docs.docker.com/docker-hub/

Seem OK.

**Comment by mstanleyjones** [comment]
Works for me too. Please reopen this issue if you are still experiencing a problem.
