### ISSUE TITLE
Improve DTR caching docs

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1733]
We already have docs for DTR caching, but users are flooding support and the field team with questions, so we should create more content around this.

- [x] What is a DTR cache and why you should care
- [x] How cache works behind the scenes (network flows)
- [x] Example for IT ops to deploy a simple cache
- [x] Example for IT ops to deploy cache with TLS
- [x] Example for IT ops to deploy complex cache (chaining)
- [ ] How can IT ops configure multiple users to use a cache (scripting)
- [ ] How can IT ops monitor a cache and check if it's running or not
- [ ] How can IT troubleshoot if a cache goes down or has problems
- [x] How can developers choose a cache
- [ ] How can developers troubleshoot if a cache is down and what are the consequences

Bonus points: How to set up geo-based caching

---
This is the documentation we have right now
- [Deploy a cache](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/deploy-a-cache/)
- [Use a cache](https://docs.docker.com/datacenter/dtr/2.2/guides/user/access-dtr/use-a-cache/)

**Comment by hinshun** [comment]
#dibs

**Comment by joaofnfernandes** [comment]
Most of the issues here where addressed, so this is no longer a P0

**Comment by johndmulhausen** [comment]
Closing per triage discussion
