### ISSUE TITLE
Document DTR garbage collection

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1734]
We currently have no documentation about this awesome feature.

- [ ] How images/manifests/tags/blobs are stored
- [ ] What is garbage collection and why you should care
- [ ] How IT ops can set up garbage collection
- [ ] How does IT ops monitor if garbage collection is really running 
- [ ] Jobs are configured in UTC. Check #905

**Comment by tonyhb** [comment]
dibs

**Comment by tonyhb** [comment]
http://i.imgur.com/q7vY1YX.gif

**Comment by vikstrous** [comment]
see also https://github.com/docker/docker.github.io/issues/905
