### ISSUE TITLE
How to integrate DTR with S3

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1736]
We currently have docs about this but they are not exhaustive and don't provide enough guidance to an IT ops user. Create a dedicated article for S3

- [ ] How to do this configuration from the UI
- [ ]  How to do this using a yml config file
- [ ] What should an IT ops know about S3 accounts, secrets, and regions

Related: #898

---

[You can find the current docs here](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/external-storage/nfs/)

**Comment by tonyhb** [comment]
dibaroo
