### ISSUE TITLE
How to integrate DTR with Azure backend

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1737]
We currently have docs about this but they are not exhaustive and don't provide enough guidance to an IT ops user. Create an article dedicated to Azure.

- [ ] How to do this configuration from the UI
- [ ]  How to do this using a yml config file
- [ ] What should an IT ops know about Azure accounts, containers, realms
---

[You can find the current docs here](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/external-storage/nfs/)

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #452](https://github.com/docker/docs-private/issues/452) via [**ZenHub**](https://www.zenhub.com/)
