### ISSUE TITLE
How to integrate DTR with Swift

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1738]
We currently have docs about this but they are not exhaustive and don't provide enough guidance to an IT ops user. Create a dedicated article for Swift

- [ ] How to do this configuration from the UI
- [ ]  How to do this using a yml config file
- [ ] What should an IT ops know about swift accounts, containers

---

[You can find the current docs here](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/external-storage/nfs/)

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #455](https://github.com/docker/docs-private/issues/455) via [**ZenHub**](https://www.zenhub.com/)
