### ISSUE TITLE
How to integrate DTR with Google Cloud Storage

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1740]
We currently have docs about this but they are not exhaustive and don't provide enough guidance to an IT ops user. Create a dedicate article for GCS

- [ ] How to do this configuration from the UI
- [ ]  How to do this using a yml config file
- [ ] What should an IT ops know about GCS accounts, buckets

---

[You can find the current docs here](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/external-storage/nfs/)

**Comment by mstanleyjones** [comment]
@joaofnfernandes was this closed by #2677?

**Comment by joaofnfernandes** [comment]
Nop, not closed. I'm going to do a pass on all the hackathon/ddc issues to remove the hackaton labels.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #454](https://github.com/docker/docs-private/issues/454) via [**ZenHub**](https://www.zenhub.com/)
