### ISSUE TITLE
Improve overview of DTR external storage

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1741]
We don't have any docs explaining why you should configure DTR to use an external backend that can be shared by all replicas. Review the "external storage" article to make sure

- [ ] Why use an external storage and why you should care
- [ ] What are the caveats of using an external storage (proxies, firewalls, ...)
- [ ] What options are available

---
- [External storage](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/external-storage/)
- [DTR architecture](https://docs.docker.com/datacenter/dtr/2.2/guides/architecture/) (has a good diagram that can be reused)

**Comment by tonyhb** [comment]
dibaroo
