### ISSUE TITLE
Update screenshots for DDC

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1742]
@sarahpark commented 

From Hans:

Hi Guys,

I've perused the DDC does and found all these pages with old screenshot that are not reflected of the latest release.

Can we please fix these during the hackathon:

Need updated screenshots

- [x] https://docs.docker.com/datacenter/install/aws/
- [x] https://docs.docker.com/datacenter/install/linux/
- [x] https://docs.docker.com/datacenter/ucp/2.1/guides/
- [x] https://docs.docker.com/datacenter/ucp/2.1/guides/admin/install/
- [x] https://docs.docker.com/datacenter/ucp/2.1/guides/admin/configure/scale-your-cluster/
- [x] https://docs.docker.com/datacenter/ucp/2.1/guides/admin/monitor-and-troubleshoot/
- [x] https://docs.docker.com/datacenter/ucp/2.1/guides/admin/monitor-and-troubleshoot/troubleshoot-with-logs/
- [x] https://docs.docker.com/datacenter/ucp/2.1/guides/user/access-ucp/
- [x] https://docs.docker.com/datacenter/ucp/2.1/guides/user/services/
- [x] https://docs.docker.com/datacenter/ucp/2.1/guides/user/secrets/
- [x] https://docs.docker.com/datacenter/ucp/2.1/guides/user/secrets/grant-revoke-access/
- [ ] https://docs.docker.com/datacenter/dtr/2.2/guides/admin/install/
- [ ] https://docs.docker.com/datacenter/dtr/2.2/guides/admin/monitor-and-troubleshoot/
- [ ] https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/pull-and-push-images/
- [ ] https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/
- [ ] https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/delete-images/

Need Product Images/screenshot in these sections:

- [x] https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/set-up-vulnerability-scans/
- [x] https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/scan-images-for-vulnerabilities/

It's pretty bad that we don't have any screenshot (that I can find) around Security Scanning and that the security scanning feedback was not included in the other pages about DTR when we see the repo details.

Broken links and broken image links

- [x] https://docs.docker.com/datacenter/dtr/2.2/guides/admin/manage-users/
- [x] https://docs.docker.com/datacenter/dtr/2.2/guides/admin/manage-users/create-and-manage-users/
- [x] https://docs.docker.com/datacenter/dtr/2.2/guides/admin/manage-users/create-and-manage-teams/

I now you guys this I'm pedantic about this but trust me on this one... first impression is everything and the moment someone (internal/external) finds such a deprecancy  then they start thinking well what else is not updated (text/feature/procedure...) 

BTW- Thanks for all the new charts... they look pretty neat and well integrated.

**Comment by sarahpark** [comment]
Work in progress: https://github.com/sarahpark/docker.github.io/tree/update-screenshots

**Comment by joaofnfernandes** [comment]
This is awesome, thanks for the help.

**Comment by joaofnfernandes** [comment]
Updated the issue since we've included some images and updated some broken links since the issue was created.

**Comment by mstanleyjones** [comment]
@joaofnfernandes what is the status of this? I am not sure why I added `claimed`... it doesn't seem accurate.

**Comment by joaofnfernandes** [comment]
Yup, I removed the `claimed` label since no one had claimed it.

**Comment by jmaitrehenry** [comment]
In this case, I will startup a new pwd UCP and make some screenshot :)
I'm in the airport right now, so maybe you will not have any news today about this issue.

**Comment by jmaitrehenry** [comment]
Not taken yet, I had 4h delay for my flight tonight, if someone else want to make this issue, feel free to do :)

**Comment by jmaitrehenry** [comment]
Finally, it's not possible to have DTR running on PWD for now, I lost all my time trying to make it working. I may not have the time to do it today, but I will try to make it tomorrow.

**Comment by joaofnfernandes** [comment]
@jmaitrehenry sorry for making you waste time. I've deployed a DDC instance that you can use for this.
* UCP - https://54.153.4.164
* DTR - https://54.153.4.164:444
* credentials: `admin/password`

I'll tear down this instance before the end of the week 😉

**Comment by jmaitrehenry** [comment]
@joaofnfernandes no problem, I need to see why it doesn't work with PWD and create an issue with the team about it.

Thanks for the instance, I will try to use it for as much DTR issue as possible but I'm now back in my daily job.

**Comment by joaofnfernandes** [comment]
No worries. About PWD I think the team already knows about that issue. If I remember correctly, DTR needs to contact UCP, and there was a networking issue or architectural decision that currently was getting in the way.

**Comment by jmaitrehenry** [comment]
Currently DTR and UCP can communicate internally without problem, but DTR use only https url when it redirect to UCP for login and for an unknown reason, the https don’t work.


On April 24, 2017 at 3:10:55 PM, Joao Fernandes (notifications@github.com) wrote:

No worries. About PWD I think the team already knows about that issue. If I remember correctly, DTR needs to contact UCP, and there was a networking issue or architectural decision that currently was getting in the way.

**Comment by jmaitrehenry** [comment]
@joaofnfernandes you could close this dtr/ucp instance, I created a new one with DO for having some DNS resolving and "valid" self-signed certificate.

**Comment by joaofnfernandes** [comment]
Nice! I've edited my previous comment to remove any data about that instance.
