### ISSUE TITLE
Document end-to-end upgrade of DDC

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1744]
@mbentley commented

### Problem description
When upgrading DDC as a whole platform, moving from Engine 1.12, UCP 2.0.x, and DTR 2.1.x to Entiner 1.13, UCP 2.1.x, and DTR 2.2.x, what is the recommended upgraded path?  What can be done in parallel?  What must be done serially?

This was specifically requested by a user but it really should be documented in our docs for everyone to see.

/cc @vsaraswat @pvnovarese 

### Problem location
n/a

### Project version(s) affected
n/a

### Suggestions for a fix
Docs overarching for DDC; specific sections referencing the proper upgrade order in the Engine, UCP, and DTR docs sections.

---

@vsaraswat commented on

Here's the latest:
Engine: Recommend sequential updates, however 1.11 to 1.13 directly is possible
UCP: 1.1.x to 2.1.x is directly possible
DTR: Enforces upgrades from minor version (so only 2.1.x to 2.2.x). 

Looks like we need two things: A DDC upgrade doc (which covers all cases), as well as a special case Engine 1.11 to 1.13 customer success document.

The first one should cover upgrade process of all components--Engine, UCP, DTR--in that order, and require sequential updates of minor versions (eg. DTR 2.1.x to DTR 2.2.x, or Engine 1.12 to 1.13). Best practice is to upgrade using the latest patches  each time as well.

However--several of our customers are upgrading from Engine 1.11 to 1.13 (UCP 1.1.x to UCP 2.1.x) and skipped Engine 1.12. We know that it is okay to upgrade directly from Engine and UCP in this specific use case, and it fact may be preferable if we are worried about stability issues in 1.12. So, we should make a customer success document that specifies doing the jump directly from 1.11 to 1.13 without sequential upgrades, and stress that is okay **only for this specific case**. DTR will still need sequential updates however.

I can work on the 2nd customer success doc. The first one is probably a good candidate for docs day

**Comment by trapier** [comment]
To avoid duplication of effort / keep everything on the same page, some of this policy is already posted here:

https://success.docker.com/KBase/Upgrading_to_Docker_Datacenter_on_Engine_1.13

**Comment by vikstrous** [comment]
This looks done. I don't think we need two sets of documentation for it.

**Comment by joaofnfernandes** [comment]
This is one of those cases where half of the content is on docs.docker.com and the other half in success.docker.com and we're providing an awful experience to our users.
@vikstrous and @alexmavr can you review the content on https://success.docker.com/KBase/Upgrading_to_Docker_Datacenter_on_Engine_1.13, and I'll later sync with the success.docker.com team.

If you have improvements, or detect wrong instructions, just post them on this issue.

**Comment by clemenko** [comment]
Had to make some assumptions in order to make the doc simple. 
https://success.docker.com/KBase/Upgrade_an_entire_cluster_with_CentOS%2C_Docker_Engine%2C_UCP%2C_and_DTR
