### ISSUE TITLE
Feedback for: engine/getstarted/step_six.md

### ISSUE THREAD

**Issue by aalapatirvbd** [docker/docker.github.io#1746]
File: [engine/getstarted/step_six.md](https://docs.docker.com/engine/getstarted/step_six/)

I think 3rd Step in pull your image section needs to be corrected. 

I am unable to use "docker image remove" command on 1.11. rc.  Shouldn't it be "docker rmi " ?

**Comment by JimGalasyn** [comment]
Thank you for your feedback. This issue seems to have been fixed. Please let me know if you're still having problems with this topic.

**Comment by JimGalasyn** [comment]
If you're satisfied with this resolution, I'll go ahead and close this issue.
