### ISSUE TITLE
Review UCP RBAC docs

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1747]
We have docs for this but some users are getting confused by the lack of clarity and a lot of caveats around our RBAC model.

- [x] What resources have RBAC. Check #624 
- [x] Improve explanation about how default permissions work and how you can extend user permissions

---

Current docs:
- [Authentication and authorization](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/manage-users/)
- [Create and manage users](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/manage-users/create-and-manage-users/)
- [Create and manage teams](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/manage-users/create-and-manage-teams/)
- [Permission levels](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/manage-users/permission-levels/)

**Comment by clemenko** [comment]
dibs

**Comment by clemenko** [comment]
fixed first part with #1772

**Comment by vsaraswat** [comment]
@clemenko just some notes on this:

Basic permission structure:
- Label Permissions: If an object has the permission label, then any users in a team with access to a label get that level of access to the label. So if container A has label `prod`, and Vivek is a member of team PM with `view-only` access to `prod`, then Vivek can view (but not alter) container A>
- Default Permissions: A user's ability to create resources without labels. If you have `Restricted Control` or `Full Control` default permissions, you can create resources without labels, and **only** you and Admins can see and access that resource. 
- Default permissions also affect ability for a user to access things that can't have labels. In the latest versions of UCP this is basically just images and nodes. In UCP 1.1.x this is volumes, networks, images, and nodes.
- Only Admins can access admin settings, create users + teams, and change permissions.

**Comment by clemenko** [comment]
Added #1776

**Comment by clemenko** [comment]
added #1777

**Comment by clemenko** [comment]
@vsaraswat Can we point the docs to reference archs? Say add it to the "where to go next" section
? specifically : https://success.docker.com/KBase/Docker_Reference_Architecture%3A_Securing_Docker_Datacenter_and_Security_Best_Practices

**Comment by vsaraswat** [comment]
I have no problem with it, but I'll defer to @joaofnfernandes if he is cool pointing to RAs. It would be good practice for things like load balancing and service discovery as well.

**Comment by joaofnfernandes** [comment]
Link away! If we have amazing content we can link to there

**Comment by clemenko** [comment]
added #1783

**Comment by clemenko** [comment]
With the last commit I think we can close this. The Securing DDC RA goes into MUCH greater detail about permissions and RBAC.

**Comment by joaofnfernandes** [comment]
I've updated your description on PR #1783. When it gets merged it will automatically close this issue.

**Comment by clemenko** [comment]
Nice. THanks
