### ISSUE TITLE
How to troubleshoot a failed UCP upgrade

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1749]
Have we been seeing people struggle with updating UCP from 2.0 to 2.1?
What do you do when it fails and how do you approach troubleshooting?

---
[Current upgrade docs are here](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/upgrade/)

**Comment by johndmulhausen** [comment]
Will close and wait for more feedback; in new versions we have single-click upgrades in the UI.
