### ISSUE TITLE
Improve docs around scaling UCP up and down

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1750]
[We already have docs](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/configure/scale-your-cluster/) on how to add/remove nodes from a UCP cluster. But some users have been running into problems because they're breaking the swarm consensus group by removing too many nodes at a time and doing other operations like that.

Improve these docs with things that are missing and might lead users into making mistakes.

**Comment by joaofnfernandes** [comment]
@alexmavr I think this is mostly addressed by #1792. Do you think that one is enough to close this issue?

**Comment by alexmavr** [comment]
I also want to add `docker swarm join-token` information in joining a node and document the expectations of UCP being installed as a secondary step, so let's leave this open for now

**Comment by joaofnfernandes** [comment]
This seems to be mostly solved by now.
