### ISSUE TITLE
Troubleshoot DTR overlay network

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1754]
Teach users how to test if the overlay network is working and other helpful troubleshooting tips and tricks.

**Comment by vikstrous** [comment]
We have one thing about overlay networks right now: how to do the ping test. We can definitely do better, but we would need help from core to build better debug tools.

**Comment by joaofnfernandes** [comment]
Talking about the ping test would be an improvement because we don't really have anything and some of the issues we're seeing are related to overlay networks.

**Comment by vikstrous** [comment]
Yep. That's already in troubleshoot-with-logs.md

**Comment by joaofnfernandes** [comment]
Solved.
