### ISSUE TITLE
Monitor DTR disk space

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1755]
If a DTR instances gets a full disk you'll see all kinds os strange errors. One way to keep track of disk usage is to go to the UCP nodes page. There you can see disk usage metrics.

Maybe we can also explain what to do to free up the disk. Maybe link to the garbage collection docs if we create them.

**Comment by joaofnfernandes** [comment]
The UCP nodes list page allows you to do this in an easy way

<img width="1012" alt="screen shot 2018-04-16 at 14 45 08" src="https://user-images.githubusercontent.com/1525937/38836914-d6ec4344-4184-11e8-864e-eea5e65a7fa5.png">

**Comment by L-Hudson** [comment]
Two years old, issues addressed subsequently. Closing ticket.
