### ISSUE TITLE
Add diagrams and screenshots to DTR security scanning

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1756]
Right now the docs are a wall of text and it's users need to read a lot to get a clear mental model of how security scanning works.

Adding diagrams and screenshots to the docs would help with this.

---
Current docs

- [set up vulnerability scans](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/set-up-vulnerability-scans/)
- [scan images for vulnerabilities ](https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/scan-images-for-vulnerabilities/)

**Comment by venalen** [comment]
#dibs
