### ISSUE TITLE
Prune security scanning logs

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1758]
DTR security scanning logs are a bit noisy, so some users might be interested in learning how to prune those logs to avoid filling the disk of the node.

**Comment by venalen** [comment]
I have a fix that will quiet the scanner logs; we'll only be showing `WARNING` and `CRITICAL` logs in the next patch release.

**Comment by joaofnfernandes** [comment]
Then, there's nothing to do in the docs. Closing this issue.
