### ISSUE TITLE
Inconsistent example for replacing MAINTAINER with LABEL

### ISSUE THREAD

**Issue by arkuuu** [docker/docker.github.io#1759]
### Problem description

The [documentation](https://docs.docker.com/engine/reference/builder/#/maintainer-deprecated) for the deprecated `MAINTAINER` says that we should replace `MAINTAINER` with `LABEL`.
But the example is inconsistent with the [documentation](https://docs.docker.com/engine/reference/builder/#/label) for `LABEL`.

The example says:
```
LABEL maintainer "SvenDowideit@home.org.au"
```

But shouldn't it be:
```
LABEL maintainer="SvenDowideit@home.org.au"
```

### Problem location

- https://docs.docker.com/engine/reference/builder/#/maintainer-deprecated

**Comment by scjane** [comment]
#dibs

**Comment by scjane** [comment]
I tested building 4 images using Dockfiles that only differ in "LABEL". The "LABEL" filelds are respectively defined in the Dockerfiles as follows:

- LABEL maintainer "wangjie5@chinaskycloud.com"
- LABEL maintainer ="wangjie5@chinaskycloud.com"
- LABEL maintainer wangjie5@chinaskycloud.com
- LABEL maintainer=wangjie5@chinaskycloud.com

All images are successfully built. Then, I checked the image info by running `docker inspect <image ID>`.  The output shows that the images all have the same correct maintainer filed as I specified. Here are some screenshots referring to the building process and the output.
  
![7](https://cloud.githubusercontent.com/assets/25146885/25117239/be235654-2443-11e7-9672-39f6ce00f332.jpg)
![8](https://cloud.githubusercontent.com/assets/25146885/25117244/cdd13e40-2443-11e7-9dbc-2973f7723c90.jpg)
![8-2](https://cloud.githubusercontent.com/assets/25146885/25117246/d3860762-2443-11e7-94d1-2a04f9c6b53a.jpg)

**Comment by scjane** [comment]
I built an image again using Dockfile with the following label defined:

> 
LABEL maintainer "wangjie5@chinaskycloud.com"  description "test adding labels in Dockfile"

The image is also successfully built. But the output of docker inspect is as follows.
![4](https://cloud.githubusercontent.com/assets/25146885/25119779/1ae1cc9a-244e-11e7-8afa-7da5eac318be.png)

It shows that the maintainer info and the description info are mixed up.

So I think if only one item is included in LABEL, it is OK to define LABEL without "=" (that is, in "LABEL key value" format, such as LABEL maintainer "SvenDowideit@home.org.au" ); but if there are two or more items, "=" is necessary. 

To avoid misleading, it is better to add  "=" between key and value.

**Comment by scjane** [comment]
Add "=" via #32682.

**Comment by mstanleyjones** [comment]
@thaJeztah WDYT? I don't think the things in the Dockerfile usually have the equals signs. Are labels different?

**Comment by vdemeester** [comment]
@mstanleyjones I think `LABEL`, `ENV` (and others) supports both notation (with and without an equal sign). But without an equal sign, it can get tricky 👼

**Comment by mstanleyjones** [comment]
Review happening upstream. Going ahead and counting this.

**Comment by mstanleyjones** [comment]
Closing as the work has shifted to `moby/moby`. Thanks @scjane!
