### ISSUE TITLE
Docker Swarm in Engine: Overlay Network explanation

### ISSUE THREAD

**Issue by BlaM** [docker/docker.github.io#176]
I think the documentation page at https://docs.docker.com/engine/swarm/networking/ could be more precise about the fact that you HAVE TO create your own overlay network to use the service discovery feature.

As discussed in https://github.com/docker/docker/issues/26993 was under the impression that - while I noticed that I have the option to create new overlay networks - Docker would give me a "default" overlay network (after all there was that `ingress` network). @sanimej has added some explanation to the [documentation of `ingress`](https://github.com/docker/docker/pull/27290), but that would not have helped me as I was working through the "Getting Started" guide - and the ingress page does not seem to be part of that.

**Comment by londoncalling** [comment]
Labelling this as a good Hackathon issue. Step one will be making sure it's not already been addressed per more recent changes, but on a quick glance, I don't think so.

**Comment by johnharris85** [comment]
I'll take a look and claim this one :)

**Comment by JimGalasyn** [comment]
@johnharris85 What's the status on this? I'll need to put it back into the unclaimed pool if we don't see a PR in a couple of hours.

**Comment by johnharris85** [comment]
Sorry @JimGalasyn, will commit before I take off :) (should be in the next 30 mins).

**Comment by londoncalling** [comment]
@surajnarwade if you want another Hackathon bug, I just removed `claimed` from this one as it was never addressed

**Comment by johnharris85** [comment]
@londoncalling it was fixed in #2972 :)

**Comment by londoncalling** [comment]
@johnharris85 nice, thanks!

**Comment by londoncalling** [comment]
Closing this issue as it is fixed per #2972
