### ISSUE TITLE
Feedback for: datacenter/dtr/2.2/guides/index.md

### ISSUE THREAD

**Issue by vikstrous** [docker/docker.github.io#1766]
File: [datacenter/dtr/2.2/guides/index.md](https://docs.docker.com/datacenter/dtr/2.2/guides/)

We should do a better job of pitching DTR  on this page. We should mention notary, security scanning and other big features such as detailed tag metadata.

**Comment by whoshuu** [comment]
The page should begin with a contents block a la wikipedia for jumping to each feature on the page once those features are added. The images are *yuge*, so it wouldn't be clear what's on the page without scrolling a lot first.
