### ISSUE TITLE
document how to manually resurrect DTR 2.2 from just the data from a rethinkdb volume

### ISSUE THREAD

**Issue by vikstrous** [docker/docker.github.io#1768]
### Problem description
It's technically possible to recover DTR to a usable state from just the contents of a rethinkdb volume from a cluster that's lost consensus, but we don't have a tool to do it or any documentation for how to do it. In DTR 2.2 this should be reasonably easy (as compared to 2.1 anyway).

### Problem location

DTR docs

### Project version(s) affected

DTR 2.2

### Suggestions for a fix

I plan to go through the steps, test them out and document them.

**Comment by vikstrous** [comment]
Update: this turned out to be more difficult than expected. We might be better off just implementing this feature in the product.

**Comment by joaofnfernandes** [comment]
This is kind of what the `docker/dtr backup` command does, so maybe it would make sense to extend that command to include this behavior.
I'm closing this docs issue since there's nothing to do here.
