### ISSUE TITLE
404 at: /userguide/dockerlinks/

### ISSUE THREAD

**Issue by remon-georgy** [docker/docker.github.io#177]
URL: /userguide/dockerlinks/

Brought by google search. Was expected documentation about linking containers.

**Comment by joaofnfernandes** [comment]
Thanks for reporting! In the meantime use https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

**Comment by johndmulhausen** [comment]
Fixed in bd630e9e3bed19c0f1f4c80166fff61536d3dc57

Thanks!
