### ISSUE TITLE
Feedback for: engine/reference/commandline/logs.md

### ISSUE THREAD

**Issue by alexryan** [docker/docker.github.io#1775]
File: [engine/reference/commandline/logs.md](https://docs.docker.com/engine/reference/commandline/logs/), CC: @mstanleyjones 

getting a full dump of the logs should be easy.
"docker logs" only shows a few lines.
"docker logs  --since 0" does NOT show all lines.

**Comment by mstanleyjones** [comment]
If you want to propose a feature to get all the logs for a container, please file it in the [`docker/docker`](https://github.com/docker/docker/issues/new) repository. Thanks!
