### ISSUE TITLE
Dockerfile question

### ISSUE THREAD

**Issue by stephaniepanah** [docker/docker.github.io#17837]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

The documentation ** may ** be incorrect. I am learning and I am unsure. 
I ran the git clone for getting-started. I am using VS Code 2022. 
Clicking the Windows tab it says to: Create an empty file name Dockerfile. 
However, there is a Dockerfile, already. Is this information to be overwritten with the #2; add the following contents......
Do I add the following, or overwrite? 

# syntax=docker/dockerfile:1
   
FROM node:18-alpine
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 3000

thank you, 
Stephanie

### Location

https://docs.docker.com/get-started/02_our_app/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Make sure you're in the correct directory. You should create the Dockerfile in the `app` subdirectory. If you see an existing Dockerfile, you're in the wrong directory.

#17771 will fix this.

**Comment by stephaniepanah** [comment]
Thank you for replying! question please. Is it alright to have two
dockerfiles in a project, as long as they are in different directories?

thanks,
Stephanie

**Comment by craig-osterhout** [comment]
Yes, you can have multiple Dockerfiles in a project, or even multiple Dockerfiles with different names in the same folder.

To learn more about `docker build` and specifying a path to the Dockerfile, see https://docs.docker.com/engine/reference/commandline/build/

**Comment by stephaniepanah** [comment]
Thank you. I appreciate that.
-s
