### ISSUE TITLE
Executing a "hot" backup for Swarm

### ISSUE THREAD

**Issue by pascalandy** [docker/docker.github.io#1793]
First thank you very much for having followed on https://github.com/docker/docker.github.io/issues/1072

We can read:

> It is possible to take a backup while the manager is running (a "hot" backup), but this is not recommended and your results will be less predictable when restoring.

Is there any plan to provide a safe way to do an hot backup ? Of course, no one will shut down their managers to do backups right ?

Thank you!

**Comment by mstanleyjones** [comment]
This is not a docs issue. Please file a feature request against the [moby/moby](https://github.com/moby/moby) repository. Thanks!
