### ISSUE TITLE
Using Secrets with DDC from the CLI and Compose file

### ISSUE THREAD

**Issue by banjot** [docker/docker.github.io#1805]
### Problem description
The current user guide docs in DDC for using secrets only talks about the GUI. It doesn't mention the CLI as a way to manage or interface with UCP to manage a secret. 

### Problem location
https://docs.docker.com/datacenter/ucp/2.1/guides/user/secrets/

### Project version(s) affected
UCP 2.1 

### Suggestions for a fix
We should document the CLI commands for secrets and mention how this works with UCP. It's essentially the same content as here: https://docs.docker.com/engine/swarm/secrets/#/example-use-secrets-with-a-service 

We should also include the fields necessary to use secrets from a compose file. Referenced in this forum message: https://forums.docker.com/t/secrets-stacks-and-odd-permissions/28340/6

**Comment by jmaitrehenry** [comment]
I take it!

**Comment by stevenhanna6** [comment]
claimed
