### ISSUE TITLE
Feedback for: compose/compose-file/index.md

### ISSUE THREAD

**Issue by c-jonua** [docker/docker.github.io#1808]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC: @londoncalling 

Block `restart_policy` contains the line with bad link:

> Configures if and how to restart containers when they exit. Replaces [restart](https://docs.docker.com/compose/compose-file/compose-file/#restart).

link https://docs.docker.com/compose/compose-file/compose-file/#restart referenced to a bad page (404)

**Comment by londoncalling** [comment]
Closing this issue, as the docs are fixed per the last referenced PR #2212 . As soon as this publishes, you should see the link working properly. Thanks!
