### ISSUE TITLE
Different compose file versions are confusing in Version 3 reference

### ISSUE THREAD

**Issue by olegmayko** [docker/docker.github.io#1809]
File: [compose/networking.md](https://docs.docker.com/compose/networking/)

Hi , I think it is a bit confusing that there are fragments of compose-file named version 2 or version 2.1 across the page named " Compose file version 3 reference" . 
then there are pieces without any references to a version 
https://docs.docker.com/compose/compose-file/#networks
The confusion is rather is it valid example for version 3 or version 2.1 , especially if you ran in error which hard to understand and little experience with working with docker-compose. 

thank you

**Comment by londoncalling** [comment]
### Hackathon Hints

- Please ignore the comments ^^ regarding the Compose file (https://docs.docker.com/compose/compose-file/#networks), which is up-to-date. (Any references to version 2 are in that file are valid as they describe features available in "version 2 and up.)

- Please update the code / config file examples in the file https://docs.docker.com/compose/networking/ from `version 2` to `version 3`. You will need to reference Compose file v3: https://docs.docker.com/compose/compose-file/, and make sure the examples map to version 3 formats and features.

**Comment by bdwill** [comment]
@londoncalling preference for 3 or 3.1?

**Comment by londoncalling** [comment]
@bdwill In terms of referencing a version, I suppose preference for simply 3 or just say 3.x. (The only exception would be if you use an example that includes a 3.1 only feature, then you would have to explicitly call out 3.1)

**Comment by mstanleyjones** [comment]
Closed via #2866

**Comment by londoncalling** [comment]
@shin- if you have any time in the future, would it be possible for you to review the changes on this PR to make sure that the examples fit v3 file format? (in terms of indent levels, keywords that got changed, etc.?). I don't feel very sure of myself catching all the fine details.
