### ISSUE TITLE
404 at: /reference/builder/

### ISSUE THREAD

**Issue by FJavierGil** [docker/docker.github.io#1818]
Referer: https://hub.docker.com/_/mysql/

"You can easily populate your mysql services by mounting a SQL dump into that directory and provide custom images with contributed data."

The link referred in "custom images" does not exist

URL: /reference/builder/

**Comment by JimGalasyn** [comment]
This issue appears to have been fixed, and the URL is forwarding correctly. Please let me know if you're still seeing this issue.
