### ISSUE TITLE
Pipe character in CLI docs create a new table column

### ISSUE THREAD

**Issue by whoshuu** [docker/docker.github.io#1822]
For example, [here](https://docs.docker.com/datacenter/dtr/2.2/reference/cli/install/#/options) for the `--nfs-storage-url` parameter.

Also shows up [here](https://docs.docker.com/datacenter/dtr/2.2/reference/cli/reconfigure/#/options).

**Comment by mstanleyjones** [comment]
I think this must have been fixed because I don't see it. :)
