### ISSUE TITLE
Feedback for: engine/admin/resource_constraints.md

### ISSUE THREAD

**Issue by jamshid** [docker/docker.github.io#1826]
File: [engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/), CC: @mstanleyjones 

The 1.13.0 docs do not describe the effect of using `--memory-swap=0`. The default is `-1` which means unlimited. Does `0` mean no swap will be allowed, or do I have to set `--memory` and `--memory-swap` to the same value to accomplish that?

https://docs.docker.com/engine/admin/resource_constraints/#/memory-swap-details

**Comment by mstanleyjones** [comment]
@thaJeztah I remember us discussing this before, quite a while ago. Did we get to the bottom of what `0` means?

**Comment by thaJeztah** [comment]
Hm, no, not sure I checked :blush:

**Comment by jamshid** [comment]
I think the description has changed recently to:

> If --memory-swap is set to the same value as --memory, and --memory is set to a positive integer, the effect is the same as setting --memory-swap to 0 (the value is treated as unset).

Is that right? How do I set --memory and --memory-swap such that it will not swap at all? I thought setting them both to the same value means no space is left for swap.

**Comment by ondrejhlavacek** [comment]
We came across the same question as @jamshid. It seems, that the docs is wrong. I wrote a simple test, that creates a 100M file and reads it to memory (in PHP)

```
docker run --rm --memory=128M php:7 sh -c 'truncate -s 100M /tmp/100M && php -d memory_limit=-1 -r "file(\"/tmp/100M\");"'
```

This runs just fine, the swap is set to 2*`memory`. It runs fine also when I set `--memory-swap=256M`. But when I set it manually to the same value as `memory`

```
docker run --rm --memory=128M --memory-swap=128M php:7 sh -c 'truncate -s 100M /tmp/100M && php -d memory_limit=-1 -r "file(\"/tmp/100M\");"'
```

this container is OOMKilled.

Tested on

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
and
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by mstanleyjones** [comment]
@justincormack PTAL and let me know if the doc needs to be changed. I think you helped us with this before.

**Comment by mstanleyjones** [comment]
I believe this was addressed in https://github.com/docker/docker.github.io/commit/9745a627ead0531c290a7ba7803cadb9c55e70bc. Please have a look at the page as it currently exists.

**Comment by ondrejhlavacek** [comment]
@mstanleyjones Thanks for the reply.

With the commands I provided earlier this statement does not seem correct

```
 +- If `--memory-swap` is set to the same value as `--memory`, and `--memory` is
 +  set to a positive integer, the effect is the same as setting `--memory-swap`
 +  to `0` (the value is treated as unset).

+- If `--memory-swap` is unset, and `--memory` is set, the container can use
 +  twice as much swap as the `--memory` setting, if the host container has swap
 +  memory configured.
```

I have verified (client v1.13.1) that setting `--memory=128M --memory-swap=128M` will OOMKill a container when its memory reaches 128M. and `--memory=128M` is stopped at 256M. 

It the configuration worked as described, what would be the settings to completely disable memory swap?

Thanks, Ondra

**Comment by mstanleyjones** [comment]
@cpuguy83 PTAL

**Comment by cpuguy83** [comment]
So, `--memory-swap` is not setting how much swap can be used, it's the total memory ("memory" + "swap") that can be used.

Setting the `--memory` and `--memory-swap` values to the same value means you can use at most  `<value>` memory, and that memory... that memory could be swap but only up to `<value>`

The default value for `--memory-swap` is 2x the `--memory` value.

Setting `-1` for the `--memory-swap` disables the swap limit, meaning the container can use all available swap space.

I believe setting `--memory-swappiness=0` this will make sure the container cannot write to swap at all.

**Comment by ondrejhlavacek** [comment]
@cpuguy83 If I set `--memory=128M --memory-swap=128M` and load a 128M file in memory, then the container will not be able to use further memory for swapping? (That's the behavior I'm observing).

The documentation says

> If `--memory-swap` is set to the same value as `--memory`, and `--memory` is  set to a positive integer, the effect is the same as setting `--memory-swap` to `0` (the value is treated as unset).

which is not what I understand from your comment, because it says that these are equal

 - `--memory=128M --memory-swap=128M` 
 - `--memory=128M --memory-swap=256M`
 - `--memory=128M --memory-swap=0`

**Comment by cpuguy83** [comment]
The 2nd and 3rd bullets are the same.
The first bullet is not.

**Comment by ondrejhlavacek** [comment]
Thanks for confirmation. I'd then consider the current documentation incorrect in this bullet 

![image](https://user-images.githubusercontent.com/497675/27930821-dc89f7dc-624c-11e7-981d-5d63cdde1f9d.png)

**Comment by cpuguy83** [comment]
I agree, this is incorrect.
