### ISSUE TITLE
History was not preserved on import of docs

### ISSUE THREAD

**Issue by stevvooe** [docker/docker.github.io#183]
Looks like docs were imported from upstream without preserving history. We lose a lot of authorship context that is very useful for archeaology.

**Comment by stevvooe** [comment]
BTW, this is really a two second process. Why wasn't this done? Extremely disappointing.

**Comment by mstanleyjones** [comment]
What files are missing history? We made a concerted effort to preserve all history, both in the master and vnext branches. The exception was content imported from private repos.

**Comment by stevvooe** [comment]
It looks like we lost history for shallow follows. `git blame` seems to be working fine.

Good job taking care of this! Sorry for the alarm. 🙇

**Comment by mstanleyjones** [comment]
The reason the shallow follows don't work is that all of these repos had unshared histories. It's frustrating that we lost some of the functionality but I was very happy that `git blame` could be made to work.

**Comment by stevvooe** [comment]
As long as I can blame!
