### ISSUE TITLE
Remove cadvisor from example host port mapping in swarm services

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#1840]
### Problem description

https://docs.docker.com/engine/swarm/services/#/publish-a-services-ports-directly-on-the-swarm-node should not provide an example of running cadvisor in a container as an example if cadvisor is known to cause problems with volumes https://docs.docker.com/engine/admin/troubleshooting_volume_errors/.

### Suggestions for a fix

Use any other app in the swarm services example.

**Comment by jmaitrehenry** [comment]
From slack:
me: Can we simplify the example by using nginx or redis?
johnharris85: ye nginx or tomcat or apache or whatever is probably a good example image for that

**Comment by t3h2mas** [comment]
Claiming

**Comment by t3h2mas** [comment]
https://github.com/docker/docker.github.io/pull/2939

**Comment by mstanleyjones** [comment]
Closed via #2939
