### ISSUE TITLE
Update command line syntax in networking guide

### ISSUE THREAD

**Issue by fosk06** [docker/docker.github.io#1844]
File: [engine/userguide/networking/index.md](https://docs.docker.com/engine/userguide/networking/), CC: @mstanleyjones 
I saw at least 2 command lines that seems to use an older syntax. I have the last docker version and on this version you have to replace " --network" by " --net".
Those lines are : 
"After you create the network, you can launch containers on it using the docker run --network=<NETWORK> option.
$ docker run --network=isolated_nw -itd --name=container3 busybox"
Regards

**Comment by shubheksha** [comment]
I'll take this one up!

**Comment by joaofnfernandes** [comment]
Unfortunatelly this is a non-issue. According to the [docker/docker:master](https://github.com/moby/moby/blob/master/cli/command/container/opts.go#L212) you should use the `--network` flag.

@shubheksha sorry for not catching this sooner. I'm closing your #2818 PR 😢

**Comment by shubheksha** [comment]
No issues!
Just to clarify: do I get points for this?

**Comment by joaofnfernandes** [comment]
Ye, don't sweat about it 😀
