### ISSUE TITLE
Secrets: "wordpress" Service errors out with "task: non-zero exit (1)"

### ISSUE THREAD

**Issue by sarahpark** [docker/docker.github.io#1848]
### Problem description

https://docs.docker.com/datacenter/ucp/2.1/guides/user/secrets/

I cannot finish the Secrets tutorial b/c the `wordpress` service returns errors:

<kbd>

<img width="1281" alt="screen shot 2017-02-17 at 6 29 57 pm" src="https://cloud.githubusercontent.com/assets/1562758/23089549/61486b00-f53f-11e6-9fcc-f99f5632c39b.png">

</kbd>

<kbd>

<img width="649" alt="screen shot 2017-02-17 at 6 33 11 pm" src="https://cloud.githubusercontent.com/assets/1562758/23089561/8ed1cbde-f53f-11e6-8b37-28a8770b83de.png">

</kbd>

<kbd>

<img width="630" alt="screen shot 2017-02-17 at 6 34 11 pm" src="https://cloud.githubusercontent.com/assets/1562758/23089569/b2a8236e-f53f-11e6-8bef-6156faf814d3.png">

</kbd>

<kbd>

<img width="638" alt="screen shot 2017-02-17 at 6 34 19 pm" src="https://cloud.githubusercontent.com/assets/1562758/23089571/bd034f50-f53f-11e6-8494-662184ad46a8.png">

</kbd>

---

Am I missing a config?

### Project version(s) affected
UCP 2.1.1-pr5289

**Comment by joaofnfernandes** [comment]
I'm not sure what's going on here, but I bet it's misconfiguration. Can you get the logs from one of the `wordpress` containers? Since you're using services and this will create multiple containers, you'll have to get the logs from the CLI.
Try:
```
docker ps -a
```

Find the id of a failed wordpress container and then

```
docker logs <container-id>
```

**Comment by sarahpark** [comment]
The `wordpress` containers keep getting created then exits. I can't seem to get the logs :thinking: 

![screen shot 2017-02-21 at 11 35 41 am](https://cloud.githubusercontent.com/assets/1562758/23181507/1162a856-f82a-11e6-8287-0c9d6671b40d.png)

**Comment by joaofnfernandes** [comment]
Yup, that's what I was looking for. This line

```
/usr/local/bin/docker-entrypoint.sh: line 20: /run/secrets/wordpress-password-v1: No such file or directory
```

You've created the secret, but when deploying the `wordpress` service you're not adding it to the service.

![b2a8236e-f53f-11e6-8bef-6156faf814d3](https://cloud.githubusercontent.com/assets/1525937/23182961/42c00e7a-f82f-11e6-8cf3-c2b4f93a4e0c.png)
