### ISSUE TITLE
Feedback for: engine/security/trust/trust_sandbox.md

### ISSUE THREAD

**Issue by jaimemartinez88** [docker/docker.github.io#185]
URL: [https://docs.docker.com/engine/security/trust/trust_sandbox.md](https://docs.docker.com/engine/security/trust/trust_sandbox/)

I cannot seem to run the example the current docker-compose.yml
When I start the containers I always get the following error from the trustsandbox container

cp: can't stat '/notarycerts/root-ca.crt': No such file or directory

I tried getting a root ca from GeoTrust and creating my own folder where I put the certificate but still no luck. I'm wondering if I need something else in my configuration?

Thanks in advance

**Comment by mstanleyjones** [comment]
Thanks for the report on this. We were able to fix it and the fix is now live.
