### ISSUE TITLE
Add commands for CentOS installation

### ISSUE THREAD

**Issue by Californian** [docker/docker.github.io#1850]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/), CC: @mstanleyjones
I would suggest adding the following commands to the installation instructions either for engine or compose, at least for CentOS 7.
```
sudo usermod -aG docker <username>
newgrp docker
```
Without the above commands, `docker-compose` fails because of a socket permission issue.

**Comment by prashant171992** [comment]
Raised a PR here : https://github.com/docker/docker.github.io/pull/2830

**Comment by prashant171992** [comment]
@JimGalasyn can u please review this PR ?

**Comment by mstanleyjones** [comment]
This is covered in the post-install instructions which are linked from each of the Linux installation topics. This is common across Linux distributions, and we don't want to duplicate it. Also, it is not strictly required for installation, as you can still run all the Docker commands using `sudo`.

You'll still get the credit, @prashant171992
