### ISSUE TITLE
Typo in getstarted/step_four.md

### ISSUE THREAD

**Issue by Neferseti** [docker/docker.github.io#1862]
File: [engine/getstarted/step_four.md](https://docs.docker.com/engine/getstarted/step_four/), CC: @mstanleyjones

There is a typographical error on this [page](https://docs.docker.com/engine/getstarted/step_four/) in 7th point of Step 1. It is not "fortunes", it is "fortune".

**Comment by mstanleyjones** [comment]
Thanks for reporting this, @Neferseti ! Would you like to try your hand at fixing it? If so, open the page (the link above works), click **Edit this page** at the right, make your correction, and submit a pull request. It's super easy!

**Comment by johndmulhausen** [comment]
This topic no longer exists.
