### ISSUE TITLE
Feedback for: Docker Quickstart Terminal

### ISSUE THREAD

**Issue by HoloSound** [docker/docker.github.io#187]
Docker Quickstart Terminal - shows:

Docker Machine is not installed. Please re-run the Toolbox Installer and try again.

Looks like something went wrong in step ´Looking for vboxmanage.exe´... Press any key to continue...
# ======

Maybe the updated VirtualBox  or the installed cygwin64 
results in above trouble.

My actual startup procedure:

Start: 
"cygwin64 Terminal"
Change Working direktory to
c:/Program\ Files/Docker\ Toolbox
execute  modified start.sh

Modifikation in start.sh: 

start.sh takes a WINDOWS ENVIRONMENT Variable VBOX_MSI_INSTALL_PATH with 
Back-Slash (windows like) PATH-partitioning.

The execution with Bach-Slashes wont work in cywin.

So I coded 

VBOXMANAGE=`echo "${VBOXMANAGE}" | sed -e 'sx\\\\x/xg'`

in line 34 - in front of execution of this command.

now I'm able to execute the script in cygwin ... and docker starts up.

REMARK:
At installation time of docker ToolBox should check if VBox is alread installed 
- and take the existing installation - instead of removing newer version ( 5.1.6 r110634)
  and installing an old one  ( 5.0.26).
  Maybe the same situation regarding the git installation.

**Comment by londoncalling** [comment]
@nathanleclaire can you take a look at this and see what you think? It's actually a suggestion for Toolbox install behaviour. I guess my questions are:

a. do you think it makes sense to implement anything like this at this point? (I suspect not), and more importantly

b.  is there anything I can add to the install docs or troubleshooting for Toolbox to clarify this issue?

**Comment by londoncalling** [comment]
Closing this issue, as it's not been reproduced.
