### ISSUE TITLE
Feedback for: engine/getstarted-voting-app/deploy-app.md

### ISSUE THREAD

**Issue by SegersIan** [docker/docker.github.io#1875]
File: [engine/getstarted-voting-app/deploy-app.md](https://docs.docker.com/engine/getstarted-voting-app/deploy-app/), CC: @mstanleyjones

In the very last step where they instruct you to run the command: `docker stack services <APP-NAME>` the output mismatched for me:

| ID       |     NAME    |         MODE   |     REPLICAS  IMAGE |
| --- |---| --- |--- |
| ...  | vote_db     |     replicated  0/1    |   postgres:9.4 |
| ...  | vote_visualizer | replicated  0/1  |      dockersamples/visualizer:stable |
| ...  | vote_worker   |   replicated  0/1     |  dockersamples/examplevotingapp_worker:latest |
| ...  | vote_redis     |  replicated  0/2     |  redis:alpine |
| ...  | vote_result    |  replicated  0/**1**      | dockersamples/examplevotingapp_result:before |
| ...  | vote_vote       | replicated  1/2      | dockersamples/examplevotingapp_vote:before |

There is only **1** replica for `vote_result`. For some reason, the majority of my services didn't launch but I guess that is because I made a mistake myself while following the tutorial.

I guess the issue is that this [commit](https://github.com/docker/example-voting-app/commit/45eb3aaf9d8373294936ddb4aff0d3b5ea023553) makes the documentation instructions inconsistent. Not sure how this change might escalate further in the tutorial.

**Comment by mstanleyjones** [comment]
@SegersIan can you please verify that the stack really didn't deploy? It can take some time. Services are "eventually consistent" so not everything happens right away. You can do `docker stack ls` and `docker service ls` to see.

**Comment by SegersIan** [comment]
The stack did deploy in the end correctly except for the `vote_result`. It did stick with just one replicate instead of two. So I guess it's just a matter of updating the *Example output* in the documentation. ( I know, we're talking really about a nitpick minor details here )

**Comment by londoncalling** [comment]
@SegersIan thanks for the feedback. I'm cc'ing @ManoMarks as I cannot replicate the problem you are seeing. (Also ccing @marcosnils and @AdHominem who commented on the referenced [commit](https://github.com/docker/example-voting-app/commit/45eb3aaf9d8373294936ddb4aff0d3b5ea023553).) 

I just redeployed everything, and checked, and am still getting the proper number of replicas  (as defined in the [`docker-stack.yml`](https://docs.docker.com/engine/getstarted-voting-app/#/docker-stackyml-deployment-configuration-file):

```
docker@manager:~$ docker stack deploy --compose-file docker-stack.yml vote
Updating service vote_visualizer (id: ya2vt9z2b4to248tccjjeqitw)
Updating service vote_redis (id: md73fohylg8q85aryz07852o0)
Updating service vote_db (id: gny9ieqxancnufrg1oeazz9gq)
Updating service vote_vote (id: 0ig0s4gb10q8auek9tris5i8z)
Updating service vote_result (id: lqwxjmmdhmegs2aw0a6ehipsp)
Updating service vote_worker (id: 8u4cfu60dtliz77x1o74kiwpr)
docker@manager:~$ docker stack services vote
ID            NAME             MODE        REPLICAS  IMAGE
0ig0s4gb10q8  vote_vote        replicated  2/2       dockersamples/examplevotingapp_vote:before
8u4cfu60dtli  vote_worker      replicated  1/1       dockersamples/examplevotingapp_worker:latest
gny9ieqxancn  vote_db          replicated  1/1       postgres:9.4
lqwxjmmdhmeg  vote_result      replicated  2/2       dockersamples/examplevotingapp_result:before
md73fohylg8q  vote_redis       replicated  2/2       redis:alpine
ya2vt9z2b4to  vote_visualizer  replicated  1/1       dockersamples/visualizer:stable
```

And the constraints seem to be working properly (e.g., `db`, `visualizer` services are running on the manager.

**Comment by ManoMarks** [comment]
In the example voting app, we reduced the number of replicas for the result app to 1. This was related to the use of a [load balancer](https://github.com/docker/example-voting-app/pull/67) causing issues with the websockets. If you're running locally, I've seen this issue have to do with memory or cpu availability on the host machine. If you're using Docker for Mac or Docker for Windows you can set that in the preferences, otherwise you can set it on the Docker daemon preferences.

**Comment by londoncalling** [comment]
@ManoMarks should I re-write the docs to show only 1 replica for the result app? I guess I wonder why I am getting 2 replicas per the configuration in the `.yml` if you changed this in the image ..?

**Comment by ManoMarks** [comment]
Sure, 1 replica is fine. It was changed as a result of a PR on the Example Voting App.

**Comment by londoncalling** [comment]
@SegersIan thanks for the feedback. I went ahead and modified the walkthrough in the docs to reflect the current configuration in the `docker-stack.yml` in the labs, so everything should match now. This should be published on the public docs site in about 30 mins per the referenced PR's above. Please re-open or comment on this issue if you see anything else related to this.
