### ISSUE TITLE
Feedback for: engine/reference/commandline/login.md

### ISSUE THREAD

**Issue by samprog1** [docker/docker.github.io#1878]
File: [engine/reference/commandline/login.md](https://docs.docker.com/engine/reference/commandline/login/), CC: @mstanleyjones 

The example is pretty misleading because of the Port 8080 usage. Isn't 5000 the default port for docker registry?

**Comment by mstanleyjones** [comment]
The content comes from https://github.com/docker/docker/blob/1.13.x/docs/reference/commandline/login.md, so please raise an issue  in `docker/docker` about this. Our files pull the long examples and descriptions from those upstream docs automatically.
