### ISSUE TITLE
404 at: /project/who-written-for/

### ISSUE THREAD

**Issue by marko-ciric** [docker/docker.github.io#188]
On a website, while navigating from https://www.docker.com/open-source to http://docs.docker.com/project/who-written-for/ through a _Start Contributing_ button, I got a `404` response (_Sorry, we can't find that page_).
Complete URL: https://docs.docker.com/sorry/#/project/who-written-for/.

**Comment by joaofnfernandes** [comment]
Looks like https://www.docker.com/open-source links to http://docs.docker.com/project/who-written-for/ which doesn't exist.

Repro
![1](https://cloud.githubusercontent.com/assets/1525937/19361392/5c724806-9137-11e6-93e8-46635d215420.gif)

**Comment by johndmulhausen** [comment]
Fixed in 1a9f1fdc349a0fc1cf835bfa08f5db0518f7bdb2
