### ISSUE TITLE
DDC Docs Does not point to the latest version of UCP 2.1 and DTR 2.2

### ISSUE THREAD

**Issue by leenamba** [docker/docker.github.io#1885]
### Problem description
https://docs.docker.com/docker-trusted-registry/
https://docs.docker.com/ucp/overview/

Does NOT point to the latest version of UCP 2.1 and DTR 2.2
### Problem location
- I saw a problem on the following URL: <URL>
https://docs.docker.com/docker-trusted-registry/
https://docs.docker.com/ucp/overview/

### Project version(s) affected
Current version of docs.docker.com

### Suggestions for a fix
UCP should point to https://docs.docker.com/datacenter/ucp/2.0/guides/
DTR should point to https://docs.docker.com/datacenter/dtr/2.1/guides/

**Comment by johndmulhausen** [comment]
Fixed manuals.md in 3d0a1d7544150ef3d8d5d68ec0e973ee7f76de4f

Unfortunately, those URLs are for legacy Datacenter installations. I agree it would be nice if those URLs were always kept up to date with the latest, but that's not where we are.
