### ISSUE TITLE
Feedback for: engine/examples/running_redis_service.md

### ISSUE THREAD

**Issue by fanzorena** [docker/docker.github.io#1891]
File: [engine/examples/running_redis_service.md](https://docs.docker.com/engine/examples/running_redis_service/), CC: @mstanleyjones

As from other documentation pages, the environment variables showed in this page are a deprecated method of getting information about the linked containers. Should be updated to the proper way of getting that information.

**Comment by mstanleyjones** [comment]
Please see https://docs.docker.com/samples/redis/, which is a more up-to-date doc. The other one will be deprecated. Thanks!

**Comment by mstanleyjones** [comment]
Topic no longer exists. See the other referenced topic.
