### ISSUE TITLE
docs: improve devicemapper configuration instructions

### ISSUE THREAD

**Issue by bgrissin** [docker/docker.github.io#19]
transferred to here from https://github.com/docker/docker/issues/27020

https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/for-a-direct-lvm-mode-configuration

This doc informs users to push all images to a remote registry and then informs to rm -f /var/lib/docker, thus removing everything including certs that may be stored under this directory tree. For good reasons, we instruct users to change from the default devicemapper loopback configuration that we recommended in early releases, of which they maybe running UCP on those nodes. Deleting the certs in /var/lib/docker/discovery_certs creates a far more complex recovery scenario than just copying the certs back after the lvm changes have been completed. This is the error received when you try to start up the docker daemon after following the doc instructions on a UCP node.

Initializing discovery with TLS
Error starting daemon: discovery initialization failed (Could not read CA certificate \ "/var/lib/docker/discovery_certs/ca.pem\" open /var/lib/docker/discovery_certs/ca.pem: no such file or directory

Can additional steps be written into the referenced doc perhaps such as copy the /var/lib/docker directory to /tmp to enable the recovery of items such as certs, etc in order to keep from placing users into extensive recovery scenarios. thnx

**Comment by mstanleyjones** [comment]
PTAL at the linked PR.

**Comment by mstanleyjones** [comment]
Fixed via #149
