### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntu.md / ubuntu-serena

### ISSUE THREAD

**Issue by mediafinger** [docker/docker.github.io#1902]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/), CC: @mstanleyjones 

Either the docs are not up-to-date, or there is an issue in the package for Linux Mint Serena:
(I followed the instructions and verified the fingerprint of the GPG key)

    $~ > sudo apt-get update
    Ign:1 http://ftp.fau.de/mint/packages serena InRelease
    Hit:2 http://ftp.caliu.cat/pub/distribucions/ubuntu/archive xenial InRelease                                    
    Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                                                                
    Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                                                  
    Hit:5 http://ftp.fau.de/mint/packages serena Release                                                                        
    Hit:6 http://ftp.caliu.cat/pub/distribucions/ubuntu/archive xenial-updates InRelease                                        
    Hit:7 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial InRelease                                                         
    Hit:8 http://archive.canonical.com/ubuntu xenial InRelease                                                                  
    Hit:9 http://ftp.caliu.cat/pub/distribucions/ubuntu/archive xenial-backports InRelease                                      
    Hit:10 http://dl.google.com/linux/chrome/deb stable Release                                               
    Get:12 https://dl.yarnpkg.com/debian stable InRelease [11,5 kB]                     
    Hit:13 https://deb.nodesource.com/node_7.x xenial InRelease                                 
    Ign:12 https://dl.yarnpkg.com/debian stable InRelease
    Ign:15 https://apt.dockerproject.org/repo ubuntu-serena InRelease
    Ign:16 https://apt.dockerproject.org/repo ubuntu-serena Release
    Ign:17 https://apt.dockerproject.org/repo ubuntu-serena/main amd64 Packages
    Ign:18 https://apt.dockerproject.org/repo ubuntu-serena/main i386 Packages
    Ign:19 https://apt.dockerproject.org/repo ubuntu-serena/main all Packages
    Ign:20 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en_US
    Ign:21 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en
    Ign:17 https://apt.dockerproject.org/repo ubuntu-serena/main amd64 Packages
    Ign:18 https://apt.dockerproject.org/repo ubuntu-serena/main i386 Packages
    Ign:19 https://apt.dockerproject.org/repo ubuntu-serena/main all Packages
    Ign:20 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en_US
    Ign:21 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en
    Ign:17 https://apt.dockerproject.org/repo ubuntu-serena/main amd64 Packages
    Ign:18 https://apt.dockerproject.org/repo ubuntu-serena/main i386 Packages
    Ign:19 https://apt.dockerproject.org/repo ubuntu-serena/main all Packages
    Ign:20 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en_US
    Ign:21 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en
    Ign:17 https://apt.dockerproject.org/repo ubuntu-serena/main amd64 Packages
    Ign:18 https://apt.dockerproject.org/repo ubuntu-serena/main i386 Packages
    Ign:19 https://apt.dockerproject.org/repo ubuntu-serena/main all Packages
    Ign:20 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en_US
    Ign:21 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en
    Ign:17 https://apt.dockerproject.org/repo ubuntu-serena/main amd64 Packages
    Ign:18 https://apt.dockerproject.org/repo ubuntu-serena/main i386 Packages
    Ign:19 https://apt.dockerproject.org/repo ubuntu-serena/main all Packages
    Ign:20 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en_US
    Ign:21 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en
    Err:17 https://apt.dockerproject.org/repo ubuntu-serena/main amd64 Packages
      403  Forbidden
    Ign:18 https://apt.dockerproject.org/repo ubuntu-serena/main i386 Packages
    Ign:19 https://apt.dockerproject.org/repo ubuntu-serena/main all Packages
    Ign:20 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en_US
    Ign:21 https://apt.dockerproject.org/repo ubuntu-serena/main Translation-en
    Fetched 114 kB in 2s (47,7 kB/s)
    Reading package lists... Done
    W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D101F7899D41F3C3
    W: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
    N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
    N: See apt-secure(8) manpage for repository creation and user configuration details.
    W: The repository 'https://apt.dockerproject.org/repo ubuntu-serena Release' does not have a Release file.
    N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
    N: See apt-secure(8) manpage for repository creation and user configuration details.
    E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-serena/main/binary-amd64/Packages  403  Forbidden
    E: Some index files failed to download. They have been ignored, or old ones used instead.

    $~ > sudo apt-get -y install docker-engine
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package docker-engine

**Comment by mstanleyjones** [comment]
We don't ship packages for Mint. There is a note in the Ubuntu installation doc (maybe wasn't there when you filed this) that says tat you may have to specify your parent Ubuntu version instead of using the `lsb_info` command. The parent for Mint Serena is Ubuntu 16.04 (xenial), so you need to use `ubuntu-xenial`. To map Mint to Ubuntu versions see https://en.wikipedia.org/wiki/Linux_Mint_version_history.
