### ISSUE TITLE
Feedback for: engine/getstarted-voting-app/customize-app.md

### ISSUE THREAD

**Issue by karptonite** [docker/docker.github.io#1919]
File: [engine/getstarted-voting-app/customize-app.md](https://docs.docker.com/engine/getstarted-voting-app/customize-app/), CC: @mstanleyjones 

It would be useful if, at the end of this tutorial, you included instructions on how to shut down the app gracefully, and remove what was installed.

**Comment by karptonite** [comment]
In particular, going through this tutorial sets env vars in such a way that you can no longer use Docker for Mac at the end, until you unset those variables. I figured that out pretty quick because I happened to have read the docs on that issue, but it might have been very annoying, otherwise.

**Comment by londoncalling** [comment]
@karptonite the Docker Machine environment variables that you set should not cause any problems with Docker for Mac. I've run this tutorial several times on Docker for Mac, and have no conflicts. 

I can add a section about shutting down the app, which essentially involves shutting down the `manager` and `worker` machines you created, and if desired, removing the machines.

Let me know what conflicts you ran into on Docker for Mac. You should just be able to open up new terminal windows, and continue working as before.

**Comment by karptonite** [comment]
The issue may have been that I continued to work in the same terminal window? I'll have to try again to confirm.

**Comment by ManoMarks** [comment]
I think it would be good to have a section on shutting down the app and the docker machine instances

**Comment by londoncalling** [comment]
@karptonite @ManoMarks

Per PR #1932 , I've added a **[new topic](https://docs.docker.com/engine/getstarted-voting-app/cleanup/)** on stopping the machines and the app, rebooting, and cleaning up altogether by removing the machines. 

I'll close this issue now, but feel free to re-open if needed to add more comments.

**Comment by londoncalling** [comment]
Closing this issue now, as it's resolved by the referenced PR ^^. Thanks for the great feedback!
