### ISSUE TITLE
Feedback for: docker-for-mac/osxfs.md

### ISSUE THREAD

**Issue by joemewes** [docker/docker.github.io#1923]
File: [docker-for-mac/osxfs.md](https://docs.docker.com/docker-for-mac/osxfs/), CC: @londoncalling 

Is it possible to get an official time-stamped update on this issue : https://github.com/docker/for-mac/issues/77 added to the docs. been relatively quiet for a few months.

**Comment by londoncalling** [comment]
@justincormack @samoht @jeanlaurent @rneugeba This is not something I can address in docs. Can someone in dev respond to @joemewes on the issue referenced ^^ ?

**Comment by joemewes** [comment]
I only ask because its already mentioned in the docs https://docs.docker.com/docker-for-mac/osxfs/#performance-issues-solutions-and-roadmap and wondered if this an appropriate place to ask Docker team for latest news on the issue. thanks

**Comment by johndmulhausen** [comment]
Feel free to continue the discussion, just want to close as this isn't an open docs issue.

**Comment by londoncalling** [comment]
@joemewes totally understand. I'll see if we can get some more feedback on this from Dev per this issue and the referenced one.
