### ISSUE TITLE
Troubleshoot article for DTR - waiting for DTR to start

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#1928]
When installing DTR, the installation might never finish and this message is displayed:

> INFO[0036] Waiting for DTR to start...

Review the command you've used to install DTR. If the `--replica-https-port`  and port in `--dtr-external-url` don't match, the installation might be successful but never return a success message.
Try accessing the DTR web UI and see the the DTR replica is healthy.

If it's not, use the `docker/dtr` destroy command, and try to install or join the replica again.

**Comment by johndmulhausen** [comment]
Closing due to no feedback; this seems more up Success' alley.
