### ISSUE TITLE
404 in API reference for Docker ID accounts API

### ISSUE THREAD

**Issue by klipitkas** [docker/docker.github.io#1940]
File: [docker-id/api-reference.md](https://docs.docker.com/docker-id/api-reference/), CC: @johndmulhausen 

Docker.io does not work for me, it redirects me to docker.com. Is this documentation still valid. What are the valid endpoints for this API so I can try some examples? Thanks.

**Comment by johndmulhausen** [comment]
This API has been deprecated and the doc removed
