### ISSUE TITLE
Feedback for: engine/extend/legacy_plugins.md

### ISSUE THREAD

**Issue by breuner** [docker/docker.github.io#1943]
File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/), CC: @mstanleyjones 
  
The BeeGFS volume plugin is missing in the list:  
https://github.com/RedCoolBeans/docker-volume-beegfs  
  
I tried using the "Edit page" link at the bottom to add it, but the link refers me to a "404 - Page not found".

**Comment by JimGalasyn** [comment]
It appears that this issue has been resolved.
