### ISSUE TITLE
Networking custom-docker0: Request for examples showing various configurations

### ISSUE THREAD

**Issue by schwimmfuzzi** [docker/docker.github.io#1946]
I would love to see better examples on how to use these configuration options above.

File: [engine/userguide/networking/default_network/custom-docker0.md](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/), CC: @mstanleyjones

**Comment by ashishkamat2791** [comment]
added to @schwimmfuzz 
I will take this up

**Comment by mstanleyjones** [comment]
Did you mean to submit a pull rquest for this? Make sure you submit the PR instead of referring to the issue in the commit message.
