### ISSUE TITLE
Feedback for: engine/getstarted-voting-app/node-setup.md

### ISSUE THREAD

**Issue by karptonite** [docker/docker.github.io#1953]
File: [engine/getstarted-voting-app/node-setup.md](https://docs.docker.com/engine/getstarted-voting-app/node-setup/)

Thanks for the great work on the Graceful shutdown in this tutorial.

Another issue I ran into was that, as a Docker for Mac user, I had never installed VirtualBox, so when I got to the about using docker-machine to create local virtual machines, it failed. I had to dig into the docs to see if I could do this with the driver included with Docker for Mac. (There was some warning about if you were using Docker for Windows, but as I was not, I unwisely skipped it). I ended up installing virtualbox so I could continue to follow the tutorial, but a more explicit explanation of what to do if you are on a Mac would be useful.

Separately, it would be nice to have a tutorial on how to use a compose file with tools that are compatible with the engine that DOES come with Docker for Mac (with Docker compose?). I assume that would mean not having multiple nodes, but multiple containers on a single node could still be useful--I am working to set up a dev environment that has multiple interacting containers, for example. Jumping straight from the single container tutorial to the multi-node, swarm tutorial without an intermediate step was kind of rough.

**Comment by londoncalling** [comment]
@karptonite , @ManoMarks - working on the first part of this, which is great - illuminated some holes in the docs. We have a short-term solution, and a great long-term one. Look for next iteration of docs in the next hour or so. I'll address the Docker Compose issue after that. Thanks!

**Comment by londoncalling** [comment]
@karptonite , @ManoMarks see updated docs here on [Set up Dockerized machines](https://docs.docker.com/engine/getstarted-voting-app/node-setup/).

Per your second point, I'll see what I can do re: adding in an example of working with a single-node Swarm, per @shkrid's nice write-up. I'll leave this issue open with regard to that point.

**Comment by londoncalling** [comment]
@karptonite I've added another topic to the "graceful shutdown" procedures per the PR #2244 

I'll merge this as soon as the build finishes running, so it should be published today.

I'm going to close this issue, as I experimented with a use case for running a pseudo multi-node swarm on Docker for Mac, and I don't think it's a useful path. The better solution will be for us to provide more samples e.g., using Docker Cloud with Swarm Mode, which we are starting to work on now.

With regard to ability run/test multiple local nodes on Docker for Mac and Docker for Windows (with something other than `docker-machine`), I'll pursue this feature request on another issue. It's come up before, although I'm not sure how likely it is, I do think it's a worthwhile request.

**Comment by karptonite** [comment]
@londoncalling Thanks! As for run multiple local nodes, or pseudo multi-node swarm, I don't think that was what I was looking for anyway, although I may bet getting lost in the terminology of a system I don't understand yet.

What I was (and still am) looking to do was to be able to spin up on my local machine (or any of our devs' local machines) a set of networked instances to emulate our production environment as closely as possible. That mean separate instances for our web server, our several dbs, memcached, etc, etc--maybe 7-10 instances talking to each other. Is that an unusual use case? Since it is for development, multiple nodes shouldn't be important (if I understand properly what a node is)--I was just going step by step through the tutorial when I hit swarms in the "Define and Deploy your app" section.

**Comment by londoncalling** [comment]
@karptonite I believe a better solution to this issue is on it's way with regard to the capabilities of Docker for Mac and Windows. Stay tuned to upcoming releases, and feel free to reach out again on this thread.
