### ISSUE TITLE
Feedback for: engine/swarm/ingress.md

### ISSUE THREAD

**Issue by Josh-West-Bose** [docker/docker.github.io#197]
URL: [https://docs.docker.com/engine/swarm/ingress.md](https://docs.docker.com/engine/swarm/ingress/)

This page seems to have gone missing from the Index/ToC on the left side of the documentation.

**Comment by mstanleyjones** [comment]
Thanks for the report. We now managed the TOC in a single file, and a few topics got missed when we did the migration. See #630 for the fix.
