### ISSUE TITLE
Feedback for: machine/examples/ocean.md

### ISSUE THREAD

**Issue by i-frost** [docker/docker.github.io#1972]
File: [machine/examples/ocean.md](https://docs.docker.com/machine/examples/ocean/), CC: @londoncalling 
How do we remove from 'docker-machine ls' when we accidentally on purpose removed it from the cloud provider?

**Comment by londoncalling** [comment]
@i-frost I see you closed this issue, but let me know if I can help. I'm not sure I understand, but it sounds like you want to know how to remove machines? Just answer on this comment and tag me if you need more help.

**Comment by i-frost** [comment]
Hi

Thanks email, I had shut down the droplet and I was trying to use kill to
remove it from machine ls output. I am used to using kill on Linux to
remove processes so I was confused!

Using rm worked just fine so that's why I closed the issue.

Thanks

On Feb 24, 2017 11:55 PM, "Victoria Bialas" <notifications@github.com>
wrote:

@i-frost <https://github.com/i-frost> I see you closed this issue, but let
me know if I can help. I'm not sure I understand, but it sounds like you
want to know how to remove machines? Just answer on this comment and tag me
if you need more help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker.github.io/issues/1972#issuecomment-282437362>,
or mute the thread
