### ISSUE TITLE
Recommended docker image remove syntax

### ISSUE THREAD

**Issue by pjamason** [docker/docker.github.io#1973]
File: [engine/getstarted/step_six.md](https://docs.docker.com/engine/getstarted/step_six/), CC: @mstanleyjones 

docker remove should be docker rmi, correct?

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by mstanleyjones** [comment]
Make note of your points for closing it!

**Comment by shubheksha** [comment]
Yes, I'll track them in a spreadsheet, thanks for the tip! :)
