### ISSUE TITLE
Recommended docker image remove syntax

### ISSUE THREAD

**Issue by 3body001** [docker/docker.github.io#1974]
File: [engine/getstarted/step_six.md](https://docs.docker.com/engine/getstarted/step_six/), CC: @mstanleyjones 

I can't find the following command in the latest version:
docker image remove 7d9495d03763

I think the it should be changed to: docker rmi -f 7d9495d03763

Following is my Docker version:
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

**Comment by JimGalasyn** [comment]
Duplicates #1973.
