### ISSUE TITLE
Need mapping of pre-1.13 to post 1.13 iptables handling

### ISSUE THREAD

**Issue by adamaig** [docker/docker.github.io#1978]
File: [engine/userguide/networking/default_network/container-communication.md](https://docs.docker.com/engine/userguide/networking/default_network/container-communication/), CC: @mstanleyjones

It seems like this document is out of sync with the recent changes to the iptables handling in version 1.13. It would be useful to have clear examples of different configuration option sets that yield a system with equivalent rules to the pre-1.13 behavior.

**Comment by stevenhanna6** [comment]
I'll take a shot at this one, claimed
