### ISSUE TITLE
Missing reference docs for `docker service create`?

### ISSUE THREAD

**Issue by hairyhenderson** [docker/docker.github.io#1981]
### Problem description

In #1829 a change was made to remove a bunch of docs that was apparently duplicated in the `docker/docker` repo, but after this change, it doesn't seem to be available anymore on the docs.docker.com site.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/engine/reference/commandline/service_create/

I expected to find this content:
https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md

### Suggestions for a fix

No idea, but I'm _guessing_ there may be something that needs to be re-generated?

**Comment by joaofnfernandes** [comment]
Can you try the url again? It seems to be working now.

**Comment by hairyhenderson** [comment]
@joaofnfernandes  The URL works, but is still missing the majority of the content for me.

**Comment by joaofnfernandes** [comment]
Oh, I get it now. It seems the information on that page was being managed both in this repo and docker/docker. We are now tracking that information in docker/docker. When building docs.docker.com we fetch the information from there, but this change as not been incorporated yet.

In the meantime you can find the information here
https://github.com/docker/docker/tree/master/docs/reference/

**Comment by mstanleyjones** [comment]
@tiborvass I think we need new YAML. The content is in the upstream Markdown files but it's not making it into the YAML here. Please advise. cc/ @FrenchBen

**Comment by joaofnfernandes** [comment]
@tiborvass it seems that a bunch of users are being impacted by this. There's anything I can do to help accelerate a fix for this?

**Comment by joaofnfernandes** [comment]
@mstanleyjones with #2330 merged, this issue is fixed, right?

**Comment by hairyhenderson** [comment]
Awesome - thanks @tiborvass & @joaofnfernandes & @mstanleyjones - I can confirm it's _fixed_ :tada:
