### ISSUE TITLE
Feedback for: engine/getstarted-voting-app/cleanup.md

### ISSUE THREAD

**Issue by ischyrus** [docker/docker.github.io#1984]
File: [engine/getstarted-voting-app/cleanup.md](https://docs.docker.com/engine/getstarted-voting-app/cleanup/), CC: @mstanleyjones 
I'm pretty sure that step two is suppose to take down the manager and worker. Not the worker twice?

**Comment by JimGalasyn** [comment]
It appears that this issues has been fixed.
