### ISSUE TITLE
Rendering issue with inline code snippet

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#1990]
File: [opensource/workflow/work-issue.md](https://docs.docker.com/opensource/workflow/work-issue/), CC: @johndmulhausen

The file name "docker.go"  in the table in section "How to work on your local branch" is not correctly displayed in code style.

**Comment by bdwill** [comment]
dibs for hackathon

**Comment by bdwill** [comment]
well :)

**Comment by prashant171992** [comment]
@bdwill u claimed it first mate !

**Comment by londoncalling** [comment]
@prashant171992 This content still has rendering issues. Please see the following in the Netlify preview: https://deploy-preview-2836--docker-docs.netlify.com/opensource/workflow/work-issue/#how-to-work-on-your-local-branch .

- HTML tags: `</tbody> </table>` are showing at the top of the table
- The code tagging is extending beyond the `docker.go` file into the sentence describing it, and there is a `</p>` tag 
_ `</td> </tr>` is showing within the table

One of the problems can be solved by changing: `<code>docker.go<code>` to `<code>docker.go</code>`

**Comment by prashant171992** [comment]
@londoncalling yeah, that caused the issue , thanks for pointing it out . I fixed it.

**Comment by londoncalling** [comment]
Fixed by @prashant171992 per PR #2836
