### ISSUE TITLE
Feedback for new navigation

### ISSUE THREAD

**Issue by MattacksWTW** [docker/docker.github.io#2002]
File: [engine/admin/systemd.md](https://docs.docker.com/engine/admin/systemd/), CC: @mstanleyjones

Left-hand menu does not work properly on Internet Explorer 11.

**Comment by apihlaja** [comment]
Dunno how it behaves in IE11 but it doesn't work on Chrome either (version: 56.0.2924.87 (64-bit) (Windows)).

When trying to scroll, menu goes below footer so some of the menu entries are unreachable.

Steps to reproduce:

1. Go to https://docs.docker.com/
2. Open "Manage a swarm" tree from left menu.
3. Try to reach last items of the submenu ("Raft consensus in swarm mode").

**Comment by johndmulhausen** [comment]
It's only on the home page, but yes, this is my Pri 1 fix right now. Thanks, all

**Comment by londoncalling** [comment]
I believe this is fixed by PR #2860 (if it hadn't been fixed previously).
