### ISSUE TITLE
Clarify behavior of docker build with a URL fragment

### ISSUE THREAD

**Issue by charly-vega** [docker/docker.github.io#2005]
It'd be nice to warn about `docker build` not doing a shallow git clone when specifying a URL with a fragment (see [gitutils.go#L45-L56](https://github.com/docker/docker/blob/master/pkg/gitutils/gitutils.go#L45-L56)), as the "Extended description > Git repositories" section doesn't clarify that to be the case.

File: [engine/reference/commandline/build.md](https://docs.docker.com/engine/reference/commandline/build/), CC: @mstanleyjones

**Comment by gschaetz** [comment]
I got this one

**Comment by mstanleyjones** [comment]
Being reviewed upstream.

**Comment by mstanleyjones** [comment]
I don't think you did this one, did you @gschaetz ? It isn't the same as the `docker attach` one you did upstream. I'm going to remove it from the hackathon milestone for now.

**Comment by mstanleyjones** [comment]
@thaJeztah do you have info on this?

**Comment by gschaetz** [comment]
Yes it got merged here a34f9b0 I made a mistake and two commits were together

**Comment by thaJeztah** [comment]
Yup looks to be there in https://github.com/docker/cli/commit/80a7f5dec763dcdc99d0e1ce49ddeb7b8fc81b03#diff-1aa9e7be44e56c4d74dfb00fd9be3bdb let me close this one
