### ISSUE TITLE
Deploy DDC on Azure

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2006]
We don't have any documentation guiding users in doing an end-to-end deployment of DDC on Azure.

Also, Docker Store has this content
<img width="707" alt="screen shot 2017-02-27 at 16 23 26" src="https://cloud.githubusercontent.com/assets/1525937/23386060/31090e96-fd09-11e6-844b-b521634c7044.png">

**Comment by JimGalasyn** [comment]
Fixed by #2796.

**Comment by joaofnfernandes** [comment]
When trying to download EE standard/advanced from store.docker.com, we are sending users to the [Azure marketplace](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/docker.dockerdatacenter?tab=Overview), which has a link about the installation but the url is pointing to success.docker.com. It would be cool to sync with the editions team to fix that link to point to the article you created.

Maybe @FrenchBen can help with that?

**Comment by uday-shetty** [comment]
Let me know the correct link.

**Comment by joaofnfernandes** [comment]
@uday-shetty it should be https://docs.docker.com/datacenter/install/azure/
