### ISSUE TITLE
Feedback for: engine/getstarted/step_three.md

### ISSUE THREAD

**Issue by rmizrahi-fullstack** [docker/docker.github.io#2009]
File: [engine/getstarted/step_three.md](https://docs.docker.com/engine/getstarted/step_three/), CC: @mstanleyjones

you asked 'can you break it?'... 

sudo docker run docker/whalesay cowsay 'hello' select *; sudo yum update

I'm pretty sure you're aware of that, but... heh... that was fun!

**Comment by JimGalasyn** [comment]
lulz, that would do it.
