### ISSUE TITLE
Feedback for: docker-cloud/infrastructure/link-aws.md

### ISSUE THREAD

**Issue by chrisvire** [docker/docker.github.io#201]
URL: [https://docs.docker.com/docker-cloud/infrastructure/link-aws.md](https://docs.docker.com/docker-cloud/infrastructure/link-aws/)

Following these instructions, I get "Invalid AWS role or insufficient permissions" when I try to add AWS Credentials.

**Comment by sanscontext** [comment]
Hey @chrisvire, thank you for your feedback. It sounds like this is a problem with your AWS permissions, and not an issue with the docs. Please file a Docker support ticket or check out
https://forums.docker.com/ to see if you can find a solution.
 
If you determine after working with Support that this is really is a documentation issue, please reopen it with more information.
