### ISSUE TITLE
Rendering issue with code snippet in list

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#2012]
File: [opensource/kitematic/set_up_dev.md](https://docs.docker.com/opensource/kitematic/set_up_dev/), CC: @johndmulhausen

In section "Clone your repository locally and create a branch", the line space and code style in step 4 are not properly displayed. However, it looks all right on the "Preview changes" tab while no change is made on the "Edit file" tab. Is this because some paragraphs around here are wrapped at much longer than 80 column lines? Really curious about this which I've encountered several times.

**Comment by orthros** [comment]
I'll take a look

**Comment by allejo** [comment]
@orthros you working on this?

**Comment by orthros** [comment]
@allejo I was but got pulled off. Sorry for late reply & thanks for forging ahead!

**Comment by johndmulhausen** [comment]
In the end, @allejo gets the points for this fix. Thanks!

**Comment by allejo** [comment]
👍 

sorry for stealing your thunder @orthros

**Comment by orthros** [comment]
@allejo no need to be sorry! Glad it got closed 😄
