### ISSUE TITLE
UI text format: bold or quotes?

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#2017]
File: [opensource/kitematic/create_pr.md](https://docs.docker.com/opensource/kitematic/create_pr/), CC: @johndmulhausen

In the following sentences, the button text is displayed in bold:

- Click **Compare & pull request**.

- Click **Create pull request**.

But the documentation guide says as follows:

> Text taken from a GUI (e.g., menu text or button text) should appear in “double quotes”. The text should take the exact same capitalisation, etc. as appears in the GUI. E.g., Click “Continue” to save the settings.

So, should we change them to double quotes instead of bold, or both are acceptable? Now, it seems that some docs use double quotes for such text (such as the one involved in #1991 ) and some others use bold.

**Comment by JimGalasyn** [comment]
UI text should be bold.

**Comment by shubheksha** [comment]
I'll fix the docs style guide for this one!
