### ISSUE TITLE
Missing Extended Description for system events

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker.github.io#2025]
Extended description of the command for `docker system events` is not copied over from https://docs.docker.com/engine/reference/commandline/events/ to https://docs.docker.com/engine/reference/commandline/system_events/.

This is very useful information and should be copied over.

**Comment by michaelspets** [comment]
I'll take this one up!

**Comment by mstanleyjones** [comment]
I'm raising the points of this because we discovered that a whole new file needed to be committed to the upstream moby repo!

**Comment by mstanleyjones** [comment]
@michaelspets and @jmaitrehenry share this one.

**Comment by mstanleyjones** [comment]
Review has shifted upstream, so closing this here. Thanks @michaelspets!
