### ISSUE TITLE
DTR install instructions should talk about UCP UI

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2026]
The UCP settings page has a snippet that you can copy-paste to install DTR. Our docs should leverage this to avoid having people inputting the wrong command and having to troubleshoot.

**Comment by prashant171992** [comment]
I'm working on this.

**Comment by joaofnfernandes** [comment]
@prashant171992 let me know if you need help deploying DDC to test this out

**Comment by prashant171992** [comment]
it can be made open for all , though will work on it tomorrow morning (midnight here).

**Comment by mstanleyjones** [comment]
Thanks @prashant171992 please feel free to submit your work for this. I'm sorry it didn't make it in time for the hackathon!
