### ISSUE TITLE
Document browser versions supported by DDC

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2027]

**Comment by anweiss** [comment]
@joaofnfernandes ... any updates on getting this published? Need compatibility matrices published for both UCP and DTR

**Comment by joaofnfernandes** [comment]
We'll document the list of browsers once the product team comes up with the list of browsers that we officially support and test.

**Comment by johndmulhausen** [comment]
Stalled until we start testing browsers and officially adopt certain browser support levels

**Comment by joaofnfernandes** [comment]
The [compatibility matrix](https://success.docker.com/article/compatibility-matrix) is going to cover this once EE 2.0 goes live.
