### ISSUE TITLE
docs concerning dns-config for Ubuntu are outdated

### ISSUE THREAD

**Issue by funkyfuture** [docker/docker.github.io#203]
this concerns the docs at https://docs.docker.com/engine/installation/linux/ubuntulinux/#/configure-a-dns-server-for-use-by-docker

i followed the instructions to configure the DNS to be used, i also knew from prior experiences that it had worked.

however, today i installed Docker on an Ubuntu 16.04 for the first time and i took me a while do figure out that setting the `DOCKER_OPTS` in `/etc/default/docker` does not work, but i had to create a `/etc/docker/daemon.json` and store the config in it.

**Comment by konstruktoid** [comment]
Hi @funkyfuture, the document states:

> The instructions below describe how to configure the Docker daemon running on Ubuntu 14.10 or below. Ubuntu 15.04 and above use systemd as the boot and service manager. Refer to control and configure Docker with systemd to configure a daemon controlled by systemd.

**Comment by funkyfuture** [comment]
hm, maybe it would be more obvious if this information was directly placed under the section's heading and be more emphasized. i was simply scrolling down to the sample configuration that seemed relevant to me as the installation comes with the described file.

furthermore, the page that deals with a systemd configuration doesn't mention the `daemon.json` at all, neither the dns options. for two reasons that would be helpful. many people don't want to tinker with systemd configs for different reasons, i also prefer configuration files that are system agnostic. a missing dns config is a showstopper right from the start for people experimenting with Docker.

is the `/etc/default/docker` file to be used on systems with systemd anyway? if it is obsolete, it shouldn't be provided by the package.

**Comment by konstruktoid** [comment]
I agree with you @funkyfuture about the location of the systemd information, but `daemon.json` isn't related to either sysvinit  or systemd.
`/etc/default/docker` is kind of a debian/ubuntu tradition and used in older versions. Provided due to backward compability.

**Comment by funkyfuture** [comment]
i'm aware that `daemon.json` doesn't relate to an init system. that is why i prefer it. a note that this file is also an option to configure a daemon wouldn't hurt, would it?

it doesn't make sense to provide a file for backward-compatibility if it doesn't have any effect.

**Comment by julianfoad** [comment]
I too find the "Configure a DNS server for use by Docker" section puzzling, right from the start, as the introductory paragraphs say:

> Systems that run Ubuntu ... typically use 127.0.0.1 ...
> When starting containers ..., Docker users see this warning:
> > WARNING: Local (127.0.0.1) DNS resolver found in resolv.conf and containers
> > can't use it. Using default external servers : [8.8.8.8 8.8.4.4]

I'm running Docker 1.12.3, and I don't see that warning. So at this point I'm already thinking there's something wrong with this documentation. If it is out of date, please update it; if not, please clarify it.

**Comment by mstanleyjones** [comment]
Thanks for the suggestions. I'll review this topic and see what I can do to make it easier to understand. By the way, updating to Ubuntu 16.04 means that you now need to use `/etc/sysconfig/docker`. I just addressed that this morning (see #625) but it's not yet merged.

**Comment by mstanleyjones** [comment]
Sorry it took so long, but this is now fixed, along with quite a lot more rewrites. Please take a look and let me know if it helps.

**Comment by julianfoad** [comment]
That looks much clearer now regarding my concern. Thanks for the work.
