### ISSUE TITLE
Formatting example causes template parse error

### ISSUE THREAD

**Issue by nschoe** [docker/docker.github.io#2036]
File: [engine/admin/formatting.md](https://docs.docker.com/engine/admin/formatting/), CC: @mstanleyjones 

Just to let you know that the example for the `join` template function doesn't work:

```Bash
$> docker ps --format '{{join .Names " or "}}'
Template parsing error: template: :1:7: executing "" at <.Names>: wrong type for value; expected []string; got string
```

For information:

```
 docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by mstanleyjones** [comment]
@vieux @vdemeester any ideas?

**Comment by vdemeester** [comment]
Hum, this won't work on `ps` (and any `ls` command I think) for now. Almost any field of those command (`Names`,`Labels`, …) return a string (and do their own `join` behind the scene). I think the example should be done on `inspect` commands only for now.

But I think we need to fix that in the engine 👼 too.

**Comment by nschoe** [comment]
Okay no problem, it's just the the documentation page _explicitly_ uses `docker ps` for the example, this is why.

I perfectly understand that it's just easy to switch command an try in `inspect`. But I know for a fact (hanging on IRC #docker) that Go templates are a mystic creature for a lot of people, so they avoid it like the pleague. I think if they find good, nice example on this doc page, it _might_ help spread the love.
But if the first example that they come across doesn't event work, I'm afraid they go "damn ,if even the docker devs can't get it right, I'm staying away from this magic" :)

Anyway, thanks for the answers in the short delays, as usual, congrats guys!

**Comment by vdemeester** [comment]
@nschoe yep, completely agreeing with you. We should update this example.

**Comment by nschoe** [comment]
I've looked into this, this is not actually not easy to find an actual value from the inspection that returns a list of string ^^

Most often, this returns a maps with key:value. So.... I'll let you guys handle this :D

**Comment by johnharris85** [comment]
Claimed.

**Comment by jburnett** [comment]
Shouldn't this work for other docker commands like images?  

```
C:\> docker image ls --format "{{join .Repository ':' }}"
Template parsing error: template: :1:7: executing "" at <.Repository>: wrong type for value; expected []string; got string

```
