### ISSUE TITLE
Feedback for: engine/installation/linux/index.md

### ISSUE THREAD

**Issue by kbeto** [docker/docker.github.io#2038]
File: [engine/installation/linux/index.md](https://docs.docker.com/engine/installation/linux/), CC: @mstanleyjones 

I think the ubuntu repository is not correct. Shouldn't it be https://apt.dockerproject.org/repo/dists/ubuntu-$(lsb_release -cs)/main/ ?

**Comment by mstanleyjones** [comment]
No, the thing after the URL is the directory. So in this case, "main" is the directory where `apt-get` will look for the `Releases` file which tells it where everything is.

**Comment by kbeto** [comment]
Yes, you are right
