### ISSUE TITLE
Feedback for: index.md

### ISSUE THREAD

**Issue by max11992** [docker/docker.github.io#2039]
File: [index.md](https://docs.docker.com/), CC: @johndmulhausen
hi,
i wanna download the documentation to read this without to be online all the time is there any way to download the full documentation(pdf or epub)?
This is really a thing search on google.com for docker documentation: search suggestions box will show up with: "docker documentation pdf" and 2docker documentation download"

Thx
Max

**Comment by johndmulhausen** [comment]
@max11992 Best method is to just run this:

`docker run -ti -p 4000:4000 docs/docker.github.io`

That will let you read the docs offline via localhost on http://localhost:4000/
