### ISSUE TITLE
--ucp-node flag is mandatory, no sample invocation of restore, --dtr-load-balancer undocumented

### ISSUE THREAD

**Issue by bryceryan-docker** [docker/docker.github.io#2046]
File: [datacenter/dtr/2.2/reference/cli/restore.md](https://docs.docker.com/datacenter/dtr/2.2/reference/cli/restore/), CC: @joaofnfernandes 

Since the --ucp-node flag is now mandatory (per the DTR 2.2 release notes), it would be helpful to mention that. If there are other flags that are required, it would be helpful to mention that fact.

Similarly, it would be helpful to provide an example invocation or two and sample output from a restore.

Lastly, the page this is referenced from (https://docs.docker.com/datacenter/dtr/2.2/guides/admin/backups-and-disaster-recovery/) uses this flag
--dtr-load-balancer <dtr-domain-name> < /tmp/backup.tar
which is not documented on this page

**Comment by joaofnfernandes** [comment]
@bryceryan-docker the article mentioning `--dtr-load-balancer` seems to be outdated. It should be `--dtr-external-url`.
