### ISSUE TITLE
Pasting CLI sample gives errors in shell

### ISSUE THREAD

**Issue by lythix** [docker/docker.github.io#2049]
File: [engine/reference/commandline/inspect.md](https://docs.docker.com/engine/reference/commandline/inspect/), CC: @mstanleyjones

Cut and pasting from these documents gives errors. 
For example:
$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 98e5c425bc96
Template parsing error: template: :1: unexpected unclosed action in range

**Comment by mstanleyjones** [comment]
I can't reproduce this. If it is still happening to you, please supply the output of `docker version`.

**Comment by johndmulhausen** [comment]
Closing due to no response
