### ISSUE TITLE
Post-launch cleanup items

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#2052]
- [x] Josh: Auto-resizing of left-nav doesn't work on homepage
- [x] Josh: Speed up the scroll animation (clicking on the right-hand menu and scrolling is feeling sluggish)
- [x] Josh: Still see the top nav wrapping at < desktop resolutions - e.g. the version dropdown
- [x] Josh: Jumpiness in resizing of right-nav due to jquery animation, which triggers a ton of scrolling that the handler can't parse in real-time
- [x] Josh: Right nav should hide first, not left nav
- [x] Josh: Right nav is overlapping content, z-index style, in < `large` screen widths
- [x] Josh: Search button looks silly on results page
- [x] John: We lost keyboard highlighting in the search autocomplete popup, though you can click on the previews and get there
- [x] Josh: [Disable wrapping on inline code blocks](https://github.com/docker/docker.github.io/issues/2052#issuecomment-283677146)
- [x] Josh: [Mobile header covers up page title and cycles through colors](https://github.com/docker/docker.github.io/issues/2052#issuecomment-283745550)
- [x] Josh: Horizontal scrollbar on wide code samples, rather than line wrapping, [like this](https://docs.docker.com/docker-id/api-reference/#list-email-addresses-for-a-user).
- [ ] Josh: No longer any difference between notes, warnings, info admonitions (all blockquotes are blue)
- [x] John: Tabs not working; Bootstrap incompatibility? https://docs.docker.com/engine/api/
- [x] John: Ship new favicons
- [x] John: Publish /v1.13/
- [x] John: Headings should be clickable and go to the anchor for that heading (sidelining for now)

cc @jsouth

**Comment by thaJeztah** [comment]
Disable wrapping on inline code blocks, to prevent confusing output such as (wrapping after the `-`);

<img width="904" alt="screen shot 2017-03-02 at 16 01 07" src="https://cloud.githubusercontent.com/assets/1804568/23512635/9707172e-ff61-11e6-91d5-54e81a83eaf9.png">

**Comment by johndmulhausen** [comment]
@jsouth Mobile header is covering up the page title and cycling through colors, even on sub-pages.

https://goo.gl/photos/CLtPZtLpX1sTh1Wj8

**Comment by johndmulhausen** [comment]
Fixed inline code blocks in 0d24ad1b1b59a3f7a0ff7603f56946838d2ba9e3

**Comment by londoncalling** [comment]
- [ ] On the mobile docs, on all but the Home page (Guides), the page title and top of the content on each page is hidden by the colour-changing banner (see attached image)

- [ ] The text on images seems to blur (e.g., look at the diagram on the Voting App sample tutorial [here](https://docs.docker.com/engine/getstarted-voting-app/#what-youll-learn-and-do).

- [ ] In general, the text is not sharp, seems a little dulled or blurry (even the text, outside of the images)

- [ ] Is there a way to allow for in-line images? See the whale icon on https://docs.docker.com/docker-for-mac/install/#install-and-run-docker-for-mac. Right now it's getting pushed onto its own separate line in the web rendering.

These are some things we already discussed, just adding them here for the record:

- [ ] Command / code text formatted with backticks `like this` should look differently when it's link text than not (e.g., code formatted links should display as bright blue, or some other indicator that they are links). Right now linked text with backticks looks no different than plain text.

**Comment by programmerq** [comment]
Some forum issues:

- [ ] In Firefox (reported with firefox 46 and tested with firefox 45), the css doesn't allow for text to be visible when choosing a title for a New Topic: 
![image](https://cloud.githubusercontent.com/assets/37278/23921283/ad381d70-08c3-11e7-8771-69f6bc5d2151.png)
- [ ] "Sign In" button in theme header takes you to docker cloud login. The actual discourse login is a separate "Log In" button that is not in the header. The "Sign In" button could probably be removed on the forum since it doesn't do what is expected (log you in to the forum).

**Comment by johndmulhausen** [comment]
@programmerq This is the repo for the docs. I think you'll have to use an internal contact to route feedback about the forums. Reassigning @jsouth.

**Comment by jsouth** [comment]
@programmerq - Cool. thanks for info and catching these bugs in the forum. I can assist with getting these in the queue to be fixed and we will move this topic to the forum specific area. thanks!

**Comment by joaofnfernandes** [comment]
Tabs for some code samples seem to be broken
<img width="720" alt="screen shot 2017-03-14 at 15 44 39" src="https://cloud.githubusercontent.com/assets/1525937/23925588/285debac-08cd-11e7-8f60-029e0ab9dc6b.png">

**Comment by johndmulhausen** [comment]
@joaofnfernandes @jsouth Joao's comment is illustrating the third to last checkboxed item in the original post. :)

**Comment by johndmulhausen** [comment]
Bug report on mobile problems, with possible solution, cc @jsouth: 

https://github.com/webcompat/web-bugs/issues/4958

**Comment by jsouth** [comment]
: UPDATE :

Working through all items listed above +  other mobile issues. Nearing completion on all items and will publish the current change-set.

Few highlights:
- Font size and color have both been increased for better readability.
- All css has been converted to sass
- Night mode styles have been updated for future use.

Have a little more cleanup + testing to work through tomorrow.

**Comment by jsouth** [comment]
: UPDATE : 

Auto-resizing of left-nav doesn't work on homepage
**Resolved: http://recordit.co/vwh3vhuSGb**

Speed up the scroll animation (clicking on the right-hand menu and scrolling is feeling sluggish)
**- Reviewed : no work needed at this time.**

Still see the top nav wrapping at < desktop resolutions - e.g. the version dropdown
**- Resolved: http://recordit.co/nPRFil4KM7**

Jumpiness in resizing of right-nav due to jquery animation, which triggers a ton of scrolling that the handler can't parse in real-time
**- Noted and could replicate, but not consistently. Please provide assistance if possible.**

Right nav is overlapping content, z-index style, in < large screen widths
**- Resolved: http://recordit.co/OigbUDngUc**

**Comment by joaofnfernandes** [comment]
"Mobile header covers up page title and cycles through colors" is marked as resolved, but it seems users are still being affected.

https://twitter.com/durdiness/status/847520728685719552

**Comment by johndmulhausen** [comment]
Closing this old guy. It has served its purpose. We should have more individual/focused bugs for any docs site behavior that looks weird.
