### ISSUE TITLE
Same page reference links are mallformed on the docs compose page. 

### ISSUE THREAD

**Issue by clemenko** [docker/docker.github.io#2053]
### Problem description
When looking at 
https://docs.docker.com/compose/compose-file/
ANY of the links that reference tags on the same page show a mallformed URL and show the resulting "Page not Found"

![screen shot 2017-03-02 at 9 43 06 am](https://cloud.githubusercontent.com/assets/3177276/23511947/f4389862-ff2c-11e6-89bd-6534bc75cffe.jpg)

When clicking through the page results with a URL of "https://docs.docker.com/sorry/#/compose/compose-file/%7B%7B%20page.url%20%7D%7D/"

![bad_links](https://cloud.githubusercontent.com/assets/3177276/23512045/49fc9474-ff2d-11e6-8e44-69c2da050d4d.gif)

### Problem location
https://docs.docker.com/compose/compose-file/

### Project version(s) affected
Current docs.docker.com

### Suggestions for a fix
The MD looks clean. Looks like a possible rendering issue.

**Comment by joaofnfernandes** [comment]
This seems to have been a temporary hiccup and is now fix.
@clemenko can you still reproduce this?

**Comment by clemenko** [comment]
Fixed.
