### ISSUE TITLE
404 at: /opensource/coding-style/

### ISSUE THREAD

**Issue by dsheets** [docker/docker.github.io#206]
URL: /opensource/coding-style/

from https://docs.docker.com/opensource/workflow/work-issue/#how-to-work-on-your-local-branch

**Comment by lynnaloo** [comment]
I was going to do a PR for this issue, but it looks like there is no longer a coding style guide in `opensource`. There is just `code.md`, which doesn't look like a style guide.

**Comment by konstruktoid** [comment]
@lynnaloo, I hope/believe it's https://github.com/docker/docker.github.io/blob/master/opensource/workflow/coding-style.md
