### ISSUE TITLE
swarm_join: --availability option not implemented

### ISSUE THREAD

**Issue by arvenil** [docker/docker.github.io#2065]
File: [engine/reference/commandline/swarm_join.md](https://docs.docker.com/engine/reference/commandline/swarm_join/)

The doc states that this command has an option `--availability` but docker command doesn't seem to have it. Actually this is more than a doc issue as this option is important. Without it I can't join network as manager and deploy without some containers ending in current manager.

From the doc
```
Options
Name, shorthand 	Default 	Description
--advertise-addr 	  	Advertised address (format: <ip|interface>[:port])
--availability 	active 	Availability of the node (active/pause/drain)
--listen-addr 	0.0.0.0:2377 	Listen address (format: <ip|interface>[:port])
--token 	  	Token for entry into the swarm
```

```term
$ docker --version
Docker version 17.03.0-ce, build 60ccb22

$ docker swarm join --help

Usage:	docker swarm join [OPTIONS] HOST:PORT

Join a swarm as a node and/or manager

Options:
      --advertise-addr string   Advertised address (format: <ip|interface>[:port])
      --help                    Print usage
      --listen-addr node-addr   Listen address (format: <ip|interface>[:port]) (default 0.0.0.0:2377)
      --token string            Token for entry into the swarm
```

**Comment by mstanleyjones** [comment]
The feature is only available in Docker 17.04, which is an Edge release. See the same document in the `/edge/` directory: https://docs.docker.com/edge/engine/reference/commandline/swarm_join/

**Comment by arvenil** [comment]
@mstanleyjones Now I don't see this option in any doc, not in current or edge

**Comment by arvenil** [comment]
@mstanleyjones Now I don't see this option in any doc, not in current or edge

![docker_swarm_join_-_docker_ce_edge_documentation](https://cloud.githubusercontent.com/assets/450355/24932024/f402fb3c-1f0f-11e7-89f0-19ff793498dd.png)
