### ISSUE TITLE
Docker daemon time units: milli- or microseconds?

### ISSUE THREAD

**Issue by tsjnsn** [docker/docker.github.io#2067]
File: [engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/)

There are instances where the units of 'microseconds' is converted incorrectly to seconds. 1 second is 1000000 microseconds. Not sure if it's the wording or units which needs to be fixed. 

line 152: Under *Configure the Docker daemon*
"10000 microseconds (1 second)"

Possibly also in line 106, assuming the same error: Under *Configure the default CFS scheduler*
"Defaults to 1 second, expressed in micro-seconds."

**Comment by mstanleyjones** [comment]
This will require looking at the `docker/docker` code to figure out what the code actually says.

**Comment by bdwill** [comment]
dibs for hackathon

Apparently fixed in another issue, file only references microseconds.

**Comment by mstanleyjones** [comment]
Thanks! You get the points!
