### ISSUE TITLE
Multiline CLI samples don't paste correctly in bash 

### ISSUE THREAD

**Issue by pondohva** [docker/docker.github.io#2069]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

Hello.
New markdown engine brokes new lines in code samples. Commands with backslash but without new lines don't work in bash.

was:
```
$ sudo yum remove docker \
                  docker-common \
                  container-selinux \
                  docker-selinux \
                  docker-engine
```

become:
```
$ sudo yum remove docker \ docker-common \ container-selinux \ docker-selinux \ docker-engine
```

**Comment by mstanleyjones** [comment]
Already fixed.
