### ISSUE TITLE
--it should be -it

### ISSUE THREAD

**Issue by jesseolsen** [docker/docker.github.io#2072]
File: [engine/admin/logging/overview.md](https://docs.docker.com/engine/admin/logging/overview/)

 docker run --it --log-opt max-size=10m --log-opt max-file=3 alpine ash

should be:

 docker run -it --log-opt max-size=10m --log-opt max-file=3 alpine ash

**Comment by johndmulhausen** [comment]
Fixed in 81de59357a78e2e8f1b0ddacf0d0f6eb0f1f2244
