### ISSUE TITLE
HA redirect needs to be updated

### ISSUE THREAD

**Issue by tfoxnc** [docker/docker.github.io#2073]
http://docs.docker.com/ucp/high-availability/set-up-high-availability/ redirects to the old version of UCP instead of the most recent.

Please update this link so it goes to the most current version.

**Comment by joaofnfernandes** [comment]
@tfoxnc that url existed for UCP 1.1, if we change it we will also be changing any bookmarks, tweets, and posts that were written for that version specifically.
If you found that URL being used in content we control and want to point it to UCP 2.1 you can link to https://docs.docker.com/datacenter/ucp/2.1/guides/admin/configure/set-up-high-availability/

**Comment by tfoxnc** [comment]
Not sure of the origin of the link. I found it in our kbase: https://success.docker.com/KBase/Why_do_I_get_a_warning_when_I_have_only_two_controllers%2F%2Fmanagers_in_my_cluster%3F along with 3 other UCP articles with similar redirects. I was thinking it would be nice to have them always updated to the latest version so the kbase content doesn't change - just the redirect, but if you think it might affect other references, then I can just update our links to the latest version of UCP.

**Comment by johndmulhausen** [comment]
@tfoxnc Please update the link in the Success article; these URLs are baked into the product which means the redirects have to stay as-is.

**Comment by johndmulhausen** [comment]
@tfoxnc Here's the latest URL: https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/set-up-high-availability/
