### ISSUE TITLE
Feature request: filtering on 'docker nodes ls' works with node.labels.*

### ISSUE THREAD

**Issue by jamespedwards42** [docker/docker.github.io#2075]
File: [engine/reference/commandline/node_ls.md](https://docs.docker.com/engine/reference/commandline/node_ls/)

Filtering is only applied to engine labels.  Had to do some issue digging to see that it is still an unresolved issue. +1 for the intuitive approach of filtering on `docker nodes ls` to work with node.labels.*

https://github.com/docker/docker/issues/28209
https://github.com/docker/docker/issues/27231

**Comment by mstanleyjones** [comment]
This is not a Docs issue. If the feature becomes available, we will document it then. :) Please file your feature request in the `docker/docker` project.

**Comment by jamespedwards42** [comment]
@mstanleyjones Sorry, I intended it be a documentation issue until the (feature is added)/(bug is fixed).  In the context of the `docker node` command I think it is reasonable to assume that filters would be applied to `node labels`.  However, unexpectedly they are applied to `engine labels`.  A simple comment explicitly stating that filtering is applied to `engine labels` only, will probably save people time.

**Comment by heathweaver** [comment]
I agree that this should be improved in the documentation, it's not clear and the example gives the impression one should be able to filter on node labels as you update the label on the node command. 

https://stackoverflow.com/questions/40026638/how-do-i-filter-docker-swarm-nodes-by-label
