### ISSUE TITLE
Change gerund form of verbs (-ing) to non-gerund form in topic

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#2082]
File: [engine/swarm/join-nodes.md](https://docs.docker.com/engine/swarm/join-nodes/)
At the beginning of this doc:

> To take full advantage of swarm mode you can add nodes to the swarm:
> 
> - Adding worker nodes increases capacity. xxx
> - Manager nodes increase fault-tolerance. xxx
> 

Will it be better if the two items in the list using parallelism, such as:

To take full advantage of swarm mode you can add nodes to the swarm:

 - Adding worker nodes increases capacity. xxx
 - Adding manager nodes increases fault-tolerance. xxx

Or:

To take full advantage of swarm mode you can add nodes to the swarm:

 - Worker nodes increase capacity. xxx
 - Manager nodes increase fault-tolerance. xxx

Only my ideas. Perhaps it's unnecessary to change as sentence flexibility helps make a doc, even a technical doc, have interesting qualities. But sometimes it's difficult for me to find a balance. Look forward to your suggestions. Thanks.

**Comment by joaofnfernandes** [comment]
@scjane looks like this issue is now worth 25 points for the #hackathon at DockerCon. Even if you're joining us at DockerCon you can fix this and claim your points!  [More info](https://docs.docker.com/hackathon/)

**Comment by scjane** [comment]
#dibs
