### ISSUE TITLE
Document support, and steps to install on different architectures

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#2085]
The current installation instructions hard-code `amd64` as an architecture, but different architectures may be available (the current download.docker.com does not have index files, so it's not possible to navigate / discover which architectures are available);

<img width="887" alt="screen shot 2017-03-03 at 10 51 11" src="https://cloud.githubusercontent.com/assets/1804568/23546371/8e29bac8-ffff-11e6-9029-00c0982e5f25.png">

We should also update the support matrix to show which architectures and distro _versions_ are supported;

<img width="926" alt="screen shot 2017-03-03 at 10 50 55" src="https://cloud.githubusercontent.com/assets/1804568/23546453/e9f8a3fa-ffff-11e6-81a6-8b1d1c3d61bd.png">

Or, possibly better, have a table/matrix per distro (and version) to show what's supported. In the past, we've seen confusion about supported versions (especially with non-LTS versions of Ubuntu and Fedora). Perhaps we can automatically generate these tables as part of the release process?

Version | Docker EE | Docker CE | Notes
---|---|---|---
**Ubuntu 12.04 (LTS)** | -  | - | EOL, docker-engine &lt; 1.13 
**Ubuntu 14.04 (LTS)** | ✅   | ✅  | |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;amd64 | ✅   | ✅  | |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;armhf | ✅   | ✅ ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;arm64 | - | - ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ppc64le | - | - ||
**Ubuntu 16.04  (LTS)** | ✅   | ✅  | |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;amd64 | ✅   | ✅  | |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;armhf | ✅   | ✅ ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;arm64 | - | - ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ppc64le | - | - ||
**Ubuntu 16.10** | -   | ✅  | |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;amd64 | ✅   | ✅  | |
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;armhf | -   | - ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;arm64 | - | - ||
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ppc64le | - | - ||

/cc @andrewhsu @friism @vieux

**Comment by andrewhsu** [comment]
I agree. Would be helpful to have more info in the table about architecture support.

**Comment by thaJeztah** [comment]
@mstanleyjones FWIW, @andrewhsu mentioned on Slack that it would probably be possible to generate the matrix; which would definitely be preferably to keep it in sync

**Comment by mstanleyjones** [comment]
I'm all for having the matrix be automatically generated. How would that work?

As for the ARM architecture and a first pass at addressing architectures in the matrix, see #2382.
