### ISSUE TITLE
Swarm-mode: same token for worker and manager nodes

### ISSUE THREAD

**Issue by nschoe** [docker/docker.github.io#2088]
File: [engine/swarm/swarm-mode.md](https://docs.docker.com/engine/swarm/swarm-mode/)

Hi again,
I'm sorry I have opened several issues regarding the docs these past couple of days, but I just want to help. Because I love docker and want to help.

So in this page, first, it is said:

> The token for worker nodes is different from the token for manager nodes. 

And then:

```Bash
$ docker swarm join-token worker

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-49nj1cmql0jkz5s954yi3oex3nedyz0fb0xx14ie39trti4wxv-8vxv8rssmk743ojnwacrr2e7c \
    192.168.99.100:2377

This node joined a swarm as a worker.
$ docker swarm join-token manager

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-49nj1cmql0jkz5s954yi3oex3nedyz0fb0xx14ie39trti4wxv-8vxv8rssmk743ojnwacrr2e7c \
    192.168.99.100:2377
```

In the docs, the tokens are **exactly the same** ^^

So is it just a typo in the docs or are the token actually the same? (I haven't upgraded to 17.03 so I can't test it, but either way, we need to fix this mitake:) )

**Comment by bdwill** [comment]
dibs for hackathon

**Comment by mstanleyjones** [comment]
@bdwill did you intend to open a PR? Please open a PR instead of referencing the issue by ID in the commit message itself. To open a PR, go to the **Pull Requests** tab, choose **New pull request**,  choose "across forks", and then select your fork and branch.

**Comment by jmaitrehenry** [comment]
@mstanleyjones did https://github.com/docker/docker.github.io/pull/2971 close this issue or need to update the doc?
