### ISSUE TITLE
Feedback for: engine/getstarted/step_six.md

### ISSUE THREAD

**Issue by roipoussiere** [docker/docker.github.io#2092]
File: [engine/getstarted/step_six.md](https://docs.docker.com/engine/getstarted/step_six/)

Maybe I missed something but when deleting the docker image, this command:

    docker image remove 7d9495d03763

do not works as is, it must be force removed since it shares the same id:

> Error response from daemon: conflict: unable to delete f855f1349f30 (must be forced) - image is referenced in multiple repositories

So, the working command is:

    docker image remove -f 7d9495d03763

Then the werd part is when I try to pull images, dockers says that all dependencies still exists locally:

```
$ docker run roipoussiere/test
Unable to find image 'roipoussiere/test:latest' locally
latest: Pulling from roipoussiere/test
e190868d63f8: Already exists 
909cd34c6fd7: Already exists 
0b9bfabab7c1: Already exists 
a3ed95caeb02: Already exists 
00bf65475aba: Already exists 
c57b6bcc83e3: Already exists 
8978f6879e2f: Already exists 
8eed3712d2cf: Already exists 
bb9f9e5ee91a: Already exists 
```

---

Docker version 17.03.0-ce, build 3a232c8
CentOS Linux release 7.3.1611

**Comment by johndmulhausen** [comment]
Instructions fixed in https://github.com/docker/docker.github.io/pull/2095

As for why certain layers exist, that's tough for us to diagnose without knowing what else you've downloaded. Docker is smart enough to share layers from all over so that you only download once.

**Comment by roipoussiere** [comment]
> As for why certain layers exist, that's tough for us to diagnose without knowing what else you've downloaded

I have followed step by step the Getting Started tutorial.
