### ISSUE TITLE
Feedback for: engine/getstarted/step_six.md

### ISSUE THREAD

**Issue by KPressley** [docker/docker.github.io#2094]
File: [engine/getstarted/step_six.md](https://docs.docker.com/engine/getstarted/step_six/)

When I type docker image remove, it returns that image is not a docker command.
In the --help information I see docker rmi. Is that the command that should be used here?

**Comment by johndmulhausen** [comment]
Fixed in https://github.com/docker/docker.github.io/pull/2095
