### ISSUE TITLE
Docker-for-azure: Cloudstor is not pre-installed

### ISSUE THREAD

**Issue by jbrjake** [docker/docker.github.io#2096]
File: [docker-for-azure/persistent-data-volumes.md](https://docs.docker.com/docker-for-azure/persistent-data-volumes/)

"Cloudstor a volume plugin managed by Docker. It comes pre-installed and pre-configured in swarms deployed on Docker for Azure."

But it's not pre-installed and pre-configured if you use stable. I just ran an install of the stable Community Edition template, and it's not listed as a plugin. Per this link, it's only available in beta, and I can't find that caveat documented anywhere else: https://forums.docker.com/t/cloudstor-volume-plugin-missing/29080/4

**Comment by alfonso-cabrera** [comment]
Submitted PR #2888 for this.
