### ISSUE TITLE
 Clarify whether a unique repository can be used both for Debian and Raspbian

### ISSUE THREAD

**Issue by jcberthon** [docker/docker.github.io#2098]
File: [engine/installation/linux/debian.md](https://docs.docker.com/engine/installation/linux/debian/)

Previous version of this document had clearer instruction on how to setup the Deb repository for Raspbian. In current release, Raspbian is still mentioned in the supported OS, but there is no longer a specific version for it.

Current document state:

```
$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
```

It seems that for Raspbian we could possibly use:

```
$ sudo add-apt-repository \
   "deb [arch=armhf] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
```

But that does not work. The `add-apt-repository` command does not work on Raspbian. What I did is the following:

```
$ echo "deb [arch=armhf] https://download.docker.com/linux/debian \
   $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
```

That seems to work and I am able to install `docker-ce` but when doing `sudo apt-get update` I have the following warning:

```
W: Conflicting distribution: https://download.docker.com jessie InRelease (expected jessie but got )
```

Anyway, previous Docker release (e.g. 1.13.1) supported Debian and Raspbian for armhf (there was 2 distinct deb packages). The documentation is unclear now if a unique repository can be used for both Debian and Raspbian.

**Comment by sandor-juhasz** [comment]
I have ran into the same issue today. Another workaround until the page is fixed is to follow the quick install command from the Raspberry PI homepage's Docker article at https://www.raspberrypi.org/blog/docker-comes-to-raspberry-pi/ It will install the latest CE version.

**Comment by NonCreature0714** [comment]
I'm working on this 💯  @mstanleyjones @londoncalling

**Comment by londoncalling** [comment]
Fixed by PR #2893

**Comment by jcberthon** [comment]
I cannot reopen this issue, but I'm going to propose a PR for this issue with slightly different changes which in my opinion are not perfect but getting closer what it should be.

**Comment by jcberthon** [comment]
@londoncalling @sandor-juhasz @NonCreature0714 

Perhaps you could all have a look at my 2 PRs and let me know what you think?

One is about consistency so that the Debian specific parts stays pure Debian (and not a mixture of Debian/Raspbian).

The other PR is about correcting the Raspbian specific part. I have checked the `.deb` package content and there is the `/etc/bash_completion.d/docker` file which is used for Bash completion. There was also other erroneous statement which I have corrected (after double checking them of course) :-)

**Comment by NonCreature0714** [comment]
@jcberthon I'll take a look for sure! 😎

**Comment by jcberthon** [comment]
The series of PR that followed the PR which stated it fixes this issue have done the countrary to solve that issue.

As far as I can tell from #2966 is that neither the script nor the old repository URL are long term solutions for Raspbian. So either the documentation should recommend using the Debian for armhf solution or another one. But currently as far as I understood, the installation steps for Raspbian should be considered deprecated.

Cc: @londoncalling (maybe you could reopen the issue in order for the right people to discuss that point and decide what is the proper fix. I cannot propose a PR because I cannot conclude anything from the discussion on #2966)
