### ISSUE TITLE
A typo in the running containers part of docs

### ISSUE THREAD

**Issue by Vikranttyagi95** [docker/docker.github.io#21006]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### There is a slight typo in the document at https://docs.docker.com/engine/containers/run/ where the line is:

"The daemon generates a random string name for containers automatically. You can also defined a custom name using [the --name flag](https://docs.docker.com/reference/cli/docker/container/run/#name)." 

### Location

https://docs.docker.com/engine/containers/run/

### Suggestion

It should be:

"The daemon generates a random string name for containers automatically. You can also define a custom name using [the --name flag](https://docs.docker.com/reference/cli/docker/container/run/#name)."

**Comment by dvdksn** [comment]
Thanks for reporting; the fix for this has been merged upstream, and will be updated with the next engine release.
