### ISSUE TITLE
Less marketing focus on "Why Docker on Azure?" page

### ISSUE THREAD

**Issue by habibcs** [docker/docker.github.io#2101]
File: [docker-for-azure/why.md](https://docs.docker.com/docker-for-azure/why/)
This page has extreme customer/sales oriented fancy documentation - same thing 3 times!
Be more focus and use your strength - technical and openness instead of commercial jargons

**Comment by frankgreco** [comment]
#dibs

**Comment by mstanleyjones** [comment]
ANy update, @frankgreco ? You still have to the end of Friday!

**Comment by johndmulhausen** [comment]
Closing as WAI
