### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntu.md

### ISSUE THREAD

**Issue by ylavoie** [docker/docker.github.io#2103]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/)
Accessing the repository gives : 
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2FEC0ECDCCFF0BD3</RequestId>
<HostId>
MGaazoRr76lXA+4vRobyNyYTbG/NPb6uskelJajYCB0fypqX80txx5OAPpjItXYTXDzLmglj4y0=
</HostId>
</Error>

Either unlock of change the doc accodingly

**Comment by thaJeztah** [comment]
The index pages are currently missing for download.docker.com (see https://github.com/docker/docker/issues/31987), which results in showing a 403 if there's no file found at an URL.

I'm not sure what the exact URL's are for the packages; if you require offline installation, you can download the `docker-engine` package, which is the old name for the `docker-ce` package, and can be found here; http://apt.dockerproject.org/repo/pool/main/d/docker-engine/

**Comment by andrewhsu** [comment]
@ylavoie apologies for the bad link. The correct URL for downloading the docker-ce package for ubuntu is within the subdirectory of https://download.docker.com/linux/ubuntu/dists/; navigate to the subdirectory for your ubuntu version, channel, and architecture within the pool directory. For example, for xenial version, stable channel, amd64 architecture, navigate to https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/ and download the .deb package for the Docker version you want.
