### ISSUE TITLE
404 link to daemon repo

### ISSUE THREAD

**Issue by bofm** [docker/docker.github.io#2108]
File: [engine/admin/logging/log_tags.md](https://docs.docker.com/engine/admin/logging/log_tags/)

logging_context link is invalid

**Comment by scjane** [comment]
#dibs

**Comment by shubheksha** [comment]
This issue is a duplicate of #2300 and #2430. It can be closed.

**Comment by johndmulhausen** [comment]
Thanks @scjane and @shubheksha. 25 points to @shubheksha for identifying the duplicate.
