### ISSUE TITLE
404 at: /docker-for-mac/index/  and /docker-for-mac/index#/where-to-go-next

### ISSUE THREAD

**Issue by wstevo4891** [docker/docker.github.io#2113]
URLs: /docker-for-mac/index/   and   /docker-for-mac/index#/where-to-go-next

Broken links

**Comment by mstanleyjones** [comment]
Use absolute links rather than relative.

**Comment by shubheksha** [comment]
Can you clarify on which page did you notice the error?

**Comment by jmaitrehenry** [comment]
I just search for relative link but don't find any broken link, I think we could close this issue.

**Comment by prashant171992** [comment]
both of these links redirect to https://docs.docker.com/docker-for-mac/

**Comment by mstanleyjones** [comment]
Thanks @jmaitrehenry
