### ISSUE TITLE
scp option doesn't work on Windows 10

### ISSUE THREAD

**Issue by benriga** [docker/docker.github.io#2114]
File: [engine/getstarted-voting-app/deploy-app.md](https://docs.docker.com/engine/getstarted-voting-app/deploy-app/)

On Windows 10, the command: docker-machine scp <filename> manager:/home/docker/. does not work for me.

I get the error: "You must have a copy of the scp binary locally to use the scp feature"

**Comment by shubheksha** [comment]
Will this be added as a Windows-specific note in the docs?

**Comment by johndmulhausen** [comment]
This topic no longer exists.
