### ISSUE TITLE
Change Docker Hub references to Docker Store   

### ISSUE THREAD

**Issue by smbkr** [docker/docker.github.io#2115]
File: [engine/getstarted/step_three.md](https://docs.docker.com/engine/getstarted/step_three/)

Should be updated to reflect that the docker/whalesay image is now located at https://store.docker.com/community/images/docker/whalesay and not at Docker Hub. It would probably be beneficial to explain the difference between Docker Store and Hub.

**Comment by mstanleyjones** [comment]
This should be throughout the doc set.

**Comment by shubheksha** [comment]
I'll take this one up!

**Comment by shubheksha** [comment]
Do all links referring to images in the hub be changed to Docker Store?

**Comment by johndmulhausen** [comment]
This topic no longer exists.
