### ISSUE TITLE
Request for Linux-focused instructions in Voting App topic

### ISSUE THREAD

**Issue by paulanthonybland** [docker/docker.github.io#2116]
File: [engine/getstarted-voting-app/node-setup.md](https://docs.docker.com/engine/getstarted-voting-app/node-setup/)

The page talks about docker-machine for windows and Mac. I am using Linux, and not touching those other two. So what do I do? The page says nothing about what to do on Linux which leaves me completely confused.

**Comment by johnharris85** [comment]
Actually not too many changes here, as you'll still need machine for Linux (for ease of having 2 machines). Probably all the mac OS instructions should be labeled as Linux too.

I'll take a look / claim this.

**Comment by johndmulhausen** [comment]
This topic no longer exists, but @johnharris85 will get points for #2837.
