### ISSUE TITLE
Missing section about creating services using templates

### ISSUE THREAD

**Issue by calind** [docker/docker.github.io#2118]
The section https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#create-services-using-templates is missing from documentation. 

I couldn't find it neither in https://docs.docker.com/engine/reference/commandline/service_create/ nor https://docs.docker.com/engine/swarm/services/. Actually I wasn't able to find it in the docs.

**Comment by mbentley** [comment]
See https://github.com/docker/docker.github.io/issues/1981

**Comment by joaofnfernandes** [comment]
I'm closing this as a duplicate of #1981, you can follow any updates there.
