### ISSUE TITLE
Update environment variable names for DOCKER_TAG and CACHE_TAG

### ISSUE THREAD

**Issue by arlofaria** [docker/docker.github.io#2125]
File: [docker-cloud/builds/advanced.md](https://docs.docker.com/docker-cloud/builds/advanced/)

The docs suggest that the `DOCKER_TAG` environment variable will be set to the name of the image tag that is currently being built/tested... e.g. `latest` or another user-configured tag.  

However, I have seen that `DOCKER_TAG` is instead always set to the string `"this"`

Meanwhile, I've noticed that there is an environment variable named `CACHE_TAG` and that is indeed set appropriately to what I would have expected `DOCKER_TAG` to be.

Is that expected?  Should the docs be updated?

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by mstanleyjones** [comment]
No action for two days, so this is up for grabs!

**Comment by shubheksha** [comment]
I'd still like to work on this.
