### ISSUE TITLE
Screenshot shows manager node's IP address instead of worker node's

### ISSUE THREAD

**Issue by uthinkso** [docker/docker.github.io#2126]
File: [engine/getstarted-voting-app/test-drive.md](https://docs.docker.com/engine/getstarted-voting-app/test-drive/)

On the second screen shot (ie. the result web page), the ip address on the picture is 192.168.99.101 which is the worker's ip in this tutorial instead of the manager's ip. Please check and update.

**Comment by bdwill** [comment]
dibs for hackathon

**Comment by johndmulhausen** [comment]
This topic no longer exists. Don't worry, you'll still get the points for the fix, @bdwill.

**Comment by mstanleyjones** [comment]
Points to @bdwill
