### ISSUE TITLE
Add note about build-time variables in FROM directive

### ISSUE THREAD

**Issue by andras-tim** [docker/docker.github.io#2127]
File: [engine/reference/commandline/build.md](https://docs.docker.com/engine/reference/commandline/build/)

**Note:**
I miss a note about you can't use build-time variables in `FROM` directive.

**Comment by johnharris85** [comment]
Don't this is applicable anymore as `ARG` _can_ now be used in a `FROM` directives (since 17.05 I believe).

**Comment by mstanleyjones** [comment]
@johnharris85 17.05 is not out yet, so any docs for it need to go in `vnext-engine`. For posterity for 17.03 (which is LTS so will be supported for a year), it would be great to have the current behavior documented. Then it will be correct when archived.

Want to take it on?

**Comment by johnharris85** [comment]
Sure, looks like it's in [moby/moby](https://github.com/moby/moby/blob/master/docs/reference/commandline/build.md) though.

**Comment by mstanleyjones** [comment]
Yes, if it is in there, then our `vnext-engine` branch will vendor it in, and no action needed here. If you want to correct the description of behavior in the upstream repo, please raise your PR there against their `17.03.x` branch instead of their `master` and make note of that in the PR comments.

**Comment by mstanleyjones** [comment]
Re-file upstream in `docker/cli` repo if you still want this.
