### ISSUE TITLE
Mention that ubuntu 24.04 lts is not fully supported

### ISSUE THREAD

**Issue by CristianArean** [docker/docker.github.io#21304]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Docker Desktop crash with sigtrap in ubuntu 22.04 LTS, the issue is known as it's mentioned in https://github.com/docker/desktop-linux/issues/209 , but the most spread workaround is completely disabling a security feature. 

### Location

https://docs.docker.com/desktop/install/linux/ubuntu/

### Suggestion

These are better workarounds that can be added in the documentation until the full support is ready:
https://github.com/docker/desktop-linux/issues/209#issuecomment-2376823330
https://github.com/docker/desktop-linux/issues/209#issuecomment-2372489613 

These suggest creating a new apparmor profile instead of disabling the unprivileged usernamespaces.

**Comment by dvdksn** [comment]
(I assume you mean 24.04, not 22.04)

24.04 I believe is fully supported in the latest version of Docker Desktop, but maybe it would be worth calling out that versions earlier than 4.35.0 do not support it. If my memory is correct - cc @aevesdocker

**Comment by CristianArean** [comment]
> (I assume you mean 24.04, not 22.04)
> 
> 24.04 I believe is fully supported in the latest version of Docker Desktop, but maybe it would be worth calling out that versions earlier than 4.35.0 do not support it. If my memory is correct - cc [@aevesdocker](https://github.com/aevesdocker)

My mistake, you're right. I wanted to mention 24.04.

About the version, it's important to notice that this is a fresh install from the [oficial website](https://docs.docker.com/desktop/install/linux/ubuntu/)  today
