### ISSUE TITLE
404 in package download engine links table

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#2130]
File: [cs-engine/1.13/index.md](https://docs.docker.com/cs-engine/1.13/)

Under the table of RPMs, the `docker-selinux` link is incorrect.  It has an `11` instead of `1` in the URL.

`RHEL 7.x and CentOS 7`	`docker-engine, docker-engine-debuginfo, docker-engine-selinux`

https://packages.docker.com/1.13/yum/repo/main/centos/7/Packages/docker-engine-selinux-1.13.1.cs2-11.el7.centos.noarch.rpm
should be
https://packages.docker.com/1.13/yum/repo/main/centos/7/Packages/docker-engine-selinux-1.13.1.cs2-1.el7.centos.noarch.rpm

**Comment by scjane** [comment]
#dibs

**Comment by johndmulhausen** [comment]
Sorry @scjane, looks like you claimed this but never submitted a PR. @bhavin192 jumped on this one.

**Comment by scjane** [comment]
@johndmulhausen OK. It is because when I was about to submit my PR, I saw @bhavin192 had already submitted one. So, I think it's breaking rules if I submit mine again. Anyway, this issuse is resolved.

**Comment by bhavin192** [comment]
@scjane I was not aware of dibs, Sorry about that.

**Comment by scjane** [comment]
@bhavin192 Never mind. Forget it🙂

**Comment by londoncalling** [comment]
Points to @bhavin192 on this one.
