### ISSUE TITLE
404 at: /docker-for-mac/index/

### ISSUE THREAD

**Issue by peternicholls** [docker/docker.github.io#2131]
URL: /docker-for-mac/index/

Accessed from: https://store.docker.com/editions/community/docker-ce-desktop-mac/plans/docker-ce-desktop-mac-tier?tab=instructions under

> **Documentation**
> To learn more, read the Docker for **Mac documentation**.
> 

Many thanks.

**Comment by londoncalling** [comment]
@nandhini can we work together to get some links fixed on Store?

1. On the [Docker for Mac Store page](https://store.docker.com/editions/community/docker-ce-desktop-mac/plans/docker-ce-desktop-mac-tier?tab=instructions), both the main docs and "Where to go next" links don't work per the feedback above: https://store.docker.com/editions/community/docker-ce-desktop-mac/plans/docker-ce-desktop-mac-tier?tab=instructions 

For the main docs link, we have `index` in the path and it shouldn't be there. The proper links are:

https://docs.docker.com/docker-for-mac/

https://docs.docker.com/docker-for-mac/#where-to-go-next

2. On Docker for Windows Store page, the first link to the docs works, but the second one, Where to go next, is broken. This should be: https://docs.docker.com/docker-for-windows/#where-to-go-next

Let me know if you need more info or want to look at these together.

**Comment by nandhini915** [comment]
The [Docker for Mac](https://store.docker.com/editions/community/docker-ce-desktop-mac/plans/docker-ce-desktop-mac-tier?tab=instructions) and [Docker for Windows](https://store.docker.com/editions/community/docker-ce-desktop-windows/plans/docker-ce-desktop-mac-tier?tab=instructions) pages are both fixed now. Links should be valid and point to https://docs.docker.com/docker-for-mac/, https://docs.docker.com/docker-for-mac/#where-to-go-next for Mac, and https://docs.docker.com/docker-for-windows/#where-to-go-next for Windows.

**Comment by londoncalling** [comment]
@peternicholls All are fixed now, closing this issue. Thank you so much for the feedback!

@nandhini915 thanks, you are awesome!!!
