### ISSUE TITLE
Request for CSn version tables 

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#2132]
File: [cs-engine/1.12/index.md](https://docs.docker.com/cs-engine/1.12/)
File: [cs-engine/1.13/index.md](https://docs.docker.com/cs-engine/1.13/)

For the offline install instructions, there are tables for the minor releases but there are not tables for the individual cs`n` release versions.  Since CS can have multiple releases for a bugfix version number, it maybe worthwhile to have the individual versions available.

For example, there isn't a table to get the 1.13.1-cs1 version anymore now that 1.13-1-cs2 has been released.

**Comment by mstanleyjones** [comment]
@cpuguy83 WDYT? We decided to only have it be the latest, I thought.

This can't be for the hackathon as these directories are not browseable without access to the S3 buckets themselves.

**Comment by cpuguy83** [comment]
Seems a bit excessive to me.

**Comment by mstanleyjones** [comment]
Can @andrewhsu work his magic and make the buckets browseable?

**Comment by mstanleyjones** [comment]
Looks like we decided again not to do this.
