### ISSUE TITLE
Feedback for: engine/installation/linux/debian.md

### ISSUE THREAD

**Issue by mauricioszabo** [docker/docker.github.io#2136]
File: [engine/installation/linux/debian.md](https://docs.docker.com/engine/installation/linux/debian/)

First, how to install on ARM? This documentation only cites installation for AMD64.

Other thing, in the session *Install from a package*, when we click on https://download.docker.com/linux/debian/pool/stable/amd64/, it returns the following XML:

```
<Error>
  <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
  <RequestId>A5EB56A90104CBEF</RequestId>
  <HostId>
    eRLqLzENNZ0xvcPhA63H3yxEw1ZdMREJ1DJOVXZ6ZuN7oh267f/KW5qCc4YX6t08yy11lEj5r48=
  </HostId>
</Error>
```

So, how to install from package, and how to install on ARM?

**Comment by thaJeztah** [comment]
The index pages are currently missing for download.docker.com (see https://github.com/docker/docker/issues/31987), which is being worked on.


The `docker-ce` packages are currently not available for ARM, only amd64. You can download the `docker-engine` package, which is the old name for the `docker-ce` package, and can be found here; http://apt.dockerproject.org/repo/pool/main/d/docker-engine/

**Comment by andrewhsu** [comment]
@mauricioszabo apologies for the broken link. The documentation is now updated with a link to a browsable directory structure. The `armhf` packages are now also released for `docker-ce` and they can be found here: https://download.docker.com/linux/debian/dists/jessie/pool/stable/armhf/
