### ISSUE TITLE
Move UCP and DTR topics to a higher level in the IA

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#2149]
The release notes for both UCP and DTR are buried under the upgrade section, it usually takes 3-4 clicks to access the notes to see what's changed when a new version is released. Is it possible to move this higher up the tree at the top level? 

File: [datacenter/ucp/2.1/guides/admin/upgrade/release-notes.md](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/upgrade/release-notes/)
File: [datacenter/dtr/2.2/guides/admin/upgrade/release-notes.md](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/upgrade/release-notes.md)

**Comment by joaofnfernandes** [comment]
Fixed.
