### ISSUE TITLE
Fix erroneous references to "docker ssh"

### ISSUE THREAD

**Issue by jlambe** [docker/docker.github.io#2151]
File: [engine/getstarted-voting-app/node-setup.md](https://docs.docker.com/engine/getstarted-voting-app/node-setup/)

At the end of the page, there are mentions to `docker ssh` commands but it looks like a mistake as those commands do not exists. Shouldn't be written `docker-machine ssh` instead?

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by johndmulhausen** [comment]
This topic doesn't exist any longer, but @shubheksha gets the points anyway. The PR was on point.
