### ISSUE TITLE
Layout / responsive CSS issue - 1st line is behind the top navigation 

### ISSUE THREAD

**Issue by TimoBlechschmidt** [docker/docker.github.io#2161]
I was reading the Tutorial in my mobile. I noticed that there is a layout issue - the first line is behind the top navigation.
![screenshot_20170307-084007](https://cloud.githubusercontent.com/assets/5502100/23646662/1ff82e02-0312-11e7-9e70-249618eb9b93.png)

**Comment by londoncalling** [comment]
@TimoBlechschmidt Thanks for the screen snap, and reporting this. 

We do have this on a list of issues to address, post launch of the new website, and hope to have it addressed asap.

 cc: @jsouth @johndmulhausen

**Comment by johndmulhausen** [comment]
This has since been fixed. :)
