### ISSUE TITLE
Build artifacts rendering on page

### ISSUE THREAD

**Issue by akimd** [docker/docker.github.io#2165]
File: [engine/reference/commandline/commit.md](https://docs.docker.com/engine/reference/commandline/commit/)

For some reason there is markup showing in the second frame: `{% raw %}` (and the closing one).

It does not appear in the markdown sources though.  The second frame also has ICONTAINER instead of CONTAINER.

Cheers!

**Comment by akimd** [comment]
I'm referring to this page: https://docs.docker.com/engine/reference/commandline/save/

**Comment by rcjsuen** [comment]
I opened [docker #31619](https://github.com/docker/docker/pull/31619) for the `ICONTAINER` problem. The pair of `{% raw %}` and `{% endraw %}` tags can be found in the [`docker_commit.yaml`](https://github.com/docker/docker.github.io/blob/7c894d5fb180fe3ad8d40f6fe074fe9c90b08ef8/_data/engine-cli/docker_commit.yaml#L62-L80) file but not in [`commit.md`](https://github.com/rcjsuen/docker/blob/de692b10655cf744a5d3a3840c2fefd5f3e461df/docs/reference/commandline/commit.md)

**Comment by mstanleyjones** [comment]
These appear to have been fixed.
