### ISSUE TITLE
Feedback for: docker-for-mac/index.md

### ISSUE THREAD

**Issue by aaronmarkham** [docker/docker.github.io#2166]
File: [docker-for-mac/index.md](https://docs.docker.com/docker-for-mac/)

There's no login option in the main menu in the current stable version of docker for mac. (as seen in the screenshots.)

**Comment by londoncalling** [comment]
@aaronlehmann you should see the login option now on latest versions of Docker for Mac Version 17.03.0-ce-mac2 and above. (Both stable and edge installers available [here](https://docs.docker.com/docker-for-mac/install/).)

Closing this issue, please re-open if you have more problems or comments.
