### ISSUE TITLE
Document that Hub / Cloud builds use a shallow clone

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#2167]
When you do a CI build on Hub / Cloud, it does a shallow clone of the repo / branch combo that you specified. If you need to do something that relies on a different branch (such as in a `post_push` hook), you won't be able to check out the second branc unless you do one of the following:

- You can get a shallow checkout of THAT branch by doing something like the following,
   assuming   the branch is called `branch`:

  ```
  git fetch origin branch:branch --depth 1
  ```

- You can also "unshallow" the clone, which fetches the whole Git history (and potentially
   takes a long time / moves a lot of data) by using the `--unshallow` flag on the fetch:

  ```
  git fetch --unshallow origin
  ```

Even if you need to operate on multiple branches serially, it's probably better to do the first multiple times, because you only get the tip of each of the branches, rather than the whole history.

We should document this behavior and these workarounds somewhere.

**Comment by clocklear** [comment]
Claimed.
