### ISSUE TITLE
Feedback for: docker-for-mac/install.md

### ISSUE THREAD

**Issue by karstengresch** [docker/docker.github.io#2178]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/)

Folks, could you please check if the shasums are still correct? Furthermore: Is it correct that both the stable and the beta version have the same server version?

```
docker --version
Docker version 17.03.0-ce, build 60ccb22
```
Perhaps it's useful to mention the actual version anyway?

Best wishes,

Karsten

**Comment by londoncalling** [comment]
@karstengresch  it is correct that both stable and edge (formerly beta) have the same server version.

@FrenchBen @friism @ebriney

Can you please verify that the Checksums are still correct?

- https://docs.docker.com/docker-for-mac/install/
- https://docs.docker.com/docker-for-windows/install/

**Comment by londoncalling** [comment]
@karstengresch thanks for this, I'm closing the issue now, as I've removed the checksums from the download links in the docs. If/when I circle back with the devs, I can re-add accurate checksums if we all think they are useful. Let me know if you have a strong preference for having them there.
