### ISSUE TITLE
Feedback for: engine/getstarted/step_six.md

### ISSUE THREAD

**Issue by lelakshm** [docker/docker.github.io#2186]
Command to remove a docker image is incorrect. This document refers to 'docker rm -f <ID>' to remove an image, which is incorrect. It should have been 'docker rmi <ID>'

**Comment by londoncalling** [comment]
@lelakshm yes, this is better

They both work in this case to actually remove the images, but technically, the[ `docker rm `](https://docs.docker.com/engine/reference/commandline/rm/) is for containers, and [`docker rmi`](https://docs.docker.com/engine/reference/commandline/rmi/) is for images

I've made the change in the PR referenced above, I'll merge this when the builds finish, and you should see it published with your corrections within the hour.

Closing this issue, thanks for the feedback!
