### ISSUE TITLE
Request for diagrams on networking containers

### ISSUE THREAD

**Issue by paulanthonybland** [docker/docker.github.io#2192]
File: [engine/tutorials/networkingcontainers.md](https://docs.docker.com/engine/tutorials/networkingcontainers/)

This really needs some diagrams to illustrate how the networks inter-relate in the host. As it is, the page presumes an underlying comprehension of the terminology being used.

**Comment by mstanleyjones** [comment]
You can use graphics from https://success.docker.com/Architecture/Docker_Reference_Architecture%3A_Designing_Scalable%2C_Portable_Docker_Container_Networks :)

**Comment by Rubab-Syed** [comment]
Hey! I want to work on this. Do I have to modify the diagram from the above link?

**Comment by mstanleyjones** [comment]
You can reuse them!

**Comment by johndmulhausen** [comment]
@Rubab-Syed Any progress? All you should need to do is just slot in the existing images!

**Comment by jmaitrehenry** [comment]
@mstanleyjones this issue should be close with the merge of #2988

**Comment by londoncalling** [comment]
Points to @Rubab-Syed on this one. (Thanks @jmaitrehenry for the heads up to close)
