### ISSUE TITLE
404 at: /docker-for-mac/index/

### ISSUE THREAD

**Issue by ggerard** [docker/docker.github.io#2197]
From the page: https://store.docker.com/editions/community/docker-ce-desktop-mac?tab=description

There's a "Where to go Next" link that winds up with a not found. Whence this ticket.

URL: /docker-for-mac/index/

**Comment by londoncalling** [comment]
Thanks @ggerard this is fixed now, per similar issue filed at #2131 .

Thanks for the feedback!
