### ISSUE TITLE
Feedback for: engine/reference/commandline/service_create.md

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#2198]
The docs don't describe how to publish ports in host mode. It provides the flags but does not what values you can or should provide for different scenarios, like `mode=host` for example. 

`docker service create --publish mode=host,target=8080,published=8081,protocol=tcp...` which should be the equivalent of:
`docker run -d -p 8081:8080...`

File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/)

**Comment by mbentley** [comment]
@yongshin - I think https://github.com/docker/docker.github.io/issues/1981 covers this.

**Comment by yongshin** [comment]
@mbentley @mstanleyjones  still don't see this in the service create in the service_create.md file. I was looking for host mode on publishing ports here: https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md

**Comment by mbentley** [comment]
Ah, you're right; there is no table for `--publish`, unlike `--mount`.

**Comment by mstanleyjones** [comment]
Any modifications need to be made to the linked file in `docker/docker` rather than here. We just import the contents. Thanks!

**Comment by yongshin** [comment]
@mstanleyjones I actually don't know the the full implications of publishing in host mode, so I filed the issue about it hoping someone else might.

**Comment by mbentley** [comment]
We should get an issue open on docker/docker to get that updated

**Comment by yongshin** [comment]
Ah got it, I didn't read carefully enough. Done: https://github.com/docker/docker/issues/31721
