### ISSUE TITLE
misdirected link at end of engine/swarm/how-swarm-mode-works/services.md page

### ISSUE THREAD

**Issue by workybee** [docker/docker.github.io#22]
In the "Learn more" section at the end of the engine/swarm/how-swarm-mode-works/services.md page
it mentions:
- "Read about how swarm mode nodes work."
with the word "nodes" as a link.
Unfortunately it links back to the services.md page, not the nodes.md page.

**Comment by workybee** [comment]
I can make a pull request with a fix if desired. Let me know: peter at mentad dot com

**Comment by johndmulhausen** [comment]
@workybee Would love a pull request! :) Sent a note.

**Comment by johndmulhausen** [comment]
Fixed in c03bb7f90c68a067a435720db0174db4378cfb98
