### ISSUE TITLE
Feature request: parameter to "docker plugin install" to allow permissions

### ISSUE THREAD

**Issue by taherv** [docker/docker.github.io#2206]
File: [engine/extend/index.md](https://docs.docker.com/engine/extend/)

To install a plugin, the "docker plugin install" seems to be interactive.
If I have a bunch (a lot) of nodes where I want to deploy a plugin, is there a parameter to "docker plugin install" to allow permissions ? If not, can we please have that ?
If not, we have to drop to writing dirty scripts to wrap around this interaction to make it automatic.

**Comment by johndmulhausen** [comment]
@taherv Add the `--grant-all-permissions` flag :)
