### ISSUE TITLE
Way for swarm manager to just run/install the plugin on any nodes joining the swarm?

### ISSUE THREAD

**Issue by taherv** [docker/docker.github.io#2207]
File: [engine/extend/index.md](https://docs.docker.com/engine/extend/)

In swarm mode, does an operator have to manually install the volume plugin (docker swarm join, followed by docker plugin install") every time a node needs to be added to swarm.
Is there a way for swarm manager to just run/install the plugin on any nodes joining the swarm, once a plugin is installed in swarm mode.

Also, in swarm mode, if I have many nodes, how do I check the status of volume plugin on each of the nodes ?

**Comment by mstanleyjones** [comment]
Fixed in #4064
