### ISSUE TITLE
Feedback for: swarm/install-manual.md

### ISSUE THREAD

**Issue by adrianp-sti** [docker/docker.github.io#221]
URL: [https://docs.docker.com/swarm/install-manual.md](https://docs.docker.com/swarm/install-manual/)

For step 3 the instruction is:
sudo docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock

This fails on my stock Linux AWS AMI with:
FATA[0001] Error starting daemon: Devices cgroup isn't mounted

You can hack round this error but it's handled more gracefully by the supplied /etc/init.d/docker script that comes by default when docker is installed.  A better instruction would be to:
- Edit /etc/sysconfig/docker and add "-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock" to the OPTIONS variable there
- Start docker as per normal with "/etc/init.d/docker start"

**Comment by riggerthegeek** [comment]
Thanks @adrianp-sti. This makes a lot more sense than the official instruction.

I found the only way to do it "officially" was to restart the machine after installing Docker (to remove the `cgroup` issue), stop the running Docker service and then start up my own one. Which clearly wouldn't be automated if I restarted my instance - your way is.
