### ISSUE TITLE
Document first use of "swarm"

### ISSUE THREAD

**Issue by AyushyaChitransh** [docker/docker.github.io#2225]
File: [engine/getstarted/last_page.md](https://docs.docker.com/engine/getstarted/last_page/)

The word `swarm` has been used here for the first time. It would be very beneficial at this point to have a small introduction about what swam is.

**Comment by mstanleyjones** [comment]
This is tricky because people don't consume the docs from top to bottom in the left-hand nav. If you feel like it's useful to link to the glossary definition of `swarm` here, that is fine.

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by shubheksha** [comment]
The word `swarm mode` has been used twice and it's already linked to the glossary definition in both places.
Should I make one of those point to the definition of `swarm` in the glossary?

**Comment by AyushyaChitransh** [comment]
The link to glossary definition of `swarm mode` is not working. It redirects to [swarm mode](https://docs.docker.com/engine/reference/glossary/#swarm) which does not exists. I would like you to recheck if we are looking at the same file, since I found only one usage of `swam mode` in File: [engine/getstarted/last_page.md](https://docs.docker.com/engine/getstarted/last_page/) .

**Comment by mstanleyjones** [comment]
I just meant that this might not be the first mention of Swarm in the whole docs, depending on how people are are reading and where they come in from. If you feel like it's the right place to define a swarm, you can definitely link to the glossary definition.

**Comment by johndmulhausen** [comment]
This topic no longer exists.
