### ISSUE TITLE
Docker Toolbox missing from the list

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker.github.io#2227]
https://www.docker.com/products/docker-toolbox is missing Docker Toolbox from the `What's in Docker Toolbox` list.

**Comment by joaofnfernandes** [comment]
Sorry @arun-gupta, I don't understand your feedback. are you saying that this list
<img width="260" alt="screen shot 2017-03-15 at 11 47 09" src="https://cloud.githubusercontent.com/assets/1525937/23965436/31a18ad6-0975-11e7-95af-526cff177854.png">

Contain an entry for 'Docker Toolbox'?

**Comment by arun-gupta** [comment]
Ah, I meant `Virtual Box` instead.

**Comment by joaofnfernandes** [comment]
@bettyjunod can you take a look at this?

**Comment by johndmulhausen** [comment]
Closing as this is not a docs bug
