### ISSUE TITLE
Rendering issues with code blocks

### ISSUE THREAD

**Issue by akimd** [docker/docker.github.io#2228]
File: [engine/reference/commandline/create.md](https://docs.docker.com/engine/reference/commandline/create/)

Hi,

That page is showing weird behaviour on the code samples.  I guess there is some pretty-printing mechanism that fires, which puts some words in bold (e.g., `create`, or `local`), and at other places we get italics+grayed text.

It hardly makes sense.  I guess the pretty-printer should be disabled.  Or maybe the code snippets need some explicit tag to disable it locally?

Cheers!

**Comment by akimd** [comment]
<img width="855" alt="capture d ecran 2017-03-09 a 15 13 45" src="https://cloud.githubusercontent.com/assets/232441/23753818/2332451a-04db-11e7-81bf-ffd7170c827d.png">

**Comment by mstanleyjones** [comment]
No longer a problem.
