### ISSUE TITLE
Sidebar menu not visible when many items are expanded

### ISSUE THREAD

**Issue by krasi-georgiev** [docker/docker.github.io#2232]
Here is a short video that shows the problem

https://screencast.com/t/dtWyUkzDdy

**Comment by stevenhanna6** [comment]
I might have a fix for this, will upload now

**Comment by stevenhanna6** [comment]
Just noticed this might be a duplicate fix for #2403 and #2002

**Comment by allejo** [comment]
Related PR is #2860, here's the Netlify test deployment to see if the issue has been fixed for you:

https://deploy-preview-2860--docker-docs.netlify.com/

**Comment by krasi-georgiev** [comment]
yes this one work ok

**Comment by mstanleyjones** [comment]
Thanks @allejo

**Comment by johndmulhausen** [comment]
Full points to @allejo, and 25 bonus points to @stevenhanna6 for the attempt.
