### ISSUE TITLE
404 at: /engine/getstarted/step_one/#docker-for-windows/

### ISSUE THREAD

**Issue by ppamidi1** [docker/docker.github.io#2233]
URL: /engine/getstarted/step_one/#docker-for-windows/

**Comment by JimGalasyn** [comment]
Thank you for your feedback. It appears that the issue at https://docs.docker.com/engine/getstarted/step_one/#docker-for-windows has been fixed. Please let me know if you're still having issues with this topic.

**Comment by ppamidi1** [comment]
Thank you.
