### ISSUE TITLE
It's not called the "Launch new service wizard"

### ISSUE THREAD

**Issue by vitorreis** [docker/docker.github.io#2237]
File: [docker-cloud/builds/push-images.md](https://docs.docker.com/docker-cloud/builds/push-images/)

There is no `Launch new service wizard` describe it better

**Comment by bhavin192** [comment]
It is showed when you turn off the swarm mode on https://cloud.docker.com
Add -> Service

**Comment by mstanleyjones** [comment]
It's worth clarifying that the wizard might be titled differently depending on whether you are using swarm mode or not.

**Comment by bhavin192** [comment]
I will take this one..

**Comment by constanzekratel** [comment]
I already took this one and submitted PR: https://github.com/docker/docker.github.io/pull/2921
