### ISSUE TITLE
Feedback for: docker-hub/bitbucket.md

### ISSUE THREAD

**Issue by MojoJojo** [docker/docker.github.io#224]
Hi,
I've been trying to configure an automated build using my BitBucket repository. However, I could not find any documentation on using private submodules on bitbucket. There are instructions on how to do this on Github, but no instructions for bitbucket. Can you please assist?

URL: [https://docs.docker.com/docker-hub/bitbucket.md](https://docs.docker.com/docker-hub/bitbucket/)

**Comment by sanscontext** [comment]
Hi @MojoJojo, 
Thanks for your feedback. We're actually [moving away from developing more features in Docker Hub](https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498), but this is documented for Docker Cloud [here](https://docs.docker.com/docker-cloud/builds/automated-build/#/build-repositories-with-linked-private-submodules). The process is the same for both Github and Bitbucket. Your Hub repositories show up automatically in Docker Cloud, so please try that.  

If you're still having trouble let me know by reopening this issue and we can figure out how to improve the Cloud doc.
