### ISSUE TITLE
Build Docker Windows Container-related content

### ISSUE THREAD

**Issue by friism** [docker/docker.github.io#225]
This is a tracking issue for building content on how to run Docker containers natively on Windows.

Ideas for topics below.
## Setup

This is partly addressed with https://github.com/docker/docker.github.io/issues/154. Also see the Docker [Labs](https://github.com/docker/labs/blob/master/windows/windows-containers/Setup.md)
- Windows 10 with Docker for Windows
  - switching between Linux and Windows containers
- Azure
- macOS and older Windows versions
## Build and push first container
- https://github.com/docker/labs/blob/master/windows/windows-containers/WindowsContainers.md
## Multi-container apps
- https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md
## Protecting the Engine Socket

Parallel to [Linux article](https://docs.docker.com/engine/security/https/). Resources:
- [Prototype built by Microsoft folks](https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/DockerTLS)
- http://blogsprajeesh.blogspot.de/2015/09/docker-for-windows-on-azure-vm-securing.html
## Windows Dockerfile best practices
- Skimming the Microsoft one, it looks really good: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/docker/optimize_windows_dockerfile
- Equivalent on Linux: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/
- Also: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/docker/manage_windows_dockerfile

cc @londoncalling @mstanleyjones @johndmulhausen @neilpeterson

**Comment by neilpeterson** [comment]
I've moved onto a new project, adding @mylesbkeating1993 from the container team.

**Comment by mylesbkeating1993** [comment]
@enderb-ms @taylorb-ms @PatrickLang adding the rest of the team.

Thanks for starting this Michael! Sorry this got lost in my "Other" inbox tab. Working on a better way to track GitHub notifications...

**Comment by londoncalling** [comment]
@JimGalasyn This seemed like a good issue for you to track. Let me know if this makes sense for you to have, maybe double-check with @johndmulhausen

**Comment by londoncalling** [comment]
In Docker for Windows, we have these topics:

- [About Windows containers and Windows Server 2016](https://docs.docker.com/docker-for-windows/install/#about-windows-containers-and-windows-server-2016)

- [Switch between Linux and Windows containers](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers)

**Comment by friism** [comment]
https://github.com/docker/docker.github.io/pull/1681

**Comment by johndmulhausen** [comment]
TODO:

- Talk with MS about importing "Manage Docker on Windows" section (w/attribution)
- Ditto "Active Directory Service Accounts," "Anti-Virus," "Hyper-V Isolation"
- Also in this section, our Windows labs: https://github.com/docker/labs/tree/master/windows
- Within Dockerfile and Compose File refs, doc Win-specific cases (use MSFT docs as a ref)
- Address multiline snippets problem (\ vs `) 
- P2: Add topic for running Docker on Windows Subsystem for Linux (WSL) - Linux dockerd binary doesn't work, but you can use docker.exe or the docker linux binary if using host of tcp://localhost:2975 -- this gives you access to Linux tools like `make` but gives you access to D4W daemon
- Add topic to ensure we cover which executable gets which privilege for a given privilege management system (e.g. PowerBroker)
- @jimgalasyn to address #3078 to ensure Getting Started w/Docker is Windows-friendly
- On our radar (perhaps Success can help): Docker + VPN = full of pain
- P3: Setting up Windows Swarm or hybrid Windows/Linux Swarm

**Comment by BrandonRoyal** [comment]
+1 on anti-virus documentation.  We're seeing issues with customers here that could be avoided with AV guidance. https://github.com/docker/orca/issues/9565  /cc @gitkenlavoie

**Comment by mistyhacks** [comment]
@BrandonRoyal you'll be happy to know we have published content about working with antivirus software! https://docs.docker.com/engine/security/antivirus/

**Comment by L-Hudson** [comment]
Two years old. Closing ticket.
