### ISSUE TITLE
The voting app does not work

### ISSUE THREAD

**Issue by geoidesic** [docker/docker.github.io#2251]
File: [engine/getstarted-voting-app/test-drive.md](https://docs.docker.com/engine/getstarted-voting-app/test-drive/)

The application doesn't work as described. Clicking on a vote does not register... the result page shows 50%/50% with no votes.

Then I did the changes to the app from "before" to "after" and it started working. Then I noticed that it only works if the browser is viewing both pages as tabs within the same window, in which case the Result updates automagically whenever you click on vote. If the result is in a different browser window then it won't update at all even on page refresh.

And then after a while it stopped working even when in the same window. 

==
EDIT:
On further testing it has nothing to do with tabbed vs. windowed... it's simply that sometimes clicking on Vote works and sometimes it doesn't. Seems to be about a 50/50 chance that clicking on vote will update the Result.
==

Seems flaky in the extreme and does not inspire confidence.
Very strange behaviour. This is on Chrome for Mac OS X Sierra.

**Comment by johndmulhausen** [comment]
This topic no longer exists.

**Comment by ABQJuan** [comment]
Was this issue every resolved? I am able to replicate the stuck at 50/50 problem today. I bashed into the postgres container and it the voting table was empty after several votes.
