### ISSUE TITLE
Problems running aufs w/mainline kernel

### ISSUE THREAD

**Issue by milesrichardson** [docker/docker.github.io#2252]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/)

I am running mainline kernel on ubuntu:

```bash
ubuntu@romano:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

ubuntu@romano:~$ uname -r
4.10.0-041000-generic
```

The docs specify installing `linux-image-extra-*` via `uname -r` substitution:

```bash
$ sudo apt-get install \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual
```

However this fails because there is currently no package built for the mainline kernel. 

According to stackoverflow (http://askubuntu.com/questions/729157) this kernel does not require `linux-image-extra-*` (unless I'm misreading that comment)

However there is no `aufs` module loaded:

```bash
ubuntu@romano:~$ lsmod | grep aufs
ubuntu@romano:~$ 
```

I'm not sure what the steps are to install `aufs` for mainline, but perhaps the docs should note that this command will fail if you are running mainline kernel. Or perhaps that's just a risk you take running mainline.

**Comment by weaming** [comment]
I just run on ubuntu 16.04 on AWS:
```
apt install docker-engine
sudo dockerd
```
