### ISSUE TITLE
I saw the problem about text format on document page

### ISSUE THREAD

**Issue by ninearif** [docker/docker.github.io#226]
### Problem description

I think there are some problem about text styling or formatting in documentation page, some indent or text style doesn't show properly.

### Problem location
- [ ] I saw the problem on the following URL: https://docs.docker.com/swarm/swarm_at_scale/deploy-app/
- [ ] This link in document is also not available now : http://vote.myenterprise.com

**Comment by thaJeztah** [comment]
We should not use `myenterprise.com` as a domain name here, as it's an existing domain, and use an `example.com` or `example.org` domain name as those are intended for documentation purposes

**Comment by ninearif** [comment]
I agree with you. It's make me confuse sometime.
