### ISSUE TITLE
Link for installing from a package is broken

### ISSUE THREAD

**Issue by nikinath** [docker/docker.github.io#2269]
### Problem description

The link for installing docker from a package in Ubuntu (link mentioned below) seems to be broken. Clicking on the link, gives the following output:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
      

<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>1234A15B9B62D9AC</RequestId>
    <HostId>1gU8Ya+fWTLx5ow7i6N4T3wZlJ4VrswcfnmucUzifE7AkhWVtw9jORKDF+Bnf3WfChZ9iZ40KtQ=
<HostId>
</Error>

```

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/installation/linux/ubuntu/#install-from-a-package

- Other: 

1. The link is referenced as `{{ download-url-base }}/pool/stable-{{ minor-version }}/amd64/` [here](https://github.com/docker/docker.github.io/blob/master/engine/installation/linux/ubuntu.md#install-from-a-package).

2. The `download-url-base` link mentioned as "https://download.docker.com/linux/ubuntu" (in this [file](https://github.com/docker/docker.github.io/blob/master/engine/installation/linux/ubuntu.md#docker-ce)) also seems to be broken. 

3. https://download.docker.com redirects to https://www.docker.com.

### Suggestions for a fix

The download link should point to: https://apt.dockerproject.org/repo/pool/main/d/docker-engine/
`

**Comment by thaJeztah** [comment]
The index pages are currently missing for download.docker.com (see https://github.com/docker/docker/issues/31987), but is being worked on

I'm not sure what the exact URL's are for the packages; For the time being, you can indeed download the `docker-engine` package, which is the old name for the `docker-ce` package, from https://apt.dockerproject.org

**Comment by andrewhsu** [comment]
@nikinath apologies for the broken link. The documentation is now fixed and the proper location for downloading the `.deb` package for `xenial` `amd64` from the `stable` channel, for example, is here:  https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/

**Comment by nikinath** [comment]
@andrewhsu Thanks for the follow up! Closing since the link is fixed.
