### ISSUE TITLE
Incorrect command shown for running Dockerized nginx container

### ISSUE THREAD

**Issue by razasayed** [docker/docker.github.io#227]
On the page https://docs.docker.com/docker-for-mac/ , the command for running a dockerized nginx container is shown as `shell docker run -d -p 80:80 --name webserver nginx` but instead it should be `docker run -d -p 80:80 --name webserver nginx` . Looks like the markdown has already been corrected in the master branch which i confirmed by doing a Preview but on the live site the typo still exists.

**Comment by sanscontext** [comment]
Closing as fixed.
