### ISSUE TITLE
Clarify language in "A view into implementation"

### ISSUE THREAD

**Issue by bbernstein** [docker/docker.github.io#2270]
File: [docker-for-mac/networking.md](https://docs.docker.com/docker-for-mac/networking/)

Referencing: "there is a bug in macOS that is only fixed in 10.12 and is not being backported"

If I am indeed running 10.12, should I disregard the workarounds and should it work as documented for linux? The pages don't have a modification date, so I don't know if this doc is up-to-date or if there are newer practices for mac networking when using the latest OS.

**Comment by johndmulhausen** [comment]
@bbernstein Yep, it should work as documented. The bug should be fixed for you. :)
