### ISSUE TITLE
Feedback for: engine/installation/index.md

### ISSUE THREAD

**Issue by cp10000** [docker/docker.github.io#2273]
File: [engine/installation/index.md](https://docs.docker.com/engine/installation/)

Provide all documentation in Adobe PDF format also, so this material can be printed and studied more effectively.

**Comment by joaofnfernandes** [comment]
Please don't kill 🌲🌳 😢
If you're looking for an effective way to learn Docker, try [doing some of these labs](https://github.com/docker/labs/tree/master). They have a ton of exercises that that will allow you to explore the Docker commands and functionality.

**Comment by johndmulhausen** [comment]
Sorry, this isn't technically feasible for us at this time.
