### ISSUE TITLE
Feedback for: engine/getstarted/step_three.md

### ISSUE THREAD

**Issue by eljuanorey** [docker/docker.github.io#2274]
File: [engine/getstarted/step_three.md](https://docs.docker.com/engine/getstarted/step_three/)

In the step three on get started tutorial say:

> Step 1: Locate the whalesay image
> Open your browser and **browse the Docker Hub.**

Is outdated information. Change Docker Hub to Docker Store and add a link to Docker Store.

Thanks for reading.

**Comment by johndmulhausen** [comment]
Fixed to point to Store in a previous commit. Thanks!
