### ISSUE TITLE
Put parallel CE/EE instructions in tabs to shorten page

### ISSUE THREAD

**Issue by sohamkamani** [docker/docker.github.io#2277]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/)

This documentation could be improved. 
People who want to install docker either want to install Docker CE or Docker EE, rarely both.

The current structure of this page is :

- Step 1
  - Docker CE
  - Docker EE
- Step 2
  - Docker CE
  - Docker EE
- Step 3
  - Docker CE
  - Docker EE

Which is quite an eyesore for anyone who only wants to install one of them. I think it could be made better through something like : 

- Docker CE 
  - Step 1
  - Step 2
  - Step 3
- Docker EE 
  - Step 1
  - Step 2
  - Step 3

I can start working on a PR if you guys are open to this

**Comment by johndmulhausen** [comment]
It's more likely that we want to use tabs so this isn't quite so disruptive. We doc how to use tabs that auto-sync with each other in https://github.com/docker/docker.github.io#creating-tabs

**Comment by johndmulhausen** [comment]
See also Synchronizing Multiple Tab Groups: https://docs.docker.com/test/#tabs

**Comment by jadametz** [comment]
I'll take this one!

**Comment by londoncalling** [comment]
@jadametz Examples of tabs are at https://docs.docker.com/test/#bootstrap-and-css-tricks. You can look at the HTML as rendered, and then look at how it's actually formatted in the raw markdown file.
