### ISSUE TITLE
Add uninstall instructions for Docker for AWS

### ISSUE THREAD

**Issue by asloan7** [docker/docker.github.io#2279]
File: [docker-for-aws/faqs.md](https://docs.docker.com/docker-for-aws/faqs/)

Please add a FAQ on how to remove the whole entire "docker-for-aws" setup

**Comment by londoncalling** [comment]
@FrenchBen is there a quick, one-click way to uninstall Docker on AWS? If not, would it be possible to create a template in order to make this easier for users?

**Comment by johndmulhausen** [comment]
cc @FrenchBen Is there a way to do this? Is there an "undo template?"

**Comment by FrenchBen** [comment]
In AWS, go to Cloudformation -> Delete Stack.
