### ISSUE TITLE
Remove -a flag from reference doc

### ISSUE THREAD

**Issue by josesa** [docker/docker.github.io#2281]
File: [compose/reference/rm.md](https://docs.docker.com/compose/reference/rm/)

Documentation refers to an optional flag `-a`.
> Options:
    -a, --all     Also remove one-off containers created by
                  docker-compose run

But when running latest (docker-compose version 1.11.2, build dfed245) `docker-compose rm` with the mentioned flag a warning is displayed:

```
WARNING: --all flag is obsolete. This is now the default behavior of `docker-compose rm`
```

Documentation should be updated to reflect the new behaviour.

**Comment by shubheksha** [comment]
I'll take this one up!

**Comment by mstanleyjones** [comment]
No action for two days, so this is up for grabs!

**Comment by shubheksha** [comment]
@mstanleyjones, a PR is open for this issue.

**Comment by mstanleyjones** [comment]
Whoops, my bad!
