### ISSUE TITLE
Feedback for: engine/installation/linux/centos.md

### ISSUE THREAD

**Issue by eliu** [docker/docker.github.io#2284]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

The offline package downloading address is not available right now (Access denied)
->  https://download.docker.com/linux/centos/7/x86_64/stable/Packages/

**Comment by thaJeztah** [comment]
The index pages are currently missing for download.docker.com (see https://github.com/docker/docker/issues/31987)

You can download the 17.03.0 CE packages using these URLs;

https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.03.0.ce-1.el7.centos.x86_64.rpm
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-selinux-17.03.0.ce-1.el7.centos.noarch.rpm

/cc @mstanleyjones @andrewhsu

**Comment by eliu** [comment]
Thanks @thaJeztah. Those links work for me!

**Comment by thaJeztah** [comment]
A browsable index should also be available now on download.docker.com (https://github.com/docker/docker/issues/31987)

**Comment by mstanleyjones** [comment]
Fixed now!
