### ISSUE TITLE
 no mention of a path from upgrading from 2.2.x to 2.2.3

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#2285]
There currently is no mention of a path from upgrading from 2.2.x to 2.2.3 and mention of whether it is supported. Ran into an issue when upgrading for 2.2.1 to 2.2.3. 

File: [datacenter/dtr/2.2/guides/admin/upgrade/index.md](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/upgrade/)

**Comment by joaofnfernandes** [comment]
We need to update the table to not use real version numbers. In the mean time don't take the version numbers on that table too literally. Read the table like:

|From|To|Description|Supported|
|:-----|:-|:-----------|:----------|
|x.x.0|x.x.2| skip patches| yes|
|x.x.2|x.x.0| downgrade patch| no|

**Comment by jennylia** [comment]
Dibs for hackathon

**Comment by jennylia** [comment]
ah I just saw this comment but I think @jmaitrehenry's PR address this pretty well.
https://github.com/docker/docker.github.io/pull/2974/files

I give @jmaitrehenry's PR a  :+1

**Comment by mstanleyjones** [comment]
Credit should be split between @jennylia and @jmaitrehenry for this one!

**Comment by jmaitrehenry** [comment]
No problem!

**Comment by londoncalling** [comment]
FYI, Points recorded as split evenly between @jmaitrehenry and @jennylia
