### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntu.md

### ISSUE THREAD

**Issue by pdbogen** [docker/docker.github.io#2286]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/)

The first step of "Install from a package" is impossible to follow, because it requires the user "Go to https://download.docker.com/linux/ubuntu/pool/stable-17.03/amd64/ and download the .deb file for the Docker version you want to install and for your version of Ubuntu."

However, visiting this URL results in a 403 Forbidden message, with the following body:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F0285A71D61FAC0C</RequestId>
<HostId>
wT3FC5PMo/ci3Odg9Ro7i27A09R94VmsfjVwJnubRSZK2PiSg5Y+pua/DV+Hsx0urm9ePrB8QCk=
</HostId>
</Error>
```

**Comment by thaJeztah** [comment]
The index pages are currently missing for download.docker.com (see https://github.com/docker/docker/issues/31987)

I'm not sure what the exact URL's are for the packages; if you require offline installation, you can download the `docker-engine` package, which is the old name for the `docker-ce` package, and can be found here; http://apt.dockerproject.org/repo/pool/main/d/docker-engine/

**Comment by andrewhsu** [comment]
@pdbogen apologies for the bad link. The correct URL for downloading the `docker-ce` package for `ubuntu` is within the subdirectory of https://download.docker.com/linux/ubuntu/dists/ and navigate to the subdirectory for your ubuntu version, channel, and architecture within the pool directory. For example, for `xenial` version, `stable` channel, `amd64` architecture, navigate to https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/ and download the .deb package for the Docker version you want.
