### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntu.md

### ISSUE THREAD

**Issue by euyuil** [docker/docker.github.io#2294]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/)

Under section "Install from a package". The URL https://download.docker.com/linux/ubuntu/pool/stable-17.03/amd64/ can't be opened.

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2F2E8CBC5085BB93</RequestId>
<HostId>
f3M9ofJZ0WExWlLpFjubvg43ruyn0ea8I/QLT3I63hcC0PQw3Z1KmvM+fW2UlM7wOZiOmHxET98=
</HostId>
</Error>
```

**Comment by thaJeztah** [comment]
The index pages are currently missing for download.docker.com (see https://github.com/docker/docker/issues/31987)

I'm not sure what the exact URL's are for the packages; if you require offline installation, you can download the `docker-engine` package, which is the old name for the `docker-ce` package, and can be found here; http://apt.dockerproject.org/repo/pool/main/d/docker-engine/

**Comment by andrewhsu** [comment]
@euyuil apologies for the broken link, documentation has been fixed now and the correct url for downloading `xenial` `arm64` packages from the `stable` channel, for example, would be: https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/
