### ISSUE TITLE
Feedback for: engine/getstarted/step_four.md

### ISSUE THREAD

**Issue by GenweiWu** [docker/docker.github.io#2298]
File: [engine/getstarted/step_four.md](https://docs.docker.com/engine/getstarted/step_four/)

this is not suitable for Centos,which can not run ok.
![image](https://cloud.githubusercontent.com/assets/16630659/23899854/cdc11d52-08f1-11e7-95c6-1fc4b27f5adb.png)

**Comment by GenweiWu** [comment]
run in the shell is OK
![image](https://cloud.githubusercontent.com/assets/16630659/23899896/09497496-08f2-11e7-9212-733d2592c6ac.png)

and the file content is:
![image](https://cloud.githubusercontent.com/assets/16630659/23928964/dfcf6532-095d-11e7-99b9-95ea87a9f6af.png)

**Comment by johndmulhausen** [comment]
Assigning to self since getting started is getting replaced

**Comment by johndmulhausen** [comment]
This topic no longer exists.
