### ISSUE TITLE
Feedback for: engine/admin/puppet.md

### ISSUE THREAD

**Issue by Lud3rik** [docker/docker.github.io#2303]
Hello,

I am currently seeking statements about extra parameters and redirection of ports.

Here is my puppet code:

node default {
        include docker

docker::image { 'fusengine/owncloud':
  ensure => 'absent',
}

docker::run { 'owncloud':
  image   => 'fusengine/owncloud',
  ports   => ['8080:80'],
}

}

The problem I am facing is that on the puppet node, an ipv6 socket is opened by default.
tcp6       0      0 :::8080                 :::*                    LISTEN

So the consequence of this issue is that the docker owncloud cannot be reached from the outside.
So if you can add documentation explaining this usecase it will be very usefull.

Regards,

File: [engine/admin/puppet.md](https://docs.docker.com/engine/admin/puppet/)

**Comment by johndmulhausen** [comment]
I don't think we can troubleshoot specific solution problems for you, sorry. In general the bug isn't making intuitive sense to me, since the port is open it would follow that its reachable.
