### ISSUE TITLE
Duplicate images used within topic

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#2339]
File: [docker-cloud/infrastructure/link-aws.md](https://docs.docker.com/docker-cloud/infrastructure/link-aws/)

The images in step 3 and step 5 in "Create a dockercloud-role role" are the same.

**Comment by bdwill** [comment]
dibs for hackathon.

Step 5 doesn't have an image anymore, perhaps fixed in another issue.

**Comment by londoncalling** [comment]
Closing this issue, give @bdwill 50 points?
