### ISSUE TITLE
Right-hand menu-like bar obscures page content

### ISSUE THREAD

**Issue by tripleee** [docker/docker.github.io#2345]
File: [engine/admin/logging/overview.md](https://docs.docker.com/engine/admin/logging/overview/)
(... though this probably affects every documentation page on the Docker site).

The right-hand menu-like bar overlaps the text in a non-maximized browser window and I can't find a way to get rid of it.

Adding insult to injury, the left-hand margin is approximately the same width and is completely empty, so the page would actually be legible even with the menu-like thing if the content was shifted over to the left to make room for the menu-like bar without obscuring the page's content.

For what it's worth, I'm using Chrome on OSX.

<img width="1016" alt="screen shot 2017-03-15 at 13 58 40" src="https://cloud.githubusercontent.com/assets/2160915/23947492/a1a0e02c-0987-11e7-93eb-5b1f9de42a18.png">

**Comment by tripleee** [comment]
Scrolling down to the end of the page revealed that there is a white on white icon which you can click to get rid of the obnoxious bar.  Perhaps coloring this so it is actually visible would already help a lot.

**Comment by tripleee** [comment]
... though the content is still too wide for my browser window.  Why do you insist on a particular width?  This makes the site absolutely unusable in some configurations, and extremely inconvenient in mine.  Perhaps your designers should be taught to examine their web sites with different browsers at different sizes?

**Comment by tripleee** [comment]
As a partial workaround, https://github.com/docker/docker.github.io/blob/master/engine/admin/logging/overview.md is basically legible.

**Comment by johndmulhausen** [comment]
This has been fixed with recent CSS updates. Thanks :)
