### ISSUE TITLE
WordPress: Error in compose file

### ISSUE THREAD

**Issue by yaswanthsunny** [docker/docker.github.io#2361]
File: [compose/wordpress.md](https://docs.docker.com/compose/wordpress/)
$ docker-compose up -d
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

After the 4th step, its giving this error

**Comment by JimGalasyn** [comment]
I've run through this walkthrough, and I can't reproduce your issue. If you can reproduce the error, can you post the yml file?

**Comment by johndmulhausen** [comment]
We'll be importing the official WordPress library readme soon; self-assigning for now

**Comment by johndmulhausen** [comment]
This file is deprecated
