### ISSUE TITLE
Should note "volume prune" is only supported with daemon version >= 1.25

### ISSUE THREAD

**Issue by aloon** [docker/docker.github.io#2366]
File: [engine/reference/commandline/volume_prune.md](https://docs.docker.com/engine/reference/commandline/volume_prune/)

inform about:
only supported with daemon version >= 1.25

**Comment by surajnarwade** [comment]
I will take this up, @londoncalling `hackathon` label :)

**Comment by mstanleyjones** [comment]
We don't document earliest supported versions for things like this. The APIs are backward compatible.
