### ISSUE TITLE
The parameter "--disable" should be "--disablerepo"

### ISSUE THREAD

**Issue by peter-mueller-nvg** [docker/docker.github.io#2370]
File: [engine/installation/linux/fedora.md](https://docs.docker.com/engine/installation/linux/fedora/)

`$ sudo dnf config-manager --disable docker-ce-edge`

The parameter "--disable" should be "--disablerepo" (at least on Fedora 25).

**Comment by shubheksha** [comment]
The parameter in the current docs is `--set-disabled`. Is this issue still relevant?

**Comment by mstanleyjones** [comment]
It's now fixed.
