### ISSUE TITLE
Engine API docs - shortcuts to links return you to top of the page

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#2373]
### Problem description
When browsing the API docs (https://docs.docker.com/engine/api/v1.26/#), there are links that appear which I'd assume should take you to the relative link.  I know that when you scroll it will update the browser URL bar with the relative link but the little link icons are deceiving and take you all the way to the top which is quite undesirable

![api_link](https://cloud.githubusercontent.com/assets/414445/24044517/f3f666ec-0af1-11e7-9030-1d09b319ccb6.gif)

Still showing where the link is pointing to:
![screenshot 2017-03-17 at 9 00 49 am](https://cloud.githubusercontent.com/assets/414445/24044532/0a9ff87c-0af2-11e7-9144-58e6ea109bdd.png)

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/api/v1.26/#

### Project version(s) affected

At least the v1.26 API docs; hadn't checked the othrs

**Comment by johndmulhausen** [comment]
Can't repro this; I think this might be fixed in the newest ReDoc version, which we're now using

**Comment by mbentley** [comment]
Still happening for me.

1. Go to https://docs.docker.com/engine/api/v1.26/#tag/Swarm
2. Scroll down to `Inspect Swarm`.
3. Click the link that is presented
4. Get scrolled to the top
