### ISSUE TITLE
Feedback for: engine/installation/linux/centos.md

### ISSUE THREAD

**Issue by asloan7** [docker/docker.github.io#2377]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

Access denied to the rpm dir mentioned here, https://download.docker.com/linux/centos/7/x86_64/stable/Packages/

**Comment by thaJeztah** [comment]
The index pages are currently missing for download.docker.com (see https://github.com/docker/docker/issues/31987)

You can download the 17.03.0 CE packages using these URLs;

https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.03.0.ce-1.el7.centos.x86_64.rpm
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-selinux-17.03.0.ce-1.el7.centos.noarch.rpm

**Comment by andrewhsu** [comment]
@asloan7 apologies for the broken link, url should now be browsable: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/
