### ISSUE TITLE
Instructions fail for making the docker engine listen on a tcp port (as well as a unix socket)

### ISSUE THREAD

**Issue by akc42** [docker/docker.github.io#2379]
File: [engine/admin/systemd.md](https://docs.docker.com/engine/admin/systemd/)

I have an installation on a raspberry pi (using raspbian jessie), and am trying to follow instructions to make the docker engine listen on a tcp port (as well as a unix socket).  As this section suggests, I created the `/etc/docker/daemon.json` file and added a `"hosts": ["tcp://0.0.0.0:4243", "unix:///var/run/docker.sock"]` entry.  However, this approach fails with a message that says that there is an entry in the config file trying to override the flags passed to the daemon on startup.  I think this is because `/lib/systemd/system/docker.service` starts the service with the the flag `-H fd://`

It is not clear the correct approach here, but the documentation just doesn't match. I am worried that editing `/lib/systemd/system/docker.service` to remove the flags will just get overwritten on the next upgrade.  Perhaps the debian package should provide a small daemon.json file rather than provide flags on the start

**Comment by NonCreature0714** [comment]
Checking this out! @johndmulhausen @mstanleyjones @londoncalling

**Comment by londoncalling** [comment]
@NonCreature0714 adding hackathon labels for you.

**Comment by NonCreature0714** [comment]
This is taking me a while to work through, I'm going to have to take this home tonight so I can connect to my own network.

**Comment by NonCreature0714** [comment]
Still working through this! It's a tad more time consuming that I expected.

**Comment by mstanleyjones** [comment]
Any luck, @NonCreature0714 ? Let me know if you are not ready to submit a PR for this one and I'll remove it from the Hackathon milestone. You can feel free to keep working through it, though!

**Comment by NonCreature0714** [comment]
@mstanleyjones I'm still working on it, but I've been super busy! I'll dedicate time to it tonight though! I'd like to see it through

**Comment by NonCreature0714** [comment]
@mstanleyjones I re-read your comment - I'm not ready to submit a PR at this time, sorry that wasn't clear! I hope to submit one tonight, but I'm aware that's probably after the Hackathon is over!

**Comment by akc42** [comment]
@NonCreature0714 what happened to this?

**Comment by NonCreature0714** [comment]
@akc42 I'm in finals, so have been extremely busy. Otherwise, no change of plans, just had other priorities come up.
