### ISSUE TITLE
Feedback for: engine/userguide/networking/index.md

### ISSUE THREAD

**Issue by bseib** [docker/docker.github.io#2389]
File: [engine/userguide/networking/index.md](https://docs.docker.com/engine/userguide/networking/)

Can't see the `<pre></pre>` text in this table:

![image](https://cloud.githubusercontent.com/assets/1313561/24075454/0633d6cc-0bc0-11e7-8797-d2974f2c9ef4.png)

Ah ha! There's the culprit:

![image](https://cloud.githubusercontent.com/assets/1313561/24075464/36fd5b98-0bc0-11e7-8431-3f5cf0bd9ef8.png)

Let's check:

![image](https://cloud.githubusercontent.com/assets/1313561/24075470/4d4d1050-0bc0-11e7-8819-55613011d2bf.png)

Much better. :-) 

![image](https://cloud.githubusercontent.com/assets/1313561/24075475/70dbf5c2-0bc0-11e7-8d69-9bb876b42da5.png)

**Comment by johndmulhausen** [comment]
Fixed by some recent CSS fixes
