### ISSUE TITLE
Syntax highlighting makes part of command look like comment

### ISSUE THREAD

**Issue by Dfred** [docker/docker.github.io#2390]
File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/)

In section **Creating and mounting a data volume container**, part of the following line appears greyed and in italic, without explicit reason:

> $ docker create -v /dbdata --name dbstore training/postgres /bin/true

If indeed this is on purpose, adding a word about it would be valuable.

**Comment by johndmulhausen** [comment]
Related: #2512

**Comment by johndmulhausen** [comment]
The solution is to change the triple backticks around the coding blocks so that they have the `none` label directly afterwards, e.g.

```none
```none
code {
  code code...
}
```

**Comment by shubheksha** [comment]
I'll take this up!
