### ISSUE TITLE
Add "continue" instructions post-install

### ISSUE THREAD

**Issue by PaulSchulz** [docker/docker.github.io#2396]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/)

Add something like.. "Continue below in the 'Install Docker' section", at the end of the "Install Docker CE"

**Comment by shubheksha** [comment]
I'll take this one up!

**Comment by mstanleyjones** [comment]
No action for two days, so this is up for grabs!

**Comment by johndmulhausen** [comment]
@alvin319 get 25 points for discovering this was a no-op
