### ISSUE TITLE
Unclear if docker group is auto-created in post-install (CentOS 7)

### ISSUE THREAD

**Issue by tgillot** [docker/docker.github.io#2397]
File: [engine/installation/linux/linux-postinstall.md](https://docs.docker.com/engine/installation/linux/linux-postinstall/)

I am researching Docker as part of a class project. While working through the Post-installation steps for Linux, I noticed that the docker group was already present on my CentOS 7 VM. Is the docker group created during the install?

**Comment by mstanleyjones** [comment]
@thaJeztah @andrewhsu can you please verify the expected behavior? I thought for CentOS and RHEL, no group was created automatically.

**Comment by mstanleyjones** [comment]
Closed via #4069
