### ISSUE TITLE
Mention the versions of the bundled tools on install page

### ISSUE THREAD

**Issue by mosesonline** [docker/docker.github.io#2398]
File: [toolbox/overview.md](https://docs.docker.com/toolbox/overview/)
It would be nice to have versions of the bundled tools not only the names.

**Comment by shubheksha** [comment]
Where can I find the appropriate versions to include here?

**Comment by mstanleyjones** [comment]
I think it would be better to go in a different direction. I think each of these tools has a `--version` flag. Maybe just mention that. The version of each tool will probably change for each release of Toolbox. There may also be release notes somewhere that list the component versions.

**Comment by mstanleyjones** [comment]
https://github.com/docker/toolbox/releases

**Comment by alvin319** [comment]
I'll try to tackle this one!
