### ISSUE TITLE
Feedback links are too close to content

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#24]
<img width="808" alt="screen shot 2016-09-30 at 16 16 00" src="https://cloud.githubusercontent.com/assets/1525937/19009480/4391a038-8729-11e6-8931-c7e8e5af64d1.png">

**Comment by johndmulhausen** [comment]
Fixed in 69ddac1efc18c7f9aee3832bcf0679ac503a9b2c
