### ISSUE TITLE
Can't scroll down left side sometimes

### ISSUE THREAD

**Issue by lucas1993ch** [docker/docker.github.io#2403]
File: [index.md](https://docs.docker.com/)
sometimes I can not scroll down the left

**Comment by johndmulhausen** [comment]
Likely to do with the JavaScript necessary to resize left side nav

**Comment by allejo** [comment]
`.sidebar`'s `position: fixed` rule is causing `#navbar` to take up 100% of the browser's height (which is being controlled by JS); similar to what's going on with the right sidebar too.

I'll call dibs on this one 👍  any pointers on where you guys have the code for this?

**Comment by londoncalling** [comment]
@allejo this _might_ be fixed. If not, can you work with @jsouth on this ?
cc: @johndmulhausen

**Comment by allejo** [comment]
Sure! I'm aware that @jsouth fixed the right sidebar width in #2804. Not sure if he's working on fixing the overlapping of both sidebars by the footer as seen here:

![current-scroll-issue](https://cloud.githubusercontent.com/assets/1246453/25156474/b11d59bc-244f-11e7-9ca9-4812d133eb77.gif)

PR #2860 has this behavior instead (still a WIP):

![patched-scroll-issue](https://cloud.githubusercontent.com/assets/1246453/25156489/bff87930-244f-11e7-89a5-10894a914a73.gif)

**Comment by londoncalling** [comment]
@allejo You are right! Go for it.

**Comment by johndmulhausen** [comment]
Points to @allejo for #2860
