### ISSUE TITLE
Feedback for: engine/installation/linux/centos.md

### ISSUE THREAD

**Issue by jorrillamustard** [docker/docker.github.io#2406]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

Under the Install from package section, the link to the community edition rpm files is broken or locked down. I receive the below information from the link:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
Error
Code>AccessDenied</Code
Message>Access Denied</Message
RequestId>8295B876D51DD105</RequestId
HostId
LzN6PGi5eJVgq1lhpTqxq/iCHZaCc//ySGI3vuA2klSdwRw9rleAL7LTGrlYONzNuVtfO1C4Fqg=
/HostId
/Error

**Comment by thaJeztah** [comment]
The index pages are currently missing for download.docker.com (see https://github.com/docker/docker/issues/31987)

You can download the 17.03.0 CE packages using these URLs;

https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.03.0.ce-1.el7.centos.x86_64.rpm
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-selinux-17.03.0.ce-1.el7.centos.noarch.rpm

**Comment by andrewhsu** [comment]
@jorrillamustard apologies for the borken link, the location in documentation should now be browsable: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/
