### ISSUE TITLE
Glossary should have entries for "namespace" and "layer"

### ISSUE THREAD

**Issue by pmerson** [docker/docker.github.io#2407]
File: [glossary.md](https://docs.docker.com/glossary/)

I'm writing to suggest adding these two items to the glossary. They're important to understand docker:
- namespace
- layer

**Comment by gabzillah** [comment]
Can I claim this for the hackathon? Thanks

**Comment by pmerson** [comment]
Yes, you can.  :^)



On Apr 12, 2017 20:30, "Gabby" <notifications@github.com> wrote:

Can I claim this for the hackathon? Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker.github.io/issues/2407#issuecomment-293735622>,
or mute the thread

**Comment by scjane** [comment]
@gabzillah Hi, are you still working on this issue?

**Comment by gabzillah** [comment]
hi @scjane yes I am still working on this issue :)

**Comment by johndmulhausen** [comment]
@gabzillah any updates?

**Comment by mstanleyjones** [comment]
No PR for this yet. @gabzillah @scjane if you have something ready to go, you can feel free to submit a PR! This is the last day for the hackathon! I'm going to go ahead and clear the `claimed` label until we have a PR in the pipeline.

**Comment by londoncalling** [comment]
Points to @subodh-dharma on this one.
