### ISSUE TITLE
Feedback for: engine/installation/linux/debian.md

### ISSUE THREAD

**Issue by Abhinav41** [docker/docker.github.io#2413]
File: [engine/installation/linux/debian.md](https://docs.docker.com/engine/installation/linux/debian/) mentions to visit this URL to download the deb package. However the page fails to load:

https://download.docker.com/linux/debian/pool/stable/amd64/

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>0C2D66C0D161126D</RequestId>
<HostId>
XqSh4WUMsImW7XNwa+wb6sxW6JJdy0T9uZKYP07HY/8aCv1MzGgT008ASkQ83f2XyucgUEYwj2M=
</HostId>
</Error>
```

**Comment by thaJeztah** [comment]
The index pages are currently missing for download.docker.com (see https://github.com/docker/docker/issues/31987)

I'm not sure what the exact URL's are for the packages; if you require offline installation, you can download the `docker-engine` package, which is the old name for the `docker-ce` package, and can be found here; http://apt.dockerproject.org/repo/pool/main/d/docker-engine/
