### ISSUE TITLE
Command-line completion for Compose needs more instructions for Mac

### ISSUE THREAD

**Issue by michelechersich** [docker/docker.github.io#2423]
File: [compose/completion.md](https://docs.docker.com/compose/completion/)

I've been installing for bash on Mac OS X. It works, but a change to the bash profile is also necessary, as reported in this post: http://davidalger.com/development/bash-completion-on-os-x-with-brew/

**Comment by drorata** [comment]
It worthy to also explain how to install the auto completion using MacPorts.

**Comment by jpooler** [comment]
#dibs for the hackathon

**Comment by mstanleyjones** [comment]
No action for two days, so this is up for grabs again!

**Comment by jpooler** [comment]
@mstanleyjones Sorry about the lack of movement on these, overcommitted myself a bit.

https://github.com/docker/docker.github.io/pull/2910 includes this issue.

**Comment by johndmulhausen** [comment]
Thanks for jumping back on it, @jpooler :)
