### ISSUE TITLE
404 in engine/admin/logging/log_tags.md (hyperlink for "logging context")

### ISSUE THREAD

**Issue by bestofmukul** [docker/docker.github.io#2430]
File: [engine/admin/logging/log_tags.md](https://docs.docker.com/engine/admin/logging/log_tags/)

Hyperlink for "logging context" in the following line is broken:
For advanced usage, the generated tag’s use go templates and the container’s logging context.

**Comment by olleolleolle** [comment]
The URL could be updated to an existing branch:

`https://github.com/docker/docker/blob/17.05.x/daemon/logger/loginfo.go`

**Comment by scjane** [comment]
#dibs

**Comment by shubheksha** [comment]
This issue is also a duplicate and can be closed.

**Comment by johndmulhausen** [comment]
Thanks @scjane and @shubheksha -- 25 points to @shubheksha for identifying the duplicate.
