### ISSUE TITLE
404 at: /reference/commandline/cli/

### ISSUE THREAD

**Issue by wlu2016** [docker/docker.github.io#2432]
URL: /reference/commandline/cli/

**Comment by mstanleyjones** [comment]
Where did you find the bad link? I can't find it mentioned anywhere on docs.docker.com, but the correct link is https://docs.docker.com/engine/reference/commandline/cli/. Please reopen this issue if you can provide the URL that has the bad link and that URL is on docs.docker.com. Thanks!
