### ISSUE TITLE
404 at registry/spec/auth/token.md (from registry/deploying.md)

### ISSUE THREAD

**Issue by imroc** [docker/docker.github.io#2433]
the bottom of registry/deploying.md has a reference to registry/spec/auth/token.md , but there is no  such file

**Comment by shubheksha** [comment]
This works as expected here: https://docs.docker.com/registry/deploying/#next
It links to https://docs.docker.com/registry/spec/auth/token/ which is accessible

**Comment by shubheksha** [comment]
This issue can be closed.
