### ISSUE TITLE
It's not obvious that you can configure the daemon with flags or a config file

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2442]
This article https://docs.docker.com/engine/reference/commandline/dockerd/ has a ton of information on how to configure the Docker daemon, but buried at the bottom of that page you have information on how to use a config file, instead of flags.

We also have other articles like this one that talk about the config file https://docs.docker.com/engine/admin/systemd/

I think we need a "top-level" admin page that tells:

1. Theres two ways to configure Docker. Using flags, or using a config file
2. If you use both, flags take precedence (needs confirmation)
3. Here's the configs that need to be done with environment vars or flags, because they're not available in the config file
4. Go here to check the flag reference
5. Go there to check the config file reference

With this, we could maybe delete that `systemd` article because we would have something more generic, or at least it wouldn't contain information that's valuable for other init systems.

**Comment by johndmulhausen** [comment]
This got fixed elsewhere. Closing per triage discussion.
