### ISSUE TITLE
Need insecure Registry instructions for Windows

### ISSUE THREAD

**Issue by theparticleman** [docker/docker.github.io#2444]
File: [registry/insecure.md](https://docs.docker.com/registry/insecure/)

The existing instructions are great for Linux. What about instructions for where to put cert files on Windows?

**Comment by joaofnfernandes** [comment]
I've researched this a bit and it seems that you can add your certs to

`C:\ProgramData\docker\certs.d\<hostname>\<hostname>.crt`. But this might have other side effects, like Docker stopping to use the system cert pool, thus stopping to trust other registries including Docker Hub. So we need to research this a bit more.

**Comment by L-Hudson** [comment]
exists in current docs. Closing ticket.
