### ISSUE TITLE
Guide for using insecure Registry "doesn't work"

### ISSUE THREAD

**Issue by mikeashbyseattle** [docker/docker.github.io#2446]
File: [registry/insecure.md](https://docs.docker.com/registry/insecure/)

This does NOT work. It just doesn't work for Ubuntu. We have tried everything. It doesn't appear to be Ubuntu but rather a Docker bug. The user should be able to EASILY force Docker to use insecure certs. Making it difficult by having users make several changes is actually far less secure. Developers are making all sorts of changes to their cert stores trying to get Docker to work. They are likely opening up security holes. You really need to fix this. This is clearly a bug in Docker. Docker error messages need to include WHERE it was looking!

**Comment by johndmulhausen** [comment]
@mikeashbyseattle Please provide your repro steps and the commands you used.

**Comment by johndmulhausen** [comment]
Closing due to no reply.
