### ISSUE TITLE
Offline installation option for DockerMsftProvider

### ISSUE THREAD

**Issue by ekitagawa** [docker/docker.github.io#2448]
### Problem description
 
Customers would like to install Docker engine offline.  Currently, the existing script "Install-Module -Name DockerMsftProvider..." fetches the package from the internet.
 
We have two customers asking for this for far.
 
### Problem location
 
OneGet/MicrosoftDockerProvider
https://github.com/OneGet/MicrosoftDockerProvider
 
### Project version(s) affected
 
1.0.0.2
 
### Suggestions for a fix
 
Will it be possible to enhance this script to allow offline install?  For example, allow users to download zip archive separately, and additional parameter with DockerMsftProvier to point to it.
 
Thank you in advance!

**Comment by friism** [comment]
```
# on online machine
invoke-webrequest -UseBasicparsing -Outfile docker.zip https://download.docker.com/components/engine/windows-server/17.03/docker-17.03.0-ee.zip
# on offline machine
Expand-Archive docker.zip -DestinationPath $Env:ProgramFiles
Remove-Item -Force docker.zip
$Env:ProgramFiles\docker\dockerd.exe --register-service
Start-Service docker
```

**Comment by friism** [comment]
cc @JimGalasyn in case this is something you'd like to help with.

**Comment by JimGalasyn** [comment]
Documented [here](https://docs.docker.com/docker-ee-for-windows/install/).
