### ISSUE TITLE
Additional docs for UCP's external cert setup

### ISSUE THREAD

**Issue by nicolaka** [docker/docker.github.io#2450]
### Problem description

There's a need to add more info/details/examples on using `--external-server-cert` when installing UCP. 

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/datacenter/ucp/2.1/reference/cli/install/#options

### Project version(s) affected

UCP 2.1.1

**Comment by joaofnfernandes** [comment]
The page you're pointing to tells

>The certificates used by the UCP web server. Create a volume named ‘ucp-controller-server-certs’ and copy the ca.pem, cert.pem, and key.pem files to the root directory. Then run the install command with the ‘–external-server-cert’ flag.

What information is missing there that would help you? Is it which format should the files be in, or what certs should be in ca.pem vs cert.pem?

**Comment by nicolaka** [comment]
I actually thought we moved to using `"$(cat cert.pem)"` format. But would be good to point out in the table that you described the exact format at the beginning of the page.

**Comment by joaofnfernandes** [comment]
I think we did something like that, but for the license.

>  The license used by UCP, by bind-mounting the file at  '/config/docker_subscription.lic' in the tool.  E.g. -v /path/to/my/config/docker_subscription.lic:/config/docker_subscription.lic  or by specifying with '--license "$(cat license.lic)"

But I'm not sure we've made changes that allow you to pass the TLS certs/keys using flags. Maybe @alexmavr can shed some light on this.

**Comment by clemenko** [comment]
Is there a way to add the certs at run time WITHOUT creating a docker volume? Sandia is asking because they want to automate the building of clusters. And there is no API for updating the certificates.

**Comment by joaofnfernandes** [comment]
If you already have UCP running, the volume is already created so you'll need to change the TLS cert/keys and restart the controller container. If you have multiple managers, you need to do this on every one of them.

**Comment by clemenko** [comment]
Is this still necessary?

**Comment by joaofnfernandes** [comment]
I think we can leave this open since our docs don't make it clear how to script an installation with custom TLS certs.

**Comment by JimGalasyn** [comment]
From @alexmavr : "place the certs in the `ucp-controller-server-certs` volume on every manager node before installing UCP or before joining said manager to an existing UCP cluster."

**Comment by JimGalasyn** [comment]
An example, per @clemenko : 

```
#echo "adding certificates"
#token=$(curl -sk "https://<your-site>/auth/login" -X POST -d '{"username":"administrator","password":"password"}'|jq -r .auth_token)

#curl -sk 'https://<your-site>/api/nodes/certs' -H 'accept-encoding: gzip, deflate, br' -H "authorization: Bearer $token" -H 'accept: application/json, text/plain, */*' --data-binary '{"ca":"-----BEGIN CERTIFICATE-----\nMIICKDCCAc6gAwIBAgIUTCPedoVlUI ... bQQ==\n-----END CERTIFICATE-----\n","key":"server3","cert":"server2"}' --compressed
```

**Comment by JimGalasyn** [comment]
API is evolving, so bumping this issue out to EE/sprint-4.

**Comment by L-Hudson** [comment]
Product evolution has addressed. Closing ticket.
