### ISSUE TITLE
Set up dev environment: Text file busy error

### ISSUE THREAD

**Issue by zkry** [docker/docker.github.io#2466]
File: [opensource/project/set-up-dev-env.md](https://docs.docker.com/opensource/project/set-up-dev-env/)

Step 8 under task three states:
```
cp bundles/1.12.0-dev/binary-client/docker* /usr/bin/
cp bundles/1.12.0-dev/binary-daemon/docker* /usr/bin/
```

After trying to execute the second copy command I encountered the error:
`cp: cannot create regular file '/usr/bin/dockerd': Text file busy`

I assumed that this is because that file was being used by docker. Upon killing docker I was able to run that step. The tutorial was confusing on this point and maybe include a step for deleting the docker process (or something else that I wasn't aware of).

**Comment by mstanleyjones** [comment]
@thaJeztah PTAL
