### ISSUE TITLE
Upcoming Django 2.0 will not officially support python 2.x

### ISSUE THREAD

**Issue by anthonyhendrickson** [docker/docker.github.io#2468]
File: [compose/django.md](https://docs.docker.com/compose/django/)

FYI:

Upcoming Django 2.0 will not officially support python 2.x -- docs will need to update the python image version in compose.yml. Nothing wrong in updating it early for users wanting to play around with Django 2.0 on Python 3.x later this year.

Alternatively, the requirements.txt should be adjusted to include the proper version req's: `Django>=1.8,<2.0`

(Django 2.0 will be released December this year)

**Comment by surajnarwade** [comment]
I forget to mention, I will pick this up, isn't this issue for hackathon ?
