### ISSUE TITLE
Create diagrams for scanning and jobrunner

### ISSUE THREAD

**Issue by sarahpark** [docker/docker.github.io#2474]
Awesome sketches from @venalen 

## Scanning:
A:
![scanning-1](https://cloud.githubusercontent.com/assets/1562758/24317297/fe1c0638-10b2-11e7-92cc-08e963965f73.jpg)
B:
![scanning-2](https://cloud.githubusercontent.com/assets/1562758/24317298/fe1d31a2-10b2-11e7-8ee2-8032f38e6c58.jpg)

(**Note**: Follow up with @toli, b/c he asked for the .sketch file to create the diagram, but unsure if he completed it)

-----

## Jobrunner:
![jobrunner-1](https://cloud.githubusercontent.com/assets/1562758/24317308/125e8774-10b3-11e7-8f46-40afc62cba73.jpg)
![jobrunner-2](https://cloud.githubusercontent.com/assets/1562758/24317307/125811c8-10b3-11e7-8eea-8b9e52b45f63.jpg)

**Comment by sarahpark** [comment]
Scanning A:

<kbd>

![scanning-1](https://cloud.githubusercontent.com/assets/1562758/24777962/dd9562cc-1adc-11e7-9a3b-5e27dca91a3b.png)
</kbd>

**Comment by johndmulhausen** [comment]
Ping @sarahpark Did any other other diagrams get created? The first one looks great!

**Comment by sarahpark** [comment]
@johndmulhausen thanks! For scanning, no more diagrams were made: the above diagram ("Scanning A") was created because of a DockerCon Austin '17 presentation: https://docs.google.com/a/docker.com/presentation/d/1duvH79L1ncnStDaHNm-XhV7WH0IlVT_St0b3kwRQW7U/edit?usp=sharing

**Comment by L-Hudson** [comment]
Due to the backlog, and refactoring, we're closing legacy tickets. If you think this is in error, please reopen. Thank you.
