### ISSUE TITLE
Use of docker-machine create erroneously refers to --url option

### ISSUE THREAD

**Issue by bioffe01** [docker/docker.github.io#2478]
File: [machine/get-started-cloud.md](https://docs.docker.com/machine/get-started-cloud/)

there is no --url flag for docker-machine command

**Comment by joaofnfernandes** [comment]
It depends on the driver you're using. If you're using Virtualbox, the flag is `--virtualbox-boot2docker-url`.

**Comment by shubheksha** [comment]
Can this be added as note?

**Comment by joaofnfernandes** [comment]
I think the best way to solve this is by reviewing the "[Adding a host without a driver](https://docs.docker.com/machine/get-started-cloud/#adding-a-host-without-a-driver)" section. It's not clear to me what is the use case. Is it "I want to provision a node manually, but then be able to do eval $(docker-machine env <machine>-name)"?

Addressing this will require a bit of research to understand the use case and validate that the snippet works.

**Comment by jmaitrehenry** [comment]
I think it's for managing a docker host manually provisioned with the same workflow as docker host created by docker machine.

For resolving this issue, I purpose to rewrite:
> You can add a host to Docker which only has a URL and no driver. Then you can use the machine name you provide here for an existing host so you don’t have to type out the URL every time you run a Docker command.

For something like: 
> You can register an already existing docker host by passing the daemon url. With that, you can have the same workflow than an host provisioned by docker-machine.

**Comment by jmaitrehenry** [comment]
More information about the none driver: https://github.com/docker/machine/issues/2667
