### ISSUE TITLE
COPY/ADD command has confusing language

### ISSUE THREAD

**Issue by ekkis** [docker/docker.github.io#2480]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

the documentation for COPY/ADD states:

> If <dest> does not end with a trailing slash, it will be considered a regular file and the contents of <src> will be written at <dest>.

if <dest> is considered a regular file, how can the contents of <src> be written *at* a regular file? that makes no sense and needs clarification.  I mean it in the case when <src> is a multiplicity of files

**Comment by johndmulhausen** [comment]
We discussed as a team and feel the text is making sense; "/" denotes a directory, otherwise that filename is used.

**Comment by ekkis** [comment]
what I'm saying is that if `<dest>` is a regular file and `<src>` specifies multiple files (using a glob) then, how can many files be written into one? are they concatenated? or?
