### ISSUE TITLE
Documentation on how to install Docker engine offline

### ISSUE THREAD

**Issue by ekitagawa** [docker/docker.github.io#2496]
### Problem description
 

 
Two customers have asked us on how to install Docker engine on on-premise server with no network connection. 
 
However, our manual doesn't cover how to install Docker engine on Windows Server.  I am not sure if we should put this on our docs or engage Microsoft to update theirs.
    
### Problem location
 

- Microsoft already hosts install instruction, so this is the most logical place to put. 
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server
  
### Project version(s) affected

 
17.03

### Suggestions for a fix

 
These steps work.

1. do this from online server
```
# on online machine
invoke-webrequest -UseBasicparsing -Outfile docker.zip https://download.docker.com/components/engine/windows-server/17.03/docker-17.03.0-ee.zip
```

2. do this from offline server
```
#— extract the archive —
Expand-Archive docker.zip -DestinationPath $Env:ProgramFiles
#clean up zip
Remove-Item -Force docker.zip
# enable hyper-v if not yet enabled
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
  
#adding docker to PATH
$env:path += "$env:ProgramFiles\Docker"
 
#register docker daemon as a service
dockerd --register-service
 
#start the daemon
Start-Service docker
```

**Comment by JimGalasyn** [comment]
Topic is live: https://docs.docker.com/docker-ee-for-windows/install/
