### ISSUE TITLE
Broken link in the menu DTR > Configuration > Auth

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#25]
<img width="240" alt="screen shot 2016-09-30 at 16 40 34" src="https://cloud.githubusercontent.com/assets/1525937/19009830/b99e7f32-872c-11e6-8bb8-fb99cad89e2f.png">

**Comment by johndmulhausen** [comment]
Fixed in 39055aeab4096facd4f5b213dfb8f931fbccc079
