### ISSUE TITLE
set-up-dev-env.md should be updated to reflect latest Docker version

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker.github.io#2501]
File: [opensource/project/set-up-dev-env.md](https://docs.docker.com/opensource/project/set-up-dev-env/) should be updated to reflect latest versions of Docker, and using Docker for Mac

**Comment by BatON-RW** [comment]
@ManoMarks does this issue reflect that `docker-cli` is a separate project now and `Task 3. Make a code change` in [opensource/project/set-up-dev-env.md](https://docs.docker.com/opensource/project/set-up-dev-env/) is not relevant?

**Comment by ManoMarks** [comment]
No, if you look for instance at Task 2, item 9 you'll see it lists the latest docker version as 1.12. I think it was elsewhere as well.

**Comment by johndmulhausen** [comment]
Let's add a variable to `_config.yaml` that has the current Engine version/path/etc to fix this.

**Comment by mstanleyjones** [comment]
Closed in favor of #2625
