### ISSUE TITLE
Possibly inconsistent instructions when configuring daemon

### ISSUE THREAD

**Issue by genevaya** [docker/docker.github.io#2510]
File: [engine/admin/systemd.md](https://docs.docker.com/engine/admin/systemd/)

Hello : between steps 4 and 5 ... the doc goes from "create /etc/systemd/docker.service.d/docker.conf" ok ... then in step 5 it says "docker.service" ... where is this file located? 

Secondly, the step 5 needs more explanations. 

thanks

**Comment by bdwill** [comment]
dibs for hackathon

Possibly fixed already as the current documentation doesn't match @genevaya's comment.

**Comment by joaofnfernandes** [comment]
Yup. It looks like there were two commits with major changes to this article, and in the process probably addressed this feedback.
@bdwill I don't believe there's anything to do here, so I'm closing this issue and removing it from the hackathon. Can you pick something else to hack or did you started working on this?

**Comment by bdwill** [comment]
@joaofnfernandes all good, just trying to claim points however possible!

**Comment by joaofnfernandes** [comment]
😂 let me know if you can't find enough things to fix. I'm sure we'll be able to find more things that need fixing

**Comment by londoncalling** [comment]
Awarded 25 points to @bdwill for verifying this was fixed.
