### ISSUE TITLE
Feedback for: datacenter/dtr/2.2/guides/user/access-dtr/configure-your-notary-client.md

### ISSUE THREAD

**Issue by adrrrrrrrian** [docker/docker.github.io#2511]
File: [datacenter/dtr/2.2/guides/user/access-dtr/configure-your-notary-client.md](https://docs.docker.com/datacenter/dtr/2.2/guides/user/access-dtr/configure-your-notary-client/)

The command `curl <download-url> -o notary` should be `curl -L <download-url> -o notary` so that it will download the file rather than an HTML page.

**Comment by joaofnfernandes** [comment]
Fixed by #2515
