### ISSUE TITLE
Syntax highlighting makes part of command look like comments

### ISSUE THREAD

**Issue by lacivert** [docker/docker.github.io#2512]
File: [toolbox/faqs/troubleshoot.md](https://docs.docker.com/toolbox/faqs/troubleshoot/)

![image](https://cloud.githubusercontent.com/assets/945612/24412818/2d2d698a-13e2-11e7-9b9c-3fb5c6e5f436.png)

this part:

> `docker-machine create --driver virtualbox default`

after -- (double dash) it looks like it is a comment and looks like you shouldn't type `--driver...`

Can you make that look as it is not a comment?

**Comment by johndmulhausen** [comment]
Solvable if someone adds `none` after the triple backticks on the example

**Comment by mstanleyjones** [comment]
Change the syntax highlighting hint to `none`.

**Comment by scjane** [comment]
#dibs

**Comment by shubheksha** [comment]
This renders correctly now, this issue can be closed.

**Comment by lacivert** [comment]
Thanks
