### ISSUE TITLE
Extend plugins docs need to mention global-scoped networks and IPAM plugins

### ISSUE THREAD

**Issue by hervenicol** [docker/docker.github.io#2514]
Hi all,

The doc here: [engine/extend/plugins_network.md](https://docs.docker.com/engine/extend/plugins_network/) says that:
> Docker Engine running in swarm mode currently only supports the built-in overlay driver for networking.

But Docker 1.13 changelog says it now has :
> Support for global-scoped network and ipam plugins in swarm-mode #27287

So I suppose this page is outdated, but also I'm uncomfortable with the whole network plugin documentation, particularly with these points:
* external plugin / engine-managed plugins.
* docker standalone net plugins / legacy swarm net plugins (global mode) / swarm-mode net plugins.

When I click the various documentation links, I'm never sure which case what I'm reading applies to.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #498](https://github.com/docker/cli/issues/498) via [**ZenHub**](https://www.zenhub.com/)
