### ISSUE TITLE
404 at: /v1.7/articles/articles/userguide/dockerlinks/

### ISSUE THREAD

**Issue by marcmerlin** [docker/docker.github.io#2528]
URL: /v1.7/articles/articles/userguide/dockerlinks/

https://docs.docker.com/v1.7/articles/networking/#binding-ports
send me to 
Again, this topic is covered without all of these low-level networking details in the Docker User Guide document if you would like to use that as your port redirection reference instead.
and docker user guide had the bad link

**Comment by johndmulhausen** [comment]
@marcmerlin We'll have a look, but you should know that Docker 1.7 is *very old* and has not been supported for some time.

**Comment by marcmerlin** [comment]
Which version of docker is irrelevant, google brought me to that page for a query on command flags and then the link on that page was broken, so I reported it as requested by your site :)

**Comment by mstanleyjones** [comment]
@marcmerlin you probably want https://docs.docker.com/engine/userguide/networking/default_network/binding/. Can you remember what you typed in Google to get that search result? We don't even publish archives for Docker 1.7 anymore, so I can't actually even directly address this for you.

**Comment by mstanleyjones** [comment]
Closed via #2786

**Comment by marcmerlin** [comment]
@mstanleyjones sadly this was a while ago so I don't have the exact search query I typed anymore, sorry.
