### ISSUE TITLE
Email flag

### ISSUE THREAD

**Issue by titpetric** [docker/docker.github.io#2534]
File: [engine/reference/commandline/login.md](https://docs.docker.com/engine/reference/commandline/login/), CC @mstanleyjones

Email flag was removed in one of the recent docker versions. It's already not available with 1.12.3, the docs should reflect this somehow.

~~~
root@serenity:~/github/titpetric/sonyflake# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:45:16 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:45:16 2016
 OS/Arch:      linux/amd64

root@serenity:~/github/titpetric/sonyflake# docker login --help

Usage:  docker login [OPTIONS] [SERVER]

Log in to a Docker registry.

Options:
      --help              Print usage
  -p, --password string   Password
  -u, --username string   Username
~~~

**Comment by mstanleyjones** [comment]
It's not removed, it's deprecated: https://github.com/docker/docker/blob/master/cli/command/registry/login.go#L44

We generate the reference file you are seeing straight from the code, and we do not filter out deprecated flags. Maybe this is possible, but that would need to be a feature request in `docker/docker`. Thanks!
