### ISSUE TITLE
Eliminate confusion of pre_build file name in the docs

### ISSUE THREAD

**Issue by teodorescuserban** [docker/docker.github.io#2535]
File: [docker-cloud/builds/advanced.md](https://docs.docker.com/docker-cloud/builds/advanced/), CC @londoncalling 

In two-phase builds the pre-build is spelled correctly (as in English) but marked as it is a keyword.

This made me waste an hour of wondering why the pre-build is not being executed.

Maybe drop the Englush spelling in favor of the actual file name (pre_build, with underscore instead of dash)?

Thank you for documentation!

**Comment by shubheksha** [comment]
I'll take this up!
