### ISSUE TITLE
Broken HTML on Compose file reference

### ISSUE THREAD

**Issue by EvGe22** [docker/docker.github.io#2536]
### Problem description

One of the items on the right menu of the 'Compose file version 3 reference' page is broken.
It says 
   4 class=”panel-title” id=”collapsible-group-item-3”>  Example Compose file version 3  
instead of just
   Example Compose file version 3 

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/compose/compose-file/

![image](https://cloud.githubusercontent.com/assets/15244527/24458329/4b2ec112-14a1-11e7-8f9c-300bc696f2e2.png)

**Comment by johndmulhausen** [comment]
Fixed by @mstanleyjones in another PR
