### ISSUE TITLE
Consider cherry-picking changes from 17.03 to main

### ISSUE THREAD

**Issue by aschauer** [docker/docker.github.io#2538]
File: [glossary.md](https://docs.docker.com/glossary/), CC @johndmulhausen 

It appears there are at least two glossaries: 

- The one I'm commenting on here: https://docs.docker.com/glossary/ (which is on 17.03.x, but uses a yaml that appears to be in master)
- This one: https://docs.docker.com/engine/reference/glossary/ (17.03.x)

I was going to create a pull request for some fixes to the (non-engine) glossary that I get when I click the glossary button on https://docs.docker.com/, but then I realized those fixes had already been made in the Engine glossary.

I think it would be good to cherry-pick changes from the 17.03.x branch to master. There are quite a few improvements, but, for example, it would be good to pick up
- the improved bulleted list formatting on terms like "container" 
- the definition of bridge

Both of those improvements appear to be in 17.03.x.

**Comment by johndmulhausen** [comment]
Hey, our glossary has diverged from the Engine at this point and it's not actually possible to cherry pick from one place to another. We will probably be deleting the Engine glossary at some point soon so things like this don't happen again.

**Comment by aschauer** [comment]
OK, to be clear, the fixes are in the Engine glossary, whereas the main one is "behind". IOW, if I had to pick one, I'd tend towards deleting the contents of the main glossary and keeping the contents of the Engine glossary. The Engine glossary includes additional terms (like the definition of bridge) and also has formatting fixes. FWIW, the Engine glossary is the #1 result of the google search "docker glossary"...so I'd think about redirects and SEO, too.
