### ISSUE TITLE
404 at: /installation/windows/

### ISSUE THREAD

**Issue by wabernathy** [docker/docker.github.io#255]
URL: /installation/windows/ is 404. (https://docs.docker.com/installation/windows)

The referring page is: [https://docs.docker.com/machine/install-machine/]

You guys still looking for a tech writer? 

--William

**Comment by tealtail** [comment]
`/installation/windows/` is also referenced in kitematic/index.md, leading to a 404

I noticed the `alias: /installation/mac` in https://github.com/docker/docker.github.io/blob/master/docker-for-mac/index.md

and the lack of a similar alias (`/installation/windows`) for https://github.com/docker/docker.github.io/blob/master/docker-for-windows/index.md

I'd like to take this one, but I need a bit of guidance. 

Would a change be needed in https://github.com/docker/docker.github.io/blob/master/_data/redirects.csv ?
