### ISSUE TITLE
Curious why community edition isn't supported on some versions

### ISSUE THREAD

**Issue by znmeb** [docker/docker.github.io#2551]
File: [engine/installation/index.md](https://docs.docker.com/engine/installation/), CC @mstanleyjones 

I'm curious why Docker Community Edition isn't supported on Oracle Linux or openSUSE. Oracle Linux is very similar to RHEL / CentOS, and openSUSE isbased on Suse Linux Enterprise.

**Comment by johndmulhausen** [comment]
Closing as this is not a docs issue; I've pinged others around here to see if they'd like to add a comment though. :)

**Comment by friism** [comment]
@znmeb free Docker Community Edition is available for infrastructure and operating systems that are themselves free and community-driven, for example Debian, Fedora and Ubuntu. For commercial operating systems like RHEL, SLES and Oracle Linux, commercial Docker Enterprise Edition is available.

**Comment by elegos** [comment]
@friism OpenSuSE is not commercial, differently from SLES. I see there is Docker 1.13 in the Tumbleweed's repositories, but no trace of 1.17 in any of the OpenSuSE repos.

**Comment by friism** [comment]
@elegos Docker is not currently building packages for OpenSuSE. The old packages you're seeing are not built or maintained by Docker Inc.

Would you like to use Docker on OpenSuSE?

**Comment by elegos** [comment]
@friism: yep, that's the distro I've been used lately... I could install docker from sources too, but an rpm would be very welcome!

**Comment by znmeb** [comment]
@elegos Is Docker in the openSUSE Build Service? I've got an account there - I ran openSUSE for years before switching to Fedora (and now Ubuntu - tired of third parties only supporting CentOS / RHEL and Ubuntu) ;-) If Docker's in OBS it may just need some build failure cleanup.

**Comment by znmeb** [comment]
Yep - it's there and it looks like the last source update was 2 months ago. https://build.opensuse.org/package/show/Virtualization:containers/docker. Anyone with an account can fork / branch the repo - not sure what the protocol is for contributing though.

**Comment by friism** [comment]
@znmeb @elegos We appreciate your interest in Docker packages for opensuse and have made a note of your request. The documentation in this repo concerns packages built and maintained by Docker Inc., so I humbly ask that you continue your discussion about other packages to the relevant opensuse forums.

**Comment by sankaushik** [comment]
I have always used openSUSE, I was happy to have previous versions of Docker available on it. With the latest version, it has disappeared from Docker website and the update on OS repo might be slower. I request that Docker continues support for openSUSE in current and future versions.
