### ISSUE TITLE
Docker Machine AWS EC2 example, clarify that you have to open port 8000 on AWS

### ISSUE THREAD

**Issue by MikeMitterer** [docker/docker.github.io#2555]
File: [machine/examples/aws.md](https://docs.docker.com/machine/examples/aws/), CC @londoncalling

![capturfiles-20170330_011734](https://cloud.githubusercontent.com/assets/116654/24501785/4a1087a2-154b-11e7-8775-ae533d9e379c.png)

**Comment by londoncalling** [comment]
Hi @MikeMitterer , when I walked through this example, I never explicitly opened a port on AWS.

@nathanleclaire @shin- @dnephin can you verify this is necessary?

**Comment by nathanleclaire** [comment]
It seems @MikeMitterer must need this to access his app, which presumably is listening on port 8000?

Generally I'd consider it in the realm of general AWS knowledge -- but it might be good to make a generic mention about opening ports in security groups to access anything `--publish`-ed.

**Comment by joaofnfernandes** [comment]
This is not really obvious. Usually AWS machines only have port 22 accessible from the outside.
If I'm new to Docker and deployed a sample app like wordpress or nginx, I'm expecting to be able to reach my app. If you don't know that you need to tweak the security group for the AWS instance, this can be hard to troubleshoot, and you might think there's something wrong with the way you deployed the app.

**Comment by nathanleclaire** [comment]
Ah, so, I did not realize that this was in reference to an article where we explicitly say to run a container and access it: https://docs.docker.com/machine/examples/aws/#step-3-run-docker-commands-on-the-instance

Since it is a walkthrough (I thought it was about the generic AWS reference), I'd say this is very valid feedback and should be added

**Comment by nathanleclaire** [comment]
@MikeMitterer This would make a good docs PR if you wanted to contribute ;)

**Comment by londoncalling** [comment]
@nathanleclaire thanks! @MikeMitterer I can either add this, or you can create a docs PR. If I don't hear from you in a day or two, I'll make the update.

**Comment by jpooler** [comment]
If it's still available, I'll take this up for the hackathon!

**Comment by londoncalling** [comment]
@jpooler great! Please have at it!

**Comment by mstanleyjones** [comment]
No action for two days, so this is up for grabs!

**Comment by jpooler** [comment]
Added to PR: https://github.com/docker/docker.github.io/pull/2913
