### ISSUE TITLE
kernel requirements for RHEL/CentOS

### ISSUE THREAD

**Issue by cyberw** [docker/docker.github.io#2558]
File: [engine/userguide/storagedriver/overlayfs-driver.md](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/), CC @mstanleyjones

I think it is worth mentioning that modern RHEL/CentOS kernels support overlay2, but you need to override the kernel check (https://github.com/docker/docker/issues/24023). Took me about a day to figure that out :)

**Comment by mstanleyjones** [comment]
Docker does not support overlayfs on RHEL / CentOS, and we cannot document unsupported configurations. These distributions are supported on device-mapper: https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-docker-with-devicemapper
