### ISSUE TITLE
memory and swap accounting steps are for ubuntu only

### ISSUE THREAD

**Issue by pvnovarese** [docker/docker.github.io#2562]
#File: [engine/installation/linux/linux-postinstall.md](https://docs.docker.com/engine/installation/linux/linux-postinstall/), CC @mstanleyjones 

Log into Ubuntu as a user with sudo privileges.
Edit the /etc/default/grub file.
Add or edit the GRUB_CMDLINE_LINUX line to add the following two key-value pairs:
GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
Save and close the file.
Update GRUB.
$ sudo update-grub
If your GRUB configuration file has incorrect syntax, an error will occur. In this case, repeat steps 3 and 4.
Reboot your system. Memory and swap accounting are enabled and the warning does not occur.

There's no explanation of the equivelent steps for RHEL-based systems.

**Comment by mstanleyjones** [comment]
I am not even 100% sure we should have those instructions for Ubuntu! Maybe we should just tell them they might have to do it, and to refer to their OS docs for how. WDYT @thaJeztah ?

**Comment by thaJeztah** [comment]
Hm, tough one; in a way, I agree with referring to their distros docs, but it can save a lot of time having the information ready. The times i've seen this configuration needed was all on Ubuntu/Debian.

@pvnovarese Is this configuration change needed on a default RHEL install?

**Comment by mstanleyjones** [comment]
This doesn't apply to RHEL because RH changed the kernel in 3.10.7 to enable these features by default.

**Comment by mstanleyjones** [comment]
Closed via #4070

**Comment by karniemi** [comment]
> karniemi unassigned mistyhacks 20 hours ago

I did what?
