### ISSUE TITLE
The "Dock Hub" glossary is not showing line break

### ISSUE THREAD

**Issue by jeffrey008** [docker/docker.github.io#2575]
File: [glossary.md](https://docs.docker.com/glossary/), CC @johndmulhausen 

What I see is: 
`Docker image hosting User authentication Automated image builds and work-flow tools such as build triggers and web hooks Integration with GitHub and Bitbucket`

What I expect from `glossary.yml`:
```
Docker image hosting 
User authentication 
Automated image builds and work-flow tools such as build triggers and web hooks 
Integration with GitHub and Bitbucket
```

**Comment by scjane** [comment]
#dibs
