### ISSUE TITLE
Improve requirements for HRM network

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2580]
https://docs.docker.com/datacenter/ucp/2.1/guides/user/services/use-domain-names-to-access-services/#under-the-hood

Explains that to use the HTTP routing mesh you can either use the default `ucp-hrm` network or create one. But we should show an example command on how to create that network, since that makes it more explicit.

We also need to make it explicit if you can create these networks at any time or you need to create them before enabling the HRM service, or you disable/enable the HRM service.

**Comment by Rubab-Syed** [comment]
I'll take this!

**Comment by prashant171992** [comment]
I'm looking into this.
