### ISSUE TITLE
UCP command reference doesn't contain examples

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#2585]
The following command should be the correct command to run when generating a support dump from command line: 

```
'docker run --rm --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:2.1.2 support > docker-support.tgz
```

File: [datacenter/ucp/2.1/reference/cli/support.md](https://docs.docker.com/datacenter/ucp/2.1/reference/cli/support/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
The support command is currently documented here https://docs.docker.com/datacenter/ucp/2.1/guides/get-support/#from-the-ui,

But it seems you uncovered something bigger. Currently the reference documentation doesn't contain examples on how to run the command. I'm updating the issue's title to reflect this.
