### ISSUE TITLE
clicking on a link in the API docs doesn't work properly

### ISSUE THREAD

**Issue by vieux** [docker/docker.github.io#2587]
![link](https://cloud.githubusercontent.com/assets/1032519/24572276/202d1eb4-162c-11e7-95ae-dcb5e04f9bd6.gif)

See the url of the page.

**Comment by johndmulhausen** [comment]
@vieux Hmm, I can't repro this in my browser.

**Comment by bdwill** [comment]
Appears to only do this on sub-items. Ex, List services is a sub-item of Services.

Services link is https://docs.docker.com/engine/api/v1.26/#tag/Service
List services link is https://docs.docker.com/engine/api/v1.26/#tag/Service

Clicking on a link to https://docs.docker.com/engine/api/v1.26/# displays the behavior as seen above.

Perhaps sub-items need to be tagged in Swagger?

**Comment by gschaetz** [comment]
I took at look at this and it appears to already be resolved

**Comment by mstanleyjones** [comment]
Thanks @gschaetz
