### ISSUE TITLE
Give example of VOLUME command for Dockerfile

### ISSUE THREAD

**Issue by lythix** [docker/docker.github.io#2589]
The command line method of creating a volume to "Mount a host directory as a data volume"
is (for example) 

```
docker run -p 1433:1433 -e SA_PASSWORD=blah e ACCEPT_EULA=Y -v H:/Data:/var/opt/mssql -d microsoft/mssql-server-linux
```
What would the equivalent Dockerfile syntax be? Give an example under the VOLUME section

File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @mstanleyjones

**Comment by jpooler** [comment]
#dibs for the hackathon

**Comment by bhavin192** [comment]
Read the note here https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume

You cant mount **host directory** from `Dockerfile` as the image we are going to build should be host dir independent.

**Comment by mstanleyjones** [comment]
No action for two days, so this is up for grabs again!

**Comment by bhavin192** [comment]
@mstanleyjones please consider my comment. It is not possible to do same with Dockerfile as we do while running a container. 

> 
> Read the note here https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume
> 
> You cant mount host directory from Dockerfile as the image we are going to build should be host dir independent.

Should it be clarified here again? Just copying Note from [here](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume) will be fine?

**Comment by tippexs** [comment]
claimed

**Comment by mstanleyjones** [comment]
@bhavin192 were you intending to claim this? If so, you were first. If not, please let @tippexs know they can have it.

**Comment by bhavin192** [comment]
@mstanleyjones yes, I want to claim it.

**Comment by bhavin192** [comment]
These files cannot be edited here so I created PR https://github.com/moby/moby/pull/32735

**Comment by mstanleyjones** [comment]
Being reviewed upstream. :)

**Comment by mstanleyjones** [comment]
Merged upstream. Thanks @bhavin192 !

**Comment by mstanleyjones** [comment]
Closed via https://github.com/moby/moby/pull/32735
