### ISSUE TITLE
docker network gateway and dhcp aren't mentioned early enough

### ISSUE THREAD

**Issue by gdennie** [docker/docker.github.io#2595]
File: [engine/userguide/networking/index.md](https://docs.docker.com/engine/userguide/networking/), CC @mstanleyjones 

The network notion discussions would seem to benefit from a mention of it's gateway and dhcp support as an organizing model for the discussion.

**Comment by thaJeztah** [comment]
Bear with me, I'm not the networking expert 😅, but could you explain a bit more in detail what kind of changes you'd like to see (what's missing, or what wasn't clear from reading the docs)?

The docker networks have a default "IPAM" driver; alternative drivers are possible, but the default doesn't use DHCP (for the containers).

Happy to help, but it would be welcome if you could add a bit more information 👍

**Comment by gdennie** [comment]
Simply put, the discussion appeared to lack a guiding principal. However, I am thinking that establishing such a thing may be premature.

In any event, a network may be considered something like a room that connected members inhabit and can talk to each other. Each is given a name/label by a tool call the DHCP. Also a designated member hangs by a window to allow occupants to talk to outsiders by relaying messages into the room or to specific members and vise versa.

**Comment by thaJeztah** [comment]
Ok, I think I see what you're thinking of; more describe the "concept" of networks (why would I use a custom networks), as an introduction, more "story telling"

I'm not sure we should bring DHCP in here, though; `docker networking` works a bit different then a regular network. Usually, a device is connected to a network, and asks for an IP address; the DHCP server hands it that IP address. Docker networks have an IPAM (IP Address Management); this is pluggable, and _could_ use a DHCP, but by default it's just enumerating IP-addresses from the available pool.

When creating a docker network, a pool of IP-addresses is reserved, and a network "namespace" created (we can call that the "room", but that may get more complicated later). When a container is started, an IP-address is issued, a network "endpoint"  is created (envision a "networking cable" being connected to the network) and given to the container. Inside the container, a new network-interface is created when the endpoint is attached.

If a container is connected to _two_ networks, it gets handed two endpoints (two cables), and only containers being plugged in to the same network are able to chat with each other.

**Comment by gdennie** [comment]
Yes, I understood the behavior upon reflection but the description as it existed was not as clear as it could be. Thanks for your attention.
