### ISSUE TITLE
Survey requires a back button to correct prior rating

### ISSUE THREAD

**Issue by gdennie** [docker/docker.github.io#2596]
File: [engine/reference/commandline/cli.md](https://docs.docker.com/engine/reference/commandline/cli/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
Survey? What does that have to do with the file you referenced here? If you are talking about the documentation survey, perhaps @johndmulhausen can help.

**Comment by thaJeztah** [comment]
I think the survey is an external service we use, not sure if it's configurable

**Comment by johndmulhausen** [comment]
It's not configurable; the survey will be fulfilled and taken offline today so closing this as no-op.
