### ISSUE TITLE
can't find detailed documentation on "docker run -v"

### ISSUE THREAD

**Issue by gdennie** [docker/docker.github.io#2597]
File: [index.md](https://docs.docker.com/), CC @johndmulhausen 

Your documentation site is starting to become pretty flashy and useless.

**Comment by thaJeztah** [comment]
Could you keep your comments constructive; there's no need to use offensive language here

We welcome feedback, and contributions, but please keep it constructive.

I see you opened another issue regarding `docker run -v`; https://github.com/docker/docker.github.io/issues/2598, so I'll close this one.
