### ISSUE TITLE
"docker run -v" description needs improvement

### ISSUE THREAD

**Issue by gdennie** [docker/docker.github.io#2598]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/), CC @mstanleyjones

Mount volume (-v, –read-only)

The description for this command is problematic. If it is reflective of the rest of this reference section, then cleaning this fundamental section up should be a priority, I think.

Each command should include a pseudo type signature

**Comment by mstanleyjones** [comment]
What is a "pseudo type signature"?

**Comment by gdennie** [comment]
In the following, the **--volume** option in this description of the **run** command uses what I characterized as a **pseudo type signature** to clarify the requirements for the option. 

[https://github.com/docker/docker/blob/17.03.x/docs/reference/commandline/run.md](https://github.com/docker/docker/blob/17.03.x/docs/reference/commandline/run.md)

**Comment by mstanleyjones** [comment]
Fixed in #4018
