### ISSUE TITLE
Markdown not being rendered correctly

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#26]
These pages are not being correctly rendered:

* https://docker.github.io/engine/installation/linux/centos/
* https://docker.github.io/engine/installation/linux/fedora/
* https://docker.github.io/engine/getstarted/step_three/
* https://docker.github.io/engine/swarm/swarm-tutorial/create-swarm/
* https://docker.github.io/engine/swarm/swarm-tutorial/add-nodes/
* https://docker.github.io/engine/swarm/swarm-tutorial/deploy-service/
* https://docker.github.io/engine/swarm/swarm-tutorial/inspect-service/
* https://docker.github.io/engine/swarm/swarm-tutorial/scale-service/
* https://docker.github.io/engine/swarm/swarm-tutorial/delete-service/
* https://docker.github.io/engine/swarm/swarm-tutorial/rolling-update/
* https://docker.github.io/engine/swarm/swarm-tutorial/drain-node/
* https://docker.github.io/engine/swarm/services/
* https://docker.github.io/engine/security/certificates/
* https://docker.github.io/docker-for-windows/troubleshoot/
* https://docker.github.io/docker-for-windows/examples/
* https://docker.github.io/docker-for-mac/examples/
* https://docker.github.io/cs-engine/install/
* https://docker.github.io/cs-engine/upgrade/
* https://docker.github.io/cs-engine/release-notes/prior-release-notes/
* https://docker.github.io/ucp/installation/install-production/
* https://docker.github.io/ucp/installation/install-offline/
* https://docker.github.io/ucp/installation/upgrade/
* https://docker.github.io/ucp/installation/uninstall/
* https://docker.github.io/ucp/configuration/use-externally-signed-certs/
* https://docker.github.io/ucp/configuration/dtr-integration/
* https://docker.github.io/ucp/configuration/multi-host-networking/
* https://docker.github.io/ucp/monitor/troubleshoot-ucp/
* https://docker.github.io/docker-trusted-registry/install/
* https://docker.github.io/docker-trusted-registry/install/install-dtr-offline/
* https://docker.github.io/docker-trusted-registry/install/upgrade/upgrade-major/
* https://docker.github.io/docker-trusted-registry/install/upgrade/
* https://docker.github.io/docker-trusted-registry/configure/config-security/
* https://docker.github.io/docker-trusted-registry/repos-and-images/
* https://docker.github.io/docker-cloud/infrastructure/link-aws/
* https://docker.github.io/docker-cloud/infrastructure/cloud-on-aws-faq/
* https://docker.github.io/docker-cloud/installing-cli/
* https://docker.github.io/docker-store/
* https://docker.github.io/toolbox/toolbox_install_mac/
* https://docker.github.io/toolbox/toolbox_install_windows/
* https://docker.github.io/kitematic/userguide/
* https://docker.github.io/registry/configuration/
* https://docker.github.io/registry/spec/manifest-v2-2/
* https://docker.github.io/registry/storage-drivers/s3/
* https://docker.github.io/notary/getting_started/
* https://docker.github.io/notary/reference/server-config/
* https://docker.github.io/notary/changelog/

**Comment by johndmulhausen** [comment]
Fixes, part 1: a0ee6c600473c9cd2036480535595f08845981ca

**Comment by johndmulhausen** [comment]
Fixes, part 2: 327c0c641f3d5fa8d1e7d8e646d934e912a3533f
