### ISSUE TITLE
Notes on roadmap for cloud distributions and being explicit about docker4x

### ISSUE THREAD

**Issue by cirocosta** [docker/docker.github.io#2604]
### Problem description

Docker doesn't explicitly states governance/roadmap/what-to-expect for `docker4x`-based images. It seemed a bit bad that the community didn't have the access to docker-for-mac sources and could really dig into it but it's ok because it's generally just a developer tool. However, when it comes to cloud deployments, one might be more tempted to question about what to expect for those closed-source components, like those containers that run in a docker-for-{aws|azure} setup.

Not just criticizing here (I've been really enjoying it so far 😁 ), just requesting some more clarity on these issues. It's ok to have this difference between CE and Enterprise versions but i think it'd be great to have more openness in terms of that. 

### Problem location

-  https://docs.docker.com/docker-for-aws/opensource/  could detail that there are some closed-source components there
- https://docs.docker.com/docker-for-aws/ could have a new section maybe describing the roles of those components
- https://github.com/docker/docker/blob/master/ROADMAP.md could probably include something related to the cloud distributions

### Suggestions for a fix
 (above)

---

Sorry if i missed something or unintendedly duplicated an issue. Please let me know!
Thanks for your great product 👍  👍

**Comment by joaofnfernandes** [comment]
Would a diagram [like this ](https://docs.docker.com/images/ddc_aws.svg) be enough to help you understand what is being deployed with a cloud template?

**Comment by cirocosta** [comment]
hey @joaofnfernandes , not really, for the overview of the services used there's already the CloudFormation template. I'd just want to have some more insights into the roadmap and know more about the magic under the hood of the docker4x containers .. or eventually at least know if someday they plan to opensource it, for instance .. this kinds of things

**Comment by joaofnfernandes** [comment]
Maybe @friism can answer here, but this seems out of scope for the docs.

**Comment by cirocosta** [comment]
@joaofnfernandes got it 😁  
about `docker4x`, is it possible to at least at some high-level document what goes on in those containers? i suppose it's different based on the platform (azure, aws ...).

@joaofnfernandes , btw, the docs overall is getting preeetty good, great work from the team that's putting effort on that!

**Comment by friism** [comment]
I agree it would be good to document - I put it on my backlog. Also cc'ing @FrenchBen in case he has time.

**Comment by londoncalling** [comment]
Issue moved to [docker/for-aws #95](https://github.com/docker/for-aws/issues/95) via [**ZenHub**](https://www.zenhub.com/)
