### ISSUE TITLE
About Docker EE page should crib from blog post

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#2606]
This: 
https://blog.docker.com/2017/03/docker-enterprise-edition/

Has a lot more detail than this: 
https://docs.docker.com/enterprise/

cc @mstanleyjones @JimGalasyn @joaofnfernandes

**Comment by joaofnfernandes** [comment]
My PR #2581 tries to add some of that information to the [Get Docker](https://docs.docker.com/engine/installation/#time-based-release-schedule) page, but maybe the right place to put that info is on the /enterprise page?
