### ISSUE TITLE
error or other example?

### ISSUE THREAD

**Issue by jjmonsalveg** [docker/docker.github.io#2607]
File: [engine/getstarted/step_four.md](https://docs.docker.com/engine/getstarted/step_four/), CC @mstanleyjones 
Hello!, in Step 2 and 4 seem to be the result of the same run but the 3 seems to be another run.

Step 2: Successfully built c2c3152907b5
Step 3: Successfully built success 7d9495d03763

Step 4 (docker images):
Docker-whale latest c2c3152907b5 4 minutes ago 275.1 MB

It is not clear whether step 3 is a sequence of 2 or it is a separate example

**Comment by jpooler** [comment]
#dibs for the hackathon

**Comment by johndmulhausen** [comment]
This topic no longer exists. @jpooler still gets the points for #2832.
