### ISSUE TITLE
404 at /en/latest/use/ambassador_pattern_linking/

### ISSUE THREAD

**Issue by Goldgod** [docker/docker.github.io#2608]
URL: /en/latest/use/ambassador_pattern_linking/

**Comment by mstanleyjones** [comment]
I can't find any link like that in the Docker docs. The closest I can find is: https://docs.docker.com/engine/admin/ambassador_pattern_linking/

Please post the page where you saw the link that failed for you.

**Comment by mstanleyjones** [comment]
Closing due to lack of info.
