### ISSUE TITLE
The right-hand side is cut off unless the screen is very wide

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#2619]
File: [engine/installation/linux/linux-postinstall.md](https://docs.docker.com/engine/installation/linux/linux-postinstall/)

Even with a browser width of 1305px, my screen looks like the attached. Surely this is not right.

<img width="1303" alt="screen shot 2017-04-04 at 2 03 01 pm" src="https://cloud.githubusercontent.com/assets/7674613/24678499/93db6076-193f-11e7-9d07-a97916f66749.png">

**Comment by mcd-php** [comment]
+1. Even worse, no horizontal scroll bar at the bottom. Had to go to dev mode in browser and delete node '.col-nav' to make room.

**Comment by jsouth** [comment]
Tightening up the fix for this today!

**Comment by allejo** [comment]
Should this one be closed? Think it's already been fixed in #2804

**Comment by mcd-php** [comment]
Yes, fixed for me (1280 - Ubuntu sidebar) on production site.

**Comment by mstanleyjones** [comment]
@allejo thanks!
