### ISSUE TITLE
Open source contributor's guide: update or pare down

### ISSUE THREAD

**Issue by londoncalling** [docker/docker.github.io#2625]
### Problem description

- Open source contributor's guide in docs is out-of-date. We should bring these docs up to date or remove them.

### Problem location

https://docs.docker.com/opensource/
https://docs.docker.com/opensource/code/

### Related issues

Issue https://github.com/docker/docker.github.io/issues/205
Issue https://github.com/docker/docker.github.io/issues/218
Issue [moby/moby#35115](https://github.com/moby/moby/issues/35115) and [PR moby/moby#35168](https://github.com/moby/moby/pull/35168)

### FYI, collaborators

@mstanleyjones @johndmulhausen

**Comment by justincormack** [comment]
Hi, I am working on the Moby Project transition - see https://github.com/moby/moby/issues/35115 - and cleaning up our docs and in particular clearing up the relation between Docker and Moby.

My view is that we should remove all of this section except a short link and explanation of the Moby Project, and we should move the relevant pieces into the moby/moby repo, ie the details of how to work with the repo.

**Comment by justincormack** [comment]
I am half way through updating the contributing guide, see https://github.com/moby/moby/pull/35168 which needs to clear this up....
