### ISSUE TITLE
Cleanup Items Round Dos

### ISSUE THREAD

**Issue by jsouth** [docker/docker.github.io#2627]
### Round Dos
original task list for launch: https://github.com/docker/docker.github.io/issues/2052

- [x] Mobile type fixes for small devices (currently "samples" link busts at the seams and floats to secondary line on iphone 4 and other very small viewports)
- [x] Window Rescale leakage between 400-800px
- [x] No longer any difference between notes, warnings, info admonitions (all blockquotes are blue)(Carried over from original fix list)
- [x] Keyboard highlighting in search autocomplete: Functional,  but needs refined: Padding issues
- [x] Create custom class for inline images (display prop)
- [x] Safari overflow issues (full sweep of safari)

**Comment by joaofnfernandes** [comment]
Some pages are overflowing the viewport. Check #2730
