### ISSUE TITLE
Publish ports on "localhost:8080" 

### ISSUE THREAD

**Issue by markvr** [docker/docker.github.io#2630]
File: [engine/swarm/services.md](https://docs.docker.com/engine/swarm/services/), CC @mstanleyjones

I've been trying the "routing mesh", and under "Publish Ports" the docs say you can try `curl localhost:8080`.  

On my system at least, this just hangs, and I need to curl the network IP address.  I can't find much by googling if the routing mesh should work with localhost or not.  If this is something wrong with my system then apologies!

Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: csoxe3y8e8ym8hrils4obqs2q
 Is Manager: true
 ClusterID: piv6ehy5tfv3pn9zjw8mitf6m
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.28.128.29
 Manager Addresses:
  172.28.128.29:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.7 MiB
Name: localhost.localdomain
ID: 7OJC:2HAR:AUFL:S2ZH:QFTU:OVMK:T37X:TPSH:Q2IA:UIKK:IH6J:DRKX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by joaofnfernandes** [comment]
If you're running Docker locally you should be able to access the service just with `curl localhost:8080`, but if the machine that's running Docker is a VM or any other external machine, then you'll have to use the IP address for that machine.
