### ISSUE TITLE
Formatting messed up with button on Docker for AWS release page

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker.github.io#2634]
File: [docker-for-aws/release-notes.md](https://docs.docker.com/docker-for-aws/release-notes/), CC @johndmulhausen 
![screen shot 2017-04-05 at 9 17 29 am](https://cloud.githubusercontent.com/assets/113855/24715578/c074656e-19e0-11e7-8a26-40ec41de98d1.png)

**Comment by scjane** [comment]
#dibs

**Comment by johndmulhausen** [comment]
@scjane Careful about claiming bugs and not submitting PRs! @stevenhanna6 got in there. Only claim bugs when you are actively working on them -- as close to one-at-a-time as you can. It jams up the works, otherwise. 

@stevenhanna6 gets the points here.
