### ISSUE TITLE
Link to new page

### ISSUE THREAD

**Issue by Syntaxide** [docker/docker.github.io#2641]
File: [engine/admin/registry_mirror.md](https://docs.docker.com/engine/admin/registry_mirror/), CC @mstanleyjones

The page at https://docs.docker.com/registry/recipes/mirror/ has up to date instructions. Either linking to this page, or making engine/admin/registry_mirror redirect to registry/recipes/mirror seems like a good idea.

**Comment by jennylia** [comment]
Dibs for hackathon
