### ISSUE TITLE
docker system prune does not support use of the "--filter" option

### ISSUE THREAD

**Issue by briantd** [docker/docker.github.io#2642]
File: [engine/reference/commandline/system_prune.md](https://docs.docker.com/engine/reference/commandline/system_prune/), CC @mstanleyjones 

It doesn't appear that the filter command provided in the example is actually accepted:
https://docs.docker.com/engine/reference/commandline/system_prune/#examples
```
~ $ docker system prune --filter "until=1h"
unknown flag: --filter
See 'docker system prune --help'.
~ $ docker system prune --help

Usage:	docker system prune [OPTIONS]

Remove unused data

Options:
  -a, --all     Remove all unused images not just dangling ones
  -f, --force   Do not prompt for confirmation
      --help    Print usage
```

**Comment by mstanleyjones** [comment]
What version of Docker do you have? I do not believe `--filter` was valid for this command until 17.03. @thaJeztah can confirm.

**Comment by thaJeztah** [comment]
Yes, looking, looks like a bad cherry-pick; the CLI fixups were against master, and the cherry-pick applied "cleanly", but pulled these changes in

**Comment by thaJeztah** [comment]
I suspect GitHub "randomly hiding diffs" made the changes in these files invisible https://github.com/docker/docker/pull/31242 😞

**Comment by briantd** [comment]
@mstanleyjones 
~ $ docker version
Client:
 Version:      17.03.0-ee-1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Fri Feb 24 19:01:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ee-1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Fri Feb 24 19:01:49 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by mstanleyjones** [comment]
We found the problem: https://github.com/docker/docker/pull/32390

This should be fixed soon!

**Comment by briantd** [comment]
Great -- that filter will be very useful!

**Comment by johndmulhausen** [comment]
Looks like it's in there now. Thanks all! :)
