### ISSUE TITLE
Mac OSX daemon.json Location

### ISSUE THREAD

**Issue by revof11** [docker/docker.github.io#2643]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/), CC @mstanleyjones 

Missing the documentation for where `daemon.json` is on Mac OSX.

Default file location for a user appears to be:
`~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/etc/docker/daemon.json`

Currently all the file has in it is the following JSON:
```json
{
  "debug": true,
  "experimental": true
}
```

I was hoping to find the full set of options as I was working with [this article on using Nexus 3 as a Docker Repository](http://www.sonatype.org/nexus/2017/02/16/using-nexus-3-as-your-repository-part-3-docker-images/).  I left a comment on on that blog as well for reference.

**Comment by mstanleyjones** [comment]
You shouldn't edit it directly. You should go to the whale in the taskbar > Preferences > Daemon > Advanced.

**Comment by revof11** [comment]
That's fine if you have access to the UI and not just the shell.  The machine I was working to test things I only have SSH access to in order to validate the functionality.  Everything worked just fine when I edited it by hand.

**Comment by shubheksha** [comment]
This file doesn't seem to be editable in this repo and needs to be fixed in the main repo?
https://github.com/docker/docker.github.io/blob/master/engine/reference/commandline/dockerd.md

**Comment by mstanleyjones** [comment]
Yep but you can submit the PR there and still get credit!

**Comment by domg123** [comment]
#dibs

**Comment by jmaitrehenry** [comment]
PR open on moby project: https://github.com/moby/moby/pull/32722

**Comment by mstanleyjones** [comment]
Getting tech review on the upstream PR now.

**Comment by mstanleyjones** [comment]
@jmaitrehenry thanks for your work. You'll get the points even though we had to close the upstream PR!

**Comment by zhaozhx** [comment]
cat ~/.docker/daemon.json

**Comment by dmitryrn** [comment]
In my case it is in `/Users/user/Library/Group Containers/group.com.docker/last-start-linux-daemon.json`. But as mentioned above you can go to Docker app Preferences -> Advanced.

**Comment by zhaozhx** [comment]
> in the case of a brew installation, where is it?

hi，I am use docker-machine.
<img width="527" alt="image" src="https://user-images.githubusercontent.com/3453004/67060500-a9a08f00-f18f-11e9-9553-d0e48a52c586.png">

you can start your docker-machine,and ssh in it.
such as:
$ docker-machine start dev
$ docker-machine ssh dev

docker@dev:~$ cat /var/lib/boot2docker/profile

now,i am edit this file.

**Comment by rufreakde** [comment]
small update:
Docker Whale Icon -> Preferences -> Docker Engine -> Edit file -> Apply and Restart

To print content do as zhaozhx mentioned:
> cat ~/.docker/daemon.json
