### ISSUE TITLE
404 at /engine/installation/linux/SUSE/

### ISSUE THREAD

**Issue by gmsantos** [docker/docker.github.io#2645]
URL: /engine/installation/linux/SUSE/

Is OpenSUSE not supported anymore in the recent versions of Docker?

I'm thinking to switch from Ubuntu to OpenSUSE, but without docker I will stay on ubuntu.

**Comment by johndmulhausen** [comment]
@gmsantos https://docs.docker.com/engine/installation/linux/suse/ seems to be working for me. :)

**Comment by gmsantos** [comment]
@johndmulhausen the docs for current version is quite different from the 1.13

https://docs.docker.com/v1.13/engine/installation/linux/suse/

It says that OpenSUSE is also supported. Also, there is no instructions to install CE edition.

I could submit a PR if you think the above points are relevant.

**Comment by johndmulhausen** [comment]
The current list of supported distros, as far as CE/EE, is here: https://docs.docker.com/engine/installation/#platform-support-matrix

Yes, some things have changed. Thanks for the offer of a PR, but I'm afraid the docs are correct.
