### ISSUE TITLE
remote API 1.27: incomplete documentation for network prune

### ISSUE THREAD

**Issue by gdevillele** [docker/docker.github.io#2648]
### Problem description

In the `network prune` section of the 1.27 remote API reference:
"Available filters:" is not followed by a list of filters.

### Problem location

https://docs.docker.com/engine/api/v1.27/#operation/NetworkPrune

<img width="645" alt="screen shot 2017-04-05 at 10 57 54 pm" src="https://cloud.githubusercontent.com/assets/939999/24739923/4f7e0432-1a53-11e7-80da-0c8c28e77160.png">

Thanks.

**Comment by mstanleyjones** [comment]
We don't update old versions of the API for compatibility reasons.
