### ISSUE TITLE
Dead link on page

### ISSUE THREAD

**Issue by akopytov** [docker/docker.github.io#2655]
File: [docker-for-mac/docker-toolbox.md](https://docs.docker.com/docker-for-mac/docker-toolbox/), CC @londoncalling 

[How to uninstall Toolbox](https://docs.docker.com/toolbox/toolbox_install_mac.md#how-to-uninstall-toolbox) links to a non-existing page.

**Comment by londoncalling** [comment]
@akopytov I'm not sure what you are seeing, but I checked the link and it's working properly both on the website docs at: https://docs.docker.com/docker-for-mac/docker-toolbox/#how-do-i-uninstall-docker-toolbox (the link goes to https://docs.docker.com/toolbox/toolbox_install_mac/#how-to-uninstall-toolbox) and from the GitHub page: https://github.com/londoncalling/docker.github.io/blob/master/docker-for-mac/docker-toolbox.md

**Comment by akopytov** [comment]
It seems to be reproducible only with NoScript. When I disable it, [this link](https://docs.docker.com/toolbox/toolbox_install_mac.md#how-to-uninstall-toolbox) loads successfully. When I enable it back, I get  a 404 page ("Sorry, we can't find that page") after clicking that link.

**Comment by londoncalling** [comment]
Ok thanks, that's weird. I'll have another look today.

**Comment by mstanleyjones** [comment]
The reason why is because it is an `<a>` link to a `.md` file. Either change it to a Markdown link or change the href to what the real link will end up being, without the `.md` extension.

**Comment by mstanleyjones** [comment]
The root cause may not be in our Markdown at all. There is some Javascript that turns `.md` links into the real places.  cc/ @johndmulhausen who knows more about this. I can't actually find a problematic link.

**Comment by londoncalling** [comment]
@mstanleyjones @akopytov Just to clarify, the link in question is formatted as markdown (not an `<a href>`):

```
For details on how to perform a clean uninstall of
Toolbox on the Mac, see [How to uninstall
Toolbox](/toolbox/toolbox_install_mac.md#how-to-uninstall-toolbox) in the
Toolbox Mac topics.
```
And does require a Javascript enabled browser to resolve properly. 

@akopytov we format these links as markdown so that they will work across GitHub files. The links require Javascript when they are served up on web pages to render as HTML.

**Comment by akopytov** [comment]
@londoncalling thanks for clarifications. Whitelisting docs.docker.com for NoScript is a feasible workaround for me.
