### ISSUE TITLE
task 1 can be accomplished with docker system prune

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker.github.io#2659]
File: [opensource/project/set-up-dev-env.md](https://docs.docker.com/opensource/project/set-up-dev-env/), CC @johndmulhausen

**Comment by jpooler** [comment]
#dibs for the hackathon

**Comment by mstanleyjones** [comment]
No action for two days, so this is up for grabs again!

**Comment by jpooler** [comment]
Referenced here: https://github.com/docker/docker.github.io/pull/2918
