### ISSUE TITLE
build number is wrong

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker.github.io#2660]
Is there a way to autopopulate the build number?
these 2 lines are out of date:
```
root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.12.0-dev/binary-client/docker* /usr/bin/
root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.12.0-dev/binary-daemon/docker* /usr/bin/ 
```

File: [opensource/project/set-up-dev-env.md](https://docs.docker.com/opensource/project/set-up-dev-env/), CC @johndmulhausen

**Comment by johndmulhausen** [comment]
We could have a _config.yml variable that had the build number in it and use it here.

**Comment by ManoMarks** [comment]
That would work

**Comment by johndmulhausen** [comment]
Closing as dupe of #2501
