### ISSUE TITLE
Mangled Markup

### ISSUE THREAD

**Issue by jcbelanger** [docker/docker.github.io#2665]
ThFile: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/), CC @londoncalling

The generated html on the docker website does not match github's.  [Screenshot](http://imgur.com/a/eT4Cl)

**Comment by johndmulhausen** [comment]
No repro at the moment. Thanks for letting us know though!

**Comment by londoncalling** [comment]
@jcbelanger thanks!!! Yes, that happened last week, and I fixed it as fast as I could after I realized the problem. Appreciate the feedback!
