### ISSUE TITLE
Splunk Logging Docs: splunk-source

### ISSUE THREAD

**Issue by carlvanschie** [docker/docker.github.io#2675]
File: [engine/admin/logging/overview.md](https://docs.docker.com/engine/admin/logging/overview/), CC @mstanleyjones 

It looks like splunk-source documentation is a little off as it looks like the splunk-token tag.

**Comment by jpooler** [comment]
#dibs for the hackathon

**Comment by mstanleyjones** [comment]
Sorry @jpooler, this one is back up for grabs!

**Comment by jpooler** [comment]
Added to PR https://github.com/docker/docker.github.io/pull/2916

**Comment by johndmulhausen** [comment]
@jpooler and @constanzekratel both can split 25 points each.
