### ISSUE TITLE
auto redeploy page does not mention requirement for tags

### ISSUE THREAD

**Issue by tzapu** [docker/docker.github.io#2677]
File: [docker-cloud/apps/auto-redeploy.md](https://docs.docker.com/docker-cloud/apps/auto-redeploy/), CC @londoncalling 

This page should mention that auto redeploy only works for hub images with the *latest* tag
Cheers

**Comment by londoncalling** [comment]
@tzapu thanks for your feedback. I've added to the notes on `autodeploy` per the referenced PRs ^^ and this should be published within the hour. I'll close this issue, but feel free to re-open if needed, or a log a new one with other issues. Much appreciate the input.
