### ISSUE TITLE
`--exit-code-from SERVICE` is not available in the latest Docker for Mac. 

### ISSUE THREAD

**Issue by antkazam** [docker/docker.github.io#2686]
File: [compose/reference/up.md](https://docs.docker.com/compose/reference/up/), CC @londoncalling

I am trying to run `docker-compose up --exit-code-from <service>` but it is apparently not a valid CLI option.

I am using `Version 17.03.1-ce-mac5 (16048)`

**Comment by londoncalling** [comment]
@shin- @dnephin @nathanleclaire @ManoMarks Can you all have a look at this?

**Comment by shin-** [comment]
You need Compose 1.12.0 which is bundled with 17.04.0-ce. Try updating
Docker for Mac.

**Comment by ajcann** [comment]
This does not seem to be available in the stable release which is at 17.03, but rather in the latest Docker for Mac Edge release (17.05)
