### ISSUE TITLE
keywords in upstream files are incorrectly formatted

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#2687]
https://docs.docker.com/metadata.txt

Do a CMD+F search for `"keywords":["`

Any results you see here show that the keywords in these files are coming in as arrays. This shouldn't happen. 

Bad front-matter: 

```
---
keywords:
- foo, blar, snarf, barge
---
```

Good front-matter:

```
---
keywords: grog, bling, glorp, flan
---
```

**Comment by johndmulhausen** [comment]
Fixed in #96b09c1

**Comment by johndmulhausen** [comment]
Actually; my workaround is good for the site but it would be nice if the real

**Comment by mstanleyjones** [comment]
Closing here since the work will happen in the `docker/distribution` repo.
