### ISSUE TITLE
Feedback for: compose/gettingstarted.md

### ISSUE THREAD

**Issue by itudoben** [docker/docker.github.io#269]
URL: [https://docs.docker.com/compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

Hi,
great article. 
Once the image is built using 'docker build -t web .' it does not say where the image is stored. I'm sure it says somewhere else other than this page, but something saying 'by default the image can be found here. For reference on image stored look at ... bla bla bla'.
Thank you.

**Comment by londoncalling** [comment]
@shin- @dnephin @ManoMarks 

Hi guys, this question has been sitting her for some time, sorry. Can any one of you all answer this for @itudoben ?

**Comment by dnephin** [comment]
The image is stored by a graph driver in the docker data directory. It's not meant to be accessed directly. You can list images with `docker image ls` and inspect it with `docker inspect <tag or id>`.

**Comment by londoncalling** [comment]
@dnephin thanks, that's right! :-) I'll add something into this article as a reminder to clarify it.

**Comment by londoncalling** [comment]
@itudoben closing this issue, as it's addressed now per PR #1600 , just merged. I added a tip and also updated an advisory on Swarm mode to point to the new Getting Started tutorial, which showcases Compose v3 and Swarm mode. Thanks for the feedback, please contact us again if you have more comments.
