### ISSUE TITLE
Incorrect link to Docker Toolbox

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker.github.io#2690]
Link to `Docker Toolbox` at https://www.docker.com/docker-mac refers to https://docs.docker.com/compose/reference/overview/.

This should instead be to https://www.docker.com/products/docker-toolbox.

**Comment by londoncalling** [comment]
@arun-gupta thanks! This is fixed now: https://www.docker.com/docker-mac

cc: @jsouth
