### ISSUE TITLE
Searchability is problematic

### ISSUE THREAD

**Issue by gdennie** [docker/docker.github.io#2691]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @mstanleyjones 

The site's resident search is limited. Recently tried searching for the term, entrypoint, and was disappointed at the weirdness. Perhaps your site needs a search-able glossary to hold all its concepts in one place.

**Comment by mstanleyjones** [comment]
The very first search result I get from https://docs.docker.com/search/?q=entrypoint is https://www.google.com/url?q=https://docs.docker.com/engine/reference/builder/, which seems to be the right one. The second and third results, which are both on forums.docker.com, also seem to be high quality results. If you want to narrow it down to only docs.docker.com content, you can click the "Docs" tab in the search results.  The top four search results are IMO very high quality.

If you think we should have a definition for Entrypoint in the glossary, I can definitely see an argument for that.

**Comment by gdennie** [comment]
The search results brings up the article and not the definition or synopsis.

________________________________

**Comment by johndmulhausen** [comment]
@gdennie You'll be happy to know we're working on it: https://github.com/docker/docker.github.io/pull/1387/files#diff-8fd00abf6369bddcce9b428356326a1aR13
