### ISSUE TITLE
Top of page becomes white with certain screen sizes in portrait orientation

### ISSUE THREAD

**Issue by phipsgabler** [docker/docker.github.io#2692]
(This seems to be a global CSS problem.)

I happen to use 1024x1280 displays in portrait mode. There is a certain width range my screen falls in, in which the top of the page consists of a huge white area, and stuff seems to be missing (with Firefox' responsive design mode, this occurs between 990 px and 1024 px):

![empty](https://cloud.githubusercontent.com/assets/7878215/24837331/5ac194e4-1d32-11e7-8f94-768aac9d1fdd.png)

This is the case on every page:

![empty2](https://cloud.githubusercontent.com/assets/7878215/24837349/bc9d130a-1d32-11e7-983d-5e62ecae2731.png)

The effect goes away if I resize the window to become smaller vertically than horizontally (the following is 1004x1003):

![not_empty](https://cloud.githubusercontent.com/assets/7878215/24837391/59ae3a8e-1d33-11e7-84d0-23a6c4756cc2.png)

It seems like the menu, on the left in the wider layout, just expands to the whole width. I'm using Firefox 52 on Ubuntu 16.04.

**Comment by allejo** [comment]
Has this been fixed for you or does the issue still exist? Might have been fixed in #2860

**Comment by phipsgabler** [comment]
@allejo yup! Looks nice now, thanks.

**Comment by johndmulhausen** [comment]
Thanks all! Glad this got handled. :)
