### ISSUE TITLE
404 at /reference/api/docker_remote_api_v1.16/

### ISSUE THREAD

**Issue by you-think-you-are-special** [docker/docker.github.io#2693]
URL: /reference/api/docker_remote_api_v1.16/

**Comment by mstanleyjones** [comment]
You can get to this (very old) version of the API using this link: https://docs.docker.com/v1.10/engine/reference/api/docker_remote_api_v1.16/

Where did you see the broken link? Our current docs contain no references to it, nor do the archives for v1.13, v1.12, or v1.11, so I can't find where it is coming up as broken.

I'm going to close this for now, but feel free to re-open if the broken link is on a page hosted on docs.docker.com.
