### ISSUE TITLE
Typo in TOC

### ISSUE THREAD

**Issue by cjh84** [docker/docker.github.io#2704]
File: [reference.md](https://docs.docker.com/reference/), CC @johndmulhausen

https://github.com/docker/docker.github.io/blob/get-started/_data/toc.yaml#L667 should say docker plugin create.

**Comment by JimGalasyn** [comment]
Verified fixed at https://docs.docker.com/engine/reference/commandline/plugin/.

**Comment by cjh84** [comment]
Thanks Jim!
