### ISSUE TITLE
"Customize the docker0 bridge" does not specify where to change the command line arguments

### ISSUE THREAD

**Issue by JustDerb** [docker/docker.github.io#2707]
This doc tells me about the options to configure at startup, but fails to tell me **where** I should make these changes.

File: [engine/userguide/networking/default_network/custom-docker0.md](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
See #3252 which should help. The best place to configure these is in the `daemon.json` file. See also https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file.
