### ISSUE TITLE
Documentation: unclear how verification is happening

### ISSUE THREAD

**Issue by artsf** [docker/docker.github.io#2715]
There is a lack of documentation (section) which describes in details how signature verification is happening and where.

It, probably, should mention:

1. Metadata containing signature and public key of signing file;
2. Initial verification happening in Notary;
3. If verification in notary doesn't succeed then image is NOT loaded;
4. If initial verification succeeds then the image is loaded and verified against SHA. 

It is also unclear if there is a second-time verification of target machine to verify signature again in addition to SHA on the image.

Originally from here: https://github.com/docker/notary/issues/1132

**Comment by mstanleyjones** [comment]
@riyazdf @cyli can you point us to some source content?

**Comment by johndmulhausen** [comment]
Relates to #2716

**Comment by riyazdf** [comment]
Per-point resources and comments:

1. Best place for information like this is the [TUF spec](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.md), but I don't think we should include this level of detail in Docker docs. Perhaps Notary is more appropriate, but even then we do link to the TUF spec IIRC.

2. This could go really detailed into the intricacies of the TUF spec, but I think it'd be best to make it clearer in the [existing docs](https://docs.docker.com/engine/security/trust/content_trust/#pull-image-content) that the notary lookup comes first

3. It could be made clearer in the existing docs that the signed tag points to a unique digest https://docs.docker.com/engine/security/trust/content_trust (there's very light technical referencing, instead there's an illustration with `rose-colored glasses`)

4. I'm not sure if we have pull-by-digest docs, but we could use those as a basis. Signing adds an extra layer of verification over the initial manifest, and then we leverage the security of a pull-by-digest's hash tree for the image layers themselves
