### ISSUE TITLE
Documentation: it is unclear where image is signed originaly

### ISSUE THREAD

**Issue by artsf** [docker/docker.github.io#2716]
Neither the architecture doc, not TUF make it clear that image is signed on originating machine, NOT in notary server.

Moved from: https://github.com/docker/notary/issues/1131

**Comment by joaofnfernandes** [comment]
My understanding [from the spec](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt) is that there several keys at play when you sign an image:
* Root
* Targets
* Snapshot
* Timestamp

The root and target keys are always offline in your machine. The timestamp key is always managed by the Notary server.

The snapshot key depends. By default it's also offline, but you can configure the Notary server to manage this key for you.
Am I getting this right @endophage?

**Comment by artsf** [comment]
"offline" and "in your machine" sounds different to me :)

**Comment by endophage** [comment]
I've used "semi-online" to describe the targets key in presentations. The root key should truly be offline, stored on some kind of media in a safe, not on your machine.
