### ISSUE TITLE
"Volumes are initialized when a container is created." ?

### ISSUE THREAD

**Issue by gdennie** [docker/docker.github.io#2717]
File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/), CC @mstanleyjones 

I am presuming data volumes are not reinitialized if they already exist. Since this feature is tied into the `docker run [--rm] -v ..." command, its presence in the discussion there is essential.

**Comment by mstanleyjones** [comment]
Content was rewritten.
