### ISSUE TITLE
Add info about HTTPS_PROXY

### ISSUE THREAD

**Issue by Hugh----** [docker/docker.github.io#2724]
### Problem location

- I have got a question on the following URL: https://github.com/docker/docker.github.io/blob/master/engine/admin/systemd.md

- Description: In the above URL, it explained how to set HTTP_PROXY environment variable for Docker in systemd. How about HTTPS_PROXY? Will docker identify it if I set it after HTTP_PROXY?

**Comment by mstanleyjones** [comment]
Yes, it works just the same. This is not Docker-specific.

**Comment by ashishkamat2791** [comment]
added to @mstanleyjones  
Yes It works same as that of HTTP_PROXY and It is something to related to network and not Docker specific.
Eg: For accessing a network behind proxy we need to setup following enviornment variables and ensure they are set as to confirm we can access a network 

`MY_PROXY_URL="http://$MY_CREDENTIALS@10.21.2.217:8080/"
HTTP_PROXY=$MY_PROXY_URL
HTTPS_PROXY=$MY_PROXY_URL
FTP_PROXY=$MY_PROXY_URL
http_proxy=$MY_PROXY_URL
https_proxy=$MY_PROXY_URL
ftp_proxy=$MY_PROXY_URL
export HTTP_PROXY HTTPS_PROXY FTP_PROXY http_proxy https_proxy ftp_proxy
`

**Comment by shubheksha** [comment]
I'll take this up!
