### ISSUE TITLE
Some pages are wider than the viewport size

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2730]
Mac osx 13", Chrome 1280x620

In this case the right menu is half hidden

![screen shot 2017-04-11 at 10 20 02](https://cloud.githubusercontent.com/assets/1525937/24922074/dbe7e224-1ea1-11e7-8434-434e5c05c8c7.png)

In this case the right sidebar totally disappears
![screen shot 2017-04-11 at 10 34 41](https://cloud.githubusercontent.com/assets/1525937/24922264/9ac78dc0-1ea2-11e7-9ebd-c4c0188eb857.png)

I suspected that the size of the images were causing this, but the article in the second screenshot doesn't have images, so it's probably something to do with the size of the content div. 

```
section.section {
    max-width: 980px;
    margin: 0 auto;
}
```
That 980px for the content doesn't leave enough space for the right sidebar

**Comment by jsouth** [comment]
Confirmed issue and is currently on the master list : on it :)

**Comment by joaofnfernandes** [comment]
Closing as duplicate of #2619
