### ISSUE TITLE
Add snippets for Windows where commands differ

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2735]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/),

Right now the reference docs rely a lot on Linux commands. We should provide equivalent commands for Windows where those commands are different.

**Comment by mstanleyjones** [comment]
This probably should be raised in `/docker/docker` instead, as that is where the source files live.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #499](https://github.com/docker/cli/issues/499) via [**ZenHub**](https://www.zenhub.com/)
