### ISSUE TITLE
Feedback for: docker-hub settings/collaborators/

### ISSUE THREAD

**Issue by lordmatanza** [docker/docker.github.io#274]
When I try to edit the collaborators from my repo the page doesn't load.
When I try to open the collaborators page in a new window i get a _502 Bad Gateway_.

**Comment by sanscontext** [comment]
Hi @lordmatanza, thanks for the report. The Hub team is aware that there are currently issues loading the Collaborators page, and they're working on a fix. 

This repository is for documentation issues, not support questions or bug reports, so I'll close this ticket.
