### ISSUE TITLE
Offline EE install 

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#2744]
Some customers need to install EE offline and need to figure out how to copy the bits over from the EE repo link. I don't know the exact steps, but I've already been asked several times for this and it would be helpful to have this posted somewhere. 

File: [engine/installation/index.md](https://docs.docker.com/engine/installation/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
Do you mean something different from these:

https://docs.docker.com/engine/installation/linux/ubuntu/#install-from-a-package
https://docs.docker.com/engine/installation/linux/rhel/#install-from-a-package
https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package
https://docs.docker.com/engine/installation/linux/oracle/#install-from-a-package
https://docs.docker.com/engine/installation/linux/suse/#install-from-a-package

**Comment by yongshin** [comment]
Ahh thanks that helps. Thanks, will close this.
