### ISSUE TITLE
Code blocks showing and not being parsed correctly in multiple locations

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#2751]
File: [engine/userguide/storagedriver/device-mapper-driver.md](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/), CC @mstanleyjones 

![screenshot 2017-04-12 at 4 26 06 pm](https://cloud.githubusercontent.com/assets/414445/24977908/c3240ff0-1f9c-11e7-8f7c-a72df194fb79.png)

**Comment by stevenhanna6** [comment]
can I claim this bug please
