### ISSUE TITLE
Feedback for: compose/django.md

### ISSUE THREAD

**Issue by ramboldio** [docker/docker.github.io#276]
URL: [https://docs.docker.com/compose/django.md](https://docs.docker.com/compose/django/)
Is it safe for production to use standard passwords here?

**Comment by konstruktoid** [comment]
@ramboldio, I don't know what you mean by standard passwords, but you should never use passwords supplied by default.

For an interesting discussion about handling secrets, I recommend checking up on https://github.com/docker/docker/issues/13490

**Comment by ramboldio** [comment]
@konstruktoid thanks for the link :wink:
