### ISSUE TITLE
This seems outdated

### ISSUE THREAD

**Issue by cerebrotecnologico** [docker/docker.github.io#2767]
File: [registry/recipes/osx-setup-guide.md](https://docs.docker.com/registry/recipes/osx-setup-guide/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
Can you be a bit more specific about what's outdated? Is the fact that the article talks about multiple options to run registry on a mac, to it should just say to install Docker for Mac? Or is it something else?

**Comment by johndmulhausen** [comment]
Closing due to no response.
