### ISSUE TITLE
Missing argument from daemon config file: "metrics-addr"

### ISSUE THREAD

**Issue by briantd** [docker/docker.github.io#2768]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/), CC @mstanleyjones 

I noticed the "metrics-addr" argument is not listed among the supported options in the section covering the allowed options in the linux config file for surfacing the prometheus endpoint.

<img width="992" alt="screenshot of safari 4-13-17 3-24-21 pm" src="https://cloud.githubusercontent.com/assets/94055/25026900/d9435a4a-205d-11e7-868a-15dcb2603e4c.png">

<img width="305" alt="screenshot of safari 4-13-17 3-24-57 pm" src="https://cloud.githubusercontent.com/assets/94055/25026901/db3237cc-205d-11e7-9812-c820f0b7ec22.png">

**Comment by surajnarwade** [comment]
@briantd , its there please check https://docs.docker.com/engine/reference/commandline/dockerd/#description

**Comment by mstanleyjones** [comment]
Yes, it is there. Sorry for the confusion.

**Comment by briantd** [comment]
@mstanleyjones -- apologies if my issue description didn't make sense.   I'm not talking about the description section at the TOP of the document, but rather the Linux and Windows daemon configuration files at the BOTTOM of the document: https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

**Comment by mstanleyjones** [comment]
I see what you mean now. It's not really possible to keep those examples up to date manually. I filed an issue in moby/moby that may help.
