### ISSUE TITLE
Layout problems at 1016 px wide

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#2772]
File: [index.md](https://docs.docker.com/), CC @johndmulhausen 

If you resize your browser to exactly 1016px, the layout gets weird if the global header is showing. The boxes that hold the left-hand nav items seem to suddenly go to 100% of the screen width, and push the middle and right content down. When you scroll down, the fixed header kicks in and the layout problem is fixed. Screenshot attached.

<img width="1019" alt="screen shot 2017-04-13 at 6 59 29 pm" src="https://cloud.githubusercontent.com/assets/7674613/25030702/a1b3da50-207b-11e7-8b3e-cb6ce8df36a5.png">

**Comment by Rubab-Syed** [comment]
I would like to work on this!

**Comment by Rubab-Syed** [comment]
I am unable to reproduce this. Is this still a bug?

**Comment by gschaetz** [comment]
I tried as well does not appear to be a broken.  Tried in chrome and safari

**Comment by mstanleyjones** [comment]
Correct, this is fixed. Thanks @runshenzhu !
