### ISSUE TITLE
Docs non-response

### ISSUE THREAD

**Issue by itsopen** [docker/docker.github.io#2778]
It seems that the main text column of the getting started webpage is non responsive, which was noticed when trying to run some CLI commands next to the docs.

Noticed on Win/Mac getting started pages.

https://docs.docker.com/docker-for-windows/ 

File: [index.md](https://docs.docker.com/), CC @johndmulhausen

**Comment by joaofnfernandes** [comment]
I can't seem to reproduce this. Can you take a screenshot/gif that shows the behavior?

**Comment by itsopen** [comment]
Here you go - this is in latest Chrome, Win10 x64 (Creators Update):

![screen](https://cloud.githubusercontent.com/assets/15907315/25056117/b6d7a3c4-215e-11e7-8358-bc6c24b43555.JPG)

**Comment by joaofnfernandes** [comment]
Oh, I got it now. Thanks for the screenshot!
Related to #2619

**Comment by johndmulhausen** [comment]
We fixed this over in #2619; I'm showing a nice, narrowing middle column as you resize, now. Thanks!
