### ISSUE TITLE
Make notes conform to new style

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2781]
Follow-up of #2710. Now that have different css classes for notes and warnings, we should clean up existing notes to make them conform to the new style.

You can see an example of the new style at #2710

**Comment by shubheksha** [comment]
I'll try to work on this over the course of this week!

**Comment by shubheksha** [comment]
Should I wait for #2795 before working on this?

**Comment by mstanleyjones** [comment]
No, you can go ahead with this work, it is only the CSS we are discussing in #2795. The classes will be the same, so the method will be the same.

**Comment by clocklear** [comment]
@shubheksha are you still working on this?  This issue hasn't been marked as claimed.

**Comment by tippexs** [comment]
claimed

**Comment by mstanleyjones** [comment]
@shubheksha had you intended to claim this or started work on it yet?

**Comment by shubheksha** [comment]
@mstanleyjones, yes I've started work on this.

**Comment by joaofnfernandes** [comment]
#2937 relates to this

**Comment by mstanleyjones** [comment]
@joaofnfernandes can this be closed?

**Comment by joaofnfernandes** [comment]
Not yet. #2937 fixed this a bit, but I'm still seeing tons of notes and warnings using the old style. Once I have time, I'll take a stab at this.

**Comment by johndmulhausen** [comment]
Closing as obsolete; thanks to @shubheksha, @tippexs, @londoncalling, and @joaofnfernandes for all contributing.
