### ISSUE TITLE
Very wide images break the page layout

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#2782]
File: [test.md](https://docs.docker.com/test/), CC @johndmulhausen 
On smaller screens, such as a 13" laptop or an iPhone, if a very wide image is on the page, it breaks the page layout, forcing the right-hand column off the page canvas completely. You can see this on `/test/`.

Probably images should be constrained to a max width of 100% of their parent div.

**Comment by domg123** [comment]
#dibs

**Comment by gschaetz** [comment]
I got it

**Comment by gschaetz** [comment]
It appears that this is already fixed =)

**Comment by londoncalling** [comment]
@gschaetz thanks for checking this out.  Giving you 25 points on this.
