### ISSUE TITLE
On the 404 page, the "Request Docs Changes" link should include the referrer, not 404.md, in the report

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#2783]
If you click Request Docs Changes on the 404 page, it reports that the error is in 404.md. This may be the case but it is much more likely that someone wants to report a 404 and has not realized that there is a link to do that in the 404 page itself. You can try it by going to https://docs.docker.com/foo and clicking "Request docs changes" and comparing its behavior to if you clicked "File a ticket" in the same page.

The fix is either to disable the Report docs  changes link on the 404 page (probably bad UX) or to make it  behave the same as the File an issue link on the same page. Either way it needs a Liquid if/then kind of thing in `_layouts/docs.html`.

**Comment by prashant171992** [comment]
Raised PR here :  https://github.com/docker/docker.github.io/pull/2838

**Comment by prashant171992** [comment]
@mstanleyjones is it ok to remove the 'Report docs changes' link on 404 page ? If yes, then I have raised the PR as above. 
If I make it to behave like 'File an issue' link , then two links will do the same way on the same page . Is it acceptable ?
