### ISSUE TITLE
Improve note accessibility

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#2784]
### Problem description

After #2710, notes are less accessible. We need to add the note type to the note title, so that people with color blindness and other color-differentiating issues can still discern the note severity and type.

One suggestion is to modify the CSS and use the `:before` selector to add the content of either `Note: `, `Important: `, or `Warning: ` before the note title.

Please don't use Javascript to do this, as we already have too much Javascript in the site.

Relates to #2781 

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by johndmulhausen** [comment]
@joaofnfernandes has called #dibs on this in #2795
