### ISSUE TITLE
Clarify differences in Cloud stack YAML vs. Compose and stack files

### ISSUE THREAD

**Issue by londoncalling** [docker/docker.github.io#2793]
### Problem description

- Users can get confused in choosing between Cloud stack YAML file,  Compose file, and `docker-stack.yml`.

- Documentation might help with this. 

### Questions
1. Does the Cloud stack YAML need updates per the latest Compose v3 file? Or are they completely independent?
2. Should we include several notes in Cloud stack YAMl to redirect users to the latest Compose file? (Both at the top of the file, and at each config option?)
3. Is there further confusion that could result from competing concepts of Cloud stack YAML and docker-stack.yml (a type of Compose file for v3, as described in the voting app sample)? If so, what's the best way to address this?
4. Is there any possibility of renaming one or more of these files? (e.g.,  Cloud stack YAML file) or somehow differentiating between these files in terms of file naming?

### Related issues

https://github.com/docker/docker/issues/32623 (opening a new issue on this in the documentation repo)

### Reviewers

@pkennedyr @KickingTheTV @ManoMarks @vdemeester @mstanleyjones

**Comment by johndmulhausen** [comment]
Closing per triage discussion.
