### ISSUE TITLE
Documentation for Docker Hub REST Api v2 

### ISSUE THREAD

**Issue by bertrandmartel** [docker/docker.github.io#2800]
I can't find API reference for Docker Hub REST Api v2. Only v1.7 is available at this location : https://docs.docker.com/v1.7/reference/api/docker-io_api/

A lot of links from external source point to : https://docs.docker.com/reference/api/docker-io_api/ which doesn't exist.

Is this intended ? Does Docker Hub RESP Api reference v2 exist ?

Thanks for your help

File: [404.md](https://docs.docker.com/404.html), CC @johndmulhausen

**Comment by johndmulhausen** [comment]
@bertrandmartel That API is no longer supported, and in fact Docker Hub itself has been superseded by Docker Store and Docker Cloud.

**Comment by fluency03** [comment]
@johndmulhausen do you know what are the APIs for Docker Store and Docker Cloud? thanks:)

**Comment by revett** [comment]
@johndmulhausen 

The API still seems to be running, as this endpoint suggests:

[https://hub.docker.com/v2/repositories/mariobehling/loklak/autobuild/](https://hub.docker.com/v2/repositories/mariobehling/loklak/autobuild/)

![image](https://user-images.githubusercontent.com/2796074/31022419-a5686e24-a530-11e7-9480-568a18e13b4b.png)

If Docker are wanting to no longer support this API, could you point me to the documentation of the API that is replacing it?

Thanks 👍

**Comment by neglectos** [comment]
@mistyhacks do you know what is the official documentation for the docker API?

Thanks!

**Comment by mistyhacks** [comment]
@johndmulhausen @KickingTheTV PTAL

**Comment by kvbx** [comment]
This is so bad.

**Comment by samkreter** [comment]
Is there still no update on the rest API docs? I can't find anything

**Comment by iDuronto** [comment]
Security through obscurity, is it?
