### ISSUE TITLE
Document what --memory-swap=0 means

### ISSUE THREAD

**Issue by jamshid** [docker/docker.github.io#2801]
File: [engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/), CC @mstanleyjones 

The latest docs https://docs.docker.com/engine/admin/resource_constraints/#/memory-swap-details do not describe the effect of using `--memory-swap=0`. The default is `-1` which means unlimited, and using a positive integer (i.e. >1) is defined. 

Does `0` mean no swap will be allowed, or do I have to set `--memory` and `--memory-swap` to the same value to accomplish that?

Filing here as recommended in https://github.com/docker/docker/issues/30716.

**Comment by joeuo** [comment]
I'll take this one up!

**Comment by johndmulhausen** [comment]
Points to @joeuo
