### ISSUE TITLE
easier way to obtain docker-stack.yml at voting app example

### ISSUE THREAD

**Issue by yurtesen** [docker/docker.github.io#2853]
At:
https://docs.docker.com/engine/getstarted-voting-app/deploy-app/#copy-docker-stackyml-to-the-manager

I think this is over complicated. Especially for a windows user, it suggests creating file in a linux machine then copy from there to windows then use `docker-machine scp` to copy to the manager machine etc.

In the previous step we already had ssh connection open to manager machine. We can simply use wget or curl to directly download the file into the machine.

`$ wget https://github.com/docker/example-voting-app/raw/master/docker-stack.yml`

is all you need to run to get the file into manager. Just change it to 1 simple step to directly download the file into manager.

**Comment by johndmulhausen** [comment]
This topic has been removed. Thanks, @yurtesen
