### ISSUE TITLE
Change references to docker/docker to moby/moby

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#2868]
### Problem description

Hitting `docker/docker` now redirects to `moby/moby` but we should clean up mentions of it in:
- docs
- Dockerfile and `_scripts/` files
- `_layouts/docs.html` and associated Javascript
- `_data/not_edited_here.yaml`

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by NonCreature0714** [comment]
Also working on this! Woot! @shubheksha @mstanleyjones @londoncalling

**Comment by shubheksha** [comment]
Hey @NonCreature0714, I already fixed this in #2873 😄

**Comment by NonCreature0714** [comment]
Darn... I was hoping I got it! @shubheksha

**Comment by mstanleyjones** [comment]
Let me review this one, then @NonCreature0714 can base their work on your work if it is ready to merge. There is plenty to do here!

**Comment by mstanleyjones** [comment]
Hey @shubheksha sorry about this, but wea re going to take the fix in #2879 for this, because it is already ready to merge. You have done fantastic work on a lot of issues so far and we really appreciate it!

**Comment by shubheksha** [comment]
This could've been communicated when the changes were approved itself because I wasted a ton of time opening a new PR for this same issue as it was decided that it would be a collaborative effort.

**Comment by mstanleyjones** [comment]
Oh, I'm sorry I was out of the loop. :(
