### ISSUE TITLE
Feature Request: PDF format download of entire docs

### ISSUE THREAD

**Issue by HariSekhon** [docker/docker.github.io#289]
Useful to read on a kindle or ipad on the daily commute.

**Comment by johndmulhausen** [comment]
Hi @HariSekhon - the best we could do is something like http://wkhtmltopdf.org/ 

Have you tried this?

**Comment by HariSekhon** [comment]
Looks interesting, I hadn't come across that before. It's probably not the right solution for each user to have to figure out independently how to mirror the entire docs structure in to a pdf, but if you're meaning to use it to generate the doc and provide a download link on the official doc site then that makes sense. Quite a lot of vendors such as Cassandra provide both the online HTML and PDF downloadable versions of the same documentation.

**Comment by johndmulhausen** [comment]
I don't think this is something we can do, sadly. If we ever change to use Pandoc it may be possible. I know it won't work on iPad, but you can run the docs locally by running:

`docker run -ti -p 4000:4000 docs/docker.github.io`
