### ISSUE TITLE
I have no clue how to use -e based on this doc

### ISSUE THREAD

**Issue by pruggera** [docker/docker.github.io#2891]
File: [engine/reference/commandline/exec.md](https://docs.docker.com/engine/reference/commandline/exec/), CC @mstanleyjones

**Comment by vishnu-narayanan** [comment]
I'll have a go at this.

**Comment by vishnu-narayanan** [comment]
https://github.com/moby/moby/pull/32739
Unable to submit PR to this repo. @JimGalasyn

**Comment by johndmulhausen** [comment]
Fix was merged upstream. Thanks!
