### ISSUE TITLE
As Flocker has shutdown So you need to add new plugin or provide shared plugin tutorial 

### ISSUE THREAD

**Issue by thatsk** [docker/docker.github.io#2897]
File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/), CC @mstanleyjones

As people are trying to search flocker but flocker has shutdown . So you need to update that

**Comment by frankgreco** [comment]
#dibs

**Comment by johndmulhausen** [comment]
Points to @frankgreco
