### ISSUE TITLE
Use official consul docker image in tutorial

### ISSUE THREAD

**Issue by fosk06** [docker/docker.github.io#2908]
File: [engine/userguide/networking/get-started-overlay.md](https://docs.docker.com/engine/userguide/networking/get-started-overlay/), CC @mstanleyjones
Hello,
Is it possible to have this tutorial with the official consul image?
This tutorial actually work with progrium/consul image wich has an old version of consul.
I tried to do it myself without success.

**Comment by joaofnfernandes** [comment]
Did you have problems following the tutorial as it is? If so, what are you seeing?

**Comment by mstanleyjones** [comment]
The problem with the tutorial is that the official `consul` image expects you to give it a command (in this case `agent`) while the unofficial one apparently did not. Addressing this as part of #4670.
