### ISSUE TITLE
separate the links

### ISSUE THREAD

**Issue by surajnarwade** [docker/docker.github.io#2934]
### Problem location
separate out the link `docker engine` and `docker-compose`

- I saw a problem on the following URL: <URL>
https://docs.docker.com/compose/gettingstarted/
- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by surajnarwade** [comment]
@londoncalling,   can you please label this as hackathon ?

**Comment by londoncalling** [comment]
@surajnarwade I just changed some of these the opposite of what you are doing here in another file. Here is my thinking on this: 
- If a code example is showing a one-line command with no output, then I think it is better _not_ to show the command prompt. That way users can simply copy-paste the command. For example: 

```
docker-compose stop
```

- If a code example is showing an example command with the output, then I think we should include the command prompt for clarity. For example: 

```
$ docker-compose up -d
Starting composetest_redis_1...
Starting composetest_web_1...

$ docker-compose ps
Name                 Command            State       Ports
-------------------------------------------------------------------
composetest_redis_1   /usr/local/bin/run         Up
composetest_web_1     /bin/sh -c python app.py   Up      5000->5000/tcp
```

**Comment by surajnarwade** [comment]
@londoncalling make sense, but which file you are pointing ?

**Comment by surajnarwade** [comment]
@londoncalling got you, shall I edit for the same ?

**Comment by londoncalling** [comment]
@surajnarwade yes that would be great. (The other files I'm working on are visible on PR #2942 , am about to merge it.)

I wouldn't go tackling all docs for this, but if you already see other problems in a file, and see this issue as well, then you can fix it along with the primary issues.

**Comment by londoncalling** [comment]
@surajnarwade , you can actually see @johndmulhausen taking this approach in the new getting started example, e.g., https://docs.docker.com/get-started/part2/

**Comment by surajnarwade** [comment]
@londoncalling got it :)
