### ISSUE TITLE
Clarify -m / --memory usage on Windows with & without isolation

### ISSUE THREAD

**Issue by PatrickLang** [docker/docker.github.io#2936]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/), CC @mstanleyjones 

Memory limits work differently on Windows depending on whether or not you're using `--isolation=hyperv`

I think it would be good to add a brief note clarifying that:

- `-m` or `-memory` do set an upper limit on memory usage for both process and hyperv isolation
- With process isolation, Windows reports the full memory of the system, not the limit
- with Hyper-V isolation, Windows reports the limit as the total system memory

I'm hoping to attach a PR shortly

Related issues:
https://github.com/moby/moby/issues/27892

**Comment by mstanleyjones** [comment]
Also relates to #2854

**Comment by PatrickLang** [comment]
Alright, fixed up my PR and gave Gordon some extra spinach

**Comment by joaofnfernandes** [comment]
It seems moby/moby##32724 made its way [into the docs](https://docs.docker.com/engine/reference/commandline/run/#specify-hard-limits-on-memory-available-to-containers--m-memory)
so I'm closing this one.
