### ISSUE TITLE
Mobile navbar disappears on mobile while scrolling

### ISSUE THREAD

**Issue by allejo** [docker/docker.github.io#2938]
While scrolling on the mobile version of the site, the navbar disappears and then reappears. This only occurs on the homepage due to Bootstrap's "affix" functionality

![apr-19-2017 14-50-02](https://cloud.githubusercontent.com/assets/1246453/25203807/83b09d84-250f-11e7-9235-17a735e77b90.gif)

**Comment by johndmulhausen** [comment]
Excellent work, @allejo !

**Comment by allejo** [comment]
wait wait this one hasn't been fixed yet! I do have a fix in mind for it though if you want the PR
