### ISSUE TITLE
show output on docker unpause

### ISSUE THREAD

**Issue by surajnarwade** [docker/docker.github.io#2951]
### Problem location

https://docs.docker.com/engine/reference/commandline/unpause/

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

as `$ docker unpause my_container` is written as command, we should show its output also

**Comment by surajnarwade** [comment]
@londoncalling @johndmulhausen thoughts, hackathon :)

**Comment by johndmulhausen** [comment]
Hey @surajnarwade -- quick note, only bugs that we have labeled "hackathon" count towards the hackathon. You are free to file bugs and PRs, though. :)

**Comment by surajnarwade** [comment]
@johndmulhausen , no  worries :)

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #589](https://github.com/docker/cli/issues/589) via [**ZenHub**](https://www.zenhub.com/)
