### ISSUE TITLE
add example to docker top

### ISSUE THREAD

**Issue by surajnarwade** [docker/docker.github.io#2953]
### Problem location

https://docs.docker.com/engine/reference/commandline/top/

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

add example for docker top command

**Comment by surajnarwade** [comment]
@londoncalling @johndmulhausen thoughts and hackathon

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #588](https://github.com/docker/cli/issues/588) via [**ZenHub**](https://www.zenhub.com/)
