### ISSUE TITLE
Misprint in a filter name

### ISSUE THREAD

**Issue by mcctomsk** [docker/docker.github.io#2955]
File: [engine/reference/commandline/stack_ps.md](https://docs.docker.com/engine/reference/commandline/stack_ps/), CC @mstanleyjones

> The currently supported filters are:
> id
> name
> desired-stat

Correct name of last filter in list is **desired-state**
And it will be good, or add there more information about using this filter, or place link to actually the same information in this article: 
https://docs.docker.com/engine/reference/commandline/service_ps/#filtering

**Comment by bhavin192** [comment]
The file needs examples also!!
I will do it.

**Comment by johndmulhausen** [comment]
Looks like the correct filter name is there now.
