### ISSUE TITLE
Feedback for: docker-store/publish.md

### ISSUE THREAD

**Issue by sanscontext** [docker/docker.github.io#296]
URL: [https://docs.docker.com/docker-store/publish.md](https://docs.docker.com/docker-store/publish/)

I just realized this isn't showing up in the Store menu. Not sure if that was intentional?

**Comment by sanscontext** [comment]
(Er @johndmulhausen since you'd probably know if there was a decision to take it out of the menu)

**Comment by johndmulhausen** [comment]
No, just pure oversight. Hmm. Well, fixed in 26f55277016d9a47e58f7d1db90b4039148bbc1c
