### ISSUE TITLE
docker-compose tutorial requires modifications to deploy app

### ISSUE THREAD

**Issue by morrisalp** [docker/docker.github.io#2963]
### Problem description

I have been following the instructions in the "Get started with Docker Compose" tutorial and found that I needed to modify the instructions slightly to get the app to deploy properly. Two modifications are needed:

1. If I follow the instructions as-is to create the contents of composetest/ and then run *docker-compose up*, I get the following error message:

```
$ docker-compose up
Creating network "composetest_default" with the default driver
Creating composetest_redis_1
Creating composetest_web_1
Attaching to composetest_redis_1, composetest_web_1
redis_1  | 1:C 20 Apr 13:32:52.515 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
web_1    | python: can't open file 'app.py': [Errno 2] No such file or directory
composetest_web_1 exited with code 2
```

   As suggested at [this issue report](https://github.com/docker/compose/issues/1616) for Docker Compose, it seems that there's some conflict between the volumes array in docker-compose.yml and the ADD instruction in the Dockerfile. I've fixed this by commenting out the volumes section in docker-compose.yml (lines 7 and 8).
   
  2. Although the tutorial says that the app will be visible at http://0.0.0.0:5000/, this doesn't resolve for me. Instead I have to find the IP address of my Docker machine with *docker-machine ip* and then open http://DOCKER_MACHINE_IP:5000/. This is similar to the instructions for Docker Machine on a Mac, but I am on Windows.

The tutorial should be updated so that it is clear when these steps must be taken to run the given code.

### Problem location

The problem is located here: [Getting started with Docker Compose](https://github.com/docker/docker.github.io/blob/master/compose/gettingstarted.md)

### Project version(s) affected

I am running Docker on Windows 7. Here is information about my versions of Docker and Docker Compose:

```
$ docker version
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.28 (downgraded from 1.29)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Wed Apr 12 19:43:25 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
 ```

```
$ docker-compose version
docker-compose version 1.11.2, build f963d76f
docker-py version: 2.1.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

### Suggestions for a fix

I'm not sure exactly when these steps must be taken, but the tutorial should make it clear when they must be done to deploy the app.

**Comment by johndmulhausen** [comment]
Assigning to @gbarr01 to verify issue

**Comment by gbarr01** [comment]
Hi, @morrisalp, the issue you reference seems different. In ([#1616](https://github.com/docker/compose/issues/1616)), the user cannot mount a local volume from a remote machine. I don't believe this is what you are experiencing. 

I wonder if you problem is closer to [#3157](https://github.com/docker/compose/issues/3157)? If so, have you tried restarting/recreating your VM?
