### ISSUE TITLE
Doc: Fix terminology: "Base image" vs. "Parent  Image"

### ISSUE THREAD

**Issue by michael-holzheu** [docker/docker.github.io#2967]
From the documentation of [Base image](https://docs.docker.com/search/?q=base%20image):

> Definition of: base image
> 
> An image __that has no parent__ is a base image.

From the documentation of [Dockerfile](https://docs.docker.com/engine/reference/builder):

> Docker runs instructions in a Dockerfile in order. The first instruction must be FROM in order to specify the `Base Image` from which you are building.

Since the image that is specified via FROM can already be a derived image,  it is probably better to say:

> Docker runs instructions in a Dockerfile in order. The first instruction must be FROM in order to specify the `parent image` from which you are building.

Besides this, there are multiple other occurrences of the term "base image" that should be checked.

And also check the following broken link that is used in https://docs.docker.com/engine/reference/builder as link for "Base Image": https://docs.docker.com/engine/reference/glossary/#base-image

**Comment by surajnarwade** [comment]
@londoncalling this is nice catch, I am claiming this

**Comment by surajnarwade** [comment]
@michael-holzheu , I am not able to find a file regarding dockerfile reference in repo, can you point me towards that ?
cc @londoncalling

**Comment by michael-holzheu** [comment]
> @michael-holzheu , I am not able to find a file regarding dockerfile reference in repo, can you point me towards that ?

Not sure what you mean with "file". I just referred to the web pages.

**Comment by surajnarwade** [comment]
@michael-holzheu , file as in markdown file for that page in repo

**Comment by michael-holzheu** [comment]
> @michael-holzheu , file as in markdown file for that page in repo

So your question is "where is the markdown file for https://docs.docker.com/engine/reference/builder", right?
I checked out https://github.com/docker/docker.github.io but couldn't not find the markdown file either.

**Comment by michael-holzheu** [comment]
I think it is in the docker repository: https://github.com/moby/moby/blob/master/docs/reference/builder.md

**Comment by londoncalling** [comment]
@surajnarwade were you able to find this file? You'll need to clone a different repository to do this one, since some reference files live with the codebase, but the process for updates is the same.

**Comment by surajnarwade** [comment]
@londoncalling sure, I will do that

**Comment by johndmulhausen** [comment]
Note: Please do not link to `/engine/reference/glossary/` anywhere.

**Comment by AliBayatGH** [comment]
Both image types allow us to create a reusable image. However, base images allow us more control over the contents of the final image.

**Comment by Coder0-0** [comment]
Thank you for sharing!!
