### ISSUE TITLE
1212

### ISSUE THREAD

**Issue by nicolechan1224** [docker/docker.github.io#2977]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by nicolechan1224** [comment]
192.168.73.96

**Comment by joaofnfernandes** [comment]
@nicolechan1224 I'm closing this issue since it doesn't have a description of something broken in the docs. Feel free to open more issues if you find anything wrong 🙃
