### ISSUE TITLE
Tag 2.7-slim not found in repository docker.io/library/python

### ISSUE THREAD

**Issue by yurtesen** [docker/docker.github.io#2978]
At : https://docs.docker.com/get-started/part2/

First time I ran docker build
```
# docker build -t friendlyhello .
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM python:2.7-slim
Pulling repository docker.io/library/python
Tag 2.7-slim not found in repository docker.io/library/python
# cat Dockerfile |grep FROM
FROM python:2.7-slim
#
```

Second time it went through. I am not sure what was wrong? This seem to be a problem in docker itself perhaps? or bad error message? problem at docker hub?

Unfortunately it happened only once, I think the problem could have been a temporary network error, but the error message is confusing if that was the case...

**Comment by johndmulhausen** [comment]
It's definitely there: https://github.com/docker-library/official-images/blob/master/library/python

Sunspots? Glad it went through the second time. :)

**Comment by yurtesen** [comment]
@johndmulhausen Maybe, but the point was that the Docker told me clear as night and day
`Tag 2.7-slim not found in repository docker.io/library/python` 
This was obviously result of a bug. Because it exists in there as you pointed out and message makes no sense. Anyway, it is up to docker guys to decide if they want to end up with software full of nonsense errors and make usability zero or fix them... :)

**Comment by Oxymoron290** [comment]
https://github.com/docker/docker.github.io/issues/7273
