### ISSUE TITLE
Impossible to follow documentation examples on Ubuntu 17.04

### ISSUE THREAD

**Issue by yurtesen** [docker/docker.github.io#2981]
Ubuntu 17.04 comes with docker v1.12.6

It is impossible to use docker repository due to:
https://github.com/docker/docker.github.io/issues/2980

When following the documentation examples at:
https://docs.docker.com/get-started/part3/#docker-composeyml

One gets an error:
```
# docker stack deploy -c docker-compose.yml getstartedlab
docker: 'stack' is not a docker command.
See 'docker --help'.
#
```

I am not sure if documentation should be sectioned by version or ? I think the stack command was added in 1.13? How does one know which version of docker the documentation applies to?

**Comment by johndmulhausen** [comment]
@yurtesen Yes, they are in 1.13. The directions do say to get started by installing docker, but we can mention that at a minimum Docker 1.13 is required in the prerequisites in the six pages.

**Comment by stevenhanna6** [comment]
I claim thee!

**Comment by yurtesen** [comment]
The problem I had was because I used ubuntu 17.04, which said it supports docker in it's release notes. But apparently it is the only release not supported by docker.

I think it would be worthwhile if you can get Ubuntu to include latest docker binaries. It is just annoying that one must uninstall ubuntu supplied docker to install the working one.

Then I installed 16.04.2 but had other problems. Overall, docker was totally unusable for me. I gave up for now. I will try docker again at a later time. Hopefully it would get more mature by then. 

Thanks for the quick responses.
