### ISSUE TITLE
Get started needs to tell you to run docker swarm init upfront

### ISSUE THREAD

**Issue by yurtesen** [docker/docker.github.io#2982]
At: https://docs.docker.com/get-started/part3/#docker-composeyml

I installed fresh Ubuntu 16.04.2 and installed docker-ce using instructions `Docker version 17.03.1-ce, build c6d412e`

After creating the yml file,  I get error when trying to follow instructions:

```
# docker stack deploy -c docker-compose.yml getstartedlab
This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
#
```

**Comment by joaofnfernandes** [comment]
Right below the deployment instructions, it says that if you see an error like that, you should run
```
docker swarm init
docker stack deploy -c docker-compose.yml getstartedlab
```

If you want to use `docker stack` you'll always have to run the `docker swarm init` command first, to that getting started should tell you that upfront.
I've updated the issue title to make that clear.

**Comment by stevenhanna6** [comment]
I claim thee
