### ISSUE TITLE
Can't deploy service from documentation

### ISSUE THREAD

**Issue by yurtesen** [docker/docker.github.io#2983]
I pushed the friendlyhello to docker hub and created docker-compose.yml on freshly installed ubuntu 16.04.2 with docker  17.03.1-ce, build c6d412e. The only thing which I had to do which was not in documentation was to run `docker swarm init` because of #2982 

Here is full output of test from scratch. As you can see, image works by itself but not when used with stack as service:
```
root@ubuntu:/home/ubuntu/docker# docker run -d -p 80:80 yurtesen/friendlyhello:latest
Unable to find image 'yurtesen/friendlyhello:latest' locally
latest: Pulling from yurtesen/friendlyhello
6d827a3ef358: Pull complete
ede2632a1ec5: Pull complete
a8e707e000d5: Pull complete
77d4d7d5b615: Pull complete
4fa183efa27b: Pull complete
9c863af25bf5: Pull complete
Digest: sha256:cf0d30602055312cd40a1f50a30489596ed674721685befbc46771ede8e08172
Status: Downloaded newer image for yurtesen/friendlyhello:latest
01ded82130828e78eeb33304ba9bcb2dc99994522e683b7898d6b3ca5b79c247
root@ubuntu:/home/ubuntu/docker# telnet localhost 80
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1

HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 118
Server: Werkzeug/0.12.1 Python/2.7.13
Date: Fri, 21 Apr 2017 10:32:35 GMT

<h3>Hello World!</h3><b>Hostname:</b> 01ded8213082<br/><b>Visits:</b> <i>cannot connect to Redis, counter disabled</i>Connection closed by foreign host.
root@ubuntu:/home/ubuntu/docker# docker ps
CONTAINER ID        IMAGE                           COMMAND             CREATED              STATUS              PORTS                NAMES
01ded8213082        yurtesen/friendlyhello:latest   "python app.py"     About a minute ago   Up About a minute   0.0.0.0:80->80/tcp   laughing_torvalds
root@ubuntu:/home/ubuntu/docker# docker stop 01ded8213082
01ded8213082
root@ubuntu:/home/ubuntu/docker# telnet localhost 80
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
root@ubuntu:/home/ubuntu/docker# cat docker-compose.yml
version: "3"
services:
  web:
    image: yurtesen/friendlyhello:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
root@ubuntu:/home/ubuntu/docker# docker stack deploy -c docker-compose.yml getstartedlab
Creating network getstartedlab_webnet
Creating service getstartedlab_web
root@ubuntu:/home/ubuntu/docker# docker stack ps getstartedlab
ID            NAME                 IMAGE                          NODE    DESIRED STATE  CURRENT STATE           ERROR  PORTS
yij73olrj31l  getstartedlab_web.1  yurtesen/friendlyhello:latest  ubuntu  Running        Running 11 seconds ago
oi1ty4ja4sj5  getstartedlab_web.2  yurtesen/friendlyhello:latest  ubuntu  Running        Running 8 seconds ago
xa2qlnzm8i3c  getstartedlab_web.3  yurtesen/friendlyhello:latest  ubuntu  Running        Running 10 seconds ago
5fb6n3wtzbuc  getstartedlab_web.4  yurtesen/friendlyhello:latest  ubuntu  Running        Running 8 seconds ago
5vezyuecha3h  getstartedlab_web.5  yurtesen/friendlyhello:latest  ubuntu  Running        Running 9 seconds ago
root@ubuntu:/home/ubuntu/docker# telnet localhost 80
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1



^C
^]
telnet> quit
Connection closed.
root@ubuntu:/home/ubuntu/docker# curl http://localhost
^C
root@ubuntu:/home/ubuntu/docker# curl -m 30 http://localhost
curl: (28) Operation timed out after 30001 milliseconds with 0 bytes received
root@ubuntu:/home/ubuntu/docker#
```

**Comment by yurtesen** [comment]
There is a mistake, because this bug was not related to `docker swarm init`. I ran `docker swarm init` but `docker stack deploy` does not function as can be seen from the output. Can you tell what I did wrong then?

**Comment by OrezzerO** [comment]
I meet the same problem in macOS ,I re-install dokcer and it works ,however the second day ,it can't work again. Finally ,I install dcoker 17.05.0-ce-rc1 ,it works.

**Comment by yurtesen** [comment]
Can you re-open the issue or explain why this was closed? I think it was closed accidentally. Other people are having problems also?

**Comment by csullivannet** [comment]
I am also seeing this issue on Fedora 25
```
docker -v
Docker version 17.03.1-ce, build c6d412e
```

**Comment by knewman00** [comment]
Same problem here:
```
Docker version 17.03.1-ce, build c6d412e
CentOS Linux release 7.3.1611 (Core)
```
CentOs on VBox

**Comment by andbar-ru** [comment]
Same problem
```
Docker version 17.06.1-ce, build 874a737
Debian 9.1, kernel: 4.9.0-3-amd64
```

**Comment by houmanb** [comment]
Same problem here:

```
$uname -a
MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0

$ docker -v
Docker version 17.06.1-ce, build 874a737
```

**Comment by dueringa** [comment]
I guess this is Getting started, step 3? I remapped to port 4000, because port 80 was in use.

    $ docker service ls
    ID                  NAME                MODE                REPLICAS            IMAGE                  PORTS
    399d9y9sor28        getstartedlab_web   replicated          1/1                 friendly_hello:step2   *:4000->80/tcp
    $ docker container ps
    CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS               NAMES
    8165162b4966        friendly_hello:step2   "python app.py"     5 minutes ago       Up 5 minutes        80/tcp              getstartedlab_web.1.xr09nfgv90g5kgjl5g4jn80lc

    $ curl http://127.0.0.1:4000
    curl: (7) Failed to connect to 127.0.0.1 port 4000: Connection refused

    $ uname -a
    Linux Gentoo64 4.9.76-gentoo-r1 #2 SMP Wed Apr 18 21:39:54 CEST 2018 x86_64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz GenuineIntel GNU/Linux
    $ docker -v
    Docker version 17.12.1-ce, build 7390fc6

With `docker-compose up`, it works.

**Comment by avalanchus** [comment]
I've tried to perform step 4 (https://docs.docker.com/get-started/part4) using swarm on Windows 10 +HyperV as host but get error: 
no such image: <my image on hub.docker.com> (when I run  "docker stack ps getstartedlab")
I also noticed that 0/5 replicas are work ("docker stack services getstartedlab"):
ID                  NAME                MODE                REPLICAS            IMAGE                       PORTS
nkax4k605s4i        getstartedlab_web   replicated          0/5                 shurhen/get-started:part2   *:4000->80/tcp
I've tried deploy with key --with-registry-auth bat result is same.
I tried to reproduce exactly what was written in the manual, but I failed. Help me pls
