### ISSUE TITLE
Front page broken in firefox: image missized

### ISSUE THREAD

**Issue by yallop** [docker/docker.github.io#2985]
### Problem description

The hackathon image is currently displayed at an enormous size on the front page.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/

Here's a screenshot:

![firefox-frontpage-800](https://cloud.githubusercontent.com/assets/1736496/25284298/81d0133c-26ae-11e7-8134-e22f059668e8.png)

**Comment by johndmulhausen** [comment]
Sorry, @yallop, no repro. You probably need to update your version of Firefox.

![](http://imgur.com/a/TYeq3)

**Comment by yallop** [comment]
@johndmulhausen: I'm using the [ESR version of Firefox provided by my distribution](https://packages.debian.org/jessie/firefox-esr).

**Comment by johndmulhausen** [comment]
Sorry, I know it sucks when things don't work, but we have to draw the line somewhere. Running Firefox 52 and 53 both worked.
