### ISSUE TITLE
DTR Upgrade Docs No Mention of Backup

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#2986]
@mark-church commented on [Mon Mar 20 2017](https://github.com/docker/dhe-deploy/issues/4895)

### What's the problem/feature request?
There is no mention of backups in the DTR upgrade docs. Field best practices always recommends doing a backup before an upgrade because many customers do not take backups or do so irregularly. A bad upgrade without a backup could result in customer data loss. Can we include doing a manual DTR backup (and link to the backup section) as the 1st step of any DTR upgrade?

[DTR 2.1 Upgrade Doc](https://docs.docker.com/datacenter/dtr/2.1/guides/install/upgrade/)
[DTR 2.2. Upgrade Doc](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/upgrade/#minor-upgrade)

### Who is asking for this?
Technical Field

### What is the (customer) Impact of this request or severity of the issue?
Potential to limit customer issues

### What versions/components are affected?
All currently supported DTR versions: DTR 2.0 - 2.2

**Comment by stevenhanna6** [comment]
I claim this new found issue
