### ISSUE TITLE
It is helpful to match the commands with the printouts

### ISSUE THREAD

**Issue by gdennie** [docker/docker.github.io#3007]
File: [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/), CC @mstanleyjones 

While `docker ps --format` uses `Go templates`, the current implementation does miss the opportunity to make the field names match the report column titles. In particular, it seems that the current possible field names should be used as the corresponding printout column titles. (I have belated suspect the pattern of lowercase with capitalized first letter; however, I think the suggestion is still good.)

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #500](https://github.com/docker/cli/issues/500) via [**ZenHub**](https://www.zenhub.com/)
