### ISSUE TITLE
Windows Server 2016 compose install instructions?

### ISSUE THREAD

**Issue by programmerq** [docker/docker.github.io#3012]
From: https://forums.docker.com/t/where-do-you-get-docker-compose-exe-for-windows-2016/31313

The current install instructions say that since Docker for Windows and Docker Toolbox already include compose that windows instructions aren't needed. Neither of these solutions encompass running a docker windows daemon/client directly on windows server 2016.

File: [compose/install.md](https://docs.docker.com/compose/install/), CC @londoncalling

**Comment by friism** [comment]
`Invoke-WebRequest "https://github.com/docker/compose/releases/download/$dockerComposeVersion/docker-compose-Windows-x86_64.exe" -UseBasicParsing -OutFile $Env:ProgramFiles\docker\docker-compose.exe`

**Comment by londoncalling** [comment]
Fixed in #3035
