### ISSUE TITLE
404 at /engine/reference/glossary/

### ISSUE THREAD

**Issue by philipsoeberg** [docker/docker.github.io#3023]
Source: https://docs.docker.com/engine/reference/builder/#from

Text: The FROM instruction sets the Base Image for subsequent instructions.
Link "Base Image" above links to https://docs.docker.com/engine/reference/glossary/#base-image which does not exist.

URL: /engine/reference/glossary/

**Comment by bdwill** [comment]
Looks like the reference was pulled sometime ago (found in v1.11 defined as "an image that has no parent image"). Is it preferred to re-add the definition or modify the docs to remove the link?
