### ISSUE TITLE
Updating Docs for new CLI?

### ISSUE THREAD

**Issue by wershlak** [docker/docker.github.io#3031]
### Problem description

Are there plans to migrate the docs to use the new CLI commands in all cases? I feel like new users should be exposed to the new commands right away (since it's new and more intuitive) but I don't want to spend time updating if it's not wanted.

### Problem location

Example: https://docs.docker.com/get-started/ "docker run hello-world" vs "docker container run hello-world"

### Project version(s) affected

1.13 and later

**Comment by joaofnfernandes** [comment]
I 100% agree with you, and would love to see that change.

**Comment by johndmulhausen** [comment]
`docker rm` and `docker rmi` are the worst offenders.

**Comment by gbarr01** [comment]
Hi, @joaofnfernandes, where can I find information on which commands are new and which are deprecated? For example, both the [Reference guide](https://docs.docker.com/reference/) and `docker --help` include `docker rmi` and `docker image rm`. Is there any definitive guidance somewhere?

**Comment by joaofnfernandes** [comment]
Technically both commands are supported, but we've done a lot of work to make the CLI follow the pattern `docker <object> <verb>`, like `docker image rm`.
After the UX research sessions I've attended, I would say that new users learn that pattern faster, so the documentation (specially anything related to getting started) should use that syntax.

I know that @mstanleyjones doesn't agree with me, so maybe ping @aluzzardi or @dmp42, since they were involved in the decision to introduce that new syntax. They might be able to help you prioritize.

**Comment by mstanleyjones** [comment]
The main one we do *not* want to update is existing instances of `docker run`. The others are fair game, and maybe it should be done a a series of PRs because it might be a little difficult to review them.

**Comment by gbarr01** [comment]
@joaofnfernandes, @mstanleyjones , I need to look at each instance carefully before I search/replace, but do these grep returns look like a reasonable place to start? 

```
grep -rn --include="*.md" --exclude-dir="release-notes" "docker rmi"
grep -rn --include="*.md" --exclude-dir="release-notes" "docker ps"
```

**Comment by mstanleyjones** [comment]
so, I would use an excellent GUI tool called [FAR](http://findandreplace.sourceforge.net/) for this. Or I'd use Atom's built-in search. But if you want to use `grep` I would add the `-l` option to only list the file names, not show the context within the file.

**Comment by gbarr01** [comment]
@mstanleyjones , thanks, I'll look at FAR. The grep commands were for demonstration only, so you could see the entries and if they made sense to replace.

**Comment by mstanleyjones** [comment]
When running your command, I got an error about recursive search on STDIN, so I adapted it:

```
grep -r "docker rmi" * |grep -v '_site' |grep -v 'release-notes' | grep '.md'
```

That worked for me and gave me results that made sense to me. If you add `-l` then you can pipe that straight into Atom, to get it to open the files for you:

```
grep -rl "docker rmi" * |grep -v '_site' |grep -v 'release-notes' | grep '.md' |while read i; do atom $i; done
```

**Comment by gbarr01** [comment]
I wonder how we should handle [this sort of thing](https://docs.docker.com/get-started/#container-diagram):

> These processes run like native processes, and you can manage them individually by running commands like docker ps—just like you would run ps on Linux to see active processes.

**Comment by mstanleyjones** [comment]
I think we should just lose that whole thing, since we don't want to be so Linux-centric anymore.

**Comment by londoncalling** [comment]
I believe the object specific commands have been added to the Getting Started, so this has been addressed in the tutorial at least. 

Removing my name as assignee here for now,  but leaving the issue open in case folks want to go through the rest of the docs.

**Comment by gbarr01** [comment]
@johndmulhausen , do you have thoughts about this discrepancy? https://kubernetes.io/docs/user-guide/docker-cli-to-kubectl/#docker-ps
