### ISSUE TITLE
404 at /edge//engine/userguide/networking/get-started-macvlan/

### ISSUE THREAD

**Issue by sharif786** [docker/docker.github.io#3039]
URL: /edge//engine/userguide/networking/get-started-macvlan/

**Comment by jaredestroud** [comment]
Is [this](https://docs.docker.com/engine/userguide/networking/get-started-macvlan/) the link you're looking for?


Also, can you provide a link to where this is broken so I can fix it? Thanks!

**Comment by mstanleyjones** [comment]
I can't find the location of the bad link, so I can only assume that maybe it's been fixed. If you come across it again, please note down the page where you were when you clicked it. Thanks!
