### ISSUE TITLE
No link content

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#3050]
File: [datacenter/ucp/2.1/guides/user/services/index.md](https://docs.docker.com/datacenter/ucp/2.1/guides/user/services/), CC @joaofnfernandes

The link in the following sentence points to no content:

> You can read the pre-release documentation for Compose V3 on Docker’s preview URL for the upcoming Compose documentation.

This also occurs on page "Deploy an app from the CLI".

**Comment by johndmulhausen** [comment]
Thanks for the bug report, @scjane :)
