### ISSUE TITLE
failed to register layer: Error processing tar file(exit status 1): write file: no space left on device

### ISSUE THREAD

**Issue by gbenmansour** [docker/docker.github.io#3052]
### Problem description
I'm using docker on windows 7 via docker toolbox , when trying to pull a big image of 4 Go I get the following error :
latest: Pulling from preintv2
50655cf8037a: Extracting [==================================================>] 4.055 GB/4.055 GB
failed to register layer: Error processing tar file(exit status 1): write write /opt/oracle/oradata/PREINTV2/ORCLPDB1/system01.dbf : no space left on device

What I find unusual is that when I type df -h :

$ df -h
Filesystem Size Used Avail Use% Mounted on
C:/Program Files/Git 239G 187G 52G 79% /
U: 3,0T 2,5T 494G 84% /u
V: 20G 8,4G 11G 44% /v
X: 14G 2,2G 11G 17% /x
Z: 16G 37K 16G 1% /z

in the partition /u the size is 3.0T I don't know from where it comes , in my windows C:/ partition it remains only 80Go .

### Project version(s) affected
$ docker version
time="2017-04-25T15:39:42+02:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ docker info
time="2017-04-25T15:22:02+02:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 2
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.59-boot2docker
Operating System: Boot2Docker 17.04.0-ce (TCL 7.2); HEAD : c69677f - Thu Apr  6 16:26:16 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: CYXK:K7TN:O3OZ:SVML:FCLM:PLSB:SL4P:2ZF4:7VF2:H6UM:W2YI:FIW6
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 26
 System Time: 2017-04-25T13:22:02.240737949Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by mstanleyjones** [comment]
Sorry for not getting to this sooner, but this is not a Docker documentation issue. Please contact Docker support if you have an entitlement, or ask your question on the Docker community soack or forums.docker.com. Thanks!
