### ISSUE TITLE
GO SDK is probably no longer valid

### ISSUE THREAD

**Issue by Jaxxed** [docker/docker.github.io#3053]
File: [engine/api/sdks.md](https://docs.docker.com/engine/api/sdks/), CC @mstanleyjones

Now that the docker org has gone an rewired the docker/docker repository so that it points to moby/mody, you should probably go and explain to all of the go app developers how their long standing go sdk is no longer going to be available.

Do you think that maybe it would make sense to make a docker/client repo yet?

BTW, this is stupid.

**Comment by shykes** [comment]
Yes we are going to make sure the Docker SDKs remain available in a separate repo and make sure it's a smooth transition.

**Comment by vdemeester** [comment]
@Jaxxed I'm not sure I get "explain to all of the go app developers how their long standing go sdk is no longer going to be available." though 😅 

As long as `client` package is present in the `moby/moby` repository and `moby/moby` imports are still using `docker/docker`, importing `github.com/docker/docker/client` still works as it did before (thanks to github redirection on the repository move).

**Comment by mstanleyjones** [comment]
Thanks for your feedback, @Jaxxed! Please feel free to open an issue in `moby/moby` if you have more concerns about the client SDKs.
