### ISSUE TITLE
Delete Notary Repo Trust Data when deleting a DTR Repo

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3055]
@yongshin commented

### What's the problem/feature request?

When deleting a repo in DTR you'll have to also delete the notary config for that repo using the notary client (in this docker-node-app is the deleted repo): 

```
notary -s https://172.28.128.4 delete 172.28.128.4/engineering/docker-node-app --remote --debug 
```

### Who is asking for this?

Just me so far trying to use notary in CI/CD workflow and ran into this usability issue. 

### What is the (customer) Impact of this request or severity of the issue?

After deleting a repository the customer will be confused about Content Trust thinking that they should need to initialize the repo again using notary when in fact it contains old content trust data. 

### What versions/components are affected?

DTR 2.2.x

---

@vikstrous commented on Fri Apr 21 2017

Looking at the code, we already do this. Are you talking about client state or DTR state? cc @endophage 

---

@endophage commented on Mon Apr 24 2017

@vikstrous I remember we did something for tag delete, did we actually do this for _repo_ delete?

N.B. a user will still have to delete their local trust cache, that's unavoidable. JS in the browser will probably never have sufficient host access to solve that issue.

---

@yongshin commented on Mon Apr 24 2017

I can test this again, after deleting the repo from DTR, what do I need to do on the client to make sure the repo is deleted? Its been a while... 

---

@endophage commented on Mon Apr 24 2017

`notary -d ~/.docker/trust delete 172.28.128.4/engineering/docker-node-app`

That will only delete local cache. Adding the `--remote` and `-s <server url>` flags will allow you to also delete the remote data, but that's the bit DTR should be doing on its own.

---

@yongshin commented on Mon Apr 24 2017

Ok so it worked, this was just about the client state. So I guess this is just a doc issue then? We'll need to document this somehow since I'm sure many people will run into this scenario?

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #451](https://github.com/docker/docs-private/issues/451) via [**ZenHub**](https://www.zenhub.com/)
