### ISSUE TITLE
Feedback for: engine/userguide/storagedriver/selectadriver.md

### ISSUE THREAD

**Issue by gregarndt** [docker/docker.github.io#306]
URL: [https://docs.docker.com/engine/userguide/storagedriver/selectadriver.md](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/)

Documentation refers to specifying the storage driver in /etc/default/docker but on ubuntu > 16.04 this is no longer handled by upstart but rather systemd so this must be specified elsewhere.

**Comment by preston** [comment]
@gregarndt does this imply that you're running on 16.10? This is OT, but curious if you have any solid instructions for doing that upgrade safely.

**Comment by mstanleyjones** [comment]
Please take a look at the referenced PR and provide feedback there. Thanks!
