### ISSUE TITLE
Instructions do not yet work for zesty

### ISSUE THREAD

**Issue by friedlotto** [docker/docker.github.io#3064]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/), CC @mstanleyjones

I have confirmed that the previous three versions are supported:

https://download.docker.com/linux/ubuntu/dists/

...and I suspect that the zesty folders will be uploaded soon. Perhaps just add a note/warning before the section using $(lsb_release -cs).

**Comment by mstanleyjones** [comment]
It's coming with the release of 17.05. Sit tight for a little longer.

**Comment by BenjamenMeyer** [comment]
So that's End of May 2017....
