### ISSUE TITLE
Cloudstor plugin doesn't have support for azure Germany

### ISSUE THREAD

**Issue by vidrascup** [docker/docker.github.io#3068]
### Problem description

Installed plugin on single docker host , but when connecting to azure de storage with it i have the following:

Apr 25 23:05:43 dockerd[39114]: time="2017-04-25T23:05:43Z" level=info msg="time=\"2017-04-25T23:05:43Z\" level=error msg=\"could not fetch metadata: cannot read metadata: open /etc/docker/plugins/cloudstor/volumes/temp_data_vol: no such file or directory\" name=\"temp_data_vol\" operation=get " plugin=e0a3e4db0938408ae80ba238aaa885358a99889b0c0f9a578f90513db44e7b51
Apr 25 23:05:43 dockerd[39114]: time="2017-04-25T23:05:43Z" level=info msg="time=\"2017-04-25T23:05:43Z\" level=error msg=\"could not fetch metadata: cannot read metadata: open /etc/docker/plugins/cloudstor/volumes/temp_data_vol: no such file or directory\" name=\"temp_data_vol\" operation=get " plugin=e0a3e4db0938408ae80ba238aaa885358a99889b0c0f9a578f90513db44e7b51
Apr 25 23:05:43 dockerd[39114]: time="2017-04-25T23:05:43Z" level=info msg="time=\"2017-04-25T23:05:43Z\" level=error msg=\"error creating azure file share: Put https://[*storagename*].file.core.windows.net/1c466a15e915e2c848ef98408c92ab79?restype=share: dial tcp: lookup [*storagename*].file.core.windows.net on 168.63.129.16:53: no such host\" name=\"temp_data_vol\" operation=create options=map[] " plugin=e0a3e4db0938408ae80ba238aaa885358a99889b0c0f9a578f90513db44e7b51

the plugin is trying to connect to azure .file.core.windows.net  but we need support for .file.core.cloudapi.de, also generate certificates for this domain in azure.

**Comment by johndmulhausen** [comment]
@ddebroy Can you advise on this? 

https://docs.docker.com/docker-for-azure/persistent-data-volumes/
https://docs.docker.com/docker-for-aws/persistent-data-volumes/

**Comment by ddebroy** [comment]
There is a `AZURE_STORAGE_ENDPOINT` installation parameter for `cloudstor` that you can configure to point to the storage endpoints for Azure Germany:

```
docker plugin install --alias cloudstor:azure --grant-all-permissions docker4x/cloudstor:17.06.1-ce-azure1  \
        CLOUD_PLATFORM=AZURE \
        AZURE_STORAGE_ACCOUNT_KEY="$SA_KEY" \
        AZURE_STORAGE_ACCOUNT="$SWARM_INFO_STORAGE_ACCOUNT" \
        AZURE_STORAGE_ENDPOINT="**core.cloudapi.de**" \
        DEBUG=1
```

**Comment by eperov** [comment]
Installing the plugin with ENDPOINT parameter for default endpoint "file.core.windows.net" fails, without the parameter it works:
Using parameter:
root@es000000:/run/docker/plugins# docker plugin install --alias cloudstor:azure \
>   --grant-all-permissions docker4x/cloudstor:17.09.1-ce-azure1  \
>   CLOUD_PLATFORM=AZURE \
>   AZURE_STORAGE_ACCOUNT_KEY="xxxxxxxxxxxxxx==" \
>   AZURE_STORAGE_ACCOUNT="zzzzzzzzzzzzz" \
>   AZURE_STORAGE_ENDPOINT="file.core.windows.net" \
>   DEBUG=1
17.09.1-ce-azure1: Pulling from docker4x/cloudstor
44e99d3a5781: Download complete
Digest: sha256:8f6f733998648695824aaacb75f7ee5812d8372e29fb75f6196135be4f38af04
Status: Downloaded newer image for docker4x/cloudstor:17.09.1-ce-azure1
Error response from daemon: dial unix /run/docker/plugins/c1dd94bb99d65923f5ea8b49d76c097af3a1b930c761f42644411a3a2705a70e/cloudstor.sock: connect: no such file or directory
root@es000000:/run/docker/plugins# docker plugin ls
ID                  NAME                DESCRIPTION                       ENABLED
c1dd94bb99d6        cloudstor:azure     cloud storage plugin for Docker   false
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
No parameter
root@es000000:/run/docker/plugins# docker plugin install --alias cloudstor:azure \
>   --grant-all-permissions docker4x/cloudstor:17.09.1-ce-azure1  \
>   CLOUD_PLATFORM=AZURE \
>   AZURE_STORAGE_ACCOUNT_KEY="xxxxxxxxxxx==" \
>   AZURE_STORAGE_ACCOUNT="zzzzzzzzzzzz" \
>   DEBUG=1
root@es000000:/run/docker/plugins# docker plugin ls
ID                  NAME                DESCRIPTION                       ENABLED
d6bdaa26f170        cloudstor:azure     cloud storage plugin for Docker   true

**Comment by mistyhacks** [comment]
This is not a docs issue but a feature request. @friism @ddebroy what is the appropriate repo for the user to file this issue?
