### ISSUE TITLE
Compose installation in the Engine installation for Debian: confusing

### ISSUE THREAD

**Issue by jcberthon** [docker/docker.github.io#3077]
### Problem description

For Debian installation, there is now a subsectino regarding installing `compose` from a 3rd party repository by running a script from that 3rd party. I've checked the script it is not maligned.

But I'm surprised for 2 reasons:

1. This is the installation instructions of Docker Engine, not Docker Compose. So these instructions are misplaced IMHO; and
2. For the convenience script for Docker Engine (1st party) there is a warning about running unknown scripts. But for that 3rd party script there are no warnings. In addition, the few steps of the script (if you remove all echos and the OS detection which are not necessary when done manually) could simply be described/documented instead of putting the user at risk to run an unknown script.

### Problem location

I saw a problem on the following URL: engine/installation/linux/debian.md commit 570b4458b41ef2cfe9a0dbf7b17b7b6a91f07dcf

### Project version(s) affected

Not applicable

### Suggestions for a fix

I would suggest to remove the installation instruction for Docker Compose. Or to move them to the Docker Compose installation instruction.

**Comment by joaofnfernandes** [comment]
@mstanleyjones what's the rationale for documenting how to install compose in the middle on an engine installation article?
https://docs.docker.com/engine/installation/linux/docker-ce/debian/#optional-install-docker-compose-for-raspbian

Does it make sense to remove that, given that we don't do it for any other distro?

**Comment by mstanleyjones** [comment]
It's because we don't distribute binaries for Compose on ARM, so that's the only way for them to get the binary only. Other distros don't have a special sub-distro like Debian / Raspbian.

**Comment by jcberthon** [comment]
I also think it is OK to keep it because of the relation between Debian and Raspbian, and the fact that no binaries are distributed for ARM as you mentioned.

But my second point regarding the convenience script is still valid. And it is very very confusing. The installation steps for the compose script recommend to use a convenience script to be downloaded and executed directly, with no warning to the user on the risks.  
In the [next chapter](https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script) it is made very clear of the risk of downloading files from internet, and the steps are even splitted , first download (with a change to review the script) and then execute it.

*Note: by the way, the statement in this chapter contradicts the first note in [chapter on Raspbian installation](https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-on-raspbian-raspberry-pi) which says that the convenience script is the recommended way, and it even pipes the download to the shell, so hard to review. As I understand it, this is contradictory/confusing.*

I can propose a PR, with the following changes:
* clarify why there is a section on installing compose here
* clarify and make coherent when a convenience script is used to install a software (so adding a warning)

Question for both of you @mstanleyjones and @joaofnfernandes, what is really the best recommendable way to install docker-compose on ARM? Shall we document the use of this convenience script (with warnings) or shall I suggest using pypi (`pip install ...) because there seems to be an official package from Docker there: https://pypi.python.org/pypi/docker-compose/1.15.0

**Comment by mstanleyjones** [comment]
It's not a "convenience script" for Docker Compose. It's not an installation script at all. It's actually a _binary_. We also provide Docker Engine  binaries. The "convenience script" for Docker Engine actually sets up repositories, downloads bits, extracts them, and installs them. The binary for Docker Compose connects to the Docker API and runs the commands defined in your `docker-compose.yml`. You can examine the Docker Compose binary script straight on Github. I suppose the binary could be compromised on Github, but that's pretty surprising if so. You're also not running the `docker-compose` binary as `root`.

**Comment by jcberthon** [comment]
Hi @mstanleyjones 

I have been unclear it seems. Maybe to better understand were I come from, I've been a software engineer (and now more project manager) since 1999, I've compiled my first kernel in 1997? I've contributed to the moby/moby project and docker/compose one to provide better support for ARMv7, I've also contributed to the raspberrypi/kernel in order to provide better support for some of Docker functionalities. My contributions were not big, so I'm not trying to impress, I just want to show that I understand the difference between a script and a binary, and that I know how to fix things so they work on platforms were they are some technologies are still "preview".

My comment will be long, I apologise, but I want it to be precise. I want first to come to your response, and then I will try to explain one more time what I wanted to illustrate.

### My response to you

> It's not a "convenience script" for Docker Compose. It's not an installation script at all. It's actually a binary.

I was referring to the installation of Docker Compose on Raspbian as it is define within the document about the installation of Docker-CE on Debian, specifically, I'm referring to the chapter `Install Docker Compose for Raspbian` (see this link https://github.com/docker/docker.github.io/blob/8fef0de5d1764637a41c4a1935de5a24ab3d09b0/engine/installation/linux/docker-ce/debian.md#optional-install-docker-compose-for-raspbian), and referring to this "convenience script" (not my words, but it seems from reading the document that scripts which performs installation and are downloaded with `curl` and run with `sh` are called elsewhere in this document "convenience script"):

`curl -s https://packagecloud.io/install/repositories/Hypriot/Schatzkiste/script.deb.sh | sudo bash`

The file `script.deb.sh` is a bash script (`head -1 script.deb.sh` prints out `#!/bin/bash`). It is downloaded from a site called `packagecloud.io` so not `docker.com`. The text says it is from the Hypriot group, which I known in an "online" way, and I trust them and I think they do great things! But here, as a **security conscious person** I do not know (so trust) this packagecloud.io site, I do not know how the GitHub repository from the Hypriot team ends up on this site, so my chain of trust is **broken**. Hence my concern with running such scripts, especially when as shown above, the script is directly piped to a shell "sudo-ed", so **that script from an unknown internet site is run as root**. That something we should not teach users to do.

> The "convenience script" for Docker Engine actually sets up repositories, downloads bits, extracts them, and installs them. The binary for Docker Compose connects to the Docker API and runs the commands defined in your docker-compose.yml. You can examine the Docker Compose binary script straight on Github. I suppose the binary could be compromised on Github, but that's pretty surprising if so. You're also not running the docker-compose binary as root.

I agree, and I know that because the first time I wanted to install Docker I was already offered the 2 choices of installing it via the convenience script or via a repository. I even reviewed at that time the script in order to see what it would do to my system. In the end I preferred the repository approach, with signed GPG keys, over downloading a script from a `https` site, I would say in terms of security both are equivalent, I need to put my trust in Docker that the signed `.deb` (and all other packages in the repository) are safe, coming from the GitHub source code, same for the convenience script. And I trusted it, no problem :smile:. I do trust GitHub, and Docker. I also know how `docker-compose` work, I've checked some of its code and provided small contributions to it even.

### Where the documentation could need improvement

#### 1st point: the docker-compose installation for Raspbian is problematic
As I pointed to you above, the optional installation steps for docker-compose on Raspbian is problematic, because there is clearly here a problem of trust. Even if one trust GitHub, Docker and the Hypriot group, the script is hosted on a 3rd party site. That chain of trust is particularly long, and it is completely opaque where this script comes from exactly. Actually the installation step on the Hypriot repository are in my opinion much better, see here https://github.com/hypriot/arm-compose#add-repo, and hereafter an extract:

```
sudo apt-get update
sudo apt-get install -y apt-transport-https
echo "deb https://packagecloud.io/Hypriot/Schatzkiste/debian/ jessie main" | sudo tee /etc/apt/sources.list.d/hypriot.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 37BBEE3F7AD95B3F
```
Here they gave you a mean (the gpg key) to verify that what is on this packagecloud.io comes really from them. And this is visible from a GitHub page provided over https. So it is good enough for me to trust that.

If we come back to the installation of Docker CE (so not talking here of the docker-compose optional installation), in the chapter "Install using the convenience script" (see https://github.com/docker/docker.github.io/blob/a922be3d0fb62e3ebd95ecfa9a9d25f835a4dd8e/_includes/install-script.md#install-using-the-convenience-script), there we can see a warning (even if the script is downloaded from Docker, and here again, this is a shell script named `get-docker.sh` after the download) about running script from internet, it states (rightly so):

> Always examine scripts downloaded from the internet before running them locally

And the steps to run that `get-docker.sh` script are better, they allow a user to review it (if he has knowledge of it).

```
$ curl -fsSL get.docker.com -o get-docker.sh
$ sudo sh get-docker.sh
```

It could still be improved, because this is first going to use `http` (so no TLS), it is then redirected to `https`, so someone could intercept that first http call and perform a man in the middle attack (MITM). See here the output of curl:

```
$ curl --verbose -L get.docker.com -o get-docker.sh
* Rebuilt URL to: get.docker.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.222.171.178...
* Connected to get.docker.com (52.222.171.178) port 80 (#0)
> GET / HTTP/1.1
> Host: get.docker.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: CloudFront
< Date: Wed, 30 Aug 2017 21:09:34 GMT
< Content-Type: text/html
< Content-Length: 183
< Connection: keep-alive
< Location: https://get.docker.com/
< X-Cache: Redirect from cloudfront
```

A **much better instruction** would be to directly give the `https` link:
```
$ curl -fsSL https://get.docker.com -o get-docker.sh
$ sudo sh get-docker.sh
```
It's longer to type (but who's not copy/pasting that anyway :wink:) but it is faster, you get to directly establish the HTTPS connection (not losing a TCP handshake and HTTP get to be informed the page has moved) and it is much harder to MITM this!

#### 2nd point: contradictions

At the very beginning of this document, it is stated (see here https://github.com/docker/docker.github.io/blob/8fef0de5d1764637a41c4a1935de5a24ab3d09b0/engine/installation/linux/docker-ce/debian.md#install-docker-ce):

> You can install Docker CE in different ways, depending on your needs:
> * Most users set up Docker's repositories and install from them, for ease of installation and upgrade tasks. This is the recommended approach.
> * Some users download the DEB package and install it manually and manage upgrades completely manually. This is useful in situations such as installing Docker on air-gapped systems with no access to the internet.
> * In testing and development environments, some users choose to use automated convenience scripts to install Docker.

Here we can see that using the apt repository is the recommended approach. And we are told that for **testing** and **development** environments **some** users choose the convenience script. It makes sense. And it's a statement. The problem is that in another chapter, but this time for Raspbian, there is a contradiction statement.

Here in the chapter on installing Docker CE on Raspbian (see https://github.com/docker/docker.github.io/blob/8fef0de5d1764637a41c4a1935de5a24ab3d09b0/engine/installation/linux/docker-ce/debian.md#install-on-raspbian-raspberry-pi), it is stated:

> Note: This isn't necessary if you used the recommended `$ curl -sSL https://get.docker.com | sh` command.

*(by the way, here is correctly uses the `https` URL notation to retrieve the get-docker.sh script, **but** it directly pipes the result in a `sh`, as I think I made clear above, this is not good security practice (btw they forgot the `sudo` statement before the `sh`, I think it is not necessary as the script will itself ask for elevated privileges, but it is not consistent with other part of the documentation))*

So on Debian, the apt repository are the recommended way, but for Raspbian they are not and it is the `curl (...) | sh` which becomes recommended. That is in my opinion contradictory.

### Conclusion

I now hope that I have been clearer. Please bare in mind that I'm not a noob when replying to me. So when you think I misunderstood something, maybe it is because I misexplained what I wanted to highlight, so please try to read a second time my statement to see if you could not interpret it in a different way. Second I'm sorry for my broken English, I'm not a native speaker. This could have added some confusion on top of me being not clear enough.

I really do hope to improve the Debian installation configuration. I think I can really help here. Let me know.

**Comment by mstanleyjones** [comment]
I see what you mean now about the shell script to add the Hypriot repository. I'll modify the doc not to go into details about how to set up the Hypriot repo, but to use the info at https://blog.hypriot.com/post/your-number-one-source-for-docker-on-arm/. Thanks.
