### ISSUE TITLE
Looking for information on stack files for Swarm? link does not work

### ISSUE THREAD

**Issue by caylorme** [docker/docker.github.io#3079]
File: [docker-cloud/apps/stacks.md](https://docs.docker.com/docker-cloud/apps/stacks/), CC @londoncalling

"Looking for information on stack files for Swarm?" this link no longer works.

**Comment by londoncalling** [comment]
@caylorme I can't find any broken links in the file you referenced ^^ https://docs.docker.com/docker-cloud/apps/stacks/. If you have links related to the old Getting Started voting app tutorial, that has been replaced by this tutorial: https://docs.docker.com/get-started/

Swarm documentation is here: https://docs.docker.com/engine/swarm/

Does this help?

**Comment by caylorme** [comment]
Hey @londoncalling, I'm not sure why it automatically added that particular page to the issue, the proper URL (currently live) that was supposed to be referenced is this one:
https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/

Specifically the text "Looking for information on stack files for Swarm?" just above the "Stack file example" header. The link redirects you here: https://docs.docker.com/compose/compose-files/
This page's header is "Sorry, we can't find that page"

Image below:
![image](https://cloud.githubusercontent.com/assets/4383446/25452908/3a67d922-2a95-11e7-82e0-7bcb1a52100d.png)
