### ISSUE TITLE
URL for Docker EE Azure template returns 404

### ISSUE THREAD

**Issue by briantd** [docker/docker.github.io#3086]
File: [docker-for-azure/archive.md](https://docs.docker.com/docker-for-azure/archive/), CC @johndmulhausen 

The link provided for 17.03.0 works, but not the one for 17.03.1.

See:
<img width="770" alt="screenshot of safari 4-26-17 12-59-18 pm" src="https://cloud.githubusercontent.com/assets/94055/25454166/64325012-2a80-11e7-8b31-6e22b8d9f8e1.png">

**Comment by johndmulhausen** [comment]
https://download.docker.com/azure/stable/17.03.1/Docker.tmpl works for me. Sorry.

**Comment by briantd** [comment]
@johndmulhausen -- Could you try the EE version?
If you go to this page: https://docs.docker.com/docker-for-azure/archive/
and use the URL for the EE version:
https://download.docker.com/azure/17.03/17.03.1/Docker.tmpl

See:
<img width="616" alt="screenshot_of_safari" src="https://cloud.githubusercontent.com/assets/94055/25591907/57435fec-2e6b-11e7-9a8e-006f74c6bc25.png">

**Comment by mstanleyjones** [comment]
@FrenchBen @kencochrane @ddebroy PTAL

**Comment by joaofnfernandes** [comment]
@FrenchBen I'm sure we have a release checklist for the cloud editions. Do we have a task to update [this docs page](https://docs.docker.com/docker-for-azure/archive/) on every release?
Looking at the [EE release notes](https://docs.docker.com/enterprise/17.03/release-notes/), I think the docs page is a bit outdated.
