### ISSUE TITLE
Correct the "Edit this page" link

### ISSUE THREAD

**Issue by rogaha** [docker/docker.github.io#3096]
File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/), CC @mstanleyjones 

Currently it takes you to: https://docs.docker.com/engine/extend
It should take you to `editable` page: https://docs.docker.com/engine/extend/legacy_plugins.md

**Comment by johndmulhausen** [comment]
It takes you to https://github.com/moby/moby/tree/17.03.x/docs/extend which is correct.

**Comment by rogaha** [comment]
@johndmulhausen would you mind explaining me why that is correct? If I want to contribute to the  current page `engine/extend/legacy_plugins.md` and I click on `edit` page it takes me to the parent `directory`. Why is that correct? The users will be lost once they get there.
