### ISSUE TITLE
Missing [] array brackets on hosts attribute example ?

### ISSUE THREAD

**Issue by migmurillo** [docker/docker.github.io#3098]
Hello, 
In Administration Guide, there is apparently a mistake at less using Docker-ce version.

"hosts": "tcp://192.168.59.3:2376"

Must be with an array []
"hosts": ["tcp://192.168.59.3:2376"]
 
"A better approach is to put these options into the daemon.json file and restart Docker. This method works for every Docker platform. The following daemon.json example sets all the same options as the above command:

{
  "debug": true,
  "tls": true,
  "tlscert": "/var/docker/server.pem",
  "tlskey": "/var/docker/serverkey.pem",
  **"hosts": "tcp://192.168.59.3:2376"**
}"

https://docs.docker.com/engine/admin/#configure-the-docker-daemon

Is it correct?

Best Regards?

**Comment by joaofnfernandes** [comment]
Fixes via #3410
