### ISSUE TITLE
when describing a "default" command, it would be nice to know what the default command is

### ISSUE THREAD

**Issue by brianbolt** [docker/docker.github.io#3103]
File: [docker-cloud/builds/advanced.md](https://docs.docker.com/docker-cloud/builds/advanced/), CC @londoncalling

The documenation says:

> Caution: A hooks/build file overrides the basic docker build command used by the builder, so you must include a similar build command in the hook or the automated build will fail.

But I have no idea what command the builder uses by default so it's hard to know what a similar command would look like

**Comment by londoncalling** [comment]
Hi @brianbolt, Thanks for your feedback. There actually is a link to the `docker build` command topics on setting variables just below the Caution note ("To learn more about Docker build-time variables, see the [docker build documentation](https://docs.docker.com/engine/reference/commandline/build/)."

But I've added another link to it inline on the Caution note, to surface it a little more.
