### ISSUE TITLE
Examples in a Dockerfile

### ISSUE THREAD

**Issue by jiminikiz** [docker/docker.github.io#3105]
File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/), CC @mstanleyjones The documentation mentions that you can add a Volume via dockerfile, but there is no example OR link to this within the documentation for `dockervolumes`.

**Comment by joaofnfernandes** [comment]
The docs about volumes have changed a lot since this issue was filed. @jiminikiz I'm going to close this issue since I expect things to be clearer now, but if that's not the case, feel free to comment.
