### ISSUE TITLE
Duplicate items in contents

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#3112]
File: [datacenter/dtr/2.2/guides/admin/manage-users/index.md](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/manage-users/), CC @joaofnfernandes

In the left navigation, this page is labeled as "Create and manage users", which is the same as the next page. 
![contents](https://cloud.githubusercontent.com/assets/25146885/25511639/86e86666-2bfa-11e7-86b9-df493054a0e0.jpg)

**Comment by bdwill** [comment]
Title in the document is correct ("Authentication and authorization in DTR") but navbar displays "Create and manage users" which I can't find in the document.
