### ISSUE TITLE
Broken Link on "Docker Cloud stack file YAML reference" page

### ISSUE THREAD

**Issue by caylorme** [docker/docker.github.io#3116]
File: [docker-cloud/apps/stack-yaml-reference.md](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/), CC @londoncalling

On this Live page: https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/

The link "Looking for information on stack files for Swarm?." points to a page with the header "Sorry, we can't find that page"

**Comment by londoncalling** [comment]
@caylorme this is being addressed in PR #3104 (you are cc'ed as a reviewer) per the other issue you filed, #3079. I'm about to merge that PR, since I've gotten no comments from reviewers.
