### ISSUE TITLE
Update Rails sample to use secrets

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3118]
Rails 5.1 supports encrypted secrets, so we can update https://docs.docker.com/compose/rails/
to leverage secrets

**Comment by johndmulhausen** [comment]
We do tell people to put clear passwords in the compose file right now. :/

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
