### ISSUE TITLE
Amazon role creation wizard change

### ISSUE THREAD

**Issue by dbackeus** [docker/docker.github.io#3127]
File: [docker-cloud/cloud-swarm/link-aws-swarm.md](https://docs.docker.com/docker-cloud/cloud-swarm/link-aws-swarm/), CC @londoncalling

According to docs the first step when creating a role is to give it a name. However that has been moved to the last (4th) step in the wizard which would correspond to around bullet point 8 in your documentation.

**Comment by londoncalling** [comment]
@dbackeus thanks! please review the PR linked above ^^
