### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntulinux.md

### ISSUE THREAD

**Issue by jacek-** [docker/docker.github.io#313]
URL: [https://docs.docker.com/engine/installation/linux/ubuntulinux.md](https://docs.docker.com/engine/installation/linux/ubuntulinux/)

The command in step Prerequisites/Update your apt sources/6 returns "Permission denied" as the /etc/apt/sources.list.d/ is usually only root writable. It should be corrected to something like this:

`sudo sh -c 'echo "<REPO>" > /etc/apt/sources.list.d/docker.list'`

which runs redirection under root and allows writing to the apt sources directory.

**Comment by konstruktoid** [comment]
I believe this was fixed in #283  @jacek-

**Comment by jacek-** [comment]
Ok, thanks!
