### ISSUE TITLE
Missing a last confirmation of successful deploy

### ISSUE THREAD

**Issue by dbackeus** [docker/docker.github.io#3130]
File: [get-started/part6.md](https://docs.docker.com/get-started/part6/), CC @johndmulhausen 

So I managed to go through all the steps to get my docker swarm initialized on EC2, prepare the DOCKER_HOST etc and successfully run `docker stack deploy -c docker-compose.yml getstartedlab`

Then the tutorial stops with: **Congratulations!**

However I still haven't seen the example app running in the cloud and there are no pointers in the tutorial on how I might be able to do that.

I went to the EC2 management console and tried loading up the public DNS urls in my browser of various nodes but all of them just time out after a while. When I run `docker ps` in my terminal everything looks like it's working:

```
$ docker ps
CONTAINER ID        IMAGE                                                                                              COMMAND                  CREATED             STATUS              PORTS                         NAMES
467f4cb64d51        dbackeus/repository@sha256:9af208bbf0200e94dc918d75cfd73755f2462fbe5ee2e84309dfe19b68458453        "python app.py"          13 minutes ago      Up 13 minutes       80/tcp                        getstartedlab_web.2.in5gjinuz1hxt6aodzfsngqx4
43d33b805a70        dbackeus/repository@sha256:9af208bbf0200e94dc918d75cfd73755f2462fbe5ee2e84309dfe19b68458453        "python app.py"          13 minutes ago      Up 13 minutes       80/tcp                        getstartedlab_web.5.tu7nmtd4y91lmdgatm8wpa2l9
2847fc23712a        dockercloud/server-proxy@sha256:eecacae35738c24f9f565e506ee85ae1352530f773c691f5315758944e813edd   "/server-proxy"          15 minutes ago      Up 15 minutes       2376/tcp                      dockercloud-server-proxy.brcoemkts9xb9lwlnezz2u1md.xe6nic1zmbki40ldhdo17685s
35a7041dfaeb        docker4x/l4controller-aws:aws-v17.03.1-ce-aws1                                                     "loadbalancer run ..."   16 minutes ago      Up 16 minutes                                     l4controller-aws
76f73b758f61        docker4x/meta-aws:aws-v17.03.1-ce-aws1                                                             "metaserver -iaas_..."   17 minutes ago      Up 17 minutes       172.31.9.201:9024->8080/tcp   meta-aws
0c028c26fce9        docker4x/shell-aws:aws-v17.03.1-ce-aws1                                                            "/entry.sh /usr/sb..."   17 minutes ago      Up 17 minutes       0.0.0.0:22->22/tcp            shell-aws
8dca420cb53b        docker4x/guide-aws:aws-v17.03.1-ce-aws1                                                            "/entry.sh"              17 minutes ago      Up 17 minutes                                     guide-aws
```

Now I suppose I could spend some time debugging what's going on and figure out what I need to do to actually see the app running in my browser but I feel like this step needs to be included in the tutorial to not leave people hanging. Especially those who are fairly new to both docker and cloud computing in general.

ps. Thanks for an amazingly well written tutorial overall, was really impressed in general with everything I saw trying docker for the first time 👍

**Comment by johndmulhausen** [comment]
@dbackeus Thanks for the kind words on the tutorial, that means a lot to me. :) 

I think all you should need to do is open up the ports on your AWS instance. We're still working on adding functionality to allow port publishing from within Docker Cloud for swarms. For now, you can follow this guide. I'll take it on that we need to add this information to Getting Started.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html

**Comment by dbackeus** [comment]
Thanks for looking into it 👍 

While going through the tutorial I was actually thinking it was one of the best textual getting started experiences I had ever had. So take it to heart 💓

**Comment by mstanleyjones** [comment]
@gbarr01 can you please add a note that if theya re using EC2 or another cloud provider, they should look on their cloud provider docs for how to open the correct access?
