### ISSUE TITLE
Connection problem when build command try to run pip install

### ISSUE THREAD

**Issue by egomezsumma** [docker/docker.github.io#3131]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen 
I follow several 'solutions' (that involve the dns specification) from stackoverflow (http://stackoverflow.com/questions/28668180/cant-install-pip-packages-inside-a-docker-container-with-ubuntu) but nothing work. I already have images/containers docker that i use from my work. But i can't do a conteiner for my personal use following this tutorial. I've already try changing Flask for Django also, but the same error ocurr. 

I use linux mint 18 cinnamon 64-bit (kernel: 4.4.0-75 generic)

Thanks in advance

![docker_tuto_problem](https://cloud.githubusercontent.com/assets/6002234/25583972/7ac709c4-2e6a-11e7-9aa6-ad94e499257f.png)

**Comment by joaofnfernandes** [comment]
@egomezsumma I've seen others report the same problem, but I can't reproduce.
Is it possible that you don't have internet connection, or are behind a proxy?
If you're behind a proxy, check if #3570 solves your problem.

**Comment by egomezsumma** [comment]
hi @joaofnfernandes I "solved" adding the following line on each statement of the Dockerfile:
`echo ‘nameserver 8.8.8.8’ >> /etc/resolve.conf && echo ‘nameserver 8.8.4.4’ >> /etc/resolve.conf’ && <command>`

It must be a best way, but it was fast for me to go ahead.
Thanks for writing

Best regards!

pd: sorry by my english
