### ISSUE TITLE
Please remove comment about graphdriver, overlayFS, & btrfs

### ISSUE THREAD

**Issue by powersplay** [docker/docker.github.io#3137]
File: [engine/installation/linux/oracle.md](https://docs.docker.com/engine/installation/linux/oracle/), CC @mstanleyjones 

OracleLinux should have the same restrictions as CentOS, Fedora, & RHel.   The statement:  "The device-mapper graph driver is supported. OverlayFS and Brtfs are not supported" is probably a typo.

**Comment by mstanleyjones** [comment]
It's not a typo. See the support matrix. I have info about this that I didn't have a chance to address before my surgery. I'll be back in a week and a half or you can talk to @dmp42 and @friism about it.

**Comment by friism** [comment]
This is the correct thing: https://success.docker.com/Policies/Compatibility_Matrix

**Comment by powersplay** [comment]
Thanks Misty.  I spoke with @dmp42 & @friism before filing the issue.  I'll take it up with them again.  Hope you get well soon.

**Comment by mstanleyjones** [comment]
@powersplay can this be closed?

**Comment by joaofnfernandes** [comment]
I'm going to close this one since we've had a lot of back and forward on this, and the documentation was updated too.
This can be used as the source of truth for what is supported https://success.docker.com/Policies/Compatibility_Matrix
