### ISSUE TITLE
How to recover UCP/DTR if replica goes down

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#3138]
File: [datacenter/dtr/2.2/guides/admin/backups-and-disaster-recovery.md](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/backups-and-disaster-recovery/), CC @joaofnfernandes 

There are no instructions for how to remove a failed replica.  Here is an example

```
docker run -it --rm docker/dtr:2.2.4 remove --replica-id fdc4ee12bb84 --existing-replica-id ed46a108546c --ucp-insecure-tls
```

Where `--replica-id` is a failed replica and `--existing-replica-id` is a healthy replica.

**Comment by joaofnfernandes** [comment]
DTR now has the `destroy` command, so things should be a bit more obvious now. Let me know if this is still an issue.

**Comment by mbentley** [comment]
The `destroy` command isn't for removing a failed replica though.  I'd like to see it documented how you would handle the loss of a single replica of DTR to restore it back to a fault tolerant state.  The docs only talk about a full restore from scratch when that is not necessary for a loss of a single replica: https://docs.docker.com/datacenter/dtr/2.3/guides/admin/backups-and-disaster-recovery/

**Comment by joaofnfernandes** [comment]
Let me reopen this issue and change the title to reflect that.

**Comment by mbentley** [comment]
https://github.com/docker/docker.github.io/issues/3684 was a duplicate of this; forgot I already had the same issue already open but for both UCP and DTR.
