### ISSUE TITLE
Add landing pages at a couple places under /datacenter/

### ISSUE THREAD

**Issue by bryceryan-docker** [docker/docker.github.io#3140]
URL: /datacenter/

Suggested improvement to the doc tree for EE products

Given that UCP & DTR docs are at these URLs: https://docs.docker.com/datacenter/ucp/2.1/guides/ and https://docs.docker.com/datacenter/dtr/2.2/guides/ : it would be nice to fill out the intermediate links so they don't return 404s. People somewhat expect the intermediate links on the way to deep links to be populated with data. Clearly someone had some organization in mind when creating the link structure, so "use the force", as they say. 

That is, 

- list all the datacenter products on https://docs.docker.com/datacenter , e.g. UCP and DTR, with links to the lower level "product specific" page
- for each product page, list each of the versions available, e.g. on https://docs.docker.com/datacenter/ucp, list 2.0, 2.1, etc.
- keep the doc trees for older versions
- if there is some other material than "guides" on the level of an individual release, list it on the version page. Otherwise, get rid of the intermediate link to "guides"

**Comment by johndmulhausen** [comment]
We're moving away from /datacenter/ before too long, so let's table this bug.
