### ISSUE TITLE
Create KB article for "unhealthy ucp controller: error docker swarm cluster..."

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3143]
UCP leverages Docker in swarm mode, but also deploys the legacy standalone swarm. So some times users get errors mentioning "Swarm" and they don't realize that those errors have nothing to do with the `1.13` functionality.

<img width="914" alt="screenshot of google chrome 4-14-17 4-20-10 pm" src="https://cloud.githubusercontent.com/assets/4483394/25082886/61927fb4-2308-11e7-82a0-e112cb24967f.png">
<img width="923" alt="screenshot of google chrome 4-14-17 4-22-30 pm" src="https://cloud.githubusercontent.com/assets/4483394/25082888/61931ef6-2308-11e7-99a3-0f4ab9cd364c.png">

Create a KB article explaining what is happening when users get this error, and that they should pay attention to the logs of the `ucp-swarm-manager` container, which is the container running the legacy standalone swarm.

**Comment by JimGalasyn** [comment]
This feedback has been passed along.
