### ISSUE TITLE
A note on docker tag idempotence

### ISSUE THREAD

**Issue by ic** [docker/docker.github.io#3148]
File: [engine/reference/commandline/tag.md](https://docs.docker.com/engine/reference/commandline/tag/), CC @mstanleyjones

I am scripting the `docker tag` command, and seeing a scenario missing from the documentation. If I am correct, the `docker tag` command is "idempotent": Running it more than once returns the same result. Like:

    $ docker tag 13ecf5204bc1 my_image_tag
    $ docker images
    REPOSITORY     TAG                 IMAGE ID            CREATED             SIZE
    original_image   latest              13ecf5204bc1        14 hours ago        5.372 GB
    my_image_tag    latest              13ecf5204bc1        14 hours ago        5.372 GB
    $ docker tag 13ecf5204bc1 my_image_tag
    $ docker images
    REPOSITORY     TAG                 IMAGE ID            CREATED             SIZE
    original_image   latest              13ecf5204bc1        14 hours ago        5.372 GB
    my_image_tag    latest              13ecf5204bc1        14 hours ago        5.372 GB

That is, trying to create `my_image_tag` twice in a row does the job only once. `docker tag` return a `0` code for each run in this scenario, implying it is not bothered by the tag already existing on the second run.

If this is correct, how about a note like this one?

**Comment by joaofnfernandes** [comment]
@ic `docker` creates a new tag and overwrites one if it already exists.
I'm not sure what you're proposing. Are you proposing that:
* The behavior of `docker tag` should be changed and never overwrite an existing tag? And maybe have a flag that allows you to explicitly do that?
* We document that `docker tag` can override an existing tag?
* We document the return code of each operation?

**Comment by ic** [comment]
I am proposing to expand the documentation.

Sorry, I just followed a link to request documentation changes, and it led me to that GitHub issue template. I thought that would set the context to documentation.

**Comment by mstanleyjones** [comment]
@stevvooe can you confirm this behavior?

**Comment by stevvooe** [comment]
While technically accurate, I am not sure what value this provides to the description. I'd have to see a PR with the specific changes.

I do think that documentation needs work, as the description starts off by waxing on about hostnames, which should probably follow some description about what a tag is and how it works.

I'd say submit a PR and see if we can improve!

**Comment by mstanleyjones** [comment]
If you want to tackle the **reference doc** you linked in the original comment, please open an issue in the `docker/cli` repository. Thanks!
