### ISSUE TITLE
Make it clear what user to use when sshing into docker for AWS

### ISSUE THREAD

**Issue by asloan7** [docker/docker.github.io#3151]
File: [docker-for-aws/index.md](https://docs.docker.com/docker-for-aws/), CC @johndmulhausen

what is the username to ssh in to these managers? Thanks!

**Comment by joaofnfernandes** [comment]
From [what I can see here](https://docs.docker.com/docker-for-aws/faqs/#how-do-i-run-administrative-commands), the username seems to be `docker`. Can you try it out and update this issue if it works for you?

**Comment by asloan7** [comment]
Yes, what I actually found was an issue with the ubuntu subsytem in Windows
10 - docker works from elsewhere

**Comment by mstanleyjones** [comment]
We might want to verify this for Azure too. @FrenchBen PTAL

**Comment by FrenchBen** [comment]
@mstanleyjones it's all the same on Azure and well documented on how to connect via SSH:
* AWS - https://docs.docker.com/docker-for-aws/deploy/#connect-via-ssh
* Azure - https://docs.docker.com/docker-for-azure/deploy/#connecting-via-ssh

**Comment by joaofnfernandes** [comment]
So it seems that this has been addressed in the docs, and we can close this one. @asloan7 you've mentioned problems with the Ubuntu subsystems in Windows 10, so feel free to open a new issue if you think there's anything that could be improved in that area.
