### ISSUE TITLE
Kitematic Installation (Windows 10)

### ISSUE THREAD

**Issue by HoloSound** [docker/docker.github.io#3163]
### Problem description

Windows 10 (German)
Installed Oracle VM Virtual Box (latest Version)
after Installation of Kitematic (Alpha)
the Virtual Box gets to an OLD Version !

### Problem location

Installation of Kitematic (Alpha)
installes (its virtualBox version) over an existing newer version of installed Virtual Box!

### Project version(s) affected

Docker Toolbox.exe from 6. April 2017

### Suggestions for a fix

Installation procedure should check if virtual Box already exists on the system.
(Only newer versions should be installed!)

Rem.: Fault was already reported in: Closed #187.

**Comment by joaofnfernandes** [comment]
Since this feedback about the product, I'm moving this to the Kitematic repository.

**Comment by joaofnfernandes** [comment]
Issue moved to [docker/kitematic #2985](https://github.com/docker/kitematic/issues/2985) via [**ZenHub**](https://www.zenhub.com/)
