### ISSUE TITLE
Wordy and unclear definition of Docker run

### ISSUE THREAD

**Issue by jontreynes** [docker/docker.github.io#3167]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/), CC @mstanleyjones

https://docs.docker.com/engine/reference/run/

"then an operator executes docker run, the container process that **runs is isolated in that it has its** own file system, its own networking, and its own isolated process tree separate from the host"

**Comment by mstanleyjones** [comment]
Hi there, these docs actually live in the `docker/cli` repository: https://github.com/docker/cli/blob/master/docs/reference/run.md It would be great if you could open a bug (or a pull request with your suggested wording) there. Thanks!
