### ISSUE TITLE
The Prerequisites should include docker machine

### ISSUE THREAD

**Issue by xiaocairush** [docker/docker.github.io#3174]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen 

I don't have a concept for docker machine and cannot learn this part smoothly. Please also tell how to or can we use ```docker-machine create --driver virtualbox myvm1``` in a VM.

**Comment by joaofnfernandes** [comment]
Yup, the instructions are not really clear on this. If you have Docker for Mac or Windows, `docker-machine` is already installed for you. If you're running Docker on Linux, I don't think `docker-machine` is installed with the Docker package, so you need to install it [by following these instructions](https://github.com/docker/machine/releases).

**Comment by johndmulhausen** [comment]
This has been added as a prereq. Thanks for the feedback, @xiaocairush !
