### ISSUE TITLE
Improve docs on logging options in Compose file reference

### ISSUE THREAD

**Issue by londoncalling** [docker/docker.github.io#3178]
### Problem description

Document logging better, especially per this [comment](https://github.com/docker/compose/issues/1083#issuecomment-299342320)  on how to limit log sizes

### Problem location

https://docs.docker.com/compose/compose-file/#logging

### Related 

[Issue 1083 in docker/compose on Feature: Ability to clear log history](https://github.com/docker/compose/issues/1083)

### Reviewers, (help w/improvements ?)

@thaJeztah @tgjamin @dnephin @shin-

**Comment by tgjamin** [comment]
Pull request adding documentation; #3243
