### ISSUE TITLE
`volumes` appears to require absolute paths

### ISSUE THREAD

**Issue by heptahedron** [docker/docker.github.io#3189]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/), CC @johndmulhausen 

I hope this isn't in error; I'm new to Docker so this could be entirely off-base, but when I tried to go through all the steps of this tutorial in order and when I got to this part, the redis service wouldn't start and I could see the beginning of 'invalid mount' in the `docker stack ps getstartedlab` entry for it. I couldn't figure out how to see the full string, but changing the volume directories to absolute paths in both the host and container paths seemed to fix it.

**Comment by joaofnfernandes** [comment]
The instructions are not very clear on that part 😢
In the docker-compose.yml file there's this instruction:
```
volumes:
      - ./data:/data
```
In this case `.` refers the directory where the compose-file.yaml is. So you need to make sure you create a `data` directory in the same place as you have your compose file.

**Comment by heptahedron** [comment]
I did, and it didn't work.

**Comment by joaofnfernandes** [comment]
Can you paste here the `docker-compose.yml` file you're using, as well as the structure of your project directory `tree .`?

**Comment by heptahedron** [comment]
I can't replicate this again, which means I probably didn't type what I thought I had typed earlier. Sorry about the mishap :sweat_smile:

**Comment by joaofnfernandes** [comment]
No worries! Thanks for following-up on this.
