### ISSUE TITLE
Standalone swarm: Rewrite "Deploy the app" to map to reality

### ISSUE THREAD

**Issue by ivoribeiro** [docker/docker.github.io#319]
URL: [https://docs.docker.com/swarm/swarm_at_scale/deploy-app.md](https://docs.docker.com/swarm/swarm_at_scale/deploy-app/)

The docs must be updated.  
"docker/example-voting-app-result-app" and "docker/example-voting-app-voting-app" dont exist.

**Comment by mstanleyjones** [comment]
Hey @ehazlett if you get a chance can you update this topic? It looks like you might have developed the initial example and the images have moved since then. You can just open the link above, go to the bottom, and click 'Edit this page' to get started. Thanks!

**Comment by ehazlett** [comment]
This probably needs to be re-written for Swarm mode.  This was originally written without the routing mesh and an older version of Docker swarm.  IMO we should remove this and replace it with a Swarm mode example.

**Comment by ivoribeiro** [comment]
@ehazlett I agree with that

**Comment by mstanleyjones** [comment]
@ehazlett are you offering? :)

**Comment by johndmulhausen** [comment]
Change `docker/example-voting-app-result-app` to point to this `https://hub.docker.com/r/docker/example-voting-app-result/tags/`

Change `docker/example-voting-app-voting-app`to `docker/example-voting-app-vote` in the case where we talk about deploying the "voting application"
