### ISSUE TITLE
PR #3092 introduces regressions

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3199]
When rebasing PR #3092 I bet we had merge conflicts in the TOC, and in solving them we reverted some changes that we introduced during the Hackaton.

Some examples:
* TOC is no longer in sentence case
* Get started tutorials are not showing in TOC. [Here's an example](https://docs.docker.com/get-started/), basically everything that the TOC file between lines `132-168` is not showing on TOC
* DDC for azure not showing in TOC

I've also been seeing some reports of broken links in the API docs that might be related to this like #3188, and #3168

**Comment by johndmulhausen** [comment]
Fixed by https://github.com/docker/docker.github.io/pull/3202 and 4df1516240ead67f4262f22c189bd4956dcff20a
