### ISSUE TITLE
Generate compliance documentation

### ISSUE THREAD

**Issue by anweiss** [docker/docker.github.io#3206]
### Problem description

We currently maintain a host of compliance documentation in our repo here -> https://github.com/docker/compliance. The goal is to autogenerate .md docs for docs.docker.com from the .yaml-based compliance content that adheres to the OpenControl [schema](https://github.com/opencontrol/schemas). Sample compliance file [here](https://github.com/docker/compliance/blob/master/opencontrol/components/DockerEE/component.yaml).

![image](https://cloud.githubusercontent.com/assets/2326106/25862131/f6116ad4-34b4-11e7-98fc-813a801bbec0.png)

We should take an approach that is similar to that which the Moby upstream autogenerates the command-line reference docs -> https://github.com/moby/moby/tree/17.03.x/docs/reference/commandline.

component.yaml -> ... -> .md for docs.docker.com

**Comment by anweiss** [comment]
Tracking in https://github.com/docker/compliance/tree/docs/docs

**Comment by johndmulhausen** [comment]
Thanks for getting this in, @anweiss !

**Comment by anweiss** [comment]
No prob!
