### ISSUE TITLE
Formatting Issue on "Best Practices"

### ISSUE THREAD

**Issue by weslord** [docker/docker.github.io#321]
### Problem location
- I saw a problem on the following URL:
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

- Around line 95:

> If you do not want to use the cache at all you can use the ` --no-cache=true`
option on the `docker build` command.

### Problem description
Github renders the markdown file just fine, but on docs.docker.com it appears like this:
> If you do not want to use the cache at all you can use the ' --no-cache=true`
option on the `docker build' command.

### Suggestions for a fix
I think the space between the " ` " and "--no-cache=true" might be confusing the processor.

**Comment by johndmulhausen** [comment]
Thanks for the bug and the PR, @weslord! :)
