### ISSUE TITLE
Are nodes being replaced by Swarm?

### ISSUE THREAD

**Issue by DanJ210** [docker/docker.github.io#3224]
File: [docker-cloud/getting-started/your_first_node.md](https://docs.docker.com/docker-cloud/getting-started/your_first_node/), CC @londoncalling

I don't see a node area that is explained in the above tutorial doc. That is, until I turned off swarm mode... So should I be looking at working with swarm instead of nodes?

**Comment by londoncalling** [comment]
@DanJ210 Hi! 

Yes, you either have to turn off swarm mode to work through the legacy tutorial cluster workflow, or turn on swarm mode and follow steps here for either or both cloud providers:

- [Create a new swarm on Amazon Web Services in Docker Cloud](https://docs.docker.com/docker-cloud/cloud-swarm/create-cloud-swarm-aws/)
- [Create a new swarm on Microsoft Azure in Docker Cloud](https://docs.docker.com/docker-cloud/cloud-swarm/create-cloud-swarm-azure/) 

Strongly recommend working through the Swarm mode steps, as this is better optimized and the direction we are going in general.

I believe that even if you have linked providers on non-Swarm mode, you have to re-link them in Swarm mode but I'm not sure about that. (I had them linked in Swarm mode, but when I switched to non-Swarm I needed to re-link them.)

In the meantime, while testing non-Swarm mode clusters, I realize our steps for AWS policy and role creation  need to be updated per their new UI's. We updated the Swarm mode steps, but not the original, so I'll work on that today. Let me know if you have any other questions, and how it goes. Thanks!

**Comment by DanJ210** [comment]
@londoncalling I appreciate the info and the links. I appreciate all of the documentation as well it has been extremely helpful. I will go with your suggestion and continue with Swarm since that's the direction things are going.

Thanks for the quick response!

**Comment by londoncalling** [comment]
@DanJ210 Thank you, that's really nice to hear! Have a good weekend.
