### ISSUE TITLE
Confusing plugin versions

### ISSUE THREAD

**Issue by bboreham** [docker/docker.github.io#3235]
File: [engine/extend/config.md](https://docs.docker.com/engine/extend/config/), CC @mstanleyjones

> Plugin Config Version 1 of Plugin V2
> This document outlines the format of the V0 plugin configuration. 

Is "V0" a typo for "V2" ?  I have never heard of V0 plugins and cannot find other references by searching the docs.

**Comment by joaofnfernandes** [comment]
Issue moved to [docker/cli #514](https://github.com/docker/cli/issues/514) via [**ZenHub**](https://www.zenhub.com/)
