### ISSUE TITLE
Code goes out of body element

### ISSUE THREAD

**Issue by Ullaakut** [docker/docker.github.io#3237]
![screen shot 2017-05-11 at 14 05 43](https://cloud.githubusercontent.com/assets/6976628/25948305/28870998-3653-11e7-97f2-40ce3840fcb4.png)
![screen shot 2017-05-11 at 14 06 13](https://cloud.githubusercontent.com/assets/6976628/25948304/2878342c-3653-11e7-9eba-fe6a31625586.png)

Instead of being in a `pre` element, this code box is in a `p` element, which is probably the reason why this problem happens. This seems like a big issue, as it's a field that lots of users probably try to copy-paste, but which they won't be able to.

File: [compose/install.md](https://docs.docker.com/compose/install/), CC @londoncalling

**Comment by anagio** [comment]
It's not the wrapping `p` tag which is fine, i'll have a PR sent for this later today.

**Comment by londoncalling** [comment]
@Ullaakut @anagio thanks I'm actually already working on this to correct the code blocks and some other things. I'll publish it today, and send you the PR # as soon as I am in the office.

**Comment by londoncalling** [comment]
Similar or tangentially related to #3216 , fixed as a part of #3225
