### ISSUE TITLE
Multiple Services script doesn't work - gives error

### ISSUE THREAD

**Issue by richb-hanover** [docker/docker.github.io#3238]
File: [engine/admin/multi-service_container.md](https://docs.docker.com/engine/admin/multi-service_container/), CC @mstanleyjones

Hi folks,

I had two (unsolved) problems on this page:

1) ` PROCESS_1_STATUS=$(ps aux |grep -q apache2)` always returns a zero status, whether or not the apache2 process is running

2) This line: `if [ $PROCESS_1_STATUS || $PROCESS_2_STATUS ]; then `

gives an error `./startup.sh: line 39: [: missing `]'`

I'm using Docker Version 17.03.1-ce-mac5 (16048) on OSX 10.12.4, with an underlying Ubuntu:trusty image.

Any thoughts? Am I doing this wrong? Thanks!

**Comment by mstanleyjones** [comment]
Hi @richb-hanover! That script was meant to be a really naive back-of-envelope example. I will look at the problems you are seeing, but the intent of the topic is that this way of managing multiple services within a container is very error-prone and that other approaches are better. Can you describe why you need the multiple services to be running in the same container? Maybe we can help you come up with a better solution.

**Comment by mstanleyjones** [comment]
For the first one, this is a pesky problem with `grep` and `ps`. By default, the `grep` command itself shows up in the `ps` output:

```
$ ps aux |grep apache2
misty            36765   0.0  0.0  2432804   1632 s000  R+   10:26AM   0:00.00 grep apache2
```

Since `grep` found something, the zero exit code is legit. We have to exclude the `grep` line:

```
$ ps aux |grep apache2 |grep -v grep

$ echo $?
1
```

**Comment by mstanleyjones** [comment]
See #3242 for the fixes to the script.

**Comment by richb-hanover** [comment]
Hi @mstanleyjones Thanks for the speedy response. I understand the general rule of Docker: "One Service Per Container".

But... I am building a little "VM" that receives netflow data (say, from a home router) and runs a couple programs to display it in useful ways (including apache2, SiLK, RRDTool, etc). The intended audience is people who will run this container on a machine at their home that's always running (and therefore able to collect and display the data). 

I believe the audience is (relatively) unsophisticated, and may only have a computer with limited performance to run it. Consequently, I want to make *single* container that wraps all the essential pieces. My hope is to have a single paragraph installation document that basically says:

1. Install Docker
2. `docker run` the container
3. Step 3? There is no step 3...

With that as prelude, does my plan make sense? As a newbie to Docker, are there better ways to accomplish my goal (of a dead-simple install)? Thanks again.

**Comment by mstanleyjones** [comment]
I think you can probably use a stack of swarm services for this. Maybe @thaJeztah or @aaronlehmann can add some helpful hints, but I think you can probably make one image per app you want to run, and use a volume to store the data itself. You'd create a Docker compose file to define the services and the volume, then you would deploy the stack to a single-node swarm.

**Comment by mstanleyjones** [comment]
Now that I think of it, you may be able to use Redis to store your data, which may make it easier for the other services to be able to access it as well.

**Comment by mstanleyjones** [comment]
In case the others don't weigh in, consider posting your question on forums.docker.com or asking in the Docker community slack (dockercommunity.slack.com).

**Comment by richb-hanover** [comment]
If I were starting afresh, I might consider using many other (and newer) technologies, such as Redis, external volumes for storage, etc.

However, I'm looking to containerize an existing app (with crufty old technology) to help people avoid the anxiety created by installing a zillion different packages. I'm willing to package it once, so many people can avoid the pain... (If you're curious about the process I'm following, you can look at the so-called "installation procedure" provided by FlowViewer at https://superb-sea2.dl.sourceforge.net/project/flowviewer/FlowViewer.pdf - not a lot of fun...)

So I would like to rely on Docker's ability to create a script to create robust and repeatable builds and make containers that will "just work".
