### ISSUE TITLE
"Error looking up volume plugin flocker: legacy plugin: plugin not found."

### ISSUE THREAD

**Issue by dusek** [docker/docker.github.io#324]
### Problem description

When following https://docs.docker.com/engine/tutorials/dockervolumes/, section [Mount a shared-storage volume as a data volume](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume), specifically issuing this command there:

``` sh
$ docker run -d -P \
  --volume-driver=flocker \
  -v my-named-volume:/webapp \
  --name web training/webapp python app.py
```

After issuing the command, this was the docker's full output:

```
docker: Error response from daemon: create my-named-volume: create my-named-volume: Error looking up volume plugin flocker: legacy plugin: plugin not found.
See 'docker run --help'.
```
### Problem location
- I saw a problem on the following URL: https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume
### Project version(s) affected

Running on Mac with:

```
$ docker --version
Docker version 1.12.2, build bb80604, experimental
```

**Comment by ingcsmoreno** [comment]
Hi @dusek, flocker is a plugin for multi-host portable volumes, if you want to use it you will probably have to manually install it (instructions here: https://flocker-docs.clusterhq.com/en/latest/docker-integration/manual-install.html).

But if what you want is just to complete the training, replace the plugin **flocker** with **local** and you will be ready to go :)

Also, here is the list of available Docker volumes plugins: https://docs.docker.com/engine/extend/legacy_plugins/#volume-plugins

**Comment by dusek** [comment]
@ingcsmoreno Thanks.

I was just reporting the issue simply because following the instructions in docs results in an error, which should not happen and is therefore a bug in the docs. I was successful at finding a way around it myself.

**Comment by mstanleyjones** [comment]
Please have a look at #626 and provide feedback there. Thanks for the report!
