### ISSUE TITLE
doesn't say how much disk space you will want

### ISSUE THREAD

**Issue by wbreeze** [docker/docker.github.io#3240]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/), CC @londoncalling

how much storage do I need
- to install?
- realistically to use with a few VM images?

Before install I have 47.97GB available
Applications: 12.42GB
Documents: 799.6MB
System: 18.16GB

Is a mid-2012 mac air with Sierra 10.12.4, 8GB memory, and a teeny tiny 120GB SD disk. Because of the teeny tiny, "System requirements" for me includes storage requirement.

Installing https://store.docker.com/editions/community/docker-ce-desktop-mac . (Yeah. Just dive in and find out.)  Where are the uninstall instructions?  Would be reassuring to know I can recover to zero docker, zero docker footprint.  Ah, here it is https://docs.docker.com/docker-for-mac/#uninstall-or-reset . Looks good.

Downloaded disk image size: 115.3MB
Application directory size: 216.6MB

After install, docker up and running, disk image deleted, I have 46.29GB available
Applications: 12.63GB
Documents: 799.6MB
System: 20.58GB

After pulling and running https://store.docker.com/community/images/circleci/build-image .
I have 33.1GB available
System: 32.72GB
The image is reported by `docker images` as 9.6GB

Well, there's a start!  Looks like 2GB to install plus about 20GB headroom to do anything useful.

**Comment by londoncalling** [comment]
@jeanlaurent @justincormack @dgageot @djs55 @friism Can you take a look at this question regarding storage and install footprint needed on Docker desktop apps?

We should document space needed to install on both [Docker for Mac](https://docs.docker.com/docker-for-mac/install/#what-to-know-before-you-install) and [Docker for Windows](https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install).  It looks like we give a RAM requirement on Mac ("At least 4GB of RAM"), but not on Windows, and nothing regarding storage space.

I can do tests like the one above done by @wbreeze , but it would be better to get specifics from Dev teams to include in install requirements.

**Comment by mstanleyjones** [comment]
The installation itself is tiny. How much space your image and container layers will take up on disk is totally dependent on your workloads. One problem is that Docker for Mac doesn't make it easy for you to see how much space is being used inside the Linux VM (and the same thing on Docker for Windows using Linux containers). I think I raised a bug about this in `docker/for-mac/` but i can't remember. When I was having issues with this, I think @thaJeztah helped me figure it out.

**Comment by johndmulhausen** [comment]
I don't think there's an action item for D4M here. It's up to users to investigate the size of images they pull; the installation itself is in fact tiny.

**Comment by wbreeze** [comment]
Saying nothing is not the same as saying that the installation is "tiny", providing some definition of "tiny", saying that the greater impact is the size of images pulled, and providing a realistic amount of headroom one might need to do something useful with Docker.

However very possibly it is true that the amount of storage required to use Docker is not something that many people much worry about.  If that is the implied justification, then no problem.
