### ISSUE TITLE
will environment variables in .env appear in containers?

### ISSUE THREAD

**Issue by FredrikWendt** [docker/docker.github.io#3241]
File: [compose/env-file.md](https://docs.docker.com/compose/env-file/), CC @londoncalling 

It is unclear (not explicit) whether environment variables defined in a `.env` file is also visible from inside the containers created from `docker-compose up` for instance.

**Comment by londoncalling** [comment]
@FredrikWendt 

* I believe that environment variables defined in the `.env` file are _not_ automatically visible inside containers

* but rather you need to set container applicable environment variables explicitly as indicated [Passing environment variables through to containers](https://docs.docker.com/compose/environment-variables/#passing-environment-variables-through-to-containers)

@shin- @dnephin @nathanleclaire Can one of you all verify that this is true ^^ , then I'll update the file Fredrik references ([Declare default environment variables in file](https://docs.docker.com/compose/env-file/)) to be a little more clear.

**Comment by dnephin** [comment]
That's correct. We have this disambiguation page: https://docs.docker.com/compose/environment-variables/
