### ISSUE TITLE
Improve restart policies docs

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3245]
There's some basic documentation for restart policies at
* https://docs.docker.com/engine/reference/run/#restart-policies---restart
* https://docs.docker.com/compose/compose-file/#restartpolicy

For each restart policy supported, it's not clear what happens if
* Container receives SIGTERM
* Container receives SIGKILL
* node is set to drain
* node is set to pause
* node shuts down
* node crashes

**Comment by londoncalling** [comment]
Compose topic on `restart` policies is here: https://docs.docker.com/compose/compose-file/#restart_policy

**Comment by mstanleyjones** [comment]
I think this is not an issue for services -- the whole point is that the manager maintains the state that you define for the service.
