### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by aalcamo** [docker/docker.github.io#3246]
File: [notary/reference/client-config.md](https://docs.docker.com/notary/reference/client-config/), CC @johndmulhausen 

I believe the tls_client_key should be ./fixtures/secure.example.com.key.
thanks,
Anthony

{
  "trust_dir" : "~/.docker/trust",
  "remote_server": {
    "url": "https://my-notary-server.my-private-registry.com",
    "root_ca": "./fixtures/root-ca.crt",
    "tls_client_cert": "./fixtures/secure.example.com.crt",
    "tls_client_key": "./fixtures/secure.example.com.**crt**"
  },
  "trust_pinning": {
    "certs": {
      "docker.com/notary": ["49cf5c6404a35fa41d5a5aa2ce539dfee0d7a2176d0da488914a38603b1f4292"]
    }
  }
}

**Comment by JimGalasyn** [comment]
Proposed change in [Update tls_client_key example path #1169](https://github.com/docker/notary/pull/1169).
