### ISSUE TITLE
"docker volume create" accepts no argument(s)"

### ISSUE THREAD

**Issue by dusek** [docker/docker.github.io#325]
### Problem description

When following https://docs.docker.com/engine/tutorials/dockervolumes/, section [Mount a shared-storage volume as a data volume](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume), specifically issuing this command there:

``` sh
$ docker volume create -d flocker -o size=20GB my-named-volume
```

After issuing the command, this was the docker's full output:

```
"docker volume create" accepts no argument(s).
See 'docker volume create --help'.

Usage:  docker volume create [OPTIONS]

Create a volume
```
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/tutorials/dockervolumes/
### Project version(s) affected

Running on macOS with:

```
$ docker --version
Docker version 1.12.2, build bb80604, experimental
```

**Comment by lybrus** [comment]
Hi!

I also following this guide. This is error in guide, see right syntax here https://docs.docker.com/engine/reference/commandline/volume_create/

```
$ docker volume create --name=my-named-volume1 --opt o=size=100m
```

But i don't use flocker.

**Comment by codyc4321** [comment]
Why is this closed if the tutorial is still broke?

**Comment by thaJeztah** [comment]
@mstanleyjones looks like these changes were cherry-picked into the 1.12.x branch, but were supposed to be for 1.13.x (where `name` could also be passed as a positional argument); https://github.com/docker/docker/pull/26343 https://github.com/docker/docker/commit/5e4e13e31c71f27e62825b55beedc096c27e3554
