### ISSUE TITLE
Clarification regarding Docker and openSuse

### ISSUE THREAD

**Issue by cgoeller** [docker/docker.github.io#3264]
File: [engine/installation/linux/suse.md](https://docs.docker.com/engine/installation/linux/suse/), CC @mstanleyjones

Could you please clarify if an installation on openSuse is supported and add a documentation?

In an older version of this document the following package repo was referenced.
https://yum.dockerproject.org/repo/main/opensuse/13.2/Packages/

It contains the current version (docker-engine-17.05.0.ce-1.x86_64.rpm) of the docker engine. So it seems there is at least a bit of support.

The RPM actually also work on SLES12 SP2. Is this just coincidence?

**Comment by mstanleyjones** [comment]
OpenSUSE is not currently supported. cc/ @friism

**Comment by cgoeller** [comment]
Thanks for the answer. Do you know why the mentioned repo contains current versions of docker-ce?

I'm wondering if I can rely on the existence of this repository for the forseeable future

**Comment by friism** [comment]
@cgoeller I'm afraid you can't - 17.05 is the last release where we'll make packages available on dockerproject.org. Docker Store (and download.docker.com) is where we'll make packages available going forward.

**Comment by cgoeller** [comment]
Thanks for the clarification!
