### ISSUE TITLE
small bug ??

### ISSUE THREAD

**Issue by albertoRamon** [docker/docker.github.io#3266]
File: [engine/swarm/swarm-tutorial/rolling-update.md](https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/), CC @mstanleyjones

docker service **create** \
  --replicas 3 \
  --name redis \

must be an docker service **update** ??  :)

**Comment by mstanleyjones** [comment]
No, I don't think so. Swarm is a declarative model, so you can define rolling update settings when you create a service, or you can update an existing service's settings to add the rolling update settings later on. cc/ @aaronlehmann in case I am missing something.

**Comment by aaronlehmann** [comment]
Correct, I don't see anything wrong with this line. This is just setting up a service for the tutorial, and there's a `docker service update` in step 4.

**Comment by albertoRamon** [comment]
yes, your are in true

thanks  !!
