### ISSUE TITLE
Define HA as it relates to Docker

### ISSUE THREAD

**Issue by westonkdavis** [docker/docker.github.io#3280]
File: [glossary.md](https://docs.docker.com/glossary/), CC @johndmulhausen 

For the glossary, how would we define High Availability as it relates to Docker?

**Comment by joaofnfernandes** [comment]
High-availability is the ability of Docker to run my services and containers without any downtime, even when one if the swarm nodes stops working.

**Comment by mstanleyjones** [comment]
This is an industry term and Docker uses it in the industry way.
