### ISSUE TITLE
Can we get a supervisord example for automatically restarting services

### ISSUE THREAD

**Issue by archit** [docker/docker.github.io#3285]
File: [engine/admin/host_integration.md](https://docs.docker.com/engine/admin/host_integration/), CC @mstanleyjones

The docs show example for Upstart & SystemD. Although the introduction mentions supervisor, there are no examples for it.

**Comment by mstanleyjones** [comment]
Actually we should take away the other examples. You should be using container restart policies for this, as stated in the first paragraph. These have been available since Docker 1.2! cc/ @thaJeztah

**Comment by thaJeztah** [comment]
Yes, looking at those examples, I see no reason to use systemd, upstart, or whatever supervisor for that, as it can be fully handled by restart policies; we should either rewrite that page to use those, or refer to the relevant information elsewhere
