### ISSUE TITLE
Google links to old versions of Docker EE products

### ISSUE THREAD

**Issue by vsaraswat** [docker/docker.github.io#3292]
### Problem description

If I type "Docker Trusted Registry" in Google I get the following results:

![image](https://cloud.githubusercontent.com/assets/4852973/26133041/3bc75b66-3a59-11e7-82e5-5e3cee10d944.png)

The very first link is DTR 2.0, an old version of the product. Similarly, "https://docs.docker.com/ucp/" is the first link for "Universal Control Plane" on Google and it redirects to UCP 1.1. 

For new users or people who are curious about Docker EE, they may get the wrong idea about what is the latest version and corresponding functionality. 

### Problem location

- I saw a problem on the following URL: 

https://www.google.com/search?q=universal+control+plane

https://www.google.com/search?q=docker+trusted+registry

### Project version(s) affected

This at least affects UCP and DTR, possibly other products as well.

### Suggestions for a fix

A couple of suggestions:
- docs.docker.com/ucp should redirect to the latest version of the product
- It might be worth having a "/latest" or similar redirect that is optimized to become the first page shown on Google. That way new users will always reach the newest documentation.

**Comment by johndmulhausen** [comment]
We should have a /latest folder within UCP and DTR and use robots.txt to block the version-specific versions of the docs from getting indexed.

**Comment by vsaraswat** [comment]
/latest would be awesome for a number of reasons...

**Comment by johndmulhausen** [comment]
Per our discussion around revamping the IA for EE documentation going forward, I'm closing this as it will be fixed as a byproduct of us rolling out the new docs using the "Deploy app in production" template.
