### ISSUE TITLE
Add Root CA rotation CLI to "How Swarm PKI works"

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#3293]
### Problem description

Docker 17.06 introduces a new `swarm ca` subcommand that allows rotating the Swarm CA.

Command line reference is added through https://github.com/moby/moby/pull/33152, but additional information should be added in the ["How PKI works in swarm mode"](https://github.com/docker/docker.github.io/blob/master/engine/swarm/how-swarm-mode-works/pki.md) page in the documentation

/cc @cyli @diogomonica @mstanleyjones

**Comment by mstanleyjones** [comment]
@cyli here is the GH issue for you.

**Comment by cyli** [comment]
@mstanleyjones Thanks!

**Comment by mstanleyjones** [comment]
Closed via #3439
