### ISSUE TITLE
Note or tip?

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#3295]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/), CC @londoncalling

The additional information given below the first paragraph in "Docker settings" is displayed in "Note: Tip:". 
![note or tip](https://cloud.githubusercontent.com/assets/25146885/26134057/7ef94856-3ade-11e7-8e84-bc41a47bd9c6.jpg)

**Comment by londoncalling** [comment]
@scjane Thanks, see the PR referenced above for the fix ^^.  I'll merge this tonight or tomorrow morning, if it looks good.
