### ISSUE TITLE
Incorrect explanation of repository key in "Delegations for content trust"

### ISSUE THREAD

**Issue by dingwilson** [docker/docker.github.io#3306]
### Problem description

In the documentation for ["Delegations for content trust"](https://docs.docker.com/engine/security/trust/trust_delegation/), it is stated:

> Using this delegation allows you to collaborate with other publishers without sharing your repository key, which is a combination of your targets and snapshot keys.

This is incorrect, as snapshot keys are now generated (since Docker Engine 1.11) on the server by default. To the best of my understanding, the repository key is now essentially just the target key itself.

The information regarding rotation of keys for the snapshot key from the overall repository key to the remote server is covered [a little later on in the doc](https://docs.docker.com/engine/security/trust/trust_delegation/#adding-a-delegation-key-to-an-existing-repository).
> If your repository was created using a version of Docker Engine prior to 1.11, then before adding any delegations, you should rotate the snapshot key to the server so that collaborators will not require your snapshot key to sign and publish tags:

Therefore, I recommend the removal of the mention of the snapshot key from the explanation of a repository key, as it was confusing and contradictory to the other explanations in the docs. [Example](https://docs.docker.com/engine/security/trust/trust_key_mng/)

>When doing a docker push with Content Trust enabled for the first time, the root, targets, snapshot, and timestamp keys are generated automatically for the image repository:
The root and targets key are generated and stored locally client-side.
The timestamp and snapshot keys are safely generated and stored in a signing server that is deployed alongside the Docker registry. These keys are generated in a backend service that isn’t directly exposed to the internet and are encrypted at rest.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/security/trust/trust_delegation/

### Project version(s) affected

Docker Engine 1.11 and higher

### Suggestions for a fix

Remove the mention of the snapshot key from the explanation of a repository key.

**Comment by mstanleyjones** [comment]
@riyazdf do you have thoughts on this?

**Comment by riyazdf** [comment]
I'd prefer to keep the docs as-is: if a snapshot key is kept locally (from an older engine, or a key rotation), it will be referred to as the "repository key"
