### ISSUE TITLE
Example instructions for NFS test server

### ISSUE THREAD

**Issue by hinshun** [docker/docker.github.io#3308]
In the current docs, if I want to quickly spin up a NFS test server with DTR, there aren't example configs for the nfs server on the docs for `DTR 2.2`:
https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/external-storage/nfs/

For my systemd based linux machine, the quickest way for me was:
1. Install `nfs-utils`
2. Edit `/etc/exports` with:
```
/tmp/nfs *(rw,all_squash,anonuid=1000,anongid=1000)
```
3. `systemctl enable nfs-server`
4. `systemctl start nfs-server`
5. Test by `showmount -e localhost`
6. Reconfigure DTR with `--nfs-storage-url nfs://localhost/tmp/nfs`

**Comment by martencassel** [comment]
Does DTR supports non-anonymous uids and gids authenticated against an LDAP directory ?

**Comment by joaofnfernandes** [comment]
This is good to have for internal reference and testing, but we can keep this info out of the docs.
