### ISSUE TITLE
env_file list order / precedence in docker-compose.yml

### ISSUE THREAD

**Issue by prometheas** [docker/docker.github.io#3311]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @londoncalling 

Hey there! Please speak briefly to whether the env files towards the top or bottom of the list override env values that may be declared in multiple files. Thanks!

**Comment by londoncalling** [comment]
@shin- @dnephin can you address this question? I can add the details to the docs, but don't know the answer.

**Comment by dnephin** [comment]
I'm not sure I understand the question. `env` always overrides `env_file`

**Comment by prometheas** [comment]
@dnephin, given the following declaration in `docker_compose.yml`:

```yaml
services:
  some-service:
    env_file:
      - a.env
      - b.env
```

And the following files:

```text
# a.env
FOO=1
```

and 

```text
# b.env
FOO=hello
```

Will $FOO be `1` or `hello`?

**Comment by dnephin** [comment]
The order of the files is significant, yes. It will be `hello`

**Comment by alanjds** [comment]
Can we have this said explicitly on the docs please?

**Comment by londoncalling** [comment]
@alanjds This was already added explicitly to the docs in the Version 3 Compose file per the referenced PR ^^ #3517

I've added further clarification in #3822, and will go ahead and update v2 and v1 as well, in this case.

**Comment by alanjds** [comment]
@londoncalling I see. Thanks.

**Comment by londoncalling** [comment]
Updates are merged, so this should be published soon. Thanks, @alanjds .

**Comment by MohammedNoureldin** [comment]
What about the *.env* file if it is not mentioned explicitly? Will overwrite the other files or is it will be overwritten?

**Comment by MohammedNoureldin** [comment]
Well, according to my observations:

Considering that:
```
# .env:
ENVVAR=.ENV

#other.env:
ENVVAR=OTHER
```

We have the following observations:

```
    env_file:
      - "other.env"
      - ".env"
#    environment:
#      - ENVVAR
```
The previous docker-compose.yml makes ENVVAR=.ENV

```
    env_file:
      - ".env"
      - "mailserver.env"
#    environment:
#      - ENVVAR
```
The previous docker-compose.yml makes ENVVAR=OTHER, which proves that the order of files matters.

```
    env_file:
#      - ".env"
      - "mailserver.env"
#    environment:
#      - ENVVAR
```
The previous docker-compose.yml makes ENVVAR=OTHER

```
    env_file:
      - ".env"
#      - "mailserver.env"
#    environment:
#      - ENVVAR
```
The previous docker-compose.yml makes ENVVAR=.ENV, which proves that the files mentioned in `env_files` are passed automatically to the container.

```
    env_file:
#      - ".env"
      - "mailserver.env"
#    environment:
      - ENVVAR
```
The previous docker-compose.yml makes ENVVAR=.ENV, which proves that the *.env* file will always override the other files mentioned in `env_files` if the variable name is mentioned in the `environment`, even if .env is included implicitly (by docker-compose convention).

```
    env_file:
      - ".env"
      - "mailserver.env"
#    environment:
      - ENVVAR
```
The previous docker-compose.yml makes ENVVAR=.ENV, which proves that the *.env* file will always override the other files mentioned in `env_files` if the variable name is mentioned in the `environment`, whatever the order of files in `env_file` is.
