### ISSUE TITLE
URL for repo doesn't work

### ISSUE THREAD

**Issue by briantd** [docker/docker.github.io#3325]
File: [engine/installation/linux/rhel.md](https://docs.docker.com/engine/installation/linux/rhel/), CC @mstanleyjones

<img width="725" alt="screenshot of safari 5-18-17 10-21-03 am" src="https://cloud.githubusercontent.com/assets/94055/26215086/c7affb28-3bb3-11e7-90ed-629de7648ddf.png">

# Elipses (...) are me obfuscating the license
```
[brian@brian-test1 ~]$ sudo yum-config-manager \
>     --add-repo \
>     https://storebits.docker.com/ee/linux/sub-3...e/docker-ee.repo
Loaded plugins: langpacks, product-id
adding repo from: https://storebits.docker.com/ee/linux/sub-3...e/docker-ee.repo
grabbing file https://storebits.docker.com/ee/linux/sub-3...e/docker-ee.repo to /etc/yum.repos.d/docker-ee.repo
Could not fetch/save url https://storebits.docker.com/ee/linux/sub-3...e/docker-ee.repo to file /etc/yum.repos.d/docker-ee.repo: [Errno 14] HTTPS Error 404 - Not Found
```

# I found adding "rhel" to the path worked
```
[brian@brian-test1 ~]$ sudo yum-config-manager \
> --add-repo https://storebits.docker.com/ee/linux/sub-3...e/**rhel**/docker-ee.repo
Loaded plugins: langpacks, product-id
adding repo from: https://storebits.docker.com/ee/linux/sub-3...e/rhel/docker-ee.repo
grabbing file https://storebits.docker.com/ee/linux/sub-3...e/rhel/docker-ee.repo to /etc/yum.repos.d/docker-ee.repo
repo saved to /etc/yum.repos.d/docker-ee.repo
```

**Comment by briantd** [comment]
Also appears this affects an earlier instruction as well.  I'm now thinking this may be the result of me using a license for Docker for Linux rather than Docker for RHEL.  I need to check whether the URL returned from the store is different for RHEL (i.e. has the edition type as a subdirectory).

**Comment by mstanleyjones** [comment]
These are the instructions for Docker EE for RHEL. Docker EE for Linux uses a different URL scheme, as documented on the Docker Store installation docs. The Store installation docs describe what you need to do to modify the instructions.

The Docker EE for Linux offering is not yet searchable on Store and not separately documented.

**Comment by krishna03312018** [comment]
centos instructions have "rhel" in the path, but replacing that with "centos" works

ex:
  sudo -E yum-config-manager \
    --add-repo \
    "$DOCKERURL/centos/docker-ee.repo"
