### ISSUE TITLE
Does document have to use big words for simple things

### ISSUE THREAD

**Issue by bobsort** [docker/docker.github.io#3329]
File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/), CC @mstanleyjones
Does document have to use big words for simple things such as context or volume for folder, 

What does "This command mounts the host directory, into the container " means? does it mean it will copy the folder inside container or just create a link to that folder ion container?

What does "A data volume is a specially-designated directory within one or more containers that bypasses the Union File System" means? what is special about that directory? what is bypassing Union File System? is that means it ignores content of directory?

**Comment by mstanleyjones** [comment]
Fixed in #4018
