### ISSUE TITLE
More details needed in Docker for Azure documentation

### ISSUE THREAD

**Issue by raquel-ucl** [docker/docker.github.io#3334]
File: [docker-for-azure/index.md](https://docs.docker.com/docker-for-azure/), CC @johndmulhausen

Hi. I'm new to docker and azure. However, I guess other people getting started with this will run into the same problem when following the docs under the `Docker for Azure` section. 

In the _Setup & Prerequisites_ section, it's mentioned:

> When setting up the ARM template, you will be prompted by the App ID and the App secret... 

I guess ARM stands for Azure Resource Manager. Why should I set up a template? Isn't that what we have done on the previous command? I've successfully run the command (` docker run -ti docker4x/create-sp-azure sp-name rg-name zone`) and found in the Azure portal there's a new resource group under the name I specified in the command. However that Resource Group has no resources.

I think there is a step missing in the docs.

It also becomes more obvious in the next part of the docs (_Deploy your app_), since it shows a screen capture with an already deployed app, and it doesn't specify how to get there. Also, if I created an Azure Web App and assign it to my new Resource Group, I don't get prompted for App Id or secret. 

Hope this helps!

**Comment by mstanleyjones** [comment]
@gbarr01 PTAL and see if these gaps still exist and seem relevant.

**Comment by mstanleyjones** [comment]
cc/ @ddebroy
