### ISSUE TITLE
Running friendlyhello app on MacOS Sierra does not work as expected

### ISSUE THREAD

**Issue by kimsyversen** [docker/docker.github.io#3336]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen 

I'm running MacOS Sierra 10.12.5 with docker installed via Homebrew. I have followed part 1 and part 2 and was about to run the _friendlyhello_ app. According to the documentation I should be able to reach the app at http://localhost:4000 after executing the following command, but it does not work.

```
docker run -p 4000:80 friendlyhello
```

However, the command below works:
```
$ curl $(docker-machine ip default):4000
<h3>Hello World!</h3><b>Hostname:</b> 788cc43b990d<br/><b>Visits:</b> <i>cannot connect to Redis, counter disabled</i>
```
I have just started to learn Docker. Based on some Googling this seem to actually be the way Docker works on MacOS. If that's correct, I think a note should be added so others don't get confused.

**Comment by johndmulhausen** [comment]
It would appear that you have created a VM with Docker Machine named `default` and are using it to deploy. This may be the default setup for Homebrew. However, you should be using Docker For Mac which includes a virtual machine solution built in. Then you won't get this problem. :)
