### ISSUE TITLE
Not obvious flask defaults to using port 5000

### ISSUE THREAD

**Issue by straticsryan** [docker/docker.github.io#3337]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/), CC @londoncalling

I was a bit confused when I encountered port 5000 in step 3. I kept looking back to understand why we were referencing port 5000 and where it was "exposed". Didn't realize flask defaulted to port 5000.

Suggested fix to add a note in step 1 that flask defaults to port 5000 like you noted for redis?

**Comment by londoncalling** [comment]
@straticsryan thanks, good point. I'm going to include this fix on a pull request I'm already working on for some other Compose examples. I'll tag you on it when it's closer to being ready.
