### ISSUE TITLE
Docs do not print well

### ISSUE THREAD

**Issue by tvon** [docker/docker.github.io#3338]
Samples attached.  I tried on a few different pages and results were consistent.

* Chrome - Mostly works but adds a bunch of blank pages to the end. [docker-docs-firefox.pdf](https://github.com/docker/docker.github.io/files/1016534/docker-docs-firefox.pdf)
* Firefox - Decides one page is probably enough and moves on to the footer. [docker-docs-safari.pdf](https://github.com/docker/docker.github.io/files/1016535/docker-docs-safari.pdf)
* Safari - Includes the sidebars and crams the content into a bout 1" of horizontal space. [docker-docs-chrome.pdf](https://github.com/docker/docker.github.io/files/1016538/docker-docs-chrome.pdf)

**Comment by mstanleyjones** [comment]
Please take a look now, because we did an entire site redesign since this issue was filed. The one possible improvement I can see is that the footer might need to be suppressed. @jsouth do you have thoughts? We use a universal footer shared with www, I believe.
