### ISSUE TITLE
Dockerd section missing options

### ISSUE THREAD

**Issue by fntlnz** [docker/docker.github.io#3340]
### Problem description

The dockerd's options section is missing a bunch of options added over time.

For example, the graph option has been deprecated (https://github.com/moby/moby/pull/28696) while experimental never reached the doc. I would suggest to write a small automation tool that can see if there's the need of a refresh at docs side for options, parameters etc.. There's the real issue of having a disparity between the implementation and the actual documentation

### Problem location

https://docs.docker.com/engine/reference/commandline/dockerd/#options

### Suggestions for a fix

Here's a diff of the options:

left: current situation on the docs
right: current situation of dockerd

```
1d0
< 
9a9
> --cluster-store-opt
11a12,14
> --cpu-rt-period
> --cpu-rt-runtime
> --data-root
15a19
> --default-shm-size
22a27
> --experimental
25d29
< --graph
29a34,35
> --init
> --init-path
48a55
> --seccomp-profile
49a57
> --shutdown-timeout
58a67
> --userland-proxy-path
```

**Comment by fntlnz** [comment]
@thaJeztah PTAL - could be a good ideal to write some code at least to warn about this kind of differencea between the docs and the target release ?

**Comment by thaJeztah** [comment]
A quick look learns me that the missing options are options that were added after 17.03. The current documentation on docs.docker.com is for the "stable" channel, hence doesn't show flags that were added after 17.03 (e.g. https://github.com/moby/moby/pull/29692)

**Comment by joaofnfernandes** [comment]
It seems that these options made it to the docs, so everything is OK 🙌

**Comment by fntlnz** [comment]
yay @joaofnfernandes thanks for looking at it
