### ISSUE TITLE
Network plugins page should clarify there are swarm-mode-compatible plugins

### ISSUE THREAD

**Issue by bboreham** [docker/docker.github.io#3343]
File: [engine/extend/plugins_network.md](https://docs.docker.com/engine/extend/plugins_network/), CC @mstanleyjones 

This page is mostly describing what are elsewhere referred to as "legacy plugins", but does not make it clear that readers wanting more up-to-date solutions should look elsewhere.

However there isn't a page to point to which (a) talks about v2 plugins and (b) shows how to use a network plugin.

In particular, the statement "existing networking plugins will not work in swarm mode" needs to be updated, because v2 plugins are supported in swarm mode.

**Comment by mstanleyjones** [comment]
@nishanttotla is this still true? @anusha-ragunathan can you provide any info?

**Comment by bboreham** [comment]
Yes it is still true.

The file is now at https://github.com/docker/cli/blob/master/docs/extend/plugins_network.md, so arguably this issue is in the wrong place.  `cli` seems a weird place to put docs about engine plugins.

**Comment by mistyhacks** [comment]
PR submitted upstream. Thanks!
