### ISSUE TITLE
Can you explain how Scale down works

### ISSUE THREAD

**Issue by BenyH** [docker/docker.github.io#3354]
File: [engine/swarm/swarm-tutorial/scale-service.md](https://docs.docker.com/engine/swarm/swarm-tutorial/scale-service/), CC @mstanleyjones
For example, If i have a scale of 10 and I scale down to 5, can I choose which containers to keep?

Thx

/Beny

**Comment by mstanleyjones** [comment]
I believe this would be considered an internal implementation detail of swarmkit and you would not be able to control this. @aaronlehmann might be able to confirm.

**Comment by aaronlehmann** [comment]
Currently there's no way to control which containers are kept.
