### ISSUE TITLE
Docker for AWS clearer instructions on deployment

### ISSUE THREAD

**Issue by easherma** [docker/docker.github.io#3356]
File: [docker-for-aws/deploy.md](https://docs.docker.com/docker-for-aws/deploy/), CC @johndmulhausen 

"docker deploy to deploy a bundle on your machine over an SSH tunnel, or copy the bundle (for example using scp) to a manager node, SSH into the manager and then run docker deploy (if you have multiple managers, you have to ensure that your session is on one that has the bundle file)"

Specific examples of either of these options would be great. The ```docker deploy``` docs don't clearly state how to deploy via ssh tunnel, and there seem to be alot of confusing/conflicting ways to do this.

**Comment by mstanleyjones** [comment]
@FrenchBen do you think we should be documenting how to SSH into the AWS / Azure machines?

**Comment by FrenchBen** [comment]
@easherma I believe those to be SSH basics and perhaps not necessarily needed, as users with certain VPN/firewall configs may complain that we don't include these instructions either. 

The ssh connection has been described here:
https://docs.docker.com/docker-for-aws/deploy/#connect-via-ssh

The DAB mention could be removed, in favor to the regular compose files, via:
`docker stack deploy -f docker-compose.yml myapp`
