### ISSUE TITLE
Windows networking defaults and options are not documented

### ISSUE THREAD

**Issue by PatrickLang** [docker/docker.github.io#3357]
File: [engine/reference/commandline/network_create.md](https://docs.docker.com/engine/reference/commandline/network_create/), CC @mstanleyjones 

There are some differences in naming between the Windows & Linux network types. We need some brief mention of this and the list of options needed to create networks on Windows. For example, someone may want to create a `transparent` network that uses a specific NIC, or set the IP address ranges used by the default `nat` network.

I'll file a work in progress PR for @Kallie-b and @jmesser81 to collaborate on.

**Comment by PatrickLang** [comment]
Discussion is happening on the PR ^^

**Comment by joaofnfernandes** [comment]
These PRs^^ never made it, so maybe someone can use them as a starting point to document address this issue moby/moby#33659

**Comment by joaofnfernandes** [comment]
Issue moved to [docker/cli #515](https://github.com/docker/cli/issues/515) via [**ZenHub**](https://www.zenhub.com/)
