### ISSUE TITLE
docker --version doesn't reflect VERSION

### ISSUE THREAD

**Issue by vochicong** [docker/docker.github.io#3368]
File: [opensource/project/set-up-dev-env.md](https://docs.docker.com/opensource/project/set-up-dev-env/), CC @johndmulhausen 

At Task 2, step 9 (Inside your container, check your Docker version)
it doesn't show the value in the VERSION file at the root of 
my docker-fork repository.

```
# pwd
/go/src/github.com/docker/docker
# hack/make.sh binary install-binary run
# which docker
/usr/local/bin/docker
# docker --version
DEBU[0590] Calling GET /_ping                           
Docker version unknown-version, build unknown-commit
# cat VERSION 
17.06.0-dev
```

**Comment by joaofnfernandes** [comment]
Yes, the version number that you'll see is the one you're building.
We could update the docs to reflect the latest version of Docker, but it's possible that you're building Docker from a branch or tag, in which case the docs would still not match.
For this reason I'm closing the issue, but feel free to comment if you think that it doesn't make sense.
