### ISSUE TITLE
Feedback for: engine/swarm/key-concepts.md

### ISSUE THREAD

**Issue by sbrattla** [docker/docker.github.io#337]
I'm fairly new to Docker, and I'm trying to understand Docker Swarm. The documentation is fine, but I find some parts confusing. That's why I've got some comments for [https://docs.docker.com/engine/swarm/key-concepts.md](https://docs.docker.com/engine/swarm/key-concepts/)

> Manager nodes also perform the orchestration and cluster management functions required to maintain the desired state of the swarm. Manager nodes elect a single leader to conduct orchestration tasks.

The first sentence says that the manager performs orchestration tasks. The second sentence says that the manager hands orchestration tasks over to someone else. Who is doing the orchestration? And what is this single leader; is that a worker node?

> Worker nodes receive and execute tasks dispatched from manager nodes [...]. The agent notifies the manager node of the current state of its assigned tasks so the manager can maintain the desired state.

Why introduce the term **agent** here? Isn't an agent just a **worker node**? If that is so, why not call it that to avoid confusion over terms?

**Comment by londoncalling** [comment]
@sbrattla thanks for the comments, we have updated the docs to clarify the points you bring up, along with some others. Feel free to re-open this issue, or a new one, if you have more ideas or feedback. You can see the updated docs here: https://docs.docker.com/engine/swarm/key-concepts/ , and/or take the links to PR #1023 to view a detailed history of the file updates and the conversation around it.
