### ISSUE TITLE
Markdown showing in mount options

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#3380]
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/), CC @mstanleyjones

<img width="890" alt="screenshot 2017-05-24 at 10 53 22 am" src="https://cloud.githubusercontent.com/assets/414445/26412750/62d27922-406f-11e7-9525-d6891e285099.png">
https://docs.docker.com/engine/reference/commandline/service_create/#add-bind-mounts-or-volumes

**Comment by mstanleyjones** [comment]
This needs to be done in `moby/moby` and is just a teensy little nit, where a `)` needs to be changed to a `]`. I'll try to get to this but you can feel free if you would like to have a go, @mbentley ;)

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #602](https://github.com/docker/cli/issues/602) via [**ZenHub**](https://www.zenhub.com/)
