### ISSUE TITLE
User couldn't find what version of UCP this documentation is for

### ISSUE THREAD

**Issue by chikaando** [docker/docker.github.io#3382]
File: [datacenter/ucp/2.1/guides/admin/configure/external-auth/index.md](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/configure/external-auth/), CC @joaofnfernandes 

A partner in Sweden helping his client (a large nordic bank) reported:
- unable to find what version of UCP this documentation is for
- the documentation is outdated, not relevant to the latest UCP. Because of that, he wasn't confident if he was looking at the right information or not to troubleshoot his issue setting up LDAP sync.

I don't know if this page is outdated or irrelevant to the latest version, but based on what he saw, a user assumed so, which is an issue. Clearly showing the version of the product may increase credibility and confidence in users reading it.

**Comment by JimGalasyn** [comment]
This is for UCP 2.1.4. The version is shown in the URL ("datacenter/ucp/2.1/") but this might be too obscure for users to see readily.

**Comment by JimGalasyn** [comment]
Thank you for the feedback. We're considering various ways of surfacing version info in the docs, but for now, the URL is the authoritative source of truth.

**Comment by joaofnfernandes** [comment]
Let's leave this issue open to track this feedback until it's fixed. I've been getting this feedback pretty consistently from enterprise users.

**Comment by gabrielmcg** [comment]
This is especially a problem when Google search brings back links to older versions of the docs first

**Comment by mstanleyjones** [comment]
Maybe we can address this in Liquid / Jekyll.

**Comment by johndmulhausen** [comment]
I believe this is fixed by the new drop-down system.
