### ISSUE TITLE
Dockerfile need to change not working  

### ISSUE THREAD

**Issue by puneethprog9** [docker/docker.github.io#3389]
File: [engine/examples/running_ssh_service.md](https://docs.docker.com/engine/examples/running_ssh_service/), CC @mstanleyjones

Dockerfile need to change not working  /etc/ssh/sshd_config contents are changed so sed not replacing anything making root cant login.And ssh not starting and not added to systemstartup

**Comment by mstanleyjones** [comment]
I'm not clear on the problem you are having. Can you try asking this on forums.docker.com? Thanks!
