### ISSUE TITLE
Error starting daemon: The docker daemon requires build 14393 or later of Windows 10

### ISSUE THREAD

**Issue by megusta420** [docker/docker.github.io#3391]
### Problem description

Tried to use docker about a week earlier and all was okay while running. After that I decided to play with docker in future and forgot about it for a couple days. Once I tried to run it again using GUI interface for Windows docker it pushed me a message that "Not enough memory". And that's at a low settings! Also some days ago it was started alright at higher settings.
So I tried to run dockerd manually and thats an error:

"Error starting daemon: The docker daemon requires build 14393 or later of Windows Server 2016 or Windows 10"

Googled that message and found nothing. So, how dockerd run at my Windows 10 days ago and do not run now? There were no any updates as I see for W10.

### Project version(s) affected

dockerd with Docker version 17.03.1-ce, build c6d412e

**Comment by joaofnfernandes** [comment]
@megusta420 sorry for only getting to this issue now. Are you still experiencing this?
Given that this is a product issue, and not a docs one, consider opening an issue on https://github.com/docker/for-win

**Comment by johndmulhausen** [comment]
Issue moved to [docker/for-win #1045](https://github.com/docker/for-win/issues/1045) via [**ZenHub**](https://www.zenhub.com/)
