### ISSUE TITLE
Ports of WordPress Multisite

### ISSUE THREAD

**Issue by castroalves** [docker/docker.github.io#3396]
File: [compose/wordpress.md](https://docs.docker.com/compose/wordpress/), CC @londoncalling

WordPress Multisite works only on 80 and/or 443 ports. I recommend adding a comment after `ports` to help people.

In my environment, only 443 port worked because another service was already running on 80. I've found it after running `docker-compose up -d` and getting the error message below:
 _"Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)"_

**Comment by johndmulhausen** [comment]
We should pull this topic down in favor of /samples/wordpress/
