### ISSUE TITLE
Adding apt repo did not work for me

### ISSUE THREAD

**Issue by raqua** [docker/docker.github.io#3400]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/), CC @mstanleyjones

Hi,

the step in docs (3.) where I should be adding a repo did not work, it seems to be little strange, never seen it like that before. I am on Mint 18.
Instead of that, I had to do: echo deb https://apt.dockerproject.org/repo ubuntu-xenial main > /etc/apt/sources.list.d/docker.list

**Comment by mstanleyjones** [comment]
Docker is not officially supported on Mint. Note that it is not listed as a supported platform. You need to use your "parent" version of Ubuntu, as you did to get it working. Thanks!

**Comment by raqua** [comment]
Understood, but I am pretty sure that your instructions would not even work on Ubuntu, that's why I wanted to let you know.

**Comment by mstanleyjones** [comment]
They certainly do. :) You just need to make sure that you follow the instructions to install the `apt-add-repository` tool. It's a lot less error-prone than echoing into files.
