### ISSUE TITLE
Anchor links missing

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker.github.io#3402]
### Problem description

In some previous iteration, heading tags (`<hN>`) produced clickable (and more importantly copyable) links on the heading.
Now the links are gone and in order to get the actual anchor link you have to inspect the element, copy the tag id and insert it into the URL.
This makes it much more difficult to give a user a link to some specific piece of documentation.

### Problem location

Every page that has heading tags

### Suggestions for a fix

Not hugely familiar with the various markdown processors or their capabilities, but....

This likely needs to be done with a bit of JS.
Since the markdown processor is already generating the ID's we just need to generate the link from the ID.

**Comment by joaofnfernandes** [comment]
This has been fixed. When you scroll the url automatically changes, so that you can copy it with the fragment.
