### ISSUE TITLE
Compatibility matrix between docker-compose and docker versions

### ISSUE THREAD

**Issue by Rots** [docker/docker.github.io#3404]
File: [compose/overview.md](https://docs.docker.com/compose/overview/), CC @londoncalling

It would be nice to have a compatibility matrix for docker-compose. E.g. In our OS software repository we have quite an old version of docker available (SLES12 SP1, Docker 1.6.2) I'd like to know which version of compose is latest compatible one with the docker installation.

**Comment by friism** [comment]
Docker 1.6.2 is no longer supported. Compose release notes have details on what Docker version is supported. It looks like Compose 1.3 is the last version that supported Docker 1.6: 

 * https://github.com/docker/compose/releases/tag/1.3.3
 * https://github.com/docker/compose/releases/tag/1.3.0

Neither Docker 1.6.2 nor Compose 1.3.3 are supported anymore and probably contain unfixed bugs. You can start a free trial for Docker for SLES on Docker Store: https://store.docker.com/editions/enterprise/docker-ee-server-sles

**Comment by Rots** [comment]
Thanks for the reply.
Yes, manually going through the release notes works, I thought that other people might have the same problem though, and it would be helpful to have a quick overview in a form of a table.

**Comment by londoncalling** [comment]
@Rots I'll look at this as soon as I get a chance, try to come up with something useful, and ask you to have a look at it, thanks
