### ISSUE TITLE
Remove duplicated blockquote text

### ISSUE THREAD

**Issue by sarahpark** [docker/docker.github.io#3409]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/).

"Note: " text is duplicated. There's a pseudo-class on blockquote as well as inline text in the markdown:  

<kbd>

<img width="1440" alt="screen shot 2017-05-25 at 2 03 18 pm" src="https://cloud.githubusercontent.com/assets/1562758/26470575/0f314ee4-4153-11e7-8eca-16e41f7bff10.png">

</kbd>

--

"Warning: " is also duplicated:

<kbd>

<img width="629" alt="screen shot 2017-05-25 at 2 16 32 pm" src="https://cloud.githubusercontent.com/assets/1562758/26471051/e0821a90-4154-11e7-9011-5a2291d3fb13.png">

</kbd>

--

Feel free to assign to me to fix later (I just don't want to shift dev environments today heh).

**Comment by johndmulhausen** [comment]
Some recent handiwork by @londoncalling has fixed this. Thanks for the report, @sarahpark !
