### ISSUE TITLE
Document ulimits option for Docker Compose

### ISSUE THREAD

**Issue by gasparch** [docker/docker.github.io#3415]
Documentation of Docker Compose about ulimits section is very terse. In other hand turns out Docker-Compose/Docker pass any option specified in that section to [setrlimit](https://linux.die.net/man/2/setrlimit) and any of `RLIMIT_*` options can be used.

Please include use case example for limiting memory usage in container as well (whcih is only way to set memory limit in `docker-compose up` mode:

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: 

https://docs.docker.com/compose/compose-file/#ulimits
or in here 
https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container-ulimit

### Suggestions for a fix

Include example like this:

```
ulimits:
  as:
    soft: 20000000
    hard: 40000000
```

**Comment by joaofnfernandes** [comment]
Relates to #3416. Maybe @shin- can correct me, but it seems that `docker-compose` doesn't validate the ulimit types, so probably it just passes it along to Docker, and it's up to Docker to do the validation. In which case, the [supported types are going to be these ones](https://github.com/docker/go-units/blob/f2145db703495b2e525c59662db69a7344b00bb8/ulimit.go#L46-L62).

**Comment by mstanleyjones** [comment]
The example doesn't have everything. The reference section does: https://docs.docker.com/compose/compose-file/#resources
