### ISSUE TITLE
/commandline/docker not rendering properly

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3418]
File: [engine/reference/commandline/docker.md](https://docs.docker.com/engine/reference/commandline/docker/), CC @mstanleyjones 

![screen shot 2017-05-26 at 17 03 28](https://cloud.githubusercontent.com/assets/1525937/26515988/432f0028-4235-11e7-8519-355ff06b9d78.png)

**Comment by johndmulhausen** [comment]
Closing in favor of #4041
