### ISSUE TITLE
Bring back lifecycle diagrams

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3419]
We used to have diagrams with the lifecycle of a container. But with the changes to the API docs we lost that.

![screen shot 2017-05-26 at 17 06 37](https://cloud.githubusercontent.com/assets/1525937/26516027/b26ee62e-4235-11e7-952f-0120ede1f444.png)
(from https://docs.docker.com/v1.11/engine/reference/api/docker_remote_api/)

Bring back these diagrams, and coordinate with @acutebrunette to use a better color palete.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
