### ISSUE TITLE
Setting content trust on swarm already running services

### ISSUE THREAD

**Issue by gabrielmcg** [docker/docker.github.io#3420]
File: [datacenter/ucp/2.0/guides/content-trust/index.md](https://docs.docker.com/datacenter/ucp/2.0/guides/content-trust/), CC @joaofnfernandes

The docs don't say what happens when you use UCP to set Content Trust on a swarm running services - do the existing services get re-started, causing them to fail if they haven't been signed? or do existing services survive and the change only affects new deployments?

**Comment by joaofnfernandes** [comment]
We can improve the docs around this, but the behavior should be that all services and containers should continue running after you enable content trust. Only new and redeployed services/containers will be checked.
