### ISSUE TITLE
Copy/pasting MongoDB instructions results in error: Unable to locate package software-properties-common

### ISSUE THREAD

**Issue by jphire** [docker/docker.github.io#3424]
File: [engine/examples/mongodb.md](https://docs.docker.com/engine/examples/mongodb/), CC @mstanleyjones

When copy/pasting the lines for the MongoDB image installation, running this line before running `apt-get update` results in error:
`RUN apt-get install -y --no-install-recommends software-properties-common`

And the thrown error is:
`E: Unable to locate package software-properties-common`

The fix is simply to update it to:
`RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common` 

This error does not concern the file that has the complete code, because it does not include the aforementioned line at all.

**Comment by gbarr01** [comment]
Hi, @jphire , thanks for the issue. This page is no longer maintained by the Docker docs team. 

It has also been moved here (#4950): https://docs.docker.com/samples/library/mongo/
