### ISSUE TITLE
could you clarify the installation instructions on Ubuntu with Intel?

### ISSUE THREAD

**Issue by fomisha** [docker/docker.github.io#3427]
File: [engine/installation/binaries.md](https://docs.docker.com/engine/installation/binaries/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
What clarification do you need? You should be using the packages provided for Ubuntu: https://docs.docker.com/engine/installation/linux/ubuntu/

**Comment by fomisha** [comment]
my confusion was that it has two choices: armhf and amd64. I used amd64 and
it worked even though I am on Intel architecture.

thanks for the reply

**Comment by mstanleyjones** [comment]
arm64 and x86-64 are the same, in this case. :)
