### ISSUE TITLE
Ubuntu install missing an optional step

### ISSUE THREAD

**Issue by nandhini915** [docker/docker.github.io#3429]
### Problem description

When going through install steps for Docker Community/Enterprise Edition on Ubuntu I get the following error 
```Unable to locate package software-properties-common```

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository

### Suggestions for a fix

Adding an optional step _before_ installation using the repository would help (I was able to successfully install Docker EE)

```sudo apt-get update```

cc @mstanleyjones

**Comment by mstanleyjones** [comment]
Closed via #3350
