### ISSUE TITLE
--build-args not supported?

### ISSUE THREAD

**Issue by Azbola** [docker/docker.github.io#3450]
File: [compose/reference/build.md](https://docs.docker.com/compose/reference/build/), CC @londoncalling 

Hi there, If I understand correctly (and looking at the options in v.1.11.2) there is no support for --build-args in docker-compose?

Thanks

**Comment by londoncalling** [comment]
@Azbola I think there _**is**_ support for build arguments in `docker-compose`. Can you provide links or more explanation for why you think this is not true?

cc: @shin- @dnephin @mstanleyjones

**Comment by Azbola** [comment]
Hi @londoncalling 

Ah apologies, I see why I am confused :-)

Looks like this was added in version 1.12, and I am using docker CE for windows which includes version 1.11.2 so this functionality is not there out of the box.

I will updated my version - thanks for the help!

**Comment by londoncalling** [comment]
Sounds good @Azbola. Thanks for reaching out to us.
