### ISSUE TITLE
Update GPG keys

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3457]
Some users are following https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository and reported that Docker's GPG key doesn't match what is documented on that page.

**Comment by andrewhsu** [comment]
i'll have a look

**Comment by andrewhsu** [comment]
For me, I'm able to get the GPG key `9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88` that is documented:

```
# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && apt-key fingerprint 0EBFCD88
OK
pub   4096R/0EBFCD88 2017-02-22
      Key fingerprint = 9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
uid                  Docker Release (CE deb) <docker@docker.com>
sub   4096R/F273FCD8 2017-02-22
```

**Comment by mstanleyjones** [comment]
We are not able to replicate this.
