### ISSUE TITLE
Current Docker Cloud settings do not correlate with screenshot - Digital Ocean not listed

### ISSUE THREAD

**Issue by SabeBarker** [docker/docker.github.io#3474]
File: [docker-cloud/infrastructure/link-do.md](https://docs.docker.com/docker-cloud/infrastructure/link-do/), CC @londoncalling

When logging in to Docker Cloud and navigating to `Cloud Settings => Service Providers`  Digital Ocean is not listed.

Is this due to the fact that Digital Ocean provides a Docker Droplet?

**Comment by londoncalling** [comment]
@SabeBarker , you are right.

@pkennedyr @KickingTheTV did we drop Digital Ocean as a service provider?

Why does it not show up here? 
![cloud-providers](https://cloud.githubusercontent.com/assets/11660803/26737816/9f5c04d6-4780-11e7-851c-77d828e18ebd.png)

**Comment by pkennedyr** [comment]
Digital Ocean is currently only available within Standard Mode (in Docker Cloud). Within Swarm mode, AWS and Azure are the supported cloud providers atm.

**Comment by londoncalling** [comment]
@pkennedyr Thanks, I thought so and thought I'd switched modes, but hadn't! 

@SabeBarker I'll add a note to the Standard Mode Cloud Settings topic near that screen snap to clarify this.

![cloud-settings-standard](https://cloud.githubusercontent.com/assets/11660803/26740053/f7e1d9de-4788-11e7-962c-7ffd676a74a0.png)

**Comment by SabeBarker** [comment]
Excellent, that looks more like it :) Thanks for the clarification.
