### ISSUE TITLE
Enter key doesn't print carriage return

### ISSUE THREAD

**Issue by superruzafa** [docker/docker.github.io#3475]
### Problem description

When creating a container, return key doesn't print "\r"

```
$ docker run --rm -it ubuntu bash
root@08e17e341a92:/# ↲ 
                     root@08e17e341a92:/# ↲
                                          root@08e17e341a92:/# ↲
                                                               root@08e17e341a92:/#
```

### Project version(s) affected

Docker Edge >= 17.06.0-ce-rc1

### Suggestions for a fix

Could be fixed by manually issuing an `stty sane`.

**Comment by c0s** [comment]
Thank you! Was driving me nuts! Damn you Docker ;(

**Comment by joaofnfernandes** [comment]
I'm closing this as the issue is being tracked in moby/moby#33489. You can follow updates there.
