### ISSUE TITLE
Typo in example daemon.json files:  default-ulimit(s)

### ISSUE THREAD

**Issue by RayPlante** [docker/docker.github.io#3477]
### Problem description

It appears that there is a typo in both the in-line examples of Linux and Windows configuration files, `daemon.json`:  both show the property `"default-ulimits": {}`.  With dockerd version 17.03 (on Linux), `dockerd` will fail to start when this is included in `daemon.json`, complaining:

    unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: default-ulimits

If the `s` is removed from this property, `dockerd` will start fine.  This is consistent with the documented rule that the config file property names match the corresponding `dockerd` command-line arguments, which in this case is `--default-ulimit` (assuming the plural rule corresponds to array-type values only).  

### Problem location

This can be seen at https://docs.docker.com/edge/engine/reference/commandline/dockerd/#linux-configuration-file; this, I believe, corresponds to the file, `_data/dockerd-cli/dockerd.yaml`.

### Project version(s) affected

This is seen in v1.13 of this repo.  The above mentioned test was done against Docker Engine version 17.03.  

### Suggestions for a fix

Edit  `_data/dockerd-cli/dockerd.yaml`, changing `"default-ulimits"` to `"default-ulimit"` under both the sections, **Linux configuration file** and **Windows configuration file**.  (Note: I only tested the issue under Linux.)

**Comment by thaJeztah** [comment]
Actually, this may be a bug, see https://github.com/moby/moby/pull/32547

**Comment by thaJeztah** [comment]
Ah, yes, it's the same - it's a bug https://github.com/moby/moby/issues/32528

**Comment by RayPlante** [comment]
Ah, yes.  My impatient searching didn't turn this up.  Thanks!

**Comment by thaJeztah** [comment]
Hopefully the PR will be merged soon, but there's some investigation going on as to why integration tests didn't reveal the bug 😞

**Comment by joaofnfernandes** [comment]
It seems that moby/moby#32547 has been merged, so the docs now reflect the product behavior. I'm going to close this issue, but feel free to comment, if I missed something.
