### ISSUE TITLE
Request more clarity as to where to find stack traces

### ISSUE THREAD

**Issue by briantd** [docker/docker.github.io#3484]
File: [engine/admin/index.md](https://docs.docker.com/engine/admin/), CC @mstanleyjones

The document does a great job of detailing how to generate a stack trace, but I had trouble finding where the stack traces were placed.

Recommendations:
1) Add LinuxKitOS/MobyOS to the list of OSes [here](https://docs.docker.com/engine/admin/#read-the-logs) (uses `/var/log/docker.log` in this case)
2) Add an example of what to look for in `/var/log/docker.log` (I'm using MobyOS).
E.g.
<img width="1203" alt="screenshot of iterm2 6-2-17 12-33-54 pm" src="https://cloud.githubusercontent.com/assets/94055/26741901/2bc6a8e0-4790-11e7-9213-57657fe406b5.png">

It'd be super helpful to provide the base names of the expected logs:
* goroutine-stacks-YYYY-MM-DD*.log
* daemon-data-YYYY-MM-DD*.log

Then it's a trivial step to use `grep` to find the lines.

**Comment by briantd** [comment]
Another gotcha to consider is that for MobyOS, a tool like `nsenter` is needed to gain access to the path where the stack traces are output (i.e. /var/run/docker/).  This also complicates transferring the log files back to a client system if for example `ssh` was used.

It'd be great if the documentation included steps or recommendations for copying the stack traces to an external system, as it's likely they're going to be used for some kind of support.

**Comment by mstanleyjones** [comment]
@briantd can you provide those steps or point me to who can?
