### ISSUE TITLE
Update Getting started Doc, rename docker-compose.yml to docker-stack.yml

### ISSUE THREAD

**Issue by Lev09** [docker/docker.github.io#3486]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/), CC @johndmulhausen 
The docker-compose.yml is usually used with docker-compose, so seeing this name used for docker stack confuses people.
Even I no more know what to think!
Is docker-compose project deprecated? or we can still use it with newest docker version?
can we use the example of docker-compose.yml file shown in this documentation with docker-compose or no?

**Comment by joaofnfernandes** [comment]
I know that it is a bit confusing, but think about it this way:
* docker-compose.yml is a specification
* `docker-compose` is a tool that can receive a docker-compose.yml file as input and do things based on what the file describes
* `docker stack deploy` is also a tool that can receive a docker-compose.yml file as input and do things based on what the file describes

Both `docker-compose` and `docker stack deploy` support a subset of the `docker-compose.yml` specification, so there's a few keywords that will be ignored or create warnings depending if you're using one tool or the other.

The other thing to know is that `docker-compose` doesn't leverage swarm features. As an example, if your `docker-compose.yml` file describes several services, all of them will be deployed in the same node.
Contrast this with `docker stack deploy`. It is aware of all the nodes that are part of your swarm and as such will spread your services through all your nodes.

**Comment by Lev09** [comment]
Thanks for explanation. I think it would be good to make some clarification in that documentation too, to make it more clear and less confusing.

**Comment by londoncalling** [comment]
@joaofnfernandes @Lev09 I've added an explanation per the referenced PR ^^. I tried to make it brief so as not to interrupt the flow of the tutorial, but with enough context to help clarify things. See what you think.

**Comment by joaofnfernandes** [comment]
@londoncalling thanks for addressing this, since I've had to explain this to a lot of people. The whole docker-compose, compose file, stack, ... is confusing when you're getting started, and it doesn't help that we use the same names for different things.

**Comment by londoncalling** [comment]
@joaofnfernandes , agreed
