### ISSUE TITLE
DOCKER_TRUST_ENABLED

### ISSUE THREAD

**Issue by gabrielmcg** [docker/docker.github.io#3488]
File: [engine/security/trust/trust_automation.md](https://docs.docker.com/engine/security/trust/trust_automation/), CC @mstanleyjones 

Is DOCKER_TRUST_ENABLED still used/needed? I cannot find any other reference to it anywhere...

**Comment by joaofnfernandes** [comment]
Seems like this needs to be updated, since I can't find any references to this variable in moby/moby or docker/notary. But maybe @riyazdf or @cyli can confirm

**Comment by riyazdf** [comment]
good eye - `DOCKER_TRUST_ENABLED` isn't required, it's probably a typo for `DOCKER_CONTENT_TRUST`

**Comment by riyazdf** [comment]
https://github.com/docker/docker.github.io/pull/3504
