### ISSUE TITLE
Corresponding Docker-compose command for docker volume

### ISSUE THREAD

**Issue by AyushyaChitransh** [docker/docker.github.io#3489]
File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/), CC @mstanleyjones 
Using volumes in docker-compose has very little documentation. If there are corresponding commands  in docker-compose then, IMHO they should be written here as well.

**Comment by joaofnfernandes** [comment]
I'm not sure we should document things that are specific to `docker-compose` in those articles, but we should definitely improve the docs on how to use volumes in your compose files.

**Comment by AyushyaChitransh** [comment]
There is a lot of confusion about what the internal docker volumes are and how are they different from the ones that are mounted. I am not sure where that should reside, the things referred to in [volumes](https://docs.docker.com/engine/admin/volumes/volumes/) page mostly apply to docker run statement. 

We could describe details about volumes in the same page or in the docker-compose [volume](https://docs.docker.com/compose/compose-file/#volumes) section. Describing how internal docker volumes are different from the ones that are mounted.

**Comment by joaofnfernandes** [comment]
Maybe I'm not really understanding your problem 🤔
Can you clarify what do you mean by

> There is a lot of confusion about what the internal docker volumes are and how are they different from the ones that are mounted

I think my confusion is around what "internal docker volumes" and "mounted volumes" mean to you?
Keep in mind that there is not right or wrong answer here. Just the fact that we're discussing volumes, shows that there's room to improve the docs 😄

**Comment by AyushyaChitransh** [comment]
Internal docker volumes are labeled volumes. They seem to be very useful and free from any problems associated to ownerships and user ID mappings.

When mounts are made by mapping volumes from host then user id mappings are not made.

The fact that userId mappings are not made, can be included in docs. I recently had this problem in [logging mysql](https://github.com/reactome/container/issues/29#issuecomment-320509452)

**Comment by joaofnfernandes** [comment]
Got it! Also don't forget that docker volumes are more portable, in the sense that if they don't exist Docker will create them for you.
When mounting, if the directory doesn't exist in the host, Docker will not create it, and fail to run the container.

**Comment by AyushyaChitransh** [comment]
The `--mount` option in the [tutorial](https://docs.docker.com/engine/admin/volumes/volumes/) is new I believe and that improves things for `docker run`.

But I don't understand how could it be used in compose. In [this article](https://docs.docker.com/compose/compose-file/#volumes) we should also mention about arguments that could be used with options:

Example:

    volumes:
      -type: <possible_variations>

**Comment by mstanleyjones** [comment]
Hi @AyushyaChitransh, I'm sorry you've had trouble understanding what volumes are all about. You might find the new guide about [managing your application data](https://docs.docker.com/engine/admin/volumes/) helpful! There are specific topics under that heading about volumes vs bind mounts. There are a few key differences between volumes and bind mounts.

After you understand the differences between volumes and bind mounts and know which one you want, check out the [volume configuration reference for compose](https://docs.docker.com/compose/compose-file/#volume-configuration-reference). When defining a service using a Compose file, you define the volume as a top-level element and also mount it into the service. To see the differences in using volumes vs bind mounts in the compose file, see [the example which shows both in action](https://docs.docker.com/compose/compose-file/#volumes).

It's on my list to add some Compose examples to the Managing application data article, but for now hopefully this will help clear up your confusion.

**Comment by AyushyaChitransh** [comment]
That was very informative :smiley: and after the updates, I believe this issue should be closed now.
