### ISSUE TITLE
Docker compose v2 doc doesn't mention the recommended syntax of a container command

### ISSUE THREAD

**Issue by gdevillele** [docker/docker.github.io#3491]
File: [compose/compose-file/compose-file-v2.md](https://docs.docker.com/compose/compose-file/compose-file-v2/), CC @londoncalling 

The recommended syntax for container commands is shown here: [https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#cmd](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#cmd)
```
["bundle", "exec", "thin", "-p", "3000"]
```

In the compose file v2 doc, two different syntaxes are shown, but the recommended one is not.
```
command: bundle exec thin -p 3000
command: [bundle, exec, thin, -p, 3000]
```

Thanks. 🐼

**Comment by londoncalling** [comment]
@gdevillele closing this per the referenced PR. If you want further changes, feel free to re-open it. Thanks!

**Comment by gdevillele** [comment]
All good! Thank you @londoncalling 🙂
