### ISSUE TITLE
Got an error on Dockerfile

### ISSUE THREAD

**Issue by feng443** [docker/docker.github.io#3493]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen 

Adding following line 
```
COPY . /app
```
before 

```
WORKDIR /app
```
fixed it.

**Comment by joaofnfernandes** [comment]
Can you share the Dockerfile you were using and the error that you got? I can't seem to reproduce this.

**Comment by johndmulhausen** [comment]
No response from user, no idea what they were doing or what page if any they were on; I think we should just close this.
