### ISSUE TITLE
1.13 cs4 link is broken

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#3505]
File: [cs-engine/1.13/release-notes.md](https://docs.docker.com/cs-engine/1.13/release-notes/), CC @joaofnfernandes

I don't think 17.03.2 release actually happened (yet?)

cc/ @cpuguy83

**Comment by cpuguy83** [comment]
That's correct.

**Comment by johndmulhausen** [comment]
Working now! :)
