### ISSUE TITLE
404 at /engine/extend/plugins_logging/

### ISSUE THREAD

**Issue by samjsong** [docker/docker.github.io#3507]
URL: /engine/extend/plugins_logging/ does not exist, but is linked in the first paragraph of https://docs.docker.com/engine/admin/logging/plugins/ , under "implement their own plugins"

**Comment by mstanleyjones** [comment]
This is a little tricky to fix until 17.06 is released. You can find the file you need at https://github.com/moby/moby/blob/master/docs/extend/plugins_logging.md. It will be fixed automatically when 17.06 is released.
