### ISSUE TITLE
docker-compose won't run correctly before database creation

### ISSUE THREAD

**Issue by GarPit** [docker/docker.github.io#3509]
File: [compose/rails.md](https://docs.docker.com/compose/rails/), CC @londoncalling

    FATAL:  database "kms_production" does not exist

First step before `docker-compose up` should be database creation and then running containers

**Comment by londoncalling** [comment]
Hi @GarPit , thanks for your feedback

I've re-tested this just to be sure, and if you follow the sample as written, it should work. I'm not sure where you got database "kms_production", as it is not a part of the sample. It might be possible that in making some changes, you changed other things.

That said, when I got your feedback, I walked through it again several times myself and found that there were some problems with my documentation. Some steps weren't clearly called out as necessary, sample output was misleading, etc. I've corrected the issues I've found.

Some things to be aware of, that may not have been clear in the previous version of the sample docs:

1. After you run `docker-compose run web rails new . --force --database=postgresql`, you then have to run `docker-compose build`. This rebuilds the Docker image based on the newly-created Gemfile. 

2. Make sure that you modify the `config/database.yml` by replacing its contents with the given configuration as shown in the first part of the "Connect the database" step.

One more caveat. If you happen to be on Docker 1.17.06, some of the command output in your shell will render misaligned. It's a known issue in that release, and should be addressed soon. This should not affect actually building or running the sample.

Please re-try the sample, following the steps (maybe using the new version from the referenced PR #3517 ) and creating the content as written. Please let me know how it goes.

cc: @dnephin @shin-

**Comment by londoncalling** [comment]
Hi guys, I'm going to merge this since it LGTM and I want to get the fixes published. Feel free to comment / correct and I'll update as needed.

**Comment by GarPit** [comment]
I'm launching my project in production mode. Maybe this is the case?
