### ISSUE TITLE
add vmwareworkstation

### ISSUE THREAD

**Issue by cwon7609** [docker/docker.github.io#3512]
File: [machine/drivers/index.md](https://docs.docker.com/machine/drivers/), CC @londoncalling 

is it possible to have a link to the unofficial vmwareworkstation driver at https://github.com/pecigonzalo/docker-machine-vmwareworkstation

chris.

**Comment by londoncalling** [comment]
@shin- @dnephin is this okay to do?

**Comment by londoncalling** [comment]
@cwon7609  I added the link per the referenced PR ^^
