### ISSUE TITLE
Document what DTR S3 backends are supported

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#3515]
### Problem description
The docs do not specify or provide a link to the customer success site that says which S3 implementations are supported.  We need to either duplicate that data in the docs or link to the support matrix:
https://success.docker.com/Policies/Compatibility_Matrix

### Problem location
DTR docs

### Project version(s) affected
DTR all

### Suggestions for a fix
See problem above

**Comment by joaofnfernandes** [comment]
This one has been solved for a while now. The [docs now list the supported storage options](https://docs.docker.com/ee/dtr/admin/configure/external-storage/).
