### ISSUE TITLE
Please add details as how can CPUs can be limited for RHEL 

### ISSUE THREAD

**Issue by srkadiyala** [docker/docker.github.io#3523]
File: [engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
Hi, I'm not sure what you mean. These settings are not distribution-specific. Did you notice https://docs.docker.com/engine/admin/resource_constraints/#cpu on the page you linked? If this isn't answering your questions, please provide more details. Thanks!

**Comment by qubusp** [comment]
I'd use cgroups aimed at the particular container.

**Comment by mstanleyjones** [comment]
@trapier @cpuguy83 do you have any insight into that approach?

**Comment by cpuguy83** [comment]
I don't think there's anything to do here.
Docs are correct for any distribution.

**Comment by johndmulhausen** [comment]
Thanks, @srkadiyala - just use the standard commands. :)
