### ISSUE TITLE
Cross-platform instructions for configuring certificates for the daemon

### ISSUE THREAD

**Issue by lpicquet** [docker/docker.github.io#3528]
File: [engine/security/certificates.md](https://docs.docker.com/engine/security/certificates/), CC @mstanleyjones 

Hi, these instructions are really good for working on unix, but there is no mention on how to do this with windows.
You say about docker for windows10: "It is a native Windows application that provides an easy-to-use development environment for building, shipping and running dockerized apps."
It should be easy to configure this... somewhere... but where?

**Comment by joaofnfernandes** [comment]
Can you take a look at https://docs.docker.com/registry/insecure/#deploying-a-plain-http-registry and see if it helps?

**Comment by mstanleyjones** [comment]
Let's review this topic.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
