### ISSUE TITLE
Feedback for: engine/userguide/networking/default_network/dockerlinks.md

### ISSUE THREAD

**Issue by kkirsche** [docker/docker.github.io#353]
URL: [https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks.md](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/)

It would be really helpful if the page included a statement what "Legacy" meant in this context. Is it deprecated or is it just an old feature?

**Comment by mstanleyjones** [comment]
I submitted PR #577 to clarify this. Please weigh in there if you have more questions. Thanks!
