### ISSUE TITLE
Docker-compose doesn't have any verification info

### ISSUE THREAD

**Issue by nominum-systems** [docker/docker.github.io#3532]
### Problem description

Docker-compose doesn't seem to have any gpg signatures or checksums. The only thing approaching a reliable signature check are md5 sums on pip, which are only useful for checking for data corruption in 2017.

### Problem location

- I saw a problem on the following URL: https://docker.github.io/compose/install/

### Project version(s) affected

compose 1.13.0-present
### Suggestions for a fix

Please publish detached GPG signatures or package compose on the official repos for yum and apt.

**Comment by joaofnfernandes** [comment]
@shin- this is more of a release management issue. Can you take a look and create an issue in other repo if necessary?

**Comment by shin-** [comment]
docker/compose#4911
