### ISSUE TITLE
Broken link at bottom of page for "Use externally-signed certificates"

### ISSUE THREAD

**Issue by grahamnscp** [docker/docker.github.io#3533]
File: [datacenter/ucp/2.1/guides/admin/configure/integrate-with-dtr.md](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/configure/integrate-with-dtr/), CC @joaofnfernandes

**Comment by johndmulhausen** [comment]
@joaofnfernandes This page has no left nav and is not in the TOC; should it even be published?

**Comment by joaofnfernandes** [comment]
Might have been lost with a merge conflict, but it should be in the TOC
