### ISSUE TITLE
docker build read from stdin needs documentation

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#3538]
### Problem description

Docker 17.05 added an option to perform `docker build` with the Dockerfile piped through `stdin`, but being able to use local (or remote) build-context. Prior to docker 17.05, building an image with a Dockerfile from `stdin` did not send the build-context.

Docker < 17.05;

```bash
docker build -t foo -<<EOF
FROM busybox
RUN echo "hello world"
EOF
```

Docker 17.05 and up;

```bash
docker build -t . -f-<<EOF
FROM busybox
RUN echo "hello world"
COPY . /my-copied-files
EOF
```

or (remote build-context);

```bash
docker build -t foo https://github.com/thajeztah/pgadmin4-docker.git -f-<<EOF
FROM busybox
COPY LICENSE config_local.py /usr/local/lib/python2.7/site-packages/pgadmin4/
EOF
```

(or other variations to get the Dockerfile from `stdin`)

The old syntax is still supported; the new one is just added

This functionality wasn't documented when the pull request was merged, so needs an update (probably both in CLI reference and other pages)

/cc @dsheets @tonistiigi @mstanleyjones 

Related pull request: https://github.com/moby/moby/pull/31236
And proposal: https://github.com/moby/moby/issues/27393

**Comment by amontalban** [comment]
Would love to have this documented, found this googling around and it's a cool feature that should be known. Thanks for being awesome guys!

**Comment by mistyhacks** [comment]
@thaJeztah Sorry I didn't get to this. You might want to tackle this in `docker/cli` instead of here.
