### ISSUE TITLE
Missing Usage

### ISSUE THREAD

**Issue by maynep** [docker/docker.github.io#3549]
File: [datacenter/ucp/2.1/reference/cli/backup.md](https://docs.docker.com/datacenter/ucp/2.1/reference/cli/backup/), CC @joaofnfernandes 

Missing Usage for UCP Backup; unclear from this page how to use the backup command. See DTR Backup for how page should look.

**Comment by joaofnfernandes** [comment]
These docs are auto-generated so right now we don't have a way to link from this page to https://docs.docker.com/datacenter/ucp/2.1/guides/admin/backups-and-disaster-recovery/ 😞
