### ISSUE TITLE
Feedback for: engine/examples/mongodb.md

### ISSUE THREAD

**Issue by carterw** [docker/docker.github.io#355]
URL: [https://docs.docker.com/engine/examples/mongodb.md](https://docs.docker.com/engine/examples/mongodb/)

Running a debian jesse image, getting a package fetch error which causes the docker build to fail;
After the step "apt-get update && apt-get install -y mongodb-org"

Hit http://deb.debian.org jessie-updates InRelease                      
Err http://repo.mongodb.org jessie/mongodb-org/3.0/multiverse amd64 Packages
  
Hit http://deb.debian.org jessie Release.gpg      
Err http://repo.mongodb.org jessie/mongodb-org/3.0/multiverse amd64 Packages
...
W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/jessie/mongodb-org/3.0/multiverse/binary-amd64/Packages  404  Not Found

**Comment by konstruktoid** [comment]
Hi @carterw, does it work if you build using `FROM ubuntu:latest` as stated in the documentation? 
And `jessie` isn't a Ubuntu version; http://repo.mongodb.org/apt/_ubuntu/dists/jessie_/mongodb-org/3.0/multiverse/binary-amd64/Packages

**Comment by carterw** [comment]
Thanks for the tip. I installed using the debian instructions and that worked, duh. :)
