### ISSUE TITLE
Clarify host-dir and container-dir

### ISSUE THREAD

**Issue by Gustra** [docker/docker.github.io#3560]
File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/), CC @mstanleyjones 

The page suddenly uses the terms "container-dir" and "host-dir" without describing what these are. They are presumably: `-v host-dir:container-dir`, but it is not immediately obvious when reading the document. 

Please add a line before the use of these terms so that the reader understands how they relate to the text (like the example string above). I am new to docker and not qualified to do so :)

**Comment by joaofnfernandes** [comment]
With #4018 we've done a major revamp to this article. Since I can't find any references to `container-dir` anymore, I'll close this issue.
@Gustra feel free to comment if the article is still confusing.
