### ISSUE TITLE
USER instruction not properly documented

### ISSUE THREAD

**Issue by Nils-Magnus** [docker/docker.github.io#3564]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @mstanleyjones 

The section about `USER` is nearly undocumented, especially the ability to also specify optionally a group as an argument. A reference to the `--user` option of `docker run` wrt/ precedence would also be helpful.

**Comment by mstanleyjones** [comment]
These edits should be made in the `docker/cli` repository, not this one. Sorry for the confusion. We only pull the file from the upstream repository.
