### ISSUE TITLE
RUN apt-get update missing

### ISSUE THREAD

**Issue by selvendran-varathan** [docker/docker.github.io#3565]
File: [engine/examples/mongodb.md](https://docs.docker.com/engine/examples/mongodb/), CC @mstanleyjones 

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
RUN apt-get install -y --no-install-recommends software-properties-common
RUN echo "deb http://repo.mongodb.org/apt/ubuntu $(cat /etc/lsb-release | grep DISTRIB_CODENAME | cut -d= -f2)/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

**Comment by mstanleyjones** [comment]
Thanks for the report. FYI, we are now pulling in all the docs from the official Docker library images, and will probably eventually deprecate this content in favor of https://docs.docker.com/samples/mongo/.

cc/ @johndmulhausen

**Comment by joaofnfernandes** [comment]
As far as I can tell you've done the content migration and https://docs.docker.com/engine/examples/mongodb/ no longer exists, so there's nothing to fix.
@selvendran-varathan I'm going to close this issue, but feel free to comment.
