### ISSUE TITLE
docker-compose pull

### ISSUE THREAD

**Issue by mahmoudmahdi24** [docker/docker.github.io#3568]
Is there a feature which allows me to specify the name and the path of the docker-compose file while launching the "docker-compose pull " command ?
`        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?
        Supported filenames: docker-compose.yml, docker-compose.yaml`

**Comment by londoncalling** [comment]
@mahmoudmahdi24 , you can use the `-f` flag, which is documented in [Overview of docker-compose CLI
](https://docs.docker.com/compose/reference/overview/)

Sorry you had to hunt for this info. I'll try and figure out a way to surface it better in the docs.

For example, suppose I'm running the [Compose Rails sample](https://docs.docker.com/compose/rails/), and I have my `docker-compose.yml` file in a directory called `sandbox/rails`. I can use `docker-compose pull` to get the postgress image for the `db` service from anywhere, by using the `-f` flag as follows: `docker-compose -f ~/sandbox/rails/docker-compose.yml pull db`

Here's the full example:

```
$ docker-compose -f ~/sandbox/rails/docker-compose.yml pull db
Pulling db (postgres:latest)...
latest: Pulling from library/postgres
ef0380f84d05: Pull complete
50cf91dc1db8: Pull complete
d3add4cd115c: Pull complete
467830d8a616: Pull complete
089b9db7dc57: Pull complete
6fba0a36935c: Pull complete
81ef0e73c953: Pull complete
338a6c4894dc: Pull complete
15853f32f67c: Pull complete
044c83d92898: Pull complete
17301519f133: Pull complete
dcca70822752: Pull complete
cecf11b8ccf3: Pull complete
Digest: sha256:1364924c753d5ff7e2260cd34dc4ba05ebd40ee8193391220be0f9901d4e1651
Status: Downloaded newer image for postgres:latest
```

**Comment by mahmoudmahdi24** [comment]
Thank you very much ! It solved my problem
