### ISSUE TITLE
Missing #

### ISSUE THREAD

**Issue by stbof** [docker/docker.github.io#3578]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/), CC @johndmulhausen 

The HTML entity in this line is missing #:

but it codifies the way that image runs&8212;what 

It should be 

but it codifies the way that image runs `&#8212;`what

**Comment by londoncalling** [comment]
Thanks @stbof , my error. Should be fixed per referenced PR ^^, and I'll check through to see if there are any other similar issues
