### ISSUE TITLE
Automatic generation of docker/docker reference docs from YAML

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker.github.io#358]
### Problem description

Need a way to generate docs on the fly from a YAML file. The first target is `docker/docker`. This issue will track that work.

cc/ @johndmulhausen @dmp42

**Comment by FrenchBen** [comment]
I should be able to get this up and running within a week. 
Plan is to re-use some of the logic found in the `docker/docker` manpage generation and add the logic found in k8s for the YAML file generation.

**Comment by londoncalling** [comment]
@mstanleyjones @FrenchBen just going through issues, and wondering if this happened and whether we can close this?

**Comment by mstanleyjones** [comment]
No, we are still working out kinks with @tiborvass .

**Comment by johndmulhausen** [comment]
Closing. Great job everyone! The new refdocs are awesome.
