### ISSUE TITLE
Better description of --publish for "docker container run"

### ISSUE THREAD

**Issue by ncraike** [docker/docker.github.io#3582]
Please better document the possible syntax for the `--publish` option to `docker container run`, or link to other documentation where the syntax is described. For example, mapping to a particular host interface or mapping a range of ports.

File: [engine/reference/commandline/container_run.md](https://docs.docker.com/engine/reference/commandline/container_run/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
This file comes from the `docker/cli` repository and should be edited there. Sorry for the confusion. Please open this there.
