### ISSUE TITLE
Quickstart repos not found

### ISSUE THREAD

**Issue by shotokai** [docker/docker.github.io#3592]
File: [docker-cloud/getting-started/deploy-app/3_prepare_the_app.md](https://docs.docker.com/docker-cloud/getting-started/deploy-app/3_prepare_the_app/), CC @londoncalling 

```bash
git clone https://github.com/moby/mobycloud-quickstart-python.git
Cloning into 'mobycloud-quickstart-python'...
remote: Repository not found.
fatal: repository 'https://github.com/moby/mobycloud-quickstart-python.git/' not found
```

**Comment by londoncalling** [comment]
@shotokai Thanks for catching this, please see the referenced PR ^^
