### ISSUE TITLE
Github URL for bash completion is wrong

### ISSUE THREAD

**Issue by trestini** [docker/docker.github.io#3620]
File: [machine/completion.md](https://docs.docker.com/machine/completion/), CC @londoncalling 

The url of bash completion scripts in instructions (box with curl) is pointing to a wrong location.

I've did a search in repo and appear that the correct url is `https://raw.githubusercontent.com/docker/docker-ce/master/components/engine/contrib/completion/bash/docker` for bash, and `https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/zsh/_docker` for zsh

Thanks.

**Comment by ggarnier** [comment]
Actually, bash completion script URL should be `https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker`
