### ISSUE TITLE
Integrate docker service create articles

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3627]
I spend a lot of time (t>30 mins) searching how to publish a port on a node, and not the routing mesh. This happened because there are multiple reference pages for `docker service create` and sometimes the info you need is in a page, sometimes in other, sometimes in neither.

- https://docs.docker.com/engine/reference/commandline/service_create/ (info not here)
- https://docs.docker.com/engine/swarm/services/ (info was here, but it's not obvious what is the syntax of `--publish`)
- https://docs.docker.com/engine/api/v1.29/#operation/ServiceCreate (says that `mode=[dnsrr,vip]`, but not `host`)

I also tried to use `docker service create --help | grep publish`, but that led me nowhere.

**Comment by mstanleyjones** [comment]
Addressing with networking guide rewrite.
