### ISSUE TITLE
Docker for Mac fix

### ISSUE THREAD

**Issue by josephrexme** [docker/docker.github.io#3638]
The current documentation has this
> By default, Docker for Mac is set to use 2 processors

I have a MacBook with 8 processors and it uses 4 by default so I think what should be said here really is

> By default, Docker for Mac is set to use half the number of processors available on the host machine.

I wanted to send a PR but the repo is so large and I don't know of any smart way to clone without pulling so much. Actually tried but got to 99% and my internet was disconnected. With how long that took I wasn't going to try again

**Comment by mstanleyjones** [comment]
Hi @josephmosby! You can close with `--depth`. Sorry we have some large objects deep in our repo. You can also use the Github UI 100%. When you are looking at the page you want to change, click the `Edit this page` link on the right-hand side. This will take you straight to the Github editor and you can fork and create a pull request as you save your changes. Thanks for offering to help!

**Comment by mstanleyjones** [comment]
cc/ @londoncalling

**Comment by josephrexme** [comment]
Thanks I did that #3806
