### ISSUE TITLE
More detail on what's different from Overview versus Nodes metrics

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#3639]
A better description on what metrics the Overview dashboard displays (aggregate CPU, Disk, memory metric) and what metrics Nodes view displays (node level metrics) would be appreciated. 

File: [datacenter/ucp/2.1/guides/admin/monitor-and-troubleshoot/index.md](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/monitor-and-troubleshoot/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
This has changed in 2.2, and the design team is reviewed that page to make it really obvious what the metrics mean.
