### ISSUE TITLE
Getting Started Guide: Continuity issue regarding mapping container port to 4000

### ISSUE THREAD

**Issue by ryancabrera** [docker/docker.github.io#3643]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen 

In Part2, we were instructed to map port 80 of the container to 4000, so when we push it onto our repos, and then run the prerequisites as specified in  the beginning of Part4, navigating to 'http://localhost' will not work as we will still need to specify port 4000.

**Comment by johndmulhausen** [comment]
The prerequisites on part 4 say to try this command:

```
docker run -p 80:80 username/repo:tag
```

And in the Docker Compose file, ports are mapped thusly:

```                                                          
    ports:                                                                                                                                                                           
      - "80:80" 
```

So, after part 2 we are consistently exposing the container's port 80 to the host's port 80. The image for the container, as built, also only knows about port 80, per the Dockerfile:

```
EXPOSE 80
```

So, `localhost` is definitely the place after you're past the one example run in part 2 that shows how port remapping works.
