### ISSUE TITLE
docker volume prune minimum supported version

### ISSUE THREAD

**Issue by onthedock** [docker/docker.github.io#3645]
File: [engine/reference/commandline/volume_prune.md](https://docs.docker.com/engine/reference/commandline/volume_prune/), CC @mstanleyjones

Please, include the minimum supported version for the commands.

docker volume prune is unrecognized in Docker version:

Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 03:23:36 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 03:23:36 2016
 OS/Arch:      linux/arm

Thank you

**Comment by mstanleyjones** [comment]
If you're on Docker 1.12, you should be using the docs from the Docker 1.12 archive: https://docs.docker.com/v1.12/ Thanks!
