### ISSUE TITLE
Create Networked Hosts Unclear How to Proceed

### ISSUE THREAD

**Issue by sjones6** [docker/docker.github.io#3646]
This section:

> Three networked host machines
> The tutorial uses three networked host machines as nodes in the swarm. These can be virtual machines on your PC, in a data center, or on a cloud service provider. This tutorial uses the following machine names:

I read through these docs a few times and couldn't find instructions on how to create three networked host machines. Perhaps a link could be provided to another location where these instructions are provided, or edit to fill in details on how to setup for the tutorial. I eventually read other tutorials (not on Docker) to figure out how to proceed.

File: [engine/swarm/swarm-tutorial/index.md](https://docs.docker.com/engine/swarm/swarm-tutorial/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
Hi there. I'm sorry for the confusion. This just means you have three computers (or EC2 instances or VMs or whatever) that can talk to each other over a network. I can try to clarify that in the docs, but this is not Docker-specific and is out of scope for Docker docs.

**Comment by mstanleyjones** [comment]
Also, the docs you are looking at are for standalone swarms. If you are just getting started, you should almost definitely be using swarm mode that is built into Docker Engine. See the tutorials at https://docs.docker.com/engine/swarm/swarm-tutorial/.
