### ISSUE TITLE
SCP command doesn't work Win10 + HyperV

### ISSUE THREAD

**Issue by baldyman81** [docker/docker.github.io#3648]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen

Using Win10 and HyperV. Docker-machine works, but scp command doesn't work. Error "You must have a copy of the scp binary locally to use the scp feature"

This occurs when trying to copy the docker-compose.yml file.

**Comment by mstanleyjones** [comment]
This is related to the SSH issue on Windows 10, @gbarr01
