### ISSUE TITLE
Localize Docker Doc

### ISSUE THREAD

**Issue by cinqs** [docker/docker.github.io#3649]
File: [index.md](https://docs.docker.com/), CC @johndmulhausen 

Hi? Any plan on localizing the Docker Doc?

I received the updates that, docker has launched the new domain name of [https://www.docker-cn.com](https://www.docker-cn.com) in China cooperated with Aliyun.

So I am thinking that the reference doc should be multi-languaged, right?

**Comment by johndmulhausen** [comment]
Hi, @cinqs -- for now all we're covering is China. The decision to support more languages is something we have to take on a market-by-market basis. Thanks for the inquiry!
