### ISSUE TITLE
Broken link for distributed application bundles in Docker for AWS docs

### ISSUE THREAD

**Issue by dailyherold** [docker/docker.github.io#3660]
### Problem description

[Docker for AWS](https://docs.docker.com/docker-for-aws/deploy/#distributed-application-bundles) has a broken link to "distributed application bundles".

### Problem location

[Docker for AWS / Distributed Application Bundles](https://docs.docker.com/docker-for-aws/deploy/#distributed-application-bundles): first sentence.

### Suggestions for a fix

Looks like [Compose ](https://docs.docker.com/compose/bundles/) now has a dedicated page for the bundle information/documentation. I have a local branch with the fix that I can open as a PR.

**Comment by mstanleyjones** [comment]
Fixed in #3661
