### ISSUE TITLE
Add Architecture image that describe work flow of docker in dockumentation.

### ISSUE THREAD

**Issue by shree007** [docker/docker.github.io#3662]
File: [engine/swarm/index.md](https://docs.docker.com/engine/swarm/), CC @mstanleyjones

I am newbie I request to you please add architecture image for docker work flow. Images elaborate each and everything in very well way. People will get very good understanding also regarding docker swarm,docker engine etc.

**Comment by mstanleyjones** [comment]
Please check out https://docs.docker.com/get-started/#container-diagram snd see if it helps.

**Comment by mstanleyjones** [comment]
Info provided.
