### ISSUE TITLE
404 at /engine/admin/reference/logging/plugins/

### ISSUE THREAD

**Issue by deivit78** [docker/docker.github.io#3665]
URL: /engine/admin/reference/logging/plugins/
404 at /engine/admin/reference/logging/plugins/ #3665

**Comment by mstanleyjones** [comment]
The correct URL is https://docs.docker.com/engine/admin/logging/plugins/. Where did you see the faulty URL?

**Comment by mstanleyjones** [comment]
I found it, see the attached PR. Thanks!
