### ISSUE TITLE
Running container with Docker Run using the flags -d and --rm

### ISSUE THREAD

**Issue by strund3r** [docker/docker.github.io#3666]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/), CC @mstanleyjones 

When talking about the `Detached (-d)` operator, it says that: 

>A container in detached mode cannot be automatically removed when it stops, this means you cannot use the --rm option with -d option.

But since the [PR #20848](https://github.com/moby/moby/pull/20848), it is allowed to use the flags -d and --rm together.

**Comment by mstanleyjones** [comment]
@thaJeztah where does this file live now?
