### ISSUE TITLE
Incorrect sytax

### ISSUE THREAD

**Issue by aglaberson** [docker/docker.github.io#3675]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/), CC @johndmulhausen

Hi,

While working my way through this wonderful tutorial I discovered the correct syntax to leave the swarm is:

docker swarm leave -f

as opposed to:

docker swarm leave --force.

Thanks! Anne

**Comment by johndmulhausen** [comment]
Thanks, @aglaberson. It turns out both are correct!

```
$ docker swarm leave --help

Usage:	docker swarm leave [OPTIONS]

Leave the swarm

Options:
  -f, --force   Force this node to leave the swarm, ignoring warnings
      --help    Print usage
```
