### ISSUE TITLE
Feedback for: toolbox/faqs/troubleshoot.md

### ISSUE THREAD

**Issue by ClearSpear** [docker/docker.github.io#368]
How do you change the settings of docker to run with 4 CPUs and 4GB of memory? I'm running from docker-toolbox in Windows 10.

**Comment by londoncalling** [comment]
@ClearSpear if you want Docker machines to run with those settings (4 CPUs and 4GB of memory), I believe you need to create machines with [these environment variables](https://docs.docker.com/machine/drivers/virtualbox/#/environment-variables-and-default-values). (See detail on [Oracle Virtual Box driver](https://docs.docker.com/machine/drivers/virtualbox/) and general steps to [create a machine](https://docs.docker.com/machine/get-started/#/create-a-machine).

Alternatively, you can find info on how to [allocate resources specifically per container](https://docs.docker.com/engine/reference/run/#/runtime-constraints-on-resources), in [Docker run reference](https://docs.docker.com/engine/reference/run/).

Let me know if this answers your questions.

@nathanleclaire @friism  @mstanleyjones @johndmulhausen any other input for this question before I close the issue?

**Comment by mstanleyjones** [comment]
LGTM. Later on if / when you decide to take advantage of Docker swarm services, you can customize your service to only run on nodes which meet certain conditions, including the amount of available CPU and RAM.

**Comment by nathanleclaire** [comment]
Yes, it depends on what @ClearSpear means, I'd guess they want to pass through 4 CPUs / 4GB memory to the VM -- @londoncalling you've covered this in your answer so I'd suggest closing the issue
