### ISSUE TITLE
Requirements Case Problem

### ISSUE THREAD

**Issue by michi-z** [docker/docker.github.io#3681]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen 

On my mac the example (friendlyhello) was not running. If i fix the lib names in the requirements.txt file to lowercase it works.

**Comment by londoncalling** [comment]
@michi-z I've run through the example on my Mac several times and it works as written. (It also works when I change the lib names to lowercase as you suggest which is weird to me because I believe they should be initial caps as shown.)

@johndmulhausen @mstanleyjones @ManoMarks any thoughts?

**Comment by ManoMarks** [comment]
I don't know what is going on with @michi-z 's setup, but Flask is always specified as "Flask" in a pip requirements.txt and at the commandline http://flask.pocoo.org/docs/0.12/installation/

**Comment by johndmulhausen** [comment]
No repro on our end, sorry.
