### ISSUE TITLE
No instructions for upgrading EE on Server 2016

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#3683]
File: [docker-ee-for-windows/install.md](https://docs.docker.com/docker-ee-for-windows/install/), CC @johndmulhausen

Instructions are available from the end of section 1: https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server#1-install-docker

> Tip: If you want to update Docker later:
> Check the installed version with `Get-Package -Name Docker -ProviderName DockerMsftProvider`
> Find the current version with `Find-Package -Name Docker -ProviderName DockerMsftProvider`
> When you're ready, upgrade with `Install-Package -Name Docker -ProviderName DockerMsftProvider -Update -Force`, followed by `Start-Service Docker`

**Comment by JimGalasyn** [comment]
We have a slightly different workflow documented here: [Update Docker EE](https://docs.docker.com/engine/installation/windows/docker-ee/#update-docker-ee).

```
PS> Unregister-PackageSource -ProviderName DockerMsftProvider -Name DockerDefault -Erroraction Ignore
PS> Register-PackageSource -ProviderName DockerMsftProvider -Name Docker -Erroraction Ignore -Location https://download.docker.com/components/engine/windows-server/index.json
PS> Install-Package -Name docker -ProviderName DockerMsftProvider -Update -Force

# Start the Docker service.
PS> Start-Service Docker
```

**Comment by joaofnfernandes** [comment]
@JimGalasyn feel free to close this if you think it's a non-issue.

**Comment by mbentley** [comment]
Yup, looks like it has been resolved elsewhere.
