### ISSUE TITLE
Bring back documentation about how to make an engine trust the self-signed certificate

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#3685]
File: [datacenter/dtr/2.2/guides/admin/configure/use-your-own-tls-certificates.md](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/use-your-own-tls-certificates/), CC @joaofnfernandes 

There is a lack of documentation that I could find about how you make an engine trust a self-signed certificate that comes with DTR.  UCP automatically adds the ca.crt to `/etc/docker/certs.d/<dtr-fqdn>/<dtr-fqdn>.crt` but most use cases have a central registry where the nodes aren't connected to the UCP cluster.

**Comment by joaofnfernandes** [comment]
I think this has been address by https://docs.docker.com/datacenter/dtr/2.4/guides/user/access-dtr/
