### ISSUE TITLE
Matching access labels for Services and Secrets

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#3686]
This doc does not mention matching access labels for services or secrets in order for them to work together. This is not the case for networks and services however.

File: [datacenter/ucp/2.1/guides/admin/manage-users/index.md](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/manage-users/), CC @joaofnfernandes

**Comment by JimGalasyn** [comment]
Thank you for the feedback! I'm closing this, because in UCP 2.2, managing access labels is handled by the new [RBAC model](https://docs.docker.com/datacenter/ucp/2.2/guides/access-control/).
