### ISSUE TITLE
machine "myvm2"  - "docker swarm join" command fails using generated join command string

### ISSUE THREAD

**Issue by MorrieAtElastic** [docker/docker.github.io#3689]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen

see https://github.com/docker/machine/issues/4064 

- the solution suggested there is to use port 2377 instead of 2376; this worked for me.

**Comment by johndmulhausen** [comment]
We also tell you to use docker 2377 on this page. @MorrieAtElastic

**Comment by johndmulhausen** [comment]
P.S. I think you did the right thing letting the Machine team know the generated message isn't useful. It's a common problem, which is why I got explicit about it when writing the tutorial. Thanks!
