### ISSUE TITLE
BSOD on Windows 10 with Hyper-V Enabled

### ISSUE THREAD

**Issue by NonCreature0714** [docker/docker.github.io#3694]
### Problem description

Trying to folow the instructions found at ["Set Up Your Swarm"](https://docs.docker.com/get-started/part4/#set-up-your-swarm) causes Windows 10 to fatally crash with a BSOD (Blue Screen of Death). This is a [long-time](https://www.virtualbox.org/ticket/15780), known [Virtualbox bug](https://www.virtualbox.org/ticket/16801), which Oracle (and I) assign blame to Microsoft.

*My issue* is that the documentation should be updated to reflect this critical error. (It's very unfortunate, because no one on windows 10 can complete the getting started guide.)

I have separately filed a [Docker Issue ](https://github.com/docker/machine/issues/4151)for the technical problem.

### Problem location

- I saw a problem on the following URL: <https://docs.docker.com/get-started/part4/#set-up-your-swarm>

### Project version(s) affected

docker-machine.exe version 0.10.0, build 76ed2a6

### Suggestions for a fix

Suggest some warning that attempting to run VirtualBox with Hyper-V enabled will cause a BSOD. Ironically, Docker requires Hyper-V enabled for itself to run.

**Comment by johndmulhausen** [comment]
@NonCreature0714 What command are you running that triggers the BSOD? If it's using `driver` of `virtualbox` instead of Hyper-V, that is not supported, which is why there are tabs and callouts on the "Set up your swarm" section.

**Comment by NonCreature0714** [comment]
@johndmulhausen I'm working to clarify. Frustratingly, following the recommended instructions caused BSOD three times yesterday - but today everything is running perfectly, so I'm struggling to reproduce. I did run into something else: using docker-machine with Powershell requires Powershell run as Administrator. 

I'm nervous to say much more if I can't reproduce the bug; I'll close this if I can't reproduce within 24 hours.

**Comment by NonCreature0714** [comment]
@johndmulhausen I should also mention that several people at my place of work also encountered this bug, but now can't reproduce.

**Comment by johndmulhausen** [comment]
@NonCreature0714 Keep me posted. At a high level: Does following the Hyper-V instructions work?

**Comment by NonCreature0714** [comment]
@johndmulhausen the Hyper-V instructions work. 

The best I can tell right now is that there was some conflict with running Vagrant and docker-machine in proximity on the same machine. Vagrant absolutely causes BSOD because of a bug in VirtualBox. And it's possible that when I ran docker-machine afterwards there was still some unresolved issue. I'm currently working to reproduce. Either way, this looks very much like an edge case.

I'm strongly advocating for Docker to internal operations/dev/IT clients, while at the same time as learning SaltStack (which uses Vagrant for tutorials). So I'm realizing now this isn't as clear cut as I thought it was. This was particularly frustrating, because I wasn't able to complete a Docker demo to my internal clients because of crashes.

**Comment by NonCreature0714** [comment]
@johndmulhausen I'm closing this ticket as un-reproducible. It appears it has something more to do with Vagrant.

**Comment by ghousseyn** [comment]
Sorry to revive this, but I have the same issue. Docker with Hyper-v disabled used to work fine before I updated to the latest version. Now it requires Hyper-v but causes a BSOD.
Version: 17.09.0-ce-win33 (13620) running on windows 10
Any ideas?

**Comment by librisius** [comment]
I also have this issue! Description: https://www.virtualbox.org/ticket/16801

**Comment by CamelCaseMaster** [comment]
@librisius & I are having the same problem: https://www.virtualbox.org/ticket/16801

**Comment by DialgicMew** [comment]
Sorry to reopen but i'm  having the sam issue. I'm using windows insider preview and docker desktop. Whenver i use docker desktop and then close docker desktop and then reboot as soon my pc reboots it goes into a BSOD HYPERVISOR_ERROR. I'm 100% sure it is docker causing the issue. please help

**Comment by maf1a** [comment]
same thing after increasing ram to 5 gb and giving 4 processor threads in the docker settings
