### ISSUE TITLE
link to docker completion file returns 404 Not found - needs update

### ISSUE THREAD

**Issue by gabbah** [docker/docker.github.io#3700]
File: [machine/completion.md](https://docs.docker.com/machine/completion/), CC @londoncalling

**Comment by mstanleyjones** [comment]
Fixed by #3701

**Comment by gabbah** [comment]
Under the Mac instructions, the link https://raw.githubusercontent.com/docker/docker-ce/master/components/engine/contrib/completion/bash/docker still returns 404, so anyone using that command will get a file with the contents "404 Not found" in it, instead of a working completion file.
Line 24 and 30.

**Comment by ShockN745** [comment]
True. My fix only was for the zsh version.
I updated with a new PR.
