### ISSUE TITLE
No explanation of setting up hosts

### ISSUE THREAD

**Issue by HeathNaylor** [docker/docker.github.io#3710]
File: [engine/swarm/swarm-tutorial/index.md](https://docs.docker.com/engine/swarm/swarm-tutorial/), CC @mstanleyjones

There is no explanation or supporting documentation for how to setup the 3 linux hosts that have docker installed on them.

**Comment by mstanleyjones** [comment]
Setting up Linux hosts is out of scope for Docker documentation. After you have set up the hosts (it's up to you), you can install Docker using the appropriate instructions for your distribution. See [Installation](https://docs.docker.com/engine/installation/).

**Comment by mstanleyjones** [comment]
You can even use Docker Machine from Docker for Mac or Docker for Windows. See [Getting Started -- Swarms](https://docs.docker.com/get-started/part4/#prerequisites).

**Comment by HeathNaylor** [comment]
Would it not make sense to use `docker machine` as it is described [here](https://docs.docker.com/get-started/part4/)?

**Comment by HeathNaylor** [comment]
I think the documentation should list that getting started guide when referencing the linux hosts.
