### ISSUE TITLE
--env example should explain how to set multiple env variables

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#3718]
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/), CC @mstanleyjones

In usability study user was looking at the docs and still confused on how to set 2 environment variables. He was trying
```
... --env MYSQL_DATABASE=wordpress MYSQL_USER=john
```

when he should be using

```
... --env MYSQL_DATABASE=wordpress --env MYSQL_USER=john
```

**Comment by mstanleyjones** [comment]
Well... let me see if I can figure out how to address this. This is more of soemthing about understanding how your shell works. You can't have a space like that. There are lots of flags where you have to specify a separate instance of the flag for each value. These are represented as arrays in the `daemon.json` or `docker-compose.yml` too.

**Comment by thaJeztah** [comment]
https://github.com/docker/cli/issues/289 was merged
