### ISSUE TITLE
Health check documentation 

### ISSUE THREAD

**Issue by mark-church** [docker/docker.github.io#372]
URL: [https://docs.docker.com/engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

Regarding https://docs.docker.com/engine/reference/builder/#/healthcheck

Can we add the following statement? 

Per @talex5  ...

> An unhealthy container will be considered healthy again after the first successful health check.

**Comment by talex5** [comment]
It already says:

> This status is initially starting. Whenever a health check passes, it becomes healthy (whatever state it was previously in). After a certain number of consecutive failures, it becomes unhealthy.

But feel free to make a PR if you find it unclear (it seems clear to me, but then I wrote it so not a good test).

**Comment by mstanleyjones** [comment]
This is reference documentation and so the source lives in `docker/docker`. Please raise a PR there if you feel like this needs to be addressed. Sorry for the confusion. We hope to make this less confusing very soon.
