### ISSUE TITLE
Unclear about `backing` option for CloudStor

### ISSUE THREAD

**Issue by hairyhenderson** [docker/docker.github.io#3750]
File: [docker-for-aws/persistent-data-volumes.md](https://docs.docker.com/docker-for-aws/persistent-data-volumes/), CC @johndmulhausen

At the top of the document, `backing` is defined:

> [...]In Docker for AWS, Cloudstor has two `backing` options:
> 
> - `relocatable` data volumes are backed by EBS.
> - `shared` data volumes are backed by EFS.

Later on, in the `Use a unique volume per task using EBS` section:

> [...]Besides `backing=local`, the following volume options are available:

And further, in one of the examples:

> ```
> [...],volume-opt=backing=local,[...]
> ```

Is `local` a valid value? Or should this be `relocatable`? If `local` is valid, it should be documented.

Thank you!

**Comment by friism** [comment]
cc @ddebroy

**Comment by ddebroy** [comment]
'local' is a doc error. Thanks for pointing it out!
