### ISSUE TITLE
Feedback for: compose/startup-order.md

### ISSUE THREAD

**Issue by raugustinus** [docker/docker.github.io#376]
URL: [https://docs.docker.com/compose/startup-order.md](https://docs.docker.com/compose/startup-order/)

It could be just me, but it took me some time to figure out why my added arguments to the wait-for-it.sh script made it fail. It was because of the shift command which I didn't know yet. You might mention this in the documentation?

**Comment by londoncalling** [comment]
@Stasmo Thanks for the feedback, and sorry for the delay.

I've added a tip regarding this in the PR referenced ^^. I was going to do more to remove the little script examples altogether, but it seems like they are nice to have there. Let me know what you think. This will be published tonight.

**Comment by Stasmo** [comment]
@londoncalling Did you mean to post in #123?

**Comment by londoncalling** [comment]
@Stasmo sorry, no I haven't gotten to that yet :-) I tagged you instead of @raugustinus
