### ISSUE TITLE
Switch Mac / MacPosts Bash Completion .bash_profile content

### ISSUE THREAD

**Issue by vthyng** [docker/docker.github.io#3764]
File: [compose/completion.md](https://docs.docker.com/compose/completion/), CC @londoncalling 
It looks like the statements to add to .bash_profile are reversed for 'Bash' and 'MacPorts Bash Completion'.  Brew is a mac command and not found on linux distros.  I get this error when I try the docs as written on my ubuntu 16.0.4 system:
source .bash_profile 
No command 'brew' found, did you mean:
 Command 'brec' from package 'bplay' (universe)
 Command 'qbrew' from package 'qbrew' (universe)

**Comment by londoncalling** [comment]
@shin- @dnephin  @mstanleyjones Can you guys take a look at this? I cannot find anything wrong with the referenced docs topic statements. Am I missing something?

**Comment by shin-** [comment]
@londoncalling In the `Bash` section, the part after the `curl` command only applies to Mac environments (`brew` doesn't exist on Linux), but it isn't really clear when reading the document.
