### ISSUE TITLE
Make a note within the security section of engine regarding Docker's stance on anti-virus and recommendations surrounding it

### ISSUE THREAD

**Issue by squizzi** [docker/docker.github.io#3766]
### Problem description
Customer encountered issues with hanging docker commands that appeared to be associated with them running anti-virus in their environment, specifically in this instance, McAfee LinuxShield. 

The problems they encountered resulted in https://github.com/docker/orca/issues/7375.  Troubleshooting this problem was very difficult from both a support and engineering perspective, this issue even resulted in the customer requesting an onsite support engagement to troubleshoot. 

The resolution was a relatively easy fix which entailed setting `/var/lib/docker` as an exclusion within the anti-virus.

This is a common practice for many anti-virus/malware tools.  Many of them feature an exclusion option which allows users to specify files and directories which should not be scanned.

I feel we should make a note of this in our documentation, perhaps in the security section.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://github.com/docker/docker.github.io/blob/master/engine/security/index.md

### Suggestions for a fix

Provide a blurb somewhere within the Prerequisites documentation that discusses Docker's stance on anti-malware, specifically our recommendations on what exclusions to set to prevent anti-virus from getting in the way of Docker engine's operation. 

The recommendation I would make is to have customers set an exclusion in their anti-virus for the `/var/lib/docker` dirtree.  Most anti-virus offerings provide a way to exclude scanning on certain directories.

**Comment by mstanleyjones** [comment]
Is this really a security best practice? What if a virus does get into `/var/lib/docker/`? What if they run an infected Windows container? Not sure who to ping on this so starting with @cyli.

**Comment by cyli** [comment]
Maybe we can just document this as a troubleshooting issue?  It does seem from googling around that some virus scanners can lock up files for extended periods of time, but I'd hesitate to document this as a pre-requisite before doing some more investigation on which scanners may be problematic, and get some numbers.

For instance, here's Microsoft's help page on virus scanning:  https://support.microsoft.com/en-us/help/822158/virus-scanning-recommendations-for-enterprise-computers-that-are-runni - they do suggest that excluding certain files will probably improve stability, but they have a ton of caveats.

**Comment by mstanleyjones** [comment]
So at the least, we need someone to give us these requirements. @riyazdf or @NathanMcCauley thoughts?

**Comment by riyazdf** [comment]
I agree with @cyli that this is more related to troubleshooting than security configuration, if requiring any additional documentation section at all. Unfortunately I don't have any additional context on the state of anti-virus compatibility with Docker, so I'm not sure how this would troubleshooting section would look.
