### ISSUE TITLE
The bash completion script does not work in RHEL 7 on AWS

### ISSUE THREAD

**Issue by hseritt** [docker/docker.github.io#3778]
File: [machine/completion.md](https://docs.docker.com/machine/completion/), CC @londoncalling

**Comment by mstanleyjones** [comment]
Can you give more details about "does not work"?

**Comment by hseritt** [comment]
Yeah stupid me :-) I thought for sure the bash_completion package was installed on RHEL7 (docker image) but evidently not.

**Comment by mstanleyjones** [comment]
I'm glad you figured it out!
