### ISSUE TITLE
Adapt docs to version 17.06

### ISSUE THREAD

**Issue by johannesbrunner-wd** [docker/docker.github.io#3803]
File: [engine/installation/windows/docker-ee.md](https://docs.docker.com/engine/installation/windows/docker-ee/), CC @mstanleyjones 

The docs describes how to install version 17.03 event the select version on the top right corner is 17.06. Please correct the docs according docker version 17.06

**Comment by thaJeztah** [comment]
Docker 17.06 EE (Enterprise Edition) was not yet released; only Docker 17.06 CE (Community Edition). Enterprise Edition usually arrives a couple of weeks after CE

**Comment by johannesbrunner-wd** [comment]
No idea why this issue was closed. It is definitly still an issue and should stay open.
Correct solution will be a description that docker ee 17.06 is currently not released.
The reader of the docs should please check out version 17.03 which is the current version for docker ee.
But acting like this would be version 17.06 (which is not, it is 17.03) is totally confusing, a common source for errors and leads to frustation and discussions by the end users, which all could be avoided easily.

**Comment by mstanleyjones** [comment]
Docker EE 17.06 will be based on Docker EE 17.06 when it is released. Docker EE 17.06 does not yet exist. So there is really nothing to write. We could just as easily talk about Docker EE 17.09 which also has not been released yet. 

cc/ @joaofnfernandes who works more on the EE docs.

**Comment by joaofnfernandes** [comment]
@johndmulhausen, @hansfrederickbrown for visibility
