### ISSUE TITLE
Please add offline documentation

### ISSUE THREAD

**Issue by InteXX** [docker/docker.github.io#3808]
File: [index.md](https://docs.docker.com/), CC @johndmulhausen 

In much of the world, Internet speeds are still very slow. It becomes a laborious click-and-wait task to read the Docker documentation.

A download link for a PDF version of your documentation will be very helpful.

**Comment by AyushyaChitransh** [comment]
Did you know that you can clone this repo and deploy the website on your system?

**Comment by InteXX** [comment]
@AyushyaChitransh — Thank you. I should have thought of that.

**Comment by thaJeztah** [comment]
There's also pre-built images of the documentation on Docker Hub; https://hub.docker.com/r/docs/docker.github.io/tags/

**Comment by InteXX** [comment]
@thaJeztah — Very good, thank you.

**Comment by InteXX** [comment]
@AyushyaChitransh — I've cloned the repo, but the files are written in Markdown. Can you recommend a suitable Markdown server for Windows?

**Comment by InteXX** [comment]
@AyushyaChitransh — I'm reopening due to problems getting the cloned repo to work. I tried it using [Harp](http://harpjs.com/docs/development/markdown), a Node.js markdown server, but that doesn't work. My next attempt was with `docker-compose`, as indicated in the [repo documentation](https://github.com/docker/docker.github.io#staging-the-docs), but I get a `docker-compose error`:

> D:\Dev\Git\docker.github.io>docker-compose up
ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

I'm afraid I've hit a dead-end; I don't know how to proceed from here. The `docker-compose` [change log](https://github.com/docker/compose/releases) indicates that the latest stable version is v1.14.0, which is a lower version number than what is indicated as required in the error message.

I'm running the latest version of Docker on my Win10 workstation. I updated yesterday.

Please advise.

**Comment by InteXX** [comment]
@thaJeztah — Would you describe this further. How would I obtain these images and how would I use them to view the documentation in Chrome on my Windows 10 desktop?

**Comment by AyushyaChitransh** [comment]
Hello @InteXX if you are having problems with using `harp`, you can use Jekyll as described in the Option 2 of `Staging the docs` section of [Readme](https://github.com/docker/docker.github.io).

If you want further details, currently there were some problems with the gems which have most probably been fixed with a pr, and [this discussion](https://github.com/docker/docker.github.io/issues/3316) might be useful to you.

**Comment by InteXX** [comment]
@AyushyaChitransh — Thank you for following up.

I've rebooted in the meantime, and it seems to be working now. I can browse to [http://localhost:4000/](http://localhost:4000/), but no content of any value is rendered. I get only an empty directory listing:

![image](https://user-images.githubusercontent.com/10966749/28289766-6ce2ca10-6af0-11e7-89ac-f7e17b06c4ae.png)

Here's my `docker-compose` output:
<pre>
D:\Dev\Git\docker.github.io>docker-compose up
Creating dockergithubio_docs_1 ...
Creating dockergithubio_docs_1 ... done
Attaching to dockergithubio_docs_1
docs_1  | Configuration file: none
docs_1  | Configuration file: none
docs_1  |             Source: /usr/src/app
docs_1  |        Destination: /_site
docs_1  |  Incremental build: disabled. Enable with --incremental
docs_1  |       Generating...
docs_1  |                     done in 0.017 seconds.
docs_1  |  Auto-regeneration: enabled for '/usr/src/app'
docs_1  | Configuration file: none
docs_1  |     Server address: http://0.0.0.0:4000/
docs_1  |   Server running... press ctrl-c to stop.
docs_1  | [2017-07-17 20:58:02] ERROR `/favicon.ico' not found.
</pre>

Is the URL supposed to display the documentation?

**Comment by AyushyaChitransh** [comment]
Yes! It should be displaying the home page of documentation. This looks strange to me. I'll see if I can reproduce this behavior.

**Comment by AyushyaChitransh** [comment]
Try getting a shell access and see if there is any content inside `/usr/src/app` of  the container.

**Comment by InteXX** [comment]
> Try getting a shell access

How is this done (on Windows)?

**Comment by AyushyaChitransh** [comment]
`docker ps` will list the containers on the machine. From there find the required container.

`docker exec -it <container_id_or_name> bash` will get shell access into the container.

[How to get into a docker container](https://stackoverflow.com/questions/30172605/how-to-get-into-a-docker-container)

**Comment by InteXX** [comment]
<pre>
C:\Users\Admin>docker exec -it 863a59969066 bash
root@863a59969066:/usr/src/app# ls
root@863a59969066:/usr/src/app# dir
root@863a59969066:/usr/src/app#
</pre>

So, it looks like... no. No content.

**Comment by AyushyaChitransh** [comment]
You need to verify the `docker-compose.yml` file which you will find in the working directory itself. And make sure you cloned the repo properly. Also you may look around for any problems associated with mounting the directories in windows.

Expected behavior:
You must be able to find all the content of the repository inside the `usr/src/app`  directory.

**Comment by InteXX** [comment]
Here's my `docker-compose.yml` file:

```
version: "2.1"
services:
  docs:
    image: docs/docstage
    ports:
     - "4000:4000"
    volumes:
     - "./:/usr/src/app"
```
I'm not yet confident in my Git knowledge, so I used Visual Studio 2017's GitHub add-in to do the clone. I can only assume that it was done correctly—I don't know how to verify this.

> Also you may look around for any problems associated with mounting the directories in windows.

Do you have any suggestions as to how I may do so?

**Comment by AyushyaChitransh** [comment]
According to `docker-compose.yml` file, all files present inside `docker.github.io` folder should be available inside the `usr/src/app` folder inside container. You still aren't having any content inside `usr/src/app`. That makes me assume that the mount is unable to happen. This should throw some error. 

As from your output which you gave earlier, I see that you are not getting any errors when you run `docker-compose up`. You could look for reasons why you are unable to see mounted files inside container. StackOverflow might be a place where you could find answers to this or see if googling helps.

**Comment by InteXX** [comment]
Does this tell you anything?

```
C:\Users\Admin>docker inspect 863a59969066
[
    {
        "Id": "863a59969066444d0b6e908a46d0f05b68605b7fe72bfd4b0ddf2036847b0779",
        "Created": "2017-07-17T20:57:06.7250794Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "jekyll serve -d /_site --watch -H 0.0.0.0 -P 4000"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 3252,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-07-17T20:57:08.0003358Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:9670258d73f081ef2c7dd476c56fc5945627ee68867e1296fbe19e612ddd29a4",
        "ResolvConfPath": "/var/lib/docker/containers/863a59969066444d0b6e908a46d0f05b68605b7fe72bfd4b0ddf2036847b0779/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/863a59969066444d0b6e908a46d0f05b68605b7fe72bfd4b0ddf2036847b0779/hostname",
        "HostsPath": "/var/lib/docker/containers/863a59969066444d0b6e908a46d0f05b68605b7fe72bfd4b0ddf2036847b0779/hosts",
        "LogPath": "/var/lib/docker/containers/863a59969066444d0b6e908a46d0f05b68605b7fe72bfd4b0ddf2036847b0779/863a59969066444d0b6e908a46d0f05b68605b7fe72bfd4b0ddf2036847b0779-json.log",
        "Name": "/dockergithubio_docs_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/D/Dev/Git/docker.github.io:/usr/src/app:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "dockergithubio_default",
            "PortBindings": {
                "4000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "4000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/8f7ba6861640a6fb639f64c475db0260cb4c9ded686711b05625ff37c19737fa-init/diff:/var/lib/docker/overlay2/0772e69f7faba8d149e7d9aed149d4607c905f1d01b28b97f5453772e5326904/diff:/var/lib/docker/overlay2/6d2a854de0c3c7af4e8e3b6ef831af1dde8c400f5aa8fd809d76a06f3ba5c705/diff:/var/lib/docker/overlay2/8a4466b60f60d0141625c1ad32233f3fee49821f534f8709685c2d6514b9d3f6/diff:/var/lib/docker/overlay2/6a4fe33cae424e9a671300332244aa19f5a314d90c945b399f35ea487e01d333/diff:/var/lib/docker/overlay2/de35de0b23cb93e811a7f2ec6b59e3e282faf770131179c60cad588c522551be/diff:/var/lib/docker/overlay2/e7f896a4b4d0da7ddbddd208a9130affea2358f4b1fd147f403b82fe7fe748aa/diff:/var/lib/docker/overlay2/b09694bfeb6b2e7d75de351286d95bf9af18181004f9d3c2d9bf73ea6538ba56/diff:/var/lib/docker/overlay2/4feb0e4dccefd6570fee715baf80ebe6ea77ab133cc3ac15fd850bb737f7e8b2/diff:/var/lib/docker/overlay2/1291c76b0bb03c133b70dad4dd08147f3c753b52f8ac3070d2e0f9bbdd99e874/diff:/var/lib/docker/overlay2/9166f2a32c7b3284fab5a95803ac66c83cba936161083f0405b630178f5dbeb2/diff:/var/lib/docker/overlay2/46499476944e8234be84f662104f3968f8717f3e36a67bb06d814f9c70998d9f/diff:/var/lib/docker/overlay2/fc1f9d566f52e9f994bd02dd73528fb3402a98a2618c5b3a9dbf10c8c5ae554c/diff",
                "MergedDir": "/var/lib/docker/overlay2/8f7ba6861640a6fb639f64c475db0260cb4c9ded686711b05625ff37c19737fa/merged",
                "UpperDir": "/var/lib/docker/overlay2/8f7ba6861640a6fb639f64c475db0260cb4c9ded686711b05625ff37c19737fa/diff",
                "WorkDir": "/var/lib/docker/overlay2/8f7ba6861640a6fb639f64c475db0260cb4c9ded686711b05625ff37c19737fa/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/D/Dev/Git/docker.github.io",
                "Destination": "/usr/src/app",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "863a59969066",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "RUBY_MAJOR=2.3",
                "RUBY_VERSION=2.3.3",
                "RUBY_DOWNLOAD_SHA256=241408c8c555b258846368830a06146e4849a1d58dcaf6b14a3b6a73058115b7",
                "RUBYGEMS_VERSION=2.6.8",
                "BUNDLER_VERSION=1.13.6",
                "GEM_HOME=/usr/local/bundle",
                "BUNDLE_PATH=/usr/local/bundle",
                "BUNDLE_BIN=/usr/local/bundle/bin",
                "BUNDLE_SILENCE_ROOT_WARNING=1",
                "BUNDLE_APP_CONFIG=/usr/local/bundle",
                "NPM_CONFIG_LOGLEVEL=info",
                "NODE_MAJOR_VERSION=4",
                "GITHUB_GEM_VERSION=112"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "jekyll serve -d /_site --watch -H 0.0.0.0 -P 4000"
            ],
            "ArgsEscaped": true,
            "Image": "docs/docstage",
            "Volumes": {
                "/usr/src/app": {}
            },
            "WorkingDir": "/usr/src/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "f86127819d2d94cf924f8d7ef0fe8579286043aebafc2940e6ca0b1d1b4828b7",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "dockergithubio",
                "com.docker.compose.service": "docs",
                "com.docker.compose.version": "1.14.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b6ad8a59f8f902f5a2fff0e4d6656bed6b3ecf1904424504886543614524f570",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4000"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/b6ad8a59f8f9",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "dockergithubio_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "docs",
                        "863a59969066"
                    ],
                    "NetworkID": "8c5980632aa0810c818544573e76247a7b27f95e86d137e5f755cbff5b16b6aa",
                    "EndpointID": "ead13e880ebeede298f16c912d4eac0f5eb89ec5600da208202d54868273927d",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

```

**Comment by InteXX** [comment]
@AyushyaChitransh — With a tip from [BMitch](https://stackoverflow.com/a/45155325/722393), I discovered why the local folder wasn't getting mounted: it was my Norton firewall.

![image](https://user-images.githubusercontent.com/10966749/28297111-8dc32da6-6b18-11e7-9391-7b7279e4b367.png)

But I temporarily disabled it and now we're back to the earlier error:

```
D:\Dev\Git\docker.github.io>docker-compose up
Creating network "dockergithubio_default" with the default driver
Creating dockergithubio_docs_1 ...
Creating dockergithubio_docs_1 ... done
Attaching to dockergithubio_docs_1
docs_1  | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:366:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'github-pages (= 137)' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:341:in `each'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:341:in `verify_gemfile_dependencies_are_found!'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:199:in `start'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:181:in `resolve'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
docs_1  |       from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
docs_1  |       from /usr/local/bundle/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
docs_1  |       from /usr/local/bundle/gems/jekyll-3.3.1/exe/jekyll:9:in `<top (required)>'
docs_1  |       from /usr/local/bundle/bin/jekyll:22:in `load'
docs_1  |       from /usr/local/bundle/bin/jekyll:22:in `<main>'
dockergithubio_docs_1 exited with code 1
```

I'm working on Option #2 now, but frankly I'm not giving it much hope. I'll report results back here.

**Comment by InteXX** [comment]
To my pleasant surprise, it works. I proceeded with [Option #2](https://github.com/docker/docker.github.io#staging-the-docs), installing and configuring Ruby. The documentation generation task took several minutes, but when it was done the website popped right up on port 4000. Good news. Good job.

You may recall my earlier comment that I need to run Windows containers; this configuration isn't suitable for my working environment. But that's OK—I can `git clone` the repo to a new Linux VM I'll create on my Hyper-V host. (Linux containers running directly on Windows [aren't quite ready yet](https://redmondmag.com/articles/2017/04/20/windows-server-2016-getting-linux-containers.aspx).)

From there I'll just expose the service to my internal network on a port of my choosing.

So my question is this: to maintain this documentation, is it simply a matter of using Git to obtain the latest files from the repo? Is this all I have to do? The guidance for [Option #2](https://github.com/docker/docker.github.io#staging-the-docs) seems to indicate that `jekyll` continually builds and rebuilds the website from new and changed files.

**Comment by AyushyaChitransh** [comment]
It seems that you have figured out how to build docker documentation offline using `jekyll` as described in  [Option #2](https://github.com/docker/docker.github.io#staging-the-docs). 

Answer to your question: Once you have done `git clone`, `git pull` will help you in keeping the docs updated. That's all you have to do. And changes that are made to files, are reflected instantly in the running instance.

**Comment by InteXX** [comment]
> That's all you have to do. And changes that are made to files, are reflected instantly in the running instance.

Excellent. Thank you. I appreciate all your help on this one.

One final quick question (related, I think): how to specify the listening port? Now that we're using `jekyll` instead of `docker-compose`, I think the `docker-compose.yml` file no longer applies here.

**Comment by InteXX** [comment]
@AyushyaChitransh — I've been able to instruct Jekyll to listen on a port other than its default (4000). I added a `port: 81` directive to the main section of the `_config.yml` and issued a `jekyll serve` command. The documentation is now running on port 81.

Thanks again for all your help.
