### ISSUE TITLE
CLI restructuring as of 1.13 and preferred syntax

### ISSUE THREAD

**Issue by dap6000** [docker/docker.github.io#3819]
I picked this page out as a specific instance of a wider issue. 

According to the blog post [Introducing Docker 1.13](https://blog.docker.com/2017/01/whats-new-in-docker-1-13/) under the section "CLI restructured" several commands have been regrouped under the logical object it's interacting with. For example `docker start my_container` and `docker container start my_container` are functionally equivalent. And both are documented. 

However, in light of sentence that closes the relevant section of the blog post: 

> The old command syntax is still supported, but *we encourage everybody to adopt the new syntax*. (Emphasis added)

1. Should the docs cross-link the old and new syntax?
2. Should the docs express a preference for the new syntax over the old syntax?
3. Should we develop a standard way of addressing these sorts of syntax changes among versions?

If the community agrees this is an issue worth addressing I will happily make the edits and file PR(s) as I'm reading my way through the documentation as someone fairly new to Docker. But, as someone fairly new to Docker, I won't assume filing a bunch of PRs in this area would actually be helpful without some input from the community. 

What do y'all think? 

File: [engine/reference/commandline/start.md](https://docs.docker.com/engine/reference/commandline/start/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
cc/ @thaJeztah 

We have discussed this a few times now, and while we do like the more verbose syntax for making it obvious which type of object is being operated on, there are some Docker commands that are just part of Docker lore / brand (like `docker run`) that we don't want to change. I'm not sure what the best way to move forward on this is. Specifically for the CLI references, we generate those through an automated process and we would like to be able to detect that a command is an "alias" of another command use redirects or some other way to consolidate them, but we are not there yet.

**Comment by mstanleyjones** [comment]
We are tracking this elsewhere. #3031
