### ISSUE TITLE
Clarify the phrase "(unless the system time is mounted)"

### ISSUE THREAD

**Issue by bryceryan-docker** [docker/docker.github.io#3825]
File: [datacenter/dtr/2.2/guides/admin/configure/garbage-collection.md](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/garbage-collection/), CC @joaofnfernandes 

I've never heard the phrase "system time is mounted" in documentation or in ordinary usage by system operators. I suggest rephrasing this, clarifying it, or using more commonly used language to describe the concept.

**Comment by joaofnfernandes** [comment]
That sentence is just adding confusion and can be deleted, since I don't think you can configure DTR containers with a different timezone.
