### ISSUE TITLE
Disable automatic language detection in *.md

### ISSUE THREAD

**Issue by rillig** [docker/docker.github.io#383]
On https://docs.docker.com/engine/tutorials/usingdocker/, the output of `docker version` has some words written normally, some are bold and numbers are colored. This is confusing, since this should be just plain text.

Therefore, each code block in the documentation should have its proper programming language declared, to allow for accurate syntax highlighting.

**Comment by mstanleyjones** [comment]
The best way is to have it default to `none`, I think.

**Comment by johndmulhausen** [comment]
Page has been taken down.
