### ISSUE TITLE
Typos in api docs

### ISSUE THREAD

**Issue by coolsvap** [docker/docker.github.io#3836]
### Problem description

Typos in api docs
### Problem location

https://github.com/docker/docker.github.io/blob/master/apidocs/docker-cloud/index.html

**Comment by londoncalling** [comment]
@KickingTheTV @pkennedyr Can we address these typos in Cloud API? If you let me know the repo, I can do it if you want, but I don't know where these files are.

**Comment by coolsvap** [comment]
@londoncalling I can create specific commits for those. I am yet to start reviewing those.

**Comment by londoncalling** [comment]
@coolsvap thank you!! Let me know if there is anything else I can do to help, or if you want me to be able to address these in future, you can let me know where the files are. Thanks again.

**Comment by johndmulhausen** [comment]
Closing as handled. Thanks, all!
