### ISSUE TITLE
Double warning text in docs

### ISSUE THREAD

**Issue by adriel** [docker/docker.github.io#3838]
File: [engine/installation/linux/docker-ce/debian.md](https://docs.docker.com/engine/installation/linux/docker-ce/debian/), CC @mstanleyjones

Warning has doubled up at:
"Warning: Warning: If you have multiple Docker repositori..."

I would submit a pull request with the fix, but I'm not sure what the correct syntax would be too bold the Warning without duplicating it.

**Comment by mstanleyjones** [comment]
This is a super annoying bug. Some CSS rules got introduced that cause this. We need to figure out the best way to tackle it throughout the docs. @londoncalling @johndmulhausen do you have thoughts?
