### ISSUE TITLE
Feedback for: engine/reference/commandline/node_ps.md

### ISSUE THREAD

**Issue by twang2218** [docker/docker.github.io#384]
URL: [https://docs.docker.com/engine/reference/commandline/node_ps.md](https://docs.docker.com/engine/reference/commandline/node_ps/)

In the `filter` section:

``` bash
$ docker node ps -f "label=usage"
ID                         NAME     SERVICE  IMAGE        LAST STATE          DESIRED STATE  NODE
b465edgho06e318egmgjbqo4o  redis.6  redis    redis:3.0.6  Running 10 minutes  Running        swarm-manager1
bg8c07zzg87di2mufeq51a2qp  redis.7  redis    redis:3.0.6  Running 9 minutes   Running        swarm-manager1
```

Which labels are the `docker node ps -f` filter on? It's `container label`? `service label`? `node label`?

The statement said: 

```
The label filter matches tasks based on the presence of a label alone or a label and a value.
```

Is there a `task label`? I didn't find any command can add a `task label` to a task.

**Comment by mstanleyjones** [comment]
This is a good question. Unfortunately this doc is not maintained in the `docker.github.io` repo, but in `docker/docker`, so if a change needs to be made, it will need to be there. Maybe @aaronlehmann or @stevvooe can help to clarify the answer here, and then I'll update the reference.

**Comment by stevvooe** [comment]
`label` will apply to the node label, since this is for a node-oriented command. Node labels are set via `node update`.

These are distinct from engine labels, which can be matched with `engine.label`, I believe.

@thaJeztah can provide more details and possibly some clarification.

**Comment by thaJeztah** [comment]
@stevvooe no, actually for `node ls` that should be the case (but see https://github.com/docker/docker/issues/28209), but `node ps -f` filters the _tasks_ on the node, not the _node_

You specify the _node_ as (optional in 1.13) parameter;

```
docker node ps some-node
```

That shows all the tasks running on the node, which can be filtered using the `-f`.

> Is there a `task label`? I didn't find any command can add a `task label` to a task.

Each task is a container; so the labels filtered on is the `--container-label` on `docker service create` (and `docker service update`)

I wonder when we should use "task" and when "container", it looks like we're not consistent there

@stevvooe @mstanleyjones any thoughts on that?

**Comment by mstanleyjones** [comment]
I don't have insight on that, but I am going to close this issue because I think this is a bigger issue than docs, and is more about the terminology we want to use when talking about swarm tasks / containers in Docker overall. Please raise an issue in `docker/docker` as appropriate, @twang2218.
