### ISSUE TITLE
Missing configuration.md

### ISSUE THREAD

**Issue by jdavisp3** [docker/docker.github.io#3844]
### Problem description

Links in the documentation to https://github.com/docker/docker.github.io/blob/master/registry/configuration.md are broken, there is no such file.

### Problem location

- I saw a problem on the following URL: https://github.com/docker/docker.github.io/blob/master/registry/deploying.md

**Comment by johndmulhausen** [comment]
It forwards to the right place on https://docs.docker.com/registry/deploying/
