### ISSUE TITLE
Automated Builds with Limited Access

### ISSUE THREAD

**Issue by costa** [docker/docker.github.io#3845]
File: [docker-hub/builds.md](https://docs.docker.com/docker-hub/builds/), CC @johndmulhausen

I can't seem to find the way to add GitHub webhooks for DockerHub manually.

**Comment by joaofnfernandes** [comment]
I'm not sure what you're trying to achieve, but have you tried checking in Docker Cloud
https://docs.docker.com/docker-cloud/builds/automated-build/

**Comment by johndmulhausen** [comment]
@costa As documented here: https://docs.docker.com/docker-hub/webhooks/

Go to: https://hub.docker.com/r/<USERNAME>/<REPOSITORY>/~/settings/webhooks/

:)
