### ISSUE TITLE
enable_ipv6 not recognized from version 3.0

### ISSUE THREAD

**Issue by jorhett** [docker/docker.github.io#3846]
### Problem description

The documentation labeled *Compose file version 3 reference* documents and shows examples with the `enable_ipv6` directive, however it is not supported in version 3 and above.

Originally reported with examples in docker/compose#4958

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/compose/compose-file/

### Project version(s) affected

Composer file format 3 and above

**Comment by mstanleyjones** [comment]
@shin- do you have info on this?

**Comment by shin-** [comment]
@mstanleyjones `enable_ipv6` is currently only available in v2.x - There's no support for it in v3 as it requires support in Swarm mode first.
