### ISSUE TITLE
The option --scope is not supported by docker network create

### ISSUE THREAD

**Issue by huikang** [docker/docker.github.io#3853]
The doc is incorrect in listing the option ``--scope`` for ``docker network create`` command

File: [engine/reference/commandline/network_create.md](https://docs.docker.com/engine/reference/commandline/network_create/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
The CLI reference is generated using Docker 17.06, in which `--scope` is definitely a supported flag. If you're not using 17.06, please use the doc archive for the Docker version you are using. See https://docs.docker.com/docsarchive/ to choose your archive link. Thanks!
