### ISSUE TITLE
dockerd configuration reloading section missing options that get reloaded

### ISSUE THREAD

**Issue by edmorley** [docker/docker.github.io#3854]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/), CC @mstanleyjones 

Hi!

The configuration reloading section here lists which prefs are reloaded when the dockerd process receives a `SIGHUP`:
https://docs.docker.com/engine/reference/commandline/dockerd/#configuration-reloading

However it appears there are a few entries missing from that list, such as:
* Daemon shutdown timeout 
* Insecure registries
* Registry mirrors

For the full list of settings that get reloaded, see:
https://github.com/moby/moby/blob/master/daemon/reload.go

Many thanks!

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #590](https://github.com/docker/cli/issues/590) via [**ZenHub**](https://www.zenhub.com/)
