### ISSUE TITLE
Advanced contributing: Design proposal section refers to two different repos

### ISSUE THREAD

**Issue by edmorley** [docker/docker.github.io#3857]
File: [opensource/workflow/advanced-contributing.md](https://docs.docker.com/opensource/workflow/advanced-contributing/), CC @johndmulhausen 

The [design proposal](https://docs.docker.com/opensource/workflow/advanced-contributing/#design-proposal) section says:

> The design proposals are all online in our GitHub pull requests.

...where the linked text points to:
https://github.com/docker/docker.github.io/pulls

However the rest of the section says to clone docker/docker instead, and add the proposal there. Looking at both repos I'm struggling to see any open proposals in either where people have created the `foo-proposal.md` file as it instructs? 

Is this process still correct? If so, which repo should be used?

Many thanks :-)

**Comment by joaofnfernandes** [comment]
@thaJeztah the [contribution guide](https://docs.docker.com/opensource/workflow/advanced-contributing/) seems to be a bit outdated too, since it still talks about `docker/docker` instead of `moby/moby`.
Can you take a look into this once you have spare cycles?

**Comment by mstanleyjones** [comment]
Closed in favor of #2625
