### ISSUE TITLE
Can you fix the URL for the correct page to download the CE image?

### ISSUE THREAD

**Issue by andersab** [docker/docker.github.io#3858]
File: [engine/installation/linux/docker-ce/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/), CC @mstanleyjones

W: Failed to fetch https://download.docker.com/linux/ubuntu/dists/jessie/stable/binary-amd64/Packages  HttpError404

**Comment by mstanleyjones** [comment]
Sorry, `jessie` is a Debian version, not Ubuntu. Try downloading something from https://download.docker.com/linux/debian/dists/jessie/.
