### ISSUE TITLE
important link is not working

### ISSUE THREAD

**Issue by fandonov** [docker/docker.github.io#3868]
File: [engine/installation/linux/docker-ce/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/), CC @mstanleyjones 
In the document is written to add Docker’s official GPG key by doing this
 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
The problem is, that the link https://download.docker.com does not exist. If the URL is changed, please update, because now is basically impossible to download Docker CE for Ubuntu

**Comment by mstanleyjones** [comment]
It definitely does exist. I just downloaded the `gpg` file by clicking on the link itself. You can also go to  https://download.docker.com/linux/ubuntu/ and see the `gpg` file there. What error are you getting?

**Comment by fandonov** [comment]
curl: (6) Could not resolve host: download.docker.com
[sudo] password for felipe: 
gpg: no valid OpenPGP data found.

From the browser:
Server not found

Firefox can’t find the server at download.docker.com.

    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

wget:
wget https://download.docker.com/linux/ubuntu/gpg
--2017-07-13 21:00:43--  https://download.docker.com/linux/ubuntu/gpg
Resolving download.docker.com (download.docker.com)... failed: Name or service not known.

ping: 
ping download.docker.com
PING d2h67oheeuigaw.cloudfront.net (52.85.180.97) 56(84) bytes of data.
64 bytes from server-52-85-180-97.fra50.r.cloudfront.net (52.85.180.97): icmp_seq=1 ttl=247 time=180 ms

**Comment by mstanleyjones** [comment]
You should confirm your DNS settings are working. Ping @andrewhsu

**Comment by fandonov** [comment]
curl: (6) Could not resolve host: download.docker.com
[sudo] password for felipe: 
gpg: no valid OpenPGP data found.

From the browser:
Server not found

Firefox can’t find the server at download.docker.com.

    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

wget:
wget https://download.docker.com/linux/ubuntu/gpg
--2017-07-13 21:00:43--  https://download.docker.com/linux/ubuntu/gpg
Resolving download.docker.com (download.docker.com)... failed: Name or service not known.

ping: 
ping download.docker.com
PING d2h67oheeuigaw.cloudfront.net (52.85.180.97) 56(84) bytes of data.
64 bytes from server-52-85-180-97.fra50.r.cloudfront.net (52.85.180.97): icmp_seq=1 ttl=247 time=180 ms

If you can open it it sounds like problem on my end, but I have no firewall, no strange network settings and don't have any problems with anything else. Is it possible my IP to be banned from the hosting/cloud provider, where the site is hosted?

**Comment by andrewhsu** [comment]
@fandonov The `wget` seems to work for me:
```
$ wget https://download.docker.com/linux/ubuntu/gpg
--2017-07-24 20:04:25--  https://download.docker.com/linux/ubuntu/gpg
Resolving download.docker.com (download.docker.com)... 54.230.19.172, 54.230.19.220, 54.230.19.239, ...
Connecting to download.docker.com (download.docker.com)|54.230.19.172|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3817 (3.7K) [binary/octet-stream]
Saving to: ‘gpg’

gpg                           100%[=================================================>]   3.73K  --.-KB/s    in 0s      

2017-07-24 20:04:25 (960 MB/s) - ‘gpg’ saved [3817/3817]
```

From your `ping` output seems like the dns is resolving `download.docker.com` for you. Something is not working for you when you try your `wget`. From the server side, there has been no downtime reported in resolution of `download.docker.com`. Perhaps check your network settings?

**Comment by mstanleyjones** [comment]
We are unable to replicate this problem.
