### ISSUE TITLE
Feedback for: docker-for-windows/index.md

### ISSUE THREAD

**Issue by mozowski** [docker/docker.github.io#387]
URL: [https://docs.docker.com/docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

Hi,
I have computed SHA256 checcum of Windows installer stable and this is different that provided by you

SHA256 hash of file .\InstallDocker.msi:
df 6d 57 2d 82 d2 ce ce 3d b1 94 99 c6 bb 8b 8a 0c 48 5e 4e 7a 46 b7 6b bb c5 e2 ec 11 a2 66 13
CertUtil: -hashfile command completed successfully.

you provide:
https://download.docker.com/win/stable/InstallDocker.msi.sha256sum

**Comment by londoncalling** [comment]
@friism @FrenchBen @jeanlaurent Can you all take a look at this re: the download hash sum?

**Comment by FrenchBen** [comment]
@mozowski I have the same sha256:
```
$ shasum -a 256 InstallDocker.msi
8a5d5b18575932c078d5474f153d2df0e413d66845e8fd37604801e165a4fed1  InstallDocker.msi
```

Same thing on Windows10
```
PS C:\Users\Docker\Desktop> Get-FileHash .\InstallDocker.msi -Algorithm SHA256

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          8A5D5B18575932C078D5474F153D2DF0E413D66845E8FD37604801E165A4FED1       C:\Users\Docker\Desktop\InstallDocker.msi
```

1. Make sure that you're looking at the proper installer
2. Make sure that you're computing a sha256

**Comment by londoncalling** [comment]
Closing this issue per @FrenchBen 's comment above. Thanks for the clarification.
