### ISSUE TITLE
404 at: /reference/logging/fluentd/

### ISSUE THREAD

**Issue by julianfrank** [docker/docker.github.io#388]
URL: /reference/logging/fluentd/

**Comment by thaJeztah** [comment]
The correct URL is https://docs.docker.com/engine/admin/logging/fluentd/, where did you find a link to this URL?

**Comment by thaJeztah** [comment]
ping @johndmulhausen looks like we're missing some redirects since the migration (see the linked page for the old location of the logging section)

@julianfrank I'll reopen this issue so that we don't forget restoring the redirects
