### ISSUE TITLE
Improve Moby inline image using Font Awesome

### ISSUE THREAD

**Issue by londoncalling** [docker/docker.github.io#3891]
### Problem

- Moby icon in docs should be consistent with branding, original was taken from Docker for Mac and Windows UIs. We now have the option to use Font Awesome images.

### Suggested Fix

- Update the `whale-x` images used in docs to the Font Awesome Docker icons (see https://github.com/wesbos/Font-Awesome-Docker-Icon)

### Related

@thaJeztah 's comments on PR #3877 

cc: @jsouth @mstanleyjones

**Comment by thaJeztah** [comment]
Well, either that one, or (preferably) an updated version with the new simplified logo (perhaps the design team can export one)

**Comment by jsouth** [comment]
@londoncalling - I love the idea of using fontawesome.  However it is slightly out of date/off brand as @thaJeztah mentioned.

I can supply an updated version for you to use now, and we can contact **wesbos** to get the icon updated(and then rock fontawesome once up to date). 

sound cool?

**Comment by londoncalling** [comment]
@jsouth @thaJeztah  

Could we get that updated version of the icon from you? And then maybe we can get back to **wesbos** to update the custom icon (https://github.com/wesbos/Font-Awesome-Docker-Icon), and you can show me how to incorporate a custom one?

**Comment by tfoxnc** [comment]
I'm cleaning up some stale issues. @londoncalling Was this every resolved?

**Comment by londoncalling** [comment]
Hi Tammy, it wasn’t resolved but I think you can close it. I think the
image looks fine as is and there are probably bigger fish to fry.

Thanks,
Vicky

**Comment by tfoxnc** [comment]
Thanks Vicky.
