### ISSUE TITLE
Storage driver documentation lacks vfs

### ISSUE THREAD

**Issue by jpetazzo** [docker/docker.github.io#3904]
The documentation on storage drivers doesn't list `vfs`. This led a user to ask me if we removed support for `vfs` (and to be fair, he was trying to start the engine with `--storage-driver vfs` and it was still starting with `overlay2` for other reasons, so I can't blame him!)

I think we should re-add explanations about `vfs`!

File: [engine/userguide/storagedriver/selectadriver.md](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/), CC @mstanleyjones

💖,

**Comment by mstanleyjones** [comment]
I think it might have been at @cpuguy83 or @trapier request that I left it off, so pinging them.

**Comment by cpuguy83** [comment]
I don't see any reason to not have it, just with some warnings that you probably don't want to.

**Comment by mstanleyjones** [comment]
Closed via #4079
