### ISSUE TITLE
Clarify what "supported" means for storage drivers

### ISSUE THREAD

**Issue by jpetazzo** [docker/docker.github.io#3905]
The documentation on storage drivers has a table indicating which storage drivers are supported (it's under the "Supported storage drivers per Linux distribution" header).

In my humble opinion, it is a bit confusing, because it doesn't say what "supported" means. All drivers are available on all platforms (as far as I know), but they are not _recommended_ (right?). For instance, we don't _support_ `btrfs` on any platform on Docker CE; but people can still use it (it's still compiled in). So, what does "supported" mean? That we provide support? Not really, since that's Docker CE – we don't have commercial support on it.

Tentatively, I think I'd go for a paragraph like the following one, below the compatibility table:

_Keep in mind that "supported storage driver" means that this distro/driver combination is in our automated regression tests, is used by a large number of users, and that if you find a reproducible issue, it will most likely be fixed very quickly. If the driver that you want to use is not "supported" according to this table, it doesn't mean that it's not available. You can run it at your own risk. You can even (and are encouraged to!) report issues if you find any. But for technical reasons, it will be harder for us to help you with the "unsupported" combinations. Yes, this means that `btrfs` is only "suppoted" in Docker EE, for instance on SLES. But you can still run it on your favorite distro if you need to!_

File: [engine/userguide/storagedriver/selectadriver.md](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
Clised via #4065
