### ISSUE TITLE
where to go for detailed authentication instructions for programmatic access

### ISSUE THREAD

**Issue by rcplane** [docker/docker.github.io#3911]
File: [apidocs/overview.md](https://docs.docker.com/apidocs/overview/), CC @johndmulhausen

**Comment by joaofnfernandes** [comment]
@rcplane you can use basic authentication with your requests. Here's an example

```
curl -u "<user>:<pass>" \
-X GET "https://<dtr-domain>/api/v0/repositories/?pageSize=10&count=false" \
-H "accept: application/json"
```

I'm going to close this issue as a duplicate of #2470, but feel free to comment, if this doesn't work for you.
