### ISSUE TITLE
Improve docs for "advanced" --publish options

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#3913]
### Problem description

This section https://docs.docker.com/engine/swarm/services/#publish-ports describes the "advanced" syntax (including host-mode) publishing for services.

However, the `docker service create` CLI reference only describes the short-hand syntax; https://docs.docker.com/engine/reference/commandline/service_create/#publish-service-ports-externally-to-the-swarm--p-publish (same for `docker run`; https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p-expose)

In addition, there's no overview of available options for the advanced syntax.

issue https://github.com/docker/docker.github.io/issues/3154 is also related

### Suggestions for a fix

I suggest to;

- add a description to the reference docs and/or link to a document describing the options in detail
- adding a table describing each option, similar to what's used for `--mount`; https://docs.docker.com/engine/reference/commandline/service_create/#add-bind-mounts-or-volumes

/cc @mavenugo @nicolaka  (re https://github.com/docker/docker.github.io/issues/3154) @mstanleyjones

**Comment by joaofnfernandes** [comment]
Relates to moby/moby#28527.
Given that this new syntax is way more intuitive to new users, I think the docs should always use the more verbose flags where they exist.

For `--publish` in particular, we've been running UX research studies and even experienced users have to double check what is the order or the arguments, i.e `--publish host:container` or `--publish container:host`. They either have to go to the docs, or do things by trial and error, which makes users waste time.

And the documentation should also be consistent. If we're using the long syntax we should use it everywhere. I've also seen some users confused by this. They started to learn their way around with one syntax type, and then they would land on a doc page using the other syntax type and get totally confused.

**Comment by mstanleyjones** [comment]
Fixed in #4018

**Comment by thaJeztah** [comment]
Oh, don't think this is fixed; this issue is about publishing ports, not about volumes (just referred to `--mount` for the tables that are used there)
