### ISSUE TITLE
so is --link deprecated or still a valid option?

### ISSUE THREAD

**Issue by roozbehid-ic** [docker/docker.github.io#3914]
On documentation for --link parameter, there is a mention of it being deprecated and not using it. But in this documentation on container communication, it is provided as a solution. It is a bit confusing in my opinion.

File: [engine/userguide/networking/default_network/container-communication.md](https://docs.docker.com/engine/userguide/networking/default_network/container-communication/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
It is deprecated, which means that it **may be taken away in the future**. Deprecation does mean that it is already gone. You should not rely on it if at all possible. For most use cases, there are better options than `--link`, such as using user-defined networks.
