### ISSUE TITLE
Document behavior of constraints on a global mode service

### ISSUE THREAD

**Issue by programmerq** [docker/docker.github.io#3915]
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/), CC @mstanleyjones

The behavior seems to be fairly clear if you find the original pull request that enables the current behavior: https://github.com/docker/swarmkit/pull/1570

The current way that this document page reads, it is unclear what the exact intended behavior is: global mode services do respect constraints.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #592](https://github.com/docker/cli/issues/592) via [**ZenHub**](https://www.zenhub.com/)
