### ISSUE TITLE
Statement that inability to route to containers due to OSX limitation is inaccurate

### ISSUE THREAD

**Issue by AlmirKadric** [docker/docker.github.io#3922]
The statements under the points `I cannot ping my containers` and `Per-container IP addressing is not possible` are inaccurate. These are not limitations of macOS nor limitations of hyperkit. This is purely a limitation of Docker for Mac.

To prove this very point I have created the following package which allows users to work around the issue by installing a shim to overwrite the arguments used to start hyperkit:
https://github.com/AlmirKadric-Published/docker-tuntap-osx

If Docker for Mac has no plans to fix the OSX routing issue natively by either allowing the networking options for the hyperkit instance to be configured, or having a tap interface by default (similar to hvint0 on Windows), the documentation should reflect that users can use the above project to workaround the issue. If for any reason the above project is insufficient in your opinion, please let me know and I will fix them.

If you believe that such a project should not be required, there is already a group of people behind that statement (myself included) and we would love to see this issue fixed at the source `Docker for Mac`

For more details, see original issue:
https://forums.docker.com/t/support-tap-interface-for-direct-container-access-incl-multi-host/17835/21

File: [docker-for-mac/networking.md](https://docs.docker.com/docker-for-mac/networking/), CC @londoncalling

**Comment by londoncalling** [comment]
@justincormack @jeanlaurent I am not sure who to route this to, so tagging you guys. Please me know if/how you want me to address this in the docs.

**Comment by londoncalling** [comment]
@jeanlaurent @justincormack @dsheets @friism can someone respond to this issue? And let me know best path forward for the docs.

**Comment by mstanleyjones** [comment]
Please open an issue in `docker/for-mac` repository relating to this if you want to pursue it. I will update the note to be more accurate.
