### ISSUE TITLE
Clarify custom path for secret version support

### ISSUE THREAD

**Issue by programmerq** [docker/docker.github.io#3923]
File: [engine/swarm/secrets.md](https://docs.docker.com/engine/swarm/secrets/), CC @mstanleyjones 

In the intermediate-example-use-secrets-with-a-nginx-service section, it specifically calls out a difference with 17.06 and <=17.05. Can this difference be clarified a little further? The way it reads, it could suggest that the targets functionality is not available in 17.05, when the real reason for the difference is that in 17.06, you can specify a full path that will populate the secret outside of /run/secrets

Additionally, I could not find a specific note in the documentation explaining that this full path support for the targets feature appeared in 17.06 (see https://github.com/moby/moby/pull/32571)

**Comment by mstanleyjones** [comment]
We don't tag every new feature by when it occurs, except in release notes. It would be unwieldy and would not serve much purpose once the feature was a couple versions old.

**Comment by mstanleyjones** [comment]
Closed via #4073
