### ISSUE TITLE
The policy listed on this page is too long

### ISSUE THREAD

**Issue by cwcoffman** [docker/docker.github.io#3939]
File: [docker-for-aws/iam-permissions.md](https://docs.docker.com/docker-for-aws/iam-permissions/), CC @johndmulhausen

Just wanted to make you aware that the policy on this page throws the following error when trying to create:

"An error occurred: Cannot exceed quota for PolicySize: 5120"  

I'll sort this out on my own, but since I imagine I need all of these permissions for provisioning Docker on AWS, using your CloudFormation template, I would very much appreciate any help you can provide.

Thank you!

**Comment by johndmulhausen** [comment]
cc @friism @FrenchBen

**Comment by FrenchBen** [comment]
@cwcoffman Most policies can be broken down into multiple chunks - You can then assign all of the policies to the user.
Typical breakdowns are:
* Cloudfront
* EC2
* DynamoDB + logs + sqs
* ELB
* Lambda

The permissions are very granular, but can be shrunk via a `*` if desired.

**Comment by cwcoffman** [comment]
Thanks so much for the reply.  Really appreciate your time.

**Comment by johndmulhausen** [comment]
@FrenchBen Should we break up the policy on the page so that people can easily copy/paste without getting the length error?

**Comment by FrenchBen** [comment]
I don't have a strong opinion on this. Feel free to do as you see fit.

**Comment by cwcoffman** [comment]
My opinion - if I had understood policies better at the time, the single
policy would have made sense, and I would have been able to work around the
errors.  I think it is valid to just put a simple, short paragraph
explaining this, and pointing folks to resources for breaking the policy up
if needed.

**Comment by mstanleyjones** [comment]
We have info about this in the Cloud docs and can duplicate or link to it from here.

**Comment by gbarr01** [comment]
See #3406

**Comment by naffiq** [comment]
If anyone still struggles with that just create role without permissions attached and attach custom inline policy.
