### ISSUE TITLE
Feedback for: engine/understanding-docker.md

### ISSUE THREAD

**Issue by maschoonover** [docker/docker.github.io#394]
URL: [https://docs.docker.com/engine/understanding-docker.md](https://docs.docker.com/engine/understanding-docker/)

In the description of "What Is the Docker Engine", it says: "The daemon creates and manages Docker objects, such as images, containers, networks, and data volumes." However, the associated image implies that CLI does that, because the lines go from the CLI to the images, containers, networks, and data volumes icons. Seems like those lines should be attached to the daemon.

**Comment by mstanleyjones** [comment]
I think the image is actually OK, because you use the CLI or API to tell the daemon what to do. If we redo this image, I will keep this feedback in mind. Thanks!
