### ISSUE TITLE
Quite a few issues with the repo path

### ISSUE THREAD

**Issue by raviupad** [docker/docker.github.io#3944]
File: [engine/installation/linux/docker-ee/rhel.md](https://docs.docker.com/engine/installation/linux/docker-ee/rhel/), CC @mstanleyjones

[root@ip-10-12-3-196 yum.repos.d]# sudo yum makecache fast
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
https://storebits.docker.com/ee/linux/<redacted>/7.3/x86_64/stable-17.03/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

 One of the configured repositories failed (Docker EE Stable 17.03 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=docker-ee-stable-17.03 ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable docker-ee-stable-17.03
        or
            subscription-manager repos --disable=docker-ee-stable-17.03

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=docker-ee-stable-17.03.skip_if_unavailable=true

failure: repodata/repomd.xml from docker-ee-stable-17.03: [Errno 256] No more mirrors to try.
https://storebits.docker.com/ee/linux/<redacted>/7.3/x86_64/stable-17.03/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
[root@ip-10-12-3-196 yum.repos.d]# ls^C
[root@ip-10-12-3-196 yum.repos.d]# sudo yum -y install docker-ee
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
https://storebits.docker.com/ee/linux/<redacted>/7.3/x86_64/stable-17.03/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

 One of the configured repositories failed (Docker EE Stable 17.03 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=docker-ee-stable-17.03 ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable docker-ee-stable-17.03
        or
            subscription-manager repos --disable=docker-ee-stable-17.03

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=docker-ee-stable-17.03.skip_if_unavailable=true

failure: repodata/repomd.xml from docker-ee-stable-17.03: [Errno 256] No more mirrors to try.
https://storebits.docker.com/ee/linux/<redacted>/7.3/x86_64/stable-17.03/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
[root@ip-10-12-3-196 yum.repos.d]#

**Comment by mstanleyjones** [comment]
You have Docker for Linux, rather than Docker EE for RHEL. This means that your repo structure is a little different as called out on your Docker Store subscription page. You need to modify your repo URL to add `/rhel/` before the `/7.3/` part of the path. I'm going to modify your comment to remove your EE subscription URL, as this is supposed to be private information. Please do not put this into a Github issue in a public repo.

**Comment by raviupad** [comment]
Thank you very much @mstanleyjones
