### ISSUE TITLE
env files

### ISSUE THREAD

**Issue by thiagonache** [docker/docker.github.io#3946]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @londoncalling 

Hello there,

In the environment file (.env), I just make it works without interpolation (the example using interpolation in the image tag doesn't work for me) and with : instead of =.
Example of .env file
VARIABLE:my_desired_value

**Comment by thiagonache** [comment]
This works:
version: '3.2'

services:
  logspout:
    image: gliderlabs/logspout
    command: "syslog+tcp://logs-01.loggly.com:514"
    entrypoint: "/bin/logspout"
    env_file: .env
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    deploy:
      mode: global

file .env
SYSLOG_STRUCTURE_DATA:XXXXXX-XXXX-XXXX-XXXX-XXXXXXXX@41058

The same compose file with file .env like above doesn't work.
SYSLOG_STRUCTURE_DATA=XXXXXX-XXXX-XXXX-XXXX-XXXXXXXX@41058

If I inspect the container, I can see the variable properly, but for some reason, logspout doesn't recognize it. 

Please, let me know any info I could add to help with it.

**Comment by johndmulhausen** [comment]
`=` is correct, as Joao mentions and as is documented in the Compose file reference.
