### ISSUE TITLE
Broken links on docker-compose installation page

### ISSUE THREAD

**Issue by peteraba** [docker/docker.github.io#3951]
File: [compose/install.md](https://docs.docker.com/compose/install/), CC @londoncalling

**Comment by londoncalling** [comment]
@peteraba I don't see any broken links on the page you referenced. Can you send me the direct link to the `404` error? If you are talking about the link to the pre-release binaries (https://dl.bintray.com/docker-compose/master/ under the [Master Builds](https://docs.docker.com/compose/install/#master-builds) topic, I believe is actually going to the correct place. (cc @shin- to verify)

**Comment by mstanleyjones** [comment]
Out of date.
