### ISSUE TITLE
Javascript is required to navigate

### ISSUE THREAD

**Issue by ThrosturX** [docker/docker.github.io#3952]
File: [index.md](https://docs.docker.com/), CC @johndmulhausen 

The navbar `nav-sidebar` does not work without javascript, and no indication is displayed to alert the user that javascript is required to make use of the site.

I would suggest implementing proper fallback methods (or at the very least a notice) so that users who, by choice or otherwise, are not running client-side scripts can still make use of the site.

Reproduction steps:
1. Disable javascript.
2. Navigate to any Docker documentation page. 
3. Attempt to use the sidebar.
4. Notice that despite the sidebar being responsive (with CSS), navigation *requires* javascript (it is indeed possible to achieve this with HTML+CSS, so requiring javascript is overly restrictive).

**Comment by ThrosturX** [comment]
It seems like this affects the Docker website more extensively than I expected.
Notice that javascript is also required to view the second resultset on https://hub.docker.com/explore/#.

**Comment by johndmulhausen** [comment]
Sorry, but this is working as intended and for many reasons we can never support a JS-free version of the docs. :(
