### ISSUE TITLE
Add difference between EE and CE

### ISSUE THREAD

**Issue by jaycode** [docker/docker.github.io#3957]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
I'm not sure what you mean. You can find that info at https://docs.docker.com/engine/installation/. I suppose I can add a link back to there.

**Comment by jaycode** [comment]
Yeah, adding a link would help, and some context to readers what EE and CE
means in that page.
