### ISSUE TITLE
Stater Theme wont' show in themes directory in WordPress

### ISSUE THREAD

**Issue by dbybanez** [docker/docker.github.io#3968]
Hi,

We're using Docker to develop our WordPress site and we want to continue developing it locally. But after migrating from the server to local, the starter theme won't show as an option.

See screenshot: http://imgur.com/a/CE0OI

Thanks,
David

**Comment by johndmulhausen** [comment]
Sorry, we don't really have tech support here; all we do to support WordPress in the official docs is publish the Library reference for Wordpress at https://docs.docker.com/samples/library/wordpress

If you're having trouble a good place to ask for help is forums.docker.com!
