### ISSUE TITLE
Feedback for: compose/wordpress.md

### ISSUE THREAD

**Issue by websocketdev** [docker/docker.github.io#397]
URL: [https://docs.docker.com/compose/wordpress.md](https://docs.docker.com/compose/wordpress/)

This tutorial actually doesn't work properly on Mac OSX, because one gets an error with th mounted directory 

ERROR: for db  Cannot start service db: Mounts denied: s for more info.

This is a common error and is due to OSX incompatibility issues, the tutorial needs to be rewritten to use a data volume that lives inside the container. The whole point of Docker is portability, I don't know why anyone would want a specific directory to be mounted from the Mac.

**Comment by johndmulhausen** [comment]
@ManoMarks We're getting multiple thumbs-down on our WordPress sample and there's a more detailed report here. Do we have a more canonical/up-to-date sample we can use?

**Comment by ManoMarks** [comment]
There's the [Example Voting App](https://github.com/docker/example-voting-app). We do a quick run through in [Docker Labs](https://github.com/docker/labs/blob/master/beginner/chapters/votingapp.md)

**Comment by johndmulhausen** [comment]
@ManoMarks Sorry, I mean a more up-to-date WordPress example.

**Comment by ManoMarks** [comment]
Oh, no I don't have one. I just ran through it with no problem. But if a number of people are getting it,  that's a problem. I don't know a lot about word press but I can take a stab at it next week.

**Comment by johndmulhausen** [comment]
@ManoMarks we don't have a plethora of data here; 2 thumbs up and 5 thumbs down and this error report. I tried it too and couldn't repo, so I think I have to close this for now; I got forwarded to http://localhost:8000/wp-admin/install.php and went into setup just fine after running `docker-compose up`
