### ISSUE TITLE
Docs say 

### ISSUE THREAD

**Issue by kurtwheeler** [docker/docker.github.io#3971]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
I'm sorry, what problem did you see in the doc? There isn't much info here.

**Comment by kurtwheeler** [comment]
Sorry, I did not mean to open this. I created a much larger issue and I guess along the way I made this one by accident.
