### ISSUE TITLE
Docs say "You can also add more storage to the thin pool." without specifying how

### ISSUE THREAD

**Issue by kurtwheeler** [docker/docker.github.io#3972]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/), CC @mstanleyjones 

In the `dm.min_free_space` section the page says:
> Whenever a new a thin pool device is created (during docker pull or during container creation), the Engine checks if the minimum free space is available. If sufficient space is unavailable, then device creation fails and any relevant docker operation fails.

> To recover from this error, you must create more free space in the thin pool to recover from the error. You can create free space by deleting some images and containers from the thin pool. You can also add more storage to the thin pool.

> To add more space to a LVM (logical volume management) thin pool, just add more storage to the volume group container thin pool; this should automatically resolve any errors.

I would like to add more storage to the thin pool as the docs make it seem like this will fix the issue I'm experiencing. However I cannot figure out how to do so. Higher up on the page it also says:

> Refer to Storage driver options below for a way how to customize this setup. ~jpetazzo/Resizing Docker containers with the Device Mapper plugin article explains how to tune your existing setup without the use of options.

The "Storage driver options below" do not contain more information about how to add storage than I have already quoted and the linked blog post has a giant disclaimer on it:

> Warning
> At some point, Docker storage driver internals have changed significantly, and the technique described here doesn’t work anymore.

I tried that technique anyway and as advertised it in fact did not work. I am suggesting that the docs be changed to no longer link to an out-of-date blog post and that they also be amended to include specific instructions for adding storage to the thin pool, adding storage to a LVM, adding more storage to the volume group container thin pool, or all of them. (I do understand the distinction between the three.)

**Comment by mstanleyjones** [comment]
@cpuguy83 @jpetazzo any insight on this?

**Comment by jpetazzo** [comment]
(Spelunking my way up through my inbox, sorry for the delay!)

About my blog post: it's definitely obsolete. It is interesting as a curiosity (i.e., if somebody wants to resize their containers by hand, uphill, both ways!) but not something that should be done on a production environment. It's totally fine to unlink it (or, if it stays linked, with a message like: _If you want to understand how volumes are resized in an environment which uses devicemapper, you can check the following blog post. The technique that it describes should not be used in a production environment, but it will give you some insights about what happens behind the scenes, were you so inclined._)

About the original question: I think it all depends how the thin pool was created in the first place. The corresponding method should be used accordingly. For instance, if the thin pool was created with the LVM tools (`pvcreate` on at least 1 PV, then `vgcreate`, then `lvcreate`), it should be extended with the LVM tools (if the VG is full, extend it with `pvcreate` on additional PVs then `vgextend` to add these PVs to the VG; and then `lvextend` on the thin pool).

HTH,

**Comment by mstanleyjones** [comment]
@gbarr01 I think we have enough info to address this now. Can you make a sister issue in `docker/cli` for the reference topic mentioned here, and also see if there is anything that needs to be added or modified in https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/ in a PR to this repo? This is a bit of an edge case, so it has lower priority than the other 17.09 work.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #587](https://github.com/docker/cli/issues/587) via [**ZenHub**](https://www.zenhub.com/)
