### ISSUE TITLE
userguide example broken: ubuntu docker image bash: ip: command not found

### ISSUE THREAD

**Issue by davidahoward** [docker/docker.github.io#3973]
File: [engine/userguide/networking/default_network/ipv6.md](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/), CC @mstanleyjones 

dhoward-osx:~ dhoward$ docker run -it ubuntu bash -c "ip -6 addr show dev eth0; ip -6 route show"
bash: ip: command not found
bash: ip: command not found

dhoward@vps118471:~$ sudo  docker run -it ubuntu bash -c "ip -6 addr show dev eth0; ip -6 route show"
[sudo] password for dhoward: 
bash: ip: command not found
bash: ip: command not found

apparently the ubuntu docker image no longer has iproute2 package installed

please update documentation with working examples

**Comment by mstanleyjones** [comment]
@thaJeztah do you know what image would be better to use, that does have the `ip` command? It looks like Ubuntu removed it in a recent version.

**Comment by davidahoward** [comment]
docker run --rm -it alpine /bin/ash


has ip command in it and works... also it is used elsewhere in docker
docs...



David A. Howard
david.a.howard.1@gmail.com

**Comment by mstanleyjones** [comment]
Closed via #4071
