### ISSUE TITLE
Describe what each field means in "docker stack ps"

### ISSUE THREAD

**Issue by manishtomar** [docker/docker.github.io#3978]
File: [engine/reference/commandline/stack_ps.md](https://docs.docker.com/engine/reference/commandline/stack_ps/), CC @mstanleyjones

It will be helpful if the doc contained description about each field listed in `docker stack ps`. All of them except ID and Name are obvious. I am always confused between container ID and task ID. Please describe the difference between the two if possible. I also had trouble figuring out what the numerical suffix in Name meant. I am assuming it is replica number.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #503](https://github.com/docker/cli/issues/503) via [**ZenHub**](https://www.zenhub.com/)
