### ISSUE TITLE
update_config failure action should be updated

### ISSUE THREAD

**Issue by jmwong** [docker/docker.github.io#3980]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @londoncalling 

This line in the compose doc should be updated to reflect a third option, `rollback`:

> failure_action: What to do if an update fails. One of continue or pause (default: pause).

to match the `docker service create` docs (https://docs.docker.com/engine/reference/commandline/service_create/#options) says:
> --update-failure-action |   | Action on update failure (“pause”\|“continue”\|“rollback”) (default “pause”)

**Comment by cthomas15** [comment]
#dibs

**Comment by cthomas15** [comment]
So you want the new bullet point to say:

"failure_action: What to do if an update fails. One of continue, rollback, or pause (default: pause)."

Is that correct?

**Comment by londoncalling** [comment]
@cthomas15 yes that looks correct as you've suggested to match https://docs.docker.com/engine/reference/commandline/service_create/#options

Do you want to make the change in the docs and submit the PR? Go for it, and I'll review it.

**Comment by cthomas15** [comment]
@londoncalling Sounds good to me.

**Comment by shin-** [comment]
:+1:

**Comment by londoncalling** [comment]
@cthomas15 you can either create a PR against `docker.github.io` or just click **Edit page** at top right on https://docs.docker.com/compose/compose-file/ and edit the page in place which will automatically create the PR when you click **Commit Changes** . Let me know if you need help with any of this, glad to help.
