### ISSUE TITLE
Firefox: Loading anchor directly fwds to top of page

### ISSUE THREAD

**Issue by dsheets** [docker/docker.github.io#3986]
### Problem description

When loading <https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact> in FF 53 on macOS, the page briefly loads some location on the page and then immediately reloads, removes the fragment, and scrolls to the top of the page.

### Problem location

<https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact> at least and probably other, similar URLs.

**Comment by dsheets** [comment]
Once on the page, if you paste the same URL (with fragment) into the address bar and press `Enter`, the page scrolls to the correct location.

**Comment by matsaman** [comment]
```diff
--- docs.js     2017-11-02 10:38:48.187751200 -0700
+++ docs.js     2017-11-02 10:37:40.836611500 -0700
@@ -10,7 +10,6 @@
 if (current[0]) {
     if (sidebarObj) {
       current[0].scrollIntoView(true);
-      body[0].scrollIntoView(true);
     }
     // library hack
     if (document.location.pathname.indexOf("/samples/") > -1){
```
More generally, just about all the JS I'm seeing is really convoluted.

Why do you need to be playing with the scroll at all? Hopefully it's not just to counteract your fixed header being over your h1-h6 text headers. To fix that you need only add some padding to those headers (or whichever element has the id on it)

```css
h1, h2, h3, h4, h5, h6 { padding-top: 50px; margin-top: -50px !important; }
```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
