### ISSUE TITLE
Task state transition diagram

### ISSUE THREAD

**Issue by manishtomar** [docker/docker.github.io#4004]
File: [datacenter/ucp/2.2/guides/admin/monitor-and-troubleshoot/troubleshoot-task-state.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/monitor-and-troubleshoot/troubleshoot-task-state/), CC @joaofnfernandes

Swarm task transitions to different states during its lifetime. Although a table is quite helpful in explaining each state, it will be super helpful to have a state transition diagram that lists each state and all possible transitions to other states.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
