### ISSUE TITLE
Ip adress

### ISSUE THREAD

**Issue by dieli** [docker/docker.github.io#4013]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen
On windows, I can not connect to localhost:4000. Instead I need to first get the machine IP via
`docker-machine ip`
and then enter this IP:4000

**Comment by joaofnfernandes** [comment]
The first step of the tutorial teaches you how to install Docker for Windows, and if you do it, you'll be able to access your application at `localhost:4000`.
In your case you've installed `docker-machine`, so you're running a virtual machine that has Docker, so you'll need to access your application using the IP of the machine.

Hopefully this makes things a bit clearer. I'm going to close the issue, but feel free to comment if this is still confusing.

**Comment by dieli** [comment]
Thanks for the clarification. Seems I was missing the difference between `docker `and `docker-machine` (Windows Home vs Professional version).

**Comment by joaofnfernandes** [comment]
No worries. Docker on Windows is a bit confusing 😒
