### ISSUE TITLE
Please create new tab in preference for 'Uninstall' button

### ISSUE THREAD

**Issue by Rei-HAYASHI** [docker/docker.github.io#4020]
File: [index.md](https://docs.docker.com/), CC @johndmulhausen 

It was difficult for me to recognize how to uninstall Docker for Mac. 

I didn't have a lot of knowledge about Docker so I'm 'beginner'.

I tried to uninstall older Docker for install the latest version.

I chose the "Reset" tab along with the official Docker documentation.
documentation URL: https://docs.docker.com/docker-for-mac/#uninstall-or-reset

I pressed the "Remove all data" button at the top of the three buttons displayed in the dialog.

<img width="492" alt="2017-07-29 14 10 07" src="https://user-images.githubusercontent.com/30530775/28743221-6e8a96ca-747f-11e7-8952-9ebbe8cfeb64.png">

However, old Docker application remained.
What I accomplished was that I could run it with the "Uninstall" button at the bottom.

I wonder if it is easy to understand by putting the "Uninstall" button on a different tab than "Reset".

Incidentally, the version of Docker that I tried to uninstall is unknown.

Mac OS version: macOS Sierra 10.12.6

**Comment by joaofnfernandes** [comment]
This is more of a feature request to Docker for Mac. @Rei-HAYASHI do you care to open an issue at https://github.com/docker/for-mac?

**Comment by Rei-HAYASHI** [comment]
@joaofnfernandes
Thank you for your reply!
I opened an issue at Docker for Mac.
https://github.com/docker/for-mac/issues/1976
For this reason, I close this issue here.
