### ISSUE TITLE
Is this documentation new?

### ISSUE THREAD

**Issue by bcccgreen** [docker/docker.github.io#4021]
File: [engine/installation/linux/docker-ce/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/), CC @mstanleyjones

So apart from the fact it doesn't explain how to install on x86_64 in step 4, (which I assume is essential because my install isn't working) the links in the page aren't correct.  I clicked the first two to get help and got page not found.

**Comment by mstanleyjones** [comment]
I'm sorry, but I can't replicate any of this. Please shift+f5 to make sure that you get a non-cached copy of the page and try again.
