### ISSUE TITLE
404 at /docker-for-aws/

### ISSUE THREAD

**Issue by ajayramesh23** [docker/docker.github.io#4027]
URL: https://docs.docker.com/docker-for-aws/
 - 404 error

![image](https://user-images.githubusercontent.com/2877819/28747464-a39e6596-7464-11e7-9507-7dfe81d64406.png)

**Comment by hairyhenderson** [comment]
Dupe of #4026 😉

**Comment by mstanleyjones** [comment]
This is no longer happening.
