### ISSUE TITLE
lack of coherence between the main menu and the Docker for Mac installation page

### ISSUE THREAD

**Issue by gdevillele** [docker/docker.github.io#404]
### Problem description

Main menu shows "Mac OS X" while related page is titled "macOS".
They should show the same name, IMHO.

![screen shot 2016-10-31 at 1 56 15 pm](https://cloud.githubusercontent.com/assets/939999/19873868/ae9f1abe-9f7e-11e6-8990-9b51a3bdec29.png)

### Problem location

- I saw a problem on the following URL: [https://docs.docker.com/engine/installation/mac/](https://docs.docker.com/engine/installation/mac/)

### Project version(s) affected

current stable

### Suggestions for a fix

fix the content.

**Comment by johndmulhausen** [comment]
Assigning to @mstanleyjones who did the Mac OS X -> macOS search/replace
