### ISSUE TITLE
Please mention that mounting files requires abs paths

### ISSUE THREAD

**Issue by subos2008** [docker/docker.github.io#4040]
As per https://stackoverflow.com/questions/34134343/single-file-volume-mounted-as-directory-in-docker mounting a file needs an absolute source path. This is not mentioned in the docs and results in the file being mounted as a directory.

File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
Fixed in #4018
