### ISSUE TITLE
The prerequisites link is broken: https://docs.docker.com/engine/installation/linux/docker-ee/#prerequisites

### ISSUE THREAD

**Issue by apuchitnis** [docker/docker.github.io#4044]
File: [engine/installation/linux/docker-ee/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ee/ubuntu/), CC @mstanleyjones

**Comment by londoncalling** [comment]
@mstanleyjones thinks this broke when #3981 was merged. @johndmulhausen can you revert #3981, and I will update all links with `#index.md<some-subtopic>` to have full paths instead of relative, if you think this will fix that other problem?

**Comment by londoncalling** [comment]
Fixed in #4051
