### ISSUE TITLE
Docs shouldn't use `\` for line separator

### ISSUE THREAD

**Issue by friism** [docker/docker.github.io#4053]
File: [engine/admin/prometheus.md](https://docs.docker.com/engine/admin/prometheus/), CC @mstanleyjones

`\` is not valid on Windows in powershell

**Comment by mstanleyjones** [comment]
@johndmulhausen what do you think? I think the line-continuation characters really help people with pasting on Linux and with making the commands be easier to read without having to scroll across the page. For Windows, I think you don't need any special character for line continuation. I'm not sure exactly how it works. Is there some way to handle this in Javascript? Do we want to go down that road?

**Comment by friism** [comment]
I don't think trying to detect browser client OS in javascript and modifying the text is a good idea.

I personally don't think the current snippets are useful:

 * I can't triple-click and get the whole multi-line thing
 * triple-clicking the first line gets only the first line, and it also includes a `$` sign. Which isn't even the prompt symbol in any normal windows prompt (but let that rest)

**Comment by johndmulhausen** [comment]
I would say a) Clicking a snippet should highlight the whole snippet. b) In general we should have `\` multi-line commands for Linux and be careful to include ` ` ` versions for Windows

And ideally we would be putting `$` in through CSS injection so it doesn't get selected

A good policy I stick to for when to include `$` and when not to: When showing both the command and its ouput, include the `$`, but if you're just showing the command, leave it out.

**Comment by friism** [comment]
(for the record I don't have a big beef with `$`. But I do think it's a problem if snippets copy-pasted from the docs don't work in Windows shells)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
