### ISSUE TITLE
Docker for Mac/Win should use `docker.for.win.localhost` (and similar for Mac)

### ISSUE THREAD

**Issue by friism** [docker/docker.github.io#4056]
File: [engine/admin/prometheus.md](https://docs.docker.com/engine/admin/prometheus/), CC @mstanleyjones 

https://docs.docker.com/docker-for-windows/release-notes/#docker-communityedition-17060-ce-win18-2017-06-28-stable

**Comment by joaofnfernandes** [comment]
@friism can you provide a bit more context here?
I can see in the release notes

> Add an experimental DNS name for the host: docker.for.win.localhost

So are use suggesting that in the snippets for Windows, we should use `docker.for.win.localhost` instead of just `localhost`?

**Comment by friism** [comment]
@joaofnfernandes yes, because I don't think `localhost` works with Docker for Mac and Windows (at least that's the memory I have from 21 days ago)
