### ISSUE TITLE
We don't explain how to configure your docker client to trust DTR

### ISSUE THREAD

**Issue by vikstrous** [docker/docker.github.io#4066]
File: [datacenter/dtr/2.2/guides/user/manage-images/sign-images/index.md](https://docs.docker.com/datacenter/dtr/2.2/guides/user/manage-images/sign-images/), CC @joaofnfernandes 
These instructions don't work for a DTR with a self signed cert unless you configure your docker client as per https://docs.docker.com/engine/reference/commandline/cli/#examples or turst DTR globally at the OS level.
cc @eiais

**Comment by joaofnfernandes** [comment]
We have instructions on how to trust DTR here https://docs.docker.com/datacenter/dtr/2.2/guides/user/access-dtr/. We just have to link the two articles

**Comment by vikstrous** [comment]
Hmm.. it's strange that there's info how to make notary turst DTR on that page but not how to make docker client trust it. Seems like both should be on the same page.

**Comment by joaofnfernandes** [comment]
https://docs.docker.com/datacenter/dtr/2.2/guides/user/access-dtr/  is supposed to be how to make your whole system trust DTR, so that you don't have to do it for each tool individually.

Then we have https://docs.docker.com/datacenter/dtr/2.2/guides/user/access-dtr/configure-your-notary-client/, that's about how to import your UCP keys into Notary.

If you see anything that's Notary-specific in the first article, let me know so that we can clean it up.

**Comment by vikstrous** [comment]
Oh, sorry, right... it doesn't tell you how to make notary trust DTR either. We have instructions only about how to do it at the OS level. Hmm... I guess that works for all tools and doesn't require you to do it differently for each one so that's good... but if you used certs.d then you end up very confused... I'm starting to think that having all these tool specific certs directories was a mistake. They should all have just used the system cert store because now they are all separate and they can't share certs in a reasonable way

**Comment by eiais** [comment]
I think I tried doing it at the OS level and still needed to use certs.d.

**Comment by joaofnfernandes** [comment]
@eiais interesting... can you describe your OS, and the versions of your Docker CLI, API, and DTR?

**Comment by eiais** [comment]
Ubuntu 16.04
Version:      1.12.6
API version:  1.24
DTR 2.4.0-alpha nightly

**Comment by joaofnfernandes** [comment]
No actionable feedback on this one, so we'll close it for now.
