### ISSUE TITLE
UCP 1.0 is not compatible with CE/EE engine 1.13 or later.

### ISSUE THREAD

**Issue by ekitagawa** [docker/docker.github.io#4068]
File: [datacenter/ucp/2.1/guides/admin/install/system-requirements.md](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/install/system-requirements/), CC @joaofnfernandes

This page says "CS Docker Engine version 1.10 or higher" but compatibility matrix says otherwise.

**Comment by JimGalasyn** [comment]
This seems to have been fixed -- I checked all of the UCP system requirements topics against the [Compatibility Matrix](https://success.docker.com/Policies/Compatibility_Matrix) at Success, and they look correct.
