### ISSUE TITLE
incorrect container name?

### ISSUE THREAD

**Issue by mshimer** [docker/docker.github.io#4092]
File: [engine/reference/commandline/port.md](https://docs.docker.com/engine/reference/commandline/port/), CC @mstanleyjones

in the example 'test' is not a container id as the doc states it should be. e.g. 'docker port test'..  

or is 'test' part of the command?

**Comment by joaofnfernandes** [comment]
This is a bit confusing, but the description of the command is `docker port CONTAINER`, which means that you can use the Id or name of the container.

If you horizontally scroll the snippet on that page, you'll see that the container `b650456536c7` is named `test`.

I think this answers your question, so I'm going to close this issue, but feel free to comment if I'm missing something.
