### ISSUE TITLE
'devicemapper storage driver in practice' appears twice

### ISSUE THREAD

**Issue by stour** [docker/docker.github.io#4098]
File: [engine/userguide/storagedriver/selectadriver.md](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/), CC @mstanleyjones

In section `Related information` at the bottom of the page item _devicemapper storage driver in practice_ appears twice with two different styles:
- `devicemapper ` storage driver in practice
- Device Mapper storage driver in practice

**Comment by cthomas15** [comment]
#dibs

**Comment by cthomas15** [comment]
Do you know which of the two bullet points is the correct style?

**Comment by mstanleyjones** [comment]
The first one 👍

**Comment by cthomas15** [comment]
@mstanleyjones, thanks!
