### ISSUE TITLE
Docker secret custom directory

### ISSUE THREAD

**Issue by anuragagarwal561994** [docker/docker.github.io#4101]
### Problem description

No where in the documentation it is mentioned on how to create directories inside /run/secrets if we want our secret keys to be organised. But if we name our target to contain slashes (representing directories), actual directories are formed within /run/secrets and it works.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/compose/compose-file/#long-syntax-2

- I couldn't find the information I wanted. I expected to find it near the following URL: I could not find the information I wanted. I explored it my self, and felt that it can be important for others to know too.

- Other: 

### Project version(s) affected

Versions supporting docker secrets.

### Suggestions for a fix

The target option says that it represents the "The name of the file that will be mounted", but more elaborately it should be path that will be mounted.

**Comment by mstanleyjones** [comment]
Docker 17.06 CE and higher support custom locations for secrets. See https://docs.docker.com/engine/swarm/secrets/.

**Comment by Enquier** [comment]
This needs to be updated. It is still incorrect in the Compose File Reference Documentation

**Comment by andrewchen5678** [comment]
why is this closed, docker-compose had the wrong documentation, it says "target: The name of the file to be mounted in /run/secrets/ in the service’s task containers. Defaults to source if not specified," but I just tested out a simple set up with target outside of the /run/secrets/ folder like `target: /etc/testfile`. It is not the first time I see documentation issues in docker compose and the tickets for it are closed w/o a fix.
