### ISSUE TITLE
Add system requirements to this page

### ISSUE THREAD

**Issue by pdevine** [docker/docker.github.io#4103]
File: [datacenter/dtr/2.2/guides/admin/install/system-requirements.md](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/install/system-requirements/), CC @joaofnfernandes 

We should include a matrix w/ recommendations and minimum guidelines based on the number of repositories and simultaneous pulls/pushes.

**Comment by joaofnfernandes** [comment]
Relates to #3656

**Comment by joaofnfernandes** [comment]
@antonybichon17 do you know if we any any metrics on this?

**Comment by bermudezmt** [comment]
Closed by #3656.
