### ISSUE TITLE
Add information about '--with-registry-auth' when creating service from private registries

### ISSUE THREAD

**Issue by SPodjasek** [docker/docker.github.io#4107]
File: [engine/swarm/services.md](https://docs.docker.com/engine/swarm/services/), CC @mstanleyjones

As stated above some words about this option would save me some time when starting with swarm.

Documentation should show that before creating service with image from private registry you should either login to that registry on each swarm node, or do this on manager from which you create service and add `--with-registry-auth` option to your `docker service create` command.

Also IMHO File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/), should contain description or example of this option usage.

**Comment by ps2goat** [comment]
I agree.  I created a new issue (5697), since it's on a different page than what this issue references.

**Comment by mistyhacks** [comment]
Relates to #5697

**Comment by stevvooe** [comment]
LGTM
