### ISSUE TITLE
Error running part 6 of tutorial

### ISSUE THREAD

**Issue by gmcfrear** [docker/docker.github.io#4108]
File: [get-started/part6.md](https://docs.docker.com/get-started/part6/), CC @johndmulhausen 

I followed the instructions to the letter, and I'm getting this error.

61pqx2vq7ge0        getstartedlab_redis.1        redis:latest                      ip-172-31-46-70.us-east-2.compute.internal    Ready               Rejected 4 seconds ago       "invalid mount config for type…"   
4semefyuexw2         \_ getstartedlab_redis.1    redis:latest                      ip-172-31-46-70.us-east-2.compute.internal    Shutdown            Rejected 9 seconds ago       "invalid mount config for type…"   
sdwm1gz9g8v2         \_ getstartedlab_redis.1    redis:latest   

Everything else works perfectly.

http://gfp-swarm-external-120wqeszoa7rs-1614970043.us-east-2.elb.amazonaws.com/
Graeme's awesome docker swarm on AWS!

Hostname: 1f89cf95f8ca
Visits: cannot connect to Redis, counter disabled

I did try to add a mount point on my 3rd try, however this isn't 100% sshing into the master node
[gfrear@gf-hypervisor docker]$ mkdir ./data
[gfrear@gf-hypervisor docker]$ docker stack deploy -c docker-compose.yml getstartedlab

I did try that too on attempt #7

[gfrear@gf-hypervisor docker]$ docker exec -it shell-aws bash
bash-4.3# ls -l / |grep data
drwxr-xr-x    2 root     root          4096 Aug  6 23:57 data
bash-4.3# ls -l /data
total 0
-rw-r--r--    1 root     root             0 Aug  6 23:57 a

I feel the issue is the filesystem is overlay, and redis expects ext4? perhaps? just maybe?

[gfrear@gf-hypervisor docker]$ docker exec -it shell-aws bash
bash-4.3# ls -l / |grep data
drwxr-xr-x    2 root     root          4096 Aug  6 23:57 data
bash-4.3# ls -l /data
total 0
-rw-r--r--    1 root     root             0 Aug  6 23:57 a
bash-4.3# ls -l /dev | grep xvd
bash-4.3# mount | grep -w /
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/KHT7J6GA536IEHNGYKYXMTSGKH:/var/lib/docker/overlay2/l/6NYXYXGSLDOMHEIZFG2ND23DXC:/var/lib/docker/overlay2/l/4WWCYYKT5OPLIXJOLAGYVBXUG7:/var/lib/docker/overlay2/l/AW7IG2XQLDKYY5BYL44MSNV5Q5:/var/lib/docker/overlay2/l/COCJ4EQTSLQVUX4DCSVXITEKWS:/var/lib/docker/overlay2/l/BBFFW33Q25UXDGPVQTQZFADT2I:/var/lib/docker/overlay2/l/2S3GTHWYTWQ4565G6GNFGF265Q:/var/lib/docker/overlay2/l/A3ELPW4ZDXOTUIOYQ22YSCK6GO:/var/lib/docker/overlay2/l/KUM35MGFALYHBIIFOOGOX2JMMN:/var/lib/docker/overlay2/l/DR6XI52UHACHNFQZM5TKH5HMIQ:/var/lib/docker/overlay2/l/PI4G5D745ZHAGDHT773VAUJV33,upperdir=/var/lib/docker/overlay2/5e6345f7464e3255cb88167abe43e2d3d8d57049aae4d50d639e292aff76bf7c/diff,workdir=/var/lib/docker/overlay2/5e6345f7464e3255cb88167abe43e2d3d8d57049aae4d50d639e292aff76bf7c/work)
bash-4.3# ls -l /var/lib/docker/overlay2
ls: /var/lib/docker/overlay2: No such file or directory

**Comment by mindbat** [comment]
i'm getting the same error when i work through the tutorial, with the addition that my app is unresponsive/unreachable when deployed via the given instructions to aws :/

**Comment by londoncalling** [comment]
Fixed by PR #4751
