### ISSUE TITLE
Service link

### ISSUE THREAD

**Issue by mochawich** [docker/docker.github.io#4124]
This seems to be wrong
> You can try this by pointing your web browser to **servicename.username.svc.dockerapp.io** or using dig or nslookup to see how the service endpoint resolves.

servicename.username.svc.dockerapp.io is not resolving to anything.

File: [docker-cloud/apps/load-balance-hello-world.md](https://docs.docker.com/docker-cloud/apps/load-balance-hello-world/), CC @londoncalling

**Comment by londoncalling** [comment]
@KickingTheTV @pkennedyr Hi guys, I have the example which is described in [docker-cloud/apps/load-balance-hello-world.md](https://docs.docker.com/docker-cloud/apps/load-balance-hello-world/) up and running to try and test this for @mochawich . 

It's Hello World running as a service called `web` in 8 containers, load balanced across 8 nodes with a single-container service Load Balancer (`lb`). 

I am trying to test using _servicename_._username_.svc.dockerapp.io (replacing  _servicename_ with my service name `lb` and _username_ with my username on Cloud), along with some other things to try and make this work, but I haven't figured it out. 

Can you all help with this? If you get a chance, it would be great to just have a look in person.
