### ISSUE TITLE
Docs to install docker-compose

### ISSUE THREAD

**Issue by barrystaes** [docker/docker.github.io#4126]
Concerns file: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/), CC @mstanleyjones s

I just installed the latest docker (17.06.0-ce) on a new Ubuntu 16.04 system and now want to install `docker-compose`. So i went looking how to do this with current versions, and ended up on the page at https://docs.docker.com/compose/install/ which refers to that page for Ubuntu.

But this page (and the CE page it links to) does not mention `docker-compose` at all.
How to install it?

I cant believe this went missing from the docs, but it certainly looks like it..

**Comment by mstanleyjones** [comment]
After you install Docker (step 1), which it sounds like you have done, to install Docker Compose on Linux, you need to follow step 3-6 to download the `docker-compose` binary from Github and install it.  I think the current step 1 should be listed as a prerequisite instead of the first step.

**Comment by barrystaes** [comment]
Indeed @mstanleyjones i misread step 1. My bad.

This likely confused me before, because i usually end up refering to a digitalocean howto. (which is step 3 ad-verbatim)

**Comment by londoncalling** [comment]
@barrystaes @mstanleyjones  can you guys take a look at the linked PR ^^ and see if this helps? Please approve if so.

**Comment by londoncalling** [comment]
This was fixed in #4130 (see https://docs.docker.com/compose/install/), so closing for now, @barrystaes feel free to ping us again if you think the docs need more changes.
