### ISSUE TITLE
Wrong install instruction for machine's bash completion

### ISSUE THREAD

**Issue by albers** [docker/docker.github.io#4138]
The download instructions in https://docs.docker.com/machine/completion/ are wrong:
```bash
curl -L https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker > /etc/bash_completion.d/docker
```
Instead of installing bash completion for Machine, the code downloads the current development version of Docker's bash completion over the installed version of Docker's completion. This will introduce inconsistencies, e.g. completion for unreleased features.

**Comment by mstanleyjones** [comment]
https://github.com/docker/machine/tree/master/contrib/completion

**Comment by johndmulhausen** [comment]
We should advise users to check out the above path that @mstanleyjones posted and choose what's right for their shell, etc. Also D4M/D4W probably already install auto-complete scripts at install time, so advise that.

**Comment by albers** [comment]
It is important to use a versioned url here so that the released binary and its completion match.
For the current 0.12.2 release, this would be
https://github.com/docker/machine/tree/v0.12.2/contrib/completion

**Comment by londoncalling** [comment]
@mstanleyjones, given @albers last comment especially (and the whole issue in general), can you clarify what needs to be done here, specifically with reference to the [current doc](https://docs.docker.com/machine/completion/)?

Should the paths as given currently, be removed and simply replaced with versioned paths to the Machine command completion scripts in the Machine repo? (e.g., https://github.com/docker/machine/tree/v0.12.2/contrib/completion)

**Comment by albers** [comment]
I created a PR with a fixed url. PTAL.
