### ISSUE TITLE
Markdown to HTML regressions from Hugo to Jekyll

### ISSUE THREAD

**Issue by londoncalling** [docker/docker.github.io#414]
### Problem description

We've had a few regressions in how markdown converts to HTML since the switch to Jekyll. Here are two I've seen so far:

1. URLs do not automatically convert to links unless they are explicitly formatted as such, either with `<a href="link">link text</a>, or in markdown with `[link text](URL)`

2. On-page links do not convert properly (e.g., `#what-you-can-do`)

See PR https://github.com/docker/docker.github.io/pull/413 for examples.

**Comment by johndmulhausen** [comment]
Issue #2 fixed in 47de0e2073d5800012c6c1d76e84fc71a929a72d

I think the explicit formatting of links is an okay expectation to set? There are probably cases where we don't necessarily want to make things a link, like http://example.com or http://localhost right?

**Comment by londoncalling** [comment]
@johndmulhausen sounds great! Closing the issue, thanks!
