### ISSUE TITLE
naive question

### ISSUE THREAD

**Issue by highpost** [docker/docker.github.io#4140]
File: [get-started/index.md](https://docs.docker.com/get-started/), CC @johndmulhausen 

As I'm reading this section, it's not clear when I run "docker run hello-world" where the container is actually running. Is it local on my Mac or on a remote Docker server?

I saw the first time I ran "docker run hello-world" that the hello-world container didn't exist and so the client instantiated it. But where did this occur?

So, two things aren't clear: where is the container and where was it run. Thx.

**Comment by mstanleyjones** [comment]
If you're on a Mac, the container is actually running on a very slim Linux VM inside the Mac. If you're on Linux, it's running directly on your localhost. If you're on Windows Server, it's running locally. If you're on Windows 10, it may be running within a slim VM. 😂

**Comment by joaofnfernandes** [comment]
@highpost I'm closing this issue since you have an answer, but feel free to comment if you still don't understand this.
