### ISSUE TITLE
Update storage-driver for promotion of overlay2

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#4141]
### Problem description

https://github.com/moby/moby/pull/34430 updated the list of storage-drivers and promoted overlay2 over aufs.

As a result, aufs will no longer be selected automatically if the required kernel modules are installed to support it. For comparison;

Before this PR (taking Ubuntu 16.04 as example, because it always has kernel 4+)

- When installing docker on a Ubuntu 16.04 machine with the `linux-image-extra` package installed (which provides `aufs`), docker would select `aufs` as storage driver.
- When installing docker on a Ubuntu 16.05 machine _without_ the `linux-image-extra` package installed, docker would select `overlay2`

After this PR, `overlay2` will be selected as the default, _unless_ an existing `aufs` directory was found (so users that are currently running `aufs` will stay on `aufs` unless they do a "factory reset" and wipe out their `/var/lib/docker` directory)

### Problem location

Most likely this section needs an update; https://docs.docker.com/engine/userguide/storagedriver/selectadriver/

### Project version(s) affected

This change will be included in the next Docker release that is using the current master of the moby/moby repository (17.08)

**Comment by AkihiroSuda** [comment]
@mstanleyjones @thaJeztah What's current status?
