### ISSUE TITLE
Docker volume create should have --name flag in doc

### ISSUE THREAD

**Issue by tobeck** [docker/docker.github.io#4148]
File: [engine/admin/volumes/volumes.md](https://docs.docker.com/engine/admin/volumes/volumes/), CC @mstanleyjones
 
sed -i -e \`s/docker volume create my-vol/docker volume create --name my-vol/g\` engine/admin/volumes/volumes.md

**Comment by mstanleyjones** [comment]
Actually either way works:

```
$ docker volume create my-vol
my-vol

$ docker volume create --name my-vol1
my-vol1

$ docker volume ls
local               my-vol
local               my-vol1

**Comment by tobeck** [comment]
It works if you run it without --name on OSX but not on CentOS7

[root@hostname ~]# docker volume create my-vol
"docker volume create" accepts no argument(s).
See 'docker volume create --help'.

Usage:  docker volume create [OPTIONS]

Create a volume
[root@hostname ~]# docker --version
Docker version 1.12.6, build 88a4867/1.12.6
[root@hostname ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

**Comment by mstanleyjones** [comment]
Whoa... that's weird. @thaJeztah is this a bug?

**Comment by thaJeztah** [comment]
in docker 1.12, only the `--name foo` option was supported; later versions added support for creating without having to use the `--name` flag
