### ISSUE TITLE
404 at /samples/maven/

### ISSUE THREAD

**Issue by Farhood0011** [docker/docker.github.io#4150]
URL: /samples/maven/

Hi, This page is not available anymore.
I would like to know how to convert Dockerfile commands to Maven commands.

**Comment by willthames** [comment]
Looks like there has been a docs restructure - /samples/library/maven works. 

There are a lot of broken links due to this restructure that should be fixed.

**Comment by johndmulhausen** [comment]
Fixed by #4195 (will be live in 15 minutes)
