### ISSUE TITLE
Instructions on how to actually set up a webhook

### ISSUE THREAD

**Issue by HaraldNordgren** [docker/docker.github.io#4152]
File: [docker-hub/webhooks.md](https://docs.docker.com/docker-hub/webhooks/), CC @johndmulhausen 

This page is the top reply on Google, but doesn't contain any info on how to actually set up a webhook.

**Comment by HaraldNordgren** [comment]
When will I see the changes on https://docs.docker.com/docker-hub/webhooks/?

**Comment by mstanleyjones** [comment]
The changes are already published, but there is a problem. I filed https://github.com/docker/docker.github.io/pull/4171.

**Comment by mstanleyjones** [comment]
@HaraldNordgren the doc is live. Thank you! 🎉
