### ISSUE TITLE
Confusion with using device-mapper

### ISSUE THREAD

**Issue by ksemaev** [docker/docker.github.io#4166]
### Problem description

The description of storage with device mapper does not explain disk usage issues and  /usr/lib/docker-storage-setup/docker-storage-setup config file.

### Problem location

https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#related-information
https://docs.docker.com/v1.12/engine/userguide/storagedriver/device-mapper-driver/

- Other: 
lvs:
docker-pool         docker twi-aot--- 12.44g             27.35  3.92

while docker info:
Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Data Space Used: 3.938 GB
 Data Space Total: 13.36 GB
 Data Space Available: 9.42 GB
 Metadata Space Used: 1.249 MB
 Metadata Space Total: 29.36 MB
 Metadata Space Available: 28.11 MB
 Thin Pool Minimum Free Space: 1.336 GB

Why do I have Space Available: 9.42 GB, but lvs shows that I have 30% used of 12Gb thin pool?

### Suggestions for a fix
Explain how to monitor real space usage

**Comment by mistyhacks** [comment]
@cpuguy83 PTAL

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
