### ISSUE TITLE
The quick start guide results in weird code placement [x-post docker/compose]

### ISSUE THREAD

**Issue by shin-** [docker/docker.github.io#4176]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/), CC @londoncalling

Originally docker/compose#1154

> **Problem**
>
> On Quick Start section under Create a Docker image, the Dockerfile copies over the current directory into the image and the Docker-compose.yml file mounts the current directory inside of the container, both actions result in code being under /code directory. For beginners this example makes more complicated to understand how the data got there.
>
> **Solution**
>
> Break up the example into two parts, explicitly showing how to both actions end up having the /code files inside of the running container.

**Comment by londoncalling** [comment]
@shin- I followed the related PR's, issues, and conversation threads, starting from [docker/compose#1154](https://github.com/docker/compose/issues/1154), and compared to our current Compose getting started, and I believe this was addressed long ago. 

What do you think?

**Comment by shin-** [comment]
@londoncalling My understanding is that the part that's criticized is still there. Note how the Dockerfile has the instruction `ADD . /code`, and the Compose file has the following section:
```yaml
volumes:
  - .:/code
```

One way to improve it could be to omit the `volumes:` section at the beginning of the tutorial, explain how the code is statically copied into the image. Then re-introduce it and explain how one could use a host mount to have their changes appear in real time inside the running container while they develop.

Does that make sense?

**Comment by londoncalling** [comment]
Hi @shin- yes that makes sense. I'll do this tomorrow, thanks!
