### ISSUE TITLE
404 at /v1.11/installation/

### ISSUE THREAD

**Issue by agershon1** [docker/docker.github.io#4182]
URL: /v1.11/installation/

**Comment by mstanleyjones** [comment]
Not sure how you came to this URL, but you might want to look at https://docs.docker.com/v1.11/engine/installation/mac/ or https://docs.docker.com/v1.11/engine/installation/windows/ or https://docs.docker.com/v1.11/engine/installation/linux/ubuntulinux/ or another of the "sibling" URLs in the left-hand navigation. Be aware that this is a very old version of Docker. If you want the latest, use https://docs.docker.com/engine/installation/.
