### ISSUE TITLE
i want read it offline please

### ISSUE THREAD

**Issue by syahputrareza** [docker/docker.github.io#4199]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/), CC @londoncalling

**Comment by mstanleyjones** [comment]
You have a few options for this. The coolest one is you can run a mirror of the docs using our Docker containers. See https://cloud.docker.com/app/docs/repository/docker/docs/docker.github.io/tags for all available tags. For instance, to run the latest docs image:

```bash
docker run  -it -p 4000:4000 docs/docker.github.io:latest
```

Or you can run it as a service:

```bash
docker service create -p 4000:4000 --name localdocs --replicas 1 docs/docker.github.io:latest
```
