### ISSUE TITLE
docker api explorer broken with 502

### ISSUE THREAD

**Issue by seriousben** [docker/docker.github.io#4203]
### Problem description

https://docs.docker.com/engine/api/v1.30/ returns a 502 right now for me.

Some people on slack and at https://github.com/moby/moby/issues/34525 are saying it is fixed but I still see the problem. 

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/api/v1.30/

<img width="876" alt="screen shot 2017-08-15 at 12 29 42 pm" src="https://user-images.githubusercontent.com/6145422/29325480-d4e36a94-81b5-11e7-8637-377b44ce8842.png">
### Project version(s) affected

N/A

### Suggestions for a fix

N/A

**Comment by mstanleyjones** [comment]
I can't replicate this. There have been intermittent problems reported with Cloudfront. Can you try in an incognito tab or clearing the cache by holding down the *shift* key when doing reload?

**Comment by seriousben** [comment]
I did multiple times since this morning without success and my co-workers
are also seeing this. But my phone renders it correctly.

**Comment by seriousben** [comment]
Fixed itself right now :)
