### ISSUE TITLE
What is the container status of 'Dead'?

### ISSUE THREAD

**Issue by twang2218** [docker/docker.github.io#4211]
File: [edge/engine/reference/commandline/ps.md](https://docs.docker.com/edge/engine/reference/commandline/ps/), CC @johndmulhausen

In the document, it listed a set of possible status, `created|restarting|running|removing|paused|exited|dead`, however, there is no explanation of each status.

I found an article explained some of the status: http://docker-saigon.github.io/post/Docker-Internals/ , but not all of them, especially the `dead` status. What is the difference between `dead` and `exited`?

I think we need some docs explain the lifecycle of a docker container and link the reference here.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #502](https://github.com/docker/cli/issues/502) via [**ZenHub**](https://www.zenhub.com/)
