### ISSUE TITLE
Clarification on multiple scope request when using token authentication registry

### ISSUE THREAD

**Issue by Simonot** [docker/docker.github.io#4219]
File: [registry/spec/auth/token.md](https://docs.docker.com/registry/spec/auth/token/), CC @joaofnfernandes

Hello, I am not sure to understand completely the request to ask when you have multiple scopes.

Docs says:
"This query parameter should be specified multiple times if there is more than one scope"
Then "The above example would be specified as: scope=repository:samalba/my-app:push"
Nevertheless the "above example" is

> Www-Authenticate:` Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:samalba/my-app:pull,push"

Where there are 2 scopes: pull and push

Nevertheless in the Example session, the request made is:

> https://auth.docker.io/token?service=registry.docker.io&scope=repository:samalba/my-app:pull,push

My question is should we use the Example request or the follwing one:
https://auth.docker.io/token?service=registry.docker.io&scope=repository:samalba/my-app:pull&scope=repository:samalba/my-app:push

If the answer is the second request, then the doc should be updated and say:

> "The above example would be specified as: scope=repository:samalba/my-app:push and scope=repository:samalba/my-app:pull"

Thank you for your time

**Comment by mstanleyjones** [comment]
@stevvooe PTAL

**Comment by stevvooe** [comment]
`push` and `pull` are not separate scopes. It is one scope with two actions. However, it can be represented as two scopes, but usually `push` alone is not useful, as one cannot figure out the information required to perform the push properly.
