### ISSUE TITLE
Add IBM Z for EE as Supported Platforms 

### ISSUE THREAD

**Issue by mideidocker** [docker/docker.github.io#4220]
File: [engine/installation/index.md](https://docs.docker.com/engine/installation/), CC @mstanleyjones 

IBM Z is mentioned only in CE/Ubuntu here: 
https://docs.docker.com/engine/installation/#server

Need to also mention for EE for Ubuntu/RHEL/SLES
<img width="913" alt="screen shot 2017-08-16 at 6 17 56 am" src="https://user-images.githubusercontent.com/9438885/29365170-d8dcbc00-824a-11e7-889f-7bceb4cf80a0.png">

NOTE: For the EE 17.6.1 release, IBM Z is available only as EE Basic.

**Comment by mstanleyjones** [comment]
This was due to the race condition between 17.6.1 EE vs CE.
