### ISSUE TITLE
Feedback for: engine/examples/mongodb.md

### ISSUE THREAD

**Issue by Xiobe** [docker/docker.github.io#424]
URL: [https://docs.docker.com/engine/examples/mongodb.md](https://docs.docker.com/engine/examples/mongodb/)

I've been trying the tutorial but the line
RUN echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.0.list

fails on lsb_release since it is not available in the container. I am running my docker on an Ubuntu Xenial and when I do it on the command line it works so it is in the container itself it doesn't work.

**Comment by johndmulhausen** [comment]
@ManoMarks Do we have a better MongoDB sample? This one is 2 votes up, 3 votes down, and this report of problems.

**Comment by mstanleyjones** [comment]
Thanks for the report, @Xiobe. Let me do some testing locally and get back with you when I find a workaround or the missing step.

**Comment by mstanleyjones** [comment]
Wow this took me  while to get back to, but it will be fixed when #2523 is merged. Meanwhile, you can get this working by just adding an extra `RUN` line in the Dockerfile, as shown there.
