### ISSUE TITLE
Update UCP redirect

### ISSUE THREAD

**Issue by JimGalasyn** [docker/docker.github.io#4241]
Reported by @mbentley: Clicking the Documentation link in UCP takes me to https://www.docker.com/ddc-docs and immediately redirects back to https://docs.docker.com/. 
Redirect seems to be broken.

**Comment by joaofnfernandes** [comment]
https://www.docker.com/ddc-docs now direct users to https://docs.docker.com/datacenter/ucp/2.2/guides/
