### ISSUE TITLE
No links for Docker EE on Server 2016

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#4243]
File: [manuals.md](https://docs.docker.com/manuals/), CC @johndmulhausen 

I couldn't find a link to https://docs.docker.com/engine/installation/windows/docker-ee/ in the `Tools` table.

**Comment by mstanleyjones** [comment]
@gbarr01 let's talk about this one next week. :)

**Comment by mstanleyjones** [comment]
Consider reusing the tables on https://docs.docker.com/engine/installation/ instead of the table that is currently on the page.

**Comment by gbarr01** [comment]
@mstanleyjones , I can use https://docs.docker.com/engine/installation/ .. but it does not include any of the tools/products on https://docs.docker.com/manuals/. Shall I remove those or create a separate table?

**Comment by mstanleyjones** [comment]
Closed via #4425
