### ISSUE TITLE
Get rid of client side redirects

### ISSUE THREAD

**Issue by aduermael** [docker/docker.github.io#425]
### Problem description

Current 404 (not found) page is a 240KB JS script that operates client side redirects.
A 6500 lines script that includes all our redirect rules... This script is built using front-matter aliases and what's in `_data/redirects.csv`.
This should be handled server side.

### Suggestions for a fix

@johndmulhausen suggests that we use `redirect_from` which Jekyll supports, to generate 301 redirects.

**Comment by johndmulhausen** [comment]
https://github.com/docker/docker.github.io/pull/152 is open to test this solution

**Comment by thaJeztah** [comment]
reopening GitHub auto-closed this because of an old commit being merged https://github.com/docker/docker.github.io/commit/e44f5d87968ccdc2680bf250f94d5ad1f8c7bd6a

**Comment by aduermael** [comment]
thank you @thaJeztah!

**Comment by johndmulhausen** [comment]
Fixed in 949a89e6ea4d47e8306451d84752654d18c5253b
