### ISSUE TITLE
Missing Release Notest for Docker Compose versions later 1.13.0.

### ISSUE THREAD

**Issue by zekefast** [docker/docker.github.io#4263]
File: [release-notes/docker-compose.md](https://docs.docker.com/release-notes/docker-compose/), CC @johndmulhausen

1.15.0 version of Docker Compose is available, but release notes present only for 1.13.0.

**Comment by mstanleyjones** [comment]
@shin- we need to come up with a better process for this. I'll fix it for now.

**Comment by shin-** [comment]
Sorry, I didn't realize release notes were on the docs site as well. I can easily add it as part of the docs update I make for each release - will do that from now on.

**Comment by mstanleyjones** [comment]
Yeah this is something new we did several months ago, so that customers don't have to search everywhere for the changelogs. Thanks!

**Comment by zekefast** [comment]
Thanks!
