### ISSUE TITLE
Docker volume with Azure

### ISSUE THREAD

**Issue by jmaitrehenry** [docker/docker.github.io#4266]
### Problem description

The documentation page for share volume with cloudstor on azure may have more informations, like how to configure the Account storage on Azure and what is supported or not.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/docker-for-azure/persistent-data-volumes

### Project version(s) affected

I testing on CoreOS alpha with docker 17.05.0-ce and docker4x/cloudstor:17.05.0-ce-azure2 and 

### Suggestions for a fix

We can add a part about how to install the plugin, how to create the storage account, add a note about `Secure transfer required` option not supported on linux.

**Comment by mstanleyjones** [comment]
@ddebroy do you have any insight?

**Comment by jmaitrehenry** [comment]
I could try to add some screenshot and other informations.
I could add a second PR once this issue will be released: https://github.com/docker/for-azure/issues/28

**Comment by mstanleyjones** [comment]
Unsure the status of this. @friism @ddebroy

**Comment by ddebroy** [comment]
Bradley Wong (can't find his github alias) will need to comment on this.

**Comment by mstanleyjones** [comment]
@brawong PTAL

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
