### ISSUE TITLE
Add note for UCP 1.1 -> UCP 2.1 upgrades

### ISSUE THREAD

**Issue by mark-church** [docker/docker.github.io#4267]
File: [datacenter/ucp/2.0/guides/installation/upgrade.md](https://docs.docker.com/datacenter/ucp/2.0/guides/installation/upgrade/), CC @joaofnfernandes

Findings from field show that direct UCP 1.1 -> 2.1 upgrades is much safer than a 1.1 -> 2.0 -> 2.1 upgrade. A direct upgrade should be the suggested path instead of going to 2.0.

**Comment by joaofnfernandes** [comment]
@dhiltgen can you confirm?

**Comment by mark-church** [comment]
This issue has a better description of the full upgrade path: https://github.com/docker/docker.github.io/issues/4269

I think we need something like this starting from UCP 1.1 and showing explicit upgrade paths to both UCP 2.1 and UCP 2.2 (our current supported versions). Ideally, we would always have an upgrade path chart for every currently supported version.

```
When upgrading to UCP 2.2 ...
- If upgrading from UCP 1.1:
  - Upgrade from UCP 1.1 -> UCP 2.1 -> UCP 2.2
- If upgrading from UCP 2.0
  - Upgrade from UCP 2.0 -> UCP 2.1 -> UCP 2.2
- If upgrading from UCP 2.1
  - Upgrade from UCP 2.1 -> UCP 2.2
```

Not sure if this should be described on the final state version upgrade page or whether it should be referenced backwards to all the initial version pages too.

**Comment by JimGalasyn** [comment]
Added @mark-church's table to the 2.2 upgrade topic.
