### ISSUE TITLE
Ubuntu URL Changes 17.03

### ISSUE THREAD

**Issue by kizbitz** [docker/docker.github.io#4268]
CC @mstanleyjones

This is for EE 17.03 installation instructions: https://docs.docker.com/v17.03/engine/installation/linux/ubuntu/#install-using-the-repository

I believe the lines should be (add `/ubuntu`):
`curl -fsSL <DOCKER-EE-URL>/ubuntu/gpg | apt-key add -`
and
`add-apt-repository "deb [arch=amd64] <DOCKER-EE-URL>/ubuntu $(lsb_release -cs) stable-17.03"`

**Comment by mstanleyjones** [comment]
Closed via #4272 (will take some time to show up)
