### ISSUE TITLE
Document upgrade path for UCP

### ISSUE THREAD

**Issue by mark-church** [docker/docker.github.io#4269]
File: [datacenter/ucp/2.2/guides/admin/install/upgrade.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/upgrade/), CC @joaofnfernandes 

Need to have an upgrade path chart on this page:

- If upgrading from UCP 1.1:
  - Upgrade from UCP 1.1 -> UCP 2.1 -> UCP 2.2
- If upgrading from UCP 2.0
  - Upgrade from UCP 2.0 -> UCP 2.1 -> UCP 2.2
- If upgrading from UCP 2.1
  - Upgrade from UCP 2.1 -> UCP 2.2

cc @dhiltgen 

But in a pretty chart :)

**Comment by joaofnfernandes** [comment]
We have [something like that for DTR](https://docs.docker.com/datacenter/dtr/2.3/guides/admin/upgrade/).
@dhiltgen can you take a look at ^^ at tell me if UCP follows the same policy?

**Comment by mark-church** [comment]
@joaofnfernandes there is a similar doc here: https://success.docker.com/KBase/Upgrading_to_Docker_17.03_(or_DDC_on_Engine_1.13)

However, this doc needs to be updated for UCP 2.2 / DTR 2.3 and probably made a little bit clearer with an explicit version chart.

**Comment by dhiltgen** [comment]
Prior to 2.2, we had upgrade flows going all the way back to 1.0, but the overhead was getting unwieldy, so we dropped all upgrade flows except N-1.  We should recommend customers running anything below 2.1 that they upgrade to the **latest** 2.1 version first, then upgrade to 2.2

**Comment by JimGalasyn** [comment]
Fixed in [Recommended upgrade paths](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/upgrade/#recommended-upgrade-paths).
