### ISSUE TITLE
Update UCP LDAP docs with change in behavior

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#4273]
File: [datacenter/ucp/2.2/guides/admin/configure/external-auth/index.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/external-auth/)

> Also, when you switch from the built-in authentication to using LDAP authentication, all manually created users whose usernames do not match any LDAP search results become inactive, with the exception of the recovery admin user which can still login with the recovery admin password.

This is no longer true. Users that were manually created will still be active.

**Comment by JimGalasyn** [comment]
Yes, I noted this in the topic.

**Comment by joaofnfernandes** [comment]
This is documented so we can close this one.
