### ISSUE TITLE
UCP article not showing in TOC

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#4274]
File: [datacenter/ucp/2.2/guides/admin/configure/external-auth/enable-ldap-config-file.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/external-auth/enable-ldap-config-file/)

This is not showing up in the TOC

**Comment by JimGalasyn** [comment]
This one is weird, because the topic shows up in the TOC, but when you click, the topic loads but the TOC breaks.

**Comment by joaofnfernandes** [comment]
It seems we're missing a `/` at the end of the TOC entry 😂. I've put a PR with that change ^^

**Comment by JimGalasyn** [comment]
D'oh, thanks!

**Comment by JimGalasyn** [comment]
Fixed!
