### ISSUE TITLE
How to use collections with stacks in UCP

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#4275]
@JimGalasyn commented on [Wed Jul 19 2017](https://github.com/docker/docs-private/issues/172)

We need to doc the `create stack` user flow and how it integrates with collections.

From @alexmavr : A "stack" is just a group of resources identified by a label. Therefore, the resources in a stack can be placed on multiple collections. Resources are placed in the user's default collection unless if an explicit com.docker.ucp.access.label is specified within the stack/compose file.

There aren't many 80%-use-case-benefits that I can think of to splitting stacks across collections, so I'm not sure if the Getting Started guide is the right spot to mention that a stack may span multiple collections. In the majority of cases, a stack file is the definition of an application, and anything that the user may have different permissions for would be external (such as an external network or secret, which could be managed in a different collection than the stack's target collection). For non-external resources in a stackfile, all of them will get deployed to a user's default collection if they don't have a `com.docker.ucp.access.label` specified in the stackfile itself.
 
If a resource does specify that label, then that resource will be targeted against that collection. 
Given that the purpose of a compose/stack file is typically to manage a single application, I would focus on the default collection feature in that context, and mention the access label override as a footnote. One of the main reasons why we added the default collection feature was to allow users to deploy the same stackfile on different contexts without editing labels every time

**Comment by JimGalasyn** [comment]
via @hansfrederickbrown

**Comment by JimGalasyn** [comment]
Related feedback from @hansfrederickbrown  https://beta.docs.docker.com/datacenter/ucp/2.2/guides/user/services/deploy-a-service/

- Explain how to deploy a service to a collections.
- Explain how to find the resources that are specific to a given service.
- More explanation about the different sub sections of the Service create
  - Scheduling
  - Network
  - Environment
  - Resources
