### ISSUE TITLE
is it "docker0" or is it "bridge"

### ISSUE THREAD

**Issue by harridu** [docker/docker.github.io#4299]
File: [engine/userguide/networking/default_network/custom-docker0.md](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/), CC @mstanleyjones 
Is it possible that this article confuses "docker0" (shown by "brctl show") and "bridge" (listed by "docker network ls")? This makes this article very hard to understand.

**Comment by mstanleyjones** [comment]
It's not really wrong, though. The name of the bridge device in the **Linux kernel** is `docker0`. The name of the device from Docker's point of view is `bridge`, even if it's on Windows.

**Comment by JimGalasyn** [comment]
Closing -- feel free to re-open if you need more details.
