### ISSUE TITLE
please make *.json files in docker "diff-friendly"

### ISSUE THREAD

**Issue by harridu** [docker/docker.github.io#4300]
If I want to add a line in in /etc/docker/daemon.json, then I have to change the old last line, too. Before:
```
{
        "graph": "/export/docker-data",
        "storage-driver": "overlay"
}
```
After:
```
{
        "graph": "/export/docker-data",
        "storage-driver": "overlay",
        "fixed-cidr": "10.20.0.0/16"
}
```
See the comma I had to insert just to make json happy? On a "diff" output I see 2 changed lines, even though only a single option has been added. This leads to merge conflicts with your favorite version control system.

I'd love to write 
```
{
        "graph": "/export/docker-data",
        "storage-driver": "overlay",
}
```
right from the start.

**Comment by joaofnfernandes** [comment]
@harridu this isn't so much a docs request but a feature request to Docker. I'm going to move your issue to https://github.com/moby/moby to reflect that.
