### ISSUE TITLE
SoftLink > SoftLayer

### ISSUE THREAD

**Issue by wilburnvanessa** [docker/docker.github.io#4304]
File: [engine/installation/index.md](https://docs.docker.com/engine/installation/), CC @mstanleyjones

Hello, I believe there's a typo on this page. This text:

```See also Docker Cloud for setup instructions for Digital Ocean, Packet, SoftLink, or Bring Your Own Cloud.```
The text should be SoftLayer and not SoftLink, right?

Thanks!

**Comment by joaofnfernandes** [comment]
@wilburnvanessa you're right, thanks for catching it! This time I've created #4307 to fix it, but you can help us too.
For small things like this, feel free to propose the change even if you're not really sure if the article is wrong or not. It will probably take you less time to propose a change than to file an issue 😀


![1](https://user-images.githubusercontent.com/1525937/29531019-82a4f270-865b-11e7-9094-d3d65034db32.png)
