### ISSUE TITLE
404 at /datacenter/dtr/2.3/admin/upgrade/

### ISSUE THREAD

**Issue by ryannoblett** [docker/docker.github.io#4305]
URL: /datacenter/dtr/2.3/admin/upgrade/

There are no instructions for upgrading to DTR 2.3.

**Comment by joaofnfernandes** [comment]
@ryannoblett can you tell me where you found that url so that we can fix it? Was it on the left navigation of the docs site?

You can use https://docs.docker.com/datacenter/dtr/2.3/guides/admin/upgrade/

**Comment by ryannoblett** [comment]
@joaofnfernandes Yeah, I found it when looking at the release notes for 2.3, here:
https://docs.docker.com/datacenter/dtr/2.3/guides/release-notes/

If you click the link for "the upgrade instructions", it leads there.
