### ISSUE TITLE
Issue triage duty ♻️

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#4306]
The triage guru is responsible for labeling issues/PRs with the appropriate product area, assign someone to the issue/PR, and close duplicates. The triage duty rotates every week. It's up to you how you manage your time. **It probably shouldn't take more than half an hour a day or 2 hours a week.**

- [ ] @gbarr01 
- [ ] @JimGalasyn 
- [x] @joaofnfernandes

If you don't know which labels to apply, assign the issue/PR to someone that has more experience with that specific product area.

## Labels

We have a ton of labels, but these are the most important ones:

| Label                       | Description                                                                                              |
|:-------------------|:--------------------------------------------------------------------|
| `priority/*`             | Priority in terms of impact to users                                                        |
| `area/*`                  | The product, component, or area of the issue                                      |
| `platform/*`           | The issue is specific to a platform (Windows, arm)                              |
| `feature-request` | Feature request for the docs site or a product                                      |
| `support-request`| Issue is asking for help troubleshooting, not reporting an issue          |

**Comment by gbarr01** [comment]
@joaofnfernandes , time to close this?

**Comment by joaofnfernandes** [comment]
Time to close it 😢
