### ISSUE TITLE
Windows Toolbox installation step 3.1 is confusing

### ISSUE THREAD

**Issue by keitherskine** [docker/docker.github.io#4309]
File: [toolbox/toolbox_install_windows.md](https://docs.docker.com/toolbox/toolbox_install_windows/), CC @londoncalling 

In step 3.1, it says "On your Desktop, find the Docker Toolbox icon.".  There are three icons in the adjoining picture.  Those icons match the ones on my Windows desktop, but none of them is called Docker Toolbox.  Which icon is the instruction referring to?

**Comment by londoncalling** [comment]
@keitherskine sorry about the confusion, the linked pull request ^^ should clear this up

**Comment by keitherskine** [comment]
Thank you, @londoncalling , that PR looks good.
