### ISSUE TITLE
Docs do not correctly render on Firefox at some window widths

### ISSUE THREAD

**Issue by Wilfred** [docker/docker.github.io#4319]
<img width="1566" alt="screen shot 2017-08-22 at 10 17 06" src="https://user-images.githubusercontent.com/70800/29558128-1e6e2e16-8723-11e7-98db-08d5d72ef653.png">

This is Firefox 55.0.2. Making the window narrower or wider fixes the issue:

Narrower:

<img width="1056" alt="screen shot 2017-08-22 at 10 18 34" src="https://user-images.githubusercontent.com/70800/29558192-50299b34-8723-11e7-8473-940cf4dcd6e6.png">

Wider:

<img width="1671" alt="screen shot 2017-08-22 at 10 18 41" src="https://user-images.githubusercontent.com/70800/29558199-5847659e-8723-11e7-9f6f-374a07b80e66.png">

File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @londoncalling

**Comment by londoncalling** [comment]
@Wilfred the docs site is designed to lose the left and right side TOC menus when you reduce the width of the browser past a certain point, or if you are on mobile those TOC's are never displayed.

When the browser width is narrow enough to lose the TOC's, you can use the hamburger menu in the upper right (the behaviour of this menu differs depending whether you are on a desktop or mobile). This menu, on a desktop, will give you back the left side overall topic list to the left. On mobile, I believe you get the topic list as an overlay. The on-page TOC (right side menu) is not available on the narrow browser width view. If the browser is very narrow, you will also get an overlay topic list on a desktop.

When you widen the browser width again on a desktop, you get both topic lists back.

Please see this video as an example: https://youtu.be/sclDyfDI-T0

**Comment by londoncalling** [comment]
@jsouth See @Wilfred 's first screen snap, it does look like there is an issue at a certain browser width where the docs content in the main body disappears. I could not reproduce it on Firefox or any other browser.

**Comment by londoncalling** [comment]
@Wilfred , our designer will be back next week, and he and I will take a look at this together, thanks!

**Comment by londoncalling** [comment]
@Wilfred  re-tried and could not reproduce in either Firefox or Chrome. Feel free to re-open if you are still seeing the issue.

**Comment by Wilfred** [comment]
Thanks. I'm seeing the same thing: I can no longer reproduce.
