### ISSUE TITLE
docker volumes doc needs to be update to also provide service option

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#4328]
This utilizes `docker run`, however it should also describe how to use a volume using `docker service create`

File: [engine/admin/volumes/volumes.md](https://docs.docker.com/engine/admin/volumes/volumes/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
It's the exact same, and also specifically called out: https://docs.docker.com/engine/admin/volumes/volumes/#syntax-differences-for-services

**Comment by yongshin** [comment]
Awesome thanks for the changes! It helps that it now specifically shows examples of using services.
