### ISSUE TITLE
Integrate note about shared volumes location in docker toolbox

### ISSUE THREAD

**Issue by sgratzl** [docker/docker.github.io#4334]
File: [toolbox/toolbox_install_windows.md](https://docs.docker.com/toolbox/toolbox_install_windows/)

I ran in the issue when installing the docker toolbox that the vm wasn't able to find my shared volume. The reason was that according to the README of boot2docker only the directory `C:\Usres` is mapped by default to the vm. see also https://github.com/boot2docker/boot2docker/blob/af8b089c8c528ed08ad2074c83f1756a5aeaa4ef/README.md#virtualbox-guest-additions.  However, my workspace was under `C:` only. 

A note about this behavior/restriction might avoid others to run into the same problem.

**Comment by gbarr01** [comment]
@mstanleyjones , ran into such a note here: https://docs.docker.com/compose/gettingstarted/#step-6-re-build-and-run-the-app-with-compose

**Comment by mstanleyjones** [comment]
Thanks!
