### ISSUE TITLE
Documentation should cover how to prevent container from using swap

### ISSUE THREAD

**Issue by delcypher** [docker/docker.github.io#4335]
File: [engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/), CC @mstanleyjones

The documentation for `--memory-swap` is rather confusing. What I wanted to do was run a container without allowing it to use swap. An initial guess would be doing something like
`--memory 1g --memory-swap 1g` but reading the documentation says that

```
If --memory-swap is set to the same value as --memory, and --memory is set to a positive integer, the effect is the same as setting --memory-swap to 0 (the value is treated as unset).
```

that then implies the behaviour is what the behaviour would be if `--memory-swap` is not set.

```
If --memory-swap is unset, and --memory is set, the container can use twice as much swap as the --memory setting, if the host container has swap memory configured. For instance, if --memory="300m" and --memory-swap is not set, the container can use 300m of memory and 600m of swap.
```

To me this is not intuitive behaviour at all but if this is Docker's current behaviour I feel it should be documented more explicitly that this is the case. I also think that given that preventing as much swap use as possible is a common use case I feel that how to achieve this (if it is possible) should be explicitly documented. If it isn't possible to do this it should be documented.

**Comment by delcypher** [comment]
In fact I'm not convinced this documentation is accurate at all. I'm using Docker 17.06.0-ce. When I launch a container like so

```
docker run --rm -ti --memory 16g --memory-swap 16g image_name
```

I can inspect the container cgroup to see that `memory.memsw.limit_in_bytes` and `memory.limit_in_bytes` are set how I would intuitively expect them to be set

```
$ cd /sys/fs/cgroup/memory/docker/<id>
$ cat memory.memsw.limit_in_bytes 
16777216
$ cat memory.limit_in_bytes 
16777216
```

This directly contradicts what the documentation states.

**Comment by mstanleyjones** [comment]
@cpuguy83 this keeps coming up. Can you help me make it better?

**Comment by cpuguy83** [comment]
> if this is Docker's current behaviour I feel it should be documented more explicitly that this is the case.

Can you explain how it can be more explicitly documented?

**Comment by cpuguy83** [comment]
I'll have to go through all this again.
I think we had another similar issue...

**Comment by cpuguy83** [comment]
Ok, the disconnect is that `--memory-swap` is the memory+swap limit.
Setting the `memory-swap` **limit** to the same value as the memory limit effectively means there is no way to use swap in addition to RAM.

It might be nice if we abstracted this better (like with did with `--cpus`) rather than dealing with the direct cgroup controls.

**Comment by delcypher** [comment]
@cpuguy83 
> Can you explain how it can be more explicitly documented?

I mean explain explicitly how to setup a container to not use swap space (i.e. set `--memory X --memory-swap X`). The way the documentation is written write now implies this is impossible with is not the case.

**Comment by mstanleyjones** [comment]
If I understand this right, then you would accomplish the goal of never using swap for a container by setting `--memory` and `--memory-swap` to the same value. Right @cpuguy83 ?

(you could also just disable swap on your Docker host :trollface: )

**Comment by cpuguy83** [comment]
@mstanleyjones That is correct.

**Comment by joelchen** [comment]
@cpuguy83 What happens when both `--memory` and `--memory-swap` are unset? I cannot find the default documented.

**Comment by cpuguy83** [comment]
The default is no limit.

**Comment by joelchen** [comment]
@cpuguy83 If I understand correctly, if both `--memory` and `--memory-swap` are unset, and `free -h` shows total swap as 1.0G, Docker container will use up to 1.0G of swap? If both `--memory` and `--memory-swap` are unset, and `free -h` shows total swap as 0B, Docker container does not use any swap?

**Comment by cpuguy83** [comment]
I doubt that "free" is cgroup aware.
But yes if there is no swap on the system then the container cannot use swap.
