### ISSUE TITLE
Add details to config networks topic

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#4344]
@JimGalasyn commented on [Tue Aug 15 2017](https://github.com/docker/docs-private/issues/230)

Incorporate feedback from @manishtomar in [Use a local node network in a swarm](https://beta.docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/use-node-local-network-in-swarm/):

1) It took me some time to understand the concept of `config-only` and `config-from` by reading https://github.com/mark-church/docs/blob/master/local-scope-swarm-networking.md#bridge-networking and https://github.com/moby/moby/pull/32981. It will be nice if some explanation for these or some links are there in the UCP docs. 
2) The steps do not say what scope to choose. I believe it is local for config-only and swarm for config-from network
3) Step 5 talks about "Macvlan configure" section. I couldn't find that in UI.
4) When creating local network, UCP is automatically prefixing with a particular host (ip-10-128-28-80 in my case). If I specify another prefix in the name when creating the network, it still prefixes that original host and generates `ip-10-128-28-80/ ip-10-128-0-100/macvlan` name. This is more of UCP issue but the docs didn't help.

I didn't reach a stage where I create a `config-from` network in UCP. All in all, I feel this is a pretty complicated topic which requires more documentation.  I think it will really help if there are  CLI commands specific to UCP (node prefixing part) that create config-only network followed by config-from network similar to how it is there in https://github.com/mark-church/docs/blob/master/local-scope-swarm-networking.md#bridge-networking. After that, there can be docs on how to achieve the same with webUI.

From:
[Clarify docs on macvlan network creation for EE+UCP #8496](https://github.com/docker/orca/issues/8496)

**Comment by JimGalasyn** [comment]
Currently, UCP web UI doesn't support `config-only`: [Network creation must include scope and config-from options #7050](https://github.com/docker/orca/issues/7050).

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #456](https://github.com/docker/docs-private/issues/456) via [**ZenHub**](https://www.zenhub.com/)
