### ISSUE TITLE
Review Engine EE installation articles

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#4347]
@joaofnfernandes commented on [Tue Aug 15 2017](https://github.com/docker/docs-private/issues/237)

For the 17.06.1 EE release we've updated some of the Engine EE installation articles to mention support for IBM Z.

We need to do a second pass on these articles to make sure we didn't miss anything.
- [ ] Does EE have support for CentOS?
- [ ] Do we need to make changes to RHEL/ Oracle, to mention the s309x repo?

**Comment by mstanleyjones** [comment]
I really think this is all done.... Yes, EE has support for CentOS, and the IBM Z stuff is in place.
