### ISSUE TITLE
mac上怎么安装docker，我安装后用iterm查版本提示找不到程序

### ISSUE THREAD

**Issue by taffy520** [docker/docker.github.io#4353]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/), CC @londoncalling

**Comment by joaofnfernandes** [comment]
@taffy520 I'm not sure if I understand your question. Are you telling that you've tried to install Docker for Mac, but when running `docker` on the terminal, it says that `docker cannot be found`?

If that's the case, try [checking this article](https://docs.docker.com/docker-for-mac/). It might help you troubleshoot.

**Comment by londoncalling** [comment]
@joaofnfernandes I got the title translated. They went through the install but when they tried the command to check the version,  it shows "software" not found

**Comment by londoncalling** [comment]
@taffy520 : Starting [here](https://docs.docker.com/docker-for-mac/install/#install-and-run-docker-for-mac), did all these steps work as described?

You have to: 1) Download the app, 2) click it/ start the install, 3) provide your system password and approve the install.

Also, you are on Mac, not Windows, right?

**Comment by taffy520** [comment]
是的，是在mac上，系统版本10.11.6，2015款mac，是这样的，从官网下载docker.dmg文件后点击安装，完成后打开有提示输入系统密码，然后显示启动中，启动完成后，我使用mac的终端工具命令docker -version或docker info都无法显示信息，总是提示command not found，是否此容器使用前需要配置路径？而且google了下也没有类似的问题解决方案。

**Comment by londoncalling** [comment]
@taffy520 well you should not need to do any other configuration. Here are some questions:

1. After you give your password and install completes, is there a whale in the upper right of your screen?  Like this:

![image](https://user-images.githubusercontent.com/11660803/29726621-4dcc5dd6-8985-11e7-9c09-dd7cfaf34866.png)

2. Do you get this popup information dialog? And do you click "Got it!" to dismiss it?

![image](https://user-images.githubusercontent.com/11660803/29726654-6ceb6158-8985-11e7-82fa-f6a7125bcbbb.png)

3. Are you typing commands in a terminal window like this?

![image](https://user-images.githubusercontent.com/11660803/29726696-9d8b4c4c-8985-11e7-8b9c-b722b9c2d1d2.png)

**Comment by taffy520** [comment]
没有显示gei it




发自网易邮箱大师
在2017年08月26日 02:08，Victoria Bialas 写道：

@taffy520 well you should not need to do any other configuration. Here are some questions:

After you give your password and install completes, is there a whale in the upper right of your screen? Like this:

Do you get this popup information dialog? And do you click "Got it!" to dismiss it?

Are you typing commands in a terminal window like this?

**Comment by ry4nz** [comment]
@taffy520 
Docker应该会安装到 `/usr/local/bin/docker`    
(Docker should be installed to `/usr/local/bin/docker`)

看看下面的命令在终端上输出是什么? 
(Can you check what's the output of the following commands on your terminal?)

```
echo $PATH  
```
```
ls -lrt /usr/local/bin/docker
```

**Comment by JimGalasyn** [comment]
Closing -- feel free to re-open if you're still having trouble.
