### ISSUE TITLE
Docs say DTR must be deployed on exactly UCP 2.0

### ISSUE THREAD

**Issue by alfred-landrum** [docker/docker.github.io#4356]
Should this say something like "2.0 or greater"?

File: [datacenter/dtr/2.1/guides/install/system-requirements.md](https://docs.docker.com/datacenter/dtr/2.1/guides/install/system-requirements/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
This seems to have been fixed by removing the version and instead, linking to the compatibility matrix.
