### ISSUE TITLE
Bad UCP Install Tag

### ISSUE THREAD

**Issue by mpanthofer** [docker/docker.github.io#4365]
### Problem description
    Instruction references an unavailable image tag for UCP install... 

### Problem location

UCP Install Step 2
>> "docker image pull docker/ucp:**2.2.1**" fails

### Project version(s) affected
Latest version of UCP

### Suggestions for a fix

>> "docker image pull docker/ucp:**2.2.0**" works

**Comment by JimGalasyn** [comment]
Thanks for the feedback! This is a transient issue, until we get ucp:2.2.2 posted. Currently, there's a public [ucp:2.2.2-rc1](https://hub.docker.com/r/docker/ucp/tags/) that you might want to try. In the meantime, I've reverted the version to 2.2.0.
