### ISSUE TITLE
Document what happens when removing a stack of services

### ISSUE THREAD

**Issue by waddles** [docker/docker.github.io#4366]
File: [engine/swarm/configs.md](https://docs.docker.com/engine/swarm/configs/), CC @mstanleyjones 
When you stop a stack with `docker stack rm <stack>`, does it remove *all* configs, including the ones you ran `--config-rm` on but have not yet deleted from the stack?

Also, is it in your roadmap to have a `docker stack config update <config>` command to update all services with that config file instead of having to create a new one, then `--config-add` and `--config-rm` it on all services?

**Comment by joaofnfernandes** [comment]
@dnephin might be able to clarify a couple of things:
* What is the behavior of deploying a stack, and then making updates to individual services? From what my tests suggest, the service will be updated.
* The behavior of `docker stack rm` will depend on whether or not the resources (network, configs, secrets) are declared as `external: true` on the compose file
* To update a stack, you make changes to your compose file, and then re-run `docker stack deploy -c <new-compose-file> <stack-name>`. If you use a new config in that file, your services will start using them. Keep in mind that configurations are immutable, so you won't be able to change the file for an existing service. Instead, you create a new config to use a different file.

**Comment by dnephin** [comment]
> When you stop a stack with docker stack rm <stack>, does it remove all configs, including the ones you ran --config-rm on but have not yet deleted from the stack?

It will remove any config that was created by `docker stack deploy` with the same stack name. It will remove a config, even if it's not referenced by a service, so it will still remove a config after a `docker service update --config-rm`

> Is it in your roadmap to have a docker stack config update <config> command to update all services with that config file instead of having to create a new one

As @joaofnfernandes mentioned the suggest way to handle updates is to edit the Compose file and then `docker stack deploy` again to perform the update. I believe this already handles the workflow you describe.
