### ISSUE TITLE
resource_constraints misleading for Windows 10

### ISSUE THREAD

**Issue by FFLSH** [docker/docker.github.io#4369]
File: [engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/), CC @mstanleyjones, @thaJeztah 

Leading on from [moby/#31604](https://github.com/moby/moby/issues/31604) clarification is required in the `resource_constraints` section, as containers running on Windows 10 have a hidden 1GB memory limit. I don't possess a full understanding of why this is and wouldn't be confident documenting it, however it needs to be documented.

**Comment by mstanleyjones** [comment]
@johnstep can you work with me on this? Are you the right person?

**Comment by johnstep** [comment]
Yes, I will help here.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
