### ISSUE TITLE
'/compose/compose-file/#links' should reflect '/compose/networking/#links' 

### ISSUE THREAD

**Issue by dgroomes** [docker/docker.github.io#4388]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @londoncalling 

caveat: I have only beginner knowledge about Docker Compose.

I'm trying to answer the question: 

> Do I need a 'links' section in my Compose file for my service 'a' to talk to my service 'b'?

I noticed conflicting advice. The description at https://docs.docker.com/compose/compose-file/#links is a little misleading and out-of-date I think when you compare it to https://docs.docker.com/compose/networking/#links. 

Where https://docs.docker.com/compose/networking/#links includes the critical distinction that links are 

> not required to enable services to communicate - by default, any service can reach any other service at that service’s name'

, then notice at https://docs.docker.com/compose/compose-file/#links you find that actually the opposite is suggested with 

> Link to containers in another service.

At https://docs.docker.com/compose/compose-file/#links I think it would useful to explain that links are not necessary for services to communicate. And that instead you can just rely on the default behavior.

I'm trying hard to write an idiomatic docker-compose file, and I'm relying on the docs.

Please let me know if I'm off base on this one, thanks

**Comment by londoncalling** [comment]
Thanks @dgroomes, I've made a small docs update per the referenced pull request ^^ and tagged you on the PR. Let me know what you think.
