### ISSUE TITLE
Document How To Manage a Swarm Registry

### ISSUE THREAD

**Issue by kolotyluk** [docker/docker.github.io#4398]
File: [engine/swarm/admin_guide.md](https://docs.docker.com/engine/swarm/admin_guide/), CC @mstanleyjones 

It would be very useful if there was some complete documentation on how to run a docker registry local to the swarm.

I have found many references to this on the internet, but they are all incomplete in detail, so it is not possible to recreate those solutions.

This is perhaps the best solution I have discovered, but I cannot reproduce it.

https://stackoverflow.com/questions/39370925/docker-swarm-worker-nodes-not-finding-locally-built-image

**Comment by mstanleyjones** [comment]
@stevvooe can you help out with this?

**Comment by stevvooe** [comment]
Is there anything that is specifically missing from the documentation? https://github.com/docker/docker.github.io/blob/master/registry/deploying.md should cover this.
