### ISSUE TITLE
How to customize TLS certs for UCP and DTR when using cloud edition

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#4407]
The docs used to teach how to do this, but we've removed it since then. https://github.com/docker/docker.github.io/blob/v17.03/datacenter/install/aws.md#configuring-docker-datacenter-dns-and-certificates

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #458](https://github.com/docker/docs-private/issues/458) via [**ZenHub**](https://www.zenhub.com/)
