### ISSUE TITLE
Add use cases for reducing metrics polling

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#4408]
@vsaraswat commented on [Fri Mar 17 2017](https://github.com/docker/orca/issues/5628)

### What's the problem/feature request?
UCP 2.1.1 added two new parameters to configure metrics polling:

- Administrators can now configure the frequency with which UCP polls metrics. Use `docker service update --env-add METRICS_SCRAPE_INTERVAL=10m ucp-agent`, and the frequency can be in s/m/h/d.
Administrators can now configure the frequency with which UCP gathers disk usage data. Use `docker service update --env-add METRICS_DISK_USAGE_INTERVAL=12h ucp-agent`, and the frequency can be in s/m/h/d.

We should add a section in the documentation around why you might want to use these options. There are two main use cases:
- Admin wants to use a different metrics solution from the one built into UCP, and so turns the frequency way down to effectively turn the built-in metrics off.
- Admin is seeing system performance issues due to the metrics and turns the frequency down in order to reduce the load.

We may also want to consider adding to customer success as a knowledge base article.

### Who is asking for this?
This is an internal request. However we have been getting some pressure from 3rd party monitoring companies to show how they can integrate with UCP.

### What is the (customer) Impact of this request or severity of the issue?
Nothing burning yet, but it provides some relief for our partners, and it could reduce burden on support team if they are getting a lot of requests in this area.

### What versions/components are affected?
UCP 2.1+

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #459](https://github.com/docker/docs-private/issues/459) via [**ZenHub**](https://www.zenhub.com/)
