### ISSUE TITLE
Upgrade docs should instruct user to check system requirements

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#4411]
@jlhawn commented on [Thu Aug 03 2017](https://github.com/docker/orca/issues/8603)

I was investigating an issue where a user was unable to successfully upgrade some UCP worker nodes from 1.1.x to 2.0.x. It looks like the root cause is because their environment had a strict firewall between these worker nodes and the manager nodes. The upgrade docs for 2.0 [here](https://docs.docker.com/datacenter/ucp/2.0/guides/installation/upgrade/) don't instruct the reader to check for system requirements before upgrading. They probably would have realized that UCP 2.0.x requires port 2377 for the Docker worker agent to communicate with the Docker "swarm-mode" manager. Since the port was blocked, their upgrade attempts would fail when the node tried to join the new swarm-mode cluster.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #461](https://github.com/docker/docs-private/issues/461) via [**ZenHub**](https://www.zenhub.com/)
