### ISSUE TITLE
Add link and/or format example of config.yml to Garbage collection topic

### ISSUE THREAD

**Issue by bobphill** [docker/docker.github.io#443]
URL: [https://docs.docker.com/registry/garbage-collection.md](https://docs.docker.com/registry/garbage-collection/)
The format of the config.yml file, or a pointer to that format, would make the page useful

**Comment by gschaetz** [comment]
ok I got this one

**Comment by joaofnfernandes** [comment]
Reopening this since #2875 is not yet merged.
