### ISSUE TITLE
Possibly misleading tag documentation

### ISSUE THREAD

**Issue by benhackett4** [docker/docker.github.io#4433]
File: [engine/reference/commandline/tag.md](https://docs.docker.com/engine/reference/commandline/tag/), CC @mstanleyjones 

> To tag a local image with ID “0e5574283393” into the “fedora” repository with “version1.0”:
> $ docker tag 0e5574283393 fedora/httpd:version1.0

I'm very new to docker, and now I'm confused. Isn't the repository "fedora/httpd" and not just "fedora"? If not, what is the terminology for the "httpd" part of the name? And where can I find some documentation explaining this in full? Thanks for any help.

**Comment by mstanleyjones** [comment]
The organization is `fedora`, the image is `httpd`, and the tag is `version1.0`. The registry knows about this syntax conventions and  does the right thing when you push to it. Does that help?

**Comment by benhackett4** [comment]
Ah okay, that helps a bit. It still seems misleading to me to call `fedora` the repository. I would have thought `fedora/httpd` or `httpd` would be the correct answer. I guess I'm still wondering if there is a definition somewhere on how image names break down into components (repository name, possibly user/organization, possibly other things).

**Comment by mstanleyjones** [comment]
You might find this area of the docs helpful: https://docs.docker.com/docker-hub/repos/#pushing-a-repository-image-to-docker-hub

**Comment by benhackett4** [comment]
Yeah those are helpful to me, thanks. Also, those docs suggest that the repository name is `httpd` (not `fedora`) unless I'm missing something.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #501](https://github.com/docker/cli/issues/501) via [**ZenHub**](https://www.zenhub.com/)
