### ISSUE TITLE
Feedback for: compose/compose-file.md

### ISSUE THREAD

**Issue by Bartman250** [docker/docker.github.io#444]
URL: [https://docs.docker.com/compose/compose-file.md](https://docs.docker.com/compose/compose-file/)

Please could we have some examples of how to format overlay networks in the docker compose file. Especially when using with swarm - thanks :)

**Comment by londoncalling** [comment]
@shin- @nathanleclaire @dnephin I need your help with this, can you guys give me some guidance here? Thanks in advance.

**Comment by dnephin** [comment]
I don't really understand the question. It should be just this: https://docs.docker.com/compose/compose-file/#/driver-1

**Comment by Bartman250** [comment]
Thanks for looking into this folks, looking forward to this working with swarm as we're having lots of fun with this at the moment.

**Comment by Bartman250** [comment]
sorry, was meant to leave the issue open

**Comment by londoncalling** [comment]
@Bartman250 I've updated the latest Compose file reference per the referenced PR ^^ with links to some Docker Labs examples of using the `overlay` driver, and to some more in-depth topics re: the network architecture for overlay networks.

I'm going to close this issue for now, the updates should be published soon at: https://docs.docker.com/compose/compose-file/#network-configuration-reference

Thanks for the feedback, let us know if this helps or is not enough.
