### ISSUE TITLE
Where do I configure my public SSH key in docker cloud?

### ISSUE THREAD

**Issue by wotanvonklass** [docker/docker.github.io#4444]
File: [docker-cloud/cloud-swarm/ssh-key-setup.md](https://docs.docker.com/docker-cloud/cloud-swarm/ssh-key-setup/), CC @londoncalling

**Comment by wotanvonklass** [comment]
The documentation lacks information where I can actually store my public ssh key.

**Comment by wotanvonklass** [comment]
-> has to be configured in AWS in the correct region.

**Comment by londoncalling** [comment]
@wotanvonklass if you follow the procedure for linking either AWS or Azure, you will see this topic as a "what's next" after setting up the SSH keys:

- on AWS: [Link Amazon Web Services to Docker Cloud](https://docs.docker.com/docker-cloud/cloud-swarm/link-aws-swarm/) (note SSH key setup is a prerequisite to the rest of the page), and as a subtopic to that, the step you are asking about is specifically: [Add your AWS account credentials to Docker Cloud](https://docs.docker.com/docker-cloud/cloud-swarm/link-aws-swarm/#add-your-aws-account-credentials-to-docker-cloud) (but you need to follow the whole procedure to get there. (You should jump back to these instructions on how to link AWS account to Docker Cloud from [Related Topics on that SSH key page](https://docs.docker.com/docker-cloud/cloud-swarm/ssh-key-setup/#related-topics))

- on Azure: [Link Microsoft Azure Cloud Services to Docker Cloud](https://docs.docker.com/docker-cloud/cloud-swarm/link-azure-swarm/) (note SSH key setup is a prerequisite to the rest of the page), and as a subtopic to that: [Add your Azure account credentials to Docker Cloud](https://docs.docker.com/docker-cloud/cloud-swarm/link-azure-swarm/#add-your-azure-account-credentials-to-docker-cloud) (You should jump back to these instructions on how to link AWS account to Docker Cloud from [Related Topics on that SSH key page](https://docs.docker.com/docker-cloud/cloud-swarm/ssh-key-setup/#related-topics))
