### ISSUE TITLE
What is meant by 'unprivileged container' in the 'Best practices for writing Dockerfiles' guide?

### ISSUE THREAD

**Issue by stefanlasiewski** [docker/docker.github.io#4446]
The Best practices for writing Dockerfiles guide brings up 'unprivileged containers' in a critical section, without explaining the idea. 

At https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run , the docs state:

> You should avoid RUN apt-get upgrade or dist-upgrade, as many of the “essential” packages from the parent images won’t upgrade inside an unprivileged container. 

Can you elaborate what an 'unprivileged container' means? I sort of know what 'unprivileged container' means in the LXC container world, but in the Dockersphere, that idea is not well explained. There's only one other reference to it in the docs according to https://www.google.com/search?q=site:docs.docker.com+%22unprivileged+container%22 . 

I'm still trying to wrap my head around why `RUN apt-get upgrade` is a bad idea, so I can't contribute verbiage myself.

File: [engine/userguide/eng-image/dockerfile_best-practices.md](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/), CC @mstanleyjones

**Comment by elliotthilaire** [comment]
I am curious about what this means too. Google lead me here.

**Comment by mistyhacks** [comment]
A container that is not run with `--privileged`... https://docs.docker.com/engine/reference/run/#security-configuration
