### ISSUE TITLE
GCS driver parameters have changed

### ISSUE THREAD

**Issue by dockersid** [docker/docker.github.io#4452]
File: [registry/storage-drivers/gcs.md](https://docs.docker.com/registry/storage-drivers/gcs/)

The Parameters table and the paragraph below it, need to be changed. There are three parameters on the gcs driver page:
1. rootdirectory - not required
2. bucket - required 
3. credentials - required

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
