### ISSUE TITLE
"an HTTP xxx" or "a HTTP xxx"?

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#4458]
File: [engine/swarm/how-swarm-mode-works/services.md](https://docs.docker.com/engine/swarm/how-swarm-mode-works/services/), CC @mstanleyjones

I see both "an HTTP xxx" or "a HTTP xxx" are used. Which one is correct?

**Comment by mstanleyjones** [comment]
"an" is correct, because the way you say HTTP it starts with an A sound. :) Do you feel like trying to clean these up? 🎉

**Comment by scjane** [comment]
OK. I'll modify it on this page first and then check it on other pages.
