### ISSUE TITLE
After install `docker run hello-world` is unsuccessful

### ISSUE THREAD

**Issue by nielsenmarkus11** [docker/docker.github.io#446]
I followed the instructions for the installation below, but when I got to the `docker run hello-world` I got the following error:

```
user@computer: ~ $ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
c04b14da8d14: Already exists
Digest: sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: Device is Busy.
See 'docker run --help'.
```

I checked the logs and this is what I see:

```
user@computer: ~ $ sudo tail /var/log/messages | grep docker
Nov  3 09:03:28 computer dockerd: time="2016-11-03T09:03:28.410929179-06:00" level=error msg="devmapper: Error unmounting device 2c4d95bcc88a425c6c2045f82b522fb2923fb941f8bb8cb9e083a38bfe4aba4f-init: Device is Busy"
Nov  3 09:03:28 computer dockerd: time="2016-11-03T09:03:28.411111247-06:00" level=error msg="Handler for POST /v1.24/containers/create returned error: Device is Busy"
```

Is there something that I haven't setup correctly?  One thing I'm dealing with is the installation of docker behind an authenticated proxy... this error doesn't appear to be a proxy issue.  I have set up the `http-proxy.conf` file as suggested in the instructions as well.

I'm have tried uninstalling then reinstalling docker along with rebooting the machine.  Does anyone have an idea of what the issue could be?

Thanks in advance.

URL: [https://docs.docker.com/engine/installation/linux/rhel.md](https://docs.docker.com/engine/installation/linux/rhel/)

**Comment by mstanleyjones** [comment]
Lots of people reported similar problems on RHEL 6. Docker on RHEL 6 is not supported. You can check out [this Github issue](https://github.com/docker/docker/issues/5684#issuecomment-117297875) for some info and workarounds to the problem you might be running into. If you're not on RHEL 6 and still having this issue, and those workarounds don't work for you, please check out https://forums.docker.com/ or participate in the Github issue above. Thanks!
