### ISSUE TITLE
LDAP Integration for DTR Teams - no details, example, mentioned only once

### ISSUE THREAD

**Issue by ElectricWarr** [docker/docker.github.io#4462]
File: [datacenter/dtr/2.3/guides/admin/manage-users/index.md](https://docs.docker.com/datacenter/dtr/2.3/guides/admin/manage-users/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
This has been fixed upstream, and will make its way to the docs in DTR 2.5.

**Comment by Bak3y** [comment]
The documentation for 2.5 appears to still have zero mention of LDAP based teams:

https://docs.docker.com/ee/dtr/admin/manage-users/create-and-manage-teams/
