### ISSUE TITLE
docker-compose up alters /etc/hosts of docker container

### ISSUE THREAD

**Issue by vishalseshagiri** [docker/docker.github.io#4490]
```docker-compose``` up seems to be altering the /etc/hosts file inside the docker container. It resets the /etc/hosts to default and I lose all my FQDN mappings. Would really appreciate it if someone could look into this or even suggest where I am going wrong.

This is what my /etc/hosts looks like everytime on startup
```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.21.0.6	b61e9e949dbe

```

**Comment by mstanleyjones** [comment]
@shin- is this an accurate characterization?

**Comment by shin-** [comment]
Probably better to post this as a complete issue report on the docker/compose repo. AFAICT, this will happen if you use the v1 format, but /etc/hosts doesn't get modified with v2/v3 (unless specifically using the legacy bridge network)

**Comment by vishalseshagiri** [comment]
@shin- Sure will do that. I use 1.14.0 maybe that's why I am facing this issue.

**Comment by vishalseshagiri** [comment]
@shin- this issue still persists 
These are my configs : 
1. ```docker-compose version 1.16.1, build 6d1ac21```
2. ```Docker version 17.06.0-ce, build 02c1d87```
3. ```Docker compose file version 3.3```
I think it modifies not just /etc/hosts but everything inside the /etc directory. I tried giving a certain user created inside docker some sudo level permissions. But on stopping and restarting the container all the changes were lost. I'll post this as a seperate issue on the docker-compose repo too.

**Comment by mstanleyjones** [comment]
Thank you for opening the issue in the `docker/compose` repository. Let's continue discussion of this issue there.
