### ISSUE TITLE
Indicate mode=ingress published ports change source IP address

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#4493]
### Problem description

See: https://github.com/moby/moby/issues/25526#issuecomment-263096241

tlvenn commented on Nov 26, 2016
> Fair enough I guess @mavenugo given we have an alternative now.
> At the very least, can we amend the doc for 1.13 so it clearly state that when using docker services with the default ingress publishing mode, the source ip is not preserved and hint at using the host mode if this is a requirement for running the service ?
>
> I think it will help people who are migrating to services to not being burnt by this unexpected behaviour.

mavenugo commented on Nov 27, 2016
> Sure and yes a doc update to indicate this behavior and the workaround of using the publish mode=host will be useful for such use-cases that fails in LVS-NAT mode.

sanimej commented on Feb 17
> thaJeztah I think we should clarify this in the documentation, suggest using the host mod if client IP has to be preserved and close this issue.

Searching this repo for `mode=host` didn't turn up such an advisory.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
