### ISSUE TITLE
CpuQuota is available while inspecting a container

### ISSUE THREAD

**Issue by asuresh4** [docker/docker.github.io#4500]
File: [engine/api/v1.22.md](https://docs.docker.com/engine/api/v1.22/), CC @mstanleyjones 
I notice that CpuQuota is available under HostConfig while inspecting a container. I actually used the docs to figure that out. But now it looks like an update might have omitted CpuQuota from the examples? This is true for various versions. I use 1.30 API and it gives CpuQuota info. Could you please look into this? Thanks!

**Comment by mstanleyjones** [comment]
Well, the version 1.22 of the API (that you filed this issue against) did not support it, but version 1.30 API does. We don't update old versions of the API at all, but new versions maintain backward compatibility. Remember that you can specify a specific version of the API if you don't want to use the latest that your client and daemon combination supports: https://docs.docker.com/engine/api/#versioned-api

**Comment by asuresh4** [comment]
@mstanleyjones Thanks for the reply. However, the documentation for version 1.30 also doesn't show CpuQuota. I was looking to the version from which CpuQuota is available in Container Inspect. Also, as per this link (https://docs.docker.com/engine/api/version-history/#v119-api-changes) CpuQuota is available from version 1.19. Please correct me if I'm wrong. Thanks!

**Comment by mstanleyjones** [comment]
@thaJeztah can you help here? Pretty sure we don't update old API versions.
