### ISSUE TITLE
Update docker-ce strings

### ISSUE THREAD

**Issue by BubbleSnap** [docker/docker.github.io#4509]
File: [engine/installation/linux/docker-ce/centos.md](https://docs.docker.com/engine/installation/linux/docker-ce/centos/), CC @mstanleyjones 

The page current doesn't quite reflect what we see in real world.
yum list docker-ce.x86_64 --showduplicates | sort -r
 * updates: mirror.i3d.net
Loading mirror speeds from cached hostfile
Loaded plugins: fastestmirror
Installed Packages
 * extras: mirror.i3d.net
 * epel: vesta.informatik.rwth-aachen.de
docker-ce.x86_64            17.06.1**.ce**-1.el7.centos             docker-ce-stable
docker-ce.x86_64            17.06.0**.ce**-1.el7.centos             docker-ce-stable
docker-ce.x86_64            17.06.0**.ce**-1.el7.centos             @docker-ce-edge
docker-ce.x86_64            17.03.2**.ce**-1.el7.centos             docker-ce-stable
docker-ce.x86_64            17.03.1**.ce**-1.el7.centos             docker-ce-stable
docker-ce.x86_64            17.03.0**.ce**-1.el7.centos             docker-ce-stable

The actual yum install line for a specific is:
sudo yum install docker-ce-<VERSION> where VERSION=17.06.0**.ce**

**Comment by mstanleyjones** [comment]
Actually the way in the doc is the documented way to install specific versions using Yum. See https://access.redhat.com/discussions/1123613 and https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sec-Working_with_Packages.html#sec-Installing. The way you describe might work as well, but it is not standard.

**Comment by BubbleSnap** [comment]
The documented way doesn't work for me. "yum install docker-ce-17.6.0" doesn't work at all on a vanilla centos 7.3 (1611) installation with docker-ce repo installed and enabled as yum doesn't find the package. adding the ".ce" made everything work fine.

**Comment by mstanleyjones** [comment]
Let me try to reproduce this.
