### ISSUE TITLE
passwd snippet doesn't work with ucp-auth-api:2.2.2

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#4513]
File: [datacenter/ucp/2.1/guides/admin/manage-users/recover-a-user-password.md](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/manage-users/recover-a-user-password/), CC @jimgalasyn

In an docker/ucp:2.2.2 installation the ucp-auth-api containers Args look like this:

    "Args": [
            "--debug",
            "--db-addr=172.31.18.93:12383",
            "--jsonlog",
            "api-server",
            "--root-prefix=enzi"
        ],

The below inspect expression will return  --debug and not the db addr and the passwd will return an error as it will contact the default db.enzi

<pre>
docker exec -it ucp-auth-api enzi \
  "$(docker inspect --format '{{ index .Args 0 }}' ucp-auth-api)" \
  passwd -i
</pre>

The below works:
<pre>
docker exec -it ucp-auth-api enzi \
  "$(docker inspect --format '{{ index .Args 1 }}' ucp-auth-api)" \
  passwd -i
</pre>

**Comment by JimGalasyn** [comment]
Thanks for the feedback! I can't repro your issue on `docker/ucp:2.2.2`. When I try with `.Args 1`, I get:
```
{"level":"fatal","msg":"unable to connect to database cluster: gorethink: dial tcp: lookup db.enzi on 172.31.0.2:53: no such host","time":"2017-09-06T16:03:04Z"}
```

But `.Args 0` works as expected.

**Comment by JimGalasyn** [comment]
Closing for now, please feel free to re-open if you have a repro.

**Comment by zdeisidr** [comment]
I'm trying to install the UCP and when I go to web client the user/password are never correct.
I try to run: enzi --debug --db-addr=10.1.1.250:12383 create-admin --interactive inside the auth container  version: docker/ucp-auth:3.1.7
but: FATA[0014] unable to connect to database cluster: gorethink: dial tcp 10.1.1.250:12383: connect: no route to host
