### ISSUE TITLE
Variable Substitution Inside the Container

### ISSUE THREAD

**Issue by kolotyluk** [docker/docker.github.io#4516]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @londoncalling 

Regarding https://docs.docker.com/compose/compose-file/#variable-substitution is there a way to do variable substitution from within the container? For example

    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$$(exec hostname):9092

That would expand to something like

    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://c2f121d9dc60:9092

Inside the container when the image is run.

If not, this would be an amazing feature. Alternatively, some sort of substitution where you can refer to container info

**Comment by mstanleyjones** [comment]
I don't think this exists. @shin-?

**Comment by kolotyluk** [comment]
So, I was able to do what I needed in the image's start script by

    # Handle the case of PLAINTEXT:$(exec hostname) by evaluating the string
    if [[ -n "$KAFKA_ADVERTISED_LISTENERS" ]]; then
        export KAFKA_ADVERTISED_LISTENERS=$(eval echo $KAFKA_ADVERTISED_LISTENERS)
    fi

And in the compose file I can say

    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$$(exec hostname):9092,OUTSIDE://Productio-External-5HJ3F3YE36TS-4682428.us-west-1.elb.amazonaws.com:9094

This would be a good example to document using `$$`

As  before, it would be a nice feature of `docker stack deploy . . .` that it had some way of delaying variable substitution to inside the container. For example

    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://~$(exec hostname):9092,OUTSIDE://Productio-External-5HJ3F3YE36TS-4682428.us-west-1.elb.amazonaws.com:9094

where `~$` means substitute `$(exec hostname)` inside the container.

**Comment by mstanleyjones** [comment]
I appreciate that you got this working, but I think this is a feature request that belongs in the `docker/compose` repository. In the meantime, check out https://docs.docker.com/compose/environment-variables/.
