### ISSUE TITLE
Update program positioning to not overlap with Docker Store

### ISSUE THREAD

**Issue by gnomestar** [docker/docker.github.io#4517]
File: [docker-hub/official_repos.md](https://docs.docker.com/docker-hub/official_repos/), CC @johndmulhausen 

> Provide a channel for software vendors to redistribute up-to-date and supported versions of their products. Organization accounts on Docker Hub can also serve this purpose, without the careful review or restrictions on what can be published

We should edit this, and any other verbiage suggesting that official images would be appropriate for this type of content (as opposed to Docker Store).

**Comment by londoncalling** [comment]
@KickingTheTV  Let's have a look at this issue when we port the Docker Store docs over from the KB, and figure out how to balance messaging between Docker Store and Docker Hub.
