### ISSUE TITLE
docker plugin upgrade is not explained well

### ISSUE THREAD

**Issue by cjellick** [docker/docker.github.io#4519]
I think this doc could be improved by doing the following:
- Explaining how is the version of the plugin picked when the plugin is first installed
- Not using the same version that is already installed in the upgrade command

There also seems to be an inconsistency:
The install command doesnt mention version:
```
docker plugin install vieux/sshfs DEBUG=1
```
but everything else does:
```
docker plugin disable -f vieux/sshfs:next
docker plugin upgrade vieux/sshfs:next vieux/sshfs:next
docker plugin enable vieux/sshfs:next
```

File: [engine/reference/commandline/plugin_upgrade.md](https://docs.docker.com/engine/reference/commandline/plugin_upgrade/), CC @mstanleyjones

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #586](https://github.com/docker/cli/issues/586) via [**ZenHub**](https://www.zenhub.com/)
