### ISSUE TITLE
Feedback for: docker-hub/bitbucket.md

### ISSUE THREAD

**Issue by AndrewLane** [docker/docker.github.io#452]
URL: [https://docs.docker.com/docker-hub/bitbucket.md](https://docs.docker.com/docker-hub/bitbucket/)

Can you link Docker Hub to a Bitbucket account that's not at bitbucket.org but rather an instance of bitbucket that's hosted internally by our company?

**Comment by sanscontext** [comment]
Hey @AndrewLane, I had to check with the dev team to confirm because this isn't a thing I was aware existed. This is not supported: Docker Hub and Docker Cloud can only autobuild from hosted Bitbucket and Github accounts.
