### ISSUE TITLE
Release notes should clearly discern between edge and stable channel

### ISSUE THREAD

**Issue by alb-i986** [docker/docker.github.io#4520]
File: [release-notes/docker-ce.md](https://docs.docker.com/release-notes/docker-ce/), CC @johndmulhausen

Like most of the end users I'm on the stable channel, and today I got the 17.06.2 update from the apt repository.
I checked the release notes and found that the [proxy support has been enhanced](https://github.com/docker/cli/pull/93), but unfortunately I hadn't noticed the version mismatch.. After a few attempts, I realized that it was not gonna work, as that feature belongs to the 17.07 which is only available on the edge channel, while I'm on the stable, like I said.

So I think that the release notes document should clearly discern the release notes for the different channels in two separate sections of the document.

BTW, please note that the release notes for 17.06.2-ce are missing.

**Comment by mistyhacks** [comment]
This was fixed. :)
