### ISSUE TITLE
Fix docker login options

### ISSUE THREAD

**Issue by timothysnave** [docker/docker.github.io#4526]
File: [engine/reference/commandline/login.md](https://docs.docker.com/engine/reference/commandline/login/), CC @mstanleyjones

From the CLI:
```
Usage:  docker login [OPTIONS] [SERVER]

Log in to a Docker registry

Options:
      --help              Print usage
  -p, --password string   Password
      --password-stdin    Take the password from stdin
  -u, --username string   Username

```

The documentation is missing --password-stdin.

**Comment by albers** [comment]
This is already fixed in the source file at https://github.com/docker/cli/blob/master/docs/reference/commandline/login.md.
So the website needs to pull this change in.

**Comment by mstanleyjones** [comment]
@albers the docs reference the latest stable version of Docker. If you want the latest Edge version, you need to change your URL to https://docs.docker.com/edge/engine/reference/commandline/login/, which does have the content. To see your Docker version, use `docker --version`

**Comment by timothysnave** [comment]
@mstanleyjones does that mean that edge is actually in development? Should I not use it? I just figured it would give me the latest security updates and stuff.

**Comment by mstanleyjones** [comment]
Edge moves much more quickly (monthly) than stable (quarterly). You can use whatever is appropriate for your needs. See https://docs.docker.com/engine/installation/. Thanks!

**Comment by albers** [comment]
Thanks, @mstanleyjones 
> If you want the latest Edge version, you need to change your URL to https://docs.docker.com/edge/engine/reference/commandline/login/, which does have the content.

I cannot find any link to the edge docs. There should be an easy-to-find way to get tho these docs, otherwise there will be more issue reports like this.

**Comment by mstanleyjones** [comment]
It's under Get Docker -> Docker Edge. There are also a bunch of Edge-specific reference docs explicitly labeled under the References tab.

**Comment by albers** [comment]
Ah, yes. Thanks. I expected it to appear somewhere in the versions picker.

**Comment by mstanleyjones** [comment]
The Edge version does not require a full docs set. Each Edge version is only supported until the next version comes out, and only a small subset of things (APIs and CLI commands, for the most part) change. We have to support our Stable users first and foremost.
