### ISSUE TITLE
No information for 17.06.2-ce-mac27 (19124)

### ISSUE THREAD

**Issue by CleanCut** [docker/docker.github.io#4527]
File: [docker-for-mac/release-notes.md](https://docs.docker.com/docker-for-mac/release-notes/), CC @gbarr01

Just trying to figure out where to get release notes for 17.06.2-ce-mac27 (19124).  It's not on that page yet.  If there's some other place to look, please point me to it.

**Comment by londoncalling** [comment]
@CleanCut They are there now, check out this link to [Docker Community Edition 17.06.2-ce-mac27 2017-08-31 (Stable)](https://docs.docker.com/docker-for-mac/release-notes/#stable-release-notes)

**Comment by CleanCut** [comment]
Thank you!
