### ISSUE TITLE
Promotion policy screenshots are out of date

### ISSUE THREAD

**Issue by pdevine** [docker/docker.github.io#4530]
File: [datacenter/dtr/2.3/guides/user/create-promotion-policies.md](https://docs.docker.com/datacenter/dtr/2.3/guides/user/create-promotion-policies/), CC @joaofnfernandes  The images on this page are from an early alpha and should be replaced with the actual DTR 2.3.0 images.  The promotion policy criteria is actually swapped in the screenshot.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
