### ISSUE TITLE
Slight error in creating certificate documentation

### ISSUE THREAD

**Issue by jtarnvik** [docker/docker.github.io#4539]
File: [engine/security/https.md](https://docs.docker.com/engine/security/https/), CC @mstanleyjones 

Hi!

I have tried to follow the documentation to "Create a CA, server ..." and I think an error exist in the documentation. I am certainly no expert but if I follow the doc I don't get a correct certificate.  One small change makes it work however. Around the middle of the page it states the following:
###################### FROM WEB
Since TLS connections can be made via IP address as well as DNS name, the IP addresses need to be specified when creating the certificate. For example, to allow connections using 10.10.10.20 and 127.0.0.1:
`$ echo subjectAltName = DNS:$HOST,IP:10.10.10.20,IP:127.0.0.1 > extfile.cnf`
Set the Docker daemon key’s extended usage attributes to be used only for server authentication:
`$ echo extendedKeyUsage = serverAuth > extfile.cnf`
##################### END FROM WEB
The error is that the second echo line will overwrite the first one. If I change the second line to 
`$ echo extendedKeyUsage = serverAuth >> extfile.cnf`
it works as expected. ('>' changed to '>>'). 

Perhaps I only am supposed to use one of the echo-lines but in that case that needs to be made more clear or I may have misunderstood something else since I hardly understand the finer details of TLS certificates, but anyway the change was needed for me to get the cert to work as expected. Hope this can be clarified or corrected.

/Jesper

**Comment by mstanleyjones** [comment]
@gbarr01 please modify the second `echo` to use append redirection (`>>`) instead of overwrite redirection (`>`).

**Comment by gbarr01** [comment]
@mstanleyjones , you mean the first `echo` right?

**Comment by mstanleyjones** [comment]
Yep! 😊
