### ISSUE TITLE
Default CPU period value

### ISSUE THREAD

**Issue by asuresh4** [docker/docker.github.io#4542]
File: [engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/), CC @mstanleyjones

Default CPU period = 100 ms according to https://docs.docker.com/engine/reference/run/#cpu-period-constraint. But this link (https://docs.docker.com/engine/admin/resource_constraints/#configure-the-default-cfs-scheduler) specifies the default to be 1 sec (1000ms). Could you please look into this? Which is the actual default value? Thanks!

**Comment by mstanleyjones** [comment]
The reference is correct because it is programmatically generated from the code. @gbarr01 please take this one, and update the resource constraints topic. Thanks!
