### ISSUE TITLE
mark "link" as deprecated or remove it in the docs

### ISSUE THREAD

**Issue by rdxmb** [docker/docker.github.io#4543]
File: [compose/networking.md](https://docs.docker.com/compose/networking/), CC @gbarr01

**Comment by gbarr01** [comment]
Hi, @rdxmb , which link are you referring to? Or do you mean the entire page? cc: @mstanleyjones

**Comment by rdxmb** [comment]
I am sorry, that was not that clear:
As the --link flag is deprecated (see https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) I assume that "links" (see https://docs.docker.com/compose/networking/#links) are also. 

edited:
Oh, probably the "links" here are: https://docs.docker.com/compose/compose-file/#links  

(I've never used the --link because I only work with the yaml-files.)

**Comment by londoncalling** [comment]
@shin- Can you work with @gbarr01 to make sure we do the right thing here in the Compose v3 file and elsewhere? Should we mark this as deprecated in the Compose v3 file or link it to this information on [legacy container links](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/)?

We have this topics on links in Compose v3:
- [links under Service Configuration](https://docs.docker.com/compose/compose-file/#links)

Which links to this topic in the Networking docs
- [links under Networking in Compose](https://docs.docker.com/compose/networking/#links)

Should the links sections be marked as deprecated, removed, or should we link them to this information on[ legacy container links](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/)

**Comment by mstanleyjones** [comment]
It's not deprecated, it's considered to be legacy. It's not going away, but we recommend that you not use it, because there are other  better ways to do this, such as using secrets or configs with Docker services, or using user-defined networks for automatic discovery. This has been addressed more thoroughly in #4956
