### ISSUE TITLE
Does Docker for Mac come with Kitematic or a similar GUI ?

### ISSUE THREAD

**Issue by commanderfun** [docker/docker.github.io#4544]
File: [docker-for-mac/docker-toolbox.md](https://docs.docker.com/docker-for-mac/docker-toolbox/), CC @gbarr01

Our developers currently use the Kitematic GUI to launch containers with a single click? Does Kitematic (or a similar easy to use GUI) come with Docker for MAC?  This isn't very clear in your documentation.

**Comment by londoncalling** [comment]
cc: @jeffdm @aduermael @gdevillele @gbarr01 

@commanderfun [Docker for Mac](https://docs.docker.com/docker-for-mac/install/) _does_ include the latest version of Kitematic, but Kitematic is considered legacy going forward. 

The new [Docker for Mac GUI](https://docs.docker.com/docker-for-mac/) does not currently include the ability to launch a container (like Kitematic), but _**you get Kitematic when you install Docker for Mac, and you can launch Kitematic from the Docker for Mac GUI**_ (see pix below).

Let me know if this helps, or if you need more info.

![d4mac-launch-kitematic](https://user-images.githubusercontent.com/11660803/30188105-8a489f5c-93e1-11e7-9f7e-c4bf0f10c2a4.png)

![d4mac-kitematic](https://user-images.githubusercontent.com/11660803/30188111-8ecdd06a-93e1-11e7-814a-b47d0c5b831c.png)

**Comment by aduermael** [comment]
Technically, Kitematic is not installed automatically with Docker for Mac. But you have the option to install & launch it through the menu.

**Comment by commanderfun** [comment]
Ok, great. Thank you for the clarification.

**Comment by Timmmm** [comment]
This is confusing though. You click "Kitematic" in the Docker for Mac menu, and it says you can install Kitematic for a GUI (yeay!), but then when you go to the Kitematic site it says it is legacy software and you should use Docker for Mac instead... wtf?

**Comment by gbarr01** [comment]
@akimd  ^

**Comment by londoncalling** [comment]
Hi guys,
Kitematic has been legacy for 3 years ... we wanted to continue to make it
available for those that wanted it, but it is not being maintained and we
want to make sure that this is clear.

The right fix for this is probably to include that information in the UI
link so folks have a heads up before downloading the tool and it won’t be
surprising when they see that “legacy” banner on the docs.

Vicky

**Comment by Timmmm** [comment]
It also doesn't help that the "you can download Kitematic [here]" link or whatever doesn't actually seem to work. And when you google "Kitematic" and go to kitematic.com it offers the "Docker Toolbox" for download. What? Is that Kitematic? Is it a bundle that contains Kitematic? I have no idea and the website doesn't make it clear.

I eventually went to https://github.com/docker/kitematic which doesn't mention it being deprecated and downloaded it from the releases page.

You should:

1. Make the Kitematic download link in Docker actually work.
2. Mention in the Kitematic repo Readme.md that it is no longer maintained but it's still the best GUI available.
3. Change kitematic.com so it has provides a big download link to Kitematic (not Docker Toolbox).
4. Explain on kitematic.com the relationship between Kitematic, Docker for Mac and Docker Toolbox. Something like this:

> *Docker for Mac* is our current solution for running Docker on Macs. Before *Docker for Mac* was available there was the *Docker Toolbox*, which is now only provided for situations where *Docker for Mac* does not work. You should use *Docker for Mac* if possible.
>
> *Kitematic* is a GUI for viewing Docker containers. It is no longer maintained but it still works. You can download it [here](https://github.com/docker/kitematic), and it is also included in *Docker Toolbox* (I guess? who knows)

**Comment by gtardif** [comment]
@Timmmm Thx for your feedback. 
We'll improve the docs to make this more clear. I don't think we'll include Kitematic in the Docker for Mac package. This install package has grown quite a lot, we're not too keen on adding another 130 MB to it just for Kitematic.
Regarding the link that doesn't work, which link are you talking about ? From Docker for Mac, the link `https://download.docker.com/kitematic/Kitematic-Mac.zip` seems to be fine (same in Docker for Windows.)

**Comment by Timmmm** [comment]
I mean when you click this button:

![](https://user-images.githubusercontent.com/11660803/30188105-8a489f5c-93e1-11e7-9f7e-c4bf0f10c2a4.png)

It shows you a dialog box with a link in it. If I click that link, nothing happens as far as I can tell.

**Comment by VickyAtThoughtSpot** [comment]
@Timmmm you might be getting confused at the point where you first download Kitematic. The workflow (if you don't yet have Kitematic installed) is:
1. Install Docker for Mac
2. Click whale menu --> **Kitematic**
3. Click to download Kitematic
4. Double-click the **Kitematic-Mac.zip** in your Downloads folder to expand the zip
5. Double-click **KItematic (Beta)** to start/open Kitematic.
6. After this is done, on the next occasion, you can start Kitematic with the **whale menu --> Kitematic** option

[Here is a short video](https://youtu.be/E08VJfSJA8s) of the above workflow.

On the [Kitematic docs](https://docs.docker.com/kitematic/userguide/), we do explain that Kitematic is a legacy solution bundled with Docker Toolbox in that banner, and provide links, and we also explain more about the progression from Docker Toolbox to Docker for Mac and Windows on the [Docker Toolbox ](https://docs.docker.com/toolbox/overview/) docs banner.

That said, we used to have a nice list of legacy products which seems to have been removed, and some of the docs navigation needs to be updated. Sorry this was confusing, but hopefully the above explanation helps. When you first click the Kitematic download link, it might not have been obvious that it was starting a download.

@gtardif thanks for jumping in, hope all is well with you

**Comment by Timmmm** [comment]
@VickyAtThoughtSpot I suggest you read my comment again. The download link did not work.

I experimented again and found this is because the dialog is not focused at first and the link only works a second or so after it is focused, but if you are quick and click it once or twice nothing happens. Anyway this is beside the point - kitematic.com is unnecessarily misleading.

**Comment by VickyAtThoughtSpot** [comment]
Hi @Timmmm I read your comment, and thought that perhaps you didn't notice the download. I'm sorry it didn't work for you, and not sure why not. Ordinarily, I would suggest logging a ticket against the product at as described in [Give feedback and get help](https://docs.docker.com/docker-for-mac/#give-feedback-and-get-help), but the problem does not seem to be inherent in the product, and could be something with your environment. I tested this on the latest versions of Docker for Mac `stable` and `edge`,  about 5 times before I took the video for you, and could not reproduce the problem.

**Comment by akimd** [comment]
@Timmmm The snapshot you sent has a "Restart" button on the top of the whale menu.  We're removed that a long time ago.  You are using an obsolete version of Docker for Mac.  Please update, and try again.

**Comment by peterlobster** [comment]
I installed Kitematic via `brew cask install kitematic`. Before that I had installed Docker via `brew cask install docker`. They both installed fine and when I click Kitematic on Docker it launches the brew cask installation of Kitematic np.

Just a note of what worked for me...

**Comment by machale** [comment]
Running Docker CE 18.06.1-ce-mac73 on macOS 10.13.6. From Docker menu, selected Kitematic, clicked the "here" link, downloaded the zip, extracted it, put Kitematic.app in /Applications. I can run Kitematic directly from /Applications, but selecting Kitematic from the Docker menu still just shows the dialog prompting me to download it. This is true even if Kitematic is already running. It remains true if I fully quit Docker and start it again.

Clearly I can work around this by starting Kitematic myself (easy with Spotlight Cmd+Space). But it seems like once Kitematic is installed, the Docker menu item should start it or give it focus if it's already running.

**Comment by peterlobster** [comment]
@machale Interesting obesevation. I suspect that it may have something to do with recent update (v1.7.5) (which fixed the connection to Docker Hub) to Kitematic. You can try downgrading Kitematic (maybe v1.7.4 but v1.7.3 was workign for me before). It may fix the issue. I don't use Kitematic (I use Portainer nowadays) but it would make sense to me that Docker for Mac hasn't issued an update to coencide with Kitematic.

**Comment by resonates7** [comment]
The option to download Kitematic via the Docker option is obviously no longer available.


<img width="267" alt="Screen Shot 2020-01-31 at 11 20 24 AM" src="https://user-images.githubusercontent.com/49754697/73555466-af0ea600-441b-11ea-8151-82517c815405.png">

**Comment by akhilt20** [comment]
> The option to download Kitematic via the Docker option is obviously no longer available.
> 
> <img alt="Screen Shot 2020-01-31 at 11 20 24 AM" width="267" src="https://user-images.githubusercontent.com/49754697/73555466-af0ea600-441b-11ea-8151-82517c815405.png">

EI am having the same issue, do you have a solution for this?
Thanks.

**Comment by londoncalling** [comment]
@akhilt20 The latest version of Docker now comes with a Dashboard, see that menu option above ^^ 

@shin- do you know what else to reference here?

**Comment by londoncalling** [comment]
@akhilt20 The latest version of Docker now comes with a Dashboard (see that menu item on your screen snap above.) You should be able to manage and monitor running containers from there.

**Comment by commanderfun** [comment]
Unfortunately the Docker Desktop "Dashboard" for Mac is nowhere near feature parity with Kitematic. I'm hoping the Docker team brings it up to date soon. For example you can't map volumes, change ports, edit environment variables, etc. in Docker "Dashboard" yet. 

Yes, I know you can do all the above from the command line but it's so much faster and easier to click buttons and not have to memorize docker commands.
