### ISSUE TITLE
docker/dtr:2.2.8 install not respecting --ucp-node argument

### ISSUE THREAD

**Issue by rcplane** [docker/docker.github.io#4549]
File: [datacenter/dtr/2.2/reference/cli/install.md](https://docs.docker.com/datacenter/dtr/2.2/reference/cli/install/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
Can you post the full command you're using to install DTR (removing any sensitive data like IPs).

The best way to deploy DTR is to go to the **settings page of UCP**. Try checking it out and compare what that page shows you with the command that you're using.
![screen shot 2017-09-07 at 11 10 38](https://user-images.githubusercontent.com/1525937/30178297-48d4240c-93bd-11e7-8a57-96c97349b7cc.png)

**Comment by joaofnfernandes** [comment]
I'm closing this issue since it doesn't seem to be reproducible, but feel free to comment @rcplane if you're still seeing this happen.
