### ISSUE TITLE
Request removal of web fonts in docs

### ISSUE THREAD

**Issue by tvon** [docker/docker.github.io#456]
The documentation pages "flicker" on load due to the web fonts.  I am experiencing this on macOS Sierra with Safari and Firefox (the only two I checked), though this is not a new issue.

On the user-side this can be resolved by using Stylish to override the CSS (to specify common fonts instead of web fonts), but it seems like this would be a worthwhile change to the documentation.

Note that I have no idea if this is specific to the way web fonts are being used here or just a common case for web fonts.

![screenshot](https://cloud.githubusercontent.com/assets/25628/20017428/efae0d26-a299-11e6-821d-5312777c6f82.png)

**Comment by johndmulhausen** [comment]
@docker/design - Any thoughts here? That does seem a shame, let me know if there is a feasible fix.

**Comment by sanscontext** [comment]
I showed this to @jsouth and we think this is because of the giant css file we inherited from www and forked around the time of DockerCon.

**Comment by johndmulhausen** [comment]
Fixed on redesign.
