### ISSUE TITLE
17.06.2-ce missing?

### ISSUE THREAD

**Issue by rdxmb** [docker/docker.github.io#4563]
File: [release-notes/docker-ce.md](https://docs.docker.com/release-notes/docker-ce/), CC @johndmulhausen 
```

root@docker-single-host:~# docker --version
Docker version 17.06.2-ce, build cec0b72
```
```

root@docker-single-host:~# grep docker /etc/apt/sources.list
deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
# deb-src [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
```

**Comment by mstanleyjones** [comment]
@gbarr01 please copy in the release notes from the `docker/docker-ce` repo, the 17.06 branch, the 17.06.2 section of the `CHANGELOG.md`. Thanks!
