### ISSUE TITLE
To doc: manually start Docker daemon on Windows after update

### ISSUE THREAD

**Issue by gbarr01** [docker/docker.github.io#4565]
Reference: #1071
Docker does not restart automatically after update anymore 

Possible affected pages (investigate for others):
https://docs.docker.com/docker-for-windows/#general
https://docs.docker.com/engine/installation/windows/docker-ee/#update-docker-ee

**Comment by londoncalling** [comment]
This was fixed in by PR #4204, see Docker for Windows install topic on how to [Start Docker for Windows](https://docs.docker.com/docker-for-windows/install/#start-docker-for-windows).
