### ISSUE TITLE
.NOT_EDITED_HERE.txt is not up to date

### ISSUE THREAD

**Issue by aduermael** [docker/docker.github.io#457]
### Problem description

[.NOT_EDITED_HERE.txt](https://github.com/docker/docker.github.io/blob/master/.NOT_EDITED_HERE.txt) doesn't seem to be up to date. Like `compose/reference/` which is not generated automatically.
### Project version(s) affected

current stable

### Suggestions for a fix

We should update this file to reflect current situation.

Also this file should be mentioned in [README.md](https://github.com/docker/docker.github.io/blob/master/README.md)

cc @londoncalling @mstanleyjones @johndmulhausen @gdevillele

**Comment by mstanleyjones** [comment]
This is being addressed in #534 and #511. Closing here.
