### ISSUE TITLE
Questions about image names in Getting Started Part 2

### ISSUE THREAD

**Issue by arunnc** [docker/docker.github.io#4578]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen

Where you say below --  please provide clarify on why its pulling 'orangesnap/get-started' when the request is to run 'john/get-started:part1' .. I havent tried it myself - hope this doesnt work this way. Or, if there is a reason why it looked up orangesnap/get-started. Please provide clarity on this. 

Otherwise, your article is really useful/ great!

$ docker run -p 4000:80 john/get-started:part1
Unable to find image 'john/get-started:part1' locally
part1: Pulling from orangesnap/get-started
10a267c67f42: Already exists
f68a39a6a5e4: Already exists
9beaffc0cf19: Already exists
3c1fe835fb6b: Already exists
4c9f1fa8fcb8: Already exists
ee7d8f576a14: Already exists
fbccdcced46e: Already exists
Digest: sha256:0601c866aab2adcc6498200efd0f754037e909e5fd42069adeff72d1e2439068
Status: Downloaded newer image for john/get-started:part1
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)

**Comment by gbarr01** [comment]
Hi, @arunnc ,  you should run against _your own username_ (that is, the username of your docker account). 

`docker run -p 4000:80 username/repository:tag`

The command with the name "john" in it is an example only. My guess is that john's real account is named, "orangesnap" (and not "john"), and that he changed the command to make it more clear that you should use a username. 

`docker run -p 4000:80 john/get-started:part1`

**Comment by thaJeztah** [comment]
opened a PR to change the output and prevent this confusion 👍  https://github.com/docker/docker.github.io/pull/4655
