### ISSUE TITLE
network "host" is missing

### ISSUE THREAD

**Issue by rdxmb** [docker/docker.github.io#4593]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01

With >= 17.06 it is possible to use the Host Network within Containers. This is also true in swarm mode.

See:
https://github.com/docker/compose/issues/5039 
https://github.com/moby/moby/issues/25873#issuecomment-319109840

On this page, this information is missing.
The sections
```
network-mode:
"This option is ignored when deploying a stack in swarm mode with a (version 3) Compose file."
```
and
https://docs.docker.com/compose/compose-file/#network-configuration-reference
keep silent about that.

**Comment by sudharkrish** [comment]
In swarm mode, when using docker service command, host networking can be used by passing this parameter like in->( docker service create --name $NAME --network=host $IMAGE)
Can you confirm, if this fix will add support for network: host, in swarm mode, in Docker Compose file version 3.

**Comment by rdxmb** [comment]
thanks !
