### ISSUE TITLE
Incorrect example for docker system prune

### ISSUE THREAD

**Issue by joeyfromspace** [docker/docker.github.io#4594]
File: [engine/reference/commandline/system_prune.md](https://docs.docker.com/engine/reference/commandline/system_prune/), CC @mstanleyjones

The example for `docker system prune` incorrectly states that `docker system prune -a` deletes volumes. However, that is not the case unless `--volumes` flag is provided.

On docker version: docker 17.06.2-ce:

```
$ docker system prune -a
WARNING! This will remove:
        - all stopped containers
        - all networks not used by at least one container
        - all images without at least one container associated to them
        - all build cache
Are you sure you want to continue? [y/N]
```

**Comment by thaJeztah** [comment]
Thanks! Opened a PR here: https://github.com/docker/cli/pull/526

**Comment by mstanleyjones** [comment]
Closed in favor of https://github.com/docker/cli/pull/526
