### ISSUE TITLE
DTR recovery instructions if a minority of replicas stops working

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#4596]
File: [datacenter/dtr/2.3/guides/admin/backups-and-disaster-recovery.md](https://docs.docker.com/datacenter/dtr/2.3/guides/admin/backups-and-disaster-recovery/), CC @joaofnfernandes

The docs have a good article about the situation when a majority of replicas are unhealthy or lost.

In the situation when a minority of replicas are unhealthy or lost, i would like to see some documentation about this scenario and that commands to perform to remove those broken replicas and replace them.   

Related to this: 
https://docs.docker.com/datacenter/dtr/2.3/guides/admin/configure/set-up-high-availability/#remove-existing-replicas

**Comment by joaofnfernandes** [comment]
Relates to #3138

**Comment by joaofnfernandes** [comment]
I'm working on this one on the upstream repo, so don't get surprised if this issued is closed. The fix will be available in the next version of DTR.
