### ISSUE TITLE
cli command options - optional and mandatory

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#4614]
### Problem description
In the cli reference docs for UCP/DTR the options are listed for each command. This list of options doesn't tell me what options are the most important ones, ie. what options are mandatory for the command, or optional.

For example, the dtr install command, the ucp-url is a mandatory option.

### Problem location

The CLI reference docs for UCP and DTR

### Project version(s) affected
All
### Suggestions for a fix

In the list of options, help me to distinguish the what are mandatory or optional options.

https://docs.docker.com/datacenter/dtr/2.2/reference/cli/
https://beta.docs.docker.com/datacenter/ucp/2.2/reference/cli/

**Comment by joaofnfernandes** [comment]
The CLI reference docs for DTR and UCP are generated from the same source as `--help`, so to implement this we need to make changes to the UCP and DTR CLI tools.

**Comment by martencassel** [comment]
Thankyou
