### ISSUE TITLE
404 at /reference/api/docker_remote_api_v1.17/

### ISSUE THREAD

**Issue by Imransysg** [docker/docker.github.io#4629]
URL: /reference/api/docker_remote_api_v1.17/

**Comment by mstanleyjones** [comment]
Where did you see the reference to this URL? We post the API back to version 1.18: https://docs.docker.com/engine/api/v1.18/

@thaJeztah are we supposed to have 1.17?

**Comment by thaJeztah** [comment]
Docker 1.5 and older are no longer supported by Docker Hub, so became dysfunctional; documentation for those API versions were removed in https://github.com/moby/moby/pull/22148, but can still be found either in the repository: https://github.com/moby/moby/tree/v1.5.0/docs/sources/reference/api, or the documentation archive: https://docs.docker.com/v1.5/reference/api/docker_remote_api_v1.17/

There used to be a link to those locations, but I think that got lost when we moved to Swagger for the API docs; perhaps we should have a simple page, and link in the API archive menu ("older versions"), although in general there's not much use for using those API versions

**Comment by mstanleyjones** [comment]
It seems like the better option would be to document that those older versions of the API are no longer supported or considered usable.
