### ISSUE TITLE
Create Linux script that automatically installs Docker on Linux flavors

### ISSUE THREAD

**Issue by gtseres** [docker/docker.github.io#4645]
### Problem description

I am not sure if this is the right repo to report this, but I as I was going through the installation steps for Ubuntu, I thought that I would be nice to have Docker automatically installed on Linux machines with the help of a script. The script would simplify the installation process (not that it is hard right now), to two commands: a download and an execution.

### Problem location

This would require the creation of a script (not sure which is the right repo to place it) and some changes in the documentation

### Project version(s) affected

Not applicable

### Suggestions for a fix

It will be an aggregation of the documented steps for the various Linux flavors. The script will initially determine the flavor and then pick the right set of commands to install Docker.

**Comment by gtseres** [comment]
Please let me know of your thoughts on this and I can help on the script.

**Comment by mstanleyjones** [comment]
This already exists for Docker CE for all Linux distributions. See https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-convenience-script, https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script, https://docs.docker.com/engine/installation/linux/docker-ce/centos/#install-using-the-convenience-script, https://docs.docker.com/engine/installation/linux/docker-ce/fedora/#install-using-the-convenience-script

**Comment by gtseres** [comment]
Thanks for the information. Even though I have installed Docker a couple of times, I didn't notice that section. Do you think it would be a good idea to float it to the top, being the most convenient option?

**Comment by pycampers** [comment]
> The script does not provide options to specify which version of Docker to install, and installs the latest version that is released in the “edge” channel.

Dealbreaker.
