### ISSUE TITLE
Add `--dtr-external-url` to DTR install example

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#4646]
File: [datacenter/dtr/2.3/guides/admin/install/index.md](https://docs.docker.com/datacenter/dtr/2.3/guides/admin/install/), CC @joaofnfernandes

`--dtr-external-url` isn't included in the example - had someone install DTR but leave that off and DTR didn't work until they ran a reconfigure to set the external URL.

**Comment by joaofnfernandes** [comment]
@vikstrous I thought `--dtr-external-url` was now optional, so this install instruction would be correct, right?

```
docker run -it --rm \
  docker/dtr:2.3.3 install \
  --ucp-node <ucp-node-name> \
  --ucp-insecure-tls
```

**Comment by vikstrous** [comment]
It is optional. What does "didn't work" mean?

**Comment by mbentley** [comment]
From the conversation I had with Uday:

> Hi Matt, qq-- getting this X509 error while logging to DTR. They installed UCP/DTR without any certs. Any thoughts on why they run into this error? 
> [root@DEE-Ctrl-3 ~]# docker login 10.65.122.64:443
> Username: admin
> Password:
> Error response from daemon: Get https://10.65.122.64:443/v2/: x509: certificate is valid for 172.17.0.1, not 10.65.122.64

> They didn’t add --dtr-external-url, after they reconfigured it worked. In the past, they had it in the install command. Looks like they changed it based on our doc. which now doesn’t mention about --dtr-external-url  —

**Comment by uday-shetty** [comment]
if --dtr-external-url is optional, we should document and provide ways as listed above to fix it.

**Comment by joaofnfernandes** [comment]
We'll solve this one in the upstream repository, so that the fix becomes available in the next version.
