### ISSUE TITLE
Incorrect statment

### ISSUE THREAD

**Issue by rupeshku** [docker/docker.github.io#4648]
File: [engine/userguide/networking/work-with-networks.md](https://docs.docker.com/engine/userguide/networking/work-with-networks/), CC @mstanleyjones
Wrong Statement: Assigned IP addresses are preserved when using non-user-defined networks, because there is no guarantee that a container’s subnet will not change when the Docker daemon restarts unless you use user-defined networks.

In my understanding 
Correct Statement: Assigned IP addresses are not preserved when using non-user-defined networks...

**Comment by shubheksha** [comment]
Can I take this up @mstanleyjones?

**Comment by mstanleyjones** [comment]
Sure, probably best to just remove the incorrect statement.

**Comment by rupeshku** [comment]
As I mentioned, you just need to fix the statement. It's useful statement, removing this is not a good idea. 
Correction: Assigned IP addresses are **not** preserved when using non-user-defined networks, because there is no guarantee that a container’s subnet will not change when the Docker daemon restarts unless you use user-defined networks.
