### ISSUE TITLE
Get rid of all of the `<DOCKER-EE-URL>` references and just use an exported environment variable

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#4654]
File: [engine/installation/linux/docker-ee/rhel.md](https://docs.docker.com/engine/installation/linux/docker-ee/rhel/), CC @mstanleyjones

From some discussions with others in the tech field, there seems to be a fair enough amount of difficulty for users failing to copy & paste, edit the URLs, and then copying & pasting the resulting lines into their console to add the package repositories.  Instead of making the users manually edit the lines, we ought to have the user export an environment variable that will allow them to do direct copy and pastes from the docs to the CLI.  While a relatively simple task to edit the URL in line, the number of times it has come up is surprisingly high.

*edit: I noticed I am late to the party... the docs on docs.docker.com do now use an environment variable; the docs in the store don't reflect as Trap mentions.

**Comment by mbentley** [comment]
For clarity sake, this applies to all of the editions, not just RHEL.

**Comment by trapier** [comment]
As of #4556 it looks like this is just a sync-content-to-docker-store issue.

**Comment by mstanleyjones** [comment]
This is already done! https://docs.docker.com/engine/installation/linux/docker-ee/rhel/#install-docker-ee

Fixed via #4556
