### ISSUE TITLE
EE install shell variable DOCKERURL in setup-yum-repo does not pass through sudo command

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#4656]
### Problem description

```
export DOCKERURL='<DOCKER-EE-URL>'
sudo sh -c 'echo "$DOCKERURL/rhel" > /etc/yum/vars/dockerurl'
```

Environment variables do not pass through sudo by default, so `/etc/yum/vars/dockerurl` ends up containing `/rhel` in this case.

### Problem location
https://docs.docker.com/engine/installation/linux/docker-ee/rhel/#install-using-the-repository

### Project version(s) affected
EE 17.03 and later

### Suggestions for a fix

Add `-E` to pass the env var through sudo:

```
export DOCKERURL='<DOCKER-EE-URL>'
sudo -E sh -c 'echo "$DOCKERURL/rhel" > /etc/yum/vars/dockerurl'
```

**Comment by thaJeztah** [comment]
ping @mstanleyjones ^^

**Comment by mstanleyjones** [comment]
On it 🙀

**Comment by thaJeztah** [comment]
@mstanleyjones I see @trapier opened a PR already https://github.com/docker/docker.github.io/pull/4658
