### ISSUE TITLE
/engine/extend/ or /engine/extend/manifest/ or both?

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#466]
Go to https://docs.docker.com/engine/extend/

This doc exists, but it forwards to https://docs.docker.com/engine/extend/manifest/

`/engine/extend/manifest/` Does not have an entry in the left nav, and seems like a weird place to end up when a doc exists at `engine/extend`, however there is a pre-existing `redirect_from:` that someone put there at some point trying to override it.

**Comment by mstanleyjones** [comment]
@thaJeztah do you know why this is this way? These files are managed in `docker/docker`.

**Comment by thaJeztah** [comment]
It should not forward; I noticed that one in your meta update in the docker/docker repo. The redirect was a copy/paste error in the manifest.md file
