### ISSUE TITLE
service update parallelism incorrect

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#4666]
### Problem description
Parallelism defaults conflict between `service create` (1) and `service update` (0) documentation.

Should the defaults for `--update-parallelism` and `--rollback-parallelism` in `service update` be change to `1`?

Would also like verification that the default for `update-delay` is 0.

### Problem location
https://docs.docker.com/engine/reference/commandline/service_create/#options

conflicts with

https://docs.docker.com/engine/reference/commandline/service_update/#options

### Project version(s) affected
Docker CE 17.06

### Suggestions for a fix
Believe the parallelism parameters should be 1 in both places.

/cc @aluzzardi for confirmation

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #591](https://github.com/docker/cli/issues/591) via [**ZenHub**](https://www.zenhub.com/)
