### ISSUE TITLE
Document MSI behavior in Dockerfiles on Windows

### ISSUE THREAD

**Issue by JimGalasyn** [docker/docker.github.io#4668]
Per [Moby #30395](https://github.com/moby/moby/issues/30395), MSI archives apparently have some idiosyncratic behavior that can make working with them in Compose files challenging. There are workarounds, *e.g.*, [AssimaSA's](https://github.com/moby/moby/issues/30395#issuecomment-330483115): 

> Very elegant solution, this worked with out a problem
> `Start-Process -filepath C:\Teste\rewrite_amd64.msi -ArgumentList "/qn" -PassThru | Wait-Process`
>
> This gave the dreaded 1601 error
> `msiexec.exe /i c:\teste\rewrite_amd64.msi /passive /l*v log.txt`

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by MariusVolkhart** [comment]
This shouldn't have been closed. It's a documentation task, and documentation around this subject is sorely missing.
