### ISSUE TITLE
Wrong sentence about devmapper deferred deletion

### ISSUE THREAD

**Issue by kolyshkin** [docker/docker.github.io#4679]
File: [engine/userguide/storagedriver/device-mapper-driver.md](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/), CC @mstanleyjones

Currently, the documentation says:

> **Note**: The deferred deletion option, `dm.use_deferred_deletion=true`,
> is not yet supported on RHEL, CentOS, or Ubuntu 14.04 when using the
> default kernel version 3.18.

This is very confusing as there is no default kernel version 3.18 for any of those platforms.

I found the original commit (https://github.com/docker/docker.github.io/pull/2266/commits/4d09936aefa3a86b96cbf57b4636e0187a04442c) and it says:

> **Note**: The deferred deletion option, `dm.use_deferred_deletion=true`, is not yet supported
> on CentOS, RHEL, or Ubuntu 14.04 when using the default kernel.  Support was added in the
> upstream kernel version 3.18.

Now, this makes the perfect sense! Please correct the sentence (the way it was stated in the original sounds correct and clear).

**Comment by kolyshkin** [comment]
cc @mbentley please take a look

**Comment by mbentley** [comment]
You are correct.
