### ISSUE TITLE
deprecated: legacy container links should be added here

### ISSUE THREAD

**Issue by rdxmb** [docker/docker.github.io#4680]
File: [engine/deprecated.md](https://docs.docker.com/engine/deprecated/), CC @mstanleyjones

see
https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

**Comment by mstanleyjones** [comment]
@thaJeztah WDYT? I am not sure it's the same sort of deprecation...

**Comment by thaJeztah** [comment]
It's not really deprecated, more "obsoleted" when using custom networks. I did write a proposal to deprecate it, and re-implement using built-in DNS for the default network as well (see https://github.com/moby/moby/issues/22295), but didn't get a lot of traction yet
