### ISSUE TITLE
Splunk logging docs should show log-opts property in daemon.json config options

### ISSUE THREAD

**Issue by anweiss** [docker/docker.github.io#4681]
### Problem description

The "Usage" section of the Splunk logging driver configuration docs [here](https://docs.docker.com/engine/admin/logging/splunk/#usage) does not provide a `daemon.json` example which includes the `"log-opts"` property. Without this, the doc page seems to infer that the only way to configure the Splunk logging driver options are when you run the containers via the `--log-opts` flag.

### Problem location

https://docs.docker.com/engine/admin/logging/splunk/#usage

`daemon.json` file sample

### Suggestions for a fix

Update `daemon.json` file sample to something like as follows:

```json
{
  "log-driver": "splunk",
  "log-opts": {
    "splunk-token": "",
    "splunk-url": "",
    ...
  }
}
```

**Comment by gbarr01** [comment]
HI, @anweiss, I'm going up update the page with your example. 

In the meantime, can you confirm that the text in the paragraph just under **Usage** should also be changed? Should log-opt be changed to log-opts in this section? 

Should this ... 

> To use the splunk driver as the default logging driver, set the log-driver and log-opt ...

be changed to ...

> To use the splunk driver as the default logging driver, set the log-driver and log-opt**s** ...

Do you know why daemon.json uses `log-opts` and docker run uses `log-opt`?

**Comment by anweiss** [comment]
Thanks @gbarr01. It should be changed to `log-opts`. This is also confirmed in the `daemon.json` listing [here](https://docs.docker.com/engine/reference/commandline/dockerd/). If I were to guess why `daemon.json` uses `log-opts` and docker run uses `log-opt` it would be due to the semantics of a JSON file's types vs. CLI best practices accepting multiple values for the same flag

**Comment by gbarr01** [comment]
Hi, @anweiss , it seem like this page has similar problems? 
https://docs.docker.com/engine/admin/logging/journald/
Do you agree?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
