### ISSUE TITLE
OS unclear

### ISSUE THREAD

**Issue by SquadronROE** [docker/docker.github.io#4683]
File: [get-started/index.md](https://docs.docker.com/get-started/), CC @johndmulhausen

It's unclear what the OS infrastructure is that this tutorial relies on, until the second page. And then only because I'm noticing they're bash scripts rather than Powershell or batch commands.

If we're relying on a specific OS to complete the tutorial it should be called out at the  beginning of the document, something simple like:

"For the purposes of this tutorial and the examples, we're assuming MacOS version _n_"

**Comment by londoncalling** [comment]
@SquadronROE this tutorial is not meant to rely on any specific OS, but rather is intended to work on Mac, Linux, and Windows systems. I'm  finishing up a PR that address some steps that did not work across all platforms. I'm attaching this issue to that PR, as it should clarify some issues about different types of commands, and hopefully solve the cross-platform problem. 

@gbarr01 has also added updates to the tutorial in this regard.

**Comment by SquadronROE** [comment]
Hey,

Sorry this is late but I wanted to thank you for taking a moment to address
this. It really helps, especially as I'm trying to encourage our developers
to use docker in personal investigations and we're a Microsoft shop. By
helping to make this OS-agnostic, you're helping me make our development
processes more fun and efficient.

Which, in turn, helps us serve our clients (non-profits) better.

Sean Long

**Comment by londoncalling** [comment]
Thanks for the kind words @SquadronROE , we had to make another change to part 5 in [Persist the data workflow](https://docs.docker.com/get-started/part5/#persist-the-data) steps 2 and 3, per PR #4725 , issue #4723 , but we are going to work on this today to see if we can dispense with any need for `scp` in this step as well.
