### ISSUE TITLE
Add support to tarball .xz with volume header

### ISSUE THREAD

**Issue by geaaru** [docker/docker.github.io#4693]
### Problem description

On ADD .xz tarball with volume header I have this error:

Step 6/14 : ADD ./portage-latest.tar.xz /usr
Error processing tar file(exit status 1): Unhandled tar header type 86

### Problem location

A description of the problem is also here: https://bugs.gentoo.org/631644

### Project version(s) affected

Server Version: 17.06.0-ce
containerd version: d24f39e203aa6be4944f06dd0fe38a618a36c764 (expected: cfb82a876ecc11b5ca0977d1733adbe58599088a)
runc version: 2d41c04 (expected: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4)
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.12.10
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64

**Comment by gbarr01** [comment]
Hi, @geaaru, you filed this under docs. Which page are you referring to?

**Comment by geaaru** [comment]
Sorry, wrong place. It's related to docker-ce.
But could be helpful add some informations to ADD command to avoid use of tar with volume header enable.

**Comment by gbarr01** [comment]
Hi @geaaru , I believe we cover this topic here: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#add-or-copy

I'm going to close this issue but continue to look for other ways to make this topic more clear.
