### ISSUE TITLE
does not work for raspbian stretch today

### ISSUE THREAD

**Issue by stuuu68** [docker/docker.github.io#4699]
File: [engine/installation/linux/docker-ce/debian.md](https://docs.docker.com/engine/installation/linux/docker-ce/debian/), CC @mstanleyjones

There appears to be no armhf stretch stable docker-ce package in your repo, so these instructions don't work.
 I was able to find an rpm under stretch/pool/test on the download page and this will install once some additional dependencies have been satisfied.
The hello-world example does not work though. Just exits with no errors or logs.

**Comment by pacdaemon** [comment]
I got the same issue.

`root@raspberrypi:/etc/apt/sources.list.d# cat /etc/apt/sources.list.d/docker.list 
deb [arch=armhf] https://download.docker.com/linux/raspbian      stretch stable
root@raspberrypi:/etc/apt/sources.list.d# apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease                       
Hit:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease                 
Hit:3 https://download.docker.com/linux/raspbian stretch InRelease
Reading package lists... Done
root@raspberrypi:/etc/apt/sources.list.d# apt-get install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-ce
root@raspberrypi:/etc/apt/sources.list.d# 
`

Thanks in advance

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
