### ISSUE TITLE
DNSRR Section seems wrong

### ISSUE THREAD

**Issue by Budwise** [docker/docker.github.io#4713]
File: [engine/swarm/networking.md](https://docs.docker.com/engine/swarm/networking/), CC @mstanleyjones

> DNS round-robin is useful in cases where you want to use your own load balancer. 

It seems it should be:
DNS round-robin is useful in cases where you don't want to use your own load balancer.

**Comment by mstanleyjones** [comment]
I think the section is actually correct. The intent is "If you want to use an external load balancer, outside of the Docker ecosystem". @thaJeztah @stevvooe please confirm. If I'm right, we can reword for clarity.

**Comment by thaJeztah** [comment]
Correct; when using VIP, there is a single IP-address exposed for the service, traffic for that IP-address is load-balanced using an internal load balancer.

If you want to use your own load balancer, you can use DNS round-robin to get the IP-addresses for the individual containers, and have you own load balancer balance traffic to those containers.

**Comment by mstanleyjones** [comment]
@gbarr01 can you take point on updating the wording on this?

**Comment by stevvooe** [comment]
Yes, this could use clarification. It might make sense to say "DNS RR is useful when you want your own load balancer to know about all service backends." We could also clarify that clients who know about DNS RR would also make the selection on their own.

I think the biggest difference is L3/4 (connection based) vs L7 (request based) but that might be a bigger bite to chew.

**Comment by gbarr01** [comment]
@mstanleyjones, absolutely.

**Comment by gbarr01** [comment]
Hi, @stevvooe , I added a bit about L3/4 and L7 in #4736. Your feedback is welcome.

**Comment by stevvooe** [comment]
@gbarr01 No worries, I'm not a maintainer here. The change LGTM.

**Comment by Budwise** [comment]
The issue I've found is when using multiple services together to make the entire application.  In my instance, we have 3 containers in the stack, an IIS app, an IIS service, and redis.  I then duplicate the stack across several VM's.  When in DNSRR mode, if you exec into any one of them and nslookup it shows you all the container IP's across all the VM's as expected and if you ping the service by name it doesn't necessarily pick the one local to it in the swarm, it could ping across from VM1 to VM3.  It load balances across the swarm backend containers.  If you used your own external load balancer in this case you'd be load balancing across the IIS container, sure, but the back end containers load balance themselves via DNSRR.  This is good and bad, but bad for our software design.  We need each stack on each VM to only network to containers on its own VM.  Unfortunately, if you don't use DNSRR it seems to break network connectivity between the containers completely.  They will resolve but not ping or pass traffic between them without using DNSRR.

**Comment by mstanleyjones** [comment]
@Budwise please file an issue in `moby/moby` if you think DNSRR should work differently with swarm services. We just try to document the current behavior and can't actually change the behavior itself.
