### ISSUE TITLE
The /containers/create call requires a Content-Length header.

### ISSUE THREAD

**Issue by rendragnet** [docker/docker.github.io#4720]
The POST /containers/create call simply returns '{"message":"EOF"}' with no other explanation, if the POST request is missing the Content-Length: header.  The example should include this header, if it is going to be required, and no clean error message is display when it is missing.  That's three hours of my life, and a lot of stracing, which I'll never get back.
 
File: [engine/api/v1.24.md](https://docs.docker.com/engine/api/v1.24/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
@thaJeztah should this be updated? We don't generally update old APIs, correct?

**Comment by thaJeztah** [comment]
old API versions are still supported, so from that perspective it would be good to update them. 

Having said that, I think it's [part of the HTTP specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4), so not specific to the API, but messaging could be better, and I agree it wouldn't hurt to update the examples.

**Comment by mstanleyjones** [comment]
Closed via https://github.com/moby/moby/pull/35129
