### ISSUE TITLE
Starting Redis outside of management node results in bind exception

### ISSUE THREAD

**Issue by jasonmevans** [docker/docker.github.io#4723]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/), CC @johndmulhausen

First, thanks for the very thorough, and well-written tutorial. I've found it extremely helpful getting acquainted with Docker.

I was following the instructions verbatim, and was having great success up to the point where I was deploying the Redis service. After creating the `~/data` folder in myvm1, checking `docker-machine ls` for myvm1 being active and running the `docker stack deploy -c docker-compose.yml getstartedlab` I noticed my Redis service was failing to start with the error *invalid mount config for type "bind": bind source path does not exist*. After Googling around for a while I determined that the issue was that the Redis service was not finding the data folder I had created on the manager node; however, it was there. I tried several times to tear down the service, restart the service and even tried creating a data folder at `/data`, but had no luck. 

Then, I remembered while watching the screen recording at the bottom of the tutorial page that you actually started the getstartedlab stack by scp-ing the docker-compose.yml file into the master, and running the `docker stack deploy ...` command directly from there. I gave that method a shot, and was successful! I believe what was happening was that the `docker-machine env myvm1` command was causing the `docker stack deploy ...` command to actually look for the data folder in my MacBook home folder INSTEAD of in the management node.

Can you confirm/refute my diagnosis, and if correct suggest how to get the posted docs to work as written? If it is not actually possible to execute the `docker stack deploy ...` command from outside of the management node for the reason I have proposed could you please update the tutorial to reflect that?

Thanks very much!
Jason Evans

**Comment by johndmulhausen** [comment]
Yep that's the issue! You can actually avoid doing it the `scp` way; @londoncalling is punching up this page so it's a little less confusing, and also `scp` is Linux-only. But the essential takeaway you have: that you have to direct the manager to run the `docker stack deploy` command is correct. :)

Will review how clear we are being about where the command needs to run with @londoncalling

**Comment by londoncalling** [comment]
@jasonmevans you are exactly right. We are trying to find a way to make the commands work natively on both Mac and Windows. We'll address this in the docs today one way or the other. More soon.

**Comment by jasonmevans** [comment]
@johndmulhausen @londoncalling I really appreciate you guys looking at this so quickly. I just tested out what I suspected was happening, and yeah it binds to the data folder in the working folder in my Mac file system. Kinda neat, actually! Docker is quite powerful. 

Anyways, thanks again. I'll check back to see what changes you end up making to the docs. I'm curious how to do this w/o involving SCP.

**Comment by londoncalling** [comment]
@shin- cc-ing you just as an FYI for when we experiment with it.

**Comment by JoeAlamo** [comment]
When I was going through the tutorial I changed the volume definition from ./data:/data to /home/docker/data:/data and that worked for me.

Should I have SCP'd the file instead to the manager node VM? (running on Ubuntu btw)

Many thanks

**Comment by londoncalling** [comment]
If this worked for you without the scp, that may have solved our problem.
I'm going to try it now.
