### ISSUE TITLE
Docker For Windows lists two default networks not three

### ISSUE THREAD

**Issue by mloskot** [docker/docker.github.io#4729]
File: [engine/userguide/networking/index.md](https://docs.docker.com/engine/userguide/networking/), CC @mstanleyjones

The doc lists three default networks:

```console
$ docker network ls

NETWORK ID          NAME                DRIVER
7fca4eb8c647        bridge              bridge
9f904ee27bf5        none                null
cf03ee007fb4        host                host
```

while `docker` from Docker For Windows (Version 17.06.2-ce-win27 (13194)) lists two:

```console
C:\>docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
44947576a074        nat                 nat                 local
332023fb05f6        none                null                local
```

and the first one is named `nat`.

It would be be helpful to clarify the differences.

This might be related to #4705

**Comment by JimGalasyn** [comment]
Thanks for the feedback! This behavior is by design.
