### ISSUE TITLE
Incorrect title hierarchy

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#4742]
File: [datacenter/install/linux.md](https://docs.docker.com/datacenter/install/linux/), CC @joaofnfernandes

The title hierarchy displayed in the right tree is somewhat incorrect. Step 2 to step 5 are disaplyed as substeps of step1. Is it because a heading 2 before step 1 is missing?
![navigation-tree](https://user-images.githubusercontent.com/25146885/30957495-00680a24-a46d-11e7-949a-e01f2a8f423f.jpg)

**Comment by johndmulhausen** [comment]
Seems like a bug with the TOC generator, @mstanleyjones

**Comment by mstanleyjones** [comment]
Not a bug, the headings start at H3 when there are no H2s. Fixed in #4788.
