### ISSUE TITLE
'docker pull' when running 'docker stack deploy' ?

### ISSUE THREAD

**Issue by marcbihlmaier** [docker/docker.github.io#4747]
File: [engine/reference/commandline/stack_deploy.md](https://docs.docker.com/engine/reference/commandline/stack_deploy/), CC @mstanleyjones

it is not defined here if
`docker stack deploy`
also pulls the new images, especially if they are tagged again with `latest`

It would be great to have this documented clearly - especially for people coming from `docker-compose`, where they are used to run `docker-compose pull` .

// edited:
seems like it is pulled only when another tag is defined - an the image does not exist locally:
https://github.com/moby/moby/issues/30951

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #585](https://github.com/docker/cli/issues/585) via [**ZenHub**](https://www.zenhub.com/)
