### ISSUE TITLE
Describe how restart with time flag works

### ISSUE THREAD

**Issue by montanaflynn** [docker/docker.github.io#4749]
File: [engine/reference/commandline/restart.md](https://docs.docker.com/engine/reference/commandline/restart/), CC @mstanleyjones

It's unclear how the `--time` flag works, does it simply simply sleep before stopping the container or does it follow the same logic as [`docker stop`](https://docs.docker.com/engine/reference/commandline/stop/) where it first sends a `SIGTERM` followed by `SIGKILL` after the time period is up?

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #584](https://github.com/docker/cli/issues/584) via [**ZenHub**](https://www.zenhub.com/)
