### ISSUE TITLE
Feedback for: cs-engine/install.md

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#475]
URL: [https://docs.docker.com/cs-engine/install.md](https://docs.docker.com/cs-engine/install/)

The links in the TOC are broken.  The right side pane seem to be correct.

**Comment by johndmulhausen** [comment]
Can't repro on Chrome, Firefox, or MS Edge. Re-open if this is still going on. Otherwise, not sure what to tell you.

**Comment by mbentley** [comment]
Broken in the Table of Contents (they don't take you to the anchor):
https://docs.docker.com/cs-engine/install/#/install-on-centos-7-1-7-2-rhel-7-0-7-1-7-2-yum-based-systems
https://docs.docker.com/cs-engine/install/#/install-on-ubuntu-14-04-lts
https://docs.docker.com/cs-engine/install/#/install-on-suse-linux-enterprise-12-3

Correct links based on what the anchors are set to:
https://docs.docker.com/cs-engine/install/#/install-on-centos-7172--rhel-707172-yum-based-systems
https://docs.docker.com/cs-engine/install/#/install-on-ubuntu-1404-lts
https://docs.docker.com/cs-engine/install/#/install-on-suse-linux-enterprise-123

**Comment by johndmulhausen** [comment]
If I click on the links on the right nav I get:

https://docs.docker.com/cs-engine/install/#install-on-centos-7172--rhel-707172-yum-based-systems

No idea where the "broken" link is coming from? What browser?

**Comment by mbentley** [comment]
The navigation on the right is fine.  The table of contents on the page is where it is broken.
Google Chrome 55.0.2883.44 beta (64-bit)

**Comment by sanscontext** [comment]
Ah, someone manually made a TOC. I

**Comment by sanscontext** [comment]
I'm on this one, one sec.

**Comment by sanscontext** [comment]
Closed via #557

**Comment by johndmulhausen** [comment]
Thanks, @sanscontext :)
