### ISSUE TITLE
docker rmi is missing, docker image rm not available

### ISSUE THREAD

**Issue by jonaseberledmind** [docker/docker.github.io#4757]
File: [engine/reference/commandline/image_prune.md](https://docs.docker.com/engine/reference/commandline/image_prune/), CC @mstanleyjones

At least for me: Docker version 1.12.4, build 1564f02

**Comment by mstanleyjones** [comment]
Hi @jonasbn, there are separate references for each command. You're looking at the one for `docker image prune`. See also [`docker rmi`](https://docs.docker.com/engine/reference/commandline/rmi/) and [`docker image rm`](https://docs.docker.com/engine/reference/commandline/image_rm/). These two commands are equivalent.

**Comment by jonaseberledmind** [comment]
I did not see that there was a switch for the version. Nvm, changing the version shows correctly that there is no "prune" and no "docker image rm".

**Comment by jonasbn** [comment]
hi @mstanleyjones I am not @jonaseberledmind :-)

**Comment by mstanleyjones** [comment]
Sorry about that!
