### ISSUE TITLE
Install plugins on Swarm broken link to the PluginSpec.

### ISSUE THREAD

**Issue by NicoTexas** [docker/docker.github.io#4773]
File: [engine/swarm/manage-nodes.md](https://docs.docker.com/engine/swarm/manage-nodes/), CC @mstanleyjones 

On https://docs.docker.com/engine/swarm/manage-nodes/#install-plugins-on-swarm-nodes
There is a broken link to the PluginSpec.

This is also missing some example on how to do plugin installation using the API.

**Comment by mstanleyjones** [comment]
Thanks for the report. I'll get it fixed shortly. As for the example, you just pass the JSON in the same way you pass other JSON objects to `/service/create` or `/service/update` endpoints. See https://docs.docker.com/engine/api/v1.32/#operation/ServiceCreate.
