### ISSUE TITLE
Link to API reference from main API/SDK page

### ISSUE THREAD

**Issue by bfirsh** [docker/docker.github.io#4775]
File: [develop/sdk/index.md](https://docs.docker.com/develop/sdk/), CC @johndmulhausen

This is the top result for "docker api" on Google, but there is no link to the actual API reference from this page which was the thing I was looking for. Perhaps worth putting a link to https://docs.docker.com/engine/api/v1.32/ in the left hand bar and as a section in this page.

Confusingly, clicking on "reference", then "Docker Engine API", then "Overview" takes me back to this page, again taking me away from the reference which was the thing I actually wanted.

**Comment by mstanleyjones** [comment]
This is difficult because we'd have to update that link every time we update the API, I think ... @johndmulhausen any ideas?

**Comment by bfirsh** [comment]
`/engine/api/latest/` or something could redirect to the latest API version, then it just needs updating in one place. :)

**Comment by johndmulhausen** [comment]
I would make a `latest_stable_api` var, then at /engine/api/latest put in a blank HTML file that just has a `<meta refresh>` forwarding to `/engine/api/{{ latest_stable_api }}`

**Comment by johndmulhausen** [comment]
Alternatively we can look into nginx vdir stuff
