### ISSUE TITLE
Wrong digest Algorithm regexp

### ISSUE THREAD

**Issue by Kanshiroron** [docker/docker.github.io#4776]
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/), CC @joaofnfernandes 

Hello,
The image digest Regular expression (grammar), should be `algorithm   := /[A-Za-z0-9_+.-]+/` instead of `algorithm   := /[A-Fa-f0-9_+.-]+/`

Best,

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
