### ISSUE TITLE
I could not be able to resize the loop-lvm with any of the methods

### ISSUE THREAD

**Issue by nicolaevladescu** [docker/docker.github.io#4780]
The device tool  from contrib/ cannot be built, there is no shell makefile
 `make: *** No rule to make target shell'.  Stop.`

The manual method fails on `dmsetup resume`
```
device-mapper: resume ioctl on docker-202:1-656745-pool failed: Invalid argument
Command failed
```

File: [engine/userguide/storagedriver/device-mapper-driver.md](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
@cpuguy83 @trapier Any ideas?

**Comment by nicolaevladescu** [comment]
The issue while using the  `device_tool` option is fairly straightforward so i won't try to reproduce it here. You can check it with a simple `git clone` and `make shell` as instructed by the documented option.
I am guessing this option is making some assumptions of where it is being ran that are not documented, please correct me if i am missing something.

This are the steps to reproduce the issue on a Amazon Linux AMI on EC2 while trying the option that uses the operating system utilities.

Note that i am resizing to a smaller volume (half of the default 100G), the example in the documentation does a resize where it increases the volume (doubles the default 100G), but it does not state that this method is exclusively to be used when resizing up.

Login to SSH after the machine booted and become `root`
`$ sudo -i`

Install Docker
`$ yum makecache && yum install docker`

Set the storage driver to `devicemapper` (it used to be the default, now i see it defaulted to overlay2 after install)
```
$ cat <<EOT >> /etc/docker/daemon.json
{
  "storage-driver": "devicemapper"
}
EOT
```
Restart Docker Engine
`$ service docker restart`

Check the storage settings
```
$ docker info | grep loop
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
```

Check the size of the data loop file
```
$ ls -lha /var/lib/docker/devicemapper/devicemapper/data | cut -d" " -f5
100G
```

Start the resize process
`truncate -s 50G /var/lib/docker/devicemapper/devicemapper/data`
```
$ ls -lh /var/lib/docker/devicemapper/devicemapper/
total 12M
-rw------- 1 root root  50G Oct  6 14:19 data
-rw------- 1 root root 2.0G Oct  6 14:08 metadata
```
```
$ echo $[ $(sudo blockdev --getsize64 /dev/loop0) / 1024 / 1024 / 1024 ]
100
```
`losetup -c /dev/loop0`
```
$ echo $[ $(sudo blockdev --getsize64 /dev/loop0) / 1024 / 1024 / 1024 ]
50
```
```
$ dmsetup status | grep ' thin-pool ' | awk -F ': ' {'print $1'}
docker-202:1-399514-pool
```
```
$ dmsetup table docker-202:1-399514-pool
0 209715200 thin-pool 7:1 7:0 128 32768 1 skip_block_zeroing
```
`$ dmsetup suspend docker-202:1-399514-pool`

Update the sector size: 209715200 / 2 = 104857600
```
$ dmsetup reload docker-202:1-399514-pool --table '0 104857600 thin-pool 7:1 7:0 128 32768 1 skip_block_zeroing'
```
```
# dmsetup resume docker-202:1-399514-pool
device-mapper: resume ioctl on docker-202:1-399514-pool failed: Invalid argument
Command failed
```

Restart Docker engine
`$ service docker restart`

All changes are undone
```
$ ls -lh /var/lib/docker/devicemapper/devicemapper/
total 12M
-rw------- 1 root root 100G Oct  6 14:26 data
-rw------- 1 root root 2.0G Oct  6 14:26 metadata
```

**Comment by ahh-docker** [comment]
Hello! Thanks for filing an issue with the Docker documentation team. Unfortunately, it looks like your issue is more of a support issue than a documentation issue.

For the Docker Community Edition (CE), please visit https://forums.docker.com/, and post your issue there.

For Docker Enterprise Edition (EE) subscribers, please visit https://success.docker.com/support, and contact Docker Support directly.

If this is a documentation issue, please reopen the issue, along with more detailed comments on what needs a review and possible edit. Thanks!
