### ISSUE TITLE
/v17.06/ thinks it's current and has no archive butterbar

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#4785]
https://docs.docker.com/v17.06/

The drop down shows "current" on 17.06 (doesn't have a concept of 17.09) and does not have the archive butterbar.

We must have missed a step for ensuring that the json got updated?

**Comment by mstanleyjones** [comment]
I'm investigating.

**Comment by mstanleyjones** [comment]
Fixed via #4787
