### ISSUE TITLE
More detailed DTR restore command

### ISSUE THREAD

**Issue by ahromis** [docker/docker.github.io#4786]
The current DTR restore example will product a `EOF unexpected end of file` error.

The only way to get a restore to work is by passing *all* expected fields (i.e. `--ucp-url`, `--ucp-node`, `--ucp-username`, `--ucp-password`, etc.), since we are streaming a tar file from the output creating a TTY with `-t` will create an error, causing this command to not be run in interactive mode.

Updating the example with this information will make it more usable for anyone trying to restore DTR, thanks!

File: [datacenter/dtr/2.2/reference/cli/restore.md](https://docs.docker.com/datacenter/dtr/2.2/reference/cli/restore/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
@ahromis you are right, and this needs to be fixed in the `docker/dtr tool` itself. In the meantime you can follow https://docs.docker.com/datacenter/dtr/2.4/guides/admin/backups-and-disaster-recovery/, which has more information on how to backup and restore.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
