### ISSUE TITLE
IP address accessible from external server?

### ISSUE THREAD

**Issue by scheung38** [docker/docker.github.io#4793]
if I am running my app inside a docker container and it is making a HTTP request to an external URL http or https, can the server obtain the user’s IP address in this case? If so how can I hide IP address if that is possible. Thanks

**Comment by mstanleyjones** [comment]
The host machine where you run Docker routes and forwards traffic for your container, so if your host machine can access the internet, then your container can. If you want external hosts to be able to reach your container, you need to open the correct ports on your firewall and configure your network appropriately. For more questions like this, please use the Docker forums at https://forums.docker.com/.
