### ISSUE TITLE
more documentation inconsistancies

### ISSUE THREAD

**Issue by BarnumD** [docker/docker.github.io#4795]
File: [engine/userguide/networking/default_network/custom-docker0.md](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/), CC @mstanleyjones 
In the example: "--fixed-cidr=172.17.2.0/24 and default-gateway=172.17.1.1"
172.17.2.0/24 and 172.17.1.1 aren't even in the same network.  How can that be?

**Comment by mstanleyjones** [comment]
I can think of a few reasons. You have more than one network interface, one of which is on the `172.17.1` network and the other of which is on the `172.17.2` network. Your default gateway is reachable through the first interface, but your Docker stuff uses the second one. You can also assign multiple IP addresses (on multiple networks) to the same physical or virtual device in Linux.
