### ISSUE TITLE
Docker for AWS template archive is out of date

### ISSUE THREAD

**Issue by josephtyler** [docker/docker.github.io#4797]
File: [docker-for-aws/archive.md](https://docs.docker.com/docker-for-aws/archive/), CC @johndmulhausen

**Comment by mstanleyjones** [comment]
@FrenchBen PTAL

**Comment by FrenchBen** [comment]
We're working on aligning the update process to match that of Azure. 
@josephtyler what's your immediate need for old deployments that do not have the latest fix?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
