### ISSUE TITLE
docker-trusted-registry url points to older DTR version

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#4799]
Short url https://docs.docker.com/docker-trusted-registry/ could probably use updated to point to version 2.3.  It currently points to DTR 2.0.

File: [index.md](https://docs.docker.com/), CC @johndmulhausen

**Comment by JimGalasyn** [comment]
Looks like we need to move the redirects from `/datacenter/dtr/2.0/index.md` to `/datacenter/dtr/2.3/guides/index.md`.

```
redirect_from:
- /docker-hub-enterprise/
- /docker-trusted-registry/overview/
- /docker-trusted-registry/
```
