### ISSUE TITLE
Heading should be "amd64" not" x86_64"

### ISSUE THREAD

**Issue by navinger** [docker/docker.github.io#4803]
File: [engine/installation/linux/docker-ce/debian.md](https://docs.docker.com/engine/installation/linux/docker-ce/debian/), CC @mstanleyjones

Hello, 
The heading above the following command currently is x86_64 and it should amd64:

$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable"

I'm linking to this page from another doc set which requires amd64, and this will make it hard for users to find the right command. 

Thanks,
Nancy

**Comment by mstanleyjones** [comment]
I believe that `amd64` is a subset of `x86_64` and these packages work on all X86 64-bit hardware. I don't think this is something we should change. We did have other users who were confused about whether we supported non-AMD X86 hardware.

cc/ @andrewhsu in case I'm wrong, but I'm inclined to close this. You can always clarify for your users on the page where you are linking from.

**Comment by andrewhsu** [comment]
In the debian world, they specify `amd64` as the architecture so I would suggest we stick to that in the documentation: https://wiki.debian.org/DebianAMD64Faq

As a side note, debian labels the power architecture `ppc64el` instead of `ppc64le`: https://lists.debian.org/debian-powerpc/2014/08/msg00042.html

I wish architecture names were more standardized across linux distros.

**Comment by mstanleyjones** [comment]
Ugh. SHould we call it `amd64` everywhere or just in Debian / Ubuntu? We have quite a bit of content reuse that will be annoying to maintain if we diverge.

**Comment by navinger** [comment]
Hi,

Just want to say that I really appreciate the quick response on this issue.

Perhaps you've already seen it, but In the Ubuntu section
<https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository>,
the heading is already "amd64" above the command:
sudo add-apt-repository \
   "deb [arch=amd64] ...

That's why I was confused when the similar command in the Debian section
had x86_64 as the heading.

In my docs, we used to have the Docker commands to install Docker on a
Debian VM instance, but they were never quite right. I think it's better to
link to your docs. This is what I've added:

Follow the steps in the Docker Docs
<https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-repository>
to
set up the Docker repository for *amd64* and install Docker CE on the
instance.

The Docker Docs list several sudo add-apt-repository commands. Make sure
you run the one for *amd64*:

$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(.
/etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable"


So I'm hoping that's clear enough for our users.

Thanks again,

Nancy

**Comment by mstanleyjones** [comment]
You're most welcome! For the record, my "ugh" response was not to you. It was just annoyance at the fact that we just standardized on `x86_64` a few weeks ago after a lot of back-and-forth. Still not sure which way to go, but I'm pondering it.

**Comment by navinger** [comment]
Hi,

I've got a link to your docs in my docs:
https://cloud.google.com/endpoints/docs/openapi/get-started-compute-engine-docker#install_docker_on_the_vm_instance

I hate linking to another doc set in a procedure. Do you think Docker CE
installation is fairly stable? It would be better to have the exact steps
for Debian in my procedure, and then a "for more information, see the
Docker documentation."

Thanks
Nancy

**Comment by mstanleyjones** [comment]
The steps should be pretty stable, yep. We revamped the installation procedures several months ago to make them less error-prone. For Docker CE you could also consider just having them use the convenience script: https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script (noting the caveats)

**Comment by navinger** [comment]
Thanks for the tip about the script. I’ll definitely add that. I think I’ll
go ahead and add the steps for installing Docker CE back to our docs, with
a link to the convenience script.
