### ISSUE TITLE
Do we have documentation explaining --config-from and --config-only?

### ISSUE THREAD

**Issue by jpetazzo** [docker/docker.github.io#4807]
We support using local networks in Swarm mode, and it can involve flags `--config-from` and `--config-only`. (The original PR, https://github.com/moby/moby/pull/32981, has some context)

But I can't find any actual documentation on these options anywhere. Is it missing, or just not properly linked/referenced?

File: [engine/reference/commandline/network_create.md](https://docs.docker.com/engine/reference/commandline/network_create/), CC @mstanleyjones 

See also: https://github.com/docker/cli/issues/407

**Comment by JimGalasyn** [comment]
We have a little bit on these options in the UCP docs, but it's pretty thin and assumes that you know what you're doing: [Use a local node network in a swarm](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/use-node-local-network-in-swarm/).

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #605](https://github.com/docker/cli/issues/605) via [**ZenHub**](https://www.zenhub.com/)
