### ISSUE TITLE
Feedback for: engine/tutorials/networkingcontainers.md

### ISSUE THREAD

**Issue by skcodes** [docker/docker.github.io#482]
URL: [https://docs.docker.com/engine/tutorials/networkingcontainers.md](https://docs.docker.com/engine/tutorials/networkingcontainers/)
I agree with others that this very clearly describes how to network 2 containers. What I'm not understanding is *why* I want/need to network containers. What am I trying to accomplish by networking containers?

**Comment by mstanleyjones** [comment]
Hi @skcodes, I'm not sure exactly what you are asking. Networking two containers is a very open-ended use case, just like networking two physical computers together. You might be segregating microservices which need to talk to each other, or the two containers could be in a dependent relationship, such as when one runs WordPress and the other runs the MySQL database needed by WordPress. Or one container may be handling ingest and the other is running a Spark service to analyze the data coming in. Or you may have 10 containers serving a website, with one container acting as a load balancer. The possibilities are endless (and therefore, difficult to document). Does this help?
