### ISSUE TITLE
Use `.yaml` Instead of `.yml` in Documentation

### ISSUE THREAD

**Issue by jasonrogena** [docker/docker.github.io#4823]
### Problem description

Not nitpicking, but it might be time to start using the recommended file extension for YAML files (`.yaml`) as [recommended on yaml.org](http://yaml.org/faq.html).

### Problem location

The docker compose file in [this page](https://docs.docker.com/compose/overview/), for instance, uses `.yml`.

### Project version(s) affected

All versions.

**Comment by thaJeztah** [comment]
I think that would make sense, but we need to make sure to mention that both `.yml` and `.yaml` are supported.

One thing I noticed is that the docker-compose code actually seems to prefer `.yml` over `.yaml`;
https://github.com/docker/compose/blob/dc838067fd4ccdf381108acb03bac261924fd297/compose/config/config.py#L133-L136

@shin- @dnephin should we change that?

**Comment by shin-** [comment]
I'm fairly confident it wouldn't cause any issues, but we do historically prefer the `yml` extension. I don't really think a change is warranted.

**Comment by jasonrogena** [comment]
Cool, I guess you can leave it as is. It's more for standards compliance.

**Comment by johndmulhausen** [comment]
Thanks for the discussion all.
