### ISSUE TITLE
Steps for forwarding on Fedora

### ISSUE THREAD

**Issue by WyseNynja** [docker/docker.github.io#4834]
File: [engine/installation/linux/linux-postinstall.md](https://docs.docker.com/engine/installation/linux/linux-postinstall/), CC @mstanleyjones

On Ubuntu with ufw, we can set `DEFAULT_FORWARD_POLICY="ACCEPT"`

On Fedora with firewalld, I needed this at `/etc/firewalld/direct.xml`:
```
<?xml version="1.0" encoding="utf-8"?>
<direct>
   [ <rule ipv="ipv6" table="filter" chain="FORWARD_direct" priority="0"> -i zt0 -j ACCEPT </rule> ]
   [ <rule ipv="ipv6" table="filter" chain="FORWARD_direct" priority="0"> -o zt0 -j ACCEPT </rule> ]
</direct>
```

The interface obviously needs to match the host system. I'm using zerotier with ipv6. I think ipv4 might need a masquerade option, too.

**Comment by mstanleyjones** [comment]
I am kind of -1 on documenting distro-specific firewall stuff. For one thing, this does not apply to Windows and the process for opening firewall ports and doing port forwarding on Windows is again different. Shouldn't we only need to state what the end state needs to be, and let the system admin figure out the appropriate way to get there using their OS documentation?

cc/ @thaJeztah in case my opinion is way off base.
