### ISSUE TITLE
Document how to use Docker on Windows (Server, primarily) from non-admin prompt

### ISSUE THREAD

**Issue by friism** [docker/docker.github.io#4870]
eg. add to `docker-users`.

https://github.com/docker/for-win/issues/868#issuecomment-312639000

... this should not be documented in the context of CE, I think - where this is supposed to be automatic.

cc @johnstep @mstanleyjones

**Comment by gbarr01** [comment]
@mstanleyjones , @friism , what do you think about a note on one or both of these pages? 

https://docs.docker.com/docker-for-windows/install/
https://docs.docker.com/docker-for-windows/

**Comment by londoncalling** [comment]
@gbarr01 given @friism 's comment re: "should not be documented in the context of CE .." the better place for a note would likely be somewhere on this page, install for EE: https://docs.docker.com/engine/installation/windows/docker-ee/ (rather than the above two pages)

What do you think @friism ?

**Comment by friism** [comment]
yes, `docker-ee` ftw

**Comment by ehwinter** [comment]
While the above was described in the context of Windows CE, I have this same issue.  Win10 corporate install where an admin remoted in/installed Docker Desktop for me, then left. As the installer he was added as a member of docker-users, but not me. Perhaps this would be added as a prompt in the install or a closing note after install is complete?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
