### ISSUE TITLE
Outdated docker-machine release notes 

### ISSUE THREAD

**Issue by jamshid** [docker/docker.github.io#4871]
### Problem description

Outdated release notes seem to be on https://docs.docker.com/release-notes/docker-machine/ (0.10.0), newer ones on https://github.com/docker/machine/releases/ (0.12.2). 

### Project version(s) affected

docker-machine 0.12.2

### Suggestions for a fix

Would be good for release notes to be complete everywhere they're shown and to be available in one consistent place (across docker projects and flavors).

FWIW I prefer github.

**Comment by mstanleyjones** [comment]
@shin- I thought you were going to submit PRs for these? Did this slip through the cracks?

**Comment by gbarr01** [comment]
@mstanleyjones , would you confirm that this is done?

**Comment by mstanleyjones** [comment]
Yep! Should be published shortly.
