### ISSUE TITLE
some links within page do not work

### ISSUE THREAD

**Issue by kolyshkin** [docker/docker.github.io#4877]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/), CC @mstanleyjones 

While reading https://docs.docker.com/engine/reference/run/ I noticed that clicking on some links right under "Operator exclusive options" does not do anything. This happens with all the links that lead to a section with double dashes (e.g. "Name (–name)", "IPC settings (–ipc)", "Restart policies (–restart)"
and "Clean up (–rm)").

The problem is, the link destination have three dashes (for example: `<a href="#restart-policies---restart">`), while the anchor name only have 1 (example: `<h2 id="restart-policies-restart">`).

I guess this is caused by how jekyll (in fact kramdown) generates Ids for headers -- it seems that it strips out dashes from the contents of header (https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/base.rb#L248), while github markdown does not (https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb#L26).

Therefore, to fix this we need to patch kramdown. As this does not look realistic, here's a workaround -- for every header which contains dashes we need to create an ID ourselves. Something like this:

```md
<a id="restart-policies---restart"></a>
### Restart policies (--restart)
```

The only question is -- will it be stripped by Jekyll (kramdown) or not? I hope not.

**Comment by thaJeztah** [comment]
Oh, looks like a dup of https://github.com/docker/docker.github.io/issues/4178 (and also discovered that kramdown does not have this option configurable :disappointed:)

**Comment by kolyshkin** [comment]
@thaJeztah thanks a lot for pointing it out! I was actually totally wrong in my analysis that dashes are removed by kramdown when making IDs. They are not removed (at least in GFM, see https://github.com/gettalong/kramdown/blob/e9714d87e842831504503c7ed67f280873d98908/lib/kramdown/parser/gfm.rb#L103). The reason of double dash removal is it's changed to endash first, and then endash is removed. So, if double-dash to endash conversion can be disabled, IDs generated will be adequate.

Closing this one as just making intralinks working is not good enough.
