### ISSUE TITLE
Terminology mismatch with DTR GUI  2.3.2

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#4885]
Please clarify the different permission levels

In Docker Trusted Registry 2.3.2

- Organizational admin
  * The GUI have the terms: Org Members: members and org owner
-  Team admin ?
  * I cant find this term in the DTR UI
- Team admin ?
  Org owner ??

File: [datacenter/dtr/2.3/guides/admin/manage-users/permission-levels.md](https://docs.docker.com/datacenter/dtr/2.3/guides/admin/manage-users/permission-levels/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
We'll solve this one in the upstream repository, so that the fix becomes available in the next release.
