### ISSUE TITLE
The nav seems to be missing

### ISSUE THREAD

**Issue by hmackiernan** [docker/docker.github.io#4898]
File: [engine/userguide/index.md](https://docs.docker.com/engine/userguide/), CC @mstanleyjones 
This page "user guide" is linked to from the end of the 'tutorial' and promises to cover topics like storage, network, etc. From what I can see, there is no nav, toc or anything; just this very brief summary page.  Where can one actually find the user guide?

**Comment by mstanleyjones** [comment]
We are on it. CDN is updating still. Try shift+f5 to clear your cache.

**Comment by joaofnfernandes** [comment]
#4896 fixed this and that build is now live, so I'm closing this as resolved.
