### ISSUE TITLE
H3 or H2?

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#4901]
File: [datacenter/dtr/2.3/guides/user/manage-images/scan-images-for-vulnerabilities.md](https://docs.docker.com/datacenter/dtr/2.3/guides/user/manage-images/scan-images-for-vulnerabilities/), CC @joaofnfernandes 

Should the last heading "Where do I do next?" be changed from H3 to H2?

**Comment by joaofnfernandes** [comment]
Yes it should be an H2, and as a best practice headings should also not have question marks.
I've filed #4917 to fix that.
