### ISSUE TITLE
Docker swarm fails to release the volume in worker nodes.

### ISSUE THREAD

**Issue by vranganatha2** [docker/docker.github.io#4911]
### Problem description

I have a swarm cluster in which one is swarm manager and the other 2 are swarm nodes.

I am creating the swarm service with volume, it then creates the service with volume and all my service are running successfully.

Problem comes when releasing the service , when releasing the service it only releases the services and volume in the manager node. It releases the service in worker nodes but It fails to release the volumes in worker nodes.

Steps to reproduce the issue:
1.Create a Docker-swarm cluster with 1 manager and 2 nodes.
2.Using swarm command create a swarm service with volume with more than 3 replicas so that it create the service gets created in all the nodes.
3.Verify the service and volume in all the nodes, It would have been created successfully.
4.Release the service from the swarm manager

it only releases the services and volume in the manager node. It releases the service in worker nodes but **It fails to release the volumes in worker nodes.**
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

 when we release the service from swarm manager , we have to check for the associate worker nodes and we need to release the volumes associated to that particular volumes aswell.

**Comment by thaJeztah** [comment]
This repository is for the documentation only; I see you also reported this in https://github.com/moby/moby/issues/35179, so let me close the issue here
