### ISSUE TITLE
--env-file not referenced in docs

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [docker/docker.github.io#4913]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/), CC @mstanleyjones

The current docs for `docker run` seem to omit any mention of the `--env-file` option.

**Comment by thaJeztah** [comment]
It's documented in the `docker run` command line reference; https://docs.docker.com/engine/reference/commandline/run/#options

**Comment by johndmulhausen** [comment]
What @thaJeztah said. The "run" page you refer to is a recipe book for common `run` tasks, the command-line page is the exhaustive reference. :)
