### ISSUE TITLE
Can the archive please be updated with all past stable/test/edge versions of the vpc and no-vpc templates please?

### ISSUE THREAD

**Issue by webologics** [docker/docker.github.io#4920]
File: [docker-for-aws/archive.md](https://docs.docker.com/docker-for-aws/archive/), CC @johndmulhausen

~Also it seems some previous templates, i.e. https://editions-us-east-1.s3.amazonaws.com/aws/test/17.06.0/Docker-existing-vpc.tmpl for instance are no longer available~:  template in question is actually Docker-no-vpc.tmpl

It is useful to know the diff when upgrading a stack. Thanks

**Comment by FrenchBen** [comment]
@webologics What's the use case for having the old templates (aside from diff)? 
Shouldn't the release notes include more details instead?

The older templates may include out-dated versions that can cause issues in the deployment, it is preferred for only the latest stable/edge to be up there.

**Comment by webologics** [comment]
If the release notes (couldn't find them recently for the latest templates 1709) are there, great, but as a fallback I like to have the older templates. We customized the 1705 template to use internal subnets and redoing this after a few months without the original 1705 template was a bit cumbersome. Now that I found the templates by direct url I'm closing this.
