### ISSUE TITLE
Compose File docs do not provide Windows examples

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#4921]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01 

Many things like volumes have different syntax for volumes.  We should provide examples for Windows for compose.

/cc @friism @brandonroyal

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
