### ISSUE TITLE
No TOC

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#4935]
File: [docker-cloud/infrastructure/byoh.md](https://docs.docker.com/docker-cloud/infrastructure/byoh/), CC @londoncalling 

There's no TOC displayed in the right navigation tree on this page.

![no toc](https://user-images.githubusercontent.com/25146885/31532147-158ee05a-b01e-11e7-80cf-4f348eeebd27.jpg)

**Comment by scjane** [comment]
The following page has the same problem:

https://github.com/docker/docker.github.io/edit/master/docker-cloud/apps/index.md

**Comment by londoncalling** [comment]
The second page you mention is https://docs.docker.com/docker-cloud/apps/ on the site, and it doesn't display a right-side on-page TOC intentionally (we don't display an on-page TOC if there are one or zero headings on the page.

The other I've fixed per the referenced PR ^^ , along with other topics in that section that I thought had similar problems.

Thanks!
