### ISSUE TITLE
How do you map a port on running container?

### ISSUE THREAD

**Issue by Mararesliu** [docker/docker.github.io#4942]
On runnning container, want to export a port outside, Any ways can quick reach it ?
docker commit  and new a container is not a good idea in my stuation.
iptables seems can not take effect.

**Comment by Mararesliu** [comment]
thanks, any progress?

**Comment by mstanleyjones** [comment]
You can't change a port mapping on a running container, but you can stop the container and restart using the `-p host:container` flag or by using the correct directive in the Docker compose file. See https://docs.docker.com/compose/compose-file/#ports.

**Comment by Mararesliu** [comment]
@mstanleyjones 
docker stop container_id
docker start -p host:container container_id ?
It's not a legitimate command...

**Comment by mstanleyjones** [comment]
You're right, you'd run the `docker run` again:

```bash
docker run -d -p 4000:4000 --name mytest mistytest

docker container stop mytest

docker container start mytest # same port

docker container stop mytest

docker container run -p 4001:4000 mytest # Now mapping container port 4000 to host port 4001
```

**Comment by Mararesliu** [comment]
It can not run success, see follow
docker container run -p 3306:3306 some-mysql
Unable to find image 'some-mysql:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/some-mysql/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.

**Comment by bhavin192** [comment]
You need to specify image name correctly which is `mysql` not `some-mysql` 
So the command should be 
```
docker run -p 3306:3306 --name name_for_container mysql
```

`name_of_container` is just a name which you can give to the container so that it would be easy to run commands related to container like `docker exec`

**Comment by Mararesliu** [comment]
Thanks, but we talk about remaping port for a container, the "some-mysql" is that container which want to remaping port. docker run -p  would create a new container not modify the old one.
If can not be modified, all of the containers's relationship will be disabled, and I must to recreate some of them.
@bhavin192 @mstanleyjones

**Comment by mstanleyjones** [comment]
I will try to be more clear.

1.  `docker stop <running-container-name>`
2.  `docker run -p <new-port-mapping> <container-name-from-step-1`

**Comment by catmonkeylee** [comment]
@mistyhacks 
I run the command:
docker container stop mytest

then the container was gone.....
why, any idea?

**Comment by sadjunky** [comment]
Tried and tested.

- Stop your container using `docker stop <container-name/container-id>`.

- Edit `hostconfig.json` and `config.v2.json` files of the respective container by adding your port to `PortBindings` key and `ExposedPorts` key respectively.

- You'll require `sudo` access, or as `root` user. Then run `systemctl stop docker` and then run `systemctl start docker`.

- Finally start your container using `docker start <container-name/container-id>`.

**Comment by JonathanAlumbaugh** [comment]
Failing to find the `hostconfig.json` file on Mac, any ideas? Just looking to open a port on a container without creating a new one.

**Comment by sadjunky** [comment]
Make a search on your machine for hostconfig.json. You should find a file
in /var/lib/docker/containers/<container-id>

**Comment by sadjunky** [comment]
Make a search on your machine for `hostconfig.json`. You should find a file
in `/var/lib/docker/containers/<container-id>`.

**Comment by sadjunky** [comment]
@JonathanAlumbaugh Make a search on your machine for `hostconfig.json`. You should find a file
in `/var/lib/docker/containers/<container-id>`.

**Comment by wanglailai** [comment]
@sadjunky  In my case, `systemctl stop docker`  should be executed before edit `hostconfig.json` and  
`config.v2.json`; or the config files will be restored.

**Comment by sadjunky** [comment]
@wanglailai haven't tested, will check this out. Thanks for the heads up!

**Comment by sadjunky** [comment]
> @sadjunky In my case, `systemctl stop docker` should be executed before edit `hostconfig.json` and
> `config.v2.json`; or the config files will be restored.
Will check this out, thanks!

**Comment by sadjunky** [comment]
> @sadjunky In my case, `systemctl stop docker` should be executed before edit `hostconfig.json` and
> `config.v2.json`; or the config files will be restored.

Haven't checked, will try this out. Thanks for the heads up!

**Comment by browncrane** [comment]
> @sadjunky In my case, `systemctl stop docker` should be executed before edit `hostconfig.json` and
> `config.v2.json`; or the config files will be restored.

I edit the `hostconfig.json` before `systemctl stop docker` and it worked.
It's Ubuntu 18.04 x86_64 with 
```
docker --version
Docker version 18.09.5, build e8ff056
```

**Comment by Eyshika** [comment]
> Tried and tested.
> 
> * Stop your container using `docker stop <container-name/container-id>`.
> * Edit `hostconfig.json` and `config.v2.json` files of the respective container by adding your port to `PortBindings` key and `ExposedPorts` key respectively.
> * You'll require `sudo` access, or as `root` user. Then run `systemctl stop docker` and then run `systemctl start docker`.
> * Finally start your container using `docker start <container-name/container-id>`.

i guess its not ExposedPort inside config.v2.json rather its Ports

**Comment by bharatrbk** [comment]
how can I stop port of docker running container.

**Comment by geeksun** [comment]
Use dockerFile can solve this problem. More pls see the link:　https://bobcares.com/blog/docker-change-container-configuration/

**Comment by hjonin** [comment]
> @Eyshika 
> Also when i did `sudo service docker stop` it removed my docker :/

The same happened to me because I made a mistake (typo) in the configuration, it should probably be the same for you.

**Comment by HamaniKhalil** [comment]
> @JonathanAlumbaugh Make a search on your machine for `hostconfig.json`. You should find a file
> in `/var/lib/docker/containers/<container-id>`.

Can you give the location for Mac OSX please ? Thanks

**Comment by alexleekt** [comment]
@HamaniKhalil 
`docker run -v /var/lib/docker:/var/lib/docker ubuntu bash`
then `/var/lib/docker/containers/<container-id>` in the bash container that starts.

ref: https://github.com/moby/moby/issues/28283

**Comment by matfolio** [comment]
An alternative to the above option of exposing port on a running container from the host machine is to create an image from the container. Then run the newly created image with desired ports to create a container with the port bindings

`docker commit -m "msg" `docker -l -q` <your-container:version_number>`
The above code would create a new image tagged with the [version_number]
then:
`docker run -it --name <container_name> --hostname <container_name> <new_image>` 
The above command would create a container using the created image.
well the hostname option is not needed if your're running in detatched or daemon mode.

Note: Editing the container config files and stopping the docker for such modification might results into unwanted issues. I prefer this option rather than editing the config files.

**Comment by lemonaidrmeyers** [comment]
Is there a way to change ports without recreating the containers on a mac with docker-compose and a yml? It's very very time consuming to recreate all the networked dockers when you want to test port changes.
