### ISSUE TITLE
Link for GlusterFS Plugin points to a version that is no longer mantained

### ISSUE THREAD

**Issue by imaia** [docker/docker.github.io#4944]
Link for GlusterFS Plugin points to a version that is no longer maintained. See below:

https://docs.docker.com/engine/extend/legacy_plugins/#volume-plugins

Pointing to a maintained version would be better.

**Comment by mistyhacks** [comment]
This is a third-party plugin that is considered legacy (see the doc link) and we cannot guarantee that these links will be up to date. I don't even know where to look for the version of the plugin that Red Hat maintains. Whoever maintains this plugin should submit a PR to update the doc at https://github.com/docker/cli/blob/master/docs/extend/plugins_volume.md.

**Comment by italomaia** [comment]
Ok. If I may, where are the non-legacy volume plugins?

**Comment by mistyhacks** [comment]
Official plugins are basically images. See https://docs.docker.com/engine/extend/.
They aren't typically developed or maintained by Docker, and only distributed on Docker Hub or Docker Store if the plugin developer publishes them there. The plugin developer publishes the plugin on a registry (such as Docker Hub). For instance, the Weaveworks network plugin: https://hub.docker.com/r/weaveworks/plugin/

A quick search for `gluster plugin` on Docker Hub revealed https://hub.docker.com/r/sapk/plugin-gluster/ which specifically states that it is not official. You'd need to contact Red Hat to find out if they publish an official plugin and what registry it's on if so.

**Comment by mistyhacks** [comment]
You can actually search Docker Store for type `plugin`: https://store.docker.com/search?category=volume&q=&type=plugin
