### ISSUE TITLE
Please include info on how to not run docker locally

### ISSUE THREAD

**Issue by FlorianHeigl** [docker/docker.github.io#4971]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/), CC @gbarr01

Sorry but it's utterly irrelevant for me to have a local VM on my laptop for running docker.
I got plenty of real servers available, so all I'll use is docker-machine.

Having the local VM components around is no more than a waste of ram, diskspace and battery life.
I would love to know a way to use the normal docker distribution without wasting at least a gigabyte of ram for _nothing at all_. 

I _do_ understand the docs are meant to be friendly to beginners, but could you also think of people who are doing this outside of a startup with 5 AWS VMs?
Please, can you put some info in the docs how to run only what's needed and not waste energy on a VM up 24x7 that will _never_ be used... This makes me want to go back to homebrew, but the lack of API compatibility in docker/-swarm/-machine/-compose makes that quite a PITA too.

**Comment by BretFisher** [comment]
Are you asking how to just run the docker cli on your mac w/o a local engine/daemon, and point  your cli to a remote engine? 

Some info on various ways to securely connect here: https://docs.docker.com/engine/security/https/

If you don't want docker engine running locally, you can use brew which just installs docker cli.

Or maybe I'm misunderstanding.

**Comment by mstanleyjones** [comment]
You can also just install the static binaries: https://docs.docker.com/engine/installation/linux/docker-ce/binaries/#install-client-binaries-on-macos

That's a different product from Docker for Mac, hence why the docs for Docker for Mac don't mention it directly.
