### ISSUE TITLE
Prometheus in service task can't talk to host metrics via "localhost"

### ISSUE THREAD

**Issue by BretFisher** [docker/docker.github.io#4972]
File: [engine/admin/prometheus.md](https://docs.docker.com/engine/admin/prometheus/), CC @mstanleyjones

This docker engine metrics shows a [`prometheus.yml`](https://docs.docker.com/engine/admin/prometheus/#configure-and-run-prometheus) file that points to `localhost` for engine metrics on linux. However, from the prom container, it can't access host's localhost, only the containers localhost, and gets a `connection refused`.

Not sure the best way to get a swarm service to see the localhost IP of the engine.

**Comment by mstanleyjones** [comment]
Run with `--net=host` probably. That will bind the port on the Docker host directly. Can you give it a try and let me know?

**Comment by markk12** [comment]
passing --network=host 
container cannot be disconnected from host network or connected to host ne

**Comment by markk12** [comment]
it works just not as service. Boh too many parameters but i dont see the more important
node cpu,disk,memory,bandwidth usage

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by johnyserpa** [comment]
Sorry for reopening this, but documentation is wrong and should be corrected.
As previous people have said, you can only connect to the docker metrics through container's `localhost` if you use the `hosts` network, which doesn't look very doable in a production environment, IMO.

Could you provide the standard way to do this by fixing the documentation?

Thanks a lot!

**Comment by dhruvjain51** [comment]
On Mac/Windows you can use host.docker.internal to connect to localhost because --net=host only works on Linux. However, I completely agree with @johnyserpa. There has to be a standard way to implement this functionality in a production environment

**Comment by kunaldawn** [comment]
please update the docs. its not working!

**Comment by earezki** [comment]
Always not working!

**Comment by colomonkey** [comment]
What is the correct way of doing this in Docker Swarm mode?
