### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by RyanDur** [docker/docker.github.io#4973]
File: [engine/swarm/swarm-tutorial/inspect-service.md](https://docs.docker.com/engine/swarm/swarm-tutorial/inspect-service/), CC @mstanleyjones

**Comment by mstanleyjones** [comment]
What is your question exactly? I need a bit more context, please.

**Comment by mstanleyjones** [comment]
lack of info. Please reopen this or open a new one if you feel like adding more info.
