### ISSUE TITLE
No scale section in 2.2

### ISSUE THREAD

**Issue by gotcha** [docker/docker.github.io#4990]
### Problem description

The 2.2 section of `compose-versioning` links to a `scale` section that does not exist.

### Problem location

See https://github.com/docker/docker.github.io/commit/f6c5c41e2d2f8993a2d8a1cc3aba2fa08ebb406b#commitcomment-25004920

### Project version(s) affected

2.2

### Suggestions for a fix

Not sure enough about what `scale`does to propose a wording

**Comment by mstanleyjones** [comment]
`scale` is only relevant to swarm services, and version 3 of the Compose file format is required to use swarm services with Docker Compose or `docker stack` commands.

**Comment by gotcha** [comment]
@mstanleyjones You should fix compose-versioning so that it does NOT mention `scale` as it does now.

**Comment by gotcha** [comment]
@mistyhacks A fix was committed in https://github.com/docker/docker.github.io/commit/995db0819326fff00307788bddfd8949a3fe6451
