### ISSUE TITLE
Unsure what needs to be changed for filtering to work well.

### ISSUE THREAD

**Issue by BarnumD** [docker/docker.github.io#4996]
File: [engine/reference/commandline/image_prune.md](https://docs.docker.com/engine/reference/commandline/image_prune/), CC @mstanleyjones

Following this pattern:
`docker image pull ubuntu`
`docker image pull node`

#Lists only ubuntu image
`docker image ls --filter "reference:ubuntu"`

#Does not* remove only ubuntu image.
`docker image rm --filter "reference=ubuntu"`
`docker image prune --filter "reference=ubuntu" -f`

#Removes all images on the host regardless of --filter.
`docker image prune --filter "reference=ubuntu" -f -a`

It seems to me that --filter has been implemented in different ways in different places.  In some places it lists an image.  In other places it doesn't list it because it's not considered dangling.  When the -a flag is thrown it's completely ignored.  What I'm trying to do is remove or prune all images with the name 'ubuntu' without touching the rest of the images on the system but all I seem to be able to do is remove them all.

**Comment by mstanleyjones** [comment]
This is not really a docs question but a question about functionality. I am not sure whether this should be asked in `docker/cli` or `moby/moby`. @thaJeztah can you weigh in?

**Comment by thaJeztah** [comment]
The `docker image rm` command does not have a filter option, so providing a `--filter` would likely produce an error;

```
Usage:	docker image rm [OPTIONS] IMAGE [IMAGE...]

Remove one or more images

Aliases:
  rm, rmi, remove

Options:
  -f, --force      Force removal of the image
      --help       Print usage
      --no-prune   Do not delete untagged parents
```

For `docker image prune`, the only filters that are supported are (from the docs: https://docs.docker.com/engine/reference/commandline/image_prune/#filtering)

- `until`
- `label`


Both examples you provided should produce an error;

```bash
$ docker image rm --filter "reference=ubuntu"
unknown flag: --filter
See 'docker image rm --help'.

$ docker image prune --filter "reference=ubuntu" -f
Error response from daemon: Invalid filter 'reference'
```

If you want to remove a specific image, you can either remove it by name/tag or by ID, for example:

```bash
docker image rm ubuntu:latest
docker image rm ee1e10916283
```

You can also combine commands "linux style", for example, filter images on specific criteria, then use the results to the `docker image rm` command to perform the delete;

```bash
docker image rm $(docker image ls --filter reference=ubuntu -q)
```

**Comment by ssbarnea** [comment]
The lack of documentation on which filters are supported by each command is bit of a mindblowing. Why the CLI does not liste them when we use `--help`? This should have implemented from the day one when --filter option was added.

User can easily search online for allowed filters just to become more confused after finding examples like `--filter name=foo`, which do not work. 

Even the error code is made without any regards to use user, failing to mention which is the list of supported filters.
```
Error response from daemon: Invalid filter 'name'
```
