### ISSUE TITLE
Grammar fix, "device mode"

### ISSUE THREAD

**Issue by mtdeguzis** [docker/docker.github.io#4997]
File: [engine/userguide/storagedriver/device-mapper-driver.md](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/), CC @mstanleyjones  

Original:

"This host is running in loop-lvm node"

Change to:

This host is running in loop-lvm mode"

**Comment by johndmulhausen** [comment]
@mtdeguzis Why not click "Edit this page" on the top right and make this simple fix? :)

**Comment by mtdeguzis** [comment]
oh, well, when I clicked on request change. Should have hit edit page :) 
![image](https://user-images.githubusercontent.com/27829577/31718950-bbbeec58-b3df-11e7-8e53-b0bdd32c475f.png)

**Comment by mtdeguzis** [comment]
#5032

**Comment by bhavin192** [comment]
There was already one PR by me to fix this.

**Comment by mstanleyjones** [comment]
@bhavin192 Nobody will know to link them together unless you mention the GH issue in the PR like `Fixes #4997`. Please try to remember to do that in the future so there isn't duplicate work. Thanks!
