### ISSUE TITLE
404 at: https://docs.docker.com/docker-cloud/getting-started/link-azure/

### ISSUE THREAD

**Issue by drlukeangel** [docker/docker.github.io#50]
Links from setting up node providers
Link from host site:https://cloud.docker.com/app/btreepress/settings#container-node-providers
Link to dead site:https://docs.docker.com/docker-cloud/getting-started/link-azure/
![image](https://cloud.githubusercontent.com/assets/22433329/19104466/8160d8b4-8a91-11e6-8e8c-c430db62346a.png)

**Comment by drlukeangel** [comment]
should go here
https://docs.docker.com/docker-cloud/infrastructure/link-azure/

**Comment by sanscontext** [comment]
Thanks for the report. It looks like Jekyll doesn't have the redirect functionality we had in the previous system. I've got a PR in to the Cloud team to update those links in the UI.

**Comment by johndmulhausen** [comment]
Fixed in 9fd1c9ad27a5735046944623216481e5564abb78
