### ISSUE TITLE
Confusion between ports in ingress explanation

### ISSUE THREAD

**Issue by yogeek** [docker/docker.github.io#5013]
File: [datacenter/ucp/2.1/guides/admin/configure/use-domain-names-to-access-services.md](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/configure/use-domain-names-to-access-services/), CC @jimgalasyn

I think there is a confusion between the port mentionned in the sentence "Wordpress service is begin served on port 8080" and the port displayed in the schema which is the 8000.
Is it a typo ? If it is, it is the same in the other parapgraph too.

**Comment by JimGalasyn** [comment]
You're correct, it should be port 8000. This has been corrected in the [latest version](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/use-domain-names-to-access-services/) of the topic, and I'll go ahead and fix in the 2.1 version.

**Comment by yogeek** [comment]
Thank you for your quick reply. As I never done itt, I have not tried to edit the page directly but for next time, I will try to make a PR.

**Comment by JimGalasyn** [comment]
Great, we love community contributions!
