### ISSUE TITLE
Feedback for: compose/compose-file.md

### ISSUE THREAD

**Issue by knaperek** [docker/docker.github.io#502]
URL: [https://docs.docker.com/compose/compose-file/](https://docs.docker.com/compose/compose-file/#/cpushares-cpuquota-cpuset-domainname-hostname-ipc-macaddress-memlimit-memswaplimit-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir)

> Each of these is a single value, analogous to its [docker run](https://docs.docker.com/engine/reference/run/) counterpart.

The *docker run* reference page linked in the cited sentence does not contain any info about the `read_only` option.

**Comment by londoncalling** [comment]
@dnephin @shin- @ManoMarks @nathanleclaire @mstanleyjones 

Hi, Can someone take a quick look at @knaperek 's  question when you get a chance? 

There is info about `read-only` (not `read_only`) at [docker run in the Engine CLI reference](https://docs.docker.com/engine/reference/commandline/run/) under the [Options](https://docs.docker.com/engine/reference/commandline/run/#/options) index list at the top and under [mount-volume](https://docs.docker.com/engine/reference/commandline/run/#/mount-volume--v---read-only).

Should we reference this also or add info about `read-only` in the doc that's currently linked to ([docker run reference](https://docs.docker.com/engine/reference/run/)) under Docker Engine? 

It's a bit confusing how these two docs relate.

**Comment by londoncalling** [comment]
Closing this issue for now.
