### ISSUE TITLE
Incorrect statement about Windows images and scanning

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#5033]
File: [datacenter/dtr/2.3/guides/user/manage-images/scan-images-for-vulnerabilities.md](https://docs.docker.com/datacenter/dtr/2.3/guides/user/manage-images/scan-images-for-vulnerabilities/), CC @joaofnfernandes

This isn't correct:
> DTR scans both Linux and Windows images, but by default Docker doesn’t push image layers for Windows images so DTR won’t be able to scan them. If you want DTR to scan your Windows images, configure Docker to always push image layers.

Specifically "Docker doesn’t push image layers for Windows images".  It is the foreign layers it doesn't push.  This makes it sound like it is all layers.

**Comment by Yusadolat** [comment]
is @joaofnfernandes working on this?

**Comment by joaofnfernandes** [comment]
@Yusadolat I'm the owner of this, but I'm not proactively working on this issue. It's on the backlog and competing against other issues.
