### ISSUE TITLE
How to download plugin

### ISSUE THREAD

**Issue by Tiago-OP** [docker/docker.github.io#5034]
File: [docker-for-azure/persistent-data-volumes.md](https://docs.docker.com/docker-for-azure/persistent-data-volumes/), CC @johndmulhausen

Hello, I would like to know how to download and run the plugin.

Thank you ,

**Comment by mstanleyjones** [comment]
I believe Cloudstor is only supported when you are using the Docker for AWS or Docker for Azure templates. cc/ @friism for verification.

**Comment by friism** [comment]
That's correct
