### ISSUE TITLE
In mysql container  commit container data had not be saved.

### ISSUE THREAD

**Issue by Mararesliu** [docker/docker.github.io#5043]
I use mysql cntainer link by web site, On runing mysql i can see data has been saved on mysql container. but when i commit that mysql container, And run the images to create other container 
data can not found in it..

**Comment by bhavin192** [comment]
If you see the [`Dockerfile of mysql`](https://github.com/docker-library/mysql/blob/86431f073b3d2f963d21e33cb8943f0bdcdf143d/8.0/Dockerfile#L62) image, `VOLUME /var/lib/mysql` instruction creates a new volume when you run a container. 

As the data is not in the container, your data is not saved even if you commit the container. 

Read this https://docs.docker.com/engine/reference/builder/#volume

```
FROM ubuntu
RUN mkdir /myvol
RUN echo "hello world" > /myvol/greeting
VOLUME /myvol
```
> This Dockerfile results in an image that causes `docker run`, to create a new mount point at `/myvol` and copy the `greeting` file into the newly created volume.

**Comment by mstanleyjones** [comment]
This is 💯 correct, and also committing containers is not an appropriate way to preserve data in them. Please consider using volumes.

**Comment by Mararesliu** [comment]
ok, thanks.
