### ISSUE TITLE
Document installation steps for ppc64le

### ISSUE THREAD

**Issue by JimGalasyn** [docker/docker.github.io#5046]
@rogaha 

This will be supported on `17.06.2-ee5`.

[Get Docker EE for Ubuntu](https://docs.docker.com/engine/installation/linux/docker-ee/ubuntu/#os-requirements)

**Comment by rogaha** [comment]
thanks @JimGalasyn! ref. document: https://docs.google.com/spreadsheets/d/1ip_1zyHiRp3LqhvSMeQ-bR6sahypOJJqk9I0PKo1osw/edit#gid=448234370

**Comment by andrewhsu** [comment]
keep in mind ubuntu calls the architecture `ppc64el`: https://lists.debian.org/debian-powerpc/2014/08/msg00042.html

more reference: https://wiki.ubuntu.com/ppc64el

as opposed to redhat which calls the architecture `ppc64le` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/installation_guide/chap-download-red-hat-enterprise-linux

**Comment by johndmulhausen** [comment]
Closing per discussion with Jim and the merged PR.
