### ISSUE TITLE
Contradicting information

### ISSUE THREAD

**Issue by dolhuis** [docker/docker.github.io#5059]
File: [engine/reference/commandline/system_prune.md](https://docs.docker.com/engine/reference/commandline/system_prune/), CC @mstanleyjones

Hi there,

I noticed the --force option having the -f flag as well in the definition of options:

--force , -f |   | Do not prompt for confirmation

while in the body of the page the -f flag is being associated with the --filter option:

Filtering
The filtering flag (-f or --filter) format is of “key=value”. If there is more than one filter, then pass multiple flags (e.g., --filter "foo=bar" --filter "bif=baz")

**Comment by mstanleyjones** [comment]
Thanks, this is a mistake in the body of the text and I'll raise a PR to fix it. The PR needs to actually go into a different repo, `docker/cli`. When I raise it, it will add the link to this issue so you can follow along.
