### ISSUE TITLE
 Feedback for: engine/installation/linux/ubuntulinux.md, Storage driver and custom kernels.

### ISSUE THREAD

**Issue by DmitriyMV** [docker/docker.github.io#506]
### Problem description

Documentation should clarify what should I do when I use custom or updated Linux kernel. It's really hard to find kernel extensions (should I build them instead?) and hasn't found any info about AuFS on 4.7+ kernel. Maybe overlayFS usage should be preferred?

### Problem location

engine/installation/linux/ubuntulinux.md 

### Project version(s) affected

Docker 1.12

### Suggestions for a fix

Add a paragraph about using overlayFS instead of AuFS (at your own risk). Because Ubuntu now runs on systemd, it would also benefit to add info about how to change the default storage driver in startup configs. I used [this](http://ciplogic.com/index.php/blog/109-docker-with-overlayfs-on-ubuntu-16-04-lts) as a quick and dirty solution, but I suppose it will do?

This topic cost me 3 hours during installation. While it's not a priority and I was able to figure out the solution eventually, it would be great if others didn't have too. I open to suggestions 😊.

**Comment by mstanleyjones** [comment]
@stevvooe can you help with the technical details of this?

**Comment by stevvooe** [comment]
Overlay or Overlay2 would be a better default, but I don't have much experience with changing this with systemd. That link (http://ciplogic.com/index.php/blog/109-docker-with-overlayfs-on-ubuntu-16-04-lts) seems reasonable, but we should have review from someone else.

@cpuguy83 @jpetazzo PTAL

**Comment by cpuguy83** [comment]
We have an article on configuring systemd -- https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options

But really this should not be suggested.
Docker has a non-distro specific location for configuration, which is `/etc/docker/daemon.json`. Using this file also has the benefit that many config options can be reloaded without restarting docker.
This is documented here: https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

In 1.13 we have already promoted overlay and overlay2 above devicemapper.
I don't see a problem recommending them, but there's some caveats:

- `overlay` uses lots of inodes and can cause inode exhaustion even though there is plenty free space
- `overlay2` requires a kernel >= 4.0, or a kernel with the neccessary backported patches.

**Comment by mstanleyjones** [comment]
All of that content has been moved out of the installation topic because it is not distro-specific. We have https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/ which is linked to from https://docs.docker.com/engine/installation/linux/linux-postinstall/#/use-a-different-storage-engine.
