### ISSUE TITLE
Documentation: missing scale parameter

### ISSUE THREAD

**Issue by gustavopaes** [docker/docker.github.io#5060]
### Problem description
There is no documentation about the new "scale" parameter at compose file doc page.

### Problem location

Compose file v2:
https://docs.docker.com/compose/compose-file/compose-file-v2/

And the link to "scale" parameter at changelog is broken:
https://docs.docker.com/compose/compose-file/compose-versioning/#version-22

**Comment by mstanleyjones** [comment]
cc/ @shin-
