### ISSUE TITLE
Feedback for: engine/reference/commandline/stop.md

### ISSUE THREAD

**Issue by ddingel** [docker/docker.github.io#507]
URL: [https://docs.docker.com/engine/reference/commandline/stop.md](https://docs.docker.com/engine/reference/commandline/stop/)

This should also mention `docker run --signal-stop`, shouldn't it?

**Comment by mstanleyjones** [comment]
No, because the command-line references are for specific commands. This reference is for `docker stop`. There is another reference for [`docker run`](https://docs.docker.com/engine/reference/commandline/run/). which does mention `--stop-signal`. Hope that helps!

**Comment by ddingel** [comment]
I am somehow puzzled will `docker stop` send always SIGTERM and a SIGKILL if necessary.
Like the website does mention it:
> The main process inside the container will receive SIGTERM, and after a grace period, SIGKILL.

 or will it send the signal given on `docker run --stop-signal`?
