### ISSUE TITLE
Images hard to read on night mode

### ISSUE THREAD

**Issue by amakarewycz** [docker/docker.github.io#5072]
File: [machine/overview.md](https://docs.docker.com/machine/overview/), CC @gbarr01

The images on this page have text which is difficult to read when selecting night mode.

**Comment by joaofnfernandes** [comment]
It seems that the images have a transparent background. Exporting the images with a white background should do the trick.

**Comment by arush-sal** [comment]
@joaofnfernandes I would its still looks pretty messed up, the white background doesn't seem to be of much help.
