### ISSUE TITLE
fix images

### ISSUE THREAD

**Issue by amakarewycz** [docker/docker.github.io#5073]
File: [machine/overview.md](https://docs.docker.com/machine/overview/), CC @gbarr01

The images on this page have text which is difficult to read when selecting night mode.

![screen shot 2017-10-21 at 6 43 36 pm](https://user-images.githubusercontent.com/1903319/31857296-dcdbe668-b68f-11e7-986e-67400051087d.png)

**Comment by joaofnfernandes** [comment]
I'm closing this as a duplicate of #5072
