### ISSUE TITLE
Missing permission

### ISSUE THREAD

**Issue by onedotover** [docker/docker.github.io#5076]
File: [docker-for-aws/iam-permissions.md](https://docs.docker.com/docker-for-aws/iam-permissions/), CC @johndmulhausen

Docker Cloud fails to create a new Node Cluster with these permission. It fails trying to modify the subnet. It needs this permission added to the policy to work: ec2:ModifySubnetAttribute

**Comment by joaofnfernandes** [comment]
@FrenchBen can you take a look into this?

**Comment by FrenchBen** [comment]
@onedotover Why would it need to modify the subnet, if it's creating it in the first place?
Can you share what you clicked on?

**Comment by onedotover** [comment]
All I did was launch a new Node Cluster using AWS form the website. When runs, there are several calls to ModifySubnetAttribute. Here is an example:
```
{
    "eventVersion": "1.05",
    "userIdentity": {
...
    },
    "eventTime": "2017-10-22T21:33:05Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "ModifySubnetAttribute",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "52.204.105.43",
    "userAgent": "Boto/2.45.0 Python/2.7.12 Linux/4.4.0-67-generic",
    "requestParameters": {
        "subnetId": "subnet-fd10729b",
        "mapPublicIpOnLaunch": {
            "value": true
        }
    },
    "responseElements": {
        "_return": true
    },
    "requestID": "e9caec76-1036-40f2-b7cd-9502b0ccdabc",
    "eventID": "2101936b-9afa-4b3a-85df-e3cc646906df",
    "eventType": "AwsApiCall",
}
```
Here is a screenshot of the CloudTrail events from one of my deployments (this is after I added the permission). Let me know if there's anything else I can provide.

![screen shot 2017-10-24 at 1 09 04 pm](https://user-images.githubusercontent.com/218888/31965619-bfb6ca88-b8bc-11e7-897e-06eb8f48feea.png)

**Comment by FrenchBen** [comment]
Interesting, I didn't see those perms before - I'll update the docs to reflect the need for those permissions.
