### ISSUE TITLE
Missing docs for new update_config order option

### ISSUE THREAD

**Issue by hairyhenderson** [docker/docker.github.io#5088]
### Problem description

In Docker 17.09, support was added for a new `order` option in the `update_config` section in the Docker Compose v3.4 file.

See https://github.com/docker/cli/pull/360 for details.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/compose/compose-file/#update_config

**Comment by hairyhenderson** [comment]
Here's a fix for this: https://github.com/docker/docker.github.io/pull/5089

**Comment by londoncalling** [comment]
@shin- @gbarr01 I'm working on a contribution to @hairyhenderson PR, but as I look at it more closely, we need to add the following:

- add a section in [about versions and upgrading](https://docs.docker.com/compose/compose-file/compose-versioning/#version-33) under `Versioning` about `Version 3.4` (I'm doing this now)

- add examples and mention of all the new `v3.4` supported parameters to their associated topics in the [Compose file reference](https://docs.docker.com/compose/compose-file/).

**Comment by shin-** [comment]
Version 3.4 was introduced in Docker Engine 17.09.0, but it hasn't made it yet in a Compose release. Those changes would have ideally been made at that time by whoever is responsible for documenting Engine features.

I did have a versioning section written out and ready to go in `vnext-compose` for when we release Compose 1.17.0 (https://github.com/docker/docker.github.io/pull/5019), as well as documentation for extension fields.
- For the fields in the `build` section, they're no-ops with `docker stack` (it ignores the `build` section entirely), but they should be documented in the [v2 reference](https://docs.docker.com/compose/compose-file/compose-file-v2/#build) and examples can probably be copied over.
- Volume name is also documented in the [v2 reference](https://docs.docker.com/compose/compose-file/compose-file-v2/#name).

**Comment by mstanleyjones** [comment]
Oh no, maybe I should revert that merge....

**Comment by hairyhenderson** [comment]
@mstanleyjones since the fix has been reverted, can this bug be reopened? It's _not ideal_ that the option remains undocumented for Swarm users...

**Comment by mstanleyjones** [comment]
It is documented in the `vnext-compose` branch, which will be merged with `master` when Compose is released. cc/ @shin- in case I am misunderstanding.

**Comment by hairyhenderson** [comment]
Ok, just to be clear, I didn't run into the lack of documentation while using `docker-compose`, but while using `docker stack deploy`.

In fact, `docker-compose` doesn't even support the `deploy` section, and logs the following when it encounters it:

```console
$ docker-compose up
...
WARNING: Some services (foo, bar) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
...
```

**Comment by mstanleyjones** [comment]
OK, I am confused about where this content should live. @londoncalling @shin- PTAL and advise.

**Comment by londoncalling** [comment]
@hairyhenderson that is correct, `docker-compose` does not support the `deploy` key as detailed here: https://docs.docker.com/compose/compose-file/#deploy

@mstanleyjones the information should still live at https://docs.docker.com/compose/compose-file/#update_config, which is a sub=topic of the parameters for the `deploy` key.
