### ISSUE TITLE
Need access rights to set reviewers to PR when updating doc for Docker For Mac / Windows releases

### ISSUE THREAD

**Issue by gtardif** [docker/docker.github.io#5094]
When creating PR to update release notes during the Docker For Mac / Windows releases, I can't set reviewers to notify @mstanleyjones & @gbarr01 about these release notes PR.
(I can create the PR but not set reviewers)

Is it possible to add access rights to users @pinata-mac, @gtardif, @ebriney ?
Thx

**Comment by johndmulhausen** [comment]
@gtardif Couldn't cc'ing the people you'd like to see as reviewers work? The perms get sloppy if we start adding non-team members to the maintainers group

**Comment by johndmulhausen** [comment]
Closing; I don't think we want this many Docs maintainers. Please just `@` people you want to look at things.

**Comment by gtardif** [comment]
Yep I'll do this, thx
