### ISSUE TITLE
How to get replica ID for DTR replicas

### ISSUE THREAD

**Issue by bkauf** [docker/docker.github.io#5095]
File: [datacenter/dtr/2.2/guides/admin/backups-and-disaster-recovery.md](https://docs.docker.com/datacenter/dtr/2.2/guides/admin/backups-and-disaster-recovery/), CC @joaofnfernandes 

How do you get the replica ID? Documentation needs to be clearer.  I get it by excluding the existing-replica-id tag and running through the backup and failing where it prompts me with the  replica ID. I then put that in the script and run the whole command as listed. This is not a smooth process.

**Comment by martencassel** [comment]
<code>
REPLICA_ID=`docker ps --filter name=dtr- | awk '{print $NF}' | sed 's/dtr-\(.*\)-//g' | grep -vi names | head -n1`
</code>

Tested on DTR 2.3.2

**Comment by bkauf** [comment]
I'm a little confused on why you even need the replica ID. You'll run the backup directly on a node, why not just default to the DTR instance running on that node?
