### ISSUE TITLE
404 at: https://docs.docker.com/sorry/#https://docs.docker.com/articles/https/

### ISSUE THREAD

**Issue by drlukeangel** [docker/docker.github.io#51]
Incoming Link from Azure Docker on Ubuntu Server compute server.
https://docs.docker.com/sorry/#https://docs.docker.com/articles/https/
Can not find the documentation  Running Docker with https to configure Docker to be reachable via the network in a safe manner linked via azure.
![image](https://cloud.githubusercontent.com/assets/22433329/19104606/75279122-8a92-11e6-9be4-651a42e4d81b.png)

**Comment by johndmulhausen** [comment]
Fixed in 5389e6cb122077d705692dec43555bc7a74ea5e0
