### ISSUE TITLE
title rendering regression

### ISSUE THREAD

**Issue by gdevillele** [docker/docker.github.io#510]
### Problem description

All titles used to have an anchor link attached to them, so that users can share links to a particular section of a page.
Now, a lot of titles are missing that anchor link.

This is a lack of consistency in those pages,
and those anchor links are now broken for the people who used them in their articles and tweets.

### Problem location

Most pages.

### Project version(s) affected

Current stable.

### Suggestions for a fix

Render all titles with the same method to ensure consistency now and in the future.

### Screenshots

Then:

![screen shot 2016-11-09 at 2 36 07 pm](https://cloud.githubusercontent.com/assets/939999/20157537/6fa8c504-a68a-11e6-91e2-1d0bdd190834.png)

And now:

![screen shot 2016-11-09 at 2 36 16 pm](https://cloud.githubusercontent.com/assets/939999/20157541/7446412c-a68a-11e6-9998-dd3848da3c7a.png)

**Comment by mstanleyjones** [comment]
I don't think it's a benefit since it would just take people to the top of the page anyway. Properly it should just link to `#`. They get the same benefit by just copying the link from their browser tab. Probably we should suppress them all instead of making them consistent? Or if they really really are visually appealing just hard-link them to `#`.

**Comment by johndmulhausen** [comment]
Agreed. Closing as WNF.

**Comment by gdevillele** [comment]
I agree with you @mstanleyjones but no matter what solution is chosen, I think this inconsistence should not remain.

You gave 2 possible solutions:
```
Probably we should suppress them all instead of making them consistent? Or if they really really are visually appealing just hard-link them to #.
```
From those two, I would personally go with the second one, as it would be bad to remove the other anchor links people have been using already (and those links are not taking you to the top of the page)

It's not about being visually appealing, it's about consistence in the page. Anchor links can be invisible, but they should remain IMO.

WDYT?

**Comment by johndmulhausen** [comment]
It's likely that all you have to do is use Liquid to generate an ID and assign it to the <h1> in docs.html and JS will do the rest, so if you'd like to send a PR that fixes this, be my guess, but I personally have higher priority things to take care of than enforcing consistency fixes that don't benefit users.
