### ISSUE TITLE
generic driver returns errors from Linux boxes

### ISSUE THREAD

**Issue by pathmav** [docker/docker.github.io#5102]
File: [machine/drivers/generic.md](https://docs.docker.com/machine/drivers/generic/), CC @gbarr01

On RHEL, only Docker EE is supported, so this will fail to install docker-ce

On OSX installed "Docker for Mac" then ran  "docker-machine  create --driver generic ......  " which
tries to run via ssh onto a Linux box "/usr/bin/docker daemon ....." which returns an error message
from the linux host:

On Centos,Ubuntu I get "docker daemon" is not supported on Linux. Please run "dockerd" directly.

**Comment by mstanleyjones** [comment]
cc/ @shin- PTAL

**Comment by shin-** [comment]
- Machine is not intended to be used with Docker EE, so it stands to reason that it wouldn't work with RHEL
- From that message, I'm fairly certain you're using an outdated version of Machine. Please upgrade to 0.13.0.
