### ISSUE TITLE
 Specify how much of the available CPU resources a container can use

### ISSUE THREAD

**Issue by nayanajith** [docker/docker.github.io#5106]
File: [engine/admin/resource_constraints.md](https://docs.docker.com/engine/admin/resource_constraints/), CC @mstanleyjones 

--cpus=<value> | Specify how much of the available CPU resources a container can use. For instance, if the host machine has two CPUs and you set --cpus="1.5", the container will be guaranteed to be able to access at most one and a half of the CPUs. This is the equivalent of setting --cpu-period="100000" and --cpu-quota="150000". Available in Docker 1.13 and higher.

Should it read as follow?:
--cpu-period="200000"

**Comment by mstanleyjones** [comment]
I think it is correct as written. @cpuguy83 PTAL

**Comment by cpuguy83** [comment]
Looks correct.
