### ISSUE TITLE
Make it easier for an admin to download the zip file and get the correct version.

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#5110]
To be able to install on an air-gapped system the admin use the manual instruction downloading to a PC then uploading the zip to the server.

To make it easier to keep track of downloaded files, i suggest you name the downloaded file as below and not just docker.zip (there could be previous version on the local pc).
The below snippet downloads the zip to the TEMP directory and not the current working directory. 

On an online machine, download the zip file.
PS> Invoke-WebRequest https://download.docker.com/components/engine/windows-server/17.06/docker-17.06.2-ee-4.zip -OutFile "$env:TEMP\docker-17.06.2-ee-4.zip" -UseBasicParsing

Do you have a latest URL pointing to the Latest Docker EE release ?

**Comment by vladandrei51** [comment]
Nah bruh, all good

**Comment by friism** [comment]
@martencassel why are you not using the DockerProvider for installation? https://docs.docker.com/engine/installation/windows/docker-ee/#install-docker-ee
