### ISSUE TITLE
Document --network=container:<name|id>

### ISSUE THREAD

**Issue by JakobGreen** [docker/docker.github.io#5116]
File: [engine/userguide/networking/index.md](https://docs.docker.com/engine/userguide/networking/), CC @mstanleyjones 

There is no longer any documentation on using "--network=container:<name|id>" when creating/running a container. This was documented in the past (1.8 I believe).

**Comment by joaofnfernandes** [comment]
In 1.9 docs we had this about `--net=container:<name|Id>` ([source](https://github.com/moby/moby/blob/v1.9.0/docs/reference/run.md#network-settings))

> #### Network: container
>
>With the network set to `container` a container will share the
>network stack of another container.  The other container's name must be
> provided in the format of `--net container:<name|id>`. Note that `--add-host`
> `--hostname` `--dns` `--dns-search` `--dns-opt` and `--mac-address` are
> invalid in `container` netmode, and `--publish` `--publish-all` `--expose` are
> also invalid in `container` netmode.
>
>Example running a Redis container with Redis binding to `localhost` then
>running the `redis-cli` command and connecting to the Redis server over the
>`localhost` interface.
>
>   $ docker run -d --name redis example/redis --bind 127.0.0.1
>    $ # use the redis container's network stack to access localhost
>   $ docker run --rm -it --net container:redis example/redis-cli -h 127.0.0.1

I don't see any mention in the release notes about this feature being deprecated, and I was able to use it on a `17.09.0-ce` engine, so I'm guessing we lost the docs during some migration?
Can you confirm that this feature was not deprecated @thaJeztah

**Comment by joaofnfernandes** [comment]
After researching this a bit more, the content is [still available in the docker run reference](https://docs.docker.com/engine/reference/run/#network-container), so for that I'm closing this issue.

@JakobGreen let me know if you don't agree.
