### ISSUE TITLE
Get rid of all of the `<DOCKER-EE-URL>` references and just use an exported environment variable

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#5126]
File: [engine/installation/linux/docker-ee/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ee/ubuntu/), CC @mstanleyjones 

This was done for RHEL but not Ubuntu
https://github.com/docker/docker.github.io/issues/4654

**Comment by mistyhacks** [comment]
I did this and didn't remember that this issue was here to tag it! 🎉
