### ISSUE TITLE
Instructions on how to add post data to a webhook

### ISSUE THREAD

**Issue by pietschy** [docker/docker.github.io#5134]
File: [docker-hub/webhooks.md](https://docs.docker.com/docker-hub/webhooks/), CC @johndmulhausen

This is my first attempt at configuring a webhook and I can't see how you actually specify the post data.  It's mentioned in the docs but there's no field for it in the UI.  Can an example be included in the docs?

**Comment by joaofnfernandes** [comment]
I think the docs are kind of misleading because I can't configure the POST payload. Docker Hub will always POST a request with the same content.
