### ISSUE TITLE
links instruction to be deprecated in compose doc

### ISSUE THREAD

**Issue by abualy** [docker/docker.github.io#5137]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01 
Hello. i  think that you need to mention that `link` instruction is deprecated since it is already mentionned in docker networking documentation 
https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

**Comment by gbarr01** [comment]
Note to self: 
https://docs.docker.com/engine/userguide/networking/work-with-networks/#link-containers-without-using-user-defined-networks
