### ISSUE TITLE
Indicate that credentials are *not* passed through registry mirrors

### ISSUE THREAD

**Issue by jpetazzo** [docker/docker.github.io#5139]
File: [registry/recipes/mirror.md](https://docs.docker.com/registry/recipes/mirror/), CC @joaofnfernandes

@nickstenning pointed out [in the following thread](https://github.com/docker/hub-feedback/issues/1225#issuecomment-339949748) that the registry mirror documentation didn't indicate how registry mirrors handled pulls of private images. I did a little experiment (details in the linked issue) confirming that credentials were not passed to the upstream registry, but that the Engine would gracefully fallback to upstream in that case, making it transparent to the user (except when the Engine's connection to the Docker Hub is impaired). I think we should update the docs to mention that, _or_ perhaps link to the appropriate document (maybe the Engine docs have more details?)

Thank you!

**Comment by gesellix** [comment]
In other words: the current implementation of the registry mirror is useless for private repositories?

**Comment by joaofnfernandes** [comment]
@aaronlehmann or @stevvooe, can you clarify how authentication is handled when a user tries to pull from a registry cache?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
