### ISSUE TITLE
DTR Health Check Organization

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#5141]
### Problem description

> (*) observation
> (+) good
> (-) could be improved

DTR health checking docs are currently in two different places:

[Monitor and Troubleshoot](https://docs.docker.com/datacenter/dtr/2.3/guides/admin/monitor-and-troubleshoot/#health-checks)
(*) coverage: undecorated list of all three endpoints (including `nginx_status`)
(-) no explanation or link to explanation of how to interpret results.
(-) does not call out the need to authenticate in order to access `cluster_status`

[Use a Load Balancer](https://docs.docker.com/datacenter/dtr/2.3/guides/admin/configure/use-a-load-balancer/#health-check-endpoints)
(*) coverage: `_ping` and `cluster_status` endpoints
(+) provides good detail on the endpoints it does document (including how to interpret)
(+) documents need to authenticate to `cluster_status`
(-) does not indicate _how_ to authenticate to `cluster_status`
(-) documents `cluster_status` in great depth, then subsequently advises not using this endpoint for load balancing

### Problem location
https://docs.docker.com/datacenter/dtr/2.3/guides/admin/monitor-and-troubleshoot/#health-checks
https://docs.docker.com/datacenter/dtr/2.3/guides/admin/configure/use-a-load-balancer/#health-check-endpoints

### Project version(s) affected
DTR 2.3.4

### Suggestions for a fix
1. List all endpoints in both load balancing and troubleshooting sections, continuing to be prescriptive in load balancing about which are most appropriate for that use case.
2. Locate the long-form explanation for each endpoint where it is most likely to be used. Keep explanation for _ping in load balancing and move cluster_status explanation to troubleshooting.
3. cross-link to long-form explanations
4. "operationalize" endpoints in the troubleshooting section by providing copy-pastable examples with `curl`.  this would be especially valuable in the context of `cluster_health`, since it requires auth. (cc https://github.com/docker/docker.github.io/issues/2470)
5. Refer troubleshooting coverage of `cluster_status` to [rethinkcli](https://deploy-preview-4791--docker-docs.netlify.com/datacenter/dtr/2.2/guides/admin/monitor-and-troubleshoot/troubleshoot-with-logs/#access-rethinkdb-directly) for cases when `cluster_status` returns error 500 instead of diagnostically useful information, such as when dtr-rethinkdb is inquorate on the underlying replica.

**Comment by joaofnfernandes** [comment]
We'll fix this one upstream so that the fix becomes available in the next release.
