### ISSUE TITLE
Docker cli command for support has container in it. Please remove container from docker run.

### ISSUE THREAD

**Issue by avikatgithub** [docker/docker.github.io#5143]
File: [datacenter/ucp/2.2/guides/get-support.md](https://docs.docker.com/datacenter/ucp/2.2/guides/get-support/), CC @jimgalasyn

**Comment by joaofnfernandes** [comment]
`docker container run` and `docker run` can be used interchangeably. We favor `docker container run` since it's more verbose and easier for new Docker users.
