### ISSUE TITLE
Import Play With Docker under "Samples"

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#5146]
Write JS that populates a table that links out to http://training.play-with-docker.com/feed.xml

JS just needs to consume this:
http://training.play-with-docker.com/feed.xml

GH Source:
https://github.com/play-with-docker/play-with-docker.github.io

Should replace the "Tutorial Labs" table.

**Comment by joaofnfernandes** [comment]
I think this got dropped, so I'm closing this issue. We can open a new one if this becomes relevant again.
