### ISSUE TITLE
Special note for windows [7?] users when Docker launches from 'Quickstart Terminal'

### ISSUE THREAD

**Issue by nagstaku** [docker/docker.github.io#5161]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen 

In the section "Run the app" it states:

> You should see a notice that Python is serving your app at http://0.0.0.0:80. But that message is coming from inside the container, which doesn’t know you mapped port 80 of that container to 4000, making the correct URL http://localhost:4000.

This however wasn't working; I installed Docker today on Windows 7 via the Toolbox and started these tutorials. I gave my system a restart just in case, and then I noticed the startup message I get from running "Docker Quickstart Terminal" states:

`docker is configured to use the default machine with IP 192.168.99.100`

A ha! I tried running http://192.168.99.100:4000 in my browser and I did get the expected result. Maybe one of those quote blocks that say 'Note: ' and something about the above possible catch would be awesome for newbies like myself. 

Big thanks!

**Comment by nagstaku** [comment]
well, i went back and tried to 'edit this page' and created a pull request, but now I can't seem to find the pull request to link it. Anyway; hopefully it's in limbo and you can find it to save yourself some time.

**Comment by joaofnfernandes** [comment]
@nagstaku are you sure you started the pull request? I can't seem to find anything from you :(
https://github.com/docker/docker.github.io/pulls/nagstaku

**Comment by johndmulhausen** [comment]
Hm, what version of Docker for Windows are you running? I could have sworn the included VM would consider `localhost`/`0.0.0.0` to be the host. And 192.168.99.100 was what `docker-machine ip default` would return back in the days before our pack-in VM. Also the "Quickstart Terminal" rings a bell as an oldschool thing and I'm not seeing it in my Windows installation. 

As noted in the tutorial, a recent Docker is a prerequisite. Start here: https://docs.docker.com/docker-for-windows/install/

**Comment by nagstaku** [comment]
So, after doing the tutorial on my newer machine, I believe the above happened as a result of running it on Windows 7 and having to install the Docker Toolbox in order to use Docker.

This is the terminal option I'm given on the Win7 machine, i think it's required to run docker:
![image](https://user-images.githubusercontent.com/6393689/32287113-f75850a2-beec-11e7-883e-ea02cbd24831.png)

and this image represents when I run it, and the IP I mention above.
![image](https://user-images.githubusercontent.com/6393689/32287158-1cd5aa8c-beed-11e7-93be-56c63f42f503.png)

@joaofnfernandes  I'll make another pull request tonight with suggestions for anyone running Docker Toolbox as the entire tutorial still worked fine.
