### ISSUE TITLE
FR: Code snippets pop up in less constrained modal window

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#5169]
Feature request: Since docker CLI spits out some pretty wide output, it would be nice if code snippets could be "popped out" into a modal popup that takes up the whole viewport width and was easily closeable (click outside, click X, hit ESC). 

At Kubernetes I used Sweet Alert for this and it was fairly easy/pretty. 

https://limonte.github.io/sweetalert2/

**Comment by akimd** [comment]
A good example is: https://docs.docker.com/engine/reference/commandline/stack_ps/ which trunks (visually) the result of the commands:
<img width="2490" alt="capture d ecran 2017-10-27 a 16 25 36" src="https://user-images.githubusercontent.com/232441/32213122-47a0d9a4-be1a-11e7-92ca-eee1c2e50bd8.png">

**Comment by akimd** [comment]
FWIW, my own desire is to be able to read the whole output without having to click on anything.  I have a wide screen, and I'd like to benefit from it to see the output of the commands exactly as is the case with my terminal.  I am not asking for any kind of change for the text body (which is wrapped), I am asking for the raw output of commands to use the whole width of my screen.

IMHO, it should be the default, and should not require any mouse action and pop-up.

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io//

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
