### ISSUE TITLE
Move CLI generation to Dockerfile, take YAML out of repo

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#5173]
Populate YAML generation output to: 

https://github.com/docker/docker.github.io/tree/master/_data/engine-cli

and 

https://github.com/docker/docker.github.io/tree/master/_data/engine-cli-edge

This will save a fair amount of build time.

**Comment by johndmulhausen** [comment]
cc @mistyhacks

**Comment by mistyhacks** [comment]
I'll do it but I'm not sure it will save build time. We'll see...

**Comment by mistyhacks** [comment]
We can't actually do this as part of our build, for technical reasons. However, if https://github.com/docker/release-packaging/issues/79 happens, we can use those artifacts as part of our build and get to the same place. cc/ @seemethere
