### ISSUE TITLE
No info on how to use docker-machine behind proxy

### ISSUE THREAD

**Issue by LawnboyMax** [docker/docker.github.io#5179]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen

I think it would be worth mentioning how to use `docker-machine` behind proxy. This would be consistent with the mention of proxy settings for `docker` in part 2.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
