### ISSUE TITLE
sync_schedule format

### ISSUE THREAD

**Issue by DockerBelfast** [docker/docker.github.io#5186]
File: [datacenter/ucp/2.2/guides/admin/configure/external-auth/enable-ldap-config-file.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/external-auth/enable-ldap-config-file/), CC @JimGalasyn 

UCP Web GUI takes an (hourly) integer format but sync_schedule is in CRON format. So the toml functionality is not working yet and breaks if you follow these steps and update the service!!

**Comment by joaofnfernandes** [comment]
Here's the testing scenario I used to validate if there's any product issues:

1. Integrate with LDAP and set the sync interval to 6 hours,
2. Check what was persisted in the UCP config file to make sure it matches what I chose in step 1.

After I do that, the value that's stored on the UCP config file is:

```
  [auth.ldap]
  sync_schedule = "0 0 */6 * *"
```

Given that the format used for this field needs to be:

```
 0 (minutes) (hours) (day of month) (month of year) (day of week, optional)
```

So everything seems to be OK. I also tried to set the UI with values that might trigger edge cases like `25 hours` or `48 hours`, and everything seems OK.

For this reason I'm closing this as a non-issue, but feel free to comment @DockerBelfast and let me know if you are seeing something different.

---

Here's the complete documentation for the `sync_schedule` field, that you can get by running
`docker run -it docker/ucp:2.2.4 example-config`.

```
# The scheduled time for automatic LDAP sync jobs. Can be specified in CRON
# table entry format (with a seconds field always set to 0):
#
#   0 (minutes) (hours) (day of month) (month of year) (day of week, optional)
#
# Can also be specified as a predefined scheduling definition: '@hourly',
# '@daily', or '@weekly'.
# Default is '@hourly' if empty or omitted.
```
