### ISSUE TITLE
Confused for a second about nodes' probable roles in a swarm

### ISSUE THREAD

**Issue by soletan** [docker/docker.github.io#5187]
File: [engine/swarm/key-concepts.md](https://docs.docker.com/engine/swarm/key-concepts/), CC @mstanleyjones

Reading this

> Docker daemons can participate in a swarm as managers, workers, or both.

I got confused for a second whether I'll have to make a manager node join the same swarm as worker as well to get it perform in both roles. It's far more plausible to see managers implicitly become workers as well, but that's slightly different from this statement. Who's wrong: me or the statement?

**Comment by joaofnfernandes** [comment]
@soletan I think this one got lost in the middle of all other issues. I'll close this issue but feel free to open a pull request to the docs if you think they can be improved.

Basically you can join nodes to a swarm. When joining a node you define if you want that node to be a manager (replicates the swarm state), or worker (runs workloads but doesn't replicate the swarm state).
By default all managers are also workers in the sense that they can also run workloads.
