### ISSUE TITLE
Template improvements

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#5190]
- [x] Description: Keep the existing, create new `intro: ` key in yaml
- [x] Ability to mark topic as "Whole topic is EE" (rather than inline in the UCP/DTR tabs)
- [x] H2s not appearing in TOC (`toc_pure_liquid` processor looks in `page.content`)
- [ ] QueryString > Tab Selection, with cookie saving
- [x] Tabs for getting things done w/API
- [x] Reduce Headings to just "In the UI/CLI/API"
- [ ] If Single Tab: Fall back to H2s
- [ ] "Previous versions" tab 
- [ ] Compatibility information (badges inline)

**Comment by joaofnfernandes** [comment]
There was no progress on this, so I'm closing it due to inactivity.
