### ISSUE TITLE
404 at: https://docs.docker.com/docker-trusted-registry/overview/

### ISSUE THREAD

**Issue by evs-mdv** [docker/docker.github.io#52]
URL: https://docs.docker.com/docker-trusted-registry/overview/

This URL is referenced [here](https://docs.docker.com/registry/#/alternatives)

Fix URL :  https://docs.docker.com/docker-trusted-registry/

**Comment by johndmulhausen** [comment]
Fixed in 9fd1c9ad27a5735046944623216481e5564abb78
