### ISSUE TITLE
Version selector breaks at 1132px

### ISSUE THREAD

**Issue by mistyhacks** [docker/docker.github.io#5207]
File: [engine/swarm/networking.md](https://docs.docker.com/engine/swarm/networking/)

At this breakpoint the version selector overlays the Edit This Page link and makes it unclickable. There is another weird breakpoint up to 1153px wide, when it gets normal. cc/ @jsouth

**Comment by jsouth** [comment]
@mistyhacks - I"ll happily take care of this! 🎉

**Comment by jsouth** [comment]
@mistyhacks Did not forget about this. I  have a fix that I will implement before the end of the week!
