### ISSUE TITLE
Update UCP instructions for integrating with DTR

### ISSUE THREAD

**Issue by JimGalasyn** [docker/docker.github.io#5217]
In [Integrate with Docker Trusted Registry](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/integrate-with-dtr/), the section on [installing the DTR certificate](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/integrate-with-dtr/#1-configure-your-local-computer) is no longer necessary. Instead, users need to [install the UCP client bundle](https://docs.docker.com/datacenter/ucp/2.2/guides/user/access-ucp/cli-based-access/#use-client-certificates).

**Comment by joaofnfernandes** [comment]
It isn't so much that users need to use the client bundle, but:
* UCP needs to trust DTR (this is done automatically)
* Users need to configure their local Engines to trust DTR. That is covered in the DTR docs.

So we can just kill this article.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #463](https://github.com/docker/docs-private/issues/463) via [**ZenHub**](https://www.zenhub.com/)

**Comment by JimGalasyn** [comment]
Update: Looks like we want to keep this topic. David Lawrence says it's necessary, and Josh Hawn reviewed and said it looks good. Josh says: "It isn't necessary when DTR is running on this UCP cluster, but it is necessary when DTR is running somewhere else. In that case it does not automatically register - you need to do this manually. So, this doc looks good."
