### ISSUE TITLE
Run the app in tutorial uses already allocated port in its second step

### ISSUE THREAD

**Issue by nohwnd** [docker/docker.github.io#5218]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen

I am following the course on Windows and as instructed I press `Ctrl+C` in the shell to terminate. This keeps the container running on the background hogging the port. The command that follows: `docker run -d -p 4000:80 friendlyhello` then fails with the usual `driver failed programming external connectivity`. This is just a small hiccup, and it is easy to google the solution, but we are on second step of a beginners tutorial. So I think a more explicit way of terminating the container should be provided,  and it would also teach the reader about `docker ps` and `docker stop`.

**Comment by londoncalling** [comment]
@nohwnd Thanks for the feedback. We actually didn't realize this was the case -- seems to be only on Windows. I've added a note in that part of the tutorial, and tagged you on the PR. I'll give you a link to the Netlify preview, as soon as it's built.
