### ISSUE TITLE
Extension fields flaw

### ISSUE THREAD

**Issue by qoomon** [docker/docker.github.io#5226]
Hi there,

I just noticed a tiny flaw on the Docker compose documentation side in the Extension fields section:

https://docs.docker.com/compose/compose-file/compose-file-v2/#extension-fields

Markdown seems broken in for 3rd code block.
And the indention of 4th code block is wrong.

Kind regards

**Comment by londoncalling** [comment]
@qoomon Thanks! I went ahead and merged the related PR #5229 to get those fixes in and published, but if you see more that is wrong with those examples, please re-open this issue, and I'll create a new PR to make follow-up fixes.
