### ISSUE TITLE
Add "namespaces" to Security page

### ISSUE THREAD

**Issue by stefanlasiewski** [docker/docker.github.io#5228]
File: [engine/security/index.md](https://docs.docker.com/engine/security/), CC @mistyhacks 

The document at https://docs.docker.com/engine/security/ makes no mention of Secure Namespaces, which are an important security feature of the Docker Engine.

The Namespaces document at https://docs.docker.com/engine/security/userns-remap/ is listed under /security/ . Could you also list it under https://docs.docker.com/engine/security/ ?

Secure Namespaces are relatively new (I think https://docs.docker.com/engine/security/userns-remap/ was only created in June) and is not well known by the community. It would be great to promote this more.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by stefanlasiewski** [comment]
I think this should be addressed in the documentation.

Linux namespaces are still a major security feature used by Docker and other containers and were frequently mentioned during the talks at Kubecon 2018 in Seattle a few weeks ago. Docker should promote them and show how to use them more.
