### ISSUE TITLE
Feedback for: docker-cloud/apps/load-balance-hello-world.md

### ISSUE THREAD

**Issue by daneroo** [docker/docker.github.io#523]
URL: [https://docs.docker.com/docker-cloud/apps/load-balance-hello-world.md](https://docs.docker.com/docker-cloud/apps/load-balance-hello-world/)

Would it make sense to deploy the lb service with:
   deployment_strategy: every_node

**Comment by sanscontext** [comment]
Hi @daneroo I have to assume you're talking about specifically in the scenario described in [Load balancing the load balancer](https://docs.docker.com/docker-cloud/apps/load-balance-hello-world/#/further-reading-load-balancing-the-load-balancer)? There's nothing stopping you from using `every_node` in that instance. You might want to use labels to specify or limit the number of nodes it gets deployed on.

This repository is for documentation issues specifically, so I'm closing your issue as there are no doc changes needed or suggested. Please route all support questions through the [Docker Support portal](https://support.docker.com/) or ask around on the [Docker Cloud Forums](forums.docker.com/c/docker-cloud).

**Comment by daneroo** [comment]
Thanks @sanscontext.
