### ISSUE TITLE
Our command syntax includes linux prompt

### ISSUE THREAD

**Issue by bkauf** [docker/docker.github.io#5234]
### Problem description
Other companies just display the commands that you can easily cut and paste. We have commands on our pages that include linux prompt and commands...so you can't just cut and paste them. Go to any one of our documentation pages that lists a CLI command to see this.

![image](https://user-images.githubusercontent.com/4654783/32498361-873daa3c-c39d-11e7-9455-1e874812ad54.png)

### Problem location

This is consistent on literally every page showing CLI. We can start with one of the most common:
https://docs.docker.com/engine/installation/linux/docker-ee/rhel/#install-docker-ee

### Suggestions for a fix

We really need to remove any item in the command syntax that cannot just be cut and pasted where possible. This is what every other tech site does as my screen shot above shows.

**Comment by thaJeztah** [comment]
related https://github.com/docker/docker.github.io/issues/4053 and (a bit more way back https://github.com/moby/moby/issues/5768)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
