### ISSUE TITLE
17.06.2-ee-4 note Serialize IP allocation docker/libnetwork#1788 links to wrong repo

### ISSUE THREAD

**Issue by adamancini** [docker/docker.github.io#5235]
`Serialize IP allocation docker/libnetwork#1788` links to https://github.com/docker/swarmkit/pull/1788  but I think it should link to https://github.com/docker/libnetwork/pull/1788

File: [enterprise/17.06/index.md](https://docs.docker.com/enterprise/17.06/), CC @johndmulhausen

**Comment by thaJeztah** [comment]
Will be addressed by https://github.com/docker/docker.github.io/pull/5236
