### ISSUE TITLE
Please add documentation for the `--chown` flag to COPY/ADD

### ISSUE THREAD

**Issue by baronfel** [docker/docker.github.io#5258]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @mistyhacks

Per release 17.09, the ADD and COPY commands take a --chown flag to set the user/group: https://github.com/moby/moby/pull/34263

The functionality is there for sure, we just did a double-take at work today because it wasn't in the docs.

**Comment by kelvich** [comment]
Same thing from me. Did some jumps around to avoid expensive 'RUN chown -R ' over a big directory.

**Comment by mistyhacks** [comment]
This has been documented for some time. Sorry for forgetting to close here.
