### ISSUE TITLE
No Minimum Spec listed for Windows Node.  

### ISSUE THREAD

**Issue by ekitagawa** [docker/docker.github.io#5263]
File: [datacenter/ucp/2.2/guides/admin/install/system-requirements.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/system-requirements/), CC @JimGalasyn  

Could we have MSR listed for Windows worker nodes?

**Comment by joaofnfernandes** [comment]
@ekitagawa you're right. We'll follow-up on this one.

**Comment by friism** [comment]
I think the current (4GB RAM) is adequate. I'm adding a note about disk space.

**Comment by joaofnfernandes** [comment]
Closed by #5437
