### ISSUE TITLE
Option `--detach` option not implemented for this call

### ISSUE THREAD

**Issue by philosoralphter** [docker/docker.github.io#5267]
File: [engine/reference/commandline/service_scale.md](https://docs.docker.com/engine/reference/commandline/service_scale/), CC @mistyhacks

**Comment by joaofnfernandes** [comment]
This option was introduced with the Docker API 1.29. Can you do a `docker version` and check what's your API version?

**Comment by mistyhacks** [comment]
What version of Docker are you running? As noted in the file you linked above, the `--detach` flag for `docker service scale` requires version 1.29 or higher of the Docker Engine API. That means you need Docker 17.05 CE or higher. See https://docs.docker.com/develop/sdk/#api-version-matrix.
