### ISSUE TITLE
CPU limit is set too low

### ISSUE THREAD

**Issue by AlexandreRio** [docker/docker.github.io#5271]
### Problem description

Docker compose documentation uses 0.01% as a reservation value 

`0.0001 CPU time reserve`

```
reservations:
    cpus: '0.0001'
```
But using it produces the following error:

```
failed to create service servicename: Error response from daemon: rpc error: code = InvalidArgument desc = invalid cpu value 0.0001: Must be at least 0.001
```

### Problem location

Files is: `compose/compose-file/index.md`
Under the section **resources**.

[Direct link](https://github.com/docker/docker.github.io/blob/master/compose/compose-file/index.md#resources)

### Project version(s) affected

docker-compose version 1.17.0
Docker version 17.10.0-ce, build f4ffd2511c

### Suggestions for a fix

Use 0.001 as a reservation value and increase the limit value accordingly or drop the reservations section.

**Comment by thaJeztah** [comment]
Yes, that doesn't make much sense as an example; I suggest changing to more reasonable values, e.g.:

In this general example, the `redis` service is constrained to use no more than
50M of memory and `0.50` (50%) of available processing time (CPU), and has
`20M` of memory and `0.25` CPU time (25%) reserved (as always available to it).

```none
version: '3'
services:
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.10'
          memory: 20M
```


Would you be interested in contributing, and opening a pull request? You can open one using the [Edit this page](https://github.com/docker/docker.github.io/edit/master/compose/compose-file/index.md) link from the docs (or click the link I just added :smile:)

**Comment by AlexandreRio** [comment]
The PR uses 25% of reserved CPU, I think your compose file contains a typo (it says 10%).

**Comment by thaJeztah** [comment]
doh! yes, wasn't paying attention, thought I used 10% :smile:
