### ISSUE TITLE
Make powershell code snippets easy to copy/paste

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#5282]
File: [datacenter/ucp/2.2/guides/admin/configure/join-windows-worker-nodes.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/join-windows-worker-nodes/), CC @JimGalasyn 

Please make powershell snippets easy to copy/paste. Right now you need to manually remove all the PS> prefixes from the snippet.

I suggess you remove the PS> prefix on PowerShell lines and just mark the snippet box with powershell.

**Comment by NickVolynkin** [comment]
@martencassel  `$` and `PS>` prefixes are used to distinguish commands from their output in all code examples.
