### ISSUE TITLE
Mac OS screen to docker tty messy code

### ISSUE THREAD

**Issue by Mararesliu** [docker/docker.github.io#5283]
On Mac OS I  use screen command to tty, cannot interact correcttly, but messy code.Any way to correct it?I set screen’s to utf8,but make not effect

**Comment by thaJeztah** [comment]
I'm guessing you mean the screen command to get access to the VM in which the daemon runs?

If so; that option is really just for debugging; not developed as a feature for regular use of docker.

However, this issue-tracker (https://github.com/docker/docker.github.io) is for the documentation.

Your question is about Docker for Mac, so I'm closing it here.

If you still think there's a bug at hand, you can open a bug report in the Docker for Mac issue tracker; https://github.com/docker/for-mac/issues, but if you do, make sure to provide the _exact_ steps to reproduce.
