### ISSUE TITLE
Broken documentation, broke package source

### ISSUE THREAD

**Issue by scoopex** [docker/docker.github.io#5284]
File: [engine/installation/linux/docker-ce/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/), CC @mistyhacks

See: https://github.com/garethr/garethr-docker/issues/739

If you are using ubuntu artful you need to use the zesty source.

**Comment by thaJeztah** [comment]
Artful is not yet supported, as is listed in the [OS requirements](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#os-requirements) section on the page you linked to;

> ### OS requirements
> To install Docker CE, you need the 64-bit version of one of these Ubuntu versions:
>
> - Zesty 17.04
> - Xenial 16.04 (LTS)
> - Trusty 14.04 (LTS)


Docker 17.11 will be the first release that has packages for Artful; see https://github.com/docker/for-linux/issues/141

**Comment by thaJeztah** [comment]
Documentation updates for Docker 17.11 are already merged in the `vnext-engine` branch; https://github.com/docker/docker.github.io/pull/5266
