### ISSUE TITLE
Links within glossary are #term-name, should be #term<space>name

### ISSUE THREAD

**Issue by NickVolynkin** [docker/docker.github.io#5288]
In glossary, links to multiple-word terms are sometimes given as `#term-name`, while they should be `#term<space>name`.

For example, in [glossary/swarm](https://docs.docker.com/glossary/?term=swarm) link to the definition of "swarm mode" is broken. See the [source](https://github.com/docker/docker.github.io/blob/cd44af55718728b9ca1aa835b9fd9090534f69be/_data/glossary.yaml#L277):

```
  A [swarm](/engine/swarm/) is a cluster of one or more Docker Engines running in [swarm mode](#swarm-mode).
```
Should probably be this:
```
  A [swarm](/engine/swarm/) is a cluster of one or more Docker Engines running in [swarm mode](#swarm mode).
```
Probable solutions:
* If changing links to the right form is enough, I can do it myself.
* Or maybe the docs builder should add both `#term-name` and `#term name` anchors to each term.

---

Files: [glossary.md](https://docs.docker.com/glossary/), [glossary.yaml](https://github.com/docker/docker.github.io/blob/master/_data/glossary.yaml).

 CC @johndmulhausen

**Comment by mistyhacks** [comment]
In general, having spaces in URLs is terrible all around. I think we should fix the anchor generation to create the anchors with `-` instead of spaces.
