### ISSUE TITLE
The link to download docker binaries for Windows is broken

### ISSUE THREAD

**Issue by veyalla** [docker/docker.github.io#5293]
File: [engine/installation/linux/docker-ce/binaries.md](https://docs.docker.com/engine/installation/linux/docker-ce/binaries/), CC @mistyhacks 

There is an extra '/' in the URL, should be: "Invoke-WebRequest https://download.docker.com/win/static/stabl
e/x86_64/docker-17.09.0-ce.zip -UseBasicParsing -OutFile docker.zip"

**Comment by mistyhacks** [comment]
See #5294. By the way you might want to update your comment as this is a public repo.

**Comment by veyalla** [comment]
Done, thanks!
