### ISSUE TITLE
Docs - need example of bind mounts for Windows container on Windows host

### ISSUE THREAD

**Issue by PatrickLang** [docker/docker.github.io#5297]
File: [engine/admin/volumes/bind-mounts.md](https://docs.docker.com/engine/admin/volumes/bind-mounts/), CC @mistyhacks

This is the top result on docs.docker.com when I search for bind mounting, and it doesn't have a Windows sample. I'll submit a PR to fix it :)

**Comment by PatrickLang** [comment]
https://blogs.msdn.microsoft.com/clustering/2017/08/10/container-storage-support-with-cluster-shared-volumes-csv-storage-spaces-direct-s2d-smb-global-mapping/ has some samples but need to check a few things

**Comment by mistyhacks** [comment]
I think at the time I rewrote the content, bind mounts were not supported on Windows? I can't remember. There are definitely examples of Windows in the sibling Volumes topic.

**Comment by PatrickLang** [comment]
Which page is that? I'm still not having luck finding it.

The topics I want to cover are:
- Example syntax, are both / and \ supported
- Any exceptions when using `docker-compose`
- Windows caveats around symlinks, uid/gid mapping that don't work the way they do on Linux

**Comment by mistyhacks** [comment]
@JimGalasyn @johnstep @friism can you help out with any specifics?

The pages i was thinking of with Windows syntax were https://docs.docker.com/engine/admin/volumes/volumes/ and https://docs.docker.com/engine/admin/volumes/bind-mounts/, where the syntax on those pages does work for both Windows and Linux.

I think in general, you can mix `/` and `\` and have been able to for some time. I think there is `/`-specific syntax around drive letters. I went looking for guidance and didn't find a lot of specific guidance even in Microsoft's docs.

**Comment by JimGalasyn** [comment]
Fwiw, I tried `dir c:\users` and `dir c:/users` in PowerShell, and they both work.

**Comment by justincormack** [comment]
I think it would be good to mention whether `/` and `\` are both supported. Also that (a) absolute paths require a drive letter and (b) you can't bind mount over a non empty directory inside the container on Windows, which is a big difference.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by jasonbivins** [comment]
https://docs.docker.com/storage/bind-mounts/

No joy for windows users on this page

**Comment by ragazzojp** [comment]
How does it actually work on Windows (VM-based docker, not WSL2)? How is the local directory exposed to the VM and then bound by linux docker?
