### ISSUE TITLE
Docker EE SLES seems to support other filesystem type

### ISSUE THREAD

**Issue by mayconbeserra** [docker/docker.github.io#5304]
File: [engine/installation/linux/docker-ee/suse.md](https://docs.docker.com/engine/installation/linux/docker-ee/suse/), CC @mistyhacks

It seems Docker EE Sles support other filesystem type, because I'm using ext3.

Could you verify if the documentation is out of date?

Cheers,

**Comment by mistyhacks** [comment]
There is a difference between a supported configuration and a configuration that happens to work. Extensive testing has been done on supported configurations. Docker on SLES using `ext3` as a backing FS has not been tested and is not a supported configuration. The [Product compatibility matrix](https://success.docker.com/article/Compatibility_Matrix) is the definitive source for supported configurations for Docker EE.

cc/ @friism for confirmation.

**Comment by mayconbeserra** [comment]
thanks for your reply @mistyhacks
