### ISSUE TITLE
Multiple LABELs

### ISSUE THREAD

**Issue by MarcDenman** [docker/docker.github.io#5305]
Just noticed a slight inconsistency between whether you should use multiple LABEL instructions within a `dockerfile`

File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/#label)

> An image can have more than one label. To specify multiple labels, Docker recommends combining labels into a single LABEL instruction where possible.

File: [engine/userguide/eng-image/dockerfile_best-practices.md](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#label)

> An image can have more than one label. Prior to Docker 1.10, it was recommended to combine all labels into a single LABEL instruction, to prevent extra layers from being created. This is no longer necessary, but combining labels is still supported.

CC @mistyhacks

**Comment by mistyhacks** [comment]
Thanks for pointing this out. The `builder.md` has gone out of date. It is not actually a file that is managed within this repo, but is in https://github.com/docker/cli/tree/master/docs/reference. It would be great if you would like to raise a PR there to make the language consistent with the language in https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#label.

**Comment by MarcDenman** [comment]
OK, thank you. I have just taken at look in [builder.md](https://github.com/docker/cli/tree/master/docs/reference/builder.md) and seen that about a month ago you made a commit fixing this! ([e49e1ea73](https://github.com/docker/cli/commit/e49e1ea739317733c8e2b2786ca8c2c99b950959)) so I shall leave it as it is for now :)

**Comment by mistyhacks** [comment]
Nice, I forgot about that! The commits in `docker/cli` eventually make it into the `docker/docker-ce` repo but this obviously hasn't happened yet for this particular fix. Once it is in `docker/docker-ce` for a release, it will automatically be updated in the docs.

**Comment by leesah** [comment]
Hi, I am curious what was done in 1.10 that can avoid extra layers from being created. I can't find any description on that.

When I run `docker build`, I still see every `LABEL` clause generates a layer, the ID of which is visible in the outputs of `docker images -a`.

**Comment by leesah** [comment]
Never mind. I found a very detailed article eventually. I'll put a link to it here in case someone else like me landed here from Google: https://windsock.io/explaining-docker-image-ids/
