### ISSUE TITLE
docker binaries install on Windows docbug fix

### ISSUE THREAD

**Issue by veyalla** [docker/docker.github.io#5309]
File: [engine/installation/linux/docker-ce/binaries.md](https://docs.docker.com/engine/installation/linux/docker-ce/binaries/), CC @mistyhacks

Hi @mistyhacks - Found another issue, we need to add this:

```PS C:\> Copy-Item $env:ProgramFiles\docker\docker*.exe $env:SystemRoot```

*after* 

```PS C:\> Expand-Archive docker.zip -DestinationPath $Env:ProgramFiles```

`$env:ProgramFiles` is not in system path, so subsequent commands in the instructions are currently failing.

Appreciate your help in getting this in soon!

**Comment by mistyhacks** [comment]
@friism @johnstep WDYT?

**Comment by friism** [comment]
We shouldn't have this, it's already covered here: https://github.com/docker/docker.github.io/pull/5310

**Comment by veyalla** [comment]
@friism What is covered in #5310 is Docker EE, this is for Docker CE which is the version our product needs. Please don't remove these instructions...

**Comment by friism** [comment]
@veyalla sorry, Docker CE is not supported on Windows Server...

**Comment by johnstep** [comment]
I will follow up with Venkat separately.

**Comment by veyalla** [comment]
@friism This is not for Windows Server but for WIndows IoT Core. Support for which was added to the Docker engine as part of PRs below and verified:

https://github.com/moby/moby/pull/33414
https://github.com/moby/moby/pull/33498

Docker for Windows doesn't work for Windows IoT Core as it lacks a full Windows 10 GUI stack.

We can follow the same style as Docker EE binary installation and clean this up, but binaries installation instructions for Docker CE on Windows have a reason to exist because of Windows IoT Core.

**Comment by mistyhacks** [comment]
Closing as out of date.
