### ISSUE TITLE
The sample does not work in default settings

### ISSUE THREAD

**Issue by mm6502** [docker/docker.github.io#5313]
File: [engine/examples/dotnetcore.md](https://docs.docker.com/engine/examples/dotnetcore/), CC @mistyhacks 

The default .dockerignore 
> \*
> !obj/Docker/publish/*
> !obj/Docker/empty/

prevents this to work. The build fails at step 
`COPY *.csproj ./`
with error
`no source files were specified`

**Comment by mm6502** [comment]
Or perhaps make the step 4 more clear. As of now, it simply gives incorrect instructions (in context to the default .dockerignore file).

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
