### ISSUE TITLE
404 at /edge/engine/reference/commandline/config/

### ISSUE THREAD

**Issue by ganeshnewt** [docker/docker.github.io#5314]
URL: /edge/engine/reference/commandline/config/

**Comment by mistyhacks** [comment]
Can you let us know where you hit this URL?

**Comment by johndmulhausen** [comment]
https://docs.docker.com/engine/reference/commandline/config/ is a thing and so is https://github.com/docker/docker.github.io/blob/master/_data/engine-cli-edge/docker_config.yaml

Looks like we're missing a shell file. Adding now.
