### ISSUE TITLE
Update needed for documentation on running docker inspect on Windows

### ISSUE THREAD

**Issue by cheenamalhotra** [docker/docker.github.io#5316]
I would suggest an update to the below documentation page, to include instructions for changing single quotes(') to double quotes(") while running docker inspect commands on Windows Platform. 

Since this is an established solution, it must be published for aiding new developers.

File: [engine/reference/commandline/inspect.md](https://docs.docker.com/engine/reference/commandline/inspect/), CC @mistyhacks

**Comment by mistyhacks** [comment]
Please open this in https://github.com/docker/cli/ which is actually where those docs originate from. You can also make the modification if you like (the file lives in https://github.com/docker/cli/tree/master/docs/reference/commandline) and submit a PR. When a release is cut, any changes there are merged into `docker/docker-ce` and then we consume them. Thanks!
