### ISSUE TITLE
Display what's the latest version of Docker EE

### ISSUE THREAD

**Issue by friism** [docker/docker.github.io#5324]
File: [enterprise/index.md](https://docs.docker.com/enterprise/), CC @johndmulhausen

Preferably using an auto-updating macro, if possible

>  could someone update it to reflect the latest version of Docker EE

 \- Suzanne Panoplos

**Comment by joaofnfernandes** [comment]
@friism given that Docker EE itself doesn't have a version, should we include the matrix (EE engine 17.06, UCP 2.2, DTR 2.3), or should we do something else?

**Comment by mistyhacks** [comment]
What do you mean EE doesn't have a version? The latest supported version of EE is 17.06 right now...

**Comment by joaofnfernandes** [comment]
17.06 is the version of the latest Docker EE engine. Docker Enterprise Edition (the subscription) so far wasn't given any version.
