### ISSUE TITLE
network_mode: "service:[service name]" not adequately documented.

### ISSUE THREAD

**Issue by jpz** [docker/docker.github.io#5325]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01

Hi, I just wanted to give some feedback here.  I'm reading someone else's docker-compose script, but I do not know how `network_mode: "service:xxxx"` behaves.

The documentation just says network_mode is like --net parameter of docker, except for the special form of "service".  But then it fails to speak any further of what it actually does :)

The documentation pretty much identical for v2 and v3, and the feedback is for both documentation on both v2 and v3 of the docker-compose file.

**Comment by joaofnfernandes** [comment]
It seems that we have docs for this, but they are hard to find. #5116 was also about the same thing.
@jpz can you check if [what's documented here](https://docs.docker.com/engine/reference/run/#network-settings) can help you?

**Comment by jpz** [comment]
Thanks for the reply - I guess this is it.  

I think what is lacking in the docker-compose documentation is to say explicitly that "service:[asdf]" maps to the docker option "container:[asdf]" - which I do assume is the behaviour. 

As an end user, that is not apparent without description.

**Comment by WyseNynja** [comment]
I can't tell from the documentation how this interacts with scaling.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by Artiume** [comment]
I would like to reopen this, the lack of documentation is still an issue.

**Comment by stedwick** [comment]
Please re-open this, the documentation is lacking

**Comment by danielezer** [comment]
+1
I think the documentation is really lacking so this needs to be re-opened

**Comment by jrivard** [comment]
I can't find any info at all really about how network-mode "service:xxx" works.  Presumably it connects to some other service.    The sum total of docs I can find on this are (from the original issue description):

Network mode. Use the same values as the docker client --network parameter, plus the special form service:[service name].

What the heck does that mean?   I've searched for more details on the --network parameter (presumably the one that is part of 'docker run' command but I can't find any info on how the 'service' actually works.
