### ISSUE TITLE
Edition names missing from table on publishing content to Docker Store

### ISSUE THREAD

**Issue by subfuzion** [docker/docker.github.io#5329]
The table displayed for [Publish content on Docker Store](https://docs.docker.com/docker-store/publish/) is missing the names of the Docker editions that the qualifications apply to.

File: [docker.github.io/docker-store/publish.md](https://github.com/docker/docker.github.io/blob/40cf7568236bf0b1468918caf5e5397ff992a811/docker-store/publish.md)

![missing-edition-name](https://user-images.githubusercontent.com/159738/32942939-5c499472-cb3f-11e7-8b80-6525f9b073de.png)

The names in the table should be updated to reflect either the *Enterprise* or *Community* edition, as appropriate.

**Comment by mistyhacks** [comment]
@friism how would you like this to look?

**Comment by friism** [comment]
this is a @KickingTheTV / nandhini question
