### ISSUE TITLE
"All nodes participate in an ingress routing mesh" is incorrect

### ISSUE THREAD

**Issue by rbucker** [docker/docker.github.io#5330]
File: [engine/swarm/ingress.md](https://docs.docker.com/engine/swarm/ingress/), CC @mistyhacks 

my testing suggests that the ingress is from manager nodes only. The DOCs suggest ANY node. When I tried to connect to the webservice on a worker I received connectino refused.

**Comment by joaofnfernandes** [comment]
@rbucker my tests show that worker nodes can also receive and route connections. Can you share your tests, to see if I'm missing something?
Keep in mind that if you're using a cloud edition like AWS, there might be firewalls or security groups causing the behavior you're seeing.

I'll close this issue for now, but please comment to make sure the docs are correct.

---

Here's my test setup, one manager and one worker:

```
docker node ls

HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
node-1              Ready               Active              Leader
node-2              Ready               Active
```

Deploy the service and make it listen on port 8000 of the ingress routing mesh. Not that it matters to the test, but let's also force the service to be scheduled on the manager node.

```
service create --name wordpress --constraint "node.role==manager" --publish 8000:80 wordpress
```

Now try to access wordpress from the worker node to see if it works:

```
curl -IL <worker-node-ip>:8000

HTTP/1.1 302 Found
Date: Fri, 17 Nov 2017 19:00:33 GMT
Server: Apache/2.4.10 (Debian)
X-Powered-By: PHP/5.6.32
Location: http://192.168.99.101:8000/wp-admin/setup-config.php
Content-Type: text/html; charset=UTF-8

HTTP/1.1 200 OK
Date: Fri, 17 Nov 2017 19:00:33 GMT
Server: Apache/2.4.10 (Debian)
X-Powered-By: PHP/5.6.32
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Content-Type: text/html; charset=utf-8
```

**Comment by mistyhacks** [comment]
As long as the endpoint-mode is `vip` and the mode for any port publications is `ingress` then hitting a published port on any swarm node will invoke the routing mesh, which will route the work to a valid worker node which is running the service. If you are using Docker for Mac or Docker for Windows, this is obscured by the fact that your Docker host is running inside a thin VM and not directly on your host OS.
