### ISSUE TITLE
Firewalld restart note needs to be added to current documentation

### ISSUE THREAD

**Issue by lmuchnick** [docker/docker.github.io#5334]
Customer is requesting updated information in our docs regarding firewalld restart on CentOS requires the docker daemon to be restarted.  They would like to see something like the note in the 1.6 install guide.

https://docs.docker.com/v1.6/installation/centos/#installing-docker-centos-7

```
FirewallD
CentOS-7 introduced firewalld, which is a wrapper around iptables and can conflict with Docker.

When firewalld is started or restarted it will remove the DOCKER chain from iptables, preventing Docker from working properly.

When using Systemd, firewalld is started before Docker, but if you start or restart firewalld after Docker, you will have to restart the Docker daemon.
```
File: [engine/installation/linux/docker-ee/centos.md](https://docs.docker.com/engine/installation/linux/docker-ee/centos/), CC @mistyhacks

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
