### ISSUE TITLE
Autocompletion is not working for MAC as not all steps are included

### ISSUE THREAD

**Issue by mkannan555** [docker/docker.github.io#5338]
File: [compose/completion.md](https://docs.docker.com/compose/completion/), CC @gbarr01

Please include the steps mentioned in https://blog.alexellis.io/docker-mac-bash-completion/

**Comment by joaofnfernandes** [comment]
I think this was addressed recently. Check https://docs.docker.com/docker-for-mac/#bash
Feel free to open a new issue if this is not fixed yet.
