### ISSUE TITLE
bash typo in [docker cp] documentation for tar-piping out of a tmpfs 

### ISSUE THREAD

**Issue by JonJagger** [docker/docker.github.io#5339]
File: [engine/reference/commandline/cp.md](https://docs.docker.com/engine/reference/commandline/cp/), CC @mistyhacks 

I think the examples showing how to tar-pipe out of a tmpfs (because you can't docker cp from a tmpfs) are missing ${}. Viz

$ docker exec CONTAINER tar Ccf $(dirname SRC_PATH) - $(basename SRC_PATH) | tar Cxf DEST_PATH -

Should be

$ docker exec CONTAINER tar Ccf $(dirname ${SRC_PATH}) - $(basename ${SRC_PATH}) | tar Cxf ${DEST_PATH} -

and the same for the second example

**Comment by mistyhacks** [comment]
Hi @JonJagger ! Thanks for this feedback. That syntax for Bash variables is to try to protect against spaces in the paths. If there were a space in a path, it would definitely break without either the curly braces or double quotes. However, the source for this page actually lives in the [`docker/cli`](https://github.com/docker/cli/tree/master/docs/reference/commandline) repository. If you raise a PR there and update the examples, they will get into the docs when your change is cherry-picked into a release branch in `docker/docker-ce`.
