### ISSUE TITLE
update the docs for extends

### ISSUE THREAD

**Issue by rdxmb** [docker/docker.github.io#5340]
File: [compose/extends.md](https://docs.docker.com/compose/extends/), CC @gbarr01

Hi,
the options to extend the compose-file has been changed.

- "extend" is deprecated and does not work with v3(.X ?) anymore
-  with compose file version 3.4 , yml extension is supported. See https://docs.docker.com/compose/compose-file/#extension-fields

This should be updated on this docs site.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
