### ISSUE TITLE
Add mention of the overlay2 graph driver now being supported

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#5344]
File: [engine/installation/linux/docker-ee/rhel.md](https://docs.docker.com/engine/installation/linux/docker-ee/rhel/), CC @mistyhacks

For RHEL and CentOS 7.4 and higher, we now support and prefer `overlay2` for EE per https://success.docker.com/article/Compatibility_Matrix over `devicemapper` :tada: :tada: .  The support began with `17.06.2-ee-5` per the footnote.  The matrix is missing the 7.4 requirement; was waiting on getting verification on that from the customer success team.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker.github.io/pull/5240
