### ISSUE TITLE
Page not found(404) on 'Service deployment in the cloud'

### ISSUE THREAD

**Issue by hallazzang** [docker/docker.github.io#5347]
### Problem description

I see page not found(404) error when pressing 'Service deployment in the cloud' link in [this page(Samples)](https://docs.docker.com/samples/#tutorial-labs).

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/samples/#tutorial-labs

- I couldn't find the information I wanted. I expected to find it near the following URL: https://github.com/docker/labs/tree/master/swarm-mode/cloud-quick-start

- Other: N/A

### Suggestions for a fix

Well, I can't find any proper link that might have been moved.

**Comment by hallazzang** [comment]
Um, I think I should add this line, too.

File: [samples/index.md](https://docs.docker.com/samples/), CC @johndmulhausen

**Comment by JimGalasyn** [comment]
Fixed in [PR 5532](https://github.com/docker/docker.github.io/pull/5532).
