### ISSUE TITLE
getting-started/index.md shouldn't exist

### ISSUE THREAD

**Issue by aduermael** [docker/docker.github.io#536]
### Problem description

This page can never be displayed, because there's a redirect set in `engine/getstarted/index.md`.

### Project version(s) affected

current

### Suggestions for a fix

remove `engine/getstarted/index.md`

**Comment by johndmulhausen** [comment]
Removed

**Comment by aduermael** [comment]
@johndmulhausen thanks!

**Comment by aduermael** [comment]
@johndmulhausen is there a PR already? The content is still here.
