### ISSUE TITLE
There is no information available on how to check a container's health status

### ISSUE THREAD

**Issue by djanderson** [docker/docker.github.io#5368]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @mistyhacks 

Neither Docker's section on `HEALTHCHECK` nor docker-compose's section on `healthcheck` include any guidance on how to check a container's health.

From what I can find, _all_ of the blog posts and s/o question say to use `docker inspect --format='{{json .State.Health.Status}}' <container_name>` but that gives `Template parsing error: template: :1:13: executing "" at <.State.Health.Status>: map has no entry for key "Health"`.

Since there's a lot of apparent mis-information out there, the official docs should include ways to check health status.

**Comment by djanderson** [comment]
In the end, I was not able to get health checks to run using the `docker-compose` file. I had to remove it from docker-compose and use `HEALTHCHECK` in the Dockerfile. Only then did the container register the health checks. This may be a more appropriate as a docker-compose issue. Feel free to close, though I still think a bit more clarification in the docs about how to check the status would be helpful.

**Comment by thaJeztah** [comment]
Are you using the `docker-compose` file with `docker stack deploy` or with `docker-compose`?

The `State.Health.Status` key is only present in the container's JSON if the container was started with a health check. You can Get the `State.Health` field instead, which always is present;

```bash
docker inspect --format '{{json .State.Health }}' <some container>
```

That will return `null` if no health check is set, and the health information if present.

If a container is started with a healthcheck:

```bash
$ docker run -d \
  --name=health \
  --health-cmd='if [ ! -f "/count" ] ; then ctr=0; else ctr=`cat /count`; fi; ctr=`expr ${ctr} + 1`; echo "${ctr}" > /count; if [ "$ctr" -gt 4 ] ; then exit 0; else exit 1; fi' \
  --health-interval=10s \
  --health-timeout=3s \
  --health-retries=3 \
  --health-start-period=60s \
  -p8080:80 \
  nginx:alpine
```

The health-status can be inspected (as mentioned earlier);

```bash
$ docker inspect --format '{{json .State.Health }}' health
{"Status":"healthy","FailingStreak":0,"Log":[{"Start":"2017-11-22T18:58:07.645784086Z","End":"2017-11-22T18:58:07.693701859Z","ExitCode":1,"Output":""},{"Start":"2017-11-22T18:58:17.697402086Z","End":"2017-11-22T18:58:17.735709794Z","ExitCode":1,"Output":""},{"Start":"2017-11-22T18:58:27.742337877Z","End":"2017-11-22T18:58:27.78168765Z","ExitCode":1,"Output":""},{"Start":"2017-11-22T18:58:37.788006017Z","End":"2017-11-22T18:58:37.82619679Z","ExitCode":1,"Output":""},{"Start":"2017-11-22T18:58:47.833221222Z","End":"2017-11-22T18:58:47.875446373Z","ExitCode":0,"Output":""}]}
```

But also shows in `docker ps`:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED                  STATUS                            PORTS                                      NAMES
543488d77903        nginx:alpine        "nginx -g 'daemon of…"   Less than a second ago   Up 3 seconds (health: starting)   0.0.0.0:8080->80/tcp                       health
```

After the container becomes healthy:

```bash
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                        PORTS                                      NAMES
543488d77903        nginx:alpine        "nginx -g 'daemon of…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:8080->80/tcp                       health
```

**Comment by djanderson** [comment]
@thaJeztah thanks for the comment. I am using `healthcheck` in the docker-compose.yml file. I made a compose file that mirrored your example and tested it successfully. That prompted me to go back and try a bit harder to figure out what was going on. Eventually I just deleted all existing containers and rebuilt them, and now I can see the `State.Health`. I hadn't thought I needed to do that, but it did solve my issue.

Thanks for the detailed example, it helped me debug my issue.

Again, feel free to close this issue, though it did add significant time to my debugging effort just not being able to find an official word on where to find the health status.

**Comment by thaJeztah** [comment]
Good to hear it helped you!

I opened a tracking issue for documentation around health-checks (see https://github.com/docker/docker.github.io/issues/3282), because I _do_ agree we need more docs around that; feel free to participate in that discussion, and add what you are missing in the docs, and what would help you.

I'll close this one 👍

**Comment by nicholasserra** [comment]
^ please disregard above, seems ordering of some of the options was causing an issue and the CLI was not complaining, only failing to start healthcheck. Thanks!
