### ISSUE TITLE
getting-started files not accessible

### ISSUE THREAD

**Issue by aduermael** [docker/docker.github.io#537]
### Problem description

These pages are not accessible directly, as `getting-started/index.md` redirects to `engine/getstarted/` (see #536):

- `getting-started/part2.md`
- `getting-started/part3.md`
- `getting-started/part4.md`
- `getting-started/part5.md`

### Project version(s) affected

current

### Suggestions for a fix

Remove these files: 

- `getting-started/part2.md`
- `getting-started/part3.md`
- `getting-started/part4.md`
- `getting-started/part5.md`

note: in these markdowns we include gists using liquid template, like this:`{% gist johndmulhausen/074cc7f4c26a9a8f9164b20b22602ad7 %}`. We shouldn't use that and keep everything local.

**Comment by johndmulhausen** [comment]
Removed

**Comment by aduermael** [comment]
@johndmulhausen thanks!

**Comment by aduermael** [comment]
@johndmulhausen is there a PR already? The content is still here.

**Comment by johndmulhausen** [comment]
@aduermael Should be removed now, sorry - multitasking late last night :)
