### ISSUE TITLE
Sometimes Docker Cloud will say autotests failed with exit code 0

### ISSUE THREAD

**Issue by davidthornton** [docker/docker.github.io#5371]
File: [docker-cloud/docker-errors-faq.md](https://docs.docker.com/docker-cloud/docker-errors-faq/), CC @londoncalling

Sometimes, Docker Cloud autotests will return this in the logs at the end of a successful test, when running in your own nodes:

```
Tests in docker-compose.test.yml succeeded
Build finished
ERROR: Build failed: Build finished
ERROR: Build failed with exit code 0
ERROR: Tests in 'dev' (ffb81ed5) failed in 0:09:00
```

**Comment by mistyhacks** [comment]
Not a docs bug. I have passed on your feedback to the Cloud team. Thanks!
