### ISSUE TITLE
bad redirection semantics

### ISSUE THREAD

**Issue by gdevillele** [docker/docker.github.io#538]
### Problem description

When hitting redirections listed in frontmatter headers (like `/mackit/`), we are not getting a 301 HTTP Code.
From my understanding, it should be the case.
https://support.google.com/webmasters/answer/93633

```shell
$ curl -v https://docs.docker.com/mackit/
*   Trying 52.84.24.231...
* Connected to docs.docker.com (52.84.24.231) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: docs.docker.com
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /mackit/ HTTP/1.1
> Host: docs.docker.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 436
< Connection: keep-alive
< ETag: 47c5-1b4-58251905
< Last-Modified: Fri, 11 Nov 2016 01:04:05 GMT
< Server: WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26)
< Date: Fri, 11 Nov 2016 05:41:57 GMT
< Cache-Control: max-age=600
< Strict-Transport-Security: max-age=15768000
< X-Cache: RefreshHit from cloudfront
< Via: 1.1 8a78b675adb2cce925860f2fe4383e71.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: 5E2yIGA8JWo8ehdUO4d9RrWqppXkRFFzCthpyxZZkH2ElGtOB6-drg==
<
<!DOCTYPE html>
<html lang="en-US">
<meta charset="utf-8">
<title>Redirecting…</title>
<link rel="canonical" href="https://docs.docker.com/docker-for-mac/">
<meta http-equiv="refresh" content="0; url=https://docs.docker.com/docker-for-mac/">
<h1>Redirecting…</h1>
<a href="https://docs.docker.com/docker-for-mac/">Click here if you are not redirected.</a>
<script>location="https://docs.docker.com/docker-for-mac/"</script>
</html>
* Connection #0 to host docs.docker.com left intact
```

### Problem location

All paths listed under `redirect_from` in frontmatter headers, like `/mackit/`.
https://docs.docker.com/mackit/

### Project version(s) affected

current stable

**Comment by johndmulhausen** [comment]
This is a limitation of using Jekyll/WEBrick as a package -- for more info see here: https://superdevresources.com/redirects-jekyll-github-pages/

The good news is that 301s are not the end-all-be-all; the URLs we produce still have `canonical` and `refresh` tags that are ABSOLUTELY supported by search engines. 

I don't think there's much we can do about this without massively rethinking how the container image works, and I'm trying to step away from being concerned about that right now and focus on content. Any help would be appreciated on getting to a 301 world.

**Comment by gdevillele** [comment]
Thank you for having done some research.
On the practical aspect, this ticket is more a request for improvement than a real issue, but from an SEO point of view, it's probably an issue. The `refresh` meta + canonical link is a trick that doesn't have the intended semantics (it doesn't express the "permanent" aspect of the redirection)

From the article:
`using a server side 301 redirect is a much better option and supported by all search engines`
`While Google doesn’t recommend its use, it has listed the meta refresh tag in its list of supported meta tags.`

Let's keep this issue for the SEO discussions and work.

**Comment by johndmulhausen** [comment]
Yes, let's. Thanks, @gdevillele !

**Comment by mstanleyjones** [comment]
This should be fixed now that we are serving the docs using Nginx.
