### ISSUE TITLE
Error response from daemon: could not get container for some-mysql: No such container: some-mysql.

### ISSUE THREAD

**Issue by YanzhongSu** [docker/docker.github.io#5385]
File: [_samples/library/wordpress/index.md](https://docs.docker.com/samples/library/wordpress/), CC @aanand when I ran `sudo docker run --name some-wordpress --link some-mysql:mysql -d wordpress` I got no such container error. The same error for `sudo docker run --name some-wordpress --link some-mysql:mysql -p 8080:80 -d wordpress` Any possible solution?

**Comment by johndmulhausen** [comment]
Hi @YanzhongSu - while we republish the Library docs, we don't actually maintain them in the docs repo. I know it's a pain, but can you open this issue over in this repo: https://github.com/docker-library/docs/tree/master/wordpress/

**Comment by ericsubach** [comment]
Just thought I would leave this here for anyone else having the same issue (as a person with almost no docker experience): you must pull and run an instance of mysql prior to running the wordpress docker. Those instructions are at https://hub.docker.com/_/mysql/
