### ISSUE TITLE
docs: Broken link to multistage-build.md

### ISSUE THREAD

**Issue by vi** [docker/docker.github.io#5388]
File: [engine/userguide/eng-image/dockerfile_best-practices.md](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/), CC @mistyhacks

> `you can use [multi-stage](!) builds to`

**Comment by mistyhacks** [comment]
There are a few links to the multi-stage build topic from that file and they all work for me. The link may appear broken if you are browsing the source on Github and relying on Github's preview, but the  content was meant to be viewed from https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/.

If you do find one that is broken, please re-open this with more details. Thanks!

**Comment by vi** [comment]
Yes, the linked page contains the broken link if JavaScript is disabled.

```
Expected: https://docs.docker.com/engine/userguide/eng-image/multistage-build/
Actual:   https://docs.docker.com/engine/userguide/eng-image/multistage-build.md
```

After enabling JavaScript the link becomes normal.

**Comment by mistyhacks** [comment]
This is expected. Our site is not really functional without Javascript.

**Comment by vi** [comment]
Then a banner like "This site is better views with JavaScript enabled" should be displayed, like on StackOverflow.

**Comment by mistyhacks** [comment]
cc/ @johndmulhausen
