### ISSUE TITLE
Docs does not work. Unable to locate stable deb file

### ISSUE THREAD

**Issue by Sarseth** [docker/docker.github.io#5392]
Hey,
just wanted to test docker on machine using ur instructions howto. Made step by step, log included. No way to install.

less /etc/apt/sources.list: 
deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable

I went even to download the file, but unable to find deb file under location you provide:
https://download.docker.com/linux/ubuntu/dists/zesty/stable/

"Instructions not clear enough" ;)
[dockerIssue.txt](https://github.com/docker/docker.github.io/files/1503272/dockerIssue.txt)

**Comment by thaJeztah** [comment]
Packages for Artful have not been released for stable releases yet, only edge:

https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#os-requirements
![img_5856](https://user-images.githubusercontent.com/1804568/33234671-6e8729cc-d22b-11e7-9424-067a84df5907.PNG)

**Comment by Sarseth** [comment]
Found that by accident, using script version of installation. Thx
