### ISSUE TITLE
localhost curl: (7) Failed to connect to localhost port 5040: Connection refused

### ISSUE THREAD

**Issue by rberge** [docker/docker.github.io#5395]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen 
I have Mac Sierra.
I spent a while on this one point in the instructions where it says to run this at the command line
docker run -p 4000:80 friendlyhello

I got  the curl error refused to connect and the similar error in Safari and Chrome.
Finally I found a reference to lookup the Docker forum with an answer from nathanleclaire Docker Staff which said to use "docker-machine ip default" to find the equivalent to localhost (if I understand him correctly).  

It would seem reasonable to tell people who are doing the tutorial that you don't literally meant to type "localhost" in the browser.  Or maybe that works for you.  I just wanted to get through this tutorial and use Docker but unfortunately had to spend a lot of time figuring out something that could have been in the tutorial.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
