### ISSUE TITLE
Missing Django new_app commands

### ISSUE THREAD

**Issue by maxgittelman** [docker/docker.github.io#5396]
File: [compose/django.md](https://docs.docker.com/compose/django/), CC @gbarr01 

Hello,

I think what would be useful to include in the docker-compose Django quickstart guide would be how to write equivalent commands from the [Django tutorials](https://docs.djangoproject.com/en/1.11/intro/) through Docker-compose. Or at the very least how to execute python commands directed in the docker images.

For example, in the [first Django tutorial](https://docs.djangoproject.com/en/1.11/intro/tutorial01/) to create a new app, one must execute:
`$ python manage.py startapp polls`

However through Docker the equivalent is:
`$ docker-compose run web python manage.py startapp polls`
`$ sudo chown -R $USER:$USER polls`

What I think is not necessarily obvious to the developer is how to execute python commands through docker. Mostly because calling `python` on localhost does not necessarily translate to the equivalent `python` environment that `docker-compose` intends to use. The next wall that I've reached is using 

`$ python manage.py migrate`

I will likely try:
`$ docker-compose run web python manage.py migrate`

If my thinking is correct, all commands given in the Django tutorials only need to add `docker-compose run web` before the command to be executed. I'm not 100% sure my thinking is correct but without a real basis for how the Django tutorials can be used via Docker-compose, there is an unnecessary learning curve for a developer to include Docker in her project. If you could add an explanation for how to follow the Django docs making use of Docker, the many Django/Python enthusiasts would have real reason to join the wave of Docker.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
