### ISSUE TITLE
Feedback for: docker-hub/github.md

### ISSUE THREAD

**Issue by tomashley** [docker/docker.github.io#54]
URL: docker-hub/github.md

The screenshots for automated builds are out of date and don't reflect the current UI

**Comment by sanscontext** [comment]
Thanks for reporting that. I admit Hub docs have not been our priority, and we've been [focusing on Docker Cloud](https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498). I'll make sure I hit those images next time I update that doc.

**Comment by sanscontext** [comment]
Hey @tomashley I'm looking at these today and I'm not entirely sure which image you're referring to. Can you be more specific?

**Comment by sanscontext** [comment]
This has been sitting for months and there's been no feedback. Closing it out, please reopen if you can point me at specific images that are out of date.
