### ISSUE TITLE
Feedback for: docker-cloud/getting-started/connect-infra.md

### ISSUE THREAD

**Issue by baksoy** [docker/docker.github.io#541]
File: [docker-cloud/getting-started/connect-infra.md](https://docs.docker.com/docker-cloud/getting-started/connect-infra/)

At To link your cloud provider accounts, first go to your Docker Cloud account dashboard. 

There is a Broken link at  **Docker Cloud account dashboard**

**Comment by sanscontext** [comment]
Closed via #535
