### ISSUE TITLE
Registry hooks

### ISSUE THREAD

**Issue by khs1994** [docker/docker.github.io#5411]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/registry/configuration/#hooks

- Other: <DETAILS>

### Suggestions for a fix

`hooks` should under `log`

![2017-11-29 11 47 16](https://user-images.githubusercontent.com/16733187/33357161-95a1b040-d4fb-11e7-9e48-0610a31ee88d.png)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
