### ISSUE TITLE
"Open source at docker"'s all sub menus are redirected to "Contribute to documentation"

### ISSUE THREAD

**Issue by Myeongjoon** [docker/docker.github.io#5412]
### Problem description

- https://docs.docker.com/opensource/code/
- https://docs.docker.com/opensource/FAQ/
- https://docs.docker.com/opensource/doc-style/
- https://docs.docker.com/opensource/get-help/
- https://docs.docker.com/opensource/project/who-written-for/ 

...
are redirected to

- https://docs.docker.com/opensource/
This url did not have many contents to cover the above menus.

### Problem location

- I saw a problem on the following URL: 
https://docs.docker.com/ -> Guide menu -> in left side "Open Source at docker" 

- I couldn't find the information I wanted. I expected to find it near the following URL: 
"Open Source at docker"'s all sub menus are have href source, but all redirected to https://docs.docker.com/opensource/

- Other: Is this redirection is error or right?

**Comment by londoncalling** [comment]
@JimGalasyn @Myeongjoon I saw this today myself. I'll try to fix it and push the PR. Those topics shouldn't be in the left-side menu anymore, as they've been replaced by a single document now.
