### ISSUE TITLE
Why not using docker-machine env instead of docker-machine ssh ?

### ISSUE THREAD

**Issue by gquemener** [docker/docker.github.io#5413]
The first step of this tutorial is to connect through ssh to the remote docker machine. What about using `docker-machine env manager1` which will have the same result without connecting through ssh into the machine?
I have read many times that ssh'ing into container is a bad practice, what about ssh'ing into the docker machine?
Thanks for your time and the set of great tools you provide,
Regards.

File: [engine/swarm/swarm-tutorial/create-swarm.md](https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/), CC @mistyhacks

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
