### ISSUE TITLE
Offline DTR upgrade

### ISSUE THREAD

**Issue by okrangerb3** [docker/docker.github.io#5414]
The customer is confused because in the engine upgrade we drain nodes.  In DTR via comand line we do not have clear instructions and if they drain a DTR node it seems to cause brief outages.

File: [datacenter/dtr/2.3/guides/admin/upgrade.md](https://docs.docker.com/datacenter/dtr/2.3/guides/admin/upgrade/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
@okrangerb3 can you provide more details about the setup:
* How many manager nodes
* How many worker nodes
* How many DTR replicas running
* How are you draining nodes and doing the engine upgrade

**Comment by bermudezmt** [comment]
@caervs Can we address this issue since we are now advising users to drain DTR nodes during an EE upgrade? Can we outline some steps and best practices for doing so?

**Comment by caervs** [comment]
@bermudezmt yeah. More detailed instructions would be great. The basic idea is to rotate out old engines for new ones. You do so by joining DTR replicas running on new engines and then destroying the old ones. I forget in which PR you documented this.

**Comment by bermudezmt** [comment]
@caervs That would be [#5414](https://github.com/docker/docker.github.io/issues/5414). On the more detailed instructions front, I found this page that we could also link out to from the upgrade pages (online and offline): https://docs.docker.com/ee/dtr/admin/configure/set-up-high-availability/ 

Can you please review the above for accuracy? My next steps will be to test the upgrade process, and document that (including common gotchas) so we can hopefully avoid the outage issue in the future.

**Comment by bermudezmt** [comment]
@JustinINevill Can we relate this issue to the enterprise content refactor issues you plan to open? This is really an enhancement request to our DTR upgrade doc.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
