### ISSUE TITLE
Upgrades inside a on-prem or air-gapped environment

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#5423]
How do you perform robust in-place upgrade of Docker EE inside a air-gapped environment ? 
With script or module ? 
There exists a scripted installation, but a scripted upgrade procedure or uninstall is missing.
How do you perform a safe in-place upgrade using a script without the powershell modules ? 
The powershell module supports upgrade and it wipes everything before updating the files.
Can you use the powershell module inside a air-gapped environment ? 

File: [engine/installation/windows/docker-ee.md](https://docs.docker.com/engine/installation/windows/docker-ee/), CC @mistyhacks

**Comment by mistyhacks** [comment]
cc/ @johnstep @andrewhsu @thaJeztah for ideas...

**Comment by thaJeztah** [comment]
Looks like it'll need to be a variation on the [scripted install](https://docs.docker.com/engine/installation/windows/docker-ee/#use-a-script-to-install-docker-ee), but @johnstep can probably better tell the exact steps that need to be documented

**Comment by mistyhacks** [comment]
Looks like this is actually missing functionality and not a docs issue. @thaJeztah I am unsure where the issue should be filed. Please advise. I will close this Docs issue.

**Comment by thaJeztah** [comment]
Think they come from https://github.com/OneGet/MicrosoftDockerProvider/blob/master/DockerMsftProvider.psm1, I'll check where we should report
