### ISSUE TITLE
Feedback for: docker-cloud/infrastructure/link-aws.md

### ISSUE THREAD

**Issue by alandsidel** [docker/docker.github.io#543]
File: [docker-cloud/infrastructure/link-aws.md](https://docs.docker.com/docker-cloud/infrastructure/link-aws/)

This page provides out of date instructions.  The AWS account info is not asking for an ARN, but the ID and secret for an AWS access key.

**Comment by sanscontext** [comment]
Hey @alandsidel, are you using the legacy (Tutum-style) Cloud UI?

**Comment by sanscontext** [comment]
Hey @alandsidel, please provide a screenshot of what you're seeing. The docs are showing the current, recommended method that's used by the new Cloud UI. If you're using the old UI, you should know that it's slated for deprecation soon.

**Comment by sanscontext** [comment]
This has been sitting without feedback for a long time. I'm going to close this out, but let me know if you can provide a screenshot of whatever you were seeing.
