### ISSUE TITLE
Add Docker Events notes about limited backlog of events and event scope.

### ISSUE THREAD

**Issue by BretFisher** [docker/docker.github.io#5432]
File: [engine/reference/commandline/events.md](https://docs.docker.com/engine/reference/commandline/events/), CC @mistyhacks

1) Great doc on the events command but I don't see anything to educate the user on the backlog limits of the events cli/api.  With all the nice date-based filter values, the reader might think it would be a file written to disk for long-term storage like the dockerd log.  I don't think that's the case, but I'm coming up with little info on how much is exactly stored.  I see a @cpuguy83 [mention here of 1000 event backlog maximum](https://github.com/moby/moby/issues/29548#issuecomment-268329529) (I assume per node). If that's true, it would be great to mention it here.
2) Second, only after using them a while did I realize that Swarm events (services/nodes/secrets/configs) are seen on managers only, and any other events are only from the local server. I know there's a filter shown for `local|swarm` but maybe it would improve visibility of this big difference to mention the two types in description, with something like "different event types have different scopes, local scoped events are only seen on the node they take place on, and swarm scoped events are seen on all managers".

If you think this is good additional info, I'm happy to submit PR but wanted to get confirmation and feedback first. Maybe these two should just be added to the [top description](https://github.com/docker/cli/blob/master/docs/reference/commandline/events.md#events)?

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #727](https://github.com/docker/cli/issues/727) via [**ZenHub**](https://www.zenhub.com/)

**Comment by joaofnfernandes** [comment]
I think this would be an awesome addition to the docs, so if you're willing to file a PR, go for it!

Looking at https://github.com/moby/moby/blob/master/daemon/events/events.go#L13, it seems that you're correct and the event queue can hold at most `1024` messages per engine.

I was able to find the methods that process [swarm-level events here](https://github.com/moby/moby/blob/master/daemon/events.go#L148-L184), but could not find out how workers and managers differ in how they log information. Knowing how swarm works I suspect you're also right, but @cpuguy83 or @thaJeztah should be able to confirm.
