### ISSUE TITLE
The terminal recording does not work on my Chrome in MAC Sierra

### ISSUE THREAD

**Issue by cisum-la** [docker/docker.github.io#5434]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/), CC @johndmulhausen
<img width="1382" alt="screen shot 2017-12-03 at 10 38 23 am" src="https://user-images.githubusercontent.com/9635484/33528513-5dcdda7c-d816-11e7-9946-c6cbfb30c9d9.png">

**Comment by johndmulhausen** [comment]
Exactly the OS and browser I'm using and I can't repro. :(
