### ISSUE TITLE
Missing style guide

### ISSUE THREAD

**Issue by schomatis** [docker/docker.github.io#5435]
The style guide mentioned in

https://github.com/docker/docker.github.io#style-guide

is missing. The link redirects to

https://docs.docker.com/opensource/doc-style/

which doesn't seem to exist in the source repo, so it defaults to

https://docs.docker.com/opensource/

This issue may be considered related to #5412, where the problem is in the TOC (here this issue refers to the repo `README.md`), but I'm filing a separate issue because my main interest is to find where the style guide is located.

**Comment by schomatis** [comment]
The style guide seems to be removed in #5232 (the document can be viewed in its corresponding [commit](https://github.com/docker/docker.github.io/blob/7cfe2e9da240cd9d2dc475593af1a4840a518614/opensource/doc-style.md)).

Has the style guide been moved to [Moby](https://github.com/moby/moby)? It's [contributing guide](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#conventions) also references the same missing link:

https://docs.docker.com/opensource/doc-style

Can I still consider the deleted style guide the most up-to-date reference?

**Comment by johndmulhausen** [comment]
@schomatis We don't have a particular style guide to recommend right now; we'll have to do some thinking and decide what guidance to provide in the future.
