### ISSUE TITLE
add --chown flag to docs for COPY and ADD

### ISSUE THREAD

**Issue by metalivedev** [docker/docker.github.io#5441]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @mistyhacks 

Per https://github.com/moby/moby/issues/6119#issuecomment-338920866 `ADD` and `COPY` now support `--chown`. Please add these to the main documentation.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #738](https://github.com/docker/cli/issues/738) via [**ZenHub**](https://www.zenhub.com/)

**Comment by thaJeztah** [comment]
Oh hai @metalivedev 👋 👋 🤗

**Comment by thaJeztah** [comment]
Linking here as well for easier finding; https://github.com/docker/cli/pull/467
