### ISSUE TITLE
Clarify what an image reference is

### ISSUE THREAD

**Issue by jcrben** [docker/docker.github.io#5442]
"reference (pattern of an image reference) - filter images whose reference matches the specified pattern"

What is the reference? It's not an easy thing to pick up in Google considering that it's a word used in many different contexts, including at Docker.

The only place I could find a definition after searching for a few minutes was a third-party repo (https://github.com/vmware/vic/issues/3945) where it is described as "specifically repository name or repository and tag".

https://docs.docker.com/engine/reference/builder/ contains no mention of an "image reference" as far as I can tell - of course reference is in the URL so there's a fair number of hits for the word 

File: [engine/reference/commandline/images.md](https://docs.docker.com/engine/reference/commandline/images/), CC @mistyhacks

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #739](https://github.com/docker/cli/issues/739) via [**ZenHub**](https://www.zenhub.com/)
