### ISSUE TITLE
deploy to swarm instructions should advise use of --with-registry-auth for private repositories

### ISSUE THREAD

**Issue by russellritchie** [docker/docker.github.io#5445]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen

Hello.

The instructions for deploying to swarms should advise use of --with-registry-auth for private repositories as many first time users will be using free Docker Cloud subscriptions with private repositories.

**Comment by johndmulhausen** [comment]
I don't think we want to do that; thanks for the suggestion though.
