### ISSUE TITLE
"Storage driver options" anchor

### ISSUE THREAD

**Issue by gustavopaes** [docker/docker.github.io#5446]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/), CC @mistyhacks 

At "Daemon storage-driver" topic, there are two anchors in "Storage driver options" texts sending to "https://docs.docker.com/engine/reference/commandline/dockerd/#storage-driver-options", but they are not working.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/cli #737](https://github.com/docker/cli/issues/737) via [**ZenHub**](https://www.zenhub.com/)
