### ISSUE TITLE
Dead link new link seem to be: https://success.docker.com/article/Compatibility_Matrix

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#5449]
File: [datacenter/ucp/2.2/guides/admin/install/system-requirements.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/system-requirements/), CC @jimgalasyn

**Comment by JimGalasyn** [comment]
Correct link is [Compatibility Matrix](https://success.docker.com/Policies/Compatibility_Matrix).
