### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#5459]
File: [datacenter/dtr/2.4/reference/cli/index.md](https://docs.docker.com/datacenter/dtr/2.4/reference/cli/), CC @joaofnfernandes

https://docs.docker.com/datacenter/dtr/2.4/reference/cli/dumpcerts

**Comment by joaofnfernandes** [comment]
Thanks for reporting this @martencassel. It seems that this command is not available anymore and we forgot to remove it from the docs.
