### ISSUE TITLE
Section "Docker for Mac and Docker for Windows" needs clarification

### ISSUE THREAD

**Issue by Kwadz** [docker/docker.github.io#5460]
### Problem description

The sentence _"Modifying the storage driver on these platforms is not supported"_ can be confusing.
Are we talking about the commercial support or the technical ability to change the storage driver?

### Problem location

At the section [Docker for Mac and Docker for Windows](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-for-mac-and-docker-for-windows)

> Docker for Mac and Docker for Windows are intended for development, rather than production. Modifying the storage driver on these platforms is not supported.

### Project version(s) affected

Docker for Mac and Docker for Windows 

### Suggestions for a fix

Make some clarification.

**Comment by mistyhacks** [comment]
What it means is that it is not possible. :)

**Comment by Kwadz** [comment]
@mistyhacks, if it means that it's not possible, then the statement is wrong according to [this discussion](https://stackoverflow.com/questions/39455764/change-storage-driver-for-docker-on-os-x).

To be sure, I just tested and I have been able to change from overlay2 to aufs and from aufs to overlay2, using Server Version: 17.09.0-ce.

![screen shot 2017-12-18 at 11 07 37](https://user-images.githubusercontent.com/1472599/34100742-c1b03b4c-e3e3-11e7-8059-485e72719bd7.png)

**Comment by mistyhacks** [comment]
OK, even if it is technically possible, we do not test it at all. There should be no reason to adjust the storage driver on Docker for Mac or Docker for Windows, as the storage driver is a deployment-time concern, and Docker for Mac and Docker for Windows are for local development only.

cc/ @dsheets who I remember talking to about this before.
