### ISSUE TITLE
Docs / example inconsistency for docker load

### ISSUE THREAD

**Issue by titpetric** [docker/docker.github.io#5461]
File: [engine/reference/commandline/load.md](https://docs.docker.com/engine/reference/commandline/load/), CC @mistyhacks

The docs say that `docker load` takes a tar file, while the example specifically references importing a `.tar.gz` file. Either the example is wrong and docker load errors out on that example, or the documentation is incomplete and gzipped tar file imports are enabled as well. Which one is it? ;)

Best,
Tit

**Comment by titpetric** [comment]
p.s. gzipped tar files are supported.

**Comment by joaofnfernandes** [comment]
Ye, it's not really obvious if `docker load` supports both `tar` and `tar.gz` or just the latter.

**Comment by mistyhacks** [comment]
Addressed in https://github.com/docker/cli/pull/789.
