### ISSUE TITLE
Unable to find docker-ce for Ubuntu 17.10

### ISSUE THREAD

**Issue by blackOcean** [docker/docker.github.io#5464]
File: [engine/installation/linux/docker-ce/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/), CC @mistyhacks 

Thanks to this @levsthings https://gist.github.com/levsthings/0a49bfe20b25eeadd61ff0e204f50088, it is working. I hope you will fix it ASAP because it cost me almost an hour for this. :+1:

**Comment by mistyhacks** [comment]
17.10 CE was an Edge release and became unsupported as soon as 17.11 CE was released. See https://docs.docker.com/engine/installation/#updates-and-patches.

In addition, Aardvark was not yet supported by Docker at the time 17.10 CE came out, so no packages were created for it.
