### ISSUE TITLE
STATUS column is not mentioned in the documentation; 

### ISSUE THREAD

**Issue by eromoe** [docker/docker.github.io#5470]
From https://github.com/moby/moby/issues/35740

I request docker swarm need `start node` command .  But it seems I misunderstand `STATUS` column which is not mentioned in the documentation;

Please provide a method to indicate how to get `Down` node back (The `Down` nodes are actually running, just status is `Down` )

File: [engine/swarm/manage-nodes.md](https://docs.docker.com/engine/swarm/manage-nodes/), CC @mistyhacks

**Comment by mistyhacks** [comment]
@stevvooe @nishanttotla any idea? Is this really a docs issue or a feature request?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
