### ISSUE TITLE
clarify "multiple Compose files" in COMPOSE_FILE

### ISSUE THREAD

**Issue by debuglevel** [docker/docker.github.io#5472]
File: [compose/reference/envvars.md](https://docs.docker.com/compose/reference/envvars/), CC @gbarr01

The documentation states that

> This variable supports multiple Compose files separated by a path separator"

But it does not make it 100% clear whether the first file found is used (like `$PATH`) or all of them are used (like `docker-compose -f 1.yml -f 2.yml`)

It would be great if it would be clarified which one applies :-)

**Comment by hansbogert** [comment]
I'm not sure how the documentation is ambiguous or unclear. All of the configurations will be used. In fact, if one of the files is not found, it will fail; for example,

    ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.dev.yml'

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
