### ISSUE TITLE
Add additional explanation for security aspects of the install script

### ISSUE THREAD

**Issue by CodingSpiderFox** [docker/docker.github.io#5478]
The documentation says

"Always examine scripts downloaded from the internet before running them locally." (https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-convenience-script)

What I would like to have next to this warning message is a link to some documentation about which security risks I can run into when I do not examine the script. Which attack vectors exist, etc.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
