### ISSUE TITLE
404 at /compose/yml/

### ISSUE THREAD

**Issue by yuyilei** [docker/docker.github.io#5495]
URL: /compose/yml/

**Comment by joaofnfernandes** [comment]
@yuyilei can you tell where you click that lead you to that url?

**Comment by johndmulhausen** [comment]
This URL is not a thing and hasn't been since I've been here which is over a year. Searching for links to such a thing also turned up nothing.

**Comment by JimGalasyn** [comment]
I don't see this link anywhere in our docs set.
