### ISSUE TITLE
GCE Driver Examples does not work without overlay2 storage driver

### ISSUE THREAD

**Issue by hudovisk** [docker/docker.github.io#5497]
Please add the need of `--engine-storage-driver overlay2` to the examples.

File: [machine/drivers/gce.md](https://docs.docker.com/machine/drivers/gce/), CC @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
