### ISSUE TITLE
Registry broken links /configuration/

### ISSUE THREAD

**Issue by selckin** [docker/docker.github.io#5500]
For example 
https://docker.github.io/registry/deploying/#support-for-lets-encrypt 
has a link to 
https://docker.github.io/registry/configuration/#letsencrypt 
that 404s

**Comment by joaofnfernandes** [comment]
Oh... it seems that you're reading the Docker docs using https://docker.github.io, but you should be using https://docs.docker.com

Without going into much detail, the url you are using only contains a subset of the documentation, so those pages will give you a 404 error.

@johndmulhausen I don't think there's any reason for us to be serving the docs on github.io anymore. Can you disable it?

**Comment by johndmulhausen** [comment]
As Joao mentions, these errors do not occur on the real URL, which is https://docs.docker.com/registry/configuration/#letsencrypt

**Comment by joaofnfernandes** [comment]
@johndmulhausen so why are we still serving https://docker.github.io?
