### ISSUE TITLE
docker enterprise edition menu item is not clickable

### ISSUE THREAD

**Issue by vikstrous** [docker/docker.github.io#5511]
### Problem description
![screenshot](https://user-images.githubusercontent.com/482425/33967227-69f92b72-e017-11e7-9443-326ae4451119.png)

### Problem location
every page

### Project version(s) affected
n/a

### Suggestions for a fix
Test on different screen sizes?

**Comment by johndmulhausen** [comment]
cc @jsouth

**Comment by jsouth** [comment]
@johndmulhausen - on it!
