### ISSUE TITLE
use ip command instead of brctl

### ISSUE THREAD

**Issue by Niemi** [docker/docker.github.io#5515]
File: [engine/userguide/networking/default_network/build-bridges.md](https://docs.docker.com/engine/userguide/networking/default_network/build-bridges/), CC @mistyhacks 

[bridge up]
ip link add name br0 type bridge
ip link set dev br0 up
[bridge down]
ip link del name br0

**Comment by joaofnfernandes** [comment]
Updated the title to better reflect what the issue is about.
@Niemi if you've bested this out and know that this works, you should create a pull request to help us fix the docs 🌈
