### ISSUE TITLE
docker run --restart=failure should be --restart=on-failure 

### ISSUE THREAD

**Issue by philiiiiiipp** [docker/docker.github.io#5516]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/), CC @mistyhacks

Under `Restart policies (–restart)` it says `no`, `failure` and `always`. Looking at the linked page [https://docs.docker.com/engine/reference/run/#restart-policies-restart](https://docs.docker.com/engine/reference/run/#restart-policies-restart) it should not be `failure` but `on-failure[:max-retries]` and another option `unless-stopped` is also available.

**Comment by mistyhacks** [comment]
Since this content is generated from the code, it is very likely that the CLI reference is correct and the run reference is wrong. @thaJeztah PTAL or delegate.

**Comment by thaJeztah** [comment]
That part of the `engine/reference/commandline/run.md` is not automatically generated; looks to be accidentally modified in https://github.com/docker/cli/commit/ddadd3db494ce568a6b847932677f837802ea6b5#diff-505c72218d90da970c16fdbf0b4f613cL551 (I see GitHub decided to "collapse" / "hide" that file, so it may have gone overlooked in the review

I can open a PR to fix it

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/cli/pull/754
