### ISSUE TITLE
Document network diagnostic

### ISSUE THREAD

**Issue by fcrisciani** [docker/docker.github.io#5518]
### Problem description
New tool introduced by https://github.com/moby/moby/pull/35677

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Project version(s) affected
17.12

### Suggestions for a fix
This is what I have so far: https://docs.google.com/document/d/1ShFRVl3ut5-MaZN-sROwnczg5szOJPgTQ6of-xUhHKE/edit#heading=h.1p5fzj10w975

**Comment by mistyhacks** [comment]
Thanks, see #5555! 👍
