### ISSUE TITLE
IPVS connection timeouts

### ISSUE THREAD

**Issue by fcrisciani** [docker/docker.github.io#5519]
### Problem description
When using docker services on an overlay with mode VIP, the load balancer used is based on IPVS.
IPVS has some timeouts that can be retrieved with the command:
```
ipvsadm -l --timeout
Timeout (tcp tcpfin udp): 900 120 300
```
Now for example if a TCP connection from a service to anther service using the VIP is left idle with no traffic for more than 900s the IPVS state will be cleared up from the ipvs connection table, after that point if the service tries again to use this connection, it won't work.

### Problem location
https://docs.docker.com/engine/swarm/networking/

### Suggestions for a fix

We should come up with some information that better describe this condition and suggests workaround like: keepalive configuration at application level or kernel level.

@selansen maybe you can add the suggestion after your test here.

**Comment by ordenador** [comment]
somebody have a service for replicate the problem?

**Comment by athilaelhuno** [comment]
Hi.
We are having a problem when replicate the service to 2 or more replicas, when replicate the service I do make a request his is answering good but in another request is denied, so far the only solution is replicate to 1. I don't know if IPVS is our problem, it is a random issue.
