### ISSUE TITLE
Clarify syslog format defaults and tag options

### ISSUE THREAD

**Issue by armchairlinguist** [docker/docker.github.io#5524]
File: [engine/admin/logging/syslog.md](https://docs.docker.com/engine/admin/logging/syslog/), CC @mistyhacks 

Note: I'd be happy to eventually turn this issue into a PR, but thought it merited some discussion first.

Essentially, the document is a bit confusing on two points: which syslog format will be used by default, and what the tag should look like.

1. Format defaults: The document does mention that the default format is "local UNIX syslog format", but only in the detailed options - the very top of the document mentions RFC5424, and it's easy for someone who doesn't read through all the options to think that's the default. (That's what I thought, the first few times I read through it.) So my first suggestion is that it should be a little clearer that the default is not RFC5424 and doesn't include a value for the hostname; this is especially useful for anyone intending to use the syslog driver with a remote endpoint.

2. Tag format: There's no explicit mention in the options section that the log tag is expected to be a single string not separated by a space, although all the given examples do show that (which is great). The effect of adding spaces to the value varies depending on the selected format, but the results generally are odd, so specifying that space isn't intended to be a separator between parts of a tag might be a good idea.

I'd love to hear thoughts - it's possible this is too much of an edge case to be worthwhile, but my hope is that an added sentence or two could clarify these and save readers from any associated hassles.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
