### ISSUE TITLE
Have archives use master docs for /datacenter

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#5526]
It is confusing for Enterprise users who select the version of engine they are running (currently 17.06) but are unable to find docs there for the version of UCP/DTR they are running (soon to be 3.0 and 2.5, respectively).

`Dockerfile` should be modified for the archived versions to pull `/datacenter` from upstream. We should also consider creating a sub toc.yaml nav file that only has `/datacenter` contents in it so that can be "included" in both the master/current nav and the archives' navs.

**Comment by mistyhacks** [comment]
@joaofnfernandes see the way I did this for `docker-hub/`, `docker-store/`, `samples/` and friends in #5231 and I think you can just add `datacenter` to the same list. You'll need to do it manually for each archive that already exists (replace `datacenter/index.html` with a redirect to the live page you want on docs.docker.com, and remove all other contents of `datacenter/` in the archive, and also update the TOC YAML in the archive. Though you have to do it manually in existing archives, set up the script in master to do the right thing for the next person making the archive.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
