### ISSUE TITLE
Kitematic installation

### ISSUE THREAD

**Issue by 86c26** [docker/docker.github.io#5548]
In this documentation is written, that kitematic is installed with Docker (The installation provides Docker Engine, Docker CLI client, Docker Compose, Docker Machine, and **Kitematic**.) But when I install Docker, i have to download Kitematic separately.

File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/), CC @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
