### ISSUE TITLE
Missing port 2379 in firewall list

### ISSUE THREAD

**Issue by CallJamesCW** [docker/docker.github.io#5569]
File: [datacenter/ucp/2.2/guides/admin/install/system-requirements.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/system-requirements/), CC @jimgalasyn

I opened the ports listed, but my swarm join wouldn't complete until I opened 2379 on my manager nodes.

**Comment by JimGalasyn** [comment]
Hi @CallJamesCW , thanks for the feedback!  The behavior you're describing is what we would expect if port **1**2379 was blocked, but not 2379; `etcd` listens on 2379 internal to the container, not on the host; that's what 12379 maps onto.

Can you `docker container ls` and `docker system info` on a manager node to see if you have an unusual port mapping?

Also:  did you set up your management plane up on 2379 (instead of the default 2377)? You should be able to diagnose this from whatever `docker system info`  reports for the manager address.

**Comment by CallJamesCW** [comment]
[5569.txt](https://github.com/docker/docker.github.io/files/1572678/5569.txt)
Jim,

I have 12379 open on my firewall, but I’m guessing my IPTables chain could be interfering with the forwarding from 12379 to 2379. I did not deliberately change the management plane mapping. Here is the IPTables log entry that led me to open up 2379
Dec 19 10:05:24 docker-prd-ucp-01 kernel: [77177.907183] IPTables-Dropped: IN=ens160 OUT=docker0 MAC=00:50:56:b0:5f:5b:00:50:56:b0:47:c1:08:00 SRC=10.32.0.18 DST=172.17.0.2 LEN=60 TOS=0x00 PREC=0x00 TTL=62 ID=20363 DF PROTO=TCP SPT=60448 DPT=2379 WINDOW=29200 RES=0x00 SYN URGP=0

PFA the `docker container ls` and `docker system info` results.

Thank you,
-James

**Comment by BillMills** [comment]
Heya James, 

As you say, the logs you posted look good to me, nothing funny there. I can cause a worker join to hang by blocking forwards to 2379, so your forwarding theory looks like it might be correct; could you please post your manager and worker iptables rules, and indicate what you changed to get things working?

Thing is, the table you mention is trying to indicate what ports need to be open for communication between managers and workers, which is a bit different than being able to forward packets to a port inside a container's network namespace - though both need to be clarified. I agree the table you linked could use a bit of work on this matter; Jim and I are looking into it presently. Thanks for the report, let us know on those iptables rules just so we can really nail this down.

**Comment by CallJamesCW** [comment]
I'm loading these rules with iptables-restore -n to disable the default flushing. So far I'm using the same rules on managers and workers to keep it easier to manage. All of my managers and workers are in 10.32..0.0/24.

*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:FILTERS - [0:0]
:DOCKER-USER - [0:0]

-F INPUT
-F DOCKER-USER
-F FILTERS

-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp --icmp-type any -j ACCEPT
-A INPUT -j FILTERS

-A DOCKER-USER -i ens160 -j FILTERS

-A FILTERS -m state --state ESTABLISHED,RELATED -j ACCEPT
-A FILTERS -m state --state NEW -m tcp -p tcp -m multiport --dports 22,80,443,8080,8443 -s 10.16.65.128/25 -j ACCEPT
-A FILTERS -m state --state NEW -m tcp -p tcp -m multiport --dports 22,80,443,8080,8443 -s 10.32.0.0/24 -j ACCEPT
-A FILTERS -m state --state NEW -m tcp -p tcp -m multiport --dports 22,80,443,8080,8443 -s 10.32.3.0/24 -j ACCEPT
-A FILTERS -m state --state NEW -m tcp -p tcp -m multiport --dports 22,80,443,8080,8443 -s 10.32.6.0/24 -j ACCEPT
-A FILTERS -m state --state NEW -i docker0 -m tcp -p tcp -m multiport --dports 22,80,443,8080,8443 -s 172.17.0.0/24 -j ACCEPT

-A FILTERS -m state --state NEW -m tcp -p tcp -m multiport --dports 2376:2377,2379,7946,12376,12379:12387 -s 10.32.0.0/24 -j ACCEPT
-A FILTERS -m state --state NEW -i docker0 -m tcp -p tcp -m multiport --dports 2376:2377,2379,7946,12376,12379:12387 -s 172.17.0.0/24 -j ACCEPT

-A FILTERS -m state --state NEW -m udp -p udp -m multiport --dports 7946,4789 -s 10.32.0.0/24 -j ACCEPT
-A FILTERS -m state --state NEW -i docker0  -m udp -p udp -m multiport --dports 7946,4789 -s 172.17.0.0/24 -j ACCEPT

-A FILTERS -m state --state NEW -p 50 -s 10.32.0.0/24 -j ACCEPT

-A FILTERS -m limit --limit 2/min -j LOG --log-prefix "IPTables-Dropped: " --log-level 4
-A FILTERS -j REJECT --reject-with icmp-host-prohibited

COMMIT


James Chabot-Weingart
Systems Administrator
Student Affairs IT at the University of Connecticut
(860) 486-4559

                        Student Affairs
One Division. Multiple Services. Students First

**Comment by BillMills** [comment]
So, if I stand up a brand new UCP cluster with nothing but its first manager up and running, Docker creates the `DOCKER` chain in my iptables:

```
Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             ip-172-17-0-4.ec2.internal  tcp dpt:2376
ACCEPT     tcp  --  anywhere             ip-172-17-0-5.ec2.internal  tcp dpt:12382
ACCEPT     tcp  --  anywhere             ip-172-17-0-6.ec2.internal  tcp dpt:12381
ACCEPT     tcp  --  anywhere             ip-172-17-0-7.ec2.internal  tcp dpt:12380
ACCEPT     tcp  --  anywhere             ip-172-17-0-7.ec2.internal  tcp dpt:2379
ACCEPT     tcp  --  anywhere             ip-172-17-0-8.ec2.internal  tcp dpt:12384
ACCEPT     tcp  --  anywhere             ip-172-17-0-8.ec2.internal  tcp dpt:12383
ACCEPT     tcp  --  anywhere             ip-172-17-0-9.ec2.internal  tcp dpt:pharos
ACCEPT     tcp  --  anywhere             ip-172-17-0-10.ec2.internal  tcp dpt:2375
ACCEPT     tcp  --  anywhere             ip-172-17-0-11.ec2.internal  tcp dpt:12387
ACCEPT     tcp  --  anywhere             ip-172-17-0-12.ec2.internal  tcp dpt:pharos
ACCEPT     tcp  --  anywhere             ip-172-17-0-13.ec2.internal  tcp dpt:webcache
```

This `DOCKER` chain is stuck near the top of my `FORWARD` chain, allowing all the forwards UCP component containers need to communicate - including the forward to 2379 you mentioned, @CallJamesCW. In your case, you have a similar rule in your `FILTERS` chain, which in turn is at the top of your `DOCKER-USER` chain, which by default is at the top of the `FORWARD` chain - meaning the `REJECT` at the bottom of your `FILTERS` is probably cutting off all subsequent rules in your `FORWARD` chain.

So, my questions for you are:
 - Do you have a `DOCKER` chain like mine on your UCP manager? Is it in your `FORWARD` chain?
 - Do you need to have that `REJECT` at the bottom of your `FILTERS` chain? `FORWARD` normally `DROP`s all by default, so all that `REJECT` is doing is cutting off the `DOCKER` (and `DOCKER-ISOLATION` and the rest of your `FORWARD`) chain, if things are set up the way I guess above. If you need it you need it, but if that just snuck in there as a default when creating a new chain, it might be messing up the default chains Docker declares when UCP is first set up.

**Comment by BillMills** [comment]
If, on the other hand, we're trying to write really restrictive iptables rules, the tightest I've been able to write and still have a worker join successfully are, on the manager, at the top of the `FORWARD` chain, where `10.10.5.83` is my worker:

```
-A FORWARD -s 10.10.5.83 -d 172.17.0.13/32 -p tcp --dport 8080 -j ACCEPT
-A FORWARD -s 10.10.5.83 -d 172.17.0.7/32 -p tcp --dport 2379 -j ACCEPT
-A FORWARD -s 10.10.5.83 -d 172.17.0.10/32 -p tcp --sport 12376 -j ACCEPT
-A FORWARD -s 10.10.5.83 -j DROP
```

 - `-A FORWARD -s 10.10.5.83 -d 172.17.0.13/32 -p tcp --dport 8080 -j ACCEPT` so packets from the worker can get forwarded to the `ucp-controller` (ie web frontend) container
 - `-A FORWARD -s 10.10.5.83 -d 172.17.0.7/32 -p tcp --dport 2379 -j ACCEPT` the same, but to the etcd db for registration in the classic node list
 - `-A FORWARD -s 10.10.5.83 -d 172.17.0.10/32 -p tcp --sport 12376 -j ACCEPT` so the `ucp-proxy` on the worker can respond to my `ucp-swarm-manager` container.

**Comment by JimGalasyn** [comment]
@CallJamesCW, if you're all set up, I'm closing this issue. Please feel free to re-open. Thanks for all of the guidance, @BillMills!
