### ISSUE TITLE
Add auto-testing option only in dockercloud

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [docker/docker.github.io#5580]
It will be helpful if the build before the test hook can be disabled, saving a lot of time on the ci.

Basically going straight to `Starting Test in *****.test.yml...
Building sut` and skipping the `Starting build of index.docker.io/....`. As some teams only want to see if their tests will fail or not before clicking a source code repository's Merge Button

And then after merging, the automated build will be the only one triggered. This will save a lot of time on ci for a lot of teams using dockercloud

**Comment by mistyhacks** [comment]
This is not a docs issue. I will pass along your feedback to the Docker Cloud team. Thanks!

**Comment by Dean-Christian-Armada** [comment]
But my question now is, is it currently possible using hooks?
