### ISSUE TITLE
Bad spacing in markdown link?

### ISSUE THREAD

**Issue by mor1** [docker/docker.github.io#5582]
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/), CC @mistyhacks

Looking at the rendered page, in the table for the option `types` I see:

```
volume: mounts a [managed volume](volume_create.md) into the container
```

That is, it looks like the text `managed volume` is supposed to link to `volume_create.md` but isn't-- perhaps there's whitespace or something between the `]` and `(`?

**Comment by mistyhacks** [comment]
This has already been fixed upstream in the `docker/cli` repository and will eventually trickle down into the docs. Thanks!
