### ISSUE TITLE
Fix broken link for "Manage data in containers"

### ISSUE THREAD

**Issue by drewmoseley** [docker/docker.github.io#5594]
File: [engine/tutorials/index.md](https://docs.docker.com/engine/tutorials/), CC @mistyhacks 
The link pointed to by the text "Manage data in containers" is incorrect.
It currently points to "https://docs.docker.com/engine/tutorials/dockervolumes/" which does not exist.  I suspect it should be pointing to "https://docs.docker.com/engine/admin/volumes/volumes/" instead.

**Comment by mistyhacks** [comment]
The first link actually redirects to the second, so it is working as intended. Be sure Javascript is enabled and clear your cache, and re-open this issue if the link still does not work for you.
