### ISSUE TITLE
Update UCP logs to ELK stack example

### ISSUE THREAD

**Issue by NicoTexas** [docker/docker.github.io#5597]
File: [datacenter/ucp/2.2/guides/admin/configure/store-logs-in-an-external-system.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/store-logs-in-an-external-system/), CC @JimGalasyn 

I tried to apply the example to send the UCP logs to ELK 6.1.0 and the filter was causing jsonparsing errors in Logstash.

`[2017-12-21T05:38:57,812][WARN ][logstash.filters.json    ] Error parsing json {:source=>"message", :raw=>"<7>2017-12-21T05:38:57Z ucp-controller-192.168.141.31 /bin/controller[1]: {\"level\":\"debug\",\"msg\":\"Writing message to listener\",\"time\":\"2017-12-21T05:38:57Z\"}", :exception=>#<LogStash::Json::ParserError: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (byte[])"<7>2017-12-21T05:38:57Z ucp-controller-192.168.141.31 /bin/controller[1]: {"level":"debug","msg":"Writing message to listener","time":"2017-12-21T05:38:57Z"}"; line: 1, column: 2]>}`

This is because the log message is not plain json

I was able to get better logs with

```
filter {
    grok {
        match => { "message" => "%{SYSLOG5424PRI}%{TIMESTAMP_ISO8601:time} %{SYSLOGHOST} %{SYSLOGPROG}: %{GREEDYDATA:ucplog}"}
    }
    json {
        source => "ucplog"
    }
}
```

This is not perfect but Logstash actually parses the logs

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
