### ISSUE TITLE
URL are broken or target not available

### ISSUE THREAD

**Issue by ifrh** [docker/docker.github.io#5598]
File: [engine/installation/linux/ubuntu.md](https://docs.docker.com/engine/installation/linux/ubuntu/), CC @mistyhacks

**Comment by mistyhacks** [comment]
All of the links on that URL work for me. Please reopen with more details if you are still having trouble.

**Comment by ifrh** [comment]
At [https://docs.docker.com/engine/installation/linux/ubuntu/ ](https://docs.docker.com/engine/installation/linux/ubuntu/ )
if I click on **Install Docker CE on Ubuntu** which points to that 
URL [https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu.md
) 
this error-page was and is on my display: 
![screenshot_docker_docu_failed](https://user-images.githubusercontent.com/3845055/34416787-780a364a-ebf5-11e7-8aec-3b671d8e42d2.jpg)

**Comment by ifrh** [comment]
@mistyhacks I cannot reopen this report.
