### ISSUE TITLE
Building container fails. 

### ISSUE THREAD

**Issue by stmorgan** [docker/docker.github.io#5606]
File: [engine/userguide/storagedriver/imagesandcontainers.md](https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/), CC @mistyhacks 

When I run the command to build the container I get this error: 

    scott@desktop-ml:~/docker/cow-test$ docker build -t acme/my-base-image:1.0 -f Dockerfile.base
    "docker build" requires exactly 1 argument.
    See 'docker build --help'.

    Usage:  docker build [OPTIONS] PATH | URL | - [flags]

     Build an image from a Dockerfile

My Docker version is thus: 

    scott@desktop-ml:~/docker/cow-test$ docker -v
    Docker version 17.11.0-ce, build 1caf76c

Ubuntu Version: 

    scott@desktop-ml:~/docker/cow-test$  lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 17.10
    Release:	17.10
    Codename:	artful

Thanks!

**Comment by mistyhacks** [comment]
If you look at the line in the docs carefully, notice that it ends in a `.`:

```
$ docker build -t acme/my-base-image:1.0 -f Dockerfile.base .
```

I know that dot is a little hard to see. In UNIX, `.` means the current directory. The `docker build` command takes multiple flags / options (things that start with a `-` or `--`), but only one argument (things that stand on their own). The argument is the path where Docker should look for the files, also called the context. The command sets the path to `.`. That's what you are missing. :)

**Comment by stmorgan** [comment]
Yes, you are right. Thanks!
