### ISSUE TITLE
Docker machine generic driver ssh key problems

### ISSUE THREAD

**Issue by rubidot** [docker/docker.github.io#5608]
File: [machine/drivers/generic.md](https://docs.docker.com/machine/drivers/generic/), CC @gbarr01 

I could not get my ubuntu server working with docker-machine until I did `ssh-add ~/.ssh/id_rsa` and omitted the `--generic-ssh-key` option, according to instructions here: https://forums.docker.com/t/docker-machine-generic-driver-to-remote-host-using-ssh/4360/2

I'd like to at least see some notes in the generic driver documentation about this issue, as it seems like it's been around a few years and trying to use docker-machine based on this documentation just doesn't work.

Thanks for your efforts.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
