### ISSUE TITLE
Wrong timeout and backoff parameters

### ISSUE THREAD

**Issue by vsizov** [docker/docker.github.io#5612]
File: [registry/configuration.md](https://docs.docker.com/registry/configuration/), CC @joaofnfernandes

Look at the https://docs.docker.com/registry/configuration/#notifications You can find parameters  `timeout: 500` and `backoff: 1000` they are all wrong. Should be 500ms and 1s.
For details look at this MR https://github.com/docker/distribution/issues/2231

**Comment by thaJeztah** [comment]
From that issue;

> The above when I run with registry:2.3, it works perfectly.

@stevvooe was that an intentional change, or was the format always intended to be a strong value, and have a unit included?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
