### ISSUE TITLE
Update screenshot to say "Support Dump" instead of "Download Logs"

### ISSUE THREAD

**Issue by vsaraswat** [docker/docker.github.io#5617]
Screenshot on this page should be updated to include "Support Dump" rather than "Download Logs"

File: [datacenter/ucp/2.2/guides/get-support.md](https://docs.docker.com/datacenter/ucp/2.2/guides/get-support/), CC @jimgalasyn

**Comment by joaofnfernandes** [comment]
This was addressed with an upstream PR.
