### ISSUE TITLE
Confusing and undocumented cpu* parameters

### ISSUE THREAD

**Issue by asarkar** [docker/docker.github.io#5622]
Moving to this repo as suggested in https://github.com/docker/compose/issues/5509

According to the [doc](https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources), the following parameters were added in v2.2. The corresponding PR appears to be https://github.com/docker/compose/pull/4835

However, I couldn't find any explanation whatsoever of what these parameters do. Doc says:
> analogous to its docker run counterpart

But, [docker run](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources) doesn't have these parameters. Neither does [this](https://docs.docker.com/engine/admin/resource_constraints/#cpu).

So I'm looking at `cpu_count: 2` and wondering how in the world is it different from `cpus: 2`. What does the word `cpu_count` mean to anyone who speaks English? Two counts of cpu. Well, that's exactly what `cpus` is supposed to be.

Can we stop this guessing game and clearly document the parameters?

**Comment by asarkar** [comment]
OS specific parameters look like a bad idea, because by that line of thinking, we may soon have 32-bit vs 64-bit, and AMD vs Intel parameters. As a user, I'd like to have Docker deal with the underlying idiosyncrasies, and not require me to read from a manual every time I have to work with Docker. We should be past this point.
![1](https://user-images.githubusercontent.com/1302775/34365267-43af3ebc-ea43-11e7-9e19-0e417c8f783e.jpg)

**Comment by mistyhacks** [comment]
@shin- can you point to which parameters should be used?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
