### ISSUE TITLE
Color difference between link text and regular text too subtle

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#5623]
@jsouth I can agree with #5615 that on some monitors that the difference in color between clickable/link text and normal text is probably too subtle. 

See: https://docs.docker.com/test/#links-and-images with dark mode turned on

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
