### ISSUE TITLE
New JS navigation doesn't remember where you were

### ISSUE THREAD

**Issue by mistyhacks** [docker/docker.github.io#5626]
The navigation does not remember iast-open position after a soft or hard page-reload (without or with using Shift). This will cause users problems with easily navigating to the previous or next topic, in the absense of in-page prev/next markers.

**This is a regression** from the static HTML TOC.

Probable solution: Have the page store info about what should be open when viewing it. It is likely the page already has this info, since the TOC opens to the correct location when the page is first loaded.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

0p
