### ISSUE TITLE
Update Redis example to fix possible race condition

### ISSUE THREAD

**Issue by mistyhacks** [docker/docker.github.io#5631]
See https://github.com/docker/docker.github.io/pull/5602#issuecomment-354110949

@shin- you were nominated by @thaJeztah as someone who might be able to update this example.

**Comment by thaJeztah** [comment]
Thanks haha

Yes; we were discussing that the example should have a retry-loop if the redis service is not available (which is also best practice to make services resilient again failures of other services)

Came up in https://github.com/docker/docker.github.io/pull/5602#issuecomment-354110949 - which can then be reverted

**Comment by shin-** [comment]
I'll take a look today. :) Making apps failure resilient is probably a topic worthy of its own page to be honest.

As a side note, we should really avoid using `links` in examples, since its usage is discouraged in favor of `depends_on` nowadays (except for v1 files)

**Comment by thaJeztah** [comment]
Thanks @shin- ! I even try to avoid `depends_on`, because it only helps you for the initial deploy, but not for updates (the reason it's not supported for swarm services).

And definitely +1 to have a section on making apps resilient (if we find the time)
