### ISSUE TITLE
Inconsistent documentation for port publishing

### ISSUE THREAD

**Issue by jeremysmitherman** [docker/docker.github.io#5632]
### Problem description

Two places in the documentation describe the port publishing syntax for swarm differently. 

### Problem location
- I saw a problem on the following URL: https://docs.docker.com/engine/reference/commandline/service_create/#publish-service-ports-externally-to-the-swarm--p-publish  AND https://docs.docker.com/engine/swarm/services/#publish-a-services-ports-using-the-routing-mesh

The first page suggests incorrectly that the TARGET-PORT is what will be accessible to the swarm, the second page correctly states that the port made accessible through the mesh is the PUBLISHED-PORT

### Suggestions for a fix

Reconcile the differences in the documentation

**Comment by mistyhacks** [comment]
Actually, the first link uses content that is maintained in an upstream repository. This was actually fixed there (see https://github.com/docker/cli/pull/746), but has not been cherry-picked into the correct place (the `docker/docker-ce` repository's 17.12 branch) where we can use it in the docs. This will be  corrected when 17.12 CE is released.
