### ISSUE TITLE
Mention that we only support the stock kernel that comes with your (supported) OS

### ISSUE THREAD

**Issue by mistyhacks** [docker/docker.github.io#5634]
We do not support third-party or custom-compiled kernels because we have no way to know what changed or test them. We need to note in the docs that we only support using the kernel that your OS ships with or that the OS vendor officially updates. I think we also don't support  "preview" or "unstable" or "beta" kernels or anything like that.

For CE we don't talk about support but about things not being tested or expected to work. For EE we talk about support.

c/ @thaJeztah

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
