### ISSUE TITLE
Docker CE support for arm64 too

### ISSUE THREAD

**Issue by vielmetti** [docker/docker.github.io#5638]
File: [engine/installation/linux/docker-ce/debian.md](https://docs.docker.com/engine/installation/linux/docker-ce/debian/), CC @mistyhacks 

> Docker CE is supported on both x86_64 (or amd64) and armhf architectures for Jessie and Stretch.

As of Docker CE 17.12, there's also Debian support for arm64; the documentation should reflect this.

**Comment by JeffUnderhill** [comment]
Note the server table on https://docs.docker.com/install/ doesn't match the https://get.docker.com/ script for Arm64/AARCH64 support (specifically fedora is missing in the table which is not good given [Fedora 28 Server now includes support for 64-bit ARM as a primary architecture](https://www.businesswire.com/news/home/20180501005148/en/Fedora-28-Generally)) - from the script:

aarch64-ubuntu-xenial
aarch64-ubuntu-bionic
aarch64-debian-jessie
aarch64-debian-stretch
aarch64-debian-buster
**aarch64-fedora-26
aarch64-fedora-27
aarch64-fedora-28**
aarch64-centos-7

Is it possible to get the table updated to reflect the script status?

On a related note none of the community edition images in https://store.docker.com/search?type=edition&offering=community appear to have ARM32 or ARM64 tags even though the images exist and some of the store pages reference support for Arm in the description <-- should this be a separate bug elsewhere to request updates to store? I see there's a 'feedback' e-mail for store so maybe I'll try that for this issue.

**Comment by gbarr01** [comment]
@joaofnfernandes

**Comment by JeffUnderhill** [comment]
@joaofnfernandes please let me know if there's something more I can do to help progress this documentation update?

FYI: I did send e-mail via the 'feedback' address for the second item mentioned above WRT to the community edition images missing the Arm tags in the Docker Store.

**Comment by tfoxnc** [comment]
@JeffUnderhill I will look into this issue and resolve it as soon as I can track down all the information needed.

**Comment by vielmetti** [comment]
Hi @ahh-docker - let me know if there's any additional info you need for this, it just came up again in conversation with a customer.

**Comment by JeffUnderhill** [comment]
Specific to my comment from Jul 10th the OS support matrix is now updated per https://github.com/docker/docker.github.io/pull/7799#issuecomment-445359122

https://docs.docker.com/engine/installation/linux/docker-ce/debian/ <-- this also seems to list arm64 now and is fixed

@vielmetti given the above can this issue be closed or are there additional outstanding items?

**Comment by JustinINevill** [comment]
Closing, old issue that will be addressed in upcoming refactor.
