### ISSUE TITLE
Document features of --tmpfs that don't exist for --mount

### ISSUE THREAD

**Issue by skycoop** [docker/docker.github.io#5640]
File: [engine/admin/volumes/tmpfs.md](https://docs.docker.com/engine/admin/volumes/tmpfs/), CC @mistyhacks

When describing the differences between `--tmpfs` and `--mount type=tmpfs`, the docs don't mention that some `--tmpfs` settings have not been implemented yet for `--mount type=tmpfs`. Specifically this is the ability to pass options like `exec`, `nosuid`, etc. (see https://docs.docker.com/engine/reference/run/#tmpfs-mount-tmpfs-filesystems).

I spent a while trying to figure out how to set the `exec` flag using either and was pretty stumped until I found a random issue in the docker-compose project that mentioned that `--tmpfs` could do this.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
