### ISSUE TITLE
Docs for run seem to be incorrect

### ISSUE THREAD

**Issue by SystemDisc** [docker/docker.github.io#5642]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/), CC @mistyhacks

The following line seems to contradict other mentions of `-d` and `--rm` in the docs.

> --rm=false: Automatically remove the container when it exits (incompatible with -d)

**Comment by thaJeztah** [comment]
Ah, yes, this used to be a conflicting option, but this changed in Docker 1.13, when the `--rm` was moved from the client to the daemon (see https://github.com/moby/moby/pull/20848)

**Comment by gbarr01** [comment]
Disregard the reference ... different page

**Comment by gbarr01** [comment]
For some reason, the docs don't update when we generate the yaml from docker-ce.  

docker/cli and  docker/docker-ce match. But not docs: 

https://github.com/docker/cli/blob/master/docs/reference/run.md#clean-up---rm
https://github.com/docker/docker-ce/blob/master/components/cli/docs/reference/run.md#clean-up---rm
https://docs.docker.com/engine/reference/run/#clean-up---rm

**Comment by mistyhacks** [comment]
Unless something has changed, you need to regenerate the YAML files and add them to the right place in the `_data` directory. It's in the docs for releasing. And you don't want them YAML files to be built against `docker-ce` `master` branch, but the branch you're trying to release.

**Comment by gbarr01** [comment]
Thanks,  @mistyhacks , nothing has changed and that's the issue. This doc is not being properly updated during YAML generation (against the proper branch).

**Comment by thaJeztah** [comment]
Oh, this is `reference/run.md`, not `reference/commandline/run.md`; it's a separate file and not auto-generated

**Comment by gbarr01** [comment]
A ha. What's the protocol? Copy/paste from docker-ce?

**Comment by thaJeztah** [comment]
I think it’s pulled in from the docker-ce repo, so we should backport it to the 18.03 branch in that repo (if it’s fixed in docker/cli)

**Comment by gbarr01** [comment]
Source page: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/docs/reference/run.md

**Comment by thaJeztah** [comment]
This should be fixed by https://github.com/docker/cli/pull/957 (backported to the 18.03 docs through https://github.com/docker/docker-ce/pull/519)

**Comment by gbarr01** [comment]
Yep, fixed. I was trying to get a handle on how this doc is generated and I got it now -- there's no actual file to diff.  From `_scripts/fetch-upstream-resources.sh`:

```
# Get a few one-off files that we use directly from upstream
wget -O ${SOURCE}/engine/reference/run.md https://raw.githubusercontent.com/docker/docker-ce/"$ENGINE_BRANCH"/components/cli/docs/reference/run.md || (echo "Failed engine/reference/run.md download" && exit -1)
# Adjust this one when Edge != Stable
wget -O ${SOURCE}/edge/engine/reference/run.md https://raw.githubusercontent.com/docker/docker-ce/"$ENGINE_BRANCH"/components/cli/docs/reference/run.md || (echo "Failed engine/reference/run.md download" && exit -1)
```
