### ISSUE TITLE
Support IBM Bluemix

### ISSUE THREAD

**Issue by ryardley** [docker/docker.github.io#5646]
File: [machine/drivers/soft-layer.md](https://docs.docker.com/machine/drivers/soft-layer/), CC @gbarr01

IBM Softlayer has been migrated to IBM Bluemix.

It is not clear as to whether or not docker-machine supports IBM bluemix. Clarification would be nice even if the new product is not supported.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
