### ISSUE TITLE
services and swarms sections require port 80 availability

### ISSUE THREAD

**Issue by mfschmidt** [docker/docker.github.io#5647]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/), CC @johndmulhausen 
I'd like to continue using port 4000 (or any available port) on a machine that already uses port 80 for standard http. It would be nice to have an aside in the tutorial about what to do if you can't take over port 80. Currently, running the tutorial "friendlyhello" app works alone on port 4000, but not in a swarm even when I try to configure the ports in the .yml file to host 4000.

**Comment by mfschmidt** [comment]
I eventually recognized that the port must be specified as "4000:80" and things work out OK. Is it possible to add that option to the getting-started? The first mention is in the docker-compose.yml file in [part3.md](https://docs.docker.com/get-started/part3/)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
