### ISSUE TITLE
Topic conflates bind mounts with volumes

### ISSUE THREAD

**Issue by mistyhacks** [docker/docker.github.io#5654]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/), CC @johndmulhausen 

The topic actually uses bind mounts but calls them volumes. It would be grand if we could rework it to actually use volumes, but I haven't properly reviewed. This was called out by @thaJeztah

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
