### ISSUE TITLE
Add example for Docker Hub webhooks

### ISSUE THREAD

**Issue by asif-khan17** [docker/docker.github.io#5656]
File: [docker-hub/webhooks.md](https://docs.docker.com/docker-hub/webhooks/), CC @johndmulhausen

This documentation for webhook is totally useless plz elaborate it with one example

**Comment by johndmulhausen** [comment]
This page has one thumbs up and over 50 thumbs down so I think @asif-khan17 is not alone.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
