### ISSUE TITLE
S3 Storage Configuration Changes Between DTR 2.2 and 2.3 

### ISSUE THREAD

**Issue by lmuchnick** [docker/docker.github.io#5657]
File: [datacenter/dtr/2.3/guides/release-notes.md](https://docs.docker.com/datacenter/dtr/2.3/guides/release-notes/), CC @joaofnfernandes 

Customer, PrismHR, upgraded from DTR 2.2.x to 2.3.x and could no longer push images.  After troubleshooting it was identified that there are additional configuration steps required for DTR 2.3 that were not required in DTR 2.2.  Customer has requested that we add a note in the release notes for DTR 2.3 to identify this change.

DTR 2.3 additional configuration steps:

`Configure your clients`

`If you’re using a TLS certificate in your storage backend that’s not globally trusted, you’ll have to configure all Docker Engines that push or pull from DTR to trust that certificate. When you push or pull an image DTR redirects the requests to the storage backend, so if clients don’t trust the TLS certificates of both DTR and the storage backend, they won’t be able to push or pull images. Learn how to configure the Docker client.`

`And if you’ve configured DTR to skip TLS verification, you also need to configure all Docker Engines that push or pull from DTR to skip TLS verification. You do this by adding DTR to the list of insecure registries when starting Docker.`

**Comment by joaofnfernandes** [comment]
@pdevine can you confirm this?

**Comment by bermudezmt** [comment]
@caervs would you know about these DTR 2.3 steps?

**Comment by caervs** [comment]
Yes. DTR has the ability to redirect engines to the storage backend for pulls. I'd have to look into it to confirm if this was introduced in `2.3`. The instructions specified make sense. You can also disable redirects in DTR but at the cost of potentially lower performance.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
