### ISSUE TITLE
Format flag arguments need quotes

### ISSUE THREAD

**Issue by understructure** [docker/docker.github.io#5658]
File: [engine/reference/commandline/swarm_ca.md](https://docs.docker.com/engine/reference/commandline/swarm_ca/), CC @mistyhacks 

Current:
docker node ls --format {{.ID}} {{.Hostname}} {{.Status}} {{.TLSStatus}}

Proposed:
docker node ls --format "{{.ID}} {{.Hostname}} {{.Status}} {{.TLSStatus}}"

Cheers!

-Maashu

**Comment by mistyhacks** [comment]
Filed upstream PR to fix this. Thanks!
