### ISSUE TITLE
Redundant and potentially confusing link in tutorial

### ISSUE THREAD

**Issue by sampablokuper** [docker/docker.github.io#5670]
File: [get-started/index.md](https://docs.docker.com/get-started/), CC @johndmulhausen

This page in the docs says:

> While we’ll define concepts along the way, it is good for you to understand [what Docker is](https://www.docker.com/what-docker) and [why you would use Docker](https://www.docker.com/use-cases) before we begin.

The first of those two links goes to https://www.docker.com/what-docker ; the second goes to https://www.docker.com/use-cases .

However, https://www.docker.com/use-cases responds with a 301 redirect to https://www.docker.com/what-docker . As such, the second link is redundant and likely to cause confusion for readers. (Especially for readers brand new to Docker, who are reading the first page of the tutorial for the first time.)

I suggest that this sentence should be re-worded as:

> While we’ll define concepts along the way, it is good for you to understand [what Docker is](https://www.docker.com/what-docker) before we begin.

**Comment by mistyhacks** [comment]
Hi @sampablokuper thanks for this catch. You can easily open a pull request for this change by clicking the "Edit this page" link at the right-hand side of the page. This would be a great contribution!

**Comment by sampablokuper** [comment]
I can't see an "Edit this page" link at the right-hand side of that page. Anyhow, PR submitted. Thanks :)

**Comment by mistyhacks** [comment]
<img width="1279" alt="Edit this page" src="https://user-images.githubusercontent.com/7674613/34657593-726cbf52-f3dc-11e7-98c7-abf622a92bec.png">

**Comment by sampablokuper** [comment]
As I said, that link isn't showing for me. (Maybe it requires JavaScript, which [would be a shortcoming worth fixing](https://unix.stackexchange.com/a/415243).)

Anyhow, thanks again for your encouragement, and for accepting the PR :)

**Comment by londoncalling** [comment]
@sampablokuper the site requires Javascript in order run navigation, Edit this page, and other features. I'm not sure if we have plans to remove dependency on this, but the page you linked to has an interesting discussion re: options to white list and/or block sites, and a follow-on comment noting   the irony that the comment thread itself about Javascript, requires Javascript :-) 

"Excuse me, although this helps against the attack, without JS, you wouldn't have been able to leave the answer here. This advice is similar to "stop using the Internet" (in 2018). – Moritz Both 2 days ago "

**Comment by sampablokuper** [comment]
@londoncalling, thanks for the reply.

Keeping a JavaScript requirement is equivalent to keeping a requirement that your users put themselves at risk. If you don't *already* have plans to remove that dependency, now would be a great time to start making such plans.

Fortunately, most aspects of the site already work fine without JS, and the edit link seems [easily fixable](https://github.com/docker/docker.github.io/pull/5689), so with any luck the plans won't need to be very complicated :)
