### ISSUE TITLE
Problems following "get-started" guide - part6

### ISSUE THREAD

**Issue by robbie70** [docker/docker.github.io#5671]
File: [get-started/part6.md](https://docs.docker.com/get-started/part6/), CC @johndmulhausen

I have been following the "get-started" guide and am currently trying to follow part6. But one of the steps I ran has now buggered up my whole docker `getstarted` environment and no commands I run are now able to run as before. I keep  getting the same error,
> C:\Program Files\Docker Toolbox\docker.exe: error during connect: Post 
https://192.168.99.102:2376/v1.33/containers/create: x509: cannot validate certificate for 
192.168.99.102 because it doesn't contain any IP SANs.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

I was following the steps on Docker Cloud to `bring your own swarm` thinking that the swarm I'd created in step5 I could bring into the Docker Cloud. The last good step I was able to run was,
> $ docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock dockercloud/registration
Unable to find image 'dockercloud/registration:latest' locally
latest: Pulling from dockercloud/registration
90f4dba627d6: Pull complete
49ab6bb20a7f: Pull complete
d185660c194b: Pull complete
Digest: sha256:11dbb757fc07870824d22030cb1034c4376cf9670e272ef8b0f393e6232d315d
Status: Downloaded newer image for dockercloud/registration:latest
Use your Docker ID credentials to authenticate:
Username: robbie70
Password:
>
>Available namespaces:
>* robbie70
Enter name for the new cluster [robbie70/npsxowoz8ks4vhy5bgu5gb3w7]: robbie70/getstartedlab
You can now access this cluster using the following command in any Docker Engine:
        docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client robbie70/getstartedlab

I then tried to connect to the Docker Cloud using the generated command above,
>$ docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client robbie70/getstartedlab

but get the error below,
>C:\Program Files\Docker Toolbox\docker.exe: error during connect: Post https://192.168.99.102:2376/v1.33/containers/create: x509: cannot validate certificate for 192.168.99.102 because it doesn't contain any IP SANs.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

And now any command I try to run, e.g.
>docker node ls,
>docker services ls,
>docker images ls,

gives me the same error message.

Can you please advise and maybe update the instructions to better take a new user through this process....

Kind Regards,
Robert Stannard

**Comment by psaint** [comment]
I have exactly the same problem following tutorial on **OSX** and using **Docker Community Edition** `Version 17.12.0-ce-mac49 (21995)`.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
