### ISSUE TITLE
.env file requirements should be documented

### ISSUE THREAD

**Issue by Jens-G** [docker/docker.github.io#5679]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01

First, the .env file needs to be UTF-8, which is common on Linux but not on Windows platforms, so it should be documented.

Next, there seems to be a problem with UTF-8 BOMs. If the file is stored with a BOM, the first line may not be read correctly, most likely because the BOM is interpreted as data. This should be documented as well (or maybe fixed)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
