### ISSUE TITLE
Most of the links at the dockerfile page don't work correctly

### ISSUE THREAD

**Issue by artus** [docker/docker.github.io#5681]
### Problem description

On the [Dockerfile](https://docs.docker.com/engine/reference/builder/) page, most links redirect to the [getting-started](https://docs.docker.com/get-started/) page instead their intended destination.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/builder/

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
