### ISSUE TITLE
Dockerfile reference typo

### ISSUE THREAD

**Issue by cuent** [docker/docker.github.io#5683]
I couldn't find the file ([engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/#add)) to fix the typo in the repository, but there is a small typo in the section _ADD_. In the first _Note_, _for_ is repeated.

CC @mistyhacks

**Comment by thaJeztah** [comment]
Thanks! That file is in the docker/cli repository. I opened a pull-request to fix: https://github.com/docker/cli/pull/792
