### ISSUE TITLE
Issue with polling processes in multi-service container script

### ISSUE THREAD

**Issue by bvwells** [docker/docker.github.io#5685]
### Problem description

The example script for running multiple services within a container has an issue. Sometimes the processes which have been launched from the entry point script can take a few seconds to start up and for the process tree to be updated to reflect the process name. Due to this, polling straight after the process has been launched can lead to the process not being found and the script exiting with a non-zero exit code.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/admin/multi-service_container/

### Project version(s) affected

N/A - Purely documentation.

### Suggestions for a fix

Wait after processes are launched to poll to see whether they have exited.

**Comment by bvwells** [comment]
Fixed in PR #5686.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
