### ISSUE TITLE
"Edit this page" link hidden by default

### ISSUE THREAD

**Issue by sampablokuper** [docker/docker.github.io#5688]
### Problem description

As stated. See https://github.com/docker/docker.github.io/issues/5670#issuecomment-355770943 .

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/get-started/

**Comment by johndmulhausen** [comment]
It's invisible by default, and made visible by JavaScript if you are viewing the page in a non-archive URL (i.e. from `/` and not from `/v17.09/`)
