### ISSUE TITLE
Unable to find documentation about how to expose ports from Kubernetes services

### ISSUE THREAD

**Issue by jnewland** [docker/docker.github.io#5690]
### Problem description

After installing Docker for Mac w/ Kubernetes and deploying a service to it, I wanted to view this service's HTTP interface from a web browser on my Mac. I'm unable to find documentation on how to do this.

### Problem location

I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/docker-for-mac/networking/ (or possibly on some non-Mac-specific URL!)

### Project version(s) affected

I'm running Version 17.12.0-ce-mac45 (21669), but this missing documentation affects the experience for all users of Docker's Kubernetes support.

### Suggestions for a fix

My [experiments](https://github.com/jnewland/local-dev-with-docker-for-mac-kubernetes) seem to indicate that Kubernetes services with `type==LoadBalancer` have their ports exposed with vpnkit, but I can't find this logic in any open source repo. I'd suggest reviewing the logic that exposes these ports and creating documentation outlining it's behavior. If ya'll can help me find that logic, I'd be happy to push up a PR with some proposed docs! 💞

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
