### ISSUE TITLE
Windows 10 - reset credentials for mounting a folder

### ISSUE THREAD

**Issue by snewell92** [docker/docker.github.io#5691]
File: [engine/admin/volumes/bind-mounts.md](https://docs.docker.com/engine/admin/volumes/bind-mounts/), CC @mistyhacks

I didn't see any mention of [needing to fiddle with permissions](https://github.com/moby/moby/issues/22981#issuecomment-346140772) to mount a folder, would be nice if a note was added to the docs.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
