### ISSUE TITLE
Docker Toolbox and mounting to host volumes

### ISSUE THREAD

**Issue by ps2goat** [docker/docker.github.io#5698]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/), CC @johndmulhausen

To be clear, I'm using the Docker Toolbox and trying to implement redis mounted as described in Part 5 of the getting started guide.

It would be nice to call out potential issues with Docker Toolbox swarms vs an installed version of Docker (CE, e.g.).  I'm unable to mount redis using the provided volume info, and I found [this](https://github.com/moby/moby/issues/34997) issue that suggests there's a translation layer issue between the Virtual Box service, the local file structure on Windows, and the Docker service.

I've also looked at [this](https://github.com/docker/compose/issues/3285) issue and tried the path types that were declared as 'working' in the chart half-way down the page.  I always either get either the `invalid mount config for type` or `invalid bind mount source, must not be an absolute path` error messages.

**Comment by londoncalling** [comment]
@ps2goat if memory serves, I don't believe you can run the Getting Started on Docker Toolbox.  Note that on Part 2, the first [prerequisite](https://docs.docker.com/get-started/part2/#prerequisites) is to Install Docker version 1.13 or higher, which takes you to[ these supported platforms for Desktop](https://docs.docker.com/engine/installation/#desktop). Granted, Docker Toolbox is a fallback for Windows users on older systems, but I don't think you can work through the whole Getting Started on it. I could be wrong .. wait to hear from @johndmulhausen, @mistyhacks  or @JimGalasyn for sure.

**Comment by ps2goat** [comment]
I just did!  I had to add a shared folder to my manager vm in the Oracle VM Virtualbox app.  After that, I was able to mount the shared folder's path using `- "/var/data:/data"` for redis.
