### ISSUE TITLE
Feedback for: engine/getstarted/last_page.md

### ISSUE THREAD

**Issue by jclark-dot-org** [docker/docker.github.io#57]
URL: engine/getstarted/last_page.md

Several of the links aren't appearing as links; they look like non-working markdown links or similar.  Of particular interest is the "more advanced examples" page, which has a broken link section like:

    [Learn by example](/engine/tutorials/index.md)</a>

However, trying https://docs.docker.com/engine/tutorials/index.md results in a 404.

**Comment by johndmulhausen** [comment]
Fixed in f6562cf92a204116db7a58085eec7ac572080127
