### ISSUE TITLE
Broken link to mobycloud-haproxy and unclear status of project

### ISSUE THREAD

**Issue by anjackson** [docker/docker.github.io#5704]
File: [docker-cloud/getting-started/deploy-app/9_load-balance_the_service.md](https://docs.docker.com/docker-cloud/getting-started/deploy-app/9_load-balance_the_service/), CC @londoncalling 

The above file links to https://github.com/moby/mobycloud-haproxy which does not exist. The correct location is presumably https://github.com/docker/dockercloud-haproxy, but this project appears to be deprecated.

Please can the documentation be updated to cover whichever load-balancing method is currently recommended?

**Comment by londoncalling** [comment]
@mistyhacks ^^  can you have a look?

@anjackson The docs currently point to [Docker Cloud’s HAProxy image](https://github.com/docker/dockercloud-haproxy) for the example. The link is not broken, it is pointing to the GitHub repository for `dockercloud-haproxy`. The project is in maintenance mode, but as far as I can tell, this doesn't mean that you still can't follow the README to use it.

**Comment by anjackson** [comment]
Thanks @londoncalling - I'm happiliy running `dockercloud-haproxy`.

I was referring to this line https://github.com/docker/docker.github.io/blame/master/docker-cloud/getting-started/deploy-app/9_load-balance_the_service.md#L77

**Comment by mistyhacks** [comment]
This was just a mistake when moving `docker/docker` to `moby/moby` I think. I'll take care of it.

**Comment by londoncalling** [comment]
@mistyhacks yes, thanks .. re: getting rid of Javascript, that seems like a lot of overhead right now, given that all of the navigation, plus tabs, drop-downs, glossary, etc. relies on it.
