### ISSUE TITLE
how do I use docker.for.mac.localhost within docker-compose.yml file?

### ISSUE THREAD

**Issue by danhammari** [docker/docker.github.io#5708]
File: [docker-for-mac/networking.md](https://docs.docker.com/docker-for-mac/networking/), CC @gbarr01 
the page mentions that I may use the special variable, docker.for.mac.localhost, to access the external IP of the mac host. However, the documentation does not explain how to use this variable within a docker-compose.yml file. Could you add some documentation to show an example of how this variable can be used in the docker-compose.yml file?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
