### ISSUE TITLE
Feedback for: compose/startup-order.md

### ISSUE THREAD

**Issue by kobenauf** [docker/docker.github.io#571]
File: [compose/startup-order.md](https://docs.docker.com/compose/startup-order/)

Just because code may need to recover from a database being unavailable it does not follow that we therefore shouldn't be able to start our system in a predictable way.  The arrogant solution proposed here is for everyone to live with logs littered with unnecessary retry and warning noise for conditions that are normal, expected, and controllable.  Farming this out to a klunky third-party solution is inadequate.

**Comment by londoncalling** [comment]
@nathanleclaire @shin- @dnephin If there are no objections, I'm going to close this ticket. It is not a docs issue. Let me know what you think.

@kobenauf if you'd like to submit an issue to the codebase, please work with the above folks ^^

**Comment by dnephin** [comment]
@londoncalling SGTM
