### ISSUE TITLE
missing download links

### ISSUE THREAD

**Issue by aronatkins** [docker/docker.github.io#5713]
There are no download links for 17.09.1-ce-mac42 and 17.12.0-ce-mac46 in the stable release notes.

File: [docker-for-mac/release-notes.md](https://docs.docker.com/docker-for-mac/release-notes/), CC @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
