### ISSUE TITLE
Link to download Toolbox for Windows gets v17.10-ce not latest (v17.12-ce)

### ISSUE THREAD

**Issue by tossj** [docker/docker.github.io#5715]
File: [toolbox/overview.md](https://docs.docker.com/toolbox/overview/), CC @gbarr01 

The latest is now https://github.com/docker/toolbox/releases/tag/v18.01.0-ce

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
