### ISSUE TITLE
windows on the use of bash command line mount successfully, but the directory is bash directory not a container directory, will cause the changes do not take effect on the container

### ISSUE THREAD

**Issue by DevilCcx** [docker/docker.github.io#5716]
### Problem description

windows on the use of bash command line mount successfully, but the directory is bash directory is not a container directory, will cause the changes do not take effect on the container

### Problem location

You can not use a docker mount similar to git bash on windows

**Comment by JimGalasyn** [comment]
Hi @GuoFang1994 , thank you for the feedback. Is this issue related to the documentation at docs.docker.com? If so, can you add a link to the topic?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
