### ISSUE TITLE
Experimental CLI Configuration

### ISSUE THREAD

**Issue by ollypom** [docker/docker.github.io#5718]
### Problem description

Some of the new Docker CLI commands are hidden behind the new Experimental CLI flag. 

I.e.
```
$ docker trust
docker trust is only supported when experimental cli features are enabled
```

However I can't find any documentation on how to enable experimental CLI. I was able to work out that you need to update your .docker/config.json file with 

```
"experimental": "enabled"
```
And then your able to run:

```
$ docker trust             

Usage:  docker trust COMMAND

Manage trust on Docker images (experimental)

Options:


Management Commands:
  key         Manage keys for signing Docker images (experimental)
  signer      Manage entities who can sign Docker images (experimental)

Commands:
  inspect     Return low-level information about keys and signatures
  revoke      Remove trust for an image
  sign        Sign an image
  view        Display detailed information about keys and signatures

Run 'docker trust COMMAND --help' for more information on a command.
```

### Problem location
Looks like the PR came in here:
https://github.com/docker/cli/pull/758

I'm not quite sure where that documentation needs to go, as I can't find a place for `.docker/config.json` information. The closest I have is:

https://docs.docker.com/engine/reference/commandline/cli/

But I definitely think we need some sort of warning on here:
https://docs.docker.com/edge/engine/reference/commandline/trust/

### Project version(s) affected
Docker Engine CE 17.12 and newer

**Comment by mistyhacks** [comment]
@ollypom see #5736 for a stop-gap which will print the instructions for what to do to get the experimental CLI and experimental daemon flags. The https://docs.docker.com/engine/reference/commandline/cli/ needs a serious rewrite (that content lives in the `docker/cli` repo if you would like to try your hand), but this should help out for now, when merged. You can check in the Netlify preview in that PR to see what the `trust` command would look like.
