### ISSUE TITLE
Section "Pull an image by digest" should reference handy docker-library/repo-info repo.

### ISSUE THREAD

**Issue by ruffsl** [docker/docker.github.io#5721]
File: [engine/reference/commandline/pull.md](https://docs.docker.com/engine/reference/commandline/pull/), CC @mistyhacks 

I've been looking for ways in uncovering an archive for past digests of Official Docker Hub Library images from the registry API for some time. I had need for retrieving previous image of ubuntu to temporarily rollback new pushed changes to it while I updated my older dockerfiles.

Seems as I was I was looking for it in the wrong direction, as [docker-library/repo-info](https://github.com/docker-library/repo-info) already appears to provide this. I'd like to recommend that this github repo be referenced for decoverbilty, geven the example section is already demonstrating the process for retrieving an older image of ubuntu, this would be a good chance to notify users where such digest may be found.

Side note, would there be a way past digests from user docker hub repos could be retrieved, i.e. non official library images? Or are only official library images preserved/archived in the registry and digest recorded. Also, for official images, how far back does the archiving of past images in the docker hub registry go? Scene inception of the official image repo, or a lapsing window of time, e.g. 2yr?

**Comment by mistyhacks** [comment]
That repo is marked as WIP in its own README. I am not comfortable linking to it. @thaJeztah PTAL and let me know.

For the side note, you'd want to file a feature request against Docker Hub.
