### ISSUE TITLE
Inconsistent documentation about supported docker storage driver

### ISSUE THREAD

**Issue by marek-surek** [docker/docker.github.io#5723]
File: [engine/installation/linux/docker-ce/centos.md](https://docs.docker.com/engine/installation/linux/docker-ce/centos/), CC @mistyhacks
In the documentation is written that recommended driver is overlay2

But in this list, overlay2 for CentOS is not supported.
https://docs.docker.com/engine/userguide/storagedriver/selectadriver/

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
