### ISSUE TITLE
Document ability to control task termination order when shutting down a swarm service

### ISSUE THREAD

**Issue by mistyhacks** [docker/docker.github.io#5727]
See 

https://github.com/moby/moby/issues/33392
https://github.com/docker/swarmkit/issues/2264
https://github.com/docker/swarmkit/pull/2265

**Comment by gbarr01** [comment]
@mistyhacks , what do you think about updating this info on these pages: 

https://docs.docker.com/engine/swarm/swarm-tutorial/scale-service/
https://docs.docker.com/engine/swarm/how-swarm-mode-works/services/

**Comment by gbarr01** [comment]
@mistyhacks , the title of this PR implies that the user can control task termination. But looking at the code, it seems that tasks are shutdown in reverse slot order. The user cannot control this with syntax.

@thaJeztah , can you confirm?

**Comment by gbarr01** [comment]
This is my understanding:

> Tasks are shut down gracefully by balancing remaining tasks across nodes. Unassigned tasks are shutdown first and running tasks are shutdown by Slot number in reverse order.

**Comment by gbarr01** [comment]
@thaJeztah , how does the user actually control termination order?

**Comment by thaJeztah** [comment]
I don't think the changes that were merged allow you to influence the order; the change that was implemented is that the order in which tasks are shutdown is more deterministic (i.e., when scaling  down, the last task is shutdown first). Order in which tasks are shutdown is still not _guaranteed_ though (at least, to my understanding), just that SwarmKit now takes it into account

**Comment by gbarr01** [comment]
Okay, thanks, @thaJeztah. That makes sense. I'm going to close this issue unless you think it needs documentation.

**Comment by kamalhakim** [comment]
Hi, Is this explained/documented anywhere? Can we rely on that tasks are terminated by reverse slot order in a swarm?  Thanks!
