### ISSUE TITLE
Document how to get Kube going on Linux Docker CE 18.01

### ISSUE THREAD

**Issue by mistyhacks** [docker/docker.github.io#5729]
18.01 includes basic support for deploying stacks onto Kubernetes. Document how to enable this, what the Kubernetes requirements are, how to get them playing nicely, and at least some very basic stack "recipes" to play with.

See https://github.com/docker/cli/issues/778 cc/ @vdemeester

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
