### ISSUE TITLE
Describe meaning of docker stats columns

### ISSUE THREAD

**Issue by artemik** [docker/docker.github.io#5734]
While some of them are obvious, It's not clear what exactly the rest of them show. For example, NET I/O, what's input and what's output?

File: [engine/reference/commandline/stats.md](https://docs.docker.com/engine/reference/commandline/stats/), CC @mistyhacks

**Comment by mistyhacks** [comment]
@artemik that file is actually maintained in a separate repo, [docker/cli](https://github.com/docker/cli/tree/master/docs/reference/commandline). In a circuitous way, changes there eventually make their way here, so you should re-file this issue there. I'm sorry for the hassle, but we want to give the issue the highest likelihood of being addressed.

@johndmulhausen at one point in time, the "Report a bug" link would redirect you to the `docker/cli` repo to file your bug. Did we lose that?
