### ISSUE TITLE
"These are the doc's for:" Line is blank

### ISSUE THREAD

**Issue by gnomestar** [docker/docker.github.io#5743]
It appears that a data key is missing here, as the sentence just ends ..

File: [datacenter/install/linux.md](https://docs.docker.com/datacenter/install/linux/), CC @joaofnfernandes

**Comment by gbarr01** [comment]
Very odd as the markdown for this page shows no sign of this. 

@JimGalasyn , @joaofnfernandes , this text comes from _includes/ee_dropdown.html: 

> <blockquote><p>These are the docs for {{ currentDoc }}</p>
> <p>To select a different version, use the selector below.</p>
> <p>{{ dropdown }}</p>
> </blockquote>

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
