### ISSUE TITLE
EE Engine installation pathway is rather confusing

### ISSUE THREAD

**Issue by gnomestar** [docker/docker.github.io#5744]
*Precondition* - I have just purchased or begun a trial of Docker EE via Docker Store
* Beginning from a license page in Docker Store, I'm given installation instructions
  * https://docs.docker.com/engine/installation/linux/ubuntu/
* These take me to a page where Step 1 links to other documentation
  * https://docs.docker.com/engine/installation/
   * At this point Docker logically knew my exact use case -- trial/new customer installing EE for Ubuntu/Linux
  * This page gives information on:
     * CE vs EE capabilities
     * Supported platforms per edition
     * Release Schedule
     * Docker Cloud
   * This page does not directly given information on -- Installation Docker EE for "Linux".
* Going into the next branch in the doc's tree gets me to this page -- https://docs.docker.com/engine/installation/linux/docker-ee/ubuntu/
  * Note, the first step here just sends me back to  the starting  point -- Store's licensing page :)

*The Ask* Has anyone taken a look at the effectiveness of this pathway? It would seem that every purchase from Docker Store allows Docker folks to know exactly what Edition and Environment is being targeted, so why send them on a discovery mission to find the correct document for Step 1?

File: [datacenter/install/linux.md](https://docs.docker.com/datacenter/install/linux/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
@gnomestar I think that a few folks tried to improve each step individually but I think you're right in that no one is actively looking and improving the end-to-end experience 😢

**Comment by mbentley** [comment]
Can we **please** get rid of all of the docs in store.docker.com and just point to the actual documentation?  I am attempting to help out a partner who is setting up Docker EE for the first time and they're very technical people but they are being led down a path that isn't getting them anywhere and leads to them guessing instead of following the docs.



> Matt, I'll give you a little background.
> 
> First, I received an install doc (PDF attached) but the link "these instructions" doesn't work...
> 
> ...so maybe everything I need to know is already somewhere, but I just don't know about it 😊
> 
> That said, I guessed my way to getting EE/UCP installed and go here...
> ...and get that error trying to upload the .lic file, contents look like...[secret bits truncated]
> 
> {
>     "authorization": "ewogICAicGF5bG9hZCI6ICJleUpsZ...",
>     "key_id": "U4gTeaPFwvwHJynIwUIT5IDw3IVgp7J824eatl0EUD87",
>     "private_key": "LH5qgSM8hrVKP..."
> }
> 
> So at this point, I tried to tails the logs of  UCP Controller container...
> 
> $ docker logs ucp-controller
> ...
> {"level":"warning","msg":"Unable to create a kube client: unable to copy kube certs from ucp-reconcile: unable to create directory: mkdir /var/lib/docker: permission denied","time":"2018-02-09T15:05:34Z"}
> ...
> Is the only "warning" I see, no errors.  There are 28 containers running, none look interesting enough to grep logs as a fishing expedition.
> 
> Overall, the process seems a little half-baked, or I'm missing the real docs.  We'll need to do a lot of work in this area before we take this to AnF.  I think Docker should consider a little automation for this.  Hand building nodes, even the first one is not really "best practice" these days.  Also, seems a shame that the install process for EE does not mirror CE with just a license step added.  Additionally, the lack of docker-machine support makes me sad.  Now I have to bring in Ansible, Terraform, etc. and other complexities, rather just use the standard docker tooling that many of use are used to.  Anyway, MTC.  -s

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
