### ISSUE TITLE
Docker EE Version Mis-match

### ISSUE THREAD

**Issue by gnomestar** [docker/docker.github.io#5745]
In the top right corner, I'm seeing a version selector which defaults to 17.12.

I'm working through the installation instructions I discovered while trying to install 17.06 from Docker Store download. My instructions all reference 17.06, which I understand to be the current Docker EE release... but this doc's versioning system is rather unclear to me given the divergence of EE and CE release cadences. 

After diving further, this is even less clear -- are the doc's outdated and should have commands for 17.12 instead of 17.06? Docker Store does not give me any information about _what version of Docker EE I've just purchased_... so now, as a potential Docker Customer, I'm confused about what I've purchased and what I need to install. Am I six months behind? :)

File: [engine/installation/linux/docker-ee/ubuntu.md](https://docs.docker.com/engine/installation/linux/docker-ee/ubuntu/), CC @mistyhacks

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
