### ISSUE TITLE
Docker for mac - networking docs changes request

### ISSUE THREAD

**Issue by hadalin** [docker/docker.github.io#5748]
File: [docker-for-mac/networking.md](https://docs.docker.com/docker-for-mac/networking/), CC @gbarr01

This section

>I WANT TO CONNECT FROM A CONTAINER TO A SERVICE ON THE HOST
The Mac has a changing IP address (or none if you have no network access). From 17.06 onwards our recommendation is to connect to the special Mac-only DNS name docker.for.mac.localhost which will resolve to the internal IP address used by the host.

should probably be updated to use DNS name `docker.for.mac.host.internal` as stated in [Docker Community Edition 17.12.0-ce-mac46 2018-01-09](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-17120-ce-mac46-2018-01-09-stable) release notes.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
