### ISSUE TITLE
Feedback for: engine/tutorials/networkingcontainers.md

### ISSUE THREAD

**Issue by mjmill** [docker/docker.github.io#575]
File: [engine/tutorials/networkingcontainers.md](https://docs.docker.com/engine/tutorials/networkingcontainers/)

Name a container should go someplace more logical.  The network page is not it.

**Comment by mstanleyjones** [comment]
I can understand why it's here. This is a tutorial about networking and if you use user-defined networks, the container name resolves to the container's IP address. That said, it can probably be improved.

This is also not the **only** place we talk about naming. :)
