### ISSUE TITLE
4.0 Kernel reference?

### ISSUE THREAD

**Issue by okrangerb3** [docker/docker.github.io#5753]
File: [engine/userguide/storagedriver/overlayfs-driver.md](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/), CC @mistyhacks

Is this ubuntu or for rhel and rhel started supporting overlay2 in the 3.10 kernel.  Can we make this clearer as there are multiple support documents pointing to different versions of the 7.4 kernel.  The prerequisites for deploying overlay2 do not match this document.

**Comment by joaofnfernandes** [comment]
Just to point to a few documents that we have:
* This one has some loose [recommendations about the drivers](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-ce) supported for Docker CE
* This one has [stricter recommendations ](https://success.docker.com/article/Compatibility_Matrix)for Docker EE

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
