### ISSUE TITLE
Filtering by volume labels documentation appears to be wrong

### ISSUE THREAD

**Issue by jsternberg** [docker/docker.github.io#5757]
### Problem description

The API documentation for filtering by labels appears to be wrong for volumes. It seems to be correct for containers and networks, but volumes appear [here](https://docs.docker.com/engine/api/v1.35/#operation/VolumeList) like this:

```
label=<key> or label=<key>:<value> Matches volumes based on the presence of a label alone or a label and a value.
```

On the containers and networks page, this is `label="<key>=<value>"`. On the volumes page, this has a colon for some reason. When using the API, using the equals sign seems to work while using a colon does not.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/api/v1.35/#operation/VolumeList

### Project version(s) affected

I'm not sure if previous versions used a colon or an equals sign. I only tested it against the following:

```
$ docker info
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 310
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.71GiB
Name: linuxkit-025000000001
ID: KLDJ:EYTQ:QI4B:HTMM:HBAZ:TUD3:ISC7:WRP4:VQF5:UEMN:LCEH:47WV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by joaofnfernandes** [comment]
You can validate that the API docs are wrong for volumes with:

```
docker volume create -d local --label zone=us myvolume
```

## Filtering with `=`

```
curl -X GET -H "Accept: application/json" --unix-socket /var/run/docker.sock 'http://localhost/volumes?filters=\{"label":\["zone=us"\]\}'

{
  "Volumes": [
    {
      "CreatedAt": "2018-01-17T22:17:54Z",
      "Driver": "local",
      "Labels": {
        "zone": "us"
      },
      "Mountpoint": "/var/lib/docker/volumes/myvolume/_data",
      "Name": "myvolume",
      "Options": {},
      "Scope": "local"
    }
  ],
  "Warnings": null
}
```

## Filtering with `:`

```
curl -X GET -H "Accept: application/json" --unix-socket /var/run/docker.sock 'http://localhost/volumes?filters=\{"label":\["zone:us"\]\}'

{
  "Volumes": null,
  "Warnings": null
}
```

---

I also think that two things could be improved in the API docs:

The `filter` query string docs tell you that you need to pass a JSON encoded object in the format `map[string][]string`. This format seems to have been deprecated, and you should use `map[string]map[string]bool`.

This means that your invocation should be:

```
 curl -X GET -H "Accept: application/json" --unix-socket /var/run/docker.sock 'http://localhost/volumes?filters=\{"label":\{"zone=us":true\}\}'
```
[source](https://github.com/moby/moby/blob/master/api/types/filters/parse.go#L119-L132)

Also, the docs for the `/containers/json` endpoint give you a JSON example of the filter - `{"status": ["paused"]}`. But this description is not available in any other endpoints, including `/networks`, and `/volumes`. It would be really useful that these endpoints also gave an example of the JSON format expected.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
