### ISSUE TITLE
typo in the "note" section of ADD instruction in this doc... Last line of the note block.

### ISSUE THREAD

**Issue by davidmukiibi** [docker/docker.github.io#5759]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @mistyhacks

**Comment by mistyhacks** [comment]
Sorry, which note in the ADD section? There are 6....

**Comment by bvwells** [comment]
I suspect it is the 'for for' In the last sentence of the first note section.

'group names to IDs restricts this feature to only be viable for for Linux OS-based containers'

Hope this helps @mistyhacks!

**Comment by mistyhacks** [comment]
Fixed upstream.
