### ISSUE TITLE
UCP 2.2.5 Release Notes

### ISSUE THREAD

**Issue by jojuva** [docker/docker.github.io#5761]
File: [datacenter/ucp/2.2/guides/release-notes.md](https://docs.docker.com/datacenter/ucp/2.2/guides/release-notes/), CC @jimgalasyn

Can please update this page?
Many thanks!

**Comment by JimGalasyn** [comment]
Hi @jojuva , thanks for the feedback! We updated the page yesterday, do you have something specific in mind?

**Comment by jojuva** [comment]
Now, I got the page updated with fixes in latest release. I may have experienced a page caching issue.
Many thanks for being so quick!!
