### ISSUE TITLE
mongodb failed to launch with mup setup (Cannot connect to the Docker daemon)

### ISSUE THREAD

**Issue by miranos** [docker/docker.github.io#5763]
First i installed UBUNTU 14.04 64bit/32bit (Tried it too with UBUNTU 16.04 64bit).
 
When i launch `mup setup`, i get this error message:

    ----------------------------------
    Started TaskList: Setup Docker
    [xx.xx.xx.xx] - Setup Docker
    [xx.xx.xx.xx] - Setup Docker: SUCCESS
     
    Started TaskList: Setup Meteor
    [xx.xx.xx.xx] - Setup Environment
    [xx.xx.xx.xx] - Setup Environment: SUCCESS
     
    Started TaskList: Setup Mongo
    [xx.xx.xx.xx] - Setup Environment
    [xx.xx.xx.xx] - Setup Environment: SUCCESS
    [xx.xx.xx.xx] - Copying mongodb.conf
    [xx.xx.xx.xx - Copying mongodb.conf: SUCCESS
     
    Started TaskList: Start Mongo
    [xx.xx.xx.xx] - Start Mongo
    [xx.xx.xx.xx] x Start Mongo: FAILED
     
            -----------------------------------STDERR-----------------------------------
            Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var
    /run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
            Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
            -----------------------------------STDOUT-----------------------------------
            ----------------------------------------------------------------------------

I created a username inside the VPS and granted it in order to work without `sudo`, i tried too with root access but all time the same error.

And launched this command before everything inside the VPS: `apt-get update`

Here is my `MUP` version: 1.3.7 (Under Windows 7 64bit)

And here `mup.js` file:

    module.exports = {
     servers: {
      one: {
          host: 'xx.xx.xx.xx',
          username: 'myusername',
          password: 'password',
      }
     },
     meteor: {
      name: 'myApp',
      path: '../myApp',
      servers: {
       one: {}
      },
      buildOptions: {
       serverOnly: true
      },
      env: {
       ROOT_URL: 'https://m.domain.com',
       MONGO_URL: 'mongodb://localhost/meteor'
      },
      docker:{
       image: 'abernix/meteord:base'
      },
      deployCheckWaitTime: 96,
      enableUploadProgressBar: false
     },
     mongo: {
      oplog: true,
      port: 27017,
      version: '3.4.1',
      servers: {
       one: {}
      }
     }
    };

When i try to restart from VPS, here the error message:
`Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.`

**Comment by joaofnfernandes** [comment]
@miranos The best way for you to get unblocked is to ask for help in the Mup community. Maybe try https://gitter.im/meteor-up/Lobby.

Searching around I've also found [this issue that might help you](https://github.com/zodern/meteor-up/issues/159).
The error message also tells you to check `systemctl status docker.service`, so that might provide more clues on what's going wrong.

Since there's no problem in the Docker docs that we can address, I'm closing this issue, but feel free to comment.
