### ISSUE TITLE
Add note to use stack deploy option --with-registry-auth

### ISSUE THREAD

**Issue by myregistration** [docker/docker.github.io#5766]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen 

Add a note in documentation for the env stack deploy command to use option --with-registry-auth when using images in a private repository or else the containers won't be created.  Perhaps it's rare that someone makes their repository private, but it is possible.

docker stack deploy --with-registry-auth -c docker-compose.yml getstartedlab

**Comment by joaofnfernandes** [comment]
Thanks for the suggestion!

We strive to maintain the getting started simple and accessible. In this case it tells you to do a `docker push <user>/<repo>:<tag>`, and assumes that 99% of the users going through this are new to Docker and have never created a repository. So when users push, a new repository will be created with the default visibility setting - public.

As users explore more about Docker and create private repositories, they can use the [docker stack deploy](https://docs.docker.com/engine/reference/commandline/stack_deploy/) to learn how to authenticate against the private registry.

For that reason I'm closing this issue, but feel free to comment.
