### ISSUE TITLE
Status code for killing stopped container is missing

### ISSUE THREAD

**Issue by shutefan** [docker/docker.github.io#5778]
When trying to kill a stopped container status code 409 is returned:
```
curl --unix-socket /var/run/docker.sock -X POST http://docker/containers/xxx/kill -I

HTTP/1.1 409 Conflict
...
```
This is not reflected in the [relevant part of the API documentation](https://docs.docker.com/engine/api/v1.35/#operation/ContainerKill) and should be added.

**Comment by joaofnfernandes** [comment]
Thanks for reporting this!
I was able to replicate your issue and moved it to the correct repository for tracking - moby/moby#36068.
