### ISSUE TITLE
awslogs-datetime format 

### ISSUE THREAD

**Issue by leonblueconic** [docker/docker.github.io#5779]
File: [engine/admin/logging/awslogs.md](https://docs.docker.com/engine/admin/logging/awslogs/), CC @mistyhacks 

The documentation page metions: 
```
$ docker run --log-driver=awslogs \
             --log-opt awslogs-region=us-east-1 \
             --log-opt awslogs-group=myLogGroup \
             --log-opt awslogs-datetime-format='[%b %d, %Y %H:%M:%S]' \
```

I find that I had to escape "[" , "]" and for my timestamp I had to escape "+" as well: 
```
[2018-01-19T07:15:58+00:00] <INFO>	[/nodeapp/myapp/app.js .... 
```

Using an updated version of the example on the documentation page I get:
```
[ec2-user]$ docker run --log-driver=awslogs --log-opt awslogs-group=DockerLogs --log-opt awslogs-datetime-format='[%Y-%m-%dT%H:%M:%S+00:00]' centos:latest /bin/bash
docker: Error response from daemon: failed to initialize logging driver: awslogs could not parse multiline pattern key "[\\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[1,2][0-9]|3[0,1])T(?:[0,1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]+00:00]": error parsing regexp: invalid character class range: `}-(`.
```

Working example:
```
docker run --log-driver=awslogs --log-opt awslogs-group=DockerLogs --log-opt awslogs-datetime-format='\[%Y-%m-%dT%H:%M:%S\+00:00\]' centos:latest /bin/bash
```

**Comment by mistyhacks** [comment]
Since you did all the work to find the fix, I encourage you to submit a PR! Just click `Edit this page` when you are looking at the page in question. It will open the Atom editor on Github and give you a chance to make the change and submit the PR. 👍

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
