### ISSUE TITLE
Security Groups don't line up between table and pictures

### ISSUE THREAD

**Issue by kimberlyesmith** [docker/docker.github.io#5781]
File: [get-started/part6.md](https://docs.docker.com/get-started/part6/), CC @johndmulhausen 

In the table given, the type listed for visualizer is listed as HTTP, but in the pictures via AWS, the type listed is Custom TCP.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
