### ISSUE TITLE
remove -it flag from 'Start a container with a volume' example

### ISSUE THREAD

**Issue by adamancini** [docker/docker.github.io#5785]
File: [engine/admin/volumes/volumes.md](https://docs.docker.com/engine/admin/volumes/volumes/), CC @mistyhacks 
```
docker run -d \
  -it \
  --name devtest \
  --mount source=myvol2,target=/app \
  nginx:latest
```

should probably read 
```
docker run -d \
  --name devtest \
  --mount source=myvol2,target=/app \
  nginx:latest
````

Since the -it flag doesn't make sense in this context and is confusing when combined with --detach.

**Comment by mistyhacks** [comment]
On the contrary, I think it does make sense to have both. This way you can still attach to the container if you want and be able to interact with it. Ping again if you disagree.

**Comment by adamancini** [comment]
@mistyhacks I think for the purpose of this example, to show volume usage, it's a non-issue, and docker exec -it can still be used to attach to the container.  I think in this instance using -it with an nginx image is unnecessary, since there's nothing you can actually interact with by attaching nginx to the shell.  The user would see the server startup messages and access logs until they disconnect their shell from the container.
