### ISSUE TITLE
Unclear if I have to use entire version string

### ISSUE THREAD

**Issue by friism** [docker/docker.github.io#5789]
> You can use the entire version string, but you need to include at least to the first hyphen.

should that be "you don't have to use the entire..."?

cc @andrewhsu @dmp42 @mistyhacks 

File: [engine/installation/linux/docker-ee/rhel.md](https://docs.docker.com/engine/installation/linux/docker-ee/rhel/), CC @mistyhacks

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
