### ISSUE TITLE
how to do an image digest retrieval?

### ISSUE THREAD

**Issue by Davidrjx** [docker/docker.github.io#5797]
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/), CC @joaofnfernandes
as not fetching valid digest, request special details about image digest, not massive but simple and clear. some example will be better.
thanks

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
