### ISSUE TITLE
"No DTR replica on UCP Manager node" statement

### ISSUE THREAD

**Issue by ekitagawa** [docker/docker.github.io#5799]
File: [datacenter/dtr/2.4/guides/admin/install/system-requirements.md](https://docs.docker.com/datacenter/dtr/2.4/guides/admin/install/system-requirements/), CC @joaofnfernandes 
 
Many customers installed DTR onto Manager nodes and suffer instability because of that.  When that happens, solving the issue is impossible because customer will have to purchase more licenses.  
 
Architecture page shows the right way to do it, but we have had several encounters where customer complain that we were not explicit enough.  Sales team inform this during negotiation, but that does not help when a large organization by licenses in bulk for multiple teams.

**Comment by joaofnfernandes** [comment]
Issue moved to [docker/docs-private #442](https://github.com/docker/docs-private/issues/442) via [**ZenHub**](https://www.zenhub.com/)
