### ISSUE TITLE
Feedback for  docker.github.io/engine/reference/commandline/commit.md

### ISSUE THREAD

**Issue by buchs** [docker/docker.github.io#580]
### Problem description

Syntax for commit --change should be further elaborated in regard to setting the Env value. The example given works for setting one Env environment variable, though it seems to be additive only. Can one set multiple Env variables? Can one delete an Env variable? Can one completely overwrite all of Env? In addition, another syntax seems to work that includes square brackets. See http://stackoverflow.com/questions/29015023/docker-commit-created-images-and-entrypoint and the answer by user: sxc731. This syntax could be elaborated upon, unless using it is not best practice. 

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/commandline/commit/

https://docs.docker.com/engine/reference/commandline/commit/

### Project version(s) affected

latest published version

### Suggestions for a fix

See above

**Comment by mstanleyjones** [comment]
These docs are reference docs and are maintained in the `docker/docker` repo. Can you please raise this PR there? Feel free to ping me on it and we'll follow up. Thanks!
