### ISSUE TITLE
Add note: 'docker run' containers are not removed from a node in the Drain state

### ISSUE THREAD

**Issue by adamancini** [docker/docker.github.io#5800]
File: [engine/swarm/swarm-tutorial/drain-node.md](https://docs.docker.com/engine/swarm/swarm-tutorial/drain-node/), CC @mistyhacks

Availability: Drain will drain swarm services from the node (`docker service create` & `docker stack deploy`), but will not drain plain containers (`docker run` or `docker-compose up`)

Propose changing the wording to read like: 
> "Sometimes, such as planned maintenance times, you need to set a node to DRAIN availability. DRAIN availability prevents a node from receiving new tasks from the swarm manager. It also means the manager stops SWARM tasks running on the node and launches replica tasks on a node with ACTIVE availability. This means that any containers ran via "docker run" locally will NOT be re-scheduled."

**Comment by mistyhacks** [comment]
@adamancini Just like you filed this issue, you can also easily file a PR by clicking the *Edit this page* link at the right-hand side of each docs page. Since you already proposed text, are you open to creating the PR? Feel free to tag me in it and I can review and copyedit as needed. 👍

**Comment by adamancini** [comment]
@mistyhacks I will submit the PR - thanks! 
Do you think this is a reasonable change?

**Comment by mistyhacks** [comment]
I think if you are going to file a PR we prefer just the PR. 👍 

I think the note is generally fine, though I will do a copy-edit for you. You don't need to capitalized Swarm (or SWARM), for instance.
