### ISSUE TITLE
Update local hostname to docker.for.mac.host.internal

### ISSUE THREAD

**Issue by sgerrand** [docker/docker.github.io#5802]
There's still a reference to `docker.for.mac.localhost` in [docker-for-mac/networking.md](https://docs.docker.com/docker-for-mac/networking/)

This should be updated to `docker.for.mac.host.internal`.

CC @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
