### ISSUE TITLE
Wrong link for offline install file

### ISSUE THREAD

**Issue by RobbKistler** [docker/docker.github.io#5809]
File: [ee/dtr/admin/install/install-offline.md](https://docs.docker.com/ee/dtr/admin/install/install-offline/), CC @johndmulhausen

Link to `https://beta.docs.docker.com/packages.docker.com/caas/dtr_images_2.5.0-beta3.tar.gz` should be `https://packages.docker.com/caas/dtr_images_2.5.0-beta3.tar.gz`

**Comment by RobbKistler** [comment]
@joaofnfernandes

**Comment by joaofnfernandes** [comment]
This one was addressed upstream.
