### ISSUE TITLE
documentation docker-compose pull: does it pull incremental or everything?

### ISSUE THREAD

**Issue by kmddevdani** [docker/docker.github.io#5810]
File: [compose/reference/pull.md](https://docs.docker.com/compose/reference/pull/), CC @gbarr01 

I just searched on the web for `docker-compose pull`, because I wanted to figure out, if the command downloads only updated data, or every time everything from scratch. https://docs.docker.com/compose/reference/pull/ was the first result, but I did not find enough information to confirm my assumptions about the command. Would it be possible to add a bit more details?

Does the command download all data from scratch, or only missing / updated data?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
