### ISSUE TITLE
Source and target not consistent

### ISSUE THREAD

**Issue by piotras** [docker/docker.github.io#5812]
File: [engine/reference/commandline/tag.md](https://docs.docker.com/engine/reference/commandline/tag/), CC @mistyhacks 

Description says:
Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
Usage is:
docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]

This is misleading. Easy to mix up source and target.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
