### ISSUE TITLE
This policy is too long.... AWS won't accept it.

### ISSUE THREAD

**Issue by scooter4j** [docker/docker.github.io#5815]
File: [docker-for-aws/iam-permissions.md](https://docs.docker.com/docker-for-aws/iam-permissions/), CC @johndmulhausen 

Is there a way to shorten this policy? I'm getting the following error:

Limit exceeded
Your request exceeds one of the limits for this account. Remove one or more existing items and try again. To request a limit increase, contact AWS Customer Support. Learn more
Cannot exceed quota for PolicySize: 6144

**Comment by mistyhacks** [comment]
@ddebroy @FrenchBen PTAL

**Comment by FrenchBen** [comment]
DUPE of https://github.com/docker/docker.github.io/issues/3939

**Comment by siddharthseetickets** [comment]
You can split the policy into multiple files. Each one shouldn't cross 6144 character count.
Solved for me!!!!

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
