### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntulinux.md

### ISSUE THREAD

**Issue by brianehlert** [docker/docker.github.io#582]
File: [engine/installation/linux/ubuntulinux.md](https://docs.docker.com/engine/installation/linux/ubuntulinux/)

$ sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: /tmp/tmp.ltAy51gG67/gpg.1.sh --keyserver
hkp://p80.pool.sks-keyservers.net:80
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm

**Comment by julianfoad** [comment]
Worked for me just now (Ubuntu 16.04, apt version 1.2.15). Temporary glitch?

**Comment by brianehlert** [comment]
hmm.  Must have been temporary.
It worked for me on re-trying today.
