### ISSUE TITLE
update_config monitor

### ISSUE THREAD

**Issue by oppianmatt** [docker/docker.github.io#5824]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01

Can the update_config section describe monitor a bit better. What is is monitoring? How is it monitoring it? is using the healthcheck in the docker? Is it the time to wait until monitoring to start? or is how long it will watch and monitor the service to see if no exit error codes?

**Comment by mistyhacks** [comment]
@shin- can you provide assistance?

**Comment by shin-** [comment]
People working on Swarm would be able to answer this better than I could, but this should be a start: https://github.com/docker/cli/blob/master/vendor/github.com/docker/docker/api/types/swarm/service.go#L99
```
 	// Monitor indicates how long to monitor a task for failure after it is
	// created. If the task fails by ending up in one of the states
	// REJECTED, COMPLETED, or FAILED, within Monitor from its creation,
	// this counts as a failure. If it fails after Monitor, it does not
	// count as a failure. If Monitor is unspecified, a default value will
	// be used.
```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
