### ISSUE TITLE
Wrongly using layer 7 instead of layer 4 load balancing

### ISSUE THREAD

**Issue by gnschenker** [docker/docker.github.io#5825]
File: [ee/ucp/interlock/install/index.md](https://docs.docker.com/ee/ucp/interlock/install/), CC @johndmulhausen

Routing mesh is layer 4 load balancing and not layer 7 (as in the very first example with WP at port 8000)

**Comment by joaofnfernandes** [comment]
Issue moved to [docker/docs-private #471](https://github.com/docker/docs-private/issues/471) via [**ZenHub**](https://www.zenhub.com/)
