### ISSUE TITLE
add docker compose file version 3.5

### ISSUE THREAD

**Issue by rdxmb** [docker/docker.github.io#5831]
File: [compose/compose-file/compose-versioning.md](https://docs.docker.com/compose/compose-file/compose-versioning/), CC @gbarr01 
see also https://github.com/docker/compose/releases

**Comment by mistyhacks** [comment]
@shin- PTAL

**Comment by shin-** [comment]
I'll try and make a PR in the next couple days.

**Comment by joaofnfernandes** [comment]
Fixed via #5912
