### ISSUE TITLE
Debian link redirects nowhere

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker.github.io#5837]
File: [install/index.md](https://docs.docker.com/install/), CC @johndmulhausen This link stalls out: https://docs.docker.com/install/linux/docker-ce/debian/

**Comment by campoy** [comment]
Report here: https://twitter.com/francesc/status/956987164549697538

**Comment by joaofnfernandes** [comment]
@mistyhacks this was probably caused by #5651. Can you take a look?
