### ISSUE TITLE
Consider implementing better code blocks

### ISSUE THREAD

**Issue by mistyhacks** [docker/docker.github.io#5842]
[This link](https://chriswells.io/blog/style-shell-commands-with-css) has a really cool idea for making better code blocks that:

- Are easier to paste because the prompts are not part of the paste-able thing
- Have customizable prompts per OS
- Even allow you to specify whether it is a root / admin prompt
- Show line numbers bug again, not paste-able
- Let you indicate what lines should have a prompt (because it's a new command) and what shouldn't (because it's output or it is a continuation from the previous line)

I never got a chance to implement it, but I think it would be a super cool addition. I wonder if @allejo might be interested in taking a crack. cc/ @johndmulhausen

**Comment by allejo** [comment]
If I could get some guidance on how'd you want it to look/work, I'd be game. Sounds pretty neat

**Comment by mistyhacks** [comment]
What makes sense to me is to use the normal Markdown callout syntax, and be able to set these things as classes, using the `{:.foo}` syntax. Maybe specify some default settings (default to a bash prompt with `user@host $` prompt, default to line numbers on, default to a prompt on the first line only). We probably need at least the following variants:

- bash user
- bash root
- Windows C:\>
- Windows PS C:\>

(does the Windows administrator prompt look different?)

**Comment by allejo** [comment]
So kramdown supports defining attributes like so,

````markdown
{: .custom-shell data-user=“root”}
```bash
#!/bin/bash

echo “Hello”
```
````

What I don't like from the link you provided is the need for having to define which lines not to treat as prompts; i.e. `data-output="2, 4-8"`. It seems like this'd be hard to maintain because if new lines were added/removed, then the author would have have to remember to modify this attribute, no?

**Comment by mistyhacks** [comment]
If it would be possible to define some "default" behaviors, I think they should be:

- Default to a bash non-root prompt, like `user@host $`
- Default to having the prompt only on line 1

I'd say you should be able to override the prompt type using some css (maybe `.win-prompt`, `.win-prompt-ps`, `.win-prompt-admin`, `.bash-prompt`, `.bash-prompt-root`)?

I do think it would be great to have the option to specify which lines should have the prompt re-stated, because there are times we want to present more than one command in one code block. It would be up to us to deal with drift (probably during the PR review)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
