### ISSUE TITLE
Document journald tag as SYSLOG_IDENTIFIER

### ISSUE THREAD

**Issue by gbarr01** [docker/docker.github.io#5843]
This issue refers to [moby/moby#35570](https://github.com/moby/moby/pull/35570).

The `journald` `tag` was not showing in basic `journalctl` output and all logs were shown as `dockerd` messages. The logging driver option `tag` was added to `SYSLOG_IDENTIFIER` (in addition to the existing `CONTAINER_TAG`). 

In this example, `journalctl` prints tag (foo), instead of unit name (dockerd) as the message source: 

`docker run --log-driver=journald --log-opt tag=foo`

**Comment by gbarr01** [comment]
@thaJeztah , looking over these docs ... 

https://docs.docker.com/config/containers/logging/journald/
https://docs.docker.com/config/containers/logging/log_tags/

... it seems as if there is not much to be documented here because the documentation implies that nothing was really broken. Do you agree? 

cc: @mistyhacks

**Comment by thaJeztah** [comment]
@gbarr01 with that PR merged, if you set `--log-opt tag` (or the default tag) it will now not only set the `CONTAINER_TAG` property on journald log-entries, but also the `SYSLOG_IDENTIFIER`


> Added logging driver option `tag` not only as `CONTAINER_TAG`  (visible only in extended view, which is not usable for practical troubleshooting) but also as [`SYSLOG_IDENTIFIER`](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#SYSLOG_FACILITY=) which support pattern matching.

So we should probably add it to the table at the top of https://docs.docker.com/config/containers/logging/journald/, and explain the the `--log-opt tag ..` option will set both `CONTAINER_TAG` and `SYSLOG_IDENTIFIER`

**Comment by thaJeztah** [comment]
@zemanlx perhaps you can help with this?

**Comment by gbarr01** [comment]
Hi, @thaJeztah , I am okay with this issue. I only mentioned the possibility of not changing the docs because the example (at the bottom of the page) produces output that previously did not work .. but does with this fix. Getting to it soon.

**Comment by gbarr01** [comment]
Duplicated by #5989
