### ISSUE TITLE
Document packaging changes for CE 18.02

### ISSUE THREAD

**Issue by gbarr01** [docker/docker.github.io#5844]
- Add packaging for Fedora 26, Fedora 27, and Centos 7 on aarch64 [docker/docker-ce-packaging#71](https://github.com/docker/docker-ce-packaging/pull/71)
- Remove support for Ubuntu Zesty [docker/docker-ce-packaging#73](https://github.com/docker/docker-ce-packaging/pull/73)
- Remove support for Fedora 25 [docker/docker-ce-packaging#72](https://github.com/docker/docker-ce-packaging/pull/72)

**Comment by thaJeztah** [comment]
@seemethere could we create a checklist so that whenever we make such changes, a PR is also opened by the packaging team to make the associated documentation changes?

**Comment by gbarr01** [comment]
Complete
