### ISSUE TITLE
big CPU process of st

### ISSUE THREAD

**Issue by dwedaz** [docker/docker.github.io#5849]
### Problem description
%Cpu(s):  9.1 us,  0.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si, 90.6 st

I just run my docker services, no container running but got high cpu process.

on ubuntu

ontainers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 237
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: u1qd0ui9q1y3raz66ezvfudkd
 Is Manager: false
 Node Address: 172.21.45.170
 Manager Addresses:
  172.21.39.189:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: N/A (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: N/A (expected: )
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-97-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 486.5MiB
Name: worker-5.data
ID: STAP:OR3Y:YYJ3:WCGJ:2BQ3:7KFX:CXEX:GFQB:65UZ:MVNB:XUNL:CGWJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=amazonec2
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by mistyhacks** [comment]
This is the repository for filing issues against the Docker docs. This seems like a support request. Please ask your question at https://forums.docker.com/ or contact Docker support if you have an entitlement. Thanks!
