### ISSUE TITLE
Inconsistent overlay network size limits

### ISSUE THREAD

**Issue by cima** [docker/docker.github.io#5853]
File: [engine/swarm/networking.md](https://docs.docker.com/engine/swarm/networking/), CC @mistyhacks states that only 256 IP addresses can be used within overlay network, while File: [engine/reference/commandline/network_create.md](https://docs.docker.com/engine/reference/commandline/network_create/), CC @mistyhacks shows example with CIDR /16 for overlay network and doesn't state any network size limitations. Can you please upgrade one or another so we know how big the overlay network can be?

**Comment by mistyhacks** [comment]
Closing in favor of upstream PR.
