### ISSUE TITLE
Better document the `tasks.service-name` DNS discovery feature

### ISSUE THREAD

**Issue by fmaturel** [docker/docker.github.io#5854]
File: [engine/swarm/networking.md](https://docs.docker.com/engine/swarm/networking/), CC @mistyhacks 

To get a list of all tasks backing a service you can do a DNS lookup for `tasks.<service-name>`.

This is clearly useful for service discovery that should not use the load balancing IPVS feature (like `Prometheus` looking for metrics nodes like `node-exporter`).

But I can not find this feature clearly documented in the docs despite what is said on this [moby issue](https://github.com/moby/moby/issues/33078)

**Comment by mistyhacks** [comment]
@nishanttotla PTAL
