### ISSUE TITLE
Example on label

### ISSUE THREAD

**Issue by Steinbjarne** [docker/docker.github.io#5862]
File: [engine/reference/commandline/image_prune.md](https://docs.docker.com/engine/reference/commandline/image_prune/), CC @mistyhacks 

Though very descriptive, it would have been nice with an example of a run with --filter label=<key> and --filter label!=<key>, same as with --filter unit=24h

**Comment by mistyhacks** [comment]
@Steinbjarne please look at the upstream example. I found some interesting edge cases and documented them too. Hopefully it will be helpful!
