### ISSUE TITLE
Offline installation - ucp windows worker

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#5863]
File: [datacenter/ucp/2.2/guides/admin/configure/join-windows-worker-nodes.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/join-windows-worker-nodes/), CC @jimgalasyn

You should write a note at the top about the offline scenario requirements. This guide is about the online scenario. It could be easily missed.:
https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/install-offline/

**Comment by RomainBelorgey** [comment]
A link to the offline documentation could be fine and warm user about the difference of adding nodes to an offline cluster or adding offline nodes.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
