### ISSUE TITLE
Bearer token handling.

### ISSUE THREAD

**Issue by rquackenbush** [docker/docker.github.io#5867]
File: [registry/spec/auth/token.md](https://docs.docker.com/registry/spec/auth/token/), CC @joaofnfernandes

The token obtained in "Requesting a Token" differs from the one used in "Using the Bearer token". Is this intentional?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
