### ISSUE TITLE
Typo in online doc

### ISSUE THREAD

**Issue by janmaterne** [docker/docker.github.io#5876]
File: [engine/reference/commandline/inspect.md](https://docs.docker.com/engine/reference/commandline/inspect/), CC @mistyhacks
Typo in "Extended description":
s/ker inspect provides detailed/docker inspect provides detailed/

**Comment by mistyhacks** [comment]
The source is correct (https://github.com/docker/cli/blame/master/docs/reference/commandline/inspect.md#L33) but the YAML is wrong (https://github.com/docker/docker.github.io/blob/master/_data/engine-cli/docker_inspect.yaml#L3). I will have to raise this issue in https://github.com/docker/cli/ as that is where the script logic lives.
