### ISSUE TITLE
Missing syntax for configs

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#5878]
File: [engine/swarm/configs.md](https://docs.docker.com/engine/swarm/configs/), CC @mistyhacks

I am not sure if I do not see it but I am not seeing where the fields are documented for utilizing configs.  I expect that there are settings for source, target, UID, GID, and Mode for the file name where the config appears but I can not seem to find it from googling or searching through the docs.

**Comment by mbentley** [comment]
Looks like I found something that worked from a blog about secrets and adapted it for configs:

`--config-add "source=com.docker.license-2,target=/etc/ucp/docker.lic,uid=65534,gid=65534,mode=292"`

**Comment by mistyhacks** [comment]
You need to use a 4-digit mode and take into account any umask set in the container. You can specify `uid` and `gid` as names instead of numbers if you want. Why does world need to read the license?

**Comment by mistyhacks** [comment]
Narrative docs fix merged and upstream PR submitted, so closing this bug.
