### ISSUE TITLE
Feedback for: compose/reference/overview.md

### ISSUE THREAD

**Issue by iBobik** [docker/docker.github.io#588]
File: [compose/reference/overview.md](https://docs.docker.com/compose/reference/overview/) and more.

Strange syntag highlighting for CLI help texts:
![snimek obrazovky 2016-11-16 v 3 23 11](https://cloud.githubusercontent.com/assets/614232/20332439/1bc8b85a-abac-11e6-936d-0ac832e9a9a6.PNG)

**Comment by sanscontext** [comment]
@iBobik Thanks for the head's up! I added a `none` cue to that code block so you shouldn't see any more spurious highlighting there.

**Comment by iBobik** [comment]
Btw, it is good to check other pages, I saw it on many of them with CLI
output.



Jan Pobořil

2016-11-17 19:48 GMT+01:00 LRubin <notifications@github.com>:

**Comment by sanscontext** [comment]
Please feel free to use the "File an issue" links to report them when you see them. (If you're feeling particularly helpful, you can click "Edit this page" to add the `none` cues yourself. ;) )
