### ISSUE TITLE
typo in file name

### ISSUE THREAD

**Issue by mrajphemi** [docker/docker.github.io#5880]
File: [engine/security/userns-remap.md](https://docs.docker.com/engine/security/userns-remap/), CC @mistyhacks 
In the "Prerequisites" section, point # 1 
"relevant entries need to be in /etc/password" 

should be:

relevant entries need to be in **/etc/passwd**

**Comment by mistyhacks** [comment]
Thanks for finding that! If you'd like to fix it for us, go back to the page and click the "Edit this page" link at the right-hand side. That will open the page in the Atom editor on Github.com and let you make the change and submit a pull request. 🎉
