### ISSUE TITLE
docker swarm generate-token worker

### ISSUE THREAD

**Issue by makkpsss** [docker/docker.github.io#5886]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @johndmulhausen

Can you please add a small step of generating token for worker 

`docker-machine ssh vm1 "docker swarm join-token -q worker"`

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
