### ISSUE TITLE
Shared storage needed for HA

### ISSUE THREAD

**Issue by foodebeer** [docker/docker.github.io#5887]
Hi,

The page on setting up high availability doesn't say that for HA DTR *needs* shared storage.
Customers are still confused about this, they expect DTR to also synchronize images, since this page just talks aboutsetting up replicas.
We must be more specific on this. I wanted to point this page to them for clarification, but then realized we're not explicit enough.

Thanks in advance!

Best regards,

Sacha

File: [datacenter/dtr/2.4/guides/admin/configure/set-up-high-availability.md](https://docs.docker.com/datacenter/dtr/2.4/guides/admin/configure/set-up-high-availability/), CC @joaofnfernandes

**Comment by joaofnfernandes** [comment]
This has been addressed upstream and will become available in the next DTR release.
