### ISSUE TITLE
it'd be good to explicitly mention if these vars work for both compose and docker stacks

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker.github.io#5898]
File: [compose/env-file.md](https://docs.docker.com/compose/env-file/), CC @gbarr01

**Comment by mistyhacks** [comment]
@shin- PTAL

**Comment by shin-** [comment]
The first paragraph on the page does mention it:

> Compose supports declaring default environment variables in an environment file named `.env` placed in the folder where **the `docker-compose` command** is executed (current working directory).

(emphasis mine). 

That said, it may be possible to highlight this better? I don't know. Adding a note saying "Only applies to `docker-compose` feels redundant.

**Comment by SvenDowideit** [comment]
no, that reads very much like it wasn't updated when docker stacks cam about - omitting mention doesn't answer the users inner question.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
