### ISSUE TITLE
404 at: https://docs.docker.com/docker-cloud/getting-started/link-aws/

### ISSUE THREAD

**Issue by mpadavala** [docker/docker.github.io#59]
URL: https://docs.docker.com/docker-cloud/getting-started/link-aws/

**Comment by sanscontext** [comment]
Thanks for the report. It looks like Jekyll doesn't have the redirect functionality we had in the previous system. I've got a PR in to the Cloud team to update those links in the UI.

**Comment by johndmulhausen** [comment]
Fixed in 9fd1c9ad27a5735046944623216481e5564abb78
