### ISSUE TITLE
Feedback for: datacenter/ucp/1.1/installation/plan-production-install.md

### ISSUE THREAD

**Issue by mariaakiba** [docker/docker.github.io#590]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by joaofnfernandes** [comment]
@mariaakiba did you forget to fill-in the issue information? What information are you looking for that you can't find?

**Comment by londoncalling** [comment]
@joaofnfernandes @mariaakiba This is the page referenced in the title of this issue: https://docs.docker.com/datacenter/ucp/1.1/installation/plan-production-install/.

I checked all the links on that page, and they work and go to the right topics. I'm going to close this for now. If you all think there is still an issue, feel free to re-open the issue and/or the discussion.
