### ISSUE TITLE
No instructions how to uninstall Docker-EE on Windows Server 2016

### ISSUE THREAD

**Issue by automatecloud** [docker/docker.github.io#5905]
### Problem description

For Troubleshooting it was necessary to uninstall and reinstall the Docker-EE von Windows Server 2016. 

### Problem location

There is no documented way how you can uninstall Docker-EE on a Windows Server 2016. Due to a misconfiguration of the Engine I was forced to reinstall the engine. At the current documentation we got a section for install, for update but not how to uninstall it on a Windows Server System. I did use the following documentation:
https://docs.docker.com/install/windows/docker-ee/

We need to have a section describes the uninstall of Docker EE as well. I used the following commands to uninstall it:

UnInstall-Package Docker -ProviderName DockerProvider -Force
UnInstall-Module DockerProvider -Force

### Project version(s) affected

Every Docker EE Version for Windows Server 2016

### Suggestions for a fix

Simply create a new section that describes how to uninstall Docker EE in the documentation at https://docs.docker.com/install/windows/docker-ee/ with a section Uninstall Docker EE.

**Comment by ekitagawa** [comment]
Actually, Microsoft has it as EE Basic is technically their product.  I don't suppose they mind if we borrow it.  
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
