### ISSUE TITLE
Windows Server EE Engine download link is broken

### ISSUE THREAD

**Issue by vAndrucha77** [docker/docker.github.io#5913]
### Problem description

Script based installation of Windows server EE engine fails.

> invoke-webrequest :
> 404 Not Found
> 404 Not Found
> Code: NoSuchKey
> Message: The specified key does not exist.
> Key: components/engine/windows-server/17.06/.zip
> RequestId: B9D40A12CF6C5BA8
> HostId: fEaJZcRqyTLr/CeHjR4oY5R0fiTnSXSWtaBh5LMHZuZ5HKTL+QZbekQ15AoPnajTr2xqNr5q2g4=
> An Error Occurred While Attempting to Retrieve a Custom Error Document
> Code: NoSuchKey
> Message: The specified key does not exist.
> Key: error.html
> At line:1 char:1
>  invoke-webrequest -UseBasicparsing -Outfile .zip https://download.doc ...
>  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    > CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-> WebRequest], WebException
> FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

### Problem location

The download link provided as part of script based Windows Server Docker EE engine installation is not complete or correct. Docker EE version is not included.

https://docs.docker.com/install/windows/docker-ee/#use-a-script-to-install-docker-ee

### Project version(s) affected

All versions of Windows Server EE engines.

### Suggestions for a fix

Include the Docker EE version in the download link or provide the instruction on how to complete the link:
e.g.  invoke-webrequest -UseBasicparsing -Outfile docker.zip https://download.docker.com/components/engine/windows-server/17.06/docker-17.06.2-ee-6.zip

**Comment by mistyhacks** [comment]
@andrewhsu PTAL

**Comment by joaofnfernandes** [comment]
@mistyhacks that page is using a variable to generate the snippet, but with the changes you've made at #5651, that variable is no longer being set, which breaks the snippet in a couple of places.

The page uses `{{ page.win_latest_buid }}`, but the `_config.yml` file is only setting that variable for pages under `/engine`:

```
...
  - scope:
      path: "engine"
    values:
      win_latest_build: "docker-17.06.2-ee-6"
...
```

Updating the `_config.yml` file will fix this.
