### ISSUE TITLE
awslogs with instance profile authentication

### ISSUE THREAD

**Issue by gkirill** [docker/docker.github.io#5915]
File: [config/containers/logging/awslogs.md](https://docs.docker.com/config/containers/logging/awslogs/), CC @johndmulhausen

Hi, there is this sentence in this document:

`or (if you are running the Docker daemon on an Amazon EC2 instance) the Amazon EC2 instance profile`

However now example or any other explanation how to get this done exactly. Can you help please? A sample would be nice.

**Comment by gbarr01** [comment]
Hi, @gkirill , this is an example that should be supplied by the aws docs so I am going to close. 

Does this address your question? 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html
