### ISSUE TITLE
command on documentation not working 

### ISSUE THREAD

**Issue by Delanyo32** [docker/docker.github.io#5916]
-- not working --
$ sudo add-apt-repository \/
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \/
   $(lsb_release -cs) \/
   stable"

**Comment by thaJeztah** [comment]
Looks like you’re using forward slashes (`/`), not backslashes (`\`) gor line continuation.

But you didn’t provide any information about your system, or the error you received, so this is largely guessing

**Comment by Delanyo32** [comment]
@thaJeztah  i am running Ubuntu 16.04, i was following the tutorial on the docker site on how to install docker on Ubuntu. However when I ran the command to add the repository, i keep getting repository invalid error

**Comment by thaJeztah** [comment]
It you are using forward slashes, then that's expected yes;

```bash
$ sudo add-apt-repository /
Error: '/' invalid
```

Changing to backslashes fires that;


```bash
$ sudo add-apt-repository \
"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) \
stable"
```

**Comment by Delanyo32** [comment]
When i tried that, i get  
Error: "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
xential  \ stable" invalid

**Comment by gbarr01** [comment]
Hi, @Delanyo32 , try without the continuation: 

`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"`

If that doesn't help, refer to this post for help: 
https://askubuntu.com/questions/989881/error-deb-arch-amd64-https-download-docker-com-linux-ubuntu-xenial-sta
