### ISSUE TITLE
Docker docs still use (soft-deprecated) `graph` instead of `data-root`

### ISSUE THREAD

**Issue by JoshuaSCochrane** [docker/docker.github.io#5922]
The use of `graph` has been soft-deprecated since moby/moby#28696 in favor of the more descriptive `data-root`, but the docs still refer to `graph` (apparently throughout). I only learned about `data-root` when I saw a comment on a GH discussion...

File: [config/daemon/systemd.md](https://docs.docker.com/config/daemon/systemd/), CC @johndmulhausen

**Comment by JoshuaSCochrane** [comment]
@mistyhacks Thanks for removing specifically `--graph`, but config references to just `"graph"` and doc references to 'graph' should also be replaced. I suppose I could check this out and create the PR in order to grep the codebase for 'graph', but... Sorry I wasn't more descriptive in the original request, but I figured a 'grep' of the docs codebase would reveal more instances.

A few examples I see when [searching the 'Docs' online](https://docs.docker.com/search/?q=graph):
* [Control Docker with systemd/Runtime directory and storage driver](https://docs.docker.com/config/daemon/systemd/#runtime-directory-and-storage-driver) uses `"graph"` in the `daemon.json` example
* [Daemon CLI (dockerd) - Edge](https://docs.docker.com/edge/engine/reference/commandline/dockerd/) page has a few references:
  * These aren't direct config examples, and I'm not 100% sure if the _term_ 'graph' (in this `/var/lib/docker' usage) is deprecated in favor of 'data root' (or just the _setting_), so I'll defer to your judgement, but they look applicable to me
  * [Daemon storage-driver](https://docs.docker.com/edge/engine/reference/commandline/dockerd/#daemon-storage-driver) references 'devicemapper **graph** location – typically /var/lib/docker/devicemapper'
  * [ZFS Options](https://docs.docker.com/edge/engine/reference/commandline/dockerd/#zfs-options) references 'where docker **graph** (/var/lib/docker) is located'
* There _may_ be other examples, or maybe not - I'm not sure

Note that not _all_ references to 'graph' may need to be replaced - I _think_ things referencing 'graph drivers' may be ok. Not sure.

**Comment by nickbreen** [comment]
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-storage-driver still refers to a `-g` option for `dockerd` too.

Confusingly without any explanation of what it is! These references should(?) be updated to `--data-root` too.
