### ISSUE TITLE
Link to 'storage driver overview' is broken.

### ISSUE THREAD

**Issue by davidneudorfer** [docker/docker.github.io#5930]
File: [storage/storagedriver/select-storage-driver.md](https://docs.docker.com/storage/storagedriver/select-storage-driver/), CC @johndmulhausen 

Third paragraph:

> After you have read the **storage driver overview**, the next step is to choose the best storage driver for your workloads. In making this decision, there are three high-level factors to consider:

Link to **storage driver overview** is broken.

**Comment by mistyhacks** [comment]
A redirect from the broken link needs to be added to https://docs.docker.com/storage/storagedriver/
