### ISSUE TITLE
Start contributing link is broken

### ISSUE THREAD

**Issue by wkruse** [docker/docker.github.io#5931]
### Problem description

Click on `START CONTRIBUTING` on https://www.docker.com/open-source redirects to https://docs.docker.com/project/who-written-for/ which shows `Sorry, we can't find that page`.

### Problem location

- I saw a problem on the following URL: https://www.docker.com/open-source

Related to #188.

**Comment by wkruse** [comment]
On the same page the links [guides you through the contribution process](http://docs.docker.com/project/who-written-for/) and [and more](http://docs.docker.com/project/make-a-contribution/) are also broken.

**Comment by mistyhacks** [comment]
Some `redirect_from:` items for those endpoints need to be added to https://docs.docker.com/opensource/ways/
