### ISSUE TITLE
Mounting host directories on a running docker container

### ISSUE THREAD

**Issue by lrodri29** [docker/docker.github.io#5935]
I believe that currently, to mount a host's directory to a docker container, you must do so when first running the container. However I sometimes find myself having to mount a different directory on the container once it is running but have to first stop it before mounting. Will this be fixed in the future?

Thank you very much for your time and for DOCKER!

**Comment by gbarr01** [comment]
Hi, @lrodri29 , thanks for your question. This does not appear to be a docs problem so I am going to close this issue.  

Please ask your question in the forums: [https://forums.docker.com/](https://forums.docker.com/)
