### ISSUE TITLE
Please note that --tmpfs option usage should be superceded by --mount with type=tmpfs

### ISSUE THREAD

**Issue by sanseihappa** [docker/docker.github.io#5941]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/), CC @johndmulhausen

The guide suggests using `--mount` instead of `--tmpfs`

https://docs.docker.com/storage/tmpfs/#choosing-the-tmpfs-or-mount-flag

It would be good to have that note in the reference docs as well.

**Comment by mistyhacks** [comment]
Addressed in the upstream issue. Thanks!
