### ISSUE TITLE
referencing links documentation is unclear

### ISSUE THREAD

**Issue by efx** [docker/docker.github.io#5950]
File: [compose/networking.md](https://docs.docker.com/compose/networking/), CC @gbarr01 
Reading through this documentation, I was unsure if I should follow the advice listed in the Links section.
If you navigate to the referenced links documentation: https://docs.docker.com/compose/compose-file/#links, it warns this behavior will be deprecated.
Shouldn't the deprecation also be noted on compose/networking.md ?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
