### ISSUE TITLE
Configure Docker to start on boot:  Reactivate init job

### ISSUE THREAD

**Issue by EricAtHaufe** [docker/docker.github.io#5956]
File: [engine/installation/linux/linux-postinstall.md](https://docs.docker.com/engine/installation/linux/linux-postinstall/), CC @mistyhacks 

Hi,  I am new to docker and  was working my way through the well written documentation.    When I got to the part about "chkconfig,"  I was not sure if infor is correct;  since got error on my terminal when tried the command.   I google and learn that Ubuntu does not support command;  Ubuntussuers site states that "If you want to re-enable an init job, simply delete the .override file (or remove the keyword "manual" in this file)."  Might consider updating the document.     Please keep up the good work.  Thanks

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
