### ISSUE TITLE
Feedback for: engine/installation/linux/ubuntulinux.md, Configure Docker to start on boot

### ISSUE THREAD

**Issue by julianfoad** [docker/docker.github.io#596]
File: [engine/installation/linux/ubuntulinux.md](https://docs.docker.com/engine/installation/linux/ubuntulinux/)

This seems to be out of date:

> For 15.04 and up, to configure the docker daemon to start on boot, run
> > $ sudo systemctl enable docker

For me, this seems to have been done by the package installation.
(Ubuntu 16.04, docker-engine package version 1.12.3)

If you agree, please remove it from the doc. (Shorter doc == better doc.)

**Comment by julianfoad** [comment]
And correspondingly in the "Install" section, step 4 "Start the docker daemon" seems to be obsolete.

Of course you don't have to just  delete the text. It may be even better to replace these steps with notes explaining that these things have been done automatically ("since version xxx"?), and this is how to do (and undo) them manually if required. Depends how long or short you want this doc to be.

**Comment by mstanleyjones** [comment]
@julianfoad there were enough people who got confused before we had these steps that we left them in as 'NOOP' instructions. You can get some history from @thaJeztah ...

But thank you for the feedback. You might want to check out #640 as well.

**Comment by thaJeztah** [comment]
Correct. Thanks for reporting; you are absolutely right that these steps should not be needed. Apparently there are certain configurations / situations where docker did not start after installation (although we haven't had reports of those recently). Alter a lot of discussion, and users `+1`-ing, we decided that it wouldn't hurt to add these steps.
