### ISSUE TITLE
unable to remove volume

### ISSUE THREAD

**Issue by ANGELMARS** [docker/docker.github.io#5971]
I create a symbolic link.
Fail to remove docker volume.
Docker version 17.12.0-ce, build c97c6d6

[name@local ~]$ **sudo ln -s /data/volumes /var/lib/docker/volumes**
[name@local ~]$ sudo docker volume create test
[name@local ~]$ **sudo docker volume rm test**
Error response from daemon: unable to remove volume: remove test: Unable to remove a directory of out the Docker root **/var/lib/docker: /data/volumes/test/_data**

**Comment by gbarr01** [comment]
Hi, @ANGELMARS , I am going to close this issue because it does not appear to be related to docs. If it _is_ a docs bug, please let us know the page and we will reopen if necessary. 

Otherwise, please ask your question on the Docker Forums: https://forums.docker.com/
