### ISSUE TITLE
404 at /userguide/dockervolumes/

### ISSUE THREAD

**Issue by madikizelap** [docker/docker.github.io#5983]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by gbarr01** [comment]
Hi, @madikizelap. Thanks for your submission. What URL is broken? 

We changed some things around, and currently, this...

[https://docs.docker.com/engine/userguide/dockervolumes](https://docs.docker.com/engine/userguide/dockervolumes)

... redirects to this (as expected): 

[https://docs.docker.com/storage/volumes/](https://docs.docker.com/storage/volumes/)

I am going to close this but if you feel something is still broken, please let us know.

**Comment by thaJeztah** [comment]
Looks like the report is for `/userguide/dockervolumes/`, which could be a very old link (before docs were moved to `/engine/`)

**Comment by gbarr01** [comment]
Thanks, @thaJeztah ... and  after `/engine` to `/storage/volumes`

**Comment by thaJeztah** [comment]
hm, yes, looks like we keep changing 😞, so may need more redirects if they're not in place
