### ISSUE TITLE
Add docs on docker service create --host

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#5994]
I was looking for a way to add entries to the `/etc/hosts` of containers created with `docker service create`.

[The docker run reference](https://docs.docker.com/engine/reference/run/#network-settings) makes it clear that there's the `--add-hosts` option, and it explains how to use it.

But the [docker service create reference](https://docs.docker.com/engine/reference/commandline/service_create/) isn't so clear about this. It mentions the `--host` option but doesn't tell how to use it and what's the syntax expected.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
