### ISSUE TITLE
--user lacks extended description and usage policy is unclear

### ISSUE THREAD

**Issue by gdennie** [docker/docker.github.io#5995]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/), CC @johndmulhausen

**Comment by gbarr01** [comment]
Hi, @gdennie 

The contents of this page are automatically generated from Docker's source code. If you want to suggest a change, you'll need to find the string by searching this repo:  https://github.com/docker/cli
