### ISSUE TITLE
Add docker update version of the command as well.

### ISSUE THREAD

**Issue by lukemcgregor** [docker/docker.github.io#5998]
File: [config/containers/start-containers-automatically.md](https://docs.docker.com/config/containers/start-containers-automatically/), CC @johndmulhausen 

It would be really useful to know that you can change this setting on a running image using `docker update --restart....` as well as on a new image

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
