### ISSUE TITLE
Feedback for: compose/wordpress.md

### ISSUE THREAD

**Issue by sanscontext** [docker/docker.github.io#601]
File: [compose/wordpress.md](https://docs.docker.com/compose/wordpress/)

I received a question forwarded to me from a user feedback list. I'm pretty sure both `.yml` and `.yaml` work, but perhaps it's worth noting either way?

> Subject: wrong extension
> Date: Nov 16 2016, at 9:41 am
> 
> Hi, yesterday i was reading one of your documentation pages and i think i found a small but crucial mistake for someone just starting like me.
> 
> on the page https://docs.docker.com/compose/wordpress/
> 
> POINT 1, last line “docker-compose.yaml”… shouldn’t it be .yml ?

**Comment by londoncalling** [comment]
Closing this issue, as it's been addressed in the docs, referenced above
