### ISSUE TITLE
Correct Metrics IP in daemon config

### ISSUE THREAD

**Issue by bkauf** [docker/docker.github.io#6012]
File: [config/thirdparty/prometheus.md](https://docs.docker.com/config/thirdparty/prometheus/), CC @johndmulhausen 

The 127.0.0.1 IP in the daemon.config file is not correct, you'd need the eth0 IP of the host for this setup to work since prometheus is running inside a container. In your screen shots you are using 192.168.65.1 or this - that is the IP you'd have to put in the prometheus config file in the target instead of the 'localhost' entry in there now and also in the daemon.json config:

Example: daemon.json file
```
{
  "metrics-addr" : "192.168.65.1:9323",
  "experimental" : true
}
```
snippet of the prometheus config to connect to this engine as a target 

```
    static_configs:
      - targets: ['192.168.65.1:9323']
```

**Comment by Baha-sk** [comment]
this is not a proper solution, it doesn't work on a Mac, I've tried to use the local IP address for my network adapter, but it doesn't work. Still getting network refused

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
