### ISSUE TITLE
In the section Build app

### ISSUE THREAD

**Issue by gopa810** [docker/docker.github.io#6013]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @johndmulhausen

IN the section Build app, just before command "docker build -t friendlyhello .", please mention that user MUST NOT omit the dot at the end. It is easily to be overlooked, so user will be saved from unnecessary dilema. I have not included dot at the end of command, so I was 1 minute thinking what is wrong on the site...  Dot (local dir) can be placed also right after "build" word, so it is not omitted when copy-pasting.

**Comment by gbarr01** [comment]
Hi, @gopa810 , I totally agree and have that covered in my upcoming rewrite. Thanks for bringing it up. This is how the step will look when I'm done: 

> Build the image with the files in _this_ directory (`.`) and tag it with a meaningful name such as ...
