### ISSUE TITLE
404 at /datacenter/dtr/reference/cli/

### ISSUE THREAD

**Issue by sujaypillai** [docker/docker.github.io#6014]
Link to [reference documentation](https://docs.docker.com/datacenter/dtr/reference/cli/) on this [page](https://docs.docker.com/datacenter/dtr/2.4/guides/admin/upgrade/) is broken

**Comment by gbarr01** [comment]
Thanks, @sujaypillai . While we fix, here is the new link (change the version as necessary): [https://docs.docker.com/datacenter/dtr/2.4/reference/cli/](https://docs.docker.com/datacenter/dtr/2.4/reference/cli/)

cc: @joaofnfernandes
