### ISSUE TITLE
Get Docker EE for CentOS page references RHEL version

### ISSUE THREAD

**Issue by arueth** [docker/docker.github.io#6015]
File: [install/linux/docker-ee/centos.md](https://docs.docker.com/install/linux/docker-ee/centos/), CC @johndmulhausen 

The statement:
```
If selinux is enabled, the overlay2 storage driver is only supported on RHEL 7.4 or higher.
```
should reference the CentOS version, not RHEL.

**Comment by joaofnfernandes** [comment]
@dmp42 we have two contradictory statements. The [compatibility matrix](https://success.docker.com/article/Compatibility_Matrix) states that for CentOS we only support the devicemapper driver.
But the [CentOS install docs](https://docs.docker.com/install/linux/docker-ee/centos/) states that overlay2 is now supported and the preferred driver. Which one is correct?

Also do we have any idea on what version of CentOS you need to have if you're using overlay2+selinux?

---
Here's what the docs are saying
<img width="623" alt="1" src="https://user-images.githubusercontent.com/1525937/36320715-efcde9d8-12fb-11e8-8d04-64f8ae126d6f.png">

**Comment by gbarr01** [comment]
Fixed by https://github.com/docker/docker.github.io/pull/6363
