### ISSUE TITLE
You have an error in one of the docs

### ISSUE THREAD

**Issue by nirsv** [docker/docker.github.io#6023]
File: [index.md](https://docs.docker.com/), CC @johndmulhausen 
Under: https://docs.docker.com/network/network-tutorial-standalone/#other-networking-tutorials
You need to change from:
docker network connect alpine-net alpine4  to:
docker network connect bridge alpine4
![image](https://user-images.githubusercontent.com/18029794/36287230-485d94e4-12bc-11e8-9779-ea4c8e0640d4.png)

**Comment by joaofnfernandes** [comment]
Fixed via #5981
