### ISSUE TITLE
Docs don't provide a strategy to migrate away from `group_add`

### ISSUE THREAD

**Issue by stefanlasiewski** [docker/docker.github.io#6024]
The page https://docs.docker.com/compose/compose-file/compose-versioning/#version-3 says:

> Removed: volume_driver, volumes_from, cpu_shares, cpu_quota, cpuset, mem_limit, memswap_limit, extends, group_add. See the upgrading guide for how to migrate away from these

However, the 'upgrading' guide doesn't have provide a way to migrate away from 'group_add'. Instead, https://docs.docker.com/compose/compose-file/compose-versioning/#version-2x-to-3x simply says this:

> group_add: This option has been removed for version: "3.x" Compose files.

group_add is a very useful command when running containers in a multi-tenant system, or when running containers as non root (OpenShift and Kubernetes have similar concepts). If it has been removed from Docker Compose v3, the docs should provide a strategy to migrate to something else.

File: [compose/compose-file/compose-versioning.md](https://docs.docker.com/compose/compose-file/compose-versioning/), CC @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
