### ISSUE TITLE
[18.03] update documentation for "SCTP port mapping"

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#6039]
### Problem description

https://github.com/docker/cli/pull/278 completed the "coding" side of a series of pull requests to add support for the SCTP protocol when publishing ports (see the graph at the top of https://github.com/moby/moby/pull/33922#issue-128554970).

Documentation changes are likely needed in some locations to mention the new option, and possibly some examples and/or description when to use this (?).

ping @AkihiroSuda @ishidawataru 

/cc @gbarr01 

### Project version(s) affected

Engine 18.03 and up

**Comment by AkihiroSuda** [comment]
opened https://github.com/docker/cli/pull/900 and https://github.com/docker/docker.github.io/pull/6078

cc @ishidawataru

**Comment by ishidawataru** [comment]
@AkihiroSuda Thanks, LGTM

**Comment by gbarr01** [comment]
References: 
https://github.com/docker/docker-ce/blob/v18.03.0-ce-rc3/CHANGELOG.md
https://github.com/docker/swarmkit/pull/2298

Possible doc location:
https://docs.docker.com/engine/swarm/ingress/#publish-a-port-for-tcp-only-or-udp-only

**Comment by gbarr01** [comment]
Hi, @thaJeztah @AkihiroSuda, I scraped together some documentation from your various PRs but the example at bottom did not work for me. I wonder if there is a simpler example we can use. 

For this page: https://docs.docker.com/engine/swarm/ingress/

> Docker supports SCTP (Stream Control Transmission Protocol) port mapping. SCTP is widely used as a transport protocol for cellular networks. With SCTP support, you can run applications such as Diameter within your Docker containers. 
> 
> Example: 
> 
> ```
> $ docker run -p 10000:20000/sctp mgoelzer/alpine-socat socat sctp-listen:20000 system:cat
> $ docker run -it --net=host mgoelzer/alpine-socat socat stdin sctp4-connect:127.0.0.1:10000,bind=127.0.0.1
> hello
> hello
> ```

Should I expect something like this for the CLI page?  https://docs.docker.com/engine/reference/commandline/service_create/#publish-service-ports-externally-to-the-swarm--p-publish

> Option:		protocol
> Short syntax: 	`--publish 8080:80/sctp`
> Long syntax: 	`--publish published=8080,target=80,protocol=sctp`
> Description: 	Non-native protocol accessible by mapping TCP port.

**Comment by AkihiroSuda** [comment]
@ishidawataru 

Do you know any free and practical Docker image that is suitable as an example usecase?

**Comment by gbarr01** [comment]
Addressed here: https://github.com/docker/docker.github.io/pull/6078
