### ISSUE TITLE
tl_PH Tagalog Localization

### ISSUE THREAD

**Issue by cordeta** [docker/docker.github.io#6040]
Hi i would like to contribute my expertise in Tagalog Localization of Filipino Translation .A staging repo would be fine for me . Rest assured that my work would be credible

**Comment by joaofnfernandes** [comment]
@cordeta Right now we're not localizing the docs, and don't have plans to do it in the near future 😢 For that reason I'll close this issue.

But keep in mind that the whole documentation website and content is open source under the Apache License 2.0. This means that you can fork, reuse, and edit as much of the docs as you want. So if you want to create a Filipino version and host it yourself you have some head start.

**Comment by cordeta** [comment]
Thak you for that offer sir . But we are graded by our sponsors in which we have to commit our localization to the Main Branch . If you think that the project is open for localization you call my attention anytime

Cheers !
