### ISSUE TITLE
daemon.json type mismatch: json-file driver opt `max-file` expects string, not integer

### ISSUE THREAD

**Issue by Leglaw** [docker/docker.github.io#6041]
File: [config/containers/logging/json-file.md](https://docs.docker.com/config/containers/logging/json-file/), CC @johndmulhausen 

Under Options, row `max-file`, description states:
> A positive integer.

This is a misrepresentation. If you use a positive integer in the daemon.json, the dockerd service will output the following error:
> cannot unmarshal number into Go value of type string

Not sure if it is particular to this json-file configuration or of it common in common throughout the daemon.json configuration, but it should be stated somewhere that it expects a type of string of an integer.

**Comment by joaofnfernandes** [comment]
Looks like the docs are wrong. [Looking at the source](https://github.com/moby/moby/blob/master/daemon/logger/loginfo.go#L13), the driver options are `string=string`.

[The tests](https://github.com/moby/moby/blob/master/daemon/logger/jsonfilelog/jsonfilelog_test.go#L145), also confirm that.

**Comment by thaJeztah** [comment]
The docs describe " A positive integer plus a modifier representing the unit of measure (k, m, or g)", which looks correct to me, although perhaps a bit difficult to grasp

**Comment by joaofnfernandes** [comment]
@thaJeztah it's the `max-file` option, not `max-size`.
I was about to make the same mistake when writing my original reply 😂

**Comment by thaJeztah** [comment]
oh! you're right, exactly how I got there.

Hm, so, yes, thinking how this should be documented. The issue here is that the "logging-driver options" are a generic way to pass options to the driver, for which strings are used.

The intent was to describe that (on the comandline) a numeric value is expected (the shell doesn't really care about integers or strings that respect). Some extra examples for the daemon.json could be useful likely

**Comment by Leglaw** [comment]
Sorry about the confusion in the title that I too got wrapped up in... m(_ _)m

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
