### ISSUE TITLE
Inconsistent documentation and implementation of clone and unshare

### ISSUE THREAD

**Issue by chrisstaite** [docker/docker.github.io#6045]
File: [engine/security/seccomp.md](https://docs.docker.com/engine/security/seccomp/), CC @johndmulhausen 

The documentation states that unshare -U and clone CLONE_USERNS are allowed. However, moby/profiles/seccomp/default.json does not implement this exception.

This is demonstrated by running the following:
docker run -ti --rm ubuntu unshare -U /bin/bash

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
