### ISSUE TITLE
The {{.ID}} formatting string is missing from the table of formatting options

### ISSUE THREAD

**Issue by thebsdbox** [docker/docker.github.io#6055]
The `docker node ps --format " {{.ID}}"` is valid but not part of the documentation

File: [engine/reference/commandline/node_ps.md](https://docs.docker.com/engine/reference/commandline/node_ps/), CC @johndmulhausen

Signed-off-by: Dan Finneran <daniel.finneran@gmail.com>

**Comment by gbarr01** [comment]
Thanks, @thebsdbox.  

@thaJeztah , should we add `.ID` to the table under "Formatting" here: https://docs.docker.com/engine/reference/commandline/node_ps/#formatting


> **Placeholder | Description**
> .ID                  | Container ID

**Comment by thebsdbox** [comment]
If you want to have the unique identifier for the container than this is pretty much a requirement.

**Comment by gbarr01** [comment]
Thanks, @thebsdbox. Some of these reference docs are auto-generated from other repos so we just need to get the update to the right channels.

**Comment by thaJeztah** [comment]
Yes, looks like that's missing. The easiest way to get a list of available fields is to output as JSON;

```bash
docker node ps --format '{{json .}}' | jq .
{
  "CurrentState": "Running 20 hours ago",
  "DesiredState": "Running",
  "Error": "",
  "ID": "qxf9cwioii26",
  "Image": "debian:stretch-slim",
  "Name": "tmpfstest.1",
  "Node": "linuxkit-025000000001",
  "Ports": ""
}
{
  "CurrentState": "Running 20 hours ago",
  "DesiredState": "Running",
  "Error": "",
  "ID": "jhz1t968jk0m",
  "Image": "nginx:alpine",
  "Name": "mystack_web.1",
  "Node": "linuxkit-025000000001",
  "Ports": ""
}
``` 

@thebsdbox the Markdown file that's used to generate that part of the docs is in the docker/cli repository: https://github.com/docker/cli/blob/master/docs/reference/commandline/node_ps.md

Are you interested in opening a PR to fix?

**Comment by thebsdbox** [comment]
Sure thing @thajeztah, I'll do it on Monday when I get home.

**Comment by thaJeztah** [comment]
Thanks!

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/cli/pull/1598 to fix
