### ISSUE TITLE
Docker for Go developer's lab

### ISSUE THREAD

**Issue by dharnnie** [docker/docker.github.io#6057]
Hey guys,
Can we have a proper Docker for Go developer's lab on the docker documentation? Every blog post I have found does things differently. Just like we have for Rails, Node, etc.

Meanwhile, I believe Docker was built with go.

File: [develop/index.md](https://docs.docker.com/develop/), CC @johndmulhausen

**Comment by gbarr01** [comment]
Hi, @dharnnie , thanks for the request. We will do what we can.

**Comment by dharnnie** [comment]
Thank you @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
