### ISSUE TITLE
Docker FAQ - docker runs "natively" on Windows?

### ISSUE THREAD

**Issue by putztzu** [docker/docker.github.io#6058]
File: [engine/faq.md](https://docs.docker.com/engine/faq/), CC @johndmulhausen

Quote:
> The Docker platform runs natively on Linux (on x86-64, ARM and many other CPU architectures) and on Windows (x86-64).

I find it notable that docker requires running in a Hyper-V instance (hence the Windows 10 Pro and Server requirement), and likely runs a Linux kernel in it.... Although I can't remember this last detail described anywhere would fully explain the Hyper-V requirement.

When has running anything in a virtualized environment been considered to be running natively?
Although I grant that the User Tools do make management **appear** to configure natively running processes.

**Comment by joaofnfernandes** [comment]
You can find more info about this in the [Microsoft docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/#windows-container-types).

I think the statement in that FAQ is technically correct, so I'll close this issue but feel free to comment if you think we can improve something.
