### ISSUE TITLE
no command "docker container ls"

### ISSUE THREAD

**Issue by souravpatnaik** [docker/docker.github.io#6066]
File: [get-started/index.md](https://docs.docker.com/get-started/), CC @johndmulhausen

Hi
my docker version is
#docker --version
Docker version 1.11.2, build 6b27105

while going through docker docs i found some commands are not there in this version, requesting you to update the document or mention in which version below commands can be found.

#docker container ls
docker: 'container' is not a docker command.
See 'docker --help'.

#docker image ls
docker: 'image' is not a docker command.
See 'docker --help'.

#docker container ls -a -q
docker: 'container' is not a docker command.
See 'docker --help'.

i also tried with Docker version 17.03.0-ce , it's not there.

**Comment by gbarr01** [comment]
Hi, @souravpatnaik , thanks for the submission.

I'm guessing that your system is not recognizing Docker version 17.03. In the recent past, we recommended that you use version 1.13 and higher. Please try again and ensure that you are using 17.03.

**Comment by sahanjay** [comment]
try "sudo docker", you might don't have permission

**Comment by souravpatnaik** [comment]
Thanks all, issue solved.

**Comment by qousarbashir** [comment]
@souravpatnaik  Please list the solution.I am facing the same issue.Thanks

**Comment by souravpatnaik** [comment]
@gbarr01 , @ sahanjay , @qousarbashir  
thanks for your comments. Issue already resolved, sorry for my late comment.
I used latest version of docker which support docker container ls .. and like wise commands.

Actually i was using older version of docker and referring a newer version docker document.
@qousarbashir , use latest Docker version.
