### ISSUE TITLE
engine/security/https.md leads to generate invalid SSL Certs.

### ISSUE THREAD

**Issue by fbouliane** [docker/docker.github.io#607]
File: [engine/security/https.md](https://docs.docker.com/engine/security/https/)

Certificates generated by the script in this page generates certificates using the deprecated CommonName and will not be valid.

When using docker-py with latest requests version (2.12.1), the generated certificates [will not be trusted by urllib3 1.19.1][2]. This page should lead to generate certificate with a DNSname Entry in the SubjectAltName along with the IP address to respect the RFC Deprecation.

The [RFC6125][1] supports that client should not check the common name when SubjectAltName IP is provided.

    As noted, a client MUST NOT seek a match for a reference identifier
    of CN-ID if the presented identifiers include a DNS-ID, SRV-ID,
    URI-ID, or any application-specific identifier types supported by the
    client.

[1]: https://tools.ietf.org/html/rfc6125#section-6.4.4
[2]: https://github.com/shazow/urllib3/issues/1043

**Comment by mstanleyjones** [comment]
@cyli @riyazdf can you work with me on this one or let me know who else can?

**Comment by cyli** [comment]
@mstanleyjones Yep - we can help.  :)  #610 does fix the issue that is reported - was there more info that should be added to the docs otherwise?
