### ISSUE TITLE
Missing addition in .bash_profile

### ISSUE THREAD

**Issue by eburgwedel** [docker/docker.github.io#6072]
File: [machine/completion.md](https://docs.docker.com/machine/completion/), CC @gbarr01

Hey guys, total newbie here for anything command line related. Battled with getting docker CLI completion to work, I believe there's a missing piece — the addition of

```
if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi
```

to `.bash_profile` as explained on the CLI completion page for docker compose: https://docs.docker.com/compose/completion/

Added this and it worked.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
