### ISSUE TITLE
unmount does not work

### ISSUE THREAD

**Issue by dmc2015** [docker/docker.github.io#6073]
File: [machine/reference/mount.md](https://docs.docker.com/machine/reference/mount/), CC @gbarr01 

if you try to unmount with the flag you get:
You must have a copy of the fusermount binary locally to use the unmount option

per:
https://github.com/osxfuse/sshfs/issues/31

fusermount does not work for mac, the install isnt' there. Cost me a lot of time and possibly data if I can't unmount this. Please change the docs and find a way to unmount.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
