### ISSUE TITLE
Add instructions to uninstall or almost a warning 

### ISSUE THREAD

**Issue by judavi** [docker/docker.github.io#6079]
File: [install/windows/docker-ee.md](https://docs.docker.com/install/windows/docker-ee/), CC @johndmulhausen 

Docker ee doesn't have an installer, so looks like the installation process is just copy the files and execute the powershell script. The problem comes when cleaning things you try to delete the docker directory and in the way you nuke the machine (https://github.com/docker/for-win/issues/1544)

**Comment by joaofnfernandes** [comment]
Might relate to #5905

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
