### ISSUE TITLE
Wrong instructions for setting service constraints through UCP web UI

### ISSUE THREAD

**Issue by sirlatrom** [docker/docker.github.io#6080]
File: [datacenter/ucp/2.2/guides/admin/configure/add-labels-to-cluster-nodes.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/add-labels-to-cluster-nodes/), CC @jimgalasyn

https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/add-labels-to-cluster-nodes/#add-a-constraint-to-a-service-by-using-the-ucp-web-ui instructs the user to set service constraints under the "Environment" configuration page - but the correct place is under "Scheduling". Both the text and the corresponding screenshot ought to be updated to correct this.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by sirlatrom** [comment]
The issue is still relevant, though I cannot find a similar page in the docs for UCP 3.0 or 3.1.
