### ISSUE TITLE
Clarify how to grow an EE swarm on Azure

### ISSUE THREAD

**Issue by andrevtg** [docker/docker.github.io#6081]
File: [docker-for-azure/index.md](https://docs.docker.com/docker-for-azure/), CC @johndmulhausen

I can't find proper info about growing up (adding workers/managers) to a running swarm created with Docker for Azure template.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
