### ISSUE TITLE
Problem with docker-compose down

### ISSUE THREAD

**Issue by richb-hanover** [docker/docker.github.io#6084]
File: [compose/wordpress.md](https://docs.docker.com/compose/wordpress/), CC @gbarr01 

I had a problem using `docker-compose down` - my database/pages/media were preserved, but many of the plugins and themes were lost when I resumed work with `docker-compose up -d`. I find that `docker-compose stop` preserves everything. Is this a better description? Thanks.

> **Stopping, Shutdown and Cleanup**
>
> To stop the containers, use the command `docker-compose stop`. This halts the container, preserving the entire database. Resume your work with `docker compose up -d` as before.
>
> The command `docker-compose down` removes the containers and default network, but preserves your Wordpress database.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
