### ISSUE TITLE
Incorrect Version In Sample YAML Under "Networks"

### ISSUE THREAD

**Issue by alexfinnarn** [docker/docker.github.io#6087]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01

under "Aliases" on https://docs.docker.com/compose/compose-file/#networks it says 

```yaml
version: '2'
```

I also see `version: '2'` in two other places when I search that index.md file. Volume Configuration Reference under "external" and Network Configuration reference also under "external".

I can make a PR, but I'm not sure if the other parts of those examples need to be updated from version 2, as well.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
