### ISSUE TITLE
Swarm Mode - firewall setup

### ISSUE THREAD

**Issue by damianaiamad** [docker/docker.github.io#6089]
File: [docker-cloud/cloud-swarm/register-swarms.md](https://docs.docker.com/docker-cloud/cloud-swarm/register-swarms/), CC @johndmulhausen 

May I request that recommended firewall settings be included in this documentation. 
I.e. Port ranges and CIDR

The doc tells you that a swarm may be unreachable due to firewall, but not how to securely configure the firewall.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
