### ISSUE TITLE
[RFD] move compose "variable substitution" outside of compose-file reference

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#6091]
### Problem description

Both Docker Compose and Docker (`docker stack ....`) have support for some forms of variable substitution in docker-compose files.

This feature is currently described as part of the compose-file reference (see https://docs.docker.com/compose/compose-file/#variable-substitution), but is not part of the compose-file specification.

In other words: what forms of substitution is supported is not dependent of the version of the compose-file format (2, 3, 3.1), but depends on what you're using to read the compose file (version of Docker Compose, and if you're using Docker Compose, or Docker). While we try to keep them in sync, differences in behavior may be present, and it's possible that support differs (as releases for compose and docker are not "synched"), for example: support for mandatory variables was added to compose in https://github.com/docker/compose/pull/5531 (compose 1.19), and in docker, through https://github.com/docker/cli/pull/893 (which is currently scheduled for docker 18.04, unless we decide to add it to 18.03 before GA).

### Suggestions for a fix

To make it more apparent that these features are not part of the compose-file specification, but a feature of the tools that use them, I suggest to move this section to a separate page (we can still link to that page from the compose file).

ping @shin- @dnephin @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
