### ISSUE TITLE
No "enable_ipv6" In Version 3

### ISSUE THREAD

**Issue by alexfinnarn** [docker/docker.github.io#6099]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/), CC @gbarr01 

From https://docs.docker.com/compose/compose-file/#enable_ipv6 it says enabling IPv6 is "Not supported in Compose File version 3" but in https://docs.docker.com/compose/compose-file/#ipv4_address-ipv6_address there is still reference to that flag. Also, there is still mention of compose version "2.1".

Is that note/caveat correct in version 3?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
