### ISSUE TITLE
Take docker.github.io down

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#6101]
We're serving docker.github.io mostly for historical reasons, but we should take it down given that users are still accessing the docs from this property, and this property doesn't do a full docs build.
A bunch of pages are missing, and you can't see previous versions of the docs there.

Users should only have one url - https://docs.docker.com

Update: I thought that this would be a simple setting on GH, but based on [GH docs](https://help.github.com/articles/unpublishing-a-project-pages-site/), it seems that this would require us to rename the repo 😢

**Comment by joaofnfernandes** [comment]
After reaching out to Github support, it seems that with our setting there's only two options:
* Deleting the repo
* Stop using the master branch

GH support also tells me that renaming the repo won't stop GH pages from being served. It only starts serving the repo from `docker.github.io/repo-name`.

I think the only solution would be to start a new repo and push there whatever we have on master today. Given that we've trained a lot of people in the community to file issues/PR against this repo, I don't think that makes sense (at least on the short term).

For that reason, I'm closing this issue.

**Comment by thaJeztah** [comment]
Can we create a `gh-pages` branch, and have GitHub pages use that one? If that would work, we could have a single page in that branch that simply does a redirect to docs.docker.com.

We can still consider renaming the repo to `docs.docker.com` (e.g.) - github redirect would take care of redirecting people to the right github repository (and one less location where we advertise the "docker.github.io" domain)

**Comment by joaofnfernandes** [comment]
I'll re-open this issue since we have a few more options on the table :D

**Comment by joaofnfernandes** [comment]
Option 1 doesn't work.
I've created a `gh-pages` branch with a single index.html page that redirects to docs.docker.com, but Github settings still don't display an option that allows you to change the GH pages settings.
@thaJeztah I'll leave the branch there so that you can verify this for yourself (don't want to post a screenshot of the repo settings here).

**Comment by thaJeztah** [comment]
Ugh that's a pity, I was hoping we could switch to that branch 😞, looks indeed like it's locked to master because the repo is named like this (IIUC); https://stackoverflow.com/a/39978969/1811501

**Comment by allejo** [comment]
What about creating the `index.html` redirect in the master branch and adding a `.nojekyll` file? I'm imagining the file would prevent the site being built as a Jekyll site and therefore it'd fall back to `index.html`.

**Comment by ondrejsika** [comment]
What about renaming repository? eg. docker/docs

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
