### ISSUE TITLE
If page is managed upstream, send users to correct repo

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#6102]
There's a couple of docs pages that are not managed in the docs repo, but are managed upstream.
For those pages, when the user clicks the `edit this page` they should be directed to the correct repository instead of a GH 404 page.

![1](https://user-images.githubusercontent.com/1525937/36749815-be9755bc-1bb0-11e8-95ea-2aca88b0ed8c.gif)

**Comment by davidjb** [comment]
Something to look out for is the place where the upstream docs are pulled from.  In this case, https://github.com/docker/docker-ce/blob/master/components/cli/docs/reference/run.md (which is pulled in via [fetch-upstream-resources.sh[(https://github.com/docker/docker.github.io/blob/master/_scripts/fetch-upstream-resources.sh#L161))isn't actually its canonical location.  In the comments of that file:

```
<!-- This file is maintained within the docker/cli GitHub
     repository at https://github.com/docker/cli/. Make all
     pull requests against that repo. If you see this file in
     another repository, consider it read-only there, as it will
     periodically be overwritten by the definitive file. Pull
     requests which include edits to this file in other repositories
     will be rejected.
-->
```

So attempting to "edit" at the first upstream location will be rejected.  An editor actually needs to notice that message and then go hunting for the canonical location at https://github.com/docker/cli/blob/master/docs/reference/run.md, and edit that.

For someone like me who wants to help contribute a small fix, this is a whole lot of digging.  Perhaps these types of files could have their own canonical edit URL in the frontmatter YAML and that used in rendering Edit links?

**Comment by jwlangston0183** [comment]
What is this, I'm so lost. Can you help me plz understand.

**Comment by davidjb** [comment]
@jwlangston0183 Which aspect in particular?

**Comment by bermudezmt** [comment]
@peter-docker this relates to the refactor. Can we prioritize this as it's caused a lot of internal and external problems?

**Comment by peter-docker** [comment]
> @peter-docker this relates to the refactor. Can we prioritize this as it's caused a lot of internal and external problems?

@bermudezmt Yes, for sure. Can y'all capture this in your refactor requirements list?

**Comment by craig-osterhout** [comment]
It appears that this fix has been implemented. Clicking "Edit this page" on pages managed in upstream repos (for example: https://docs.docker.com/engine/reference/run/), now redirects to the appropriate GitHub repo instead of a GH 404 error.
