### ISSUE TITLE
Virtual Machine Issue

### ISSUE THREAD

**Issue by chnakamura** [docker/docker.github.io#6106]
File: [storage/bind-mounts.md](https://docs.docker.com/storage/bind-mounts/), CC @johndmulhausen 

Here: https://github.com/moby/moby/issues/22981#event-672064967 it is stated that this doesn't work properly in some virtual machines, if this could be put in the dockers it could solve some confusion.

I was using an ubuntu virtual machine on VMWare on mac OS 10.13.13

Thank you

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
