### ISSUE TITLE
CS Engine vs EE Basic?

### ISSUE THREAD

**Issue by gnomestar** [docker/docker.github.io#6108]
File: [datacenter/ucp/2.2/guides/admin/install/index.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/), CC @JimGalasyn 

The last CS Engine I'm familiar with is 1.13. I don't believe that this is the version of Docker consistent with EE 17.06?

**Comment by thaJeztah** [comment]
I could find a mention of CS on that page, or is it in one of the screenshots?

**Comment by gnomestar** [comment]
> Step 2: Install Docker EE on all nodes
> UCP is a containerized application that requires the commercially supported Docker Engine to run.

Apologies, should have quoted :) 
Think we intended EE Basic here?

**Comment by thaJeztah** [comment]
Ah, yes, looks like it (was looking for “cs”, not “commercially supported”).

If you want to, you can click the “edit this page” button on the docs to open a PR :innocent:

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
