### ISSUE TITLE
It seems that the incorrect sentence exists on this page.

### ISSUE THREAD

**Issue by yihyunyi** [docker/docker.github.io#6110]
File: [develop/develop-images/baseimages.md](https://docs.docker.com/develop/develop-images/baseimages/), CC @johndmulhausen 

It seems that the incorrect sentence exists on this page.

![image](https://user-images.githubusercontent.com/7202790/36765122-1506b074-1c73-11e8-85c8-9d27ebebc9c0.png)

In the sentence, repeated "you" twice.  

Thank you.

**Comment by gbarr01** [comment]
Thanks, @yihyunyi. Do you want to click "edit this page" and remove one? :)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
