### ISSUE TITLE
user defined bridge steps in the doc needs update

### ISSUE THREAD

**Issue by Vishant0031** [docker/docker.github.io#6111]
File: [engine/userguide/networking/default_network/build-bridges.md](https://docs.docker.com/engine/userguide/networking/default_network/build-bridges/), CC @mistyhacks

1. Configure the new bridge.

$ sudo ip link set dev br0 up <======= this is invalid step, this should be:
ip link add name bridge0 type bridge

$ sudo ip addr add 192.168.5.1/24 dev bridge0

$ sudo ip link set dev bridge0 up

Similarly, in this section:
Remove the now-unused docker0 bridge.

$ sudo ip link set dev docker0 down

$ sudo ip link del name br0 <======= there is typo,it should be 
sudo ip link del name docker0

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
