### ISSUE TITLE
Update _config.yml for archives to remove non-maintainers

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#6117]
In `_config.yml` we keep a list of maintainers that automatically get pinged when someone files an issue for a specific docs area.
We've updated master to remove people that are no longer maintainers, but the archive branches are still pinging those people. We should clean that, so that only maintainers get pinged on new issues.

This requires updating the `_config.yml` file for each archive branch where the username is mentioned.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
