### ISSUE TITLE
username for linux VM in scale set

### ISSUE THREAD

**Issue by frankfuu** [docker/docker.github.io#6119]
File: [docker-cloud/cloud-swarm/create-cloud-swarm-azure.md](https://docs.docker.com/docker-cloud/cloud-swarm/create-cloud-swarm-azure/), CC @johndmulhausen 

Just wanted to say that the docs should probably tell us what username was used to provision the linux VMs in the scale set.

I was getting error messages when trying to SSH into the master node. I tried `admin` but didn't work.
```
$ ssh -p 50000 admin@<ssh load balancer ip>
Permission denied (publickey,keyboard-interactive).
```

By luck, I tried using `docker` as the username e.g. `ssh -p 50000 docker@<ssh load balancer ip>` and it worked but hopefully the next person following this tutorial won't need to go through that ;)

**Comment by gbarr01** [comment]
Hi, @frankfuu , I see nothing about scale sets on this page. Can you provide more information?

**Comment by frankfuu** [comment]
On step 9 of this page Docker Cloud instructs the user's Azure Subscription to provision assets (scale sets, load balancers etc) behind the scenes based on a template (which I assume is written by Docker Cloud) to provision x number of master nodes and y number of worker nodes (on step 8).

Once this is done, the user will want to ssh into a given instance within the scale set, however, without knowing what username to use for the ssh session, he/she may not be able to gain access.

**Comment by gbarr01** [comment]
Got it. Thanks, @frankfuu .

**Comment by frankfuu** [comment]
No worries! Thanks @gbarr01 and team for writing these tutorials, it really helps us get started!

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
