### ISSUE TITLE
Overlay network is not automatically created on the second host

### ISSUE THREAD

**Issue by r3mus-n0x** [docker/docker.github.io#6134]
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/), CC @gbarr01 
In tutorial "Use an overlay network for standalone containers" Step 4 suggests that an overlay network "test-net" should be automatically created on the second host once user runs a container using that network. However this doesn't happen since no service has been deployed on the swarm using that network.

**Comment by gbarr01** [comment]
@r3mus-n0x , not sure what you experienced here as the tutorial is accurate through step 4 (and I'm fixing the broken parts in PR #6398 ). Once I push my changes, please try again.
