### ISSUE TITLE
Additional node state

### ISSUE THREAD

**Issue by darwin-traver** [docker/docker.github.io#6136]
File: [datacenter/ucp/2.2/guides/admin/monitor-and-troubleshoot/troubleshoot-node-messages.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/monitor-and-troubleshoot/troubleshoot-node-messages/), CC @JimGalasyn 

Missing node state:
Awaiting healthy status in classic node inventory

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
