### ISSUE TITLE
Tutorial about Docker repositories does not exist

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker.github.io#6137]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @gbarr01 

> The image can be any valid image – it is especially easy to start by **pulling an image** from the [_Public Repositories_](https://docs.docker.com/engine/tutorials/dockerrepos/).

The link (https://docs.docker.com/engine/tutorials/dockerrepos/) no longer exists.

**Comment by gbarr01** [comment]
Hi, @rcjsuen 

The content you are referring to was incorporated into other pages a long time ago. In fact, it only lives in one archive: 

[https://docs.docker.com/v1.12/engine/tutorials/dockerrepos/](https://docs.docker.com/v1.12/engine/tutorials/dockerrepos/)

We cover logging in and pushing to a public repo in the Get Started and also on the Docker Hub pages:

https://docs.docker.com/docker-hub/repos/
https://docs.docker.com/get-started/part2/

I believe these pages should address your concerns. If not, please file another ticket with a detailed account of what you are looking for.

**Comment by rcjsuen** [comment]
@gbarr01 Isn't it better to fix the link instead of relying on redirects?
