### ISSUE TITLE
404 at /en/latest/installation/ubuntulinux/

### ISSUE THREAD

**Issue by sheryf** [docker/docker.github.io#6139]
URL: /en/latest/installation/ubuntulinux/

**Comment by gbarr01** [comment]
Hi, @sheryf , this doesn't look like one of our URLs.  You can find the Ubuntu installation pages here: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by thaJeztah** [comment]
I suspect this is an url from a veeeeeeery long time ago (pre docker 1.0), where we had URLs with language prefix.

@sheryf if you found a site using that link, I suggest to contact the website, asking them to update the link
