### ISSUE TITLE
Add more GO template examples in the formatting section

### ISSUE THREAD

**Issue by Timunas** [docker/docker.github.io#6141]
## Problem
- Please consider add more GO template examples in this page : https://docs.docker.com/config/formatting

Basically the problem is that I was trying to get a container IPAddress using this:

```docker inspect -f "{{.NetworkSettings.Networks.1scix3z5s7j_default.IPAddress}}" fea5b383ac92f3c7d6f71809187a29427e69860ba2ee8c37f77b3aa2a7c0c29d```

But I got this error: 

`Template parsing error: template: :1: bad number syntax: ".1s"`

And I only got this error for network names started by numbers.

I opened an issue (see link below), and it turned out that the problem was in the template that I was using.

So I started to use this template:

```docker inspect --format '{{(index .NetworkSettings.Networks "1scix3z5s7j_default").IPAddress}}' foo```

- Other: Check this [issue](https://github.com/moby/moby/issues/36470) for more deatils.

**Comment by gbarr01** [comment]
Got it. Thanks, @Timunas . We will put it on the to do list.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
