### ISSUE TITLE
CMD needs to be defined if ENTRYPOINT is overriden

### ISSUE THREAD

**Issue by lgandras** [docker/docker.github.io#6142]
### Problem description

The interaction between `CMD` and `ENTRYPOINT` is not fully described. Whenever you override `ENTRYPOINT`, `CMD` will be cleared. If you want to use the old `CMD` with a new `ENTRYPOINT`, you need to declare both in the new `Dockerfile`. As an example, take the PHP `Dockerfile` for fpm (stretch): https://github.com/docker-library/php/blob/master/7.2/stretch/fpm/Dockerfile. If you need to do something like changing the `umask` using the `ENTRYPOINT`, but you still want to use `CMD ["php-fpm"]`, you need to declare both in the new `Dockerfile`. Declaring the `ENTRYPOINT` only will lead to PHP not executing at all, because the `CMD` (parameter for the `ENTRYPOINT`) won't exist.

### Problem location

https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact

### Project version(s) affected

Docker version 18.01.0-ce, build 03596f5

**Comment by thaJeztah** [comment]
Thanks for opening this ticket.

Yes, this may need some additional documentation. Depending on _when_ / _where_ the `ENTRYPOINT` is overridden, the `CMD` is reset.


### Overriding in the same buildstage / single Dockerfile

When changing the `ENTRYPOINT` in the same buildstage, the `CMD` is kept:

```Dockerfile
FROM busybox

CMD ["foo %d bar\n", "1"]
ENTRYPOINT ["echo"]
ENTRYPOINT ["printf"]
```

```bash
docker build --no-cache -t overridden .
```


Running the image shows that `printf` is used:

```bash
docker run overridden
foo 1 bar
```

As can be seen when inspecting the image:

```bash
docker inspect --format 'entrypoint: {{json .Config.Entrypoint}} cmd: {{json .Config.Cmd}}' overridden
entrypoint: ["printf"] cmd: ["foo %d bar\n","1"]
```

### Overriding at runtime (`--entrypoint`)

When overriding at runtime, the `CMD` is reset

```bash
docker run --entrypoint="echo" overridden
# empty output (because CMD is reset)
```

A new cmd can be set by passing it as argument:

```bash
docker run --entrypoint="echo" overridden thisisthenewcommand
thisisthenewcommand
```

### Overridding in a "child" image (`FROM ..`)

When building a new image that _extends_ the original image, the `CMD` is reset:

```Dockerfile
FROM overridden
ENTRYPOINT ["echo"]
```

```bash
docker build --no-cache -t overridden2 .
```

Running the image shows that the `CMD` is reset

```
docker run overridden2
# empty output (because CMD is reset)
```

As can be seen when inspecting the image:

```bash
docker inspect --format 'entrypoint: {{json .Config.Entrypoint}} cmd: {{json .Config.Cmd}}' overridden2
entrypoint: ["echo"] cmd: null
```


### Overriding in a multi-stage build

In a multi-stage build, the situation is the same as when building an image that _extends_ (it just is being done in a single Dockerfile);

```Dockerfile
FROM busybox AS stage1

CMD ["foo %d bar\n", "1"]
ENTRYPOINT ["echo"]
ENTRYPOINT ["printf"]

FROM stage1
ENTRYPOINT ["echo"]
```

```bash
docker build --no-cache -t overridden3 .
```


Running the image shows that `echo` is used, but that the `cmd` is reset:

```bash
docker run overridden3
# empty output (because CMD is reset)
```

And, again, can be seen when inspecting the image:

```bash
docker inspect --format 'entrypoint: {{json .Config.Entrypoint}} cmd: {{json .Config.Cmd}}' overridden3
entrypoint: ["echo"] cmd: null
```

**Comment by thaJeztah** [comment]
The Markdown file used to generate that page in the documentation can be found in the docker/cli repository; https://github.com/docker/cli/blob/master/docs/reference/builder.md

Perhaps you're interested in opening a pull-request to enhance the documentation?

/cc @gbarr01 if you have suggestions for wording to use 🤗

**Comment by thaJeztah** [comment]
The [`ENTRYPOINT` section](https://github.com/docker/cli/blob/afcc78aae356c287177b2ed71f3448258a323fbd/docs/reference/run.md#entrypoint-default-command-to-execute-at-runtime) in the `run` _reference_ actually mentions the behaviour. (We still need to figure out how to deal with `run reference` vs `docker run` command-line reference: it's confusing to have both @gbarr01 )



Other locations that may need to mention this;

- [`ENTRYPOINT` section in the Dockerfile best practices](https://github.com/docker/docker.github.io/blob/aed0b2e2ac522a6c4e9144efbe2da7f97de97c0e/develop/develop-images/dockerfile_best-practices.md#entrypoint)
- the [`docker run` command line reference](https://github.com/docker/cli/blob/d281b72a9890d2085d9c3b700db291039e970765/docs/reference/commandline/run.md) currently doesn't describe the flag
- the [`docker create` command line reference](https://github.com/docker/cli/blob/d281b72a9890d2085d9c3b700db291039e970765/docs/reference/commandline/create.md) also currently doesn't describe the flag; possibly we could have a central location to describe it, and share between `create` and `run`

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
