### ISSUE TITLE
Doc Samples InfluxDB correction

### ISSUE THREAD

**Issue by antsman** [docker/docker.github.io#6143]
File: [_samples/library/influxdb/index.md](https://docs.docker.com/samples/library/influxdb/)

At **MANUALLY INITIALIZING THE DATABASE**
instead of
      `-e INFLUXDB_DB=db0 -e INFLUXDB_ADMIN_ENABLED=true \`
correct is
      `-e INFLUXDB_DB=db0 -e INFLUXDB_HTTP_AUTH_ENABLED=true \`

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
