### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bigb123** [docker/docker.github.io#6145]
There is a typo in "ch of these commands has the same result." in "Examples" section. Probably should be "Each" rather than "ch".

File: [engine/reference/commandline/export.md](https://docs.docker.com/engine/reference/commandline/export/), CC @gbarr01

**Comment by joaofnfernandes** [comment]
Thanks for reporting this @bigb123.
It seems this [was fixed upstream](https://github.com/docker/cli/blob/c26f37c0cce47c2e2c2d8e5f0df261c95c930479/docs/reference/commandline/export.md#examples), so it should make its way to the docs soon.

**Comment by joaofnfernandes** [comment]
Oh... It seems @gbarr01 has a fix for this so I'm re-opening this issue.
