### ISSUE TITLE
Text and example diverge. ATTACH/CONNECT

### ISSUE THREAD

**Issue by sabkent** [docker/docker.github.io#6148]
File: [network/network-tutorial-standalone.md](https://docs.docker.com/network/network-tutorial-standalone/), CC @gbarr01 

Use user-defined bridge networks point 3 states use 
```docker network attach```
but the code example is 
```docker network connect```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
