### ISSUE TITLE
Duplicated command in Get Started, Part 2

### ISSUE THREAD

**Issue by hjonin** [docker/docker.github.io#6149]
Hi,

It seems there is a duplicated command which makes the second one useless in https://docs.docker.com/get-started/part2/#tag-the-image:

> Run **docker image ls** to see your newly tagged image. (You can also use **docker image ls**.)

Thanks!

File: [get-started/part2.md](https://docs.docker.com/get-started/part2/), CC @gbarr01

**Comment by joaofnfernandes** [comment]
@hjonin thanks for reporting this 🙌
I've submitted #6150 to fix this, and it's actually a trivial change. Even if you don't know much about Docker you can help us improve the docs by clicking the 'Edit this page' link. 

<img width="183" alt="screen shot 2018-03-05 at 09 11 41" src="https://user-images.githubusercontent.com/1525937/36989019-4cf8fa9c-2055-11e8-8e46-0d5572dcd445.png">

I know it can be scary or you just don't have the time, but next time you see something as easy as this one, feel free to open a change request 😄
