### ISSUE TITLE
the reference of access remote api with curl (--unix-socket) has syntax error

### ISSUE THREAD

**Issue by cfansimon** [docker/docker.github.io#615]
### Problem description

in the reference of api/docker_remote_api.md, it shows:

```
curl --unix-socket /var/run/docker.sock http:/containers/json
```

but it will always return {"message":"page not found"} in api v1.24

and if exec the follow:
```
curl --unix-socket /var/run/docker.sock http/containers/json
```
it seems to be right. Please check this.

**Comment by johndmulhausen** [comment]
@bfirsh has a PR that will eliminate incorrect API reference information.

**Comment by johndmulhausen** [comment]
Closing this oldie.

**Comment by fatagun** [comment]
Oldie but a goodie, shit still doesnt work. 

`curl --unix-socket /var/run/docker.sock http:/containers/json`
This doesnt work.

**Comment by vaughnbeanz** [comment]
@fatagun I think I get the same result as you when I run:

```curl --unix-socket /var/run/docker.sock http:/containers/json
{"message":"page not found"}
```

However, the following works on my system:

```➜  test docker --version
Docker version 17.12.0-ce, build c97c6d6
➜  test curl --unix-socket /var/run/docker.sock http:/1.34/containers/json
[]
➜  test curl --unix-socket /var/run/docker.sock http/containers/json
[]
```

Note the api version in the first cmd and the lack of ":" in the second command.

I'm not aware of any documentation describing the full form of the url when using curl to access the socket.
