### ISSUE TITLE
Are both Devicemapper & OverlayFS supported for Docker?

### ISSUE THREAD

**Issue by stefanlasiewski** [docker/docker.github.io#6152]
I'm trying to figure out if we should go with Devicemapper or OverlayFS for our CentOS 7.4 (Kernel  3.10.0-693+) systems. However, the Storage Driver documentation has some contradictory statements.

https://docs.docker.com/storage/storagedriver/device-mapper-driver/ says the following:

> devicemapper storage driver is the only supported storage driver for Docker EE and Commercially Supported Docker Engine (CS-Engine) on RHEL, CentOS, and Oracle Linux. See the Product compatibility matrix.

And clearly, the Product compatibility matrix says Devicemapper is supported.

However, this contradicts what I read in https://docs.docker.com/storage/storagedriver/overlayfs-driver/#prerequisites , which makes it sound like OverlayFS is also supported.

> OverlayFS is supported if you meet the following prerequisites:
> * The overlay2 driver is supported for Docker EE and recommended for Docker CE.

But the wording is a little ambiguous, but I read this as "OverlayFS is now supported".

Could you either:

1. Update the docs to clarify that both Devicemapper & OverlayFS are supported
2. Remove the ambiguous wording to clarify that OverlayFS is not yet supported, perhaps with something like this:

> OverlayFS will be supported at a future date when the following prerequisites are met:
> * When the overlay2 driver is officially supported by Docker EE and when it's supported by Docker CE.

File: [storage/storagedriver/device-mapper-driver.md](https://docs.docker.com/storage/storagedriver/device-mapper-driver/), CC @gbarr01

**Comment by joaofnfernandes** [comment]
This issue relates/overlaps with #6015.

@stefanlasiewski based a [comment on that issue](https://github.com/docker/docker.github.io/issues/6015#issuecomment-367479156), we recommend Overlay2 for CentOS.

Ping @dmp42 for visibility.

**Comment by stefanlasiewski** [comment]
Thanks for the tip. Sounds like the documentation for Devicemapper is a little out of date.

I fixed a typo: I'm actually using Docker CE (not EE).

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
