### ISSUE TITLE
Adding configuration file example to dockerd "daemon socket option" item

### ISSUE THREAD

**Issue by FlyingOnion** [docker/docker.github.io#6154]
### Suggestions for a fix

Configuration file example could be added in the "daemon socket option" item <https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option> 
like the "options per storage driver" item <https://docs.docker.com/engine/reference/commandline/dockerd/#options-per-storage-driver> does. 
Like this: 
<pre>
{
  "hosts": [
    "unix:///var/run/docker.sock",
    "tcp://127.0.0.1:2375"
  ]
}
</pre>
This configuration works in fedora 26 with docker 17.12.1-ce.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
