### ISSUE TITLE
Wrong version number in docker for windows release notes?

### ISSUE THREAD

**Issue by LKajan** [docker/docker.github.io#616]
### Problem description

Currently on windows release notes it states that newest version is 1.13.3. Should that be 1.12.3?

There is also a high probability I have understood something wrong.

### Problem location

https://github.com/docker/docker.github.io/blob/master/docker-for-windows/release-notes.md

**Comment by londoncalling** [comment]
@LKajan this is fixed now. Thanks for the feedback. See related PR #645 for details on the file changes.
