### ISSUE TITLE
Recommended storage driver for CentOS contradicts the Get Docker CE for CentOS page

### ISSUE THREAD

**Issue by inclementweather** [docker/docker.github.io#6162]
File: [storage/storagedriver/select-storage-driver.md](https://docs.docker.com/storage/storagedriver/select-storage-driver/), CC @gbarr01 

https://docs.docker.com/install/linux/docker-ce/centos/

**Comment by joaofnfernandes** [comment]
Relates to #6152

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
