### ISSUE TITLE
Document header is inconsistent with body - Is Ubuntu 16.04 supported for docker engine 12.1 ?

### ISSUE THREAD

**Issue by yairinot** [docker/docker.github.io#6166]
File: [cs-engine/1.12/index.md](https://docs.docker.com/cs-engine/1.12/), CC @joaofnfernandes

The top of the document states:

> CS Docker Engine can be installed on the following operating systems:
>
> CentOS 7.1/7.2 & RHEL 7.0/7.1/7.2 (YUM-based systems)
> **Ubuntu 14.04 LTS**
> SUSE Linux Enterprise 12

But when continue reading the instructions I can see
> Install on **Ubuntu 14.04 LTS or 16.04 LTS**

So if one is looking on the header only he can think Ubuntu 16.04 is not supported

**Comment by thaJeztah** [comment]
IIRC, Ubuntu 16.04 wasn’t supported / verified for Docker CS (Commercially Supported, which predates Enterprise Edition) 1.12.

Be aware though that Docker CS 1.12 reached end of life/end of support

**Comment by joaofnfernandes** [comment]
According to the [compatibility matrix](https://success.docker.com/article/Compatibility_Matrix), only Ubuntu 14.04LTS is supported.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
