### ISSUE TITLE
Need to clarify Windows doesn't support host networking

### ISSUE THREAD

**Issue by PatrickLang** [docker/docker.github.io#6168]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/), CC @gbarr01 

> With the network set to host a container will share the host’s network stack and all interfaces from the host will be available to the container. The container’s hostname will match the hostname on the host system. Note that --mac-address is invalid in host netmode. Even in host network mode a container has its own UTS namespace by default. As such --hostname is allowed in host network mode and will only change the hostname inside the container. Similar to --hostname, the --add-host, --dns, --dns-search, and --dns-option options can be used in host network mode. These options update /etc/hosts or /etc/resolv.conf inside the container. No change are made to /etc/hosts and /etc/resolv.conf on the host.

There's a few point we need to clarify around Windows

1. host networking isn't supported on Windows

2. Customers often use this expecting to inherit /etc/resolv.conf and /etc/hosts from the host. There is no way to do this on Windows `nat` networking - only the DNS server addresses are propagated to the container.

**Comment by PatrickLang** [comment]
cc @ekitagawa @daschott

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
