### ISSUE TITLE
Feedback for: engine/security/trust/trust_sandbox.md

### ISSUE THREAD

**Issue by reinerj** [docker/docker.github.io#618]
File: [engine/security/trust/trust_sandbox.md](https://docs.docker.com/engine/security/trust/trust_sandbox/)

Hello,

we just tried to play with the content trust demo. sandboxregistry and sandboxtrusteddocker_notaryserver_1 was started but the trustsandbox failed. The logs show the following output. 

cp: can't stat '/notarycerts/root-ca.crt': No such file or directory

The notaryserver 

ls /go/src/github.com/docker/notary/fixtures/

So it looks like there is something missing in the image

**Comment by mstanleyjones** [comment]
Duplicate of #185 which was fixed in #629. Please reopen this if it is still not working for you. Thanks!
