### ISSUE TITLE
Missing macos platform in 'What platforms does docker run on' section.

### ISSUE THREAD

**Issue by mojochao** [docker/docker.github.io#6181]
The FAQ mentions that macOS is supported at the top, but not in the 'What platforms does docker run on' section.

**Comment by joaofnfernandes** [comment]
@mojochao Can you point me to the url of the article that you think needs improvement?

**Comment by mojochao** [comment]
Sure.  The page is https://docs.docker.com/engine/faq/.  The first section of page mentions availability on macOS but the https://docs.docker.com/engine/faq/#what-platforms-does-docker-run-on section does not.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
