### ISSUE TITLE
Screen shot out of date

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#6185]
File: [datacenter/ucp/2.2/guides/admin/configure/add-labels-to-cluster-nodes.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/add-labels-to-cluster-nodes/), CC @JimGalasyn 
One of the screen shots here is out of date and has an invalid service label of `disk = ssd`:

![https://docs.docker.com/datacenter/ucp/2.2/guides/images/add-constraint-to-service.png](https://docs.docker.com/datacenter/ucp/2.2/guides/images/add-constraint-to-service.png)

The compose example is correct above it but if you're loosely following along to deploy your own service, you may not catch the different syntax.

**Comment by JimGalasyn** [comment]
@mbentley Thanks for the feedback! What are the valid labels for `node.labels.disk`?

**Comment by mbentley** [comment]
The docker-compose YAML has the correct label.  `node.labels.disk == ssd`

**Comment by mbentley** [comment]
The text instruction of what you should enter also needs to be updated and not just the screen shot:
![screenshot 2018-04-12 at 1 19 02 pm](https://user-images.githubusercontent.com/414445/38693171-282f022a-3e54-11e8-8816-0038793c4603.png)

**Comment by JimGalasyn** [comment]
Great, thanks!

**Comment by JimGalasyn** [comment]
@mbentley Funny, it doesn't work if I use `node.labels.disk` on the node, but it does work when I use just `disk`.

**Comment by mbentley** [comment]
Oh sorry, I misread the tex...  My fault!  The labeling of the node is correct.  I incorrectly saw the text and thought it was labeling the service.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
