### ISSUE TITLE
Cannot install docker-ce on ubuntu 16.04

### ISSUE THREAD

**Issue by measwel** [docker/docker.github.io#6186]
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable"

This leads to:

aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Ubuntu/xenial

**Comment by joaofnfernandes** [comment]
It seems the command is using differs a bit from what is presented on the [install docs](https://docs.docker.com/install/linux/docker-ce/ubuntu/), specifically this part

![screen shot 2018-03-09 at 14 55 25](https://user-images.githubusercontent.com/1525937/37233918-10c0d68c-23aa-11e8-8a64-d6ccf36fc701.png)

Have you tried using this ^^ instead?

**Comment by measwel** [comment]
Yes Joao,

I keep getting the following error, also when following the official guide:

```
sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 114, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 607, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Ubuntu/xenial
```

**Comment by joaofnfernandes** [comment]
I've tested the install procedure on a Ubuntu 16.04 and everything seems to work.
Searching around I think the problem might with [the way your machine is configured](https://askubuntu.com/questions/49040/apt-could-not-find-a-distribution-template-error).

To troubleshoot this try `apt-get install` some package and see if fails. If it fails, the problem is with your config and not with the Docker docs, in which case you can try to use the article above to fix your problem.

**Comment by measwel** [comment]
It worked after I did a apt-get upgrade. Must have been some old module. Thanks Joao!

**Comment by joaofnfernandes** [comment]
Glad I was able to help 🙌

**Comment by tulik** [comment]
If someone has issues with installation on Ubuntu I created _copy/paste_ cheat-sheet [link](https://tulik.github.io/devops-docker/2018/01/10/installing-docker-on-ubuntu-5-steps/)
