### ISSUE TITLE
Introduce each Dockerfile keyword with a one-line of what it's for first.

### ISSUE THREAD

**Issue by mmpfeffer** [docker/docker.github.io#6192]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @gbarr01 

May I suggest that for each key word described in the dockerfile reference, the first sentence should answer the question "what is this for/what does this do?" before describing syntax, options and issues surrounding the feature.

For example, the current doc for Dockerfile COPY first describes the syntax and details, and only many points later the purpose. Here is what it currently says:

```
COPY
COPY has two forms:

COPY [--chown=<user>:<group>] <src>... <dest>
COPY [--chown=<user>:<group>] ["<src>",... "<dest>"] (this form is required for paths containing whitespace)
Note: The --chown feature is only supported on Dockerfiles used to build Linux containers, and will not work on Windows containers. Since user and group ownership concepts do not translate between Linux and Windows, the use of /etc/passwd and /etc/group for translating user and group names to IDs restricts this feature to only be viable for for Linux OS-based containers.
```
And only after reading all of this, do I find out what COPY is for, with the following text:
```
The COPY instruction copies new files or directories from <src> and adds them to the
filesystem of the container at the path <dest>.
```

While this provides all the information, it is possible to make it even more straightforward.  I would suggest to start the entire section with something like this:

```
The COPY instruction copies files from the host file system into the container at build time.
```

This statement is sufficient, clear, and guides the reader immediately to understand:
a) whether to read
b) what to expect.

I think this principle could be applied elsewhere in the documentation, but as I am learning Dockerfile at the moment, I noticed this here.

--Moshe Pfeffer

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
