### ISSUE TITLE
Documentation directs users to support channel that isn't public

### ISSUE THREAD

**Issue by joelbernstein** [docker/docker.github.io#6198]
File: [registry/help.md](https://docs.docker.com/registry/help/), CC @joaofnfernandes 
"If you need help, or just want to chat, you can reach us:
[...]
on the Docker community Slack."

However, it is only possible to signup for the dockercommunity slack if one has a @docker.com email address. So this support is not actually open at all except to Docker employees. Perhaps this is a Slack misconfiguration, I can't speculate.

**Comment by joaofnfernandes** [comment]
@joelbernstein [Check this blog post](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/#h.vvhcau5wal5v) with instructions on how to get invited to the community Slack.

I'm leaving this issue open because we can clarify the sign-up process in the docs.

**Comment by thaJeztah** [comment]
I think the link for registration is http://dockr.ly/community (which redirects to the correct registration form)

**Comment by joelbernstein** [comment]
Ah! Thanks. That was -really- not obvious. Please do update the docs!

**Comment by joelbernstein** [comment]
Actually, no - even after following the registration process there I end up in a webapp that is definitely not Slack. And the login details I entered during that reg process don't let me into the Dockercommunity Slack.

They *do* let me into https://community.docker.com/main/groups/4316/lounge but that's of dubious use since there seem to be no public discussion threads and I have no idea who to personally message. I actually want to log a different bug re Docker Cloud autobuilds, and I thought that Slack would be the place to initially ask about it. Perhaps not.

Not that it's related to this ticket, but I'm having trouble with Docker Cloud (paid account, private repos) autobuilds with the "build on your own nodes" option. My nodes are on Google Cloud (i.e. not a cloud provider docker cloud manages directly) and have been connected with the Docker Cloud "bring your own node" feature by running the dockercloud-agent on them.

When I enable building on my own nodes, I expect that Docker cloud builds triggered by github events will now build on the servers I've connected in that manner, instead of on the Docker Cloud shared build environment. However, what I actually get is nothing building at all (no build attempts logged) until I switch back to the "build on Docker's servers" option. Additionally, the node(s) I bring into Docker Cloud control in this way end up being added to my Docker Swarm and having containers deployed onto them. This seems entirely counterintuitive. It is not clear whether it would behave differently if I used a cloud provider like Azure which Docker Cloud can provision arbitrary nodes on, however this is not mentioned in the documentation and it's certainly against my expectation for what a "build on your hardware" feature should do. Is there in fact no way to build on my own arbitrarily-specified nodes via Docker Cloud?

[apologies, I know this doesn't belong here except inasmuch as it is also a documentation issue - if you could direct me to the correct place to log the bug it would be very helpful]

**Comment by thaJeztah** [comment]
> Actually, no - even after following the registration process there I end up in a webapp that is definitely not Slack

Ah, yes (it's been a while since I went through that process), there's indeed a community portal there, but after registering there, you should also get an invite per e-mail to join the community slack channel. I _think_ that invite is automated nowadays, but give it a day, and check your spam box as well (just to be sure)

**Comment by thaJeztah** [comment]
For the docker cloud thing; if you have a paid account, I guess the best way forward is to open a ticket through support@docker.com (I don't have insight into the Docker Cloud stack 😅)

**Comment by joelbernstein** [comment]
(turns out i got a slack invite in a separate email...)

I'd still love to know how/where to file the bug described above, though, please. I don't think it's a documentation bug _unless the feature actually isn't supported at all_.

**Comment by joaofnfernandes** [comment]
If you're a paying user, you can open a support case at https://support.docker.com

**Comment by joelbernstein** [comment]
That's really not correct. I'm a paying user of Docker Cloud but can't get any support there.

It would be more correct to say that Docker Enterprise Edition users, which seems to cost 1000s, can open support cases there. Docker Cloud customers don't seem to get any support even when the promised service doesn't work properly.

**Comment by joelbernstein** [comment]
I will try submitting it via email to support@docker.com, thanks.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
