### ISSUE TITLE
To doc: Add support for multiple composefile when deploying

### ISSUE THREAD

**Issue by gbarr01** [docker/docker.github.io#6200]
References:
https://github.com/docker/docker-ce/blob/v18.03.0-ce-rc3/CHANGELOG.md
https://github.com/docker/cli/pull/569

Possible doc location:
https://docs.docker.com/compose/extends/#understanding-multiple-compose-files
https://docs.docker.com/compose/production/

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
