### ISSUE TITLE
To doc: Disallow attaching ingress network

### ISSUE THREAD

**Issue by gbarr01** [docker/docker.github.io#6202]
References: 
https://github.com/docker/docker-ce/blob/v18.03.0-ce-rc3/CHANGELOG.md
https://github.com/docker/swarmkit/pull/2523

Possible doc location:
https://docs.docker.com/network/overlay/#operations-for-standalone-containers-on-overlay-networks

**Comment by gbarr01** [comment]
@thaJeztah ... I was thinking that this needed a note for folks who actually attempted to attach an ingress network, but now I'm having 2nd thoughts per your comment that it's just a bug fix. Shall I close?

**Comment by thaJeztah** [comment]
IIUC, it's a bug fix, but it wouldn't hurt to mention somewhere that the ingress network should not be manually attached to

**Comment by gbarr01** [comment]
Actually, @thaJeztah , I see now that it's just a bug fix so if you don't mind I won't document this one. If you feel strongly about it, feel free to reopen.
