### ISSUE TITLE
product request for creating repos in docker hub - allow admins for that repo

### ISSUE THREAD

**Issue by jonathanong** [docker/docker.github.io#621]
sorry, this is the only button i found in [docker-hub/repos.md](https://docs.docker.com/docker-hub/repos/) for making any sort of request. contact us page seemed like an enterprise question form.

it requires you to be an owner of a GitHub org for you to create a repo from that org. it would be nice if you allowed admins for repos (via GitHub's newer team management system).

thanks. feel free to close this and triage this however you'd like.

**Comment by jonathanong** [comment]
nvm i read this wrong. it thought i had to be an owner of the GitHub org. nvm!

**Comment by sanscontext** [comment]
Hi Jonathan, 
Ha, and I was in the middle of writing a long response. ;)  Glad you figured it out!  For next time, here's the link to the [Support Portal](https://support.docker.com), and feel free to ask questions on [the Docker Forums](https://forums.docker.com/). (Both use your Docker ID for login.)
