### ISSUE TITLE
404 at /engine/userguide/networking/default_network/configure-dns/

### ISSUE THREAD

**Issue by balamurugan105** [docker/docker.github.io#6211]
URL: /engine/userguide/networking/default_network/configure-dns/

**Comment by gbarr01** [comment]
@balamurugan105 , I believe that this page has been baked into this one: https://docs.docker.com/network/bridge/

**Comment by gbarr01** [comment]
Actually, this seems better: https://docs.docker.com/config/containers/container-networking/

**Comment by gbarr01** [comment]
This should work shortly: https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/
