### ISSUE TITLE
Document differences in CLI behavior when using client bundle vs not

### ISSUE THREAD

**Issue by johnharris85** [docker/docker.github.io#6214]
### Problem description

We should document somewhere the different behavior in `docker` cli commands when using the client bundle vs not. Couple of examples:

- When using the bundle, `docker ps` will omit _running_ containers, if they're designated as 'system containers'
- When using the bundle, `docker node ls` shows health of the `ucp agent` container, whereas against a regular daemon shows the health of the swarm node itself.

### Problem location

Not sure if this lives in the docs for CLI reference or EE bundle (https://docs.docker.com/datacenter/ucp/2.2/guides/user/access-ucp/cli-based-access/#download-client-certificates).

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
