### ISSUE TITLE
Missing or incorrect docs info

### ISSUE THREAD

**Issue by magick93** [docker/docker.github.io#6220]
File: [storage/storagedriver/device-mapper-driver.md](https://docs.docker.com/storage/storagedriver/device-mapper-driver/), CC @gbarr01

> A community-contributed script called device_tool.go is available in the contrib/ directory of the Docker Github repository. 

This appears to not exist.

if it does, please link directly to this.

**Comment by gbarr01** [comment]
Hi, @magick93 , it's here: https://github.com/moby/moby/tree/master/contrib/docker-device-tool

**Comment by gbarr01** [comment]
It should now say, "moby/moby" Github repository, not "Docker Github repository"
