### ISSUE TITLE
Restart policies differs

### ISSUE THREAD

**Issue by dkurzaj** [docker/docker.github.io#6230]
Hello,

I've found that the **--restart** option can take different values from where you read it in the documentation :

File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/), CC @gbarr01 

File: [config/containers/start-containers-automatically.md](https://docs.docker.com/config/containers/start-containers-automatically/), CC @gbarr01 

Or maybe are those pages talking about different things.

Thank you !

Dorian

**Comment by gbarr01** [comment]
Thanks, @dkurzaj .   

@joaofnfernandes, 

This docs page: https://docs.docker.com/engine/reference/commandline/run/#restart-policies---restart

is generated from this cli page: https://github.com/docker/cli/blob/c19b272c09274c18e2a1eeafe4b495d3fecd837f/docs/reference/commandline/run.md#restart-policies---restart

The docs page does not match and I'm trying to figure out why. I just committed a tiny change by adding two newlines ...  if this doesn't work, perhaps you can help me debug.

**Comment by thaJeztah** [comment]
This looks to already have been fixed through https://github.com/docker/cli/pull/909; that fix is included in the upcoming 18.03 release https://github.com/docker/docker-ce/commit/767a8f62271a7a65b635a98e339a773bb01fd881

**Comment by gbarr01** [comment]
This was fixed in:  https://github.com/docker/docker.github.io/pull/6234
