### ISSUE TITLE
docs dont say what to do when File Sharing widget does not allow changing bound shares

### ISSUE THREAD

**Issue by djangofan** [docker/docker.github.io#6237]
File: [docker-for-mac/osxfs.md](https://docs.docker.com/docker-for-mac/osxfs/), CC @gbarr01 

docs dont say what to do when File Sharing widget does not allow changing bound shares

**Comment by joaofnfernandes** [comment]
@djangofan can you be a bit more specific? What's your use case?
Are you trying to remove a default one, adding a new one, or something else?
