### ISSUE TITLE
Clarification: change "sign" to "sign-off" or similar

### ISSUE THREAD

**Issue by dakotahawkins** [docker/docker.github.io#6238]
File: [opensource/code.md](https://docs.docker.com/opensource/code/), CC @johndmulhausen 

I was familiar with git's gpg signing capability (`-S`) but not with signing off on commits (`-s`).

It would have saved me a lot of time to realise I didn't need to set up gpg to follow the rules! :)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
