### ISSUE TITLE
The `--with-registry-auth` disclaimer needs to specify private "repository" rather than "registry"

### ISSUE THREAD

**Issue by sudo-bmitch** [docker/docker.github.io#6239]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @gbarr01 

From [this SO post](https://stackoverflow.com/a/49308437/596285), users are confused at the need to include `--with-registry-auth` when accessing a private repository on the public Docker Hub registry server. The wording on when that option is needed should be updated to specify it applies to private repositories where a login is needed to pull images. It would also help to indicate the "No such image" error message means they have either entered the incorrect image name, or that their image is in a private repository and they need to perform the quoted procedure.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
