### ISSUE TITLE
DDC Create and manage teams. com.docker.ucp.access.label do not apply to all resources

### ISSUE THREAD

**Issue by leenamba** [docker/docker.github.io#624]
### Problem description

DDC Create and manage teams. com.docker.ucp.access.label do not apply to all resources. Nodes and applications do not apply.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/datacenter/ucp/2.0/guides/user-management/create-and-manage-teams/

### Project version(s) affected

UCP 2.0

### Suggestions for a fix

Replace "resources" with "certain resources" or "resources listed below" and then should match permissions here I think:
https://docs.docker.com/datacenter/ucp/2.0/guides/user-management/permission-levels/

**Comment by clemenko** [comment]
fixed with #1772
