### ISSUE TITLE
Linux user namespacing documentation, bad link

### ISSUE THREAD

**Issue by nmschulte** [docker/docker.github.io#6244]
File: [engine/security/userns-remap.md](https://docs.docker.com/engine/security/userns-remap/), CC @gbarr01 

`s/user-namespace-known-restrictions/user-namespace-known-limitations/` here:
https://github.com/docker/docker.github.io/blame/master/engine/security/userns-remap.md#L128

----

Also, the second sentence in this paragraph doesn't quite make sense:
https://github.com/docker/docker.github.io/blame/master/engine/security/userns-remap.md#L259
> User namespaces are an advanced feature and require coordination with other
capabilities. For example, if volumes are mounted from the host, **file ownership
must be pre-arranged need read or write access** to the volume contents.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by nmschulte** [comment]
@L-Hudson I cannot re-open the issue.  The issue still exists.
