### ISSUE TITLE
docs.docker.com pages are missing "edit" and "file an issue" links.

### ISSUE THREAD

**Issue by cowlinator** [docker/docker.github.io#6247]
### Problem description

The readme for this documentation repo states "We really want your feedback, and we've made it easy. You can edit, rate, or file an issue at the bottom of every page on https://docs.docker.com/."  However, all pages I looked at only had the ability to rate, not edit nor file an issue.  (See attachment)

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/builder/#dockerfile-examples

### Project version(s) affected

Docker version 17.12 docs.  

### Suggestions for a fix

Either add the Edit and File An Issue buttons to the doc pages (preferred), or remove the statement from the readme.  

### Attachments

![doc](https://user-images.githubusercontent.com/4963190/37539744-cab1f91a-2911-11e8-9f5e-f3429a54bd4f.png)

**Comment by joaofnfernandes** [comment]
That README file is probably a bit outdated. You can edit and file issues, but that functionality is now at the top-right.

If you're up for it, you can submit a pull request to help fix that README file 🙌

![2018-03-16_14-41-48](https://user-images.githubusercontent.com/1525937/37546047-5ce0bc7a-2928-11e8-8836-f5a8bc5cea04.png)
