### ISSUE TITLE
"docker build" omits that you need to repeat "--build-arg" for each arg.

### ISSUE THREAD

**Issue by cowlinator** [docker/docker.github.io#6248]
### Problem description

The documentation about --build-arg gives the description "Set build-time variable**s**", but fails to mention that you must add --build-arg for each build argument.

This confusion is further compounded by the fact that "docker build --help" prints "--build-arg list" (on windows).  See also https://stackoverflow.com/questions/42297387/docker-build-with-build-arg-with-multiple-arguments

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

### Project version(s) affected

Ver. 17.12 documentation

### Suggestions for a fix

Explicitly state that you must add --build-arg for each build argument.  
Also, possibly change "Set build-time variable**s**" to "Set build-time variable"

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
