### ISSUE TITLE
Dockerfile ENV and ARG have neither explanation nor example of variable usage on Windows

### ISSUE THREAD

**Issue by cowlinator** [docker/docker.github.io#6249]
### Problem description

Dockerfile `ENV` and `ARG` give no indication of how to use variables on Windows.  Specifically, the `$var` format must be used for Dockerfile commands, but the `%var%` or `$env:var` format must be used with `RUN`.

It's easy to assume that `RUN` behaves exactly like all other Dockerfile commands: Docker itself performs the substitution.  But in reality, `RUN` passes the variables unchanged directly to the shell.

There is no explanation of this concept, nor any usage examples for Windows.

See also:
https://github.com/moby/moby/issues/18492#issuecomment-162869083
https://forums.docker.com/t/windows-container-build-arguments/29065
https://forums.docker.com/t/unable-to-consume-arg-or-env-variables-in-run-commands/25467

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/builder/#arg
- I saw a problem on the following URL: https://docs.docker.com/engine/reference/builder/#env

### Project version(s) affected

Ver. 17.12 documentation

### Suggestions for a fix

In both the `ENV` and the `ARG` sections, explain that with `RUN`, variables are passed unchanged directly to the shell.
In both the `ENV` and the `ARG` sections, give an example of using variables with `RUN` on both Linux and Windows.
In both the `ENV` and the `ARG` sections, give an example of using variables with a non-RUN command, and explain that the `$var` format is universal with non-RUN commands.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by cowlinator** [comment]
@L-Hudson , what impending refactor?  Can you please link to the relevant PR, issue, or some other source of information?
