### ISSUE TITLE
Missing template for CE 17.09 in Docker for AWS template archive

### ISSUE THREAD

**Issue by vce-xx** [docker/docker.github.io#6251]
The Docker for AWS template archive page is missing the template for CE (Stable) 17.09.
File: [docker-for-aws/archive.md](https://docs.docker.com/docker-for-aws/archive/), CC @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
