### ISSUE TITLE
No guidance for exporting / importing docker volumes

### ISSUE THREAD

**Issue by MFAshby** [docker/docker.github.io#6252]
File: [storage/volumes.md](https://docs.docker.com/storage/volumes/), CC @gbarr01

There is no guidance on this page for exporting and importing docker volumes. 

The 'docker export' command reference contains a link to a non-existent section on this page 'https://docs.docker.com/engine/tutorials/dockervolumes/#backup-restore-or-migrate-data-volumes', implying there used to be some documentation for this and it has been removed. 

Moving a volume from one container host to another seems like it should be a straightforward task, as it is for containers with 'docker export' and 'docker import'.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by MFAshby** [comment]
I'd like to re-open - there's still no documentation on how to export a volume from one machine and import it onto another.

**Comment by MFAshby** [comment]
Reopened in https://github.com/docker/docker.github.io/issues/7963
