### ISSUE TITLE
404 at /engine/installation/linux/docker-ee/suse/

### ISSUE THREAD

**Issue by bhavin192** [docker/docker.github.io#6257]
URL: `/engine/installation/linux/docker-ee/suse/`
https://docs.docker.com/engine/installation/linux/docker-ee/suse/
This url is not getting redirected to `/install/linux/docker-ee/suse`

Probably because of a typo in word `installation`?
https://github.com/docker/docker.github.io/pull/5651/files#diff-8e7b805a1fd465c206721f9e2d8779f2R7

**Comment by gbarr01** [comment]
Fixed by #6261
