### ISSUE TITLE
Add banner for DockerCon

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#6262]
Use this for inspiration
![screen shot 2018-03-19 at 1 31 52 pm](https://user-images.githubusercontent.com/1525937/37625266-7c388352-2b88-11e8-8675-eda5271bf0c8.png)

![](https://user-images.githubusercontent.com/107040/37482437-5f010538-2841-11e8-8555-2e7a889b5868.png)

The assets are here
[DockerConBannerAssets.zip](https://github.com/docker/docker.github.io/files/1827159/DockerConBannerAssets.zip)

Clicking on the image should direct you to  https://2018.dockercon.com

**Comment by FSHA** [comment]
@vcoisne for visibility
