### ISSUE TITLE
docker run documentation does not mention the --ulimit option

### ISSUE THREAD

**Issue by justincormack** [docker/docker.github.io#6263]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/), CC @gbarr01 

Somehow we seem to have omitted the docs for this.

**Comment by gbarr01** [comment]
Thanks, @justincormack . This is a known issue and we are working on it.

**Comment by gbarr01** [comment]
@justincormack , you should see it now: 
https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit
