### ISSUE TITLE
Feedback for: docker-for-windows/troubleshoot.md

### ISSUE THREAD

**Issue by lusitania** [docker/docker.github.io#63]
URL: docker-for-windows/troubleshoot.md
There appears to be no documentation on how to lower StartupBytes for MobyLinuxVM below 1024MB. I've altered mine by calling
```
Set-VMMemory mobylinuxvm -StartupBytes 64MB -DynamicMemoryEnabled $true -MinimumBytes 64MB -MaximumBytes 512MB
```
but these changes are reverted once I start "docker for windows.exe". I can't find the location where docker for windows stores these settings to adjust them accordingly.

edit: I've figured out that VmMemory in %appdata%\Docker\settings.json configures StartupBytes. This should be documented.

**Comment by johndmulhausen** [comment]
@lusitania -- Just FYI, you can hit "Edit This Page" and suggest the documentation changes that you've figured out. It's a lot more likely to get fixed quickly that way. :)

**Comment by londoncalling** [comment]
@friism @jeanlaurent @rneugeba 
Can you look at @lusitania 's comments, and let me know how you want me to address this in the docs? I can certainly add the bit about how to set `StartupBytes` per his discovery, but we aren't documenting anything else in that `json` file. How should we address this? 

Here are all the options with default values in that file. Don't we want to provide any needing settings via the UI? 

```{"VmCpus":2,
"VmMemory":2048,
"SubnetAddress":"10.0.75.0",
"SubnetMaskSize":24,
"UseDnsForwarder":true,
"NameServer":"8.8.8.8",
"IsTracking":true,
"SharedDrives":{},
"DaemonOptions":"{\"registry-mirrors\":[],\"insecure-registries\":[]}",
"SysCtlConf":"",
"ExecutableDate":"10/01/201602:05:18",
"AutoUpdateEnabled":true,
"StartAtLogin":true,"ProxyExclude":"",
"ProxyHttp":"",
"ProxyHttps":"",
"UseHttpProxy":false}
```

**Comment by friism** [comment]
@londoncalling no, I don't think we should document this, editing that file is not a public interface that users can rely on

**Comment by londoncalling** [comment]
@friism , makes sense

@lusitania until or if we expose a setting for `StartupBytes` on the UI, we can't really document this per @friism 's comment. Other avenues for feedback on the product (vs. just a docs request) are [Docker for Windows forums ](https://forums.docker.com/c/docker-for-windows)  and [Docker for Windows issues on GitHub](https://github.com/docker/for-win/issues).

Closing this request for now.

**Comment by lusitania** [comment]
I also agree that editing settings.json is more of a hack and should not be relied on. If I can come up with a not too specific, yet sufficient wording I'll create the according pull request. Thanks
