### ISSUE TITLE
Remove mention of hub/cloud scanning

### ISSUE THREAD

**Issue by manishtomar** [docker/docker.github.io#6312]
File: [docker-store/publish.md](https://docs.docker.com/docker-store/publish/), CC @gbarr01

In https://docs.docker.com/docker-store/publish/#scan-your-own-private-repositories the following statement "consider using Docker Security Scanning on your own private Docker repositories in Docker Cloud and Docker Hub" is incorrect as we've deprecated scanning for private repositories. However, we do provide scanning for images staged to be published. So I am not sure what is the right wording here.

**Comment by joaofnfernandes** [comment]
@manishtomar can you take the lead on this one and submit a PR with a proposal?
If you get the ball rolling, we can assist with a review, but if we take the lead it might take a while for this to see the light of day 😭

**Comment by manishtomar** [comment]
@KickingTheTV What is the best wording for this situation?
