### ISSUE TITLE
Example file throws a 404

### ISSUE THREAD

**Issue by mikecasas** [docker/docker.github.io#6317]
File: [engine/examples/postgresql_service.md](https://docs.docker.com/engine/examples/postgresql_service/), CC @gbarr01

The url in the example throws a 404.

``` example Dockerfile for https://docs.docker.com/examples/postgresql_service/ ```

Maybe the link should be 
``` https://docs.docker.com/engine/examples/postgresql_service/ ```

**Comment by gbarr01** [comment]
Hi, @mikecasas, do you have time to make the change and file a pull request? Click edit at the top right of the page.

**Comment by gbarr01** [comment]
Hi, @mikecasas , I fixed it (though, in truth, it should probably be removed ... looks like it was copied from raw content somewhere else). Anyway .. thanks for filing.
