### ISSUE TITLE
Please describe that ppc64 is big endian

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#6322]
File: [install/linux/docker-ee/rhel.md](https://docs.docker.com/install/linux/docker-ee/rhel/), CC @gbarr01 

There seems to be some confusion for people installing EE on Power thinking ppc64 is what we support. Could we be more explicit and add the following the the note about ppc64le?

```
If you run `uname -a` and see the results of the command include `ppc64` 
instead of `ppc64le` this means you are running RHEL in big endian mode. 
```

**Comment by justincormack** [comment]
the title of this issue should read "Please describe that ppc64 is little endian"!!!

**Comment by gbarr01** [comment]
Hi, @yongshin , I can add it, but we do say: 

> To install Docker EE, you need ... ppc64le (IBM Power) architectures.

**Comment by yongshin** [comment]
I know this might be tricky to accommodate in that page, but really people think they can install on pp64, we just need to be explicit and say that if you see 'ppc64' that is RHEL in big endian mode and we don't support it. Otherwise they will still try to install even though they see it on works on 'ppc64le'.

**Comment by gbarr01** [comment]
Fixed by https://github.com/docker/docker.github.io/pull/6363
