### ISSUE TITLE
Mount points -> Mount point volumes

### ISSUE THREAD

**Issue by cowlinator** [docker/docker.github.io#6325]
File: [storage/index.md](https://docs.docker.com/storage/), CC @gbarr01

Volumes have been a source of confusion for me, and this page wasn't particularly helpful.

It seems that `mount points` are often referred to as volumes, as in `docker run --volume` and Dockerfile's `VOLUME`.

I feel like the mounts should be called `managed volumes`, `mount point volumes`, and `tmpfs volumes`.
Thoughts?

**Comment by cowlinator** [comment]
Hmm, I now see where `docker run --mount type=` values are `volume`, `mount`, `tmpfs`.  Anyway, it seems that even the cli need consistency in terminology.  It doesn't make sense to use `docker run --volume` with something if it isn't considered a volume. :(

**Comment by gbarr01** [comment]
@thaJeztah,  when you get a chance, thoughts?
