### ISSUE TITLE
Improvements needed on cloud.docker.com sign up form

### ISSUE THREAD

**Issue by SharakPL** [docker/docker.github.io#6339]
I'm trying to create my docker account but it's rather problematic. Sign up form keeps telling me on `Choose your Docker ID` field that my ID is invalid. Only doesn't say anything about why is it invalid. Is it already taken or does it need more characteres or maybe different types of characters? Nothing. Would be helpful if it was more specific on that.

Happened on Chrome v.65 on Windows 10 64.
The same values on Firefox got sent without problems.

**Comment by gbarr01** [comment]
Hi, @SharakPL , can you please contact support@docker.com with the Docker ID you are attempting to create?  Sorry for the inconvenience.

**Comment by SharakPL** [comment]
I've already created it with Firefox. Don't know why Chrome was causing problems there.
Nevertheless form validation should be better.

**Comment by gbarr01** [comment]
I've passed the word to support. Thanks for reaching out.
