### ISSUE TITLE
404 at /engine/installation/linux/repo_files/centos/docker.repo

### ISSUE THREAD

**Issue by aminep7** [docker/docker.github.io#6355]
URL: /engine/installation/linux/repo_files/centos/docker.repo

**Comment by aminep7** [comment]
failed to download docker-repo

**Comment by joaofnfernandes** [comment]
I can't find any mention of this url in the docs. Can you point me to the place that has this link?

**Comment by L-Hudson** [comment]
more than 6 months old; closing ticket
