### ISSUE TITLE
Confusing on Layer ID, Feedback for: engine/userguide/storagedriver/imagesandcontainers.md

### ISSUE THREAD

**Issue by twang2218** [docker/docker.github.io#636]
File: [engine/userguide/storagedriver/imagesandcontainers.md](https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/)

## Why is not possible to store the layer ID in the overall config file?

In the paragraph:

```markdown
Note: Under the content addressable storage model introduced with Docker 1.10, 
image history data is no longer stored in a config file with each image layer. It is 
now stored as a string of text in a single config file that relates to the overall image. 
This can result in some image layers showing as “missing” in the output of the 
docker history command. This is normal behaviour and can be ignored.

You may hear images like these referred to as flat images.
```

It's not clearly explained why "some image layers showing as 'missing'". Whether storing the config file in each layer or in the overall image shouldn't affect the result of missing layer ID directly, in another words, I cannot see the reason why we can't store the layer ID in the overall image config file.

I think there should be more info about the *flat image* and why is not possible to store such layer ID in the overall config.

## Layer directories name are not Layer ID since 1.10, so where it came from?

Below the section:

```bash
$ docker pull ubuntu:15.04
15.04: Pulling from library/ubuntu
1ba8ac955b97: Pull complete
f157c4e5ede7: Pull complete
0b7e98f84c4c: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:5e279a9df07990286cce22e1b0f5b0490629ca6d187698746ae5e28e604a640e
Status: Downloaded newer image for ubuntu:15.04

$ ls /var/lib/docker/aufs/layers/
1d6674ff835b10f76e354806e16b950f91a191d3b471236609ab13a930275e24
5dbb0cbe0148cf447b9464a358c1587be586058d9a4c9ce079320265e2bb94e7
bef7199f2ed8e86fa4ada1309cfad3089e0542fec8894690529e4c04a7ca2d73
ebf814eccfe98f2704660ca1d844e4348db3b5ccc637eb905d4818fbfb00a06a
```

there is an statement:

```
See how the four directories do not match up with the image layer IDs pulled in the previous step.
```

Yes, they do not match anymore, however, then where the directory name come from?

When I dig more to understand, I found it's more confusing.

Let's take `swarm:latest` image as example, when I pull the image, I got:

```bash
$ docker pull swarm
Using default tag: latest
latest: Pulling from library/swarm
220609e0bc51: Pull complete
b54bf338fe2f: Pull complete
d53aac5750d5: Pull complete
Digest: sha256:c9e1b4d4e399946c0542accf30f9a73500d6b0b075e152ed1c792214d3509d70
Status: Downloaded newer image for swarm:latest
```

I thought `220609e0bc51`, `b54bf338fe2f` are *Layer IDs*, however, `docker inspect` tell me the other way:

```bash
$ docker inspect swarm
...
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:249a306ce89e40e513e6d30a49f4624fab8322a08df9dbb543098aecedd4f480",
                "sha256:2fe4d825a161e1d03b9b32a1aabdbb403ecd214939f404aeeccc3887900a1be3",
                "sha256:c54d433c22fee8e25917bf419bf3804548d84f06efa56a8586f7772867319628"
            ]
        }
```

They do not match up, then I think, as described in the article, "directories do not match up with the image layer IDs", so the directories name may be match one of them, then it will tell me where the directories name came from. However, it's another set of IDs:

```bash
$ tree
...
├── layers
│   ├── 0713d9169b66ea56296f0dac3003fbe2f5c792f60c232ffd120286d77c298b4e
│   ├── 57c4c4fa1934498f8a8c766b2c1b3841c0fd4e9990221c609cfebb380cac9b39
│   └── 9de5c8c1c6e3baed3b72a9559b1ad9a131c4b099cb8e6743a9107d52e19b6fdd
...
13 directories, 5 files
```

And the `docker history` is not helping:

```bash
$ docker history swarm
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
942fd5fd357e        3 months ago        /bin/sh -c #(nop) CMD ["--help"]                0 B
<missing>           3 months ago        /bin/sh -c #(nop) ENTRYPOINT &{["/swarm"]}      0 B
<missing>           3 months ago        /bin/sh -c #(nop) VOLUME [/.swarm]              0 B
<missing>           3 months ago        /bin/sh -c #(nop) EXPOSE 2375/tcp               0 B
<missing>           3 months ago        /bin/sh -c #(nop) ENV SWARM_HOST=:2375          0 B
<missing>           3 months ago        /bin/sh -c #(nop) COPY dir:d556676b4fb31ddaa2   0 B
<missing>           3 months ago        /bin/sh -c #(nop) COPY file:4ac98efa752a9c4de   277.2 kB
<missing>           3 months ago        /bin/sh -c #(nop) COPY file:25d95a7c5d1ad440c   19.19 MB
```

Most of the ID are missing, the only one left didn't match up with any of the 3 sets IDs above, it's the Image ID actually.

Ok, Let's push to another registry,

```bash
$ docker push localhost:5000/swarm
The push refers to a repository [localhost:5000/swarm]
c54d433c22fe: Pushed
2fe4d825a161: Pushed
249a306ce89e: Pushed
latest: digest: sha256:078310063599ccef2f57b34a652d4cc77c1485fef07b446706ce280e22dadef8 size: 945
```

It's not matched up with the `docker pull`, it's matched up with the directories names. 

I'm lost here, we have 3 sets of IDs, at least, and `docker pull` using different sets of ID of `docker push`, actually, they all different somehow. So, I think we might need more explanation in the documentation on what are they, what is the intention to differentiate them, or maybe change the code to make them more consistent.

**Comment by mstanleyjones** [comment]
@thaJeztah can you point me to the right person to work with on this?

**Comment by thaJeztah** [comment]
let me /cc @tonistiigi and @aaronlehmann

**Comment by tonistiigi** [comment]
> Why is not possible to store the layer ID in the overall config file?

The issue is in "some image layers showing as “missing”". Correct would be "parent images showing as missing". "missing" means that there is no local image associated with this history chain.

> Yes, they do not match anymore, however, then where the directory name come from?

They are random, generated on pull.

> It's not matched up with the docker pull, it's matched up with the directories names.

IDs shown in pull are the checksums of compressed artifacts in the registry. We can't show the layer IDs because we can only determine them after data has been pulled. Same with push, to get the checksum for compressed artifact we first need to push it. There is a way to work around it for schema2 but the checksum wouldn't be secure until download has finished. If this is confusing, it would be simpler to just show "layer 1, layer 2, etc" as these IDs really don't have any meaning for user.
