### ISSUE TITLE
FAQ broken link

### ISSUE THREAD

**Issue by manishtomar** [docker/docker.github.io#6365]
File: [docker-for-mac/faqs.md](https://docs.docker.com/docker-for-mac/faqs/), CC @gbarr01 

https://docs.docker.com/docker-for-mac/faqs/#adding-tls-certificates link from https://docs.docker.com/docker-for-mac/faqs/#how-do-i-add-custom-ca-certificates is broken.

**Comment by gbarr01** [comment]
Hi, @manishtomar , the new page is: https://docs.docker.com/docker-for-mac/#add-tls-certificates
