### ISSUE TITLE
This says device mapper is the only supported storage driver for docker EE

### ISSUE THREAD

**Issue by okrangerb3** [docker/docker.github.io#6366]
File: [storage/storagedriver/device-mapper-driver.md](https://docs.docker.com/storage/storagedriver/device-mapper-driver/), CC @gbarr01

**Comment by joaofnfernandes** [comment]
Relates to #6152

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
