### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by charliemcelfresh** [docker/docker.github.io#6380]
File: [engine/admin/logging/view_container_logs.md](https://docs.docker.com/engine/admin/logging/view_container_logs/), CC @mistyhacks 

commmand’s is spelled wrong

**Comment by mistyhacks** [comment]
@gbarr01 I probably shouldn't be on the auto-CC list anymore...

@charliemcelfresh You can fix that typo by clicking "Edit this page". :)

**Comment by joaofnfernandes** [comment]
Sorry @mistyhacks, but once 🐳always 🐳
Your handle is not present in master but it's still referenced in the archive branches. So anyone reading an archive were you're mentioned will ping you.

**Comment by gbarr01** [comment]
Fixed by https://github.com/docker/docker.github.io/pull/6384
