### ISSUE TITLE
SLAT (Second Level Adress Translation) hardware feature not clearly defined as prerequisite for Docker for Windows

### ISSUE THREAD

**Issue by docbenton** [docker/docker.github.io#6381]
File: [docker-for-windows/troubleshoot.md](https://docs.docker.com/docker-for-windows/troubleshoot/), CC @gbarr01 

after installing Docker for Windows  ( Linux container chosen)
engine fails to start with famous popup : 
"An error occurred. Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled"

the aim of this current issue is to avoid the user fighting to enable hypervisor to avoid this popup at the end of install.

the pre-requisite for hypervisor to start mobylinux vm are
- cpu virtualisation feature, enabled in bios,   
- data execution protection
- SLAT cpu feature (called EPT by intel)
- windows 10 enterprise
..
but in paragraph VIRTUALIZATION MUST BE ENABLED,
SLAT/EPT is not stated in the referred page, and no tool is suggested to check for it...

for instance,  'systeminfo'  command output : 

Hyper-V Requirements:
                           VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: No
                           Data Execution Prevention Available: Yes
`

could easily be checked by installer...
and 'docker toolbox' could be suggested as workaround...
 that's what I did, but not immediately, only after several install attempts and finally discovering that my cpu was not SLAT compliant.

near virtualization,  i was also not able to find  a reference on SLAT/EPT on this page https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

**Comment by thaJeztah** [comment]
Ping @akimd

**Comment by docbenton** [comment]
sorry for silly question, but how to ping/send a msg ? using his email he may has left has a commiter ?

**Comment by akimd** [comment]
Actually by merely mentioning my GitHub ID (which the @ before), thaJeztah pinged me.  And his "ping akim" was the action itself, he was not suggesting "you should ping akim" :)

**Comment by plemon** [comment]
Doc File: [https://docs.docker.com/docker-for-windows/install/](url)

Docs should be improved a little regarding CPU requirements where it says 'CPU SLAT-capable feature'. Users can be helped greatly with a link to check if the target installation CPU meets SLAT capability or not. 

Please consider referencing this MS page so users can do an easy verification:
[https://docs.microsoft.com/en-us/sysinternals/downloads/coreinfo](url)
see the -v option

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
