### ISSUE TITLE
Comments on Interlock section

### ISSUE THREAD

**Issue by davidwilliamson** [docker/docker.github.io#6386]
File: [ee/ucp/interlock/deploy/production.md](https://docs.docker.com/ee/ucp/interlock/deploy/production/), CC @johndmulhausen 

From swarm's point of view, the label we choose is arbitrary. However, since interlock is an integral part of UCP, I think the label should follow UCP's labeling convention:

docker node update --label-add **nodetype=loadbalancer** <node> 

docker node inspect --format '{{ index .Spec.Labels "**nodetype**" }}' <node>

[Extensions]
  [Extensions.default]
    ProxyConstraints = ["node.labels.com.docker.ucp.orchestrator.swarm==true", "**node.labels.nodetype==loadbalancer**"]

Instead of **nodetype=loadbalancer**,  I would suggest using a label like: **node.labels.com.docker.ucp.routingmesh.loadbalancer=true**

Further, I would recommend coordinating with the UCP team to define the label, since in future UCP releases, the UCP team may want to create backend code that knows which nodes are behaving as Interlock proxies.

@joaofnfernandes

**Comment by joaofnfernandes** [comment]
Issue moved to [docker/docs-private #584](https://github.com/docker/docs-private/issues/584) via [**ZenHub**](https://www.zenhub.com/)
