### ISSUE TITLE
Suggest reordering and renaming deployment section names

### ISSUE THREAD

**Issue by davidwilliamson** [docker/docker.github.io#6387]
File: [ee/ucp/interlock/deploy/index.md](https://docs.docker.com/ee/ucp/interlock/deploy/), CC @johndmulhausen

The current ordering in the left panel does not follow a typical work flow for enabling and then configuring Interlock. 

Also, there are two topics mentioning 'deployment', implying that either topic by itself will result in deploying interlock, when the actual work flow is to perform the "simple Deployment" task, then (optionally) perform the "Production deployment" task.

IMO, the ordering in the left panel should mirror the actual deployment work flow, and titles be changed to better indicate that these topics represent a sequential work flow.

1. Enable feature (Required for all subsequent tasks)
2. Tweak to support a production environment (common task)
3. Supporting host mode networking (less common task)
4. Further topics for power users
5. Complete reference to all options

![screen shot 2018-04-06 at 8 51 55 am](https://user-images.githubusercontent.com/6767139/38431806-5b1e4a9e-397a-11e8-845c-6aa76315dd7e.png)

@joaofnfernandes

**Comment by joaofnfernandes** [comment]
Issue moved to [docker/docs-private #585](https://github.com/docker/docs-private/issues/585) via [**ZenHub**](https://www.zenhub.com/)
