### ISSUE TITLE
Typo in title

### ISSUE THREAD

**Issue by davidwilliamson** [docker/docker.github.io#6388]
File: [ee/ucp/interlock/deploy/index.md](https://docs.docker.com/ee/ucp/interlock/deploy/), CC @johndmulhausen

Title has a typo (missing 'l' in 'layer'

`Enable ayer 7 routing`

Should be
``` 
Enable layer 7 routing
       ^
```

Note: I tried to use the "Edit this page" functionality to submit the change myself, and got a 404. 
@joaofnfernandes

**Comment by joaofnfernandes** [comment]
Issue moved to [docker/docs-private #586](https://github.com/docker/docs-private/issues/586) via [**ZenHub**](https://www.zenhub.com/)
