### ISSUE TITLE
Mention about network aliases when using docker-compose run

### ISSUE THREAD

**Issue by holms** [docker/docker.github.io#6403]
### Problem description

When using `docker-compose run` and in `docker-compose.yml` file there are networks  specified for containers, they are just simply ignored. According to [this ticket](https://github.com/docker/compose/issues/4052) there's a need to add network aliases, this is not documented anywhere, I've spend almost whole day to find out what's happening here.

### Problem location

- I saw a problem on the following URL: https://github.com/docker/compose/issues/4052

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/compose/reference/run/

- Other:  also `--use-aliases` not documented at all I have no idea how to use it.

### Project version(s) affected

Docker compose 3

### Suggestions for a fix

Mention all cases when docker-compose-run doesn't do something by default. I've noticed that you have to specify --service-ports in order to enable port mapping, also --name if I want to dependencies to connect to this container hostname via it's default name. This information is absent in there, and I do imagine what people been going through to find out  how to solve these issues.

**Comment by holms** [comment]
@gugahoi i pulled my hairs whole day with this I remember, and it's still not documented properly :(

**Comment by joebowbeer** [comment]
Both `--use-aliases` and `--service-ports` are included in options list at https://docs.docker.com/compose/reference/run/

What doc is still missing?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
