### ISSUE TITLE
Overlay Networking Tutorial Docs

### ISSUE THREAD

**Issue by MitranLiviuMarian** [docker/docker.github.io#6407]
Hi,

The fourth tutorial from Overlay Networking Tutorial https://docs.docker.com/network/network-tutorial-overlay/3 it is about 2 standalone containers communicating in a bridge network type.
Shouldn’t be about one swarm service communicating with a standalone container through a overlay network?

Thank you,
Marian M.

File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/), CC @gbarr01

**Comment by joaofnfernandes** [comment]
Taking a cursory look at this, I would say that you're right. The section title is `Communicate between a container and a swarm service`, but it actually teaches you how to use overlay networks between two containers.

I think you can use the info in the article to figure this out, but to get you going,  the trick to make a service and a container talk it to create the overlay network with:
```
docker network create --driver=overlay --attachable test-net
```

That way, both services and containers can attach to it.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
