### ISSUE TITLE
The `cache_from` option is missing from the Docker Compose file version 2.x documentation

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/docker.github.io#6408]
### Problem description

The Docker Compose `cache_from` option was introduced into Compose version [1.12](https://github.com/docker/compose/blob/master/CHANGELOG.md#1120-2017-04-04) or [1.17](https://github.com/docker/compose/blob/master/CHANGELOG.md#1170-2017-11-02), depending on which release note is correct. While it's only listed in the Compose 3.x documentation, I see `cache_from` in search results in the [2.x schemas](https://hangouts.google.com/hangouts/_/vaeit.com/scrub?authuser=0). 

I don't see any mentions of this option on the [documentation site](https://docs.docker.com/compose/compose-file/compose-file-v2/), though!

Related: https://github.com/docker/compose/issues/5860

### Problem location

https://docs.docker.com/compose/compose-file/compose-file-v2/

### Project version(s) affected

Docker Compose 1.12+

### Suggestions for a fix

I don't know how your documentation is generated or if it's hand-written, but it seems like a small oversight and can probably just be copied/pasted from the 3.x documentation (if it works the same... I suspect so).

**Comment by gbarr01** [comment]
Hi, @shin- , I saw your recommendation to update the docs ... but I wonder ... 

Yes, `cache_from` was introduced in **Docker Compose 1.12** ... but it was added to **Docker Compose _file reference_ 3.2** which was released with 1.12. Then in  Docker  Compose 1.17, that shipped with file reference 3.4, `cache_from` got added support. 

https://docs.docker.com/release-notes/docker-compose/#1120-2017-04-04

> Added support for cache_from in the build section of services

https://docs.docker.com/release-notes/docker-compose/#1170-2017-11-01

> Added support for cache_from, network and target options in build configurations

So the docs seem correct: 
https://docs.docker.com/compose/compose-file/#cache_from

Or am I missing something here?

**Comment by gbarr01** [comment]
Got it. Thanks, @AnthonyMastrean
