### ISSUE TITLE
Emphasize that Docker Swarm cannot be used solely with windows nodes and manager

### ISSUE THREAD

**Issue by ghayes7** [docker/docker.github.io#6409]
File: [engine/swarm/swarm-tutorial/index.md](https://docs.docker.com/engine/swarm/swarm-tutorial/), CC @gbarr01 
The line: "Currently, you cannot use Docker for Mac or Docker for Windows alone to test a multi-node swarm." Should be really emphasized, maybe reiterated at the very top of the page.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
