### ISSUE TITLE
The examples on this page do not work. 

### ISSUE THREAD

**Issue by geoidesic** [docker/docker.github.io#6412]
File: [develop/develop-images/multistage-build.md](https://docs.docker.com/develop/develop-images/multistage-build/), CC @gbarr01

Also it would be handy if the example from the previous page was continued, rather than starting a completely new example. This because some of the relationships between the commands are not obvious and are not explained. Like for example: 1) how does one know what the WORKDIR should be? 2) How does one know which folder should be copied with the `copy --from=0` 3) Also how does one debug a docker build that won't launch, or which launches and then exits immediately?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
