### ISSUE TITLE
Feedback for: compose/compose-file.md

### ISSUE THREAD

**Issue by alex-dr** [docker/docker.github.io#642]
File: [compose/compose-file.md](https://docs.docker.com/compose/compose-file/)

It's very hard to find frozen docs for old versions of the software. For various reasons I'm currently limited to compose version 1.3.1 and its difficult to find a compose file reference that is relevant to my needs.

At the very least, having the version in which a given feature was added would be helpful.

**Comment by alex-dr** [comment]
(Yes, I know I can go to https://github.com/docker/docker.github.io/blob/v1.6/compose/ for an approximation of what the compose 1.3.1 docs should be)

**Comment by londoncalling** [comment]
I believe this is addressed by the linked PR's

**Comment by alex-dr** [comment]
This is great, thanks for the update.
