### ISSUE TITLE
'layers' folder not present

### ISSUE THREAD

**Issue by gitcodex** [docker/docker.github.io#6424]
File: [storage/storagedriver/index.md](https://docs.docker.com/storage/storagedriver/), CC @gbarr01

I don't find the layers folder in /var/lib/docker/overlay/.
I have Docker EE trial version on rhel 7.4.
`ls -ltr /var/lib/docker/overlay/layers/`
`ls: cannot access /var/lib/docker/overlay/layers/: No such file or directory`

[docker info.txt](https://github.com/docker/docker.github.io/files/1896440/docker.info.txt)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
