### ISSUE TITLE
Insufficient information

### ISSUE THREAD

**Issue by geoidesic** [docker/docker.github.io#6427]
File: [machine/drivers/gce.md](https://docs.docker.com/machine/drivers/gce/), CC @gbarr01 

This document doesn't describe how docker relates to Google Compute at all. The images it seems to allude to images that are part of the Google image infrastructure, rather than from the docker image libraries. This distinction needs to be elaborated. It should be explained whether or not it is possible to reference a docker image rather than a Google VM image and how. It should also be explained what the `docker-machine create` instruction does exactly.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
