### ISSUE TITLE
IBM Cloud (beta) removal

### ISSUE THREAD

**Issue by JimCodified** [docker/docker.github.io#6432]
File: [install/index.md](https://docs.docker.com/install/), CC @gbarr01 

We need to remove or edit the line item "IBM Cloud (beta)". The current beta has been cancelled and is being restarted with IBM. We should either remove it completely or change to "IBM Cloud - coming soon". This would also require removal of the installation instructions at https://docs.docker.com/docker-for-ibm-cloud/.

CC @brawong PM working with IBM and @bettyjunod from Prod Marketing for approvals.

**Comment by gbarr01** [comment]
Hi, @JimCodified , which do you prefer? The edit or the  removal?

**Comment by gbarr01** [comment]
Also, there are a ton of pages in the IBM Cloud section ... do you want them all removed? or only this page? https://docs.docker.com/docker-for-ibm-cloud/

**Comment by gbarr01** [comment]
Number of references to beta in the IBM cloud docs: 

```
$ grep -cri --include="*.md" "beta" | grep -v ':0$'
administering-swarms.md:5
index.md:3
why.md:2
release-notes.md:7
quickstart.md:6
faqs.md:3
cli-ref.md:3
```

**Comment by JimCodified** [comment]
Just met with @joaofnfernandes about this - we're going to remove the whole ibm cloud section. On the install page there will just be a "coming soon". I just sent a PR with a bunch of changes and the edits to the install page are there too.
