### ISSUE TITLE
Deleting an Image- note about default registry config needed.

### ISSUE THREAD

**Issue by tbowden** [docker/docker.github.io#6434]
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/), CC @joaofnfernandes 

https://docs.docker.com/registry/spec/api/#deleting-an-image

It would be helpful under this section if a note was added that the default configuration of a registry was set to:
storage:
  delete:
    enabled: false

Trying to delete an image with this config setting results in an api error "UNSUPPORTED", the documentation of which doesn't adequately hint at the root cause in this case. ("The operation was unsupported due to a missing implementation or invalid set of parameters.") 

This issue probably also applies to deleting blobs.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
