### ISSUE TITLE
Feedback for: engine/admin/systemd.md

### ISSUE THREAD

**Issue by ebuildy** [docker/docker.github.io#644]
File: [engine/admin/systemd.md](https://docs.docker.com/engine/admin/systemd/)

After installed Docker 1.12 on Ubuntu 16.04, your doc is referring a file:

/etc/systemd/system/docker.service.d : No such file or directory

**Comment by mstanleyjones** [comment]
Related to #640. I'll evaluate what else needs to change here.

**Comment by mstanleyjones** [comment]
See https://docs.docker.com/engine/installation/linux/linux-postinstall/
