### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by ranjeetkowel** [docker/docker.github.io#6443]
File: [docker-for-mac/faqs.md](https://docs.docker.com/docker-for-mac/faqs/), CC @gbarr01.
The link Adding TLS certificates link (https://docs.docker.com/docker-for-mac/faqs/#adding-tls-certificates) is dead. It is not navigable.

**Comment by gbarr01** [comment]
@joaofnfernandes , is there a way to redirect anchors? 

This link:
https://docs.docker.com/docker-for-mac/faqs/#adding-tls-certificates

Is now this: 
https://docs.docker.com/docker-for-mac/#add-tls-certificates

cc: #6365
