### ISSUE TITLE
Multiple docker registries share single S3 bucket

### ISSUE THREAD

**Issue by lli-hiya** [docker/docker.github.io#6446]
### Problem description

I have deployed multiple docker registries in cloud, and used s3 as the storage. It works perfectly fine when each registry has its own S3 bucket, but it would be nice if I can just have one single bucket, then I can save a lot of data transfer and storage cost because all my registries are configured to use same up-stream source. 

I'd like to know is this feasible? I can see there is a `scheduler-state.json` file in the bucket, so my concern is that when multiple registries share the single bucket, the state probably cannot be kept correctly?

**Comment by gbarr01** [comment]
Hi, @lli-hiya , this seems more of a product question and not one for docs. 

Can you please ask this on the forums? https://forums.docker.com/

Thank you!
