### ISSUE TITLE
"Use a pre-existing network" outdated

### ISSUE THREAD

**Issue by Xsysstar** [docker/docker.github.io#6453]
File: [compose/networking.md](https://docs.docker.com/compose/networking/), CC @gbarr01

The documentation under "Use a pre-existing network" is outdated ("external.name" is no longer used).

By the way: I'm looking for ways to deploy my stack on (indeed) a pre-existing network, but I just can't get it to work. The following Compose.yaml fragment *does* cause a separate network to be created ("MyApp_default") instead of using the "intranet" network that already existed.

```yaml
networks:
  default:
    external: true
    name: intranet
```

If you could add documentation on what I'm doing wrong, it'd be very much appreciated.

**Comment by Xsysstar** [comment]
@gbarr01 The exact message is:

> WARN[0000] network default: network.external.name is deprecated in favor of network.name

**Comment by Xsysstar** [comment]
Note: I've also found *why* I couldn't get it it work. My network (`intranet`) did exist but it was not 'attachable'. Recreating my network with `--attachable` solved that particular problem it seems :-).

**Comment by gbarr01** [comment]
Okay, thanks @Xsysstar , I'll take a look as soon as I can.

**Comment by gbarr01** [comment]
@shin- , when you get a chance, is using an attachable network the right solution here? 

https://docs.docker.com/compose/networking/#use-a-pre-existing-network

**Comment by anthraxn8b** [comment]
Can confirm this.
Documentation seems a little bit weired here: https://docs.docker.com/compose/compose-file/#external

"[...] external.name was deprecated in version 3.4 file format use name instead [...]"

So how should my brand new code in version 3.6 look like?

**Comment by shin-** [comment]
Sorry I missed this.

The recommendation is the same for volumes, networks, secrets and configs ; instead of
```yaml
foo:
  external:
    name: something
```

one should now write

```yaml
foo:
  external: true
  name: something
```

for versions of the format that support it (that's 3.4+ for volumes and 3.5+ for everything else). These two snippets are functionally equivalent.

**Comment by NitroBAY** [comment]
Why not updating the doc then ? https://docs.docker.com/compose/networking/
