### ISSUE TITLE
Add example for the node RBAC in Swarm

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#6456]
File: [ee/ucp/authorization/isolate-nodes.md](https://docs.docker.com/ee/ucp/authorization/isolate-nodes/), CC @JimGalasyn 

Under the section `Alternative: Use a grant instead of the default collection`, it would be useful to provide a basic example of the usage as it isn't very clear; something as basic as `docker service create --name nginx --label "com.docker.ucp.access.label=/Prod/Webserver" nginx:alpine` would help.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
