### ISSUE TITLE
Windows bootcamp docs?

### ISSUE THREAD

**Issue by valgaze** [docker/docker.github.io#6465]
### Problem description

Should there be any docs for Docker-For-Windows running on a Mac using Bootcamp? 

There's an odd/not-officially-documented procedure to get virtualization enabled and perhaps it could be of value to make a separate doc pertaining just to bootcamp and not pollute main documentation with the procedure or any guidance

ex. 
### Problem location

- Other: No documentation

### Project version(s) affected
n/a

### Suggestions for a fix

If it makes sense to be included, add docs about how Docker for Windows does indeed work on Windows Bootcamp but there is an actual step that needs to be taken from the MacOS side

ex.

```
### Virtualization on Windows Bootcamp (Mac)

If you are on a capable Mac machine using [Bootcamp](https://support.apple.com/en-us/HT201468) to run Windows10 Pro, you can enable virtualization by setting Bootcamp/Windows as the system startup disk:

(Apple Menu in top left) > System Preferences > Target Disk > Bootcamp

```

**Comment by gbarr01** [comment]
cc: @akimd

**Comment by gavinwilliams** [comment]
This oddly works!

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
