### ISSUE TITLE
Unknown units of DiskSize and Memory 

### ISSUE THREAD

**Issue by artemik** [docker/docker.github.io#6476]
File: [machine/reference/inspect.md](https://docs.docker.com/machine/reference/inspect/), CC @gbarr01

The documentation or the values of the DiskSize, Memory, etc should tell what units they are in.

**Comment by gbarr01** [comment]
Hi, @artemik , thanks for the submission. Actually, the docs reflect the output and cannot add units where they do not exist. 

If this is something you want, please file your issue here: https://github.com/docker/machine

**Comment by artemik** [comment]
@gbarr01 whatever wherever technically resides, I, as a user of the documentation page `docker-machine inspect` want to know what values it returns and how to interpret it. A few examples, that are currently there, isn't enough. If the output corresponds to docker machine values, a link should be put denoting that and telling where to find meaning of each value.

Also, I shouldn't be guessing does it format docker machine values somehow or not. This also needs to e added.
