### ISSUE TITLE
docker-machine inspect unknown list of properties

### ISSUE THREAD

**Issue by artemik** [docker/docker.github.io#6477]
File: [machine/reference/inspect.md](https://docs.docker.com/machine/reference/inspect/), CC @gbarr01 

The documentation should enumerate all possible properties and their values of the output of the `docker-machine inspect` command. Right now it has a few examples only, without any explanation.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
