### ISSUE TITLE
Can we add document about -p HostIP:HostPort:ContainerPort?

### ISSUE THREAD

**Issue by longquanzheng** [docker/docker.github.io#6478]
File: [config/containers/container-networking.md](https://docs.docker.com/config/containers/container-networking/), CC @gbarr01

It is actually working

**Comment by joaofnfernandes** [comment]
@longquanzheng I don't really understand what you think should be improved. Can you detail it a bit more?

**Comment by longquanzheng** [comment]
I wanted use docker to run a container assigned with specific IP(other than 127.0.0.1). 
For example:
```
docker run -d --name cass3.11-3  -p  127.0.0.4:9242:9042 cassandra:3.11
```
It is already supported but the document does't say about it.

**Comment by joaofnfernandes** [comment]
From what I can tell both the [API and CLI support this](https://github.com/docker/go-connections/blob/master/nat/nat.go?utf8=%E2%9C%93#L11-L22), but it doesn't seem to be documented anywhere, including the API docs.

@thaJeztah is my assessment correct? If so, what's the use case for using this?
