### ISSUE TITLE
Not recommending a timeout in UCP load-balancer configurations

### ISSUE THREAD

**Issue by axeal** [docker/docker.github.io#6484]
File: [datacenter/ucp/2.2/guides/admin/configure/use-a-load-balancer.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/use-a-load-balancer/), CC @JimGalasyn 

The configuration examples in the 'Use a load balancer' docs page for UCP include the configuration of timeouts. However, per [esc/572](https://github.com/docker/escalation/issues/572), such timeouts can cause issues for the console or logs view within the UCP UI, or the `docker exec` or `docker logs` via a UCP Client Bundle.

[Recommendation from the escalation](https://github.com/docker/escalation/issues/572#issuecomment-382480092) is that 'we should not recommend setting a timeout in your proxy/load-balancer config for UCP connections. Instead, make sure that your proxy/load-balancer is using TCP Keep-alives for both ends of the connection. The system should handle terminating a connection if there are too many keepalive failures.'

**Comment by joaofnfernandes** [comment]
Issue moved to [docker/docs-private #625](https://github.com/docker/docs-private/issues/625) via [**ZenHub**](https://www.zenhub.com/)
