### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mauromussin** [docker/docker.github.io#6487]
File: [network/proxy.md](https://docs.docker.com/network/proxy/), CC @gbarr01 
the correct code is (v. 17.06)
```
docker run _variables_ --env "HTTP_PROXY=http://<user>:<password>@<proxy_address>:<proxy_port>"
```
and the same with HTTPS

**Comment by gbarr01** [comment]
Hi, @mauromussin  ... I'm not sure what you're saying here. Can you please clarify?

**Comment by gbarr01** [comment]
I reviewed this page and  as far as I can tell, the references to 17.06 and 17.07 are correct. I'm closing this issue but feel free to provide more info.
