### ISSUE TITLE
stop_signal says that it's ignored but it isn't?

### ISSUE THREAD

**Issue by skylerbunny** [docker/docker.github.io#6497]
### Problem description

The Compose Version 3 reference for the stop_signal command says, "This option is ignored when deploying a stack in swarm mode with a (version 3) Compose file."

However, I can do a stack deploy with a container with stop_signal specified on a container in a version 3.1 file, and doing an inspect does in fact show that stop_signal was used (and not ignored as the docs say) - and that said kill signal is used when I actually scale the service down:
```
$ docker stack deploy -c "/tmp/stack.yml" stackname
$ docker inspect <service>
...
        stop_signal: SIGINT
...
```

This disclaimer does NOT appear in the Version 2 reference at https://docs.docker.com/compose/compose-file/compose-file-v2/ , so I don't know if this is an oversight, or what was meant to be a temporary note about a bug in Compose 3 that was later fixed. In any event, I don't think "This option is ignored when deploying a stack in swarm mode with a (version 3) Compose file." is correct.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/compose/compose-file/#stop_signal

### Suggestions for a fix

Remove the affected text if someone can back up my assertion with their own testing (that stop_signal is NOT ignored, and is in fact used/supported in a swarm)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
