### ISSUE TITLE
index.md#shared-drives link on FAQ page is broken

### ISSUE THREAD

**Issue by kbuzby** [docker/docker.github.io#6499]
File: [docker-for-windows/faqs.md](https://docs.docker.com/docker-for-windows/faqs/), CC @gbarr01

The link to index.md#shared-drives does not work on the docker website. Seems like it must have some handling of index.md and redirecting that to the current page instead of the actual file referenced.

I'm not sure what the best way to fix this is, but if you let me know I can make the pull request for the edit.

**Comment by kbuzby** [comment]
@gbarr01 The changes in the PR you referenced this issue in was for the Docker for Mac FAQ, but this issue is for the Docker for Windows FAQ.  
The index.md#shared-drives links still don't work from that page.

**Comment by gbarr01** [comment]
Ah. Thanks, @kbuzby . I'll take a look.
