### ISSUE TITLE
Feedback for: toolbox/toolbox_install_mac.md

### ISSUE THREAD

**Issue by rogererens** [docker/docker.github.io#650]
File: [toolbox/toolbox_install_mac.md](https://docs.docker.com/toolbox/toolbox_install_mac/)

When uninstalling Toolbox, do you recommend to remove ~/.docker as well?

**Comment by londoncalling** [comment]
@rogererens I don't believe that's necessary, but pinging @chanezon , @justincormack , @nathanleclaire to be sure. Our current Toolbox uninstall instructions on Mac are here: https://docs.docker.com/toolbox/toolbox_install_mac/#/how-to-uninstall-toolbox

**Comment by londoncalling** [comment]
@rogererens, you should be okay with following the uninstall instructions above. Please ping us again here or on the [Docker Forums](https://forums.docker.com/) if you have more questions.

**Comment by nathanleclaire** [comment]
Yes, leaving `~/.docker` around should be fine in most cases

**Comment by nathanleclaire** [comment]
If you run into issues with VM creation that you are trying to avoid by re-installing from scratch, I suggest making sure your VirtualBox VMs are all deleted and un-installing that, but the `~/.docker` directory just stores some Docker program configuration and/or state (e.g., info of created machines such as certificates).
