### ISSUE TITLE
FROM syntax spec is not clear about hash algo

### ISSUE THREAD

**Issue by halfer** [docker/docker.github.io#6500]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @gbarr01

I was getting really stuck on the docs for the `FROM` directive in the `Dockerfile` format, which says:

    FROM <image>[@<digest>] [AS <name>]

So I was using:

    FROM alpine@3d44fa76c2c83ed9296e4508b436ff583397cac0f4bad85c2b4ecc193ddb5106 AS build

which produces:

> invalid reference format

After much searching, and not finding any examples of pinning to a hash, I tried this on a whim:

    FROM alpine@sha256:3d44fa76c2c83ed9296e4508b436ff583397cac0f4bad85c2b4ecc193ddb5106 AS build

That worked. Thus, since I don't think it is clear that `<digest>` needs to specify the hash algorithm and a colon, can we change this to:

    FROM <image>[@<hash-algo>:<digest>] [AS <name>]

Or, can an example be added in this section, so it is clear that the algo is required?

**Comment by halfer** [comment]
The above is a suggested documentation change. However, the error message could also be tweaked (additionally or instead of the above change).

Instead of:

> invalid reference format

it could be:

> invalid reference format, the syntax is @<hash-algo>:<hash>

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by halfer** [comment]
I'd love to be able to change the error message, but I am not sure how to shepherd such a change into the code, and I don't know whether the change is desired or welcome. Ideally, I'd like to hear feedback from core devs or fellow users about whether they agree with the proposal first.
