### ISSUE TITLE
[WIP] Update proxy docs

### ISSUE THREAD

**Issue by gbarr01** [docker/docker.github.io#6514]
Update and clarify the proper way to use a web proxy on the daemon and client. 

Ensure Desktop products do not have to configure Docker.

https://docs.docker.com/network/proxy/
https://docs.docker.com/config/daemon/systemd/

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
