### ISSUE TITLE
Document the --read-only flag in the Security page

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#6526]
Moving from the moby/moby repository (https://github.com/moby/moby/issues/12656);

https://github.com/docker/docker.github.io/blob/374d240c6a1ed1a4baa2d1d22ac7314d1f6943cd/engine/security/security.md Should mention --read-only on container here.

/cc @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
