### ISSUE TITLE
Edit url

### ISSUE THREAD

**Issue by PW-Snow** [docker/docker.github.io#6527]
File: [install/linux/docker-ee/rhel.md](https://docs.docker.com/install/linux/docker-ee/rhel/), CC @gbarr01

Step 6 of setting up the registry contains the example snippet $DOCKERURL/rhel/... 

However, the /rhel/ was already set before and is therefore obsolete. The current example results in an invalid /rhel/rhel URL.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
