### ISSUE TITLE
Engine API docs for /build missing description of response body

### ISSUE THREAD

**Issue by cdunklau** [docker/docker.github.io#6530]
File: [develop/sdk/index.md](https://docs.docker.com/develop/sdk/), CC @gbarr01

First of all, if this is the wrong forum to report this, please suggest a more suitable one. I chose to use this "Request docs changes" link because the Engine API docs are linked from that page.

The /build endpoint docs don't discuss the format or semantics of the response body: https://docs.docker.com/engine/api/v1.37/#operation/ImageBuild

Is this documented elsewhere, or can it be added to the API docs? I'd like to at least see answers for these questions:

1. What are the structures of the various JSON lines?
2. What do they represent?
3. Under what circumstances are the specific "types" present and absent?
4. How can I tell if the build succeeded or failed after it was initially accepted (and the API sent a 200 status)?

The following is what I've found out so far about the distinct message "types":

### Keys: "stream"

Example: `{"stream": "Step 1/9 : FROM debian:stretch-slim"}`

Appears to be chunks of general information from the build, along with the output of commands run in the container. Lines may be spread over several JSON messages.

### Keys: "id", "status"

Example: `{"id": "stretch-slim", "status": "Pulling from library/debian"}`

I've only seen at most one of these per build, but I wonder if there could be several in the event of a multi-stage build?

### Keys: "id", "progressDetail", "status"

Example: `{"id": "2a72cbf407d6", "progressDetail": {}, "status": "Pulling fs layer"}`

I saw four of these in one build.

### Keys: "id", "progressDetail", "progress", "status"

Example:
```
{
    "id": "2a72cbf407d6",
    "progressDetail": {"current": 228636, "total": 22488979},
    "progress": "[>                                                  ]  228.6kB/22.49MB",
    "status": "Downloading"
}
```

There were a lot of these, around 60. Possible values for status are "Downloading", "Verifying Checksum", "Download complete", and "Extracting".

### Keys: "status"

Example: `{"status": "Digest: sha256:613efd414e9818dcef858201484a94603a548a0e04fd4356e77eb758aeb16124"}`

I only saw two of these. One with the hash of the parent image, and one with "Status: Downloaded newer image for debian:stretch-slim".

### Keys: "aux"

Example:
```
{
    "aux": {
        "ID": "sha256:e7b81c7b21f3445eff249dc098092372ef1494caffaaf1c003bb0cb0ae9bb630"
    }
}
```

This only happened once, and the hash matches the ID of the completed image.
As far as I can tell, this is the most important JSON message, but the semantics are unclear. Will there ever be more than one? Does this message mean the image was successfully built, or are there other conditions that need to be met?

I'd appreciate any pointers towards existing docs, or even the source code where these messages are generated and emitted. I've been tearing my hair out for days looking for them without much success. Thanks in advance for any assistance you can provide.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by cdunklau** [comment]
Hi @L-Hudson, it's still unclear to me where the documentation for the API endpoints is located, so I don't know the proper place for this issue. I'd prefer if you could re-open (I apparently don't have that ability) at least until someone can help point to the proper place for this issue... the latest doc version still has the problem: https://docs.docker.com/engine/api/v1.39/#operation/ImageBuild
