### ISSUE TITLE
Advanced Recipes Overview page is listed as a source for how to setup a custom authentication method with a private docker registry, but does not include such information

### ISSUE THREAD

**Issue by BBKolton** [docker/docker.github.io#6545]
File: [registry/recipes/index.md](https://docs.docker.com/registry/recipes/), CC @joaofnfernandes 

I'm working on setting up a private repo with advanced authentication. I made my way to the recipes file, which had then provided several advanced configurations of the docker repository, but none of them include an example of how to set up an authenticator for repo logins. All the linked examples only provide basic username and password auth. 

I'll be working through the problem and will create a PR with updated documentation if no one else can get to it first :)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
