### ISSUE TITLE
Mention that volumes under Windows are not available to the host.

### ISSUE THREAD

**Issue by helmbold** [docker/docker.github.io#6546]
File: [storage/volumes.md](https://docs.docker.com/storage/volumes/), CC @gbarr01

I wondered where Docker stores the volumes. The output of `docker volume inspect` is not that helpful in this regard under Windows, since it shows a Linux path. It should be mentioned that you have to create a folder, enable shared drives in the setting and then mount the folder from the host system.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
