### ISSUE TITLE
No mention of arm64 in the install instructions

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#6556]
File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/), CC @gbarr01

This page (https://docs.docker.com/install/#server) mentions arm64 under Docker CE but I do not see it listed in the table for install instructions.

**Comment by gbarr01** [comment]
Hi, @mbentley , I need to figure out how to handle these discrepancies because we do not _officially_ support arm64. @andrewhsu , please confirm.

**Comment by mbentley** [comment]
Ah ok, I mistook the check marks on the install page linked above as meaning supported.  Turns out that I was actually interested in `armhf` anyway.  Thanks!

**Comment by gbarr01** [comment]
No worries, I hope to clear up the confusion soon. I have other open issues addressing it. Thanks, Matt.
