### ISSUE TITLE
List Associated Aspects

### ISSUE THREAD

**Issue by gg2** [docker/docker.github.io#6557]
File: [engine/reference/commandline/pause.md](https://docs.docker.com/engine/reference/commandline/pause/), CC @gbarr01

Provide on this page what command would be used to unpause a container. And vice versa, on whatever page for the command that might do that, reference `docker pause` as the command that would lead to using that. Make references to pairwise or otherwise similar associations, state implications, descriptions of consequences of taking an action in documentation, please.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
