### ISSUE TITLE
Tutorial forgets about the default master node

### ISSUE THREAD

**Issue by starrychloe** [docker/docker.github.io#6576]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/), CC @gbarr01
https://docs.docker.com/get-started/part4/#create-a-cluster

Somehow the tutorial just plain forgets about the default master manager node and assumes it no longer exists.

```
C:\Temp\docker-tutorial>docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
tfn7ol5mtro2oqrni49w3nkdk *   default             Ready               Active              Leader              18.03.1-ce
elk7bb1eotp9dao3qxnbxdo7h     myvm1               Ready               Active                                  18.03.1-ce
monv04o4s14jq2whh9gt5y3hd     myvm2               Ready               Active                                  18.03.1-ce
```

The rest of the tutorial tries to use myvm1 as the manager node for some reason which isn't necessary.

**Comment by gbarr01** [comment]
Hi, @starrychloe , I don't understand ... `myvm1` should be the manager. 

> Now that you have myvm1, you can use its powers as a swarm manager to deploy your app ....

I'm guessing that you did not leave the swarm in part 3?

**Comment by starrychloe** [comment]
Just because you leave the swarm doesn't make the default machine go away. (Unless it's supposed to work that way, in which case it's a bug.) 

```
C:\Temp\docker-tutorial>docker swarm leave --force
Node left the swarm.

C:\Temp\docker-tutorial>docker node ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.

C:\Temp\docker-tutorial>docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v18.03.1-ce
myvm1     -        virtualbox   Running   tcp://192.168.99.101:2376           v18.03.1-ce
myvm2     -        virtualbox   Running   tcp://192.168.99.102:2376           v18.03.1-ce
```

Remove the machines...

    docker-machine rm myvm1
    docker-machine rm myvm2

Create the machines...

    docker-machine create --driver virtualbox myvm1
    docker-machine create --driver virtualbox myvm2

So why do you only list 2 machines?

LIST THE VMS AND GET THEIR IP ADDRESSES: https://docs.docker.com/get-started/part4/#create-a-cluster

There are now 3 machines, not 2.

```
C:\Temp\docker-tutorial>docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v18.03.1-ce
myvm1     -        virtualbox   Running   tcp://192.168.99.103:2376           v18.03.1-ce
myvm2     -        virtualbox   Running   tcp://192.168.99.104:2376           v18.03.1-ce
```

Why do you try to make myvm1 the manager when you already have the default machine available? What's the point? Why is it necessary?

    $ docker-machine ssh myvm1 "docker swarm init --advertise-addr <myvm1 ip>"

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
