### ISSUE TITLE
Missing exec_die event in event docs

### ISSUE THREAD

**Issue by nstapelbroek** [docker/docker.github.io#6579]
Heya!

After some digging around into my `docker events` I found out that my containers are producing a couple of `exec_die` events that aren't listed in the docs. I found a PR that introduces the event here: https://github.com/moby/moby/pull/35744

Am I correctly assuming that this is an event we should add to the list?  

File: [engine/reference/commandline/events.md](https://docs.docker.com/engine/reference/commandline/events/), CC @gbarr01

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
