### ISSUE TITLE
Broken link in "WHAT DO I DO IF I THINK THE SCAN RESULTS ARE INCORRECT?"

### ISSUE THREAD

**Issue by beckmani** [docker/docker.github.io#6585]
File: [docker-cloud/builds/image-scan.md](https://docs.docker.com/docker-cloud/builds/image-scan/), CC @gbarr01

Broken link in: frequently-asked-questions
under: "WHAT DO I DO IF I THINK THE SCAN RESULTS ARE INCORRECT?"

**Comment by gbarr01** [comment]
Hi, @beckmani , are you looking at an archived page? https://docs.docker.com/v17.12/docker-cloud/builds/image-scan/

**Comment by beckmani** [comment]
@gbarr01, yes. 
See the attached image
![s80429-22314539](https://user-images.githubusercontent.com/10331175/39410240-9f62cece-4bfd-11e8-87fa-c67164168014.jpg)
