### ISSUE TITLE
Geomanist font not properly rendering in sections

### ISSUE THREAD

**Issue by carolineartz** [docker/docker.github.io#659]
### Problem description

The side navigation, many of the headings, and various other places aren't rendering the Geomanist font. See the image below for a couple examples. In the image, the sidebar is rendering my browser default font because the defined font cannot resolve; the sidebar is rendering Helvetica Neue because it's defined as such.

<img width="648" alt="docker plugin api - today at 9 28 29 pm" src="https://cloud.githubusercontent.com/assets/2850369/20460126/8eeab5e0-ae9f-11e6-8950-39d2d7ebba94.png">

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ and any child pages

- Other: <DETAILS>

### Suggestions for a fix

I did see a comment on [456](https://github.com/docker/docker.github.io/issues/456) noting the very large css file. 

Beyond organization and overriding the headings with the desired font, I don't think there is currently good support for using the primary font as a family and specifying only the weight when adjusting. Some of the resolution errors are because the font is referenced as a family name that doesn't exist (e..g, 'Geomanist Regular'). The current copies of the font files for this typeface do not make it easy to use the `font-family: Geomanist` with whatever weight is appropriate. However, it's possible to adjust the files to make it work! Check out [Geomanist font files -- updated](https://www.dropbox.com/sh/4pfiwa1ly04hbid/AADd4sHkbYiBq9s2xB5beppJa?dl=0)

**Comment by johndmulhausen** [comment]
Closing this oldie; think we're all set. Thanks!
