### ISSUE TITLE
Change of version changes the page

### ISSUE THREAD

**Issue by akimd** [docker/docker.github.io#6590]
### Problem description

1. Go to https://docs.docker.com/docker-for-mac/
2. Set the version of the doc to 17.12 for instance
3. You land at https://docs.docker.com/v17.12/ instead of https://docs.docker.com/v17.12/docker-for-mac

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
