### ISSUE TITLE
How to set seccomp to unconfined while starting docker service ?

### ISSUE THREAD

**Issue by chakravarthy392** [docker/docker.github.io#6594]
ARCH : S390X
OS : SLES 12 SP2

I am getting the below error while creating container on SLES using docker-18.03 installed from [static binary](https://download.docker.com/linux/static/stable/s390x/).

"docker: Error response from daemon: OCI runtime create failed: container_linux.go:265: starting container process caused "seccomp: config provided but seccomp not supported": unknown.
"

I have installed `libseccomp` dependency and able to create a container by including `--security-opt seccomp=unconfined` while executing docker run command, but I want to disable seccomp while initializing the docker service itself.

I have tried to do it by passing the same parameter to docker service file but could not start the docker. Please let me know if there is any way.

**Comment by jupiterianian** [comment]
@chakravarthy392, some remarks from the noob: my gut feeling, that in spite of docker itself, seems, and you can easily prove it with `docker info`, was built with seccomp enabled, the underlying containerization env was not. The only way, here someone can correct me, is either to build `runc` with seccomp enabled, replace the `docker-runc`, shipped with static binaries, and enjoy the default docker's seccomp profile or to avoid static binaries in the way they are available today. If my guess is right, hope, Dockerers will provide fixed binaries some day.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
