### ISSUE TITLE
Where is the 2.2 UCP offline version

### ISSUE THREAD

**Issue by AsaBeavers** [docker/docker.github.io#6599]
File: [datacenter/ucp/2.1/guides/admin/install/install-offline.md](https://docs.docker.com/datacenter/ucp/2.1/guides/admin/install/install-offline/), CC @jimgalasyn

**Comment by joaofnfernandes** [comment]
You can find it here - https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/install-offline/
