### ISSUE TITLE
Feedback for: engine/reference/commandline/search.md

### ISSUE THREAD

**Issue by hyunjun19** [docker/docker.github.io#660]
File: [engine/reference/commandline/search.md](https://docs.docker.com/engine/reference/commandline/search/)

<img width="1021" alt="2016-11-20 4 08 30" src="https://cloud.githubusercontent.com/assets/421863/20461268/b1235792-af3b-11e6-9528-f7ba756fa5d2.png">

example command is wrong.
```bash
$ docker search --filter "is-automated=true" --filter "stars=3" busybox
```

`is-automated` -> `is-official`
```bash
$ docker search --filter "is-official=true" --filter "stars=3" busybox
```

**Comment by mstanleyjones** [comment]
Filed https://github.com/docker/docker/pull/28890 to fix this. Work will happen in that repo. Thanks for the report!
