### ISSUE TITLE
Following the guide on OSX does not work

### ISSUE THREAD

**Issue by cpoDesign** [docker/docker.github.io#6601]
File: [compose/aspnet-mssql-compose.md](https://docs.docker.com/compose/aspnet-mssql-compose/), CC @gbarr01

Hi I was trying to follow the guide of my Mac and it does not work. It would be great to have a pointer to some github repo with examples

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
