### ISSUE TITLE
--volume options [z|Z] and [[r]shared|[r]slave|[r]private] not described at all.

### ISSUE THREAD

**Issue by cowlinator** [docker/docker.github.io#6603]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/), CC @gbarr01 
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/), CC @gbarr01

Both of these pages mention do not have any information about what the [z|Z] and
[[r]shared|[r]slave|[r]private] "options" for --volume are or what they do.  

I was able to find that information in the 'man' page (  https://github.com/docker/cli/blob/master/man/docker-run.1.md ) 
but the man page does not seem to be anywhere on the web documentation; or at the very least it is very difficult to find.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
