### ISSUE TITLE
Regular docker login

### ISSUE THREAD

**Issue by NescobarAlopLop** [docker/docker.github.io#6607]
File: [engine/reference/commandline/login.md](https://docs.docker.com/engine/reference/commandline/login/), CC @gbarr01

I think it would be helpful to add the basic docker login instruction:

:~$ docker login
Username: <your_username>
Password: <your_password>

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
