### ISSUE TITLE
Docs - Docker EE Weave

### ISSUE THREAD

**Issue by kenlavoie** [docker/docker.github.io#6610]
File: [ee/ucp/kubernetes/install-cni-plugin.md](https://docs.docker.com/ee/ucp/kubernetes/install-cni-plugin/), CC @gbarr01 

Requesting a change to this, as Weave requires clusterroles capabilities, which are not supported in the current RBAC model

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
