### ISSUE TITLE
GELF driver does not accept tcp connections

### ISSUE THREAD

**Issue by adamancini** [docker/docker.github.io#6611]
If trying to configure GELF logging driver, Docker Engine reports `gelf: endpoint needs to be UDP`

File: [config/containers/logging/gelf.md](https://docs.docker.com/config/containers/logging/gelf/), CC @gbarr01

**Comment by joaofnfernandes** [comment]
Thanks for filling this! As it is your feedback is not very actionable. Can you tell what's wrong, what could be fixed?
If this can be fixed with a simple tweak to the docs, please consider opening a PR and fixing it directly.

**Comment by adamancini** [comment]
For some reason the link on the docs page that usually allows me to edit/submit PR's is not listed - maybe because my github orgs were revoked a week or two ago because of a lost laptop incident?

**Comment by adamancini** [comment]
But in any case, we should edit the docs where it says: 

gelf-address | required | The address of the GELF server. tcp and udp are the only supported URI specifier and you must specify the port. | --log-opt gelf-address=udp://192.168.0.42:12201

to not specify TCP as a valid option

**Comment by adamancini** [comment]
I submitted ^ manually

**Comment by thaJeztah** [comment]
TCP support was added to the GELF driver in https://github.com/moby/moby/pull/34758 - what version of Docker did you test this on?
