### ISSUE TITLE
inconsistent

### ISSUE THREAD

**Issue by vpronov** [docker/docker.github.io#6616]
File: [engine/userguide/networking/default_network/custom-docker0.md](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/), CC @mistyhacks 
"For instance, you can configure --fixed-cidr=**172.17.2.0/24** and default-gateway=**172.17.1.1**"
default-gateway must be in range **172.17.2.1-172.17.2.254**

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
