### ISSUE TITLE
Certified infrastructure feedback

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#6621]
From Slack

Somehow some old text got put into the docs. There is mention of EE released quarterly. (Instead of more recently I’ve seen released twice a year.  Also text around DDC. `If you're a Docker DDC or CS Engine customer, you don't need to upgrade to Docker EE to continue to get support.`
^^ here: https://docs.docker.com/ee/supported-platforms/#docker-enterprise-edition-release-cycles

---

The Tiers on the docs page is old too, references before 17.06 launch I think. Doesn’t match the pricing page: https://www.docker.com/pricing

---

Also - we should remove `security` from `Container engine and built in orchestration, networking, security` and put it under `Certified infrastructure, plugins and ISV containers`

for this https://docs.docker.com/ee/supported-platforms/#docker-ee-tiers ^^

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
