### ISSUE TITLE
Raspbian install instructions are contradictory

### ISSUE THREAD

**Issue by AlxndrPsclt** [docker/docker.github.io#6626]
### Problem description
The install instructions for Raspbian offer conflicting informations on the same page. It is written several times that install using repository is not possible, and one should use the convenience script.

> "Raspbian users cannot use this method!
>     For Raspbian, installing using the repository is not yet supported. You must instead use the convenience script."

> Most users set up Docker’s repositories and install from them, for ease of installation and upgrade tasks. This is the recommended approach, except for Raspbian.

Yet the install docker-ce section specifies that the procedure also works with Raspbian.

> "Install Docker CE
>     Note: This procedure works for Debian on x86_64 / amd64, Debian ARM, or Raspbian."

And indeed, using the armf repository the installation seems to work.

This should be clarified. Is docker now installable on Raspbian using the normal armf repository? Or is this installation causing a problem? 

### Problem location

- I saw a problem on the following URL:
https://docs.docker.com/install/linux/docker-ce/debian/#install-docker-ce

### Project version(s) affected
Docuementation for docker Raspbian/armf install

### Suggestions for a fix

I can do a pull request to clarify documentation once I'm sure if convenience script is still required for Raspbian install (would be usefull to specify why this is the case), or if the armf repository is ok for Raspbian install.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
