### ISSUE TITLE
min_tls_version nows defaults to 1.2

### ISSUE THREAD

**Issue by darwin-traver** [docker/docker.github.io#6632]
File: [ee/ucp/admin/configure/ucp-configuration-file.md](https://docs.docker.com/ee/ucp/admin/configure/ucp-configuration-file/), CC @gbarr01 

min_tls_version | no | Sets the minimum TLS version for the controller to serve. Valid options are tlsv1, tlsv1.0, tlsv1.1, and tlsv1.2. An empty string defaults to TLS version 1.0.

As per UCP 2.2.6+, min_tls_version now defaults to 1.2 and not 1.0 as per the chart.

Code reference:
https://github.com/docker/go-connections/blob/master/tlsconfig/config.go#L69

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
