### ISSUE TITLE
Cluster management in Docker Cloud and getting started guide

### ISSUE THREAD

**Issue by thibauds** [docker/docker.github.io#6638]
### Problem description

The part 6 of the getting started guide "[Deploy your app](https://docs.docker.com/get-started/part6/)" mentions "Docker Cloud to help manage your app" but does not mention that Cluster management is being retired from Docker Cloud.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/get-started/part6/

**Comment by ethanyanjiali** [comment]
seeing the same issue here still

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
