### ISSUE TITLE
Linux Isn't Listed in Desktop Section

### ISSUE THREAD

**Issue by felicianotech** [docker/docker.github.io#6642]
File: [install/index.md](https://docs.docker.com/install/)

Linux distros are listed in the server section but not in the desktop section. Linux is also a desktop OS.

Ideally, have a few popular desktop distros such as Ubuntu, Debian, Fedora, or Elementary would be nice. Docker runs natively on/because of Linux. Some desktop love would be great.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
