### ISSUE TITLE
three options to stage the docs? there are only two in readme

### ISSUE THREAD

**Issue by dongzhuoer** [docker/docker.github.io#6644]
In [Staging the docs](https://github.com/docker/docker.github.io#user-content-staging-the-docs)

> You have three options:
> 1. ...
> 2. ...

Where is the third option?

**Comment by joaofnfernandes** [comment]
I don't think there's a third option. If there is a third option, it is use the `docker run` command that's equivalent to the using docker-compose.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
