### ISSUE TITLE
Documentation doesn't match images

### ISSUE THREAD

**Issue by benmar** [docker/docker.github.io#6645]
File: [get-started/part6.md](https://docs.docker.com/get-started/part6/)

In [this image](https://docs.docker.com/get-started/images/cloud-app-in-browser.png) it seems that Redis is not accessible. Whats going wrong?

On [this other image](https://docs.docker.com/get-started/images/cloud-visualizer.png) the redis container doesn't appear, and it shows a dockercloud-server-proxy that is not mentioned in the article.

Anyway, great work!

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
