### ISSUE TITLE
Not valid JSON in "Example Manifest List"

### ISSUE THREAD

**Issue by agonzalezro** [docker/docker.github.io#6652]
File: [registry/spec/manifest-v2-2.md](https://docs.docker.com/registry/spec/manifest-v2-2/)

There is an extra `,` in line 11. Where it says:

```
      "platform": {
        "architecture": "ppc64le",
        "os": "linux",
      }
```

It should say:

```
      "platform": {
        "architecture": "ppc64le",
        "os": "linux"
      }
```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
