### ISSUE TITLE
Swarm routing mesh documents missing step for applying node constraints

### ISSUE THREAD

**Issue by ericsmalling** [docker/docker.github.io#6654]
### Problem description
https://docs.docker.com/ee/ucp/interlock/deploy/production/ fails to mention the step outlined at https://interlock-dev-docs.netlify.com/install/production/#configure-proxy-service which causes the proxy containers to actually get the constraint configurations

The "Note" on the page about deploying a service to cause the proxies to restart does not actually put the new node constraints into them.  Per Slack chat with @ehazlett , this last step (linked above) must be performed:

```
$> docker service update --replicas=2 \
    --constraint-add node.labels.nodetype==loadbalancer \
    --stop-signal SIGQUIT \
    --stop-grace-period=5s \
    $(docker service ls -f 'label=type=com.docker.interlock.core.proxy' -q)
```

### Problem location

https://docs.docker.com/ee/ucp/interlock/deploy/production/ at the "Known issue" box near the bottom of the document.

### Project version(s) affected

UCP 3.0.0+

### Suggestions for a fix
Copy text from https://interlock-dev-docs.netlify.com/install/production/#configure-proxy-service in place of the "Known issue"

**Comment by ericsmalling** [comment]
Note - the host mode page also is missing a similar step as described at https://interlock-dev-docs.netlify.com/usage/host_mode/#configure-proxy-services

Basically, after changing either of these configurations, the proxies service has to be updated to re-schedule it correctly.

**Comment by martencassel** [comment]
This is not clear...

How is interlock-proxy scheduling configurations updated ? 

    - Can i just update ProxyConstraints in the configuration file, 
      by updating the configuration object ? 

      Will interlock service run a docker service update using 
      the new ProxyConstraints if i update its configuration  file ? 

    - Do i have to run a docker service update myself ? 

    - The ProxyConstraints is not documented in the configurations listning among other Proxy* properties:

    https://docs.docker.com/ee/ucp/interlock/deploy/configuration-reference/#core-configurations

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
