### ISSUE TITLE
Google chrome is not working in Ubuntu docker container 

### ISSUE THREAD

**Issue by sam0104** [docker/docker.github.io#6655]
### Problem description
Google chrome is not working in Ubuntu docker container  unless deploy docker container with docker run -d --cap-add=SYS_ADMIN  or --privileged which is not secure for production deployment. How to run google chrome with more secure way without compromise security.

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by joaofnfernandes** [comment]
@sam0104 I don't really understand your question. Are you trying to follow some tutorial in the Docker docs and it doesn't work for you?

**Comment by sam0104** [comment]
It does not work for me. The only way to use chrome inside ubuntu 18.x with xrdp is deploy the docker using --cap-add=SYS_ADMIN or --privileged   . If I just use docker run -d  and install chrome using apt-get then chrome never works. It only works if I deploy it using SYS_ADMIN or privileged mode.
I tried to find the documentation from Docker website regarding SYS_ADMIN parameter but could not find much information. 

My question : Is it safe to use --cap-add=SYS_ADMIN rather --privileged in production ?
What type of security risk I open if I deploy container with --cap-add=SYS_ADMIN ? 
Can I use other configuration so that chrome browser will work without make the docker container less prone to attack ?

reference to chrome browser issue on docker :  https://github.com/GoogleChrome/lighthouse/issues/378#issuecomment-386742508

**Comment by joaofnfernandes** [comment]
I think our docs can give you examples how Docker can be used, but we should not go into specifics about how to run Chrome or other apps in Docker.

We have some docs around `--privileged `, `--cap-add`, `--cap-rm` here - https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
And you can learn more about capabilities in these man pages - http://man7.org/linux/man-pages/man7/capabilities.7.html

From what I can tell `--cap-add=SYS_ADMIN` is really permissive, and while technically different than `--privileged`, for all effects and purposes there's not too much of a difference between the two.

I'm going to close this issue, given that this is specific to Chrome, but feel free to comment.
