### ISSUE TITLE
Multiple Compose files in docker stack deploy

### ISSUE THREAD

**Issue by new-guy** [docker/docker.github.io#6656]
File: [engine/reference/commandline/stack_deploy.md](https://docs.docker.com/engine/reference/commandline/stack_deploy/)

Under the examples about multiple compose files, it suggests you can supply multiple compose files with the format `docker stack deploy --compose-file [COMPOSE_FILE_1] -f [COMPOSE_FILE_2] [STACK_NAME]`

In the options section, though, it says that you specify compose files only with the options `--compose-file` or `-c` (no mention of -f at all).

Would it be possible to get some consistency/further explanation regarding this?  Thanks!

**Comment by sorabhm** [comment]
Moreover, even we supply multiple compose files using the -c parameters only the last compose file is read and loaded by docker stack. Is this issue already been tracked somewhere?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
