### ISSUE TITLE
install old version of docker

### ISSUE THREAD

**Issue by doveStep** [docker/docker.github.io#6657]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/)

I need to install an old version of docker-- 1.13.
I've tried the following to no avail: 
1) homebrew and cask don't have older versions of docker-- or none that i could find
2) i went to https://docs.docker.com/v1.13/docker-for-mac/install/ and it installed v1.18 !!!!! not what i wanted!
3) i google searched for 10 minutes trying to figure out how to download 1.13 instead of the latest and am still searching...

**Comment by joaofnfernandes** [comment]
Did you check the information that's on the release notes? https://docs.docker.com/docker-for-mac/release-notes/#docker-for-mac-1130-2017-01-19

I'm closing this issue given that this is documented, but feel free to comment.
