### ISSUE TITLE
A better command for install docker-compose on linux.

### ISSUE THREAD

**Issue by taichunmin** [docker/docker.github.io#6658]
### Problem description

A better command for install docker-compose on linux.

Original install command will out of date very quickly. So maybe we can update the command to prevent install old version. This is helpful when somebody copy the command to their own article or docs. It is easy to forget to update the docker-compose to the latest version. I can create a PR for this.

p.s. Following is a screenshot for "[The Docker Book](https://dockerbook.com/)."
![](https://i.imgur.com/be52FJd.png)

### Problem location

- I saw a problem on the following URL: https://github.com/docker/docker.github.io/blob/master/compose/install.md

### Project version(s) affected

docker-compose all version docs

### Suggestions for a fix

```bash
sudo curl -L https://github.com/docker/compose/releases/download/$(curl -sL https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d'"' -f 4)/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
