### ISSUE TITLE
Interlock Config $NEW_CONFIG_NAME missing

### ISSUE THREAD

**Issue by stevenfollis** [docker/docker.github.io#6659]
File: [ee/ucp/interlock/deploy/configure.md](https://docs.docker.com/ee/ucp/interlock/deploy/configure/)

Hi, looks like in a recent edit the setting of `$NEW_CONFIG_NAME` was removed. If you run the steps as written, when you reach `docker config create $NEW_CONFIG_NAME config.toml` it comes back without having that variable set. 

Likely just needs to be added back in? Thanks!

**Comment by trapier** [comment]
@stevenfollis: looks like assignment of `NEW_CONFIG_NAME` is there now.  Take a look and close this out if so?
