### ISSUE TITLE
Feedback for: engine/reference/api/docker_remote_api_v1.24.md

### ISSUE THREAD

**Issue by VamsidharMuggulla** [docker/docker.github.io#666]
File: [engine/reference/api/docker_remote_api_v1.24.md](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/) 

The container stats based on resource usage has values could be provided with the information like the metric or units the values signify.
`"total_usage" : 100215355,` in cpu_stats the value 100215355 is something which I cannot understand, whether it is a time in ms or ns, or a percentage per something.

**Comment by johndmulhausen** [comment]
Self assigning this (beastly-numbered) issue which will be obsolete when #606 merges.

**Comment by johndmulhausen** [comment]
Closing this oldie; we now use ReDoc for API references
