### ISSUE TITLE
Feedback for: engine/reference/commandline/swarm_join.md

### ISSUE THREAD

**Issue by alssi** [docker/docker.github.io#667]
File: [engine/reference/commandline/swarm_join.md](https://docs.docker.com/engine/reference/commandline/swarm_join/)

This flag specifies the address that will be advertised to other members of the swarm for API access. If unspecified, Docker will check if the system has a single IP address, and use that IP address **with with** the listening port (see --listen-addr).

Duplicate "with"?

**Comment by mstanleyjones** [comment]
Will be fixed as part of https://github.com/docker/docker/pull/28891

While I was thinking of doubled words, I found and fixed some in this repository too: 

https://github.com/docker/docker.github.io/pull/728

And in some other upstream vendored repos:

https://github.com/docker/distribution/pull/2083
https://github.com/docker/notary/pull/1047
