### ISSUE TITLE
Issue with prometheus instructions

### ISSUE THREAD

**Issue by anomaly256** [docker/docker.github.io#6674]
File: [config/thirdparty/prometheus.md](https://docs.docker.com/config/thirdparty/prometheus/)

This document seems to completely ignore how host, container, and docker swarm networking interacts and as such is not usable

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by anomaly256** [comment]
I'm fairly certain that these instructions are still going to be wrong despite any refactor.  They bind port 9323 to localhost on the swarm node in question, then expect the service to be able to reach that through the overlay network.  In the case of the Linux prometheus yaml they also expect localhost to resolve to the specific docker node the metrics are to be pulled from.

**Comment by anomaly256** [comment]
Also it seems I am actually unable to re-open this anyway, github isn't giving me the option
