### ISSUE TITLE
Docker cloud CACHE_TAG not working

### ISSUE THREAD

**Issue by javiersvg** [docker/docker.github.io#6684]
### Problem description

The documentation about [docker cloud](https://docs.docker.com/docker-cloud/builds/advanced/#environment-variables-for-building-and-testing) indicates that the CACHE_TAG variable can be utilized in builds. This feature does not work. Nor staright in the docker file nor using the build hooks.

### Problem location

- I saw a problem on the following URL: 
   - https://hub.docker.com/r/zotonic/zotonic/builds/bkd5umkd5bdielp49v9rvb7/
   - https://cloud.docker.com/swarm/javiersvg/repository/registry-1.docker.io/javiersvg/tour-of-heroes/builds/65a7f2be-373b-45ea-bf51-cfdf24e217e6
- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: I have created a stackoverflow [post](https://stackoverflow.com/questions/50194780/docker-cloud-cache-tag-not-being-pased-over-to-hook) and there is an ananswered [question](https://forums.docker.com/t/build-env-var-cache-tag-not-passed-to-post-push-hook/41747) in docker forum

### Project version(s) affected

   Docker Cloud's infrastructure
### Suggestions for a fix

I have no idea sadly

**Comment by puittenbroek** [comment]
Any update on this? We're experiencing this bug as well.

**Comment by javiersvg** [comment]
Not here nor in stackoverflow sadly. I think I will be create my containers with travis.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
