### ISSUE TITLE
Update required to documentation for changing docker_gwbridge IP address

### ISSUE THREAD

**Issue by ctelfer** [docker/docker.github.io#6685]
### Problem description

The documentation for changing the IP address of the docker_gwbridge network is out of date for current versions of docker.  This showed up recently with https://github.com/moby/moby/issues/37018.

### Problem location

I saw a problem on the following URL: https://success.docker.com/article/how-do-i-change-the-docker-gwbridge-address

### Project version(s) affected

I'm not certain at which versions of engine the behavior changed requiring this fix.  It certainly affects the 18.03 versions of engine.

### Suggestions for a fix

As per  https://github.com/moby/moby/issues/37018, the docs need to describe how the node must leave the cluster and rejoin in order to properly change the IP addresses.  There should already be a documentation fix in progress to address this.

**Comment by tfoxnc** [comment]
The fix is in https://github.com/docker/kbase/pull/927, but see my comment to Trap about version numbers.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
