### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by davidwmartines** [docker/docker.github.io#6686]
from https://github.com/docker/for-win/issues/new

clicked on link in issue template:  https://docs.docker.com/docker-for-win/troubleshoot

**Comment by gbarr01** [comment]
Hi, @davidwmartines , the link you say is broken is not referenced in the docs. From the `docker.github.io repo`, this command ... `grep -ri --include=".*.md" "docker-for-win/troubleshoot"` ... yields no results.  

Please provide more info if you still believe there is broken link.
