### ISSUE TITLE
the "scheduler" option is enabled be default, the doc says false by default

### ISSUE THREAD

**Issue by ftsiadimos** [docker/docker.github.io#6692]
File: [ee/ucp/admin/configure/ucp-configuration-file.md](https://docs.docker.com/ee/ucp/admin/configure/ucp-configuration-file/)

The documentation says the "scheduler" option is false by the default when I check in the WebUI Admin Settings >>  Scheduler the option is enabled
------------------------------------------------
enable_admin_ucp_scheduling | no | Set to true to allow admins to schedule on containers on manager nodes. The default is false.
-- | -- | --

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
