### ISSUE TITLE
Clarify whether whitespace is allowed before comments in Dockerfile

### ISSUE THREAD

**Issue by andymadge** [docker/docker.github.io#6700]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

The page says:

> Docker treats lines that begin with # as a comment

Does that mean that whitespace is allowed before the the # ? I've tested and it does seem to be allowed, but the docs are ambiguous.

The same page states clearly that in a .dockerignore file, the # must be in column 1,. Therefore presumably the lack of similar statement about Dockerfile comments means they are different.

As use case for this would be comments inside indented multi-line RUN commands.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
