### ISSUE TITLE
Remove mention of tested notary binaries vs. non-tested

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#6714]
File: [notary/getting_started.md](https://docs.docker.com/notary/getting_started/)

True or not, `Windows is not officially tested, but if you are a developer and Windows user, we would appreciate any insight you can provide regarding issues.` isn't necessarily something that is necessary in the docs to understand.  If it is mentioned in the `notary` repository, fine but I am not sure that makes sense to actually have in our docs.

/cc @millerdz

**Comment by gbarr01** [comment]
Hi, @mbentley , this should be fixed by #6714
