### ISSUE TITLE
[Errno 2] No such file ... 'requirements.txt'

### ISSUE THREAD

**Issue by sloughin** [docker/docker.github.io#6729]
File: [compose/django.md](https://docs.docker.com/compose/django/)

I had to make the following change to the example Dockerfile to get it to run, otherwise I got the error in the subject line.

    FROM python:3
    ENV PYTHONUNBUFFERED 1
    RUN mkdir /code
    ADD requirements.txt /code/
    RUN pip install -r /code/requirements.txt
    ADD . /code/

The line beginning with RUN pip install had been
    RUN pip install -r requirements.txt

which was causing the file-not-found error.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
