### ISSUE TITLE
boot2docker problem in docker toolbox

### ISSUE THREAD

**Issue by ThinhVu** [docker/docker.github.io#6731]
### Problem description
1. **boot2docker.iso** shipped with **docker toolbox installer** is **out-of-date**.
2. Docker toolbox installer doesn't copy **boot2docker.iso** from **C:\Program Files\Docker Toolbox** to **C:\Users\{username}\.docker\machine\cache** when user install Docker Toolbox. One must copy this iso manually (it'll be very bad if they doesn't know that).

The problem is on the first **Docker QuickStart Terminal** run, it always display an error that it doesn't found boot2docker iso or this file is out-of-date and trying to get latest boot2docker.iso from github.

I wonder why:
1. You guys put boot2docker.iso in DockerToolbox installer file, make installer size larger for nothing.
2. No directly link to download latest boot2docker.iso from http://boot2docker.io/.
There is a link to download boot2docker.iso but when user click to this link, it open a github page which show a lot of version of Docker for Window Installer.
The actualy boot2docker download link is: https://github.com/boot2docker/boot2docker/releases
But what ppl got: https://github.com/boot2docker/windows-installer/releases

3. boot2docker from github take very long time to download (don't know it's connection problem or not).

Help you guy fix these issue to make it easier for new commer.

**Comment by gbarr01** [comment]
Hi, @ThinhVu , this is not a docs issue so I am going to close. 

Please report Toolbox issues here: https://github.com/docker/toolbox
