### ISSUE TITLE
Mandatory variable syntax in docker-compose.yml is strictly docker 18.04+

### ISSUE THREAD

**Issue by jamiejackson** [docker/docker.github.io#6732]
### Problem description

Docs don't specify that the mandatory variable syntax, `${MYVAR:?}` [doesn't work for `docker stack` until docker version 18.04](https://github.com/docker/cli/pull/893). 

### Problem location

https://docs.docker.com/compose/compose-file/#variable-substitution

### Suggestions for a fix

Add a note.

----

# References:

* https://github.com/docker/compose/issues/5683

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
