### ISSUE TITLE
Regex `algorithm` wrong

### ISSUE THREAD

**Issue by robertlacroix** [docker/docker.github.io#6736]
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/#content-digests)

The grammar for `algorithm` seems wrong.

```
algorithm   := /[A-Fa-f0-9_+.-]+/
```

doesn't match the example `sha256`.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
