### ISSUE TITLE
Up until now, you have been using Docker in a single-host mode on your local machine

### ISSUE THREAD

**Issue by cnrmck** [docker/docker.github.io#6737]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

I found this part confusing: 
>Up until now, you have been using Docker in a single-host mode on your local machine. But Docker also >can be switched into swarm mode

My thought was, "wait, didn't I already use swarm mode in the last section?" 

So, I went back and checked. Sure enough, already ran this command from [here](https://docs.docker.com/get-started/part3/#run-your-new-load-balanced-app)
![image](https://user-images.githubusercontent.com/22061955/40328702-8bd7fa60-5d04-11e8-81df-b2117c61c977.png)

Unless this is a different type of swarm, then I recommend removing or rephrasing the "Up until now, you have been using Docker in a single-host mode on your local machine." sentence for clarity sake.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
