### ISSUE TITLE
Please explain why running in detached mode is a thing...

### ISSUE THREAD

**Issue by rowild** [docker/docker.github.io#6741]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

I am daring to add my 2 cents here: 
As a total beginner of Docker (and DevOp in general, for that matter), I was wondering, why running in detached mode is a thing. Maybe it will be explained in a later step of the tutorial, but I think it would be a rather good idea to either add a little explanation or a link to the page, where the advantage/use case of detached mode is explained.

Thank you!

PS: Also, the video on that page (in the bottom) does not work (Chrome 66, Mac OSX 10.12)

**Comment by rowild** [comment]
Thank you very much for your excellent explanation! Makes total sense :-)
This must be in the docu! :-)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
