### ISSUE TITLE
unable to ping host from containers and vice versa with macvlan and sub-interface

### ISSUE THREAD

**Issue by joshlingard** [docker/docker.github.io#6745]
My host network is in 172.19 subnet with an ip of 172.19.1.10. I want to have container1 with ip address 172.19.1.30 and container2 with ip address 172.19.1.31.
My requirement for the host and container is that host needs to ping the ip address of the container and it needs to also ping 8.8.8.8 and containers needs to ping each other along with the host’s ip and 8.8.8.8. Also, my other requirement is that host and containers’ ip need to have ssh access from other hosts (172.19.1.11/172.19.1.12/172.19.1.13)

The solution that I have attempted till now is I created a macvlan1 network inside the host(172.19.1.10)
Docker network create -d macvlan --subnet=172.19.1.0/24 --gateway=172.19.1.1 -0 parent=eth1 macvlan1
Then I created two containers inside the host
Docker run -itd --net=macvlan1 --name=container1 --ip=172.29.1.30 centos7:latest /bin/bash
Docker run -itd --net=macvlan1 --name=container2 --ip=172.29.1.31 centos7:latest /bin/bash

Now my host (172.19.1.10) can ping 8.8.8.8
My container1 (172.19.1.30) can ping 172.19.1.31 and 8.8.8.8
My container2(172.19.1.31) can ping 172.19.1.30 and 8.8.8.8 
Host and both of my containers have ssh access from other hosts(172.19.1.11/172.19.1.12/172.19.1.13).

The only remaining requirement that I have is 
host(172.19.1.10) can not ping 172.19.1.30 and 172.19.1.31 
container1(172.19.1.30) cannot ping the host(172.19.1.10)
container2(172.19.1.31) cannot ping the host(172.19.1.10)
So probably this was the restriction of macvlan and docker documentation suggests to create a sub-interface if the connection is still required between hosts and containers.
So I created sub-interface with macvlan as
Docker network create -d macvlan --subnet=192.168.2.0/16 --gateway=192.168.1.1 -o parent=eth1.1 macvlan2
Ip link add mymacvlan2 link eth1.1 type macvlan mode bridge
Ip addr add 192.168.2.10/24 dev mymacvlan2
Ifconfig mymacvlan2 up
Still I am having the same problem where I cannot ping containers from host and ping host from containers.

I also tried as it was suggested in this https://sreeninet.wordpress.com/2016/05/29/docker-macvlan-and-ipvlan-network-plugins/ and creating containers with the sub-interface ip but then I couldn't ssh into 192 address from other 172 address and I cannot ping host and container too.

Can someone help me out.

Thanks

**Comment by gbarr01** [comment]
Hi, @joshlingard , this doesn't appear to be a docs issue. Can you please ask your question on the forums? https://forums.docker.com/
