### ISSUE TITLE
Please disable "smooth scroll"

### ISSUE THREAD

**Issue by idontusenumbers** [docker/docker.github.io#6750]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

The smooth scrolling behavior on this page (and probably all other pages) is exceedingly frustrating.

1. It slows down accessing the information users are looking for
2. It is disorienting
3. It is forcing behavior upon the user which they already have control over through their user agent/OS
4. The script needlessly increases the size and complexity of the code behind the site

On top of this, I see no actual benefit.

Personally, I have explicitly disabled it at an OS and browser level.

**Comment by mhsmith** [comment]
I don't object to the smooth scrolling per se, but it takes far too long to get to its destination (feels like a full second), which needlessly breaks your train of thought.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by idontusenumbers** [comment]
What refactor? Does the refactor entail explicitly excluding smooth-scroll?

**Comment by mhsmith** [comment]
It looks to me like the smooth scroll is already gone.
