### ISSUE TITLE
Healthcheck fail fast feature during container start up

### ISSUE THREAD

**Issue by petr-ujezdsky** [docker/docker.github.io#6751]
### Problem description

Current [`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) command does not allow some sort of _fail fast_ functionality.

Let's assume some big web app that typically starts up in about 10 minutes. The following config seems to be your suggestion given the documentation:

Dockerfile:
```
HEALTHCHECK --interval=10s --timeout=3s --start-period=10m\
  CMD curl -f http://localhost/ || exit 1
```

Now imagine that due to some configuration error the app deploy fails 15s after the docker is run. The web server (Tomcat, Jboss etc.) continue to run though, so the docker container stays up.
Then I would have to wait approx. 10 minutes to know that something went wrong.

### Suggestions for a fix

Maybe implement third state among the current two

- 0: success - the container is healthy and ready for use
- 1: unhealthy - the container is not working correctly

to indicate the startup stage. Or to indicate some critical unrecoverable failure, that marks container unhealthy even within the `--start-period` period.

Or do not reinvent the wheel and use [2 different healthchecks](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) like the Kubernetes.

**Comment by gbarr01** [comment]
Hi, @petr-ujezdsky , this issue doesn't appear to address a docs bug. Would you please ask you question on the forums? Thanks. https://forums.docker.com/
