### ISSUE TITLE
ports documentation is incomplete

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [docker/docker.github.io#6756]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/#ports)

The short syntax includes examples like the below, where an ip address is specified, however the documentation does not indicate what the ip address is for, nor does it indicate in the long format how one would accomplish the same thing, IE would it be added to published?

```
ports:
 - "3000"
 - "3000-3005"
 - "8000:8000"
 - "9090-9091:8080-8081"
 - "49100:22"
 **- "127.0.0.1:8001:8001"
 - "127.0.0.1:5000-5010:5000-5010"**
 - "6060:6060/udp"
```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by dhilgarth** [comment]
I just wanted to open the same issue. The documentation is really missing this information and therefore, this issue should be re-opened.
