### ISSUE TITLE
Improve registry docs about garbage collection

### ISSUE THREAD

**Issue by harridu** [docker/docker.github.io#6762]
File: [registry/garbage-collection.md](https://docs.docker.com/registry/garbage-collection/)
The document states clearly "You should ensure that the registry is in read-only mode or not running at all", but it doesn't tell how this could be achieved.  It doesn't actually tell how to run the garbage collector in the registry, either (using docker commands).

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
