### ISSUE TITLE
api changes links not working

### ISSUE THREAD

**Issue by krasi-georgiev** [docker/docker.github.io#677]
see the image for the links reference.
http://screencast.com/t/AMrZRDCY

these do nothing when clicked due to an anchor spelling error

**Comment by johndmulhausen** [comment]
@krasimir-georgiev What URL is this?

**Comment by krasimir-georgiev** [comment]
just an online screenshot sharing.

**Comment by johndmulhausen** [comment]
Yes, but what URL where you at when the screenshot was taken? I don't know what page you were on. :)

**Comment by krasimir-georgiev** [comment]
ah sorry , small confusion.

this one.
https://docs.docker.com/engine/reference/api/docker_remote_api/ <https://docs.docker.com/engine/reference/api/docker_remote_api/>

**Comment by johndmulhausen** [comment]
Self-assigning; these pages will be wiped out when #606 merges, will close then.
