### ISSUE TITLE
Please add reference.

### ISSUE THREAD

**Issue by shimada123** [docker/docker.github.io#6774]
### Problem description
I could not find how to install Docker to deployed Amazon Linux environment,
I tried to install Docker reffering to this page(https://docs.docker.com/install/linux/docker-ce/centos/).
But i failed the following step 'Set up the repository>1.Install required packages'.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL:https://docs.docker.com/docker-for-aws/

### Suggestions for a fix

I could not find how to install Docker to deployed Amazon Linux environment,
I tried to install Docker reffering to this page(https://docs.docker.com/install/linux/docker-ce/centos/).
But i failed the following step 'Set up the repository>1.Install required packages'.

**Comment by gbarr01** [comment]
@shimada123 , it should be straightforward. Please try this: 

```
sudo yum install -y yum-utils device-mapper-persistent-data lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install docker-ce
sudo systemctl start docker
sudo docker run hello-world
```



```
$ sudo docker version

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
