### ISSUE TITLE
Please clarify that this is for Linux containers

### ISSUE THREAD

**Issue by jasonbivins** [docker/docker.github.io#6780]
File: [engine/reference/commandline/checkpoint.md](https://docs.docker.com/engine/reference/commandline/checkpoint/)

on my Windows environment, i get this error message when using Windows containers
Tested with both CE and EE versions

`C:\Users\DockerJ>docker checkpoint create Tester checkpoint1
Error response from daemon: Cannot checkpoint container Tester: Windows: Containers do not support checkpoints`

**Comment by gbarr01** [comment]
@jasonbivins , two questions: 

- Are you using API version 1.25 or higher? Run `docker version`.
- Do you have experimental set to true? See https://docs.docker.com/docker-for-windows/#daemon

My guess is that you have experimental set to off. See the top of the [checkpoint page](https://docs.docker.com/engine/reference/commandline/checkpoint/) for caveats.

**Comment by jasonbivins** [comment]
@gbarr01    I checked that before I posted :)

`C:\Users\Administrator>docker version
Client:
 Version:       17.06.2-ee-11
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    06fc007
 Built: Thu May 17 06:14:39 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-11
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   06fc007
  Built:        Thu May 17 06:17:26 2018
  OS/Arch:      windows/amd64
  Experimental: true
`

**Comment by gbarr01** [comment]
Oh hang on, I see. You are using _Windows_ containers. Sorry about that. I need to think about how best to handle the docs. Editing the CLI reference docs is probably not the best solution.

**Comment by jasonbivins** [comment]
Is there a better place to send requests like this?

**Comment by gbarr01** [comment]
Not necessarily. We need to clarify CLI limitations (if they exist) for Windows containers. But if you need help now, you could ask on the [Docker forums](https://forums.docker.com/) or Stackoverflow, of course.

**Comment by gbarr01** [comment]
@thaJeztah , @gtardif , do you know about CLI limitations for Windows containers?

**Comment by thaJeztah** [comment]
In this case, it's an experimental feature that uses CRIU, which is a Linux only feature.

Not related to the Windows side of things, but checkpoint/restore currently has some issues due to the migration to containerd, and will get a major overhaul in future.

What _should_ be done though, is that the CLI hides these commands if the daemon is running on Windows; I think we do so for some other commands (likely we didn't do that yet when this feature was implemented)

**Comment by thaJeztah** [comment]
Opened https://github.com/docker/cli/pull/1094 to address this

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
