### ISSUE TITLE
Interactive problems in the process of constructing Image using Dockerfile

### ISSUE THREAD

**Issue by lkalbert001** [docker/docker.github.io#6783]
### Problem description

Dear lady/gentleman，
I prompted to enter area information when I am building r-base image through Dockerfile.
But it doesn't work after input.
I want to know how to deal with the information interaction in the process of images construction ?
Looking forward to your reply.

Problem PrintScreen：
![3a00a40f6e5e1140cb9628e9939f55ba](https://user-images.githubusercontent.com/34129931/40704059-b8b3c278-6419-11e8-985d-ea52b28a2f85.jpg)

Dockerfile：
![11](https://user-images.githubusercontent.com/34129931/40704064-bf78ce00-6419-11e8-90da-a6da910352ef.JPG)

**Comment by gbarr01** [comment]
Hi, @lkalbert001 , the `R` docs could use more information but that could take a while. Please ask your question in the [Docker forums](https://forums.docker.com/) or on [Stackoverflow](https://stackoverflow.com/).

**Comment by gbarr01** [comment]
For internal reference: https://docs.docker.com/samples/library/r-base/

**Comment by lkalbert001** [comment]
Thanks for your reply. Now I known what has happenned . It just needs to set the 'tzdata' before doing this.
