### ISSUE TITLE
Resources not compatible with version 3 files using docker stack deploy!

### ISSUE THREAD

**Issue by Nicbyte** [docker/docker.github.io#6784]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)
Hi

When using v3 of the docker compose file you cannot specify the resources bits as per your documentation. If you specify the resources and try to use the docker stack deploy commands it wont work!
I got my example working fine removing the resources bits from your example. 

My Environment info:

Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false

Regards

**Comment by gbarr01** [comment]
@Nicbyte , this seems strange given your version (17.12.0). Can you provide any other info? The command history, for example.

**Comment by Nicbyte** [comment]
Hi, 

I'm trying to mimic your Documentation in my compose file but I keep getting and error on the line where I have the "resource:" part. 

hope this helps explain the scenario. 

""version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: username/repo:tag
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
""


_admin@DSHackDockerVM:~$ cat dockerfile/docker-compose.yml
version: "3"
services:
  web:
    image: centos-hp2mpg:v0.1
    deploy:
      replicas: 3
#      resources:
#       limits:
#         cpus: "0.1"
#         memory: 50M
      restart_policy:
        condition: on-failure
    ports:
     - "80:5001"

_admin@DSHackDockerVM:~$ sudo vi dockerfile/docker-compose.yml
_admin@DSHackDockerVM:~$ cat dockerfile/docker-compose.yml
version: "3"
services:
  web:
    image: centos-hp2mpg:v0.1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
     - "80:5001"


capitec_admin@DSHkDockerVM:~$ sudo docker stack deploy -c dockerfile/docker-compose.yml test_api
yaml: line 7: found character that cannot start any token
_admin@DSHkDockerVM:~$
_admin@DSHkDockerVM:~$ sudo vi dockerfile/docker-compose.yml
_admin@DSHkDockerVM:~$
_admin@DSHkDockerVM:~$ cat dockerfile/docker-compose.yml
version: "3"
services:
  web:
    image: centos-hp2mpg:v0.1
    deploy:
      replicas: 3
#      resources:
#       limits:
#         cpus: "0.1"
#         memory: 50M
      restart_policy:
        condition: on-failure
    ports:
     - "80:5001"

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
