### ISSUE TITLE
Docker container not able to communicate to SQL server

### ISSUE THREAD

**Issue by VijayPatel1** [docker/docker.github.io#6785]
I have two ASP.NET Core 2.0 application "App A" and "App B".
App A is the hosted in Host machine IIS and communicate with SQL server to get data from database.
App B is deployed in Docker container and communicate with App A. But I am getting error when App A is trying to establish connection with MS SQL server and giving error like below:

"Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'"

When I create user 'NT AUTHORITY\ANONYMOUS LOGON' in SQL server then it is able to communicate correctly and getting data from the database.

Can you please suggest why it is required the 'NT AUTHORITY\ANONYMOUS LOGON' user under SQL server? Can we have connection without this user creation?

**App B Docker File**:

FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY ./DeployPackage .
ENTRYPOINT ["dotnet", "AppB.dll"]

**App B Docker-Compose File:**

version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: tscon
    ports:
      - "80:80"

**Comment by gbarr01** [comment]
Hi, @VijayPatel1 , this doesn't appear to be a docs issue. Would you please ask your question on the forums? https://forums.docker.com/  Thank you!
