### ISSUE TITLE
Incorrect subtitles

### ISSUE THREAD

**Issue by kencplee** [docker/docker.github.io#6787]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

Just found a little mistake in the section of "Build the App", "Troubleshooting for Linux users", the subtitles for proxy and DNS configuration are mismatched.

![image](https://user-images.githubusercontent.com/3761764/40738427-217e8426-6476-11e8-92c6-3122967de649.png)

**Comment by gbarr01** [comment]
Thanks, @kencplee . Yes, and the use of `ENV` also needs to be changed. Coming soon.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
