### ISSUE TITLE
FRESH INSTALL - kubectl does not run, its missing its config file? 

### ISSUE THREAD

**Issue by nigel-dewar** [docker/docker.github.io#6789]
fresh install here, enabled kubernetes. 

I can run kubectl and this works,

but trying to run kubectl get nodes results in the following error.

PS C:\> kubectl get nodes
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
PS C:\>

So I did a 
PS C:\> kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []

and got nothing.

It seems that kubernetes is not setup properly and missing its config file??? How come this is not working, was this supposed to be setup with the install or I am supposed to do this. Secondly, where is the KUBECONFIG file located anyway on my windows 10 machine?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
