### ISSUE TITLE
Launch Docker as administrator

### ISSUE THREAD

**Issue by carl-ashby** [docker/docker.github.io#6791]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)

I'd suggest suggesting that you launch Docker with elevated permissions using the Run-As-Administrator command. I was unable to run any docker builds due to "level=error msg="failed to dial gRPC: unable to upgrade to h2c, received 500". Running as administrator solved this.

**Comment by jvanlangen** [comment]
Even running as administrator, this error will still occur (here)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
