### ISSUE TITLE
conflicting statements - Kubernetes support on Mac Docker CE

### ISSUE THREAD

**Issue by dansayo** [docker/docker.github.io#6795]
File: [get-started/index.md](https://docs.docker.com/get-started/)
> For full Kubernetes Integration
> Kubernetes on Docker for Mac is available in 17.12 Edge (mac45) or 17.12 Stable (mac46) and higher.
> 

[source](https://docs.docker.com/docker-for-mac/kubernetes/)
> Kubernetes is only available in Docker for Mac 17.12 CE Edge and higher, on the Edge channel. Kubernetes support is not included in Docker for Mac Stable releases.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
