### ISSUE TITLE
A potential error in the documentation.

### ISSUE THREAD

**Issue by yakom** [docker/docker.github.io#6797]
Hello!

File: [engine/security/https.md](https://docs.docker.com/engine/security/https/).

At the end of the _Create a CA, server and client keys with OpenSSL_ section there is a box titled _Run it on the client machine_ which says 

> This step should be run on your Docker client machine. As such, you need to copy your CA certificate, your server certificate, and your client certificate to that machine.

 Do we really need to copy the server certificate if, from what I know, the server is going to present it during the TLS handshake? It should rather say _the client key_ which does need to be copied, as said in the line above and shown in the subsequent example?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
