### ISSUE TITLE
Feedback for: machine/get-started-cloud.md

### ISSUE THREAD

**Issue by fernandezcuesta** [docker/docker.github.io#681]
File: [machine/get-started-cloud.md](https://docs.docker.com/machine/get-started-cloud/)

Link on "Drivers for cloud providers" section (pointing to https://docs.docker.com/drivers/) doesn't work, the one in the "Where to go next" section does (https://docs.docker.com/machine/drivers/).

**Comment by sanscontext** [comment]
@fernandezcuesta thanks for the report. This looks like this is fixed now, and we're working on adding link-checking to our CI tests.
