### ISSUE TITLE
Change url for docker-volume-glusterfs

### ISSUE THREAD

**Issue by tcoupin** [docker/docker.github.io#6811]
File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/)

https://github.com/calavera/docker-volume-glusterfs is no more maintained
Can you update the page with one of fork ? 
ex: https://github.com/amarkwalder/docker-volume-glusterfs

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
