### ISSUE TITLE
kubectl not installed as part of EE

### ISSUE THREAD

**Issue by yongshin** [docker/docker.github.io#6818]
Technically kubectl is not installed as part of the EE engine or UCP as described in the docs here around Kubernetes CLI tools: https://docs.docker.com/ee/#use-the-kubernetes-cli. The customer would need to download the kubectl CLI manually, it would be nice to put instructions on how to do this here. 

File: [ee/index.md](https://docs.docker.com/ee/)

**Comment by joaofnfernandes** [comment]
You can find that information here - https://docs.docker.com/ee/ucp/user-access/kubectl/

**Comment by yongshin** [comment]
Sure but it says explicitly on these docs that kubectl is installed as part of EE. Could we remove that @joaofnfernandes

**Comment by joaofnfernandes** [comment]
ups.. if that's the case I'll tweak the sentence that says that.
