### ISSUE TITLE
Feedback for: engine/userguide/storagedriver/device-mapper-driver.md

### ISSUE THREAD

**Issue by czka** [docker/docker.github.io#682]
File: [engine/userguide/storagedriver/device-mapper-driver.md](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/)

> Currently, the following distributions support the driver:

Please count Arch Linux in :).

**Comment by czka** [comment]
> Truncate data file to the size of the metadata file (**approximage** 200GB).

Did you mean mean **approximate**?

**Comment by mstanleyjones** [comment]
I found that you are correct about Arch Linux: https://wiki.archlinux.org/index.php/Docker
