### ISSUE TITLE
Incorrect formatting for TOML UCP config file

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#6827]
File: [ee/ucp/admin/configure/integrate-with-multiple-registries.md](https://docs.docker.com/ee/ucp/admin/configure/integrate-with-multiple-registries/)

The value of `host_address = $dtr_host_address` needs to be in quotes; it should be `host_address = "$dtr_host_address"`

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
