### ISSUE TITLE
config.json location

### ISSUE THREAD

**Issue by kostapsimoulis** [docker/docker.github.io#6830]
File: [engine/userguide/networking/index.md](https://docs.docker.com/engine/userguide/networking/)

Issue in page:
https://docs.docker.com/v17.09/engine/userguide/networking/

I believe the location of config.json should be ~/.docker/config.json instead of ~/.config.json

According to documentation on https://docs.docker.com/network/proxy/

In Docker 17.07 and higher, you can configure the Docker client to pass proxy information to containers automatically.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
