### ISSUE TITLE
documentation: supervisord should be run with nodaemon

### ISSUE THREAD

**Issue by datvong-wm** [docker/docker.github.io#6835]
File: [config/containers/multi-service_container.md](https://docs.docker.com/config/containers/multi-service_container/)

The documentation example should be
CMD ["/usr/bin/supervisord", "--nodaemon"]

Or should mention nodaemon in the config.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by dropsonic** [comment]
Faced the same issue today. Official example doesn't work without "nodaemon" option.
