### ISSUE TITLE
Example section HTTPS_PROXY should use http:// protocol

### ISSUE THREAD

**Issue by Nopius** [docker/docker.github.io#6837]
File: [network/proxy.md](https://docs.docker.com/network/proxy/)

Usually proxy protocol used for all tunneled protocols is either socks or http (at least in most command line tools that support environment variables to detect proxy), so for HTTPS_PROXY it should look like:
ENV HTTPS_PROXY "http://127.0.0.1:3001", (NOT "https://127.0.0.1:3001"). Sure I admit that it's possible to have HTTP proxy running on HTTPS port, but in most implementations it's just a plain HTTP with CONNECT capability.
The same applies to FTP_PROXY. It's not possible to proxy FTP with ftp:// protocol.

I have tested docker configuration with ENV HTTPS_PROXY "http://127.0.0.1:3001" and it works well.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
