### ISSUE TITLE
lvm-direct in a existing VG -- add in documentation 

### ISSUE THREAD

**Issue by publicocean0** [docker/docker.github.io#6838]
### Problem description

in the documentation it is not clear using lvm-direct 
1) if in container i map a volume to a host path placed in a VG different from docker VG  it is ok? This is important for understanding if i can handle easy the volume size also if in advance (when i install docker)i cant know the real volume sizes(using a second partition). For example if in docker i install a container mongodb using a db size 200gb  i need forecely to use VG docker bigger than 200gb or i can mount container  db volume in a path associated to a different disk (or lv not included in docker vg)  where have huge space?
2) lvm-direct uses a volume group   inside a physical partition. In the example it is explictely written to use a physical device block with vg 'docker'. It is not clear if docker can use also a existing VG with other LV present for example. If the answer is no to previous question, it is not clear if adding a second VG in the same phisical device it is OK. 
These clarification can help to manage better volumes in the real cases

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
