### ISSUE TITLE
No stable package for Fedora 28 (x86_64 or aarch64)

### ISSUE THREAD

**Issue by jwbowen** [docker/docker.github.io#6841]
### Problem description
There is no **stable** package for Fedora 28.

### Problem location

https://download.docker.com/linux/fedora/28/x86_64/stable/Packages/
https://download.docker.com/linux/fedora/28/aarch64/stable/Packages/

### Project version(s) affected
Current **stable** Fedora Linux repos. There are packages for Fedora 28 for the **test**, **edge**, and **nighly** repos.

### Suggestions for a fix
Is Docker CE simply not considered stable on Fedora 28? If it is, it would be nice to have a package in the `linux/fedora/28/$basearch/stable repos`.

### Other notes
[Get Docker CE for Fedora ](https://docs.docker.com/install/linux/docker-ce/fedora/) still lists Fedora 26, which reach end-of-life on June 1, 2018. Fedora 27 and 28 are the currently supported versions.

[Unsupported Fedora Releases](https://fedoraproject.org/wiki/End_of_life)

**Comment by thaJeztah** [comment]
Packages are available now on the stable channel as well
