### ISSUE TITLE
Mismatching docker-compose.yml mapped port and localhost port.

### ISSUE THREAD

**Issue by ghost** [docker/docker.github.io#6853]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)

Error on the docu.

In the docker-compose.yml code, the 80 "internal" port of the service is mapped to the 4000 external port on localhost

```
 ports:
      - "4000:80"
```
A few lines after, the documentation says:

> You can run curl -4 http://localhost several times in a row, or go to that URL in your browser and hit refresh a few times."

The documentation needs to indicate the 4000 port on the curl parameter.

`curl -4 http://localhost:4000`

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
