### ISSUE TITLE
Update `name_to_handle_at` syscall capability gate to `CAP_DAC_READ_SEARCH` 

### ISSUE THREAD

**Issue by nvcastet** [docker/docker.github.io#6854]
As mentioned by @justincormack  in issue moby/moby#37242:
`name_to_handle_at` syscall capability needed to be updated to "Already gated by `CAP_DAC_READ_SEARCH`."

File: [engine/security/seccomp.md](https://docs.docker.com/engine/security/seccomp/)

**Comment by thaJeztah** [comment]
ping @justincormack PTAL
