### ISSUE TITLE
I found broken links

### ISSUE THREAD

**Issue by myralucy** [docker/docker.github.io#6856]
Several links are broken in the section "Create your swarm" of [this page](https://docs.docker.com/v17.09/get-started/part6/#create-your-swarm).
For example, the link to ["automatically create a swarm on AWS".](https://docs.docker.com/v17.09/docker-cloud/cloud-swarm/create-cloud-swarm-aws/)

**Comment by L-Hudson** [comment]
two versions back. Current version is corrected. Closing.
