### ISSUE TITLE
Requesting change to devicemapper doc

### ISSUE THREAD

**Issue by jeliyo** [docker/docker.github.io#6863]
File: [storage/storagedriver/device-mapper-driver.md](https://docs.docker.com/storage/storagedriver/device-mapper-driver/)

> devicemapper storage driver is the only supported storage driver for Docker EE and Commercially Supported Docker Engine (CS-Engine) on RHEL, CentOS, and Oracle Linux

I believe this should be changed as we now support multiple storage drivers. I believe our preference is `overlay2`

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
