### ISSUE TITLE
Docker Security issue!

### ISSUE THREAD

**Issue by lkalbert001** [docker/docker.github.io#6865]
### Problem description
**How to enable " docker run" to mount only files or folders that the user has permission to**. Otherwise, the user can modify or delete files or folders that only root has permission. Whether it is intentional or unintentional, this is very dangerous.

Just like it. It will delete all files in /mnt. 
`docker run -it -v /sbin/:/mnt ubuntu:14.04 rm -rf /mnt/`

**Comment by thaJeztah** [comment]
Yes this is known, and documented; having access to the remote API is equal to having root access on the host; for that reason it's important to secure access to the API.

Additional security measures, such as role-based access control are possible, but not part of a standard Docker CE installation (Docker Enterprise Edition provides role-based access control).

This atrack vector is described in the security section of the documentation; https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface

**Comment by lkalbert001** [comment]
@thaJeztah Thank you for your reply. 
And I hope the Docker CE has also the function of role-based access control like Docker EE, even if it is free.
This is a latent danger for users who are beginners of Docker. 
Best wished to your Docker organization!

**Comment by thaJeztah** [comment]
You can add restrictions through authorization (authz) plugins, which are supported by Docker CE, but full access control requires various components that are out of scope for the Docker daemon itself, and part of the EE platform (there's some third party solutions as well)

Let me go ahead and close this issue, but feel free to continue the conversation

**Comment by lkalbert001** [comment]
Thank you！I think I should study kubernetes first. I learnt that k8s has the function of RBAC. Very grateful for your help.
