### ISSUE TITLE
Add warning header for older/archived pages

### ISSUE THREAD

**Issue by RomainBelorgey** [docker/docker.github.io#6876]
### Problem description
A warning is visible when accessing https://docs.docker.com/v17.09/

But when accessing directly a page (ex : https://docs.docker.com/v17.09/datacenter/ucp/2.2/guides/admin/configure/use-a-load-balancer/) there is no more warnings.

Got an issue with a customer following https://docs.docker.com/v17.09/datacenter/ucp/2.2/guides/admin/configure/use-a-load-balancer/ instead of https://docs.docker.com/ee/ucp/admin/configure/join-nodes/use-a-load-balancer/#load-balancing-ucp-and-dtr 

It can be also confusing for EE customers because there are not using 17.09 engine version.

### Problem location

All archived pages.

### Suggestions for a fix

Add a warning header.

**Comment by L-Hudson** [comment]
Just ran into this same problem myself. Moving to Backlog.

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
