### ISSUE TITLE
Reference to cloud.docker.com

### ISSUE THREAD

**Issue by ScottFred** [docker/docker.github.io#6879]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

This Getting Started Guide, Part 2, says to create an account on https://cloud.docker.com which was shut down on 24 May 2018.  This needs to be updated.  I would assume that since this section of the tutorial is only referring to the Docker Repository, this could simply be changed to reference creating an account on https://hub.docker.com

**Comment by joaofnfernandes** [comment]
Fixed via #6886
