### ISSUE TITLE
Feedback for: engine/reference/glossary.md

### ISSUE THREAD

**Issue by sanscontext** [docker/docker.github.io#688]
File: [engine/reference/glossary.md](https://docs.docker.com/engine/reference/glossary/)

Filing this so I don't forget a third time - we don't explain what a "bridge" network is in the glossary, even though it's referenced a lot in other docs. I had to search in the doc for "bridge" and then ctrl + f over a few tabs to find the description and confirm the definition.

**Comment by mstanleyjones** [comment]
Closing this issue because the PR is in another repo. Please follow along there.
