### ISSUE TITLE
Postgresql issue in Windows 10

### ISSUE THREAD

**Issue by nmlbio** [docker/docker.github.io#6884]
We have developed a Docker-Galaxy based on [the original docker-galaxy created by Dr. Grüning](https://github.com/bgruening/docker-galaxy-stable).  our customization was mainly about installing more tools from the toolshed as well as updating the existing tools. We also added some genome data for tools such as deeptools, GATK, etc. Our docker-galaxy runs well on both Mac and Ubuntu boxes, but failed on Windows 10 computers due to its inability to start Postgresql (postgresql abnormal termination)---underlying database inaccessible, very likely some kind of permission issue (we are admin of the computers). We have tried a few things but so far no luck.  We have also noticed several mentionings of the similar Postgresql problems in Windows on the web.   We hope the issue will be looked at by the docker team.  Many thanks!

YC

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
