### ISSUE TITLE
missing config document of docker-compose ulimits

### ISSUE THREAD

**Issue by dlintw** [docker/docker.github.io#6887]
### Problem description
missing config document of docker-compose ulimits

### Problem location

- I saw a problem on the following URL:  https://docs.docker.com/compose/compose-file/#ulimits

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/compose/compose-file/#ulimits

- Other: 

It is require to listing all possible keywords in the document.

### Project version(s) affected

Docker version 18.04.0-ce, build 3d479c0af6

### Suggestions for a fix

valid keyword are:
nofile: ...
core_dump_size:...
...

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
