### ISSUE TITLE
[docs] no community edition in "Product Manuals"

### ISSUE THREAD

**Issue by pmacko1** [docker/docker.github.io#6889]
File: [ee/index.md](https://docs.docker.com/ee/)

**Comment by joaofnfernandes** [comment]
Thanks for the feedback!

You can find information about docker CE on the main page https://docs.docker.com/
I'm going to close this issue since I think things should stay the way they are.

**Comment by pmacko1** [comment]
Thanks for taking time to respond, Joao. My pov was that all docs should be accessible and visible from one place if you know where im coming from. I had to blindly try different sections looking for CE. Sugg: put reference in product manuals->Open Source projects?  Cheers!

**Comment by joaofnfernandes** [comment]
I absolutely agree and have been thinking for a while on how to address that. I think this is a more structural problem than spans the entire docs site.

It should be possible for users to know:
* There are two options: CE and EE
* What you get with each
* If you chose one, you should be able to see docs just for your edition

I'm going to keep the issue closed, but we'll definitely work to address this friction.
