### ISSUE TITLE
custom docker0 config example broken

### ISSUE THREAD

**Issue by FlorianLudwig** [docker/docker.github.io#6891]
File: [engine/userguide/networking/default_network/custom-docker0.md](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/)

Using the example from the documentation:
```
{
  "bip": "192.168.1.5/24",
  "fixed-cidr": "192.168.1.5/25",
  "fixed-cidr-v6": "2001:db8::/64",
  "mtu": 1500,
  "default-gateway": "10.20.1.1",
  "default-gateway-v6": "2001:db8:abcd::89",
  "dns": ["10.20.1.2","10.20.1.3"]
}
```

which is inconsistent in itself and wouldn't work.

```
Error starting daemon: Error initializing network controller: Error creating default "bridge" network: auxilairy address: (DefaultGatewayIPv4:10.20.1.1) must belong to the master pool: 192.168.1.0/24
```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
