### ISSUE TITLE
Problem in "Get Started with Docker - Part 5" on Visualizer

### ISSUE THREAD

**Issue by huskysun** [docker/docker.github.io#6896]
Hey, I guess I found a problem in the "Add a new service and redeploy" section, in page "Get Started with Docker - Part 5". On step 4, which is "Take a look at the visualizer", it says that I can go to either IP address of the output `docker-machine ls` at port 8080 to see the visualizer running. However, I strictly followed the instruction, but can only see the visualizer by the IP address of the swarm manager. I cannot open the visualizer by the worker's IP address. I guess this is because that the visualizer is only deployed on the manager, as specified in `docker-compose.yml ` file?

File: [get-started/part5.md](https://docs.docker.com/get-started/part5/)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by paulolorenzobasilio** [comment]
hi please reopen.

**Comment by paulolorenzobasilio** [comment]
hi. pls reopen having the same issue on visualizer part. cannot access the port :8080

**Comment by paulolorenzobasilio** [comment]
solved. it was weird. i had to execute "docker-machine upgrade <node>" then scp docker-compose.yml to node "docker-machine scp docker-compose.yml <node>:~"
