### ISSUE TITLE
I found broken links

### ISSUE THREAD

**Issue by znz** [docker/docker.github.io#6898]
In <https://docs.docker.com/install/linux/docker-ce/debian/#install-docker-ce>,
- set up Docker’s repositories https://docs.docker.com/install/linux/docker-ce/#install-using-the-repository
- install it manually https://docs.docker.com/install/linux/docker-ce/#install-from-a-package
- convenience scripts https://docs.docker.com/install/linux/docker-ce/#install-using-the-convenience-script
are broken links.

**Comment by L-Hudson** [comment]
All fixed in current version. Closing ticket.
