### ISSUE TITLE
Feedback for: engine/reference/api/docker_remote_api.md Request for linkback to getting started with Docker Remote API

### ISSUE THREAD

**Issue by chamunks** [docker/docker.github.io#690]
File: [engine/reference/api/docker_remote_api.md](https://docs.docker.com/engine/reference/api/docker_remote_api/)

I'm not seeing any links back to any prerequisite data on how to use this functionality or how to set it up.  Googling for API information has lead me to this page and not to any information on getting started.

**Comment by johndmulhausen** [comment]
These pages are going away when #606 merges; self-assigning.

**Comment by londoncalling** [comment]
LGTM per the referenced PR ^^, and the current version of this topic does provide context and links to getting started on the left nav: https://docs.docker.com/engine/api/
