### ISSUE TITLE
Missing "log" command for the alternative to collect logs

### ISSUE THREAD

**Issue by sergiu-terman** [docker/docker.github.io#6901]
File: [docker-for-mac/troubleshoot.md](https://docs.docker.com/docker-for-mac/troubleshoot/)

In the `check the logs` section the alternative way to collect the logs command is missing is missing the `log` command

Right now it's:
```bash
show --debug --info --style syslog --last 1d --predicate "$pred" >/tmp/logs.txt
```
While it should be:

```
log show --debug --info --style syslog --last 1d --predicate "$pred" >/tmp/logs.txt
```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
