### ISSUE TITLE
[docker/compose] [Minor] Obsolete release notes from https://docs.docker.com/release-notes/docker-compose/

### ISSUE THREAD

**Issue by fodger** [docker/docker.github.io#6902]
### Problem description
Hi,
it's minor but release notes from https://docs.docker.com/release-notes/docker-compose/ concerns 1.21.0 version, not the 1.21.2.

I guess it is about fixes, but it is always good to know details.

Thanks all team for your incredible work !

### Problem location

https://docs.docker.com/release-notes/docker-compose

### Project version(s) affected

1.21.2

### Suggestions for a fix

Add 1.21.2 release notes.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
