### ISSUE TITLE
Clarification: curl localhost on the port specified in the docker-compose.yml

### ISSUE THREAD

**Issue by dutchminator** [docker/docker.github.io#6904]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)

The instructions mention to `curl -4 http://localhost`, however this will curl to the default port 80. The services are however running on localhost port 4000 as specified in the docker-compose.yml file. I propose the instructions and sample screenshot are changed to specifically mention `curl -4 http://localhost:4000`.

**Comment by joaofnfernandes** [comment]
You're right! Can you file a pull request to fix it?

**Comment by dutchminator** [comment]
Beat me to it. Thanks for the quick fix. :)

**Comment by joaofnfernandes** [comment]
There's a ton of other things that need fixing 😉
