### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by cbittencourt** [docker/docker.github.io#6906]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)

Links to [Switch between Windows and Linux containers](https://docs.docker.com/docker-for-windows/install/#switch-between-windows-and-linux-containers) and [Docker Settings](https://docs.docker.com/docker-for-windows/install/#docker-settings) point to non-existent anchors. 

Side note: I'm trying to switch from windows containers to linux containers with `17.06.2-ee-13` on `Windows Server 2016 1709` and the DockerCLI.exe file referenced in other documentation cannot be found. I was hoping both broken links above would lead to a solution for this.

**Comment by L-Hudson** [comment]
still true in this release. Please fix.
