### ISSUE TITLE
Docker capability CAP_AUDIT_READ is not listed in docs?

### ISSUE THREAD

**Issue by sethkoehler** [docker/docker.github.io#6908]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

CAP_AUDIT_READ isn't listed in either the default on or default off sections of the docker run docs here?

https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

Should it be?

**Comment by smythluke** [comment]
Can't seem to find an answer anywhere as to weather this is default on or off.
I think it should default to off.

The capability was added in kernel version 3.16 so if you run a kernel less than this you won't have access to this anyway (e.g. centos 7).

Although CAP_BLOCK_SUSPEND was added in 3.5 and is in the docker documentation...

**Comment by sethkoehler** [comment]
My brief searching didn't turn up anything too meaningful either.  This page (https://blog.lizzie.io/linux-containers-in-500-loc.html) seemed to indicate READ is more dangerous than WRITE (the latter of which seems default on), so I'd hazard a guess that it being off by default is reasonable too.  However, I don't know how it's actually implemented (or even which of the docker repos it'd be in)?

Thanks for looking into this!

**Comment by justincormack** [comment]
I think it was omitted by accident. It is not in the default capability set.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by sethkoehler** [comment]
Not sure about the refactor you mention, but AUDIT_READ still isn't on the doc page initially mentioned, while AUDIT_WRITE and AUDIT_CONTROL are?  I think it just needs to be added in the appropriate section (either defaulted on or defaulted off).

**Comment by sethkoehler** [comment]
I don't see a way for me to leave this open, but I suspect it should be left open...though ultimately it's your docs :)
