### ISSUE TITLE
I found a broken link: https://docs.docker.com/v1.7/reference/reference/userguide/dockervolumes

### ISSUE THREAD

**Issue by knangia** [docker/docker.github.io#6909]
I was trying to look for docker run command here <https://docs.docker.com/v1.7/reference/run/>, specifically with -v option mentioned in the section of VOLUME (shared filesystems) here <https://docs.docker.com/v1.7/reference/run/#volume-shared-filesystems>. In that section, this is written : "The volumes commands are complex enough to have their own documentation in section Managing data in containers ",  where **Managing Data in containers** link is **broken** . The **Broken link** is : **<https://docs.docker.com/v1.7/reference/reference/userguide/dockervolumes>**

**Comment by L-Hudson** [comment]
Straightforward correction, in docs that are archived, yet still in use. Please fix.

**Comment by ahh-docker** [comment]
@thaJeztah can you help us with this one? We can't find where this is coming from. Thanks!

**Comment by thaJeztah** [comment]
hm so the correct link should be without `/reference/reference/`, thus: https://docs.docker.com/v1.7/userguide/dockervolumes/

I suspect there's a relative link in a markdown file that doesn't resolve correctly.

However; the page containing the broken link is in the archived docs for docker 1.7, which is over 3 years old (released in June 2015 https://github.com/moby/moby/releases/v1.7.0).

I can have a look in the archive branch, but chances are that we'll run into issues when regenerating that archive

**Comment by thaJeztah** [comment]
ok; looks like the 1.7 archive only contains the generated HTML, not the Markdown, so should be an easy fix; https://github.com/docker/docker.github.io/blob/v1.7/reference/run/index.html

I'll open a PR

**Comment by L-Hudson** [comment]
This version of the docs is outside our maintenance window. Closing ticket.
