### ISSUE TITLE
Missing instructions for persistence of shared mount updates

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#6913]
File: [ee/ucp/admin/install/index.md](https://docs.docker.com/ee/ucp/admin/install/)

The docs mention the updating of the mount sharing for Ubuntu 14.04 but they do not specify how to make sure that the settings are persisted across reboots.  There is a customer success article on this: https://success.docker.com/article/install-ucp-3-on-old-distro but this should be in the docs because UCP fails to start up on manager nodes and the `ucp-reconcile` container fails to run as well on workers.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
