### ISSUE TITLE
Remove or update installation links for non-supported CNI plugins

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#6919]
File: [ee/ucp/kubernetes/install-cni-plugin.md](https://docs.docker.com/ee/ucp/kubernetes/install-cni-plugin/)

Either remove documented for unsupported CNI plugins or correct the link to use non-RBAC versions.  Example: flannel has RBAC that isn't supported in UCP.  Looks like there is a legacy version that doesn't use RBAC: https://github.com/coreos/flannel/blob/master/Documentation/k8s-manifests/kube-flannel-legacy.yml

Looks like the same issue exists for Weave and Romana.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
