### ISSUE TITLE
UCP instructions to create grant for a service account out of sync with UI

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#6929]
### Problem description

UI and instructions for creating a grant for a service account do not align with current UI (UCP 3.0.2):

![2018-06-22-145358_1667x1983_scrot](https://user-images.githubusercontent.com/3613189/41794114-48f83e1c-762c-11e8-92e2-02e066729f33.png)

For instance, there is no `left pane` in the above screenshot, taken from UCP 3.0.2.   Current instructions:

> To give the service account access to cluster resources, create a grant with
> `Restricted Control` permissions.
> 
> 1.  Navigate to the **Grants** page and click **Create Grant**.
> 2.  In the left pane, click **Resource Sets**, and in the **Type** section,
>     click **Namespaces**.
> 3.  Select the **nginx** namespace.
> 4.  In the left pane, click **Roles**. In the **Role** dropdown, select
>     **Restricted Control**.
> 5.  In the left pane, click **Subjects**, and select **Service Account**.
> 
>     > Service account subject type
>     >
>     > The **Service Account** option in the **Subject Type** section appears only
>     > when a Kubernetes namespace is present.
>     {: .important}
> 
> 6.  In the **Namespace** dropdown, select **nginx**, and in the
>     **Service Account** dropdown, select **nginx-service-account**.
> 7.  Click **Create**.
> 
>     ![](../images/create-service-account-3.png){: .with-border}
> 

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ee/ucp/kubernetes/create-service-account/#create-a-grant

### Project version(s) affected

UCP 3.0

### Suggestions for a fix

Re-write and update screenshot to match current UI.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
