### ISSUE TITLE
Can't find Docker CE on portal.azure, only Docker EE

### ISSUE THREAD

**Issue by burgeriitis** [docker/docker.github.io#6934]
File: [docker-cloud/cloud-swarm/link-azure-swarm.md](https://docs.docker.com/docker-cloud/cloud-swarm/link-azure-swarm/)

**Comment by ziad-halabi9** [comment]
Any update on this issue?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
