### ISSUE TITLE
install for docker-ce does not work

### ISSUE THREAD

**Issue by nschmandt** [docker/docker.github.io#6936]
Hi! I'm sorry to trouble, but I'm trying to get docker working on linux 16.04, and I followed the instructions but then at this line
sudo apt-get install docker-ce
it cannot find the package. Please update the instructions, and let me know the proper way to install docker.
Thanks!

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
