### ISSUE TITLE
I never see any packets match this rule after create a port mapping 

### ISSUE THREAD

**Issue by threen134** [docker/docker.github.io#6938]
### Problem description
I create a port mapping  for expose container port 80 to host port 8080 
and then I notice a nat rule was create on iptables  with sip and dip is same container IP as following 

-A POSTROUTING -s 172.17.0.4/32 -d 172.17.0.4/32 -p tcp -m tcp --dport 80 -j MASQUERADE

I test some traffic situation and I never see any packets match this rule 
<img width="1475" alt="screen shot 2018-06-25 at 1 44 28 pm" src="https://user-images.githubusercontent.com/13844762/41832335-36cd2d02-787e-11e8-8275-7fa52cd2cbe9.png">

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
