### ISSUE TITLE
storagedriver: device mapper - document including thin-provisioning-tools

### ISSUE THREAD

**Issue by grooverdan** [docker/docker.github.io#6942]
File: [storage/storagedriver/device-mapper-driver.md](https://docs.docker.com/storage/storagedriver/device-mapper-driver/)

I got into this situation:
<pre>
# journalctl -u docker.service
Jun 26 15:51:44 master dockerd[21882]: time="2018-06-26T15:51:44.813796908+10:00" level=info msg="libcontainerd: new containerd process, pid: 21892"
Jun 26 15:51:45 master dockerd[21882]: Error starting daemon: error initializing graphdriver: devicemapper: Non existing device docker-thinpool
Jun 26 15:51:45 master systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 15:51:45 master systemd[1]: Failed to start Docker Application Container Engine.

# vgchange -ay
  /usr/sbin/thin_check: execvp failed: No such file or directory
  Check of pool docker/thinpool failed (status:2). Manual repair required!
  0 logical volume(s) in volume group "docker" now active
</pre>

On ubuntu-16.04 I needed to install thin-provisioning-tools to provide this executable. After installation activation of the volume group and docker was possible.

As this use of thin provisioning is likely to be a first use by a sysadmin, providing a hint to include the package containing thin_check would be a useful hint. Installation will succeed without it but whenever a recovery is needed it becomes necessary.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
