### ISSUE TITLE
Vice versa documentation for docker load and save.

### ISSUE THREAD

**Issue by Makoehle** [docker/docker.github.io#6943]
File: [engine/reference/commandline/load.md](https://docs.docker.com/engine/reference/commandline/load/)

Add:
Examples
Load a backup that can then be used with [docker save](https://docs.docker.com/engine/reference/commandline/save/#usage).

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
