### ISSUE TITLE
Misleading Known Issues Info in EE Release Notes

### ISSUE THREAD

**Issue by rchourasia** [docker/docker.github.io#6946]
### Problem description

Known Issues section in release notes is misleading as it's not consistent across different releases. Case in point UCP 3.0.x. For UCP 3.0.0 we had a lengthy list of known issues. One would expect that 3.0.1 lists all the known issues that still exist in product and possibly some new ones. Not having these known issues called out in subsequent patches gives an impression that all those issues are resolved which is clearly not the case.

### Problem location

In all UCP, DTR and Engine EE release notes.

### Project version(s) affected

All

### Suggestions for a fix

One possible solution could be to maintain a common running list of known issues for each release train (e.g. one for UCP 3.0.x, another for UCP 2.2.x) and link them to respective release notes. The list should mention the release version where the issue got fixed. This is just one suggestion, there could be other ways. Looking for inputs from folks in CC.

cc @pkennedyr @ry4nz @marcusmartins @mghazizadeh @JustinINevill @dmp42 @Docker-Minh @pdevine @brawong @andrewhsu @mark-church

**Comment by bermudezmt** [comment]
@rchourasia I've added this to our EE content refactoring doc. I really like your suggestion for a fix and would like to explore it further. We should definitely solve for the problems of release notes accessibility (in general), associated known issues for a major release, and a tally of the fixes which should link to the specific patch releases which introduced the fix.

**Comment by bermudezmt** [comment]
Need feedback on current mockup for "Known Issues". cc: @anthonyleungdocker @david-yu @mark-church

**Comment by bermudezmt** [comment]
This is being tracked in the other repo now.
