### ISSUE TITLE
Typo or error in Docker Run Reference for memory settings

### ISSUE THREAD

**Issue by dougli1sqrd** [docker/docker.github.io#6958]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

When introducing the --memory-swap 1G option for `run` in docker, the page says:

> We set both memory and swap memory, so the processes in the container can use 300M memory and 700M swap memory.

But the command in reference just above is:
> `$ docker run -it -m 300M --memory-swap 1G ubuntu:14.04 /bin/bash`

Are the options just confusing or is the line a mistake? Should it say something more like: "...can use 300M memory and 1G swap memory"?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
