### ISSUE TITLE
Oracle Linux Storage driver clarification needed

### ISSUE THREAD

**Issue by darwin-traver** [docker/docker.github.io#6966]
File: [install/linux/docker-ee/oracle.md](https://docs.docker.com/install/linux/docker-ee/oracle/)

As per the https://success.docker.com/article/compatibility-matrix, EE 2.0 removed devicemapper as a supported storage driver, leaving only overlay2.

Requesting clarification/rewording of the Oracle Linux Prerequisites bullet list.

Also the section 'Architectures and storage drivers' needs to be edited:

> On Oracle Linux, Docker EE only supports the devicemapper storage driver. In production, you must use it in direct-lvm mode, which requires one or more dedicated block devices. Fast storage such as solid-state media (SSD) is recommended. Do not start Docker until properly configured per the storage guide.

**Comment by tfoxnc** [comment]
We have added devicemapper back to the comp matrix starting with UCP 3.0.2.

This section needs to reworded to reflect what the comp matrix says for both EE 17.06 and EE 2.0.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
