### ISSUE TITLE
Clarification to Devicemapper page to reflect overlay2 addition

### ISSUE THREAD

**Issue by darwin-traver** [docker/docker.github.io#6967]
File: [storage/storagedriver/device-mapper-driver.md](https://docs.docker.com/storage/storagedriver/device-mapper-driver/)

The following section needs to be adjusted:
> devicemapper storage driver is the only supported storage driver for Docker EE and Commercially Supported Docker Engine (CS-Engine) on RHEL, CentOS, and Oracle Linux. See the Product compatibility matrix

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
