### ISSUE TITLE
unknown shorthand flag: 'f' in -f

### ISSUE THREAD

**Issue by michaeldayCA** [docker/docker.github.io#6970]
File: [engine/reference/commandline/stack_deploy.md](https://docs.docker.com/engine/reference/commandline/stack_deploy/)

When attempting to use the syntax in the document:
```
docker stack deploy --compose-file docker-compose.yml -f docker-compose.prod.yml vossibility
```
I get the following error:
```
unknown shorthand flag: 'f' in -f
See 'docker stack deploy --help'.
```

I think the example should have a -c or --compose-file for the 2nd compose file instead of the invalid flag -f

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
