### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by s-santhosha** [docker/docker.github.io#6971]
From this link URL: https://docs.docker.com/edge/engine/reference/commandline/build/#set-ulimits-in-container---ulimit 

Under the section:
Set build-time variables (--build-arg)

For detailed information on using ARG and ENV instructions, see the **_Dockerfile reference._**

Dockerfile reference is a broken link

**Comment by L-Hudson** [comment]
Should link to https://docs.docker.com/engine/reference/builder/

**Comment by ahh-docker** [comment]
@s-santhosha We are not getting a 404 with this. Can you please be more specific with your issue? CC: @thaJeztah

**Comment by paigehargrave** [comment]
@s-santhosha - Thank you for bringing this to our attention - this is now fixed.
