### ISSUE TITLE
cloudformation:PreviewStackUpdate - Wrong action

### ISSUE THREAD

**Issue by polorumpus** [docker/docker.github.io#6973]
File: [docker-for-aws/iam-permissions.md](https://docs.docker.com/docker-for-aws/iam-permissions/)

cloudformation:PreviewStackUpdate
IAM does not recognize this action. The action name might include a typo or might be part of a previewed or custom service

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
