### ISSUE TITLE
I found a broken link: docker-compose file reference

### ISSUE THREAD

**Issue by cpdean** [docker/docker.github.io#6977]
From the [Docker Compose index](https://docs.docker.com/compose/) if you click on "Compose file reference" it brings you to the url `https://docs.docker.com/compose/compose-file/index.md` which throws a 404.

**Comment by cpdean** [comment]
If you remove the `index.md` filename, the url resolves correctly:

https://docs.docker.com/compose/compose-file/

**Comment by peter-kehl** [comment]
Hi Conrad,

Would you double-check, please. The link works now (screenshot below). The problem was most likely temporary.

![image](https://user-images.githubusercontent.com/4270240/42351468-ef509ede-8069-11e8-863b-898e3961fb43.png)

**Comment by peter-kehl** [comment]
For docker docs maintainers: The link currently works when run with docker-compose locally, too:
![image](https://user-images.githubusercontent.com/4270240/42353475-70111af2-8075-11e8-9331-f5f155231aee.png)

**Comment by cpdean** [comment]
yep, the link now works as expected
