### ISSUE TITLE
Offline install/upgrade links for UCP 3.0.2 on Windows only point to Windows Server 1709 image

### ISSUE THREAD

**Issue by axeal** [docker/docker.github.io#6978]
### Problem description

The offline install and upgrade links for UCP 3.0.2 on Windows - [here](https://docs.docker.com/ee/ucp/admin/install/install-offline/) and [here](https://docs.docker.com/ee/ucp/admin/install/upgrade-offline/) - point to the Windows Server 1709 specific image `https://packages.docker.com/caas/ucp_images_win_1709_3.0.2.tar.gz`. For Windows Server 2016 there is a separate image `https://packages.docker.com/caas/ucp_images_win_2016_3.0.2.tar.gz`, which needs to be called out in the documentation.

### Problem location

- https://docs.docker.com/ee/ucp/admin/install/install-offline/
- https://docs.docker.com/ee/ucp/admin/install/upgrade-offline/

### Project version(s) affected

UCP 3.0.2

### Suggestions for a fix

Include version specific links for Windows Server 2016 and Windows Server 1709

**Comment by ollypom** [comment]
Fixed in https://github.com/docker/docker.github.io/pull/6988
