### ISSUE TITLE
Docker-compose misleading information about resources limits ('cpus'-parameter)

### ISSUE THREAD

**Issue by telac** [docker/docker.github.io#6979]
### Problem description

In the docker-compose docs (https://docs.docker.com/compose/compose-file/#resources) it is mentioned that `cpus` variable limits to a percentage of available processing time:

>In this general example, the redis service is constrained to use no more than 50M of memory and 0.50 (50%) of available processing time (CPU), and has 20M of memory and 0.25 CPU time reserved (as always available to it).

While actually it would seem that `cpus` variable allocates a number of cpu-cores available to the container. I ran a benchmark using partially parallel code with following results:

```
deploy:
    resources:
     limits:
      cpus: "0.3"

 Yielded 

real  2m9.230s
user  0m38.620s
sys   0m0.104s

deploy:
    resources:
     limits:
      cpus: "1.0"

Yielded

real  0m38.088s
user  0m37.732s
sys   0m0.112s

deploy:
    resources:
     limits:
      cpus: "2.0"

Yielded

real  0m28.868s
user  0m37.472s
sys   0m0.116s

```

(And the parallel portions of the code were almost exactly halved according to my timers inside the program)

 While the documentation is not entirely untrue, I feel it is slightly misleading as it mentions that the variable sets a percentage of CPU time, but that percentage can exceed 100% in a multicore-setup. I.e. the current documentation can lead one to believe that selected a value of for example `0.5` in a 4-core setup would allocate two cores to the service within the swarm, while it actually only allocates 0.5 cores to that service.

### Problem location

https://docs.docker.com/compose/compose-file/#resources

### Project version(s) affected

docker-compose docs (latest)

### Suggestions for a fix

What `cpus` actually seems to do is better documented here: https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory and I think it would be less confusing if same definition was used in `docker-compose` docs:

>Specify how much of the available CPU resources a container can use. For instance, if the host machine has two CPUs and you set `--cpus="1.5"`, the container is guaranteed at most one and a half of the CPUs. This is the equivalent of setting `--cpu-period="100000"` and `--cpu-quota="150000"`. Available in Docker 1.13 and higher.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
