### ISSUE TITLE
Does instruction execution has order in same line?

### ISSUE THREAD

**Issue by browncrane** [docker/docker.github.io#6982]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

In your example here:

> Environment variable substitution will use the same value for each variable throughout the entire instruction. In other words, in this example:
> 
> ```
> ENV abc=hello
> ENV abc=bye def=$abc
> ENV ghi=$abc
> ```
> 
> will result in `def` having a value of `hello`, not `bye`. However, `ghi` will have a value of `bye` because it is not part of the same instruction that set `abc` to `bye`.

It says `def` will having a value of `hello`, but `abc=bye` is on the left of `def=$abc`
Does that mean the instruction execute from right to left?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
