### ISSUE TITLE
Add port 4000 in Accessing your cluster

### ISSUE THREAD

**Issue by bkelemen56** [docker/docker.github.io#6983]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

Under "Accessing your cluster" section:

The IP address of myvm1 or myvm2 alone will not bring up the page.  Port 4000 must also added.
The screen capture of a browser would also need to be regenerated:

<img width="653" alt="screen shot 2018-07-03 at 8 41 24 am" src="https://user-images.githubusercontent.com/1868882/42220465-03cb7bb4-7e9d-11e8-88a1-0640adea1421.png">

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
