### ISSUE TITLE
Not able to access page on browser using IP only need to append port as well.

### ISSUE THREAD

**Issue by HareshChhelana** [docker/docker.github.io#6991]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

As we using same `docker-compose.yml` file which is created on part3 and there is host port mapping is `4000:80` so will not able to access page after deploy app on swarm manger using IP like `192.168.99.100`. Either we need to add `4000` port after IP like `192.168.99.100:4000` or need update port mapping '80:80 instead of '4000:80 ''on `docker-compose.yml` file before deploy app on swarm manager.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
