### ISSUE TITLE
reference manual is horribly out of date

### ISSUE THREAD

**Issue by harridu** [docker/docker.github.io#6993]
File: [reference.md](https://docs.docker.com/reference/)

Hi folks,
when introducing new or deprecating old features, would you please consider keeping the reference manual up-to-date? IMHO the reference manual should change **first**, all these guides and product manuals on docs.docker.com can follow later.

Famous example: The network guide provides a little bit information about "macvlan", "ipvlan", "overlay", etc., but if you look into the reference for "docker network create" to dive into it, then all you find is "host" and "bridge". This is highly frustrating.

Regards
Harri

**Comment by L-Hudson** [comment]
/reference isn't maintained by docs, and the feedback is a few revisions back. Closing ticket.
