### ISSUE TITLE
Installing docker-compose on openSUSE

### ISSUE THREAD

**Issue by peter-kehl** [docker/docker.github.io#6996]
Please, add a note on installing docker-compose on openSUSE (as per current version Tumbleweed 20180703) referring to https://en.opensuse.org/SDB:Docker. That currently installs Docker version 17.09.1-ce and docker-compose version 1.21.2. It seems to fit on https://docs.docker.com/install and https://docs.docker.com/compose/install/#install-compose.

Side notes:
 * install/linux/docker-ee/suse.md
 * issues/3264 - even though openSUSE wasn't supported back then, openSUSE now has docker as per above. Hence why not promote it?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
