### ISSUE TITLE
Remove this page - service in no longer offered by docker hub. 

### ISSUE THREAD

**Issue by programingnotes** [docker/docker.github.io#6999]
File: [docker-cloud/apps/auto-redeploy.md](https://docs.docker.com/docker-cloud/apps/auto-redeploy/)

- so many people get tripped up by this. Please remove this page as you no longer offer this service to non-enterprise users.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
