### ISSUE TITLE
Feedback for: engine/installation/binaries.md

### ISSUE THREAD

**Issue by mMontu** [docker/docker.github.io#700]
File: [engine/installation/binaries.md](https://docs.docker.com/engine/installation/binaries/)

I'm trying to install docker on Slackware, and as it isn't present on the list at https://docs.docker.com/engine/installation/linux/ I proceeded to install it from binaries. The instructions for the latest versions expects that the .tgz file contains something like the following:

```
$ tar -xvzf docker-latest.tgz

docker/
docker/docker
docker/docker-containerd
docker/docker-containerd-ctr
docker/docker-containerd-shim
docker/docker-proxy
docker/docker-runc
docker/dockerd
```

But downloading the latest versions,
```

wget https://get.docker.com/builds/Linux/i386/docker-1.12.2.tgz
wget https://get.docker.com/builds/Linux/i386/docker-1.12.3.tgz
wget https://get.docker.com/builds/Linux/i386/docker-latest.tgz

```

, brings only the following:

```
docker/
docker/docker
```

Thus I'm unable to start the daemon, as mentioned in the explanation:
```

$ mv docker/* /usr/bin/
$ sudo dockerd &
```

Trying to start the daemon following the instructions for older releases results in a error:
```

$ sudo ./docker/docker daemon
`docker daemon` is not supported on Linux. Please run `dockerd` directly
```

Am I missing something, or the binary files provided for the latest versions are incomplete?

**Comment by mstanleyjones** [comment]
Thanks for the report. I'll try to replicate this and let you know what I find out.

**Comment by mstanleyjones** [comment]
Hi there, this is actually the correct behavior, because you are downloaded the 32-bit binary (`i386` in the URL). For 32-bit binaries, only the `docker/docker` binary is included. If you change the URLs to use `x86_64` instead of `i386`, you will see all the files you expect:

```bash
$ wget https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz

--2016-12-02 09:39:03--  https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
Resolving get.docker.com... 52.85.209.88, 52.85.209.224, 52.85.209.159, ...
Connecting to get.docker.com|52.85.209.88|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28891346 (28M) [application/x-tar]
Saving to: ‘docker-1.12.3.tgz’

docker-1.12.3.tgz           100%[=========================================>]  27.55M  9.55MB/s    in 2.9s

2016-12-02 09:39:07 (9.55 MB/s) - ‘docker-1.12.3.tgz’ saved [28891346/28891346]

$ tar tzvf docker-1.12.3.tgz
drwxr-xr-x  0 0      0           0 Oct 26 16:31 docker/
-rwxr-xr-x  0 0      0     2879456 Oct 26 16:31 docker/docker-proxy
-rwxr-xr-x  0 0      0     8760704 Oct 26 16:31 docker/docker-runc
-rwxr-xr-x  0 0      0     3721360 Oct 26 16:31 docker/docker-containerd-shim
-rwxr-xr-x  0 0      0    45517296 Oct 26 16:31 docker/dockerd
-rwxr-xr-x  0 0      0    11290184 Oct 26 16:31 docker/docker-containerd
-rwxr-xr-x  0 0      0    15673768 Oct 26 16:31 docker/docker
-rwxr-xr-x  0 0      0    10537480 Oct 26 16:31 docker/docker-containerd-ctr
```

By the way, have a look at PR #764 where I am improving the topic about installing binaries.

**Comment by mMontu** [comment]
@mstanleyjones so I guess that in 32-bit machines only the client works. Thanks!
