### ISSUE TITLE
Broken repository link in engine/reference/commandline/README.md

### ISSUE THREAD

**Issue by cwgem** [docker/docker.github.io#7000]
### Problem description

There's a broken repository link in engine/reference/commandline/README.md

### Problem location

engine/reference/commandline/README.md

### Suggestions for a fix

The readme links to the moby/mobi repository docs folder which doesn't contain `reference/commandline`. My guess is that it should be pointing to the docker/cli repository instead:

https://github.com/docker/cli/tree/master/docs/reference/commandline

**Comment by L-Hudson** [comment]
Please verify and make the change.

**Comment by ahh-docker** [comment]
Reference documentation: hopefully this can be fixed when we regenerate it. Otherwise, I'll see if there's more on the process. See https://github.com/docker/docker.github.io/pull/7731

**Comment by ahh-docker** [comment]
Working with @seemethere to see if this falls under docker.github.io or docker/cli.

**Comment by seemethere** [comment]
This can be closed now

**Comment by ahh-docker** [comment]
closing per @seemethere
