### ISSUE TITLE
More information on configuring rfc5424 logging drivers

### ISSUE THREAD

**Issue by nwertzberger** [docker/docker.github.io#7004]
File: [engine/admin/logging/syslog.md](https://docs.docker.com/engine/admin/logging/syslog/)

Could more be written about setting company id, the thing before the company id, setting metadata, etc, for rfc5424?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
