### ISSUE TITLE
awslogs credentials delivery

### ISSUE THREAD

**Issue by leriel** [docker/docker.github.io#7007]
File: [config/containers/logging/awslogs.md](https://docs.docker.com/config/containers/logging/awslogs/)

Please consider updating the credentials delivery section. Mentioning `/etc/systemd/system/docker.service.d/aws-credentials.conf` would come a long way.

I found full instructions under https://wdullaer.com/blog/2016/02/28/pass-credentials-to-the-awslogs-docker-logging-driver-on-ubuntu/

Thanks

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
