### ISSUE TITLE
Bug IDs for UCP release notes

### ISSUE THREAD

**Issue by darwin-traver** [docker/docker.github.io#7009]
File: [ee/ucp/release-notes.md](https://docs.docker.com/ee/ucp/release-notes/)

Request to add the internal Bug IDs for UCP patch fixes for reference purposes.

**Comment by trapier** [comment]
Issue moved to [docker/docs-private #693](https://github.com/docker/docs-private/issues/693) via [**ZenHub**](https://www.zenhub.com/)

**Comment by darwin-traver** [comment]
Pending PM, closing out.
