### ISSUE TITLE
Bug IDs for DTR release notes

### ISSUE THREAD

**Issue by darwin-traver** [docker/docker.github.io#7010]
File: [ee/dtr/release-notes.md](https://docs.docker.com/ee/dtr/release-notes/)

Request to add the internal Bug IDs for DTR patch fixes for reference purposes.

**Comment by trapier** [comment]
Issue moved to [docker/docs-private #697](https://github.com/docker/docs-private/issues/697) via [**ZenHub**](https://www.zenhub.com/)

**Comment by darwin-traver** [comment]
Pending PM, closing out.
