### ISSUE TITLE
Run on client machine: text incorrectly specifices that the server certificate has to be copied

### ISSUE THREAD

**Issue by thernstig** [docker/docker.github.io#7012]
File: [engine/security/https.md](https://docs.docker.com/engine/security/https/)

I believe the text here in is incorrect but I am not entirely sure. Just before the part that says "Run it on the client machine" it reads:

> To connect to Docker and validate its certificate, provide your client keys, certificates and trusted CA:

Then it reads:

> This step should be run on your Docker client machine. As such, you need to copy your CA certificate, your **server certificate**, and your client certificate to that machine.

And finally the example shows:
```
$ docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem \
  -H=$HOST:2376 version
```

As such, the bolded text above (**server certificate**) seems incorrect. It should say "client key" instead. Or at least it looks at it from the preceding text and the code example

**Comment by thaJeztah** [comment]
ping @cyli PTAL

**Comment by cyli** [comment]
Yes, the @thernstig is correct - it should be "client key", since the client doesn't need the server certificate.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by thernstig** [comment]
@L-Hudson It is a real bug in the documentation, should it really be closed?
