### ISSUE TITLE
Service clusters with Interlock (Layer 7 Routing in Swarm) missing proxy constraints

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#7017]
File: [ee/ucp/interlock/usage/service-clusters.md](https://docs.docker.com/ee/ucp/interlock/usage/service-clusters/)'

This page is missing the `ProxyConstraints` for the `us-east` and `us-west` service clusters:
`ProxyConstraints = ["node.labels.nodetype==loadbalancer","node.labels.region==us-east"]`
and
`ProxyConstraints = ["node.labels.nodetype==loadbalancer","node.labels.region==us-west"]`
respectively.

/cc @lenestopage

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
