### ISSUE TITLE
Need way to call a specific auto-created service container (e.g., compose/reference/scale.md)

### ISSUE THREAD

**Issue by sslavic** [docker/docker.github.io#702]
File: [compose/reference/scale.md](https://docs.docker.com/compose/reference/scale/)

Do different service instances get instance identifiers auto assigned, and is that value exposed to the running container as some environment variable, e.g. generic DOCKER_INSTANCE_INDEX, or service specific variant DOCKER_service_INSTANCE_INDEX?

**Comment by londoncalling** [comment]
@nathanleclaire @dnephin @ManoMarks @mstanleyjones Can you take a look at this question, and shed some light here?

**Comment by dnephin** [comment]
Each container has a unique name, but the name is not exposed to the container. https://github.com/docker/compose/issues/1503

**Comment by londoncalling** [comment]
@dnephin Okay I've read the discussion thread at [docker/compose#1503](https://github.com/docker/compose/issues/1503) and I'm almost tempted to just put a link to the issue in the docs at https://docs.docker.com/compose/reference/scale/ and https://docs.docker.com/compose/compose-file/#replicas. Do you have any thoughts on how to handle the "docs issue" side of this? 

It's a good question, relevant discussion, and doesn't seem entirely solved ..
