### ISSUE TITLE
Dead link in "File system sharing (osxfs)"

### ISSUE THREAD

**Issue by tlxtellef** [docker/docker.github.io#7025]
File: [docker-for-mac/osxfs.md](https://docs.docker.com/docker-for-mac/osxfs/)

Dead link: [#preferences](https://docs.docker.com/docker-for-mac/osxfs/#preferences).

**Comment by paigehargrave** [comment]
@tlxtellef - Very sorry for the delayed response on this - this link appears to be working. Please open another issue if you continue to experience a problem. Thank you!
