### ISSUE TITLE
Misleading wording about build contexts

### ISSUE THREAD

**Issue by tgeliot** [docker/docker.github.io#7026]
File: [develop/develop-images/dockerfile_best-practices.md](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

On the above-linked page, we find this paragraph talking about the effect of having too much stuff in the build context:

> Inadvertently including files that are not necessary for building an image results in a larger build context and larger image size. This can increase the time to build the image, time to pull and push it, and the container runtime size. To see how big your build context is, look for a message like this when building your Dockerfile:
> 
> Sending build context to Docker daemon  187.8MB

The mention of "larger image size" and "time to pull and push it, and container size" implies that if an unneeded file is included in the context, it will end up in the resulting image, even if there's nothing in the Dockerfile to cause it to be included in the image.  This isn't true, is it?

**Comment by L-Hudson** [comment]
https://vimeo.com/15351476
