### ISSUE TITLE
Feedback for: engine/installation/linux/fedora.md Fedora 25 lacks support

### ISSUE THREAD

**Issue by scottidler** [docker/docker.github.io#703]
File: [engine/installation/linux/fedora.md](https://docs.docker.com/engine/installation/linux/fedora/)

The section on creating a dnf|yum repo for docker on fedora 25 does not work, because there is not a 25/ folder at this url currently.

https://yum.dockerproject.org/repo/main/fedora/

Fix by adding the folder and the appropriate contents or by mentioning that support for Fedora 25 isn't available yet.

**Comment by mstanleyjones** [comment]
@thaJeztah WDYT about this?

**Comment by thaJeztah** [comment]
The top of that same page mentions 

> Docker is supported on Fedora version 22, 23, and 24.

Fedora 25 support is added in docker 1.13, as it was not released yet when docker 1.12.3 was released.

**Comment by mstanleyjones** [comment]
I'll repurpose this issue to remind myself to document Fedora 25 support in the `vnext-engine` branch.

**Comment by mstanleyjones** [comment]
Closed via #1159
