### ISSUE TITLE
edge documentation contains outdated sentence

### ISSUE THREAD

**Issue by sixcorners** [docker/docker.github.io#7035]
File: [edge/index.md](https://docs.docker.com/edge/)
"Stable releases are not published to the Edge channel, so Linux repository users should subscribe to both Edge and Stable channels.

The [linux install instructions](https://docs.docker.com/install/linux/docker-ce/ubuntu/) say this:
> Note: Starting with Docker 17.06, stable releases are also pushed to the edge and test repositories.

**Comment by L-Hudson** [comment]
https://vimeo.com/15351476
