### ISSUE TITLE
No network called "pub_net"

### ISSUE THREAD

**Issue by githubfromgui** [docker/docker.github.io#7036]
File: [network/network-tutorial-macvlan.md](https://docs.docker.com/network/network-tutorial-macvlan/)

In the sentence: _You can use docker network ls and docker network inspect pub_net commands to verify that the network exists and is a macvlan network._ It actually should be docker network inspect **my-macvlan-net** (real network name in the example).

**Comment by L-Hudson** [comment]
https://vimeo.com/15351476

**Comment by githubfromgui** [comment]
@L-Hudson ... and the reference means ?!? :dagger: :smiley_cat:
