### ISSUE TITLE
Formatting is screwed up in sample compose file

### ISSUE THREAD

**Issue by rlundy** [docker/docker.github.io#7037]
### Problem description

The sample compose file in the docs has no indenting and hence is very hard to read.

### Problem location

- I saw a problem on the following URL: https://github.com/docker/docker.github.io/blob/master/compose/compose-file/index.md

### Suggestions for a fix

I've already produced a PR to fix this:  https://github.com/docker/docker.github.io/pull/6926

If you [look at the diff in rich diff view](https://github.com/docker/docker.github.io/pull/6926/commits/ea2d505e8147d32441d1365aeecb5b5d0a5da8ae?short_path=06edd26#diff-06edd26f33bf2c3f6ee590618f41c62c), you'll see that it fixes the formatting.

I hope someone will see fit to merge this PR.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
