### ISSUE TITLE
Feedback for: engine/installation/binaries.md

### ISSUE THREAD

**Issue by bitwombat** [docker/docker.github.io#704]
File: [engine/installation/binaries.md](https://docs.docker.com/engine/installation/binaries/)

Very hard to find the latest version!  This page doesn't help but was my first stop.  I was hoping to get a file listing from https://get.docker.com/builds/Linux/x86_64/ but that's 404.

**Comment by mstanleyjones** [comment]
You get it from https://github.com/docker/docker/releases, as mentioned on the page you linked:

https://docs.docker.com/engine/installation/binaries/#get-the-docker-engine-binaries

Be sure to read the whole page very carefully, as installing from binaries is an advanced topic.

**Comment by bitwombat** [comment]
That's what I'm trying to convey.  The URL pattern:

https://get.docker.com/builds/Linux/i386/docker-<version>.tgz

Is useless if I don't know the docker versions.  This URL page should give a directory listing:

https://get.docker.com/builds/Linux/i386/

As well as the other URLs:

https://get.docker.com/builds/Linux/

and

https://get.docker.com/builds/

**Comment by mstanleyjones** [comment]
Unfortunately, it is not possible to show you a directory listing. This is a limitation with the way that `get.docker.com` works. However, you can get the links for a specific release by looking at the release notes for that version. Have a look at #764, as it might help.
