### ISSUE TITLE
I found a broken link: docker-for-aws

### ISSUE THREAD

**Issue by ambrons** [docker/docker.github.io#7051]
Searching for Docker for AWS and found links, but all are broken.
![screenshot-20180719012440-1159x436](https://user-images.githubusercontent.com/1403700/42923228-8a34f5d4-8af2-11e8-9ac2-6a2fe3f0c777.png)
![screenshot-20180719012424-1081x537](https://user-images.githubusercontent.com/1403700/42923229-8a42380c-8af2-11e8-8cb5-894df63218c3.png)

**Comment by gary-cowell** [comment]
Wondering if docker for-aws is abandoned, as all the documentation has been removed.

**Comment by hairyhenderson** [comment]
https://github.com/docker/docker.github.io/commit/14e01eea810cd3cff08a4f202f982a955d6a312c

The doc change was reverted it looks like.

**Comment by tfoxnc** [comment]
Yes. I just reverted it. These were removed while updating the installation docs for Docker CE to note the new release channel (see the lastest blog post). The removed docs have been added back. They need to be updated and were inadvertently removed.
