### ISSUE TITLE
18.03.1-ee-2 release-notes missing

### ISSUE THREAD

**Issue by mpepping** [docker/docker.github.io#7053]
### Problem description

The `18.03.1-ee-2` release-notes aren't available on <https://github.com/docker/docker.github.io/blob/master/ee/engine/release-notes.md>

The `18.03.1-ee-2` is available for download since 2018-07-11. The release-notes for this release aren't published yet. The `18.03.1-ee-1` (2018-06-27) release is the latest release published on the release-notes page.

**Comment by tfoxnc** [comment]
Sorry for the delay. They are being posted via https://github.com/docker/docker.github.io/pull/7072.
