### ISSUE TITLE
Network option to build configurations in docker-compose is not documented

### ISSUE THREAD

**Issue by Ajedi32** [docker/docker.github.io#7059]
### Problem description

Version 3.4 of the Docker compose file introduced the `network` option to build configurations: https://github.com/docker/docker.github.io/blob/master/compose/compose-file/compose-versioning.md#version-34

This option is not explained anywhere in the documentation.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/compose/compose-file/#build

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by Ajedi32** [comment]
@L-Hudson I can't reopen issues closed by contributors, but this is still applicable. See the links I included in the original issue.

I'm not sure what refactor you're referring to, but this issue is with the documentation's _content_, not its organization so I think it's unlikely that this would be fixed by a refactor.
