### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by niboowin** [docker/docker.github.io#7063]
From the page:
https://store.docker.com/editions/community/docker-ce-aws?tab=resources

Was unable to find the linked pages:

- [Detailed installation instructions](https://docs.docker.com/docker-for-aws/)
- [Overview and case studies](https://www.docker.com/aws)
- [What is docker (aws)](https://aws.amazon.com/docker/)

**Comment by tfoxnc** [comment]
Sorry for the confusion. These links have been fixed.
