### ISSUE TITLE
Available filters for docker image ls

### ISSUE THREAD

**Issue by jouve** [docker/docker.github.io#7067]
File: [engine/reference/commandline/image_ls.md](https://docs.docker.com/engine/reference/commandline/image_ls/)

What are the available filters for `docker image ls -f ???`

**Comment by jouve** [comment]
https://docs.docker.com/engine/api/v1.25/#operation/ImageList

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
