### ISSUE TITLE
--userns option is not documented for "docker run" command

### ISSUE THREAD

**Issue by asnisarenko** [docker/docker.github.io#7071]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/)

`docker run` reference has no documentation for `--userns` option. All it says is
`User namespace to use`, which is an ambiguous statement. Does it mean you can pick a different user (and thus that users namespace mappings) for a specific container ?

The only place i've seen the option mentioned is on this page: https://docs.docker.com/engine/security/userns-remap/, and only one  value is discussed (`--userns=host`).

What are the other possible values, and what do they do ?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by peey** [comment]
https://docs.docker.com/engine/reference/commandline/run/ should mention that the only allowed value is `host`

**Comment by peey** [comment]
Is it also possible to map uids and gids per-container? The system-wide mapping being the only option gives me goosebumps.

**Comment by corwin-of-amber** [comment]
Why was this closed? The docs have not been updated.
