### ISSUE TITLE
Outdated page regarding swarm mode

### ISSUE THREAD

**Issue by InDieTasten** [docker/docker.github.io#7075]
File: [docker-cloud/cloud-swarm/using-swarm-mode.md](https://docs.docker.com/docker-cloud/cloud-swarm/using-swarm-mode/)

As far as I understand, swarm mode is now enforced for everyone and cannot be disabled anymore.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
