### ISSUE TITLE
Is there any way to restart a shutdown task in a docker service and make it available?

### ISSUE THREAD

**Issue by CptJack2** [docker/docker.github.io#7076]
### Problem description
when I lauch docker service ps, I notice there are some containers have been shut down maybe out of some mistakes. However, I want to make them available again instead of letting swarm open a new container for the service because I already put some data in the shutdown container, and they all go missed in the new container. Is there any way to do that? Thanks a lot!

$ docker service ps redis

ID            NAME         IMAGE        NODE      DESIRED STATE  CURRENT STATE                   ERROR  PORTS
jf1i992619ir  redis.4      redis:3.0.6  worker1   Running        Running 10 seconds ago
blkttv7zs8ee   \_ redis.4  redis:3.0.5  worker1   Running       Shutdown 11 seconds ago

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
