### ISSUE TITLE
Error while running convenience script (Installation on Raspbian)

### ISSUE THREAD

**Issue by kappelloss** [docker/docker.github.io#7079]
File: [install/linux/docker-ce/debian.md](https://docs.docker.com/install/linux/docker-ce/debian/)

console throws the following output:

root@raspberrypi:/home/pi# curl -sSL https://get.docker.com | sh
# Executing docker install script, commit: 36b78b2
+ sh -c apt-get update -qq >/dev/null
E: The repository 'http://archive.raspberrypi.org/debian stretch Release' does no longer have a Release file.

**Comment by seemethere** [comment]
Yeah we saw the same issue in our nightly pipeline as well although I can't replicate it now.

Debian repositories for architectures outside of `x86_64` have always been pretty finicky for us so just try running it again and see if you get the same results.

**NOTE**: This isn't an issue with the convenience script but rather an issue with the debian package repositories for alternative architectures.

@thaJeztah this issue can be closed.
