### ISSUE TITLE
Feedback for: engine/reference/commandline/dockerd.md

### ISSUE THREAD

**Issue by VijitCoder** [docker/docker.github.io#708]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

Json config examples are wrong. There should be "default-ulimit" (singular). Also, it is necessary to show, how exactly to derermine those limits via json config. I killed an hour to find it out. Today, on the server ver. 1.12.3 in can be like this:

```json
{
    "default-ulimit": [
        "nofile=64000:1048576",
        "nproc=64000:1048576"
    ]
}
```

**It just don't leads to failing the daemon**. Actually, this limits **has no effect** in the container. Check:

```sh
root@Z710:~# docker run -it ubuntu bash -c "ulimit -a"
...
open files                      (-n) 65536
max user processes              (-u) unlimited
...
```

**Comment by mstanleyjones** [comment]
If this is still a problem, please raise a Github issue in the https://github.com/docker/docker project.
