### ISSUE TITLE
Windows engine does not support a volume with NFS

### ISSUE THREAD

**Issue by ekitagawa** [docker/docker.github.io#7081]
File: [engine/reference/commandline/volume_create.md](https://docs.docker.com/engine/reference/commandline/volume_create/)
 
"Edit This Page" doesn't allow me to update for some reason, so I will state it here.
 
Could we change it from:
> The built-in local driver on Windows does not support any options.
 
To something like this:
  
> The built-in local driver on Windows does not support any options; therefore, Windows engine 
> cannot create a volume mapped to NFS drive.  Use of smb and bind mount is recommended 
> instead.
> For hosts running on Azure or AWS, CloudStor plugin can provide connections to persistent storage.
 
Reasoning:
 
Because options are not supported on Windows engine with `volume create`, it cannot pass url and credential for NFS connection.  Also, NFS client on Windows does not support NFS ver 4 (which makes up majority of installations) too.  We should document this as limitation until feature will be added. 
 
https://github.com/kubernetes/kubernetes/issues/56188
 
smb is recommended here too
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#smb-mounts

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
