### ISSUE TITLE
UCP supported platforms link goes to CE instead of EE engine page

### ISSUE THREAD

**Issue by arueth** [docker/docker.github.io#7082]
The link in:
View the 'supported platforms' and click on your platform to get platform-specific instructions for installing Docker EE. 
takes you to
https://docs.docker.com/install/
instead of:
https://docs.docker.com/ee/supported-platforms/

File: [ee/ucp/admin/install/index.md](https://docs.docker.com/ee/ucp/admin/install/)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
