### ISSUE TITLE
documentation for command line docker container ls fails to specify --format go fields

### ISSUE THREAD

**Issue by aberezin** [docker/docker.github.io#7085]
File: [engine/reference/commandline/container_ls.md](https://docs.docker.com/engine/reference/commandline/container_ls/)

The docs for *docker image ls* enumerate the --format go template fields that can be specified.  However, *docker container ls* does not.  In general, the docs should enumerate the fields or, better yet, explain how one can introspect or, using conventions, guess the fields.

Specifically, it is not obvious (to me at least) what the field is for 'CONTAINER ID' and I had to dig around to find it here
http://manpages.ubuntu.com/manpages/bionic/man1/docker-container-ls.1.html

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
