### ISSUE TITLE
Make the example functional or add better explanation under what circumstances it does function

### ISSUE THREAD

**Issue by blackduck-joe** [docker/docker.github.io#7087]
File: [engine/reference/commandline/inspect.md](https://docs.docker.com/engine/reference/commandline/inspect/)

This is what I get for ANY of my containers:

docker inspect --format='{{range $p, $conf := .NetworkSettings.Ports}} {{$p}} -> {{(index $conf 0).HostPort}} {{end}}' 82b567527c70

Template parsing error: template: :1:59: executing "" at <index $conf 0>: error calling index: index of untyped nil

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
