### ISSUE TITLE
Feedback for: compose/swarm.md, Do something about old Swarm vs new Swarm confusion

### ISSUE THREAD

**Issue by jamshid** [docker/docker.github.io#709]
File: [compose/swarm.md](https://docs.docker.com/compose/swarm/)
I know you're still working on the new Compose and Swarm integration, (dabs, deploy, services ). 

Until then could you at least put a warning at the top of legacy pages? E.g. this doc is all about using Compose with the *old* Swarm approach (docker-machine env --swarm).

**Comment by londoncalling** [comment]
@jamshid I'm closing this issue for now as we added the banners, please re-open if you have more comments
