### ISSUE TITLE
Add a sample firewall rules for the most popular Firewall Software, i.e. Norton Internet Security

### ISSUE THREAD

**Issue by hack2root** [docker/docker.github.io#7092]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

Norton Firewall:

If you open Firewall activity logs, you may notice that incoming connections from subnet 10.0.75.0 is blocked by default Firewall rules

![security history 7_24_2018 9_18_21 pm](https://user-images.githubusercontent.com/383256/43157978-22db7374-8f87-11e8-912d-55160b807b4f.png)

You need to find corresponding rule in rule Firewall settings and add a new rule and move it up just before that rule. 

You may want to create a rule which allows connections from other computers

![settings 7_24_2018 9_28_04 pm](https://user-images.githubusercontent.com/383256/43158543-94fdbe3e-8f88-11e8-9d3f-02309b835900.png)

![settings 7_24_2018 9_29_58 pm](https://user-images.githubusercontent.com/383256/43158612-c21aa328-8f88-11e8-86d0-2387cc2f5a3c.png)

![settings 7_24_2018 9_23_21 pm](https://user-images.githubusercontent.com/383256/43158275-f723af66-8f87-11e8-99e1-a9a179e56c88.png)

![settings 7_24_2018 9_24_54 pm](https://user-images.githubusercontent.com/383256/43158320-15fcf1ea-8f88-11e8-8702-d30a67f3c679.png)

Your newly created rule allows incoming TCP connections to local computer ports from subnet 10.0.75.0 with mask 255.255.255.0 to allow inbound connections to all local ports from this subnet.  You may need to find blocking rule in rule Firewall settings and move up newly created rule  just on top of that blocking rule from firewall rule list. 

![settings 7_24_2018 9_15_01 pm](https://user-images.githubusercontent.com/383256/43157931-0bcf2298-8f87-11e8-9c1c-093748c9c0ae.png)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by F21** [comment]
This worked for me and should really be documented somewhere.
