### ISSUE TITLE
Change references of redis  versions

### ISSUE THREAD

**Issue by srufle** [docker/docker.github.io#7094]
File: [engine/swarm/swarm-tutorial/rolling-update.md](https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/)
I do not think 3.0.6 are in dockerhub anymore. 
https://hub.docker.com/r/library/redis/tags/

Propose moving page to reference in 3.2.6 and 3.2.7

**Comment by L-Hudson** [comment]
Please verify and update, thanks!

**Comment by bermudezmt** [comment]
Hi @srufle - sorry for the very delayed response on this. For maintainability, we have added a note regarding the older Redis tag being used in the example. Please submit another issue if you find another problem. Thank you for bringing this to our attention!
