### ISSUE TITLE
Predict/resolve intended changes for docker-compose up command

### ISSUE THREAD

**Issue by tomwwright** [docker/docker.github.io#7095]
### Problem description

`docker-compose up` will examine running services and determine what is going to be created/recreated, I would have expected there to be some functionality to display the intended changes but I can't appear to find anything of the sort

### Problem location

I would have expected to find this information somehow referenced in the CLI reference for `up`: https://docs.docker.com/compose/reference/up/

Disclaimer: I'm not sure if this is an issue with documentation, or actually constitutes a change/feature request -- any clarity on this would be welcome

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
