### ISSUE TITLE
 --dispatcher-heartbeat What is the correct use for?

### ISSUE THREAD

**Issue by byeong0** [docker/docker.github.io#7096]
I have a small anxiety about configuring a docker swarm.

Do the docker swaram manager node fail the dispatcher-heartbeat of the woker node and the container restart action if the woker node reconnects?

I do not want the container to be restarted in the event of a network outage.

Because the dispatcher-heartbeat fails in the leader node, we want the container in the woker of the other region to function normally, because the network of the disparate regions may be disconnected.

This is serious if the container is restarted in the production environment.

1. Can I update the dispatcher-heartbeat period very long?
2. If the dispatcher-heartbeat fails, does the docker swarm work to restore the container?

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
