### ISSUE TITLE
Facing issues with configuring Elasticsearch on docker contianer on a private server

### ISSUE THREAD

**Issue by RajaSureshAditya** [docker/docker.github.io#7097]
Hi ,

I am trying to configure the elasticsearch inside a contianer in a Private instance , logstash and kibana is on public instance ,
so i have ran the below command to get the elasticsearch up and running

https://pastebin.com/e8cer2Fz

now application is running inside the contianer but was not able to access from outside the container such as curl localhost:9200 or curl 192.x.x.2:9200 , from the host server

but the same command is working from inside the contianer
curl locahost:9200
{
“name” : “YF4XMEc”,
“cluster_name” : “docker-cluster”,
“cluster_uuid” : “pwhgUUPQTPy5DgENhaf6og”,
“version” : {
“number” : “6.3.0”,
“build_flavor” : “oss”,
“build_type” : “tar”,
“build_hash” : “424e937”,
“build_date” : “2018-06-11T23:38:03.357887Z”,
“build_snapshot” : false,
“lucene_version” : “7.3.1”,
“minimum_wire_compatibility_version” : “5.6.0”,
“minimum_index_compatibility_version” : “5.0.0”
},
“tagline” : “You Know, for Search”
}

issue here is am not able to access the elasticsearch with the host server ip and port

can some one help me with this approach where am i going wrong 

Thanks & Regards,

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
