### ISSUE TITLE
Question: memory-swap and memory-swappiness

### ISSUE THREAD

**Issue by Cyber1000** [docker/docker.github.io#7104]
I have a question on the documentation: https://docs.docker.com/config/containers/resource_constraints/#prevent-a-container-from-using-swap

In "PREVENT A CONTAINER FROM USING SWAP" it says:

> If --memory and --memory-swap are set to the same value, this prevents containers from using any swap. 

But wouldn't that be the same if I set memory-swappiness to 0?
It was not 100% clear for me from this part of documention.

Thanks!

**Comment by Cyber1000** [comment]
I'll ask this question on docker-forums, since it seems more appropriate there. If documentation needs changes to be clear I come back to this issue. Otherwise I'll close here. Thanks!

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
