### ISSUE TITLE
Feedback for: engine/swarm/swarm-tutorial/create-swarm.md

### ISSUE THREAD

**Issue by undying** [docker/docker.github.io#711]
File: [engine/swarm/swarm-tutorial/create-swarm.md](https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/)

Hello!
It would be nice to provide information about creating new swarm cluster with multiple managers and how to guarantee the fault tolerance of one of them.
This information described about old style swarm, but not described for new one.

**Comment by mstanleyjones** [comment]
Sorry for not getting back to you sooner! The information you are looking for already exists at https://docs.docker.com/engine/swarm/manage-nodes/. You'll probably find lots of good info there!
