### ISSUE TITLE
--default-address-pool option missing from dockerd documentation

### ISSUE THREAD

**Issue by jakegatsby** [docker/docker.github.io#7127]
Good day,

The  `--default-address-pool` option introduced in 18.06 is missing from the dockerd documentation.  Thanks for your time.

File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
