### ISSUE TITLE
improper content in sample YAML file

### ISSUE THREAD

**Issue by WellspringCS** [docker/docker.github.io#7128]
File: [docker-for-windows/kubernetes.md](https://docs.docker.com/docker-for-windows/kubernetes/)

the build option is (as I understand it) invalid content in a YAML file used with a stack deploy call. The error "Ignoring unsupported options: build" is returned if this demo file is used.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the issue is old, some context may have been lost. The issue appears to no longer exist in the current topic. If the issue still does exist, please let us know.
