### ISSUE TITLE
Feedback for: engine/reference/commandline/cp.md

### ISSUE THREAD

**Issue by jubins** [docker/docker.github.io#713]
File: [engine/reference/commandline/cp.md](https://docs.docker.com/engine/reference/commandline/cp/)

It would be better if doc gives some example on how to use cp. I'm sure many other people would be facing this issue as well.

I am using Docker Toolkit version 1.12.3 build 6b644ec on Windows 10 and just want to copy files from my local computer into docker container. So I am running below command:
 `$ docker cp OneDrive/Documents/GitHub/Machine-Learning-Project/DataSets/DataSets.tar \ $HOME/tf_files:/tf_files`

and it gives below error:
`unexpected status code from daemon: 301`

![image](https://cloud.githubusercontent.com/assets/18559677/20613008/8eb05430-b28d-11e6-9d91-86f71b4c7bd4.png)

How can I copy files from my local computer into docker container at this path: `$HOME/tf_files/`?

**Comment by mstanleyjones** [comment]
Just to get you going, you need the container name at the start of the second argument:

`docker cp path/to/file CONTAINER_NAME:/path/in/container/`

So in your case:
```
$ docker cp OneDrive/Documents/GitHub/Machine-Learning-Project/DataSets/DataSets.tar YOUR_CONTAINER:/tf_files/

$ docker cp $HOME/tf_files/* YOUR_CONTAINER:/tf_files/
```

(assuming I understand your intentions).

The command-line references are actually maintained in `docker/docker`. Please file the issue there. I would encourage you to try your hand at updating the reference, too. Thanks!
