### ISSUE TITLE
Remove fixed pixel font size from CSS

### ISSUE THREAD

**Issue by robcresswell** [docker/docker.github.io#7130]
### Problem description

The documentation website uses fixed 14px font sizes in many places; this means browser font size settings do not apply. This is a big accessibility problem for people who do not have perfect eyesight.

### Problem location

https://github.com/docker/docker.github.io/search?q=14px&unscoped_q=14px

### Project version(s) affected

N / A

### Suggestions for a fix

Change the root font size (probbly defined in `html` or `body` to 1rem, and remove all other instances of hardcoded 14px. Then alter any other headers to scale appropriately; it's fairly common to do something like 3rem for h1, 2rem for h2, 1.5rem for h3, 1.25 for h4, and 1rem for h5 / h6, but these can just fit your websites brand image; the size itself is not important, just that it is **relative to the browsers font size definition** not a hardcoded value.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
