### ISSUE TITLE
Clarify that services don't need to be attached to special networks

### ISSUE THREAD

**Issue by programmerq** [docker/docker.github.io#7131]
File: [ee/ucp/interlock/deploy/configure.md](https://docs.docker.com/ee/ucp/interlock/deploy/configure/)

HRM users expect to have to attach services to networks that have the `com.docker.ucp.mesh.http: true` label. Interlock does not require this. Add a clarifying note that makes this clear.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by programmerq** [comment]
This is still relevant, and could be reopened (I don't seem to have permission to reopen it)
