### ISSUE TITLE
Step 2, where one should be is unclear.

### ISSUE THREAD

**Issue by jerturowetz** [docker/docker.github.io#7132]
Whether on the users cloud homepage, the users settings page or the users repository page, there is no left hand navigation and there is no notifications section.

File: [docker-cloud/slack-integration.md](https://docs.docker.com/docker-cloud/slack-integration/)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
