### ISSUE TITLE
Docker directory for mac missing in antivirus exclusion document

### ISSUE THREAD

**Issue by kmddevdani** [docker/docker.github.io#7136]
File: [engine/security/antivirus.md](https://docs.docker.com/engine/security/antivirus/)

The document mentions the directories that should be excluded from antivirus software scans for **Windows and Linux**. But it misses information about which directory should be excluded from antivirus software scans for **Mac**.

I would suggest this to be:
$HOME/Library/Containers/com.docker.docker/

... but I am not an expert at all... Any better suggestions?

**Comment by ahh-docker** [comment]
Pull request #7137 resolves this issue.
