### ISSUE TITLE
404 at: /swarm/docker-compose.yml/

### ISSUE THREAD

**Issue by deniswal** [docker/docker.github.io#714]
URL: /swarm/docker-compose.yml/

Missing page...

**Comment by johndmulhausen** [comment]
Where is there a link to that URL? Where in the docs would you normally expect it to land? We can add a redirect with a little more info.

**Comment by johndmulhausen** [comment]
@deniswal ^

**Comment by deniswal** [comment]
I was browsing the swarm documentation (From the top of my head, a tutorial about swarm).
I found this missing page and clicked on the report link.
Sorry for the lack of context, I thought the link would bundle it when reporting.

I now have some difficulties to backtrace the path I took three days ago.

Denis
