### ISSUE TITLE
The doc is deprecated

### ISSUE THREAD

**Issue by beuleal** [docker/docker.github.io#7141]
File: [docker-cloud/getting-started/your_first_node.md](https://docs.docker.com/docker-cloud/getting-started/your_first_node/)

Im trying to create a node using the following tutorial, but it doesnt correpond with the actual version.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The issue appears to be no longer applicable to the current docs. Closing the issue. If the issue still exists, please let us know.
