### ISSUE TITLE
storage/volumes.md: 'Use a read-only volume' text refers to bind-mounts, should refer volumes

### ISSUE THREAD

**Issue by mhaas** [docker/docker.github.io#7142]
File: [storage/volumes.md](https://docs.docker.com/storage/volumes/)

The section "Use a read-only" volume currently starts with the following text:

> For some development applications, the container needs to write into the bind mount so that changes are propagated back to the Docker host. At other times, the container only needs read access to the data. 

I find this very confusing: the entire document is about volume, so bind mounts should not be mentioned in this context. If volumes are used, there is no such thing as 'changes' which 'are propagated back to the Docker host', especially if a storage driver other than 'local' is used.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
