### ISSUE TITLE
storage/volumes.md: No mention of permission handling

### ISSUE THREAD

**Issue by mhaas** [docker/docker.github.io#7143]
File: [storage/volumes.md](https://docs.docker.com/storage/volumes/)

I'd like to request that a note on handling of permissions is added to the volumes documentation.

If a the mount destination does not exist in the image, the destination will always be created with root ownership even if the `-u` argument is given to `docker run`. If the destination exists, then the original owner and group is retained.

The reason for the request is that there is a lot of confusion regarding permissions and storage in Docker (usually relating to bind mounts), so this should be as clear as possible how the system behaves under which circumstances.

**Comment by ksze** [comment]
Not just permission, but also ownership.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
