### ISSUE TITLE
Docker Get Started Part 6 refers to discontinued features

### ISSUE THREAD

**Issue by dpboard** [docker/docker.github.io#7146]
File: [get-started/part6.md](https://docs.docker.com/get-started/part6/)

Hello,

Following the getting started guide, all was good until I got to part 6 and then everything seemed to go off the rails. It seems the guide refers to 'swarm mode' in 'docker cloud' which appear to have been recently discontinued. This is very confusing for novice users such as myself. I feel a 'getting started' guide being even slightly out of date is a disaster, as it is liable to turn off new users from the technology.

**Comment by justinclift** [comment]
Ugh, that's not good.  I've just been going through the Getting Started bit myself, discovering `docker-machine` in the earlier section is [now discontinued as well](https://github.com/docker/machine/issues/4537). :frowning: 

Where's the info on swarm mode being discontinued?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This issue appears to be no longer applicable to the current docs. Closing the issue. If the issue still exists, please let us know.
