### ISSUE TITLE
NFS instructions needed for Swarm

### ISSUE THREAD

**Issue by tfoxnc** [docker/docker.github.io#7148]
### Problem description

The Use NFS persistent storage page  is only written for Kubernetes even though NFS volumes are also supported in Swarm.

### Problem location

https://docs.docker.com/ee/ucp/admin/configure/use-nfs-volumes/

### Suggestions for a fix

Instead of /ee/ucp/admin/configure/use-nfs-volumes.md, create /ee/ucp/admin/configure/use-nfs-volumes/nfs-kubernetes.md and /ee/ucp/admin/configure/use-nfs-volumes/nfs-swarm.md and add similar information about NFS and Swarm.

@kavikat discovered this issue and has agreed to fix it.

**Comment by JustinINevill** [comment]
Closing, will be made irrelevant in upcoming refactor.
