### ISSUE TITLE
while performing Post-installation steps for Linux , "~/.docker/"  was  not found

### ISSUE THREAD

**Issue by shahadesneha** [docker/docker.github.io#7158]
************************************************************************************
while performing Post-installation steps for Linux , "~/.docker/"  was  not found
************************************************************************************
Specification of my machine:

OS : Linux 64 bits
redhat-release : Red Hat Enterprise Linux Workstation release 7.5 (Maipo)

Steps to reproduce:

Download the static binary archive. Go to https://download.docker.com/linux/static/stable/ (or change stable to edge or test), choose your hardware platform, and download the .tgz file relating to the version of Docker CE you want to install.

2. Extract the archive using the tar utility. The dockerd and docker binaries are extracted.
$ tar xzvf /path/to/<FILE>.tar.gz

3.  Move the binaries to a directory on your executable path,
$ sudo cp docker/* /usr/bin/

4. Start the Docker daemon:
$ sudo dockerd &

5. Verify that Docker is installed correctly by running the hello-world image.
$ sudo docker run hello-world

Now while performing Post-installation steps for Linux (Manage Docker as a non-root user), "~/.docker/"  was  not found
Also the error message that I am getting is different then what mention here https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

Please through some light on this issue in doc as well

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
