### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by hycind** [docker/docker.github.io#7159]
From this url. https://success.docker.com/article/how-do-i-set-the-docker-daemon-options

It tries to navigate to https://docs.docker.com/engine/reference/commandline/daemon/ which is broken

**Comment by L-Hudson** [comment]
link should point to https://docs.docker.com/config/daemon/

**Comment by ahh-docker** [comment]
@L-Hudson this needs to be updated in the Success article, not in the reference documentation. The correct link for all the options. The links they should refer to are both https://docs.docker.com/config/daemon/ and  https://docs.docker.com/engine/reference/commandline/dockerd. CC: @thaJeztah

**Comment by bermudezmt** [comment]
Hi @hycind - sorry for the delayed response. This is actually a support article, so we have opened up an issue in the applicable repository. Thank you so much for bringing this to our attention!
