### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by smkarlap** [docker/docker.github.io#7164]
Borken link: https://docs.docker.com/v17.09/docker-hub/builds/ 

Source page: https://docs.docker.com/v17.09/engine/userguide/eng-image/dockerfile_best-practices  
Clicked on the link '* More about Automated Builds' under 'Additional resources' at the end of the page.

**Comment by L-Hudson** [comment]
Corrected in the current version of the docs. Closing ticket.
