### ISSUE TITLE
GitHub service hooks

### ISSUE THREAD

**Issue by meyenberger-webapps** [docker/docker.github.io#7168]
I'm new to Docker. So I want to try automatic builds. When I activated GitHub service hooks, I got the following message: https://developer.github.com/changes/2018-04-25-github-services-deprecation/ 

So how would a webhook look like for GitHub? Probably the section "GitHub service hooks" should be updated?

File: [docker-hub/github.md](https://docs.docker.com/docker-hub/github/)

**Comment by lantrix** [comment]
This also seems to apply to the [docker-hub/builds.md](docker-hub/builds.md) documentation which refers to:

> Within GitHub, a Docker integration appears in your repositories Settings > Webhooks & services page

Following the steps to [create an automated build](https://docs.docker.com/docker-hub/builds/#create-an-automated-build) and it no longer creates a service setup. Instead it creates a web hook correctly, however the builds documentation lags.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
