### ISSUE TITLE
Hugo: Early warning about pulling out the relative link support

### ISSUE THREAD

**Issue by bep** [docker/docker.github.io#717]
I'm @bep, the lead maintainer of Hugo.

See https://github.com/spf13/hugo/search?q=SourceRelativeLinksEval&type=Issues&utf8=%E2%9C%93

This query illustrates the approximate situation.

This feature was implemented and merged to support Docker by now two former Docker employees,  @SvenDowideit and @Spf13.

No one is actively maintaining this feature.

So it is left to me.

I have plenty of other issues that are way plenty higher up the ladder, and, to be honest, it isn't the cleanest code I have seen, so unless someone from Docker is coming forward and claiming ownership of that code, I am marking it for deletion in Hugo 0.18.

**Comment by joaofnfernandes** [comment]
Yup, we are now using Jekyll. So feel free to deprecate the feature.

**Comment by johndmulhausen** [comment]
@SvenDowideit @bep Very kind of you guys to check in on us. It's true, we are on Jekyll now. Thanks so much for looking in. :)
