### ISSUE TITLE
It seems that "Docker for Mac" "stable" channel now allows "Kubernetes support" but docs aren't updated

### ISSUE THREAD

**Issue by nfwatsoncom** [docker/docker.github.io#7172]
File: [docker-for-mac/kubernetes.md](https://docs.docker.com/docker-for-mac/kubernetes/)

It seems that "Docker for Mac" "stable" channel now allows "Kubernetes support" but docs aren't updated.

From page:  "Kubernetes support is not included in Docker for Mac Stable releases."  It seems however that current release "8.06.0-ce-mac70 (26399)" supports Kubernetes.  Please update docs (or perhaps I'm mistaken and I don't understand how the pieces fit together).

**Comment by claui** [comment]
This is backed by the [18.06.0-ce-mac70 stable release notes](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-18060-ce-mac70-2018-07-25), where it says:

> - New
>     - Kubernetes Support. You can now run a single-node Kubernetes cluster from the “Kubernetes” Pane in Docker For Mac Preferences and use kubectl commands as well as docker commands. See https://docs.docker.com/docker-for-mac/kubernetes/

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
