### ISSUE TITLE
Table for CMD/ENTRYPOINT contains double rows

### ISSUE THREAD

**Issue by aviv-ebates** [docker/docker.github.io#7177]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

See highlighted below:
![image](https://user-images.githubusercontent.com/37817804/43731563-bf99182a-9963-11e8-80bf-e8b91c6156f9.png)

Second and third rows are identical, except for the names of the parameters:
```
CMD [“exec_cmd”, “p1_cmd”]
CMD [“p1_cmd”,   “p2_cmd”]
```

Unifying them would make the table a little bit clearer.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
