### ISSUE TITLE
Docker for windows: docker-machine create as admin

### ISSUE THREAD

**Issue by andb0t** [docker/docker.github.io#7180]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

On docker for windows, the power shell (or whatever other shell one might be using) has to be initialized with administrator rights. Otherwise `docker-machine create [...]` returns the following error:

```shell
Running pre-create checks...
Error with pre-create check: "Hyper-v commands have to be run as an Administrator"
```

Could you please add that to the (otherwise perfect <3 ) documentation? If you know a work-around I'd be happy to see it of course!

Cheers

**Comment by bardware** [comment]
I'd like to know why Hyper-V and therefore `docker-machine` can only be used by an admin. 
However, on [Stackoverflow](https://stackoverflow.com/a/51607832/577052) there's a workaround

```
Check localgroup by: > net localgroup
Add to Hyper-V Admininstrators: > net localgroup "Hyper-V Administrators" <current username> /add
```

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
