### ISSUE TITLE
IP of docker manager node

### ISSUE THREAD

**Issue by andb0t** [docker/docker.github.io#7181]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

Hi all,
in the docs at `docker-machine ssh myvm1 "docker swarm init --advertise-addr <myvm1 ip>"`, it is not mentioned that the <myvm1 ip> has to be the URL of the myvm1, given by 
docker-machine ls. This wasn't obvious to me, maybe an additional sentence might help? I propose:

> [...] and the second is a worker.
Note that you have to advertise the IP address of the manager node to join manager and workers together, in this case `192.168.99.100`.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
