### ISSUE TITLE
API docs should be available outside of DTR

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#7189]
File: [apidocs/overview.md](https://docs.docker.com/apidocs/overview/)

**Comment by bermudezmt** [comment]
@kavikat This is part of my planned work in the near future. The current DTR (and other API pages) can actually be accessed from here: https://docs.docker.com/reference/ with the DTR API specifically linking to https://docs.docker.com/reference/dtr/2.6/api/.
