### ISSUE TITLE
Docker Trust Docs are Out of Date

### ISSUE THREAD

**Issue by afrazkhan** [docker/docker.github.io#719]
### Problem description

The docs regarding [Docker Trust](https://github.com/docker/docker.github.io/blob/a5e01e1844a6eb57e18fb3599e0e21f5dbc03da4/engine/security/trust/content_trust.md) seem to be out of date.

For example, there's talk of automatic password generation when first using Trust, but it seems that root keys are passwordless by default, and now embedded in json in `.docker/trust/tuf/[REGISTRY]/library/[IMAGE]/metadata`

It is unclear how any of this works in relation to consumers accepting keys, or which keys should be shared. It is difficult to figure this information out, since the structure seems to have changed so much.

### Problem location

All documentation [here](https://github.com/docker/docker.github.io/blob/a5e01e1844a6eb57e18fb3599e0e21f5dbc03da4/engine/security/trust/content_trust.md), and linked to from that page.

### Project version(s) affected

Testing with 1.12.x

### Suggestions for a fix

Update the docs :)

I'm happy to write them, but need a starting point, as currently I'm a bit lost using the current docs. The most crucial information needed being; where is public key that needs to be shared to consumers of images? And how can passwords be enabled?

**Comment by mstanleyjones** [comment]
@cyli do you have any info about this so that I can get started?

**Comment by cyli** [comment]
> For example, there's talk of automatic password generation when first using Trust, but it seems that root keys are passwordless by default

That's a huge bug if that's the case.  If Docker detects that you have a root key already (you've previously pushed some other repo with trust enabled), it won't generate a new one, but whenever one is generated it should ALWAYS request a passphrase.

Could you please run a content trust operation with `-D`?  Perhaps `docker -D push <some repo>`, and paste the results?

< and now embedded in json in .docker/trust/tuf/[REGISTRY]/library/[IMAGE]/metadata

Those are public keys only.  The private keys continue to live in `~/.docker/trust/private`.

https://github.com/docker/docker.github.io/blob/a5e01e1844a6eb57e18fb3599e0e21f5dbc03da4/engine/security/trust/trust_key_mng.md is still correct in terms of what the keys do.

**Comment by cyli** [comment]
cc @riyazdf @endophage @n4ss for visibility

**Comment by afrazkhan** [comment]
This was either something to do with VPN / networking at the time, or has been fixed since I filed this. Just tried it again, and I'm getting the expected behaviour.

**Comment by cyli** [comment]
@afrazkhan Thank you for checking again!  Closing this for now - please re-file if you encounter any issues again.
