### ISSUE TITLE
Kubernetes docs don't describe how to work with services

### ISSUE THREAD

**Issue by paultiplady** [docker/docker.github.io#7195]
File: [docker-for-mac/kubernetes.md](https://docs.docker.com/docker-for-mac/kubernetes/)

From reading blog posts and digging around, it seems that `LoadBalancer` services are proxied to localhost, but this isn't documented here, and it's not working for me, so I'm not sure if I'm missing something.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
