### ISSUE TITLE
Feedback for: engine/getstarted/step_four.md

### ISSUE THREAD

**Issue by ashish-logmaster** [docker/docker.github.io#720]
File: [engine/getstarted/step_four.md](https://docs.docker.com/engine/getstarted/step_four/)

Very unix/osx specific. esp the "touch fname". You might want to try to allow folks on windows to follow as well.  All prior pages works great, this page needs some work.

**Comment by mstanleyjones** [comment]
Thanks for the feedback. Have a look at #870 and let me know what you think.

**Comment by ashish-logmaster** [comment]
Thanks, looks great
