### ISSUE TITLE
Python/Django version mismatch

### ISSUE THREAD

**Issue by robkautz** [docker/docker.github.io#7206]
Just heads up, running django <2.0 with python 3.7 did not work for me, and you might want to make versions a bit more specific in the docs. I think python 3.7 introduced something that django did not handle until after version 2.0. I tried following this guide again, specified python 3.6 and django 2.1 and everything worked as expected 😄 

File: [compose/django.md](https://docs.docker.com/compose/django/)

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
