### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by bjozzi** [docker/docker.github.io#7211]
"Registry API" link is broken
https://docker.github.io/registry/deploying/#next-steps

**Comment by ahh-docker** [comment]
Link needs to be https://docs.docker.com/registry/spec/api/

**Comment by bermudezmt** [comment]
@bjozzi sorry for the delayed response. This  has been fixed via https://github.com/docker/docker.github.io/commit/6a1f9f919327. Thank you for reporting the issue!
