### ISSUE TITLE
Add instructions info for who are using Docker Toolbox

### ISSUE THREAD

**Issue by tadashi-hata** [docker/docker.github.io#7214]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)

Hi,

I'm starting my journey to learn Docker and when I was doing the get-started part 3 I faced the follow error when tried to run **docker swarm init**
```
Error response from daemon: could not choose a IP address to advertise sinse the system has multiple addresses in different interfaces ....
```
I'm using Docker Toolbox in a windows 8 system (I know that it not the best choice :P)
Then I googled that and found a soluction using the option --advertise-addr

```
$ docker swarm init --advertise-addr <docker-machine ip>:2377
```

I don't know if this is the rigth soluction but it worked for me and I think I could help other folks too.

Thanks in advance!
Best regards,

Tadashi Hata.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
