### ISSUE TITLE
update engine api docs for docker-ce 18.06 api v1.38

### ISSUE THREAD

**Issue by andrewhsu** [docker/docker.github.io#7219]
### Problem description

Docker API docs page needs to be updated to reflect the new API v1.38 changes for docker-ce 18.06.0 release.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/develop/sdk/#api-version-matrix

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/engine/api/v1.38/

### Project version(s) affected

docker-ce 18.06

### Suggestions for a fix

need to update the docs similar to https://github.com/docker/docker.github.io/pull/6288

cc @thaJeztah

**Comment by sudo-bmitch** [comment]
Along with this, we also need an archive created for 18.03. Ref: https://github.com/docker/docker.github.io/blob/master/README.md#creating-a-new-archive

**Comment by L-Hudson** [comment]
Fixed since filed. Closing ticket.
