### ISSUE TITLE
Spurious greater than sign.

### ISSUE THREAD

**Issue by RobertKielty** [docker/docker.github.io#7220]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

The following Notes has a spurious greater than (>) character **"as well as > being"**

Note: As promising as overlay is, the feature is still quite young and should not be used in production. Most notably, using overlay can cause excessive inode consumption (especially as the number of images grows), as well as > being incompatible with the use of RPMs.

This should be removed.

I would have fixed this myself but the **Edit This Page** link 404s 

It currently points to 
[https://github.com/docker/docker.github.io/edit/master/engine/reference/commandline/dockerd.md]
(https://github.com/docker/docker.github.io/edit/master/engine/reference/commandline/dockerd.md)

**Comment by ahh-docker** [comment]
Work completed here: https://github.com/docker/cli/pull/1565

**Comment by ahh-docker** [comment]
Once merged with docker/cli repo, I'll mark this as done.

**Comment by ahh-docker** [comment]
Merged. Closing.

**Comment by bermudezmt** [comment]
@seemethere sorry I forgot to bring this up during our meeting. This does appear to be fixed within `docker/cli` via https://github.com/docker/cli/pull/1565. In this case, do we need to regenerate the YAML file to port over the change to `docs.docker.com`? This is still an issue here: https://docs.docker.com/engine/reference/commandline/dockerd/ cc: @shampabh

**Comment by seemethere** [comment]
@bermudezmt It probably will require a regeneration of the YAML
