### ISSUE TITLE
Docker images not visible in swarm

### ISSUE THREAD

**Issue by randallk** [docker/docker.github.io#7221]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

I had to run 
 docker pull privateamerica/get-started:part2
for the image to be visible in the swarm manager.  This isn't mentioned in the docs.  The images on the host machine aren't visible to the swarm manager, perhaps there's a way to do that as well.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
