### ISSUE TITLE
Clarify if the docker swarm mesh prefers a local task if it is running on that node

### ISSUE THREAD

**Issue by igor-petruk** [docker/docker.github.io#7222]
File: [engine/swarm/ingress.md](https://docs.docker.com/engine/swarm/ingress/)

The doc says 

> The routing mesh enables each node in the swarm to accept connections on published ports for any service running in the swarm, even if there’s no task running on the node. 

Please clarify what happens if it is **opposite** - the node does run the task. Does the mesh guarantee the selection of the local task? Will it at least prefer it on best-effort?

**Comment by trapier** [comment]
To answer the question:

> Does the mesh guarantee the selection of the local task? Will it at least prefer it on best-effort?

Answer is no.  The ingress routing mesh uses a round-robin load balancing scheme which has no preference for endpoint location.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
