### ISSUE TITLE
This guide should show how to create Django/Postgres project with Django waiting for postgres to start. 

### ISSUE THREAD

**Issue by derwustenfuchs** [docker/docker.github.io#7225]
File: [compose/django.md](https://docs.docker.com/compose/django/)

This example has very little use as nobody creates new django project inside running container but rather build container with earlier created django application. This tutorial would be perfect to present compose start-up order with bash script waiting for postgres container and only after that starting django app.

**Comment by perk11** [comment]
I agree. I saw a person who was new to docker use this tutorial and add their whole project to the container, because that's what the tutorial says. And then they were wondering why Docker is so slow for them.
There should be a mention of ADD not being required.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!

**Comment by snoop2head** [comment]
I definetely agree to this point.
