### ISSUE TITLE
don't recommend docker cloud here

### ISSUE THREAD

**Issue by clausdenk** [docker/docker.github.io#7226]
File: [machine/get-started-cloud.md](https://docs.docker.com/machine/get-started-cloud/)
At the head of the page users are recommended to go to the docker cloud service "as the most up-to-date way to run Docker on your cloud providers" which is not an option anymore, right?

**Comment by anujkumar-df** [comment]
Seems so, I was checking its feasibility and all the goodies have been taken away.

**Comment by aliceminotto** [comment]
I support this change, the warning it's still up and it doesn't even point to the migration doc, but to the main explanation. This should really go away if the situation changed 5 months ago.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
