### ISSUE TITLE
Swarm mode key concepts - incorrect word used?

### ISSUE THREAD

**Issue by thernstig** [docker/docker.github.io#7227]
File: [engine/swarm/key-concepts.md](https://docs.docker.com/engine/swarm/key-concepts/)

I am wondering if the following line has used an incorrect word:

> A key difference between standalone containers and swarm services is that only swarm managers can manage a **swarm**, while standalone containers can be started on any daemon.

I am thinking it should be:

> A key difference between standalone containers and swarm services is that only swarm managers can manage a **swarm service**, while standalone containers can be started on any daemon.

It is possible both are correct though.

Another note: Generally I found it hard to undersand if the documentation says there is a "service" and a "swarm service" i.e. if the differentiate.

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
