### ISSUE TITLE
Cannot mount the persistent data volume on single node swarm with replicated service

### ISSUE THREAD

**Issue by krufab** [docker/docker.github.io#7229]
File: [docker-for-azure/persistent-data-volumes.md](https://docs.docker.com/docker-for-azure/persistent-data-volumes/)

Please, do specify that in case of a single node swarm (i.e. in a development phase), it is not possible to mount the the same persistent data volume on replicated services. Only one replica will be able to mount the volume, while the other will fail to be deployed with the following error:
`"VolumeDriver.Mount: mount failed: exit status 32
output="mount error(16): Resource busy\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs)\nmount: mounting //XXXXXX.file.core.windows.net/uploaded-files on /mnt/cloudstor/uploaded-files failed: Resource busy\n""`

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
