### ISSUE TITLE
Clarification regarding `dockremap` subuid/subguid addition

### ISSUE THREAD

**Issue by amitsaha** [docker/docker.github.io#7232]
File: [engine/security/userns-remap.md](https://docs.docker.com/engine/security/userns-remap/)

Consider this warning:

> Warning: Some distributions, such as RHEL and CentOS 7.3, do not automatically add the new group to the /etc/subuid and /etc/subgid files. You are responsible for editing these files and assigning non-overlapping ranges, in this case. This step is covered in Prerequisites.

Since `dockremap` is a system user (original [commit](https://github.com/moby/moby/pull/21266/commits/c18e7f3a0419e35aeab4eefa51f3c17fbd72381f)) , it is the behavior of `adduser` to not add entries to `/etc/subuid` and `/etc/subgid`. Hence, the warning regarding the behavior being an issue on CentOS/RHEL seems incorrect? It is really a documented/expected behavior i think?

**Comment by L-Hudson** [comment]
Issue will be addressed in editing pass. Closing ticket.
