### ISSUE TITLE
registry/insecure: Ambiguous format for self-signed certificates

### ISSUE THREAD

**Issue by Diftraku** [docker/docker.github.io#7243]
### Problem description

When following the steps to generate a self-signed certificate for the registry, there is no mention of what format the certificate must be in. The file extension `.crt` can easily lead you to believe it is a certificate in DER-format, yet Docker-daemon and the registry expects this to be in PEM-format.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/registry/insecure/#use-self-signed-certificates

### Project version(s) affected

N/A or unknown, all tested machines were running Docker 18.06.0-ce, build 0ffa825

### Suggestions for a fix

The documentation should explicitly state the certificates need to be in PEM-format, to avoid any confusion about the certificate's format the filename might cause.

**Comment by L-Hudson** [comment]
@dmp42 , can you take a look at this and let me know if this is a change that you think we should make?

**Comment by L-Hudson** [comment]
closing ticket due to very narrow scope of problem. Generally we don't recommend using self-signed certs.

**Comment by Diftraku** [comment]
The same ambiguity is also present on the instructions on setting up a registry with a trusted CA-signed certificate (https://docs.docker.com/registry/deploying/).

Regardless of what you support or not, the certificate format is ambiguous in both guides.
