### ISSUE TITLE
Create a simple parent image using scratch, confusion over image and static binary

### ISSUE THREAD

**Issue by stevet11** [docker/docker.github.io#7248]
File: [develop/develop-images/baseimages.md](https://docs.docker.com/develop/develop-images/baseimages/)

The example seems to confuse new users.  It makes it look like the building a static linked hello file somehow makes the hello image.

I understand that it does not, but you do build the image before the steps to compile and link the static linked binary.  Have the static link hello steps before the Dockerfile build that uses it.  And maybe call the static linked file something else?  hello_static?  hello_binary?  

First time submitting an issue.

**Comment by L-Hudson** [comment]
addressed in subsequent update. Closing ticket.
