### ISSUE TITLE
Random emoji on docker-cloud/getting-started/deploy-app/12_data_management_with_volumes.md

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#725]
File: [docker-cloud/getting-started/deploy-app/12_data_management_with_volumes.md](https://docs.docker.com/docker-cloud/getting-started/deploy-app/12_data_management_with_volumes/)

Gear icon in a snippet on this page.

**Comment by sanscontext** [comment]
When I tested this, it actually managed to show a gear icon in the terminal when a long-running startup was in progress. Trying to find something that takes long enough to start up to re-validate.

**Comment by sanscontext** [comment]
@johndmulhausen confirmed: this displays `u2699`, the `gear` character when stopping. I'm not sure why it's rendering so fancy in the docs. Do you want to leave this open to investigate un-fancifying it?

**Comment by johndmulhausen** [comment]
I suppose the fancification is appropriate in this case. Sorry for the noise!
