### ISSUE TITLE
GitLab Runner + docker-machine on AWS EC2 ignores the environment variables

### ISSUE THREAD

**Issue by gerdzhikov** [docker/docker.github.io#7250]
File: [machine/drivers/aws.md](https://docs.docker.com/machine/drivers/aws/)

I've installed the gitlab runner on an EC2 instance running AMI amzn-ami-2018.03.a-amazon-ecs-optimized (ami-10e6c8fb)

Docker environment (installed via yum)

- docker.x86_64                         18.03.1ce-5.0.amzn1           @amzn-updates
- gitlab-runner.x86_64                  11.1.0-1                      @runner_gitlab-runner

Here the runner configuration:
`/etc/gitlab-runner/config.toml`
```
concurrent = 2
check_interval = 0
environment = ["DOCKER_DRIVER=overlay2"]
log_level="debug"

[[runners]]
  name = "Docker AWS Runner (gitlab-runner)"
  url = "https://gitlab.com/"
  token = "*******************"
  executor = "docker+machine"
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = true
    disable_cache = true
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    Type = "s3"
    ServerAddress = "s3.amazonaws.com"
    BucketName = "****-******-******-cachebucket-**********"
    BucketLocation = "eu-central-1"
    Shared = true
  [runners.machine]
    IdleCount = 0
    IdleTime = 1800
    MaxBuilds = 2
    MachineDriver = "amazonec2"
    MachineName = "gitlab-docker-machine-%s"
    MachineOptions = [
      "amazonec2-instance-type=t2.micro",
      "amazonec2-region=eu-central-1",
      "amazonec2-security-group=devops-gitlab-runner-RunnersSecurityGroup",
      "amazonec2-use-private-address=true",
      "amazonec2-iam-instance-profile=devops-gitlab-runner-RunnersInstanceProfile-BMX*******",
      "amazonec2-root-size=8"
    ]
    OffPeakTimezone = "Europe/Berlin"
    OffPeakPeriods = ["* * 0-9,18-23 * * mon-fri *", "* * * * * sat,sun *"]
    OffPeakIdleCount = 0
    OffPeakIdleTime = 1200
```
... and the environment:
`/etc/environment `
```
AWS_VPC_ID=vpc-**********
AWS_ZONE=b
AWS_REGION=eu-central-1
AWS_SUBNET_ID=subnet-**********
```
I've checked the environment variables via connecting via SSH to the host and they were set according the evironment file.

According to the documentation I've expected that the VPC, Subnet and Availability zone will be resolved from the environment variables, but they were completely ignored and the default VPC, Subnet and Az were applied.

**Comment by L-Hudson** [comment]
Technical problem rather than a documentation problem. Closing ticket.
