### ISSUE TITLE
Perhaps an issue with Django version?

### ISSUE THREAD

**Issue by dixonpete** [docker/docker.github.io#7253]
https://docs.docker.com/compose/django/#connect-the-database

This documentation no longer works as written. When the command 'docker-compose up' is given I see this is the server log:

test_db_1 is up-to-date
Creating test_web_1 ... done
Attaching to test_db_1, test_web_1
db_1   | The files belonging to this database system will be owned by user "postgres".
db_1   | This user must also own the server process.
db_1   | 
db_1   | The database cluster will be initialized with locale "en_US.utf8".
db_1   | The default database encoding has accordingly been set to "UTF8".
db_1   | The default text search configuration will be set to "english".
db_1   | 
db_1   | Data page checksums are disabled.
db_1   | 
db_1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1   | creating subdirectories ... ok
db_1   | selecting default max_connections ... 100
db_1   | selecting default shared_buffers ... 128MB
db_1   | selecting dynamic shared memory implementation ... posix
db_1   | creating configuration files ... ok
db_1   | running bootstrap script ... ok
db_1   | performing post-bootstrap initialization ... ok
db_1   | syncing data to disk ... ok
db_1   | 
db_1   | Success. You can now start the database server using:
db_1   | 
db_1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1   | 
db_1   | 
db_1   | WARNING: enabling "trust" authentication for local connections
db_1   | You can change this by editing pg_hba.conf or using the option -A, or
db_1   | --auth-local and --auth-host, the next time you run initdb.
db_1   | ****************************************************
db_1   | WARNING: No password has been set for the database.
db_1   |          This will allow anyone with access to the
db_1   |          Postgres port to access your database. In
db_1   |          Docker's default configuration, this is
db_1   |          effectively any other container on the same
db_1   |          system.
db_1   | 
db_1   |          Use "-e POSTGRES_PASSWORD=password" to set
db_1   |          it in "docker run".
db_1   | ****************************************************
db_1   | waiting for server to start....2018-08-22 17:58:48.596 UTC [43] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2018-08-22 17:58:48.646 UTC [44] LOG:  database system was shut down at 2018-08-22 17:58:48 UTC
db_1   | 2018-08-22 17:58:48.656 UTC [43] LOG:  database system is ready to accept connections
db_1   |  done
db_1   | server started
db_1   | ALTER ROLE
db_1   | 
db_1   | 
db_1   | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1   | 
db_1   | 2018-08-22 17:58:48.756 UTC [43] LOG:  received fast shutdown request
db_1   | waiting for server to shut down....2018-08-22 17:58:48.758 UTC [43] LOG:  aborting any active transactions
db_1   | 2018-08-22 17:58:48.759 UTC [43] LOG:  worker process: logical replication launcher (PID 50) exited with exit code 1
db_1   | 2018-08-22 17:58:48.759 UTC [45] LOG:  shutting down
db_1   | 2018-08-22 17:58:48.820 UTC [43] LOG:  database system is shut down
db_1   |  done
db_1   | server stopped
db_1   | 
db_1   | PostgreSQL init process complete; ready for start up.
db_1   | 
db_1   | 2018-08-22 17:58:48.867 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2018-08-22 17:58:48.867 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2018-08-22 17:58:48.883 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2018-08-22 17:58:48.908 UTC [61] LOG:  database system was shut down at 2018-08-22 17:58:48 UTC
db_1   | 2018-08-22 17:58:48.919 UTC [1] LOG:  database system is ready to accept connections
web_1  | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feae53ab510>
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
web_1  |     autoreload.raise_last_exception()
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
web_1  |     six.reraise(*_exception)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
web_1  |     raise value.with_traceback(tb)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
web_1  |     apps.populate(settings.INSTALLED_APPS)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
web_1  |     app_config = AppConfig.create(entry)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
web_1  |     module = import_module(entry)
web_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 4, in <module>
web_1  |     from django.contrib.admin.filters import (
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/filters.py", line 10, in <module>
web_1  |     from django.contrib.admin.options import IncorrectLookupParameters
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 13, in <module>
web_1  |     from django.contrib.admin import helpers, widgets
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 152
web_1  |     '%s=%s' % (k, v) for k, v in params.items(),
web_1  |     ^
web_1  | SyntaxError: Generator expression must be parenthesized

**Comment by L-Hudson** [comment]
updated in current version. Thanks!
