### ISSUE TITLE
Offline UCP installer page missing 3.0.4 versions

### ISSUE THREAD

**Issue by ericsmalling** [docker/docker.github.io#7259]
File: [ee/ucp/admin/install/install-offline.md](https://docs.docker.com/ee/ucp/admin/install/install-offline/)

https://packages.docker.com/caas/ucp_images_3.0.4.tar.gz exists but is not linked here (nor are other architecture versions)

**Comment by bermudezmt** [comment]
@ericsmalling you can download that specific offline package via https://docs.docker.com/datacenter/ucp/3.0/guides/admin/install/install-offline/.
