### ISSUE TITLE
Feedback for: engine/reference/glossary.md

### ISSUE THREAD

**Issue by tianqig** [docker/docker.github.io#726]
File: [engine/reference/glossary.md](https://docs.docker.com/engine/reference/glossary/)

Very useful glossary to help me to understand your terms. Suggest to add **Docker for Mac**

Thanks

**Comment by mstanleyjones** [comment]
@londoncalling can you add D4M and D4M definitions?

**Comment by londoncalling** [comment]
@tianqig thanks for the feedback! Great suggestions.

We added [Docker for Mac](https://docs.docker.com/engine/reference/glossary/#docker-for-mac) and [Docker for Windows](https://docs.docker.com/engine/reference/glossary/#docker-for-windows) to the [glossary](https://docs.docker.com/engine/reference/glossary/) some time ago now per your idea, so I'll close this issue.
