### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by mkrajaci** [docker/docker.github.io#7265]
File: [compose/django.md](https://docs.docker.com/compose/django/)

Tutorial missing note about required preinstalled Docker-compose.

**Comment by cyroxx** [comment]
I just checked, the second sentence of the tutorial reads: "Before starting, install Compose."

**Comment by thaJeztah** [comment]
Thanks for checking @cyroxx - looks indeed like no change is needed.

Let me close this issue, but feel free to continue the conversation
