### ISSUE TITLE
chucksums for offline UCP install files?

### ISSUE THREAD

**Issue by programmerq** [docker/docker.github.io#7269]
File: [ee/ucp/admin/install/install-offline.md](https://docs.docker.com/ee/ucp/admin/install/install-offline/)

Are checksums available for the published tarballs? Where can those be found?

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
