### ISSUE TITLE
Documentation update or Issue ? - Exception "no matching manifest for unknown"

### ISSUE THREAD

**Issue by dasariramacharan** [docker/docker.github.io#7273]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

Env: Windows 10 Pro 
        Docker CE 18.06.0
        using  Windows containers Mode

Command executed - as per getting started steps            

> docker build -t friendlyhello .

I get exception "no matching manifest for unknown...."

Switched to linux containers and the build command works fine.

Suggest updating documentation that 
1) we should be using linux containers to run the getting started app on windows 10
2) there is a dot at the end of the command. i hope it was explained why it is required.
3) when i run "docker image ls" command after the build step i see 2 images one is friendlyhello which is the image just created and also one more image "python"  (not mentioned in documentation)
4) also talk about windows defender/antivirus notification for vpnkit when trying to run container for the first time how much security is needed for running this app or in general reference for how to pick which options to choose of the available - allow on private , allow on public 

Thanks for the tutorials.

Please suggest otherwise.

**Comment by Oxymoron290** [comment]
+1

**Comment by ashokjha** [comment]
I am also getting the error in Window 10 Pro environment.

![image](https://user-images.githubusercontent.com/633452/49730303-f8db8080-fc9d-11e8-9987-c7c2409e9235.png)

**Comment by ashokjha** [comment]
After doing below steps re executed the command and found working.
1. reinstall docker
2. logged-in
3. install git

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The issue appears to be no longer applicable to the current docs. If you think the issue is still applicable, please let us know.
