### ISSUE TITLE
Kubernetes is now in Docker for Mac and Windows Stable

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker.github.io#7274]
File: [docker-for-mac/kubernetes.md](https://docs.docker.com/docker-for-mac/kubernetes/)

Please update error message that says it is only in edge

**Comment by rondemena** [comment]
I dont have a mac, and if documentation is incorrect, I could just be changing it.  I did adjust the Windows Getting started and it appears the documentation is updated in most places but the Getting started page.  If I had a mac and could install the release to prove it ... I'd update it.  I would suggest that @ManoMarks you actually edit and submit the code in a PR.

**Comment by ManoMarks** [comment]
I was hoping that a Docker Tech Writer would pick this up but didn't. My current job doesn't let me contribute to projects without approval.

**Comment by rondemena** [comment]
awkward ... so your personal GitHub account on personal time is not allowed in the context of contribution?  Wow - if its google doing this as an underpinned portion of employment ... I am shocked.  I did scope some other spots but the automatons and parameters should be injecting the correct versions on a "rebuild".

**Comment by ManoMarks** [comment]
Honestly I could and it probably wouldn't be an issue but technically I should get approval and it's a lot of hassle. I filed this issue when I worked at Docker and talked to the techwriting team at the time, that was the right way to go and they haven't fixed it yet.

**Comment by aevesdocker** [comment]
Closing issue as it refers to content that has since been removed/reorganised/archived
