### ISSUE TITLE
Promote a Node to Manager

### ISSUE THREAD

**Issue by githubfromgui** [docker/docker.github.io#7281]
In the sentence "_This command targets a docker engine that is a manager in the swarm._ " it should not be "This command targets a docker engine that is **NOT** a manager in the swarm." ?

Because we want to promote a NOT manager to BE a manager.

File: [edge/engine/reference/commandline/node_promote.md](https://docs.docker.com/edge/engine/reference/commandline/node_promote/)

**Comment by L-Hudson** [comment]
Still valid in current version of the docs.

**Comment by ahh-docker** [comment]
PR is here: https://github.com/docker/cli/pull/1578 Being handled by @andrewhsu's team. Fix done.
