### ISSUE TITLE
Updates from HPE Nimble Storage.

### ISSUE THREAD

**Issue by datamattsson** [docker/docker.github.io#7285]
File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/)

**Plugin:** Nemo
**URL:** https://github.com/NimbleStorage/Nemo
**Description:** Nemo is an Open Source Docker Volume plugin built on top of OpenZFS. It aims to be compatible with HPE Nimble Storage Docker Volume plugin to serve as an emulator for Enterprise storage.

**Plugin:** HPE Nimble Storage
**URL:** https://www.hpe.com/us/en/storage/containers.html
**Description:** A volume plug-in that integrates with HPE Nimble Storage arrays. The plug-in abstracts array volume capabilities to the Docker administrator to allow self-provisioning of secure multi-tenant volumes and clones with integrated data protection.

**Plugin:** HPE Cloud Volumes
**URL:** https://cloudvolumes.hpe.com
**Description:** A volume plugin is available for HPE Cloud Volumes customers to take advantage of Enterprise storage in the public cloud. It supports volume placement, QoS Limits, snapshots, clones and the ability to clone or import replicated volumes as Docker Volumes.

**Comment by ahh-docker** [comment]
@drajen: Could you please be more specific on what you're trying to tell us about the documentation and what needs to be changed? Thanks.

**Comment by drajen** [comment]
Thanks for looking at this.

- Nemo is a net new Docker Volume plugin we released some time ago. We'd like to add that to the list of legacy plugins. Nemo is a Docker Volume plugin "emulator" for HPE Nimble Storage arrays. It has other uses too.
- Nimble Storage got acquired by HPE over a year ago. We'd like to have the name changed.
- HPE Cloud Volumes is a new offering from HPE/Nimble where we provide a Docker Volume plugin for both AWS and Azure. We don't have any public facing documentation on that one just yet besides some YouTube videos and blog posts. It will be available shortly.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the information is still applicable, please help create an issue or a PR in the source repo at https://github.com/docker/cli/tree/master/docs/extend
Closing this issue as unable to fix in this repo.
