### ISSUE TITLE
Add section about how to set proxy config in containers

### ISSUE THREAD

**Issue by mplescano** [docker/docker.github.io#7287]
File: [toolbox/faqs/troubleshoot.md](https://docs.docker.com/toolbox/faqs/troubleshoot/)

**Comment by ahh-docker** [comment]
@mplescano: Could you please be more specific about what you're trying to add? Thanks.

**Comment by mplescano** [comment]
I was referring to add examples in how to se proxy configuration in the file ~/.docker/config.json

Regards

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
