### ISSUE TITLE
Feedback for: engine/reference/commandline/stats.md

### ISSUE THREAD

**Issue by nelsonenzo** [docker/docker.github.io#729]
File: [engine/reference/commandline/stats.md](https://docs.docker.com/engine/reference/commandline/stats/)

Docker version 1.8.3, build cedd534-dirty

```docker stats```  returns the following:
```
docker stats
docker: "stats" requires a minimum of 1 argument.
See 'docker stats --help'.

Usage:	docker stats [OPTIONS] CONTAINER [CONTAINER...]

Display a live stream of one or more containers' resource usage statistics
```

**Comment by mstanleyjones** [comment]
I can verify that you can run `docker stats` with no other option in Docker 1.12 and Docker 1.13 RC4. This was added for Docker 1.10: https://github.com/docker/docker/pull/16742

To use this functionality, please upgrade Docker to 1.10 or newer.
