### ISSUE TITLE
Describe the default detach sequence

### ISSUE THREAD

**Issue by tln** [docker/docker.github.io#7306]
File: [engine/reference/commandline/attach.md](https://docs.docker.com/engine/reference/commandline/attach/)

**Comment by nigelpoulton** [comment]
Hi @tln

Do you think changing the following:

To stop a container, use `CTRL-c`. This key sequence sends `SIGKILL` to the container. If `--sig-proxy` is true (the default), `CTRL-c` sends a `SIGINT` to the container. You can detach from a container and leave it running using the `CTRL-p CTRL-q` key sequence.


To this would help? If so I'll propose the clarification.

Use the `CTRL-p` and `CTRL-q` key sequenceo detach from a container and leave it running in the background. Typing `exit` will send a `SIGKILL` to the container's main process and place the container in the `Exited` state.

**Comment by tln** [comment]
I think that stating the default (`ctrl-p ctrl-q`) in the table of options
is ideal. Right now it looks like there is no default.

Putting the detach keys first as you suggest seems like an improvement
since detaching is an important action.  The
rest of your paragraph doesn't match with the previous information about
stopping, SIGKILL, SIGINT etc.
Wouldn't "exit" only work in a shell?  Attach won't be in a shell, usually.

I think the current doc page is sufficient, at the time I viewed the page
last August I believe the ctrl-p ctrl-q sequence
wasn't mentioned on the page at all.

Hope this feedback helps.

**Comment by nigelpoulton** [comment]
> I think the current doc page is sufficient, at the time I viewed the page last August I believe the ctrl-p ctrl-q sequence wasn't mentioned on the page at all.

@tln are you saying you're happy to close this? If not, just let me know what you want adding and I'll look at getting it done.

Thanks again for your input on this one 👍

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. Closing this as stale. If an issue still persists, please help open an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
