### ISSUE TITLE
Specify on which node you should run upgrade

### ISSUE THREAD

**Issue by ekitagawa** [docker/docker.github.io#7319]
File: [ee/dtr/admin/upgrade.md](https://docs.docker.com/ee/dtr/admin/upgrade/)
 
I saw new users getting confused about on which node the upgrade command should run.  It should no matter because UCP knows which worker nodes has replica, but not specifying that on the step caused enough confusion for at least one person (and probably for many other customers)

**Comment by KoryKessel-Docker** [comment]
PR #10139 submitted on 13-January-2020.

**Comment by KoryKessel-Docker** [comment]
Not added to topic to clarify that DTR upgrade command can be run on any available node.
