### ISSUE TITLE
Show how to find a docker plugin

### ISSUE THREAD

**Issue by SimonHeimberg** [docker/docker.github.io#7321]
File: [engine/extend/index.md](https://docs.docker.com/engine/extend/)

The listed page does not tell how to find a docker plugin. There is a list, but it is on the legacy page, so it is probably outdated.

Please list some possibilities how to find docker plugins.
Maybe like  https://store.docker.com/search?category=volume&q=&type=plugin (from https://github.com/docker/docker.github.io/issues/4944#issuecomment-362690431)
Is there a nice possibility in https://hub.docker.com as well?

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This issue appears no longer applicable to the current docs. The current topic informs that plugins can be found as images in Docker Hub or private registries. If you feel this issue is still applicable, please let us know.
