### ISSUE TITLE
I found a broken link and wrong info in doc

### ISSUE THREAD

**Issue by mmmcorpsvit** [docker/docker.github.io#7327]
in https://success.docker.com/article/how-do-i-set-the-docker-daemon-options has broken link: https://docs.docker.com/engine/reference/commandline/daemon/

and at this page wrong info: https://success.docker.com/article/how-do-i-set-the-docker-daemon-options
CentOS 7, in real possible use variable:
```
Environment="DOCKER_OPTS=-H=0.0.0.0:1111 -H unix:///var/run/docker.sock --tlsverify --tlscacert=/home/docker/ca.pem --tlscert=/home/docker/server-cert.pem --tlskey=/home/docker/server-key.pem"

ExecStart=/usr/bin/dockerd $DOCKER_OPTS
```

**Comment by bermudezmt** [comment]
Hi @mmmcorpsvit - sorry for the delayed response. These are actually support articles, so we have opened up an issue in the applicable repository. Thank you so much for bringing this to our attention!

**Comment by trapier** [comment]
@mmmcorpsvit fix should be published within the next two to three business days.  Thanks again!
