### ISSUE TITLE
does killing a container also prune's it?

### ISSUE THREAD

**Issue by gdennie** [docker/docker.github.io#7330]
File: [engine/reference/commandline/container_kill.md](https://docs.docker.com/engine/reference/commandline/container_kill/)

**Comment by nigelpoulton** [comment]
Negative. It sends a `KILL` signal to the container process PID 1 that puts the container into the `Exited` state. I'll propose adding the following to the docs, but can't promise they'll be approved:

**The `docker kill` doc**

Add this to the **Extended description** section.

Most signals sent to a container will stop the container and put it in the `Exited` state. This means it will not be pruned and can possibly be restarted with `docker container start`.

**The `docker container kill` doc**

Change the **Description** section to say "Kill one or more running containers and place them in the `Exited` state."

============

There's also a separate discussion to be had about linking or merging the docs pages for `docker kill` and `docker container kill` (and all other related commands that have new and old syntaxes).

**Comment by craig-osterhout** [comment]
Closing this issue as stale. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
