### ISSUE TITLE
interlock ucp screenshot incorrect

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#7339]
location: https://docs.docker.com/ee/ucp/interlock/deploy/

issue: screenshot on this page says `Routing Mesh`.  UCP 3.0.4 UI says `Layer 7 Routing`:

![2018-09-07-175925_1526x1088_scrot](https://user-images.githubusercontent.com/3613189/45244904-d402f600-b2c7-11e8-94fe-7ecc74617832.png)

**Comment by bermudezmt** [comment]
Fixed by https://github.com/docker/docker.github.io/pull/7379. Thanks, @trapier !
