### ISSUE TITLE
Edit this page link is broken for the engine reference page on the builder.

### ISSUE THREAD

**Issue by jefferys** [docker/docker.github.io#7345]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

The "edit this page" link that appears on the page at https://docs.docker.com/engine/reference/builder/ is broken. It links to https://github.com/docker/docker.github.io/edit/master/engine/reference/builder.md and reports a 404 error. The actual page seems to be in the github.com/docker/cli repo at path docs/reference/builder.md

**Comment by JustinINevill** [comment]
Closing as known issue that will be fixed in upcoming refactor.
