### ISSUE TITLE
Clarify space requirements for `/var`

### ISSUE THREAD

**Issue by quadespresso** [docker/docker.github.io#7347]
### Problem description

It would be helpful to be more explicit when describing the [disk space requirements](https://docs.docker.com/ee/ucp/admin/install/system-requirements/#hardware-and-software-requirements), ie, `/var` in particular.

The reason is that kubelet will respond to `DiskPressure` if the free space drops below the threshold of 1.5Gi (ref: https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#node-conditions )

One example of this is when UCP swarm reports `Calico-node_pod_is_unhealthy:_%!s(<nil>)` for a node.

One possible contributing cause is when `/var/log` is using the same partition as `/var/lib/docker`. If there's a lot of log churn, and the log files aren't being adequately managed, then an excess in log file activity can lead to a DiskPressure condition.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ee/ucp/admin/install/system-requirements/#hardware-and-software-requirements

### Project version(s) affected

UCP 3.0.4 + engine 17.06.2-ee-16

### Suggestions for a fix

As part of planning/design, it would be helpful to have `/var/log` on a partition separate from `/var/lib/docker`. How exactly one should apportion the available disk space for each will be a matter of expected log verbosity, size and frequency of log file rotation, etc. Creating this separation will help to mitigate unexpected DiskPressure conditions. One suggestion might be: 25GiB for `/var/log`, 25-75GB for `/var/lib/docker`.

In the case where the admin chooses to have `/var/log` and `/var/lib/docker` on the same partition (ie, `/var`), they should try to be as generous as possible when allocating disk space. In this instance, an aggregate of 50GB (minimum) to 100GB might be encouraged.

**Comment by bermudezmt** [comment]
@bermudezmt to confirm this has been documented

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
