### ISSUE TITLE
Typo in daemon.json configuration

### ISSUE THREAD

**Issue by KevinClaudius** [docker/docker.github.io#7351]
File: [engine/userguide/networking/index.md](https://docs.docker.com/engine/userguide/networking/)

In the section "DISABLE THE DEFAULT BRIDGE NETWORK", the following daemon.json snippet is provided:

```
"bridge": "none",
"iptables": "false"
```

Using this in daemon.json causes an error when the daemon attempts to start:

```
dockerd[19412]: unable to configure the Docker daemon with file /etc/docker/daemon.json: json: cannot unmarshal string into Go struct field Config.iptables of type bool
```

The correct config might be to remove double quotes around "false":

```
"bridge": "none",
"iptables": false
```

**Comment by jotumn** [comment]
Great job, guys. Still there a year later!

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. I'm not able to find that sample snippet in the current docs anymore. If you still find the snippet in the docs, please let us know.
