### ISSUE TITLE
update dockerd commandline reference with latest doc changes from docker/cli

### ISSUE THREAD

**Issue by andrewhsu** [docker/docker.github.io#7358]
File: [edge/engine/reference/commandline/dockerd.md](https://docs.docker.com/edge/engine/reference/commandline/dockerd/)

needs to be updated based on upstream doc changes in docker/cli, e.g. https://github.com/docker/cli/pull/1314

fyi @AntaresS

**Comment by ahh-docker** [comment]
@andrewhsu does this refer to edge only?

**Comment by andrewhsu** [comment]
the doc changes will specifically be related to 18.09.0

in addition, there will not be any more engine releases to the edge channel, so i think the docs may need a change there as well

**Comment by ahh-docker** [comment]
@JustinINevill please take a look at @andrewhsu's comment about no more edge. We should figure out the best place to put this change.

**Comment by ahh-docker** [comment]
@andrewhsu interesting. @gtardif told me this morning they're release edge for desktop, so they'll be separate releases?

**Comment by JustinINevill** [comment]
@ahh-docker Let's solve the CLI changes first, then you can reserve how extensive the edge changes will need to be and we can scope and schedule that work. @andrewhsu Do we just need to pull in the latest  /cli/docs/reference/commandline/dockerd.md from the 'docker/cli' repo?

**Comment by bermudezmt** [comment]
@ahh-docker @andrewhsu does #7753 address this issue?

**Comment by bermudezmt** [comment]
I'm going to assume this has been resolved.
