### ISSUE TITLE
Docker for Windows: FAQs: clarify how to add certificates

### ISSUE THREAD

**Issue by AndreasFagschlunger** [docker/docker.github.io#7359]
File: [docker-for-windows/faqs.md](https://docs.docker.com/docker-for-windows/faqs/)

e.g. the FAQ tells you to create a directory `<MyRegistry>:<Port>`, that's not possible in Windows since a colon is not allowed in directory names.

Also the tilde (~) is common in Linux, but not in windows - maybe use `%USERPROFILE%` instead?

There is also a discussion about this issue here:
https://github.com/moby/moby/issues/21189

As mentioned there, `C:\ProgramData` would be the right directory?

**Comment by aevesdocker** [comment]
Closing as issue has been fixed
