### ISSUE TITLE
Feedback for: engine/reference/commandline/diff.md

### ISSUE THREAD

**Issue by lekrame** [docker/docker.github.io#736]
File: [engine/reference/commandline/diff.md](https://docs.docker.com/engine/reference/commandline/diff/)

please mention the difference between what 2 things, e.g. the current state vs. the last committed one

**Comment by mstanleyjones** [comment]
Please follow along in https://github.com/docker/docker/pull/29603. Closing this because the source file is in a different repo. Thanks!
