### ISSUE TITLE
Need an external network....

### ISSUE THREAD

**Issue by mpanthofer** [docker/docker.github.io#7360]
File: [ee/ucp/interlock/usage/index.md](https://docs.docker.com/ee/ucp/interlock/usage/)

This example does not appear to work properly without making the demo-network an external network.  As written, proxy can't connect demo service.   

1) update network section of docker-compose.yml ...
networks:
  demo-network:
    external: true

2) Run the following before docker stack deploy step...
docker network create demo-network -d overlay 

3) Launch the stack...
docker stack deploy -c docker-compose.yml demo

**Comment by paigehargrave** [comment]
@mark-church - Hi Mark - this looks like a demo code bug - can you PTAL? Thanks!

**Comment by paigehargrave** [comment]
@ehazlett - Hi Evan - would be able to take a quick look at this? The location may have moved with the re-org'd info, but if it's not correct, I'd like to get it updated. Thank you in advance for any help!

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docs-private/pull/1333

**Comment by traci-morrison** [comment]
Work completed in https://github.com/docker/docs-private/pull/1333.
