### ISSUE TITLE
 repository and tag it as part2

### ISSUE THREAD

**Issue by jimshowalter** [docker/docker.github.io#7361]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

should be:

 repository and tags it as part2

**Comment by ahh-docker** [comment]
@jimshowalter could you be more specific on what needs to be reworded?

**Comment by jshowalter** [comment]
It's currently tag, which isn't correct.

This puts the image in the get-started repository and tag it as part2.

should be:

This puts the image in the get-started repository and tags it as part2.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. Closing this as the get started tutorial has been updated and this issue no longer exists.
