### ISSUE TITLE
In later steps, map port

### ISSUE THREAD

**Issue by jimshowalter** [docker/docker.github.io#7363]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

should be:

In later steps, you will map port

**Comment by ahh-docker** [comment]
@jimshowalter: Could you please be more specific where the line needs to be fixed? Thanks.

**Comment by jimshowalter** [comment]
you will map port

should be:

you will map a port

**Comment by casaulenbo** [comment]
The document has been changed, i even can not find this sentence anymore "you will map port". This issues should be closed.
