### ISSUE TITLE
The result of the command posted here is wrong, should be `docker ps --no-trunc`, not `docker ps`

### ISSUE THREAD

**Issue by tonghuaroot** [docker/docker.github.io#7368]
The result of the command posted here is wrong, should be `docker ps --no-trunc`, not `docker ps`

File: [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/)

Examples
Prevent truncating output
Running docker ps --no-trunc showing 2 linked containers.

$ docker ps

CONTAINER ID        IMAGE                        COMMAND                CREATED              STATUS              PORTS               NAMES
4c01db0b339c        ubuntu:12.04                 bash                   17 seconds ago       Up 16 seconds       3300-3310/tcp       webapp
d7886598dbe2        crosbymichael/redis:latest   /redis-server --dir    33 minutes ago       Up 33 minutes       6379/tcp            redis,webapp/db

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
