### ISSUE TITLE
Feedback for: engine/userguide/networking/default_network/ipv6.md

### ISSUE THREAD

**Issue by xwtqin** [docker/docker.github.io#738]
File: [engine/userguide/networking/default_network/ipv6.md](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)
The graph of the section Routed network enviroment is the same as that of Switched network enviroment?

**Comment by mstanleyjones** [comment]
@mark-church do you have any graphics that would be better for this topic? It seems like somewhere along the way one of the images got lost. I'll go through the history and try to spot it, but you might have better ones anyway.

**Comment by mstanleyjones** [comment]
We found the original image!!! Thank you so much for pointing this out after two years of it being in its current state, @xwtqin ! I'll get a pull request up shortly.
