### ISSUE TITLE
update docker rmi with tags in the example

### ISSUE THREAD

**Issue by jcp78** [docker/docker.github.io#7390]
File: [engine/reference/commandline/rmi.md](https://docs.docker.com/engine/reference/commandline/rmi/)
specifically : https://docs.docker.com/engine/reference/commandline/rmi/#examples

Change the tag in the example to something other than 'latest'.  
If there is a tag like 1.0 then it needs included in the rmi command-
$ docker rmi jcphillips/hello-world:1.0
This caused me issues because I just followed the example and used the repository name with out the tag and it failed.
![image](https://user-images.githubusercontent.com/31142123/45777119-e57ec300-bc22-11e8-84b1-866d72ea6a98.png)

**Comment by sudo-bmitch** [comment]
The above PR makes the latest tag explicit. Hopefully that will be useful in knowing to change `latest` to `1.0` in your situation.
