### ISSUE TITLE
 manifest

### ISSUE THREAD

**Issue by salmanuddinsyed** [docker/docker.github.io#7392]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by ahh-docker** [comment]
@salmanuddinsyed can you please provide the details on what you've found?

**Comment by traci-morrison** [comment]
Thank you for your feedback. There doesn't seem to be enough details in the issue for us to work on. If this really is a documentation issue and I have misunderstood, please reopen it with more information.
