### ISSUE TITLE
interlockpreview/interlock:2.0.0-preview

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#7395]
File: [ee/ucp/interlock/usage/service-clusters.md](https://docs.docker.com/ee/ucp/interlock/usage/service-clusters/)

Is the interlockpreview/interlock:2.0.0-preview image the recommended in a production setup ?

**Comment by bermudezmt** [comment]
Hi @martencassel , the latest copy of the page should reflect the recommended image version now. This was fixed via https://github.com/docker/docker.github.io/pull/7238.
