### ISSUE TITLE
Missing recommended package for Ubuntu install of CS engine

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#74]
The CS Docker engine Ubuntu docs show:

```
Install additional virtual drivers not in the base image.
$ sudo apt-get install -y linux-image-extra-virtual
```

There is a chance they will get devicemapper if the virtual package pulls down a newer version of the kernel that is available.  This puts the users in a non-supported configuration.  It should be:

```
Install additional virtual drivers not in the base image.
$ sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
```

/ping @mbentley

**Comment by johndmulhausen** [comment]
@mbentley Has there been a pull request with commit fefc408 yet? Looks like you were approaching a fix for this!

**Comment by mbentley** [comment]
@johndmulhausen - https://github.com/docker/docker.github.io/pull/103

**Comment by mstanleyjones** [comment]
#103 is still waiting on tech feedback.
