### ISSUE TITLE
Explain the placeholder variables marked with <>

### ISSUE THREAD

**Issue by rickschmoo** [docker/docker.github.io#7413]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

As per https://github.com/docker/machine/issues/4303 , I recommend adding a paragraph:

Command line variables are enclosed with < >. Replace with your local value, e.g. local IP address.

**Comment by duxbuse** [comment]
I totally agree with this, it is not obvious that there isn't some variable loading occurring in the background.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as the older tutorial no longer exists and in the new get started tutorial, the first usage of <> is explained. 
https://docs.docker.com/get-started/03_updating_app/#remove-a-container-using-the-cli
