### ISSUE TITLE
Supported Languages for Docker EE not documented

### ISSUE THREAD

**Issue by bermudezmt** [docker/docker.github.io#7421]
### Problem description

Hello! Do we have documentation anywhere on the site specifying which language(s) are supported in UCP/DTR?? Got a customer question yesterday around if Mandarin was supported. Found https://github.com/docker/orca/blob/master/ui/i18n/zh-cn.json but it wasn't the most straight forward approach - https://docker.slack.com/archives/C02FVEK5M/p1537877794000100

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: docs.docker.com

### Suggestions for a fix

Update overview pages perhaps. TBD with docs team.

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.
