### ISSUE TITLE
I found a broken link at https://docs.docker.com/engine/swarm/services/

### ISSUE THREAD

**Issue by aki-k** [docker/docker.github.io#7435]
On page https://docs.docker.com/engine/swarm/services/ the link "label" in
"In the following example, the service only runs on nodes with the label region set to east." is broken.

The link target is currently: https://docs.docker.com/engine/swarm/engine/swarm/manage-nodes/#add-or-remove-label-metadata but the whole page is missing.

**Comment by bermudezmt** [comment]
Jeez, good find. Fixing this.
