### ISSUE TITLE
docker-diagnose is not in the documented location

### ISSUE THREAD

**Issue by code-for-coffee** [docker/docker.github.io#7437]
File: [docker-for-mac/troubleshoot.md](https://docs.docker.com/docker-for-mac/troubleshoot/)

Hello,

The current documents are out of date. For console troubleshooting they refer to this bin:

```
/Docker.app/Contents/Resources/bin/docker-diagnose --help
```

However, in the latest release it does not exist:

```
me in me /Applications/Docker.app/Contents/Resources/bin
$ ls
com.docker.hyperkit		docker-credential-osxkeychain
com.docker.vpnkit		docker-machine
docker				kubectl
docker-compose			notary
```

Could the docs be updated with the appropriate location?

**Comment by aevesdocker** [comment]
Closing issue as this has been fixed
