### ISSUE TITLE
Curl command not working

### ISSUE THREAD

**Issue by docanaebi** [docker/docker.github.io#7443]
File: [ee/ucp/admin/configure/create-audit-logs.md](https://docs.docker.com/ee/ucp/admin/configure/create-audit-logs/)

In https://beta.docs.docker.com/ee/ucp/admin/configure/create-audit-logs/#procedure step 4:

The curl command returns the following when using the cert in the bundle downloaded from UCP:
```
curl -k --cert ./cert.pem --key ./key.pem --cacert ./ca.pem -H "Content-Type: application/json" -X PUT --data $(cat auditlog.json) https://${UCP_HOST}/api/ucp/config/logging
curl: (58) unable to load client key: -8178 (SEC_ERROR_BAD_KEY)
```

I used a Bearer Token and got the following:

```
curl -sk -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHTOKEN" -X PUT --data $(cat auditlog.json) https://${UCP_HOST}/api/ucp/config/logging
{"message":"unable to parse request body: unexpected end of JSON input"}
```

It was missing some quotes for the --data parameter:
```

curl -sk -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHTOKEN" -X PUT --data "$(cat auditlog.json)" https://${UCP_HOST}/api/ucp/config/logging
{"logLevel":"INFO","auditLevel":"metadata","supportDumpIncludeAuditLogs":false}
```

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
