### ISSUE TITLE
Feedback for: swarm/install-w-machine.md

### ISSUE THREAD

**Issue by ajrader** [docker/docker.github.io#745]
File: [swarm/install-w-machine.md](https://docs.docker.com/swarm/install-w-machine/)
When using docker from Windows 10 hyper-V pre-empts virtualbox and so I can't execute the second step:

> 2. Create a VirtualBox machine called local on your system.
```
$ docker-machine create -d virtualbox local
INFO[0000] Creating SSH key...
INFO[0000] Creating VirtualBox VM...
INFO[0005] Starting VirtualBox VM...
INFO[0005] Waiting for VM to start...
INFO[0050] "local" has been created and is now the active machine.
  	INFO[0050] To point your Docker client at it, run this in your shell: eval "$(docker-machine env local)"
```

as indicated on this page. Are there alternative commands to do this on a Windows10 machine?

**Comment by mstanleyjones** [comment]
@allencloud can you help with this? @ajrader FYI these docs are related to standalone Docker Swarm, not Swarm mode in Docker Engine.

**Comment by mstanleyjones** [comment]
Swarm mode is part of Docker for Windows. The file you referenced in your initial feedback is for standalone swarms, which are considered legacy. For more detailed instructions about HyperV and VirtualBox interaction, see https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install.
