### ISSUE TITLE
Typo in --mount options docs for "docker service create"

### ISSUE THREAD

**Issue by ryancastle** [docker/docker.github.io#7451]
The documentation refers to option "types", but I believe this should be singular "type"

File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/)

```
$ docker service create -p 80:80 --mount types=bind,source=/mnt/data,destination=/data nginx
invalid argument "types=bind,..." for "--mount" flag: unexpected key 'types' in 'types=bind'
```

**Comment by L-Hudson** [comment]
Correction already made. Thank you so much for the catch!
