### ISSUE TITLE
Disable docker install and apt-get update in "Docker machine Create --driver generic ... "

### ISSUE THREAD

**Issue by shubjain26** [docker/docker.github.io#7452]
File: [machine/drivers/generic.md](https://docs.docker.com/machine/drivers/generic/)

I'm working on machines where there is no internet connectivity.
How can I disable the below tasks : 

> 1. If docker is not running on the host, it is installed automatically.
> 2. It updates the host packages (apt-get update, yum update...).

Or to accept errors in apt-get update and proceed to next task.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. Closing as Docker Machine is now deprecated.
