### ISSUE TITLE
I found a broken link - links to installation instructions

### ISSUE THREAD

**Issue by StevenMaude** [docker/docker.github.io#7459]
On the [install](https://docs.docker.com/install/) page, *all* linked URLs in the [server](https://docs.docker.com/install/#server) table there are broken, and refer to Markdown files instead of the correct page.

For example, `https://docs.docker.com/install/linux/docker-ce/centos.md` should be `https://docs.docker.com/install/linux/docker-ce/centos/`

Would put a PR in, but there seems to be some magic in those links as written in the source.

**Comment by StevenMaude** [comment]
(While I'm here, but not going to make a separate issue, the whole distinction on that page between "Desktop" and "Server" seems a little odd. For instance, some people use Linux as a desktop and not a server. Personally, I'd just list all platforms in the same table under "Platform".)

**Comment by bermudezmt** [comment]
@JustinINevill same here. I think it's also relevant for the next release.

**Comment by ProfessorTom** [comment]
@StevenMaude Link to your PR?

**Comment by ProfessorTom** [comment]
Thorough reading is a skill: I missed the word “would“.

**Comment by arshadkazmi42** [comment]
I checked the server table, looks like all the links are working in the server table. I think this has already been fixed

**Comment by bermudezmt** [comment]
Thank you for reporting - already fixed.
