### ISSUE TITLE
ucp certificates: outdated screenshot + text describing input fields

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#7467]
### Problem description

The screenshot for configuring UCP certificates does not reflect UCP 3.0.  The order of the input fields has changed since the version in the current screenshot, which means the order of the accompanying text describing the input field should be updated when the screenshot is updated.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ee/ucp/admin/configure/use-your-own-tls-certificates/#configure-ucp-to-use-your-own-tls-certificates-and-keys

### Project version(s) affected

EE 2.0 -> UCP 3.0

### Suggestions for a fix

Update screenshot, change order of bullets describing input fields to match current UI.

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docker.github.io/pull/10076

**Comment by traci-morrison** [comment]
Fixed via https://github.com/docker/docker.github.io/pull/10076
