### ISSUE TITLE
Docker Cloud deprecated, yet docu still exists

### ISSUE THREAD

**Issue by davidjmeier** [docker/docker.github.io#7479]
File: [docker-cloud/index.md](https://docs.docker.com/docker-cloud/)

The Docker Cloud documentation is still available and makes it look like a viable consideration.  Should this be archived or flag it as deprecated?

**Comment by aliceminotto** [comment]
I agree, just landed there from the warning here: https://docs.docker.com/machine/get-started-cloud/ and ended up well confused

**Comment by paigehargrave** [comment]
@davidjmeier Hi David, this now redirects to Docker Hub. Cloud documentation has been deprecated. Please let us know if this is sufficient to close this issue. Thank you!

**Comment by traci-morrison** [comment]
This issue is now resolved.
