### ISSUE TITLE
Tiny suggestion: missing "to"

### ISSUE THREAD

**Issue by sharon-indegy** [docker/docker.github.io#7484]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/)
Under section "Persist the data", Step 3:
The bullet "Run docker-machine ls to list machines and make sure you are connected to myvm1, as indicated by an asterisk next it."
Maybe it should be:
"Run docker-machine ls to list machines and make sure you are connected to myvm1, as indicated by an asterisk next **to** it."

**Comment by paigehargrave** [comment]
Closing due to fix provided in #7504.
