### ISSUE TITLE
Mistake in docker stack deploy spec?

### ISSUE THREAD

**Issue by deemoowoor** [docker/docker.github.io#7485]
File: [engine/reference/commandline/stack_deploy.md](https://docs.docker.com/engine/reference/commandline/stack_deploy/)

$ docker stack deploy --compose-file docker-compose.yml -f docker-compose.prod.yml vossibility

Seems like there's no option "-f" for "docker stack deploy". It's a docker-compose command.

**Comment by 5bentz** [comment]
Fixed in https://github.com/docker/cli/commit/2ee9635b1e7163aaea285a2f58033575f8b0e4ed#diff-5aab53303f06fca3f82a5c447268b876be057a3b3a35114e55e647d4abc33194R84

I think this could be closed.
