### ISSUE TITLE
Misleading linking

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#7487]
File: [datacenter/dtr/2.0/reference/migrate.md](https://docs.docker.com/datacenter/dtr/2.0/reference/migrate/)

The link for version 2.4 points to general information rather than the equivalent migrate command for dtr 2.4.x

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
