### ISSUE TITLE
Register for Docker ID link points to docker cloud

### ISSUE THREAD

**Issue by jlk** [docker/docker.github.io#7490]
Step 1 asking users to go to https://cloud.docker.com/ to sign up for an account brings users to a page where there's a unusuable link to create a new account. Perhaps send users to Docker Hub now, instead?

Looks like id.docker.com doesn't do registrations, itself...

File: [docker-id/index.md](https://docs.docker.com/docker-id/)

**Comment by paigehargrave** [comment]
@jlk Hi John - thank you for fixing this!
