### ISSUE TITLE
Links to install pages are dead links

### ISSUE THREAD

**Issue by evolarjun** [docker/docker.github.io#7494]
File: [install/index.md](https://docs.docker.com/install/)
Links to pages in the "Supported platforms" table are dead links (removing the '.md' in the link makes them live)
e.g., link to https://docs.docker.com/install/linux/docker-ce/centos.md should be changed to https://docs.docker.com/install/linux/docker-ce/centos

**Comment by jrkong** [comment]
I'll fix this

**Comment by L-Hudson** [comment]
all working in this release. Closing the ticket.
