### ISSUE TITLE
Which side of --publish is host side?

### ISSUE THREAD

**Issue by jpaugh** [docker/docker.github.io#7505]
Whenever I use docker, I have difficulty remembering which side of the colon is for the host port. Is it `-p host:container` or `-p container:host`?

It would be great to be able to access that info by running `docker help run`.

File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/)

**Comment by jaredestroud** [comment]
```docker port $CONTAINER_NAME``` can show what side is listening on the host vs the container thus help you trouble shoot the order of ```-p```.

**Comment by ulm0** [comment]
@jpaugh 

```sh
docker run -p [CONTAINER]:[HOST] ...
```

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. If the issue is still relevant, please help create an issue in the CLI repo at https://github.com/docker/cli
