### ISSUE TITLE
Broken Link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by arshadkazmi42** [docker/docker.github.io#7518]
### Problem description

Link to `style guide` in CONTRIBUTING.md is broken

### Problem location

- I saw a problem on the following URL: https://github.com/docker/docker.github.io/blob/master/CONTRIBUTING.md#style-guide

### Project version(s) affected

This is there in master branch

### Suggestions for a fix

I explored a bit and found that this file is available in `v17.06` branch.
So for fixing it, it should be either linked to style-guide of that branch or the file needs to be added in the master branch.

Can someone confirm on this? I will create a PR on this, after confirmation of the bug by someone from core team

**Comment by bermudezmt** [comment]
@arshadkazmi42 we removed the link because we currently do not have a style guide that we support. We are happy to take contributions and take care of the technical and editorial reviews on our end. Thank you and sorry for the delayed response!
