### ISSUE TITLE
Broken link in supported-platforms.md

### ISSUE THREAD

**Issue by arshadkazmi42** [docker/docker.github.io#7519]
### Problem description

`Install Docker` link is broken in `supported-platforms.md` and `engine/index.md`

### Problem location

- I saw a problem on the following URL: 
https://github.com/docker/docker.github.io/blob/master/ee/supported-platforms.md#where-to-go-next
https://github.com/docker/docker.github.io/blob/master/engine/index.md#installation-guides

### Project version(s) affected

In `master` branch

### Suggestions for a fix

Installation directory here https://github.com/docker/docker.github.io/tree/master/engine is missing in  `master`, due to  which the url is redirecting to 404 page

I checked on other branches and found the installation directory is available on this branch.

Can someone confirm on this? Whether it should go to that branch or the folder is needed in master branch?

**Comment by bermudezmt** [comment]
Hey, @arshadkazmi42 - can you please try accessing the site pages directly through docs.docker.com? 

First link should be: https://docs.docker.com/ee/supported-platforms/#where-to-go-next
Second should be: https://docs.docker.com/engine/#installation-guides

In the case of the Markdown links you've mentioned, those point to pages which have been redirected. So they redirect properly through the site but not through Github. Please feel free to open another issue if you still see a problem.
