### ISSUE TITLE
Document how the list to --args should be provided.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [docker/docker.github.io#7528]
File: [engine/reference/commandline/service_update.md](https://docs.docker.com/engine/reference/commandline/service_update/)

`--args` is a list.  Please document how this list should be passed.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. You can find an explanation of multiple options at https://docs.docker.com/engine/reference/commandline/cli/#option-types
This particular content is maintained in an upstream repo. If there is still an issue, please help open an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
Closing this issue as unable to fix in this repo.
