### ISSUE TITLE
Explanation of multiple --filter arguments is ambiguous.

### ISSUE THREAD

**Issue by jeffstearns** [docker/docker.github.io#7532]
File: [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/)

The sentence says:
> If there is more than one filter, then pass multiple flags (e.g. --filter "foo=bar" --filter "bif=baz").

The semantics are ambiguous.  Does this mean that ps will return lines matching **either** of these conditions, or lines which match **both** of these conditions?

The difference is pretty significant.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this in favor of #7424. 
You can also find a little more explanation in that issue.
