### ISSUE TITLE
Remove section of Overlay Networking Tutorial

### ISSUE THREAD

**Issue by tduval** [docker/docker.github.io#7534]
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)

The last section of the page (_Communicate between a container and a swarm service_) is unrelated to the Overlay Networking and is a duplicata of the Bridge Network Tutorial.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/docker.github.io/issues/8387
