### ISSUE TITLE
Provide complete list of downloadable tarballs for UCP 2.2.x series in the 2.2 docs

### ISSUE THREAD

**Issue by programmerq** [docker/docker.github.io#7539]
File: [datacenter/ucp/2.2/guides/admin/install/install-offline.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/install/install-offline/)

This list does not list all the patch releases for UCP 2.2.x. For example, https://packages.docker.com/caas/ucp_images_win_2.2.10.tar.gz is available for download but doesn't appear in the list.

**Comment by paigehargrave** [comment]
@programmerq Hi - what are the missing offline packages? Thank you!

**Comment by programmerq** [comment]
It looks like this has been solved-- the list of 2.2.x tarballs seems fairly complete at the referenced link.
