### ISSUE TITLE
Update Ingress Docs to include HA NGINX Controller and ingress object example

### ISSUE THREAD

**Issue by nicolaka** [docker/docker.github.io#7554]
Here's a doc I recommend: https://gist.github.com/nicolaka/7b82839bf10d7b265934ec69c2f6cf4b

cc @ahh-docker 

File: [ee/ucp/kubernetes/layer-7-routing.md](https://docs.docker.com/ee/ucp/kubernetes/layer-7-routing/)

**Comment by nicolaka** [comment]
The doc I put together is based on UCP 3.0 just need to test it against 3.1 to make sure it's still working.

**Comment by arueth** [comment]
You shouldn't need the grant in 3.1, it should probably be replaced by the Kube RBAC alternative.

**Comment by nicolaka** [comment]
We're getting many customers complaining about lack of docs around this topic. I provided a sample doc and updated it based on @arueth feedback so it should be good. Let's make sure this gets into the UCP docs.

**Comment by nicolaka** [comment]
cc @JustinINevill @ahh-docker

**Comment by arueth** [comment]
@nicolaka do you have a link to a PR or where your new doc is?

**Comment by nicolaka** [comment]
@arueth https://github.com/nicolaka/docker-enterprise/tree/master/ingress

**Comment by paigehargrave** [comment]
@nicolaka PTAL at https://github.com/docker/docker.github.io/pull/8346 - thank you!

**Comment by paigehargrave** [comment]
@nicolaka Closing this since #8346 was merged. Thank you!
