### ISSUE TITLE
Is it possible to add a code package to the tutorial for newcomers to download?

### ISSUE THREAD

**Issue by controlloli** [docker/docker.github.io#7563]
When I was learning Use multi-stage builds, the code had problems. According to the source code attached to Alex Ellis' code, it can be executed correctly.

**Comment by aevesdocker** [comment]
There's isn't any information on the ticket for us to take action on or the information is outdated. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
