### ISSUE TITLE
wrong doc for persistentstorage on nfs

### ISSUE THREAD

**Issue by sluetze** [docker/docker.github.io#7567]
File: [ee/ucp/admin/configure/use-nfs-volumes.md](https://docs.docker.com/ee/ucp/admin/configure/use-nfs-volumes/)

Hi,

this walkthrough has some issues from top to bottom. I wanted to correct it, but in my opinion a complete rewrite is necessary. 
The "correct" way to implement a nfs-provisioner in kubernetes is described here:
https://github.com/kubernetes-incubator/external-storage/tree/master/nfs
maybe it would be clever just to link on this ressource?

Furthermore some thoughts:
- what about external NFS provisioners? is this supported by ucp or not?
- is dynamic nfs provisioning supported through ucp or just manual?

Identified issues
* Create the NFS Server
--> This is a pod, not a deployment/statefulset, this is against best practice
--> The pod doesnt mount any persistent disk. Not even a hostpath-mount. thus when the pod exits the data is lost

* Create the default storage class
--> it is correct, that you need the default storage class, but you don't get any dynamic provisioning.

* Create Persistent Volumes
The examples do not use the nfs-server (pod) which was previously created but hostpath mounts.

**Comment by traci-morrison** [comment]
This issue was fixed via https://github.com/docker/docker.github.io/pull/8306.
