### ISSUE TITLE
Virtual machine stack example is broken :(

### ISSUE THREAD

**Issue by EmilyH4t1qbit** [docker/docker.github.io#7570]
File: [get-started/index.md](https://docs.docker.com/get-started/)

**Comment by ryancharris** [comment]
This is the offending `img` tag: 
```html
<img src="https://www.docker.com/sites/default/files/VM%402x.png" alt="Virtual machine stack example" width="300px">
```

**Comment by ryancharris** [comment]
![image](https://user-images.githubusercontent.com/4997781/47607771-6a16eb00-d9f2-11e8-979c-ec8851e5ec48.png)
