### ISSUE TITLE
Consider removing the topic "Use Supervisor with Docker"

### ISSUE THREAD

**Issue by immunda** [docker/docker.github.io#758]
File: [engine/admin/using_supervisord.md](https://docs.docker.com/engine/admin/using_supervisord/)

This seems to be a total anti-pattern and very much against separation of concerns. I'm quite surprised to see it "officially" endorsed through the documentation.

I appreciate that sometimes folks really wish to do this, but it's often for the wrong reasons and almost never really required. Have you considered more thoroughly educating them in the introduction paragraph to explain the implications of doing this, or more importantly, benefits of properly separating concerns and how they might well be served by Compose?

**Comment by londoncalling** [comment]
@mstanleyjones @immunda seems to bring up a good point. Should we remove this topic from the docs or not?
