### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by LeBovin** [docker/docker.github.io#7582]
Hello

1) Go on : https://docs.docker.com/v1.7/reference/run/
2) Click on "Option types"
3) Broken link on "https://docs.docker.com/v1.7/reference/reference/reference/commandline/cli/#option-types"

**Comment by jaredestroud** [comment]
That page is archived, I believe what you're looking for is [here](https://docs.docker.com/engine/reference/commandline/cli/#option-types).

**Comment by L-Hudson** [comment]
Again, thank you jaredstroud! Closing ticket.
