### ISSUE TITLE
Run the UCP installation script for Windows should link to latest version, not 2.2

### ISSUE THREAD

**Issue by arueth** [docker/docker.github.io#7584]
Under:
Preparing a Docker EE Engine for use with UCP

The 'UCP installation script for Windows' link points to:
https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/join-windows-worker-nodes/#run-the-windows-node-setup-script
when it should probably point to:
https://docs.docker.com/ee/ucp/admin/configure/join-nodes/join-windows-nodes-to-cluster/#run-the-windows-node-setup-script

File: [install/windows/docker-ee.md](https://docs.docker.com/install/windows/docker-ee/)

**Comment by traci-morrison** [comment]
@arueth This issue appears to be fixed via https://github.com/docker/docker.github.io/pull/8221. Can you please confirm? Thanks.

**Comment by traci-morrison** [comment]
Work completed in https://github.com/docker/docker.github.io/pull/8221.
