### ISSUE TITLE
default-address-pools config options missing in daemon.js section

### ISSUE THREAD

**Issue by setiseta** [docker/docker.github.io#7587]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
