### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by buanzo** [docker/docker.github.io#7588]
File: [install/index.md](https://docs.docker.com/install/)

All links in the aforementioned document that point to :
https://docs.docker.com/install/linux/docker-ce/{DISTRO}.md
Such as: https://docs.docker.com/install/linux/docker-ce/centos.md or https://docs.docker.com/install/linux/docker-ce/ubuntu.md

do not exist.

**Comment by thaJeztah** [comment]
probably related to https://github.com/docker/docker.github.io/issues/5711

**Comment by aevesdocker** [comment]
Closing as issue has now been fixed
