### ISSUE TITLE
Curly quotes in command samples should be replaced with regular ""

### ISSUE THREAD

**Issue by akost** [docker/docker.github.io#7592]
File: [engine/userguide/eng-image/dockerfile_best-practices.md](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/)

Curly quotes in command samples should be replaced with regular `"` to allow copy-paste examples.

**Comment by akost** [comment]
E.g., CMD `[“php”, “-a”]` should be `CMD ["php", "-a"]`.

**Comment by imedqq** [comment]
Hello, I would like to work on this.
