### ISSUE TITLE
Suggest showing how to apply conceptual tutorial topics with to Docker and Compose files 

### ISSUE THREAD

**Issue by OysteinAmundsen** [docker/docker.github.io#760]
File: [engine/tutorials/dockervolumes.md](https://docs.docker.com/engine/tutorials/dockervolumes/)

Since Dockerfile and docker-compose.yml seems to be the way people are using your platform, why not apply this and similar pages with a "how to apply knowledge in this article to a Dockerfile or docker-compose" section? Or links to other parts of the docs describing this? It would help people like me who is just starting with docker.

**Comment by johndmulhausen** [comment]
Closing; rather broad in scope with no exit conditions, and it's now 2018 and this bug hasn't garnered so much as a comment.
