### ISSUE TITLE
Document Hub/Registry hostnames for UCP System Requirements

### ISSUE THREAD

**Issue by adamancini** [docker/docker.github.io#7601]
I feel that support has gotten this question often, and we should probably publish the required hostnames for exceptions for enterprise users accessing DockerHub through a firewall:

Currently known:

- auth.docker.io
- index.docker.io
- hub.docker.com
- registry-1.docker.io
- production.cloudflare.docker.com 

File: [ee/ucp/admin/install/system-requirements.md](https://docs.docker.com/ee/ucp/admin/install/system-requirements/)

**Comment by traci-morrison** [comment]
@adamancini Is this issue still applicable? I can add a section for hostname requirements. Please advise. Thanks!

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
