### ISSUE TITLE
page not available

### ISSUE THREAD

**Issue by RFGuy200** [docker/docker.github.io#7606]
File: [404.md](https://docs.docker.com/404.html)

the following page was not available:
https://docs.docker.com/v1.7/reference/reference/reference/commandline/cli/#option-types

**Comment by jaredestroud** [comment]
That page is archived, I believe what you're looking for is [here](https://docs.docker.com/engine/reference/commandline/cli/#option-types).

**Comment by L-Hudson** [comment]
jaredstroud, thanks much! Closing the ticket.
