### ISSUE TITLE
Docker doesn't use Go filepath.Match, fix docs

### ISSUE THREAD

**Issue by s0x** [docker/docker.github.io#761]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)
The section ".dockerignore file" states that Go's filepath.Match rules are used although this is actually not the case.

In dockers source you can find the following comment:
```
filepath's Match() has some really weird rules that are inconsistent
so instead of trying to dup their logic, just call Match() for its
error state and if there is an error in the pattern return it.
If this becomes an issue we can remove this since its really only
needed in the error (syntax) case - which isn't really critical.
```

You might have a look on docker/docker#29014 as well

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by shubheksha** [comment]
I cannot find a `builder.md` file in the [`engine`](https://github.com/docker/docker.github.io/tree/master/engine) folder to make the changes. Am I missing something?

**Comment by londoncalling** [comment]
@shubheksha let me take a look, the file might have moved.

**Comment by londoncalling** [comment]
@shubheksha Okay, this is a bit tricky, but do-able :-)

- we have a few sets of reference files that were originally in the `docker/docker/` repository and never moved (when we moved the rest of the documentation to its own repository). API docs, and some sets of commands, stay with the codebase. This is one of them. 

- So to work on this file, you _would have_ needed to clone the `docker/docker` repository and there find the file in `docs/reference/builder.md`

- However, Solomon just open-sourced `docker/docker` today at the conference to `moby/moby`! So if you already had cloned `docker/docker` you will be redirected to `moby/moby`.

If you are starting with this repository for the first time, then clone [moby/moby/](https://github.com/moby/moby](https://github.com/moby/moby). You will find the file at [moby/moby/docs/reference/builder.md](https://github.com/moby/moby/blob/master/docs/reference/builder.md).

**Comment by shubheksha** [comment]
Thanks for the detailed info :)
Should I just remove the line which claims that Go filepath.Match is used to fix this?

**Comment by shubheksha** [comment]
@londoncalling, found the text relevant to this issue:

"Matching is done using Go's filepath.Match rules. A preprocessing step removes leading and trailing whitespace and eliminates . and .. elements using Go's filepath.Clean. Lines that are blank after preprocessing are ignored.

Beyond Go's filepath.Match rules, Docker also supports a special wildcard string ** that matches any number of directories (including zero). For example, **/*.go will exclude all files that end with .go that are found in all directories, including the root of the build context."

**Comment by londoncalling** [comment]
@shubheksha yes I'm looking through this, it's a bit complicated. Let's try to figure it out together.

**Comment by londoncalling** [comment]
@thaJeztah @duglin @johnstep Can you give us some guidance on docs fixes with regard to this? It looks like the related issues in the codebase are fixed (https://github.com/docker/docker/issues/29014) but it is not totally clear whether docs fix is to remove all mention of Go's `filepath.Match` rules. If so, we need to describe the rules that are in place and might need some guidance here.

cc: @shubheksha

**Comment by shubheksha** [comment]
Any update on this?

**Comment by londoncalling** [comment]
No response from Dev yet .. someone else at Hackathon was looking at it as
well but I don't think any of us is going to figure it out without input
from Dev.

**Comment by mstanleyjones** [comment]
Sorry @shubheksha we did not get you the info in time for the hackathon!

**Comment by shubheksha** [comment]
@mstanleyjones, no issues! 😄

**Comment by mstanleyjones** [comment]
@thaJeztah ping? I'd like to get this one taken care of, but we need some technical guidance.

**Comment by mistyhacks** [comment]
Closing due to lack of info.
