### ISSUE TITLE
(HTTP code 500) server error - Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:51848->10.0.2.3:53: i/o timeout

### ISSUE THREAD

**Issue by Andru1999** [docker/docker.github.io#7612]
### Problem description

I write command : `docker run rnix/openssl-gost -it /bin/bash` and get error
`(HTTP code 500) server error - Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:51848->10.0.2.3:53: i/o timeout`

### Project version(s) affected

Os: Windows 10 Home
Docker: version 18.03.0-ce, build 0520e24302   
Docker work from boot2docker image in virtualbox V 5.2.20 r125813 (Qt5.6.2)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If there is an issue in the docs, please let us know. Please check your DNS server settings. For further support, please try: 
 - https://dockercommunity.slack.com/
 - https://forums.docker.com/
