### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by a-dimas** [docker/docker.github.io#7621]
Page: https://docs.docker.com/install/linux/docker-ce/ubuntu/
Many of the links are missing /ubuntu/:

Upgrade Docker CE
To upgrade Docker CE, first run sudo apt-get update, then follow the **installation instructions**, choosing (...)

Installation instructions points to https://docs.docker.com/install/linux/docker-ce/#install-docker-ce and it should point to https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce

**Comment by L-Hudson** [comment]
Problem resolved. Closing ticket.
