### ISSUE TITLE
Quickstart: Compose and WordPress - not working

### ISSUE THREAD

**Issue by jiajiewu1988** [docker/docker.github.io#7630]
File: [compose/wordpress.md](https://docs.docker.com/compose/wordpress/)

Hi,

I followed this tutorial and trying to setup wordpress and mysql by docker on my AWS Ubuntu vm, but after finished with all the steps, wordpress container does not start running, it keeps restarting.

Any one know if there are any issues?

**Comment by bh-adrienne** [comment]
I am also having this issue, the quickstart example does not work as stated.

**Comment by td-gonzales** [comment]
[This](https://github.com/docker/docker.github.io/pull/8091) pull request fixes this problem.

**Comment by td-gonzales** [comment]
That pull has been merged so this issue can be closed. #8091
