### ISSUE TITLE
Remote Build Trigger Parameters

### ISSUE THREAD

**Issue by wjdavis5** [docker/docker.github.io#7632]
File: [docker-hub/builds.md](https://docs.docker.com/docker-hub/builds/)

You show a few different parameters being passed in, but you dont explain their meaning, nor do you list all possible parameters.

Please indicate to the rest of us what can be passed into this command and explain what it does. A link to the API docs here would be great.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As this issue is old and a lot has changed, it's difficult to understand without the old context.
If the issue is still applicable, can you provide more details based on the current content?
