### ISSUE TITLE
DTR 2.5.x offline images missing

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#7639]
File: [datacenter/dtr/2.5/guides/admin/install/install-offline.md](https://docs.docker.com/datacenter/dtr/2.5/guides/admin/install/install-offline/)

The DTR 2.5.x offline images missing images are missing on this page.

**Comment by bermudezmt** [comment]
Issue moved to [docker/docs-private #880](https://github.com/docker/docs-private/issues/880) via [**ZenHub**](https://www.zenhub.com/)
