### ISSUE TITLE
There are no warnings that docker cloud is gone

### ISSUE THREAD

**Issue by icyitscold** [docker/docker.github.io#7641]
I got hooked by Docker Cloud about page and then spent a lot of time reading about how amazing docker cloud is before realizing that it was shit down _months ago_. The following warning from the migration page should be duplicated on every page underneath the Docker Cloud section

> Cluster and application management services in Docker Cloud are shutting down on May 21. You must migrate your applications from Docker Cloud to another platform and deregister your Swarms."

File: [docker-cloud/index.md](https://docs.docker.com/docker-cloud/)

P.S Since we're stepping into a new year, the message should probably be changed to past tense, i.e. "was shut down on May 21st 2018"

**Comment by EdgarBarrantes** [comment]
Indeed there is an overhaul needed in the docs. Given the circumstances it's understandable that it hasn't been updated, it's a pretty big change. 
Btw: the [getting started](https://docs.docker.com/get-started/part6/) (part 6) should be updated.

**Comment by michelalbers** [comment]
This is greatly misleading:

> We’re excited to announce that #Docker Store and Docker #Cloud are now part of Docker Hub, providing a single experience for finding, storing and sharing container images.

Seems to me that docker cloud is not "part of docker hub" but simply gone. Is this right?!

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It appears that the issue is no longer applicable to the current docs. If you feel there is still an issue, please let us know.
