### ISSUE TITLE
Conflicting instructions for Docker EE on Windows Server 2016

### ISSUE THREAD

**Issue by heaths** [docker/docker.github.io#7642]
File: [install/windows/docker-ee.md](https://docs.docker.com/install/windows/docker-ee/)

In https://store.docker.com/editions/enterprise/docker-ee-server-windows you instruct to use install and use the "DockerProvider" (last updated on powershellgallery.com on 9/22/2017), but in https://docs.docker.com/install/windows/docker-ee/ you say to use the "DockerMsftProvider" (last updated 7/20/2018), which is also inline with Microsoft documentation.

Which is preferred? Could you update the other doc with the prefer provider as well?

**Comment by StefanScherer** [comment]
The docs have been updated to use `DockerMsftProvider` with PR https://github.com/docker/docker.github.io/pull/5993.
