### ISSUE TITLE
This statement is misleading.

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#7650]
File: [engine/release-notes.md](https://docs.docker.com/engine/release-notes/)

Customers have reported they have tried to set up multiple logging drivers because of this statement.

This should be reworded to specify that it is a feature of the docker logs command, not for multiple drivers.

**Comment by ahh-docker** [comment]
@kavikat Could you please be more specific on which statement? Thanks.

**Comment by kavikat** [comment]
“Add support for multiple logging drivers for docker logs.” <- bad (misleading statement)

"Added functionality for the `docker logs` command to include the output of multiple logging drivers." <- better (more specific)

**Comment by paigehargrave** [comment]
The current version of the release notes contains this fix.
