### ISSUE TITLE
error installing docker-ce on ppc64le

### ISSUE THREAD

**Issue by ghatwala** [docker/docker.github.io#7660]
File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

Hi,

On a power machine , power architecture is shown as below
```
# arch
ppc64le
```
if docker.list is configured as below
```
~ /etc/apt/sources.list.d# cat docker.list
deb      [arch=ppc64le] "https://download.docker.com/linux/ubuntu" xenial stable edge
```
getting below error
```
# apt-get update
Hit:1 https://download.docker.com/linux/ubuntu xenial InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports xenial-backports InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease
Reading package lists... Done
N: Skipping acquire of configured file 'stable/binary-ppc64le/Packages' as repository 'https://download.docker.com/linux/ubuntu xenial InRelease' doesn't support architecture 'ppc64le'
N: Skipping acquire of configured file 'edge/binary-ppc64le/Packages' as repository 'https://download.docker.com/linux/ubuntu xenial InRelease' doesn't support architecture 'ppc64le'

```
Which is caused as those packages are missing here 
stable - https://download.docker.com/linux/ubuntu/dists/xenial/stable/binary-ppc64le/
edge - https://download.docker.com/linux/ubuntu/dists/xenial/edge/binary-ppc64le/

whereas if we update the docker.list above as below , docker-ce installation works as expected.
```
~ /etc/apt/sources.list.d# cat docker.list
deb      [arch=ppc64el] "https://download.docker.com/linux/ubuntu" xenial stable edge
```
as edge - https://download.docker.com/linux/ubuntu/dists/xenial/edge/binary-ppc64el/
and stable - https://download.docker.com/linux/ubuntu/dists/xenial/stable/binary-ppc64el/ are present as expected.

also in the documentation page  here , its written as ppc64le and ppc64el.
can the below be possible -
1 ) update the packages under stable/edge in below
stable - https://download.docker.com/linux/ubuntu/dists/xenial/stable/binary-ppc64le/
edge - https://download.docker.com/linux/ubuntu/dists/xenial/edge/binary-ppc64le/

2) update the documentation clearly to indicate both ppc64le/ppc64el.

**Comment by L-Hudson** [comment]
Closing, as the related ticket is also closed.
