### ISSUE TITLE
Install Docker points to Docker CE

### ISSUE THREAD

**Issue by foodebeer** [docker/docker.github.io#7672]
File: [ee/supported-platforms.md](https://docs.docker.com/ee/supported-platforms/)

Hi,

The link 'Install Docker' at the bottom of the page points to Docker CE, which is undesirable for the Enterprise product.
Since there is no landing page for Install Docker Engine, I can't change it myself. I think it's a good idea to create a landing page for Install Docker Engine, so I can send that page to customers. Currently there are only OS specific pages.

Best regards,

Sacha

**Comment by L-Hudson** [comment]
fixed. Thank you!
