### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by yeep-synopsys** [docker/docker.github.io#7677]
From page https://docs.docker.com/v1.7/reference/run/

Section:

VOLUME (shared filesystems)
The volumes commands are complex enough to have their own documentation in section **_Managing data in containers._**

Broken Link: https://docs.docker.com/v1.7/reference/reference/userguide/dockervolumes

**Comment by L-Hudson** [comment]
This is in archived documentation, and so won't be updated. Sorry!
