### ISSUE TITLE
Updating doc for Store logs in Remote Server

### ISSUE THREAD

**Issue by prashshr** [docker/docker.github.io#7682]
### Problem description

Firstly, in UCP `3.1.0` under Logs there is no option for "Configuring Remote Syslog Server" anymore. The current document page though still shows an example of the same. 

* UCP `3.0.1` Admin Settings
![image](https://user-images.githubusercontent.com/20244490/48493221-bb650e00-e82b-11e8-95c4-96547c0ed162.png)

* Document Page
![image](https://user-images.githubusercontent.com/20244490/48493304-dd5e9080-e82b-11e8-8926-2d820f9c0293.png)

Secondly,
The ELK containers don't support latest tags. The example doesn't seem to take that into consideration.

### Problem location

Document Page: [store-logs-in-an-external-system](https://docs.docker.com/ee/ucp/admin/configure/store-logs-in-an-external-system/)

### Project version(s) affected

UCP: 3.0.1

### Suggestions for a fix

Possibly just need to remove the example.

**Comment by prashshr** [comment]
Relates to https://github.com/docker/orca/issues/14915

**Comment by bermudezmt** [comment]
Hi @prashshr . This has been deprecated as of UCP 3.1. @ollypom took care of this via #8071 . Thanks for bringing it up!
