### ISSUE TITLE
Update Engine Install Guides for 18.09 (Windows)

### ISSUE THREAD

**Issue by pdebruin** [docker/docker.github.io#7683]
### Problem description

The Docker engine docs mention 18.03 whereas the latest version is 18.09.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/install/windows/docker-ee/#update-docker-ee

- Other: <DETAILS>

Although not specific, this worked for me.
Install-Package -Name docker -ProviderName DockerMsftProvider -Verbose -Update

**Comment by stefantrimborn** [comment]
There is a workaround currently:
Grab the JSON of: https://dockermsft.blob.core.windows.net/dockercontainer/DockerMsftIndex.json
In it you will find the current working download links.

**Comment by traci-morrison** [comment]
This issue is resolved. If the problem persists, please open a new issue. Thank you.
