### ISSUE TITLE
No definition of persist 

### ISSUE THREAD

**Issue by dios231** [docker/docker.github.io#7691]
File: [glossary.md](https://docs.docker.com/glossary/)

The glossary does not contain the definition of the _persist_ concept

**Comment by traci-morrison** [comment]
@dios231 I propose that we add the following entry for persistent storage: "Persistent storage or volume storage provides ways for an application or user to store data generated by a running container. It extends beyond the life or boundaries of an existing or running container."

Is this OK? Once we agree on the definition, I will create a PR and tag you to review. Thanks.

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docker.github.io/pull/9294

**Comment by traci-morrison** [comment]
Fixed via #9333
