### ISSUE TITLE
Get started page, pictures are 404

### ISSUE THREAD

**Issue by pavelkim** [docker/docker.github.io#7697]
File: [get-started/index.md](https://docs.docker.com/get-started/)

[Error] Failed to load resource: the server responded with a status of 404 () (VM@2x.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (Container@2x.png, line 0)

**Comment by paigehargrave** [comment]
@pavelkim - Thank you for bringing this to our attention! This has been fixed.
