### ISSUE TITLE
18.03.1-ee-3 and 17.06.2-ee-17 missing from new release notes page

### ISSUE THREAD

**Issue by sgammill** [docker/docker.github.io#7701]
File: [engine/release-notes.md](https://docs.docker.com/engine/release-notes/)

**Comment by ahh-docker** [comment]
@sgammill The release notes for 17.06.02-ee-17 are there. however, `18.03.ee-5` should be `18.03.1-ee-5`. They're there, so I'll create a PR to fix it.
