### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by mick1627** [docker/docker.github.io#7707]
From page https://docs.docker.com/ee/ucp/admin/configure/external-auth

Broken Link:  https://docs.docker.com/ee/ucp/admin/configure/external-auth/enable-ldap-config-file/

**Comment by paigehargrave** [comment]
@mick1627 - Very sorry for the delayed response on this. We have done some restructuring to that page, so we believe it has been fixed. We are going to go ahead and close this issue, but please submit another issue if you are still experiencing problems! Thank you!
