### ISSUE TITLE
Specify that content-trust in daemon.json is EE only

### ISSUE THREAD

**Issue by smiller171** [docker/docker.github.io#7709]
File: [engine/security/trust/content_trust.md](https://docs.docker.com/engine/security/trust/content_trust/)

It appears that the ability to set DCT from daemon.json is currently EE only, but that's not documented correctly here. Lost over an hour trying to track down why this wasn't working. If this is in fact EE-only, that should be documented. If it's supposed to work in CE I can open a separate bug.

**Comment by JustinINevill** [comment]
@andrewhsu Can you validate where this should work (EE vs CE)?

**Comment by ahh-docker** [comment]
@JustinINevill once @andrewhsu verifies, I'll go ahead and create a PR for this so we get it done.

**Comment by bermudezmt** [comment]
This issue was addressed by @ollypom via #8049 . @ahh-docker @JustinINevill can you please track https://github.com/docker/docs-private/issues/913 for the corresponding EE content updates that need to be made?

Thank you once again, Olly!
