### ISSUE TITLE
After UCP upgrade cluster switched to swarm mode

### ISSUE THREAD

**Issue by leenamba** [docker/docker.github.io#771]
### Problem description
From DDC customer.
[EDITED to remove potential sensitive information]

### Problem location

- The customer couldn't find the information they wanted. They expected to find it near the following URL: https://docs.docker.com/datacenter/dtr/2.1/guides/install/upgrade/
- Other: release notes for UCP 2.0.x

### Project version(s) affected
UCP 2.0.x

### Suggestions for a fix

We should say that UCP 2.0 requires swarm mode and that updating from 1.x will enable swarm mode in the engine.

**Comment by joaofnfernandes** [comment]
@leenamba this is a public repository, so I've removed the link you included in the issue.
