### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by WilliamDugdale** [docker/docker.github.io#7711]
Page: https://success.docker.com/article/how-do-i-set-the-docker-daemon-options

Clicked link on word 'docs' (marked with **docs**) in text:

"<top of page>

All the Docker daemon options are documented at in the Docker **docs.**

..."

Went to dead link

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. It appears that this issue is no longer applicable to the current docs because the parent page no longer exists. If you feel this issue still exists, please let us know.
