### ISSUE TITLE
How do I delete --purge k8s cluster in docker for windows?

### ISSUE THREAD

**Issue by mehemken** [docker/docker.github.io#7714]
File: [docker-for-windows/kubernetes.md](https://docs.docker.com/docker-for-windows/kubernetes/)

My users need to have the ability to remove their kubernetes cluster and restart from "factory settings" so to speak. If somehow they screw up their cluster and they need to start from scratch, how do they do that?

**Comment by aevesdocker** [comment]
Closing issue as this has been addressed in the docs
