### ISSUE TITLE
Fix HEALTHCHECK docs

### ISSUE THREAD

**Issue by joebowbeer** [docker/docker.github.io#7718]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

Given that multi-stage builds are supported, I assume there can be a HEALTHCHECK per build stage, which may result in multiple HEALTHCHECK instructions per Dockerfile.

Expected:

> There can only be one HEALTHCHECK instruction in a build stage.

Actual:

> There can only be one HEALTHCHECK instruction in a Dockerfile.

**Comment by aevesdocker** [comment]
Closing as this has now been fixed.
