### ISSUE TITLE
Debian 9 did not have add-apt-repository command

### ISSUE THREAD

**Issue by glenpike** [docker/docker.github.io#7722]
File: [install/linux/docker-ce/debian.md](https://docs.docker.com/install/linux/docker-ce/debian/)

Need to install a package:
`sudo apt-get install software-properties-common`

https://unix.stackexchange.com/a/45905

**Comment by brainwane** [comment]
https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository does now include `software-properties-common` as a package prerequisite. So I think this issue has been fixed and can be closed.
