### ISSUE TITLE
DTR documentation outdated

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker.github.io#7732]
Latest version of DTR removes the "images" tab
File: [ee/dtr/user/manage-images/pull-and-push-images.md](https://docs.docker.com/ee/dtr/user/manage-images/pull-and-push-images/)

**Comment by bermudezmt** [comment]
Issue moved to [docker/docs-private #891](https://github.com/docker/docs-private/issues/891) via [**ZenHub**](https://www.zenhub.com/)
