### ISSUE TITLE
Add stable release notes for v2.0 on macOS

### ISSUE THREAD

**Issue by stevepiercy** [docker/docker.github.io#7736]
File: [docker-for-mac/release-notes.md](https://docs.docker.com/docker-for-mac/release-notes/)

The release notes appear in the downloaded product, but not the website:

### 2018-11-16 2.0.0.0-mac78

* Upgrades
  - [Docker 18.09.0](https://github.com/docker/docker-ce-packaging/releases/tag/v18.09.0)
  - [Docker compose 1.23.1](https://github.com/docker/compose/releases/tag/1.23.1)
  - [Docker Machine 0.16.0](https://github.com/docker/machine/releases/tag/v0.16.0)
  - [Kitematic 0.17.5](https://github.com/docker/kitematic/releases/tag/v0.17.5)
  - Linux Kernel 4.9.125

* New
  - New version scheme

* Deprecation
  - Removed support of AUFS
  - Removed support of OSX 10.11

* Bug fixes and minor changes
  - Fix appearance in dark mode for OSX 10.14 (Mojave)
  - VPNKit: Improved scalability of port forwarding. Related to [docker/for-mac#2841](https://github.com/docker/for-mac/issues/2841)
  - VPNKit: Limit the size of the UDP NAT table. This ensures port forwarding and regular TCP traffic continue even when running very chatty UDP protocols.
  - Ensure Kubernetes can be installed when using a non-default internal IP subnet.
  - Fix panic in diagnose

**Comment by paigehargrave** [comment]
This appears to be in current version of https://docs.docker.com/docker-for-mac/release-notes/, so I'm closing this request. Please open another issue if there are still additional updates needed. Thank you!
