### ISSUE TITLE
where the heck is hyper-v manager

### ISSUE THREAD

**Issue by kucerarichard** [docker/docker.github.io#7745]
File: [machine/drivers/hyper-v.md](https://docs.docker.com/machine/drivers/hyper-v/)

Add this little blurb (in your own words):

1) Where the Hyper-V Manager is

The Hyper-V Manager is under Windows Administrative Tools on your Start Menu. 

2) How to start the Hyper-V Manager

Simply click on the Hyper-V Manager icon under Windows Administrative Tools..  That starts the Hyper-V Manager.

Then in the top right of the Manager page you will see "Connect to Server."  Click that and choose "Local Computer" for the server.  The "Action" pane (the right side of the Manager page) will then populate and you can proceed.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as Docker Machine is now deprecated. If the issue still persists elsewhere, please let us know.
