### ISSUE TITLE
dockerd can't start up after modify /etc/docker/daemon.json

### ISSUE THREAD

**Issue by wangdong268** [docker/docker.github.io#7748]
File: [config/containers/live-restore.md](https://docs.docker.com/config/containers/live-restore/)
In my environment there isn't have this file /etc/docker/daemon.json
So, I follow this doc to create one witt { "live-restore": false }
After save, I can't start docker 
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-11-26 13:17:12 CST; 43s ago
     Docs: http://docs.docker.com
  Process: 1103 ExecStart=/usr/bin/dockerd-current --add-runtime oci=/usr/libexec/docker/docker-runc-current --default-runtime=oci --authorization-plugin=rhel-push-plugin --containerd /run/containerd.sock --exe>
 Main PID: 1103 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

Finally, I found a way to disable --live-restore

Delete "#OPTIONS='--selinux-enabled --log-driver=journald --live-restore'" --live restore from this line in file /etc/sysconfig/docker

**Comment by L-Hudson** [comment]
not a docs issue. Closing ticket.
