### ISSUE TITLE
AzureChinaCloud valid value for cloud key

### ISSUE THREAD

**Issue by omegamormegil** [docker/docker.github.io#7750]
File: [ee/ucp/admin/install/install-on-azure.md](https://docs.docker.com/ee/ucp/admin/install/install-on-azure/)

Customers deploying to the China cloud need to change "cloud":"AzurePublicCloud" to "cloud":"AzureChinaCloud" but this isn't clear from this doc because the "cloud" key doesn't have an '*'.

It would be useful to include a list of valid values for this key.

**Comment by xinfengliu** [comment]
There's another PR regarding the improvement of azure installation docs. https://github.com/docker/docker.github.io/pull/7353
I think we can add comments there.

**Comment by L-Hudson** [comment]
addressed and closed elsewhere.
