### ISSUE TITLE
Docker version dropdown broken CSS

### ISSUE THREAD

**Issue by jcoleman-techempower** [docker/docker.github.io#7751]
### Problem description

The docs version dropdown is (still) broken. Clicking the dropdown _does_ show it, but it's cut off by the hidden overflow of the top nav bar.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/docker-for-mac/install/

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

Remove the `overflow: hidden` on

```css
@media only screen and (max-width: 1150px) and (min-width: 376px)
```

**Comment by aevesdocker** [comment]
Closing the PR as this has been fixed
