### ISSUE TITLE
Engine version is not same as requirements page

### ISSUE THREAD

**Issue by foodebeer** [docker/docker.github.io#7756]
Hi,

The Engine version stated on this page is not the same as stated on the requirements page for UCP:
https://docs.docker.com/ee/ucp/admin/install/system-requirements/

Maybe you can just refer to the Compatibility Matrix for the right versions?

Best regards,

Sacha

File: [ee/end-to-end-install.md](https://docs.docker.com/ee/end-to-end-install/)

**Comment by usha-mandya** [comment]
Hello @foodebeer! Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this here for that reason. Feel free to continue the conversation after I close.
