### ISSUE TITLE
Call out Kubernetes in EE backup documentation

### ISSUE THREAD

**Issue by axeal** [docker/docker.github.io#7757]
### Problem description

The Docker EE / UCP Backup documentation does not call out the backing up of Kubernetes objects. Kubernetes objects, e.g. deployments, daemonsets etc., are stored in the ucp-kv etcd database that is backed up (and restored) as part of UCP backup/restore, so we should call this out in the docs.

### Problem location

https://docs.docker.com/ee/backup/
https://docs.docker.com/ee/ucp/admin/backups-and-disaster-recovery/

### Project version(s) affected

UCP >= 3.0

**Comment by traci-morrison** [comment]
Fixed via https://github.com/docker/docker.github.io/pull/9980.
