### ISSUE TITLE
The links for `Add TLS certificates` are incorrect on the website, but seem to be correct in the source code on master

### ISSUE THREAD

**Issue by espoelstra** [docker/docker.github.io#7765]
File: [docker-for-mac/faqs.md](https://docs.docker.com/docker-for-mac/faqs/)

In these paragraphs,

How do I add custom CA certificates?
Starting with Docker for Mac Beta 27 and Stable 1.12.3, all trusted certificate authorities (CAs) (root or intermediate) are supported.

For full information on adding server and client side certs, see Add TLS certificates in the Getting Started topic.

How do I add client certificates?
Starting with Docker for Mac 17.06.0-ce, you do not need to push your certificates with git commands anymore. You can put your client certificates in ~/.docker/certs.d/<MyRegistry>:<Port>/client.cert and ~/.docker/certs.d/<MyRegistry>:<Port>/client.key.

For full information on adding server and client side certs, see Add TLS certificates in the Getting Started topic.

**Comment by aevesdocker** [comment]
Closing as issue has been fixed
