### ISSUE TITLE
Get Started part 4 connection refused from node on virtual machine

### ISSUE THREAD

**Issue by steve-donnelly** [docker/docker.github.io#7767]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

The issue is described and resolved in this forum page:
https://forums.docker.com/t/get-started-part-4-connection-refused-from-node-on-virtual-machine/62511
Also https://github.com/docker/machine/issues/4608

Port is 4000, netstat -l shows 4000 is it listening on the vm but curl http://localhost:4000 still returns Connection Refused.

**Comment by DawnWood-Docker** [comment]
Hi @steve-donnelly Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
