### ISSUE TITLE
Engine requirement needs fix.

### ISSUE THREAD

**Issue by ekitagawa** [docker/docker.github.io#7769]
File: [ee/ucp/admin/install/system-requirements.md](https://docs.docker.com/ee/ucp/admin/install/system-requirements/)

I found this statement:
> Docker EE Engine version 18.09.0-ee-8; values of n in the -ee-<n> suffix must be 8 or higher
 
However, there is no `ee-8` build exists.  I could have just deleted that line, but I wasn't sure about the policy around supporting UCP 2.1 with 17.06 engine.

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
