### ISSUE TITLE
Article -  docker build trough UCP

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#7771]
### Problem description

You should highlight and demonstrate that you can run docker build through Universal Control Plane
in a safer way than having to have direct container host access.
Maybe you can show alternative ways to do builds without having to have privileged access.

### Problem location

Is this feature widely known ?

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
