### ISSUE TITLE
Bad yum-config-manager line for 18.09

### ISSUE THREAD

**Issue by arueth** [docker/docker.github.io#7773]
`sudo yum-config-manager --enable docker-ee-stable-18.09.0`
should be:
`sudo yum-config-manager --enable docker-ee-stable-18.09`

File: [install/linux/docker-ee/centos.md](https://docs.docker.com/install/linux/docker-ee/centos/)

**Comment by thaJeztah** [comment]
@seemethere @ahh-docker PTAL

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
