### ISSUE TITLE
`swarm ca` does not seem to be a part of the command line client anymore

### ISSUE THREAD

**Issue by artheus** [docker/docker.github.io#7778]
File: [engine/reference/commandline/swarm_ca.md](https://docs.docker.com/engine/reference/commandline/swarm_ca/)

Should be deprecated, scoped to specific versions or removed.

**Comment by thaJeztah** [comment]
What version of docker are you running? 

```
docker swarm ca --help

Usage:	docker swarm ca [OPTIONS]

Display and rotate the root CA

Options:
      --ca-cert pem-file          Path to the PEM-formatted root CA certificate to use for the new cluster
      --ca-key pem-file           Path to the PEM-formatted root CA key to use for the new cluster
      --cert-expiry duration      Validity period for node certificates (ns|us|ms|s|m|h) (default 2160h0m0s)
  -d, --detach                    Exit immediately instead of waiting for the root rotation to converge
      --external-ca external-ca   Specifications of one or more certificate signing endpoints
  -q, --quiet                     Suppress progress output
      --rotate                    Rotate the swarm CA - if no certificate or key are provided, new ones will be generated
```

w.r.t. scoped to specific version; this command requires API version 1.30, which correlates to Docker Engine 17.06 and up; https://docs.docker.com/develop/sdk/#api-version-matrix

The current documentation is for version 18.09;

<img width="294" alt="screenshot 2018-12-02 at 14 07 43" src="https://user-images.githubusercontent.com/1804568/49340128-f6dd4600-f63b-11e8-84e2-29e7cc1c703b.png">


but you can use that dropdown to view reference docs for older versions, for example, when selecting [the Docker 17.03 version of the documentation](https://docs.docker.com/v17.03/reference/), the command is not listed

<img width="346" alt="screenshot 2018-12-02 at 14 09 36" src="https://user-images.githubusercontent.com/1804568/49340139-212f0380-f63c-11e8-93a0-0984c863412e.png">

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As this issue is dated, some of the previous information for the solution may no longer apply. I'll close this as stale, but if the issue still persists, please provide the information requested in the previous comment and help open the issue or a PR in the source repo for the content at https://github.com/docker/cli/tree/master/docs/reference/commandline
