### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by Phelilix** [docker/docker.github.io#7779]
The nearest header is: https://docs.docker.com/edge/engine/reference/commandline/build/#build-with-path

The text of the broken link is: ADD

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The docs have changed since you reported the issue, so some context was lost. The link for the "ADD" text now links to https://docs.docker.com/engine/reference/builder/#add . If there's still any issue, please let us know.
