### ISSUE TITLE
Getting-started Part 3 and Part 4 breaks with boot2docker.iso v18.09.0

### ISSUE THREAD

**Issue by kamry-bowman** [docker/docker.github.io#7780]
File: [machine/get-started.md](https://docs.docker.com/machine/get-started/)

Going through this tutorial, for Parts 3 and 4, I was unable to get responses from the exposed port from my swarm.

I found a solution here:
https://forums.docker.com/t/get-started-part-4-connection-refused-from-node-on-virtual-machine/62511/10

Essentially, when vms get created, they need to use this boot2docker iso https://github.com/boot2docker/boot2docker/releases/tag/v18.06.1-ce

It practice it just means adding `--virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.06.1-ce/boot2docker.iso` to the command to create a new vm. 

Not sure if this is a transient issue that will be fixed, but in practice having the basic intro tutorial not work made me feel like docker wasn't going to work for me, and it was only digging around in the forums that allowed me to get it back running.

So is it worth adding a note of some sort to the tutorial at least until this is fixed?

**Comment by paigehargrave** [comment]
@kamry-bowman Hi, very sorry for the delayed response on this. We believe this has been fixed in Engine version 18.09.2 using `docker service create -p 5000:80 nginx`. (More information in https://github.com/docker/machine/issues/4608.)

**Comment by bermudezmt** [comment]
Hey @kamry-bowman if there's still a problem, please submit a new issue. We believe this has been fixed as per https://github.com/docker/docker.github.io/issues/7780#issuecomment-469022882.
