### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by kbruner** [docker/docker.github.io#7784]
From https://docs.docker.com/v17.09/engine/installation/ click on "Amazon Web Services setup guide" under Docker Cloud (https://docs.docker.com/v17.09/docker-cloud/cloud-swarm/link-aws-swarm/)

**Comment by ahh-docker** [comment]
@L-Hudson This is an archive link that's broken. Please advise how to proceed. CC: @thaJeztah

**Comment by bermudezmt** [comment]
@kbruner sorry for the delayed response. Docker Cloud has been deprecated so we've removed the section and added a redirect to Docker Hub. Please submit another issue if you're still experiencing problems.
