### ISSUE TITLE
Docker file usage rights issue

### ISSUE THREAD

**Issue by HualongWu** [docker/docker.github.io#7786]
### Problem description
  The main problem is the permission issue that occurs after docker -v is mounted. If you use docker run -v to mount the local folder, enter the container and find that the folder to be mounted has root permissions and is in the container. Create a file on the mounted folder, then the permissions of this file are also root, so there is a big security issue. If the namespace "user-remap" "default" is used, the properties of the folder mounted by docker -v are none and nogroup. Although the security problem is solved, I can't mount any folder. The function I want to achieve is that after the normal user joins the docker user group, it can be obtained by using the docker run -v to get the corresponding user's permission to use the folder. How can I solve this?

PS：OS is Ubuntu 16.04，There are two users test1 and test2 in this machine and there is no sudo permission.

**Comment by L-Hudson** [comment]
This is not a documentation ticket; closing.
