### ISSUE TITLE
Kubernetes ingress link points to Kube 1.8 docs instead of 1.11

### ISSUE THREAD

**Issue by arueth** [docker/docker.github.io#7793]
File: [ee/ucp/kubernetes/layer-7-routing.md](https://docs.docker.com/ee/ucp/kubernetes/layer-7-routing/)

Kubernetes provides an NGINX ingress controller that you can use in Docker EE without modifications. Learn about ingress in Kubernetes.

The 'ingress in Kubernetes' link points to https://v1-8.docs.kubernetes.io/docs/concepts/services-networking/ingress/ which no longer exist. It should point to https://v1-11.docs.kubernetes.io/docs/concepts/services-networking/ingress/ as that is the current version we are on.

**Comment by bermudezmt** [comment]
@arueth this will be fixed via #8375 which should get merged soon.
