### ISSUE TITLE
404 on "ingress in Kubernetes" link

### ISSUE THREAD

**Issue by bermudezmt** [docker/docker.github.io#7804]
File: [ee/ucp/kubernetes/layer-7-routing.md](https://docs.docker.com/ee/ucp/kubernetes/layer-7-routing/)

**Comment by thaJeztah** [comment]
Source for the docs can be found here; https://github.com/kubernetes/website/tree/snapshot-final-v1.8

Perhaps we should host it ourself

**Comment by traci-morrison** [comment]
This issue was resolved via https://github.com/docker/docker.github.io/pull/1228.
