### ISSUE TITLE
Incorrect instructions on UCP Kubernetes deployment doc

### ISSUE THREAD

**Issue by bermudezmt** [docker/docker.github.io#7807]
### Problem description

![screenshot from 2018-12-06 14-53-42](https://user-images.githubusercontent.com/5844484/49616821-f4922900-f966-11e8-9405-75ab8ddce912.png)

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/ee/ucp/kubernetes/#inspect-the-deployment

### Project version(s) affected

All versions

### Suggestions for a fix
Update deployment guide for Kubernetes

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
