### ISSUE TITLE
Outdated instructions

### ISSUE THREAD

**Issue by bermudezmt** [docker/docker.github.io#7810]
File: [ee/ucp/kubernetes/layer-7-routing.md](https://docs.docker.com/ee/ucp/kubernetes/layer-7-routing/)
"In the ingress-nginx namespace, click the More options icon, and in the context menu, select Set Context."

**Comment by bermudezmt** [comment]
Follow up with @paigehargrave on this one.

**Comment by paigehargrave** [comment]
@bermudezmt - Looks like this can be closed due to the restructuring of this topic, but wanted to verify with you first.
