### ISSUE TITLE
Changing administrator password incorrect index in command

### ISSUE THREAD

**Issue by prashshr** [docker/docker.github.io#7815]
### Problem description

When changing the UCP administrator password. It doesn't work in all scenarios, e.g. the index 0 returns `--debug` instead of `--db-addr` if UCP is logging in debug mode.

There could possibly be more scenarios, but this one was reported by the customer and could easily corroborate in a lab after enabling DEBUG logging in UCP.

Incorrect:
```
$ docker inspect --format '{{ index .Spec.TaskTemplate.ContainerSpec.Args 0 }}' ucp-auth-api
--debug
```

Correct:

```
$ docker inspect --format '{{ index .Spec.TaskTemplate.ContainerSpec.Args 0 }}' ucp-auth-api
--db-addr=127.0.0.1:12383
```
### Problem location

Documentation Link:
https://docs.docker.com/ee/ucp/authorization/reset-user-password/#change-administrator-passwords

### Project version(s) affected

UCP

### Suggestions for a fix

Can do with piped filters but would be cleaner if we have it done within `--format`

**Comment by prashshr** [comment]
For a quick check, do we have an update on this?

**Comment by bermudezmt** [comment]
Update the command when running in debug mode

**Comment by paigehargrave** [comment]
@prashshr Hi - please see the suggested fix in https://github.com/docker/docker.github.io/pull/8274 - I only added a brief statement - not sure what else is needed. Can you PTAL? Thank you!

**Comment by paigehargrave** [comment]
@prashshr - PTAL when you have a moment - thank you!

**Comment by prashshr** [comment]
@paigehargrave In my view, asking the customer to revert from `DEBUG` log level won't be a reasonable step. We may instead adopt either of the two approaches,

1. An alternate command, when UCP is running in `DEBUG` log level. Use index `1` instead of `0` in that case:
```
$ docker inspect --format '{{ index .Spec.TaskTemplate.ContainerSpec.Args 1 }}' ucp-auth-api
--db-addr=127.0.0.1:12383
```


2. Have a single command which rather than using indexing, looks for a text `db-addr` in `.Spec.TaskTemplate.ContainerSpec` to get the database address value.

Unfortunately, I haven't been able to get a working command/filter for this. I will check with Customer success team if someone has a command handy. Additionally it'll be great if someone in engineering well-versed in filtering could help quickly with this.

**Comment by paigehargrave** [comment]
@prashshr - Are you OK with closing this issue since #8274 got merged? Thanks!

**Comment by prashshr** [comment]
@paigehargrave LGTM.
Thanks.

**Comment by paigehargrave** [comment]
@prashshr Thank you!
