### ISSUE TITLE
No hyperlinklink

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#7821]
File: [ee/upgrade.md](https://docs.docker.com/ee/upgrade/)

There is no link to a doc/anchor link for upgrading EE, this is inconsistent and inconvenient.

**Comment by traci-morrison** [comment]
To upgrade Docker Enterprise, you must individually upgrade each of the components described on the page. The instructions to upgrade Docker Engine - Enterprise are described here, which is linked from that page: https://docs.docker.com/ee/upgrade/#upgrade-docker-engine---enterprise
