### ISSUE TITLE
Zip file donwload Not found, no such key

### ISSUE THREAD

**Issue by willam-gregoire** [docker/docker.github.io#7827]
DockerEE does not download usign this script. Where can I find the the correct links?

File: [install/windows/docker-ee.md](https://docs.docker.com/install/windows/docker-ee/)

PS C:\Users\dockeradmin> invoke-webrequest -UseBasicparsing -Outfile docker-18.09.1-ee-18.zip https://download.docker.com/components/engine/windows-server/2.1/docker-18.09.1-ee-18.zip
invoke-webrequest :
404 Not Found
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: components/engine/windows-server/2.1/docker-18.09.1-ee-18.zip
RequestId: 5AF334EB33B9F8AB
HostId: MW17Ek05/1gN/zlo2XqjlQHPe9ElQWZD4Nyp5R8fBf3lrIM28bUk5AD+pZrfr+SQyYjczcyP658=
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html
At line:1 char:1
+ invoke-webrequest -UseBasicparsing -Outfile docker-18.09.1-ee-18.zip  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by willam-gregoire** [comment]
I found the error:

on the URL, 2.1 shoudl be removed...correct url is:

https://download.docker.com/components/engine/windows-server/17.06/docker-17.06.2-ee-16.zip

**Comment by paigehargrave** [comment]
@willam-gregoire - Thank you for bringing this to our attention! To find the link for 17.06, please refer to https://docs.docker.com/v17.12/install/windows/docker-ee/#use-a-script-to-install-docker-ee.

**Comment by ajeyaprakash148** [comment]
Can anyone tell me for the Community Edition?
