### ISSUE TITLE
Node RBAC instructions don't seem to be updated to EE 2.1/UCP 3.1

### ISSUE THREAD

**Issue by nicolaka** [docker/docker.github.io#7828]
The instructions listed are for EE 2.0 not latest 2.1 version. Current docs don't work in UCP 3.1.

File: [ee/ucp/authorization/isolate-nodes.md](https://docs.docker.com/ee/ucp/authorization/isolate-nodes/)

**Comment by bermudezmt** [comment]
@nicolaka what isn't covered in the 3.1 version of the page? Can you please give us some more details?

**Comment by nicolaka** [comment]
@bermudezmt the second part of that page is basically not up-to-date with the new introduction of the Kubernetes-native RBAC in 3.1. Along with the images associated with it ( it's not just the images btw, it's foundational not application for anyone using version 3.1 or newer). 

The correct method to associating a namespace to nodes is in the namespace definition itself. The info is provided here : https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector.

Happy to help if you have more questions.

**Comment by paigehargrave** [comment]
@nicolaka  Thank you for the information! We are working on the UCP backlog, and will put this on our 'list'. Is this causing customer problems? If so, we can prioritize it and get to it sooner.

**Comment by paigehargrave** [comment]
@nicolaka - I've attempted some updates in https://github.com/docker/docker.github.io/pull/8309. Please bear with me as I try to learn this stuff! (And yes, you're allowed to laugh at my attempt. :)) PTAL and see what needs to be fixed/added/deleted. Thank you!

**Comment by nicolaka** [comment]
I provided my feedback @paigehargrave

**Comment by traci-morrison** [comment]
Updates made in https://github.com/docker/docker.github.io/pull/8309.
