### ISSUE TITLE
Typo in "binding.s"; it should be written "bindings."

### ISSUE THREAD

**Issue by glennie** [docker/docker.github.io#7841]
File: [glossary.md](https://docs.docker.com/glossary/)

Hello,
There is typo on https://docs.docker.com/glossary/?term=fig (on line "docker-compose port"). It says "Prints the public port for a port binding.s". The last word should written as "bindings." not as "binding.s".

Kind regards,

**Comment by adzimzf** [comment]
Hi,
anyone pick this issue?
