### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by Muscothym** [docker/docker.github.io#7842]
I googled ucp-instance-id

result returned:
https://docs.docker.com/reference/ucp/
https://docs.docker.com/reference/ucp/3.0/
https://docs.docker.com/reference/ucp/3.0/cli/
https://docs.docker.com/reference/ucp/3.0/cli/id/
https://docs.docker.com/reference/ucp/3.0/cli/backup/

Action:
navigated to the page
Result:
Each of the above links gave the following error message from site. 

>     Sorry, we can't find that page
>      it seems the page you’re looking for doesn’t exist. Maybe you’re on the wrong track, maybe you 
>      found a broken link. Who knows?

as an aside:
What I was trying to access:
in the UCP backup it requires a "ucp-instance-id" and would like to know how to find it.

**Comment by bermudezmt** [comment]
@Muscothym the last URL should properly redirect you now to https://docs.docker.com/datacenter/ucp/3.0/reference/cli/backup/. The latest UCP CLI pages point to https://docs.docker.com/reference/ucp/3.1/cli/, so `3.0` is now archived. Since Google hasn't indexed the new pages yet, I added redirects.
