### ISSUE TITLE
Wrong hyperlink

### ISSUE THREAD

**Issue by arnauvc** [docker/docker.github.io#7843]
File: [ee/end-to-end-install.md](https://docs.docker.com/ee/end-to-end-install/)

The hyperlink "Docker Enterprise Edition" on the first bullet point redirects to Docker Community Edition instead of Docker Enterprise

![docker_link](https://user-images.githubusercontent.com/5579758/49875816-3b2dca80-fe22-11e8-9d75-b8963723e3d4.PNG)

**Comment by traci-morrison** [comment]
This issue is resolved. If the problem persists, please open a new issue. Thank you.
