### ISSUE TITLE
UCP Interlock Documentation Unclear on "Host" mode

### ISSUE THREAD

**Issue by stshow** [docker/docker.github.io#7844]
@mklamb commented on [Fri Sep 28 2018](https://github.com/docker/docs.docker.com/issues/303)

The documentation states to set PublishMode = "host" in the configuration of the "ucp-interlock" service and gives no other possible action to take. The expected outcome would be to have ucp-interlock and ucp-interlock-extension communicate over exposed ports. 

By doing only this action ,what happens is that the ucp-interlock-proxy gets exposed using host mode networking (good!) but nothing else. So as far as I can tell the only 2 options are to 

A) Expose ucp-interlock-proxy using ingress 
B) Expose ucp-interlock-proxy using host mode 

There are other configurations that are possible.  For example, you can choose to:
A)Configure the ucp-interlock and ucp-interlock-extension services to communicate using host mode networking. 
B)Configure the ucp-interlock-proxy and your swarm service to communicate using host mode networking. 
C)Use host mode networking for all of the components. 

So we have multiple configuration options available.  We should either 1) list them in the docs or 2) provide advice against these configurations if we are not comfortable with their behavior in the product

thanks

---

@thaJeztah commented on [Wed Oct 31 2018](https://github.com/docker/docs.docker.com/issues/303#issuecomment-434878788)

Could you open this ticket in the https://github.com/docker.github.io/issues issue tracker?

**Comment by stshow** [comment]
This may help: https://interlock-dev-docs.netlify.com/usage/host_mode/

**Comment by stshow** [comment]
Problematic docs: https://docs.docker.com/ee/ucp/interlock/deploy/host-mode-networking/

**Comment by bermudezmt** [comment]
@david-yu can you weigh in on this? I think we missed this during our prioritization call. cc: @paigehargrave

**Comment by david-yu** [comment]
@mark-church Would be the best person to weigh on Interlock, since it is networking related

**Comment by paigehargrave** [comment]
@stshow @mklamb - Can you PTAL and see if the information refactor has resolved the concerns? I have pulled in all the information from the Netlify site into docs.docker.com. Thank you in advance for your time!

**Comment by mklamb** [comment]
LGTM

**Comment by paigehargrave** [comment]
@mklamb @stshow Thank you Kent! Steven, I'm going to close this issue, but if you have additional concerns, please let me know and I can reopen this. Thanks in advance.
