### ISSUE TITLE
remove outdated ambassador pattern

### ISSUE THREAD

**Issue by programmerq** [docker/docker.github.io#7845]
File: [config/thirdparty/ambassador_pattern_linking.md](https://docs.docker.com/config/thirdparty/ambassador_pattern_linking/)

The ambassador pattern was superceded by multihost networking and service discovery which was introduced in [2015 with Docker 1.9](https://github.com/moby/moby/blob/master/CHANGELOG.md#190-2015-11-03)

This section of the docs has been marked obsolete for some time, and older versions of the docs will still include this information. It is probably time to remove this from the docs altogether.

**Comment by JustinINevill** [comment]
@bermudezmt Approved to remove from current version. Thanks @programmerq for spotting and raising!
