### ISSUE TITLE
Update docker diff command instructions

### ISSUE THREAD

**Issue by Pa1K** [docker/docker.github.io#785]
File: [engine/reference/commandline/diff.md](https://docs.docker.com/engine/reference/commandline/diff/)
docker diff CONTAINER
here CONTAINER is container id or container name

**Comment by mstanleyjones** [comment]
The file already has this:

```none
You can use the full or shortened container ID or the container name set using docker run --name option.
```

I think that is adequate. If you disagree, please file a bug in the `docker/docker` repository, where the source code that generates this text resides.
