### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by gtholpadiperitusai** [docker/docker.github.io#7851]
I was reading this page: https://docs.docker.com/samples/library/solr/#distributed-solr --- and saw a link to this page: https://docs.docker.com/samples/library/solr/docs/docker-networking/

But the latter link seems to be broken.

**Comment by L-Hudson** [comment]
Looks like the "example" page no longer exists... remove reference.

**Comment by bermudezmt** [comment]
Need to verify the fix on the next docs publishing schedule.

**Comment by bermudezmt** [comment]
@gtholpadiperitusai thanks for bringing this to our attention. This has been fixed!
