### ISSUE TITLE
Clarify Linux/Windows Security scan inconsistencies

### ISSUE THREAD

**Issue by jasonbivins** [docker/docker.github.io#7854]
File: [docker-hub/official_images.md](https://docs.docker.com/docker-hub/official_images/)
Windows images do not show scan results - but Linux images do.  Please update the docs to make this more clear

```
Navigate to the repository of the Official Image whose security scan you want to view.
Click the Tags tab to see a list of tags and their security scan summaries.
```

This is correct for Linux images:  https://hub.docker.com/r/library/alpine/tags/

Microsoft Images are very different, there is no security scan information
https://hub.docker.com/r/microsoft/nanoserver/tags/
https://hub.docker.com/r/microsoft/dotnet/tags/

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the issue is old, a lot has changed. The information is no longer applicable.
