### ISSUE TITLE
Nginx example points to wrong file location

### ISSUE THREAD

**Issue by demee** [docker/docker.github.io#786]
File: [swarm/swarm_at_scale/deploy-infra.md](https://docs.docker.com/swarm/swarm_at_scale/deploy-infra/)

 /etc/conf/nginx.conf <- this file does not exist normally and it's suggested in one of the examples. Docker container does not start because of that. Please update with correct file location/content.

**Comment by shubheksha** [comment]
What will be the correct file location for this?

**Comment by prashant171992** [comment]
Raised a PR here : https://github.com/docker/docker.github.io/pull/2833

**Comment by prashant171992** [comment]
@demee can u please take a look at the PR .
