### ISSUE TITLE
wrong statememt in supported-platforms

### ISSUE THREAD

**Issue by jzyao** [docker/docker.github.io#7860]
### Problem description

In page, https://docs.docker.com/ee/supported-platforms/#new-licensing-for-docker-enterprise
It is listed
```
When using Docker Enterprise

IBM Power is not supported as managers or workers. Microsoft Windows Server is not supported as a manager. Microsoft Windows Server 1803 is not supported as a worker.
```
I think this is wrong 'Microsoft Windows Server 1803 is not supported as a worker.'

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
