### ISSUE TITLE
Request to add repo for Power 9 users

### ISSUE THREAD

**Issue by hannah-docker** [docker/docker.github.io#7861]
- Request is to add to this section

```
For IBM Power only (little endian):

$ sudo yum-config-manager --enable extras
$ sudo subscription-manager repos --enable=rhel-7-for-power-le-extras-rpms
$ sudo yum makecache fast
$ sudo yum -y install container-selinux
```
- The repository `rhel-7-for-power-le-extras-rpms` only address Power 8 and users might also need to know about:
"Red Hat Enterprise Linux 7 for IBM Power 9 - Extras (RPMs)" that requires `rhel-7-for-power-9-extras-rpms` Power 9 repository. 

File: [install/linux/docker-ee/rhel.md](https://docs.docker.com/install/linux/docker-ee/rhel/)

**Comment by hannah-docker** [comment]
Just checking in on this one, is this going to be updated?

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this here for that reason. Feel free to continue the conversation after I close.
