### ISSUE TITLE
wrong engine version in system requirements

### ISSUE THREAD

**Issue by doanbutar** [docker/docker.github.io#7863]
### Problem description

In page, https://docs.docker.com/ee/ucp/admin/install/system-requirements/

It was mentioned that Docker EE Engine version `18.09.0-ee-8`; values of n in the -ee-<n> suffix must be 8 or higher

### Suggestions for a fix
I think it should be Docker EE Engine version `18.09.0-ee-1` or higher

**Comment by bermudezmt** [comment]
Closed by https://github.com/docker/docker.github.io/pull/8046.
