### ISSUE TITLE
Networking documentation lacking

### ISSUE THREAD

**Issue by Ghent** [docker/docker.github.io#7884]
File: [engine/userguide/networking/index.md](https://docs.docker.com/engine/userguide/networking/)

So... lots left out here.  What's `::` do in `-p`?  How do you bind a port range (not a singular port) with a specific external IP?  If these questions are answered elsewhere, where is that?  I would expect to find those answers here in the networking documentation.  I appreciate what's here, but documentation isn't a stream of consciousness conversation, it should be specific and thorough.

**Comment by L-Hudson** [comment]
Thanks for the comment, @Ghent. We're doing a refactoring, after which we expect these sorts of issues to be resolved. If you have any specific changes you'd like to see, don't hesitate to file another ticket. Thanks!
