### ISSUE TITLE
text says port 80 is mapped to 4000, but don't see where this happens

### ISSUE THREAD

**Issue by shabaz** [docker/docker.github.io#7889]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)
I'm going through the docs and I can see where port 80 is mapped to port 80, but not 4000 (where the text states "Map port 4000 on the host to web’s port 80"), in the yaml file on top. Looking through commits I guess this was changed recently. I guess the text could be changed to be consistent with the YAML file, though I would argue it is nice having two different ports here so it is clear which one is the internal port and which is the external.

**Comment by L-Hudson** [comment]
fixed in other tickets.
