### ISSUE TITLE
Update Engine Install Instructions

### ISSUE THREAD

**Issue by jasonbivins** [docker/docker.github.io#7903]
File: [ee/end-to-end-install.md](https://docs.docker.com/ee/end-to-end-install/)

Step 1: Select a platform and click through to install the Docker Enterprise Edition container engine on all hosts you want to manage.

The link goes here but there are no instructions on how to install anything : 
 https://docs.docker.com/ee/supported-platforms/

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
