### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by vossenjp** [docker/docker.github.io#7907]
https://docs.docker.com/docker-hub/official_images/ has a link in "...Exemplify Dockerfile best practices and..." to https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/ which is 404.
I just found https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ in Google and it's 404 too.  But https://docs.docker.com/v17.12/develop/develop-images/dockerfile_best-practices/ works.

**Comment by bermudezmt** [comment]
@jmorganca can you please address?
