### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by ozanoner** [docker/docker.github.io#7909]
Hi,
Page: https://docs.docker.com/engine/reference/commandline/docker/#child-commands 
navigate to "docker builder" leads to 
https://docs.docker.com/engine/reference/commandline/builder/
which says
"Sorry, we can't find that page
It seems the page you’re looking for doesn’t exist. Maybe you’re on the wrong track, maybe you found a broken link. Who knows?

Either way, here’s a couple of options for you:

Open an issue
Go to back
Tweet us something"  

Regards

**Comment by paigehargrave** [comment]
Anne - Currently, builder.md is outside of the command line directory within https://github.com/docker/cli/tree/master/docs/reference/. This needs to be moved in order to prevent the 404 within docs.docker.com. We don't have access to this repo to change it.

**Comment by craig-osterhout** [comment]
The link (https://docs.docker.com/engine/reference/commandline/builder/) no longer returns an error. If you're still experiencing an issue, please let us know.
