### ISSUE TITLE
We should not officially endorse the community-supported editions

### ISSUE THREAD

**Issue by johndmulhausen** [docker/docker.github.io#791]
@bettyjunod and I were talking about this. We appreciate the community-supported editions, but we send mixed messages to users about our support level when we link to them. 

- Arch Linux
- OpenSUSE
- CRUX Linux
- Gentoo

Wherever we mention these -- if people have problems, they are using packages that we didn't create and for which we can't vouch. This will become more imperative to fix as editions come out of beta.

**Comment by londoncalling** [comment]
@johndmulhausen I believe this issue is no longer a problem per the new website and @mstanleyjones 's updates to Linux installers. Is that correct? If so, I'll close this one ...

**Comment by londoncalling** [comment]
This is addressed per the referenced PR ^^
