### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by Sun-pei** [docker/docker.github.io#7910]
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Best practices for writing Dockerfiles | Docker Documentation。

Sorry, we can't find that page
It seems the page you’re looking for doesn’t exist. Maybe you’re on the wrong track, maybe you found a broken link. Who knows?

Either way, here’s a couple of options for you:

Open an issue
Go to back
Tweet us something

**Comment by bermudezmt** [comment]
Fixed by #7908 .
