### ISSUE TITLE
No description for `scheduledAt` variable.

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#7919]
File: [ee/dtr/admin/manage-jobs/job-queue.md](https://docs.docker.com/ee/dtr/admin/manage-jobs/job-queue/)

`scheduledAt` is not described anywhere in the documentation.

**Comment by bermudezmt** [comment]
Hey @kavikat , I have transformed Job Queue into a "required reading" page before you can perform job audits [via the UI](https://docs.docker.com/ee/dtr/admin/manage-jobs/audit-jobs-via-ui/) and [via the API](https://docs.docker.com/ee/dtr/admin/manage-jobs/audit-jobs-via-api/), which is currently at `v0`. The DTR team and I are in the beginning stages of scoping out the work for fleshing out our API documentation. I am hoping that we can start documenting example JSON responses and what the response fields represent in the near future. cc: @caervs @Docker-Minh
