### ISSUE TITLE
Digital Ocean docker-machine seems to be incorrect on hello world example

### ISSUE THREAD

**Issue by CerebralMastication** [docker/docker.github.io#7923]
File: [machine/examples/ocean.md](https://docs.docker.com/machine/examples/ocean/)

In documentation Step 4 point 2. It looks like this chunk is for local docker, not docker-machine. Running the commands as given runs them locally. 

I'm new to Docker and docker-machine so I'm not really sure what the right answer is here, but it feels like maybe we should be doing something to execute on the remote machine instead of the local. ssh maybe?

Here's what the docs say:

In this example, the -p option is used to expose port 80 from the nginx container and make it accessible on port 8000 of the docker-sandbox host.
```
 $ docker run -d -p 8000:80 --name webserver kitematic/hello-world-nginx
 Unable to find image 'kitematic/hello-world-nginx:latest' locally
 latest: Pulling from kitematic/hello-world-nginx
 a285d7f063ea: Pull complete
 2d7baf27389b: Pull complete
 ...
 Digest: sha256:ec0ca6dcb034916784c988b4f2432716e2e92b995ac606e080c7a54b52b87066
 Status: Downloaded newer image for kitematic/hello-world-nginx:latest
 942dfb4a0eaae75bf26c9785ade4ff47ceb2ec2a152be82b9d7960e8b5777e65
```
In a web browser, go to http://<host_ip>:8000 to bring up the webserver home page. You got the <host_ip> from the output of the docker-machine ip <machine> command you ran in a previous step. Use the port you exposed in the docker run command.

**Comment by thaJeztah** [comment]
The docker cli connects to the docker daemon running on the remote machine using the docker API, so there's no need to ssh into that machine.

**Comment by CerebralMastication** [comment]
Ah, I see now what's supposed to be happening. Only on my Mac it does not automatically connect. But now that I know what's supposed to be happening I realize what I need to do is this:

> The new docker-sandbox machine is running, and it is the active host as indicated by the asterisk (*). When you create a new machine, your command shell automatically connects to it. If for some reason your new machine is not the active host, run docker-machine env docker-sandbox, followed by eval $(docker-machine env docker-sandbox) to connect to it.

This is one of those things where once I realize the expected behavior then I can grok the docs. Thanks for the explanation.
