### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by eysz7x** [docker/docker.github.io#7939]
### Problem location

- I saw a problem on the following URL: [![Bugs](https://img.shields.io/github/issues/Microsoft/vscode/bug.svg)](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Abug)

- I couldn't find the information I wanted. I expected to find it near the following URL: [![Feature Requests](https://img.shields.io/github/issues/Microsoft/vscode/feature-request.svg)](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc)

- Other: [![npm](https://img.shields.io/npm/v/apollo.svg)](https://www.npmjs.com/package/apollo) [![Get on Slack](https://img.shields.io/badge/slack-join-orange.svg)](http://www.apollostack.com/#slack) [![Maven Central](https://img.shields.io/maven-central/v/net.zetetic/android-database-sqlcipher.svg?label=Maven%20Central)](https://search.maven.org/search?q=g:%22net.zetetic%22%20AND%20a:%22android-database-sqlcipher%22)

**Comment by eysz7x** [comment]
[![Feature Requests](https://img.shields.io/github/issues/Microsoft/vscode/feature-request.svg)](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc) [![Bugs](https://img.shields.io/github/issues/Microsoft/vscode/bug.svg)](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Abug)

**Comment by L-Hudson** [comment]
It's been a week with no response; I'm going to close the ticket. If you feel that this was an error, please feel free to reopen the ticket with the necessary information. Thanks!
