### ISSUE TITLE
Remote syslog setup has been removed in 3.1.x < , misleading screenshot of UI

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#7940]
File: [ee/ucp/admin/configure/store-logs-in-an-external-system.md](https://docs.docker.com/ee/ucp/admin/configure/store-logs-in-an-external-system/)

**Comment by kavikat** [comment]
The screenshot of the remote syslog setup in the UI is misleading for UCP 3.1.x users as this feature has ben removed.

**Comment by bermudezmt** [comment]
Closed by #8071 .
