### ISSUE TITLE
Can't access cluster

### ISSUE THREAD

**Issue by weslowsk** [docker/docker.github.io#7944]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

After getting to the "accessing your cluster" section, I'm unable to proceed because neither of the nodes are responding when I try to access them in the browser, as shown by the screenshot. I thought that port 4000 was just missing and I tried adding that port to the URLs but that didn't make a difference.
How can I proceed with the getting started guide?

**Comment by bermudezmt** [comment]
Hi @weslowsk , what's the output of `docker-machine ls`? And were you trying to access the app using your VM's IP address as shown here? https://docs.docker.com/get-started/part4/#configure-a-docker-machine-shell-to-the-swarm-manager

**Comment by weslowsk** [comment]
I don't remember what the output of docker-machine ls was.

There was a problem with the latest boot2docker iso as described here.

https://forums.docker.com/t/get-started-part-4-connection-refused-from-node-on-virtual-machine/62511/9

I resolved the issue by using an older boot2docker image, as described in the post.

**Comment by bermudezmt** [comment]
Hey, thanks for linking that! Looks like it's a known Docker machine issue that should be fixed in `18.09.1`

**Comment by bermudezmt** [comment]
@ahh-docker I think this needs to be added to the list of known issues in the release notes for `18.09.0` (if not there already): https://github.com/docker/machine/issues/4608

**Comment by paigehargrave** [comment]
@weslowsk - I added this to the release notes for the late January patch - please let me know if it's no longer needed - thanks!
https://github.com/docker/docs-private/pull/929

**Comment by weslowsk** [comment]
If it's in the release notes, then that should take care of it.

**Comment by bermudezmt** [comment]
Thanks for taking care of this, @paigehargrave , and @weslowsk for bringing it to our attention!
