### ISSUE TITLE
Install steps for Centos and remote access needs an update

### ISSUE THREAD

**Issue by tomko80** [docker/docker.github.io#7946]
File: [install/linux/docker-ce/centos.md](https://docs.docker.com/install/linux/docker-ce/centos/)
Under "configuring remote access": 

- fd:// will not work, use /usr/bin/dockerd -H unix:// -H tcp://127.0.0.1:2375
- netstat is depreciated, use ss

**Comment by thaJeztah** [comment]
`fd://` should work to use socket-activation; what version of docker are you running? docker versions before 18.09 didn't have socket activation on the rpm packages

**Comment by L-Hudson** [comment]
More than a week without response; I'm closing the ticket. Feel free to reopen if you feel you need to circle back. Thanks!
