### ISSUE TITLE
docker-machine env does not seem to work on Ubuntu on Windows

### ISSUE THREAD

**Issue by tinne** [docker/docker.github.io#7947]
When I set my environment as described in file: [get-started/part4.md](https://docs.docker.com/get-started/part4/) using not a PowerShell or Cmd shell on Windows, but instead running a Ubuntu shell using the Windows linux subsystem (in my case, Ubuntu 18.04 LTS on Windows 10 Pro 17763.rs5_release.180914-1434), setting the environment as specified by the output of `docker-machine.exe env <some-machine>` does not make docker automatically connect to the remote machine when issuing commands to the swarm manager.

It should be added to the documentation that in this case a manual set up of the shell at hand is necessary, by running `eval $(docker-machine.exe env --shell bash <some-machine>)`.

(Then again, irrespective whether I auto-set the environment as specified above of manually configure and export env to adjust the five relevant environment variables, docker.exe simply seems to ignore them. Kindly point me to where to report this in case you also consider it an error.)

**Comment by DawnWood-Docker** [comment]
Hi @tinne Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
