### ISSUE TITLE
Typo in network-tutorial-overlay

### ISSUE THREAD

**Issue by billgrant** [docker/docker.github.io#7952]
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)

```
$ docker swarm --join --token <TOKEN> \
  --advertise-addr <IP-ADDRESS-OF-WORKER-1> \
  <IP-ADDRESS-OF-MANAGER>:2377
```
Should be

```
$ docker swarm join --token <TOKEN> \
  --advertise-addr <IP-ADDRESS-OF-WORKER-1> \
  <IP-ADDRESS-OF-MANAGER>:2377
```

**Comment by L-Hudson** [comment]
@billgrant, your before and after are identical. Please let me know what the typo is?

**Comment by billgrant** [comment]
The after doesn't have --  
This was fixed here https://github.com/docker/docker.github.io/pull/7953

So I am going to close this.
