### ISSUE TITLE
Remote Syslog configuration not available in UCP 3.1

### ISSUE THREAD

**Issue by bootswithdefer** [docker/docker.github.io#7954]
File: [ee/ucp/admin/configure/store-logs-in-an-external-system.md](https://docs.docker.com/ee/ucp/admin/configure/store-logs-in-an-external-system/)

Docs should be updated to say that UCP 3.1 does not support Remote Syslog configuration from the UI, instead the Docker Engine must be configured in daemon.json

**Comment by bermudezmt** [comment]
Closed by #8071 . Thank you, @ollypom !
