### ISSUE TITLE
Error in documentation for ARG instruction

### ISSUE THREAD

**Issue by suneelgali** [docker/docker.github.io#7955]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

BUILDARCH - **OS component of** BUILDPLATFORM
BUILDVARIANT - **OS component of** BUILDPLATFORM

Please correct the above and update the documentation

**Comment by nigelpoulton** [comment]
Thanks @suneelgali 

Please can you be more specific about what is incorrect, and how it should look.

If you provide the detail, I'll get the doc updated.
