### ISSUE TITLE
Link to style guide on CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by sypets** [docker/docker.github.io#7960]
### Problem description

[CONTRIBUTING.md](https://github.com/docker/docker.github.io/blob/master/CONTRIBUTING.md#style-guide) contains broken link to style guide: https://github.com/docker/docker.github.io/blob/master/opensource/doc-style

**Comment by L-Hudson** [comment]
"Docker does not currently maintain a style guide. Use your best judgment, and try to follow the example set by the existing documentation."

Closing ticket.

**Comment by thaJeztah** [comment]
@L-Hudson there was a style-guide, but looks like it was accidentally removed when removing the contributing guides for the open-source projects; 
https://github.com/docker/docker.github.io/pull/5232

This is the one that was removed; https://github.com/docker/docker.github.io/blob/v17.06/opensource/doc-style.md

**Comment by sypets** [comment]
Broken link was removed with merging of PR #7663. Thanks.
