### ISSUE TITLE
No guidance for exporting / importing docker volumes

### ISSUE THREAD

**Issue by MFAshby** [docker/docker.github.io#7963]
### Problem description
There is no guidance on this page for exporting and importing docker volumes.

The 'docker export' command reference contains a link to a non-existent section on this page 'https://docs.docker.com/engine/tutorials/dockervolumes/#backup-restore-or-migrate-data-volumes', implying there used to be some documentation for this and it has been removed.

Moving a volume from one container host to another seems like it should be a straightforward task, as it is for containers with 'docker export' and 'docker import'.

- I couldn't find the information I wanted. I expected to find it near the following URL:
https://docs.docker.com/storage/volumes/

### Suggestions for a fix
- Document commands for importing and exporting volumes, if such commands exist. 
- Provide guidance on how to do the task if the commands don't exist.
- Fix the broken documentation link

**Comment by nigelpoulton** [comment]
I'll get a more authoritative answer, but I'm pretty sure no such functionality exists. Watch this space...
