### ISSUE TITLE
docker-machine installation command should be updated

### ISSUE THREAD

**Issue by drakulis** [docker/docker.github.io#7974]
File: [machine/install-machine.md](https://docs.docker.com/machine/install-machine/)

Install command for Linux is wrong. 

**Currently it is:**
```
$ base=https://github.com/docker/machine/releases/tag/v0.16.0 &&
  curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
  sudo install /tmp/docker-machine /usr/local/bin/docker-machine
```

**But is should be:**
```
$ base=https://github.com/docker/machine/releases/download/v0.16.0 &&
  curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
  sudo install /tmp/docker-machine /usr/local/bin/docker-machine
```

***download*** instead of ***tag***. I assume that command for MAC and Windows should also be updated.

**Comment by bermudezmt** [comment]
Hello @drakulis - sorry for the delayed response. The page has been updated to reflect `download` instead of `tag`. Thank you for bringing this to our attention.
