### ISSUE TITLE
This article is based on deprecated version

### ISSUE THREAD

**Issue by willam-gregoire** [docker/docker.github.io#7976]
File: [docker-for-azure/index.md](https://docs.docker.com/docker-for-azure/)

According to this article, this version is deprecated, therefore I recomend mentioning in the article, otherwise people loosing their time, since the new guidance is on the Docker Certified Infrastructure for Microsoft Azure documentation: 

https://hub.docker.com/editions/enterprise/docker-ee-azure

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this here for that reason. Feel free to continue the conversation after I close.
