### ISSUE TITLE
Clarification EC2 instances must be set to the private DNS hostname of the instance (will typically end in .internal)

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#7984]
File: [ee/ucp/kubernetes/configure-aws-storage.md](https://docs.docker.com/ee/ucp/kubernetes/configure-aws-storage/)

I dont understand this sentence
 "EC2 instances must be set to the private DNS hostname of the instance (will typically end in .internal)"

What must be set in the EC2 instances ?  A property ? What  property ?

**Comment by ddebroy** [comment]
It should say `hostname of the EC2 instances`

**Comment by david-yu** [comment]
@bermudezmt You can set the EC2 hostname using the following docs from AWS: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-hostname.html

**Comment by paigehargrave** [comment]
@martencassel - This looks like it's been fixed - PTAL at the current version of the file and see if additional updates are needed - thank you!
