### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by burtsevyg** [docker/docker.github.io#7993]
on page:
https://docs.docker.com/machine/install-machine/

base=https://github.com/docker/machine/releases/tag/v0.16.0

correct link:
base=https://github.com/docker/machine/releases/download/v0.16.0

**Comment by paigehargrave** [comment]
@burtsevyg Hi - very sorry for the delayed response on this - it looks like this has been fixed. We are going to go ahead and close this issue. Please submit another issue if you are still experiencing problems. Thank you!
