### ISSUE TITLE
Update to reflect latest versions

### ISSUE THREAD

**Issue by blackduck-joe** [docker/docker.github.io#7994]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

The matrix seems to stop at 2018.06, what about 09 and 12?

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the issue is old, a lot has changed. You can find the legacy information in https://docs.docker.com/compose/compose-file/compose-versioning/
