### ISSUE TITLE
can‘t open https://docs.docker.com/reference/run/’

### ISSUE THREAD

**Issue by lemongao** [docker/docker.github.io#7997]
### Problem location

- I saw a problem on the following URL: <https://docs.docker.com/reference/run/>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by thaJeztah** [comment]
that page moved to l https://docs.docker.com/engine/reference/run/ a long time ago; where did you find a link to the old location?

**Comment by L-Hudson** [comment]
Closing the ticket; not an issue with docs.
