### ISSUE TITLE
Type in docker Command

### ISSUE THREAD

**Issue by diveygupta** [docker/docker.github.io#8011]
File: [engine/userguide/networking/default_network/custom-docker0.md](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/)

"docker run --rm -it alpine /bin/ash" should be "docker run --rm -it alpine /bin/bash"

**Comment by nigelpoulton** [comment]
I don't see the command and typo in the docs page this ticket is raised against @diveygupta
