### ISSUE TITLE
Link no longer exist

### ISSUE THREAD

**Issue by rova05** [docker/docker.github.io#8015]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by 1c7** [comment]
> I saw a problem on the following URL:
where?
![image](https://user-images.githubusercontent.com/1804755/51362719-b8c6b380-1b0f-11e9-9a7f-20fe5944600a.png)

**Comment by L-Hudson** [comment]
no actionable info on the ticket.
