### ISSUE TITLE
Link to  help page in machine/concepts.md is broken

### ISSUE THREAD

**Issue by gctwnl** [docker/docker.github.io#8017]
### Problem description

The link to the help page at the end of the document is broken (404)

### Problem location

machine/concepts.md

**Comment by gctwnl** [comment]
Thanks. New to this stuff.

However, got a nice script now that facilitates easy running docker-machines on macOS, including having docker-machines that start when the Mac boots, but that is very OT.

**Comment by gctwnl** [comment]
I will. But I’ve thought of some improvements still that make it even easier to use so first finish that

G

**Comment by paigehargrave** [comment]
@gctwnl Hi! Just circling back to this - we thank you for your time and effort, and would love to publish your script if it's available!

**Comment by gctwnl** [comment]
My docker work is suspended until the machine I have been running this on is fixed (hardware problems possibly, GPU crashes.

The current version of the script is available on GitLab: 
https://gitlab.com/gctwnl/rnadockermachineonmacmanager

But I still want to make it somewhat easier to use. The fundamentals work, though.
