### ISSUE TITLE
Constraint Related Question

### ISSUE THREAD

**Issue by ghostplant** [docker/docker.github.io#802]
### Problem description

1) Does constraint support 'not equal to'? Such as:
  docker tcp://<manager_ip:manager_port>  run -d -P -e constraint:storage!=ssd --name db mysql
2) Does label set by 'dockerd --label aaa=bbb' take effect in swarm mode if it becomes a part of swarm node?
3) I want to join a node into an existing swarm cluster as manager role, and I don't want the swarm allocator to put any services on this node "BY DEFAULT". Is there any option supporting this requirement?
Currently if I run 'docker join' it and run 'docker node update .. --label-add node=forbidden', there is still a time gap to be allocated services. Besides, it is also inconvenient since every service to run have to add extra options like: 'docker service run .. --constraint node!=forbidden'

**Comment by joaofnfernandes** [comment]
@ghostplant This is the repository for Docker documentation. Feel free to open issues if you can't find the information you need in the documentation, but this is not the best place to ask questions.
Use [the forums](https://forums.docker.com/) or stackoverflow instead.

With a quick google search I was able to find that

1. You can use the [not equals operator for constraints](https://docs.docker.com/engine/reference/commandline/service_create/#/specify-service-constraints---constraint)
2. [Docker daemon labels are different than node labels](https://docs.docker.com/engine/userguide/labels-custom-metadata/)
3. You can [pause or drain a node](https://docs.docker.com/engine/swarm/swarm-tutorial/drain-node/), but I don't think you can join a node in paused or drained mode, so you will always have the time between a node joining and their availability changing.
