### ISSUE TITLE
Hope docker proxy setup daemon.json  and support socket4/5

### ISSUE THREAD

**Issue by 120011676** [docker/docker.github.io#8023]
Hope docker proxy setup daemon.json  and support socket4/5

希望docker 代理配置放入配置daemon.json文件，也支持下socket4、5

**Comment by 120011676** [comment]
Effective in time, no restart

及时生效，无重启

**Comment by 120011676** [comment]
More importantly, support for docker build command line proxy.
For example: docker --proxy https://username:password@www.proxy.com:8080 build

更重要的是支持docker build命令行代理
如：docker --proxy https://username:password@www.proxy.com:8080 build

**Comment by L-Hudson** [comment]
It's not clear to me that this is related to anything in the docs; looks like it's more about the product. Please clarify.

**Comment by L-Hudson** [comment]
closing for lack of response
