### ISSUE TITLE
Can we remove these sections and just have documentation on a per-version basis?

### ISSUE THREAD

**Issue by brianmartens** [docker/docker.github.io#8028]
It's very confusing when your documentation directs me outside of the version-specific docs to the additional sections as they are not likely to be the same version I'm working in (e.g. V3). The file below is a good example. Is it possible to reorganize the docs site so that each version has it's own set of subsections instead of just one gigantic page per version? The fact that many things break between one version and the next makes this all the more important to have.
File: [compose/startup-order.md](https://docs.docker.com/compose/startup-order/)

**Comment by L-Hudson** [comment]
Thanks for the comment; we have a refactor in progress, and that should solve a lot of problems.
