### ISSUE TITLE
Feedback for: swarm/scheduler/strategy.md

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#803]
File: [swarm/scheduler/strategy.md](https://docs.docker.com/swarm/scheduler/strategy/)

This page refers to `swarm manage` and there is no `docker swarm manage` commands in Engine 1.12.  `docker swarm update` also does not have any scheduling strategy configuration listed in the help commands.

**Comment by mstanleyjones** [comment]
This topic is about legacy standalone swarm, not swarm mode.
