### ISSUE TITLE
Re-frame the "secure out of the box" phrase regarding swarm overlay networking

### ISSUE THREAD

**Issue by terryburton** [docker/docker.github.io#8038]
File: [engine/userguide/networking/overlay-security-model.md](https://docs.docker.com/engine/userguide/networking/overlay-security-model/)

"Docker swarm mode overlay network security model: **Overlay networking for Docker Engine swarm mode comes secure out of the box** ... // You can also encrypt data exchanged between containers on different nodes on the overlay network."

I would like to see this often-repeated (and summarised) phrase "secure out of the box" re-framed so that it is completely clear that it only applies to the activity of swarm nodes exchanging control plane information (use of the secure Gossip protocol) rather than to the general swarm overlay network's data plane, for which encryption must be enabled explicitly.

For example, it is more correct and informative to say "The control plane coordinating overlay networking for Docker Engine swarm mode comes secure out of the box."

It would be better to not have any bold statements from the official documentation that could be read/spoken in isolation (i.e. without wider context) that unintentionally mislead those who read/hear them, especially for security-related matters.

**Comment by nigelpoulton** [comment]
I agree @terryburton 

I'm currently going through tickets on Engine docs and will get this updated accordingly.

Appreciate you pointing this out.

**Comment by nigelpoulton** [comment]
@terryburton Looks like updates have been made to the docs since you raised this ticket. I don't see any reference to "secure out of the box" any more. Seems like your comment was heard and acted upon, but this ticket never got updated.

**Propose the ticket be closed**

**Comment by terryburton** [comment]
It's a lot better now.

But perhaps:

> This network sits on top of (overlays) the host-specific networks, allowing containers connected to it (including swarm service containers) to communicate securely.

Should be:

> This network sits on top of (overlays) the host-specific networks, allowing containers connected to it (including swarm service containers) to communicate securely _when encryption is enabled._

Emphasis for this conversation rather than for the page.

**Comment by nigelpoulton** [comment]
Magic. I'll look at getting it sorted 👍
