### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by icfly2** [docker/docker.github.io#8054]
File: [machine/examples/ocean.md](https://docs.docker.com/machine/examples/ocean/)

I may be daft but after the excellent guide on how to get a remote machine via the CLI with docker-machine

and the examples on docker-compose, it is unclear on how to progress from running hello world examples to running your own container, just created with docker-compose.

**Comment by L-Hudson** [comment]
@icfly2, is there a specific correction you want made? I'm not entirely understanding your ask. Please clarify.

**Comment by icfly2** [comment]
Hi, the issue is that the two parts of the docs: https://docs.docker.com/get-started/
and the part on machine are not linked, so it is hard to understand how to launch a container on a machine just created in the getting started guide. Either a cross reference, like:
 - now you have a machine in the cloud, put your own images on it (here is how you create them)
- now you have your own image, this is how you launch them on your own machine on Digital Ocean

Essentially both the launching a docker image from the register on the server is well explained and easy, the creation of the own images is well explained two, but linking the two is hard and requires a lot of searching due to it not being clear which bits do what (compose, image ...)

**Comment by paigehargrave** [comment]
@icfly2 Hi - Thank you for your feedback on this! I've added a couple links for this - PTAL and see if this is sufficient - thank you!

**Comment by bermudezmt** [comment]
Closed via #8356 .
