### ISSUE TITLE
Typo in Interlock Extentions

### ISSUE THREAD

**Issue by doanbutar** [docker/docker.github.io#8055]
In page [service cluster](https://docs.docker.com/ee/ucp/interlock/usage/service-clusters/#configure-proxy-services)

There was a typo on the section 
`[Extensions.us-west] `
`ProxyImage = "nginx:alpine"`

It should be 
`[Extensions.us-west] `
` ProxyImage = "docker/ucp-interlock-proxy:3.1.2"`

Dani confirmed here : https://docker.slack.com/archives/C0JS68GRL/p1546826937023300

**Comment by L-Hudson** [comment]
looks like a C&P error. Corrected. Thanks!
