### ISSUE TITLE
Typo in upstream file

### ISSUE THREAD

**Issue by tescherm** [docker/docker.github.io#807]
Noticed a small typo, should:

> Using an authorization plugin, a Docker administrator can configure granular access policies for managing access to Docker daemon

read: 

> Using an authorization plugin, a Docker administrator can configure granular access policies for managing access to **the** Docker daemon

File: [engine/extend/plugins_authorization.md](https://docs.docker.com/engine/extend/plugins_authorization/)

**Comment by mstanleyjones** [comment]
Closed in favor of https://github.com/docker/cli/pull/226.
