### ISSUE TITLE
404s on howto page(s)

### ISSUE THREAD

**Issue by rhizome** [docker/docker.github.io#8070]
### Problem description
All links 404

### Problem location
https://docs.docker.com/install/linux/docker-ce/debian/
- I saw a problem on the following URL: https://docs.docker.com/install/linux/docker-ce/debian/

### Suggestions for a fix

use acceptance testing

**Comment by L-Hudson** [comment]
Not finding any broken links on the page.

**Comment by rhizome** [comment]
This appears to have been caused by having javascript turned off, which apparently removes the link-to-anchor functionality of the links down the right-hand column.
