### ISSUE TITLE
Support `prefers-color-scheme` and remove light/dark mode toggle if it is set.

### ISSUE THREAD

**Issue by jtkiley** [docker/docker.github.io#8082]
The docs website has a toggle for light and dark modes (and each version looks nice).
However, if a user has chosen a light or dark mode at the system level (i.e. `prefers-color-scheme` has a value of `light` or `dark`), it may be nicer to simply respect that and not display the toggle.

I think doing so silently would be fine (and the best alternative), but there are a couple of middle ground approaches:

1. Indicate that the system setting is being relied upon. Instead of the toggle, have text saying something like `System color scheme: dark`. This site is early on the dark mode theme selection trend, but it seems plausible that this would eventually be removed as users become accustomed to pages adapting to the system scheme.
1. Same as above, except provide the ability to reveal the toggle, and then provide an indication that the system setting is being overridden (if it is). That may run afoul of the issue [mentioned here](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme). It also creates an ambiguity of intent in the case that the system setting and the per-site setting match and then the user changes the system setting. Should the prior per-site setting be respected or the subsequent system change?

**Comment by L-Hudson** [comment]
This is an excellent point; thanks @jtkiley. The Docs team doesn't have any control whatsoever over the display of the docs. @peter-docker, any idea who should take a look at this?

**Comment by L-Hudson** [comment]
I've opened this up as a new issue over here: https://github.com/docker/success-center/issues/344. Closing this ticket.
