### ISSUE TITLE
Dd.aagkllaaccgyyyyyuuuuooozzzzxxaa

### ISSUE THREAD

**Issue by adsmf70** [docker/docker.github.io#8085]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by L-Hudson** [comment]
My keyboard does that very thing when my ferrets leap across it. Closing ticket, as I'm pretty sure Docker for Ferrets isn't launched yet.
