### ISSUE TITLE
Improve UX and documentation for pull mirroring page

### ISSUE THREAD

**Issue by bermudezmt** [docker/docker.github.io#8088]
### Problem description
More details can be found here: https://github.com/docker/dhe-deploy/issues/9787

- I saw a problem on the following URL: https://docs.docker.com/ee/dtr/user/promotion-policies/pull-mirror/
- Save vs Save & Apply needs to be documented. Button labels might be changed in the future to avoid confusion.

### Project version(s) affected

DTR 2.6.x

**Comment by JustinINevill** [comment]
Scope of this issue to just correct current buttons.
