### ISSUE TITLE
Update Install Doc to Include Linux Mint specific repository addition

### ISSUE THREAD

**Issue by cglaeser** [docker/docker.github.io#8109]
File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

Hi,
if you included the step mentioned in the answer on:
https://stackoverflow.com/questions/52545945/docker-install-on-linux-mint-19-tara

that would greatly benefit users of Linux Mint who wish to install Docker CE.

Thanks in advance!

**Comment by ahh-docker** [comment]
Thanks for your contribution. We are resolving this in https://github.com/docker/docker.github.io/pull/8102.
