### ISSUE TITLE
Link to download Toolbox

### ISSUE THREAD

**Issue by rapha-opensource** [docker/docker.github.io#811]
File: [toolbox/toolbox_install_mac.md](https://docs.docker.com/toolbox/toolbox_install_mac/)

there's no link to download toolbox in this page.

**Comment by scjane** [comment]
#dibs

**Comment by scjane** [comment]
A link for downloading Toolbox is provided now. This issue can be closed.

![123](https://cloud.githubusercontent.com/assets/25146885/25110993/bf36db5c-241a-11e7-87e9-089ee273eb24.jpg)
