### ISSUE TITLE
Sorry, we can't find that page

### ISSUE THREAD

**Issue by yyyyy210** [docker/docker.github.io#8127]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/userguide/level1/

- I couldn't find the information I wanted. I expected to find it near the following URL:https://docs.docker.com/userguide/level1/

**Comment by L-Hudson** [comment]
Hi @yyyyy210! I need to know what page you found this link on so I can correct. Thank you!

**Comment by bermudezmt** [comment]
@yyyyy210 since no additional information came through, I am closing this issue. Please submit another issue if you notice anything else on the site.
