### ISSUE TITLE
Port mapping forgotten

### ISSUE THREAD

**Issue by acraw1** [docker/docker.github.io#8129]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

In part-3 we configured a port mapping from 4000:80 within docker-compose.yaml, but in part-4 we're being instructed to test the swarm using port 80, which does not work.  It took me a few minutes to realize that we should actually be testing against port 4000 on the swarm nodes, not port 80 as instructed.  The documentation for part-4 should be updated to avoid this confusion & make it more clear.

**Comment by DawnWood-Docker** [comment]
Hi @acraw1 Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
