### ISSUE TITLE
[DDC] Guide users after deployment

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#813]
For the previous versions of UCP we had sample tasks that users could do after they deployed Docker Datacenter.
This was useful to guide new users through a couple of features and hand hold them until they know their way around.

Maybe we can leverage what we currently have on the UI dashboard page.

**Comment by johndmulhausen** [comment]
In light of Hosted Trial and Play With Docker we're closing per triage discussion.
