### ISSUE TITLE
Documentation is not clear

### ISSUE THREAD

**Issue by manojadepu3** [docker/docker.github.io#8133]
File: [docker-hub/index.md](https://docs.docker.com/docker-hub/)

unable to run below steps in windows.

One we create my-first-rep in Docker Hub.. what steps do we need to in windows m/c..
i already did docker login..

I have able to run 
docker build - < Dockerfile
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM busybox
 ---> 3a093384ac30
Step 2/2 : CMD echo "Hello world! This is my first Docker image."
 ---> Using cache
 ---> 046e827e09b3
Successfully built 046e827e09b3
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

But unable to ran below command and unable to push..
Run docker build -t <your_username>/my-first-repo . to build your Docker image
Test your docker image locally by running docker run <your_username>/my-first-repo
Run docker push <your_username>/my-first-repo to push your Docker image to Docker Hub

**Comment by L-Hudson** [comment]
This seems to be more of a technical issue than a specific issue with the documentation. Please check out the forums, or tech support. Thanks!
