### ISSUE TITLE
no daemon configuration for macOS?

### ISSUE THREAD

**Issue by hmijail** [docker/docker.github.io#8136]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

There is no mention of macOS here, only Linux and Windows. 
The preferences in Docker for Mac says I can type in a docker json configuration, but the "host" option is not recognized and "hosts" says can not be used in Desktop.

So... some mention of what is supported or plans or whatever would be good.

**Comment by paigehargrave** [comment]
@hmijail Hi - thank you for bringing this to our attention! After one technical review, we believe that this is not valid for Mac, but will verify.

**Comment by paigehargrave** [comment]
@andrewhsu Hi Andrew - can someone on your team verify this? Thank you in advance for any help!

**Comment by paigehargrave** [comment]
@andrewhsu Hi Andrew - can someone on your team verify this? Thank you in advance for any help!

**Comment by bermudezmt** [comment]
Hey @andrewhsu - can you please address?

**Comment by craig-osterhout** [comment]
Closing this as stale. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline to get better visibility.
