### ISSUE TITLE
Please remove Docker for IBM Cloud docs info

### ISSUE THREAD

**Issue by sealbou** [docker/docker.github.io#8139]
File: [docker-for-ibm-cloud/quickstart.md](https://docs.docker.com/docker-for-ibm-cloud/quickstart/)

This product was sunset last year yet we still have people pinging about it so please remove from the documentation to indicate it's no longer available. 

https://docs.docker.com/v17.12/docker-for-ibm-cloud/quickstart/#step-1-get-all-your-accounts-in-order

**Comment by bermudezmt** [comment]
@sealbou while I'm not entirely happy with our bare minimum new landing page now for this EOL'd product, v17.12 now redirects to https://docs.docker.com/docker-for-ibm-cloud/. We will take this into account during our content refactor.

**Comment by bermudezmt** [comment]
Needs to be redirected for all supported versions: 18.03, 17.12, 17.09, 17.06.

**Comment by bermudezmt** [comment]
@shampabh  I added this issue to Redirects / 404s row of the CCS requirements doc.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The topics appear to longer exist in the current documentation. Closing the issue. If the issue still persists, please let us know.
