### ISSUE TITLE
Issue in Docker Setup is Azure or AWS

### ISSUE THREAD

**Issue by snytech14** [docker/docker.github.io#8150]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

<!-- If you have details about the steps to perform to get docker setup done on Azure, let us know--!>

**Comment by L-Hudson** [comment]
closing due to no information in the ticket. Feel free to reopen with data update, thanks!
