### ISSUE TITLE
Input/output error after building image while trying to start

### ISSUE THREAD

**Issue by panagiotismavridis** [docker/docker.github.io#8151]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)
On Windows 10, while in the powershell while finishing most of the STEPS, just before running one can get something similar to:

Error response from daemon: driver failed programming external connectivity on endpoint compassionate_shockley (4354ce12687e6a9558c53934037f55f3720f136586b5b3ba1241dece190d21c6): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:4000:tcp:172.17.0.2:80: input/output error.

**FIX: If you restart Docker client it runs it with no issues.**
I would suggest in the docs they include a note, that restart is needed. It is a getting started guide, while in part 2 is could be frustrating to start getting these kind of errors 👍

**Comment by paigehargrave** [comment]
@panagiotismavridis - I've added a blurb for restarting - PTAL and make sure that it's in the right location. Thank you for bringing this to our attention!

**Comment by bermudezmt** [comment]
Closing as per #8358 . Please submit another issue if you're still experiencing problems with this guide.
