### ISSUE TITLE
Expanded 3rd-party monitoring documentation

### ISSUE THREAD

**Issue by stevenfollis** [docker/docker.github.io#8157]
### Problem description

Currently we [document](https://docs.docker.com/config/thirdparty/prometheus/) integration of Prometheus with Docker Enterprise. Does it make sense to add page(s) for other common monitoring integration points such as [SysDig](https://sysdig.com/), [DataDog](https://www.datadoghq.com/), etc.?

**Comment by L-Hudson** [comment]
@ahh-docker, thoughts? Seems like a refactor task.

**Comment by stevenfollis** [comment]
Just realized that we have this content over in the Success Center:

https://success.docker.com/article/sysdig-monitoring
https://success.docker.com/article/datadog-monitoring

So perhaps a hyperlink from docs over to 3rd party options in Success Center would be a better path?

**Comment by aki-k** [comment]
@stevenfollis The URLs redirect to 

https://goto.docker.com/Q118-Docker-Certified-Infrastructure-Download_LP.html

What happened to them?

**Comment by paigehargrave** [comment]
@stevenfollis @aki-k  I'd be happy to add these two links to this from the docs, but I'm getting prompted to log in - that seems ugly when someone is looking for help. I've inquired about these links.

**Comment by bermudezmt** [comment]
Follow-up: https://docker.slack.com/archives/C02FVEK5M/p1550595912021900
