### ISSUE TITLE
UCP 3.0 documents how to use HRM

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#8180]
### Problem description

https://docs.docker.com/datacenter/ucp/3.0/guides/user/services/use-domain-names-to-access-services/

^ documents HRM, which is not available in UCP 3.0.  UCP 3.0 shipped with interlock which uses different network names and service labels and web ui and bits.

### Suggested solution

Backport interlock docs to UCP 3.0, removing notes on any features not available in UCP 3.0 Interlock.  I'm not aware of any, but it's worth noting that it's a backport.

**Comment by trapier** [comment]
As suspected on #8192, something is amiss here:

```
docker.github.io]$ git grep -ic kubernetes datacenter/ucp/3.0/
datacenter/ucp/3.0/guides/admin/install/install-on-azure.md:15
datacenter/ucp/3.0/reference/api/main.js:1
datacenter/ucp/3.0/reference/cli/install.md:3
datacenter/ucp/3.0/reference/cli/upgrade.md:3
docker.github.io]$ 
```

**Comment by bermudezmt** [comment]
@trapier we are looking into this.

**Comment by JustinINevill** [comment]
@bermudezmt to:
1. Remove HRM from 3.0
2. Backport interlocks docs to 3.0
