### ISSUE TITLE
Bad "Edit this page" link for the 'Docker run reference' documentation page

### ISSUE THREAD

**Issue by ghost** [docker/docker.github.io#8183]
The [Edit this page](https://github.com/docker/docker.github.io/edit/master/engine/reference/run.md) link on this page [Docker run reference](https://docs.docker.com/engine/reference/run/) is not rendering. You get a HTTP 404.

I"m trying to edit the Docker run reference doc.

**Comment by paigehargrave** [comment]
The link after this is broken as well. Third link works.

This is the third link in that section - works: <a href="https://github.com/docker/docker.github.io/edit/master/engine/reference/commandline/docker.md"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit this page</a>

This is the second link - broken b/c cli.md does not exist: <a href="https://github.com/docker/docker.github.io/edit/master/engine/reference/commandline/cli.md"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit this page</a>

This is the first link - broken - path appears to be incorrect: <a href="https://github.com/docker/docker.github.io/edit/master/engine/reference/run.md"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit this page</a>

**Comment by PatMyron** [comment]
related to https://github.com/docker/docker.github.io/issues/6102 ?

**Comment by rcjsuen** [comment]
How can we help move this issue forward? It seems like we need a way to provide a custom `edit_path` instead of blindly appending `page.path` to `https://github.com/docker/docker.github.io/edit/master/`?

https://github.com/docker/docker.github.io/blob/bbee70403d2974530eedf8f9b03f8235a63d281c/_layouts/docs.html#L18-L19

**Comment by craig-osterhout** [comment]
The "Edit this page" link now redirects to the GitHub repo.
