### ISSUE TITLE
Banner only displaying on landing pages for certain archived versions

### ISSUE THREAD

**Issue by bermudezmt** [docker/docker.github.io#8184]
### Problem description

See: 

- https://docs.docker.com/v18.03/ee/
- https://docs.docker.com/v17.12/reference/
Suggestions for a fix:

This archived version displays the banner consistently: https://docs.docker.com/v1.13/samples/

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. It appears this is no longer applicable to the current docs. As this issue is old, the context may have changed. If the issue still persists, please let us know.
