### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by cowlinator** [docker/docker.github.io#8201]
File: [install/windows/docker-ee.md](https://docs.docker.com/install/windows/docker-ee/)

On https://docs.docker.com/install/windows/docker-ee , 
the "What to know before you install" link is broken.  It appears to refer to a fragment that does not exist.
Also, the " 32 GB minimum recommendation for Windows" link is broken.  (Returns HTTP code 404)

**Comment by bermudezmt** [comment]
Thanks for reporting the issue, @cowlinator . This has been fixed by @themousepotato . :)

**Comment by cowlinator** [comment]
@bermudezmt , so, to be clear, this issue lists 2 broken links.

#8204 does indeed fix the "32 GB minimum recommendation for Windows" link.

However, there does not appear to be a fix for the "What to know before you install" link.

**Comment by bermudezmt** [comment]
Hey @cowlinator , can you please review https://github.com/docker/docker.github.io/pull/8221 and see if that addresses the other broken link issue? Thank you.

**Comment by cowlinator** [comment]
Yes, deleting the link does make it non-broken.

**Comment by bermudezmt** [comment]
Hi @cowlinator - I apologize for any confusion. This topic has undergone a rewrite from one of our engineers, so there were multiple non-trivial changes. Please let me know if you think we have removed something that should not have been removed.
