### ISSUE TITLE
ip-util-check does not account for the ip-range parameter

### ISSUE THREAD

**Issue by kapiteined** [docker/docker.github.io#8208]
File: [ee/upgrade.md](https://docs.docker.com/ee/upgrade/)

Hi, the ip-util-check does not account for the ip-range parameter for the subnets it checks.
If you create a /24 subnet  with --ip-range=w.x.y.z/27, the ip-util-check shows more free addresses 
then there are available in the range.

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
