### ISSUE TITLE
In tutorial (Drain a node on the swarm) the link to next tutorial is outdated

### ISSUE THREAD

**Issue by thacoon** [docker/docker.github.io#8210]
File: [engine/swarm/swarm-tutorial/drain-node.md](https://docs.docker.com/engine/swarm/swarm-tutorial/drain-node/)

The link in [this  tutorial](https://docs.docker.com/engine/swarm/swarm-tutorial/drain-node/) to the next tutorial is not valid. The next tutorial is linked with the following link: [https://docs.docker.com/engine/swarm/ingress.md](https://docs.docker.com/engine/swarm/ingress.md) which results in 404.

**Comment by bermudezmt** [comment]
@thacoon this should be a valid link when accessing the webpage: https://docs.docker.com/engine/swarm/swarm-tutorial/drain-node/ - Please feel free to file another issue if you are still seeing a problem on your end.
