### ISSUE TITLE
Bad link on page 

### ISSUE THREAD

**Issue by bneil** [docker/docker.github.io#8214]
File: [ee/ucp/authorization/group-resources.md](https://docs.docker.com/ee/ucp/authorization/group-resources/) See the "Learn more about Kubernetes namespaces." - the link goes to a 404 here https://v1-8.docs.kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

**Comment by bermudezmt** [comment]
@bneil Thanks for reporting the issue. This should be addressed by https://github.com/docker/docker.github.io/pull/8168/commits/8065e72bfe14bd8ecefbcf36b258c24ec3cd3970, which we are hoping to merge soon.
