### ISSUE TITLE
Can't find the page for Docker v1.12

### ISSUE THREAD

**Issue by SueGraham** [docker/docker.github.io#8234]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/v1.12/

- Other: I get this message: "Sorry, we can't find that page"

### Project version(s) affected

https://docs.docker.com/v1.12/

**Comment by bermudezmt** [comment]
Hello @SueGraham , we have removed unsupported documentation versions from `docs.docker.com` but you should still be able to access the documentation. Please see https://github.com/docker/docker.github.io#accessing-unsupported-archived-documentation for details on how. Let us know if you have any more questions.

**Comment by SueGraham** [comment]
Thanks :)
