### ISSUE TITLE
Feedback for: docker-cloud/getting-started/deploy-app/4_push_to_cloud_registry.md

### ISSUE THREAD

**Issue by kirill-chilingarashvili** [docker/docker.github.io#824]
File: [docker-cloud/getting-started/deploy-app/4_push_to_cloud_registry.md](https://docs.docker.com/docker-cloud/getting-started/deploy-app/4_push_to_cloud_registry/)

In the end the doc says:

> $ docker-cloud repository ls
> NAME                                    DESCRIPTION
> my-username/quickstart-python
> my-username/quickstart-go

But according to this issue: https://github.com/docker/dockercloud-cli/issues/23
and according to how the command responds using current version, you will not be able to see any repositories hosted on Docker Hub, 
I think this should be clarified in the last section

**Comment by sanscontext** [comment]
Hey @kirill-chilingarashvili thanks for the catch. I checked with the team, and I'm unclear how this got into the doc because it looks like it may never have worked. 🤔 

If you can hold tight for a bit I'll update this with a different verification step.
