### ISSUE TITLE
Incorrect netmask for ipv6

### ISSUE THREAD

**Issue by mvhconsult** [docker/docker.github.io#825]
File: [engine/userguide/networking/default_network/ipv6.md](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)
This line is below one of the earlier examples:
"In this setup the subnet 2001:db8:23:42::/80 with a range from 2001:db8:23:42:0:0:0:0 to 2001:db8:23:42:0:ffff:ffff:ffff is attached to eth0, with the host listening at ..."

Shouldn't it be a ::/64 network that was attached to the eth0? As per the Figure?

**Comment by shubheksha** [comment]
I'll take this one up!

**Comment by JimGalasyn** [comment]
@shubheksha , how's your progress on this? We'll need to return this to the unclaimed pool for the hackathon by tomorrow, if we don't see movement on this. Thanks!

**Comment by shubheksha** [comment]
This completely fell off my radar though I remember commenting to asking for clarification!
I'm a little confused about which value needs to be changed here. I tried reading the description multiple times but just got more confused. Would really appreciate some help!

**Comment by JimGalasyn** [comment]
Okay, I'll ping the engineers to see if we can get some clarity.

**Comment by aboch** [comment]
Yes, the previous sentence
```
Often servers or virtual machines get a `/64` IPv6 subnet assigned (e.g.`2001:db8:23:42::/64`). In this case you can split it up further and provide Docker a `/80` subnet while using a separate `/80` subnet for other applications on the host:
```
seems in fact to imply the writer wanted to show the use case of further subnet split inside the host.

So, IMO, not only the following text whould use `/64` for `eth0`, like the submitter requested, but also the picture should be changed, the host `eth0` address should be `2001:db8:23:42::1/64`

**Comment by shubheksha** [comment]
@aboch, @JimGalasyn - can you please confirm if this is correct or I need to make other changes?
<img width="569" src="https://cloud.githubusercontent.com/assets/7693422/25243017/3b80c47a-2619-11e7-8bae-f77c713f3486.png">

**Comment by aboch** [comment]
@shubheksha The containers' `eth0` address and mask should be `/80` as before.
Only the `host1` `eth0` mask needed to change to `/64`

**Comment by shubheksha** [comment]
Alright, updated the image and pushed the changes, PTAL :)
