### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#8251]
File: [ee/ucp/admin/install/upgrade.md](https://docs.docker.com/ee/ucp/admin/install/upgrade/)

There is no information regarding upgrade paths, this is historically inconsistent with UCP upgrade docs and is important information to share with customers.  Please refer to :
https://docs.docker.com/v17.09/datacenter/ucp/2.2/guides/admin/install/upgrade/#recommended-upgrade-paths

**Comment by paigehargrave** [comment]
@ry4nz - Hi Ryan, perhaps there is some history on this that I'm unaware of. The previous upgrade path info is:
If you're running a UCP version that's lower than 2.1, first upgrade to the latest 2.1 version, then upgrade to 2.2. Use these rules for your upgrade path to UCP 2.2:

From UCP 1.1: UCP 1.1 -> UCP 2.1 -> UCP 2.2
From UCP 2.0: UCP 2.0 -> UCP 2.1 -> UCP 2.2
From UCP 2.1: UCP 2.1 -> UCP 2.2

Does this still apply to UCP 3.1, and if not, what is the upgrade path? Thank you in advance!

**Comment by ry4nz** [comment]
For UCP 3.1, upgradable from 3.0
For UCP 3.0, upgradable from 2.2
For UCP 2.2: upgradable from 2.1

**Comment by bermudezmt** [comment]
Closed via #8400
