### ISSUE TITLE
typo on 'docker stats' page

### ISSUE THREAD

**Issue by vocatan** [docker/docker.github.io#8272]
File: [engine/reference/commandline/stats.md](https://docs.docker.com/engine/reference/commandline/stats/)

Notation at bottom of page has typo:

"Note: On Docker 17.09 and older, the {{.Container}} column was used, **in stead** of {{.ID}}\t{{.Name}}."

should be

Note: On Docker 17.09 and older, the {{.Container}} column was used, **instead** of {{.ID}}\t{{.Name}}.

**Comment by paigehargrave** [comment]
@L-Hudson Hi Laureen - Let me know if you want me to do a PR for this or whether you would prefer to handle it - I'm fine either way. :)

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The issue appears no longer be in the topic. Closing the issue. If the issue still persists, please let us know.
