### ISSUE TITLE
Latest version not showing

### ISSUE THREAD

**Issue by smarts** [docker/docker.github.io#8275]
File: [docker-for-windows/release-notes.md](https://github.com/docker/docker.github.io/blob/69b11698a6a4f12296aee1c728609d2189fae4cb/docker-for-windows/release-notes.md)

The file has the most current version but the page doesn't show it. I assume this is a caching problem
![image](https://user-images.githubusercontent.com/1002257/52880852-f707c080-3117-11e9-9abd-87256f22cb14.png)
^Not the latest version
From browser:
![image](https://user-images.githubusercontent.com/1002257/52880909-1a327000-3118-11e9-8c87-9a042a16eec5.png)

**Comment by bermudezmt** [comment]
@smarts this will be live shortly. Thank you for reporting the issue!
