### ISSUE TITLE
Can't find instructions for installation on Linux

### ISSUE THREAD

**Issue by simchuck** [docker/docker.github.io#8276]
### Problem description

I am looking for installation instructions on OpenSUSE.  Following the link led me to a 404.  

### Problem location

- Other: 
Link from https://blog.docker.com/2013/11/docker-0-7-docker-now-runs-on-any-linux-distribution/

"On Linux systems, first install the [Docker] for your OS as described on the Get Docker page, then come back here for instructions on installing Compose on Linux systems."

leads me to ...
https://docs.docker.com/install/index.md#server

**Comment by paigehargrave** [comment]
@simchuck For current images by the openSUSE Project, see opensuse/leap and opensuse/tumbleweed   images provided and maintained by the openSUSE Project release team at https://www.opensuse.org/. Thank you!

**Comment by hestellez** [comment]
@simchuck have you tried some of these https://en.opensuse.org/SDB:Docker ?

**Comment by craig-osterhout** [comment]
The blog is no longer available. You can access the Get Docker page at https://docs.docker.com/get-docker/
