### ISSUE TITLE
Bormon007

### ISSUE THREAD

**Issue by Bormon007** [docker/docker.github.io#8284]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by Bormon007** [comment]
Newlifedocker2019

**Comment by paigehargrave** [comment]
@Bormon007 - Hi, this issue does not contain enough information for us to take action, so we are going to close it. Please submit a new issue with additional details if you are experiencing a problem with the documentation. Thank you!
