### ISSUE TITLE
Feedback for: engine/installation/mac.md

### ISSUE THREAD

**Issue by kenergy** [docker/docker.github.io#83]
URL: engine/installation/mac.md

is there a setup script to deploy Docker for Mac? It would be nice to have a script that Docker is completely setup once it's in the /Applications folder. The goal is to use a application delivery system and have Docker be completely installed.

**Comment by mstanleyjones** [comment]
Hi there. Unfortunately, I don't think this is a documentation issue. It sounds like a feature request on the Docker for Mac installer. Please file this feature request at https://github.com/docker/for-mac/issues. In the future, you can reach this link by opening Docker on your Mac and going to **Diagnose and Feedback**. We really appreciate the suggestion.
