### ISSUE TITLE
Missing information in docker for mac install process

### ISSUE THREAD

**Issue by terribleplan** [docker/docker.github.io#8301]
### Problem description

The documentation for installing docker for mac is great, but it seems that there is no link to actually download the thing. The link on the page just takes me to some weird page asking for a username and password I don't have.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/docker-for-mac/install/

### Suggestions for a fix

Figure out where the file is hosted and fix the broken link.

**Comment by sujaypillai** [comment]
You need to login to Docker Hub for downloading Docker Desktop for Mac. Your Docker Hub account would be required for you to upload/share docker images, to download other certified images and plugins. So the link above referred by you is taking you to proper page.

**Comment by terribleplan** [comment]
What? That makes no sense. I am just trying to download docker, not do anything that would require logging in. Is this related to the whole docker/moby split thing? Do I need to download moby for mac now or something? Where can I download the open source version?

**Comment by aevesdocker** [comment]
Closing issue as this has been fixed
