### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#8308]
File: [ee/ucp/kubernetes/layer-7-routing.md](https://docs.docker.com/ee/ucp/kubernetes/layer-7-routing/)

https://v1-8.docs.kubernetes.io/docs/concepts/services-networking/ingress/ 

link throws err `NET::ERR_CERT_COMMON_NAME_INVALID`

should be replaced with:

https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by paigehargrave** [comment]
@kavikat - Hi - we've done some major restructuring to this page based on engineering feedback.

#8375

**Comment by bermudezmt** [comment]
#8375 has been merged and the link should be updated.
