### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by spectrumcomputing** [docker/docker.github.io#8312]
File: [_samples/library/alpine/index.md](https://docs.docker.com/samples/library/alpine/)

The following link from the above page does not seem to be working:

This image is well documented. Check out the documentation at Viewdocs.

http://gliderlabs.viewdocs.io/docker-alpine

Just gives:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html><head>
    <title>503 Backend unavailable, connection timeout</title>
  </head>
  <body>
    <h1>Error 503 Backend unavailable, connection timeout</h1>
    <p>Backend unavailable, connection timeout</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-bwi5121-BWI 1550613579 2210964732</p>
    <hr/>
    <p>Varnish cache server</p>
  

</body></html>

**Comment by paigehargrave** [comment]
@spectrumcomputing - Hi - I've tried this link in both FF and Chrome and it's working for me. Can you clear your browser cache and try the link again? Thank you in advance!

**Comment by spectrumcomputing** [comment]
Hi, thanks for coming back to me so quickly.  It must have been a temporary issue with the server as I'm all up again.  Thanks again.

**Comment by paigehargrave** [comment]
@spectrumcomputing You are very welcome - glad everything is OK now! Please let us know if you experience any additional issues - we value your feedback!
