### ISSUE TITLE
UCP install docs broken link to HA doc

### ISSUE THREAD

**Issue by cflee** [docker/docker.github.io#8316]
### Problem description

The link "Learn about high availability" on the page indicated below is a broken link.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ee/ucp/admin/install/plan-installation/

### Project version(s) affected

N/A, this broken link is in the current docs on the website.

### Suggestions for a fix

I think it should be going to https://docs.docker.com/ee/ucp/admin/configure/join-nodes/, as that's where it was moved to in https://github.com/docker/docker.github.io/commit/9d0682e8db16002c76d12bc41887f2d8a241e8f0#diff-66529bbb2c1e41afa72b363f504f0de4

**Comment by bermudezmt** [comment]
@cflee this has been addressed via #8324 .
