### ISSUE TITLE
Docs for docker version 1.7 are 404

### ISSUE THREAD

**Issue by flaviut** [docker/docker.github.io#8319]
### Problem description

When I navigate to https://docs.docker.com/v1.7/, I get a 404. This page used to contain the docs for version 1.7.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/v1.7/

### Suggestions for a fix

Restore the content at https://docs.docker.com/v1.7/

**Comment by bermudezmt** [comment]
We have removed unsupported documentation versions from docs.docker.com but you should still be able to access the documentation. Please see https://github.com/docker/docker.github.io#accessing-unsupported-archived-documentation for details on how. Let us know if you have any more questions.
