### ISSUE TITLE
Collect Docker metrics with Prometheus  documentation example is wrong

### ISSUE THREAD

**Issue by gforghetti** [docker/docker.github.io#8325]
File: [config/thirdparty/prometheus.md](https://docs.docker.com/config/thirdparty/prometheus/)

This example will never work if the prometheus collector container is started as a docker service.
The **prometheus.yml** file specifies the docker job target endpoint as **- targets: ['localhost:9323']**. **localhost** is not reachable by the prometheus collector container.
In order for a container started by a **docker service command** command to reach the docker metrics endpoint running on the docker node requires **--network host** which is not supported by a Docker service.  The prometheus collector container needs to be started with a `docker container run` command.

Example:

```
docker container run \
--detach \
--name my-prometheus \
--network host \
--mount type=bind,source=$(pwd)/prometheus.yml,destination=/etc/prometheus/prometheus.yml \
prom/prometheus:latest
```

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
