### ISSUE TITLE
Docker builder documentation not found

### ISSUE THREAD

**Issue by nassimBouazabia** [docker/docker.github.io#8336]
### Problem description

Docker builder documentation redirect to not found page

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/commandline/docker/

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/engine/reference/commandline/builder/

### Project version(s) affected

No specific version

### Suggestions for a fix

Command doesn't exist anuymore, just delete link

**Comment by moreal** [comment]
In my command line, there was the command like `docker builder`
is the element, `docker builder` right element?

**Comment by paigehargrave** [comment]
@bermudezmt - I'm wondering if we should link to https://docs.docker.com/engine/reference/builder/, or whether it's better to just remove 'docker builder' entry. It's confusing here since it's not an actual command. Thoughts?

**Comment by bermudezmt** [comment]
@nassimBouazabia @moreal - hello there. This is part of a larger Engine CLI reference docs issue that we are working on. Please bear with us as we get the problem sorted out.

**Comment by bermudezmt** [comment]
This has been fixed.
