### ISSUE TITLE
The web page is missing

### ISSUE THREAD

**Issue by billmetangmo** [docker/docker.github.io#8337]
### Problem description

I found on this article : https://container-solutions.com/running-docker-containers-with-systemd/ a reference to the page https://docs.docker.com/articles/host_integration/ for systemd integration wih docker best practices however the page does not exist anymore.

**Comment by arjun-dandagi** [comment]
https://docs.docker.com/config/daemon/systemd/ is this what you were looking for @billmetangmo

**Comment by billmetangmo** [comment]
Oki thanks @arjun-dandagi

**Comment by paigehargrave** [comment]
@billmetangmo @arjun-dandagi Thank you for your input and time here! I'm closing this issue as it appears there is nothing else needed at this time. Please resubmit another issue if you are experiencing problems with the Docker documentation. Thank you!
