### ISSUE TITLE
18.06

### ISSUE THREAD

**Issue by vamsigundimeda** [docker/docker.github.io#8338]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by bermudezmt** [comment]
@vamsigundimeda Did you mean to access 18.03 or information around Engine `https://docs.docker.com/engine/release-notes/#18062`?

**Comment by bermudezmt** [comment]
Hi @vamsigundimeda. Since no additional information came through, I am closing this issue. Please submit another issue if you notice anything else on the site.
