### ISSUE TITLE
Toolbox download .exe is a year outdated (v18.03)

### ISSUE THREAD

**Issue by BretFisher** [docker/docker.github.io#8348]
File: [toolbox/toolbox_install_windows.md](https://docs.docker.com/toolbox/toolbox_install_windows/)

https://github.com/docker/toolbox/releases has 18.09.2 as the latest release for download, but the download link on this page for windows still installs 18.03 version.

**Comment by bermudezmt** [comment]
Thanks for raising the issue, @BretFisher . Hey @guillaumerose - Paige and I are thinking about updating the download link and adding the following note to https://docs.docker.com/toolbox/toolbox_install_windows/:

> To continue using Docker Toolbox, see https://github.com/docker/toolbox/releases for information about downloading the latest version of Docker Toolbox and related components.

**Comment by BretFisher** [comment]
LGTM. The one difference is the github download gets an unsigned warning (verified publisher dialog). The docker.com one is signed and less alarming on install.

**Comment by bermudezmt** [comment]
@BretFisher We did confirm that downloading the executable file via docker/toolbox Github gives you the unsigned warning as shown in the screenshot below:
![windows-toolbox](https://user-images.githubusercontent.com/5844484/53528268-02ef6d00-3a9e-11e9-9eea-8be332bd8ea8.png)


We've looked for the official download link but can't find it here: https://download.docker.com/win/static/stable/x86_64/ - Can you provide us with the official link and we'll update the link and add the note to the file?

**Comment by BretFisher** [comment]
https://download.docker.com/win/stable/DockerToolbox.exe is the link to download from https://docs.docker.com/toolbox/toolbox_install_windows/

**Comment by paigehargrave** [comment]
@BretFisher Hi Bret - I am closing this issue based on the #8465 addition. Please let us know if you see additional issues - thank you for bringing this to our attention!
