### ISSUE TITLE
"Limitations of Windows containers for localhost and published ports" outdated

### ISSUE THREAD

**Issue by Leon99** [docker/docker.github.io#8353]
File: [docker-for-windows/troubleshoot.md](https://docs.docker.com/docker-for-windows/troubleshoot/)

### Limitations of Windows containers for localhost and published ports
is no longer an issue, according to https://blog.sixeyed.com/published-ports-on-windows-containers-dont-do-loopback/

**Comment by bermudezmt** [comment]
@gtardif @mikeparker - can you please verify that we can remove this info from the page?

**Comment by StefanScherer** [comment]
@bermudezmt Windows containers work with published ports on localhost beginning with Windows 10 1809 using Docker Desktop for Windows as well as Windows Server 2019 / 1809 using Docker EE.

**Comment by paigehargrave** [comment]
@StefanScherer Thank you so much for the information and quick response!
