### ISSUE TITLE
Setting TLS via both daemon.json and dockerd register-service breaks engine

### ISSUE THREAD

**Issue by stevenfollis** [docker/docker.github.io#8368]
### Problem description

If you setup TLS certificates both via the `daemon.json` [as instructred](https://docs.docker.com/ee/ucp/admin/configure/join-nodes/join-windows-nodes-to-cluster/#compatibility-with-daemonjson) _and_ register the Windows Service with the `dockerd` command that is [referenced](https://docs.docker.com/ee/ucp/admin/configure/join-nodes/join-windows-nodes-to-cluster/#set-up-certs-for-the-dockerd-service) then you get an error of duplicative TLS declarations (one in daemon.json, one in service registration).

### Problem location

- I saw a problem on the following URL: [Join Windows Worker nodes to your cluster](https://docs.docker.com/ee/ucp/admin/configure/join-nodes/join-windows-nodes-to-cluster)

### Suggestions for a fix

Logging this before I forget but haven't thought through an approach. Needs to call out that if you use the `docker container run --rm -v C:\ProgramData\docker\daemoncerts:C:\certs docker/ucp-agent-win:3.1.2 generate-certs` command then you do not want to set those values in `daemon.json`

**Comment by traci-morrison** [comment]
@stevenfollis Is this issue for all versions of UCP or only 3.1.2? Thanks.

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.

**Comment by traci-morrison** [comment]
@stevenfollis The Infrastructure team is copying our repos over to Mirantis this week. Any open PRs and issues will be lost, so please do what you can to close or merge this PR before Thursday. Thank you!

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
