### ISSUE TITLE
yum list docker-engine.x86_64 --showduplicates

### ISSUE THREAD

**Issue by iamfelic** [docker/docker.github.io#8374]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by traci-morrison** [comment]
Thank you for your feedback. There doesn't seem to be enough details in the issue for us to work on. If this really is a documentation issue and I have misunderstood, please reopen it with more information.
