### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by hcgrove** [docker/docker.github.io#8376]
### Problem description

https://docs.docker.com/config/pruning/ contains a link called "docker volume prune reference" to https://docs.docker.com/engine/reference/commandline/volume_prune.md, but that page does not exist.

**Comment by moreal** [comment]
Did you say this page?

https://docs.docker.com/engine/reference/commandline/volume_prune/

**Comment by hcgrove** [comment]
No, I didn't say that.

I didn't see it either, but I did find what I was after somewhere else. That page looks like what should be linked to.

**Comment by traci-morrison** [comment]
This issue is resolved. If the problem persists, please open a new issue. Thank you.
