### ISSUE TITLE
Need getting started with Docker version 1.12.6, build 78d1802

### ISSUE THREAD

**Issue by DebRez** [docker/docker.github.io#8388]
File: [get-started/index.md](https://docs.docker.com/get-started/)
'docker' commands are different than the get-started doc for 17.06

Where is a tutorial for Docker version 1.12.6, build 78d1802?

**Comment by bermudezmt** [comment]
@DebRez We have removed unsupported documentation versions from docs.docker.com but you should still be able to access the documentation. Please see https://github.com/docker/docker.github.io#accessing-unsupported-archived-documentation for details on how. I have filed an issue [here](https://github.com/docker/docker.github.io/issues/8393) to provide a proper redirect and hopefully avoid further confusion around this change. Please let us know if you have any more questions.

**Comment by thaJeztah** [comment]
I'd highly recommend updating to a current version of Docker, as docker 1.12 has not been maintained for a long time, and has known vulnerabilities (including possible container escapes, which allows a container to obtain full `root` access on the host)
