### ISSUE TITLE
Docker cannot be downloaded without login

### ISSUE THREAD

**Issue by stumo** [docker/docker.github.io#8396]
### Problem description

You need to login to download docker CE. This makes no sense for a CE product.

### Problem location

- I saw a problem on the following URL: https://hub.docker.com/editions/community/docker-ce-desktop-windows

### Suggestions for a fix

Allow download without login

**Comment by guba-odudkin** [comment]
Apparently you can't download it even after login :) It's broken completely right now

**Comment by traci-morrison** [comment]
Thank you for your feedback. This seems to be a feature request or a fundamental change in the way Docker works, but this GitHub repository is only for Docker documentation. Please file an issue in
https://github.com/docker/docker-ce instead.
