### ISSUE TITLE
Using ssh keys in Dockerfile

### ISSUE THREAD

**Issue by glass-ships** [docker/docker.github.io#8404]
File: [index.md](https://docs.docker.com/)

I'm not sure how common a use case this is, or where a good place would be for it, but no thorough/official documentation currently exists for a situation where a Dockerfile needs to pull a private repository by ssh-key. 

In such a situation (where the ssh-key already exists) a user can pass their key as an ARG in the Dockerfile. **Note that** in the case of rsa keys (have not tested other key types), both the public and private keys, as well as the known_hosts file must _all_ be passed (without the known_hosts file, a prompt will ask if the user wants to accept the fingerprint, and the non-zero return stops the build process). 

As an example (from my CDMS JupyterLab Dockerfile), 
```
## supply credentials
ARG SSHKEYPUB
ARG SSHKEYPVT
ARG SSHHOSTS

RUN mkdir /root/.ssh && \
	echo "$SSHKEYPUB" > /root/.ssh/id_rsa.pub && \
	echo "$SSHKEYPVT" > /root/.ssh/id_rsa && \
	echo "$SSHHOSTS" > /root/.ssh/known_hosts

COPY scripts/ssh-config /root/.ssh/config
```
Followed by the build command: 
```
docker build \
    --build-arg SSHKEYPVT="$(cat ~/.ssh/id_rsa)" \
    --build-arg SSHKEYPUB="$(cat ~/.ssh/id_rsa.pub)" \
    --build-arg SSHHOSTS="$(cat ~/.ssh/known_hosts)" \
    --rm \
    -f Dockerfile .
```
Note that this example assumes the existence of an ssh config file (under `scripts/` relative to the Dockerfile) which designates a host name and port number, but this is not necessary. 

It is also worth addressing security implications of such a setup: users certainly do not want their ssh keys lingering in the final build. By using the multi-stage built feature of Docker CE Edge, this can be done in an intermediate image, and the contents of the `git pull` can then be passed to the final image - **no lingering keys**!  For an example, see [my Dockerfile setup for CDMS's analysis environment](https://github.com/glass-ships/cdms-jupyterlab)

**Comment by AkihiroSuda** [comment]
The right way is to use `docker build --ssh` (introduced in Docker v18.09)

**Comment by glass-ships** [comment]
Sorry for the delay in responding; this was tricky to find in documentation, but is exactly what I was looking for at the time! 

I've since decided to create a bash script that clones and interacts with repositories locally, and they're later passed into the image via `COPY` commands.
