### ISSUE TITLE
interlock: remove instructions on how to deploy ucp-interlock

### ISSUE THREAD

**Issue by trapier** [docker/docker.github.io#8415]
### Problem description

It would simplify UCP support life if the only documented way to deploy interlock were through the UCP UI or API, with the most explicit goal being that the interlock core service is always named `ucp-interlock`.  Please remove references to `docker service create docker/ucp-interlock` from the docs.

### Problem location
Instructions for service clusters start by creating the core service from scratch:

https://github.com/docker/docker.github.io/blob/master/ee/ucp/interlock/usage/service-clusters.md

I don't see any others after a review of `git grep -A10 service.create ee/ucp/interlock`

### Project version(s) affected

UCP 3.0 and UCP 3.1

### Suggestions for a fix

Update the service cluster doc to remove the `docker service create` call and replace it with instructions for enabling interlock via UCP WebUI or API.

**Comment by paigehargrave** [comment]
@trapier - I'm almost finished with a restructure of all of the Interlock information. I'll loop you in when I open the PR - would love to set up a brief call to go through it all as well as incorporate what is needed for this Issue. Thank you for all of your help with this information!

**Comment by paigehargrave** [comment]
@trapier - I think this has been addressed with the content refactor, but if not, please let me know and I'll reopen it - thank you!
