### ISSUE TITLE
Best practice for ENV is not correct

### ISSUE THREAD

**Issue by easymf** [docker/docker.github.io#8422]
File: [develop/develop-images/dockerfile_best-practices.md](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

I am following steps in ENV section and the first invocation of "$ docker run --rm -it test sh echo $ADMIN_USER" ends up with;

sh: can't open 'echo': No such file or directory

This is on Ubuntu with docker 18.06-1.ce

**Comment by thaJeztah** [comment]
Ah, thanks for reporting; yes, the example is incorrect, and should be;

```bash
docker run --rm test sh -c 'echo $ADMIN_USER'
```

I'll open a pull-request to fix that 👍

**Comment by thaJeztah** [comment]
PR is here; https://github.com/docker/docker.github.io/pull/8424
