### ISSUE TITLE
Conflicting instruction switching between edge and stable

### ISSUE THREAD

**Issue by eric-johnson** [docker/docker.github.io#8429]
File: [docker-for-mac/faqs.md](https://docs.docker.com/docker-for-mac/faqs/)

This red text in the answer for switching back-and-forth between stable and edge is inconsistent with the messaging in the Docker for Mac app.
On this page:
> To safely switch between Edge and Stable versions ... uninstall the current version before installing another.

Docker for Mac -> Preferences -> "switch to stable" link
> We will uninstall the edge version after you install the stable one.
You will lose your containers and settings.
Do you want to continue?

**Comment by eric-johnson** [comment]
Maybe these two messages have a different meaning of "uninstall."
This FAQ would make sense if it meant "remove Docker from your Applications before installing another."
The message in the app would make sense if it said "When a different version of Docker Desktop is launched for the first time, all of your existing containers, images, and setting will be removed"

**Comment by aevesdocker** [comment]
Closing issue as this has been fixed
