### ISSUE TITLE
little mistake on document part 2 

### ISSUE THREAD

**Issue by mygh021** [docker/docker.github.io#8436]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

In the section[Run the App]  In later steps, map port 4000 on the host to port 80 .
Should be
 In later steps, map port **80** on the host to port 80

**Comment by DawnWood-Docker** [comment]
Hi @mygh021 Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
