### ISSUE TITLE
update docker-compose autocomplete docs

### ISSUE THREAD

**Issue by rahulpatil-99** [docker/docker.github.io#8439]
File: [compose/completion.md](https://docs.docker.com/compose/completion/)

There is difference between docs and md file. Docs seems confusing because numbering is wrong but as i go through the completion.md file, it is in correct manner. so have a look at it and update the docs.

I have attached both screenshot.

docs file :- 

<img width="983" alt="Screenshot 2019-03-11 at 12 15 49 PM" src="https://user-images.githubusercontent.com/34855244/54104922-79259500-43f7-11e9-97af-1876f16f5851.png">

md file :-

<img width="973" alt="Screenshot 2019-03-11 at 12 17 32 PM" src="https://user-images.githubusercontent.com/34855244/54104995-ac682400-43f7-11e9-8039-5e0c308d1b9f.png">

**Comment by bermudezmt** [comment]
@rahulpatil-99 this was fixed by https://github.com/docker/docker.github.io/pull/8516. Thanks for reporting the issue!
