### ISSUE TITLE
Misleading comment in docker toolbox points users for expensive alternative

### ISSUE THREAD

**Issue by marcelotaube** [docker/docker.github.io#8440]
File: [toolbox/toolbox_install_windows.md](https://docs.docker.com/toolbox/toolbox_install_windows/)

This is about the statement "Legacy desktop solution. Docker Toolbox is for older Mac and Windows systems...."
A tool like docker is provided for free and used as a standard used for open source and free projects as well as self training for individuals.
Docker for windows requires windows 10 professional for hyper V, this is not only a very specific version of the operating system but also the most expensive flavour, which costs an extra 100 dollars.
My brand new computer comes with windows 10 home included, and i had no plan on buying a new operating system, I was mislead by that statement in many ways, first Docker for windows would not work for my system even if my computer is not "an older Windows system", but also if i develop my project and my scripts on top of Docker Windows rather than Docker Toolbox I would prevent many of my users from using easily my project and they would have to adapt it. I want to make life easier for my users rather than more difficult.

Having say that i understand that the docker windows is the new project which contains the new features which you don't offer with the toolbox, and that your brand new project is the exciting one for you guys and that is the one you want to promote. All fine and very understandable. But I would like you guys to provide a neutral statement which has the best thing for all kinds of users in mind.

**Comment by craig-osterhout** [comment]
No longer applicable as Docker Toolbox has been deprecated.
