### ISSUE TITLE
Suggest using docker-machine (instead of setting up HTTPS manually)

### ISSUE THREAD

**Issue by efrainsteinbach** [docker/docker.github.io#8444]
File: [engine/security/https.md](https://docs.docker.com/engine/security/https/)

I suggest adding a remark or warning at the top of the https doc page to remind readers that they should consider using docker-machine (with generic driver) to setup the HTTPS connection - this works beautifully with just one command. I lost two hours struggling with certificates and config files until luckily I remembered this alternative.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As Docker Machine has been deprecated, this issue appears to be no longer applicable. If you feel the issue persists, please let us know.

**Comment by efrainsteinbach** [comment]
idk, maybe you could still add a comment block about `docker swarm join` then? I mean the question is why one would land on this page about exposing/securing the daemon. I'd say the typical scenario is that people want to remote control a daemon on a ci/cd/test or production machine, and for that docker swarm (or k8s) is easier.
