### ISSUE TITLE
Show error message that appears if you haven't added a DTR to UCP

### ISSUE THREAD

**Issue by programmerq** [docker/docker.github.io#8445]
File: [ee/dtr/user/manage-images/sign-images/trust-with-remote-ucp.md](https://docs.docker.com/ee/dtr/user/manage-images/sign-images/trust-with-remote-ucp/)

Another example error to consider adding:

```
$ docker run --rm -it dtr.example.com/admin/trustdemo:1 echo hello world
docker: Error response from daemon: dtr.example.com must be a registered trusted registry.
See 'docker run --help'.
```

This error message can happen until you register DTR with the currently running UCP, as outlined in the registering-dtr-with-a-remote-universal-control-plane section of this document.

This error message didn't reveal a whole lot when googled, and there should be a clear pointer from this error message to that section.

**Comment by bermudezmt** [comment]
Closed via #8480 .
