### ISSUE TITLE
Bad URL for `Docker Enterprise Basic Edition` at `Windows containers and Windows Server 2016` section

### ISSUE THREAD

**Issue by ivasilyev-servicetitan-com** [docker/docker.github.io#8468]
### Problem description

There is a died URL for `Docker Enterprise Basic Edition` at [Windows containers and Windows Server 2016](https://docs.docker.com/docker-for-windows/troubleshoot/#windows-containers-and-windows-server-2016)

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/docker-for-windows/troubleshoot/#windows-containers-and-windows-server-2016

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/ee/index

- Other: <DETAILS>

**Comment by bermudezmt** [comment]
This has been fixed via #8470
