### ISSUE TITLE
Add proxy example with HTTPS

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#847]
File: [engine/admin/systemd.md](https://docs.docker.com/engine/admin/systemd/)

The proxy example on this page isn't great.  It doesn't include HTTPS.  Most environments that have a proxy for HTTP would also have one for HTTPS.

**Comment by frankgreco** [comment]
per [these](https://docs.docker.com/hackathon/#claiming-a-bug) instructions, I am claiming this bug.

**Comment by frankgreco** [comment]
PR #2861
