### ISSUE TITLE
Scan on push default is a poorly written statement.

### ISSUE THREAD

**Issue by okrangerb3** [docker/docker.github.io#8473]
File: [ee/dtr/admin/configure/set-up-vulnerability-scans.md](https://docs.docker.com/ee/dtr/admin/configure/set-up-vulnerability-scans/)

**Comment by paigehargrave** [comment]
@okrangerb3 Hi Brent, is this better: 
Set repository scanning mode

Two scanning modes are available when security scanning is enabled:

- **On push**: images are scanned on each `docker push` to the repository, and when users with write access select the **Start Scan** link or **Scan** button.
- **Manual**: images are only scanned when users with write access select the **Start Scan** link or **Scan** button.

By default, new repositories are set to **On push**, but you can change this setting during repository creation.

**Comment by bermudezmt** [comment]
@paigehargrave - great suggestions. This page needs to be revisited/refactored in general.

**Comment by bermudezmt** [comment]
cc: @jose-bigio - don't think I'll get around to this.

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
