### ISSUE TITLE
Document since when ARG before FROM is allowed

### ISSUE THREAD

**Issue by nightlyone** [docker/docker.github.io#8477]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

I just broke a build since the documentation is unclear since when ARG before FROM in a Dockerfile is allowed.

A simple reference that this works since v17.06 only, but the ARG directive is accepted before as documented on stackoverflow (see https://stackoverflow.com/questions/40273070/docker-build-arg-in-source-file ) would have saved me quite some time.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://github.com/docker/cli/tree/master/docs/reference
