### ISSUE TITLE
The link version Docker was invalid

### ISSUE THREAD

**Issue by ankhang140296** [docker/docker.github.io#8493]
### Problem location

- I saw a problem on the following URL: <
https://docs.docker.com/v17.12/
https://docs.docker.com/v17.09/
https://docs.docker.com/v17.06/
https://docs.docker.com/v17.03/
https://docs.docker.com/v1.13/>

- I couldn't find the information I wanted. I expected to find it near the following URL: <https://docs.docker.com/v18.03/
https://docs.docker.com/v17.12/
https://docs.docker.com/v17.09/
https://docs.docker.com/v17.06/
https://docs.docker.com/v17.03/
https://docs.docker.com/v1.13/>

- Other: <I can't find the information>

**Comment by traci-morrison** [comment]
Thank you for your feedback. There doesn't seem to be enough details in the issue for us to work on. If this really is a documentation issue and I have misunderstood, please reopen it with more information.
