### ISSUE TITLE
Typo on page? (syscall/signal)

### ISSUE THREAD

**Issue by hectoras** [docker/docker.github.io#8497]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

In the paragraph that reads:
> The STOPSIGNAL instruction sets the system call signal that will be sent to the container to exit. This signal can be a valid unsigned number that matches a position in the kernel’s syscall table, for instance 9, or a signal name in the format SIGNAME, for instance SIGKILL.

Maybe it should say **kernel’s signal table** instead of **kernel’s syscall table**?

**Comment by grumbach** [comment]
This triggered me as well, I think you're right :D

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The source content is in an upstream repo at https://github.com/docker/cli/tree/master/docs/reference
If the issue is still applicable, please help open an issue or PR in that repo where it can be fixed.
