### ISSUE TITLE
Need more info about running CentOS in a VM

### ISSUE THREAD

**Issue by vikramkhatri** [docker/docker.github.io#850]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

Under Create Docker Group --> (4) Log out and log back in is not sufficient if running in a VM. Restarting the VM was only option for CentOS 7.1.

Please see this link:

http://stackoverflow.com/questions/33562109/docker-command-cant-connect-to-docker-daemon

You should modify this to : logout and login and then restart the VM (if applicable)

**Comment by johndmulhausen** [comment]
Thanks tio @jaredestroud, who gets the points.
