### ISSUE TITLE
container-selinux (suggestion)

### ISSUE THREAD

**Issue by asijoumi** [docker/docker.github.io#8502]
File: [install/linux/docker-ce/centos.md](https://docs.docker.com/install/linux/docker-ce/centos/)

Hello, sometimes, when we try to install docker on CentOS (especially on AWS EC2 - RedHat), we have to install container-selinux.

It will be easy to install docker with this command line (with the appropriate version) :
```bash
sudo yum install http://vault.centos.org/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
```

Before the docker command line : 
```
sudo yum install docker-ce docker-ce-cli containerd.io
```

I hope this will help, and thanks to Docker Team :D

**Comment by thaJeztah** [comment]
That package is specified as required dependency for docker, so should already be installed automatically; 
https://github.com/docker/docker-ce-packaging/blob/2aac85e93495fffa62171fc50a48ec2cf50c1883/rpm/SPECS/docker-ce.spec#L18

does that not happen automatically for you?

**Comment by asijoumi** [comment]
Yes I and understand why the error appear, unfortunately when I follow the docker documentation installation, selinux is not automatically installed..  

My OS (on AWS EC2): 
```shell
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```

**Comment by thaJeztah** [comment]
so tries to install the dependency, but it produces an error during installation?

ping @seemethere PTAL

**Comment by thaJeztah** [comment]
This one went stale, and I haven't heard new reports about this, so let me go ahead and close
