### ISSUE TITLE
"List containers" modified to "List containers (default shows just running)"

### ISSUE THREAD

**Issue by ld-zero** [docker/docker.github.io#8517]
File: [engine/reference/commandline/container_ls.md](https://docs.docker.com/engine/reference/commandline/container_ls/)

Maybe this command description can add some details.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
