### ISSUE TITLE
Update Python image in tutorial

### ISSUE THREAD

**Issue by jlin83** [docker/docker.github.io#8520]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

With Python 2 on the path to deprecation, it would be nice to begin assuming people are building with Python 3 going forward.  I used `python:3.7-slim` and it seemed to work fine in this step of the tutorial.

**Comment by DawnWood-Docker** [comment]
Hi @jlin83 Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
