### ISSUE TITLE
MariaDB exemple problem

### ISSUE THREAD

**Issue by dbi2017** [docker/docker.github.io#8524]
File: [_samples/library/mariadb/index.md](https://docs.docker.com/samples/library/mariadb/)

The example in that tutorial will just not work, please add the next command before the mysql server creation:
docker netowork create some-net 
and then in the next command, which uses the mysql client, add the next option
--protocol=tcp
in order to have a really working example

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. Closing as the topic no longer exists.
