### ISSUE TITLE
Move Join nodes to your cluster to the install section

### ISSUE THREAD

**Issue by david-yu** [docker/docker.github.io#8525]
File: [ee/ucp/admin/configure/join-nodes/join-linux-nodes-to-cluster.md](https://docs.docker.com/ee/ucp/admin/configure/join-nodes/join-linux-nodes-to-cluster/)

Its currently hard to find the documentation on Joining nodes to your cluster since there are a lot of configuration steps for UCP after install. I would propose adding the join your nodes to the install section since it is technically part of the Install process: https://docs.docker.com/ee/ucp/admin/install/

![image](https://user-images.githubusercontent.com/551323/54884880-4934b380-4e33-11e9-9850-eb4fe0961627.png)

**Comment by david-yu** [comment]
cc @paigehargrave

**Comment by paigehargrave** [comment]
@david-yu Hi David - Thank you for pointing this out! We will address this for the content refactor - I'm hoping to include this with the Amberjack install work.

**Comment by traci-morrison** [comment]
Closing. The current structure will change once the docs are migrated to the Mirantis website.
