### ISSUE TITLE
Add additional instructions on how to configure orchestrators for worker nodes after joining

### ISSUE THREAD

**Issue by david-yu** [docker/docker.github.io#8526]
File: [ee/ucp/admin/configure/join-nodes/join-linux-nodes-to-cluster.md](https://docs.docker.com/ee/ucp/admin/configure/join-nodes/join-linux-nodes-to-cluster/)

Currently there is no documented process for switching Orchestrators upon joining by CLI. The process for doing so via the UI is very well documented but the process of doing this by CLI is not documented. Below are some suggestions from the Docker team:

You can change orchestrators from Swarm to Kube after joining by setting the swarm node label "com.docker.ucp.orchestrator.kubernetes" to "true".

Node labels are how you change individual nodes' orchestrators; this is expected and this is the desired API for doing so. You can set node labels through the Docker API.

You can modify the UCP config through the `/api/ucp/config-toml` API as well:
https://docs.docker.com/reference/ucp/3.1/api/

This lets you change the default node orchestrator, although you shouldn't need to change this very often. You can also supply a config file at install time.

cc @paigehargrave

**Comment by paigehargrave** [comment]
@david-yu Hi David - I think the CLI portion is documented here: https://docs.docker.com/ee/ucp/admin/configure/set-orchestrator-type/#use-the-cli-to-set-the-orchestrator-type. Please let me know if this is not what you are looking for. With regard to the API information, I can add a link to that in both https://docs.docker.com/ee/ucp/admin/configure/join-nodes/join-linux-nodes-to-cluster/ and https://docs.docker.com/ee/ucp/admin/configure/set-orchestrator-type/. Would that work, and if not, please let me know what you prefer. Thank you!

**Comment by david-yu** [comment]
No I should've scrolled down. Thanks, I'll close this.

**Comment by paigehargrave** [comment]
@david-yu - Seems like I should add a note about the API information - what do you think? Also, I'm happy to move the information to be in a more logical spot.

**Comment by david-yu** [comment]
You mean this particular part? Yes it would be helpful to see that in the docs, but not a high priority item: 

> You can modify the UCP config through the /api/ucp/config-toml API as well:
> https://docs.docker.com/reference/ucp/3.1/api/
> 
> This lets you change the default node orchestrator, although you shouldn't need to change this very often. You can also supply a config file at install time.
