### ISSUE TITLE
How does jeklly work in this site

### ISSUE THREAD

**Issue by exotfboy** [docker/docker.github.io#8528]
It looks like this site is using jeylly, while it said that the `_post` folder is where you put your contents, however I can not found that folder.

Also, the permalink of `pretty` will result in styles like this:
```
permalink: /:categories/:year/:month/:day/:title/
```

But there is no year or month or day in the url of the document link.

What's the magic?

**Comment by craig-osterhout** [comment]
Thanks for sharing. As this does not appear to be an issue with the documentation, I will close it. If you feel there is an issue, please let us know.
