### ISSUE TITLE
tutorial screen shots have wrong port number

### ISSUE THREAD

**Issue by michaelthoward** [docker/docker.github.io#8534]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)

In parts 3 and 4 of tutorial, screen shots shows default http port 80, but should explicitly show port 4000. 
Note that curl command in text explicitly says http://localhost:4000

![image](https://user-images.githubusercontent.com/6756054/55035856-60b89b80-4fef-11e9-8fae-e70cfdfbf2eb.png)

This caused a problem for me when I hit Tutorial Part 4 because while googling for a solution I found #4608 and got confused. 

Note that there is no mention of port 4000 in the text nor in the screen shot

![image](https://user-images.githubusercontent.com/6756054/55083417-e41ecf00-5079-11e9-8e98-d92f54feaa04.png)

yet port 4000 is required

![image](https://user-images.githubusercontent.com/6756054/55083528-103a5000-507a-11e9-80e0-edae5265efb3.png)

**Comment by michaelthoward** [comment]
This port confusion problem is pervasive. 
In part 3, the docker-compose.yml file shows using port 4000 and the text reinforces that. 

![image](https://user-images.githubusercontent.com/6756054/55085632-5b099700-507d-11e9-9161-e051a734f8ee.png)

Yet, the Recap and cheat sheet video shows using port 80

![image](https://user-images.githubusercontent.com/6756054/55085696-7bd1ec80-507d-11e9-890e-e8412297acd1.png)

**Comment by michaelthoward** [comment]
By the time you get to Part 5 everything assumes port 80.
This is a source of confusion for newbies who are struggling to learn about port mapping. 
The tutorial is where they/we start, and if it is confusing then that does not build confidence.

**Comment by abuuzayr** [comment]
thanks @michaelthoward .. however since this is a swarm I am expecting to be able to access the app via the 2nd VM's IP as well, even with port. However I can only get a response from the first VM:

![Screen Shot 2019-05-23 at 12 32 41 PM](https://user-images.githubusercontent.com/37131556/58225935-e25e4880-7d56-11e9-8e88-41fe410988aa.png)

Is it working for you?

**Comment by abuuzayr** [comment]
Ok wow. this is strange. I just tried it and its working without the ports:

![Screen Shot 2019-05-23 at 12 35 46 PM](https://user-images.githubusercontent.com/19371989/58226010-4da81a80-7d57-11e9-9a9d-13704b1b4a4a.png)

The ports in my docker compose is set to `80:80`:

![Screen Shot 2019-05-23 at 12 35 59 PM](https://user-images.githubusercontent.com/19371989/58226024-5ac50980-7d57-11e9-8849-ab38f5c194a7.png)

**Comment by DawnWood-Docker** [comment]
Hi everyone!! Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
