### ISSUE TITLE
correct typo

### ISSUE THREAD

**Issue by patriques82** [docker/docker.github.io#8549]
File: [engine/userguide/networking/work-with-networks.md](https://docs.docker.com/engine/userguide/networking/work-with-networks/)

Under
-> Limitations of docker network
-> USE NETWORK-SCOPED ALIASES
-> Example
there is a typo in .2 

"PING container5 (172.25.0.6): 56 data bytes" should be "PING container6 (172.25.0.6): 56 data bytes"

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The issue appears to be no longer applicable to the current docs. If the issue still persists, please let us know
