### ISSUE TITLE
Incomplete sentence in Azure requirements

### ISSUE THREAD

**Issue by henrytk** [docker/docker.github.io#8551]
File: [ee/ucp/admin/install/install-on-azure.md](https://docs.docker.com/ee/ucp/admin/install/install-on-azure/)

This sentence is incomplete:

> An Azure Service Principal with Contributor access to the Azure Resource Group hosting the UCP Nodes.

What about the Azure Service Principal? You need to have one? I don't get it.

**Comment by bermudezmt** [comment]
@ollypom can we take this into account before merging #8522 ?

**Comment by ollypom** [comment]
@bermudezmt @henrytk no problem :), will include within https://github.com/docker/docker.github.io/pull/8522.

**Comment by traci-morrison** [comment]
This update was included in https://github.com/docker/docker.github.io/pull/8522.
