### ISSUE TITLE
Windows command prompt can't find "docker"

### ISSUE THREAD

**Issue by Korporal** [docker/docker.github.io#8561]
### Problem description
Starting a Windows command prompt (or power shell) as instructed here fails:

https://docs.docker.com/docker-for-windows/

It fails with:

![image](https://user-images.githubusercontent.com/12262952/55291921-53a5fe80-5399-11e9-83c0-03c33aa20f91.png)

### Problem location

See above URL

### Suggestions for a fix

Either correct the way that Docker For Windows installs so that it adjusts the relevant path settings or enhance the documentation to explain how we can get the command prompt to find `docker`.

I do not know if installation was successful or failed in some way, it is running I can see that much and I did give it my credentials with my Docker account and so on but the inability to find `docker `in the console window could be due to some install issue - I simply have no idea. 

I've gone to the trouble of installing this and preparing to explore Docker with Visual Studio 2019 and now I'm stuck because I cannot even begin to follow the _Getting started with Docker for Windows_ tutorial.

NOTE: This happens with newly opened console windows, opened after installing Docker For Windows.

**Comment by usha-mandya** [comment]
Closing this as it is not a documentation issue.
