### ISSUE TITLE
Broken link in navigation to Interlock Labels Reference

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#8563]
### Problem description

In the left hand navigation, the link to https://docs.docker.com/ee/ucp/interlock/usage/labels-reference/ is broken.  It directs me to https://docs.docker.com/ee/ucp/interlock/usage/labels-reference.md/.  

### Problem location

The navigation in the Product manual section is:

`Universal Control Plane` > `Deploy apps with Swarm` > `Layer 7 routing` > `Routing traffic to services` > `Using routing labels`

**Comment by bermudezmt** [comment]
Fixed by #8565 . Thanks again, @paigehargrave !
