### ISSUE TITLE
Update minimum requirements: UCP Manager and worker disk space

### ISSUE THREAD

**Issue by avinashdesireddy** [docker/docker.github.io#8585]
File: [ee/ucp/admin/install/system-requirements.md](https://docs.docker.com/ee/ucp/admin/install/system-requirements/)

**UCP Manger and Worker minimum requirements - review**
In the minimum requirements section, "5GB of free disk space for the `/var` partition for manager nodes." This info misleads customers or users because several applications use `/var` and user verifies they have space during the install and soon run into issues with docker or ucp or other components in the system.
Instead of `/var`, it is good to add how much space is required or used by `/var/lib/docker` and `/var/lib/kubelet` for a minimum install and refer to the details(may be in a different page) with what is stored in `/var/lib/docker` and `/var/lib/kubelet` and how to estimate the sizing for the nodes based on the workload. 

**Space consumption on UCP manager and worker**
I installed UCP 3.1.5 and noticed that `/var/lib/docker` is consuming more space that what is specified in the minimum requirements

**UCP Manager on RHEL 7**
```
[root@ip-172-31-8-212 ~]# du -s -h /var/lib/docker
5.9G	/var/lib/docker
[root@ip-172-31-8-212 ~]#
```
**UCP Worker on RHEL 7**
```
[root@ip-172-31-18-155 yum.repos.d]# du -s -h /var/lib/docker
2.0G	/var/lib/docker
```

```
Server: Docker Enterprise 2.1
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       c3516c4
  Built:            Wed Mar 27 18:05:47 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 Universal Control Plane:
  Version:          3.1.5
  ApiVersion:       1.39
  Arch:             amd64
  BuildTime:        Tue Mar 26 20:37:31 UTC 2019
  GitCommit:        e3b1ac1
  GoVersion:        go1.10.6
  MinApiVersion:    1.20
  Os:               linux
 Kubernetes:
  Version:          1.11+
  buildDate:        2019-03-01T22:07:27Z
  compiler:         gc
  gitCommit:        b7a0d533758a3a4dda2a8aa632f88eafc589da90
  gitTreeState:     clean
  gitVersion:       v1.11.8-docker-1
  goVersion:        go1.10.8
  major:            1
  minor:            11+
  platform:         linux/amd64
 Calico:
  Version:          v3.5.2
  cni:              v3.5.2
  kube-controllers: v3.5.2
  node:             v3.5.2
```

cc: @ericsmalling @clemenko

**Comment by bermudezmt** [comment]
@david-yu can we please look into this? cc: @paigehargrave

**Comment by bermudezmt** [comment]
@david-yu Has this issue been handled?

**Comment by david-yu** [comment]
@bermudezmt This was the prior recommendation from the field an the QA team. @antonybichon17 Could you verify if the 5GB limit still stands or if we should update to perhaps 10GB? cc @mklamb

**Comment by david-yu** [comment]
It looks like the current recommendation is 6GB: https://docs.docker.com/ee/ucp/admin/install/system-requirements/

**Comment by mklamb** [comment]
disk space is cheap.  lets not be too conservative here.  10GB provides some protection, I think....

**Comment by paigehargrave** [comment]
Added to https://github.com/docker/docs-private/pull/1121

**Comment by david-yu** [comment]
@paigehargrave LGTM

**Comment by paigehargrave** [comment]
@david-yu Thank you! Closing this issue per docker/docs-private#1121.
