### ISSUE TITLE
Feedback for: docker-cloud/getting-started/deploy-app/5_deploy_the_app_as_a_service.md

### ISSUE THREAD

**Issue by talex5** [docker/docker.github.io#859]
File: [docker-cloud/getting-started/deploy-app/5_deploy_the_app_as_a_service.md](https://docs.docker.com/docker-cloud/getting-started/deploy-app/5_deploy_the_app_as_a_service/)

Some problems I had following the tutorial:

- It tries to deploy to my personal account (which has no nodes) rather than to my organisation account. I don't know how to tell it where to deploy.

- I can't work out how to remove the service now that it's been created (`docker-cloud service rm web` doesn't seem to exist).

**Comment by sanscontext** [comment]
Hey, thanks for the feedback. This tutorial was developed before we had teams and orgs in Cloud. I've got a PR staged, let me know if this helps.
