### ISSUE TITLE
Uninstall is not working for CentOS

### ISSUE THREAD

**Issue by Bonu** [docker/docker.github.io#8590]
File: [install/linux/docker-ee/centos.md](https://docs.docker.com/install/linux/docker-ee/centos/)

Use the below commands to uninstall docker from your machine

      # yum list installed | grep -i docker
      # sudo yum remove docker-ce-cli.x86_64
      # sudo yum remove containerd.io.x86_64

**Comment by joeyhub** [comment]
It might be useful to give a bit of the output.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If the issue still persists, please provide more details and let us know how the issue applies to the documentation. If you're looking for help with your specific system, you may try the Docker Community Forums.
