### ISSUE TITLE
Orphan links in docker compose file reference

### ISSUE THREAD

**Issue by tallero** [docker/docker.github.io#8598]
### Problem description

Documentation links to an orphan page

### Problem location

    https://docs.docker.com/compose/compose-file/#volume-configuration-reference

- I saw a problem on the following URL:

    https://docs.docker.com/engine/admin/volumes/volumes.md

The correct link is

    https://docs.docker.com/storage/volumes/

In general I saw a lot of links are broken.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. It appears that the broken link no longer appears in https://docs.docker.com/compose/compose-file/#volume-configuration-reference. If you find that the issue still persists, please let us know.
