### ISSUE TITLE
Feedback for: engine/reference/commandline/dockerd.md

### ISSUE THREAD

**Issue by shazChaudhry** [docker/docker.github.io#86]
URL: engine/reference/commandline/dockerd.md

My environment is "docker for windows v1.12.1" on windows 10 and VirtualBox; created a node with "docker-machine create --driver virtualbox". where do I find daemon configuration file please? Is it not under %programdata%\docker\config\daemon.json

**Comment by mstanleyjones** [comment]
Hey @londoncalling, can you answer @shazChaudhry's question or point them to the right place in the docs?

**Comment by londoncalling** [comment]
@friism @rneugeba @dave-tucker @jeanlaurent can someone answer this question? This came in as docs feedback, but is really for the product. Let me know if you want me to log it on https://github.com/docker/for-win/issues for @shazChaudhry .

**Comment by friism** [comment]
@shazChaudhry you can find the config file for the Docker engine running in the linux VM in the normal placement for linux (`/etc/docker/daemon.json`). Use `docker-machine ssh <foo-machine>` to access it: https://docs.docker.com/machine/reference/ssh/

Please post more details on what you're trying to do if this doesn't clear things up.

**Comment by rneugeba** [comment]
@shazChaudhry you wrote: "My environment is "docker for windows v1.12.1" on windows 10 and VirtualBox". Docker for Windows does not use VirtualBox. Could you please clarify?

**Comment by shazChaudhry** [comment]
I have spent quite a few days trying to work out how to use the following and been struggling to find any documentation to get round the errors on boot2docker created by doceker-machine:

1. I have not been able to find documentation on how to set "--log-driver" option to the Docker daemon  (_i.e. dockerd --log-driver=splunk_) after a boot2docker is created by docker-machine (I read a blog somewhere that such a driver can be set in the daemon.json file? ). The following error is thrown: _docker@node1:~$ dockerd --log-driver=splunk
FATA[0000] Error starting daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid_. 

2.  When running a docker container on a Ubuntu 14.04 based machine, mounting a Docker socket (_i.e.  -v /var/run/docker.sock:/var/run/docker.sock_) is not a problem; trying to run docker commands from a Jenkins instance running in a container. But it does not appear to work on boot2docker based machines. As a reference, I was trying to work with this article: [https://stefanprodan.com/2016/continuous-integration-with-jenkins-and-disposable-containers/](url). On boot2docker machine, Jenkins container was up and running fine but could not execute docker commands and threw the following errors:
_Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon. Is the docker daemon running on this host?_

3. I suspect that no. 2 above can be resolved by setting environment options. But how do you stop, start or restart Docker daemon when boot2docker is already created by docker-machine? There seems to be no option or documentation.
_docker@node1:~$ dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock &
docker@node1:~$ FATA[0000] Error starting daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid_

So, do we have any documentation that shows how during the creation of a boot2docker (_docker-machine create --driver virtualbox_) the following flags can be set without errors?

- set log driver to splunk

- set DOCKER_OPTS=" -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock


 






@rneugeba I am certain that I did indeed install Docker for Windows as I am using a windows 10 laptop. However I had to turn off Hyper-V as it kept disabling my wi-fi connection. So, I am able to use Oracle VM VirtualBox instead:

$ docker version
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

@friism "_/etc/docker/daemon.json_" does not exist in boot2docker machine that was created by docker-machine. Please see logs below:

Using docker-machine, this is how I created a box:
**_$ docker-machine create --driver virtualbox --virtualbox-memory "2048" node1_**
Creating CA: C:\Users\shahzad.a.chaudhry\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\shahzad.a.chaudhry\.docker\machine\certs\cert.pem
Running pre-create checks...
(node1) Image cache directory does not exist, creating it at C:\Users\shahzad.a.chaudhry\.docker\machine\cache...
(node1) No default Boot2Docker ISO found locally, downloading the latest release...
(node1) Latest release for github.com/boot2docker/boot2docker is v1.12.1
(node1) Downloading C:\Users\shahzad.a.chaudhry\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.1/boot2docker.iso...
(node1) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(node1) Copying C:\Users\shahzad.a.chaudhry\.docker\machine\cache\boot2docker.iso to C:\Users\shahzad.a.chaudhry\.docker\machine\machines\node1\boot2docker.iso...
(node1) Creating VirtualBox VM...
(node1) Creating SSH key...
(node1) Starting the VM...
(node1) Check network to re-create if needed...
(node1) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe env node1

**_$ docker-machine.exe env node1_**
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="C:\Users\shahzad.a.chaudhry\.docker\machine\machines\node1"
export DOCKER_MACHINE_NAME="node1"
Run this command to configure your shell:
eval $("C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe" env node1)

**_$ docker-machine ssh node1_**
Boot2Docker version 1.12.1, build HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
Docker version 1.12.1, build 23cf638
docker@node1:~$ ls -latr /etc/docker/daemon.json
**ls: /etc/docker/daemon.json: No such file or directory**

**Comment by londoncalling** [comment]
@shazChaudhry @friism @rneugeba @nathanleclaire  @johndmulhausen  

@shazChaudhry, it sounds like you are largely using Docker via Docker Machine, not Docker for Windows. (When you disable Hyper-V, Docker for Windows cannot run. However, installing Docker for Windows gives you an install of Docker Machine, so you have it available to use.) 

Here is some detail on setting up logging drivers for containers: https://docs.docker.com/engine/admin/logging/overview/, and here is detail on the driver for Virtual Box: https://docs.docker.com/machine/drivers/virtualbox/

But beyond that, It looks like your issue is primarily concerned with trouble you are having with Docker itself. There are likely documentation updates we can make, but first we need to understand how to help you address the problems you are having with Docker.

Please log an issue with your questions on the Docker Machine repo issues list: https://github.com/docker/machine/issues, then let's move this conversation to there. Feel free to copy-paste your questions from here or link the issues.

**Comment by nathanleclaire** [comment]
@shazChaudhry `/etc/docker/daemon.json` doesn't exist by default in boot2docker, you'd have to create it and then `sudo /etc/init.d/docker restart` the daemon.

> set DOCKER_OPTS=" -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock

this is done by default

> set log driver to splunk

`docker-machine create -d virtualbox --engine-opt log-driver=splunk`

Thanks -- I'd recommend this issue be closed @londoncalling

**Comment by londoncalling** [comment]
Closing this issue now per @nathanleclaire suggestion.
