### ISSUE TITLE
Commonly used commands

### ISSUE THREAD

**Issue by kushalmahajan** [docker/docker.github.io#8607]
Maybe it would be nice to uplift the most commonly used commands in a dedicated section. 

File: [engine/reference/commandline/build.md](https://docs.docker.com/engine/reference/commandline/build/)

**Comment by bermudezmt** [comment]
@thaJeztah can you please have a look?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If the issue is still applicable, please help create an issue or PR in the upstream repo that contains the content at https://github.com/docker/cli/tree/master/docs/reference/commandline
