### ISSUE TITLE
Kubernetes is ''always'' starting in Docker Desktop for Windows 18.09.2 stable

### ISSUE THREAD

**Issue by py2013** [docker/docker.github.io#8608]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

My Kubernetes is ''always'' starting in Docker Desktop for Windows 18.09.2 stable. What's wrong with my Docker?  In one page, I found that Kubernetes is only available in Edge channel.

But in another page, the document says ''From Docker Desktop for Windows 18.02 CE Edge and 18.06 CE Stable a standalone Kubernetes server is included that runs on your Windows host, so that you can test deploying your Docker workloads on Kubernetes''.

**Comment by usha-mandya** [comment]
@py2013 Could you let us know which page you are referring to? Thanks.

**Comment by py2013** [comment]
> @py2013 Could you let us know which page you are referring to? Thanks.
I'm sorry. It has been already revised.
https://docs.docker.com/docker-for-windows/
https://docs.docker.com/docker-for-windows/kubernetes/
Thanks for your reply! It is my first time to ask a question.
