### ISSUE TITLE
Crap

### ISSUE THREAD

**Issue by allguitars** [docker/docker.github.io#8610]
File: [toolbox/toolbox_install_windows.md](https://docs.docker.com/toolbox/toolbox_install_windows/)

Are you bullying Windows 10 home users?

**Comment by thaJeztah** [comment]
could you elaborate?

**Comment by allguitars** [comment]
> could you elaborate?

It's hard to find the package for Windows 10 Home by just following your guideline. I was stuck on the website for more than 30 mins and still couldn't get my installation done on the Windows 10 Home machine. 

I suggest you just go straight to the point on the head of the first Download page saying like "Hey, are you using Windows 10 Home? Just click the following link to download the package that suits you." 

Do not just redirect people again and again, in the end making people get lost in the maze.

**Comment by thaJeztah** [comment]
The "Install Docker Desktop for Windows" page (https://docs.docker.com/docker-for-windows/install/) has a note under "System Requirements";

<img width="936" alt="Screenshot 2019-04-13 at 17 44 42" src="https://user-images.githubusercontent.com/1804568/56081994-d7d59880-5e13-11e9-9c96-cb5e2a88bf4e.png">

Would moving that note to the top of the page satisfy your request?
