### ISSUE TITLE
docker inspect -s <container> not returning sizie 

### ISSUE THREAD

**Issue by magick93** [docker/docker.github.io#8615]
File: [engine/reference/commandline/inspect.md](https://docs.docker.com/engine/reference/commandline/inspect/)

# Steps to reproduce

1. run ` docker run -it ubuntu bash `
1. In another terminal, check that there is a running container with `docker ps`.
1. Based on https://docs.docker.com/engine/reference/commandline/inspect/ I should now be able to get the: 'total file sizes if the type is container' if I run `docker inspect -s a5638b6d233a`.

## Actual result

Running ` docker inspect -s a5638b6d233a ` does not display the size. Instead it returns the same result as if I didnt specify the `-s` option.

## Docker version

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:52:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Wed Feb 13 00:24:14 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
