### ISSUE TITLE
apt-key adv --keyserver is about to stop working

### ISSUE THREAD

**Issue by alanfranz** [docker/docker.github.io#863]
### Problem description

In your Ubuntu and Debian docs, you suggest the classical ```apt-key adv --keyserver ...``` command for installing a public key for a repo; according to Ubuntu maintainers (but it seems that Debian ones are going the same way), **this is not the way to go anymore** and such approach **may not work on Ubuntu Yakkety**, since an optional component for such functionality, **dirmngr**, is not installed by default. Ubuntu Yakkety's docker-engine is currently in the testing repo and it's expected to be released along with 1.13 final, AFAIK.

See:
[https://bugs.launchpad.net/ubuntu/+source/enigmail/+bug/1623087]()
[https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1634464]()

### Problem location

https://github.com/docker/docker.github.io/blob/master/engine/installation/linux/ubuntulinux.md

### Suggestions for a fix

Either figure out how the ``` /etc/apt/trusted.gpg.d/``` directory is supposed to work, or recommend users to install the **dirmngr** package on Ubuntu Yakkety and later distros.

**Comment by mstanleyjones** [comment]
Thanks for this heads-up! Starting with Docker Engine 1.13.0, we now use `apt-key-add`, as in https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository.
