### ISSUE TITLE
Which version of Docker for Windows is Kubernetes available in?

### ISSUE THREAD

**Issue by py2013** [docker/docker.github.io#8632]
1.  File: [get-started/index.md](https://docs.docker.com/get-started/)
"Kubernetes on Docker Desktop for Windows is available in 18.02 Edge (win50) and higher edge channels only."

1. In this page ( https://docs.docker.com/docker-for-windows/kubernetes/ )
"Kubernetes is only available in Docker Desktop for Windows 18.06.0-ce-win70 CE and higher. "

1. In this page ( https://docs.docker.com/docker-for-windows/ )
"Kubernetes on Docker Desktop for Windows is available in 18.02 Edge (win50) and higher, and in 18.06 Stable (win70) and higher. "

**Comment by rondemena** [comment]
Just updated the get-started/index.md to reflect the correct indication as in the no. 2.   PR #8758 addresses this change.  As its best to reflect the stable release vs. the original edge release.  The remaining pages are correct.  This should be closed when the PR is merged.

**Comment by DawnWood-Docker** [comment]
Hi @py2013 and @rondemena I see the pr is merged. Thanks for the feedback!!
