### ISSUE TITLE
No download link

### ISSUE THREAD

**Issue by jmirkin** [docker/docker.github.io#8635]
File: [toolbox/toolbox_install_windows.md](https://docs.docker.com/toolbox/toolbox_install_windows/)

The download link for the windows version of docker toolbox is missing. It is still available for macOS.

**Comment by usha-mandya** [comment]
Hi @jmirkin, thanks for your feedback on the download URL. Please note that Docker no longer maintains the download.docker.com URL for Docker Toolbox. You can download the latest version of Docker Toolbox from https://github.com/docker/toolbox/releases. 

Docker Toolbox documentation has been updated to reflect this change. For more information, see:

- https://github.com/docker/docker.github.io/pull/8969/
- https://docs.docker.com/toolbox/overview/

Closing this issue.
