### ISSUE TITLE
Required port not listed in documentation

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#8636]
File: [ee/ucp/admin/install/system-requirements.md](https://docs.docker.com/ee/ucp/admin/install/system-requirements/)

Several customers are aware of this and it should be added asap. 

https://forums.docker.com/t/port-missing-in-ucp-system-requirements/28633

12387 <--------------This one is not referenced in the document

**Comment by thaJeztah** [comment]
What's that port used for (for the description in the table?)

**Comment by ollypom** [comment]
Hey @kavikat Port 12387 is not required in the latest UCP release (UCP 3.1.x) as the metrics server has moved to be a Kubernetes deployment. Port 12387 was required in previous versions of UCP and can be found in the relevant docs. For example in UCP 3.0 https://docs.docker.com/datacenter/ucp/3.0/guides/admin/install/system-requirements/.
