### ISSUE TITLE
DTR - Docker Volume Configuration Planning

### ISSUE THREAD

**Issue by ingshtrom** [docker/docker.github.io#8637]
### Problem description
Right now, there is documentation talking about the external storage and [just mentioning the internal storage via Docker Volumes](https://docs.docker.com/ee/dtr/admin/configure/external-storage/#local-filesystem). It doesn't talk about how to plan for your Postgres and RethinkDB database mounts, which are local (to each node in the DTR cluster) as Docker Volumes. How much throughput should I be planning for? How big should I make them? For example, Prometheus gives you an idea of how big, in the general case, a single metric will take up in disk. This is useful because we can take our current deployment to plan for how much a new deployment will need. That way we aren't on our heels when a node runs out of disk space.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/ee/dtr/admin/configure/external-storage/#local-filesystem

Maybe there is an "Internal Storage" section around this URL ^^

### Project version(s) affected
I don't think this is version specific. It depends on how long we've been using Postgres and RethinkDB under the hook of DTR.

### Suggestions for a fix
--

**Comment by bermudezmt** [comment]
Hi @ingshtrom - hope we can chat about this in person sometime next week. :)

**Comment by bermudezmt** [comment]
@cquon @caervs @RobbKistler Had a quick chat around this issue with @ingshtrom while at DockerCon. This is mainly a gap in our DTR documentation - I don't think I can dig deep until about 2-3 weeks from now, but if we can start thinking about how to tackle the documentation work now, that should help with a faster resolution/fix. 

In case I haven't said this enough, thank you for everybody's help with docs. :)

**Comment by bermudezmt** [comment]
@jose-bigio FYI - this is a gap in our documentation. It hasn't been documented at all.

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
