### ISSUE TITLE
Docker mounts still not working properly intermittently

### ISSUE THREAD

**Issue by joeyhub** [docker/docker.github.io#8642]
On multiple machines now docker mounts have stopped working with multiple docker compose files. Instead there's simply an empty directory.

Is it running out of loops or something? This isn't reproducable by giving some particular configuration. You just have to use docker a lot. More than you might in production. Happens in ubuntu hosts, centos hosts, using only root fs mounts, using shared directory mounts, etc.

Maybe once every week or so of moderate usage and bringing things up and down on multiple machines with multiple setups it becomes unable to mount. It does not emit any error, it simply presents an empty folder in the container.

Once it happens it becomes hard to get it to work again. It might involved just purging everything and starting from scratch. This can be very time consuming.

In at least one instance, as just happened now, the folder suddenly appeared sometime after the container was run. It's possible for a volume to be provided an arbitrary amount of time after a container runs? After that it started working again.

Can someone please look at how volumes are working and make sure if it's async the container start actually waits for them as well as making it fail on volumes not mounting, also making sure things like loops aren't exhausted, it's not having issues with multiple mounts, stale mounts, etc? Would be great, this has made my life a misery many a time.

I always use the latest docker from the repos (latest docker-compose from pip, but releases, not candidates) and this has been happening over the last few months are the least including on recent new installs.

Example...

```
host# run --rm -v /dir:/dir container
Warning: Could not load init file /dir/init.file doesn't exist.
guest# ls /dir
total 0
guest# exit
host# ls /dir
init.file
host# run --rm -v /dir:/dir container
Warning: Could not load init file /dir/init.file doesn't exist.
guest# ls /dir
total 0
guest# ls /dir
init.file
guest# exit
host# run --rm -v /dir:/dir container
guest# ls /dir
init.file
```

To have an idea of the impact this has several months ago I had a job application where a technical test required docker. I installed it as usual and has this problem where volumes would just not present and it refused refused to go away. After a point of spending too much time wrestling with it, it became too much and instead I just cancelled that application and got on with others. In future I'd use lxc or chroot (debbootstrap, rpm/yum, etc) rather than risking it with docker. Since then I'm still sometimes encountering this problem. Another impact of this is that I'm now trying to get something working for someone with docker and teaching them docker at the same time but this issue constantly coming up makes it very hard to learn. If you teach someone a command that doesn't work (because docker misfired), that's not easy. Because of issues like this I've hardly been able to get any work done today.

**Comment by joeyhub** [comment]
I'll add a note, I strongly suspect that if you look through the code and see nothing, then it's probably Linux not working as you expected, keep an open mind.

**Comment by DawnWood-Docker** [comment]
Hi @joeyhub I'm reviewing comments in this repo, and want to touch base with you before closing this issue. I hope that this is no longer a problem for you, but if it is let me know in the next few days.

**Comment by joeyhub** [comment]
You can close it for now. It's very frustrating for me I can't reproduce it. It's possible some other patch fixed it.

Basically whenever I start a new project or pick up some legacy it means lots or trial and error. Restarting and rebuilding a lot. Something with that frequency would trigger it probably combined with underlying specifics of my approach such as using windows for UI/IDE and vbox with xming/superputty/kitty for the bridges.

After that when I get the images and everything right the frequency of trial and error drops hugely but if something fails you just restart. It's either too infrequent then or time restraints are gone or you have a solution you know will work most rolls so just reroll. Lots of back to back seems to be a factor.

Close for now but if it happens again but is repeatable I'll got to town with the strace and gdb to get to the bottom of it then reopen with more actionable and less wild goose chase info.

**Comment by DawnWood-Docker** [comment]
Thanks for the reply, please do let us know if it happens again.
