### ISSUE TITLE
Get started. swarm. Can't start service

### ISSUE THREAD

**Issue by avalanchus** [docker/docker.github.io#8653]
I've tried to perform [step 4 of manual](https://docs.docker.com/get-started/part4) using swarm on Windows 10 +HyperV as host but get error:
_no such image: my_image_on_hub.docker.com_ (when I run "**docker stack ps getstartedlab**")
my_image_on_hub.docker.com - this image was obtained in step two
I also noticed that 0/5 replicas are work ("**docker stack services getstartedlab**"):

 ID                   |        NAME              |      MODE   | REPLICAS | IMAGE                                       | PORTS       
----------------|----------------------|-------------|------------|-----------------------------------|-------------
|nkax4k605s4i  | getstartedlab_web  | replicated  |    0/5        |mydockhubid/get-started:part2 | *:4000->80/tcp 

I've tried deploy with key --with-registry-auth but result is same.
I tried to reproduce exactly what was written in the manual, but I failed. Help me pls

**Comment by DawnWood-Docker** [comment]
Hi @avalanchus Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to. 
Love to hear your feedback on the updated guide.
