### ISSUE TITLE
Missing link in docker for windows documentation

### ISSUE THREAD

**Issue by binaryflesh** [docker/docker.github.io#8656]
I clicked on the [Docker Toolbox link in the docs](https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install) hyperlink and I got:
File: [404.md](https://docs.docker.com/404.html)

**Comment by paigehargrave** [comment]
@binaryflesh This is working for me - are you still experiencing a problem?

**Comment by usha-mandya** [comment]
Hi @binaryflesh, thanks for your feedback on the download URL. Please note that Docker no longer maintains the download.docker.com URL for Docker Toolbox. You can download the latest version of Docker Toolbox from https://github.com/docker/toolbox/releases. 

Docker Toolbox documentation has been updated to reflect this change. For more information, see:

- https://github.com/docker/docker.github.io/pull/8969/
- https://docs.docker.com/toolbox/overview/

Closing this issue.
