### ISSUE TITLE
Docker Kitematic Overview not found

### ISSUE THREAD

**Issue by binaryflesh** [docker/docker.github.io#8657]
### Problem description

I was trying to find kitematic docs.
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/kitematic/userguide.md

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by paigehargrave** [comment]
@binaryflesh - Try https://docs.docker.com/kitematic/userguide/ - this is working for me. Which file contains the broken link?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as kitematic is now deprecated.
