### ISSUE TITLE
Feedback for: cs-engine/install.md

### ISSUE THREAD

**Issue by rahim888** [docker/docker.github.io#867]
File: [cs-engine/install.md](https://docs.docker.com/cs-engine/install/)

There is no such thing as SLES12.3. 
https://www.suse.com/releasenotes/

Please check with @mavenugo on the right version

**Comment by joaofnfernandes** [comment]
@mavenugo @cpuguy83 what version of SLES does CS Engine support, given that SLES 12 only seems to have 2 service packs.
