### ISSUE TITLE
docker ps -f reference="name:tag" behaves differently than docker images -f reference="name:tag"

### ISSUE THREAD

**Issue by nawgz** [docker/docker.github.io#8671]
File: [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/)

Here, in [docker images](https://docs.docker.com/engine/reference/commandline/images/#filtering) docs, you can see the example:
```
Filtering with reference would give:

$ docker images --filter=reference='busy*:*libc'
```
So this lead me to easily finding my image using
```
docker images --filter reference="image-name:latest"
```
to get the image ID for an image I just build via `docker build . -t image-name:latest`.

I expected this exact same behavior in `docker ps` (it's the same filter, no?), a la:
```
docker ps --filter reference="image-name:latest"
```
But then I got the message
```
Error response from daemon: Invalid filter 'reference'
```

Is there a technical reason it is impossible to support ubiquitous filter formats?

**Comment by nawgz** [comment]
Now, obviously, I can use
```
docker ps --filter ancestor="image-name:latest"
```
But it's a little surprising to me x is considered x's own ancestor. 

Cheers.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create a new issue/discussion in that repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
