### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by omegamormegil** [docker/docker.github.io#8676]
File: [reference/dtr/2.6/cli/backup.md](https://docs.docker.com/reference/dtr/2.6/cli/backup/)

Under "Advanced (with chained commands)" the hyperlinked "Back up your DTR metadata" link is broken. 

It should go to "https://docs.docker.com/ee/dtr/admin/disaster-recovery/create-a-backup/" but is going to "https://docs.docker.com/reference/dtr/2.6/cli/ee/dtr/admin/disaster-recovery/create-a-backup/#back-up-dtr-metadata" which returns a "Sorry, we can't find that page"

**Comment by bermudezmt** [comment]
This has been fixed. Thanks for reporting, @omegamormegil .
