### ISSUE TITLE
Dedicated Linux worker nodes for Interlock / Ingress

### ISSUE THREAD

**Issue by avinashdesireddy** [docker/docker.github.io#8679]
File: [ee/docker-ee-architecture.md](https://docs.docker.com/ee/docker-ee-architecture/)

With several customers using Windows workers for their workloads, there is no reference for requirements when the interlock is used and customers are using UCP nodes to route the application traffic with load-balancer.

It is good to have some explicit references to have dedicated Linux worker nodes if interlock is used.

**Comment by traci-morrison** [comment]
@euanh PTAL.

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
