### ISSUE TITLE
Add an example for --reserve-memory

### ISSUE THREAD

**Issue by approxit** [docker/docker.github.io#868]
File: [engine/reference/commandline/service_create.md](https://docs.docker.com/engine/reference/commandline/service_create/)

`--reserve-memory` is quite important for swarms with dynamic service spawning. It's a pity that this have not a single word of explanation.

In docker/docker#29278 we encountered lack of information about further memory limiting.

It looks like we have 3 steps of memory limiting:
- Limit memory for container/service
- Reserve memory for service
- Limit memory for dockerd (possible by cgroups)

In all that 3 steps it should be mentioned about other limiting possibilities.

**Comment by mstanleyjones** [comment]
Addressing this in https://github.com/docker/docker/pull/32631, so closing this issue.
