### ISSUE TITLE
Docker "linux-postinstall" dead link 

### ISSUE THREAD

**Issue by ghost** [docker/docker.github.io#8684]
### Problem location

- I saw a problem on the following URL: <https://docs.docker.com/install/linux/linux-postinstall.md>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by Pingumann** [comment]
Problem description section in ISSUE_TEMPLATE.md does not seem to work. Could not get the description in with it.

Description is:
The link "https://docs.docker.com/install/linux/linux-postinstall.md" in Docker document "https://docs.docker.com/install/linux/linux-postinstall.md" Delivers following error: "Sorry, we can't find that page"

**Comment by thaJeztah** [comment]
What page did you find the broken link on? Do you happen to have JavaScript disabled?

I think this is the page you're looking for; https://docs.docker.com/install/linux/linux-postinstall/

But if you can point to the page where you found the broken link, then we can have a look at fixing it.

Thanks!

**Comment by Pingumann** [comment]
SOLVED the issue -- thanks.
The Link is on https://docs.docker.com/v17.09/engine/installation/linux/centos/

Yea, it was JS. 
By default JS is disabled in browsers for security reasons. Never had that before ...

**Comment by traci-morrison** [comment]
This issue appears to be resolved.
