### ISSUE TITLE
"docker build" does not work as mentioned in this guide (Windows)

### ISSUE THREAD

**Issue by flechnical** [docker/docker.github.io#8691]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

On Docker for Windows you have to declare the directory you want to run docker build on.

You could do "docker build ." or "docker build ./" and it will use the Dockerfile in the current terminal directory (".").

**Comment by DawnWood-Docker** [comment]
Hi @flechnical Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
