### ISSUE TITLE
Issue with Dockerfile preventing tutorial from running on Mac OS X

### ISSUE THREAD

**Issue by jcucl** [docker/docker.github.io#8701]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

The creation of the Dockerfile contains:

```
# Copy the current directory contents into the container at /app
COPY . /app
```

This makes the docker run command exit silently and nothing happens. The line needs to be replaced with:

```
# Copy the current directory contents into the container at /app
ADD . /app
```

Solution found here: https://stackoverflow.com/questions/47630767/docker-get-startedpython-not-working

**Comment by DawnWood-Docker** [comment]
@jcucl Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
