### ISSUE TITLE
Instructions for *Install Docker Toolbox on Windows** enters a pages cycle

### ISSUE THREAD

**Issue by HelioGuilherme66** [docker/docker.github.io#8703]
File: [toolbox/index.md](https://docs.docker.com/toolbox/)

There is a link to: `Go to the Docker Toolbox page.`  that takes to https://docs.docker.com/toolbox/
from there we get:
```
Ready to download Toolbox? See Install Docker Toolbox on macOS or Install Docker Toolbox on Windows for download and install instructions.
```
where if we follow the link **Install Docker Toolbox on Windows** we return to this page:
https://docs.docker.com/toolbox/toolbox_install_windows/

So we are in a cycle, because is missing the step and link to get the executable.
There is a note, but it is not linked:
```
Note: To continue with the latest version of Docker Toolbox, see https://github.com/docker/toolbox/releases for information about downloading the latest version and related components.
```

Maybe is because of this cycle, that you have the **Rate this page:**  up =95 down = 1109

This may be a duplicate of #7257

**Comment by jnoordzij87** [comment]
Nice, thanks! Brilliant webdesign by our docker friends :/

**Comment by usha-mandya** [comment]
Hi @HelioGuilherme66, thanks for your feedback on the download URL. Please note that Docker no longer maintains the download.docker.com URL for Docker Toolbox. You can download the latest version of Docker Toolbox from https://github.com/docker/toolbox/releases. 

Docker Toolbox documentation has been updated to reflect this change. For more information, see:

- https://github.com/docker/docker.github.io/pull/8969/
- https://docs.docker.com/toolbox/overview/

Closing this issue.
