### ISSUE TITLE
Bad Github Link

### ISSUE THREAD

**Issue by javajason** [docker/docker.github.io#8707]
File: [engine/release-notes.md](https://docs.docker.com/engine/release-notes/)
In the 18.09.5 section of the [Docker Engine Release Notes](https://docs.docker.com/engine/release-notes/), the Known Issues is the following:

> Known Issues
> There are [important changes](https://github.com/docker/docker.github.io/blob/patch-04-2019/ee/upgrade) to the upgrade process that, if not correctly followed, can have an impact on the availability of applications running on the Swarm during upgrades. These constraints impact any upgrades coming from any version before 18.09 to version 18.09 or later.
> 

The "important changes" link directs you to https://github.com/docker/docker.github.io/blob/patch-04-2019/ee/upgrade, which displays a 404 error. (This may be a permissions issue rather than a traditional "page not found" error that 404 usually means, but it still shouldn't happen.)

**Comment by adrian-plata** [comment]
This issue has been resolved.
