### ISSUE TITLE
docker-machine mount does not work

### ISSUE THREAD

**Issue by RRicardotj** [docker/docker.github.io#8710]
File: [machine/reference/mount.md](https://docs.docker.com/machine/reference/mount/)

I am following the steps of docker-machine explanation but it does not work. When I use the command `docker-machine mount dev:/home/docker/foo foo` on my mac the terminal answerd is `You must have a copy of the sshfs binary locally to use the mount feature`.

Can anyone help me?

**Comment by guille-mas** [comment]
Install sshfs first. I used brew to do so and it worked. 
`brew install sshfs`

**Comment by RRicardotj** [comment]
> Install sshfs first. I used brew to do so and it worked.
> `brew install sshfs`

Thanks, now it's works!

**Comment by PhilETaylor** [comment]
This no longer works, 

`brew install sshfs`

as it gives error

`Error: sshfs has been disabled because it requires closed-source macFUSE!`

**Comment by WayneChang65** [comment]
> This no longer works,
> 
> `brew install sshfs`
> 
> as it gives error
> 
> `Error: sshfs has been disabled because it requires closed-source macFUSE!`

Ref here. It works for me.

https://github.com/telepresenceio/telepresence/issues/1654#issuecomment-873538291
