### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by scjane** [docker/docker.github.io#8712]
File: [registry/configuration.md](https://docs.docker.com/registry/configuration/)
When I click "Edit this page", it displays "Page not found", as shown in the following figure.
![04251](https://user-images.githubusercontent.com/25146885/56706523-e000d280-6747-11e9-8fd6-f23da5ef4322.jpg)

**Comment by BlaM** [comment]
Also https://github.com/docker/docker.github.io/blob/master/registry/deploying.md links to configuration.md which simply isn't there.

**Comment by traci-morrison** [comment]
This issue appears to be resolved. Please open a new issue if the problem persists. Thank you.
