### ISSUE TITLE
Doc Containers do not launch. 

### ISSUE THREAD

**Issue by Andr3sC** [docker/docker.github.io#8751]
File: [docsarchive.md](https://docs.docker.com/docsarchive/)

The command provided to launch the doc Container does not seem to work,  It seems you have to launch nginx manually. So the command goes like this...

`docker run -dit -p 4001:4000 docs/docker.github.io:latest nginx -g 'daemon off;'`

instead of

`docker run -ti -p 4000:4000 docs/docker.github.io:latest`

It looks like entryPoint/Cmd is not correctly set on image.

**Comment by craig-osterhout** [comment]
This issue has been resolved in newer images.
