### ISSUE TITLE
Docker engine diagram on Docker Overview page is inverted/confusing

### ISSUE THREAD

**Issue by rwalle61** [docker/docker.github.io#8757]
File: [engine/docker-overview.md](https://docs.docker.com/engine/docker-overview/)

On this page, the image https://docs.docker.com/engine/images/engine-components-flow.png suggests (to newbs like me) that *containers* manage the client docker CLI (, which manages the REST API, which manages the docker daemon). I had to read the description and work out that actually the daemon is the user's point of control. 

I think it'd be clearer if the daemon were at the top of the picture. Also, having the daemon light-coloured, and the other things progressively darker, would be most intuitive.

**Comment by thaJeztah** [comment]
Hm, yes that diagram is rather confusing, we should replace that

**Comment by craig-osterhout** [comment]
Closing as it appears that the image no longer appears in any current topic, although it's still in the source.
