### ISSUE TITLE
docker/ucp version clarification

### ISSUE THREAD

**Issue by daywalked** [docker/docker.github.io#8784]
Clarification if it matters the docker/ucp:{version}, if it needs to match the existing UCP, if to match the target upgrade, or so on.
File: [reference/ucp/3.1/cli/upgrade.md](https://docs.docker.com/reference/ucp/3.1/cli/upgrade/)

**Comment by traci-morrison** [comment]
Thank you for your feedback. There doesn't seem to be enough details in the issue for us to work on. If this really is a documentation issue and I have misunderstood, please reopen it with more information.

**Comment by daywalked** [comment]
> Thank you for your feedback. There doesn't seem to be enough details in the issue for us to work on. If this really is a documentation issue and I have misunderstood, please reopen it with more information.

Well, since the page looks deleted/moved, sure, 'solved'!
