### ISSUE TITLE
Sorry, we can't find that page

### ISSUE THREAD

**Issue by MuhammadUmarFarooq786** [docker/docker.github.io#8785]
### Problem description

When I tried to navigate to  https://docs.docker.com/engine/examples/mongodb/
It gave me following error. If the requested page is moved to another location then link to that location should be given in this error page.
Regards

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. If you found the link in the Docker documentation, please let us know the source. That page currently no longer exists, so there is no other location to redirect to.
