### ISSUE TITLE
Minor Windows permissions clarification

### ISSUE THREAD

**Issue by mossywell** [docker/docker.github.io#8786]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)
"you need to run the following as administrator or else you don’t have the permission to create hyperv VMs!"
Should say: "you need to run the following as either a local administrator or a member of the 'Hyper-V Administrators' local group or else you don’t have the permission to create hyperv VMs!"
(Rationale: Not everyone runs as a local admin.)

**Comment by DawnWood-Docker** [comment]
Hi @mossywell Thanks for the feedback!! Also saw your other comments so this boilerplate may not be helpful to you. :) Adding it anyway, in case someone else finds it useful. 

We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
