### ISSUE TITLE
Error in the screenshot

### ISSUE THREAD

**Issue by mossywell** [docker/docker.github.io#8788]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)
The screenshot of the browser testing connectivity to the swarm should show port 4000 (or the accompanying text).

**Comment by DawnWood-Docker** [comment]
Hi @mossywell Thanks for the feedback!! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
