### ISSUE TITLE
Typo "conatiner" in reference architecture article

### ISSUE THREAD

**Issue by ddimtirov** [docker/docker.github.io#8791]
### Problem description

The networking architecture article contains the typo `conatiner` instead of `container`

### Problem location

- I saw a problem on the following URL: https://success.docker.com/article/networking

### Suggestions for a fix

Apart from fixing the typo, you may want to add a commit hook looking for `conatiner` - a quick [GitHub search](https://github.com/search?q=org%3Adocker+conatiner&unscoped_q=conatiner) shows 14 commits and 25 issues

**Comment by traci-morrison** [comment]
This issue is resolved. If the problem persists, please open a new issue. Thank you.
