### ISSUE TITLE
https://registry.docker-cn.com is down

### ISSUE THREAD

**Issue by khs1994** [docker/docker.github.io#8793]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/registry/recipes/mirror/#use-case-the-china-registry-mirror

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by XhstormR** [comment]
Yes, I have the same problem：
```
C:\Users\XhstormR>curl -ik https://registry.docker-cn.com
curl: (7) Failed to connect to registry.docker-cn.com port 443: Timed out
```

BTW, it seems that Docker does not intend to provide services in China.
```
C:\Users\XhstormR>curl -ik https://www.docker-cn.com
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://www.docker.com/
```

**Comment by khs1994** [comment]
a765e84efccb4ff028e8a6b79a02bff53f1dd949
