### ISSUE TITLE
Interlock documentation has a dead link

### ISSUE THREAD

**Issue by mikedbrook** [docker/docker.github.io#8797]
### Problem description

Reading through the interlock documentation the link below is dead

### Problem location

https://docs.docker.com/ee/ucp/interlock/usage.index/

### Suggestions for a fix

update the link https://docs.docker.com/ee/ucp/interlock/usage.index/ with the correct page

**Comment by bermudezmt** [comment]
Addressed by #8798 . Thanks for reporting the issue, @mikedbrook .

Thank you for fixing, @paigehargrave .
