### ISSUE TITLE
Interlock documentation contains a dead link

### ISSUE THREAD

**Issue by mikedbrook** [docker/docker.github.io#8802]
### Problem description

While running rough the documentation on configuring interlock, the link for HA Proxy is a dead link

https://docs.docker.com/ee/ucp/interlock/config/

On this page is the following section 

Proxy
Options are made available to the extensions, and the extensions utilize the options needed for proxy service configuration. This provides overrides to the extension configuration.
Because Interlock passes the extension configuration directly to the extension, each extension has different configuration options available. Refer to the documentation for each extension for supported options:
Nginx
HAproxy 

### Problem location
HAproxy is a hyperlink that returns sorry we can't find that page

https://docs.docker.com/ee/ucp/interlock/config/haproxy-config/

### Suggestions for a fix

fix the HAproxy link https://docs.docker.com/ee/ucp/interlock/config/haproxy-config/ on the https://docs.docker.com/ee/ucp/interlock/config/ page

**Comment by ollypom** [comment]
@mikedbrook Thanks for reporting :) It looks like as part of https://github.com/docker/docker.github.io/pull/8722, the HA Proxy config was removed but that link was missed. Cleaned up in https://github.com/docker/docker.github.io/pull/8803 so will close the issue when that gets merged.
