### ISSUE TITLE
NAT/IP configuration troubleshooting links broken

### ISSUE THREAD

**Issue by zappy-shu** [docker/docker.github.io#8808]
### Problem description

The "Network" and "Settings" links in the NAT/IP configuration section of the Docker Desktop for Windows Logs and troubleshooting page don't go anywhere.

### Problem location

- I saw a problem on the following URL: NAT/IP configuration

### Suggestions for a fix

By the wording those links should be going to a separate page that describes the settings rather then sub-sections of the troubleshooting guide. I don't know where that page is though.

**Comment by aevesdocker** [comment]
Closing issue as it refers to content that no longer exists.
