### ISSUE TITLE
Title is misleading

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#8811]
File: [ee/ucp/admin/install/upgrade.md](https://docs.docker.com/ee/ucp/admin/install/upgrade/)

The title is "Upgrade to UCP 3.1"

There should be general "Upgrade UCP" documentation less specific to versions with best practices etc. For instance, if a customer is already on a 3.1.x version, where do they look for upgrade best practices?

**Comment by traci-morrison** [comment]
@kavikat Thank you for your feedback. Each version of UCP has it's own version of documentation. We include general upgrade information here: https://docs.docker.com/ee/ucp/admin/install/upgrade/#upgrade-ucp

I will close this issue for now. If this really is a documentation issue and I have misunderstood, please reopen it with more information.
