### ISSUE TITLE
Stop making people turn around for a download link

### ISSUE THREAD

**Issue by lovoni** [docker/docker.github.io#8814]
File: [toolbox/toolbox_install_windows.md](https://docs.docker.com/toolbox/toolbox_install_windows/)

PLEASE, PLEASE, just simply and clearly put the link to download the toolbox on this page. We understood it's legacy and you are promoting Docker Desktop For Windows and may not support toolbox. But my system doesn't meet the requirements. Do you want me to upgrade it right now?
Stop making people turn around and wast time for a simple download link.
This is really ennoying.

Cheers

**Comment by paigehargrave** [comment]
@guillaumerose @chris-crone @seemethere - FYI.

**Comment by usha-mandya** [comment]
Hi @lovoni, thanks for your feedback on the download URL. Please note that Docker no longer maintains the download.docker.com URL for Docker Toolbox. You can download the latest version of Docker Toolbox from https://github.com/docker/toolbox/releases. 

Docker Toolbox documentation has been updated to reflect this change. For more information, see:

- https://github.com/docker/docker.github.io/pull/8969/
- https://docs.docker.com/toolbox/overview/

Closing this issue.
