### ISSUE TITLE
Creating the External virtual switch in Hyper-V manager kills your network speed.

### ISSUE THREAD

**Issue by davyvanlaere** [docker/docker.github.io#8817]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

This article lets the user create an external virtual switch. Doing so on a current windows version (may 2019) will kill your machines network speed (speed test reported 0.1Mbps instead of the usual 100Mbps).I am no HyperV expert, but if i understood correctly, this step became unneccesary. I used "Default Switch" and was able to successfully finish the tutorial.

**Comment by DawnWood-Docker** [comment]
Hi @davyvanlaere Thank you for the feedback! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
