### ISSUE TITLE
Needs punc: COMMAND should be an executable, a chained or a quoted command will not work.

### ISSUE THREAD

**Issue by petjal** [docker/docker.github.io#8820]
File: [engine/reference/commandline/exec.md](https://docs.docker.com/engine/reference/commandline/exec/)

I think this line needs some punctuation:
COMMAND should be an executable, a chained or a quoted command will not work.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
