### ISSUE TITLE
Need new terminal?: Next, set an environment variable in the current bash session.

### ISSUE THREAD

**Issue by petjal** [docker/docker.github.io#8821]
File: [engine/reference/commandline/exec.md](https://docs.docker.com/engine/reference/commandline/exec/)

It's not clear that this command should be run in a separate terminal, I think:

**Next, set an environment variable in the current bash session.**
**$ docker exec -it -e VAR=1 ubuntu_bash bash**

because the prior command

**Next, execute an interactive bash shell on the container.**
**$ docker exec -it ubuntu_bash bash**

drops you into that interactive shell?  Or, the user should exit that interactive shell with, well, "exit".

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
