### ISSUE TITLE
Describe what are valid identifiers in a variable

### ISSUE THREAD

**Issue by rcjsuen** [docker/docker.github.io#8835]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

> Environment variables are notated in the `Dockerfile` either with `$variable_name` or `${variable_name}`. They are treated equivalently and the brace syntax is typically used to address issues with variable names with no whitespace, like `${foo}_bar`.

From my experiments, it seems like a variable name includes alphanumeric characters and the underscore...? If this is correct, could this please be mentioned in the Dockerfile reference?

Thanks!

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue/discussion in the repo at https://github.com/docker/cli/tree/master/docs/reference

**Comment by rcjsuen** [comment]
I have opened https://github.com/docker/cli/issues/3642.
