### ISSUE TITLE
docker for windows guides are not updated for windows , it is mostly Linux based guide

### ISSUE THREAD

**Issue by devesh-bansal** [docker/docker.github.io#8838]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

https://docs.docker.com/docker-for-windows/?install_site=vsonwin

**Comment by traci-morrison** [comment]
Thank you for your feedback. There doesn't seem to be enough details in the issue for us to work on. If this really is a documentation issue and I have misunderstood, please reopen it with more information.
