### ISSUE TITLE
https://docs.docker.com/ee/ucp/interlock/deploy/

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#8843]
File: [ee/ucp/interlock/deploy/index.md](https://docs.docker.com/ee/ucp/interlock/deploy/)

"The ucp-interlock-extension generates a configuration to be used by the proxy service. By default the proxy service is NGINX, so this service generates a standard NGINX configuration. ****( Is this valid here????)**** UCP creates the com.docker.ucp.interlock.conf-1 configuration file and uses it to configure all the internal components of this service."

**Comment by paigehargrave** [comment]
@ehazlett - Can you PTAL at this? Thank you in advance!

**Comment by ehazlett** [comment]
Yes that looks like it was a docs comment and should be removed.

**Comment by paigehargrave** [comment]
@ehazlett Ah - thank you. At first glance, I thought it was a new question. I've removed it. :)
