### ISSUE TITLE
UCP load balancer sample configs do not handle port 6443

### ISSUE THREAD

**Issue by cflee** [docker/docker.github.io#8844]
### Problem description

Load balancer docs text mentions to configure load balancer to load-balance TCP traffic on port 443 and port 6443, but sample configs only cover port 443. Therefore, Kubernetes apiserver connections (as configured by UCP client bundle) will not work.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ee/ucp/admin/configure/join-nodes/use-a-load-balancer/

### Project version(s) affected

All versions since Kubernetes was introduced (since Enterprise 2.0+?)

### Suggestions for a fix

Adjust the three sample configs (NGINX, HAProxy, AWS LB) to handle both port 443 and 6443.

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
