### ISSUE TITLE
python 2.7 no longer maintained and requirements.txt error

### ISSUE THREAD

**Issue by IamKraZ** [docker/docker.github.io#8851]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

When i go to create the new image in the tutorial Python throws the error:

**_DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
The command '/bin/sh -c pip install --trusted-host pypi.python.org -r requirements.txt' returned a non-zero code: 1_**

and my test image is not created. Is there a work around? or am I doing it wrong, lol?

**Edit**
Also what is the  "none" file?

**_REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
"none"              "none"              d4e018f2c61b        12 seconds ago      120MB
python              2.7-slim            eb40dcfcbc42        2 weeks ago         120MB_**

I  attempted to create the Dockerfile 
**docker build -t friendlyhello .**
 
and got this:

**_Sending build context to Docker daemon   5.12kB
Step 1/7 : FROM python:2.7-slim
2.7-slim: Pulling from library/python
743f2d6c1f65: Already exists
9bfbedfce8de: Already exists
7f4da2474cef: Already exists
ffc893575679: Already exists
Digest: sha256:686bc67cbebf4c4fb0d96d55650d8704d00ccb6b9c6bdd0bee5fad48b827a6cb
Status: Downloaded newer image for python:2.7-slim
 ---> eb40dcfcbc42
Step 2/7 : WORKDIR /app
 ---> Running in 21b1d8621926
Removing intermediate container 21b1d8621926
 ---> c23711eb7762
Step 3/7 : COPY . /app
 ---> d4e018f2c61b
Step 4/7 : RUN pip install --trusted-host pypi.python.org -r requirements.txt
 ---> Running in 8a077703e81b
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
The command '/bin/sh -c pip install --trusted-host pypi.python.org -r requirements.txt' returned a non-zero code: 1_**

Tried it multiple times with the same results (yes insanity, lol).

**Comment by GersonHuang** [comment]
@IamKraZ below link may be the solution for your problem
[docker-compose error - unable to read file](https://stackoverflow.com/questions/30690435/docker-compose-error-unable-to-read-file)

**Comment by IamKraZ** [comment]
@GersonHuang thank you for the reply. I checked the link and think it is not the same as my issue, but will try it and see if it does work.

**Comment by jromerof** [comment]
@GersonHuang the problem with pip is because you are Copying all the files to the directory /app inside the container, so the requirements.txt is now inside /app/requirements.txt. To fix it you should write the RUN line like this `RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt` .
(I'm also doing the getting started part)

**Comment by IamKraZ** [comment]
Awesome thank you. This fixed my problem. Kuddos.

**Comment by DawnWood-Docker** [comment]
@IamKraZ sounds like you got around this. So glad!! @jromerof thanks for helping!!
We also just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to.
Love to hear your feedback on the updated guide.
