### ISSUE TITLE
As a publisher, I have not setup any payment account. How does money get to me if my commercial content gets purchased by customers?

### ISSUE THREAD

**Issue by gnomestar** [docker/docker.github.io#8863]
File: [docker-hub/publish/publisher_faq.md](https://docs.docker.com/docker-hub/publish/publisher_faq/)

This Question should be removed with the deprecation of Pay-via-Docker

**Comment by paigehargrave** [comment]
Included in https://github.com/docker/docker.github.io/pull/8880

**Comment by gnomestar** [comment]
Perfect, thank you!
