### ISSUE TITLE
Customize the default proxy service example: Add HTTPS default

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#8865]
File: [ee/ucp/interlock/config/index.md](https://docs.docker.com/ee/ucp/interlock/config/)

It would be helpful to give an example on how to setup a default HTTPS page in addition to the default HTTP page.

**Comment by paigehargrave** [comment]
@euanh @ehazlett Can you PTAL at this - thank you in advance!

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
