### ISSUE TITLE
https://docs.docker.com/ee/ucp/interlock/

### ISSUE THREAD

**Issue by martencassel** [docker/docker.github.io#8866]
File: [ee/ucp/interlock/index.md](https://docs.docker.com/ee/ucp/interlock/)

If you do the examples in these sections one after the other, you run in to the issue that in the examples the token demo or demo-network is used in many of the examples (In the docker-compose.yml or in the docker service create examples). 

It might be better to name these to unique things that are related to the example in the actual section.

**Comment by paigehargrave** [comment]
@ehazlett @euanh  - Can I enlist your help with this (to ensure I don't introduce errors)? Thank you in advance!

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
