### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by dasjet** [docker/docker.github.io#8874]
### Problem description

Page not found

### Problem location

- I found this link on the following URL: https://docs.docker.com/datacenter/ucp/1.1/installation/system-requirements/

- I saw a problem on the following URL: https://docs.docker.com/cs-engine/install/

**Comment by paigehargrave** [comment]
@bermudezmt - PTAL (link was updated).

**Comment by traci-morrison** [comment]
This issue was resolved via https://github.com/docker/docker.github.io/pull/8898. The link now points to https://docs.docker.com/install/.
