### ISSUE TITLE
Fedora repo link fail to sync

### ISSUE THREAD

**Issue by 404NotFoundv2** [docker/docker.github.io#8883]
### Problem description

Following the installation on https://docs.docker.com/install/linux/docker-ce/fedora/, the repo link for Fedora (30) doesn't sync.

`$ sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo`
```
$ sudo dnf install docker-ce docker-ce-cli containerd.io

Fedora Modular 30 - x86_64                                40 kB/s |  25 kB     00:00    
Fedora Modular 30 - x86_64 - Updates                      33 kB/s |  24 kB     00:00    
Fedora 30 - x86_64 - Updates                              39 kB/s |  23 kB     00:00    
Fedora 30 - x86_64                                        43 kB/s |  25 kB     00:00  
Failed to synchronize cache for repo 'docker-ce-stable'
Ignoring repositories: docker-ce-stable
No match for argument: docker-ce
No match for argument: docker-ce-cli
No match for argument: containerd.io
Error: Unable to find a match
```

I saw that currently it only supports Fedora versions 28 & 29, but since 30 is the latest, I was expecting it to work.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/install/linux/docker-ce/fedora

**Comment by TurinTuramba** [comment]
Hi Jasper,
i encountered the same problem this morning.
At this location https://download.docker.com/linux/fedora/30/x86_64/ You'll see there is no `stable` version, as of 2019-06-03T12:00:00GMT.
So my work around, up to a stable release, is to use the nightly build 
```bash
sudo dnf config-manager --set-enabled docker-ce-nightly
```
this works for me.
regards
Roland

**Comment by 404NotFoundv2** [comment]
Hi Roland,

Thanks! This works for me as well! :+1:

**Comment by thaJeztah** [comment]
Closing because Fedora 30 is not yet in the list of packages that's shipping for the current release; https://docs.docker.com/install/linux/docker-ce/fedora/#os-requirements
