### ISSUE TITLE
proposal: Add option to pull base images

### ISSUE THREAD

**Issue by larroy** [docker/docker.github.io#8886]
### Problem description

When using a base image and --cache-from to avoid rebuilding containers in CI environments for example, if the base image used in the dockerfile is stale, it triggers a rebuild of the container. This is not the case when the base images are pulled.

Ideally there would be a way to pull a container and it's base images so they are all updated.

For example, see the use of --cache-from in our CI for MXNet here:

http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-cpu/branches/master/runs/707/nodes/49/steps/176/log/?start=0

### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

See above.

**Comment by traci-morrison** [comment]
Thank you for your feedback. This seems to be a feature request or a fundamental change in the way Docker works, but this GitHub repository is only for Docker documentation. Please file an issue in https://github.com/docker/ instead.
