### ISSUE TITLE
download link missing

### ISSUE THREAD

**Issue by tosho-ait** [docker/docker.github.io#8890]
File: [toolbox/index.md](https://docs.docker.com/toolbox/)

download link for the docker toolbox is missing from the page.

**Comment by thaJeztah** [comment]
the download link looks to be on https://docs.docker.com/toolbox/toolbox_install_mac/

Which is linked from the page you mentioned

**Comment by Softyy** [comment]
The windows installer is missing on this page.

https://docs.docker.com/toolbox/toolbox_install_windows/

**Comment by usha-mandya** [comment]
Hi @tosho-ait, thanks for your feedback on the download URL. Please note that Docker no longer maintains the download.docker.com URL for Docker Toolbox. You can download the latest version of Docker Toolbox from https://github.com/docker/toolbox/releases. 

Docker Toolbox documentation has been updated to reflect this change. For more information, see:

- https://github.com/docker/docker.github.io/pull/8969/
- https://docs.docker.com/toolbox/overview/

Closing this issue.
