### ISSUE TITLE
Conflicting information about the defaults for the local log driver

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#8896]
File: [config/containers/logging/local.md](https://docs.docker.com/config/containers/logging/local/)

In the 2nd paragraph on the page, it mentions this for `max-size`:

> By default the local driver preserves 100MB of log messages per container and uses automatic compression to reduce the size on disk.

In the table for `max-size`, it mentions:
> Defaults to 20m

Also, I am curious if, because there is a default, that this is true about the `max-file` option or not:
> Only effective when max-size is also set.

Also in testing the example I wasn't sure if the example was assuming that you had previously set the log-driver setting at the daemon level or not.  If not:
```
$ docker run -it --log-opt max-size=10m --log-opt max-file=3 alpine ash
```

Inspect the container
```
$ docker inspect 2b --format '{{json .HostConfig.LogConfig}}'
{"Type":"json-file","Config":{"max-file":"3","max-size":"10m"}}
```

If it is meant to be explicitly specifying the driver at the run command instead of assuming that it is being done at the daemon:
```
$ docker run -it --log-driver local --log-opt max-size=10m --log-opt max-file=3 alpine ash
```

```
$ docker inspect 7a4343ede05c --format '{{json .HostConfig.LogConfig}}'
{"Type":"local","Config":{"max-file":"3","max-size":"10m"}}
```

**Comment by paigehargrave** [comment]
@anusha-ragunathan @ddebroy Can you PTAL at this and confirm what is correct for the docs? Thank you!

**Comment by anusha-ragunathan** [comment]
@mbentley : Regarding max-size:

-  max-size is `100M or 20M?`
The default size for each file is 20M. 
The default count for number of such files (to account for log rotation) is 5.
So the total size of preserved logs by default is 100M.

- `Also, I am curious if, because there is a default, that this is true about the max-file option or not:`
You are correct. The bit about `Only effective when max-size is also set.` should be removed.

**Comment by anusha-ragunathan** [comment]
Regarding the example:
I agree that the example should be explicit in setting the log-driver for `docker run`

So
`$ docker run -it --log-opt max-size=10m --log-opt max-file=3 alpine ash`

should be changed to
`$ docker run -it --log-driver local --log-opt max-size=10m --log-opt max-file=3 alpine ash`

**Comment by paigehargrave** [comment]
@anusha-ragunathan Many thanks for your time and help here! I've made updates in #8905 . @mbentley PTAL - thank you!

**Comment by mbentley** [comment]
👍 looks awesome and thank you for the rapid response & fix as always!

**Comment by paigehargrave** [comment]
@mbentley @anusha-ragunathan Thank you both for the help!
