### ISSUE TITLE
Interlock docs missing some configuration options

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#8901]
File: [ee/ucp/interlock/usage/labels-reference.md](https://docs.docker.com/ee/ucp/interlock/usage/labels-reference/)

Looks like some references are missing:

Table taken from the Interlock repo `docs/config/service_labels.md`

| Label | Description | Example |
| --- | --- | --- |
| `com.docker.lb.hosts` | Comma separated list of the hosts that the service should serve | `example.com,test.com` |
| `com.docker.lb.port` | Port to use for internal upstream communication | `8080` |
| `com.docker.lb.network` | Name of network the proxy service should attach to for upstream connectivity | `app-network-a` |
| `com.docker.lb.context_root` | Context or path to use for the application | `/app` |
| `com.docker.lb.context_root_rewrite` | Boolean to enable rewrite for the context root | `true` |
| `com.docker.lb.ssl_only` | Boolean to force SSL for application | `true` |
| `com.docker.lb.ssl_cert` | Docker secret to use for the SSL certificate | `example.com.cert` |
| `com.docker.lb.ssl_key` | Docker secret to use for the SSL key | `example.com.key` |
| `com.docker.lb.websocket_endpoints` | Comma separated list of endpoints to configure to be upgraded for websockets | `/ws,/foo` |
| `com.docker.lb.service_cluster` | Name of the service cluster to use for the application | `us-east` |
| `com.docker.lb.ssl_backend` | Enable SSL communication to the upstreams | `true` |
| `com.docker.lb.ssl_backend_tls_verify` | Verification mode for the upstream TLS | `none` |
| `com.docker.lb.sticky_session_cookie` | Cookie to use for sticky sessions | `none` |
| `com.docker.lb.redirects` | Semi-colon separated list of redirects to add in the format of `<source>,<target>`.  Example: (`http://old.example.com,http://new.example.com;`) | `none` |
| `com.docker.lb.ssl_passthrough` | Enable SSL passthrough | `false` |
| `com.docker.lb.backend_mode` | Select the backend mode that the proxy should use to access the upstreams. Defaults to `task`. | `vip` |

**Comment by mbentley** [comment]
Oh hmm, actually the setting that I was specifically looking for, `com.docker.lb.ssl_only`, appears to not be supported and that documentation I was referring to is inaccurate.

**Comment by paigehargrave** [comment]
@mbentley Hi Matt - I believe what you are looking for is here: https://docs.docker.com/ee/ucp/interlock/config/service-labels/.

**Comment by mbentley** [comment]
Hmm, the two pages are confusing:
https://docs.docker.com/ee/ucp/interlock/usage/labels-reference/
vs
https://docs.docker.com/ee/ucp/interlock/config/service-labels/

It's like it is the same content, different versions.

**Comment by paigehargrave** [comment]
Yikes! You are right! Where is the better place from the user's point of view? 'Usage' or 'Config'? Are there other options that should be removed or added?

**Comment by mbentley** [comment]
I always looked at config as where I would go to setup Interlock itself and then under "Routing traffic to services", I am looking from the application perspective but I've just trained myself to go under that section at this point :D

**Comment by paigehargrave** [comment]
OK - I'll leave it under "Routing traffic to services" and remove it from the other location. Is there any other information that needs fixing (besides that one option)?

**Comment by paigehargrave** [comment]
@mbentley - Looks like these options are in conflict - I have removed them - please let me know if I'm making a mistake. :)

| `com.docker.lb.ssl_backend` | Enable SSL communication to the upstreams | `true` |
| `com.docker.lb.ssl_backend_tls_verify` | Verification mode for the upstream TLS | `none` |

**Comment by mbentley** [comment]
Yeah, so it looks like there are 3 options that differ just based off of a count.  Unfortunately I am not certain which ones apply to a given version of Interlock (e.g. - if those options are included in the latest 3.1.7 version of Interlock or not.  @euanh - could you take a look to see which options are actually the correct ones?

**Comment by paigehargrave** [comment]
https://github.com/docker/docker.github.io/pull/8902

**Comment by paigehargrave** [comment]
@euanh A total of three options were removed - thank you in advance for your help!

**Comment by paigehargrave** [comment]
Closing per #8902 @mbentley and @euanh Thank you!
