### ISSUE TITLE
Docker Docs - 'Docker Hub' -  'Automated Builds' - 'Testing in Automated Builds' -- 'any Docker Hub repository' broken link

### ISSUE THREAD

**Issue by varunaiah** [docker/docker.github.io#8915]
Steps Reproduce:
Go to: `https://docs.docker.com/docker-hub/builds/automated-testing/`
Click on 'any Docker Hub repository' hyperlink

Expected: User should navigate to corresponding page

Actual:
`File: [404.md](https://docs.docker.com/404.html)`

**Comment by craig-osterhout** [comment]
The link now directs to https://docs.docker.com/docker-hub/repos/
