### ISSUE TITLE
Clarification on  --native-ssh

### ISSUE THREAD

**Issue by ChandlerSwift** [docker/docker.github.io#8918]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

The section on `--native-ssh` says that "Docker Machine has the option to let you use your own system’s SSH...", which seems to contradict the [documentation on the `--native-ssh` flag](https://docs.docker.com/machine/reference/ssh/#different-types-of-ssh), which says that the flag means the Go library's SSH client is used rather then the binary on the system. Am I reading this correctly?

If that's the case, it might be more clear to change this to something more similar to what's in the docs on the flag, possibly something like "Docker attempts to use the system's SSH binary if it is found, and falls back to a native Go implementation otherwise. To force the native Go implementation to be used, you can use the `--native-ssh` flag." If that makes sense, I can create a pull request to that effect.

**Comment by DawnWood-Docker** [comment]
Hi @ChandlerSwift Thank you for the feedback. We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the machine steps that you allude to. :)
Love to hear your feedback on the updated guide.
