### ISSUE TITLE
Powershell to download client bundle needs to be updated

### ISSUE THREAD

**Issue by Akulshr** [docker/docker.github.io#8922]
File: [ee/ucp/user-access/cli.md](https://docs.docker.com/ee/ucp/user-access/cli/)

I tried the powershell that is mentioned currently on docs for downloading client bundle. I ran that successfully but it actually didn't download zip file.

Below is the command that does downloaded client bundle zip file.

$AUTHTOKEN=((Invoke-WebRequest -Body '{"username":"<username>", "password":"<password>"}' -Uri https://<ucp-url or IP>/auth/login -Method POST).Content)|ConvertFrom-Json|select auth_token -ExpandProperty auth_token

Invoke-WebRequest -Uri https://<ucp-urel or IP>/api/clientbundle -Headers @{"Authorization"="Bearer $AUTHTOKEN"} -OutFile bundle.zip

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
