### ISSUE TITLE
Changes to Microsoft Windows Server Installation instructions due to PSCX installation

### ISSUE THREAD

**Issue by stonesbg** [docker/docker.github.io#8927]
### Problem description

I came across and issue where on of the Windows Server 2016 machines had PSCX installed and there looks to be a bug in that is you have PSCX installed it will use that version of the Extract-Archive.  If you run it you will get the error:

Install-Package : A parameter cannot be found that matches parameter name 'DestinationPath'. At line:1 char:1 + Install-Package -Name docker -ProviderName DockerMsftProvider -Verbos ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception + FullyQualifiedErrorId : FailedToDownload,Install-Package,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

The solution that I used was to use the instructions "Use a script to install Docker EE"

### Problem location

On this [page](https://docs.docker.com/install/windows/docker-ee/) under "Use a script to install Docker EE" I had to change the command on the "# Extract the archive" to use 

Expand-Archive docker-18.09.6.zip -DestinationPath $Env:ProgramFiles -Force

TO:

Microsoft.PowerShell.Archive\Expand-Archive docker-18.09.6.zip -DestinationPath $Env:ProgramFiles -Force

### Project version(s) affected

All Versions

### Suggestions for a fix

Expand-Archive docker-18.09.6.zip -DestinationPath $Env:ProgramFiles -Force

TO:

Microsoft.PowerShell.Archive\Expand-Archive docker-18.09.6.zip -DestinationPath $Env:ProgramFiles -Force

**Comment by usha-mandya** [comment]
Closing this issue. Please see https://github.com/docker/docker.github.io/pull/8929 for details.
