### ISSUE TITLE
Mongo container isn't right

### ISSUE THREAD

**Issue by XDavidT** [docker/docker.github.io#8931]
File: [_samples/library/mongo/index.md](https://docs.docker.com/samples/library/mongo/)
Need to change mongo:tag to mongo

**Comment by thaJeztah** [comment]
The `samples` are taken from the upstream documentation from Docker Hub;

<img width="874" alt="Screenshot 2019-06-12 at 13 24 16" src="https://user-images.githubusercontent.com/1804568/59347687-89f6e700-8d15-11e9-818b-b76b1b8f4985.png">

Looking at that example, I think `:tag` is intended as a placeholder for "the tag/version of MongoDB you want to deploy".

Having said that; if you think this could be improved, please open a ticket in the upstream repository where this content is fetched from; https://github.com/docker-library/docs/tree/master/mongo/

I'll close the ticket here, but feel free to continue the conversation
