### ISSUE TITLE
Include image of files to make Dockerfile type clear

### ISSUE THREAD

**Issue by participator** [docker/docker.github.io#8933]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/)

This image or a similar image would be helpful in showing that a Dockerfile does not have an extension (like .git files).

![image](https://user-images.githubusercontent.com/7463405/59392776-bdde0680-8d2d-11e9-8daf-9ad4333a84c3.png)

**Comment by DawnWood-Docker** [comment]
Hi @participator Thanks for the feedback! We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the steps that you allude to above. 
Love to hear your feedback on the updated guide.
