### ISSUE TITLE
Troubleshooting 

### ISSUE THREAD

**Issue by InterceptorF** [docker/docker.github.io#8944]
File: [get-started/index.md](https://docs.docker.com/get-started/)

 When Docker doesn't start it crushes our systems. There should be troubleshooting steps on teh Website.

**Comment by DawnWood-Docker** [comment]
Hi @InterceptorF So sorry that you're having issues. We just updated the whole [Get Started](https://docs.docker.com/get-started/) guide to align with current best practices. As a bonus, we also removed the broken steps that you allude to. Appreciate your request for troubleshooting content. In the meantime, consider posting your questions/problems on our [forums](https://forums.docker.com/) if you are still unable to use Docker.
