### ISSUE TITLE
Docs point reader in a loop

### ISSUE THREAD

**Issue by david-mears** [docker/docker.github.io#8961]
This file [toolbox/toolbox_install_windows.md](https://docs.docker.com/toolbox/toolbox_install_windows/) points users to "Go to the Docker Toolbox page" to "click the installer link"; but the Docker Toolbox page points users back here: "See [...] Install Docker Toolbox on Windows for download and install instructions."

I had to go to Intel's page to find an install link: https://software.intel.com/en-us/intel-system-studio-docker-install-windows-install-docker-toolbox

**Comment by usha-mandya** [comment]
Hi @david-mears, thanks for your feedback on the download URL. Please note that Docker no longer maintains the download.docker.com URL for Docker Toolbox. You can download the latest version of Docker Toolbox from https://github.com/docker/toolbox/releases. 

Docker Toolbox documentation has been updated to reflect this change. For more information, see:

- https://github.com/docker/docker.github.io/pull/8969/
- https://docs.docker.com/toolbox/overview/

Closing this issue.
