### ISSUE TITLE
use emergency-repair command 

### ISSUE THREAD

**Issue by homiak** [docker/docker.github.io#8966]
File: [reference/dtr/2.6/cli/restore.md](https://docs.docker.com/reference/dtr/2.6/cli/restore/)

**Comment by homiak** [comment]
Use emergency repair command instead of this command because this refers to restore which is not correct

**Comment by ollypom** [comment]
Thank you for your feedback. Do you mind providing a bit more context? The `restore` and `emergency-repair` commands serve different purposes :)

**Comment by homiak** [comment]
My apologies, I thought that text highlight when creating the issue is copied over to that issue, but I see this is not the case. 
The issue is here 

There are three steps you can take to recover an unhealthy DTR cluster:

If the majority of replicas are healthy, remove the unhealthy nodes from the cluster, and join new nodes for high availability.
If the majority of replicas are unhealthy, use this command to revert your cluster to a single DTR replica.
If you can’t repair your cluster to a single replica, you’ll have to restore from an existing backup, using the restore command.

In particular in this paragraph:

If the majority of replicas are unhealthy, use this command to revert your cluster to a single DTR replica.

"use this" refers to restore command, but this is not correct. As far as I understand this should refer to "emergency repair" not the restore.

**Comment by ollypom** [comment]
Ah ok, thanks for the context. Updated in https://github.com/docker/docker.github.io/pull/8971.
