### ISSUE TITLE
Docker Compose : Instructions for Raspberry Pi [Raspbian GNU/Linux 9.9 (stretch)] installation.

### ISSUE THREAD

**Issue by Tas-sos** [docker/docker.github.io#8968]
The instructions in the file: [compose/install.md](https://docs.docker.com/compose/install/) can not be applied to **Raspbian GNU/Linux 9.9 (stretch)**, because mention to execute the following command (_in order to download the docker compose_) :
```sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose```
> * Where this will mean in the Raspberry Pi :
> github.com/docker/compose/releases/download/1.24.0/docker-compose-**Linux**-**armv7l**
 
But [I don't see any package](https://github.com/docker/compose/releases/tag/1.24.0) for the Raspberry microprocessor architecture.
Docker Compose **doesn't** support this architectures or there is an alternative with which we can approach the issue ?

Thank you.

**Comment by ollypom** [comment]
Thanks for the feedback, however this is not an issue with Docs. 

Do you mind moving your conversation to the compose repo https://github.com/docker/compose. Additionally you may find this useful https://github.com/docker/compose/issues/6188#issuecomment-421185249.
