### ISSUE TITLE
Documentation implies --icc=false by default

### ISSUE THREAD

**Issue by tammersaleh** [docker/docker.github.io#8973]
### Problem description

The first bullet in [Differences between user-defined bridges and the default bridge](https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge) ("User-defined bridges provide better isolation and interoperability between containerized applications") is incorrect or misleading.

It says that two containers on the default bridge network cannot talk to each other unless their ports are explicitly exposed via `-p` or `-P`.  However, [the inter-container communication](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/container-communication/#communication-between-containers) document says that `--icc=true` is set by default, allowing such communication.  My testing confirms this:

##### The Dockerfile:

``` dockerfile
FROM python:3.7.3
RUN pip3 install flask==1.0.2
WORKDIR /app
COPY app.py .
EXPOSE 8000
ENV PORT=8000
CMD ["./app.py"]
```

#### The commands:

``` console
$ docker network ls --filter=driver=bridge
NETWORK ID    NAME   DRIVER   SCOPE
3761c22399bc  bridge bridge   local

$ docker build -qt app .
sha256:e12465b379ec...

$ docker run -d --name app app
ec3cd0fc4cd62d0d774...
```

(note the lack of `-p` or `-P` above)

``` console
$ docker inspect app | grep IPAddress
"IPAddress": "172.17.0.2",

$ docker run superorbital/bash curl -s 172.17.0.2:8000
{"hello":"world"}
```

**Comment by Maximization** [comment]
This issue can be closed now as the bullet point has been removed by https://github.com/docker/docker.github.io/pull/10320. Not sure why Github didn't auto-close on merge

**Comment by usha-mandya** [comment]
Closing this issue. Thank you @Maximization!
