### ISSUE TITLE
Unable to install docker on Operating System: SUSE Linux Enterprise Server 12 SP3

### ISSUE THREAD

**Issue by venkateshilango7** [docker/docker.github.io#8981]
### Problem description
Unable to access a link https://docs.docker.com/engine/installation/linux/SUSE/

**Comment by venkateshilango7** [comment]
![image](https://user-images.githubusercontent.com/9502407/60048731-a550e300-9681-11e9-8d2c-3cca87209d4c.png)

**Comment by ollypom** [comment]
Hey @venkateshilango7, I'm not sure where you received that URL from however the correct page is https://docs.docker.com/install/linux/docker-ee/suse/. 

I've added a redirect from that URL back to there in https://github.com/docker/docker.github.io/pull/8983
