### ISSUE TITLE
Confusing use of both storage-opts and storage-opt

### ISSUE THREAD

**Issue by monoburn** [docker/docker.github.io#8985]
A couple of pages contain both 'storage-opts' and 'storage-opt'. Are both correct?  Anyway, it's confusing to see both spellings since there's no doc on they being aliases of each other.

File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/) and
[storage/storagedriver/device-mapper-driver.md](https://docs.docker.com/storage/storagedriver/device-mapper-driver/)

Kind regards
Erik S

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The content is maintained in an upstream repo. 
My interpretation is that storage-opts is a key in files and storage-opt is a flag in the CLI. If that sounds wrong or you'd like to get an answer from the source, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
