### ISSUE TITLE
Feedback for: registry/configuration.md

### ISSUE THREAD

**Issue by jnials** [docker/docker.github.io#899]
File: [registry/configuration.md](https://docs.docker.com/registry/configuration/)

Good grief.  Please fix the formatting.  Half of the entries are illegible.

**Comment by joaofnfernandes** [comment]
We're going to fix it, in the mean time you can read it from the source
https://github.com/docker/distribution/blob/release/2.5/docs/configuration.md

**Comment by sanscontext** [comment]
Fixed in https://github.com/docker/distribution/pull/2116
