### ISSUE TITLE
10.10.3 Yosemite

### ISSUE THREAD

**Issue by knod** [docker/docker.github.io#8991]
File: [toolbox/toolbox_install_mac.md](https://docs.docker.com/toolbox/toolbox_install_mac/)

'If you have macOS 10.10.3 Yosemite or newer, consider using Docker for Mac instead' - I'm on 10.11 and docker said the version of Mac was too old when I tried to use it.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the toolbox has been deprecated, it is no longer an issue in the documentation.
If you have an intel chip, the requirements for the latest version are 10.15. You can find the information at https://docs.docker.com/desktop/mac/install/
