### ISSUE TITLE
unable to find the page-- broken link

### ISSUE THREAD

**Issue by thanusivan** [docker/docker.github.io#8994]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by ollypom** [comment]
Thank you for your feedback. There doesn't seem to be enough details in the issue for us to work on. If this really is a documentation issue and I have misunderstood, please reopen it with more information.

**Comment by thanusivan** [comment]
https://docs.docker.com/ee/ucp/kubernetes/ee/ucp/user-access/cli/#download-client-certificates

Please have look ..

**Comment by ollypom** [comment]
Do you mind giving a bit of background on where you got this URL?

It is indeed a 404 and should be pointing to https://docs.docker.com/ee/ucp/user-access/cli/#download-client-certificates.

**Comment by thanusivan** [comment]
I got from below link  "CLI Based Access"
https://docs.docker.com/ee/ucp/kubernetes/install-cni-plugin/

**Comment by thanusivan** [comment]
Cool. Thank you..

**Comment by ollypom** [comment]
@thanusivan Sorry, the PR only just got merged. It should be live on the site in the next 24 hrs.
