### ISSUE TITLE
remove Cloud Object Storage - Standard Regional Swift API

### ISSUE THREAD

**Issue by lifemikey** [docker/docker.github.io#8998]
File: [docker-for-ibm-cloud/dtr-ibm-cos.md](https://docs.docker.com/docker-for-ibm-cloud/dtr-ibm-cos/)

please remove this section as the Regional Swift API has gone End of Support
**Configure IBM Cloud Object Storage Regional Swift API for DTR**

**Comment by lifemikey** [comment]
remove this as well 
"or Cloud Object Storage - Standard Regional Swift API"
under **Create an IBM Cloud Object Storage account instance**

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this here for that reason. Feel free to continue the conversation after I close.
