### ISSUE TITLE
Incorrect default for --health-interval

### ISSUE THREAD

**Issue by kwgurney** [docker/docker.github.io#9004]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/)

--health-interval |   | Time between running the check (ms\|s\|m\|h) (default 0s)

Experience shows me the default is 30seconds, not 0.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
