### ISSUE TITLE
[Spiped] the sample cound not running sucessful

### ISSUE THREAD

**Issue by BOFA1ex** [docker/docker.github.io#9011]
File: [_samples/library/spiped/index.md](https://docs.docker.com/samples/library/spiped/)
Change:
[Error]docker run -d -v /data/spiped/keyfile:/spiped/key:ro ...
ps: I did not understand the ro what meaning for.
=>
[Success]docker run -d -v /data/spiped/keyfile/spiped-keyfile:/spiped/key ...
Just in my personal experience..

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this topic no longer exists.
