### ISSUE TITLE
docker copy documentation

### ISSUE THREAD

**Issue by tiny-dancer** [docker/docker.github.io#9017]
Docker copy command with env variables silently does nothing

```Dockerfile
COPY --from=builder /app/linux_amd64/ $HOME/.terraform.d/plugins/linux_amd64
```

will lead to empty ~/.terraform.d/plugins/linux_amd64 in container

 

```Dockerfile
COPY --from=builder /app/linux_amd64/ <USER>/.terraform.d/plugins/linux_amd64
```

will correctly copy files

File: [engine/userguide/eng-image/dockerfile_best-practices.md](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/)

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As this issue is old, the context may have changed. It appears that the command no longer appears in the new topic. If the issue still persists, please let us know.
