### ISSUE TITLE
unable to locate the packages installed in the docker

### ISSUE THREAD

**Issue by NomanSaleem4** [docker/docker.github.io#9023]
### Problem description
I have installed the python packages using pip in the docker container, now i want to change the modules in the package. Firstly i am unable to locate the packages installed in the docker. secondly whats the best approach to customize the 3rd party packages. Thanks

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As this is an old issue, some context may have been lost.
You can refer to the documentation at https://docs.docker.com/language/python/
If you find any issues in the documentation, please let us know.
