### ISSUE TITLE
engine/builder: CMD doesn't need full path

### ISSUE THREAD

**Issue by tharvik** [docker/docker.github.io#9025]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

> If you want to run your <command> without a shell then you must express the command as a JSON array and give the full path to the executable.

Actually, it only needs path relative to `WORKDIR`.

The next Dockerfile builds an image behaving as `library/bash`
```dockerfile
FROM bash
WORKDIR /usr/local
CMD ["bin/bash"]
```

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://github.com/docker/cli/tree/master/docs/reference
