### ISSUE TITLE
I can't land on a general page for installing Docker EE on Linux

### ISSUE THREAD

**Issue by patsmith-public** [docker/docker.github.io#9032]
### Problem description

I want to land on a page that lets a reader choose the flavor of Linux to install Docker EE on. However, I have to specify a flavor to land on such as https://docs.docker.com/install/linux/docker-ee/rhel/.  I'd like to point them to the parent of this page, but it just opens and closes the TOC in the left pane. 

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/install/linux/docker-ee/

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/install/linux/docker-ee/rhel/

- Other: <DETAILS>

**Comment by craig-osterhout** [comment]
This is an old issue that seems to be no longer applicable. Docs regarding the Enterprise Edition are no longer available. For different flavors of CE, you can check https://docs.docker.com/engine/install/
If the issue is still applicable, please let us know.
