### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by HarveyStroud** [docker/docker.github.io#9034]
File: [get-started/index.md](https://docs.docker.com/get-started/)

There are two images on this page:

Virtual Machine diagram
(*broken image link here*) Virtual machine stack example

Container diagram
(*broken image link here*) Container stack example

**Comment by HarveyStroud** [comment]
Hold on, looks like I had clicked on a link sending me to an old version of this page?

https://docs.docker.com/v17.09/get-started/#containers-vs-virtual-machines

The images for the link in my first comment up above are actually working.

**Comment by DawnWood-Docker** [comment]
@HarveyStroud We do have archives, so that might have been the issue. I'm closing because it sounds like this is no longer an issue, but lmk if you question/problem has not been addressed.
