### ISSUE TITLE
Broken links in docker-for-windows installation instructions

### ISSUE THREAD

**Issue by Mierpo** [docker/docker.github.io#9037]
File: [docker-for-windows/install.md](https://docs.docker.com/docker-for-windows/install/)

https://download.docker.com/win/edge/InstallDocker.msi
https://download.docker.com/win/stable/InstallDocker.msi

Those links no longer work. Referenced here:
"Legacy (.msi) installers are available for Edge and Stable channels." in the docs

**Comment by raghuasr29** [comment]
+1. This is required for enterprise deployment.

**Comment by aevesdocker** [comment]
Closing issue as this has been fixed
