### ISSUE TITLE
Documentation does not match the current screens on docker.com

### ISSUE THREAD

**Issue by mattbellwork** [docker/docker.github.io#9042]
File: [docker-cloud/cloud-swarm/create-cloud-swarm-azure.md](https://docs.docker.com/docker-cloud/cloud-swarm/create-cloud-swarm-azure/)

This documentation does not match the screens I see when I login to docker.

**Comment by thaJeztah** [comment]
Thanks for reporting; @cowsrule @caervs ptal

**Comment by craig-osterhout** [comment]
The screenshots were updated in https://github.com/docker/docker.github.io/commit/711da925fc4ea379a37ad1f33bb231bf78edd8ee
