### ISSUE TITLE
ENTRYPOINT hyperlink in right margin yields Moby Dock for browsers without JS

### ISSUE THREAD

**Issue by gsvolt** [docker/docker.github.io#9044]
### Problem description

In a browser that does not have JS enabled, when you visit this link:

https://docs.docker.com/engine/reference/builder/

And click ENTRYPOINT

You are presented with Moby Dock page with a message: Sorry, we can't find that page.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/engine/reference/builder/

### Project version(s) affected

Docker v18.09 documentation.

### Suggestions for a fix

At the time of reporting this issue, the ENTRYPOINT url looks like this:

https://docs.docker.com/engine/reference/#entrypoint

I propose that we simply append *builder* after reference like so:

https://docs.docker.com/engine/reference/builder#entrypoint

Personal anecdote:

I propose this change because I believe in this content being universally accessible by all device types. My inspiration for this issue is Gmail app which can be used on browsers with Javascript disabled.

Side Issue:

- I tried to access the  "Edit this page" hyperlink, but sadly it also is currently non-functional (atleast for me). At the time of writing this, it points to:

https://github.com/docker/docker.github.io/edit/master/engine/reference/builder.md

Which yields a github 404 octocat page.

**Comment by gsvolt** [comment]
Screenshots 

![Screenshot from 2019-07-10 14-08-24](https://user-images.githubusercontent.com/46934/60993331-41cee280-a31c-11e9-82f8-d9b69c823d7c.png)

![Screenshot from 2019-07-10 14-09-26](https://user-images.githubusercontent.com/46934/60993400-662abf00-a31c-11e9-9603-d690ecb15b2f.png)

**Comment by giosim** [comment]
If I may  add a note, which might perhaps use a different issue, having up to date manpages would also be great.

With up to date manpages I wouldn't even have to fire up a browser in order to get the documentation!

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Which browser are you using?
After disabling javascript in the latest version of Chrome, I was able to click the ENTRYPOINT(https://docs.docker.com/engine/reference/builder/#entrypoint) link.

**Comment by thaJeztah** [comment]
Ah, I think this one has been fixed since

I recall that in the past we had some javascript to generate some links (or fix up some anchors)

I think this was the one that fixed it; https://github.com/docker/docker.github.io/pull/10549

**Comment by craig-osterhout** [comment]
Thanks, @thaJeztah. Resolving this issue. 
@gsvolt, if the issue still persists, please let us know.
