### ISSUE TITLE
Document CS Engine install script

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#907]
@joaofnfernandes commented on [Wed May 25 2016](https://github.com/docker/dhe-deploy/issues/2202)

We explain how to install the cs engine using different package managers.
We should also document that an installation script is available and you can use it with

```
curl -SLf https://packages.docker.com/1.12/install.sh | sh
```

**Comment by johndmulhausen** [comment]
This has been fixed
