### ISSUE TITLE
"Communicate between a container and a swarm service" needs to be updated.  It is a duplicate of the bridge.

### ISSUE THREAD

**Issue by zkSNARK** [docker/docker.github.io#9074]
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)

**Comment by Mikuu** [comment]
+1

**Comment by pluckhuang** [comment]
the same #9046

**Comment by DavidSonoda** [comment]
Please fix this as soon as possible. 

I looked for this tutorial for a long time and when I finally found it here it's just not related to the 'Communication between a container and a swarm service' at all. Does anyone have the correct tutorial?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/docker.github.io/issues/8387
