### ISSUE TITLE
Docker for Mac "get started" docs change request

### ISSUE THREAD

**Issue by rizkysyazuli** [docker/docker.github.io#9075]
File: [docker-for-mac/index.md](https://docs.docker.com/docker-for-mac/)

This code example doesn't work for me:

    docker run --detach --publish=80:80 --name=webserver nginx

I have Apache running on port 80. The docs should accommodate people with existing web server setup. Which i assume *many* web developers already have.

Anyway, I tried using port 3000, but this gives me `ERR_EMPTY_RESPONSE` when accessed from [localhost:3000](http://localhost:3000). Not sure i'm doing it right either.

    docker run --detach --publish=3000:3000 --name=webserver nginx

Pls advise. Thx.

**Comment by aevesdocker** [comment]
Closing issue as it refers to deprecated docs
