### ISSUE TITLE
Get Started, Part 4 question about VirtualBox

### ISSUE THREAD

**Issue by rizkysyazuli** [docker/docker.github.io#9076]
File: [get-started/part4.md](https://docs.docker.com/get-started/part4/)

In the section "**Create a cluster**", under the tab for "Mac, Linux, Windows 7 and 8". We are asked to install VirtualBox.

I'm using Docker for Mac. Is it really necessary? Because in the docs for [Docker Desktop for Mac](https://docs.docker.com/docker-for-mac/docker-toolbox/) says it already has HyperKit instead of Virtual Box.

Pls advise. Thx.

**Comment by DawnWood-Docker** [comment]
@rizkysyazuli Thanks for letting us know you had issues with our [Get Started](https://docs.docker.com/get-started/) guide. We just updated the whole guide to align with current best practices. As a bonus, we also removed the outdated steps that you allude to above. Virtual box is not necessary. Hope this helps and love to hear your feedback on the updated guide.
