### ISSUE TITLE
https://docs.docker.com/v17.09/docsarchive/ links return 404

### ISSUE THREAD

**Issue by dylankolson** [docker/docker.github.io#9077]
### Problem description
Looking for archive doc link for version 1.13 and the URL given returns a 404 as well as the URL a user would suspect to find the archived docs under. 

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/v17.09/docsarchive/

- I couldn't find the information I wanted. I expected to find it at the following URL: https://docs.docker.com/v17.09/v1.13/ OR https://docs.docker.com/v1.13/

### Project version(s) affected

Current Docs website

**Comment by craig-osterhout** [comment]
This issue appears no longer applicable as the topic now directs users to view version-specific documentation locally. If you encounter issues viewing the docs locally, please let us know.
