### ISSUE TITLE
document how to recover from auth config errors

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#908]
@vikstrous commented on [Tue May 10 2016](https://github.com/docker/dhe-deploy/issues/2083)

If you re-install UCP without re-installing DTR you may end up getting a blank page when trying to log into DTR. The URL would be something like:

```
https://ucp.ucp/enzi/authorize?client_id=e403f21b-37fc-4681-a86b-4c2648b430f9&redirect_uri=https%3A%2F%2F172.17.0.1%2Fapi%2Fv0%2Fopenid%2Fcallback&response_type=code&scope=openid&state=eyJyZWRpcmVjdE5leHQiOiIiLCJyZWRpcmVjdFVSSSI6Imh0dHBzOi8vMTcyLjE3LjAuMS9hcGkvdjAvb3BlbmlkL2NhbGxiYWNrIn0.4tr1RfSvBDM2q0f4e3gsniKEhkAlAajSpPWOLxR8QqM
```

To recover from this you need to run the reconfigure command without changing any configs and it'll repair the openid service registration.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #448](https://github.com/docker/docs-private/issues/448) via [**ZenHub**](https://www.zenhub.com/)
