### ISSUE TITLE
HUB API Documentation

### ISSUE THREAD

**Issue by tjamet** [docker/docker.github.io#9080]
### Problem description

I am experiencing troubles finding docker hub API documentation

### Problem location

In docker hub, I have been trying to find documentation about the API, following this link https://docs.docker.com/docker-hub/ but struggle to find information relative to the actual hub documentation.

I am trying mainly to access 2 features:
- Searching an image within an organisation, which the docker hub seems to be doing internally by `https://hub.docker.com/v2/repositories/<org>/?page_size=25&page=1&ordering=last_updated&name=<term>`
- Updating an image README

I am unsure wether those should are part of the hub API, or the Registry API, neither am I certain that this endpoint is public and its contract is maintained over time.

Would it be doable to document how to interact with Docker HUB using an API?

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As this issue is old, some context may have changed. The Hub API documentation is now available under Reference (https://docs.docker.com/reference/) on the top menu or through Reference on the new landing page (https://docs.docker.com/).
