### ISSUE TITLE
[2.0.0] Docs - No description of how to copy over files after upgrade

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#909]
@mbentley commented on [Mon May 09 2016](https://github.com/docker/dhe-deploy/issues/2075)

After doing an upgrade, there is no mention of copying the files for local storage or how one should do that.  I used:

```
cp -r /var/local/dtr/image-storage/local/docker /var/lib/docker/volumes/dtr-registry-71bd7dc5a534/_data/
```

Also, the docs in `configure/config-storage.md` still have references to `/var/local/dtr/image-storage/local` for local storage which isn't true for DTR 2.0.

**Comment by johndmulhausen** [comment]
Issue moved to [docker/docs-private #449](https://github.com/docker/docs-private/issues/449) via [**ZenHub**](https://www.zenhub.com/)
