### ISSUE TITLE
"Get started with Docker for Windows" issues

### ISSUE THREAD

**Issue by ouroborus** [docker/docker.github.io#9092]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

These are based on my experience after running `Docker for Windows Installer.exe` v2.0.0.31259 on Windows 10 Pro and trying to follow along with "Get started with Docker for Windows".

---

`docker login` was required before being able to run `docker run hello-world`. Without it, I would get:

```
> docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout.
See 'docker run --help'.
```

This was even after logging in via the Docker Desktop tasktray app.

---

On Windows 10, port 80 can be occupied by IIS as part of a normal OS install, preventing the `nginx` container from running as configured in "Getting started ...".

**Comment by aevesdocker** [comment]
Closing issue as it refers to old version of Docker Desktop
