### ISSUE TITLE
Sorry, we can't find that page

### ISSUE THREAD

**Issue by prime123** [docker/docker.github.io#9093]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by prime123** [comment]
when opening pages getting error as Sorry, we can't find that page.

**Comment by thaJeztah** [comment]
Do you have a link to the page that failed to load?

**Comment by traci-morrison** [comment]
@prime123  Thank you for your feedback. There doesn't seem to be enough details in the issue for us to work on. If this really is a documentation issue and I have misunderstood, please reopen it with more information.
