### ISSUE TITLE
No explanation for error message

### ISSUE THREAD

**Issue by aszalacinski** [docker/docker.github.io#9094]
File: [engine/examples/dotnetcore.md](https://docs.docker.com/engine/examples/dotnetcore/)

Following the tutorial on this page and when I go to build this dockerfile i get the error message:
invalid from flag value build-env: pull access denied for build-env, repository does not exist or may require 'docker login'

There should be some context on how to troubleshoot this message when it appears. I am new to docker and am now having to spend time troubleshooting.

**Comment by thaJeztah** [comment]
What version of docker are you running?

Also. did you copy the whole example in your Dockerfile (including both `FROM` lines? Thus;

```Dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
```

**Comment by aszalacinski** [comment]
Newbie alert. Yeah... hand keyed the whole file and missed that 'AS build-env'... :/ Ignore and close. I know better than that. My bad.

**Comment by thaJeztah** [comment]
No worries, glad you found the problem!
