### ISSUE TITLE
404 on https://docs.docker.com/install/linux/docker-ce/debian/

### ISSUE THREAD

**Issue by Bushmills** [docker/docker.github.io#9096]
### Problem description
https://docs.docker.com/install/linux/docker-ce/debian/ has a broken link where it refers to 
https://docs.docker.com/install/linux/linux-postinstall.md

### Problem location
Problem exists on page https://docs.docker.com/install/linux/docker-ce/debian/, Section `Install Docker CE`:

`Docker CE is installed and running. The docker group is created but no users are added to it. You need to use sudo to run Docker commands. Continue to Linux postinstall to allow non-privileged users to run Docker commands and for other optional configuration steps.`

Link `postinstall` is 404

Same non-existing document is also linked to in section `Next steps`, `Continue to Post-installation steps for Linux`

### Suggestions for a fix
Provide file linked to, or adjust links accordingly

**Comment by damoose** [comment]
Still a problem on Aug 10/19

**Comment by traci-morrison** [comment]
This issue is resolved. If the problem persists, please open a new issue. Thank you.
