### ISSUE TITLE
Release mentioned was not found - 1.25.0

### ISSUE THREAD

**Issue by jskumar** [docker/docker.github.io#9104]
File: [compose/install.md](https://docs.docker.com/compose/install/)

docker compose - current stable build referred in the document 1.25.0 was not found.

only 1.24.1 (stable) and 1.25.0-rc1 was available. 

Thanks.

**Comment by jskumar** [comment]
Thanks @usha-mandya, @ollypom .

Are we changing the install.md documentation as well?
- The instructions below outline installation of the current stable release **(v1.25.0)** of Compose

**Comment by ollypom** [comment]
Hey @jskumar, I updated the variables file (_config.yml). All pages pull from that variable. So once the cache clears all page (including install) will include the 1.24.1 variable.

**Comment by jskumar** [comment]
Thanks @ollypom. It works :)
