### ISSUE TITLE
[2.0.0] Docs - Upgrade suggestions

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#911]
@mbentley commented on [Thu May 05 2016](https://github.com/docker/dhe-deploy/issues/2034)

In `Step 2. Install DTR 2.0`, the following upgrade step is suggested:

```
If you decide to install the new DTR on the same node, you’ll need to install it on a port other than 443, since DTR 1.4.3 is already using it. Use these instructions to install DTR 2.0:
```

Instead of making DTR 2.0 use a port besides 443, why not change the DTR 1.4.3 to use a different port so that your new 2.0 install doesn't use some non-standard port when you're done?

In the `Step 7. Decommission DTR 1.4.3` section, it says:

```
Once you’ve fully tested your new installation, you can uninstall DTR 1.4.3 by deleting /usr/local/etc/dtr and /var/local/dtr and removing all dtr containers.
```

I'd expect the uninstall process to actually be:
1.) Stop DTR properly:
   `sudo bash -c "$(sudo docker run docker/trusted-registry stop)"`
2.) Remove `/usr/local/etc/dtr` and `/var/local/dtr`

This is because the order does matter.

**Comment by johndmulhausen** [comment]
Closing per triage discussion
