### ISSUE TITLE
On windows, daemon.json requires double slashes for file system paths

### ISSUE THREAD

**Issue by mikenri** [docker/docker.github.io#9114]
File: [ee/ucp/admin/configure/join-nodes/join-windows-nodes-to-cluster.md](https://docs.docker.com/ee/ucp/admin/configure/join-nodes/join-windows-nodes-to-cluster/#compatibility-with-daemonjson)

The syntax listed in the documentation is not correct. 

If you enter it as shown in the documentation, you get an error due to an invalid escape character. 

The correct syntax must contain double slashes:

                "debug":     true,
		"tls":       true,
		"tlscacert": "C:\\ProgramData\\docker\\daemoncerts\\ca.pem",
		"tlscert":   "C:\\ProgramData\\docker\\daemoncerts\\cert.pem",
		"tlskey":    "C:\\ProgramData\\docker\\daemoncerts\\key.pem",
		"tlsverify": true,

**Comment by traci-morrison** [comment]
Fixed via https://github.com/docker/docker.github.io/pull/9976.
