### ISSUE TITLE
document the load balancer chicken and egg problem better

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker.github.io#912]
@vikstrous commented on [Thu Apr 28 2016](https://github.com/docker/dhe-deploy/issues/1878)

method 1:  one replica first
- should use ip of vm if a vm
- can use docker0 if local
- pushes/pulls require first replica to be up
- you still need to know what node you're installing on
  -> you can reconfigure the replica after adding a load balancer

method 2: load balancer first
- you need to use --ucp-node to make sure it's on the right node that's already in your load balancer
- alternatively you can load balance over all ucp nodes and just let it pick whatever

**Comment by johndmulhausen** [comment]
Closing per triage discussion
