### ISSUE TITLE
[Feature request] release and package the docker documentation building tool-chain

### ISSUE THREAD

**Issue by noraj** [docker/docker.github.io#9130]
## Description

Docker documentation is so nice, well organized, nice features (tags support, ligh/dark themes, glossary), etc.

It could be nice to release and package the tool-chain docker is using to build its documentation into one documentation tool/generator project on a dedicated git repository.

So anyone should be able to create it's own documentation using the docker documentation tool.

PS : I'm sorry if such a repo is already existing.

**Comment by traci-morrison** [comment]
Thank you for your feedback. This seems to be a feature request or a fundamental change in the way Docker works, but this GitHub repository is only for Docker documentation. Please file an issue in https://github.com/docker/ instead.

**Comment by noraj** [comment]
> This seems to be a feature request or a fundamental change in the way Docker works, but this GitHub repository is only for Docker documentation.

I'm talking about the docker documentation so I don't understand why you say that.

I'm saying the documentation system is so nice it would be great to make a generic documentation software from it.
