### ISSUE TITLE
docker-machine create slow

### ISSUE THREAD

**Issue by danielesk** [docker/docker.github.io#9139]
### Problem location

![image](https://user-images.githubusercontent.com/10652829/61939740-84541880-afc6-11e9-8fc6-96da03a77f6d.png)

I have run this command for an hour or not, it is better to install docker directly manually; since it is so slow, I want to know what the value of docker-machine exists? I wasted too much time, please answer my questions positively and give me a reasonable explanation.

- Other: <DETAILS>

**Comment by usha-mandya** [comment]
@danielesk  Thank you for your feedback. It looks like this issue is not related to Docker documentation. Please file an issue in https://github.com/docker/machine instead.
