### ISSUE TITLE
Registry configuration link is broken

### ISSUE THREAD

**Issue by AmauryOrtega** [docker/docker.github.io#9159]
### Problem description

The registry [deploying documentation](https://github.com/docker/docker.github.io/blob/master/registry/deploying.md), the registry configuration documentation and parts of it are linked. These links result in an HTTP 404 when browsing the documentation on GitHub.

### Problem location

```shell
$ grep "configuration.md" deploying.md --line-number

12:[configuration reference](configuration.md).
30:> continue to the [configuration guide](configuration.md) to deploy a
97:For more details, see the [registry configuration reference](configuration.md).
171:configuration options](./configuration.md#storage).
256:[registry configuration](configuration.md#letsencrypt).
466:[configuration information here](configuration.md#auth).
562: - [Configuration reference](configuration.md)
```

### Related issues

#6866

**Comment by traci-morrison** [comment]
Closing per https://github.com/docker/docker.github.io/issues/6866.
