### ISSUE TITLE
Document that redirects are not supports when interlock is configured for TLS passthrough

### ISSUE THREAD

**Issue by mikenri** [docker/docker.github.io#9167]
File: [ee/ucp/interlock/usage/redirects.md](https://docs.docker.com/ee/ucp/interlock/usage/redirects/)

There is currently a limitation where redirects do not work if a service is configured for TLS passthrough in interlock proxy. 

This limitation should be noted in the documentation. 
A support case indicated that this is currently an existing feature request tracked by reference number FIELD-280

**Comment by traci-morrison** [comment]
https://docker.atlassian.net/browse/FIELD-280

**Comment by traci-morrison** [comment]
@trapier @dani-docker @euanh PTAL at this issue.

**Comment by trapier** [comment]
@traci-morrison this issue report is accurate.   There is a KB on the issue at https://success.docker.com/article/interlock-support-for-http-redirect-to-tls-passthrough

**Comment by euanh** [comment]
Yes, this report is accurate.   There is a fix in master, and all things going well it will be in the next Interlock release.

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docker.github.io/pull/10048

**Comment by traci-morrison** [comment]
Completed in https://github.com/docker/docker.github.io/pull/10048.
