### ISSUE TITLE
Docker crashing on new Ubuntu 18.04 droplet on digital ocean when running swarm

### ISSUE THREAD

**Issue by arshadm** [docker/docker.github.io#9168]
### Problem description

I created a brand new Droplet on digital ocean (spec 8GB RAM, 160GB Disk, 4 v-cpu) with both a public IP and private IP address (10.138.223.25). Updated ubuntu to the latest release (the OS info is as follows):

Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-55-generic x86_64)

I installed docker-ce - Docker version 19.03.1, build 74b1e89 

I am finding once I do a swarm init the container.d and then dockerd both exit after about 10 mins of operation. 

There are a lot of errors in the logs (here is a sample):

Jul 30 05:48:36 ubuntu-s-4vcpu-8gb-sfo2-01 dockerd[21359]: time="2019-07-30T05:48:36.258880439Z" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed" module=libcontainerd namespace=plugins.moby
Jul 30 05:48:36 ubuntu-s-4vcpu-8gb-sfo2-01 dockerd[21359]: time="2019-07-30T05:48:36.258927297Z" level=error msg="failed to get event" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed" module=libcontainerd namespace=plugins.moby

### Problem location

- Other: <DETAILS>

### Project version(s) affected

Docker version 19.03.1, build 74b1e89 

### Suggestions for a fix

None at the moment, it's broken Cap'n.

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
