### ISSUE TITLE
More info on asking 'Is this node a manager'

### ISSUE THREAD

**Issue by antofthy** [docker/docker.github.io#9187]
File: [engine/reference/commandline/info.md](https://docs.docker.com/engine/reference/commandline/info/)

It took me ages to figure out how to ask if the current node is a manager.

Solutions I eventually found were...
```
  docker node inspect --format '{{.ManagerStatus.Leader}}' `hostname`
  docker info --format '{{json .Swarm.Managers}}'
```
Though I am not certain if there is a difference between a 'Leader' and a 'Manager'.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
