### ISSUE TITLE
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz: could not connect to server (check repositories file)

### ISSUE THREAD

**Issue by ramazan86** [docker/docker.github.io#9188]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

Hi guys, 
I have a problem with working through the steps.
In step 4, the docker-compose up command triggers an error for me. The error looks like this:

> Building web
Step 1/9 : FROM python:3.7-alpine
 ---> 930a7e894675
Step 2/9 : WORKDIR /code
 ---> Using cache
 ---> eff5ad3bd9eb
Step 3/9 : ENV FLASK_APP app.py
 ---> Using cache
 ---> d3496fa54b32
Step 4/9 : ENV FLASK_RUN_HOST 0.0.0.0
 ---> Using cache
 ---> 862ad97952ac
Step 5/9 : RUN apk add --no-cache gcc musl-dev linux-headers
 ---> Running in b7f8031691aa
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz: could not connect to server (check repositories file)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz: could not connect to server (check repositories file)
ERROR: unsatisfiable constraints:
  gcc (missing):
    required by: world[gcc]
  linux-headers (missing):
    required by: world[linux-headers]
  musl-dev (missing):
    required by: world[musl-dev]
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk add --no-cache gcc musl-dev linux-headers' returned a non-zero code: 3

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information.
