### ISSUE TITLE
duplicate versions in release notes

### ISSUE THREAD

**Issue by kolyshkin** [docker/docker.github.io#9191]
I see the following issues with https://docs.docker.com/engine/release-notes/

1. 18.03.1-ee-7 is mentioned twice (introduced by commit fa1c4bf5e40c4e7b66275120d51cf92d1d5a1b66, cc @paigehargrave)

2. 17.06.2-ee-22 is mentioned twice, one time out of order (added by commit ead1e1d8d5a855cbb4c8510a9241cccd9076ae71, cc @usha-mandya)

**Comment by kolyshkin** [comment]
@ollypom @usha-mandya PTAL

**Comment by usha-mandya** [comment]
@kolyshkin - Thanks for reporting this issue. I'll fix this.

**Comment by usha-mandya** [comment]
This issue has been fixed. Updated release notes are live at - https://docs.docker.com/engine/release-notes/
