### ISSUE TITLE
Tab completion in PowerShell for docker 19.x

### ISSUE THREAD

**Issue by Bafff** [docker/docker.github.io#9208]
Any plans on adding info for PowerShell modules that add autocomplete feature?
We had it for 17.x but missing for 19.x version of docs

For example we can mention this tool: https://github.com/matt9ucci/DockerCompletion
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

**Comment by aevesdocker** [comment]
Closing issue as it refers to old version of the docs
