### ISSUE TITLE
Verify MarkDown on Syslog logging driver page

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker.github.io#9217]
### Problem description

Reported by Alexis Viscogliosi on Slack; they copied the example code from https://docs.docker.com/config/containers/logging/syslog/, and pasted that in the terminal, however, one of the hyphens is not a standard hyphen, which caused the command to fail 

```
docker run -–log-driver syslog –-log-opt syslog-address=udp://localhost:4000 alpine echo hello world
```

```
unknown shorthand flag: 'â' in -–log-driver
See 'docker run --help'.
```

I haven't had time to check yet, but we should verify if the MarkDown source uses the correct hyphens, or (worse) if Jekyll is converting those hyphens to typographic symbols

### Problem location

https://docs.docker.com/config/containers/logging/syslog/

**Comment by thaJeztah** [comment]
@adrian-plata ptal (haven't checked yet if there's something wrong, and if it's reproducible)

**Comment by adrian-plata** [comment]
I copied it straight from the site, pasted it in my terminal window, and received the same error. Strange, I'll do more poking around.

**Comment by thaJeztah** [comment]
So the problem is one of the dashes; I think the second `-` at the start might be an em-dash

```
-–log-driver
```

**Comment by adrian-plata** [comment]
I copied from the .md file and received the same error. When I swapped out `-–log-driver` with `--log-driver` and `–-log-opt` with `--log-opt` and the error went away. It looks like the original code used a weird symbol on accident or it got transformed in some way. I'll open a PR to fix this.
