### ISSUE TITLE
Azure Subnet Size Considerations

### ISSUE THREAD

**Issue by wlieberman** [docker/docker.github.io#9230]
While the documentation discusses "Considerations for IPAM Configuration," it's not clear that failure to go through this step will create fatal errors.  The documentation needs to clearly specify that you MUST go through this step and either use the appropriate size network in Azure or take the appropriate action to fit within the subnet.  Failure to go through this step has caused major issues during the installation process.
File: [ee/ucp/admin/install/cloudproviders/install-on-azure.md](https://docs.docker.com/ee/ucp/admin/install/cloudproviders/install-on-azure/)

**Comment by traci-morrison** [comment]
@wlieberman Thanks for opening this issue. Do you think adding a note in the "Considerations for IPAM Configuration" section would help? The note would be formatted like the "Azure IPAM, UCP, and Kubernetes" note at the end of that section.

The text would read:

"Warning
You must complete this step, and either use the appropriate size network in Azure or take the proper action to fit within the subnet. Failure to complete this step may cause significant issues during the installation process."

**Comment by wlieberman** [comment]
That would be a good addition.  Maybe adding something else along the lines of "Failure to complete all the steps listed would result in significant error during the installation process" in bold font in the section under "Azure Prerequisites."

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docker.github.io/pull/9301
