### ISSUE TITLE
Docs @ Docker readme or image is wrong

### ISSUE THREAD

**Issue by tanarurkerem** [docker/docker.github.io#9235]
### Problem description
Docs Readme on the docker.hub is incorrect. https://hub.docker.com/r/docs/docker.github.io

"Read these docs offline" topic suggest use the latest tag, but it does not work.

Following does not work:
```
docker run -ti -p 4000:4000 docs/docker.github.io
docker run -ti -p 4000:4000 docs/docker.github.io:latest
docker run -ti -p 4000:4000 docs/docker.github.io:livedocs

```
This image(s) does not contain any entrypoint or command:

```
Paloczs-MacBook-Air:~ pp$ docker inspect --format='{{.Config.Cmd}}' docs/docker.github.io:latest
[/bin/sh -c #(nop) COPY dir:0a00c2455604e560e3d9bdb63ad1761c8c8941144c92743dd46c4c479459ad29 in /usr/share/nginx/html ]
Paloczs-MacBook-Air:~ pp$ docker inspect --format='{{.Config.Entrypoint}}' docs/docker.github.io:latest
[]

```
prod-61 works fine:

`docker run -ti -p 4000:4000 docs/docker.github.io:prod-61
`
It has cmd:
```
Paloczs-MacBook-Air:dockerdocs pp$ docker inspect --format='{{.Config.Cmd}}' docs/docker.github.io:prod-61
[/bin/sh -c echo -e "Docker docs are viewable at:\nhttp://0.0.0.0:4000"; exec nginx -g 'daemon off;']
```

**Comment by CxistHans** [comment]
run
`docker run  -it -p 4000:4000 docs/docker.github.io:latest`
to：https://hub.docker.com/r/docs/docker.github.io#read-these-docs-offline
same to can not start，no log，Can you help me？

**Comment by tanarurkerem** [comment]
> run
> `docker run -it -p 4000:4000 docs/docker.github.io:latest`
> to：https://hub.docker.com/r/docs/docker.github.io#read-these-docs-offline
> same to can not start，no log，Can you help me？

`docker run -it -p 4000:4000 --entrypoint "nginx" docs/docker.github.io:latest -g 'daemon off;'`

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the issue is old, it seems to have been resolved on newer images. If the issue still persists on newer images, please let us know.
