### ISSUE TITLE
typo or grammer error in ENV doc section

### ISSUE THREAD

**Issue by dmedhora** [docker/docker.github.io#9236]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

**Comment by dmedhora** [comment]
The URL: https://docs.docker.com/engine/reference/builder/
Section: ENV
.....in the build stage and can be replaced inline in many as well.

The above line contains a typo or grammatical error ("in many"...?)
Thank you.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. That content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference
