### ISSUE TITLE
WSL 2 docs don't mention that Ubuntu 18.04 has to be the default distro in WSL

### ISSUE THREAD

**Issue by tdaniely** [docker/docker.github.io#9244]
File: [docker-for-windows/wsl-tech-preview.md](https://docs.docker.com/docker-for-windows/wsl-tech-preview/)

The distro isn't detected in the prereq phase in the WSL 2 tool if it's not the default distro for wsl.
Need to run `wsl -s Ubuntu-18.04`.

**Comment by usha-mandya** [comment]
@tdaniely - Thanks for your feedback on the WSL 2 documentation. We will add a step on setting Ubuntu 18.04 as the default distro.
