### ISSUE TITLE
SNI (Server Name Indication) example is not great

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#9247]
File: [ee/ucp/kubernetes/cluster-ingress/ingress.md](https://docs.docker.com/ee/ucp/kubernetes/cluster-ingress/ingress/)

The example for `SNI (Server Name Indication)` isn't great since the example doesn't use a TLS connection.  For the purpose of a basic example, isn't not relevant and can probably be removed OR we could show someone how to deploy an application that uses TLS.

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
