### ISSUE TITLE
https://docs.docker.com/v17.09/docker-hub/builds/  "page not found"

### ISSUE THREAD

**Issue by nkadbi** [docker/docker.github.io#9258]
### Problem description

page not found

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/v17.09/docker-hub/builds/

- Other: "Sorry, we can't find that page"

**Comment by DawnWood-Docker** [comment]
Hi @nkadbi where did you see this link? It will help me troubleshoot if I know where you are coming from. 
Thanks,
Dawn
Senior Writer @ Docker

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing the issue as stale. If the issue still persists, please provide the details asked about in the previous comment.
