### ISSUE TITLE
Confusing wording about environment variables

### ISSUE THREAD

**Issue by urbantom** [docker/docker.github.io#926]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)
Regarding the paragraph "The ENV instruction has two forms. The first form, ENV <key> <value>, will set a single variable to a value. The entire string after the first space will be treated as the <value> - including characters such as spaces and quotes."

I suggest to consider the variant "The entire string after the second space will be treated as the <value> ..." as the proper one.

**Comment by jadametz** [comment]
I got this one.

**Comment by Rubab-Syed** [comment]
On it!

**Comment by prashant171992** [comment]
@urbantom i raised a PR(https://github.com/docker/docker.github.io/pull/2849) to merge in docker:v1.13 as this file not present in master branch

**Comment by urbantom** [comment]
Thanks in behalf of all newbies. ;-)
