### ISSUE TITLE
https://docs.docker.com/ee/admin/restore/restore-dtr/

### ISSUE THREAD

**Issue by docker-dev** [docker/docker.github.io#9264]
### Problem description

Reported by customer, case number [00094456](https://docker.my.salesforce.com/5000f00001ShxRB)

out of date documentation.

restore process is missing new command syntax and requires one of the following arguments:
`--dtr-use-default-storage, --dtr-storage-volume, or --nfs-storage-url`

### Problem location

https://docs.docker.com/ee/admin/restore/restore-dtr/

### Project version(s) affected

DTR 2.6

### Suggestions for a fix

I think there is a mismatch on the DTR restore documentation :

https://docs.docker.com/ee/admin/restore/restore-dtr/

It's saying :

docker container run \
--rm \
--interactive \
--env UCP_PASSWORD=$UCP_PASSWORD \
docker/dtr:2.7.1 restore \
--ucp-url <ucp-url> \
--ucp-insecure-tls \
--ucp-username <ucp-username> \
--ucp-node <hostname> \
--replica-id <replica-id> \
--dtr-external-url <dtr-external-url> < dtr-metadata-backup.tar

but it doesn't work. It seems you need at least one of this args :
`--dtr-use-default-storage, --dtr-storage-volume, or --nfs-storage-url`

Also

Regarding the destroy part (before the restore) you should also add the interactive in your example where it's also doesn't work :

```
[root@dckprddck118 testresto]# docker container run \
> --rm \
> --interactive \
> docker/dtr:2.7.1 destroy \
> --ucp-insecure-tls
INFO[0000] Beginning Docker Trusted Registry replica destroy
ucp-url (The UCP URL including domain and port): https://caas-prod.fr.world.socgen
ucp-username (The UCP administrator username): admin
ucp-password: ERRO[0036] cannot prompt for a password because the container was not started in tty mode (-t)
```

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this here for that reason. Feel free to continue the conversation after I close.
