### ISSUE TITLE
Please improve contrast on docs.docker.com

### ISSUE THREAD

**Issue by harridu** [docker/docker.github.io#9265]
File: [engine/reference/commandline/inspect.md](https://docs.docker.com/engine/reference/commandline/inspect/)
Maybe its just me, but I find light blue chars on a very light blue background difficult to read. Some light color chars on a black background would be fine, but the dark mode on docs.docker.com is rather disappointing. Sorry to say, but your documentation web pages lack contrast.

Would it be possible to get some reasonable colors providing a good contrast without over-straining the eyes? Something you can easily read without being blinded by the background?

Thanx in advance

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
