### ISSUE TITLE
Feedback for: registry/configuration.md

### ISSUE THREAD

**Issue by amouat** [docker/docker.github.io#927]
File: [registry/configuration.md](https://docs.docker.com/registry/configuration/)

Markdown is currently borked.

**Comment by joaofnfernandes** [comment]
We're going to fix it, in the mean time use the source
https://github.com/docker/distribution/blob/release/2.5/docs/configuration.md

**Comment by sanscontext** [comment]
Fixed in https://github.com/docker/distribution/pull/2116
