### ISSUE TITLE
Need to specify default units for commands like --restart-delay

### ISSUE THREAD

**Issue by omegamormegil** [docker/docker.github.io#9281]
File: [engine/reference/commandline/service_update.md](https://docs.docker.com/engine/reference/commandline/service_update/)

Customer ran into an issue (case# 95623) where they assumed the units defaulted to ns (nanoseconds), but they default to s (seconds) causing impact to production. Their service was configured to restart after waiting 665 years instead of 21 seconds.

Every option on this page which accepts different units needs to be updated with the default units.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
