### ISSUE TITLE
ucp kubernetes resources: update graphics

### ISSUE THREAD

**Issue by JimCodified** [docker/docker.github.io#9283]
File: [ee/ucp/kubernetes/kube-resources.md](https://docs.docker.com/ee/ucp/kubernetes/kube-resources/)

The resources shown on this screen reflect the older version of UCP. In UCP 3.2 the items have changed. Can we update this graphic to show the same info with the new UCP 3.2 items? See attached screenshot from 3.2.

<img width="196" alt="Screen Shot 2019-08-21 at 4 43 06 PM" src="https://user-images.githubusercontent.com/16492759/63472692-8b8d0b80-c438-11e9-8314-5c16f14fa373.png">

**Comment by JimCodified** [comment]
Possible new alternative - please double check that I haven't missed anything and I got all the resources attached to right buckets. I have an editable version if needed.

![ucp32-kube-resources](https://user-images.githubusercontent.com/16492759/63474295-4370e780-c43e-11e9-8e46-853e4def1419.png)

**Comment by traci-morrison** [comment]
This issue is resolved. If the problem persists, please open a new issue. Thank you.
