### ISSUE TITLE
Get Started Step 6 does not show cloud deployment

### ISSUE THREAD

**Issue by PerMildner** [docker/docker.github.io#9285]
File: [get-started/part6.md](https://docs.docker.com/get-started/part6/)

The "Install Docker Engine --- Community" tab says "cloud" and "the cloud hosted swarm" but there is nothing obvious in the instructions that relates to making anything run in "the cloud". It all looks like the previous steps, i.e. running locally on the developer machine.

**Comment by DawnWood-Docker** [comment]
Thank you for the feedback. 
1. We just published a new **[Get Started](https://docs.docker.com/get-started/)** guide that uses best practices for the latest release of Docker, including a section on using Docker Desktop and another on Kubernetes. part6.md is not part of the updated guide and will be redirected to the new topics. 
2. For installation of Docker Engine - Community, here's a link to the [Azure](https://docs.docker.com/docker-for-azure/) topic. 
Hope this helps.
