### ISSUE TITLE
Use < STDIN redirect instead of cat pipe in docker import examples

### ISSUE THREAD

**Issue by pangdaxing23** [docker/docker.github.io#9303]
File: [engine/reference/commandline/import.md](https://docs.docker.com/engine/reference/commandline/import/)

If only for consistency, would match this page on a similar command: https://docs.docker.com/engine/reference/commandline/load/

I checked in my shell and this works:
`docker import - somerepo/import_test < container.tar`

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
