### ISSUE TITLE
Your nginx command doesn't work anymore .. the original one did

### ISSUE THREAD

**Issue by londoncalling** [docker/docker.github.io#9328]
File: [docker-for-mac/index.md](https://docs.docker.com/docker-for-mac/)

Hi, 

The command to run `nginx` web browser that you show on the newest docs (step 2 [here](https://docs.docker.com/docker-for-mac/#explore-the-application)) doesn't work:

```
docker run --detach publish=80:80 --name=webserver nginx
```

e.g.,

```
vicky-MBP13:~ vicky$ docker run --detach publish=80:80 --name=webserver nginx
docker: invalid reference format.
See 'docker run --help'.
```

The original command that was in there for this step  does work (for example, [step 2 here in v.17.12](https://docs.docker.com/v17.12/docker-for-mac/#explore-the-application)):

```
vicky-MBP13:~ vicky$ docker run -d -p 80:80 --name webserver nginx
```
e.g., 

```
vicky-MBP13:~ vicky$ docker run -d -p 80:80 --name webserver nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
1ab2bdfe9778: Pull complete
a17e64cfe253: Pull complete
e1288088c7a8: Pull complete
Digest: sha256:53ddb41e46de3d63376579acf46f9a41a8d7de33645db47a486de9769201fec9
Status: Downloaded newer image for nginx:latest
5d53bbdae97561bbc38bb3ce3ea532ea383d3075150b3921168c77b7a181369a
```
Thanks,
Vicky

**Comment by mrmcshane** [comment]
Hi Vicky,

I'm able to run the command from step 2:
```
docker run --detach --publish=80:80 --name=webserver nginx
```
Looking at the command you're running, there looks to be two hyphens missing before `publish=80:80` that are showing in the documentation :)

Thanks,
Andrew
