### ISSUE TITLE
Mistake in netmask for ipv6

### ISSUE THREAD

**Issue by drnybble** [docker/docker.github.io#933]
File: [engine/userguide/networking/default_network/ipv6.md](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)

I think this line is incorrect: So if you have a /64 for your whole environment use /78 subnets for the hosts and /80 for the containers. This way you can use 4096 hosts with 16 /80 subnets each.

2^12 = 4096
2^4 = 16

I think it should be a /76 subnet: 12 bits = 4096 hosts and 4 bits = 16 /80 subnets

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by shubheksha** [comment]
I tried to understand what's written in the issue description, but it's a little confusing. Can someone explain which value needs to be changed here?

**Comment by aboch** [comment]
@shubheksha The submitter is pointing out that the sentence
```
So if you have a /64 for your whole environment use /78 subnets for the hosts and /80 for the containers. This way you can use 4096 hosts with 16 /80 subnets each.
```
has some incorrect info.

It suggests that if you reserve `/78` subnets for the docker hosts, you will be able to use 4096 hosts, and that each host will be given 16 `/80` subnets to use for container networks.

This is incorrect, given your env is given a /64, you can carve 2^14 `/78` host subnets, and only 4 `/80` container subnets.

To get to the 4096 host subnets and 16 container subnets, the host subnets must be `/76`, as @drnybble  suggested.
