### ISSUE TITLE
Couldn't get a Redis Container to work.

### ISSUE THREAD

**Issue by stebird** [docker/docker.github.io#9338]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/)

Followed the guide up to this point, but when I deployed my stack my Redis container returns a non-zero exit code after 4 seconds.  After a little bit of looking error messages up, I found out how to read the logs and I now see this error:
find: '.': Permission denied

Not sure what Redis is looking for or why it's getting permission denied.  I assume it's running as a non-privileged user based on the Redis documentation, but not sure where the permission denied error is coming from.

**Comment by DawnWood-Docker** [comment]
Hi @stebird We just updated the whole [Get Started ](https://docs.docker.com/get-started/)guide to align with current best practices. As a bonus, we also removed the broken steps that you allude to.
Love to hear your feedback on the updated guide!
