### ISSUE TITLE
Broken Link in Registry Proxy Cache article

### ISSUE THREAD

**Issue by cwilby** [docker/docker.github.io#9339]
### Problem description

[This blog post](https://blog.docker.com/2015/10/registry-proxy-cache-docker-open-source/) has a broken link to https://docs.docker.com/articles/configuring/

### Problem location

- I saw a problem on the following URL: https://blog.docker.com/2015/10/registry-proxy-cache-docker-open-source/)

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/articles/configuring/

### Suggestions for a fix

Not sure if it's the right link, but perhaps update to https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the issue is old, a lot has changed. The blog post appears to be no longer available.

**Comment by cwilby** [comment]
Nicely done @craig-osterhout 👍
