### ISSUE TITLE
Add tag on image of elasticsearch, logstash and kibana

### ISSUE THREAD

**Issue by piyushkv1** [docker/docker.github.io#9341]
File: [datacenter/ucp/2.2/guides/admin/configure/store-logs-in-an-external-system.md](https://docs.docker.com/datacenter/ucp/2.2/guides/admin/configure/store-logs-in-an-external-system/)

docker volume create --name orca-elasticsearch-data

docker container run -d \
    --name elasticsearch \
    -v orca-elasticsearch-data:/usr/share/elasticsearch/data \
    elasticsearch elasticsearch -Enetwork.host=0.0.0.0

docker container run -d \
    -p 514:514 \
    --name logstash \
    --link elasticsearch:es \
    logstash \
    sh -c "logstash -e 'input { syslog { } } output { stdout { } elasticsearch { hosts => [ \"es\" ] } } filter { json { source => \"message\" } }'"

docker container run -d \
    --name kibana \
    --link elasticsearch:elasticsearch \
    -p 5601:5601 \
    kibana

Image latest tag is not supported now. Please add tag on image name.

**Comment by traci-morrison** [comment]
This issue is resolved. If the problem persists, please open a new issue. Thank you.
