### ISSUE TITLE
Missing switch for UCP backup

### ISSUE THREAD

**Issue by darwin-traver** [docker/docker.github.io#9359]
File: [reference/ucp/3.2/cli/backup.md](https://docs.docker.com/reference/ucp/3.2/cli/backup/)

As per https://docs.docker.com/ee/admin/backup/back-up-ucp/#create-a-ucp-backup-using-the-cli, there is a new switch (--include-logs) that needs to be added to the table.

**Comment by darwin-traver** [comment]
@ollypom Filed this as an issue (as I did not have the full details of the new switch for a full PR).

More details located:
https://github.com/docker/orca/pull/16149

**Comment by ollypom** [comment]
Tracking in https://docker.atlassian.net/browse/ENGDOCS-125.
