### ISSUE TITLE
Download links don't work

### ISSUE THREAD

**Issue by guba-odudkin** [docker/docker.github.io#9369]
### Problem description
All the download links lead to the same place, even after I registered and logged in with Docker ID. How do I download older stable version of docker, where is the list/link anything? Work stopped because newest build is broken (even though it claims it's "stable") and I can't find an older one :/ Please advice.

### Problem location
https://docs.docker.com/docker-for-windows/release-notes/

**Comment by mrmcshane** [comment]
It looks as though the default behaviour is to always present the newest version at https://hub.docker.com/?overlay=onboarding

A few people have asked for this: https://github.com/docker/for-win/issues/1026

There is no specific link to older versions, however if you browse https://download.docker.com you should find older versions (17.06-17.09)
