### ISSUE TITLE
This docs indicates that Kitematic is legacy and suggests Docker Desktop. However, Docker Desktop show a button to install Kitematic. It seems confuse to me.

### ISSUE THREAD

**Issue by hugufc** [docker/docker.github.io#9375]
File: [kitematic/index.md](https://docs.docker.com/kitematic/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As this issue is old, some context may have been lost. Closing as the topic no longer exists. If the issue still persists, please provide more details.
