### ISSUE TITLE
Update Learn more about Kubernetes namespaces link

### ISSUE THREAD

**Issue by arueth** [docker/docker.github.io#9379]
File: [ee/ucp/authorization/group-resources.md](https://docs.docker.com/ee/ucp/authorization/group-resources/)

Change Learn more about Kubernetes namespaces link from:
https://v1-11.docs.kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
to:
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces

**Comment by ollypom** [comment]
Closed via: https://github.com/docker/docker.github.io/pull/9389
