### ISSUE TITLE
Deploy on Kubernetes for Mac page makes no sense

### ISSUE THREAD

**Issue by yaizudamashii** [docker/docker.github.io#9381]
File: [docker-for-mac/kubernetes.md](https://docs.docker.com/docker-for-mac/kubernetes/)

The first code sample

```
docker stack deploy --compose-file /path/to/docker-compose.yml mystack
docker stack services mystack
```

Where did docker-compose.yml come from?  What should be in it?  What is mystack? Is that a docker repo name or official image?

I copied the contents of Example app later in the page to docker-compose.yml and ran the command again, and got error

```
this node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again
```

I did that and now I seem to have created something running.  
```
Creating network mystack_default
Creating service mystack_web
Creating service mystack_words
Creating service mystack_db
```
But what is swarm?  Is the example app running?  How do I access it?  

issuing command
```
kubectl get services
```
only shows
```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   24h
```
Is mystack running?
The documentation should cover all of those questions.

**Comment by sixcorners** [comment]
The first three paragraphs mention that you have to enable kubernetes. It looks like you deployed your stack to docker swarm.
