### ISSUE TITLE
Download without registration

### ISSUE THREAD

**Issue by pbuzdin** [docker/docker.github.io#9383]
no option to download docker for windows without registration

**Comment by lkreimann** [comment]
This isn't really an issue with the documentation, rather a company policy. Isn't it?!

**Comment by traci-morrison** [comment]
Thank you for your feedback. This seems to be a feature request or a fundamental change in the way Docker works, but this GitHub repository is only for Docker documentation. Please file an issue in
https://github.com/docker/&lt;REPOSITORY> instead.
