### ISSUE TITLE
Cleanup some of the release note formatting

### ISSUE THREAD

**Issue by arueth** [docker/docker.github.io#9397]
File: [engine/release-notes.md](https://docs.docker.com/engine/release-notes/)

The following releases naming isn't consistent, they should probably have the Docker EE removed:
Docker EE 17.03.2-ee-8
Docker EE 17.03.2-ee-7
Docker EE 17.03.2-ee-6
Docker EE 17.03.2-ee-5
Docker EE 17.03.2-ee-4
Docker EE 17.03.1-ee-3
Docker EE 17.03.1-ee-2
Docker EE 17.03.0-ee-1

The following releases have h3 headers instead of h2 headers:
Docker EE 17.03.2-ee-6
Docker EE 17.03.2-ee-5
Docker EE 17.03.2-ee-4
Docker EE 17.03.1-ee-3
Docker EE 17.03.1-ee-2
Docker EE 17.03.0-ee-1

The release date format for Docker EE 17.03.2-ee-5 isn't consistent:
20 Jul 2017
should be:
2017-07-20

The release date format for Docker EE 17.03.0-ee-1 isn't consistent:
(2 Mar 2017)
should be on the next:
2017-03-02

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this here for that reason. Feel free to continue the conversation after I close.
