### ISSUE TITLE
Omitted logs plugin

### ISSUE THREAD

**Issue by ad-m** [docker/docker.github.io#9414]
File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/)

In that page was omitted logs plugins. Logs plugins are supported according to https://docs.docker.com/v17.09/engine/extend/plugins_logging/ .

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular topic is maintained in an upstream repo. If the issue is still applicable, please help create an issue or a PR in the source repo at https://github.com/docker/cli/tree/master/docs/extend
Closing this issue as unable to fix in this repo.
