### ISSUE TITLE
Scale the app

### ISSUE THREAD

**Issue by viniciobb** [docker/docker.github.io#9420]
### Problem description

 "Scale the app" doesn´t work

"Docker performs an in-place update, **no need to tear the stack down first or kill any containers.**
Now, re-run docker container ls -q to see the deployed instances reconfigured. If you scaled up the replicas, more tasks, and hence, more containers, are started."

i´ve got an docker-compose with 10 replicas already running, then i´ve changed to 5 .

When re-run docker stack deploy -c docker-compose.yml mycontainerservice5
i got an error : 

Creating network mycontainerservice5_webnet
Creating service mycontainerservice5_web
failed to create service mycontainerservice5_web: Error response from daemon: rpc error: code = InvalidArgument desc = port '4000' is already in use by service 'mycontainerservice10_web' (c44lrfmqaj84ft3te1079h4ke) as an ingress port

### Problem location
The part 3 documentation

### Project version(s) affected
Engine 19.3.2

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the issue is dated, some context has changed. If the issue is still applicable, please help provide a link to the topic or the topic name.
