### ISSUE TITLE
mongodb can use mounted /data/db volume on Mac OS X

### ISSUE THREAD

**Issue by gypapp** [docker/docker.github.io#9426]
File: [_samples/library/mongo/index.md](https://docs.docker.com/samples/library/mongo/)

I think the following warning message is not valid anymore at least in OS X:

> WARNING (Windows & OS X): The default Docker setup on Windows and OS X uses a  VirtualBox VM to host the Docker daemon. Unfortunately, the mechanism VirtualBox uses to share folders between the host system and the Docker container is not compatible with the memory mapped files used by MongoDB (see vbox bug, docs.mongodb.org and related jira.mongodb.org bug). This means that it is not possible to run a MongoDB container with the data directory mapped to the host.

Though I haven't tested thoroughly just did a simple write-restart-read scenario and succeeded with no error:
```
$ docker run --name mongo-mount -d -p 27017:27017 -v /tmp/mongo-data:/data/db mongo:3.4
$ ./mongo-test.py '{"author": "me", "date": "nowish"}'
<pymongo.results.InsertOneResult object at 0x10447f550>

$ docker stop mongo-mount
$ docker rm mongo-mount
$ docker run --name mongo-mount -d -p 27017:27017 -v /tmp/mongo-data:/data/db mongo:3.4
$ ./mongo-test.py
['posts']
{'_id': ObjectId('5d781f3d2744b1161c11e0ba'), 'author': 'me', 'date': 'nowish'}
```

Versions:
* mongo:3.4 image
* docker desktop (community) 2.1.0.2
* docker engine: 19.03.2
* Max OS X Mojave, version: 10.14.6 (18G95)
* test-mongo.py script:
```
#!/usr/bin/env python3
from pymongo import MongoClient
from pprint import pprint
import sys
import json

client = MongoClient('localhost', 27017)
db = client.test_database
if len(sys.argv) > 1:
    post = json.loads(sys.argv[1])
    pprint(db.posts.insert_one(post))
else:
    pprint(db.list_collection_names())
    pprint(db.posts.find_one())
```

**Comment by stefandesu** [comment]
Can confirm, Docker for Mac now uses Hyperkit for virtualization AFAIK, so maybe that fixed the issue.

**Comment by thaJeztah** [comment]
This page was a copy of the documentation hosted on Docker Hub for that image (https://hub.docker.com/_/mongo) and is no longer hosted on docs.docker.com.

Could you open a ticket in the issue tracker for that image in https://github.com/docker-library/docs/tree/master/mongo/ instead?
