### ISSUE TITLE
append/prepend

### ISSUE THREAD

**Issue by rdzien** [docker/docker.github.io#9428]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)

The line: 

> Look for output for the web service, prepended with your app name. 

should be 

> Look for output for the web service, appended with your app name.

As the _web is added to the end not the beginning of the name.

**Comment by DawnWood-Docker** [comment]
@rdzien Good catch!! We just rewrote the whole [Get Started](https://docs.docker.com/get-started/) guide, and the above mistake is no longer in the text. Would love to hear your feedback on the new guide!
