### ISSUE TITLE
Dead link in https://docs.docker.com/install/linux/docker-ce/debian/

### ISSUE THREAD

**Issue by blaiseli** [docker/docker.github.io#9433]
### Problem description

The page https://docs.docker.com/install/linux/docker-ce/debian/ contains a link to
https://docs.docker.com/install/linux/docker-ce/#install-using-the-repository, but that page doesn't seem to exist:

> Sorry, we can't find that page
> [a picture]
> Please file an issue at https://github.com/docker/docker.github.io.

**Comment by adrian-plata** [comment]
Hi There,

We can't find the link you're referring to on the Debian installation page. Do you still see the issue?

**Comment by blaiseli** [comment]
Hi, the link seems to have changed to https://docs.docker.com/install/linux/docker-ce/debian/#install-using-the-repository, which works.

So no more issue. I'll close.
