### ISSUE TITLE
update Manual UCP uninstall command

### ISSUE THREAD

**Issue by jasonbivins** [docker/docker.github.io#9437]
File: [ee/ucp/admin/install/uninstall.md](https://docs.docker.com/ee/ucp/admin/install/uninstall/)

The manual Uninstall UCP command is incomplete and includes services that don't exist on the UCP manager

Here's the error I get when I run that command:
```root@ubuntuleaderldap:/etc/kubernetes# docker service rm ucp-agent-win ucp-agent-s390x ucp-agent
Error: No such service: ucp-agent-win
Error: No such service: ucp-agent-s390x
Error: No such service: ucp-agent```

**Comment by traci-morrison** [comment]
@ry4nz PTAL at this issue. These are the commands in question:

> docker service rm ucp-agent-win ucp-agent-s390x ucp-agent
docker ps -a | grep ucp | awk '{print $1}' | xargs docker rm -f
docker volume ls | grep ucp | awk '{print $2}' | xargs docker volume rm

Are these command examples correct? Should the example be generic? For example:

> docker service rm SERVICE [SERVICE...]
docker ps [OPTIONS]
docker volume ls [OPTIONS]

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
