### ISSUE TITLE
Doc states that Suse only supports btrfs

### ISSUE THREAD

**Issue by aenright79** [docker/docker.github.io#9444]
File: [install/linux/docker-ee/suse.md](https://docs.docker.com/install/linux/docker-ee/suse/)

The above doc says that only btrfs is supported but the compatibility matrix as well as the code itself support overlay2 as well.  (overlay2 is actually the default on all other supported Linux distros)

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
