### ISSUE TITLE
load balancing not working as demonstrated on part 3 of get started

### ISSUE THREAD

**Issue by AnwarShah** [docker/docker.github.io#9446]
File: [get-started/part3.md](https://docs.docker.com/get-started/part3/)

load balancing not working as demonstrated on part 3 of get started. All the other outputs are just fine, but the container id shown for each request to localhost:4000 shows the same! That means there isn't any round-robin fashioned container choosing between requests.

Am I missing something? 

I'm using Docker Server Version: 19.03.1, in Windows 10 . Tested in Linux container mode.

**Comment by DawnWood-Docker** [comment]
Hi @AnwarShah You are not missing anything. We just updated the whole [Get Started ](https://docs.docker.com/get-started/)guide to align with best practices. As a side bonus, we eliminated errors by completely re-writing the steps. :) Would love to hear your feedback on the new guide.
