### ISSUE TITLE
Describe Managed Password setting for UCP SAML auth configuration

### ISSUE THREAD

**Issue by ivansharamok** [docker/docker.github.io#9460]
### Problem description

[Enable SAML authentication](https://docs.docker.com/ee/ucp/admin/configure/enable-saml-authentication/) article does not mention anything about **Disable Managed Password Authentication And Account Creation** setting. Please add details about this setting and what behavior it affects when enabled/disabled.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/ee/ucp/admin/configure/enable-saml-authentication/

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
