### ISSUE TITLE
Step 4 produces errors on Win 10 Pro SB2 updated

### ISSUE THREAD

**Issue by somedesa** [docker/docker.github.io#9464]
File: [docker-hub/index.md](https://docs.docker.com/docker-hub/)

Here is the forum thread.  Just trying to exactly follow steps.  Two fails.

https://forums.docker.com/t/out-of-box-fail-powershell/81233

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. That step was updated awhile ago and the issue has been resolved. It now instructs the user to create a Dockerfile without the example commands.
