### ISSUE TITLE
Update recommended storage driver for Oracle Linux

### ISSUE THREAD

**Issue by nicolaka** [docker/docker.github.io#9466]
This page still recommends using devicemapper for oracle linux. And still points to oracle linux 7.3. We need this updated to match what we recommend/support in compat matrix https://success.docker.com/article/compatibility-matrix.

File: [install/linux/docker-ee/oracle.md](https://docs.docker.com/install/linux/docker-ee/oracle/)

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
