### ISSUE TITLE
Ubuntu EE engine docs page still has old, 18.09 versioning info

### ISSUE THREAD

**Issue by ericsmalling** [docker/docker.github.io#9469]
File: [install/linux/docker-ee/ubuntu.md](https://docs.docker.com/install/linux/docker-ee/ubuntu/)

References to 18.09 as latest stable should be changed to 19.03

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this here for that reason. Feel free to continue the conversation after I close.
