### ISSUE TITLE
Broken link to v17.09/datacenter/dtr/2.4/admin/configure/deploy-caches

### ISSUE THREAD

**Issue by wilsonmar** [docker/docker.github.io#9484]
### Problem description
At https://docs.docker.com/v17.09/datacenter/dtr/2.4/guides/
when I click "cache images closer to users" the link https://docs.docker.com/v17.09/datacenter/dtr/2.4/admin/configure/deploy-caches/
appears with "Sorry, we can't find that page".

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
