### ISSUE TITLE
The instruction is not working

### ISSUE THREAD

**Issue by nik3011** [docker/docker.github.io#9487]
File: [get-started/part2.md](https://docs.docker.com/get-started/part2/) - The instruction does not work in the docker version 19.03.2. After i build the image and try to run the localhost:4000 in my url, it does not work. Moreover, the container immediately exits after starting.

**Comment by DawnWood-Docker** [comment]
Hi @nik3011 We just updated the whole [Get Started](https://docs.docker.com/get-started/
) guide to align with current best practices. As a bonus, we also removed the broken steps that you allude to. 
Love to hear your feedback on the updated guide.
