### ISSUE TITLE
Binaries files page not found

### ISSUE THREAD

**Issue by haithamsha** [docker/docker.github.io#9499]
### Problem description
Binaries files page not found

### Problem location

Binaries files page at this link not found https://docs.docker.com/installation/binaries/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As the issue is old, a lot has changed. 
I'm unable to find a dead link inside the current version of https://docs.docker.com/engine/install/binaries/
If the issue still persists, please let us know and provide more information about the links location.
