### ISSUE TITLE
Clarify where the RUN command runs from

### ISSUE THREAD

**Issue by julien-lecomte** [docker/docker.github.io#951]
File: [engine/reference/commandline/exec.md](https://docs.docker.com/engine/reference/commandline/exec/)

This page should mention that the `run` command runs from the last WORKDIR specified.

Also, chained/quoted shell does not work:
docker run --rm toto "cd /foobar && touch me" fails...

**Comment by shubheksha** [comment]
I'll take this up!

**Comment by JimGalasyn** [comment]
@shubheksha how's your progress on this? We'll need to return this to the unclaimed pool for the hackathon by tomorrow, if we don't see movement. Thanks!

**Comment by shubheksha** [comment]
I'll fix this!

**Comment by JimGalasyn** [comment]
Cool, thanks!

**Comment by shubheksha** [comment]
This needs to be fixed in https://github.com/moby/moby I think?

**Comment by mstanleyjones** [comment]
Yes, @shubheksha :) In the `docs/reference/commandline/` directory.

**Comment by jmaitrehenry** [comment]
Trying to fix it in https://github.com/moby/moby/pull/32831

**Comment by mstanleyjones** [comment]
The work for this has moved upstream and the fix is under review. Thanks @jmaitrehenry !
