### ISSUE TITLE
Document regex for DTR

### ISSUE THREAD

**Issue by mbentley** [docker/docker.github.io#952]
Related to https://github.com/docker/distribution/issues/2100#issuecomment-267474190, since namespaces are a Hub concept, it would be good to document the regex for namespaces and repositories  that DTR utilizes.

**Comment by joaofnfernandes** [comment]
Just to confirm, you're talking about which characters are valid when creating a users/orgs and repos. Am I right?

It seems that for repos the regex is

```
/^[a-z0-9]+(?:[._-][a-z0-9]+)*$/
 
Must start and end with an alphanumeric character and consist of lower case letters, numbers, or \._-\
```

It seems to be about the same for namespaces, but I need to confirm this.

**Comment by johndmulhausen** [comment]
Closing per triage discussion
