### ISSUE TITLE
Sidebar link incorrect for Avoid IP Range Conflicts section

### ISSUE THREAD

**Issue by jeliyo** [docker/docker.github.io#9522]
File: [ee/ucp/admin/install/plan-installation.md](https://docs.docker.com/ee/ucp/admin/install/plan-installation/)

Requesting that we change the sidebar link for the `Avoid IP range conflicts` section on the `Plan a production UCP installation` page [screenshot attached].

<img width="799" alt="Screen Shot 2019-09-26 at 4 36 55 PM" src="https://user-images.githubusercontent.com/20586509/65723299-24d4c080-e07c-11e9-8184-c7773a432cae.png">

The current (incorrect) link is "https://docs.docker.com/ee/ucp/admin/install/#avoid-ip-range-conflicts".
The correct link is "https://docs.docker.com/ee/ucp/admin/install/plan-installation/#avoid-ip-range-conflicts".

**Comment by traci-morrison** [comment]
@jeliyo Can you confirm that this link is still broken? It goes to the correct link in my browser. Thanks.

**Comment by jeliyo** [comment]
@traci-morrison if I click on the hyperlink in the page, it scrolls to the correct portion of the document. However, if I `right-click` > `copy link address`, I find this is what comes up https://docs.docker.com/ee/ucp/admin/install/#avoid-ip-range-conflicts which directs us to a different page.

**Comment by traci-morrison** [comment]
@allysmith424 Hi, Ally. Can you take a look at this issue? I don't understand the behavior that Jasmine is seeing. Why are the sidebar links pointing to a different page? The expected behavior is for the sidebar links to be created based on the Markdown headings within the md file. Thanks.

**Comment by traci-morrison** [comment]
Closing as links will be changed during the docs transition.
