### ISSUE TITLE
glossary does not contain entry for "orphan"

### ISSUE THREAD

**Issue by bcx** [docker/docker.github.io#9524]
There is an environment variable [`COMPOSE_IGNORE_ORPHANS`](https://docs.docker.com/v17.12/compose/reference/envvars/#compose_ignore_orphans).

It would be helpful for the glossary to include an entry for "orphan", to clarify what behavior is controlled by this flag.  I believe there are other similar-but-different uses of the term "orphan" in the Docker world.  It would be good for these to be collected together into a single glossary entry.

File: [glossary.md](https://docs.docker.com/glossary/)

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
