### ISSUE TITLE
Documentação de opção de comando ausente .

### ISSUE THREAD

**Issue by gatosdeolhosazuis** [docker/docker.github.io#9530]
### Problem description

Na página do comando `docker container run` a opção `-it` está não listada nem descrita mas é usada no Quick Start 4º passo Run em https://hub.docker.com/?overlay=onboarding .

### Problem location

Página do comando `docker container run` .

- I saw a problem on the following URL: <URL>
https://hub.docker.com/?overlay=onboarding

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>
https://docs.docker.com/engine/reference/commandline/container_run/

- Other: <DETAILS>

### Suggestions for a fix

Na página dentro de Options inserir em observação a ordem alfabética , o nome dessa opção , seu shorthand , o default e a description .

No windows se executar `docker run -d` ao invés de `docker run -it -d` o container não é criado .

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. -it is a shorthand for using both the -i and -t.
More information about this particular syntax is at https://docs.docker.com/engine/reference/commandline/cli/#option-types
