### ISSUE TITLE
Cloudstor support on Azure

### ISSUE THREAD

**Issue by docker-dev** [docker/docker.github.io#9558]
### Problem description

Can you please verify that Cloudstor is still supported. According to my TSE colleague's it's no longer supported on Azure and the documentation is out of date and still being referred to by Docker customers. Apparently the OS must support SMB 3.0 and I think Cloudstor uses SMB 2.1:

https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-windows

I have a case open (00099016) and customer has referred to these docs and tried to install the cloudstor plugin but it fails.

The plugin is also not listed as officially certified:
https://success.docker.com/article/working-with-docker-certified-plugin-cases

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/docker-for-azure/persistent-data-volumes/

**Comment by mhtsharma948** [comment]
any update?

**Comment by alex200789** [comment]
Any Update? We want to use CloudStor on a Azure Storage Account with Secure Transfer enabled, which requires SMB 3.0
