### ISSUE TITLE
Missing steps – Install Docker Engine Community

### ISSUE THREAD

**Issue by shaneparsons** [docker/docker.github.io#9578]
**File: [get-started/part6.md](https://docs.docker.com/get-started/part6/)**

---

It seems like this page is missing steps in the **Install Docker Engine Community section**.

It starts with:

> Find the [install instructions](https://docs.docker.com/install/#supported-platforms) for Docker Engine --- Community on the platform of your choice.

Which in my case is a **DigitalOcean Docker Image** (missing from the install instructions page, which is another issue)... It then continues to say:

> Run `docker swarm init` to create a swarm on the node.

What "node" is this refering to? If "node" refers to the new server, running `docker swarm init` doesn't do anything... Where is the connection to the repository? Do I have to pull it in first? How do I do that?

This leaves many un-answered questions at the end of what was otherwise a very concise tutorial.

**Comment by shaneparsons** [comment]
Seems related to https://github.com/docker/docker.github.io/issues/9285

**Comment by DawnWood-Docker** [comment]
Hi @shaneparsons Thank you for the feedback. A couple of things:
1. "platform of your choice" in this sentence means you can install on your choice of operating system, not Docker Image. It could be clearer for sure. For example, you can install on Linux [Centos](https://docs.docker.com/install/linux/docker-ce/centos/), [Debian](https://docs.docker.com/install/linux/docker-ce/debian/), etc. 
2. We just published a new **[Get Started](https://docs.docker.com/get-started/)** guide that uses best practices for the latest release of Docker, including a section on using Docker Desktop and another on Kubernetes. part6.md is not part of the new guide and will be redirected to the new topics. It's still (hopefully) concise. 

Would love to hear your feedback after looking at the new guide.

**Comment by DawnWood-Docker** [comment]
oops, didn't mean to close this. Will let you do that @shaneparsons

**Comment by shaneparsons** [comment]
Thanks @DawnWood-Docker I'll have a look and keep you posted!

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. Closing it as stale. If you have any feedback, please let us know.
