### ISSUE TITLE
Volume performance tuning could be more useful

### ISSUE THREAD

**Issue by fulldecent** [docker/docker.github.io#9580]
File: [docker-for-mac/osxfs-caching.md](https://docs.docker.com/docker-for-mac/osxfs-caching/)

This guide explains a lot about how these configuration options work. Before all of that, a few examples would be very welcome:

* In a development workflow when you mount your code into the container you should use ____
* If your container is generating large build artifacts that are not time-sensitive for the host you should use ____

Additionally, there is no mention of the option readonly and how it affects these new mounting options.

**Comment by aevesdocker** [comment]
Closing as refers to old documentation
