### ISSUE TITLE
DDE: Outline how to change default text editor from VSCode

### ISSUE THREAD

**Issue by stevenfollis** [docker/docker.github.io#9589]
File: [ee/desktop/user/windows-user.md](https://docs.docker.com/ee/desktop/user/windows-user/)

The App Designer default to using VSCode as its text editor:

![image](https://user-images.githubusercontent.com/5393923/66335019-27e77080-e908-11e9-816f-5208118f5c47.png)

We need instructions on how to configure this to a different editor, for example if I wish to use IntelliJ or Sublime instead.

**Comment by aevesdocker** [comment]
Closing issue as it refers to old documentation
