### ISSUE TITLE
DTR - external storage needs azure examples

### ISSUE THREAD

**Issue by jasonbivins** [docker/docker.github.io#9592]
File: [ee/dtr/admin/configure/external-storage/index.md](https://docs.docker.com/ee/dtr/admin/configure/external-storage/)

This page has links on the right to NFS and AWS but not Azure. No Azure content or explanations either. 

 There is an Azure tag at the very bottom that takes you to the DTR 2.0 Storage config document.

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
