### ISSUE TITLE
Container networking page doesn't mention that Dockerfile needs EXPOSE command

### ISSUE THREAD

**Issue by vegarsti** [docker/docker.github.io#9610]
I tried to put a Flask app inside a Dockerfile, but I couldn't figure out how to expose the port. Turns out I need to put `EXPOSE <port number>`, which I did not realize when reading [the docs for _container networking_](https://docs.docker.com/config/containers/container-networking/). Would it be a good idea to mention that somewhere in that documentation page? I'm happy to submit a PR for it.

**Comment by Maximization** [comment]
Exposing a port doesn't actually open the port. It's only for documentation purposes and makes no practical difference.

For inter-container communication, when two containers share the same network **all ports** are opened between the two.

For communication from the host or outside world, the port needs to be published.

Expose causes a lot of confusion and there's many tutorials who don't get this right. Doesn't help if a highly upvoted and accepted SO answer also gets this wrong: https://stackoverflow.com/questions/22111060/what-is-the-difference-between-expose-and-publish-in-docker.

**Comment by vegarsti** [comment]
Ah, so I have misunderstood. Thank you for clarifying!
