### ISSUE TITLE
Add hint for Ubuntu SSL paths for Docker daemon behind an HTTPS_PROXY

### ISSUE THREAD

**Issue by danial-k** [docker/docker.github.io#9611]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)
Point 2 under ```Running a Docker daemon behind an HTTPS_PROXY``` states:

> Ask your network admin for the proxy’s CA certificate and append them to /etc/pki/tls/certs/ca-bundle.crt

In Ubuntu/Debian this is located in ```/etc/ssl/certs/ca-certificates.crt```.
It would be helpful for users following instructions on setting up proxy CA certs if this was mentioned, even in passing.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
