### ISSUE TITLE
BUG getting 403 while attempting to download docker-ce

### ISSUE THREAD

**Issue by videte47** [docker/docker.github.io#9613]
### Problem description
I am getting 403 while following the instructions https://docs.docker.com/install/linux/docker-ce/centos/ to install the docker-ce

### Problem location

- I saw a problem on the following URL:https://docs.docker.com/install/linux/docker-ce/centos/

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>
<img width="717" alt="Screen Shot 2019-10-10 at 12 31 20 PM" src="https://user-images.githubusercontent.com/18494956/66589007-9ff9a480-eb5b-11e9-92af-46f287a96448.png">

**Comment by n-cc** [comment]
Noticed this for Ubuntu as well, looks like all of the linux directory is 403ing: https://download.docker.com/linux

**Comment by Tuumke** [comment]
+1 on trying to update.
`E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/bionic/InRelease  403  Forbidden [IP: 13.225.78.44 443]
E: The repository 'https://download.docker.com/linux/ubuntu bionic InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

Also trying to clean /etc/apt/source.list and re-add pgp key and source doesnt work.
On adding the pgp key
`curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
curl: (22) The requested URL returned error: 403
gpg: no valid OpenPGP data found.
`

**Comment by Tuumke** [comment]
Problem seems solved again.
`curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
OK
`

`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Get:2 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]
Hit:3 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:6 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages [8880 B]
Fetched 73.3 kB in 1s (113 kB/s)
Reading package lists... Done
`
p.s. how do you create new lines in code blocks :S

**Comment by seemethere** [comment]
Issue should now be resolved, this can be closed

**Comment by Basil-Kuriakose** [comment]
This issue is back again.
