### ISSUE TITLE
Repository bulletin <> bulletinboard

### ISSUE THREAD

**Issue by Fabian1976** [docker/docker.github.io#9620]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/)

On this page, you explain that you have to create a repository "bulletin" in your docker hub but then you upload the image to a repository called "bulletinboard" which leaves the manually created repository empty and creates a new one.

The upload to a non-existing repository automatically creates the repository. So I would suggest to either remove the step of manually creating the repository and explain that it is automatically created of fix the names.

**Comment by bpelikan** [comment]
Caused by #9609 (#9608)
PR: #9618 #9623
@DawnWood-Docker in #9623 screenshot still pointing to `bulletin` repository name instead to `bulletinboard`.
