### ISSUE TITLE
How to setup docker-machine using Hyper-V Internal switch?

### ISSUE THREAD

**Issue by sathishc58** [docker/docker.github.io#9628]
### Problem description

I am trying to create 'manager' node (for Docker-swarm) using Hyper-V (using internal v-switch) in my office, but it hung with the following

ERROR:  Waiting for the host

My office desktop has got only one NIC, If I create 'external vswitch' and share it using 'network adapter sharing' I lose connectivity to all my office / client related applications

Hence I chose to create hyper-v 'manager' node using 'internal switch'. I also tried setting up NAT and provided IP address to 'internal switch'. But NOTHING worked

Should I need / create a hyper-v external switch prior creating Internal switch ? Or am I doing something wrong with internal switch setup?

Kindly let me know if the issue is related to Docker version

### Problem location

- Other:

================
Version details
================

Version: 17.03.1-ce-rc1-win3 (10625)
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.637.amd64fre.rs3_release_svc.180808-1748

===================
Hyper-V Switch details
===================

Created Hyper-V Internal switch "NATSwitch"

NATSwitch configuration

IPv4 Address:  10.1.35.197
Subnet mask :  255.0.0.0
Pref DNS    :  10.1.35.1

=======================
Docker-Machine console output
=======================

PS C:\Windows\system32> docker-machine create --driver hyperv --hyperv-virtual-switch "NATSwitch" manager
Running pre-create checks...
(manager) Unable to get the local Boot2Docker ISO version:  EOF
(manager) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(manager) Latest release for github.com/boot2docker/boot2docker is v19.03.3
(manager) Downloading C:\Users\sathishkumar.kailas\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v19.03.3/boot2docker.iso...
(manager) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(manager) Unable to get the local Boot2Docker ISO version:  EOF
(manager) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(manager) Latest release for github.com/boot2docker/boot2docker is v19.03.3
(manager) Downloading C:\Users\sathishkumar.kailas\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v19.03.3/boot2docker.iso...
(manager) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(manager) Copying C:\Users\sathishkumar.kailas\.docker\machine\cache\boot2docker.iso to C:\Users\sathishkumar.kailas\.docker\machine\machines\manager\boot2docker.iso...
(manager) Creating SSH key...
(manager) Creating VM...
(manager) Using switch "NATSwitch"
(manager) Creating VHD
(manager) Starting VM...
(manager) Waiting for host to start...

PS C:\Windows\system32> docker-machine ls
NAME       ACTIVE   DRIVER   STATE     URL   SWARM   DOCKER    ERRORS
manager    *        hyperv   Running                 Unknown   IP not found

### Project version(s) affected

N/A

### Suggestions for a fix

N/A

[log.txt](https://github.com/docker/docker.github.io/files/3720294/log.txt)

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
