### ISSUE TITLE
Image links are broken.

### ISSUE THREAD

**Issue by kxen42** [docker/docker.github.io#9630]
File: [get-started/index.md](https://docs.docker.com/get-started/)

Please fix the images links that compare the container stack to a VM stack.

**Comment by adrian-plata** [comment]
Hi  There,

If you're referring to the two images under [Containers and virtual machines](https://docs.docker.com/get-started/#containers-and-virtual-machines), those seem to be rendering correctly.

**Comment by traci-morrison** [comment]
This issue is resolved. If the problem persists, please open a new issue. Thank you.
