### ISSUE TITLE
wrong link i suppose

### ISSUE THREAD

**Issue by CarloBerni** [docker/docker.github.io#9638]
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by lena-larionova** [comment]
Thanks for reporting an issue, but it looks like there isn't enough information for us to work with. Please reopen this issue with the link and the page it's located on (if applicable) if you want us to take a look.
