### ISSUE TITLE
Clarify task-history-limit

### ISSUE THREAD

**Issue by phillijw** [docker/docker.github.io#9647]
File: [engine/reference/commandline/swarm_update.md](https://docs.docker.com/engine/reference/commandline/swarm_update/)

Can someone add some verbiage on what the number means? Does it mean how many total containers there will be (stopped and started) or how many old containers it will keep around?

**Comment by phillijw** [comment]
I just updated this value to 0 and existing containers did not go away. Clarifying when this takes effect would also be nice.

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
