### ISSUE TITLE
Add examples of storage-opts and log-opts for the daemon

### ISSUE THREAD

**Issue by gswallow** [docker/docker.github.io#967]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

There are no examples of how to add storage-opts or log-opts, nor anything in second-level lists of properties, really, to /etc/docker/daemon.json.  Here's an example that would save a few folks' time.

```
{
  "storage-driver": "devicemapper",
  "storage-opts": [
    "dm.thinpooldev=/dev/mapper/vg0-pool0",
    "dm.use_deferred_deletion=true",
    "dm.use_deferred_removal=true"
  ],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "10"
  }
}
```

**Comment by scjane** [comment]
#dibs

**Comment by JimGalasyn** [comment]
@scjane  How's your progress on this? We'll need to return this to the unclaimed pool for the hackathon, if we don't see a PR. Thanks!

**Comment by alvin319** [comment]
I'll try to tackle this one!

**Comment by alvin319** [comment]
I have created a PR in moby to add this example in the documentation.

**Comment by mstanleyjones** [comment]
Reviewing upstream. Looks great!

**Comment by mstanleyjones** [comment]
Merged upstream!
