### ISSUE TITLE
fixed-cidr-v6 field mandatory with "ipv6":true

### ISSUE THREAD

**Issue by arkodg** [docker/docker.github.io#9676]
When the user is enabling `ipv6`, it is mandatory for the `fixed-cidr-v6` field to be specified

this page has better details https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6/#using-ndp-proxying

File: [config/daemon/ipv6.md](https://docs.docker.com/config/daemon/ipv6/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It appears fixed in https://github.com/docker/docker.github.io/commit/1b319c30a57334d82096bc4e1cabfab3a8b6dda1
