### ISSUE TITLE
Feedback for: registry/configuration.md

### ISSUE THREAD

**Issue by yzhivkov** [docker/docker.github.io#968]
File: [registry/configuration.md](https://docs.docker.com/registry/configuration/)

Page is broken. Headings do not display properly (show ### ...)

**Comment by sanscontext** [comment]
Hey @yzhivkov thanks for the feedback, we're working on getting this fixed, but this doc lives in an upstream repo. In the meantime you can read it from the source here:
https://github.com/docker/distribution/blob/release/2.5/docs/configuration.md

**Comment by sanscontext** [comment]
Fixed in https://github.com/docker/distribution/pull/2116
