### ISSUE TITLE
Please provide MD5 Sums for Downloads in "Versions available" section.

### ISSUE THREAD

**Issue by hatdropper1977** [docker/docker.github.io#9684]
File: [ee/ucp/admin/install/upgrade-offline.md](https://docs.docker.com/ee/ucp/admin/install/upgrade-offline/)

Add MD5 and SHA checksum of UCP and DTR offline images.

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
