### ISSUE TITLE
Change docker for windows nginx example to not use port 80

### ISSUE THREAD

**Issue by shelmire** [docker/docker.github.io#9689]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

Using port 80 for the nginx container will cause issues if you aren't running as admin (80 is a protected port on windows, at least with default settings). You can see that this issue has been faced by many others here: https://stackoverflow.com/questions/46533482/error-starting-userland-proxy-bind-for-0-0-0-080-unexpected-error-permission . I suggest this be changed to port 8000, as that's usually unused (and less likely to conflict with 8080 which is fairly common for web devs to use in development).

**Comment by aevesdocker** [comment]
Closing issue as it refers to old documentation that has since been moved/deprecated.
