### ISSUE TITLE
Wrong indentation level of the quote block in the Dockerfile reference

### ISSUE THREAD

**Issue by brlin-tw** [docker/docker.github.io#9690]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

Refer the following screenshot, the quote block should be on the same level of the list node's content.

![Screenshot_20191021_131509](https://user-images.githubusercontent.com/13408130/67178682-318fce80-f406-11e9-8afd-573c0030a6ac.png)

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or a PR in the repo at https://github.com/docker/cli/tree/master/docs/reference
