### ISSUE TITLE
Missing page title in the title bar of the Dockerfile reference

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [docker/docker.github.io#9691]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

Refer the browser's title bar when browsing <https://docs.docker.com/engine/reference/builder>:

![Screenshot_20191021_132707](https://user-images.githubusercontent.com/13408130/67178840-d27e8980-f406-11e9-9108-4e9b571ec4ac.png)

The page title should  be visible (probably "Dockerfile reference")

**Comment by nunovieira** [comment]
Seems like a simple fix, but I can't even find the file to fix it myself. Could someone point in the right direction, please?
