### ISSUE TITLE
Docker installed but it does not run

### ISSUE THREAD

**Issue by Kevinoh47** [docker/docker.github.io#9697]
File: [docker-for-mac/index.md](https://docs.docker.com/docker-for-mac/)

following the instructions, i checked: docker --version, docker-compose --version, and docker-machine --version. All are slightly later than the versions shown in the documentation.

Then I ran docker run hello-world, as instructed in the next step. Instead of what is expected, I get: "docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'."

Your instructions don't help me figure out what to do next. Docker run --help is not helpful. And following links, I was quickly lost. Can you update the documentation to explain what to do if you have the correct docker, docker-compose, and docker-machine installed, but the daemon is not working?

Thanks!

**Comment by aevesdocker** [comment]
Closing issue as it refers to docs that have since been moved/deprecated
