### ISSUE TITLE
Request to add confirmation that dtr in "mixed" mode is expected

### ISSUE THREAD

**Issue by brinker211** [docker/docker.github.io#9702]
File: [ee/ucp/admin/configure/set-orchestrator-type.md](https://docs.docker.com/ee/ucp/admin/configure/set-orchestrator-type/)

A question that I have gotten in support multiple times is:
"Why can't I change DTR orchestration type to something other than mixed?" or
"Is DTR supposed to be in "mixed" orchestration?"

The request being submitted is to add information or at least confirmation that DTR's default and expected behavior is to be in "mixed" orchestration. The same is true of UCP managers which is already said in the document. The reasoning that I have used in the past with customers is that DTR, just like UCP managers, are considered "system" nodes and need to be in mixed mode. 

Additionally if DTR mode type is changed to swarm only or kube only, reconciliation will revert the node back to "mixed" mode. This is expected behavior but customers have asked if this is normal. 

Thanks team!

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docker.github.io/pull/9757

**Comment by traci-morrison** [comment]
This issue was fixed in https://github.com/docker/docker.github.io/pull/9757.
