### ISSUE TITLE
UCP docs have incorrect statement on workloads on managers

### ISSUE THREAD

**Issue by mklamb** [docker/docker.github.io#9714]
File: [ee/ucp/admin/install/system-requirements.md](https://docs.docker.com/ee/ucp/admin/install/system-requirements/)

in the above doc, we state: 
These requirements assume that manager nodes won’t run regular workloads. If you plan to run additional workloads on manager nodes, you may need to provision more powerful nodes. If manager nodes become overloaded, the cluster may experience issues.

We do not support workloads on managers.  Can we please change this call out to something like:
Docker does not support workloads other than those required for UCP on UCP manager nodes

thanks!

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docker.github.io/pull/9756

**Comment by traci-morrison** [comment]
This issue was fixed in https://github.com/docker/docker.github.io/pull/9756.
