### ISSUE TITLE
DTR 2.7.3: Need to update image for "repositories/admin/dtr/mirrors/new" page

### ISSUE THREAD

**Issue by cemckenzie** [docker/docker.github.io#9719]
![Screen Shot 2019-10-22 at 3 53 36 PM](https://user-images.githubusercontent.com/5015378/67341640-08923b00-f4e5-11e9-879a-f0f787a535f2.png)
File: [ee/dtr/user/promotion-policies/push-mirror.md](https://docs.docker.com/ee/dtr/user/promotion-policies/push-mirror/)

The page for "repositories/admin/dtr/mirrors/new" shown is from DTR 2.6.0 and has  _**Push to remote registry**_  before _**Pull from remote registry**_.
![Screen Shot 2019-10-22 at 3 54 29 PM](https://user-images.githubusercontent.com/5015378/67341552-d1238e80-f4e4-11e9-948b-3bb4447d44e4.png)

This page from DTR 2.7.3 shows the options reversed, e.g. _**Pull from remote registry**_ before _**Push to remote registry**_ , Confusing!

**Comment by cemckenzie** [comment]
@DawnWood-Docker ^

**Comment by DawnWood-Docker** [comment]
hey @cemckenzie thanks for the ping. @lena-larionova works on the DTR docs.

**Comment by lena-larionova** [comment]
Fixed and updated in #9727
