### ISSUE TITLE
Clarify what `docker builder prune` will and will not delete, reference to "images"

### ISSUE THREAD

**Issue by maiamcc** [docker/docker.github.io#9738]
File: [engine/reference/commandline/builder_prune.md](https://docs.docker.com/engine/reference/commandline/builder_prune/)

Description for `--all` tag says: "Remove all unused images, not just dangling ones." Is this copypasta from the [`image prune`](https://docs.docker.com/engine/reference/commandline/image_prune/) docs? As I understand it, the build cache doesn't even deal directly with images, but rather with layers. I don't have a good sense of what layers `docker builder prune` will and will not delete, full stop, let alone when the `--all` flag is specified. Could someone clarify? Thank you!

**Comment by yusufgungor** [comment]
"--all" deleted the all caches not only used ones.

+1

**Comment by strowk** [comment]
When I tried that, it deleted even cache, which was used for one of tagged image, so I guess "--all" is misleading

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
