### ISSUE TITLE
Confusion about "start a development container"

### ISSUE THREAD

**Issue by vipul1409** [docker/docker.github.io#974]
File: [opensource/project/set-up-dev-env.md](https://docs.docker.com/opensource/project/set-up-dev-env/)

In "Task 2. Start a development Container section." Step 1 have steps to check VM status for Mac users. So far in the development setup there was not VM setup discussion (I ignored this step and continued with setup) but was little confused regarding this step, it will be good to have more clarification here.

**Comment by londoncalling** [comment]
See #218 (and overview issue #2625)

**Comment by audioboxer217** [comment]
I will take this one.
