### ISSUE TITLE
Add the admin `Networks` option to Interlock config

### ISSUE THREAD

**Issue by arkodg** [docker/docker.github.io#9748]
File: [ee/ucp/interlock/config/index.md](https://docs.docker.com/ee/ucp/interlock/config/)

https://github.com/docker/interlock/pull/311 introduced a feature to allow the administrator to cherry-pick a list of Networks, Interlock can connect to . We need to add documentation for this feature

e.g.
```
[Extensions.default]
  ...
  ...
  ...
  Networks = ["testNet1", "testNet2"]

```
cc @traci-morrison

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docker.github.io/pull/9762

**Comment by traci-morrison** [comment]
Issue resolved via https://github.com/docker/docker.github.io/pull/9780.
