### ISSUE TITLE
Support new label com.docker.lb.algorithm

### ISSUE THREAD

**Issue by arkodg** [docker/docker.github.io#9749]
File: [ee/ucp/interlock/usage/labels-reference.md](https://docs.docker.com/ee/ucp/interlock/usage/labels-reference/)

https://github.com/docker/interlock/pull/296 introduced a new label - `com.docker.lb.algorithm`
Now the user will be able to pick the load balancing
algorithm by setting `com.docker.lb.algorithm` to `round_robin` | `ip_hash` |
`least_conn` and if no label is set, `round_robin` will be used to decide
the backend server

cc @traci-morrison

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docker.github.io/pull/9758

**Comment by traci-morrison** [comment]
Closing because the feature will not be released before the repository is migrated.
