### ISSUE TITLE
Need to add secure-overlay to cluster_config table

### ISSUE THREAD

**Issue by arkodg** [docker/docker.github.io#9754]
File: [ee/ucp/admin/configure/ucp-configuration-file.md](https://docs.docker.com/ee/ucp/admin/configure/ucp-configuration-file/)

Need to add this to the UCP Cluster Config table
`secure-overlay` (optional)/`boolean` Enables IPSec Network Encryption in Kubernetes

Reference - https://github.com/docker/orca/pull/17464

This needs to go live post the Nov patch release
cc: @traci-morrison

**Comment by traci-morrison** [comment]
WIP: https://github.com/docker/docs-private/pull/1421

**Comment by traci-morrison** [comment]
Issue resolved in the November patch release.
