### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by huikang** [docker/docker.github.io#976]
### Problem description
Link not working

### Problem location

... refer to the API documentation here and here for details... 
The two ``here`` do not direct to the correct URLs.

<https://github.com/docker/docker.github.io/blob/b72b9d3ba5d57437a72a0429428de26169d89b98/registry/garbage-collection.md#garbage-collection-in-the-registry>

### Suggestions for a fix

Put the correct URLs

**Comment by johndmulhausen** [comment]
At some point it appears this got fixed.
