### ISSUE TITLE
documentation needs update to match to be consistent with current UCP version(s)

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#9760]
File: [ee/ucp/kubernetes/index.md](https://docs.docker.com/ee/ucp/kubernetes/)

The screenshots/instructions for deploying workloads need to be updated to reflect current versions of UCP as there have been major changes to the UI.

**Comment by traci-morrison** [comment]
Thank you for your feedback. The Docker Enterprise platform business, including products, customers, and employees, has been acquired by Mirantis, inc., effective 13-November-2019. With this change, we are currently evaluating our documentation. In line with this, additions and updates are temporarily on hold, including product descriptions, instructions, illustrations, etc. while we evaluate the state of our documentation.
