### ISSUE TITLE
How to restore DTR when using a cloud storage provider is not documented

### ISSUE THREAD

**Issue by mikenri** [docker/docker.github.io#9767]
File: [ee/admin/restore/restore-dtr.md](https://docs.docker.com/ee/admin/restore/restore-dtr/)

This documentation is missing flags for how to restore DTR when using a cloud storage provider. 
When running the command to restore, it returns an error:

FATA[0000] Must explicitly set one of --dtr-use-default-storage, --dtr-storage-volume, or --nfs-storage-url

There are no switches available to specify how to use the various cloud storage providers that DTR supports.

**Comment by lena-larionova** [comment]
You should use the `--dtr-use-default-storage` flag - see https://docs.docker.com/reference/dtr/2.7/cli/restore/ for more info. I'll add that to the restore page as well.

**Comment by lena-larionova** [comment]
Fixed in #9786
