### ISSUE TITLE
Typo "/etc/docker.daemon.json"

### ISSUE THREAD

**Issue by Vincoll** [docker/docker.github.io#9770]
File: [network/iptables.md](https://docs.docker.com/network/iptables/)

This documentation page contains a typo.
In the section _"Prevent Docker from manipulating iptables"_ it is indicated :

> Docker engine’s configuration file at `/etc/docker.daemon.json`

Where should be **`/etc/docker/daemon.json`**

**Comment by lena-larionova** [comment]
Fixed in #9787
