### ISSUE TITLE
what are defaults for `local` driver on windows for volume create?

### ISSUE THREAD

**Issue by surfaceowl** [docker/docker.github.io#9779]
File: [engine/reference/commandline/volume_create.md](https://docs.docker.com/engine/reference/commandline/volume_create/)

This document says:  "The built-in local driver on Windows does not support any options.".  **This document should be updated to list the default, unchangeable behaviors of the windows local driver. ** <br><br>As an example, the mount options listed immediately below this reference [here](http://man7.org/linux/man-pages/man8/mount.8.html) show many options.  Although the mount options vary between linux and windows, there are some basics that everyone wants to know - *e.g. is this local drive automatically read-write? *

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. That particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue in the source repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
