### ISSUE TITLE
CLI reference for Enterprise features needs notice

### ISSUE THREAD

**Issue by sudo-bmitch** [docker/docker.github.io#9782]
### Problem description

The CLI reference documentation includes Enterprise only features without any notation in the docs, leading users to ask why they cannot use these features. The repo where these docs are built from also appears to be inaccessible for submitting external PR's.

### Problem location

Multiple URLs, including:

- https://docs.docker.com/engine/reference/commandline/assemble/
- https://docs.docker.com/engine/reference/commandline/cluster/
- https://docs.docker.com/engine/reference/commandline/registry/
- https://docs.docker.com/engine/reference/commandline/template/

All child pages would also be included.

### Project version(s) affected

Current stable documentation is affected.

### Suggestions for a fix

These docs should include a notice that they apply to the Enterprise CLI only, and not to Docker CE users, similar to how a notice is posted that they are experimental features today.

It would also be useful if these docs where exposed for future PR's similar to the CE documentation that we have today at: https://github.com/docker/cli/tree/master/docs/reference/commandline

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/. Closing this PR here for that reason.
