### ISSUE TITLE
Image for deploy to Docker Cloud is broken.

### ISSUE THREAD

**Issue by emm3ttarmstrong** [docker/docker.github.io#9788]
Here is the broken link:
https://files.cloud.docker.com/images/deploy-to-dockercloud.svg

Linked file: [docker-cloud/apps/deploy-to-cloud-btn.md](https://docs.docker.com/docker-cloud/apps/deploy-to-cloud-btn/)

**Comment by peter279k** [comment]
Yes. I also believe that these links are broken.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. This issue appears to be no longer applicable in the current docs. Docker Cloud is now part of Docker Hub and the "Deploy to Docker Cloud" button image is no longer applicable. If the issue is still relevant to the documentation, please let us know.
