### ISSUE TITLE
Documentation Hyperlink Issue

### ISSUE THREAD

**Issue by spectrumcomputing** [docker/docker.github.io#9792]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/get-started/part2/

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: Just after the start of the setting up section there is a link on the page to with the text ' https://git-scm.com/book/en/v2/Getting-Started-Installing-Git'  however the actual hyperlink (which is broken) attempts to go to 'https://docs.docker.com/get-started/install%20instructions'

### Project version(s) affected

Only looked at 19.03 Current

### Suggestions for a fix
Fix broken link

**Comment by lena-larionova** [comment]
Fixed in https://github.com/docker/docker.github.io/pull/9765. Will be published later today.
