### ISSUE TITLE
clarify docker-ee s390x linux packages only for 17.06

### ISSUE THREAD

**Issue by andrewhsu** [docker/docker.github.io#9798]
Docker EE install instructions mention installing docker-ee on s390x (aka z systems). It should clarify that it is only applicable for 17.06, e.g. https://github.com/docker/docker.github.io/blob/master/install/linux/docker-ee/rhel.md

Since according to the compatibility matrix, docker-ee only had supported packages on s390x architecture for the 17.06 version: https://success.docker.com/article/compatibility-matrix

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
