### ISSUE TITLE
Feedback for: engine/reference/commandline/version.md

### ISSUE THREAD

**Issue by rkawajiri** [docker/docker.github.io#98]
URL: engine/reference/commandline/version.md

The go format becomes empty on HTML sites. 

![screen shot 2016-10-06 at 18 48 34](https://cloud.githubusercontent.com/assets/661102/19147952/8b43cd7c-8bf5-11e6-8da7-484cae88fa49.png)

**Comment by johndmulhausen** [comment]
Fixed in #48
