### ISSUE TITLE
Add MD5 and SHA checksum

### ISSUE THREAD

**Issue by zaggash** [docker/docker.github.io#9815]
File: [ee/ucp/admin/install/install-offline.md](https://docs.docker.com/ee/ucp/admin/install/install-offline/)

It would be great to add MD5 and SHA checksum of UCP and DTR offline images.

**Comment by zaggash** [comment]
I just see it as a dup of https://github.com/docker/docker.github.io/issues/9684

**Comment by traci-morrison** [comment]
Closing as this is a duplicate of #9684
