### ISSUE TITLE
docker.io is not outdated

### ISSUE THREAD

**Issue by KaindlJulian** [docker/docker.github.io#9821]
File: [install/linux/docker-ce/debian.md](https://docs.docker.com/install/linux/docker-ce/debian/)

The debian provided docker.io package is being actively maintained, not outdated as stated in the docs.

Package Tracker: https://tracker.debian.org/pkg/docker.io 
Source: https://salsa.debian.org/docker-team/docker/-/tags

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. As the issue is old, some context may have changed. The current version of the docs uses the wording "older versions of Docker were called" rather than "outdated".
