### ISSUE TITLE
Include steps for linux users for kubernetes and swarm usage

### ISSUE THREAD

**Issue by qrthey** [docker/docker.github.io#9841]
File: [get-started/index.md](https://docs.docker.com/get-started/) only gives descriptions for OSX and Windows. It would be nice to at least provide some pointers for linux users as well.

**Comment by RafatRashid** [comment]
Same here. Having a hard time trying to explore both docker and kubernetes same time. Apparently kubernetes clusters arent as easy to run as in docker desktop. So some precise instructions would be much appreciated.

**Comment by aevesdocker** [comment]
Closing issue as it refers to content that has been removed/reorganised
