### ISSUE TITLE
Cannot connect to Docker from WSL2 until you go to resourcer/wsl integration

### ISSUE THREAD

**Issue by MaurGi** [docker/docker.github.io#9846]
File: [docker-for-windows/wsl-tech-preview.md](https://docs.docker.com/docker-for-windows/wsl-tech-preview/)

With the new release of Docker Desktop integration with WSL2, the instructions in this page are not enough to connect with WSL - I had to go into Settings/Resources/WSL Integration and select my distro before this started working
![image](https://user-images.githubusercontent.com/13138584/68611509-26f9af80-046f-11ea-9092-9fc828ab4b1c.png)

**Comment by aevesdocker** [comment]
closing issue as this has now been resolved
