### ISSUE TITLE
connect registry to docker

### ISSUE THREAD

**Issue by kidjinxs** [docker/docker.github.io#9862]
File: [registry/spec/api.md](https://docs.docker.com/registry/spec/api/)

**Comment by kidjinxs** [comment]
< hello the copy of windows 10 is expired no key >think in a bit of trouble here is there  way to keep it going <   />

**Comment by lena-larionova** [comment]
This doesn't sound like a documentation issue, so unfortunately I can't help you out. However, that document is actually edited in the https://github.com/docker/distribution repo, which is the home of docker registry in general - you might get some help over there.
