### ISSUE TITLE
Add Powershell instructions for Couchbase

### ISSUE THREAD

**Issue by alex75it** [docker/docker.github.io#987]
File: [engine/examples/couchbase.md](https://docs.docker.com/engine/examples/couchbase/)

I think it is assumed that you are on a Linux system.
Powershell have "curl" cmdlet but it does not work with the examples in the doc.

**Comment by bdwill** [comment]
Take this one for hackathon (but I don't think there's much to do in Docker documentation). 

@alex75it, I would try installing Git for Windows which includes `curl`. You're right, although PowerShell has a `curl` command, it's an alias for Invoke-WebRequest which operates (and outputs) a bit differently.

**Comment by JimGalasyn** [comment]
@bdwill Thank you for the reply! We were hoping that somebody could write another topic showing the PowerShell workflow, or modify this topic to include it, possibly using the tabs feature (https://github.com/docker/docker.github.io/blob/master/test.md#tabs). This is why we gave it 250 points to fix for the hackathon.

**Comment by mstanleyjones** [comment]
Hi, we are now importing the Couchbase docs from the official Docker repo on Docker Hub: https://docs.docker.com/samples/couchbase/#documentation

The doc you were looking at will be deprecated in favor of the official one, and you can give feedback [there](https://github.com/couchbase/docker). Thanks!
