### ISSUE TITLE
How to remove Kitematic if you used Toolbox

### ISSUE THREAD

**Issue by cognish** [docker/docker.github.io#988]
File: [toolbox/toolbox_install_mac.md](https://docs.docker.com/toolbox/toolbox_install_mac/)

If Kitematic is part of the Toolbox then shouldn't the instructions for uninstalling Toolbox on Mac include rm -fr ~/Library/Application\ Support/Kitematic ? [I'm a Docker newbie or I'd make the change]

**Comment by Mikel7220** [comment]
#

**Comment by londoncalling** [comment]
@nathanleclaire can you give us some guidance on how to fully uninstall Kitematic? This question has come up a few times. 

I had written this "uninstall Toolbox" topic: https://docs.docker.com/toolbox/toolbox_install_mac/#how-to-uninstall-toolbox, but not anything specific about Kitematic right now.
