### ISSUE TITLE
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk add --no-cache gcc musl-dev linux-headers' returned a non-zero code: 3

### ISSUE THREAD

**Issue by ruoru** [docker/docker.github.io#9882]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

Environment: macOS 10.15

it seems like not support mac os:

>ERROR: unsatisfiable constraints:
  gcc (missing):
    required by: world[gcc]
  linux-headers (missing):
    required by: world[linux-headers]
  musl-dev (missing):
    required by: world[musl-dev]
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk add --no-cache gcc musl-dev linux-headers' returned a non-zero code: 3

```shell
➜  composetest docker-compose up
Building web
Step 1/9 : FROM python:3.7-alpine
 ---> b11d2a09763f
Step 2/9 : WORKDIR /code
 ---> Using cache
 ---> 49d8f5c54778
Step 3/9 : ENV FLASK_APP app.py
 ---> Using cache
 ---> 2a03733e9261
Step 4/9 : ENV FLASK_RUN_HOST 0.0.0.0
 ---> Using cache
 ---> 4ca73678001c
Step 5/9 : RUN apk add --no-cache gcc musl-dev linux-headers
 ---> Running in df2b94fc5244
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  gcc (missing):
    required by: world[gcc]
  linux-headers (missing):
    required by: world[linux-headers]
  musl-dev (missing):
    required by: world[musl-dev]
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk add --no-cache gcc musl-dev linux-headers' returned a non-zero code: 3
```

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.

**Comment by prabhashibuddhima** [comment]
> File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)
> 
> Environment: macOS 10.15
> 
> it seems like not support mac os:
> 
> > ERROR: unsatisfiable constraints:
> > gcc (missing):
> > required by: world[gcc]
> > linux-headers (missing):
> > required by: world[linux-headers]
> > musl-dev (missing):
> > required by: world[musl-dev]
> > ERROR: Service 'web' failed to build: The command '/bin/sh -c apk add --no-cache gcc musl-dev linux-headers' returned a non-zero code: 3
> 
> ```shell
> ➜  composetest docker-compose up
> Building web
> Step 1/9 : FROM python:3.7-alpine
>  ---> b11d2a09763f
> Step 2/9 : WORKDIR /code
>  ---> Using cache
>  ---> 49d8f5c54778
> Step 3/9 : ENV FLASK_APP app.py
>  ---> Using cache
>  ---> 2a03733e9261
> Step 4/9 : ENV FLASK_RUN_HOST 0.0.0.0
>  ---> Using cache
>  ---> 4ca73678001c
> Step 5/9 : RUN apk add --no-cache gcc musl-dev linux-headers
>  ---> Running in df2b94fc5244
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
> WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
> ERROR: unsatisfiable constraints:
>   gcc (missing):
>     required by: world[gcc]
>   linux-headers (missing):
>     required by: world[linux-headers]
>   musl-dev (missing):
>     required by: world[musl-dev]
> ERROR: Service 'web' failed to build: The command '/bin/sh -c apk add --no-cache gcc musl-dev linux-headers' returned a non-zero code: 3
> ```

hi, have you solved this issue? I'm facing the same
