### ISSUE TITLE
URGENT(!)  Please add new features: image_scan_aggregation_enabled  swarm_polling_disabled

### ISSUE THREAD

**Issue by cemckenzie** [docker/docker.github.io#9886]
File: [ee/ucp/admin/configure/ucp-configuration-file.md](https://docs.docker.com/ee/ucp/admin/configure/ucp-configuration-file/)

image_scan_aggregation_enabled  from ENGORC-2746
swarm_polling_disabled from ENGORC-2722

**Comment by traci-morrison** [comment]
Issue resolved via https://github.com/docker/docker.github.io/pull/9887. There may be additional updates in the future.
