### ISSUE TITLE
How to safely stop the images

### ISSUE THREAD

**Issue by restlessdesign** [docker/docker.github.io#989]
File: [compose/rails.md](https://docs.docker.com/compose/rails/)

>  Note: If you stop the example application and attempt to restart it, you might get the following error: web_1 | A server is already running. Check /myapp/tmp/pids/server.pid. One way to resolve this is to delete the file tmp/pids/server.pid, and then re-start the application with docker-compose up.

Unless `Ctrl-C` is not the preferred way to terminate the process, this issue happens 100% of the time (for me\*). Per docker/compose#1393, the workaround is to change the command to the following:

```yaml
command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
```

Would there be any opposition if I were to create a PR which amended this tutorial? If not, would the preference be to **A.)** update the `command` line directly and remove the note or **B.)** amend the note to suggest this alternative?

-----------------

_\* — System/environment specs are as follows (macOS):_

```
Version 1.12.5 (14777)
Channel: Stable
3e6f00c1dc
```

**Comment by mstanleyjones** [comment]
See the response on #3730 about why we are going to leave this as it is. Thanks!

**Comment by cowgill** [comment]
If you're using Alpine Linux (with no bash), you'd want to use this command instead:
```
command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
```

**Comment by benthorner** [comment]
I came across this problem myself. Another approach, if you don't re-use your containers (e.g. if you use the '--rm' flag) is to specify -P /tmp/rails.pid in the startup command. This means you can run the same Rails app in multiple containers, and the pidfile gets automatically deleted with the container.

rails/rails#36486
