### ISSUE TITLE
Feedback for: engine/tutorials/usingdocker.md

### ISSUE THREAD

**Issue by akharsa** [docker/docker.github.io#990]
File: [engine/tutorials/usingdocker.md](https://docs.docker.com/engine/tutorials/usingdocker/)

Running the tutorial on a windows client with a docker machine (Vbox host) the container has the name amazing_bose instead of nostalgic_morse

**Comment by tevjef** [comment]
The names are random.

**Comment by sanscontext** [comment]
Hey @akharsa , as @tevjef pointed out, the container names are randomly generated. I've submitted a PR to add a note to that effect to the tutorial you were reading.

**Comment by akharsa** [comment]
That would be great! thanks
