### ISSUE TITLE
Unclear documentation and comparison of Editions

### ISSUE THREAD

**Issue by XristophD** [docker/docker.github.io#9931]
File: [install/overview.md](https://docs.docker.com/install/overview/)

I have a problem understanding the differences between the editions, due to missing links to further documentation. 

E.g., 
- Image management --> Not clear
- Container app management --> Not clear, App container is a preview feature also available within docker CE

Are both functions about the Universal Control Plane only available in Enterprise?

**Comment by lena-larionova** [comment]
@adrian-plata PTAL
