### ISSUE TITLE
UCP internal variable "page.ucp_version" needs to be bumped to 3.2.4

### ISSUE THREAD

**Issue by cemckenzie** [docker/docker.github.io#9933]
File: [ee/ucp/admin/install/upgrade.md](https://docs.docker.com/ee/ucp/admin/install/upgrade/)

This page references 3.2.3 thru an internal variable:
`This page helps you upgrade Docker Universal Control Plane (UCP) to version {{
page.ucp_version }}.`

The internal variable needs to be bumped to 3.2.4 for the November 2019 release.

**Comment by traci-morrison** [comment]
@cemckenzie @lena-larionova Can you see the updated version? When I view the page, it references 3.2.4.

**Comment by lena-larionova** [comment]
Yep, that shows the right version for me now.

**Comment by traci-morrison** [comment]
OK, I will close this issue for now.
