### ISSUE TITLE
Docker Registry: CloudFront requirements table broken

### ISSUE THREAD

**Issue by r-joyce** [docker/docker.github.io#9935]
File: [registry/configuration.md](https://docs.docker.com/registry/configuration/)

The table for AWS CloudFront is borked. I would have forked and opened a PR but I can't seem to find the configuration file in the registry folder. And selecting the "edit this page" leads to a 404 in GitHub.

**Comment by thaJeztah** [comment]
Thanks for reporting; that page is sourced from the docker/distribution repository; https://github.com/docker/distribution/blob/master/docs/configuration.md

If you're interested in opening a pull request there, that would be welcome; feel free to "ping" me there to help getting it reviewed and merged

**Comment by lena-larionova** [comment]
Fix right here: https://github.com/docker/distribution/pull/3053
