### ISSUE TITLE
Get Started - Step 1 kubernetes swarm concept not introduced

### ISSUE THREAD

**Issue by pholly** [docker/docker.github.io#9939]
File: [get-started/index.md](https://docs.docker.com/get-started/)

Step 1 shows how to enable Kubernetes and Docker Swarm but does not introduce them at all as orchestrators or mention that users will eventually need to pick one or the other if they want to use an orchestrator. May help making them their own step or at least marking them as optional.

**Comment by usha-mandya** [comment]
@pholly Many thanks for your feedback. This issue has been addressed in https://github.com/docker/docker.github.io/pull/9974. You can see the updated docs at https://docs.docker.com/get-started/#orchestration.

I'm closing this issue.
