### ISSUE TITLE
Feedback for: docker-for-windows/index.md

### ISSUE THREAD

**Issue by myuseringithub** [docker/docker.github.io#994]
File: [docker-for-windows/index.md](https://docs.docker.com/docker-for-windows/)

Please add an emphasized statement which says that "Docker native for Windows doesn't support mounts for docker-machine (when Hyper-V is used)". Took me a lot of time to realize that mounting folders from the host filesystem is supported only for  containers not docker-machine VMs. It is not mentioned in the docs ! I understand that Docker for Windows should be used in a specific workflow, but it is not always clear for those switching from Vagrant & VirtualBox to using Docker Machine & Native Docker containers as its intended to be combined with swarm mode. 

Thanks

**Comment by friism** [comment]
@londoncalling if we add this, can you put it in the FAQ? The frontpage already has a long pre-amble before getting to the point of helping users set up Docker for Windows.

**Comment by londoncalling** [comment]
Closing this issue now, as it's been addressed in the docs per the above PR
