### ISSUE TITLE
What does the * mean in the outline?

### ISSUE THREAD

**Issue by bionicles** [docker/docker.github.io#9949]
File: [engine/reference/commandline/builder.md](https://docs.docker.com/engine/reference/commandline/builder/)
Hi, some items are starred in the left-side menu ... it's unclear what this star means. Would it be possible to add some hint to n00bs to tell us what that means?

**Comment by lena-larionova** [comment]
The short answer is: we don't even know what they mean. They're helping no one (you're not the first to ask), so I just took them out. Thanks!
