### ISSUE TITLE
Under "Download Docker for Mac" SHA256  checksum links to bad page(s)

### ISSUE THREAD

**Issue by tadman** [docker/docker.github.io#9950]
File: [docker-for-mac/install.md](https://docs.docker.com/docker-for-mac/install/)

There are links to the checksums for the downloads available in the "Download Docker for Mac" section shown here:

<img width="752" alt="Screen Shot 2019-11-26 at 5 00 34 PM" src="https://user-images.githubusercontent.com/6184/69676292-6ed32600-106e-11ea-8e8f-858eca318efd.png">

The links go to: https://download.docker.com/mac/edge/Docker.dmg.sha256sum

This is a 404 page.

**Comment by aevesdocker** [comment]
Closing issue as it refers to old docs that have since been moved/deprecated/refreshed.
