### ISSUE TITLE
Installing on CentOS 7

### ISSUE THREAD

**Issue by KookosPahkina** [docker/docker.github.io#9968]
I followed this guide to install docker on centos 7 64bit but it keeps giving problems and ive tried reinstalling the OS.. i've tried the rpm and the repository both fail.
https://docs.docker.com/install/linux/docker-ce/centos/#install-from-a-package
it just keeps failing to download the packages, it may start downloading with like 10kbs but eventually it goes to 0bytes per sec

docker-ce-cli-19.03.5-3.el7.x8 FAILED
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-cli-19.03.5-3.el7.x86_64.rpm: [Errno 12] Timeout on https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-cli-19.03.5-3.el7.x86_64.rpm: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 10 seconds')
Trying other mirror.
docker-ce-19.03.5-3.el7.x86_64 FAILED                                          194 B/s | 370 kB 130:04:26 ETA
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-19.03.5-3.el7.x86_64.rpm: [Errno 12] Timeout on https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-19.03.5-3.el7.x86_64.rpm: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 10 seconds')
Trying other mirror.
containerd.io-1.2.10-3.2.el7.x FAILED                                          537 B/s | 359 kB  47:04:35 ETA
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.10-3.2.el7.x86_64.rpm: [Errno 12] Timeout on https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.10-3.2.el7.x86_64.rpm: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 10 seconds')
Trying other mirror.
docker-ce-cli-19.03.5-3.el7.x8 FAILED
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-cli-19.03.5-3.el7.x86_64.rpm: [Errno 12] Timeout on https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-cli-19.03.5-3.el7.x86_64.rpm: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 10 seconds')
Trying other mirror.

Error downloading packages:
  3:docker-ce-19.03.5-3.el7.x86_64: [Errno 256] No more mirrors to try.
  containerd.io-1.2.10-3.2.el7.x86_64: [Errno 256] No more mirrors to try.
  1:docker-ce-cli-19.03.5-3.el7.x86_64: [Errno 256] No more mirrors to try.
it just keeps doing this over and over again

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information
