### ISSUE TITLE
Docker Push Fails

### ISSUE THREAD

**Issue by davesargrad** [docker/docker.github.io#9971]
### Problem description

I am trying to tag and push a docker image. I've done this successfully with 2 other private (insecure) docker registries.

### Problem location

docker push to private registry

I created the registry like this:
 `docker run -d -p 5007:5000 --restart=always --name registry registry:2`

The command I am trying to run
![image](https://user-images.githubusercontent.com/48793689/70083086-c37c2100-15d9-11ea-921e-03e2040d9bc9.png)

**The error I see in /var/log/messages**

![image](https://user-images.githubusercontent.com/48793689/70083047-af382400-15d9-11ea-815d-bfc473d23d04.png)

### This worked on another docker registry, on a different server
I was able to run this command successfully on a separate docker registry I have (using all the same kind of configuration - including the insecure-regstiry), created in identically the same way

![image](https://user-images.githubusercontent.com/48793689/70083441-5d43ce00-15da-11ea-95ce-9eabf8db6284.png)

### Project version(s) affected

![image](https://user-images.githubusercontent.com/48793689/70082853-4781d900-15d9-11ea-86b7-3f635288bfce.png)

### Other configuration
I am using an insecure registry
![image](https://user-images.githubusercontent.com/48793689/70082981-86179380-15d9-11ea-93fc-b0ffb558b445.png)

### 

Docker image list 
![image](https://user-images.githubusercontent.com/48793689/70083238-050ccc00-15da-11ea-95df-f40ed4ef6925.png)

### I also configure a corporate proxy
![image](https://user-images.githubusercontent.com/48793689/70083663-d9d6ac80-15da-11ea-856b-0abe02cc02be.png)

The IP of this proxy is 10.93.64.3 (which is the IP we see in the error in /var/log/messages.  Yet I believe that I have NO_PROXY setup correctly (10.93.97.123 is 4th in following list):
![image](https://user-images.githubusercontent.com/48793689/70084178-d7c11d80-15db-11ea-8c30-b755221b1ff4.png)

### Some other views into the docker state
![image](https://user-images.githubusercontent.com/48793689/70087647-b3b50a80-15e2-11ea-9962-19525ee57154.png)

![image](https://user-images.githubusercontent.com/48793689/70087931-35a53380-15e3-11ea-9504-5e0eac0c34bd.png)

**Comment by davesargrad** [comment]
I've seen so many issues that relate to this kind of thing guys.   I think it relates to proxy, yet I'm not sure. 

I'm not sure I've seen any clear response that makes it clear how to diagnose.

At the very least it strikes me that there should be a better way to diagnose this problem. Perhaps there is a diagnostic I can turn on in the docker daemon.. 

Any suggestion would be appreciated.

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/70144265-89f3f600-166b-11ea-83be-83461017cac6.png)

**Comment by davesargrad** [comment]
So... I temporarily commented out the proxy setting inside (then I restarted the docker daemon)

/etc/systemd/system/docker.service.d/http-proxy.conf

![image](https://user-images.githubusercontent.com/48793689/70144933-f7eced00-166c-11ea-86ba-5b81c8afd9ca.png)


![image](https://user-images.githubusercontent.com/48793689/70144950-03401880-166d-11ea-83cc-2f909bf37f6a.png)


And I was able to push successfully.

![image](https://user-images.githubusercontent.com/48793689/70144890-e1469600-166c-11ea-8029-fbbba6cfd097.png)


It would seem that NO_PROXY is not working. 

```
[root@benin ~]# echo $NO_PROXY
10.93.98.51,10.93.98.16,10.93.103.236,10.93.97.123,10.93.97.202,10.244.0.1,10.244.0.2,10.244.0.3,10.244.0.4,10.244.0.5,10.244.0.6,10.244.0.7,10.244.0.8,10.244.0.9,10.244.0.10,10.244.0.11,10.244.0.12,10.244.0.13,10.244.0.14,10.244.0.15,10.244.0.16,10.244.0.17,10.244.0.18,10.244.0.19,10.244.0.20,10.244.0.21,10.244.0.22,10.244.0.23,10.244.0.24,10.244.0.25,10.244.0.26,10.244.0.27,10.244.0.28,10.244.0.29,10.244.0.30,10.244.0.31,10.244.0.32,10.244.0.33,10.244.0.34,10.244.0.35,10.244.0.36,10.244.0.37,10.244.0.38,10.244.0.39,10.244.0.40,10.244.0.41,10.244.0.42,10.244.0.43,10.244.0.44,10.244.0.45,10.244.0.46,10.244.0.47,10.244.0.48,10.244.0.49,10.244.0.50,10.244.0.51,10.244.0.52,10.244.0.53,10.244.0.54,10.244.0.55,10.244.0.56,10.244.0.57,10.244.0.58,10.244.0.59,10.244.0.60,10.244.0.61,10.244.0.62,10.244.0.63,10.244.0.64,10.244.0.65,10.244.0.66,10.244.0.67,10.244.0.68,10.244.0.69,10.244.0.70,10.244.0.71,10.244.0.72,10.244.0.73,10.244.0.74,10.244.0.75,10.244.0.76,10.244.0.77,10.244.0.78,10.244.0.79,10.244.0.80,10.244.0.81,10.244.0.82,10.244.0.83,10.244.0.84,10.244.0.85,10.244.0.86,10.244.0.87,10.244.0.88,10.244.0.89,10.244.0.90,10.244.0.91,10.244.0.92,10.244.0.93,10.244.0.94,10.244.0.95,10.244.0.96,10.244.0.97,10.244.0.98,10.244.0.99,10.244.0.100,10.244.0.101,10.244.0.102,10.244.0.103,10.244.0.104,10.244.0.105,10.244.0.106,10.244.0.107,10.244.0.108,10.244.0.109,10.244.0.110,10.244.0.111,10.244.0.112,10.244.0.113,10.244.0.114,10.244.0.115,10.244.0.116,10.244.0.117,10.244.0.118,10.244.0.119,10.244.0.120,10.244.0.121,10.244.0.122,10.244.0.123,10.244.0.124,10.244.0.125,10.244.0.126,10.244.0.127,10.244.0.128,10.244.0.129,10.244.0.130,10.244.0.131,10.244.0.132,10.244.0.133,10.244.0.134,10.244.0.135,10.244.0.136,10.244.0.137,10.244.0.138,10.244.0.139,10.244.0.140,10.244.0.141,10.244.0.142,10.244.0.143,10.244.0.144,10.244.0.145,10.244.0.146,10.244.0.147,10.244.0.148,10.244.0.149,10.244.0.150,10.244.0.151,10.244.0.152,10.244.0.153,10.244.0.154,10.244.0.155,10.244.0.156,10.244.0.157,10.244.0.158,10.244.0.159,10.244.0.160,10.244.0.161,10.244.0.162,10.244.0.163,10.244.0.164,10.244.0.165,10.244.0.166,10.244.0.167,10.244.0.168,10.244.0.169,10.244.0.170,10.244.0.171,10.244.0.172,10.244.0.173,10.244.0.174,10.244.0.175,10.244.0.176,10.244.0.177,10.244.0.178,10.244.0.179,10.244.0.180,10.244.0.181,10.244.0.182,10.244.0.183,10.244.0.184,10.244.0.185,10.244.0.186,10.244.0.187,10.244.0.188,10.244.0.189,10.244.0.190,10.244.0.191,10.244.0.192,10.244.0.193,10.244.0.194,10.244.0.195,10.244.0.196,10.244.0.197,10.244.0.198,10.244.0.199,10.244.0.200,10.244.0.201,10.244.0.202,10.244.0.203,10.244.0.204,10.244.0.205,10.244.0.206,10.244.0.207,10.244.0.208,10.244.0.209,10.244.0.210,10.244.0.211,10.244.0.212,10.244.0.213,10.244.0.214,10.244.0.215,10.244.0.216,10.244.0.217,10.244.0.218,10.244.0.219,10.244.0.220,10.244.0.221,10.244.0.222,10.244.0.223,10.244.0.224,10.244.0.225,10.244.0.226,10.244.0.227,10.244.0.228,10.244.0.229,10.244.0.230,10.244.0.231,10.244.0.232,10.244.0.233,10.244.0.234,10.244.0.235,10.244.0.236,10.244.0.237,10.244.0.238,10.244.0.239,10.244.0.240,10.244.0.241,10.244.0.242,10.244.0.243,10.244.0.244,10.244.0.245,10.244.0.246,10.244.0.247,10.244.0.248,10.244.0.249,10.244.0.250,10.244.0.251,10.244.0.252,10.244.0.253,10.244.0.254,10.244.0.255,127.0.0.1
```

I'm closer, since I've verified that this is related to proxy. However I've found many issues on docker github that talk about setting either /etc/systemd/system/docker.service.d/http-proxy.conf .. or ~/.docker/config.json. In fact the docker documentation also talks about these. But this has not worked for me.

https://docs.docker.com/network/proxy/

**Comment by davesargrad** [comment]
So I've put the HTTP_PROXY environment back the way I think it needs to be..  and I have problems connecting to the private docker registry as i expected (this is a view from a container created by kubrnetes (using kamel)

![image](https://user-images.githubusercontent.com/48793689/70148038-6af96200-1673-11ea-8101-aa431754b179.png)

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood, please reopen it with more information

**Comment by davesargrad** [comment]
Hi @traci-morrison 

I didnt think I was filing a documentation issue. Is this not the right issue list for docker problems?
