### ISSUE TITLE
Please explain -v option in similar matter as run -rm 

### ISSUE THREAD

**Issue by a-ness** [docker/docker.github.io#9973]
File: [engine/reference/commandline/rm.md](https://docs.docker.com/engine/reference/commandline/rm/)

The note under https://docs.docker.com/engine/reference/run/#clean-up---rm explains in a better way that only anonymous volumes will be removed with -v option. 

Please consider using this explanation instead of what is currently written about -v

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. This particular content is maintained in an upstream repo. If the issue is still applicable, please help create an issue or PR in the repo at https://github.com/docker/cli/tree/master/docs/reference/commandline
