### ISSUE TITLE
Typo in second instance of --hyperv-cpu-count

### ISSUE THREAD

**Issue by farscapian** [docker/docker.github.io#998]
File: [machine/drivers/hyper-v.md](https://docs.docker.com/machine/drivers/hyper-v/)

In the "Environment variables and default values" section, the --hyperv-cpu-count parameter is listed twice.  On the second occurrence, the Environment varable states "HYPERV_VLAN_ID".  I suspect that the second --hyperv-cpu-count needs to change.
Derek

**Comment by scjane** [comment]
#dibs

**Comment by scjane** [comment]
There are no duplicate "--hyperv-cpu-count" now, and the original second "--hyperv-cpu-count" is "--hyperv-vlan-id". This issue can be closed.

![123](https://cloud.githubusercontent.com/assets/25146885/25111175/edcde5fe-241b-11e7-9d51-d7191dc775da.jpg)
