### ISSUE TITLE
cannot find the docs of ver 1.5

### ISSUE THREAD

**Issue by ghost** [docker/docker.github.io#9988]
### Problem description

The link of Docs for v1.5 is dead.

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/v17.03/v1.5/

### Project version(s) affected
for ver 1.5, it seems more controllable

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. As this issue is old, some context may have changed. You can view archived documentation following the procedure here, https://docs.docker.com/docsarchive/
If found a dead link in the current documentation, please let us know.
