### ISSUE TITLE
Need to provide specifics around org naming conventions

### ISSUE THREAD

**Issue by kavikat** [docker/docker.github.io#9995]
File: [ee/dtr/admin/manage-users/create-and-manage-orgs.md](https://docs.docker.com/ee/dtr/admin/manage-users/create-and-manage-orgs/)

Information regarding org naming should be presented, there is a limitation in UCP where accounts regardless of type (user, team, org) cannot have duplicates.

**Comment by usha-mandya** [comment]
Thanks for your feedback. Docker Enterprise docs are now part of Mirantis. You can take a look at the Docker Enterprise documentation at https://docs.mirantis.com/docker-enterprise/.

Let me close this issue here for that reason. Feel free to continue the conversation after I close.
