### ISSUE TITLE
Old links at https://docs.docker.com/compose/environment-variables/

### ISSUE THREAD

**Issue by oj-lappi** [docker/docker.github.io#9996]
### Problem description

The url [https://docs.docker.com/compose/compose-file.md](https://docs.docker.com/compose/compose-file.md) no longer points to anything.
This url is linked to from [https://docs.docker.com/compose/environment-variables/](https://docs.docker.com/compose/environment-variables/)

The link is displayed as "Variable substitution"

I assume it should be pointing at [https://docs.docker.com/compose/compose-file/](https://docs.docker.com/compose/compose-file/) instead

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/compose/environment-variables/

### Project version(s) affected

No version, online documentation

### Suggestions for a fix

Point the link at[https://docs.docker.com/compose/compose-file/#variable-substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) instead.

**Comment by Wallenstein61** [comment]
File: [compose/index.md](https://docs.docker.com/compose/)

Just came across the same problem: I cannot find any detailed information on "variable subsitution". The suggestion for a fix above 

> Point the link at https://docs.docker.com/compose/compose-file/#variable-substitution instead.

 seems not to work. There is no anchor `variable-substitution` on this page.

**Comment by oj-lappi** [comment]
This issue is over a year old, I believe the documentation has changed structure since then.

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/12060 to fix
